### ISSUE TITLE
Video player enhancements

### ISSUE THREAD

**Issue by CodeCubeNeo** [google/ExoPlayer#10002]
I would like to recommend some enhancements for this video player, that some other video players (like vlc) have. here are the enhancements in (my!) order of importance (first is most important):
- select/deselect/none audio tracks
- audio (and brightness) controls with swiping gestures (right half of the screen, up and down for lower/higher volume and the left half for lower/higher brightness)
- subtitles (select file from the encrypted volume)
If those were added it would be really awesome!!!

**Comment by christosts** [comment]
Just to confirm:

> * select/deselect/none audio tracks

This is supported. The [demo app](https://exoplayer.dev/demo-application.html) for example demonstrates how to select specific audio tracks or none. There is documentation on [Track selection](https://exoplayer.dev/track-selection.html) too. Is there something that is not covered for your app needs?

**Comment by tonihei** [comment]
As pointed out above, audio selection, volume and subtitles are already supported technically. It sounds like the original request was more about supporting additional UI elements in `PlayerView`. We do not intend to cater to all UI use cases and just want to provide a useful default. In that sense, we are unlikely to add additional custom controls features for now. There is also an effort to provide Compose UI elements, which may offer more customization options in the future. I'll close the issue since there was no new activity for almost 2 years.
