### ISSUE TITLE
How can I get current live offset prior to version 2.12.0?

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#10012]
I have been using version 2.11.8
And I saw that in version 2.12.0 `getCurrentLiveOffset()` was added to `BasePlayer`
Is there something similar or how can I get the value of current live off set versions prior to 2.12.0 ?

**Comment by marcbaechinger** [comment]
If there is the option to upgrade to a recent ExoPlayer version, this would a great way of getting `getCurrentLiveOffset()`.

If that's not possible then the last resort would be to look into the [implementation in BasePlayer](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/BasePlayer.java#L352). I believe this is everything based on a public API sou you can adapt that code for your purpose.

When you make a method to which you pass the player you can do just the same replacing `this` with the player. Use `player.getCurrentWindowIndex()` instead of `CurrentMediaItemIndex` that probably doesn't exists since too long.

**Comment by wishygupta** [comment]
I did made some changes as per your suggestion however I am unsure what should be the alternative for `window.getCurrentUnixTimeMs()`

This is what I have added for version 2.11.8

`       fun BasePlayer.getLiveOffset(): Long {

        val timeline: Timeline = currentTimeline
        if (timeline.isEmpty) {
            return C.TIME_UNSET
        }
        val window = Timeline.Window()
        val windowStartTimeMs =
            timeline.getWindow(currentWindowIndex, window).windowStartTimeMs
        return if (windowStartTimeMs == C.TIME_UNSET) {
            C.TIME_UNSET
        } else window.getCurrentUnixTimeMs() - window.windowStartTimeMs - getCurrentPosition()
    }`

**Comment by marcbaechinger** [comment]
If `getCurrentUnixTimeMs` has been added with 2.12 then this is not available in 2.11.8. You can't easily replace this because the unix time that this gives you is synchronized with the media origin server which is something you can't easily add. So I think the only suggestion here is to migrate to a recent version I'm afraid.
