### ISSUE TITLE
Custom controller layout not recognizing play and pause buttons.

### ISSUE THREAD

**Issue by mdurokov** [google/ExoPlayer#10023]
Hi, I think there is a bug with the custom controller layout.

I tried to add a custom controller layout to StyledPlayerView on the demo app and it is loaded, but when I override the exo_play and exo_pause buttons they don't work. 
Weird thing is that exo_ffwd and exo_rew work as expected (I didn't try others).

Player Activity contains StyledPlayerView

```
    <com.google.android.exoplayer2.ui.StyledPlayerView
          android:id="@+id/player_view"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          app:controller_layout_id="@layout/exo_player_layout"/>
```

And this is exo_player_layout

```
     <LinearLayout
            android:id="@+id/play_controls"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center">

            <ImageButton
                android:id="@id/exo_play"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:srcCompat="@drawable/ic_exo_play" />

            <ImageButton
                android:id="@id/exo_pause"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:srcCompat="@drawable/ic_exo_pause"/>

        </LinearLayout>

```

Does anyone have any ideas?

**Comment by marcbaechinger** [comment]
I think the `StyledPlayerView` is using `@id/exo_play_pause` rather than `@id/exo_play` and `@id/exo_pause`.

If you want to provide your custom layout you should use a single button with `@+id/exo_play_pause`. The styled control view does not hide/show one or the other of these buttons, but instead change the drawable of the icon. If you want to change these icons you can do so by adding a `drawables.xml` in the `values` folder of the app module to override the drawables used by default:

```
<resources>
  <drawable name="exo_styled_controls_play">@drawable/custom_controls_play</drawable>
  <drawable name="exo_styled_controls_pause">@drawable/custom_controls_pause</drawable>
</resources>
``` 

Please see #10008 also which is about a similar issue.

There were quite some changes in the ui components, so if the above does not help, please let us know the exact ExoPlayer version you are depending to with your app.

**Comment by mdurokov** [comment]
That does the trick, thank you! 
I didn't see it documented anywhere.
As a matter of fact, I did use PlayerView before and it worked with exo_play and exo_pause.

**Comment by draganstojanov** [comment]
It works. But, i have two sets of icons, one for vertical oriented video and other for horizontal oriented. Is there any way to programmatically override drawables?
