### ISSUE TITLE
How to detect Widevine security level supported by the device

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#10024]
**Question**

We wanted to check the drm capabilities of the device and what is the Drm security level it supports

We tried to read `android.media.MediaDrm.getMaxSecurityLevel()` but this always returns value 6 in both L1 and L3 use-cases.

Pls let us know what is the correct way to get the security level of the device.

We checked MediaDrm instance methods but could not find any.

We are using MediaItem.Builder interface to pass drm license url to player

**Comment by krackjack234** [comment]
Got the details

_mediaDrm.getPropertyString("securityLevel")_ returns L1/L3 as per the device capability.

We can close this ticket if this is the right way to get this data.

**Comment by icbaker** [comment]
[ah, my reply raced with your update - I'll post it anyway for completeness]

The value returned from `MediaDrm.getMaxSecurityLevel()` is only intended to be passed to `MediaDrm.openSession(int)` - not directly consumed/interpreted by an application. This is explained in [its javadoc](https://developer.android.com/reference/android/media/MediaDrm#getMaxSecurityLevel()):
> Returns a value that may be passed as a parameter to openSession(int) requesting that the session be opened at the maximum security level of the device.

As you can see from the [source of `MediaDrm`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/media/java/android/media/MediaDrm.java;l=2090;drc=054d15cd3d469338d0f8f9a324bb6f4e298a01bb), the value `6` is a sentinel value meaning 'the max level supported by the device':
```java
/**
 * Indicates that the maximum security level supported by the device should
 * be used when opening a session. This is the default security level
 * selected when a session is opened.
 * @hide
 */
public static final int SECURITY_LEVEL_MAX = 6;
```

And `getMaxSecurityLevel()` always returns this:
```
public static final int getMaxSecurityLevel() {
    return SECURITY_LEVEL_MAX;
}
```

The Widevine security level of a device (e.g. L1 or L3) is available from `mediaDrm.getPropertyString("securityLevel")`. `"securityLevel"` is a Widevine-specific key, which is why this isn't documented in the `MediaDrm` javadoc (because that class can be used with other DRM implementations). Instead this key is documented in the "Widevine CDM Vendor Extensions" documentation which is available to Widevine partners - if you need access to these docs please reach out directly to Widevine: https://www.widevine.com/contact.

**Comment by krackjack234** [comment]
Thanks @icbaker for the references

**Comment by krackjack234** [comment]
@icbaker  may I ask a follow up question please?

We are using `MediaItem.DrmConfiguration` and adding it to `MediaItem.Builder` to create the media item.
In this context how can we use MediaDrm and set the securityLevel to L3 if needed?

**Comment by icbaker** [comment]
Can you provide more information about exactly what this means?
> set the securityLevel to L3 if needed

A complete (but concise) code snippet showing what you're trying to achieve and what currently doesn't work as expected would be helpful.

**Comment by krackjack234** [comment]
hi @icbaker  we have streams which are having both L1 and L3 licenses, L1 being used for 720p and 1080p resolutions.
We wanted to force the drm security level to L3 and play the same stream so that it plays all tracks below 720p and does not switch to L1 ones

We referred below link to get a reference
 https://github.com/google/ExoPlayer/issues/7790

However, we are using below code snippet in our current code where we add a drm configuration to a media item and then add the mediaItems to the player.

```
MediaItem.Builder builder =
                    new MediaItem.Builder()
                            .setUri(uris[i])
                            .setMimeType(adaptiveMimeType);

builder
           .setDrmUuid(drmConfig.getUuid())
            .setDrmLicenseUri(drmConfig.getLicenseUri())
            .setDrmMultiSession(drmConfig.isMultiSession())
            .setDrmLicenseRequestHeaders(drmConfig.getRequestHeaders());

 mediaItems.add(builder.build());
 player.setMediaItems(mediaItems, 0);
```
We are unable to figure out how to use **MediaDrm** in this flow and set the required security level.

**Comment by icbaker** [comment]
> We wanted to force the drm security level to L3 [...]

To use the code snippet from https://github.com/google/ExoPlayer/issues/7790#issuecomment-678473131 with `MediaItem` you will need to provide a custom `MediaSource.Factory` with a custom `DrmSessionManagerProvider` when constructing your player (as explained here: https://exoplayer.dev/drm.html#using-a-custom-drmsessionmanager). For example:

```java
DefaultDrmSessionManager drmSessionManager = // Code from https://github.com/google/ExoPlayer/issues/7790#issuecomment-678473131
DefaultMediaSourceFactory mediaSourceFactory =
    new DefaultMediaSourceFactory(/* context= */ this)
        .setDrmSessionManagerProvider(mediaItem -> drmSessionManager);
ExoPlayer player = new ExoPlayer.Builder(/* context= */ this, mediaSourceFactory).build();
```

-----

> [...] play the same stream so that it plays all tracks below 720p and does not switch to L1 ones

Currently ExoPlayer will try and switch to a track even if it doesn't have the DRM keys required to play it. Changing this is tracked by #4825. For now you're best off customising your track selection logic to exclude the streams you don't want to play. More info here: https://exoplayer.dev/track-selection.html
