### ISSUE TITLE
how to create exoplayer.jar with Exoplayer library only

### ISSUE THREAD

**Issue by JanuszChmiel** [google/ExoPlayer#10033]
Dear advanced engineers from The powerful Google company,
I love Pascal programming language. So I Am using PPCJVM free pascal compiler which is capable to produce Java classes. As A result I need to have Exoplayer.jar prepared, which contain all classes related to Exoplayer library. Special complex command line is capable to generate Pascal header files for Exoplayer by using compiled .jar library.
Could you tell Me The secret command which is capable to compile Exoplayer to The standalone .jar library? Id o not want to have .jar library with included examples. I need to have only exoplayer.jar with Exoplayer library compiled with class files inside .jar file.
Any good advice is very very welcomed.

Thank you very much for your answer.
With The deepest appreciation and with The kindness regards.
Janusz Chmiel

**Comment by ojw28** [comment]
If you only need the `jar` file for something in your tool-chain, for example a command line tool that generates Pascal header files, then you could try downloading the `aar` files from https://maven.google.com/web/index.html?q=exoplayer#com.google.android.exoplayer and then converting them to `jar` files that contain just the classes. There's some guidance on how to do this on StackOverflow [here](https://stackoverflow.com/questions/21417419/how-to-convert-aar-to-jar). You would likely have to do this for all of the individual ExoPlayer modules that you're trying to use. It should be noted that this approach will not include the classes in dependencies that ExoPlayer has, which you might also need in order to use some parts of ExoPlayer's API surface.

Closing, since this is far outside the scope of what we're able to support. I suspect that the benefit of being able to use Pascal is  not worth the additional tool-chain complexities that you're creating for yourself. But have fun trying this out, and good luck :)!
