### ISSUE TITLE
AudioTrackScore missing in r2.17.0

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#10048]
Hello,

Updating from r2.16.1 to r2.17.0 , class `AudioTrackScore` has disappeared. It was not deprecated in previous versions.
I was using it to compare tracks. Is there a substitute or are we expected to do it custom now?
Please advise.
Thanks.

**Comment by ojw28** [comment]
It looks like the closest equivalent is `DefaultTrackSelector.AudioTrackInfo`, but it's marked as private. Would you be able to do what you did previously if it were protected instead? I'd suggest you try depending on ExoPlayer as source, changing it to protected and trying it out, because it's probably quite difficult to reason about just by looking at the source code.

**Comment by kvillnv** [comment]
We haven't done the update yet. We will explore alternate solutions and consider your suggestion. 
No need to re-open the ticket.
Thanks.

**Comment by ojw28** [comment]
I'll leave it closed for now, because there's nothing actionable for us at this moment. Once you have some feedback you can respond here, or file a new issue is long enough elapses for this issue to be locked. Thanks!

**Comment by ojw28** [comment]
Heh, apologies, I initially misread your comment as a request to re-open the ticket :). It sounds like we're aligned; please ignore my post above!
