### ISSUE TITLE
defaultAudioLink.flush causes OutOfMemory

### ISSUE THREAD

**Issue by halizton** [google/ExoPlayer#10057]
This is a follow up of the issue [8728](https://github.com/google/ExoPlayer/issues/8728)

We encounter the same issue in our application. The context is that we are a feed application where we may play several videos at the same time in the feed. We can also play full screen video from time to time. We try to keep reusing the players that have already been created.

There are several circumstances where we will release a player:
- To treat the system memory nicely, we also release all players if the application goes to the background.
- We will release a player if the cache pool already has enough players, for example, 4. We do this check after the video is scrolled off the screen.

Since we have quite a lot videos in our feed, we try to keep using the players and at the same time, we would release players periodically. There are some pages with lots of videos and we could suddenly release lots of players. I think the current implementation of the defaultAudioLink.flush() would lead to too many threads created in some cases in our application.

This is an example of the crash:
![image](https://user-images.githubusercontent.com/12901839/157966844-da8c1774-c46e-43d5-a136-b1ea978e50d9.png)

So it would be great to offer something like this 
![image](https://user-images.githubusercontent.com/12901839/157966522-807ce1ec-b831-41fa-ae74-9894492e3cef.png)

- ExoPlayer version number: 2.14.2
- Android version: OS 10 (this seems only happen on OS 10)
- Android device: many

**Comment by tonihei** [comment]
Sorry for the delay in addressing this. 

What do you think about using a shared single threaded `ExecutorThread` to release all the audio tracks? This was already suggested in #8728 as a potential solution. If we think this makes sense, we could even handle this inside `DefaultAudioSink` via a shared static `ExecutorThread` that can be kept alive as long as there are active audio sinks. 

In #8728, @andrewlewis is concerned that 
> the main thread might be blocked for too long if doing that (the last player will wait until all the other AudioTrack.release calls have returned before it can do its call).

This particular concern only applies when we try to release a player with an `AudioTrack` that is currently being initialized and waiting for a previous `AudioTrack` in the same player to be released. Regular release calls are not blocked because `AudioTrack.flush()` returns without waiting. We could try to avoid this edge case by not blocking the playback thread when initializing a new `AudioTrack` and instead retry the initialiation later (=return `false` from `AudioTrack.handleBuffer`)

**Comment by halizton** [comment]
Yeah, a single threaded `ExecutorThread` approach sounds good! Thanks for addressing.

**Comment by tonihei** [comment]
This should be fixed now by automatically using a single thread executor for releases that happen at the same time.

**Comment by halizton** [comment]
> This should be fixed now by automatically using a single thread executor for releases that happen at the same time.

Which release contains this fix, @tonihei ?

**Comment by andrewlewis** [comment]
[Edited to correct my previous reply as only part of this made it into 2.18.1, thanks to @icbaker for the heads up]

It's unreleased and will most likely go into 2.19.0 (as not all the referenced commits are marked for inclusion in a minor release).
