### ISSUE TITLE
How to read SEI message from MP4 file or HLS stream

### ISSUE THREAD

**Issue by koreex** [google/ExoPlayer#10068]
I'm playing a local MP4 file in ExoPlayer. While playing it, I need to read SEI message from the file so I can get custom metadata that I put when creating the file. No need to parse SEI message. Just need to get byte data. I can parse that byte data in the application. Let me know the method

**Comment by andrewlewis** [comment]
I think the SEI data will be "combined" with the video data in the samples read by the video renderer for an MP4. If you're happy to parse the sample yourself then the quickest way to get at this is probably to subclass `MediaCodecVideoRenderer` and override `onQueueInputBuffer` (use a custom renderers factory to have the player use your renderer rather than the normal `MediaCodecVideoRenderer`).

The buffer passed to that method wraps a `MediaCodec` input buffer so you will need to parse the data in it and pick out just the SEI NAL unit. The utilities in `NalUnitUtil` may be useful for identifying the NAL unit header (and I think you may need to unescape the stream as well though I'm not 100% sure about this). This is reading the data on the input side of the decoder so the buffers will appear in "decode order" (not "presentation order" if that's different for the video stream you are using).

If you're looking for something more automatic than this then, from what I can tell, I'm afraid we don't support it yet and realistically we aren't likely to have time to add support for this use case soon.

**Comment by koreex** [comment]
Thanks for your reply. I can parse NAL unit myself. What I need is to get SEI NAL unit in the hosting application from ExoPlayer. How can we use custom `RenderersFactory` in `ExoPlayer`?

**Comment by andrewlewis** [comment]
> How can we use custom RenderersFactory in ExoPlayer?

It's covered under https://exoplayer.dev/shrinking.html#specify-which-renderers-your-app-needs.

**Comment by koreex** [comment]
Thank you. It works
