### ISSUE TITLE
Live streaming issue when using ExoPlayer version 2.17.0 and above 

### ISSUE THREAD

**Issue by tpuserhp** [google/ExoPlayer#10065]
I can stream a m3u8 link from my app when  using ExoPlayer 2.16.1 libraries,. But when using ExoPlayer 2.17.0 or 2.17.1 libraries, I don't see the streaming  from my app. I then use the  demo app of 2.12.3 version and can  see the streaming. for that link.  But when using the demo app of 2.17.0, I don't see the streaming.  I would appreciate if the support  could review and recommend actions that I can take. I will submit the link later. Thanks .

**Comment by tpuserhp** [comment]
I have  emailed the link to support  for testing. Thanks.

**Comment by icbaker** [comment]
Thanks for the link. I tried it with the 2.17.1 [demo app](https://exoplayer.dev/demo-application.html) and observed that playback never started (player stayed in the buffering state forever). I observed the same behaviour on 2.17.0.

On the 2.16.1 demo app the playback starts successfully. 

So something seems to have changed between 2.16.1 and 2.17.0. Over to @christosts to take a closer look at this HLS stream.

**Comment by christosts** [comment]
I can verify the problem. I'll try to get a fix in next week.

Note to self: The loading thread is blocked on TimestampAdjuster.sharedInitializeOrWait() because the first HlsMediaChunk loaded is not a master timestamp source. In 2.16.1 on the other hand, the first chunk loaded is a master timestamp source. I need to check if a load re-ordering has happened between 2.16.1 and 2.17.1.

**Comment by tpuserhp** [comment]
Thanks for the issue investigation and the update!!!

**Comment by christosts** [comment]
The symptom seems to be related with **HLS chunkless preparation** which is enabled by default in the 2.17 release. To quickly fix the problem in 2.17, you may instantiate the player with an HLS media source that has chunkless preparation disabled:

```java
HlsMediaSource.Factory factory = 
  new HlsMediaSource.Factory(dataSourceFactory).setAllowChunklessPreparation(false);
ExoPlayer player =  
  new ExoPlayer.Builder(context).setMediaSourceFactory(factory).build();
```

I still need to check if there is a bug in chunkless preparation or this playlist is incompatible with the feature. I'll update this issue accordingly. 

Information on chunkless preparation on this [blog post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6).

**Comment by tpuserhp** [comment]
Thank you support for providing the quick fix which works very  well .  My app is now running release 2.17 with no problem from that playlist.  Much appreciated!!

**Comment by christosts** [comment]
Root-causing the issue: the player fails to load/prepare the playlist in chunkless mode because the playlist contains the CODECS attribute but it is missing the audio codec. The player assumes the video variants are prepared but the audio one is not, and the player gets stuck.

If you have access to the encoding/packaging process, I'd suggest you update how the playlist is created and add the audio codec to CODECS. Then try with chunkless preparation, you might see some improvements in start-up time. 

On the ExoPlayer side, we submitted a fix to detect this case and fall back to traditional preparation. The fix will be available on the next ExoPlayer release.

**Comment by tpuserhp** [comment]
Thanks for your help and support. I will try out the fix once the next
release is available.
