### ISSUE TITLE
How to get played time from an HLS Radio Stream?

### ISSUE THREAD

**Issue by vyagrah** [google/ExoPlayer#10081]
I am using `exo_position` to show playback time to the user. But whenever I play HLS stream it shows weird values, even negative one. Also `exo_duration` which just shows 00:00 in case of normal stream (which is ok because I am using live radio stream), shows random time intervals in case of HLS stream.

<LinearLayout android:id="@id/exo_time"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:paddingStart="@dimen/exo_styled_bottom_bar_time_padding"
    android:paddingEnd="@dimen/exo_styled_bottom_bar_time_padding"
    android:paddingLeft="@dimen/exo_styled_bottom_bar_time_padding"
    android:paddingRight="@dimen/exo_styled_bottom_bar_time_padding"
    android:layout_gravity="center_vertical|start"
    android:layoutDirection="ltr">

    <TextView android:id="@id/exo_position"
        android:textColor="?attr/colorPrimary"
        style="@style/ExoStyledControls.TimeText.Position"/>

    <TextView
        android:textColor="?attr/colorPrimary"
        style="@style/ExoStyledControls.TimeText.Separator"/>

    <TextView android:id="@id/exo_duration"
        android:textColor="?attr/colorPrimary"
        style="@style/ExoStyledControls.TimeText.Duration"/>

I tried disabling chunkless prepartion but it not helped:

`HlsMediaSource hlsMediaSource =
new HlsMediaSource.Factory(dataSourceFactory)
    .setAllowChunklessPreparation(false)
    .createMediaSource(MediaItem.fromUri(hlsUri));`

Is there any way to show user the time he played stream ? Actually I don't want to put custom code because `exo_position` showing exactly what I want in case of normal streams.

**Comment by icbaker** [comment]
It's probably easier to discuss the behaviour of various `Player.getXXX` methods (in order to separate this issue from ExoPlayer's UI components, which I don't think are directly relevant to your question).

This section of the dev guide explains how the various position/duration numbers are reported for adaptive (e.g. HLS) live streams: https://exoplayer.dev/live-streaming.html#detecting-and-monitoring-live-playbacks

This shows that the position that the user started playback is not known/recorded by the player, so there's no simple `Player` method that will report the time since this point.

I suspect you will need to implement this manually in your app, by recording the wall-clock time (since Unix epoch) that the user starts playback and comparing this to the values of `Window.getCurrentUnixTImeMs()` and `Player.getCurrentLiveOffset()`.

**Comment by vyagrah** [comment]
@icbaker I am new with exoplayer.

In my app **I am not using seeking feature** provided by exoplayer.

I noticed when I play normal stream `onTimelineChanged `called only one time, but with HLS streams it is called again and agian. I also noticed that `exo_position `gives same value as `player.getDuration()`.

I think if I can stop seeking feature on HLS stream `onTimelineChanged ` will not be called again and again.

Is there any way to stop seeking for HLS streams?

**Comment by vyagrah** [comment]
I looked at this issue:
https://github.com/google/ExoPlayer/issues/2118#issuecomment-263536694
It says that to add support of seeking in DASH and SmoothStreaming, getCurrentPosition returns wrong values for HLS streams. :(

His code is working but only with those HLS streams which start playing from 00:00.
like this:
https://lmil.pc.cdn.bitgravity.com/lmil/live/aajtak_150k/chunklist_ao.m3u8

But check this HLS stream:
https://streaming.fabrik.fm/izwi/echocast/audio/index.m3u8

here whenever you start playing, playing position always starts with 3:36.

Here that code also not works :(

I can't post comment on that issue because they stopped taking comment.
