### ISSUE TITLE
Howto read from codec output buffers

### ISSUE THREAD

**Issue by gtg287y** [google/ExoPlayer#1009]
I am attempting to play the HLS sample filie BipPop.  I have added code to MediaCodecVideoTrackRenderer. 

The following code can be called in processOutputBuffer or in renderOutputBufferV21 but gets the same buffer freed error regardless (and the video successfully plays despite the buffer supposedly being freed).

    private Boolean customHack(MediaCodec codec, int bufferIndex) {
    ByteBuffer buffer = codec.getOutputBuffer(bufferIndex);
    byte[] data =  new byte[buffer.remaining()];
        try {
          buffer.get(data);
        }catch(Exception e){
          Log.e("Custom", "Error trying to get the buffer",e);
          return false;
        }
    }

My objective is post-decode modification of the buffer.  I can do this using the regular Android player with non HLS content, but in ExoPlayer, I get the BufferFreed problem.

**Comment by ojw28** [comment]
There are quite strict rules about calls to `getOutputBuffer`. Specifically, in the `MediaCodec` Javadoc, it says: *After calling this method, any ByteBuffer or Image object previously returned for the same output index MUST no longer be used.*. It's likely that your call to `getOutputBuffer` is causing an output buffer that ExoPlayer code already has a reference to to become invalid.

If you're modifying `processOutputBuffer` then you should read from the `buffer` argument that gets passed to it, rather than making any calls to `getOutputBuffer` yourself. Note also that you shouldn't rely on the position and limit of the buffer being set correctly. Use the `bufferInfo` argument to find out the offset and size of the data in the buffer. You can set the buffer position and limit using this information yourself, like:

```
buffer.position(bufferInfo.offset);
buffer.limit(bufferInfo.offset + bufferInfo.size);
```

**Comment by gtg287y** [comment]
Thank you for response. I changed my code to use the buffer that is passed into the processOutputBuffer method directly, and it works unless I need to get the width and the height, which I use the bufferIndex to do as well.

int h = codec.getOutputImage(bufferIndex).getHeight();

Is there an alternate way to get the width and the height without running into this error?

**Comment by ojw28** [comment]
MediaCodecVideoTrackRenderer already has `currentWidth` and `currentHeight` variables.

**Comment by gtg287y** [comment]
I do in fact see that now, thank you so much, you have answered my question in full.

**Comment by ojw28** [comment]
No worries; Glad you got it working!

**Comment by nikhilkilivayil** [comment]
Can you post sample full source code? @ojw28
