### ISSUE TITLE
Adaptive Quality Selection and Track selecting UI in StyledPlayerView

### ISSUE THREAD

**Issue by arunkumartdr** [google/ExoPlayer#10092]
Hai , This is Feature request for Adaptive track (quality) selector for hls and dash.

Adaptive track selection and building a custom ui for track selection is a big problem for inexperienced peoples like me.

If it was provided by default many peoples headache is solved.

As far now thanks for giving the UI , function to change speed and audio selction in StyledPlayerView.

![image](https://user-images.githubusercontent.com/31769796/159085841-ec98c62a-2570-45c2-bf18-22d128814a68.png)

**Comment by icbaker** [comment]
Are you asking us to build a UI like the one that you've screenshotted into `StyledPlayerView`? I think we're unlikely to do that, because I suspect most non-power users will be quite confused by being able to select multiple video tracks (of course we understand that what they're doing is selecting the tracks that the player is then allowed to switch between).

`StyledPlayerView` is designed to solve the majority of simple playback use-cases. We expect that most apps with more complex needs will need to implement their own components, possibly by forking the ExoPlayer ones: https://exoplayer.dev/ui-components.html#further-customization

Note that the [demo app track selection dialog](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java) **does** look similar to your screenshot, so you should be able to see how that's implemented in order to implement something similar in your app (that may be how you created that screenshot, not sure).
