### ISSUE TITLE
How can I increase the buffersize ? The amount of stream that is fetched ahead of the current location ?

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1010]
Working with a very volatile connection, I would like to configure the player to fetch ahead more than what the current fetch limit/size is. How can I go about doing it ?

**Comment by abhiguru** [comment]
For DASH it seems to be setting  the below consts in the DASHRendererBuilder
private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
private static final int VIDEO_BUFFER_SEGMENTS = 200;

**Comment by ojw28** [comment]
As per above, you can modify the constants that you located in order to change the buffer size. Increasing the number of segments is normally better than increasing the segment sizes. The other renderer builders have similar constants.

In the 2.x release it will become easier to change the buffer size, and the approach will be the same regardless of playback type.

**Comment by Behrouz-m** [comment]
Hi. Please tell me how to set buffer size in the 2.x release?

**Comment by hellofishy** [comment]
^ bump

**Comment by akashGitAgni** [comment]
For 2.x , Buffer size can be modified using LoadControl 
  `  DefaultLoadControl loadControl = new DefaultLoadControl(allocator, 30000, 45000, 1500,
                DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS);`
