### ISSUE TITLE
Does udta box belong to leaf box?

### ISSUE THREAD

**Issue by dreamwhigh** [google/ExoPlayer#10149]
In the ISO/IEC 14496-12-2015 documentation,  udta box belongs to container box. See the following statement.

> Box Type:	‘udta’
Container:	Movie Box (‘moov’) or Track Box (‘trak’)
Mandatory:	No
Quantity:	Zero or one
This box contains objects that declare user information about the containing box and its data (presentation or track).
The User Data Box is a **_container box_** for informative user-data. This user data is formatted as a set of boxes with more specific box types, which declare more precisely their content.

But in ExoPlayer source code, the udta box is parsed as leaf atom. I wonder if I can write other box in udta box such as the structure is shown in the following figure.

```  java
private static boolean shouldParseLeafAtom(int atom) {
    return atom == Atom.TYPE_mdhd
        || atom == Atom.TYPE_mvhd
        || atom == Atom.TYPE_hdlr
        || atom == Atom.TYPE_stsd
        || atom == Atom.TYPE_stts
        || atom == Atom.TYPE_stss
        || atom == Atom.TYPE_ctts
        || atom == Atom.TYPE_elst
        || atom == Atom.TYPE_stsc
        || atom == Atom.TYPE_stsz
        || atom == Atom.TYPE_stz2
        || atom == Atom.TYPE_stco
        || atom == Atom.TYPE_co64
        || atom == Atom.TYPE_tkhd
        || atom == Atom.TYPE_ftyp
        || atom == Atom.TYPE_udta
        || atom == Atom.TYPE_keys
        || atom == Atom.TYPE_ilst;
  }

```
![image](https://user-images.githubusercontent.com/48209921/161374194-d8a470b7-e86c-4d25-9d23-bfbe0550a5af.png)

Looking forward to your reply. Thank you.

**Comment by ojw28** [comment]
There is nothing stopping you from writing a user defined box in the `udta` box. ExoPlayer wont parse it by default though. You can see what we parse from the `udta` box by looking at `AtomParsers.parseUdta`.

Regarding the code: The presence in `TYPE_udta` in `shouldParseLeafAtom` is  due to the way that we handle `udta` box parsing. We effectively treat it as a leaf to read the whole box into memory, and then parse the children from the in-memory representation in `AtomParsers.parseUdta`.

**Comment by dreamwhigh** [comment]
Ok, I get it. Thanks for your reply.
