### ISSUE TITLE
player.getCurrentPosition() doesn't return correct value in case of live streaming, how can i get valid current position of live streaming?

### ISSUE THREAD

**Issue by shreyassingh431** [google/ExoPlayer#10153]
Unfortunately we can't answer all questions. Unclear questions or questions with
insufficient information may not get attention.

Before filing a question:
-------------------------

- Ask general Android development questions on Stack Overflow
- Search existing issues, including issues that are closed
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website (https://exoplayer.dev/) and Javadoc
  (https://exoplayer.dev/doc/reference/)

When filing a question:
-------------------------

Describe your question in detail.

In case your question refers to a problem you are seeing in your app:

- Output of running `$ adb bugreport` in the console

In case your question is related to a piece of media:

- URI to test content
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

Don't forget to check supported formats and devices
(https://exoplayer.dev/supported-formats.html).

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

**Comment by marcbaechinger** [comment]
`player.getCurrentPosition()` returns the position in the current live window. 

You may want to add [`Timeline.Window.windowStartTimeMs`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html#windowStartTimeMs) to get the UNIX epoch time of that position. This implies that your live stream is actually setting the `windowStartTimeMs` accordingly.

Please also look into these two JavaDoc pages that contain some diagrams that explain the different kind of timelines you may have for a live stream and what properties you can get from the `Timeline` or the `Timeline.Window`:

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.html
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html

**Comment by gabrielgarciagava** [comment]
I see that the OP did not add any description to this ticket, but I am also experiencing a wrong information comming from `player.getCurrentPosition()`.

I am using ExoPlayer to show an HLS video. If I pause the video, and request the timestamp with `getCurrentPosition`, it gives me a value that around ~100ms before what is actually being shown in the video player (around 2 frames of the video I am using). I am comparing this to the frames extracted using ffmpeg, and comparing the timestamp reported for each frame by ffmpeg.

For the sake of comparison, I am running the exact same expereriment using AVPlayer on iOS. There, the timestamp that it gives matches the frame I extract with ffmpeg.

An alternative way to execute the experiment and get to the same result. Pick any frame using ffmpeg, look the timestamp of the frame. Open the video with ExoPlayer and call seekTo to that position. The same thing will happen, the frame that will be shown is around ~2 frames (I say around 2 since I've seen 1,2 and 3 frames of difference during my tests) after the one seen with ffmpeg.

**Comment by marcbaechinger** [comment]
Thanks for reporting! Is this specific to live streaming with HLS? If not may I ask you to create a new issue? You can just copy and paste what you've written above which is a good description of what you found. 

The original issue was low-quality and the reporter also didn't want to answer questions, so I'd suggest to create a new issue instead of continuing here, because I don't think it is about the same problem.

**Comment by gabrielgarciagava** [comment]
I experienced it specifically with HLS. I did not try anything else.

Should I create a new ticket anyway?

**Comment by marcbaechinger** [comment]
Yes, please, if you don't mind. I think yours needs a different investigation than the initial question.

**Comment by marcbaechinger** [comment]
Thanks Gabriel!

I'm closing this issue due to lacking activity from the original author.
