### ISSUE TITLE
How to separate the video downloading from the player's control logic

### ISSUE THREAD

**Issue by jsw-zorro** [google/ExoPlayer#10157]
Hi all, I want to do some customization on the data downloading part when do the MPEG-DASH based video streaming. I know customizing the data source can be an option. However, as the load control and track seletion part is deeply bonded in the player's logic, and it is hard to do the customization in all these layers at the same time. So I am wondering whether I can separate the download logic from the player, for example, directly customizing the download method and download the things in the cache, and then let ExoPlayer directly read data from the cache to do the display. I wonder whether there's some instructions to implement the functions like this in DASH video streaming? I know the download helper can download and then display the adaptive video stream. However, can the downloading and displaying happen at the same time, for example, after a chunk has been downloaded then, the downloader will download the next chunk, while player can go on displaying it?

**Comment by ojw28** [comment]
It's not entirely clear what you're trying to do. If you only need to customize the component that actually downloads the data, then customizing the `DataSource` would be sufficient. However, you also write about the need to simultaneously customize load control and track selection components, at which point it becomes unclear what you're trying to do and what your definition of "download logic" encompasses.

If you do need to customize all of the components you mention to do what you're interested in doing, then I don't think there's a good alternative to doing that given ExoPlayer's architecture. It should also be noted that it's fundamentally difficult to separate out the logic that these components encapsulate from the rest of the player, because properties like the current playback position and speed, and actions like when the user performs a seek, would typically be inputs to a component that would decide what to load next (and when to load it).
