### ISSUE TITLE
Synchronizing two different video streams

### ISSUE THREAD

**Issue by jack-jjm** [google/ExoPlayer#10154]
I am trying to develop an app to run inside of a VR headset. The implementation is basically a phone in a head-brace type situation: there's one display, the app's code sees one logical display, and so you just render what you want the left eye to see on the left hand side and what you want the right eye to see on the right hand side.

I've tried two implementations: (1) pre-processing video before putting it on the headset, to clone the video horizontally, and playing it in one ExoPlayer instance. (2) just playing the video twice, in two side-by-side ExoPlayer instances (one muted). Right now I'm doing the latter, but it's ugly and also gives me some very slight desynchronization issues.

I found [this](https://github.com/google/ExoPlayer/issues/2855) question from 2017 with a similar use case. Mine is simpler - that person was using DASH, I am (for now) just trying to play local video files, and I'm not doing any OpenGL post-processing. My problem is that I just don't understand the answer posted there by an ExoPlayer contributor. I got as far as subclassing `DefaultRenderersFactory` like I said, but then I realized there was no place to inject the information about the relative layout of the two video streams (horizontally side by side) and I came to the conclusion that I wasn't going to get this working without a bit more help.

I'm really sorry to ask this broad, vague question that basically just amounts to "I don't get it and I need help", but... I don't get it and I need help. Can anyone offer *any* hints as to how to get something like this working?

**Comment by ojw28** [comment]
I think that (1) is a better approach, and that you should discard (2) because it's clearly the worse of the two options. I also think (although could be wrong) that (1) is pretty much the accepted way of doing this. Searching the web for "SBS video" throws up quite a few examples.

(1) guarantees synchronization between the two eyes, even down to frame drops. In particular, you don't start running into weird cases if the decoders can't keep up, where different frames may end up getting dropped for one eye than the other. Solution (1) also guarantees that data is buffered at an equal rate for both eyes, only requires a single decoder instance, and is likely going to be much easier to get working with other players, if you ever branch out beyond ExoPlayer.

**Comment by jack-jjm** [comment]
Thanks for the reply. I suppose if I pre-processed the videos on the headset itself that might be acceptable (so as a user you can just stick a regular video file on the device and not need any more software). However, this is still not entirely satisfactory since I'd eventually like to move on to spherical/360 video and allow the user to look around in it. I'm pretty sure no (reasonable) amount of pre-processing could handle that use-case since the viewing angles would only be known at runtime.

**Comment by ojw28** [comment]
You can use a single preprocessed video for spherical/360 as well. You need to encode the 360 video using a suitable projection, and then render it onto corresponding geometry during playback (e.g., the inside of a sphere for each eye).
