### ISSUE TITLE
No longer able to customize playback speeds

### ISSUE THREAD

**Issue by vanniktech** [google/ExoPlayer#10166]
Starting with version 2.17 I can no longer customize the playback speeds, before I was able to do the following:

```xml
  <integer-array name="exo_speed_multiplied_by_100" tools:ignore="ResourceName,UnusedResources" translatable="false">
    <item>25</item>
    <item>50</item>
    <item>75</item>
    <item>100</item>
    <item>125</item>
    <item>150</item>
    <item>200</item>
    <item>225</item>
    <item>250</item>
    <item>275</item>
    <item>300</item>
  </integer-array>

  <string-array name="exo_playback_speeds" tools:ignore="ResourceName,UnusedResources" translatable="false">
    <item>0.25x</item>
    <item>0.5x</item>
    <item>0.75x</item>
    <item>1x</item>
    <item>1.25x</item>
    <item>1.5x</item>
    <item>2x</item>
    <item>2.25x</item>
    <item>2.5x</item>
    <item>2.75x</item>
    <item>3x</item>
  </string-array>
```

This isn't possible anymore with because of:

https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L246-L247

Why was an option to overwrite this removed?

**Comment by icbaker** [comment]
The `exo_playback_speeds` array resource was removed in https://github.com/google/ExoPlayer/commit/abef4f4e1442f645d2f18bd7ca95983f9bd7df8d as part of fixing https://github.com/google/ExoPlayer/issues/9811.

Overriding this array in order to change the values presented by the player wasn't really an officially supported customization of the UI components.

The current setup with fixed speeds is already pretty fragile (because the same values have to be kept in sync between the Java field constant and the string representations in `strings.xml`). I think it's quite unlikely we'd make this officially customizable, because that's likely to greatly increase the risk of the values getting out of sync. 

This likely falls into the 'further customization' of our UI components where we expect app developers to implement their own support (possibly by forking our components): https://exoplayer.dev/ui-components.html#further-customization

**Comment by vanniktech** [comment]
Don't you think it's a bit much if simply wanting to have higher playback speed (2.25x, 2.5x, 2.75x, 3x) I need to roll my entire UI?
