### ISSUE TITLE
Latency Optimization - video play back start up time

### ISSUE THREAD

**Issue by skusuj** [google/ExoPlayer#10195]
**Question**

We are using react-native-video for video playback which on Android uses Exoplayer. We determine video playback start up time (Play To First Frame) by capturing the moment when user clicks on play button and the moment when we receive onReadyForDisplay event from native player. To better understand where most of the time spent we further break it up as player initialization time (user click to video load start event), Video Load duration (video load start event to video load event) and player ready duration (video load event to onReadyForDisplay). As part of latency optimization we are now passing buffer config with 'bufferForPlaybackMs' as 1500ms so that play back starts earlier. Our hypothesis was buffer config optimization would reduce video load duration and the overall start up time will be reduced. But what we see is though over all start up time has reduced but video load time has regressed. We are unable to understand this behavior. Could you please help me understand why is video load duration regressing and even after this regression how are we seeing over all start up time gain?

**Exoplayer Library version**: 2.11.4

**Environment info**

React Native Environment Info:
System:
OS: macOS 11.6.2
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 106.40 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
API Levels: 29, 30, 31
Build Tools: 29.0.3, 30.0.2, 31.0.0, 32.0.0
System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 2020.3 AI-203.7717.56.2031.7784292
Xcode: 11.6/11E708 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.3 => 16.8.3
react-native: 0.59.8 => 0.59.8

**Comment by skusuj** [comment]
Hi christosts,

Could you please help me with this query. Does video load duration metric provide latency information about the time spent to buffer data to start playback? If so then why in our experiment we see regressed video load duration while play to first frame has improved. Adding debug points didnt help much since there are multiple threads involved.

thanks

**Comment by tonihei** [comment]
This issue is bit old by now and may no longer be relevant. Sorry for not providing a reply sooner! 

I think we are also unlikely to solve your problem fully because you are asking to debug and optimize your app directly, which is beyond what we can do in this issue tracker. We are happy to understand common problems though and we also know that it may beneficial to lower `bufferForPlaybackMs` for the overall start time (in fact, we are considering to change our default in the future). As video and audio are competing for the same resources, the earlier start signal may contribute to the increased video load time you measured, but this is only a wild guess.
