### ISSUE TITLE
Logging Manifest and Segment Loading

### ISSUE THREAD

**Issue by jamescahall** [google/ExoPlayer#10192]
In streaming linear / live video with SSAI, we are seeing unexpectedly low render rates on FireTV devices and trying to isolate the problem.

We suspect this may be due to the player loading excessive manifest requests and/or continuing to load manifests while the app is in the background even when the player is paused.

To help evaluate this, we would like to be able to log when each manifest request is made (master and media playlists) as well as when each TS segment is loaded as well as the urls loaded.

Is there any logging we can turn on to get details at this level?

**Comment by icbaker** [comment]
You can register an `AnalyticsListener` and implement the load-related methods to give you an insight into what is being loaded. `MediaLoadData.dataType` will tell you whether a load is for a manifest, media or other types.

More info about registering and implementing `AnalyticsListener`: https://exoplayer.dev/analytics.html

**Comment by jamescahall** [comment]
Thank you.  This is helpful.  As a follow-on question, is it expected that m3u8 requests will continue when the app is put in to the background even when the player is paused?  This is causing issues with SSAI Render rates and unclear how to completely stop the player from continuously requesting the m3u8 manifests on live/linear streams when the app is in the background and should be fully suspended.  When the app returns, we are expected to start re-requesting at that time.  We don't want to have to completely destroy and re-create the player in this case.

**Comment by icbaker** [comment]
If you pause the player without stopping or releasing it, all player logic will continue while your app process is still running, whether it's in the foreground or not - ExoPlayer generally doesn't behave differently if the app ends up in the background (for example, many apps want audio playback to work 'normally' from a service with no UI).

That likely explains why we continue to refresh the HLS manifest, as required by this part of the spec: https://datatracker.ietf.org/doc/html/rfc8216#section-6.3.4

You probably shouldn't be leaving the player paused in the background for a long period, because it holds locks to scarce shared resources like video decoders - so the best way to solve this is probably to release or stop the player when your app is backgrounded.

**Comment by jamescahall** [comment]
Thanks for the feedback.  I guess this just differs from other platforms / players where if there is a not a permission or feature set to enable background audio, video playback should automatically be suspended and resumed with app lifecycles for entering and returning from background.  Typically pausing will handle that.  This is the only platform / player we've experienced this on.

**Comment by icbaker** [comment]
The way our demo app handles the player is a good reference for what we consider 'best practice' for integrating our library with the android app lifecycle (including splitting behaviour between `onPause` and `onStop` depending on API level):
https://github.com/google/ExoPlayer/blob/r2.17.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L146
