### ISSUE TITLE
r2.17.1: Is audio backbuffer only filled when paused?

### ISSUE THREAD

**Issue by AndreasVogelfrei** [google/ExoPlayer#10190]
I am using ExoPlayer to play audio streams like this one.

http://listen.100xr.com:80/aac

I have successfully implemented a backbuffer that fills up to the configured time/size when I pause the player. I monitor the buffered time using "getDuration()". However, the duration value will only increase when being in pause mode.

Is there any way to also fill the buffer while playing to be able to rewind to something that was played some time ago?

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by AndreasVogelfrei** [comment]
Sorry for being unclear. Here is a simplified version of my code:

```
	DefaultLoadControl.Builder loadControlBuilder = new DefaultLoadControl.Builder();
	loadControlBuilder.setBufferDurationsMs( 5000, // 5 seconds
			60 * 60 * 1000, // 60 minutes
			5000, // 5 seconds
			5000); // 5 seconds

	DefaultLoadControl loadControl;
			loadControlBuilder.setTargetBufferBytes(10 * DEFAULT_AUDIO_BUFFER_SIZE);
			loadControlBuilder.setBackBuffer(60 * 60 * 1000, false);
		loadControl = loadControlBuilder.build();

	ExoPlayer.Builder playerBuilder = new ExoPlayer.Builder(mAppContext);
	playerBuilder.setLoadControl(loadControl);
	playerBuilder.setMediaSourceFactory(new DefaultMediaSourceFactory(new DefaultHttpDataSource.Factory().setUserAgent("Exoplayer 2.14.0")));

	mExoPlayer = playerBuilder.build();
	mExoPlayer.setAudioAttributes(AudioAttributes.DEFAULT, false);
	mExoPlayer.addAnalyticsListener(mAnalyticsListener);
	mExoPlayer.setPlayWhenReady(true);		
	mExoPlayer.setMediaItem(MediaItem.fromUri(http://listen.100xr.com/aac));
	mExoPlayer.prepare();

	....

	mExoPlayer.getTotalBufferedDuration();

```

- When running above code, I will get a return value of about 5 to 10 seconds from the call to "getTotalBufferedDuration()" consistently while the stream is played.
- When executing "mExoPlayer.pause()" the buffer value will increase, so calls to "getTotalBufferdDuration()" will return with incrementing values as long as player is in "paused" state. So for example after 1 minute of pause, "getTotalBufferdDuration()" will return with 70 seconds.

My question is:

- Is there any way to build up a buffer of up to 60 minutes while playing the stream without pause()?

**Comment by icbaker** [comment]
The stream link provided is to a live stream - so playback will start close to the live edge and if both the playback position and live edge are advancing in real time (as you'd expect) then it's surely impossible for the buffer to increase any further than the offset between playback position and live edge?

When you pause then the playback position stops but the live edge keeps advancing, and the offset grows, allowing the buffer size to increase.

More information about playing live streams with ExoPlayer: https://exoplayer.dev/live-streaming.html

Given all that, I think what you're seeing is expected - because this is a live stream.

If you play a non-live stream (e.g. just an MP3 file) then you should exactly see the buffer building up to your specified limit whether playback is playing or paused.

**Comment by AndreasVogelfrei** [comment]
Thank you for this information. The idea of live streams is clear. So of course it is not possible to go back prior to the start of live stream.

However, even if this is a live stream it would be possible to fill a (separate) buffer while playing the stream, not only when paused. So a "last played live stream buffer" could be build up that would store a maximum of the last x byte (minutes). With this buffer it would be possible to rewind a live stream up to the size of the buffer or the start of the live stream. My question was, whether this kind of buffer is available or how I can configure ExoPlayer to being able to support this "live stream rewind" feature in my application.

**Comment by icbaker** [comment]
Ah sorry, despite it being in the title and the first comment I missed you're specifically asking about **back buffer**.

I think the problem might be that [`Player.getTotalBufferedDuration`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getTotalBufferedDuration()) doesn't include the back buffer, it only measures the amount of buffer **ahead** of the playback position. The `total` word refers to the fact that it also includes buffered content in upcoming playlist items. From the javadoc (emphasis mine):
> Returns an estimate of the total buffered duration **from the current position**, in milliseconds. This includes pre-buffered data for subsequent ads and [media items](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html).

So I would expect that the back buffer is being filled up, but you're not seeing it reported through this method.

**Comment by AndreasVogelfrei** [comment]
Thanks for the clarification.

Is there a method available to retrieve the duration of media within the back buffer? Or a way to calculate this using a combination of other methods?

And related:

After hitting pause (and seeing the buffer ahead the playback position incrementing) I tried to seek forward 5 seconds using:

mExoPlayer.seekTo(mExoPlayer.getCurrentPosition() + 5000);

However, this will lead to a new buffering and starts building up the buffer from 0 again. 
Next I tried:

            mExoPlayer.seekTo(mExoPlayer.getCurrentPosition());

I would expect no change in output but it seems like this will stop the stream and restarts.

Is there something wrong in my understanding and/or implementation to seek in live streams?

**Comment by AndreasVogelfrei** [comment]
Question about seeking in audio live streams is still open.
I did read the chapter "Seeking in live streams" here: https://exoplayer.dev/live-streaming.html
I did read https://exoplayer.dev/progressive.html#enabling-constant-bitrate-seeking

My setup for this part now looks like this:

```
            DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory()
                                                       .setConstantBitrateSeekingEnabled(true)
                                                       .setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_CONSTANT_BITRATE_SEEKING_ALWAYS);
            DefaultMediaSourceFactory mediaSourceFactory = new DefaultMediaSourceFactory(mAppContext, extractorsFactory);
            playerBuilder.setMediaSourceFactory(mediaSourceFactory);
```
I still have the same issue: I am not able to seek forward or backward in a live audio stream without restarting the stream.

**Comment by marcbaechinger** [comment]
I don't think we support seeking in progressive streams that are used as live streams. Such streams just start streaming from the current position that they are currently at. A live stream that supports seeking needs a way to seek in the media as opposed to seek in the available buffer. 

>  I am not able to seek forward or backward in a live audio stream without restarting the stream.

That's because such a stream is not seekable.

Accordingly, when I play the URI you posted above ExoPlayer tells me that the current window is not seekable:

```
window [?, seekable=false, dynamic=false]
```

When the Developer Guide is talking of live streams it is about adaptive formats with a manifest or playlist (see first sentence of the page you refering to: `ExoPlayer plays most adaptive live streams out-of-the-box without any special configuration`). The manifest delivers the chunks with which the player can build a live window in which seeking is supported. This is because the player can send requests to the server to seek to a given position in that live window and the server responds accordingly. The stream you are using behaves differently.

**Comment by AndreasVogelfrei** [comment]
Ok. Thanks a lot for this clarification. This issue can be closed.
