### ISSUE TITLE
How to lazily create MediaSource from MediaItem? Lazy Uri for MediaItem

### ISSUE THREAD

**Issue by vfsfitvnm** [google/ExoPlayer#10200]
Hi! My use case is pretty similar to #7087 and  #8324.

Basically, in order to get the `Uri` of a `MediaItem` (a song), I have to execute an additional HTTP request.
This is simply unfeasible when building playlists: I cannot fire 20+ more requests at a single time, so I was looking for a way to postpone the `Uri` thing until it is actually needed, e.g. when the player is about to play the next song, it retrieves the `Uri` and plays the song.

I came to this (working) solution:

```kt
@UnstableApi
class LazyMediaSource(private val base: MediaSource) : MediaSource by base {
    companion object {
        // A special Uri to be replaced
        val UriPlaceholder = "UriPlaceholder".toUri()
        
        // Well, MediaItem.LocalConfiguration::uri is final
        private val UriField = MediaItem.LocalConfiguration::class.java.getDeclaredField("uri").apply {
            isAccessible = true
        }
    }

    override fun prepareSource(
        caller: MediaSource.MediaSourceCaller,
        mediaTransferListener: TransferListener?,
        playerId: PlayerId
    ) {
        mediaItem.localConfiguration?.let { localConfiguration ->
            if (localConfiguration.uri != UriPlaceholder) return@let

            val id = mediaItem.mediaMetadata.extras?.getString("id") ?: error("A id must be set.")

            // Perform http request that retrieves the url
            // Can I safely do this? I guess yes because we aren't on the main thread now
            val url = getSongUrl(id) // blocking call

            // reflection
            UriField.set(localConfiguration, url.toUri())
        }

        // resume the flow
        base.prepareSource(caller, mediaTransferListener, playerId)
    }

    class Factory(private val base: MediaSource.Factory) : MediaSource.Factory by base {
        override fun createMediaSource(mediaItem: MediaItem): MediaSource {
            return LazyMediaSource(
                base.createMediaSource(
                    mediaItem.buildUpon().setUri(UriPlaceholder).build()
                )
            )
        }
    }
}
```
And then:
```kt
val player = ExoPlayer.Builder(this)
  .setMediaSourceFactory(LazyMediaSource.Factory(DefaultMediaSourceFactory(/* ... */))
  .build()
```
As you can see, `LazyMediaSource` acts as a sort of interceptor. However, this snippet feels hacky (it involves reflection to edit a `final` field) - so I was wondering if there was an "official" way accomplish my task (I also don't know if this solution is robust).

Thanks!

**Comment by marcbaechinger** [comment]
I think you should use a [`ResolvingDataSource.Factory`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java). If you need this for every media source in the playlist you can just pass it to the constructor of the  `DefaultMediaSourceFactory` and then use the `DefaultMediaSourceFactory` to build the player.

> I cannot fire 20+ more requests at a single time, so I was looking for a way to postpone the Uri thing until it is actually needed

By default `MediaSource`s are prepared lazily already. That's when `prepareSource` is called in your code above and that is also when the (resolving) data source is called.  

So you won't do several requests when you add the media items to the playlist. Instead is is called on demand when playback is close to the beginning of a media item in the playlist. If you think this is not the case, please file a bug because lazy preparation is how it is intended to work (and I'm actually pretty sure this works that way).

> // Can I safely do this? I guess yes because we aren't on the main thread now

You are on the playback thread when this is called but similar to the main thread you don't want to block the playback thread. That's another reason why you should use a `ResolvingDataSource` for this, because a specific loader thread is used to load data with data sources and you are allowed to block this thread just as a network access would block this thread in the same way.

Please also see the Developer guide that has a [section](https://exoplayer.dev/customization.html#customizing-server-interactions) around this topic.

**Comment by vfsfitvnm** [comment]
Oh. Now I see. `ResolvingDataSource` is what I was looking for (I saw it in the past days but I somehow felt discouraged because I didn't see neither a `MediaItem` nor a `MediaSource`, shame on me); I just implemented it and works fine, but, unfortunately, it doesn't require reflection so it's less cool :-1:

Thanks for the quick reply, closing!
