### ISSUE TITLE
dolby vision video problem since 2.17.0

### ISSUE THREAD

**Issue by bbq778** [google/ExoPlayer#10201]
### ExoPlayer Version

2.17.0

### Devices that reproduce the issue

lenovo xiaoxin pad pro 12.6(p12 pro)
andrioid 11

### Reproduction steps

 Play dolby vision video with Just Player 0.104+ based on ExoPlayer 2.17.0+
test files
https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/
http://www.makemkv.com/download/dvtest/

### Actual result

dolby vision profile4 profile8 Video playback in compatible format (hdr10,sdr,etc.) instead of dolby vision ，profile9 have no sample to test, But I think it will be the same.
It seems to be because  in  Exo2.17.0 "Video: Fix decoder fallback logic for Dolby Vision to use a compatible H264/H265 decoder if needed."   p5 playback Normal （Because no  compatibility mode？）

Sorry for my poor English

### Media

https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/
http://www.makemkv.com/download/dvtest/

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Can you please help us understand the issue better? Are you saying that:
- ExoPlayer should be playing Dolby Vision profile4 profile8 with HEVC
- ExoPlayer should fallback Dolby Vision profile9 with HEVC decoder too?
- ExoPlayer no longer uses the Dolby Vision decoder in the Lenovo device and instead is picking up the HEVC decoder? And you believe that's because of the change you mentioned ("Fix decoder fallback logic for Dolby Vision...")?
