### ISSUE TITLE
Exoplayer user agent

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#10213]
I have users that report different http user agent sent from my application and I'm not sure why.

I'm using a custom DataSource factory:
```
class PlayableMediaItemDataSourceFactory internal constructor(
    context: Context,
    private val musicPlayer: MusicPlayer,
    okHttpClient: OkHttpClient,
) : HttpDataSource.BaseFactory() {

    private val okHTTPFactory = OkHttpDataSource
        .Factory(okHttpClient)
        .setUserAgent(Util.getUserAgent(context, "Symfonium"))
        .setCacheControl(null)

    override fun createDataSourceInternal(defaultRequestProperties: HttpDataSource.RequestProperties): HttpDataSource {
        return PlayableMediaItemDataSource(okHTTPFactory.setDefaultRequestProperties(defaultRequestProperties.snapshot).createDataSource(), musicPlayer)
    }
}
```

So the user agent should be properly set for everything.
Yet the user report 
![image](https://user-images.githubusercontent.com/932609/164762431-821cea63-2a04-4b23-9d5e-893e95d02226.png)

So there's an ExoPlayerLib and a stagefright headers generated by Exoplayer. Is there any documentation about what I might be missing to only have 1 user agent for all requests?

**Comment by marcbaechinger** [comment]
The user agent created with `Util.getUserAgent(this, "Symfonium")` gives me the following string:

`Symfonium/1.0.0-alpha03 (Linux;Android 11) ExoPlayerLib/2.17.1`

the  `1.0.0-alpha03` is probably different for you because this is the versionName that you define in the `build.gradle` file of your app.

From the screenshot above it is a bit unclear what the actual user agent string is that the tool reports. Option 2 and 3 both could be derived from the user agent string above. I don't know where the `stagefright` user agent comes from to be honest.

I also don't know how you are using `PlayableMediaItemDataSourceFactory` and what requests your app is making against your users' server.

For media playback ExoPlayer may do requests for:

- downloading media (progressive or adaptive)
- downloading manifests (HLS/DASH/SmoothStreaming)
- text tracks (sideloaded or referenced by a manifest)
- downloading DRM licences
- native APIs
 
Can you provide me with some more info on 

1) How you build the player that you are using and how you inject your custom `PlayableMediaItemDataSourceFactory`?
2) What formats you are using?
3) What type of requests you are expecting your app to do against the server of your users (from the list above)?
4) How the exact user agent string look like that arrive at your users' server (note: they may come from different app versions also)?
5) Are you using any native extensions or native APIs?

**Comment by Tolriq** [comment]
1) The data is wrapped by
```
class ExternalPlaylistDefaultDataSourceFactory(
    private val context: Context,
    private val musicPlayer: MusicPlayer,
    okHttpClient: OkHttpClient,
) : DataSource.Factory {

    private val baseDataSourceFactory = PlayableMediaItemDataSourceFactory(context, musicPlayer, okHttpClient)

    override fun createDataSource(): DataSource {
        return ExternalPlaylistDataSource(context, baseDataSourceFactory.createDataSource(), musicPlayer)
    }
}
```
Then I use addMediaSources and map my media with
```
        val dataSourceFactory = ExternalPlaylistDefaultDataSourceFactory(applicationContext, this, okHttpClient)
        return ProgressiveMediaSource.Factory(dataSourceFactory, extractorsFactory).setDrmSessionManagerProvider { DrmSessionManager.DRM_UNSUPPORTED }
            .createMediaSource(MediaItem.Builder().setUri(uri).setMediaId(playableMediaItem.uuid).build())
```

The PlayableMediaItemDataSource is just a wrapper over the OkHttpDataSource to initiate transcoding or update the actual media url before delegating.

2) Virtually anything music related without DRM as I do not control the user server and data.
3) For this server it's only direct music urls without file extension and not sure about the headers it returns, so not sure what ExoPlayer use to detect the type and renderer.
4) Unfortunately the user have no more answered to give it's server logs, I may try to rebuild an identical one but was hopping there was something obvious I missed :(
5) I use ffmepg extension for flac, opus, alac, then the default ExoPlayer one for the rest.

**Comment by marcbaechinger** [comment]
Ok, thanks. In this case I think it's worth getting the exact user-agent strings before starting digging too much. I specifically want to rule out that the user agents are coming from various app versions. Please update the issue once you have a response from your users. The access log would be sufficient which gives some idea about how the entire ua string looks like and for what resources they requested.

**Comment by Tolriq** [comment]
So got some logs for the ExoPlayerLib and it's a bug in that application as it use all the XXX/version and not just the first. It's easy to workaround on my side.

Since he was not able to provide the logs about the stagefright let's assume it was the same issue and Android add that to the header and it's not a direct header from it.

If I ever get some logs showing otherwise I'll ping here.
