### ISSUE TITLE
Device information in the User Agent 

### ISSUE THREAD

**Issue by sc00ter5** [google/ExoPlayer#10222]
When receiving traffic from ExoPlayer the user agent does not contain information pertaining to the device the video player is running within.  This makes it impossible to attribute traffic to device categories such as ConnectedTV, Mobile App, or Tablet. 

We typically see user agent strings that looks as follows:  *AppName* (Linux;Android 7.1.2) ExoPlayerLib/2.8.4

Is there a way to pass the UserAgent string related to the device in which the request from ExoPlayer is being passed?

**Comment by marcbaechinger** [comment]
Agreed that being able to attribute requests to model and devices sounds like useful. I'm marking this issue as an enhancement. I don't think we will work on this soon I'm afraid though. 

Once because of other priorities. But probably more because it's on one hand not easy to implement this on a library level to meet everyones use cases without bloating the ua string. And on the other hand it is easy for apps to set their own ua string to exactly what ever they need it to have.

So for a quick fix for your use case, you can use some library help to get specific information. You may have noticed the string that `ExoPlayerImpl` [logcats at the beginning of construction](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L222):

```
I/ExoPlayerImpl: Init c57d78b [AndroidXMedia3/1.0.0-alpha03] [redfin, Pixel 5, Google, 32]
```

This gives you a first pointer to look into when you want some [information about device, model et al](https://github.com/google/ExoPlayer/blob/dev-v2/library/common/src/main/java/com/google/android/exoplayer2/util/Util.java#L141).

You can augment [`Util.getUserAgent(context, applicationName)`](https://github.com/google/ExoPlayer/blob/dev-v2/library/common/src/main/java/com/google/android/exoplayer2/util/Util.java#L1473) with this or roll your own to get the actual user string.

[`DefaultHttpDataSource.Factory`](https://github.com/google/ExoPlayer/blob/dev-v2/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L100) and other HTTP based data source factories let you set the user agent that will be used.

**Comment by icbaker** [comment]
I think we're unlikely to change to ExoPlayer's default user agent logic, since from 2.13.0 onwards (specifically https://github.com/google/ExoPlayer/commit/2a5f6d8f627307041050adac608c5253c20d6cb5) we don't set a default user agent at all, instead just relying on the default value of the network stack being used, unless a developer provides an explicit user agent value as Marc described. So there isn't really any logic to change.

**Comment by sc00ter5** [comment]
First of all, thanks to everyone for your replies.  

@icbaker and @marcbaechinger  - I understand your stance here.  The downside to this approach is that from my experience the majority of implementations don't take the step to define the user agent.  THis isn't traditionally required in other libraries.  The result is that services such as video platforms or ad platforms doing SSAI (server side ad insertion) aren't getting user agent strings they can work with.  I work at a video platform and we have multiple CTV apps from various vendors using ExoPlayer and nearly all of them provide these shortened user agent strings.  The real world impact of these shortened user agents is that video platforms track the traffic as "unknown" and advertisers don't buy the traffic because it can't be attributed to a device such as a tablet, phone, or CTV set. So there is a very real reporting and revenue impact on the companies that use this player.  I do not see these issues with any other video player across apps or web.  

I understand that during implementation it is possible to specify the user agent to pass the device level data, but this step isn't required by other video players, so it doesn't get done by most engineers when implementing ExoPlayer.

**Comment by icbaker** [comment]
> The real world impact of these shortened user agents is that video platforms track the traffic as "unknown" and advertisers don't buy the traffic because it can't be attributed to a device such as a tablet, phone, or CTV set. So there is a very real reporting and revenue impact on the companies that use this player.
> ...
> I understand that during implementation it is possible to specify the user agent to pass the device level data, but this step isn't required by other video players, so it doesn't get done by most engineers when implementing ExoPlayer.

If there's revenue impact when not doing this step, then it seems the developers of the apps should be incentivised to do the step - in order to increase their revenue?

---

Aside:

> The result is that services such as video platforms or ad platforms doing SSAI (server side ad insertion) aren't getting user agent strings they can work with.

It sounds like you're describing a particular way of doing SSAI where an untrusted/uncontrolled app directly makes requests to get a media stream that has ads already embedded. This leads to relying on generally unreliable properties, like the user agent of the request. As an example of why this could be a problem: A malicious app that wanted to maximise ad revenue could trivially spoof all their requests to come from the 'highest value' user agent string (devices that advertisers are willing to pay the highest amount to target). Maybe the ad-insertion server has some heuristic analysis that can detect this kind of spoofing as it wouldn't fit the expected histogram of devices - but in that case they can likely also trivially detect the 'shortened' user agent strings problem you describe.

This isn't the only way to do SSAI - it's possible to build systems where the ad server can have information about the playback environment that's much harder to spoof.

----

I'm going to close this as we're not going to change ExoPlayer's user agent defaults - apps that need the user agent to have a particular value for revenue purposes should use the APIs available to set the value.

**Comment by sc00ter5** [comment]
Thank you for the feedback.  I will try to educate app developers on how to implement this player framework so that the user agent of the device is passed.
