### ISSUE TITLE
onMediaItemTransition event happens 50-100 millis after the media item is transitioned

### ISSUE THREAD

**Issue by ScottPierce** [google/ExoPlayer#10224]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Pixel C Emulator - API 32, along with FIreTV / Android TV devices

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Create a basic ExoPlayer
2. Add several videos to a `ConcatenatingMediaSource` to make a play list
3. Add a `Player.Listener` to the `ExoPlayer`, and log timestamps for `onRenderedFirstFrame` and `onMediaItemTransition`.
4. Notice that the timestamps in the emulator are 50-100 millis behind each other. This can be even worse on low end AndroidTVs.

### Expected result

I receive the `onMediaItemTransition` event at the same time as the `onRenderedFirstFrame` event.

### Actual result

`onMediaItemTransition` event comes 50-100 millis after the `onRenderedFirstFrame` event.

### Media

This is media agnostic, but should work with any h264 videos.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I can not repro this to the extend you are reporting. When I play a playlist with two items I get two `onFirstFrameRendered` and `onMediaItemTransitioned` events - one for each media item I get this log:

```
2022-04-28 10:56:59.614 I/ExoPlayerImpl: Init 426d192 [AndroidXMedia3/1.0.0-alpha03] [raven, Pixel 6 Pro, Google, 32]
// initial media item transition when changing the playlist (setMediaItems(mediaItems))
2022-04-28 10:56:59.620 D/EventLogger: mediaItem [eventTime=0.00, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]

// first frame rendered: eventTime=0.25, window=0, period=0, mediaPos=0.00
2022-04-28 10:56:59.871 D/EventLogger: renderedFirstFrame [eventTime=0.25, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0x745af8f]

// first frame rendered: eventTime=25.38, window=1, period=1, mediaPos=0.00
2022-04-28 10:57:25.000 D/EventLogger: renderedFirstFrame [eventTime=25.38, mediaPos=0.00, window=1, period=1, Surface(name=null)/@0x745af8f]
2022-04-28 10:57:25.016 D/EventLogger: positionDiscontinuity [eventTime=25.40, mediaPos=0.02, window=1, period=1, reason=AUTO_TRANSITION, PositionInfo:old [mediaItem=0, period=0, pos=25000], PositionInfo:new [mediaItem=1, period=1, pos=0]]
// media item transition: eventTime=25.40, window=1, period=1, mediaPos=0.01
2022-04-28 10:57:25.018 D/EventLogger: mediaItem [eventTime=25.40, mediaPos=0.02, window=1, period=1, reason=AUTO]
```

According to this log the media item transition event actually happens 2 milliseconds after the `firstFrameRendered` event and is reported by logcat 18 milliseconds after it. The first eventTime is when the event is happening in ExoPlayer. The second timestamp is produced by logcat at the moment the log line is output.

> I receive the onMediaItemTransition event at the same time as the onRenderedFirstFrame event.

Well, I think you don't mean 'at the same time' in that very sense on a single thread. So there is a bit of a delay between receiving two events that you need to accept. Actually happening are the events at `eventTime` which is 2ms as reported above.

>  log timestamps for onRenderedFirstFrame and onMediaItemTransition

Can you clarify when these timestamps are generated when you measure? Is this a timestamp you take at the moment when you receive the `onFirstFrameRendered` event or is it the logcat timestamp?

> Add several videos to a ConcatenatingMediaSource to make a play list

If you use the top-level playlist API instead of the `ConcatenatingMediaSource` and then measure again, do you get the same results or do you see improved latency? If you measure again I'd use a real device for this as opposed to an emulator.

**Comment by marcbaechinger** [comment]
> I receive the onMediaItemTransition event at the same time as the onRenderedFirstFrame event.

I just came to my mind that if you are using the `onEvents(Player, Events)` callback instead of two different callbacks, then you are virtually receiving these events at the same time.

**Comment by ScottPierce** [comment]
On my emulator I'm seeing these events pretty far apart, and this is even worse on low end AndroidTV / FireTV devices.

You are testing this on a `Pixel 6 Pro` it looks like? Maybe it's just running faster?

**Comment by ScottPierce** [comment]
I was using an older version of Exoplayer, and I noticed that `onEvents(Player, Events)` was coming at the same time as the `onMediaItemTransition` on the older version. When I updated to the latest version, I found that there was an event being thrown at roughly the same time as `onRenderedFirstFrame`.

Currently we're working around this by using `onRenderedFirstFrame`, and fixing the View overlays there so its not noticeable.

**Comment by marcbaechinger** [comment]
Thanks for letting me know. Closing this issue. Please reopen if you think this is required.

**Comment by ScottPierce** [comment]
@marcbaechinger Its not letting me reopen the issue.

Is there a technical reason that `onMediaItemTransition` doesn't come at the same time as `onRenderedFirstFrame`?

I had the work around in place before I filed this ticket. I filed the ticket so that hopefully this would be fixed and I don't need to continue doing hacky things in my code to work around this.
