### ISSUE TITLE
How can I find the currently playing `cmfv` source url? (DASH/HLS)

### ISSUE THREAD

**Issue by greypins** [google/ExoPlayer#10223]
What's the best approach to determining which `cmfv` url is currently being played in ExoPlayer? Specifically for DASH/HLS streams.

I didn't see a direct callback in `AnalyticsListener`, however I was able to find all the information from the `EventTime.timeline.manifest` in `AnalyticsListener.onTimelineChanged`, but I'm not sure how to grab the url for the `cmfv` we're playing from the `manifest` via the `onTimelineChanged` callback (since there are multiple tracks in the manifest and I don't see a "selected index" for said tracks)

Is there an API that can tell me what the url is of the loaded `cmfv` media? 

Reason being, we want to log this whenever the player "changes tracks" when playing ABR media. It's easy to log the loaded base url (e.g. `foobar.mpd` or `foorbar.m3u8`), but very cumbersome to find the playing `cmfv` (e.g. `foobar_720.cmfv`).

Thanks!

**Comment by marcbaechinger** [comment]
> we want to log this whenever the player "changes tracks" when playing ABR media

If it's not about the files but just about the track selection made by the player then you may find `onTrackChanged` more useful because this reports exactly that.

I don't think there is a way to find out what chunk is currently *being played* but you can track when a file *is being loaded*. For this `AnalyticsListener` [has callbacks telling you](https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L765) when a file is being loaded and whether the load has been completed, cancelled or failed (`onLoadStarted()`, `onLoadCompleted()` and `onLoadCancelled()` and `onLoadError()`).

**Comment by greypins** [comment]
Thanks @marcbaechinger, the `onLoadXXX` gets the job done! I'll need to connect the dots myself between "track selected" and the file/path that was "selected".

It would be nice to know the path of which chunk/track is being played via `onTrackChanged` (or a different API?), but this works in the meantime.
