### ISSUE TITLE
Problem with ExoPlayer Notification Controls

### ISSUE THREAD

**Issue by devayush20** [google/ExoPlayer#10233]
I am making a audio player app. I created a service for audio player and playback notification. I am facing problem with the previous/next buttons in the Player as well as the playback notification.

1. The previous/next buttons in the audio playback notification just restarts the playback and do not change the song/audio file. 
Other controls work well.
2. The previous/next buttons in the audio player (using exoplayer) change and play the next/previous file but the player artwork (image for audio file) do not change. Also, the play/pause button remains in paused state and when pressed, it plays a different file.
Please Help!

**Comment by marcbaechinger** [comment]
You need to add a bit more context for us, so we know how you are trying to achieve the above things.

From what you describe it looks like there is something completely not working as intended, so I think it's worth that you review you app code to see whether you are really doing what you are intended to do. We can not review your app code I'm afraid, but if you think you found a bug in the library please create a narrowed down sample that exhibits the problem so we can take a look.

With the available information I can just guess and based on the experience of `PlayerNotificationManager` working well for many apps I would probably be tempted to blame app code for the malfunctioning which may be wrong. So if you want to make us look into this issue, you need to add some more information about what you do and how you think the library is wrong.

For your point 1, this could look like your service is restarted after it crashes and is restarted again because of the `START_STICKY` flag that you probably use. That's a guess. Please add `EventLogger` to your player, go through the scenario again and the take a bug report which you attach to this issue. This would make your issue actionable for us.

For your point 2, that is a different issue than 1, I'd kindly ask you to try this with the demo app and see whether it behaves the same. If you see the same issue with the demo app, I'd suggest to open a different issue, because this is not related to the notification. In this case please provide us with sample media URIs of these audio files, so we can see where the metadata is coming from and why the artwork is not displayed as expected.
