### ISSUE TITLE
Replacement for ActionFileUpgradeUtil.upgradeAndDelete ?

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#10237]
When updating to version 2.17.1, I find that `ActionFileUpgradeUtil.upgradeAndDelete` in package `com.google.android.exoplayer2.offline` was removed. What is the replacement for this method?

**Comment by ojw28** [comment]
There is no built in replacement. Given how long action files have been deprecated, I'd be somewhat surprised if you still need it. It would probably only be used in cases where a user hasn't updated your app for a _long_ time, and then does so. Pragmatically, it may well be OK just to delete any previously downloaded content in this case, since the number of users affected is likely to be very small.

If you do need to maintain backward compatibility this far back, it's straightforward just to copy `ActionFileUpgradeUtil` and `ActionFile` from the last release in which it was present into your own codebase. You also need to copy `DownloadManager.mergeRequest` into `ActionFileUpgradeUtil`, but nothing else is needed to get things working. I think it's a ~5 minute job.
