### ISSUE TITLE
Detect subtitle load errors when using the `MediaItem` API

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#10247]
Hi, I've been migrating to lastest release called 2.17.1

I am trying to use `SubtitleConfiguration` when setting `MediaItem`.

And I used to use below function when playing external subtitles.
`SingleSampleMediaSource.Factory.setTreatLoadErrorsAsEndOfStream`

However, There is nothing that I could assign corresponding values or function using `SubtitleConfiguration`.

It could be easy if there is a deligating interface of it, even though, it still can use previous way.

**Comment by icbaker** [comment]
The default value for `SingleSampleMediaSource#treatLoadErrorsAsEndOfStream` is `true` (since https://github.com/google/ExoPlayer/commit/f076080434c24a00309098ef3afc350d175ec4bb, as mentioned in the [2.13.0 release notes](https://github.com/google/ExoPlayer/blob/r2.13.0/RELEASENOTES.md#2130-2021-02-04)) - so I assume you're trying to set it to `false`? The default was flipped as part of https://github.com/google/ExoPlayer/issues/8430 in order to avoid adding this very implementation-detail-y option to the `MediaItem` (and friends) API surface (which is basically what you're asking for here).

Could you add a bit of detailed context about why you need to set this value to `false`?

Thanks!

**Comment by HyowonHwang** [comment]
Yes, I'm trying to set it to `false`.

When I play content with side-loaded subtitles, and sometimes meet errors while loading it.
Each time, I would like to figure out reasons why happened.  

However, if there is any way to do it,  even though `SingleSampleMediaSource#treatLoadErrorsAsEndOfStream` is `true` . Please, let me know it.

**Comment by icbaker** [comment]
If you just want to know that a load error occurred (to allow you to investigate it), you can listen to [`AnalyticsListener#onLoadError`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onLoadError(com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime,com.google.android.exoplayer2.source.LoadEventInfo,com.google.android.exoplayer2.source.MediaLoadData,java.io.IOException,boolean)). That should still be triggered for load errors that are treated as end-of-stream (i.e. with the option set to `true`).

**Comment by icbaker** [comment]
Closing because I think the question was answered.
