### ISSUE TITLE
Is it possible to play two audio files simultaneously with exo-player?

### ISSUE THREAD

**Issue by sriramkp** [google/ExoPlayer#10258]
I have a requirement to play two audio files with different volume simultaneously. 
For example, a music audio file and instructions audio file together based on the language selection by the user.

If possible, please share any documentation or code snippet.

**Comment by tonihei** [comment]
The answer depends a bit on your synchronization requirements between these files.

If one file is just background music and the other spoken text that has no direct synchronization to the music, then I would just use two independent `ExoPlayer` instances at the same time. Then you can also set the volume independently.

If you need to play both files synchronously, then it becomes considerably more complicated. Each player uses the audio output as the primary time source (from `MediaCodecAudioRenderer.getPositionUs` specifically). Having one player use the other player as time source doesn't work very well for this case because audio can't be easily adapted to "wait" for the other player. So the only sensible way to achieve synchronization is to use one `Player` which playes both files together and then merges both raw audio PCM data in a special `AudioSink`. See #4261 where this has been explored in more detail.

**Comment by tonihei** [comment]
Closing because the question was answered.
