### ISSUE TITLE
Concerns on `SimpleExoPlayer(SimpleExoPlayer.Builder)` deprecation

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#10277]
**Before upgrading ExoPlayer 2.16.1**

We had a custom implementation by inheriting `SimpleExoPlayer(SimpleExoPlayer.Builder)` in order to override some of the `Player.java` interface methods which are implemented in `SimpleExoPlayer.java` to add some customizations on top of the default implementation.

Example: 
```
class CustomExoPlayer internal constructor (builder: SimpleExoPlayer.Builder): SimpleExoPlayer(builder) {

        override fun setMediaSources(mediaSources: MutableList<MediaSource>, startWindowIndex: Int, startPositionMs: Long) {
                //We added some custom implementation here
                super.setMediaSources(mediaSources, startWindowIndex, startPositionMs)
        }

}
```

**Now we are upgrading to ExoPlayer 2.16.1**

Since `SimpleExoPlayer.java` is annotated as `Deprecated` and Suggested to use `ExoPlayer.Builder`.

https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L364

`ExoPlayer.Builder` class is a final so could not inherit to achieve what we had done previously with `SimpleExoPlayer.Builer`.

**Question 1**
Going forward How we can inherit `ExoPlayer` to override the existing implementation in `SimpleExoPlayer.java`?

**Question 2**
We can see `SimpleExoPlayer.Builder(builder: ExoPlayer.Builder)` has been used internally with package-level restrictions, will there be a chance to access this from outside the library?

**Question 3**
https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L964

We can still see `ExoPlayer.java` using `SimpleExoPlayer` to build an instance, going forward will there be a chance `SimpleExoPlayer.java` will be removed since it has been marked as Deprecated?

**Comment by icbaker** [comment]
We've removed the ability to subclass the `ExoPlayer` implementation because we believe you should be able to achieve all the customisations you need via the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) instead. This is much easier to reason about, both for app developers and library maintainers, and helps to avoid some of the spaghetti code that can result from lots of code-sharing via inheritance.

----

> **Question 1**
> Going forward How we can inherit `ExoPlayer` to override the existing implementation in `SimpleExoPlayer.java`?

The customisation you describe here is possible using the decorator pattern (with some help from [`ForwardingPlayer`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ForwardingPlayer.html)):

> ```
> class CustomExoPlayer internal constructor (builder: SimpleExoPlayer.Builder): SimpleExoPlayer(builder) {
> 
>         override fun setMediaSources(mediaSources: MutableList<MediaSource>, startWindowIndex: Int, startPositionMs: Long) {
>                 //We added some custom implementation here
>                 super.setMediaSources(mediaSources, startWindowIndex, startPositionMs)
>         }
> 
> }
> ```

Something like (forgive me for writing in Java, it's much faster/more natural for me, I'm sure you can convert to Kotlin):

```
class CustomExoPlayer extends ForwardingPlayer implements ExoPlayer {
  private final ExoPlayer delegate;

  CustomExoPlayer(ExoPlayer delegate) {
    super(delegate);
    this.delegate = delegate;
  }

  @Override
  setMediaSources(List<MediaSource> mediaSources, int startWindowIndex, long startPositionMs) {
    // Add your custom implementation here
    delegate.setMediaSources(mediaSources, startWindowIndex, startPositionMs);
  }

  ... All the other ExoPlayer-only methods will need to be implemented to forward directly through to this.delegate.
}
```

Note that this is not quite equivalent to your existing `extends SimpleExoPlayer` approach, because it **won't** be called from any of the places inside `ExoPlayerImpl` (or `SimpleExoPlayer`) that call `setMediaSources(List<MediaSource>, int, long)`. However, relying on these calls before was extremely fragile - because it was quite reasonable for the implementation to change in a way that these methods are no longer called internally (this is what I'm referring to above as subclassing making things hard to reason about). If you care about hooking every overload of `setMediaSources` then you need to 'decorate' each one in your `CustomExoPlayer` class.

Unfortunately we don't currently have a `ForwardingExoPlayer`, which makes this solution slightly more verbose than it needs to be. If there's enough demand for these sorts of customisations we would certainly consider adding a `ForwardingExoPlayer` to the library.

-----

> **Question 2**
> We can see `SimpleExoPlayer.Builder(builder: ExoPlayer.Builder)` has been used internally with package-level restrictions, will there be a chance to access this from outside the library?

This constructor only exists to reduce code duplication between `SimpleExoPlayer` and `ExoPlayer` and their builders. We don't have any plans to increase its visibility.

----

> **Question 3**
> 
> https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L964
> 
> We can still see `ExoPlayer.java` using `SimpleExoPlayer` to build an instance, going forward will there be a chance `SimpleExoPlayer.java` will be removed since it has been marked as Deprecated?

This method also only exists to reduce code duplication. We plan to remove `SimpleExoPlayer` in a future release (no firm date yet), and when we do this method will be removed as well.

**Comment by drayan85** [comment]
Thanks, @icbaker for your detailed response
