### ISSUE TITLE
why ExoPlayer not use Kotlin

### ISSUE THREAD

**Issue by yuzhidi** [google/ExoPlayer#10275]
why ExoPlayer not use Kotlin? mostly code is JAVA. 
is there any consideration? as performance, cpu loading, memory usage, easy integrating as so on

**Comment by besarmemishi** [comment]
Why should they use Kotlin?

**Comment by yuzhidi** [comment]
> Why should they use Kotlin?

less code than JAVA
JAVA is boring

**Comment by icbaker** [comment]
There's a couple of reasons we don't currently have any Kotlin in the library:

* **History:** ExoPlayer was started when Kotlin was a much less mature language than it is now - so at the time the natural choice was Java.
* **Library size:** Apps that depend on Kotlin see APK size increase by at least 40kB (after all minification). This is obviously not an issue for any apps that are already pulling in Kotlin, either via another dependency or by writing parts in Kotlin themselves. But as a very widely used library, we're aware that apps use us in a huge range of contexts - some of which are very sensitive to APK size. Unconditionally increasing the size of all these apps would be a shame (and likely lead to complaints :)).
  * This issue makes it harder for us to use Kotlin in our most commonly used components - but it makes it more likely that we will use it in a new extension module, or one that already pulls in Kotlin via its own dependencies. An example of this second one is our OkHttp extension, because OkHttp is written in Kotlin. In this case we just haven't got the capacity to rewrite the existing Java extension into Kotlin for little concrete benefit.

The team would like to use more Kotlin in the library in future - but we're basically waiting for the right opportunity when it makes sense.

**Comment by yuzhidi** [comment]
> There's a couple of reasons we don't currently have any Kotlin in the library:
> 
> * **History:** ExoPlayer was started when Kotlin was a much less mature language than it is now - so at the time the natural choice was Java.
> * **Library size:** Apps that depend on Kotlin see APK size increase by at least 40kB (after all minification). This is obviously not an issue for any apps that are already pulling in Kotlin, either via another dependency or by writing parts in Kotlin themselves. But as a very widely used library, we're aware that apps use us in a huge range of contexts - some of which are very sensitive to APK size. Unconditionally increasing the size of all these apps would be a shame (and likely lead to complaints :)).
>   
>   * This issue makes it harder for us to use Kotlin in our most commonly used components - but it makes it more likely that we will use it in a new extension module, or one that already pulls in Kotlin via its own dependencies. An example of this second one is our OkHttp extension, because OkHttp is written in Kotlin. In this case we just haven't got the capacity to rewrite the existing Java extension into Kotlin for little concrete benefit.
> 
> The team would like to use more Kotlin in the library in future - but we're basically waiting for the right opportunity when it makes sense.

thank you very munch !!!
