### ISSUE TITLE
Rebuffering Events over 250Mbps Wi-Fi Link

### ISSUE THREAD

**Issue by imranbuet63** [google/ExoPlayer#10281]
Hi, 

I am playing low latency live Dash video hosted at a server that is just one hop away from the phone (pixel 5, Exoplayer 2.16.1). The Wifi router has 250Mbps + BW available and has no congestion or network interruptions. The live version of the MPD is attached. We observed for the same MPD, Exoplayer playback experiences at least one rebuffer event during the playback. Out of 10 runs, this occurs on average 5 times. In other times the player is able to playback without any rebuffer event. 

While investigating the issue we found out that the parameter bufferDurationUS has variations between the runs. 

For a segment size of 3 seconds, a target latency of 4 seconds is set at the server  we ran 10 runs and found out that

1. In the runs (5 /10) with rebuffer events the bufferDurationUS  varies between 100ms to 3s.
2.  In the runs with no rebuffer events bufferDurationUS varies between 3s to 6s.

Why does the player have these two types of behaviors under the same setting? Is there any other issue that could be causing the rebuffer events?

[samplempd.txt](https://github.com/google/ExoPlayer/files/8737082/samplempd.txt)

**Comment by icbaker** [comment]
Based on the information provided, it seems reasonably likely that the rebuffers you're seeing are due to the data not being available from the server when the player requests it (the link speed is obviously only one factor, if the server can't provide the requested data fast enough then it doesn't really matter how fast the link is, you're still going to see a rebuffer).

See the discussion in https://github.com/google/ExoPlayer/issues/9750 for a similar case.

**Comment by imranbuet63** [comment]
Thanks for the reply. We also suspected that. We thought data not being available from the server when the player requests it would always result in 404 media load errors. But for this case, we don't see such 404 errors. Would you explain how the player would adapt to avoid 404 errors? if possible please guide us to the piece of code that would help us to debug further.

**Comment by icbaker** [comment]
> We thought data not being available from the server when the player requests it would always result in 404 media load errors.

This really depends on your server implementation, and how it behaves when data is requested that isn't ready yet. It could just block the request until the data is ready, instead of returning a failed status - and this seems like a very reasonable behaviour for a live streaming server, where it's likely (as in this case) that a player will request data that isn't ready yet, and immediately failing the request could be quite disruptive.

You should be able to get a much more complete picture of how the player is interacting with the server by looking at both player and server logs together.

**Comment by tonihei** [comment]
Some further comments:
 - When you are using a `SegmentTimeline`, ExoPlayer assumes all listed segments are available for loading (=don't result in a 404 or similar) without checking any of the timing values. 
 This isn't technically correct, because according to the DASH spec, we should check the end time of the segment and the `availabilityTimeOffset` property to understand when the segment becomes available. Your manifest doesn't seem to set `availabilityTimeOffset` at all at the moment and you may want to fix this. This isn't an issue yet, but it may become one if we start using the `availabilityTimeOffset` property for `SegmentTimelines`.
 - The sample manifest only defines a single available segment and sets the target latency very close to the end of this segment. Even if we were loading a new manifest that declares the next available segments immediately, the player would still only have ~1 second to load and parse this manifest, potentially load the init segment, and start loading and decoding the new segment. 
 Example timing from the provided manifest snapshot: Single segment from 06:52:58.304 - 06:53:01.304, with a publish time of 06:53:04.046 (assuming this is sync'ed to the UTC clock) and a target offset of 4 seconds, meaning the player should be playing at 06:53:00.046, leaving only 1.258 seconds until the end of the segment.
 - The player isn't likely to load this new manifest immediately though because it leaves exactly 3 seconds (`minimumUpdatePeriod`) until the next manifest reload. So in the provided example, it seems almost inevitable that the player runs into rebuffer before even attempting to load the next manifest. 
 - You may not see this rebuffer happening very often because during initial start-up, the player also waits a bit until it has 2.5 seconds of buffered media decoded before starting playback, likely implying you are further than the target 4 seconds away from the live edge. And then it attempts to get to this 4 second target offset, but only if it deems it safe to do so. This safety net likely prevents the player from ever reaching the 4 second target if the manifests always look like that and likely prevents the majority of rebuffers that could have happened. You can log `player.getCurrentLiveOffset` to see where the player is actually playing.

Overall the issues above indicate that your setup is very fragile even under perfect network conditions and you should probably try to increase the segment availability, decrease the manifest update period, make segments available earlier if possible (e.g. by using a `SegmentTemplate` without a `SegmentTimeline` and declaring the `availabilityTimeOffset`) and increase the target latency to make playback more robust if needed.

**Comment by tonihei** [comment]
Closing this issue because I assume the question was addressed with the answer above.
