### ISSUE TITLE
[Question] Retrieving current Audio Focus from AudioFocusManager

### ISSUE THREAD

**Issue by xeinebiu** [google/ExoPlayer#10293]
### Problem

While setting the `Audio Attributes` to the player

````kotlin
setAudioAttributes(
 AudioAttributes
      .Builder()
      .setUsage(C.USAGE_MEDIA)
      .build(),
    true   // handle audio focus
)
````

I am not able to find any way how to listen for the `handle focuss` flag change event. 

### Question

Is there any property or listener to allow me to receive the flag used in the Exo player for handling audio focus?

### Other
````gradle
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.17.1'
````

**Comment by christosts** [comment]
The player does not propagate audio focus change events to the app, there's no listener/callback available. If the app needs/wants to listen to such events, the app needs to register its own `AudioManager.OnAudioFocusChangeListener`. 

That said, can you please share a use-case why would you need to handle those events explicitly even when you ask the player to handle audio focus?

**Comment by xeinebiu** [comment]
> The player does not propagate audio focus change events to the app, there's no listener/callback available. If the app needs/wants to listen to such events, the app needs to register its own `AudioManager.OnAudioFocusChangeListener`.
> 
> That said, can you please share a use-case why would you need to handle those events explicitly even when you ask the player to handle audio focus?


To be consistent while programming, I always send commands to `ExoPlayer` such as `shuffle | repeat | speed ...` and only save the configuration into the database when `ExoPlayer` through the `Player.Listener` emits the events. 
So, I assumed because even though I know what commands and flags I send to the player, the player still informs me about changes through Listeners and the same would be the case for the Audio Focus option.

**Comment by christosts** [comment]
When playback is stopped due to loss of audio focus, [`Player.Listener.onPlaybackSuppressionReasonChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onPlaybackSuppressionReasonChanged(@com.google.android.exoplayer2.Player.PlaybackSuppressionReasonint)) will be called with reason `Player.PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS`.

The event included in `Player.Listener.onEvents()` with key `EVENT_PLAYBACK_SUPPRESSION_REASON_CHANGED`.

Does this cover your use-cases?
