### ISSUE TITLE
MPEGTS, Video played but no sound. Can someone correct me the code.

### ISSUE THREAD

**Issue by DinhLap96** [google/ExoPlayer#10299]
Video link : http://cdn.socolacdn.online:8080/VTV1/mpegts  (with audio, video)

After adding "FLAG_DETECT_ACCESS_UNITS", the video can play images but no sound, following the instructions from https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play
#r2.17.1

Can someone tell me how to play the sound again.

                val dataSourceFactory: DataSource.Factory = DefaultHttpDataSource.Factory()
                    .setAllowCrossProtocolRedirects(true)
                val extractorsFactory = DefaultExtractorsFactory()
                    .setConstantBitrateSeekingEnabled(true)
                    .setConstantBitrateSeekingAlwaysEnabled(true)
                    .setTsExtractorFlags(FLAG_ALLOW_NON_IDR_KEYFRAMES or
                            FLAG_DETECT_ACCESS_UNITS or
                            FLAG_IGNORE_SPLICE_INFO_STREAM or
                            FLAG_ENABLE_HDMV_DTS_AUDIO_STREAMS)
                    .setTsExtractorTimestampSearchBytes(TsExtractor.TS_PACKET_SIZE)
                    .setFragmentedMp4ExtractorFlags(FLAG_WORKAROUND_IGNORE_EDIT_LISTS or
                            FLAG_WORKAROUND_IGNORE_TFDT_BOX or
                            FLAG_WORKAROUND_EVERY_VIDEO_FRAME_IS_SYNC_FRAME or
                            FLAG_ENABLE_EMSG_TRACK)
                    .setTsExtractorMode(TsExtractor.MODE_MULTI_PMT)
                    .setAdtsExtractorFlags(AdtsExtractor.FLAG_ENABLE_CONSTANT_BITRATE_SEEKING)

               val mediaSource= ProgressiveMediaSource.Factory(dataSourceFactory,extractorsFactory)
                    .setContinueLoadingCheckIntervalBytes(ProgressiveMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES / 2)
                    .createMediaSource(MediaItem.fromUri(Uri.parse(url.toString())))

        exoPlayer.setMediaSource(mediaSource)
        exoPlayer.prepare()

**Comment by christosts** [comment]
`mediainfo` says the audio encoding is "MPEG Audio Version 1 Layer 2", which I believe is not guaranteed to be supported by the Android platform.  Consider testing the specific content with the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html) and inspecting the log output. Look out for logs produced by the `EventLogger`. You will be able to verify whether the audio format is supported by the device or not. 

Here's a sample log output when the audio format is supported

```
MediaCodecAudioRenderer [
        Group:1, adaptive_supported=N/A [
          [X] Track:0, id=2, mimeType=audio/ac3, channels=6, sample_rate=48000, language=en, label=ENG VO : AC3 5.1, supported=YES
        ]
      ]
```

If you see `supported=NO`, then that's why you can't hear audio. In that case, consider using a different audio encoding (if you have access to the content creation), or consider using the [ffmpeg module](https://github.com/google/ExoPlayer/tree/r2.17.1/extensions/ffmpeg).

**Comment by DinhLap96** [comment]
Thank you for your input on the "ffmpeg module". Add "ffmpeg","AV1", the sound is already there. But the running image is still not perfect, has noise, blue screen.
