### ISSUE TITLE
Is default max bitrate for E-AC-3 too high?

### ISSUE THREAD

**Issue by mayurk2** [google/ExoPlayer#10296]
We were trying to play an E-AC-3 DASH stream but playback was not starting.
On adding multiple logs, we found that audio is not starting and due to that the video was also stuck.

It was a multi period DASH stream with first period of ~2.9s (Very short).
When we try to play longer period DASH stream, it was working fine. But we noticed that the playback was starting after feeding ~8 seconds of audio data to renderer.

On further analysis we found that Audio renderer was configured with with high buffer size. This was happening as E_AC3_MAX_RATE_BYTES_PER_SECOND (6144 * 1000 / 8) was used to calculate the buffer size.

In our stream, the bitrate of the E-AC-3 stream was very low (192 kbps) compared to the bitrate value used by the Exoplayer.

We resolved the issue by using lower bitrate value.

My question is on what basis value for E_AC3_MAX_RATE_BYTES_PER_SECOND is chosen? Is it the typical value? Or is it too high? Thanks.

**Comment by christosts** [comment]
The value of `E_AC3_MAX_RATE_BYTES_PER_SECOND` seems correct as per spec. If playback got stuck, that might be due to something else. Does the issue occur with the latest version of ExoPlayer (2.17.1 at the moment of writing this)? If yes, would you be able to share a link to the content so I can take a look?

If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #10296". Please also update this issue to indicate you've done this.

Thanks.
