### ISSUE TITLE
prepare() followed by seekTo(0) for HLS event playlist causes playback to start at live edge

### ISSUE THREAD

**Issue by ptsekov** [google/ExoPlayer#10291]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Amlogic S905X4 Android TV device running Android 10
Amlogic S905X Android TV device (Mecool KM8) running Android 8

### Reproducible in the demo app?

Yes

### Reproduction steps

1) prepare() the player with HLS event playlist and position 0
2) optionally call seekTo(0)

### Expected result

Media plays at start of the playlist

### Actual result

Media plays at live edge

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ptsekov** [comment]
We've recently moved from ExoPlayer 2.7.0 to ExoPlayer 2.15.1. It came to our attention that in certain cases the media would start playing at live edge where it used to play from the start of the live playlist before we upgraded to ExoPlayer 2.15.1. Basically what the code does is call prepare() with MediaSource (deprecated) followed by seekTo(0). I've also tested with the suggested replacement - setMediaSource() passing source and position followed by prepare() with the same result. If I change the position to > 0 the playback starts at the expected position.

**Comment by ptsekov** [comment]
Just tested with a slightly modified version of the ExoPlayer demo from release-v2 branch in Android TV emulator running Android 9. The problem exists. I changed the demo to add a single media item to the player and pass position 0 to setMediaItem() .

**Comment by christosts** [comment]
I  can't tell exactly when the behavior changed since 2.7.0, but the current behavior is aligned with the HLS spec, to start at 3 target-durations back from the live edge( [Section 6.3.3](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-10#section-6.3.3) of the spec). You can use [EXT-X-START](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-10#section-4.4.2.2) in the playlist to define a different start time. Unfortunately, `seek(0)` has a bug (#7975), and you and call `seek(1)` to go the beginning of the playlist.

You can find more information on #8218 and #7975.

Let me know if the if you need additional information.

**Comment by ptsekov** [comment]
@christosts, thank you very much for providing the pointers - its much appreciated. I tried to look for similar issues but could not get the right terms to find those issues.
