### ISSUE TITLE
Android TV ads focus issue

### ISSUE THREAD

**Issue by sowmiya1697** [google/ExoPlayer#10292]
### ExoPlayer Version

Older (unsupported)

### Devices that reproduce the issue

Android TV and Firestick Tv

### Reproducible in the demo app?

Not tested

### Reproduction steps

1.Use simple exoplayer with hls url for playing videos
2. Insert client side ads url which are skippable, in the media source
3. Use pre roll ads 
4. When we play the video the ads is played first and the focus is on the skip button 
5. When we click on the skip button the entire frame in which the ad is played comes to focus and its redirect to the browser. If there is no browser app toast is shown no app available.
6. The ads never skipped and it keep on playing

Note: We are using player the frame is not playing full screen but 70 percentage of TV screen (We have attached the video for same). This issue does not occur when the video is played full screen

### Expected result

1. When playing ads the skip button should be auto focused and click ok button from tv remote the ads will be skip

### Actual result

1. When playing ads the skip button should be auto focused but the selection of like yellow border line focused full player
2. Click ok button from tv remote it moved to web browser if available

### Media

Video is sent to the mail

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I'm not entirely sure how the reproduction steps work - do you trigger the OK button on your remote only once or multiple time? It looks like the first press on OK does not skip the ad and instead refocusses on the entire video. 

In any case, I believe this problem is outside of what we can control or fix. It's either an issue in your app UI or a problem in the overlay UI provided by IMA (which should be reported to them). ExoPlayer just takes the overlay view and passes it on to IMA to display the right buttons.
