### ISSUE TITLE
Screenshot function

### ISSUE THREAD

**Issue by chodison** [google/ExoPlayer#1033]
Hello guys. Is it possible to get playback screenshot from playing?

**Comment by Android4MediaPlayer** [comment]
+1

**Comment by NoGirlFriendException** [comment]
+1

**Comment by Android4MediaPlayer** [comment]
@ojw28

**Comment by luckcoolla** [comment]
+1

**Comment by sbaar** [comment]
Use a textureview instead of a surfaceview, then use getBitmap().

**Comment by luckcoolla** [comment]
@sbaar, textureview has helped. But probably is't not a big deal to add the screenshot function in the exo player, so developers will fill free to use SurfaceView or TextureView.

**Comment by ojw28** [comment]
It's actually quite complicated to add such a function. As @sbaar noted you can use `TextureView` and then use its `getBitmap()` method. From Android N there's also a new [`PixelCopy`](https://developer.android.com/reference/android/view/PixelCopy.html) API for copying the contents of a `Surface` into a `Bitmap`, which should work with `SurfaceView` too.

**Comment by ChernyshovYuriy** [comment]
Hi colleagues,

I understand that this is closed issue but in case someone could still answer.
Android functionality of screenshot (Power + Volume Down) does work on Clear content but does not on Widevine protected. Is this something dictates by the Widevine License (or DRM system) on the native layer?

Also, it is impossible to use TextureView with Widevine protected content, getting "MediaCodecRenderer$DecoderInitializationException".

So, in general, whether or not it is possible to do screenshot of the Widevine protected content?

**Comment by ojw28** [comment]
You can use TextureView if you force Widevine into L3 mode. This will only work if the content license doesn't require a secure output path, since L3 cannot provide one. It *might* also be possible to use TextureView with L1 if the license doesn't mandate a secure output path, but I'm not sure about that. You'd have to give it a try.

It's working as intended that video displayed using the secure output path is not captured in screenshots. See [here](https://developer.android.com/reference/android/view/Display.html#FLAG_SECURE) for some related documentation.
