### ISSUE TITLE
Live DASH starts playing minutes behind live edge

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#10342]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

* Pixel 3a (Android 12)
* Pixel 4a emulator (Android 12)
* Changhong GIU6770 (Android 9)
...

### Reproducible in the demo app?

Yes

### Reproduction steps

We've recently migrated from 2.11.8 to 2.17.1 and we've been seeing strange inaccuracies in connection with live offset. E.g. instead of 10 seconds behind live edge, some streams start playing more than 2 minutes behind live edge in the default configuration. We tried to set `MediaItem.LiveConfiguration.targetOffsetMs` to 1 hour and the stream started playing 1 hour and 2 minutes behind live edge. So it seems that ExoPlayer thinks the live edge is offset by 2 minutes. We've only noticed this issue to be happening with DASH, HLS behaved as expected.

The content starts at an expected position in ExoPlayer 2.12.3 and before, the inaccuracies occur starting 2.13.0. The content also starts at an expected position in ShakaPlayer.

Scenario 1: Default live offset
1. Play the attached live DASH stream without specifying live configuration
2. The playback starts far behind live edge (sometimes even more than 2 minutes)

Scenario 2: Live offset of 60 minutes
1. Play the attached live DASH stream with target live offset of `3_600_000`
2. The playback starts more than 60 minutes behind live edge

### Expected result

Scenario 1: Default live offset
- The playback should start about 10 seconds behind live edge

Scenario 2: Live offset of 60 minutes
- The playback should start 60 minutes behind live edge

### Actual result

Scenario 1: Default live offset
- The playback starts far behind live edge (sometimes even more than 2 minutes)

Scenario 2: Live offset of 60 minutes
- The playback starts far behind live edge minus 60 minutes (sometimes even more than 2 minutes, i.e. more than 62 minutes behind live edge)

### Media

Sent via email

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
The manifest contains a `UTCTiming` element with `"urn:mpeg:dash:utc:http-head:2014"`, which isn't supported by ExoPlayer at the moment. So the player falls back to the device clock as the time source.

Not sure if related, but the specified time source also produces a 404 when I try to access it manually. 

When using a phone with a properly synced clock, I still see the apparent 1-2min offset. However, ExoPlayer is reporting an offset (`player.getCurrentLiveOffset`) of around 10 seconds as expected. The reason is that the segment definition in the manifest doesn't quite add up. In the example manifest we have:
 - `availabilityStartTime="2022-06-13T05:56:28Z"`
 - a segment timeline with `timescale="90000"` defined as `<S t="15737185200" d="288000" r="4688"/>`
 This means the last segment ends at `2022-06-13T05:56:28Z + 15737185200/90000 + 4688*288000/90000` = `2022-06-15T10:40:47Z`
 - The manifest was supposedly published at `publishTime="2022-06-15T10:39:33Z"`, so the last available segment is 1 minute and 14 seconds in the future. 
 - This means when the player is playing 10 seconds behind "now", it plays 1 minute 24 seconds behind the last segment in this particular manifest snapshot. 

I can see two ways in which this can be solved, depending on what is more correct:
 1. Provide a working `UTCTiming` element that tells the player that the stream lives 1-2 minutes in the future to match the segment definition.
 2. Correct `availabilityStartTime` or the `t` element of the segment timeline to match the actual intended sample timestamps.

It's definitely possible to play the segments in the future, so I assume (2) is more correct. I'd also recomemnd to use a `UTCTiming` element that we support  to make sure that phones with an unsynced clock can play this stream. If you think `"urn:mpeg:dash:utc:http-head:2014"` is the source you'd like to use, I can also turn this into a feature request.

**Comment by okycelt** [comment]
Providing a `UTCTiming` element with a shifted value seems to have worked around the issue. Correcting the segment definitions would probably be the right way to go, but it seems that the "shift" is caused by a source issue which we are not in control of.

> If you think `urn:mpeg:dash:utc:http-head:2014` is the source you'd like to use, I can also turn this into a feature request.

It's not necessary for us. We've moved to a different scheme.

@tonihei, thank you
