### ISSUE TITLE
Black Screen Player.STATE_ENDED

### ISSUE THREAD

**Issue by AlexSkvor** [google/ExoPlayer#10344]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Any device

### Devices that do not reproduce the issue

Not found

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play video till the end
2. When video is at STATE_ENDED press Home or Recent Apps system button
3. Return to the app

### Expected result

When return to the app the last frame is shown
Just like when the video reaches STATE_ENDED the last frame is shown

### Actual result

Last frame is replaced with black screen

### Media

Not applicable

I created a minimal example here https://github.com/AlexSkvor/ExoplayerIssue
Also there is video illustrating problem https://github.com/AlexSkvor/ExoplayerIssue/blob/master/video_2022-06-16_10-44-15.mp4

P.s. This issue is duplicate for https://github.com/google/ExoPlayer/issues/6660 closed due to inactivity

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I think you need to release the player when going into background so that resources can properly be reclaimed by the system. When you come back to foreground, you can then restart playback with a new player instance. The black screen is likely an artifact of this as the system was automatically reclaiming some data. Only when you come back to the app quickly, the decoded frames are still there.

Please have a look at the [demo app](https://exoplayer.dev/demo-application.html) to see how this is handled there.
