### ISSUE TITLE
Hide player controls & menu items when the relevant player command is not available

### ISSUE THREAD

**Issue by inerognes** [google/ExoPlayer#10359]
[](url)I've just upgraded from `PlayerView` to `StyledPlayerView` in my app (since PlayerView is marked as deprecated), and I see there is a new settings/gear icon now available with the options to change speed and audio.  I was wondering if it's possible to hide this new settings in any way?

I am able to hide it by setting use_controller to false, but then everything else (like play, pause, progress) gets hidden as well. 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/39592250/174574969-f957e9ee-9496-4880-b8c4-36a5ee079056.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/39592250/174575107-4e6ce367-5a34-4171-ba31-d46e00e74f28.png">

**Comment by icbaker** [comment]
This is currently not possible.

We're a little wary of adding a toggle for every possible configuration preference to `StyledPlayerView`, because it can get pretty unwieldy and hard to reason about how they might all interact with each other.

However, I think there are some changes we can make here that might result in the same outcome of hiding the settings cog in some cases:
1. Update `StyledPlayerView` to hide the speed menu if `Player#COMMAND_SET_SPEED_AND_PITCH` is not available.
2. Update `StyledPlayerView` to hide the caption button and audio track selection menu item if `Player#COMMAND_SET_TRACK_SELECTION_PARAMETERS` is not available (the buttons are already [disarmed in this case](https://github.com/google/ExoPlayer/blob/r2.18.0/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L1124-L1128)).
3. If the settings menu would be empty (because audio and speed selection buttons are both hidden), hide the cog.

An optional variation/extension on (2) would be to also hide the button if there's no optional (i.e. not forced) text tracks or zero or one audio tracks. 

Another optional follow-up for (2): Get rid of `StyledPlayer(Control)View.setShowSubtitleButton`, because the same behaviour can be achieved via available commands.

You would then find that the settings cog only shows up when it's 'useful' - and if you want to ensure it's never shown, you can customise your `Player` instance to remove  `COMMAND_SET_SPEED_AND_PITCH` and `COMMAND_SET_TRACK_SELECTION_PARAMETERS` from the list of available commands.

Would that help your use-case?

If not, it might help to give a bit more context about why you're trying to hide the settings cog.

**Comment by inerognes** [comment]
Thanks for the detailed reply @icbaker! 

These suggestion would enhance the user experience for sure. But I am not sure if it would solve my particular use case: 

In our app, the users can upload and edit a video before posting it. We use `PlayerView` to show the preview of the video today. With `StyledPlayerView`, the user might change the speed in the viewer, and then expect the changes to be reflected when posting it, which will not be the case. So that is why I was wondering if it was possible to just simply hide the setting cog. I was picturing another property, e.g `use_settings` or something like that. 

Might be that my scenario is an edge case though, or that there are other solutions that I am not aware of?

**Comment by icbaker** [comment]
For that use-case, assuming (1) from my suggestion above is implemented, I think you can just configure the `Player` you pass to the UI to not allow speed changes, e.g. using `ForwardingPlayer`:

```
Player fixedSpeedPlayer =
    new ForwardingPlayer(player) {
      @Override
      public boolean isCommandAvailable(@Player.Command int command) {
        return command != Player.COMMAND_SET_SPEED_AND_PITCH
            && super.isCommandAvailable(command);
      }

      @Override
      public Commands getAvailableCommands() {
        return super.getAvailableCommands()
            .buildUpon()
            .remove(Player.COMMAND_SET_SPEED_AND_PITCH)
            .build();
      }

      @Override
      public void setPlaybackParameters(PlaybackParameters playbackParameters) {
        // Setting speed and pitch is disabled
      }

      @Override
      public void setPlaybackSpeed(float speed) {
        // Setting speed and pitch is disabled
      }
    };
```

And that would result in the speed control being hidden from the UI.

**Comment by inerognes** [comment]
@icbaker Aha I see! Then this change is more than welcome from my side :)

**Comment by aliap1376ir** [comment]
i do this very simple here is my method 
```
            Field field = playerView.getClass().getDeclaredField("controller");
            field.setAccessible(true);

            StyledPlayerControlView view = (StyledPlayerControlView) field.get(playerView);
            if (flag) {
                view.animate().alpha(1f).setDuration(300);
            } else {
                view.setAlpha(0);
            }

            view.findViewById(com.google.android.exoplayer2.ui.R.id.exo_settings).setVisibility(GONE);

```

**Comment by tonihei** [comment]
I think this should be fixed now by https://github.com/google/ExoPlayer/commit/641c3b1b22cc67133151b7af9905473485b0f51c.
