### ISSUE TITLE
a question when both device and player volume is 0

### ISSUE THREAD

**Issue by 1mean** [google/ExoPlayer#10362]
ExoPlayer volume contains device volume and player volume
```
val playerVolume  = mPlayer.volume
val deviceVolume  = mPlayer.deviceVolume
```
Normally, these two values are the same, And when I change the volume of the device, the volume of the player also changes
When i need to turn off the volume on the player, looks like this
```
mPlayer.volume = 0f
```
When I want to turn on the sound of the player, like this
```
mPlayer.volume = mPlayer.deviceVolume.toFloat()
```
Set the volume of the device to the player, If the volume of the device is also 0, The player still has no sound, no matter how we adjust the sound of the phone
So, I have to observe the volume buttons on my phone, to solve the problem when both device and player volume is set to 0
```
override fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean {

    when (keyCode) {
        KeyEvent.KEYCODE_VOLUME_UP -> {
            if (_mPlayer != null) {
                mPlayer.volume = mPlayer.deviceVolume.toFloat()
            }
        }
        KeyEvent.KEYCODE_VOLUME_DOWN -> {
            if (_mPlayer != null) {
                mPlayer.volume = mPlayer.deviceVolume.toFloat()
            }
        }
    }
    return super.onKeyDown(keyCode, event)
}
```
I wonder if there is a better way to solve this problem, just use ExoPLayer, To ensure that the volume of the device and the player is always the same, no matter how we modify it
Thanks!!!

**Comment by icbaker** [comment]
> ExoPlayer volume contains device volume and player volume
> 
> ```
> val playerVolume  = mPlayer.volume
> val deviceVolume  = mPlayer.deviceVolume
> ```
> 
> Normally, these two values are the same, And when I change the volume of the device, the volume of the player also changes

This statement surprises me. Not least because `Player.getVolume()` returns a float that's [documented](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getVolume()) to be between `0.0` and `1.0` inclusive, while `Player.getDeviceVolume()` returns an `int`, so it seems unlikely that they're always the same.

I did some testing locally and without calling `player.setVolume()`, I see `player.getVolume()` stay at `1.0f` while `player.getDeviceVolume()` changes as I use the device hardware volume keys, from `0` (mute) to `25` (full volume). Each press of a hardware volume key seems to increment or decrement the value of `player.getDeviceVolume()` by 1.

-----

> When I want to turn on the sound of the player, like this
> 
> ```
> mPlayer.volume = mPlayer.deviceVolume.toFloat()
> ```

This is only valid if `mPlayer.deviceVolume` is either `0` (mute) or `1` (1 increment above mute). In all other cases you're passing a value that's out of the permitted range for `Player.setVolume()`.

----

> I wonder if there is a better way to solve this problem, just use ExoPLayer, To ensure that the volume of the device and the player is always the same, no matter how we modify it

It's not clear to me what you mean by this since - as explained above - I don't believe that `Player.getVolume()` and `Player.getDeviceVolume()` should be returning 'the same' value in general, so I'm not sure why you'd be trying to keep them the same.

We might be able to help if you provide more information, or context about exactly what you're trying to achieve.

**Comment by 1mean** [comment]
Thank you very much for your reply，Thanks!!!  I need to fix my code
