### ISSUE TITLE
Currently Playing media URI with 2.18.0

### ISSUE THREAD

**Issue by ybonjour** [google/ExoPlayer#10373]
Hello,

I am trying to get the media URI of the currently playing media Item.
I used to store this in the `mediaUri` field of the MediaItem metadata and then retrieve it through:

```
player.currentMediaItem?.mediaMetadata?.mediaUri
```
This used to work without a problem.

But since version 2.18 this is not possible anymore as the mediaUri field has been moved to requestMetadata. So I adapted my code as follows:
```
player.currentMediaItem?.requestMetadata?.mediaUri
```
However the `mediaUri` field of `requestMetadata` is always null for me (even when there is currently a media item playing).
Also I am not able to add the mediaURI to the Metadata anymore as the `setMediaUri` method has been removed from MediaMetadata.Builder

What is the recommended way to get the uri of the currently playing media item with 2.18.0?

**Comment by icbaker** [comment]
Have you tried using [`mediaItem.localConfiguration.uri`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.LocalConfiguration.html#uri)?

That's the field the player reads to actually load the media.

**Comment by ybonjour** [comment]
Thanks. `mediaItem.localConfiguration.uri` works for me.

**Comment by Waldmann375** [comment]
When I set mediaitems to a MediaController, in the callback `onAddMediaItems()` of  `MediaSession.Callback`  Im getting `localConfiguration?.uri` returns null. 
`mediaMetadata?.mediaUri` worked fine back then and did provide a proper uri.

**Comment by icbaker** [comment]
@Waldmann375 Are you referring to `androidx.media3.session.MediaController`? Please file media3 issues & questions in the AndroidX Media GitHub project: https://github.com/androidx/media/issues

(It's going to be much clearer to discuss your question in a separate issue rather than try and explain it here, because there are differences when sending `MediaItem` data between the controller and the session)
