### ISSUE TITLE
Refresh manifest while the player is paused

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10379]
Hello,

Following a test on a dynamic manifest with the Exo 2.17.1 version, in the case of a pause we noticed that the Player continues to ask for the manifest at each "minimumUpdatePeriod" seconds even though it is in a pause state.
Is this normal? Is there a configuration to prevent the Player to ask for a manifest in this case?

BR,

**Comment by marcbaechinger** [comment]
This is an [expected behaviour for a manifest of type `dynamic` with the `minimumUpdatePeriod` attribute set](https://github.com/google/ExoPlayer/blob/release-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L861). In such a `dynamic` case the manifest signals that it may change. The player keeps loading to update its state such as the timeline and the current position within the available live window according to the manifest change. 

The configs are the `type` and `minimumUpdatePeriod` attributes of the MDP element as per DASH spec. I'm not an expert on the packaging/delivery side, but when looking at ExoPlayer DASH code I think the timing of loading the next manifest can be determined quite accurately when serving, given that the clocks are synchronized and the `minimumUpdatePeriod` attribute is set dynamically.

Programmatically, there is no API to prevent this I think. If the activity goes to background you should call `stop/release`, in case you are asking regarding such a background scenario.
