### ISSUE TITLE
MediaExtractor

### ISSUE THREAD

**Issue by hakobt** [google/ExoPlayer#10372]
Hi, thanks for great library
I am trying to develop a video editor application, and i am using Android's native MediaExtractor. By digging through ExoPlayer's version history i noticed that MediaExtractor was removed in favor of your custom-built extractors. I was wondering if there is anything wrong with Android's MediaExtractor, if only local files will be played?

**Comment by icbaker** [comment]
https://exoplayer.dev/pros-and-cons.html sums up the general trade-offs of using ExoPlayer vs Android's framework-level media components. Most of these are relevant to this question. It basically boils down to ExoPlayer giving an app more control over exactly what functionality is shipped, at the cost of APK size - because `MediaExtractor` behaviour might vary per API level (or per device) if there were bug fixes or improvements in later Android versions.
