### ISSUE TITLE
Latency in the live media as compare to Shaka Player

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10389]
Hi, 

I am checking a live content and can clearly see that in Shaka Player [demo app](https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;panel=HOME;build=uncompiled), player is around 5 seconds before the live edge but in ExoPlayer it is around 30 seconds. There is no `suggestedPresentationDelay` in the media.

And if i configure the LowLatency with target offset then it goes closer to the live edge. Question is why the player does not try to go as much as possible to the live edge like Shaka Player. 

ExoPlayer version: 2.17.1

I have sent the media over the email. Can you please help me to understand it ?

**Comment by rohitjoins** [comment]
You can reduce latency by using a custom load control as explained [here](https://stackoverflow.com/questions/69748951/how-to-get-low-latency-in-exoplayer-rtsp-live-streaming-on-android).

**Comment by tonihei** [comment]
Assuming you mean live latency, this is likely related to how your manifest is configured and which values the players read and use. In addition, the actual live latency may depend on any clock synchronization issues (if a `UTCTiming` element is present) and also on the actual buffering speed in case the player determines it can't get any closer to avoid rebuffers.

I'm probably able to give you a more concrete explanation of what's happening once I have access to the stream, but unfortunately the manifest sent via email only returns 403's for me. I tried using a VPN to the Czech Republic (best guess based on the TLD), but that didn't help either.

**Comment by GouravSna** [comment]
Hi @tonihei , 

I have sent the media again. It is tokenized URL hence it was unauthorized. Please use India or Israel VPN for the test.

-Thanks

**Comment by tonihei** [comment]
I tested the newly provided streams with VPN to both India and Israel, but I still only get 404s. If you want, you can also send a manifest snapshot instead, because I suspect the question can be answered with a single snapshot of the manifest.

**Comment by GouravSna** [comment]
I apologize that the media is short living. I have shared you the complete manifest with the latest media/license as well.

-Thanks

**Comment by tonihei** [comment]
Thanks for the manifest. As you already pointed out yourself, it doesn't have the `suggestedPresentationDelay` value defined and thus ExoPlayer falls back to a default value of 30 seconds.  ExoPlayer has to choose some value and because many live streams can't support low latency values, 30 seconds is a sensible default that should work for most streams.

That leaves you with multiple ways to fix it:
 1. Update the manifest to include a `suggestedPresentationDelay` or a `ServiceDescription` with a `Latency` `target` value.
 2. Define which fallback ExoPlayer should use if both values are missing by setting `DashMediaSource.Factory.setFallbackTargetLiveOffsetMs`
 3. Override the target live offset (even if defined by the manifest) by setting `MediaItem.LiveConfiguration.Buiider.setTargetOffsetMs` for specific `MediaItem` instances, or use `DefaultMediaSourceFactory.setLiveTargetOffsetMs` to set an override for all `MediaItems`.

**Comment by GouravSna** [comment]
Thanks a lot @tonihei
