### ISSUE TITLE
how to understand AdaptationCheckpoint by reading unit test AdaptiveTrackSelectionTest#updateSelectedTrack_withAdaptationCheckpoints_usesOnlyAllocatedBandwidth

### ISSUE THREAD

**Issue by yuzhidi** [google/ExoPlayer#10383]
Hi, 
    I try to understand AdaptationCheckpoint by reading unit test. [AdaptiveTrackSelectionTest#updateSelectedTrack_withAdaptationCheckpoints_usesOnlyAllocatedBandwidth](https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/test/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelectionTest.java#L477)

It seems if there is multi-tracks, somtime for a track, getBitrateEstimate() is ok to upgrade quality. But if all tracks  upgrade quality, the BitrateEstimate maybe not enough, so we can use AdaptationCheckpoint to limit each track bitrate range. 

Or if want to quality change at specific time range

Thanks for anyone who let me know how to use AdaptationCheckpoint

**Comment by tonihei** [comment]
You already provided the correct intention behind `AdaptationCheckpoints` : allow multiple track groups to adapt to the bitrate at the same time. Because they need to share the available *total bandwidth*, each track group only has an *allocated bandwidth* to use. The sum of all *allocated bandwidths* should generally be the *total bandwidth*.

`AdaptiveTrackSelection.Factory` calculates the mapping from  *total bandwidth* to *allocated bandwidth* in advance to decide how the allocation to track groups is done for every possible value of *total bandwidth*. 

As we can't provide a mapping for every possible value of *total bandwidth*, we use a series of checkpoints (where we define the mapping) and assume a linear interpolation in-between. For example, if you set checkpoints as 
(`total=1000`, `allocated=500`) and (`total=2000`, `allocated=700`), then this track group would assume it has an *allocated bandwidth* of `600` if the *total bandwidth* is `1500`.  If the *total bandwidth* is less than the first checkpoint's value or more than the last checkpoint's value, we extrapolate the values from the first two or last two checkpoints. 

If you like, you can set the adaptation checkpoints to whatever allocation you want to use. By default, `AdaptiveTrackSelection.Factory` tries to allocate the quality increases fairly across all track groups (see [this comment](https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L770) for details).

**Comment by yuzhidi** [comment]
thx
