### ISSUE TITLE
How to play automatically after executing seekTo

### ISSUE THREAD

**Issue by LeifDong** [google/ExoPlayer#10399]
Hi there
My Application used MediaSessionCompat and MediaSessionConnector like the UAMP. the exoPlayer will response and seekTo next song when I send a skipToNext action. But only when it is playing, it will be automatically played after the skipToNext action. It just update metadata and don't automatcially play when it's not playing. I try to add "player.playWhenReady = true" in the TimelineQueueNavigator's function like this:
```kotlin
private inner class UampQueueNavigator(
        mediaSession: MediaSessionCompat
    ) : TimelineQueueNavigator(mediaSession) {
        override fun getMediaDescription(player: Player, windowIndex: Int): MediaDescriptionCompat {
            if (windowIndex < currentPlaylistItems.size) {
                return currentPlaylistItems[windowIndex].description
            }
            return MediaDescriptionCompat.Builder().build()
        }

        override fun onSkipToPrevious(player: Player) {
            player.playWhenReady = true
            super.onSkipToPrevious(player)
        }

        override fun onSkipToQueueItem(player: Player, id: Long) {
            player.playWhenReady = true
            super.onSkipToQueueItem(player, id)
        }

        override fun onSkipToNext(player: Player) {
            player.playWhenReady = true
            super.onSkipToNext(player)
        }
    }
```
It will be automatcially played even it's not playing. But, it will not be automatcially played after onPlayerError. That is to say, even if I add **"player.playWhenReady = true"**, It's not work. Does anyone know how to autoplay after the seekTo is executed? 
Thanks!!!

**Comment by LeifDong** [comment]
I found that the playerError affects playback.So I change my code to this:
``` kotlin
private inner class UampQueueNavigator(
        mediaSession: MediaSessionCompat
    ) : TimelineQueueNavigator(mediaSession) {
        override fun getMediaDescription(player: Player, windowIndex: Int): MediaDescriptionCompat {
            if (windowIndex < currentPlaylistItems.size) {
                return currentPlaylistItems[windowIndex].description
            }
            return MediaDescriptionCompat.Builder().build()
        }

        override fun onSkipToPrevious(player: Player) {
            super.onSkipToPrevious(player)
            if (player.playerError != null) {
                player.prepare()
            }
            player.playWhenReady = true
        }

        override fun onSkipToQueueItem(player: Player, id: Long) {
            super.onSkipToQueueItem(player, id)
            if (player.playerError != null) {
                player.prepare()
            }
            player.playWhenReady = true
        }

        override fun onSkipToNext(player: Player) {
            super.onSkipToNext(player)
            if (player.playerError != null) {
                player.prepare()
            }
            player.playWhenReady = true
        }
    }
```
It's worked. I wonder if this is the right way. Hope to get your help, thanks.

**Comment by marcbaechinger** [comment]
It does not look right to me to set `playWhenReady` to true when a user skips to the next item. A user probably wants to skip trough the playlist when it is paused, and then start playback when they found the item they want to play.

For the `PlaybackError` you can listen to the `Player.Listener.onPlaybackError` to get notified when a playback error occurs. In this case you can correct the problem at the moment when the errors occur. There is probably a reason for this error like a media item that can not load or play for some reasons, so you may want to remove this media item from the playlist or similar in such a case. Then prepare to be ready for further playback. Without that, your user probably will see a similar error again when hitting the problematic media item again.

In any case, the check should probably be `player.playbackState == Player.STATE_IDLE` instead of the checking for the `playerError`  because you want to prepare when in this state. But again, I think this should be checked in `play` rather than in `onSkipToNext/Previous/QueueItem`. These callbacks are for navigation only.

**Comment by LeifDong** [comment]
thanks for your suggestion
