### ISSUE TITLE
seekTo restarts playback in LibopusAudioTrackRenderer

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#1039]
The ExoPlayer.seekTo function does not seem to work when playing an audio only file. It always ends up starting from the beginning of the audio file. The following cases have been tried:
1) Seek before Start - Calling seekTo, and immediately setting playWhenReady to true.
2) Seek after Start - Calling seekTo during an ongoing playback.

In both the cases, the playback restarts from the beginning.

One sample audio file has been transcoded using ffmpeg 2.8.3. Another audio file is from the chromium source (https://chromium.googlesource.com/chromium/src/+/master/media/test/data/bear-opus.webm). All sources are at current HEAD. The NDK version is r10e.

**Comment by vigneshvg** [comment]
The file in the chromium source does not have Cues (seek index) and thus it is un-seekable (it is possible that the opus demo app isn't handling un-seekable files correctly - but i'll leave that out).

FFmpeg does not write out Cues on audio only encodes. There are two workarounds here:
1) Use the -dash 1 parameter in FFmpeg. This will ensure that Cues are written out (even for audio only encodes), but has some other implications (like when a Cluster is created, etc.)
2) Encode the file using FFmpeg and then use sample_muxer from libwebm [1] with -cues_on_audio_track 1 to force Cues to be written on audio tracks.

Once you have Cues in your file, seeking will work as expected. Also note that this behavior has nothing to do with LibopusAudioTrackRenderer. This behavior is because of the way the Extractor handles Seeking. Please make sure you are using ExtractorSampleSource and not FrameworkSampleSource (because the latter only looks at Cues on video track [2]).

[1] https://chromium.googlesource.com/webm/libwebm
[2] http://androidxref.com/6.0.0_r1/xref/frameworks/av/media/libstagefright/matroska/MatroskaExtractor.cpp#455

**Comment by Brahmasmi** [comment]
Thank you Vignesh for the elaborate explanation.

As a background, I had assumed that the seek index would be present on the transcoded file. And if it was missing there, it might be on the chromium sample. To be honest, my initial assumption for the seek failing was that the order in which the player was performing seek was wrong. It took me some time to wrap my head around this, and hence this post and #1040 . Turns out that the player can perform seek any time.

I will try the second libwebm based suggestion and report back, since it seems there are some other implications with the first ffmpeg one.

**Comment by Brahmasmi** [comment]
Acknowledging that the libwebm based suggestion works and the new audio file can be seeked. Thank you.

On an unrelated note, the file containing the seek index is actually smaller than the original file without the seek index, as transcoded by ffmpeg. By any chance, would you happen to know what might be causing this?

**Comment by vigneshvg** [comment]
I can't think of anything off the top of my head. Is there a significant difference? If possible, please share the file and i can take a look.

**Comment by Brahmasmi** [comment]
Using this https://chromium.googlesource.com/chromium/src/+/master/media/test/data/bear-opus.webm, the file sizes before and after the sample_muxer are 25717 and 25551 bytes respectively. In another local file, the before and after sizes are 286027 and 285171 bytes respectively.

I presume the differences are not significant (around 0.5%). However, it seems interesting considering that the file size goes down after adding additional data.

sample_muxer steps
```
mkdir libwebm-test
cd libwebm-test
wget https://github.com/webmproject/libwebm/archive/libwebm-1.0.0.27.tar.gz
tar xvf libwebm-1.0.0.27.tar.gz
cd libwebm-libwebm-1.0.0.27/
mkdir temp-build
cd temp-build
cmake ../ -DCMAKE_BUILD_TYPE=release
make sample_muxer
./sample_muxer -i <path/to/bear-opus.webm> -o <path/to/bear-opus-cued.webm> -output_cues 1 -cues_on_audio_track 1
ls -al <path/to>
```
If the make barfs due to c++11, please add this to the cmake line
```
-DCMAKE_CXX_FLAGS:STRING="-std=c++11"
```
