### ISSUE TITLE
Testing DefaultBandwidthMeter.initialBitrateEstimates  

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#10415]
I've done changes to initial bitrate setting (**initialBitrateEstimates**), and I'd like to do some testing in order to verify that this value has an effect on the algorithm that makes the player choose a lower or higher resolution.

For example we got for a set of countries next initial bitrates depending on network type: 

Default values in (bits per second)

   | DE (Germany) | AT (Austria)
   WIFI | **5_400_000** | **5_400_000**
   2G | **1_700_000** | **1_700_000**
   3G | **1_000_000** | **2_300_000**
   4G | **1_400_000** | **3_400_000**
   5G_NSA | **5_200_000** | **7_500_000**
   5G_SA | **1_700_000** | **1_700_000**

So if I decide, let's say to reduce WIFI | **5_400_000** | **5_400_000** to WIFI | **3_400_000** | **3_400_000** is there any 
practical way that will help me to test how the player bitrate estimation behaviour changes? 

My question is if you have any idea how the fluctuation of this value could be tested. Since I could not see a big difference if this value is increased or decreased.

**Comment by christosts** [comment]
The initial estimates should affect the first playback after an app cold start. The DefaultBandwidthMeter uses a static singleton instance so that the bandwidth measurements are re-used. Only after a cold start the initial estimate will be used.

Decreasing the initial estimates means that for the first few downloads the player might select a lower bitrate video (and audio, if you're using adaptive audio too). If you keep the remaining parameters of the DefaultBandwidthMeter unchanged, the initial estimate is in place until ~2-3MB of data are downloaded. That could be just 1-2 segments per video/audio (the duration of these segments depends on how you create the adaptive content). After that, the measured bandwidth estimate will be used. Note that the bitrate selection is subject to bitrates/resolutions available on your adaptive content. Roughly speaking, the player will select a bitrate that is approximately no more than 75% of the bandwidth estimate. If your content does not have any formats over 3Mbps, then nothing will change for example.

In a controlled environment, you can simply test that the player starts at a lower bitrate/resolution. Such changes however are better evaluated in larger populations, e.g. having telemetry in place and collecting analytics from devices, possibly running an A/B test too. If you decrease the initial estimate for WIFI for the specific countries, then you I'd expect to see that for the first playback after app cold start
- playback starts at lower bitrate/resolution
- join time decreases, that is playback starts slightly faster. Some additional links for this: documentation on [using the PlaybackStatsListener](https://exoplayer.dev/analytics.html#event-processing-with-playbackstatslistener), and [PlaybackStats.html.getMeanJoinTimeMs()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#getMeanJoinTimeMs())

Let me know if that covers your question.

**Comment by javaboboApp** [comment]
Thanks @christosts  for the answer is clear to me.
What I try to archive is a decrease in the VST(video start time) using lower resolution when video starts.

I have done some test and I can see that that player selects the lowest resolution when I reduce the values. 

I have also noticed that this happens during a small period of time.

I guess it is related with **DefaultLoadControl.bufferForPlaybackMs**  so player load 2500 ms before starting playing and during this time DefaultBandwidthMeter calculates real bitrate (it realises that real britate is bigger) so the track selector selects a better resolution. 

So I was wondering if there is a way to increase this (2-3 Mb) threshold. So we will allow player play with lower resolution in order to start quicker. Another idea is to reduce   **bufferForPlaybackMs**.

**Comment by christosts** [comment]
There are different parameters you can tune on the player, but I believe what you are trying to achieve is functionally best suited to go into `AdaptiveTrackSelection`. At the moment, the player's algorithm tries to download the best possible resolution without risking a rebuffering. You want to tune it to start playback sooner by lowering the downloaded content's bitrate. 

By changing the DefaultBandwidthMeter values, you are feeding the default AdaptiveTrackSelection algorithm with lower estimates and consequently the algorithm chooses lower bitrates/resolution. As soon as enough data are downloaded, the DefaultBandwidthMeter will report the measured estimate (the 2-3MB threshold I mentioned was referring to an implementation detail inside the meter). By further decreasing `DefaultLoadControl.bufferForPlaybackMs`, you will let the player start playback sooner, at the risk of a rebuffer though. You'll need to test such a change too and measure the gains over the rebuffering trade-offs.

Imo, it'd be best to move part of your logic `AdaptiveTrackSelection`.  Please see #6630 and likely [this comment](https://github.com/google/ExoPlayer/issues/6630#issuecomment-1023007702) how to achieve this. In `AdaptiveTrackSelection` you can directly decide which bitrate to download regardless of the bandwidth meter estimates. This way you can control what to download even after the meter has a measured estimate. You can still experiment with DefaultLoadControl.bufferForPlaybackMs as I described above.
