### ISSUE TITLE
MKV Video with VC1 Codec not supported

### ISSUE THREAD

**Issue by alizahid1996** [google/ExoPlayer#10435]
I have downloaded an mkv file online. The file plays correctly but it shows a black screen. Audio from the video is playing but the video not showing, instead, a black screen is displayed.

I have also tried to play the same video on other players like Vlc Media Player and Mx Player, they play it perfectly with video and audio.

I have tested this on many devices like (Xiaomi Redmi Note 9 Pro, Oppo A3s, Samsung Galaxy A32) but the issue is the same.

Although exoPlayer supports mkv video files after checking the metadata of the video, I found that the Video Codec of this mkv file is VC-1 and not H264. All the videos that ExoPlayer was playing were H264 codec videos but this file was VC-1.

I want to know if this codec is supported in ExoPlayer?

If yes, then how can I play this file?

Also, can I download a codec externally and embedded it with ExoPlayer to make support this codec?

ExoPlayer Version Used:
2.17.0

Screenshot of Video MetaData:
![video metadata](https://user-images.githubusercontent.com/50871184/178953079-39553fed-fee4-459b-88ff-0de42b1fc234.png)

**Comment by marcbaechinger** [comment]
By default ExoPlayer is using the hardware decoders of the Android platform. The formats supported by these can be found [here](https://developer.android.com/guide/topics/media/media-formats?authuser=1#core). Like you already noticed the VC-1 is not supported.

You could in theory use a software codec for decoding but this is not trivial because you would need to have a specific renderer for this. There is an [extension for ffmpeg](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg), but this only has a renderer for audio.

So you would need to do your own video renderer for ffmpeg which is non-trivial and quite some work.

**Comment by alizahid1996** [comment]
So VC-1 codec is not supported by ExoPlayer, can I download the codec externally and somehow attach or integrate the codec with ExoPlayer? Because I have seen it in Playit, they show a dialog for downloading the codec, and the video plays

**Comment by marcbaechinger** [comment]
That's not possible with ExoPlayer I'm afraid.

**Comment by alizahid1996** [comment]
> That's not possible with ExoPlayer I'm afraid.

Okay then, thanks for the information.
