### ISSUE TITLE
set max duration to exo_progress

### ISSUE THREAD

**Issue by Usman-Click** [google/ExoPlayer#10457]
Hi,

I just want to ask if there is anyway I can set max duration to exo_progress (defaultTimeBar) programmatically (like to overide its setMax value) because there are some videos that I want to stop before they reach their Duration 

Thanks

**Comment by ojw28** [comment]
If you want to clip a piece of media so that it stops at a certain position that's earlier than its duration, then you can use clipping as documented [here](https://exoplayer.dev/media-items.html#clipping-a-media-stream). Does that answer your question?

**Comment by Usman-Click** [comment]
Well... to the straight point No,

What I want to do is set a max duration to exo_progress

I tried
exo_progress.setDuration(duration) but it's not working 

What am I missing ?
How do I suppose to do it ?

**Comment by ojw28** [comment]
Sorry, I don't really understand what you're trying to do, or why. Perhaps you could describe your use case, rather than the specific way you're trying to solve it that isn't working. If your use case is to not allow the piece of media to play past a certain duration, then my link above is the correct way of doing that.

**Comment by Usman-Click** [comment]
Okay

I tried the link above it works but the time timeBar is showing the full duration 

What should I do now 🙃

**Comment by ojw28** [comment]
I tried this and the time bar was updated to show the clipped duration. It's also easy to demonstrate that this works correctly using our [demo app](https://exoplayer.dev/demo-application.html). With the app installed, you can have it play a video clip with the following ADB command:

```
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://html5demos.com/assets/dizzy.mp4
```

You can clip it, which applies clipping just like in the link I've referenced above, with the following ADB command:

```
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://html5demos.com/assets/dizzy.mp4 --el clip_end_position_ms 10000
```

You will see that the duration shown in the UI and used for the timebar is the clipped duration (i.e., 10 seconds).

If you'd like us to investigate whatever you're seeing in more detail, please provide a small patch to our demo app that performs clipping and does _not_ adjust the time bar duration, so that we can reproduce what you're seeing.

**Comment by Usman-Click** [comment]
Thank you, it works
