### ISSUE TITLE
Why amazon port of ExoPlayer fixes are not adopted?

### ISSUE THREAD

**Issue by baiqindotfubotv** [google/ExoPlayer#10454]
Amazon has an official port of ExoPlayer: https://github.com/amzn/exoplayer-amazon-port. They fixed some playback issues on amazon specific devices (Like this one: https://github.com/amzn/exoplayer-amazon-port/commit/dfe65fdd636adfbc61aae31bbdf8a20758d56ec1). Considering amazon fire tv devices is one major target where ExoPlayer runs, so why fixes like these were not merged into main ExoPlayer codebase?

**Comment by ojw28** [comment]
If Amazon had sent that change as a pull request with a signed CLA as per our [contributing guidelines](https://github.com/google/ExoPlayer/blob/release-v2/CONTRIBUTING.md), then I think we'd have happily merged it. So I think your question is one that you should pose to Amazon (i.e., why do they submit this type of change into their own fork rather than sending it as a pull request to the original project?).

We have previously merged fixes that are equivalent to some of the ones that have been made in the Amazon fork. We are happy to do this where it makes sense, and would also consider any pull requests that do this. We may not merge fixes that are highly invasive and/or are more for enabling FireOS specific features, but the change you reference is not an example of this!

**Comment by ojw28** [comment]
I made a quick skim through the current set of commits that Amazon maintain in their fork (on top of 2.18.0). I think most of them do fall into the "invasive and/or FireOS specific feature" category. The specific commit you reference is an exception to this; I'll take a look at whether we can get something equivalent merged into the main project.

**Comment by ojw28** [comment]
I merged a change that should be equivalent to https://github.com/amzn/exoplayer-amazon-port/commit/dfe65fdd636adfbc61aae31bbdf8a20758d56ec1. I think we can close this.
