### ISSUE TITLE
KEYCODE_DPAD_CENTER not working on ExoPlayer controller

### ISSUE THREAD

**Issue by DeWolfRobin** [google/ExoPlayer#10466]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

 * Android TVs

### Devices that do not reproduce the issue

 * Touch based devices

### Reproducible in the demo app?

Not tested

### Required:
 * Normal ExoPlayer setup
 * Android TV VM
 * following code:
```
@SuppressLint("RestrictedApi")
    override fun dispatchKeyEvent(event: KeyEvent?): Boolean {
        if (event?.action == KeyEvent.ACTION_DOWN) {
            when (event.keyCode) {
                KeyEvent.KEYCODE_DPAD_CENTER -> {
                    if (viewBinding.playerView.isControllerFullyVisible) {
                        return viewBinding.playerView.dispatchKeyEvent(event) || super.dispatchKeyEvent(event)
                    } else {
                        viewBinding.playerView.showController()
                    }

                    return true
                }
            }
        }

        return false
    }
```

### To reproduce:
 * Open the app on the Android TV VM
 * Start the video on ExoPlayer
 * Open the TV controller ("Extended Controls")
 * Pressing the Dpad center should first show the controller
 * Navigate to any button, for example the play button
 * Press Dpad center again
### Result:
When the controller is active, no events from the KeyCode.KEYCODE_DPAD_CENTER are accepted.

### Expected result

When pressing the Dpad center when the controller is active, it should press whichever button is currently focussed.

### Actual result

When the controller is active, no events from the KeyCode.KEYCODE_DPAD_CENTER are accepted.

### Media

N/A => can create a video if nessesary

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by DeWolfRobin** [comment]
Apparently, KeyEvent.KEYCODE_DPAD_CENTER only works on KeyEvent.ACTION_UP, this resolved my issue, but is this still a bug? as other keyevents work fine, such as KeyEvent.KEYCODE_DPAD_UP

**Comment by tonihei** [comment]
ExoPlayer's `PlayerView` and `StylesPlayerView` handle these actions automatically without any app code needed. When you tap DPAD center first, the controls are shown and any further tap with send the event for the currently selected button. I verified this in the demo app and everything is working fine. 

This indicates the problem is somewhere in your custom app code and I would advise you to just start with the simplest integration (no custom code), adding new handling step-by-step to find out where your code is not working as expected. We can't help with generic Android key handling questions I'm afraid. So if you are stuck, you may want to ask on sites like StackOverflow or similar.
