### ISSUE TITLE
Player reaches the ENDED state during a MPEG-DASH live streaming.

### ISSUE THREAD

**Issue by jeronimomunoz** [google/ExoPlayer#10479]
### ExoPlayer Version

2.14.2

### Devices that reproduce the issue

No device dependent

### Reproducible in the demo app?

Not tested

### Reproduction steps

Reproductions steps:

1. Start the live streaming playback
2. Keep playing the live streaming until the player reaches the ENDED state. Something it takes a few minutes and something a few hours. 

### Expected result

The media plays successfully and the playback never ends because the media represents a live streaming channel.

### Actual result

Playback ends after a few minutes/hours. What I see is that the player reaches the ENDED state. After a further investigation, I realized that the issue is caused by an MPD update.

Here how the MPD looks before the issue:

```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:scte35="urn:scte:scte35:2013:xml" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" id="1527" type="dynamic" publishTime="2022-07-27T08:09:04" minimumUpdatePeriod="PT2S" availabilityStartTime="2021-03-23T08:40:21Z" minBufferTime="PT30S" suggestedPresentationDelay="PT25.000S" timeShiftBufferDepth="PT58.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT42419722.556S" id="21177256">
  ...
  </Period>
</MPD>
```

Here how the MPD looks after the issue:

```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:scte35="urn:scte:scte35:2013:xml" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" id="1554" type="dynamic" publishTime="2022-07-27T08:09:15" minimumUpdatePeriod="PT2S" availabilityStartTime="2021-03-20T07:28:38Z" minBufferTime="PT30S" suggestedPresentationDelay="PT25.000S" timeShiftBufferDepth="PT58.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT42683219.256S" id="21230901">
  ...
  </Period>
</MPD>
```
As you can notice, the period id "21177256" is no longer available and a new period "21230901" is available after the MPD update, also the MPG@availabilityStartTime is updated. I think this period transition is causing the player to reach the ENDED state but I don' know why because the new MPD looks valid. While the Period@id is kept through the MPD updates the media plays normally, but if the current Period@id is removed and a new one is added, then the playback ends, as detailed in the above examples.

### Media

I cannot provide the media URL as the media is encrypted and a license is required. However, I can provide the manifest files if as the problem occurs when the MPD file is updated (current period is removed and a new period is added)

[before_issue.txt](https://github.com/google/ExoPlayer/files/9198581/before_issue.txt)

[after_issue.txt](https://github.com/google/ExoPlayer/files/9198584/after_issue.txt)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I think this MPD update is not really spec-conformant because periods are meant to be continuous from one another. So usually you'd get Period A in one manifest, at some point Period B is added in addition (so that both periods are listed) and then Period A is removed once it's no longer relevant.

In particular, see [this section](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#timing-mpd-updates) mentioning that `availabilityStartTime` is not allowed to change and [this section](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#timing-mpd-updates-remove-content) saying that periods are not allowed to be removed when they are still within the available time range.

ExoPlayer tries to cope with this situation by creating a new period and updating the other values as well. And then it attempts to find a suitable new period to play. Because it doesn't know that the new period is after the previous one (since it didn't exist at any point before), it concludes that it can't find a suitable new period and ends playback instead.

**Comment by jeronimomunoz** [comment]
Thanks a lot for this information @tonihei. I was checking an old version of the DASH-IF IOP document. Now it is clear, I'll transmit this information to the packager provider in order to fix the MPD generation.
