### ISSUE TITLE
Some type of subtitles are not visible

### ISSUE THREAD

**Issue by teletcl** [google/ExoPlayer#10489]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

TCL AndroidTV 8 (tested on some apps that based on ExoPlayer)

### Devices that do not reproduce the issue

KODI application

### Reproducible in the demo app?

Not tested

### Reproduction steps

On some videos subtitle are not displaying.
If play that file in KODI or Vimu, subtitles are visible.
Maybe because subtitles in this video are in color?

### Expected result

subtitles should be visible

### Actual result

subtitles are not displaying

### Media

[subtitles_not_visible._20211104_222254.zip](https://github.com/google/ExoPlayer/files/9236535/subtitles_not_visible._20211104_222254.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
I'm able to reproduce the issue in the demo app at 2.18.1. I played the attached TS file, enabled the Polish text track (DVB subtitles) and didn't see any subtitles on screen.

However I then played the same file in VLC on my computer, and enabled the same subtitle track, and also saw no subtitles.

Given two independent players both show no subtitles, I think that points to this being a media issue rather than a problem with ExoPlayer.

If you believe this is incorrect, the onus is on you to demonstrate the file you've provided is valid and describe in more detail what ExoPlayer is failing to parse. This likely requires you to dig into the bytestream of the file and refer to the MPEG TS and DVB specs.

**Comment by teletcl** [comment]
VLC doesn't but e.g. KODI (both Android and Windows) or Media Player Classic Home Cinema ( https://github.com/clsid2/mpc-hc ) shows subtitles in this video sample.
![subtitles](https://user-images.githubusercontent.com/66688147/182589897-57bf5a1b-0ce8-4a10-bb60-86351ae6aa1e.jpg)

**Comment by teletcl** [comment]
I've found that also Vimu Media Player ( https://play.google.com/store/apps/details?id=net.gtvbox.videoplayer ) shows subtitles in this sample video.
Maybe VLC it's not good enough?
