### ISSUE TITLE
Instruct Exoplayer to start download/playback with first segment of a m3u8 manifest not the last one

### ISSUE THREAD

**Issue by Damax72** [google/ExoPlayer#10481]
Upfront, I googled a lot and could not find any answer. Maybe I have gooled with wrong string, but Itried various search strings nothing. We use Exoplayer as general player, Browser+Android, works pretty well, thanks to all devs! In some scenarios with bad internet, playback is stuttering. While tracing in background we have recognized, that Exoplayer - when having downloaded the manifest m3u8, it always starts to play the last segment of the manifest and not the first. Like I said, we have googled a lot and read many docs, but we could not find any setup option to tell Exoplayer to start with the first segment and not with the last. Most likely this questions sounds stupid to you, but simply don´t know how to change this behaviour. 

The reason behind is, when playing the last segment it is alwys at the end and the new segment requires new m3u8 download. When it would start with the first segment, and there is 5 ts segments announced, we can reduce m3u8 download 50% and the player can pre-load the remaining ts segements.

To make it more visible, once m3u8 is downloaded, player downloads always last segment of the manifest 65883122.ts instead the first, 65883118.ts

I have two concrete questions:

1. What setting do we have to change to instruct player to start download/playback with first segment of a m3u8 manifest?

2. How do we tell the player to download the new manifest, e.g. when the second to last segment is downloaded, to minimize manifest download traffic?

![grafik](https://user-images.githubusercontent.com/110097485/181283887-f9e748dc-1678-4ea1-adce-41850b0c09be.png)

**Comment by tonihei** [comment]
> What setting do we have to change to instruct player to start download/playback with first segment of a m3u8 manifest?

There are 4 inputs deciding where to start playback (in decreasing order of priority):
 - The value of #EXT-X-START in the playlist (if available).
 - App-provided overrides set in `MediaItem.LiveConfiguration.targetOffsetMs` (if set)
 - Playlist-provided targets set in `HOLD-BACK` of `#EXT-X-SERVER-CONTROL` (if available)
 - A default value of 3 times `#EXT-X-TARGETDURATION`.

Based on that, I'd assume your playlist tries to start 3 * 10 seconds = 30 seconds away from the live edge. The live edge is also defined by the current device time relative to the `#EXT-X-PROGRAM-DATE-TIME` value, so if either of these values is off, it would explain why you start with the last segment and not the third one.

If you suspect something is not working correctly, you'd need to share a link to the live stream here or via email to dev.exoplayer@gmail.com with "Issue #10481" in the subject. Otherwise, we can't really investigate further.

> How do we tell the player to download the new manifest, e.g. when the second to last segment is downloaded, to minimize manifest download traffic?

This is handled internally by `HlsPlaylistTracker` and you shouldn't usually customize this behavior because the right thing happens automatically.

**Comment by Damax72** [comment]
Thank you very much Tonihei, I will forward this to our team. Maybe I will comeback with "questions"

**Comment by tonihei** [comment]
Closing for now as no new questions came up. Please reopen if needed or file a new issue, thanks!
