### ISSUE TITLE
Black Screen when Player in STATE_END and activity back to home and resume.

### ISSUE THREAD

**Issue by visla-yewang** [google/ExoPlayer#10501]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Samsung Galaxy P20, Google Nexus 4

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. when video is loaded, play the video to end.(make sure the player status is STATE_END)
2. in end status, back the app to Home Screen.
3. back to app from Home Screen.

### Expected result

the last frame of the video should be kept instead of showing a black screen

### Actual result

black screen is shown at this moment.

### Media

no media needed.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
I performed the repro steps in the demo app at version 2.18.1 on a Pixel 5 running Android 13, and observed that when bringing the app back to the foreground a black screen is shown briefly, and then the final frame of the video is shown. I suspect this delay is related to re-preparing the player and decoders (which are released when the demo app is put in the background).

Given this doesn't reproduce in the demo app, this sounds like an issue with your app's integration with ExoPlayer, rather than an inherent problem with the library. I recommend you take a look at how the demo app is implemented: https://github.com/google/ExoPlayer/tree/release-v2/demos/main
