### ISSUE TITLE
is there any difference between addMediasource and setMediasource method as in case of setMediaSource method we always need to call player.prepare method? will it affect start time of video?

### ISSUE THREAD

**Issue by kshailes** [google/ExoPlayer#10529]

**Comment by rohitjoins** [comment]
@kshailes Based on the documentation for these methods:

- `setMediaSource` : Clears the playlist and adds the specified MediaSource
- `addMediaSource` : Adds a media source to the end of the playlist. 

So that is basically the difference between these methods. Both these methods have multiple overridden methods to reset position or start playing from a particular index in the playlist.

`player.prepare()` is called to move the player out of idle state and start loading media, which for `addMediaSource` is not always required if the player is already playing a playlist and a media source gets added to the list.

**Comment by kshailes** [comment]
thanks @rohitjoins
