### ISSUE TITLE
Bug with video playback in Android API 33

### ISSUE THREAD

**Issue by cogier** [google/ExoPlayer#10539]
I'm using ExoPlayer inside of a Flutter app. When I run my app on a device with the latest Android API (33 at this time) I'm having an issue with the video playback. The first time I navigate to a view and stream a video, it works correctly for ~30sec, then the video zooms in to display just the top left corner.
This problem is NOT present just one version back in Android API 32. Is there an important difference between the APIs that I'm missing?

I was not able to reproduce this bug in the demo app.

I've encountered this issue with multiple different streams, but this is the test stream I'm using.
https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8

**Comment by marcbaechinger** [comment]
Difficult to tell with the information available. I actually do not think this is related to ExoPlayer as it can't be reproduced ion the demo app. According to your report it also doesn't seem to be a media related problem, as it happens with different streams. We haven't heard similar reports from users with API 33 devices.

So, I would actually look into what event is causing a change after 30 seconds. I don't think this is something triggered by the player, but rather by the app or a library that you are using (like Flutter). You can add an [`EventLogger`](https://exoplayer.dev/debug-logging.html) to the player to see whether the player emits some events at the moment this happens.  That would be an information that would make it actionable for us. 

With the current information it is hard to tell and I would claim it's coming from something else than ExoPlayer. Please narrow down the issue to something that gives evidence that the problem is actually coming from the ExoPlayer library and not the app or Flutter.

**Comment by cogier** [comment]
I tested this on an actual Android device and wasn't able to reproduce the issue. It appears that this my just be an issue with my emulator. Still not sure what's causing it.
