### ISSUE TITLE
Support for media served over partial content (HTTP 206)

### ISSUE THREAD

**Issue by PaulCombal** [google/ExoPlayer#10537]
### Use case description

I want to serve my content over HTTP 206 partial content. Because the audio content I want to stream can be fairly long (audio books, hour long music sets..), it is impractical to serve the content over HTTP 200 since it means the client needs to download the whole file contents before playing (high data usage, not the best performance-wise).
It would be a great feature to have the audio/video content to be partially downloaded and buffered while previous segments are being played.

Ranged requests are described in RFC 9110: https://www.rfc-editor.org/rfc/rfc9110.html#name-range-requests

### Proposed solution

Use ranged requests when the given URI for the media returns code 206 or 416 instead of throwing an error (`Loading finished before preparation is complete.`).

New optional parameters might be needed for initial range size and desired range size.

### Alternatives considered

None. 

Implementing a custom solution playing sound from a buffer. [Food for thought.](https://stackoverflow.com/a/34759311/3001271)

**Comment by icbaker** [comment]
ExoPlayer's 3 HTTP `DataSource` implementations (`DefaultHttpDataSource`, `CronetDataSource` and `OkHttpDataSource`) all support making range requests and handling 206 and 416 HTTP response codes.

Please provide more information about what further enhancement you're proposing here.

**Comment by PaulCombal** [comment]
If I'm not mistaken, in the following example:

```java
// Build the media item.
MediaItem mediaItem = MediaItem.fromUri(videoUri);
// Set the media item to be played.
player.setMediaItem(mediaItem);
// Prepare the player.
player.prepare();
// Start the playback.
player.play();
```

if the `videoURI` is an address that returns partial content, this example will not work. I thought this would be a neat feature to have a default behavior in this situation.

I know there are lots of ways to customize Exoplayer, only many packages use it as a "backend", and do not offer the same customization capabilities.

**Comment by icbaker** [comment]
I would expect that to work without any customization - would you be able to provide a link to some content where it doesn't work, so we can investigate what's going on?

**Comment by PaulCombal** [comment]
I made a Proof Of Concept repository with React Native here: https://github.com/PaulCombal/react-native-test-exoplayer

It is essentially trying to play audio from this URL: https://youtubue-server.fly.dev/test 

You can add any extension to "test" if desired, even though content-type is included in the response header. By the way, Chrome can't play the content out of the box but Firefox can, it's standard mp3. Adding .mp3 to the URL doesn't change anything.

![image](https://user-images.githubusercontent.com/5382590/185703777-d62d396a-985c-447c-85b6-3fa819da20c7.png)

No sound whatsoever, player state stuck at `1` (`Player.STATE_BUFFERING` I presume)

EDIT: I forgot to mention that this example works fine with HTTP 200 responses, you can try it yourself with [this demo url](https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj).

From my server log:
![image](https://user-images.githubusercontent.com/5382590/185704446-9337724e-46e8-44d2-9034-6107d58fa8a7.png)

Meaning the player did one GET request on the resource without range headers (makes sense), and the server responded with a HTTP 206 including the content-range & cie in the header as well as the 632 first bytes of the resource, but has not received a subsequent request for more data. Exoplayer seems to be hanging when it should request more of the data, leaving me thinking this is not implemented.

Bonus: `curl https://youtubue-server.fly.dev/test -v`

![image](https://user-images.githubusercontent.com/5382590/185705370-2832590a-64be-4522-bf20-828b057b6f1a.png)

Please let me know if I can do anything to help, or make this feature request considered.

**Comment by icbaker** [comment]
Sorry it's taken me a while to look into this. I agree that the URL you've provided doesn't play successfully.

I was looking a bit further into it and the URL started completely timing out - would you be able to see if the server is still up and healthy?

It's **really** helpful having a repro example like this, and again sorry for not getting round to using it until just now.

**Comment by icbaker** [comment]
I've done a bit more digging through ExoPlayer's HTTP-handling code and concluded roughly:
* ExoPlayer supports partial-content responses only in response to explicit range requests. This is useful for e.g. seeking halfway along a 10GB file, because we can ask the server to only send us the second 5GB.
* In the repro case here, we're trying to play a file from the beginning, and we don't make a range request - but the server responds with partial content regardless.
  * It's unclear to me if this server is operating within the recommendations of RFC 9110, which says in section 15.3.7 (emphasis mine):
     > The 206 (Partial Content) status code indicates that the server is successfully fulfilling a **range request** for the target resource by transferring one or more parts of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110.html#selected.representation).

     And higher up, in section 14.2, a 'range request' is defined as a request with a `Range` header:
     >  The "Range" header field on a GET request modifies the method semantics to request transfer of only one or more subranges of the selected representation data ([Section 8.1](https://www.rfc-editor.org/rfc/rfc9110.html#representation.data)), rather than the entire [selected representation](https://www.rfc-editor.org/rfc/rfc9110.html#selected.representation).

It makes sense to me that a server must reply to a non-range HTTP request with the whole resource, because range requests are an explicitly optional part of HTTP, and therefore both server and client must be prepared for the other not to support the feature (from top of section 14):
> Range requests are an OPTIONAL feature of HTTP, designed so that recipients not implementing this feature (or not supporting it for the target resource) can respond as if it is a normal GET request without impacting interoperability.

So ExoPlayer makes a plain HTTP request, expecting to receive the entire content in response. The server only provides 632 bytes. ExoPlayer thinks the entire file is 632 bytes long, and ends up throwing the error you see.

I understand there's enough info in the `Content-Range` response header for ExoPlayer to know how long the file really is. This information is not currently used because ExoPlayer generally keeps a single HTTP request open to load the whole file (until e.g. a seek causes reading to need to happen at a new location). It's theoretically possible for ExoPlayer to support this (invalid?) HTTP response, but before we look into that I'd like to understand why this is important.

From your original report you say:
> Because the audio content I want to stream can be fairly long (audio books, hour long music sets..), it is impractical to serve the content over HTTP 200 since it means the client needs to download the whole file contents before playing (high data usage, not the best performance-wise).

This isn't a correct statement. Playback will start as soon as the player has buffered enough content (by default this is controlled by [`DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html#DEFAULT_BUFFER_FOR_PLAYBACK_MS)). The HTTP connection will be kept open while the rest of the data is loaded. In fact, this is arguably more efficient than making lots of 632-byte HTTP requests because each additional request has round-trip overhead which is avoided by using a single connection for the whole playback.

Given that, I'm inclined to close this as I believe the HTTP server is misbehaving here, and I'm not sure what the advantage of supporting this misbehaviour in ExoPlayer would be.

**Comment by PaulCombal** [comment]
> Sorry it's taken me a while to look into this. I agree that the URL you've provided doesn't play successfully.

It does for me. If this doesn't work out of the box in Chrome, it's normal, [there is a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1352179). Try opening it in VLC or Firefox and on my side it works just fine.

> This isn't a correct statement. Playback will start as soon as the player has buffered enough content

You are right, I was thinking of the data usage only; even if the  playback can start after the first milliseconds are loaded, the data will still be fetched. My apologies if this was worded badly. 

As an example, if I want to listen to an audiobook, I might want to load the data 10MB by 10MB (for example) to avoid using too much bandwith, instead of downloading the whole file through a 200, regardless of the how much time it takes until playback starts.
In the example, only ~630 bytes are served because this is the size of the audio's metadata, of course subsequent requests would have a bigger range.


I understand your statement. In this case, what do you think would be a clean solution to streaming audio by chunks using ExoPlayer? 
Would having an option to enforce a range request since the first request, or to further customize headers provide more flexibility?

**Comment by icbaker** [comment]
> if I want to listen to an audiobook, I might want to load the data 10MB by 10MB (for example) to avoid using too much bandwith, instead of downloading the whole file through a 200

ExoPlayer will not necessarily load the whole audiobook in this example. It will generally try and buffer a certain distance ahead of the playback position. If the audiobook is 2hr long and 200MB, it will not load all 200MB if you only play the first 5 minutes of the book. The exact buffering behaviour depends on the `LoadControl` instance used when instantiating the player. Just because an HTTP server responds with a 200 response doesn't obligate the client to consume the entire request.

> what do you think would be a clean solution to streaming audio by chunks using ExoPlayer?

If you don't like ExoPlayer's default buffering behaviour, I would suggest you modify that behaviour by using a custom `LoadControl` (probably an instance of `DefaultLoadControl`).

**Comment by PaulCombal** [comment]
This is probably the best answer. Thank you for your time and contribution to open source ❤️
Would some light about `LoadControl`'s usage and use cases in the documentation be a good addition?

Feel free to close the issue if nothing needs to be added.

**Comment by icbaker** [comment]
`LoadControl` is briefly mentioned here as controlling buffering behaviour: https://exoplayer.dev/customization.html

There's more details in the [`LoadControl`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/LoadControl.html) and [`DefaultLoadControl`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html) javadoc pages.
