### ISSUE TITLE
`Player.Listener.onEvents` not called when crossing track boundaries

### ISSUE THREAD

**Issue by mattrob33** [google/ExoPlayer#10544]
I am constructing an `.m3u8` playlist of mp3 files server-side to be played by my ExoPlayer client. The below code plays my `.m3u8` file successfully, however, I also need to know when the player crosses from one mp3 to the next, and I am not seeing _any_ events in my `Player.Listener`, even in `onEvents()`.

This is my Kotlin code

```kotlin
val hlsUri = Uri.parse(..)
val dataSourceFactory = DefaultHttpDataSource.Factory()
val hlsDataSourceFactory = DefaultHlsDataSourceFactory(dataSourceFactory)
val mediaSourceFactory = HlsMediaSource.Factory(hlsDataSourceFactory)
val mediaSource = mediaSourceFactory.createMediaSource(MediaItem.fromUri(hlsUri))
player.setMediaSource(mediaSource)
player.prepare()
player.playWhenReady = true
```

and my .m3u8 file
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:9
#EXT-X-DISCONTINUITY
#EXTINF:4
https://.....mp3
#EXTINF:9
https://.....mp3
#EXTINF:5
https://.....mp3
#EXT-X-ENDLIST
```

Shouldn't I be seeing events in my `Player.Listener` when the player crosses from one mp3 to the next in the `HlsMediaSource`? I don't see anything in the documentation about this and can't decipher intended behavior from the code. Is this a bug, or is there a different way to listen for these events?

**Comment by marcbaechinger** [comment]
Yes, this is working as intended.

Such a `m3u8` playlist makes each of the MP3 file a segment of the HLS stream that is created with it. There are no events that are emitted because these segments are wrapped by a single period. 

You can add each of these MP3 as a single progressive media item. In this case you get an event `onMediaItemTransition` that tells you when the playback transitions from one to the next media item.

```
player.setMediaItems(
   ImmutableList.of(
     MediaItem.fromUri("https://.....mp3"),
     MediaItem.fromUri("https://.....mp3"),
     MediaItem.fromUri("https://.....mp3")
   )
);
```
