### ISSUE TITLE
How to reduce the buffer time when using SeekTo(positionMs) method

### ISSUE THREAD

**Issue by 1mean** [google/ExoPlayer#10587]
1. play a video from the beginning. it only takes 70-110 ms from state_buffering to state_ready. The video plays after a short buffer
2. after add `seekTo(positionMs)` method. from buffering to ready. sometimes it takes 300ms. sometimes 700ms. even 900ms. Its a long buffer time before the video starts to play

code like this
```
mPlayer.addMediaItem(mediaItem)
mPlayer.seekTo(playPos) //play a video with last position
mPlayer.playWhenReady = true
mPlayer.prepare()
```
play a video with last position in a activity. Can I make the buffer time shorter? I don't know how to use the `SeekTo()` method properly

**Thank you very much**

**Comment by icbaker** [comment]
It's likely that the seek is slow because we have to decode (and throw away) every frame from the previous keyframe until the seek point - before we can start playback. This is an unavoidable side-effect of the way most video compression algorithms work - every frame can only be decoded if all previous frames have also been decoded, back to the previous keyframe.

So some questions:

1. How frequent are the keyframes in your content?
2. How much do you care about the accuracy of your seek?

If you have frequent keyframes and/or you're not worried about seek accuracy you can tell the player to start playing from the nearest keyframe by using [`ExoPlayer.Builder.setSeekParameters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.Builder.html#setSeekParameters(com.google.android.exoplayer2.SeekParameters)).

If that's unsatisfactory, then there's not much you can do beyond re-encoding your content to increase the frequency of keyframes (which will result in a larger output file).

**Comment by 1mean** [comment]
Thank you very much for your reply.
