### ISSUE TITLE
The flv url can't play but potplayer can play

### ISSUE THREAD

**Issue by FongMi** [google/ExoPlayer#10592]
Exo version 2.18.1

Test Url
https://upos-hz-mirrorakam.akamaized.net/upgcxcode/32/70/18667032/18667032-1-64.flv?e=ig8euxZM2rNcNbRBhwdVhwdlhWUVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1662555298&gen=playurlv2&os=akam&oi=3544964488&trid=85b2924bf09c4d19bb6de0786384b330u&mid=0&platform=pc&upsig=5df6fac32d38afc6ce2afdee7f169de5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1662555298~hmac=1c1773fc5f7653496107c0e2c2e6d0f180d0c8d0ae658282059863135e351cfa&bvc=vod&nettype=0&orderid=0,1&agrr=0&bw=150542&logo=80000000

Error
![image](https://user-images.githubusercontent.com/3471963/188861883-4815a13a-9400-4b47-a9e3-17c6f06fb1cf.png)

I think this "data" legnth is zero so can't play
![image](https://user-images.githubusercontent.com/3471963/188862119-0d8e11a6-eeb2-45a0-b55f-3bb233439f74.png)

**Comment by thucngv** [comment]
> s

can't access the media url
<img width="629" alt="image" src="https://user-images.githubusercontent.com/23202870/189062722-1684a9f3-fcb2-422b-8613-6fdb975ab457.png">

**Comment by FongMi** [comment]
Sorry, here is new link

https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/32/70/18667032/18667032-1-64.flv?e=ig8euxZM2rNcNbRBhwdVhwdlhWUVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1662629798&gen=playurlv2&os=cosovbv&oi=3544964488&trid=c92c2de6c729466a87845f1130a2b06eu&mid=0&platform=pc&upsig=dacd3d75b6a3fe45df569b7d6ba7e85d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&agrr=1&bw=150542&logo=80000000

**Comment by icbaker** [comment]
> Sorry, here is new link

I get a 403 from this one.

> I think this "data" legnth is zero so can't play

Walking back up the stack trace a bit, the real problem is that `audioSpecificConfig` is empty here, which implies the packet is a 'sequence header' but has no content beyond the type `byte`. This likely implies the file is malformed. Some players are more permissive than others when playing malformed files - showing that a file plays with another player doesn't demonstrate the file is compliant with the relevant spec.

https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/flv/AudioTagPayloadReader.java#L101-L105

**Comment by icbaker** [comment]
> Sorry, here is new link

I get a 403 from this one.

> I think this "data" legnth is zero so can't play

Walking back up the stack trace a bit, the real problem is that `audioSpecificConfig` here, which implies the packet is a 'sequence header' but has no content beyond the type `byte`. This likely implies the file is malformed. Some players are more permissive than others when playing malformed files - showing that a file plays with another player doesn't demonstrate the file is compliant with the relevant spec.

https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/flv/AudioTagPayloadReader.java#L101-L105

**Comment by FongMi** [comment]
Here is new link
https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/32/70/18667032/18667032-1-64.flv?e=ig8euxZM2rNcNbRBhwdVhwdlhWUVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1662661714&gen=playurlv2&os=cosovbv&oi=3544964488&trid=57afd057fd9240faa8b6a0fce9c4cfe5u&mid=0&platform=pc&upsig=a973d95f47d3f40b10ec8e7465f88441&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&agrr=1&bw=150542&logo=80000000

**Comment by FongMi** [comment]
Is there any way to bypass the error packet ?
I have clone source and ready to edit

**Comment by icbaker** [comment]
The latest link also returns 403 for me.

> Is there any way to bypass the error packet ?
> I have clone source and ready to edit

I haven't tested this, but you could try returning `false` from inside the `if` block I quoted above if the packet seems empty, something like:

```java
if (packetType == AAC_PACKET_TYPE_SEQUENCE_HEADER && !hasOutputFormat) {
  if (data.bytesLeft() == 0) {
    return false;
  }
  // Parse the sequence header. 
  byte[] audioSpecificConfig = new byte[data.bytesLeft()]; 
  data.readBytes(audioSpecificConfig, 0, audioSpecificConfig.length); 
```

**Comment by FongMi** [comment]
Ok, I will try it, thanks.
