### ISSUE TITLE
Set desired bitrate.

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1059]
Dear developers,

Is there any way to set ExoPlayer process only desired bitrate caping?

**Comment by ojw28** [comment]
In what context? DASH, SmoothStreaming or HLS? Please provide more detail about your use case. Thanks.

**Comment by ChernyshovYuriy** [comment]
Preferably, for all supported formats. I asked this question in perspective of use-case when it is necessary to keep Player on one of the lowest bitrate (or provide a range between bitrates) for the low level connections, like LTE.

**Comment by ojw28** [comment]
Is the purpose of keeping to the lowest bitrates to avoid exhausting a limited data plan, or because higher bitrates will result in re-buffering due to limited bandwidth?

If the question is about the former, you can implement your own DashTrackSelector and SmoothStreamingTrackSelector instances to limit the streams that get selected in DASH and SmoothStreaming respectively. For HLS, you can specify a variantIndices parameter to the HlsChunkSource to restrict which variants are selected.

If the question is about the latter, ExoPlayer dynamically selects a stream based on the measured available bandwidth, and so this shouldn't be a concern.

**Comment by ojw28** [comment]
Note that you can also manually select a specific fixed format using `ExoPlayer.selectTrack` for DASH and SmoothStreaming (we're working on providing this functionality for HLS also).

**Comment by ChernyshovYuriy** [comment]
Thank you for suggestion with custom TrackSelectors. I was on the same opinion :-)
There are several reasons for this feature ... We have couple applications that are long time in market and use different versions on Player. Based on this experience, we have necessity to provide ability to Player to use specific bitrate (bitrates range) only. Unfortunately, quite often Player (types of Player that we use) stays on high variant while connection is pure.

It would be a good feature though to control bitrate with some convenient way in ExoPLayer.
