### ISSUE TITLE
Provide DRM Key Content Directly?

### ISSUE THREAD

**Issue by praxder** [google/ExoPlayer#10601]
Is there a way to play DRM protected content with ExoPlayer, given that you have manually fetched the body of the DRM key? 

As far as I can tell, ExoPlayer only supports passing the license key url, and ExoPlayer then fetches the key. Is there a way to manually input the key data, given that it's been manually fetched?

Thanks.

**Comment by icbaker** [comment]
ExoPlayer uses a [`MediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html) instance to handle DRM license key request and responses. The default implementation is [`HttpMediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.html), which makes HTTP requests to the license URI. You can provide your own implementation of `MediaDrmCallback` and handle the license request however you like. You may be able to use [`LocalMediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/LocalMediaDrmCallback.html), otherwise you're probably best off implementing the interface directly.

You can provide your custom `MediaDrmCallback` to the player by building a custom `DrmSessionManager` instance with it: https://exoplayer.dev/drm.html#using-a-custom-drmsessionmanager
