### ISSUE TITLE
 Internal track renderer error

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1062]
Hi,

I'm getting this error while playing unencrypted video in android kitkat 4.2.

```
E/ExoPlayerImplInternal( 2098): Internal track renderer error.
E/ExoPlayerImplInternal( 2098): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:455)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/ExoPlayerImplInternal( 2098):         at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2098):         at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2098):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 2098): Caused by: com.google.android.exoplayer.BehindLiveWindowException
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.dash.DashChunkSource.getChunkOperation(DashChunkSource.java:363)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.chunk.ChunkSampleSource.updateLoadControl(ChunkSampleSource.java:544)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.chunk.ChunkSampleSource.onLoadCompleted(ChunkSampleSource.java:462)
E/ExoPlayerImplInternal( 2098):         at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:231)
E/ExoPlayerImplInternal( 2098):         at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2098):         ... 3 more
I/Lukupplayer( 2098): maybeReportPlayerState()
```

I've mailed you the original source url in gmail to olly.exoplayer@gmail.com.

Regards,
Randeep

**Comment by ojw28** [comment]
In the manifest, `timeShiftBufferDepth` defines the window of media that the server makes available to be only 10 seconds long. `DashRendererBuilder` in the demo app tries to start playback 30 seconds behind live (defined by `LIVE_EDGE_LATENCY_MS`). Since only 10 seconds of media are advertised as being available in the manifest, this is 20 seconds behind the oldest media that's advertised as being available. Hence playback fails within `BehindLiveWindowException`.

A 10 second media window isn't really sufficient for acceptable streaming performance for mobile devices. Unless low latency is a critical requirement, it's generally much better for a mobile devices to be playing about ~30 seconds behind live. This allows the client to maintain 30 seconds of media in a local buffer, which then allows it to seamlessly survive temporary networking issues lasting less than this duration.

It also appears that the server actually has a much larger window of available media than the 10 seconds advertised in the manifest (if I hardcode the window to be two minutes rather than parsing the value from the manifest, then playback works fine). So I think the fix is to reconfigure the manifest and/or server.

**Comment by randeeppr** [comment]
@ojw28 

I'll change the segment length to 30s. Also I'll change the max-age header to 30s.

Regards,
Randeep

**Comment by randeeppr** [comment]
@ojw28 

Its working now. Thanks a lot.

Regards,
Randeep

**Comment by ishantsagar** [comment]
@randeeppr I am facing a similar issue with Live HLS videos, could you please guide me as how did you managed to overcome the issue, I don't have any control on the HLS manifest file.

**Comment by randeeppr** [comment]
@ishantsagar what I remember is it worked when I changed max age.

**Comment by ishantsagar** [comment]
@randeeppr Thanks for the response, I suppose this "max age" is something that I need to configure in the manifest file? Also I want to know how can I access the manifest file, as right now I only have a HLS url.

**Comment by randeeppr** [comment]
@ishantsagar No. Its not to be configure in the manifest file but with the manifest file. It is the http header of the manifest file. In the origin server of the stream there will be provision to do it.
