### ISSUE TITLE
What is goldfish decoder?

### ISSUE THREAD

**Issue by lmartin** [google/ExoPlayer#10622]
When testing on Android emulators from Android Studio, I notice that I have some videos that are playing jerky when running on Android 11 and later. When running on Android 9 or 10, the same videos are playing smooth.

Regarding video decoder used by Exoplayer, I notice that there are some differences when playing the same video:
- on Android 9 or 10 : OMX.google.h264.decoder
- on Android 11 : OMX.android.goldfish.h264.decoder
- on Android 12/13 : c2.goldfish.h264.decoder

So my question is what is the goldfish h264 decoder? Is it only available on virtual device or also on real device?

**Comment by rohitjoins** [comment]
@lmartin Goldfish decoder is a `MediaCodec` which is part of the emulator system change. It is android software decoder which runs on emulator. I think the difference is because of change in package name used for different android OS version. 

If you want to report an issue please provide more information using our issue template found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
