### ISSUE TITLE
How can I use Italic type in Subtitle?

### ISSUE THREAD

**Issue by halilozel1903** [google/ExoPlayer#10633]
Helloooo,

I want to change Subtitle settings but I don't find `ITALIC` type.

```kotlin
CaptionStyleCompat(
                    Color.RED,
                    Color.GREEN,
                    Color.TRANSPARENT,
                    CaptionStyleCompat.EDGE_TYPE_DROP_SHADOW,
                    ContextCompat.getColor(context, R.color.transparentShadowColor),
                    Typeface.DEFAULT_BOLD
                )
```

There is no parameter to use directly in `Typeface`.

You can help me?

**Comment by icbaker** [comment]
`CaptionStyleCompat` is simply a wrapper around the framework [`CaptionStyle`](https://developer.android.com/reference/android/view/accessibility/CaptioningManager.CaptionStyle), which doesn't support making the content italic.

In order to make your subtitles italicized you either need to:
1. Use source media with italic subtitles. Many of the formats the ExoPlayer supports allow the subtitle author to mark certain subtitles with italics, e.g. WebVTT, TTML, etc.
2. Mutate the `Cue` objects before they're shown on the screen, as described in [this comment](https://github.com/google/ExoPlayer/issues/7243#issuecomment-614651130). You'll want to add a [`StyleSpan`](https://developer.android.com/reference/android/text/style/StyleSpan) to `Cue.text` - see more info about styling text with spans here: https://developer.android.com/develop/ui/views/text-and-emoji/spans

**Comment by halilozel1903** [comment]
I see. Thanks for your comments.
