### ISSUE TITLE
multiple subtitles with same language code

### ISSUE THREAD

**Issue by onikaii** [google/ExoPlayer#10631]
I have a .mkv video, this video has multiple subtitles, 7 in total.

getTrackFormat(i).language -> getTrackFormat(i).label
 en -> English
 pt -> Portuguese(Brazil)
 es -> Spanish(Latin_America)
 es -> Spanish(Spain)
 fr -> French
 it -> Italian
 ru ->Russian 

 as you can see the language code  is repeated in Spanish(Latin_America) and Spanish(Spain), they have the same value "es".

The problem comes when I try to select the subtitle, if I select " es -> Spanish(Spain)" exoplayer understands that I try to select " es -> Spanish(Latin_America)" because they have the same value.

```
    trackSelector.setParameters(
    trackSelector.buildUponParameters()
        .setRendererDisabled(C.TRACK_TYPE_VIDEO, false)
        .setSelectUndeterminedTextLanguage(true)
        .setPreferredTextLanguage(language]) //  es -> Spanish(Latin_America)  |  es -> Spanish(Spain)  same language code
```

Is there any other way to select a subtitle than by its language code?

**Comment by icbaker** [comment]
If the tracks have an ID you can use that to distinguish between them and set an override using [`TrackSelectionParameters.Builder.setOverrideForType](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelectionParameters.Builder.html#setOverrideForType(com.google.android.exoplayer2.trackselection.TrackSelectionOverride)).

Otherwise it sounds like you're asking the library to distinguish between tracks that have identical metadata but different content. That sounds hard/impossible (if you can't tell the tracks apart from the metadata, how can the library?) - can you just fix the media to be correct?

**Comment by onikaii** [comment]
Thanks, using "setOverrideForType" worked.
