### ISSUE TITLE
TimeOut by setting the setAdPreloadTimeoutMs method.

### ISSUE THREAD

**Issue by pineapplevine** [google/ExoPlayer#10651]
Hello.  
I don't understand the behavior when TimeOut is set with the setAdPreloadTimeoutMs method of the ImaAdsLoader.Builder class.

- When the parameter (adPreloadTimeoutMs) specified in the setAdPreloadTimeoutMs method is a small value (100 or 200).

  When the network is unstable preloadTimeoutMs judgment is executed just before ad playback in rare cases (no ads play).  
  However there is no "Ad preloading timed out" log, so preload timeout does not seem to have occurred.

- When the parameter (adPreloadTimeoutMs) specified in the setAdPreloadTimeoutMs method is set to 20000.

  "Ad preloading timed out" was logged when I destabilized the network.  
  (The TimeOut log was output even when the parameter adPreloadTimeoutMs was set to the default of 10000).

I don't understand the behavior of TimeOut by setting the setAdPreloadTimeoutMs method.   
What kind of settings does TimeOut occur?
please tell me.
  
Code:
```java
    private AdsLoader getClientSideAdsLoader(MediaItem.AdsConfiguration adsConfiguration) {
        // The ads loader is reused for multiple playbacks, so that ad playback can resume.
        if (clientSideAdsLoader == null) {
            ImaAdsLoader.Builder builder = new ImaAdsLoader.Builder(this);
            builder.setAdPreloadTimeoutMs(20000);   // <- here

            clientSideAdsLoader = builder.build();
        }
        clientSideAdsLoader.setPlayer(player);
        return clientSideAdsLoader;
    }
```
  

Spec:
- Android Studio Chipmunk | 2021.2.1
- Pixel5a Andriod11
- ExoPlayer Version r2.17.1  
- IMA Android SDK Version 3.26.0

Sample app:  
- ExoPlayer r2.17.1  
- https://github.com/google/ExoPlayer/tree/r2.17.  

Ad tag:  
Ad URL used in the sample app (see below)
- https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

- https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=

**Comment by tonihei** [comment]
The timeout starts when ExoPlayer triggers an ad load and times out if the IMA SDK doesn't reply with the required ad information. This is just a safeguard for cases where the SDK misbehaves (because it should just send us an error in all cases where the ad load fails), and i's there to ensure that playback doesn't get stuck due a misbehaving SDK. 

If you set this timeout to a very low value (100/200 in your example above), you risk running into this timeout too often because the SDK as almost no time to reply with the required ad data. So the recommendation is to leave it at a higher value (we chose 10 seconds by default) as it's just the last resort fallback to avoid stuck playbacks.

**Comment by grapevine23** [comment]
Thanks for explaining.
