### ISSUE TITLE
MediaCodecVideoDecoderException

### ISSUE THREAD

**Issue by farkasadam** [google/ExoPlayer#10652]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Example: 
* OnePlus 7T running Android 11

### Devices that do not reproduce the issue

Example:
* Samsung S20+ running Android 12

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play the asset
2. Player stops with error code 4003

(On most of the devices we don't have this issue. We have 3 environments, on test we have this device-specific issue very rarely. On preprod and prod it occurs always on the problematic devices) 

### Expected result

Media should be played.

### Actual result

Errorcode 4003

Stacktrace:
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=663977, null, null, video/avc, avc1.42C01E, 668000, null, [640, 360, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc.secure
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2830)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 

### Media

We'll send one via email

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by pradeepvernekarzee** [comment]
We are also facing a similar issue. Any updates?

**Comment by farkasadam** [comment]
@icbaker can you please update us? When I created the ticket I sent an email about the next steps how we can provide you a sample asset

**Comment by icbaker** [comment]
I looked in the bug report provided over email, I don't see the stack trace you posted in the original comment. Please could you take a look and check the BR covers the time that the error was thrown?

I'm afraid we're not able to provide the information requested for a reproducible stream - if you want us to try and reproduce the problem you would need to make the stream globally available. That said, we may be able to help just based on a BR that includes the error in question.

**Comment by farkasadam** [comment]
Please reopen this ticket, I sent an email about this topic

**Comment by icbaker** [comment]
The logcat contains the stack trace at timestamp `2022-11-22 10:09:38.234` but the bugreport was captured at `2022-11-21-17-20-07` - i.e. 17 hours earlier (assuming both those are in the same timezone). I can't see any mention of `ExoPlaybackException` in the bugreport. The bugreport should show the same logs that logcat captures for a period just before the bugreport is triggered. We ask for a bugreport rather than just logcat snippets because it sometimes contains additional clues about the problem.

Does this reproduce on any of the DRM-protected assets in our [demo app](https://exoplayer.dev/demo-application.html)?

**Comment by farkasadam** [comment]
I sent you another bugreport from UAT.
They tried with the demo app as well, and It is reproducible with DRM protected assets

**Comment by farkasadam** [comment]
@icbaker do you have any update on this?

**Comment by icbaker** [comment]
@rrfrias PTAL - I see some errors logged from OEMCrypto in `bugreport-OnePlus7T_EEA-RKQ1.201022.002-2022-12-21-16-08-34.zip`:

```
12-21 16:09:54.931 media   948  1007 I WVCdm   : [cdm_engine.cpp(314):AddKey] Adding key: session_id = sid9
12-21 16:09:55.023 10330 10922 10922 D ExoEventLogger: drmKeysLoaded [eventTime=0.77, mediaPos=0.00, window=0, period=0]
12-21 16:09:55.029  1046  1373  2676 E OMXNodeInstance: getConfig(0xe5900014:qcom.decoder.avc.secure, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
12-21 16:09:55.031 media   948  1007 E QCOM-OEMCrypto: Error at trusted_app_decrypt_cenc : 2563
12-21 16:09:55.031 media   948  1007 E QCOM-OEMCrypto: TA Result : 1 OEMCryptoResult : 25
12-21 16:09:55.032 media   948  1007 I QCOM-OEMCrypto: -----------------------------------------------------------------
12-21 16:09:55.032 media   948  1007 I QCOM-OEMCrypto: Error stack trace[7] for TA version 1:78
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 cipher_set_data_input : 314
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 decrypt_blocks : 378
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 decrypt_ctr_block_offset : 875
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 decrypt_ctr : 919
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 decrypt_subsample : 1359
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 process_subsample : 1398
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: 	 i_widevine_session_decrypt_cenc : 1729
12-21 16:09:55.032 media   948  1007 I QCOM-OEMCrypto: -----------------------------------------------------------------
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: Error at decrypt_data : 1874
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: Error at _oecc48 : 2320
12-21 16:09:55.032 media   948  1007 E QCOM-OEMCrypto: Error at _oecc105 : 3118
12-21 16:09:55.032 media   948  1007 E WVCdm   : [crypto_session.cpp(1521):Decrypt] OEMCrypto_DecryptCENC failed: status = 25
12-21 16:09:55.032 media   948  1007 E WVCdm   : Decrypt error in session sid9 during a sample with protected data: 1
12-21 16:09:55.032 10330 10922 21511 W MediaCodec: Log queueSecureInputBuffer error: -2147483648
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer: Video codec error
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:   android.media.MediaCodec$CodecException: Error 0x80000000
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2830)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:233)
12-21 16:09:55.033 10330 10922 21489 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Leva01** [comment]
@icbaker Any update about this ticket? We have the same problem, thx.

**Comment by rrfrias** [comment]
From https://github.com/google/ExoPlayer/issues/10652#issuecomment-1370266786

> They tried with the demo app as well, and It is reproducible with DRM protected assets

Can you let us know which asset in the demo app you used to test with? Do i have your permission to share the bug report with Qualcomm? Also is this a problem only on the OnePlus 7T (running Android 11) or do you see it on any other devices?

Internal ref: 267124387

**Comment by grisoftumut** [comment]
@rrfrias we have also same issue at General Mobile GM5 which version is Android 7.1.1

**Comment by rrfrias** [comment]
@grisoftumut, does it just fail with that particular device and works fine for others? As the device is running an older Android release it might be a different problem. Can you please provide the result of adb bugreport captured after the failure and upload here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject  `Issue #10652`.

**Comment by farkasadam** [comment]
> Can you let us know which asset in the demo app you used to test with? Do i have your permission to share the bug report with Qualcomm? Also is this a problem only on the OnePlus 7T (running Android 11) or do you see it on any other devices?

@rrfrias I received more details from UAT:
- in demo app every widewine-protected assets work fine, they misunderstood the task earlier, I'm sorry for that!
- this issue majorly reported for Xiaomi devices, especially for Xiaomi Mi 9. Way back we faced this issue intermittently for example on Samsung S9 as well, but UAT reports that they cannot reproduce it on that device now.
- earlier we had two Oneplus 7T, model "HD1901" with Android 11 and model "HD1903" with Android 10. The issue was only on Android 11. When we updated the HD1903 to Android 11, issue appeared there too
- there are cases when the error comes after a few minutes of playback, not at the start

I'm still waiting for a confirmation about sharing bugreport with Qualcomm, I will get back to you.

**Comment by farkasadam** [comment]
@rrfrias we got the permission to share the bug report with Qualcomm

**Comment by rrfrias** [comment]
Thanks. Might it be possible to share a demo app that reproduces the problem that Qualcomm can use to test and verify a potential fix? As usual upload here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject Issue #10652

**Comment by Awille** [comment]
Hello, any update? i have same problem in xiaomi rednote 9.

![image](https://user-images.githubusercontent.com/32134785/217711884-21b67b68-182a-457d-8efb-f493fbaa0fd5.png)

**Comment by Awille** [comment]
@rrfrias i have met the same problem in redmi note 9,  am i have sent you the bugreport via [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com).  please check.

here is the exact stack trace :
**********************************************************
02-09 11:37:44.460 10320  4377  5508 W System.err: java.lang.IllegalStateException
02-09 11:37:44.461 10320  4377  5508 W System.err: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-09 11:37:44.462 10320  4377  5508 W System.err: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
02-09 11:37:44.464 10320  4377  5508 W System.err: 	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)
02-09 11:37:44.465 10320  4377  5508 W System.err: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1819)
02-09 11:37:44.466 10320  4377  5508 W System.err: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
02-09 11:37:44.468 10320  4377  5508 W System.err: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
02-09 11:37:44.470 10320  4377  5508 W System.err: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
02-09 11:37:44.471 10320  4377  5508 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
02-09 11:37:44.472 10320  4377  5508 W System.err: 	at android.os.Looper.loop(Looper.java:224)
02-09 11:37:44.473 10320  4377  5508 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
*****************************************

it also have other exceptions in bug report:
***************************************
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal: Playback error
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:224)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2194)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:166)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReinitializeCodec(MediaCodecRenderer.java:833)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onPositionReset(MediaCodecRenderer.java:679)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onPositionReset(MediaCodecVideoRenderer.java:498)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.resetPosition(BaseRenderer.java:168)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.resetPosition(BaseRenderer.java:161)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetRendererPosition(ExoPlayerImplInternal.java:1318)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1296)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1235)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToInternal(ExoPlayerImplInternal.java:1206)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:493)
02-09 11:37:24.805 10320  4377 11648 E ExoPlayerImplInternal:       ... 3 more
**********************************************************************

**Comment by Awille** [comment]
and i found that is easy to reproduces when use android.avc.decoder and prepare one play more than one time,  when use other decoder like OMX.MTK.VIDEO.DECODER.AVC,  it would not happen.      @rrfrias

**Comment by rrfrias** [comment]
@Awille   This looks like a different issue. I see a lot of memory pressure on the device
```
02-09 11:37:24.511  lmkd   556   556 E lowmemorykiller: MTK_packageName=com.xiaomi.bluetooth,taskname=com.xiaomi.bluetooth,strcmp=104
02-09 11:37:24.514  lmkd   556   556 I lowmemorykiller: Kill 'com.xiaomi.bluetooth' (17034), uid 1002, oom_adj 800 to free 83628kB
```

and other decoder failures

```
02-09 11:37:24.040 10320  4377  4454 D BufferQueueProducer: [SurfaceTexture-1-4377-30](this:0x714b60b000,id:30,api:3,p:-1,c:4377) cancelBuffer: slot 1
02-09 11:37:24.040 10320  4377  4454 E BufferQueueProducer: [SurfaceTexture-1-4377-30](this:0x714b60b000,id:30,api:3,p:-1,c:4377) cancelBuffer: BufferQueue has no connected producer
02-09 11:37:24.040 10320  4377  5523 D BufferPoolConnection: connection 18800747764955 closed on death
02-09 11:37:24.040 10320  4377  5523 D BufferPoolConnection: connection 18800747764957 closed on death
02-09 11:37:24.040 10320  4377  5523 E CCodec  : Codec2 component "c2.android.avc.decoder" died.
02-09 11:37:24.040 10320  4377 17189 E MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 6
```

Probably best to open a separate issue tracker (mention your comments here) if you would like us to follow up.

**Comment by wangdakuan** [comment]
我也遇到这个问题，请问有解决方案吗？

**Comment by wangdakuan** [comment]
I also met this problem. Is there a solution?

**Comment by rrfrias** [comment]
@wangdakuan can you share a bugreport/logcat/stack trace so that we can check if this is the same issue reported in this tracker.

**Comment by wangdakuan** [comment]
Playback error
                   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, -1, null, [720, 398, 24.006426], [-1, -1]), format_supported=YES
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
                       at android.os.Handler.dispatchMessage(Handler.java:113)
                       at android.os.Looper.loopOnce(Looper.java:205)
                       at android.os.Looper.loop(Looper.java:293)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
                       at android.os.Handler.dispatchMessage(Handler.java:113) 
                       at android.os.Looper.loopOnce(Looper.java:205) 
                       at android.os.Looper.loop(Looper.java:293) 
                       at android.os.HandlerThread.run(HandlerThread.java:67) 
                   Caused by: android.media.MediaCodec$CodecException: Error 0xffffffed
Disable failed.
                   java.lang.IllegalStateException
                       at android.media.MediaCodec.native_flush(Native Method)
                       at android.media.MediaCodec.flush(MediaCodec.java:2350)
                       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:230)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:858)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:851)
                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:691)
                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:609)
                       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1670)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1411)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1372)
                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:594)
                       at android.os.Handler.dispatchMessage(Handler.java:113)
                       at android.os.Looper.loopOnce(Looper.java:205)
                       at android.os.Looper.loop(Looper.java:293)
                       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by rrfrias** [comment]
@wangdakuan can you let us know if you have repro steps. Please mention devices that exhibit this problem. If you have a bugreport can you send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject Issue https://github.com/google/ExoPlayer/issues/10652

**Comment by rrfrias** [comment]
@farkasadam In case you missed my question from https://github.com/google/ExoPlayer/issues/10652#issuecomment-1421560715 Might it be possible to share a demo app that reproduces the problem that Qualcomm can use to test and verify a potential fix? As usual upload here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject Issue https://github.com/google/ExoPlayer/issues/10652

**Comment by farkasadam** [comment]
> @farkasadam In case you missed my question from [#10652 (comment)](https://github.com/google/ExoPlayer/issues/10652#issuecomment-1421560715) Might it be possible to share a demo app that reproduces the problem that Qualcomm can use to test and verify a potential fix? As usual upload here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject Issue #10652

@rrfrias We will discuss it internally but I think we cannot provide a demo app since we don't have any public asset. Is it possible to raise a ticket to Qualcomm with the bugreport only?

**Comment by rrfrias** [comment]
We did share the bugreport with Qualcomm. Qualcomm investigated and believes they have identified the problem and has provided a fix for it. We were hoping that a repro attempt would confirm the fix, but we understand if an app is unavailable.

We are in the process of creating qualification tests so that new devices do not have this bug. For existing devices Qualcomm will work with OEMs to try and patch devices when possible. Are there any devices other than OnePlus 7T running Android 11 mentioned in the [first comment](https://github.com/google/ExoPlayer/issues/10652#issue-1386169420) that you know of that exhibit this problem so that we can work with the OEMs.

**Comment by ying7sai** [comment]
We have seen a similar failure on Pixel 4 device with ExoPlayer 2.18.2:

```
04-24 19:08:34.974  1024 12075 E QCOM-OEMCrypto: Error at trusted_app_decrypt_cenc : 2563
04-24 19:08:34.974  1024 12075 E QCOM-OEMCrypto: TA Result : 1 OEMCryptoResult : 25
04-24 19:08:34.975  1024 12075 I QCOM-OEMCrypto: -----------------------------------------------------------------
04-24 19:08:34.975  1024 12075 I QCOM-OEMCrypto: Error stack trace[7] for TA version 1:85
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 set_cipher_iv : 253
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 drm_cipher_op : 1431
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 decrypt_blocks : 382
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 decrypt_ctr : 949
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 decrypt_subsample : 1371
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 process_subsample : 1410
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: 	 i_widevine_session_decrypt_cenc : 1745
04-24 19:08:34.975  1024 12075 I QCOM-OEMCrypto: -----------------------------------------------------------------
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: Error at decrypt_data : 1919
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: Error at _oecc48 : 2366
04-24 19:08:34.975  1024 12075 E QCOM-OEMCrypto: Error at _oecc105 : 3166
04-24 19:08:34.975  1024 12075 E WVCdm   : [crypto_session.cpp(1679):Decrypt] OEMCrypto_DecryptCENC failed: status = 25
04-24 19:08:34.975  1024 12075 E WVCdm   : Decrypt error in session sid15 during a sample with protected data: 1
```

**Comment by rrfrias** [comment]
@ying7sai that does look similar. If you can, can you share a demo app that reproduces the problem that Qualcomm can use to test and verify a potential fix? Upload here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject "Issue #10652"

**Comment by rrfrias** [comment]
Opened internal tracker [283024925](http://b/283024925) so that OnePlus can pick up the fix from Qualcomm for OnePlus7T. Let me know if this affects any other devices. We are adding additional qualification tests to prevent this from occuring in the future.

This problem occurs when one of the subsamples in the content is smaller than 16 bytes (AES block code size). You might want to see if you can tweak your encoding configurations to avoid this.

**Comment by farkasadam** [comment]
> Opened internal tracker [283024925](http://b/283024925) so that OnePlus can pick up the fix from Qualcomm for OnePlus7T. Let me know if this affects any other devices. We are adding additional qualification tests to prevent this from occuring in the future.
> 
> This problem occurs when one of the subsamples in the content is smaller than 16 bytes (AES block code size). You might want to see if you can tweak your encoding configurations to avoid this.

@rrfrias thank you for the updates! Talking about affected devices we received this earlier: 
"The device models which are affected are majorly OnePlus and Xiaomi devices, especially Xiaomi Mi 9. We purchased the Xiaomi device too, but not able to reproduce "4003" error on that one. In past, we faced intermittently on Samsung S9 as well. Now it is not reproducible there."

**Comment by rrfrias** [comment]
If it happens, the problem should be consistently reproducible for a given piece of content + build on a make+model. Can you tell from your data if failing attempts cluster around some combinations? 

To follow up with device makers, what might be helpful is make+model+build information for any devices that consistently fail (or failure % if occasional).

**Comment by wangdakuan** [comment]
I tried again after the exception to create a new one that could decode and play normally




王达宽
***@***.***







                       
原始邮件
                       
                     

发件人："rrfrias"< ***@***.*** &gt;;

发件时间：2023/5/18 3:06

收件人："google/ExoPlayer"< ***@***.*** &gt;;

抄送人："BasisRequestProject"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [google/ExoPlayer] MediaCodecVideoDecoderException (Issue #10652)




 
If it happens, the problem should be consistently reproducible for a given piece of content + build on a make+model. Can you tell from your data if failing attempts cluster around some combinations? What might be helpful is make+model+build information for any devices that consistently fail (failure % if occasional).
 
&mdash;

**Comment by rrfrias** [comment]
@wangdakuan In the previous comment, i cannot tell if you have additional information to share. Can you please comment again?
