### ISSUE TITLE
Analytics: Getting time to video metric using getTotalJoinTimeMs or getTotatWaitTimeMs

### ISSUE THREAD

**Issue by tonyv** [google/ExoPlayer#10668]
I'm trying to understand the amount of time it takes to start playing a live stream once playback has been initated in ExoPlayer. This is commonly referred to as Time to video (TTV).

I'm using the playbackStatsListener within the ExoPlayer Demo App to get this metric. My understanding is that [getTotalJoinTimeMs() ](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#getTotalJoinTimeMs()), [getTotatWaitTimeMs()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#getTotalWaitTimeMs()), or [totalValidJoinTimeMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#totalValidJoinTimeMs) is the value I'm looking for.

Can someone on the ExoPlayer team confirm which of these would be closer to what I need?

**Comment by tonihei** [comment]
I think you are very likely looking for the "join time", which only includes the time until the playback starts for the first time. "Wait time" includes all times where playback was blocked, for example it also includes rebuffers.

The difference between `getTotalJoinTimeMs` and `totalValidJoinTimeMs` is that the "valid" time is filtered by cases where playback was joining in the background (=it wasn't a user wait time), or where playback never started and the eventual join time is effectively undetermined. So if you are looking for a single value, you should probably use `totalValidJoinTimeMs`. 

Please also read the Javadoc you linked, since it explains the differences already.

**Comment by tonihei** [comment]
I'll close the issue assuming the question was answered.
