### ISSUE TITLE
onAdPlaybackState: The number of AdPlaybackState#adGroupCount ad groups may not change after the first call

### ISSUE THREAD

**Issue by kotucz** [google/ExoPlayer#10677]
The above is stated in the documentation of `AdsLoader.EventListener.onAdPlaybackState`.
Implementing new loading of ads as follows:
- Prerolls are loaded from VAST and set `AdPlaybackState` with single preroll ad group, before the playback starts.
- Later, midrolls are loaded from VMAP and added to `AdPlaybackState` using `withNewAdGroup`.
- Then updating `AdsMediaSource.onAdPlaybackState` crashes with `IllegalStateException`, because the ad group count has changed with the new midrolls. 

We want to be able to load more mid-rolls ads lazily mid-playback (for e.g. every 30 minutes).

Is there a chance, changing ad group count will be implemented as a feature?

If not, what is recommended workaround?

Currently trying with pre-allocating enough ad groups to be reused later:
`AdPlaybackState(adsId, 0, *LongArray(MAX_MIDROLLS_COUNT) { Long.MAX_VALUE })`
Can this approach have some unexpected impact on something?

**Comment by tonihei** [comment]
> Is there a chance, changing ad group count will be implemented as a feature?

There is nothing wrong with adding new ad groups to the list in theory. `AdsMediaSource` just doesn't support it yet because it was written with the IMA-specific ads loader in mind that always loads all ads upfront. 

To support adding new ad groups, we need to update some state tracking in `AdsMediaSource` that currently doesn't handle this case. If you are sufficiently motivated to have this feature, feel free to send a PR for this. 

This feature request is also already tracked in #5482 (but with another use case in mind), so I'll close as a duplicate.

> Currently trying with pre-allocating enough ad groups to be reused later:
AdPlaybackState(adsId, 0, *LongArray(MAX_MIDROLLS_COUNT) { Long.MAX_VALUE })

This may work as long as you make sure to set the midroll times far enough into the future and if you never want to end the stream (because the player would want to play all remaining midrolls at some point). Haven't tested this though and can't tell you exactly where it may go wrong.
