### ISSUE TITLE
Video plays at very low FPS on Amazon device

### ISSUE THREAD

**Issue by alekssunsss** [google/ExoPlayer#10681]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Kindle Fire HD (3rd Generation)

### Devices that do not reproduce the issue

Samsung galaxy Tab E (Android 4.4),
Samsung Galaxy A5 (Android 8),
Amazon Fire HD 8 (10th Generation),
Amazon Fire HD 10 (11th Generation),
Samsung Galaxy Tab A7 Lite (Android 11)

### Reproducible in the demo app?

Yes

### Reproduction steps

This issue is linked to https://github.com/google/ExoPlayer/issues/10665

We have Amazon device which cannot play video file well using ExoPlayer. 

The same video plays well on the same device (Kindle Fire HD (3rd Generation) using another players (Prime photos and TotalCmd (Queue)). But when we try to play video using ExoPlayer sometimes we get error (Failed to initialize decoder: OMX.TI.DUCATI1.VIDEO.DECODER) or sometimes the video starts to play (using the same codec OMX.TI.DUCATI1.VIDEO.DECODER) but FPS is very low (one frame per one second or maybe lower).
The same issue reproduces using test application ExoPlayer demo app.

Why do we have this issue using ExoPlayer while another players work well?
Is there any way to get current FPS of video playback so we could skip it at the beginning?

### Expected result

video file plays without issues

### Actual result

video is stuttering (playback with very low FPS)

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
> The same video plays well on the same device (Kindle Fire HD (3rd Generation) using another players (Prime photos and TotalCmd (Queue))

Are these players using the same `OMX.TI.DUCATI1.VIDEO.DECODER` decoder? You can probably see what decoder they're using by taking a bug report while they're playing.

Is this a software decoder? Software decoder performance is basically completely undefined, because it depends on the other CPU load of the device at the time.

I don't have the problematic device to hand to confirm, but it's possible that the video file you're trying to play is considered 'exceeds capabilities' by a hardware decoder on the device, while the software decoder claims to fully support it (software decoders generally claim to support any resolution, and don't try and make any claims about performance due to the problem described above). In this case ExoPlayer will pick the software decoder (because 'fully supported' is considered better than 'exceeds capabilities'), even though the **actual** software codec performance might be very poor for the content in question. We are looking at changing this behaviour to prefer an 'exceeds capabilities' hardware decoder over a 'fully supported' software decoder.

If you're able to [depend locally](https://github.com/google/ExoPlayer#locally) on ExoPlayer you could try modifying `MediaCodecUtil` to prevent the player selecting this codec (as a debugging step). You'd do this by adding the following block into the codec selection loop just after L331:

https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L331

```java
if (name.equals("OMX.TI.DUCATI1.VIDEO.DECODER")) {
  continue;
}
```

Please let us know if this helps, and if so what codec the player ends up selecting instead, whether it's a hardware codec, and whether the player reports that codec support is 'exceeds capabilities'.
