### ISSUE TITLE
ExoPlayer decoder buffer doesn't release - playback freeze

### ISSUE THREAD

**Issue by danielgliga3ss** [google/ExoPlayer#10687]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

SEI Robotics SEI700TE device (https://www.androidtv-guide.com/pay-tv-provider/tele2-tv-hub-mini/) -> Android 11
The bug was reported by the SEI Robotics team.

### Reproducible in the demo app?

Not tested

### Reproduction steps

No steps to reproduce the problem. 

### Expected result

No playback freeze.

### Actual result

Comments from SEI Robotics:
"In general, mediacodec interface needs to audio decoder and video decoder after attaining from apk. Then decoder buffer will be released via Mediscodec interface to apk. After getting the buffer from apk, the apk should return back the buffer. (shown like the below image)
![00d0e886-a6ba-41f2-9488-64b30f2388c5](https://user-images.githubusercontent.com/60341615/195584926-44362642-cc5a-4513-8468-810ce23ae2b9.jpeg)
After reproducing the frozen issue, we found decoder buffer hasn’t sent back by the app/Exoplayer."
![16317a08-9b29-43f1-88e7-36a434f4e02a](https://user-images.githubusercontent.com/60341615/195586369-5d435727-88d4-40c3-8cea-5d256d405f9c.png)

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
There isn't really enough info here to be actionable. You haven't provided any steps to reproduce the problem, nor an analysis of the source code to point out what you believe to be wrong. Is it possible that ExoPlayer not releasing the buffer (as you claim) is a symptom of the wider freezing problem you observe, rather than a cause?

If this is a general problem with the ExoPlayer library (which it sounce like you're claiming) then it shouldn't be device-specific, it should be possible to reproduce on any device - so please provide complete repro instructions we can use to observe the problem. Thanks!
