### ISSUE TITLE
Video rotation with SurfaceView

### ISSUE THREAD

**Issue by milan-fabian** [google/ExoPlayer#10693]
Hello,

I am looking for a way to display video portrait video on a portrait TV in native (not UI) resolution using an Android box:

- The Android box has UI layer resolution 1080p and output resolution of 4K, so according to https://exoplayer.dev/ui-components.html#choosing-a-surface-type only SurfaceView can be used for actual 4K rendering. TextureView will render the video only in 1080p (UI layer resolution).
- The Android box doesn't support portrait display natively (`Activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)` does nothing), so the video has to be rotated in software.

I tried using `SurfaceView.setRotation()`, but it doesn't affect the video. `TextureView.setRotation()` works fine, but the video is rendered in 1080p instead of 4K (which is expected according to the documentation).

Does anybody know if there is a way of solving this without having to rotate the video using re-encoding?

**Comment by christosts** [comment]
You could have the decoder rotate the video during decoding. Ultimately, the MediaCodec needs to be configured with a `MediaFormat` that contains the key `MediaFormat.KEY_ROTATION` and the rotation degrees for a value.

There are several methods in `MediaCodecVideoRenderer` you can override to achieve this, possibly just start with overriding [`MediaCodecVideoRenderer.getMediaFormat()`](https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1476). You'd need to customize the renderers for this, and create the player with your custom renderers, where you use your own custom instance instead of the `MediaCodecVideoRenderer` one.

**Comment by milan-fabian** [comment]
Thank you for the tip, I am getting promising first results after changing:
```
MediaFormatUtil.maybeSetInteger(mediaFormat, MediaFormat.KEY_ROTATION, format.rotationDegrees);
```
to
```
MediaFormatUtil.maybeSetInteger(mediaFormat, MediaFormat.KEY_ROTATION, (format.rotationDegrees + this.myRotation) % 360);
```
