### ISSUE TITLE
Values of SBL and RBL 

### ISSUE THREAD

**Issue by shripaljadhav** [google/ExoPlayer#10711]
how to change 'start-up buffer length' and 'rebuffering buffer length (SET) these default parameters programmatically, and how to read (GET) values of 'bitrate', 'start-up buffer length' and 'rebuffering buffer length' from exo-player instance, at any time when video is playing.

**Comment by christosts** [comment]
I see you also filed #10689 so I'll answer with that issue in context too

> how to change 'start-up buffer length' and 'rebuffering buffer length (SET) these default parameters programmatically

This information is in [`DefaultLoadControl`](https://github.com/google/ExoPlayer/blob/r2.18.1/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java) and it cannot be changed after the instance is created. If you want to dynamically change these values, you'd have to create a custom `LoadControl` and inject it to the player. You can try copying `DefaultLoadControl` and modifying it to meet your app requirements. 

> how to read (GET) values of 'bitrate', 'start-up buffer length' and 'rebuffering buffer length' from exo-player instance, at any time when video is playing.

The  'start-up buffer length' and 'rebuffering buffer length' are part of the `DefaultLoadControl`, and there are no getters for those fields. Since they are final, and their default values are public, the app knows what the values are in this instance (either the default ones or the ones the app set itself during construction of the instance). If you want to change these values and then have getters for these, then my suggestion remains as above, to create your own custom `LoadControl` instance.

I'm not sure what you mean by 'bitrate'. Is it the currently downloaded content bitrate or the observed network throughput based on which the player makes [ABR](https://en.wikipedia.org/wiki/Adaptive_bitrate_streaming) decisions? I think you mean the latter. If so, this information in the `BandwidthMeter`, and the default implementation is `DefaultBandwidthMeter` (same naming scheme :) ) This class uses the singleton pattern, so you can have access to the instance from everywhere and then get the observed bandwidth estimation with `DefaultBandwidthMeter.getSingletonInstance(context).getBitrateEstimate()`. In addition, the `BandwidthMeter` is also something that can be injected to the player during construction, so you can pass your own instance if you want.

High-level comment: from this question and also #10689, it sounds like you are trying to tune the player for ABR. It might be worth sharing in high-level what is the situation you are facing and what you are trying to achieve, because we might be able to offer better advice, rather than specific points in the code.
