### ISSUE TITLE
Signal media period id is an ad

### ISSUE THREAD

**Issue by zilinx** [google/ExoPlayer#10723]
Hi, I have a DAI system (not Google) for VOD and Live (DVR). It serves multiperiod DASH and matching ad metadata. Each period will either contain content or one ad. There can be multiple ads in one ad break. 
I would like to try integrating it with ExoPlayer rather than "slapping" the listeners etc. on top, for better experience and to be able to use other nice source-manipulation features ExoPlayer offers. 

I'm having trouble understanding how I can signal to ExoPlayer which media periods are ads. I looked at `ServerSideAdInsertionMediaSource` but (tested on VOD) setting `AdPlaybackState` with `adGroupTimeUs` was giving me some issues (STATE_READY event is received, but then nothing happens) and there's no documentation for that class so I am a little afraid I wouldn't implement it correctly. 

Is there an uncomplicated way to signal to ExoPlayer which periods are ads? Perhaps there's another solution I should be looking at?

**Comment by marcbaechinger** [comment]
The `ServerSideAdInsertionMediaSource` has a method `setAdPlaybackStates` that expects a map of `AdPlaybackState`s. The map contains an `AdPlaybackState` for each period of the stream with the period UID as the key in the map. So for multi-period DASH you have to create an `AdPlaybackState` for each period and then set this map accordingly.

For the case you are describing you'd have an empty `new AdPlaybackState(adsId)` for each content period and for ad periods an `AdPlaybackState` with a single ad spanning the entire period. If you know which periods are ads and which are content, this can be straight forward. The `adGroupTimeUs` of the single ad group in an `AdPlaybackState` starts at period position 0 and the duration of the ad is the duration of the entire period (as a start you may want to only use empty ad playback states. With this the stream should play but without ads integration. Just as a starting point).

1. Create the `ServerSideAdInsertionmediaSource` that gets the content media source passed to the constructor.
2. Add the media source instance to the player and call `player.prepare()'.
3. When the content source is prepared, `AdPlaybackStateUpdater.onAdPlaybackStateUpdateRequested(Timeline contentTimeline)` is called and passes you the timeline of your DASH stream.
4. Create the map with `AdPlaybackStates` for each period in the timeline and put it in the map with the key being `period.uid` as the key.
5. Pass the map to `ServerSideAdInsertionMediaSource.setAdPlaybackStates(map)` (obviously, you need to keep a reference to the source for that. The method can be called from any thread).

The `ServerSideAdInsertionMediaSource` then takes care that the durations of ad periods are not included in the duration of the stream, so that for instance the `PlayerView` displays the duration of only the content periods in the timebar.

**Comment by zilinx** [comment]
Thank you very much for taking time to explain how to use this SSAI media source! It put some of the assumptions I made in a new light. It also clarified a good deal of things I wasn't sure of. Probably most importantly it gave me the confidence I needed :). I hope you don't mind if I ask some follow up questions:

You suggested I should use `AdPlaybackState.NONE` for content, but the assertions in `setAdPlaybackStates` fails, because `adsId` is null for this object:
- if the first `AdPlaybackState` in the map was `AdPlayabckState.NONE`, the not null assertion fails:
```Object adsId = checkNotNull(adPlaybackStates.values().asList().get(0).adsId);```
- if the first state is an ad, but any state after that is `AdPlayabckState.NONE`, the equality assertion fails once `NONE` is reached:
```checkArgument(Util.areEqual(adsId, adPlaybackState.adsId));```

I've been using `AdPlaybackState(adsId)` to work around the assertions, but I'm not sure if that's ok. Am I missing something?
My code in `onAdPlaybackStateUpdateRequested` looks like this:
``` 
val adStatesBuilder = ImmutableMap.builder<Any, AdPlaybackState>()
(0 until contentTimeline.periodCount).forEach { periodIndex ->
    val uid = contentTimeline.getUidOfPeriod(periodIndex)
    adStatesBuilder.put(uid,  AdPlaybackState(adsId)) // should be AdPlaybackState.NONE
}
serverSideAdInsertionMediaSource?.setAdPlaybackStates(adStatesBuilder.build())
```

Other than that it seems to work well when I connect it to ads metadata.  Mind having a look if this looks ok? My loop ended up looking like this:
```
(0 until contentTimeline.periodCount).forEach { periodIndex ->
    contentTimeline.getPeriod(periodIndex, timelinePeriod, true)
    val uid = timelinePeriod.uid!!
    val thisPeriodStart = timelinePeriod.positionInWindowMs
    val matchingAd = ads?.firstOrNull { it.start == thisPeriodStart }
    val adPlaybackState: AdPlaybackState =
        if (matchingAd != null) {
            val state = AdPlaybackState(adsId)
                .withNewAdGroup(0, 0)
                .withAdCount(0, 1)
                .withAdDurationsUs(0, timelinePeriod.durationUs)
            state
        } else {
            AdPlaybackState(adsId)
        }
    adStatesBuilder.put(uid, adPlaybackState)
 }
 ```
 
Final question - what exactly is the purpose of `adsId`? I saw in IMA implementation that it's taken from the request URL, but does it have any real purpose? For now I just always set it to 0, so I wonder if that could lead to some unwanted consequences.

**Comment by marcbaechinger** [comment]
> I've been using AdPlaybackState(adsId) to work around the assertions

Yes, sorry. My advice was wrong. I forgot about the check of `adsId`. `AdPlaybackState(adsId)` is the right thing to do, not using `AdPlaybackState.NONE`.

EDIT: I corrected the comment above to use `new AdPlaybackState(adsId)` instead of `AdPlaybackState.EMPTY`

> what exactly is the purpose of adsId?

It just identifies the ad, I think you are right that it is probably coming from the IMA implementation. For IMA it makes sure that the same ad tag can be added to a playlist multiple times and that the `AdPlaybackState` [can be restored properly](https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaServerSideAdInsertionMediaSource.java#L376) when the `AdsLoader` is created with a saved state (for instance after backgrounding the app).

Make sure it is unique and you don't have an issue.

Yeah, code looks correct to me. 

Mark all your ad groups as `serverSideInserted` and (very-minor) pass the `adGroupTimeUs` directly to the construcotr to save one `AdPlaybackState` object creation:

```
val state = AdPlaybackState(adsId, /* adGroupTimesUs= */ 0)
              .withAdCount(0, 1)
              .withAdDurationsUs(0, timelinePeriod.durationUs)
              .withIsServerSideInserted(/* adGroupIndex= */ 0, true);
```

A further note of which I'm not sure you are already aware of.  If you listen for `Player.Listener.onPositionDiscontinuity(PositionInfo oldPosition, PositionInfo newPosition)` you can detect when an ad has been played and mark it as played.

`PositionInfo` gives you the `periodUid` and `adGroupIndex` (there is only a single ad so `adIndexInAdGroup` is always 0 for your case). If you keep your map of `adPlaybackStates` you can lookup the state by the `periodUid` and do something like the following (not checked if it compiles, it should give the sense though :))

```
@Override
public void onPositionDiscontinuity(
        Player.PositionInfo oldPosition,
        Player.PositionInfo newPosition,
        @Player.DiscontinuityReason int reason) {
    // Note: with multiple items in the playlist you need to address this. 
   // This snippet assumes a single media item in the playlist only
    if (oldPosition.adGroupIndex != C.INDEX_UNSET && newPosition.adGroupIndex == C.INDEX_UNSET) {
        AdPlaybackState playedState = 
            mapOfStates.get(oldPositionInfo.periodUid)
                .withPlayedAd(oldPositionInfo.adGroupIndex, 0);
       mapOfStates.put(oldPositionInfo.periodUid, playedState);
       serverSideAdIndesrtionMediaSource.setAdPlaybackStates(mapOfStates);
   }
}
```

When marked as played the period is skipped if the user seeks back in a VOD stream.

**Comment by zilinx** [comment]
Thank you for sharing the sample on how to mark the ads as completed! This was one of those features of `ServerSideAdInsertionMediaSource` which attracted me in the first place :). The `period.uid` was a bit problematic to reference because it seems to change for `oldPosition` in the discontinuity callback - it was a pair of <object, number> or <object, object> instead of a number like it was when I received the timeline in `onAdPlaybackStateUpdateRequested`. I tried to figure out what's going on there, but it felt like a rabbit hole. Is period index safe to use?

I also ran into a crash which seems to happen most often when seeking past the position of the next ad break (I've never seen it happen if I just let the entire stream play or if seeking after all midrolls have played). This happens after MediaPeriod was created but was not yet prepared, so the array `hasNotifiedDownstreamFormatChange` is still empty when `onDownstreamFormatChanged` is called. I suspect it has something to do with the fact that a new period is getting loaded, but I can't really see how I could sync those two operations. Do you have any ideas you could share? Here's the crash stacktrace if it helps:
```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SharedMediaPeriod.onDownstreamFormatChanged(ServerSideAdInsertionMediaSource.java:901)
       at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource.onDownstreamFormatChanged(ServerSideAdInsertionMediaSource.java:526)
       at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$downstreamFormatChanged$5$com-google-android-exoplayer2-source-MediaSourceEventListener$EventDispatcher(MediaSourceEventListener.java:471)
       at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher$$ExternalSyntheticLambda4.run(Unknown Source:6)
       at com.google.android.exoplayer2.util.Util.postOrRun(Util.java:549)
       at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.downstreamFormatChanged(MediaSourceEventListener.java:469)
       at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.downstreamFormatChanged(MediaSourceEventListener.java:454)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:752)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.maybeNotifyPrimaryTrackFormatChanged(ChunkSampleStream.java:744)
       at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:390)
       at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SharedMediaPeriod.readData(ServerSideAdInsertionMediaSource.java:862)
       at com.google.android.exoplayer2.source.ads.ServerSideAdInsertionMediaSource$SampleStreamImpl.readData(ServerSideAdInsertionMediaSource.java:1210)
       at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:425)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:961)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by zilinx** [comment]
Figured the issue above is probably related to the issue in the stream itself. The way the player parsed it, the time would sometimes shift a few milliseconds after seeking, causing this issue.

Thank you very much for all your help to implement `ServerSideAdInsertionMediaSource` in my app!
