### ISSUE TITLE
[exoplayer][media3][HLS] hlsmanifest on timeline changed returns always null

### ISSUE THREAD

**Issue by ofcbujin** [google/ExoPlayer#10735]
Hello, I'm trying to get some HLS tag from the playlist (#EXT-X-PROGRAM-DATE-TIME). Looking out into the documentation I know that to achieve this I need to get the currentmanifest from the onTimelineChanged event, the problem is that it always returns null.

For context I'm using the MediaLibraryService. Here I initialize the Exoplayer as follow:

```
        val defaultDataSourceFactory = DefaultHttpDataSource.Factory()
            .setAllowCrossProtocolRedirects(true)
            .setConnectTimeoutMs(DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS)
            .setReadTimeoutMs(DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS)

        val source = HlsMediaSource.Factory(defaultDataSourceFactory)
            .setAllowChunklessPreparation(false)

   
        player =
            ExoPlayer.Builder(this)
                .setAudioAttributes(AudioAttributes.DEFAULT
                    , /* handleAudioFocus= */ true)
                .setTrackSelector(trackSelector)
                .setMediaSourceFactory(source)
                .setHandleAudioBecomingNoisy(true)
                .setWakeMode(C.WAKE_MODE_LOCAL)
                .build()

        mediaLibrarySession =
            MediaLibrarySession.Builder(this, player, librarySessionCallback)
                .setSessionActivity(sessionActivityPendingIntent!!)
                .build()

```

In the main Activity I create a SessionToken and call a ListanableFuture to get the mediacontroller when is ready. 

```
        val sessionToken = SessionToken(this, ComponentName(this, PlayerService::class.java))
        mediaControllerFuture =    MediaController.Builder(this, sessionToken)
```

Once is ready I add a Listener in the Mediacontroller and try to get the manifest:

```
mediaController.addListener(
            object : Player.Listener{

            override fun onTimelineChanged(timeline: Timeline, reason: Int) {
                    if(timeline.windowCount > 0) {
                        var window = Timeline.Window()
                        window = timeline.getWindow(0,window)
                        playerPositionMs = window.positionInFirstPeriodMs
                        Log.e(TAG, "onTimelineChanged: position: $playerPositionMs", )
                        val manifest = mediaController.currentManifest //This is always null
                    }

                }
}
)
```

This implementation returns the manifest always as null object.

Exoplayer played the stream without problem but I'm not being able to get the manifest. Here is an example of the playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-CUSTOM-ID: [ID]
#EXT-CUSTOM-STARTTIME:1667065680
#EXT-CUSTOM-LASTIME:1667324872
#EXT-X-MEDIA-SEQUENCE:829422
#EXT-X-TARGETDURATION:5
#EXT-X-ALLOW-CACHE:YES
#EXT-X-START:TIME-OFFSET=0
#EXT-X-PROGRAM-DATE-TIME:2022-11-01T17:47:37.000Z
#EXTINF:5.0,
https://example.stream.com/lq_1667324857.ts
#EXT-X-PROGRAM-DATE-TIME:2022-11-01T17:47:42.000Z
#EXTINF:5.0,
https://example.stream.com/lq_1667324862.ts
#EXT-X-PROGRAM-DATE-TIME:2022-11-01T17:47:48.000Z
#EXTINF:5.066666,
https://example.stream.com/lq_1667324868.ts
#EXT-X-PROGRAM-DATE-TIME:2022-11-01T17:47:52.000Z
#EXTINF:5.0,
https://example.stream.com/lq_1667324872.ts
```

What is that i'm doing wrong? Thanks

**Comment by marcbaechinger** [comment]
You are doing nothing wrong. I think this is working as intended. [`MediaController.getCurrentManifest()` is documented to return null](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L889). Methods that return an `Object` can't really be remoted in an easy way as they are neither `Bundleable` not `Parceable` and its type is unclear. 

You could access the manifest on the service side by using `MediaSession.player.getCurrentManifest()` to get the `HlsMediaPlaylist`. Before you do this I'd look into `HlsMediaPlaylist` whether you find the attributes that you are looking for. 

I'm mentioning this because ExoPlauer does not parse every field of a playlist and also does not include every field in the `HlsMediaPlaylist` object. In the case of `#EXT-X-PROGRAM-DATE-TIME` for instance and from inspecting the [source code of `HlsPlaylistParser`](https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistParser.java#L847), we only read the first occurrence of the tag. You would have to inspect the segment list and the durations of thes  segments to get similar information.

**Comment by ofcbujin** [comment]
Thank you Marc for the response. I could access the manifest calling the onTimelineChanged on the service side as you mentioned changed my code for working from there. Thanks again!
