### ISSUE TITLE
How to use IMA extension with Leanback on Android TV?

### ISSUE THREAD

**Issue by pastafarianGit** [google/ExoPlayer#10736]
I am trying to add local ads implementation with leanback exoplayer.
I am following https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side

But I am unsure on what to set  adViewProvider since I am using PlaybackTransportControlGlue and not player view.
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/DefaultMediaSourceFactory.html#setLocalAdInsertionComponents(com.google.android.exoplayer2.source.ads.AdsLoader.Provider,com.google.android.exoplayer2.ui.AdViewProvider)

Any tips will be really appreciated.

**Comment by marcbaechinger** [comment]
If you are not using `PlayerView` then your app UI needs to provide an `ViewGroup` rather than using the player view. The `ViewGroup` needs to be an overlay of the surface that plays the ad, so that the ad SDK can insert UI elements that appear on top of the ad while the ad is playing (like the skip button or the `more info` link and the like). Add such a `ViewGroup` to your UI and pass it as return value of the `AdViewProvider.getAdViewGroup()`.

**Comment by pastafarianGit** [comment]
jup that was it. Thanks alot for help ! You are my hero. <3
I just implemented AdViewProvider on my VideoSupportFragment and it worked. 
```
public class PlayerFragment extends VideoSupportFragment implements AdViewProvider{
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mPlayerView = (ViewGroup) super.onCreateView(inflater, container, savedInstanceState);
        }
        
    @Override
    public ViewGroup getAdViewGroup() {
        return mPlayerView;
    }
}
```
