### ISSUE TITLE
How to reuse an ExoPlayer inside a recyclerview that each item has multiple videos

### ISSUE THREAD

**Issue by lenhatquang97** [google/ExoPlayer#10759]
Hi, I am doing video autoplaying app. In this recyclerview, each item has a grid with multiple videos. Everytime a video plays, a video creates new ExoPlayer.Builder(context).build(). After the video plays to the end or the video is not visible when user scrolls, this player is released, and other video continues to play. I want to know how to reuse ExoPlayer.Builder because I have searched solution but it does not match this case. This grid is a CustomView and I add PlayerView into this grid programmatically. (Note, everytime data binds, ViewHolder adds PlayerView into this grid)

After profiling, I realize that this retained size is too large
![image](https://user-images.githubusercontent.com/54705069/200477196-dd69d22c-0df3-427b-ab3b-c2ea20c7a7a4.png)

Sample of this demo app. 
![Screenshot_20221108-114454](https://user-images.githubusercontent.com/54705069/200477471-1b916c7f-b814-48a9-9016-b815b82a1525.png)

Thanks in advance.

**Comment by tonihei** [comment]
You can reuse the `ExoPlayer` object itself instead of reusing the `Builder`. Just call `setMediaItem` again to set new media. `PlayerView` has a method called [`switchTargetView`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#switchTargetView(com.google.android.exoplayer2.Player,com.google.android.exoplayer2.ui.PlayerView,com.google.android.exoplayer2.ui.PlayerView)) to update the output of the player instance. If only one player is playing at a time, you should be able to use a single `Player` instance in your app.
