### ISSUE TITLE
Fire TV Stick - 2nd Gen (AFTT) gets stuck in buffering state after seeking

### ISSUE THREAD

**Issue by Koster35** [google/ExoPlayer#10769]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

- Fire TV Stick - 2nd Gen (AFTT), Fire OS 5

### Devices that do not reproduce the issue

- Chromecast with Google TV, Android 10
- Fire TV Stick Lite - 1st Gen (AFTSS), Fire OS 7
- Fire TV Stick - 3rd Gen (AFTSSS), Fire OS 7

### Reproducible in the demo app?

No

### Reproduction steps

First, it's important to describe how our seekbar implementation works. We setup a listener on our seekbar like this:
```
        seekBar.setOnSeekBarChangeListener(object : SeekBar.OnSeekBarChangeListener {
            override fun onProgressChanged(seekBar: SeekBar, progress: Int, fromUser: Boolean) {
                // Call Player.seekTo(windowIndex, positionMs)...
            }

            override fun onStartTrackingTouch(seekBar: SeekBar?) {
            }

            override fun onStopTrackingTouch(seekBar: SeekBar?) {
            }
        })
```

So, when the user moves the seekbar forward or back, it results in many successive `Player.seekTo(windowIndex, positionMs)` calls in a short period of time (multiple calls per second).

With that in mind, here are the steps:
1. Seek forward or back through a video using repeated  `Player.seekTo(windowIndex, positionMs)` calls.
2. Observe that the player state changes from `STATE_READY` to `STATE_BUFFERING` when seeking starts.

### Expected result

Player state changes from `STATE_BUFFERING` to `STATE_READY` after seeking completes, allowing playback to proceed.

### Actual result

Player state never changes from `STATE_BUFFERING` after seeking, so the video cannot play further. Seeking again or changing the player's `playWhenReady` state has no effect, the player still remains stuck buffering.

### Media

This can be reproduced with the HLS sample "Apple 16x9 basic stream (TS)" in the demo app:
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
This sounds like a device specific bug you should report to Amazon. As this device is quite old and unlikely to receive further updates, it's a bit unclear if we can do anything about it. 

Your bugreport contains a lot of `CodecNameUnknown-MediaCodecVideoRenderer: skipOutputBuffer: bufferIndex = 5, PTS = 183049800`. I assume that's your own logging? They also look not concerning because they indicate the player correctly skips buffers from the last available key frame. For example your last seek was to `188984000` and then the renderer starts decoding from `180146900` and skips all buffers until it reaches `188955711` (presumably the last sample before your seek time). And there are no other logs indicating a problem.

**Comment by Koster35** [comment]
Those logs were added by Amazon. This bug occurs in ExoPlayer 2.17.1 and the ExoPlayer Amazon port 2.17.1, so I must have mistakenly submitted the bug report I took using the Amazon port.

Thanks for looking into this. I will try to reach out to Amazon about this again.
