### ISSUE TITLE
onPlaybackStateChanged with PlaybackState STATE_ENDED is not called when seeking on a paused video

### ISSUE THREAD

**Issue by ThibaultBee** [google/ExoPlayer#10783]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Pixel 4 running on Android 13

### Reproducible in the demo app?

Yes. 
Reproduced with `demo` application and one of the HLS stream. 
I added breakpoint in `EventLogger` `onPlaybackStateChanged` and watch logcat but it displays:
```
2022-11-16 14:11:18.171 24711-24711 EventLogger             com.google.android.exoplayer2.demo   D  state [eventTime=134.08, mediaPos=1800.00, window=0, period=0, BUFFERING]
2022-11-16 14:11:18.212 24711-24711 Choreographer           com.google.android.exoplayer2.demo   I  Skipped 65 frames!  The application may be doing too much work on its main thread.
2022-11-16 14:11:18.838 24711-24711 EventLogger             com.google.android.exoplayer2.demo   D  state [eventTime=135.16, mediaPos=1800.00, window=0, period=0, READY]
2022-11-16 14:11:18.881 24711-24711 Choreographer           com.google.android.exoplayer2.demo   I  Skipped 39 frames!  The application may be doing too much work on its main thread.
```

### Reproduction steps

1. Load an HLS video with exoplayer
2. Play it
3. Pause the video
4. Use the slider or the fast forward button to go till the end of the video

### Expected result

When the current position is at the end of video, I expect that `onPlaybackStateChanged` is triggered with state = `STATE_ENDED`

### Actual result

`onPlaybackStateChanged` is not triggered.
If I press the play button, the `onPlaybackStateChanged` with state = `STATE_ENDED` is triggered. 

### Media

This issue looks like https://github.com/google/ExoPlayer/issues/3918

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
This is a bit of an edge case where it depends on the exact interpretation of these state to know which one is "correct". We concluded that everything is working as intended because the seek itself end up just *before* the end of the video to display the last frame. So while the player is paused, you haven't technically reached the end yet because the player is in a state where it rendered the last frame and as soon as you "play" again, it will handle the end of stream signal and transition to the ENDED state.

Another example that makes this potentially more obvious is a playlist of multiple items. Instead of the ENDED state, the player starts showing the frames of the next video once it reached the end of the previous one. Note that that these two transitions are basically the same end of stream signal handling:
_"Transition to ENDED state at the end of the playlist == Transition to the next item within a playlist"_ 
If you seek the end of an item in the playlist while paused, the clear expectation is that the player shows the last frame of the current item and not the first frame of the next item. So again we expect not to make this equivalent transition while paused.

**Comment by ThibaultBee** [comment]
Ok, thank you for your answer.
I am trying to add a specific icon for replay when the player is at the end of the video (even when the user seek while the player is in pause state). Is there a way to detect that we are at the end of the video or at the last frame in `onPositionDiscontinuity`?

**Comment by tonihei** [comment]
You can probably compare the position and the duration in the `onPositionDiscontinuity` callback. Just curious: did you receive user feedback that they expect to see the replay button when they seek to the end while paused? It's non-obvious to me what the expected UI behavior is in such a case and as a user I wouldn't be surprised to only see the replay button once I actually played the last bit of the stream.

**Comment by ThibaultBee** [comment]
It is not easy to compare the new position and the duration in the `onPositionDiscontinuity` because there are not equals. I notice that there are a small time difference between both.
It is a behavior that we have on our other players and we wish to implement it on our Android player as well.

**Comment by tonihei** [comment]
Yes, this is the time difference indicating you haven't actually reached the end of playback on a technical level. For the user-facing UI, I think you'd need some form of threshold between position and duration to show this button. If I think of a full-length movie, I would expect the UI changes for the end of playback to happen as soon as I reach the credits (e.g. a long time before reaching the technical end of the stream). If you take this example, it doesn't sound too surprising to choose a threshold at which you want to show a replay button.
