### ISSUE TITLE
Video content freezes for 1-5sec before playing when postroll is present via IMA

### ISSUE THREAD

**Issue by natrubin24** [google/ExoPlayer#10792]
### ExoPlayer Version

Older (unsupported)

### Devices that reproduce the issue

Any FireTV device

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Download and open the IMDb What to Watch app on any FireTV device (sign in not required)
2. Navigate to the This or That or Time Machine game
3. Play through either of the games until a fullscreen video that says "Intermission" appears
4. Notice the 2-5 second pause before the countdown timer appears in the bottom right of the video.

### Expected result

Video content ("Intermission" screen/video) does not show frozen frame before playing (experience when ad is not present)

### Actual result

When preroll ad is loaded using IMA, video content appears frozen for 1-5 seconds before playing. The duration of frozen video is longer on older devices.

### Media

https://user-images.githubusercontent.com/117224058/202594177-b96d5bae-c18b-429b-bc9c-0a3a8eef0aaa.mov

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Are you using the FireTV fork of ExoPlayer and this only reproduces on FireTV devices? If so, I would suggest reporting it to the maintainers of that project: https://github.com/amzn/exoplayer-amazon-port

If this reproduces on other devices and you'd like us to look into it then we need source-based repro instructions - ideally using our demo app. We can't investigate how our library is used within an APK installed from the Play Store, as we don't have the necessary insight into how our library is being used or modified in that situation (since it's already compiled and obfuscated).
