### ISSUE TITLE
Value of getDuration at CONTENT_RESUME_REQUEST when ads are skipped

### ISSUE THREAD

**Issue by pineapplevine** [google/ExoPlayer#10797]
Hello.
We want to get the duration of the content by getDuration.
If we do not skip the ad, we can call getDuration on the CONTENT_RESUME_REQUESTED event of AdEventListener to get the duration of the content.
However, if the ad is skipped, calling getDuration on the CONTENT_RESUME_REQUESTED event of AdEventListener will get the duration of the ad.
Please confirm this issue as we believe it is an internal processing bug in ExoPlayer.

We believe the problem lies in the following isPlayingAd() process.
```
<ExoPlayerImpl.java>
public long getDuration() {
    verifyApplicationThread();
    if (isPlayingAd()) {
      MediaPeriodId periodId = playbackInfo.periodId;
      playbackInfo.timeline.getPeriodByUid(periodId.periodUid, period);
      long adDurationUs = period.getAdDurationUs(periodId.adGroupIndex, periodId.adIndexInAdGroup);
      return Util.usToMs(adDurationUs);
    }
    return getContentDuration();
  }
```

### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Pixel5 running Android13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the attached media in the demo app
2. Skip the pre-roll ad
3. Get duration on CONTENT_RESUME_REQUESTED event

### Expected result

We can get the content duration.

### Actual result

We get the ad duration.

### Media

・Single skippable inline
uri:https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv
ad_tag_uri:https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Adding a listener directly on the ads SDK (=adding a custom `AdEventListener`) means you get events at the same time as the player and thus the updates triggered by these events haven't happened yet in the player itself. That's why the player state is still `isPlayingAd()` true and `getDuration()` correctly returns the ad duration. You can also always get the content duration even while an ad is playing by calling `player.getContentDuration()`.

If you want to listen to ad-content transitions in the player, I'd recommend to listen to `Player.EventListener.onPositionDiscontinuity`, which has detailed information about the transition and a reason. The reason for CONTENT_RESUME_REQUESTED would likely be DISCONTINUITY_REASON_SKIP.
