### ISSUE TITLE
Seek in AAC

### ISSUE THREAD

**Issue by rimeissner** [google/ExoPlayer#1079]
According to #227 it is not supported to seek in an AAC stream. Is it somehow possible to implement this feature?

I need to seek within a AAC file that is shorter than 10 seconds and is stored on the clients device. 

Any pointers would be appreciated.

**Comment by andrewlewis** [comment]
Is it possible to put the media in a container where we support seeking, like MP4 or Matroska?

As noted in #227, to seek in a .aac file (using AdtsExtractor) it seems that it is necessary to build an index having read the whole file, which is generally not efficient.

**Comment by rimeissner** [comment]
Thanks for the answer, I will put the stream file into an mp4 container

**Comment by pottabathini** [comment]
@andrewlewis 
I am sorry to comment in a closed thread, but I think this is good place to add my comment to know more information/ example form you.

I red above comment there you written 

> Is it possible to put the media in a container where we support seeking, like MP4 or Matroska?

Can you give example on this, I am playing MP4 video so I hope there is a chance of seek from your answer. If you give sample code or example that would be great.

**Comment by andrewlewis** [comment]
@pottabathini Is there a specific problem you are seeing? Seeking in unfragmented MP4 and fragmented MP4 files with indices should just work.

**Comment by pottabathini** [comment]
@andrewlewis  When I seek forward it is just working fine but when I seek backward, buffered content also going and again it is buffering from the seek position 

I need a behaviour my buffered video should stay when I seek backward it should not again load, is there any specific settings we need to do?

Please guide me to overcome this. 
Thank you

**Comment by andrewlewis** [comment]
I'm afraid this is working as intended for the current design. See #896 and #978.

**Comment by pottabathini** [comment]
@andrewlewis  Sorry andrew I thought we need to change some settings to work this, as per your answer this is a code level change.

I am using Xamarin bindings for your ExoPlayer which is written by @martijn00 [https://github.com/martijn00/ExoPlayerXamarin](url)  

Unfortunately he is still in .4 version only. I will check with him to update xamarin andorid bindings. 

Thank you

**Comment by andrewlewis** [comment]
We do not currently support retaining data before the current playback position, so you will always see buffering when seeking backwards, even in the latest version. Sorry if I wasn't clear in my previous reply.

As per the linked issues, we might change this behavior so that we only discard data if it's possible to buffer more future media (for example, if the entire stream fits in the buffer) but this is not a priority at the moment.

**Comment by andrewlewis** [comment]
Correction: we might change this behavior so that we only discard data if it's _impossible_ to buffer more future media (for example, if the entire stream fits in the buffer)

**Comment by pottabathini** [comment]
yes, sounds good but as per your response you guys are not taking this has priority to implement as of now :-(

Unfortunately for my project it is very high priority where user see the videos of time less than 3 to 5 minutes. if he is in mobile data when he seek to and fro few times it will keep on load and it will consume more mobile data

**Comment by andrewlewis** [comment]
Please ignore the previous correction! I meant to write that: we might change this behavior so that we only discard data if it's possible to buffer more future media. If the entire stream fits in the buffer, there is no more media to buffer, so the played data wouldn't be discarded.

Sorry the current functionality is suboptimal for your use case.
