### ISSUE TITLE
Files encrypted using AesCipherDataSink takes a lot of time (for playback to start). 

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#10805]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Oneplus Nord 2
Samsung f62

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Encrypt and write a file to disk using AesCipherDataSink
2. try to play it. 
playback will take good 10-15 secs to start, based on the device performance.

please note that i am using AesCipherDataSource with no modifications to read.

### Expected result

The playback should start instantly.

### Actual result

Playback takes a lot of time.

### Media

Not applicable

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
There are multiple parameters that affect playback start-up time, for example, custom load control settings just to name one. Therefore, the issue could be related to the AesCipherDataSink that you mention, but there may be other factors in play too, such as custom configurations in your app.

Can you make changes on the  [demo app](https://exoplayer.dev/demo-application.html) to play your content and check if the issue reproduces there? If yes, please share your test content and your code changes on the app (can be a simple patch) so that we reproduce too. Also share a bug-report obtained right after the issue occurs on your device.

Note that If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly on this issue, you can send them to dev.exoplayer@gmail.com with subject "Issue #10805". Please also update this issue to indicate you've done this.

Thanks
