### ISSUE TITLE
Track a player's audio track progress

### ISSUE THREAD

**Issue by dimitradg** [google/ExoPlayer#10812]
As I understand, there is no progress event listener implementation within ExoPlayer, and that is because it would need multiple API calls.

What I would like to ask is if there is a workaround to capture an audio's progress. What I would like to implement is the following:

I have player A which constantly plays a background music, and I have player B which plays a playlist of tracks. When the playlist of player B is done, player A also stops (also when play and pause buttons are pressed.)

I would like to reduce the volume of player A when a track on player B starts ("fade out") and increase the volume of player A when a track on player B ends ("fade in") in order to create background effects. Therefore I would like to capture player B's each track progress so I can make changes e.g. during the last 3 seconds and the first 3 seconds of each track of player A.

Any ideas?

**Comment by christosts** [comment]
There are multiple events raised from the player that can work for your use case. You can start with the [Player events](https://exoplayer.dev/listening-to-player-events.html) page. There are explicit events when playback starts/pauses/ends and making transitions between media items in a playlist. By describing your use-case, it sounds like you might an event just before the media item reaches its end, so you can volume-down for the last few seconds. Can you read how to [Fire events at specified playback positions](https://exoplayer.dev/listening-to-player-events.html#firing-events-at-specified-playback-positions) for this.

Since you mentioned fade-in and fade-out, you could also experiment with a custom [audio processor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html), to lower the volume of the stream by modifying the audio samples directly, rather than setting the volume (multiple times?). This might create a smoother result, but AudioProcessors can be applied to specific kind of audio playback only, and of course you need to dive into audio samples processing yourself. I'm afraid we don't have a documentation page set up for custom audio processors, but you can find plenty of [info searching in the tracker](https://github.com/google/ExoPlayer/issues?page=2&q=custom+audioprocessor).

I'll close this issue as I think the documentation about events will help you for your use-cases, feel free to re-open if you need more information.
