### ISSUE TITLE
HDR support on ExoPlayer with DASH Live stream

### ISSUE THREAD

**Issue by He12345678901** [google/ExoPlayer#10837]
Unfortunately we can't answer all questions. Unclear questions or questions with
insufficient information may not get attention.

Before filing a question:
-------------------------

- Ask general Android development questions on Stack Overflow
- Search existing issues, including issues that are closed
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website (https://exoplayer.dev/) and Javadoc
  (https://exoplayer.dev/doc/reference/)

When filing a question:
-------------------------

Describe your question in detail.

In case your question refers to a problem you are seeing in your app:

- Output of running `$ adb bugreport` in the console

In case your question is related to a piece of media:

- URI to test content
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

Don't forget to check supported formats and devices
(https://exoplayer.dev/supported-formats.html).

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

**Comment by He12345678901** [comment]
Hi
first I'd like please to understand which HDR standards supported on ExoPlayer version 2.13.2  - HDR10, HDR-PQ10 and HLG - which ones of those is being supported with DASH Live ?
also, what is the exact required manifest signalization needed for the HDR in order for ExoPlayer to present it properly on the screen? I have tried HDR-PQ10 with the following parameter in the manifest MPD and the video quality was degraded  - is there another set of manifest tag (such as in AdaptationSet) required to signalize HDR-PQ10 for ExoPlayer ?
```
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash-if-uhd#hevc-hdr-pq10"
```

what's the required dash manifest signalization for HDR-HLG on ExoPlayer ?
thanks

**Comment by He12345678901** [comment]
hi

any update please ?
thanks

**Comment by christosts** [comment]
Please read [HDR video playback](https://exoplayer.dev/supported-formats.html#hdr-video-playback). ExoPlayer does not parse HDR specific data on DASH manifests but it will detect the presence of HDR when parsing the actual bitstream for some formats and try to find a decoder with matching capabilities on the device. It is then up to the app to select playing those tracks or not based on the display capabilities. That said, there are have been some fixes on parsing HDR metadata from mp4 containers after 2.13.2, so it could be possible that your app is hitting those bugs.

> I have tried HDR-PQ10 with the following parameter in the manifest MPD and the video quality was degraded

It will be easier to help you if you provide us concrete DASH manifests and content to test ourselves, and also provide information on what device you tested and a bug-report (the information that is available on the issue description basically).

**Comment by He12345678901** [comment]
Hi
thanks for your replay,
please find a Live dash manifest example, where HDR signaling in manifest is the following one:
http://dashif.org/guidelines/dash-if-uhd#hevc-hdr-pq10"
[Live_Dash_HDR-PQ10_MPD.txt](https://github.com/google/ExoPlayer/files/10201954/Live_Dash_HDR-PQ10_MPD.txt)
1. question is if version 2.13.2 has some bugs on this type of HDR metadata parsing, where this metadata is within this attribute in MPD: http://dashif.org/guidelines/dash-if-uhd#hevc-hdr-pq10"
2. should I try to check HDR of the same manifest over an advanced ExoPlayer version ? should I expect differ video quality in respect to HDR ? which ExoPlayer version is recommended in this case to test with ?
3. device we tested is Android10 and above and the resulted video quality is degraded given this HDR signaling in manifest
thanks.

**Comment by christosts** [comment]
> device we tested is Android10 and above and the resulted video quality is degraded given this HDR signaling in manifest
thanks.

 Please do the following:

1. Please clarify what you mean by video quality degradation. Is it just the resolution or also the colour that looks worse?
2. Please share the content with us. That is, we need a working URL to the DASH manifest so that we can test and inspect the stream. Do not attach the manifest directly on the issue. Ideally, we need two URLs, one to the manifest without the HDR metadata, and one to the manifest with the HDR metadata (which you say the video quality is degraded).
3. Please specify what device you are seeing the issue with. Have you observed this on a Pixel device for example? It's easier for us to test with Pixel devices.
4. Please attach two [bug reports](https://developer.android.com/studio/debug/bug-report) obtained from the device you're testing. The first bug report should be with the first manifest (without HDR metadata) and the second one after playing the manifest with the HDR metadata (which shows degraded quality).

If you're unable to share the above publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #10837" and update this issue to indicate you've done this.

As mentioned above, ExoPlayer does not parse HDR metadata from manifests but it parses the HDR data directly from the bitstream and passes them directly to the decoder. In general we ask developers to use the most recent release as we are improving the library and fix bugs. I'd like to inspect your content before suggesting a specific version.

**Comment by He12345678901** [comment]
Hi
1. by video quality degradation I mean that color looks worse
2. I have sent to you by email the URL (but only with HDR metadata)
3. this info you'll find in the email
4. you'll find 2 bug reports on the email sent with subject "Issue #10837"
please check and update
thanks a lot

**Comment by christosts** [comment]
I got your email. 

First, when I try to open the link, it returns an HTTP 403. I tried with a couple of browsers, and also with ExoPlayer from the demo app. Can you please make sure the URL is reachable from us. Eg, is it geofenced, do we need to pass certain HTTP headers, or can the link be valid for a long of period of time (I noticed the stream is live)?

Ideally, we'll take the URL and try it in the [demo app's exolist.json file](https://exoplayer.dev/demo-application.html#1-editing-assetsmediaexolistjson) directly.

Second, for the bug-reports please attach the entire zip file that is created from the `adb bugreport` command.

**Comment by He12345678901** [comment]
Hi
the link is valid for your period of test - do you have a specific source public IP address I can white-list for you to access the link ?
I'll check for this entire zip of bug report
thanks

**Comment by christosts** [comment]
> do you have a specific source public IP address

No, I'm afraid I don't have a specific IP and don't control that. We have the ability to VPN, so if the link geo-restricted to a specific country, we can use a country-based IP address.

**Comment by He12345678901** [comment]
is it possible for you to assist based on full bug reports (I'll provide) and manifest of the stream without playing it ?
thanks

**Comment by christosts** [comment]
I'll take a look at what you can provide and let you know. Just to summarize
- ExoPlayer does not parse HDR-specific metadata from DASH manifests.
- Since you say you see a degradation in colours,  there may be something else involved which could be (i) an ExoPlayer bug, (ii) content is not valid, (iii) a device-specific issue.
- I want to read the manifest to see the codec string used for video.
- I also want test the stream to see if the actual content is consistent with the manifest, hence why I ask for a working url and not just a copy of the manifest.
- I may not be able to reproduce the issue with the devices in my disposal, hence the ask for the bug-reports which may reveal an issue specific to the devices you are using.

**Comment by He12345678901** [comment]
Hi
I have sent the full bug report zip files into your email [dev.exoplayer@gmail.com]
thanks

**Comment by He12345678901** [comment]
Hi
any update ?
thanks

**Comment by christosts** [comment]
Sorry for the delay

From the bug reports, I noticed this log

```
01-01 02:00:21.109  1000  3664  3692 I DisplayManagerService: Display device added: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:15352497257671956", 1920 x 1080, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1920, height=1080, fps=50.0, xDpi=81.28, yDpi=80.682}], colorMode 0, supportedColorModes [0], HdrCapabilities android.view.Display$HdrCapabilities@40f16308, density 320, 81.28 x 80.682 dpi, appVsyncOff 1000000, presDeadline 20000000, touch INTERNAL, rotation 0, type BUILT_IN, address {port=20, model=0x368b03d1756d}, state UNKNOWN, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
```

with the important part being `HdrCapabilities android.view.Display$HdrCapabilities@40f16308`. Unfortunately,  HdrCapabilities does not override `toString()` so I can't really tell what the log is reporting. I noticed the device is a set-top-box. Is the device connected to a monitor over HDMI? Can you please check what [Display.getHdrCapabilities().getSupportedHdrTypes()](https://developer.android.com/reference/android/view/Display.HdrCapabilities#getSupportedHdrTypes()) returns? 

It could be that there is mismatch between the content's HDR version and the display's HDR version and the display maybe just convert the HDR stream to SDR (with washed out colors). Note that to verify this theory, we'd need to double check the content too. 

Are you seeing the issue on the specific device/display set up? For example, does the issue happen when playing the content on a relatively new phone that has an HDR screen?

**Comment by He12345678901** [comment]
Hi
thanks for your response,
we had tried to run the [Display.getHdrCapabilities().getSupportedHdrTypes()] and got:
HDR10+ display
any more thoughts how to proceed ?
thanks

**Comment by christosts** [comment]
Thanks. In general, if colors look worse, it means the display does not support the stream's HDR version. In general, ExoPlayer does not avoid HDR tracks when connected to a display that does not support them, and this is something that we plan to address soon. 

However, your display is HDR10+ and I'd assume that any HDR10/HDR10+ content would display fine. It could be that the actual video was encoded with a different HDR version, or that the player failed to parse the content correctly. At this point, I'd need a working manifest so that we inspect the content and figure out what's wrong.

**Comment by He12345678901** [comment]
Hi
only manifest is sufficient for you ?
thanks
[Live_Dash_HDR-PQ10_MPD.txt](https://github.com/google/ExoPlayer/files/10401863/Live_Dash_HDR-PQ10_MPD.txt)

**Comment by christosts** [comment]
I'm afraid not, it's the content we need to inspect

**Comment by christosts** [comment]
Please ignore the bot responses, I'm removing the `stale` label, and keep this issue open for parsing the DASH specific HDR labels which are currently not parsed by ExoPlayer.
