### ISSUE TITLE
notification using playerNotificationManager not showing playback controls in android 13

### ISSUE THREAD

**Issue by maknon** [google/ExoPlayer#10857]
Hi,

I have compiled the same code in android 9 & 13
the playback controls is shown in android 9 notification but not in android 13. not sure if this is a behavioural things between the android versions but how can i have the same controls in all versions.

I tried also to set it manually without success e.g.
```
playerNotificationManager.setUseFastForwardAction(true);
playerNotificationManager.setUseFastForwardActionInCompactView(true);
playerNotificationManager.setUseRewindAction(true);
playerNotificationManager.setUseRewindActionInCompactView(true);
```

also i have CustomActionReceiver that is not shown as well

any support is appreciated

**Comment by marcbaechinger** [comment]
If your app is on targetSdk 33 or higher and running on Android 13, then the miniplayer is based on the media session rather than on the notification. So you need to add the actions and custom actions to the media session by replicating the actions on the notification with the `MediaSessionConnector`.

Please find the information about changes in Android 13 with this document: https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls

**Comment by maknon** [comment]
thank you @marcbaechinger. 
i will use targetSdk 32 for the time being until the migration to media3. there is a lack of examples on how to adapt all of these changes and it takes a lot of time until you reach a workable piece of code.

**Comment by YogeshSinghPathania** [comment]
Hi i found the solution Please upgrade the liberary in 2.16.1
and than use these property
  notificationManager.setUseRewindAction(true)
        notificationManager.setUseFastForwardAction(true)
