### ISSUE TITLE
How can EXO directly use the framework's capabilities? 

### ISSUE THREAD

**Issue by RexSuper** [google/ExoPlayer#10885]
My device is a deeply customized Android device. The underlying supports various software and hardware solutions. How can EXO directly use the framework's capabilities? For example, FLV queries tell you that you have said that you will not continue to support more complex FLVs, but my device has already been supported by using mediacotec directly. If you use the exo shell and the device's software and hardware solutions, please give me a hard answer

**Comment by RexSuper** [comment]
Let me give another specific example. For example, exo's flv does not support H263, but my device framework supports it. How can I set exo to go to the framework's MediaCodec instead of directly throwing an exception "Video format not supported: 2"

**Comment by tonihei** [comment]
ExoPlayer checks support using the `MediaCodecInfo` objects provided by the system (search for "supportsFormat" in ExoPlayer to see relevant code snippets). If your customized Android device supports a certain format, it should declare it through the usual channels so that app code like ExoPlayer can query it. Writing a custom Android version is a bit outside of the scope of this issue tracker, so we won't be able to help you with the details there.

**Comment by tonihei** [comment]
Closing the issue as the question was answered.
