### ISSUE TITLE
How to signal that the activation status of an `AudioProcessor` has changed?

### ISSUE THREAD

**Issue by OxygenCobalt** [google/ExoPlayer#10896]
As an optimization, I try to avoid "no-op" scenarios that would require an expensive copy in my `AudioProcessor` by overriding `isActive` and returning `false` if the `AudioProcessor` has nothing to do. The issue is that the activation status can change during playback, and I've recently realized that ExoPlayer is highly inconsistent in when it checks if the `AudioProcessor` is active. 

For example, if the `AudioProcessor` was *active*, then became *inactive*, and then became *active* again, ExoPlayer picks up on it immediately. However, if the `AudioProcessor` starts *inactive* and then becomes *active*, ExoPlayer does not pick up on it until the next `MediaItem` plays. This results in really in-explicable issues in my app.

Is there a way to signal ExoPlayer to always re-check my `AudioProcessor` when it's activation status changes? There should be some way to do it given that `SonicAudioProcessor` could feasibly change it's activation status during playback too. Without this, I'm stuck either with this inconsistent behavior or removing the `isActive` optimization entirely and doing a copy when there's nothing to do, neither of which are desirable in any capacity.

Any help here would be appreciated.

**Comment by tonihei** [comment]
Your observations fit the current implementation:
Whether `AudioProcessors` are active or not is evaluated only once during set up. And they are only reset when the chain of processors if flushed (e.g. when the format changes, a new item starts playing or new `PlaybackParameters` are applied). The reason for this is that the chain of processors takes the output format of one processor and uses it as input format for the next processor in the list. If you suddenly deactivated a processor in a chain without flushing, the input format wouldn't match anymore. Moreover, if the chain suddenly produces a new output format (e.g. because some processors got activated/deactivated), the entire AudioTrack needs to be flushed. 

There are probably two ways in which you can make this work:
 1. *Change your audio processor to be a no-op, but leave it active*: This still requires one copy of the audio data. You mentioned that you consider this expensive, but given it's just audio data it shouldn't be too bad. The implementation can call `replaceOutputBuffer(inputBuffer.remaining()).put(inputBuffer).flip()` from `queueInput` (assuming you overwrite `BaseAudioProcessor`). This should also avoid any additional memory allocations mid-playback.
 2. *Treat this as a feature request to force a audio processor chain flush/re-configure*: There is currently no way for you to do this without interrupting playback. We could add a method to `DefaultAudioSink` that lets you reconfigure the audio processors mid-playback. This is non-trivial and we are unlikely to address this soon.

**Comment by OxygenCobalt** [comment]
Okay, I'll just do a copy then and take the worse performance on high-bitrate files.
