### ISSUE TITLE
widevine DRM cbcs content decode error

### ISSUE THREAD

**Issue by sridhard** [google/ExoPlayer#10890]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Vivo 1907, Android 11

Issue happens in few devices in multiple brands like vivo, oneplus, redmi. 

### Devices that do not reproduce the issue

cbcs works in samsung, vivo, oneplus, redmi etc. Issue happens only in few devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

Just play the CBCS encrypted video.

### Expected result

Video should play successfully

### Actual result

video decode fails with the following crash:

{"error":{"errorStackTrace":"com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 1322752, null, [1970, 1080, 25.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:257)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC.secure\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 3 more\nCaused by: java.lang.IllegalStateException\n\tat android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)\n\tat android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)\n\tat com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1806)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)\n\t... 5 more\n","errorCode":"24003","errorException":"MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 1322752, null, [1970, 1080, 25.0], [-1, -1]), format_supported=YES","errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}

### Media

This does not happen for specific media file. If it happens in user device, it happens for all videos

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Could you send a full bugreport as requested in the template? Please send it to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with "Issue #10890" in the subject line and then leave a comment here so we know you've sent something. 

@rrfrias: This looks like a DRM issues on these devices, please have a look once the bugreport is provided.

**Comment by rrfrias** [comment]
@sridhard can you mention the models you have seen this problem on Vivo, OnePlus, Redmi other than Vivo 1907? A full bugreport would be helpful if possible. 

An app with repro steps would also be helpful. Instructions for where to send the app/repro steps/bugreport are mentioned in the previous comment.

We also need your permission to share the app with Vivo/OnePlus/Xioami to investigate furthur.

**Comment by sridhard** [comment]
@rrfrias We are nit able to reproduce the issue in our devices, It happens in multiple customer devices.

**Comment by rrfrias** [comment]
@sridhard: The team looking into this issue needs a bugreport to make progress since it is device specific. Unfortunately the stack trace you shared did not contain sufficient information to root cause. If users report the issue to you (rather than through analytics) here are steps to capture https://developer.android.com/studio/debug/bug-report . Or you can share through the internal tracker that you opened with Google.

Internal ref: 264681114

**Comment by golottie-jens** [comment]
Hi,
We are seeing a very similar Exception when trying to play Widevine-DRM content on certain devices. It works fine on most devices, but crashes on at least one that we know of. This is the Amazon Fire. Here is the log that we see (this is from a flutter app using the [betterplayer library](https://pub.dev/packages/better_player), so we are not using exoplayer directly):

> I/ExoPlayerImpl(20468): Init 3f55838 [ExoPlayerLib/2.17.1] [onyx, KFONWI, Amazon, 28]
E/System  (20468): TRACE Starting certificate trust
D/CRLSetManager(20468): getInstance binder: android.os.BinderProxy@a2b78f9
I/MediaDrm(20468): Drm event (1,0)
E/System  (20468): TRACE Starting certificate trust
D/CRLSetManager(20468): getInstance binder: android.os.BinderProxy@a2b78f9
I/OMXClient(20468): IOmx service obtained
D/SurfaceUtils(20468): connecting to surface 0xb72d1808, reason connectToSurface
I/MediaCodec(20468): [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 20959233
D/SurfaceUtils(20468): disconnecting from surface 0xb72d1808, reason connectToSurface(reconnect)
D/SurfaceUtils(20468): connecting to surface 0xb72d1808, reason connectToSurface(reconnect)
I/MediaCodecLogger(20468): [ASAP] HW.video.avc P2 + 10249922
I/MediaCodecLogger(20468): HW.video.avc Adaptive Streaming max w:1280 h:720, screen size:SD
I/ACodec  (20468): codec does not support config priority (err -1010)
I/MediaCodecLogger(20468): [ASAP] HW.video.avc P2 - 10249935
D/MediaCodecLogger(20468): Got amazon_media_codec_logger Service. Calling PID = 20468
I/MediaCodecLogger(20468): [ASAP] HW.video.avc P3 + 10249937
E/System  (20468): TRACE Starting certificate trust
D/CRLSetManager(20468): getInstance binder: android.os.BinderProxy@a2b78f9
D/SurfaceUtils(20468): set up nativeWindow 0xb72d1808 for 640x360, color 0x7f000001, rotation 0, usage 0x402933
W/ACodec  (20468): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 6 failed: -22
W/ACodec  (20468): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 5 failed: -22
I/MediaCodecLogger(20468): [ASAP] HW.video.avc P3 - 10249977
I/MediaCodecLogger(20468): [ASAP] HW.video.avc Got First Input Frame 10249979 pts:0
W/MapperHal(20468): buffer descriptor with invalid usage bits 0x2000
I/OMXClient(20468): IOmx service obtained
I/MediaCodecLogger(20468): [ASAP] SW.audio.mp4a P2 + 10250038
I/ACodec  (20468): codec does not support config priority (err -2147483648)
I/MediaCodecLogger(20468): [ASAP] SW.audio.mp4a P2 - 10250042
D/MediaCodecLogger(20468): Got amazon_media_codec_logger Service. Calling PID = 20468
I/MediaCodecLogger(20468): [ASAP] SW.audio.mp4a P3 + 10250044
D/SurfaceUtils(20468): set up nativeWindow 0xb72d1808 for 640x360, color 0x7f000001, rotation 0, usage 0x402933
W/ACodec  (20468): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 18 failed: -22
W/ACodec  (20468): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 17 failed: -22
W/MapperHal(20468): buffer descriptor with invalid usage bits 0x2000
I/MediaCodecLogger(20468): [ASAP] SW.audio.mp4a P3 - 10250066
I/MediaCodecLogger(20468): [ASAP] SW.audio.mp4a Got First Input Frame 10250071 pts:0
E/MediaCodecVideoRenderer(20468): Video codec error
E/MediaCodecVideoRenderer(20468):   android.media.MediaCodec$CodecException: Error 0x80000000
E/MediaCodecVideoRenderer(20468):       at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
E/MediaCodecVideoRenderer(20468):       at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
E/MediaCodecVideoRenderer(20468):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
E/MediaCodecVideoRenderer(20468):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
E/MediaCodecVideoRenderer(20468):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
E/MediaCodecVideoRenderer(20468):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
E/MediaCodecVideoRenderer(20468):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
E/MediaCodecVideoRenderer(20468):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(20468):       at android.os.Looper.loop(Looper.java:193)
E/MediaCodecVideoRenderer(20468):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(20468): Playback error
E/ExoPlayerImplInternal(20468):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.64001E, 1619122, null, [640, 360, 25.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
E/ExoPlayerImplInternal(20468):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(20468):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal(20468):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(20468):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
E/ExoPlayerImplInternal(20468):       ... 3 more
E/ExoPlayerImplInternal(20468):   Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
E/ExoPlayerImplInternal(20468):       at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
E/ExoPlayerImplInternal(20468):       at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
E/ExoPlayerImplInternal(20468):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
E/ExoPlayerImplInternal(20468):       ... 5 more
W/MapperHal(20468): buffer descriptor with invalid usage bits 0x2000
I/chatty  (20468): uid=10174(com.totoli.client) CodecLooper identical 9 lines
W/MapperHal(20468): buffer descriptor with invalid usage bits 0x2000
D/SurfaceUtils(20468): disconnecting from surface 0xb72d1808, reason disconnectFromSurface
I/MediaCodecLogger(20468): 20468.secure.HW.video.avc.ASAP-P2Ms = 13
I/MediaCodecLogger(20468): 20468.secure.HW.video.avc.ASAP-P3Ms = 40
I/MediaCodecLogger(20468): 20468.secure.HW.video.avc.FirstFrameReadyMs = -10249979
W/MediaDrm(20468): MediaDrm went away with unhandled events
W/MediaDrm(20468): MediaDrm went away with unhandled events

Does this help? Is there something we could try? Or some more info we could provide you with?

Thanks,
Jens
