### ISSUE TITLE
Some devices not able to play EAC3 audio with external speakers

### ISSUE THREAD

**Issue by Bhupesh71** [google/ExoPlayer#10914]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

![IMG_20230110_113640_2](https://user-images.githubusercontent.com/78247191/211475000-aaf5226e-d293-491a-9262-ca6a7d49fd91.jpg)

External speakers: Model - SA-WS500RF

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Launch ExoPlayer demo app
2. Play any content.

### Expected result

Should be audible when using external speakers all the time.

### Actual result

Content is audible using external speakers only on first playback after device start, all subsequent playback do not have audio output through external speakers.

### Media

Will send to dev.exoplayer@gmail.com 

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
In the bug-report there's one playback attempt. Did audio sound play? I do see an error output from the platform audio system after the player is released but I can't tell if that's related or not:

```
01-10 12:14:56.163  1041  1224 10848 W StreamHAL: Error from HAL stream in function pause: Unknown error -1
01-10 12:14:56.164  1041  1224 10848 E AudioFlinger: Error when pausing output stream: -61
```

What happens when there is no audio out? Does video play? If yes, that means that the platform's AudioTrack is advancing the playback position, so for ExoPlayer things look as if everything is working ok. What if the second playback attempt is not EAC3 but some other format (preferably AAC)?

Have you tried this with any other combination of devices (different TV & same speakers, same TV & different speakers)?
