### ISSUE TITLE
Video and audio do not send to Casting Receiver

### ISSUE THREAD

**Issue by CDKCTS** [google/ExoPlayer#10917]
I'm trying to implement casting based off the Casting Example included in this repo and I'm running into some problems.

To start though, my ExoPlayer versions are all 2.18.1 and because of that, I am using the deprecated CastContext.getSharedInstance, since I'm getting some annoying async issues using an executor and I just need to get this working for now before figuring that problem out. I have implemented the PlayerManager near identically, with the exception of adding some extra control over the MediaRouteButton. In alignment with implementing the PlayerManager near identically, I have included all I can from MainActivity into my own activity, with the next exception being that I am not implementing any kind of playlist behavior, so I have some of the code relating to such view removed. From my analysis, it does not seem like anything removed should be related to my issue, but I also only know so much.

To finally describe my issue, I am able to get the casting button to show and connect to my Chromecast, but once I do, nothing gets sent over; I just get a screen with the casting icon. Over on my tablet, the video stops, but the audio continues. If I disconnect and reconnect, the same behavior happens but I now have two audio sources at once. They do not stack further beyond this. I'm really at a loss as to what's happening and why my video isn't being sent over. The video has been working on the ExoPlayer for months so as far as I'm aware, it shouldn't be a support issue.

Any help would be appreciated. I am emailing my code to the provided email address, but if there is any other context missing, please let me know. I also apologize in advance for any ignorance, as I inherited this codebase without documentation or dev help, so I am only so knowledgeable on how it works.

**Comment by marcbaechinger** [comment]
Unfortunately we can't give you 1:1 support for your app I'm afraid. If you think something is wrong with the library please narrow down your question so we can investigate whether the library has an issue. Best is to demonstrate an issue in the demo app. 

Sorry for not being able to give you a better answer.

**Comment by Congtie** [comment]
It sounds like you're encountering an issue where the video is not being sent to the Chromecast, while the audio continues to play on the device. This could be caused by a number of factors, including issues with the media format of the video file, problems with the ExoPlayer configuration, or issues with the way the video is being sent to the Chromecast.

One thing to check is the format of the video file you are trying to cast. Chromecast supports a limited number of video codecs and container formats, so it's possible that the video file you're trying to cast is not supported. You can check Chromecast's supported media formats here: https://developers.google.com/chromecast/docs/media

Another thing to check is the configuration of the ExoPlayer. Make sure that the ExoPlayer instance is correctly configured to play the video file, and that the appropriate codecs and renderers are being used.

Additionally, check the way the video is being sent to the Chromecast. Make sure that the correct video track is being selected and that the video is being sent in the correct format. It's also worth checking the logs of the Chromecast device to see if there are any error messages or issues that may be causing the video to not be sent.

It's also possible that the issue is related to the specific version of ExoPlayer you're using (2.18.1) which may have some known bugs or compatibility issues with Chromecast. You may consider upgrading to a more recent version of ExoPlayer.

If none of these solutions work, please share your code and I will be happy to take a closer look and see if there's anything else that might be causing the issue.

**Comment by CDKCTS** [comment]
I was able to get through these issues but am running into new ones concerning our HLS videos. I have made a new thread in the Issue Tracker, so this ticket can be closed. Thank you for all the information.
