### ISSUE TITLE
Expect exoplayer could continue to play although the meta of video is invalid.

### ISSUE THREAD

**Issue by joechan-cq** [google/ExoPlayer#10911]
### [REQUIRED] Use case description
Some videos have the invalid meta block, for example:
![image](https://user-images.githubusercontent.com/9456005/211250147-21a425ad-338b-4619-81e0-5c1e1edb189d.png)
this video is only 5MB. The Audio and Video trackers are valid.

Exoplayer can't play this video, it would throw `InvalidResponseCodeException: Response Code 416`. However, chrome, desktop and ffplay can play the video. I'm not good at media development, and for the protection of user privacy, I can't provide the video or other detailed message. 

### Proposed solution
Is it possible that skip the throw-exception step that read and parse the unnecessary data, so that exoplayer can continue to read and parse the next data, finally play the video successfully.

#3123

**Comment by christosts** [comment]
> for the protection of user privacy, I can't provide the video or other detailed message.

I don't think it will be easy to help unless we have some input data to repro and test. Note that you don't need to share content publicly, you can send the files to dev.exoplayer@gmail.com with subject "Issue #10911" and update this issue to indicate you've done this.

For reference to anyone readin, `InvalidResponseCodeException: Response Code 416` is a network error but likely returned by the server because the player is trying to read outside the boundaries of the file.

**Comment by joechan-cq** [comment]
#10087
same issue, same reason, even same device(XiaoMI). My video is also invalid, because of meta box that doesn't start with the mandatory hdlr box.

**Comment by christosts** [comment]
over to @rohitjoins, I see #10087 has media attached.

**Comment by rohitjoins** [comment]
Hi @joechan-cq,

I think we need clarity on how this video was generated in order to debug this issue further. Generally, we try to strictly follow the spec unless we know it is a common issue on media generated by a specific device. We don't have playback parity with other media players in the industry and try to follow the spec wherever possible.

**Comment by joechan-cq** [comment]
The abnormal videos may be shot by Mi 12, 12pro, and 12s Ultra, because the meta of the video has a special value of the key mcvr. Currently, only videos shot by the corresponding Xiaomi devices have this metainfo. 
However, the videos shot by the cloud test platform can be played normally, and no similar complaints were received recently. I also cannot reproduce the problem. Maybe this issue can be closed if developers would not to solve it with the video in #10087

**Comment by rohitjoins** [comment]
Thanks for the info @joechan-cq. Closing this issue as bad media.
