### ISSUE TITLE
Custom buffering audio processor : sync issues on seek/loop

### ISSUE THREAD

**Issue by Ste-RH** [google/ExoPlayer#10929]
ExoPlayer version: Various - 2.16 right through 2.18.2

I am using a custom audio processor (extends BaseAudioProcessor) that (in queueInput(...) ):

- stashes audio samples into a custom buffer
- zeros the samples going into the output buffer - to preserve timing, etc

Audio is played back externally to ExoPlayer - being pulled off the custom buffer.  All seemed to work as desired.  However, I am seeing sync issues when seeking.  I initially looked to empty my custom buffer in overrides of onFlush(),  onQueueEndOfStream() and onReset().  Sync is still not right, and looping also appears to be out of sync.

Can anyone offer some guidance on when I should be emptying my custom audio buffer?

**Comment by Ste-RH** [comment]
I am wondering if it is a combination of issues.  Here are a few things that seem to help...

1) No re-creating/flushing my audio buffer in onConfigure seems to help the loop - I think this is firing before the audio system that pulls samples (Unity) has chance to pull the samples at the end of the video before loop.

2) Not actually flushing my audio buffer in the flush that gets triggered after 'onQueueEndOfStream' is called

Is there a description or diagram of how the audio processing chain works with respect to looping?  That would be a great help!

**Comment by tonihei** [comment]
Could you clarify what you mean by "looping" in this context? Is it looping the same item in the player? If so, it means that we can likely keep all processors and the `AudioTrack` alive because the format matches exactly. In this case, you should probably see a call to `queueEndOfStream()` followed by calls to `getOutput()` until `isEnded()` returns true. After that, the processor is flushed with `flush()` in order to receive new input data (via `queueInput`) from the new or repeated source. As no format change happened, I don't expect any call to `configure` in this scenario. 

Generally, the idea is that you only need to flush your internal buffers if `flush()` is called. In the transition case described above, your internal buffers should actually be empty already at the point where `flush()` is called because they were drained before until the processor ended.
