### ISSUE TITLE
FFmpegExtractor  can add

### ISSUE THREAD

**Issue by liuguangsen** [google/ExoPlayer#10923]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by christosts** [comment]
Can you please clarify what the request is about? I don't understand from the issue title.

**Comment by ivs88** [comment]
@christosts I was going to submit an issue with the same title)
It would be great if ffmpeg extension also include an extractor implementation. Why? For example, FFmpeg does a really(!) good job reading all kinds of media metadata. Right now we can handle some metadata like ID3 and mp4, but it's far from enough. FFmpeg can fully handle that if it can be used by MetadataRetriever.

**Comment by christosts** [comment]
I'd like to understand the use cases better, in case we can improve ExoPlayer components directly.

You mention metadata. Are these required for playback? If yes, what is it that you are missing from ExoPlayer? If they are not required for playback, how would you use an ExoPlayer instance even if there was an ffmpeg extractor?

Are there other use cases that you need improvements for?

**Comment by ivs88** [comment]
Chapters are pretty important for playback navigation if that's what you mean. As far as I can tell right now ExoPlayer extracts only ID3 chapters. ID3 metadata usually used in mp3 but there are others like m4b chapters, opus, matroska, etc. I don't have a full list.

The thing is if you want to improve components directly - you have to do them all, otherwise it's useless if you can rely on it only for some formats and forced to fallback to another library. FFmpeg would provide maximum coverage.

To illustrate, say you have a 10h audiobook. Would you like to listen it with or without chapters? Imagine this 10h long seekbar - not good, right?

**Comment by ivs88** [comment]
@christosts did you have a chance to think this through?

**Comment by christosts** [comment]
It is unlike that we will implement this as it goes in the opposite direction of where we are headed with ExoPlayer. For gaps and missing features, we prefer to implement them directly on ExoPlayer, and we welcome code contributions too. Implementation-wise, the work required to wrap the ffmpeg extractors in ExoPlayer is not negligible either and we prefer to spend that time extending the player.

If there's a specific feature that you need (such as any of the ones you mentioned above), please file an issue so that we add it in our plan.

Thanks
