### ISSUE TITLE
Session Exception : Failed to get provision request (-2014) Playback Error

### ISSUE THREAD

**Issue by dev-sharma-deltatre** [google/ExoPlayer#10947]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/105206700/215053866-35297f9d-2de2-4d78-96f2-b34fe36a6ca8.png)

Can someone help me in understanding the reason behind this error?

**Comment by marcbaechinger** [comment]
@rrfrias Can you interpret this error code?

**Comment by icbaker** [comment]
@dev-sharma-deltatre Please provide the result of `adb bugreport` captured after reproducing the stack trace you've screenshotted. Please either upload it here or send to dev.exoplayer@gmail.com using the subject in the format `Issue #10947`. Please also update this issue to indicate you’ve done this.

There will be much more information in the bug report that will help us to understand the problem you're seeing.

**Comment by rrfrias** [comment]
The stack trace does not contain sufficient information to root cause the issue. A bugreport will help. An alternative is to collect metric data that should give us some insight into the problem. You will need to modify the app and call [MediaDrm.getPropertyByteArray](https://developer.android.com/reference/android/media/MediaDrm#getPropertyByteArray(java.lang.String))("metrics") . This returns a byte[] so you might need to convert it to a Base64 encoded string before you share with us (Base64.getEncoder().encodeToString(bytes)) .

**Comment by rrfrias** [comment]
@dev-sharma-deltatre can you let us know which Android release the device is running. The error is transient. Without more information we cannot tell what the root cause is but it is possible that the issue might be resolved if the app retries the operation after waiting for 1 second.

**Comment by dev-sharma-deltatre** [comment]
@rrfrias Hello thank you for your response. I am closing this as this is not reproducible anymore. Seems like some VPN issue.
