### ISSUE TITLE
Exoplayer does not scale video properly in HLS 

### ISSUE THREAD

**Issue by wanoghoco** [google/ExoPlayer#10950]
am using the latest version of exoplayer(2.18.2), am trying to scale  video(HLS) as the track or quality changes to a higher resolution but the videos does not get scaled properly when the track changes, I can't see anything like changing the resolution when the track changes on the documentation. I noticed the video scale properly when I set InitialBitrateEstimate(Integer.MAX_VALUE), but by default settings, when it changes track, it doesn't scale properly..

**Comment by tianyif** [comment]
Hi @wanoghoco,

Thanks for reporting! Did you see this issue on demo app? And by saying track changes, did you mean the adaptive track selection during the course of loading the chunks or manually change of track? For the adaptive track selection, we determine the ideal track to select based on the bandwidth estimate from `BandwidthMeter`. And when the video size changes (either due to adaptive track change or manual track change), `PlayerView` will [get notified and update the ratio](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L1465). 

However, I couldn't see a clear reason why `setInitialBitrateEstimate(Integer.MAX_VALUE)` can directly affect the video scaling at this point. Probably an improper initial bandwidth estimation can cause the video size to be updated too frequently and further cause scaling problem, I'm not very sure. Do you mind sending us the media link so I can take a deeper look? And could you please also add the Logcat trace by filtering with the keyword "EventLogger" just in case that I cannot reproduce with the sent media link. Thanks in advance!

**Comment by wanoghoco** [comment]
I also notice this issue from the flutter package also, after testing HLS video on it. when the adaptive track changes, it does not scale the next resolution properly..

**Comment by wanoghoco** [comment]
I mean when you set to  setInitialBitrateEstimate(Integer.MAX_VALUE, it start with the best quality and resolution so it scales it properly but when u start from lower resolution to higher, the resolution does not scale properly on the device that the issue

**Comment by tianyif** [comment]
Could you please add the Logcat trace if possible?
