### ISSUE TITLE
Can we fix this NoSuchMethodError if the version is different?

### ISSUE THREAD

**Issue by YogeshSinghPathania** [google/ExoPlayer#10956]
Hi, I have one question im using JWplayer(EXoplayer version 2.18.0) and BrightCove(Exoplayer version 2.17.1). I create two frame one for JWplayer and one for BrightCove. But only one player working at a time. 
If i setup these version im getting this issue
java.lang.NoSuchMethodError: No virtual method setDrmSessionManager(Lcom/google/android/exoplayer2/drm/DrmSessionManager;)Lcom/google/android/exoplayer2/source/hls/HlsMediaSource$Factory; in class Lcom/google/android/exoplayer2/source/hls/HlsMediaSource$Factory; or its super classes (declaration of 'com.google.android.exoplayer2.source.hls.HlsMediaSource$Factory' appears in /data/app/~~v_vIfy6_Ax302ZGA7l7dVg==/com.newscorp.newstand-TsBEGYLMoDv45z12qECXHA==/base.apk!classes32.dex)

**Comment by YogeshSinghPathania** [comment]
@marcbaechinger Can you please give me some suggestion what should i do in this case.?

**Comment by microkatz** [comment]
Hi @YogeshSinghPathania. According to the [Exoplayer/RELEASENOTES](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md), `setDrmSessionManager` was removed in Exoplayer version 2.17.0. It was labeled as deprecated previously to that. Can you use `setDrmSessionManagerProvider` instead?

**Comment by YogeshSinghPathania** [comment]
Hi @microkatz thanks for your reply. Actually Brightcove is only using the 2.17.1 i also upgrade with this version but in JWplayer  they did not add exoplayer 2.17.1. We found that JWPlayer has directly upgraded the version of Exoplayer from 2.16.1 to 2.18.1. It means they have never created a release for 2.17.1. But for BrightCove, we are using 2.17.1. where i change this can you please guide me

**Comment by microkatz** [comment]
From 2.17.0 onwards, `setDrmSessionManager` is removed. It might be a jar classloading issue as you have two different SDKs that are loading the same exact Exoplayer jar files with same classnames, objects, etc(albeit two different versions). 

It seems based on JWPlayer's demo [build.gradle file](https://github.com/jwplayer/jwplayer-sdk-android-demo/blob/master/app/build.gradle) that they are using Exoplayer 2.16.1? Perhaps JWPlayer is the one using the removed setDrmSessionManager API?

I would suggest setting up bugs with JWPlayer and/or Brightcove to either update their Exoplayer versions or not use `setDrmSessionManager`. Or use just a single player rather than two.

**Comment by YogeshSinghPathania** [comment]
But im using this version https://docs.jwplayer.com/players/changelog/android-471
