### ISSUE TITLE
Some bmp ts can't play

### ISSUE THREAD

**Issue by FongMi** [google/ExoPlayer#10965]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

* Samsung Galaxy S10+

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

Play hls url
1. http://t.grelighting.cn/m3u8/djVxNWlDcUE5U3RDMnNXTUNqQlJ2NVFHdkptWnp0dWQ=.m3u8
2. http://t.grelighting.cn/m3u8/L3RKU1R4MGVQUkdSNjB3cFVHVjJZRDRUTkcxUWpVQzg=.m3u8

### Expected result

1. can play
2. can play

### Actual result

1. can play
2. can't play

### Media

1. http://t.grelighting.cn/m3u8/djVxNWlDcUE5U3RDMnNXTUNqQlJ2NVFHdkptWnp0dWQ=.m3u8
2. http://t.grelighting.cn/m3u8/L3RKU1R4MGVQUkdSNjB3cFVHVjJZRDRUTkcxUWpVQzg=.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by FongMi** [comment]
I think ts parser not found the accurate position at second url.

**Comment by tianyif** [comment]
Hi @FongMi,

Actually I can reproduce the same issue on both of the media urls, for the first one, the exception happens at the mid of the playback, while for the second one, the exception happens when the playback starts.

Let me take the second manifest for example. The exception is thrown at the first segment:
https://pic.rmb.bdstatic.com/bjh/af85b02e34b34f3ea1167df5c408d6eb.bmp

I used your key to decrypt that bmp file to `output.ts`, and then I used [tsduck](https://tsduck.io/) to analyze it (`tsanalyze output.ts`), then I got 
```
*** Synchronization lost after 40,007 TS packets
*** Got 0x00 instead of 0x47 at start of TS packet
```
There is another tool in tsduck `tsresync`, which resynchronizes a non-standard or corrupted MPEG transport stream. I used it to resync `output.ts` and produced a new copy `output_resync.ts`, and I separately created two playlists which contain only `output.ts` or `output_resync.ts`, and tried on our demo app. I could see the playlist that contains `output.ts` fail to play, with throwing the above exception, and the one that contains `output_resync.ts` play successfully.

So I think you may need to resync some of your media segments.
