### ISSUE TITLE
Is it possible to cache a frame and starts decode from it instead of decoding from the nearest I frame?

### ISSUE THREAD

**Issue by TinTran64** [google/ExoPlayer#10972]
I want to improve the seek time of so that when users scrub the seek bar they'll have smooth preview of the video just like IOS media player or the Samsung gallery app.

I'm using `seekTo` to implement this feature but it's pretty slow if the frame is far from the I frame. My video is usually a short video of 2 - 4 seconds so it has only 1 or 2 I frames at most. 1 at the start and 1 close to the end of the video.

So I was wondering if I can cache some decoded frame and feed it into the decoder and start decode from there. If this can be done it would greatly improve the seek time.

**Comment by stevemayhew** [comment]
The seek operation flushes the CODEC if the seek target is outside of the boundaries of what has been loaded.  If you set the back buffer duration to > 0 (https://github.com/google/ExoPlayer/blob/a9444c880230d2c2c79097e89259ce0b9f80b87d/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L68) I can't see how any seek you would issue in a 2 second video would not resolve to frame where the NAL data is cached.  

Also how is your seek bar to time mapping done?  With only 2 seconds of video you need sub-second level seeks to reach a frame with a track bar gesture

Lastly what hardware is this?  If the decoder is very slow then yes decoding all the frames from iFrame to the seek point is likely your bottle neck.

**Comment by christosts** [comment]
It seems you have identified that the bottleneck for your app is decoding. Specifically about decoding and seeking:

> So I was wondering if I can cache some decoded frame and feed it into the decoder and start decode from there. If this can be done it would greatly improve the seek time.

When a seek is performed, we need to flush the codec and start decoding from the nearest I-frame before the seek point, so the delay for decoding all frames between the I-frame and the seek point can't be avoided.  ExoPlayer does not cache decoded frames either.  That would be very difficult and complicated to control (if not impossible) because of the platform APIs design. The number of decoded frames available is controlled by the device via MediaCodec's output buffers. If we are to cache MediaCodecs output buffers, it's likely the codec will not have enough resources for decoding so we'd get stuck. Alternative approaches such as copying the decoded frames would bring in more complications in terms of memory usage and slow performance than the sought benefits.

Have you thought of alternative approaches for your app? There's a discussion on #9850 how to improve "scrubbing" and maybe there are valid ideas for your app too, such as changing the [player's seek parameters](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#setSeekParameters(com.google.android.exoplayer2.SeekParameters))? Also, is there the option of changing the encoding to include more I-frames?

The comment from @stevemayhew points to loading, which would be an issue if your files are loaded from the network. Is that the case for your app? You mentioned gallery apps on iOS or Samsung and asked specifically for decoding, so I assumed your app is playing local files, but perhaps the bottleneck you're observing includes network loading too.

**Comment by TinTran64** [comment]
@stevemayhew This is my `LoadControl` config. My test device is a Samsung A53 but it's not improving much on Pixel 6 which has fairly powerful hardware.
```
DefaultLoadControl.Builder()
            .setBackBuffer(3000, true)
            .setPrioritizeTimeOverSizeThresholds(true)
            .setBufferDurationsMs(3000, 50000, 2500, 2500)
            .build()
```
Every time I issue a seek, I see this log in the logcat, indicating that the codec has been flushed. Shortly after that the frame is rendered so I think the bottleneck here is the time needed to flush the buffers is too high
```
[OMX.qcom.video.decoder.avc] signalFlush
[OMX.qcom.video.decoder.avc] ExecutingState flushing now (codec owns 4/4 input, 10/15 output).
[OMX.qcom.video.decoder.avc] Now Flushing
[OMX.qcom.video.decoder.avc] FlushingState onOMXEvent(0,1,1)
[OMX.qcom.video.decoder.avc] FlushingState onOMXEvent(0,1,0)
[OMX.qcom.video.decoder.avc] Now Executing
```
@christosts I don't think the decoder is the bottleneck because it plays the local files just fine on the Samsung gallery app. The video used is loaded from network but I used the `CacheDataSource` so theoretically it's playing the local file. I've tried playing local video as well and the result is the same. It's worth mentioning that the Samsung gallery app seems to use `NuPlayer` and not `ExoPlayer`

**Comment by christosts** [comment]
> I think the bottleneck here is the time needed to flush the buffers is too high

Can you try disabling asynchronous buffer queueing? You need to pass a custom renderers factory instance

```
DefaultRenderersFactory renderersFactory =
    new DefaultRenderersFactory(context)
        .forceDisableMediaCodecAsynchronousQueueing();
ExoPlayer exoPlayer = new ExoPlayer.Builder(context, renderersFactory).build();
```

Some info on asynchronous buffer queueing is [here](https://exoplayer.dev/customization.html#enabling-asynchronous-buffer-queueing). I wonder if the multiple threads operating (compared to synchronous queueing) are making flushing take longer. The two devices you have mentioned so far (Pixel 6 and Samsung A53) should be running Android 12+, so asynchronous buffer queueing is probably enabled by default unless you turn it off yourself.

In addition to that, I linked to #9850 on my previous comment and if you follow the comments thread, you'll land on [this comment](https://github.com/google/ExoPlayer/issues/6794#issuecomment-573068211) on #6794 which discusses some practices to make rewind & fast forward smoother, which may apply to your app.

**Comment by TinTran64** [comment]
@christosts I've already done most of what's mentioned on #6794 which has improved the scrubbing responsiveness before asking this question. Disabling asynchronous buffer queueing drastically improved frame latency though. Still, it hasn't matched the iOS media player's smoothness but it's acceptable. Thank you for the help!!

**Comment by christosts** [comment]
I assume we can now close this issue. Feel free to re-open it if needed.
