### ISSUE TITLE
Video Enhancement Solution 

### ISSUE THREAD

**Issue by liushaowei123** [google/ExoPlayer#11007]
feature request:
-----------------------
There is an urgent need for an integrated solution where the player can perform video enhancement for low-resolution videos to make the video clearer

Use case description
For low-resolution videos, the player can perform video enhancement to make the video clearer
### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
Using a trained model, it can be integrated into the exoPlayer player in the form of a plug-in

**Comment by icbaker** [comment]
This probably would be best as an extension to the library, rather than direct changes in the library - and that extension doesn't need to be hosted/maintained/owned by us. I suggest that if you're interested in this functionality you work on building this extension yourself. If there's specific hooks/extension points you need in the core library in order to make that feasible then please file new issues with details about what you would need to change in the core library.

We don't plan to work on this, so I'm going to close this.
