### ISSUE TITLE
Cut Closed captions (C608) when html tag mixed with normal text

### ISSUE THREAD

**Issue by ZygmuntMalek** [google/ExoPlayer#11019]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

All devices 
I've tested at Samsung Galaxy A10 but our client report it at multiple devices

### Reproducible in the demo app?

Yes

### Reproduction steps

It's reproducible at demo device but required is special content.
IMHO when measure space need to draw Closed captions 608, in case there is html mixed content 
eg.

>    The USS<i> Cerritos</i> remains in  
Spacedock, impounded for further
         investigation. 

Also this is a regression introduced between r2.11.8  => r2.12.3 and can be reproduced on newest version

### Expected result

Issue were not observed eg. at Exoplayer r2.11.8

### Actual result

Space for draw Closed captions is cut, and such subtitles are not displayed properly
Exoplayer 2.11.8

![Exoplayer2 11 8](https://user-images.githubusercontent.com/47888710/221231183-2ded5371-4e4e-43b6-9544-a73439515709.png)

Exoplayer 2.12.3

![Exoplayer2 12 3](https://user-images.githubusercontent.com/47888710/221231192-669c4b9f-210a-4e4d-bdb3-292bce3e7985.png)

Exoplayer 2.18.2

![Exoplayer2 18 2](https://user-images.githubusercontent.com/47888710/221231200-3f73889e-f706-4c47-81ad-6ad8f66412d1.png)

Exoplayer 2.7.3
![Exoplayer 2 7 3](https://user-images.githubusercontent.com/47888710/221231204-13dd5367-ff9e-499a-a039-911645b370a6.png)

### Media

I'm trying to get publicly accessed content but currently I'm waiting for it.

IMHO to reproduce issue there is need content with embed closed caption where html tagged eg. by Italic text fragment is mixed with normal text

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Please provide a file we can play that reproduces the issue - without this it's not really feasible for us to investigate I'm afraid.

Please either upload it here or send to dev.exoplayer@gmail.com using the subject `Issue #11019`. Please also update this issue to indicate you’ve done this.

**Comment by ZygmuntMalek** [comment]
@icbaker link to content sent in email

**Comment by icbaker** [comment]
I had a look at the provided media. I copied the entire directory (maintaining the structure from the zip file) to my device and tried playing both the `.ism` and `.ismc` files as Smooth Streaming manifests, but ExoPlayer failed because it expected to find a `/Manifest` directory underneath the `ism` file. It looks like there might be some directory structure missing? I'm afraid I'm not going to try and recreate it by trial and error.

I looked at the 360p file directly with mediainfo and it thinks it contains CEA-608 subtitle data, but ExoPlayer doesn't find any tracks apart from the video one when it plays the file directly (skipping the manifests). I didn't see any subtitle-specific data in the manifests, but I'm not a Smooth Streaming expert so I might have missed it.

Can you please provide fuller repro steps of how to get the subtitles to display in our demo app?

**Comment by ZygmuntMalek** [comment]
Access to new content sent by email - it should be easiest to use it, I were able to reproduce issue using this content myself - if there will be need for more details I could pass detailed steps how to.

**Comment by icbaker** [comment]
Thanks - I'm able to reproduce the problem now.

I added some logging and I see the full text of the cue when the italic span is being added:

```
Cea608Decoder.setItalicSpan() builder='The USS Cerritos remains in', start=8, end=17
```

The end of the text gets lost in the `truncate` calls here (see #7341 for context on why we truncate here):

https://github.com/google/ExoPlayer/blob/ac9d5337b2b51a855f3c33f3b126d9ef921ebc69/library/extractor/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L969-L979

In the case of your `The USS Cerritos remains in` line, we have `indent=16` and `tabOffset=3`, so we truncate the string to `32 - 16 - 3 = 13` characters.

The `indent=16` comes from a packet with `cc1=0x11 cc2=0x58` at timestamp `55488766µs`. This part looks correct, Table 53 in the ANSI CEA-608-E 2014 spec shows that `0x58` indicates an indent of `16`.

So I think your content is not strictly valid, because it tries to encode more than 32 characters into a single row (when accounting for the 16 char indent and the 3 char tab offset).

However, I think we can probably tweak our 'truncate to 32 chars' logic to ignore indentation and offset and only operate on the actual visible text characters. This will continue to resolve the concern in #7341 (screen full of chars) and will also mean your content works too. I'll send a change for this.

With this change it looks like this:

![android-screenshot-2023-06-29T141153](https://github.com/google/ExoPlayer/assets/1279752/12de655a-4e0c-4385-8912-43a6522a3aec)

**Comment by ZygmuntMalek** [comment]
After your change our client text looks similar to version Exoplayer 2.11.8 - so IMHO looks good - is this change available at some dev branch ?

**Comment by icbaker** [comment]
I've submitted the change internally, it will be pushed to the [`dev-v2` branch](https://github.com/google/ExoPlayer/tree/dev-v2) here and the [media3 `main` branch](https://github.com/androidx/media/tree/main) in the next week or so. The commits will be linked in this issue when it's pushed.
