### ISSUE TITLE
Only Audio playback for an mp4 hevc file not DASH or HLS ( using Extractor)  

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1102]
Verified video and audio plays okay on Msft Edge browser on laptop. 
Video url : http://stagecms.vcu.tv/bc/src/temp/output.mp4
Cannot see anything critical in the logs that would suggest why video is not playing. Tried to play the video using the demo app logcat in Gist below :
https://gist.github.com/abhiguru/f14df147d8b8099aaa51

**Comment by abhiguru** [comment]
probably related too https://github.com/google/ExoPlayer/issues/1099. If so please close and I will work on the same resolution.

**Comment by ojw28** [comment]
This isn't related to #1099. The video track of this file has an elst (edit list) box that defines a single edit with segment_duration set to 0 and media_time set to 3000. We interpret this as edit as removing all samples from the track, meaning `trackSampleTable.sampleCount == 0` in `Mp4Extractor.processMoovAtom`. This results in the video track being dropped.

@andrewlewis - ISO 14496-12 added an example not present in earlier revisions of the spec that suggests this is a way to subtract 3000 from the sample timestamps. That would map the first sample timestamp to 0 in this sample, which seems right. The spec kind of suggests this is only valid in fragmented MP4, but it's written in quite a confusing way. There is also this related [document](https://w3c.github.io/media-source/isobmff-byte-stream-format.html) (search for edts).

Thoughts?



 the interpretation 

 What do you think?

**Comment by andrewlewis** [comment]
In fragmented MP4, where we don't currently apply edit lists, a 0-duration edit makes sense because there may be no samples yet in the media timeline, and the edit can provide an offset for timestamps in subsequent fragments (as described in the specification). But for unfragmented MP4 files all sample timestamps are known so it is not necessary to specify an edit without a duration.

I'm not certain that the current implementation of dropping samples that aren't explicitly included by an edit is correct, but I guess it would be strange if the last edit was treated specially, so I'm tempted to leave this as-is. Alternatively, we could add special handling for the case of one 0-duration edit, and assume that no-one would deliberately make an edit list that removed all samples.

**Comment by abhiguru** [comment]
Awesome, Thanks for the fix! Its working now.
