### ISSUE TITLE
Dynamic changes to playlist, removing items

### ISSUE THREAD

**Issue by MrBzik** [google/ExoPlayer#11037]
Hi. I can not find uptodate information wheather exoplayer supports dynamic changes to playlist. 
For example I need to remove items. 
I set exoplayer with concatenating mediasource, and I only find .removeMediaItem(index) method. It throws IllegalArgumentException when I call it while exoplayer is playing. 
So is there a way to do this?

**Comment by christosts** [comment]
The MediaItem API offers functionalities for adding and removing items in a playlist. The [Playlists](https://exoplayer.dev/playlists.html) page has more details. Is there a reason you cannot use that and you prefer the concatenating media source?

**Comment by MrBzik** [comment]
Oh, I see. Well, since in my case there is a bunch of playlists, I thought it would be more efficient to create one when needed with concatenating media source,  so I can switch between playlists(media sources) without adding separate media items every time, and clearing out previous playlist items.  Can I use MediaItem.mediaId to achive such functionality? Or create separate lists of media items and switch between them

**Comment by christosts** [comment]
> Can I use MediaItem.mediaId to achieve such functionality?

I don't understand how you plan to use that.

> Or create separate lists of media items and switch between them

From your answer, yes that sounds like it fits better to your use-case.

In high-level, using the concatenating media source to represent a playlist of items, including adding/removing items on the fly will not work. You'll need to work with adding/removing MediaItems.

Closing the issue because the question seems answered, feel free to re-open or add new comments if more information is needed.
