### ISSUE TITLE
Subtitles don't work inside segment of m3u8

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#11030]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

Pixel 6 pro and Chromecast with Google TV

### Reproducible in the demo app?

Yes

### Reproduction steps

Opened the demo project and added to `demos/main/src/main/assets/media.exolist.json` the json below:
```
{
    "name": "My tests",
    "samples": [
      {
        "name": "Caption 1",
        "uri": "https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8"
      },
      {
        "name": "Caption 2",
        "uri": "https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/profile_0/chunklist.m3u8"
      }
    ]
  }
```

When I run the demo, it doesn't show any subtitles for the video titles `Caption 1` but it does for `Caption 2` even though 2 is just one of the variants of the master list 1. 

### Expected result

It should show a subtitle track. 

### Actual result

No subtitles shown. 

### Media

https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/playlist.m3u8

Whereas this specific variant works https://bcovlive-a.akamaihd.net/c9bf201b06694453bb29282f97191f58/us-east-1/6240731308001/profile_0/chunklist.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Thanks @casolorz for reporting!

I was able to reproduce this issue on the demo app. The first playlist (multi-variant playlist) doesn't have the CC because the it falls onto the chunkless preparation path but without CC tracks declared in itself. For chunkless preparation, closed caption tracks are exposed if and only if they are declared by the master playlist (please see our blog https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6 for reference, maybe need to search by the term "closed caption tracks"). 

Currently we use [two flags](https://github.com/google/ExoPlayer/blob/r2.18.3/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaPeriod.java#L638) `allowChunklessPreparation` and `codecsStringAllowsChunklessPreparation` to decide whether we should do the chunkless preparation. For the first one, it is an [opt-in flag](https://github.com/google/ExoPlayer/blob/r2.18.3/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java#L256) that can be set in `HlsMediaSource.Factory`. Looks like this flag is `true` by default. For the second one `codecsStringAllowsChunklessPreparation`, it is based on the [number of video and audio codecs](https://github.com/google/ExoPlayer/blob/r2.18.3/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaPeriod.java#L615-L619) that retrieved from the multi-variant playlist. Since the first playlist is a multi-variant one with codecs declared "CODECS="avc1.64001f,mp4a.40.2", and the number of video and audio codecs result a value of of `true`, then it goes to the chunkless path. However, the second one is a media playlist, when loading which directly we just create a "single variant" multi-variant playlist for it, and the codecs of that variant are not specified in that way. With `codecsStringAllowsChunklessPreparation` being `false`, and we just do a traditional preparation for it. So that's why CC appears for the second playlist.

While we will discuss if there is any improvements we can make, I think the quickest workaround is to set the `allowChunklessPreparation` to `false` via the setter of `HlsMediaSource.Factory`.

**Comment by casolorz** [comment]
Thank you for the detailed explanation, very helpful. What are the downsides of setting `allowChunklessPreparation` to `false`?

**Comment by tianyif** [comment]
It will result in the traditional preparation for HLS. For the playlist that includes incomplete or incorrect track information, ExoPlayer will extract the track information from the media content itself, which requires downloading a single chunk from one of the variants and one from each non-muxed audio track - this is how traditional preparation works.

The chunkless preparation works when track information is defined correctly in the multi-variant playlist, and it will be faster compared to the traditional preparation by avoiding the chunk download. The [blog](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) also contains some data on the preparation durations of these two strategies. So if the track information in the multi-variant playlist is complete and correct, the downside of setting `allowChunklessPreparation` to `false` is that the preparation will be slower.

**Comment by casolorz** [comment]
Ok, thank you. And just to confirm, setting `allowChinklessPrepapration` fixed it.
