### ISSUE TITLE
when using Clipping Configuration, the last few seconds of the fragment are cut off

### ISSUE THREAD

**Issue by fanok1** [google/ExoPlayer#11035]
I have a large audio file, I use Clipping Configuring to divide it into parts (one part ends and a new fragment starts from the same position).  With this performance, several seconds sometimes disappear between fragments.  This happens with different files and with different fragments.

**Comment by christosts** [comment]
Have you verified whether this is reproduced with the [demo app](https://exoplayer.dev/demo-application.html) playing your content? You can have your files in a playlist and specify `clip_start_position_ms`and `clip_end_position_ms` for each file. If the issue is reproduced on the demo app, would you be able to share the content, as well as your modified `media.exolist.json` file, for us to try as well?

Note, if you cannot share content publicly, please send us an email at dev.exoplayer@gmail.com with subject "Issue #11035" and then update this issue to indicate you've done this.

Thanks
