### ISSUE TITLE
ExoPlayer Live Video Latency

### ISSUE THREAD

**Issue by YileKu** [google/ExoPlayer#11047]
I have a laptop encoding video and sending it to my android phone.  I developed an app using ExoPlayer to play the video ( I was using ffmpeg ).  ExoPlayer always has a latency of about 4.5 seconds between when something happens and the video shows the action on the phone.  I have tried several APIs and options that relate to buffering but no luck decreasing this latency.  If anyone knows how to decrease this latency,  I would appreciate any pointers.
Thanks
Y-

**Comment by rohitjoins** [comment]
You may try to [tweak](https://stackoverflow.com/questions/69748951/how-to-get-low-latency-in-exoplayer-rtsp-live-streaming-on-android) `LoadControl` to reduce the latency. 

Please provide more detailed information on what you are trying to achieve and may be we can help better. Assigning to @christosts, who knows more in this area.

**Comment by christosts** [comment]
@YileKu what network protocol are you using for streaming? HTTP or RTP?

**Comment by YileKu** [comment]
We are using UDP multicast.  The laptop has a hardware encoder that sends
UDP multicast.

Thanks
Y

**Comment by christosts** [comment]
As @rohitjoins mentioned, you need to tweak `LoadControl` and bring down the min buffer as much as possible. Please note that ExoPlayer has not been designed for real-time streaming use-cases like conferencing or cameras, therefore some noticeable delay will always be there. We are aware of apps that managed to get the delay down to ~1s, but no less. 

For the `LoadControl`, try setting low values for`minBufferMs` and `bufferForPlaybackMs` in DefaultLoadControl, e.g. experiment with 1000ms and perhaps attempt to go below that.

**Comment by YileKu** [comment]
I have tried several variations of the code below.  All of the attempts
still incur about a 4.5 second latency.  I can play the video on another
laptop with ffmpeg and get about 1/5 second latency.

Thanks,
Y


       mPlayerView = m_view.findViewById(R.id.player_view);


        DefaultRenderersFactory renderersFactory;

        DefaultLoadControl.Builder builder = new
DefaultLoadControl.Builder();
        builder.setAllocator(new DefaultAllocator(true,
C.DEFAULT_BUFFER_SEGMENT_SIZE));
        try {
            builder.setBufferDurationsMs(
                    100,
                    200,
                    100,
                    0
            );
        }catch(Exception e)
        {
            Log.d("tactical", "Exception");
        }

        LoadControl loadControl = builder.build();
        @DefaultRenderersFactory.ExtensionRendererMode int
extensionRendererMode =
DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER;
        renderersFactory = new DefaultRenderersFactory(m_tacActivity)
.setExtensionRendererMode(extensionRendererMode);

        // we are creating a media source with above variables
        // and passing our event handler as null,
        LDataSource.LDataSourceFactory lDataSourceFactory = new
LDataSource.LDataSourceFactory();
        DefaultMediaSourceFactory defaultFactory= new
DefaultMediaSourceFactory(m_tacticalActivity).setLiveTargetOffsetMs(100);
        MediaItem mItem = new
MediaItem.Builder().setUri("").setLiveConfiguration(
                new MediaItem.LiveConfiguration.Builder()
                        .setMaxPlaybackSpeed(1.02f)
                        .build())
        .build();

        MediaSource videoSource = new
ProgressiveMediaSource.Factory(lDataSourceFactory)
                .createMediaSource(mItem);

        mExoPlayer = new ExoPlayer.Builder(m_tacActivity,
defaultFactory).setLoadControl(loadControl).build();

        mExoPlayer.setMediaSource(videoSource );

**Comment by christosts** [comment]
Looking at the snippet, there are several parameters that could play a role here. The stream itself is one parameter, and also I see you are using your own DataSource implementation (`LDataSource`). I don't think your data source would add delays at the level of seconds, but it'd be good to narrow down the problem as much as possible. 

Ideally, we need info to repro your setup and verify the delay ourselves, so that we figure out where the source(s) of delay is. Can you share instructions (including your content) how to setup the server so that we can test the stream with the demo app? Ideally, an automated script that we can just run on a linux machine? And also, how do you measure the latency?

If you cannot share the setup, the next thing I can think of is to repeat your experiments using the [demo app](https://exoplayer.dev/demo-application.html) and share with us a [bug-report](https://developer.android.com/studio/debug/bug-report). We be able to get some information from there.

Note that from your previous comment (`We are using UDP multicast.  The laptop has a hardware encoder that sends
UDP multicast.`), I'm assuming the content is transported over RTP, i.e. the content URI is `rtp://...`.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #11047". Please also update this issue to indicate you've done this.

**Comment by YileKu** [comment]
Christosts,

I have used my data source with a ffmpeg decoder and I only get about a
1/10 of second latency.  I will try some other tests to make sure that my
data source is not causing the permanent latency.

There are several off-the-shelf video encoders that can send live video
using UDP multicast.  I am using our companies encoder that encodes live
video using H264 in a transport stream.    You could also use a USB video
CAM and VLC to view, encode, and multicast the stream over UDP to the phone
over WiFi.    Measure the latency at the laptop and then in ExoPlayer on
the phone.

Let me know if you have any questions.
Kyle

**Comment by christosts** [comment]
I performed some testing with mpeg-ts content streamed by `ffmpeg` directly. I do see several areas where the player is not optimized for sub-second latencies but I'm not sure how these affect your use-case and whether it can actually improve.

First of all, if you know the stream is mpeg-ts, it's probably best to set the extractors factory to use only the TsExtractor to reduce setup time. For example

```java
ExoPlayer.Builder playerBuilder = new ExoPlayer.Builder(context)
          .setMediaSourceFactory(
               new ProgressiveMediaSource.Factory(
                   new DefaultDataSource.Factory(context), 
                   /* extractorsFactory= */ () -> new Extractor[] {new TsExtractor()}))
          .setLoadControl(new DefaultLoadControl.Builder().setBufferDurationsMs(100, 100, 100, 100).build());
player.setMediaItem(MediaItem.fromUri("udp://..."));
```

Can you try this and let me know if there are any improvements?
