### ISSUE TITLE
STATE_READY not triggering

### ISSUE THREAD

**Issue by mis-kcn** [google/ExoPlayer#11041]
### ExoPlayer Version

2.18.4

### Devices that reproduce the issue

- Android 9 TV Emulator
- Set-up box running on Android 9

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the attached media in the demo app

### Expected result

The media plays successfully

### Actual result

- Stream is stuck on loading
- `vfpo` is stuck on N/A, sib, sb, rb, db, mcdb, and dk is stuck on 0
- VLC can play the stream OK

### Media

Will email the stream URL to dev.exoplayer@gmail.com

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @mis-kcn,

Thanks for reporting! I could reproduce this issue and also confirm that VLC player is able to play this media.

I think the problem here is that this stream doesn't contain IDR frames (**A special type of I-frame in H.264; An IDR frame specifies that no frame after the IDR frame can reference any frame before it**). I logged the `nalUnitType` [here](https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/H264Reader.java#L487), and I never saw the `nalUnitType` to be `NalUnitUtil.NAL_UNIT_TYPE_IDR`. As the consequence, there is nothing read into the `MediaCodecVideoRenderer`, and it doesn't [notify that the first frame is renderered](https://github.com/google/ExoPlayer/blob/bc3537260b1df38b30100e67ac5e1ac592fb5f26/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1424). Thus `renderedFirstFrameAfterReset` is never set to true, and the `MediaCodecVideoRenderer` can never be ready, then the `STATE_READY` cannot be set due to `rendererAllowPlayback` is [`false`](https://github.com/google/ExoPlayer/blob/bc3537260b1df38b30100e67ac5e1ac592fb5f26/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L1045).

As a workaround, you can set the `FLAG_ALLOW_NON_IDR_KEYFRAMES` in the [`DefaultTsPayloadReaderFactory`](https://github.com/google/ExoPlayer/blob/r2.18.4/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/DefaultTsPayloadReaderFactory.java#L116). Please also look at a similar [issue](https://github.com/google/ExoPlayer/issues/1894) for reference.

**Comment by mis-kcn** [comment]
Hi @tianyif! 

Setting the `FLAG_ALLOW_NON_IDR_KEYFRAMES` worked, however it doesn't play or seems to be stuck on Google TV Emulator (sdk_google_atv_x86 (PSR1.180720.121)). 

Closing this ticket, thank you.
