### ISSUE TITLE
Why here need a sleep

### ISSUE THREAD

**Issue by vipjml** [google/ExoPlayer#1104]
MediaCodecVideoTrackRenderer.java:430-445
```java
if (earlyUs < 30000) {
        if (earlyUs > 11000) {
          // We're a little too early to render the frame. Sleep until the frame can be rendered.
          // Note: The 11ms threshold was chosen fairly arbitrarily.
          try {
            // Subtracting 10000 rather than 11000 ensures the sleep time will be at least 1ms.
            Thread.sleep((earlyUs - 10000) / 1000);
            Log.d("WhatyMediaPlayer","sleep"+earlyUs);
          } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
          }
        }
        renderOutputBuffer(codec, bufferIndex);
        consecutiveDroppedFrameCount = 0;
        return true;
 }
````

the sleep will block the player event loop,this can be problem in some situation,for example,when playing video in 4x speed,the player need to render 100 frame per seconds,this sleep will make too much time wasted on sleeping. Why not write in this way:
```java
if (earlyUs < 10000) {
        renderOutputBuffer(codec, bufferIndex);
        consecutiveDroppedFrameCount = 0;
        return true;
 }
````
the RENDERING_INTERVAL_MS is 10ms,so we can still render the frame with 10ms accurate.I think this should be more smooth when playing video on poor performace device.

**Comment by ojw28** [comment]
In practice there are issues with other things blocking the player event loop on quite a few older devices. This means that if you don't block when you're "reasonably close" to needing to release a video frame in the video renderer, something else can then end up blocking the player event loop that then causes the video frame release to end up being late. The net effect is that frame release is less smooth and there are more dropped frames if you do it as you suggest, rather than being smoother. This issue is significantly worse when playing DRM protected content, but to some extent applies to non-DRM protected content too.

Note that the code you reference is only for older devices. Newer devices use a different code path that's much better suited for things like fast frame release.
