### ISSUE TITLE
video downloading is stop at the same point

### ISSUE THREAD

**Issue by leesunr-dev** [google/ExoPlayer#11068]
![225493117-9f975692-dcd9-4a3f-a733-8d4a311bc42c](https://user-images.githubusercontent.com/89774934/225498100-fedc606d-7829-4805-9f86-57f03225415f.png)

please i need help
I have observed that when the network connection is lost, the local database metadata is set to 0000000, and when the network connection is restored, video download stops at the same point. It seems that the cache data has been corrupted, and the data source is attempting to read it.

**Comment by marcbaechinger** [comment]
Resuming a download after turning on and off airplay mode works for me. 

It's odd indeed that there are a only these 8 zeros. Do you see an exception in the logs when this happens? When you say loosing the connection, how is the connection lost and do you see an exception in the logs?

I'm asking because the length of the file that would be encoded into the `metadata` field, is the result of opening the upstream data source. So I would expect that this either gives the actual length or an exception is thrown in the method that writes the entry to the database. 

The repro steps would be helpful and if possible in the demo app that is available to us for debugging.  Can you provide us with this information and a bug report right after you have a repro?

**Comment by leesunr-dev** [comment]
@marcbaechinger thank you for the comment.

I have finally identified the problematic section. There is a code in the `resolveDataSpec()` that communicates with the network while downloading HLS video. When the network connection is lost, an exception occurs in this part. At that moment, I suspect that the metadata of the stream being read is corrupted and the download stops.

adding a try-catch block to the entire `resolveDataSpec()`, the stopping issue has disappeared.
