### ISSUE TITLE
HTTP URIs not supported

### ISSUE THREAD

**Issue by dsg25** [google/ExoPlayer#11067]
Hello! 
Dont work playing audio from URL "http://78.129.229.120:10741/"
How can fix it?

**Comment by marcbaechinger** [comment]
I believe this is because you are using a URI that uses a cleartext http scheme. Please read [this section](https://developer.android.com/guide/topics/media/exoplayer/troubleshooting#fixing-cleartext-http-traffic-not-permitted-errors) in the developer guide on why that is and how you can resolve this if you really want to.

I'm closing this issue. In case your issue is caused by another reason, then please reopen and include a stack trace or any other information that makes your case actionable for us. Without further information, we won't be able to help.
