### ISSUE TITLE
Getting exception: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#11066]
Hi according to our support team we are getting next exception: 

com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=YES at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(:43) at android.os.Handler.dispatchMessage(Handler.java:103) at android.os.Looper.loop(Looper.java:214) at android.os.HandlerThread.run(HandlerThread.java:67) Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 12, 65600) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(:7) at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(:1) at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(:1) at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(:2) at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(:16) at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(:7) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(:32) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(:16) at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(:14) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(:25) ... 3 more Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 12, 65600) ... 13 more Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack at android.media.AudioTrack$Builder.build(AudioTrack.java:1018) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(:11) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(:2) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(:1) ... 12 more Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack at android.media.AudioTrack$Builder.build(AudioTrack.java:1018) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(:11) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(:2) at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(:1) ... 12 more

I have investigated this error and I found that main possible reasons: 

- **Memory leak in the application**, not releasing the player resources can cause the initialisation of the application to fail. That cause has been ruled out as it has been checked that the player instance is freed correctly.

- **We can see in the logs that audio decoder is released after getting an error first time**: 

audioDecoderReleased [eventTime=1.67, mediaPos=30.70, window=0, period=0, c2.android.aac.decoder]

After that we retry and we still get the same error. 

- **Unsupported audio format**: audio codec used is:  audio/mp4a-latm ,  according to the logs we can see the format is supported by the device.

**- Bad media?? audio chunks are corrupted.** 

Do you have any idea more what could be the root of the cause? Since it is not really clear wha could be the reason apart from bad media chunks being returned from the content source.

I have sent report a logs to exoplayer gmail account.

**Comment by christosts** [comment]
The logs show the crash is coming from the platform `AudioTrack` when creating the instance, so it's not bad media because the player has not fed media yet to `AudioTrack` yet.

The logs sent via email say that the `c2.android.aac.decoder` (which correclty maps to audio/mp4a-latm)  is acquired and released. But when the exception happens, the logged audio format is `audio/raw`. This format is usually used when the decoder is only used for decryption and the actual audio data is sent to AudioTrack over passthrough. In a typical flow, only one of the two should have happened, either a decoder should have been acquired for local decoding and the printed format should have been  `audio/mp4a-latm`, or the `audio/raw` decoder should have been acquired only for decryption and data should have been sent to AudioTrack. I'm not sure why both things are logged. Perhaps there is a bug how things are logged in 2.15. It'd be good if we can get more data, and ideally a bug-report.

Some follow-up questions:
1. Are you able to reproduce locally? Getting a bug-report from the device after the error happens will help us see if the platform audio components log an error.
2. Are you able to reproduce using the ExoPlayer demo app? That would eliminate any app-specific parameters and we can focus on the player. 
3. Alternatively, are you using any customizations with ExoPlayer, and if yes, what exactly?
4. Can you share the content to us so we can play it with the demo app? I'd like to see how with your content the player produces the log output that you sent us (=> acquiring the aac decoder and also logging the "audio/raw" MIME type).
5. Have you seen this error on any other device?

**Comment by javaboboApp** [comment]
Hi @christosts  I can answer the questions: 

1. Are you able to reproduce locally? Getting a bug-report from the device after the error happens will help us see if the platform audio components log an error.

I am not able to reproduce it locally since it errors happen not very often.

2. Are you able to reproduce using the ExoPlayer demo app? That would eliminate any app-specific parameters and we can focus on the player.

I have to try to play content using the demo app, and I am not getting errors. Since we are using the same audio codecs, video codecs for all the content.

3. Alternatively, are you using any customisations with ExoPlayer, and if yes, what exactly?

We customising PlayerControlView,PlayerView only. Also we are using a CustomBandwidthMeter in order to change the initial bitrate. 

We are using DRM license. And we are customising also HttpMediaDrmCallback in order to detect if token use by the license needs to be refreshed. Using a callback when the function executeKeyRequest is executed we check if drm token is expired. If the token is expired we refresh the token and update keyRequestProperties (using the new Bearer xxx header key). You can see this happening in the logs "[MediaSourceGenerator] updateRequestPropertiesIfNeeded called"

4. Can you share the content to us so we can play it with the demo app? I'd like to see how with your content the player produces the log output that you sent us (=> acquiring the aac decoder and also logging the "audio/raw" MIME type).

 I will send you another normal mpd file , the issue looks happening in linear channel most of the time. 
 
 5. Have you seen this error on any other device?
 
 We only have this device since product was created for this specific device. 
 
 By the way the exoplayer version that you are using is **2.17.1** not **2.15.x**. 
 
 Also I will send you more logs of another crash related to this possible bug.

**Comment by christosts** [comment]
Thanks for the data. I tested the content which worked fine. As for the dubious logging (aac vs audio/raw), that's an unfortunate logging issue on ExoPlayer which can be misleading and I'm going to change it. But other that, things work as expected with the stream.

From the sent logs, I see the failure comes from building the platform's AudioTrack which throws an UnsupportedOperationException with message `Cannot create AudioTrack`. This indicates an error is happening further down in the device and I cannot say what that would be, since the parameters used to create AudioTrack seem trivial (`Config(48000, 12, 65600)` => PCM stereo audio at 48Khz with 65KB buffer). I'm afraid this looks like a device specific issue. We could provide some more assistance if you are able to get a bug-report (or a copy of logcat) when the error happens on the device, the AudioTrack should log the error.

Have you tried contacting the device OEM?

**Comment by javaboboApp** [comment]
Thanks for the answer @christosts  I will be escalating this issue to OEM.   

For now, we do not have any possibility that allows us to gather system logs so we will need to integrate it and it can take a while. I will share this information as soon as I can, thanks again.
