### ISSUE TITLE
Why Exoplayer stops after buffering without any Error throwing onPlaybackError()?

### ISSUE THREAD

**Issue by deepanshuDPS** [google/ExoPlayer#11078]
This case is very simple when there is low network connectivity and some buddy is listening to long episodes in Podcasts when after some time exoplayer buffers and stops without throwing any error.

Can you please help me out, on how to track this by using any callback because I am not getting any error onPlaybackError()?

Exoplayer Version: 2.16.0

**Comment by deepanshuDPS** [comment]
Any update on this, do you have any hint of it??

**Comment by icbaker** [comment]
What network stack are you using with ExoPlayer? https://exoplayer.dev/network-stacks.html

Can you provide a link to a podcast that reproduces the issue in the [demo app](https://exoplayer.dev/demo-application.html) (and a rough indication for how long it takes to reproduce the issue)? Please either upload it here or send to dev.exoplayer@gmail.com using the subject `Issue #11078`. Please also update this issue to indicate you’ve done this.

**Comment by deepanshuDPS** [comment]
Shared some streaming URLs with you via mail, please check.

**Comment by icbaker** [comment]
Please answer the other questions in my comment:
* Does this reproduce in the demo app? What about at 2.18.5 (the latest version)?
* How long (roughly) does it take to reproduce (a second, minute, day, month, year, or aeon)?

**Comment by deepanshuDPS** [comment]
I just checked this issue on different devices, the timings depend upon different devices and it comes in 1-2 hours mostly. And after logging playback states, I got playbackState = 1, so I just want to ask, why player paused with player state = 1.

**Comment by icbaker** [comment]
Thanks, please also answer the other question:

> * Does this reproduce in the demo app? What about at 2.18.5 (the latest version)?

If you're able to reproduce in the demo app it would be helpful to share the result of `adb bugreport` taken immediately after playback stops. If you're unable to reproduce it in the demo app it suggests there's something different that your app is doing, and I would suggest you try and debug what that difference is.

I'm afraid we don't plan to spend 1-2 hours trying to reproduce this issue unless you can show clearly it's a library issue, rather than e.g. a problem with the serving infrastructure - you will have to help us out here.

----

> And after logging playback states, I got playbackState = 1, so I just want to ask, why player paused with player state = 1.

1 is [`STATE_IDLE`](https://exoplayer.dev/doc/reference/constant-values.html#com.google.android.exoplayer2.Player.STATE_IDLE), which indicates the player thinks it has completed playback (either because it reached the end, or because it encountered an error). Do you observe an callbacks to [`Player.Listener.onPlayerError`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onPlayerError(com.google.android.exoplayer2.PlaybackException))?

**Comment by deepanshuDPS** [comment]
It will take some time to configure my app to version 2.18.5. 
Do you observe an callbacks to [Player.Listener.onPlayerError](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onPlayerError(com.google.android.exoplayer2.PlaybackException))?
No, that's actually my question which I raised in this issue.

And a/c to documentation:
Player.STATE_IDLE: This is the initial state, the state when the player is stopped, and when playback failed. The player will hold only limited resources in this state.

Is there any memory or resources issue possible?? and If that, then is it resolved in updated version of exoplayer??

**Comment by icbaker** [comment]
Does the issue reproduce in the demo app? That should be easy for you to test (and easy to switch between versions, just check out a different git tag in the repo): https://exoplayer.dev/demo-application.html
