### ISSUE TITLE
MediaPlayerService: MediaPlayerService::getOMX

### ISSUE THREAD

**Issue by loveleopard** [google/ExoPlayer#11083]
**Please do not file new issues in this repository.**

All new questions should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=question.md).

We will continue to update and reply to existing issues in this repository and
will keep existing feature requests active.
03-25 15:01:09.421 26823 32433 I MediaPlayerService: MediaPlayerService::getOMX
03-25 15:01:09.422 28360  1484 I OMXClient: MuxOMX ctor
03-25 15:01:09.422 28360  1484 I ACodec  : onAllocateComponent:6752 mSoftCodecPref:0 componentName:OMX.google.mp3.decoder
03-25 15:01:09.422 28360  1484 I ACodec  : onAllocateComponent:6783 mSoftCodecPref:0 componentName:OMX.google.mp3.decoder
03-25 15:01:09.423   339  1004 I OMXMaster: makeComponentInstance(OMX.google.mp3.decoder) in mediacodec process
03-25 15:01:09.425   339 21241 E OMXNodeInstance: setConfig(153005e:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
03-25 15:01:09.425 28360  1484 I ACodec  : codec does not support config priority (err -2147483648)
03-25 15:01:09.445 28360 28395 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
03-25 15:01:09.453 28360 28381 D AudioTrack: Client defaulted notificationFrames to 3740 for frameCount 11220

**Comment by loveleopard** [comment]
com.google.android.exoplayer:exoplayer:2.10.4

**Comment by tianyif** [comment]
Hi @loveleopard,

Thanks for reporting! Could you please provide more details (reproduction steps, the media content to reproduce, and etc.) for this issue? You can refer to the [Issue Template](https://github.com/androidx/media/issues/new?template=question.md) for the details we need. 

We will begin to triage the issues in [media repository](https://github.com/androidx/media) (new home of ExoPlayer) only, so please make sure the future issues are filed for that repository instead of this one. I noticed that this issue was opened for ExoPlayer 2.10.4 and there is no corresponding Media3 released version, so it's fine to me that this issue continues staying in this repository. However, could you please also try to reproduce this issue on new versions of ExoPlayer since 2.10.4 is quite old and many issues might be already fixed along with the releases. Thanks!
