### ISSUE TITLE
Exoplayer:com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException

### ISSUE THREAD

**Issue by Sulochana-M** [google/ExoPlayer#11093]
### Bug

Hi , few devices of OS version 8 in android Tv devices are facing the issue 
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.broadcom.video_decoder.secure, Format(6, null, null, video/avc, avc1.64001e, 967648, null, [854, 480, 25.0], [-1, -1])

**Comment by Sulochana-M** [comment]
Its not reproducing in OS version of 9 Android Tv devices

**Comment by tonihei** [comment]
This isn't very actionable for us I'm afraid. To see more details of the error, we'd need a bugreport at least. It's very likely a device specific problem though and or an issue with an older decoder version running on the devices. Given these devices are unlikely to receive future updates, there may not be much we can do about it either. We may be able to block using this decoder under certain circumstances, but this may not help you either because the media will become unplayable?
