### ISSUE TITLE
Bumpy video playback of MPEG-2 video 

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#1112]
* video lags and freezes during playback, sound is good
* NVidia Shield
* file: https://docs.google.com/uc?id=0B4_pcf38WwzYQkZEeF8xNjNLcEU&export=download
* ExoPlayer dev branch (6eea4bdbc34dea86a5bc81991163ca26761cae83)
* according to the log, there are frame drops:

> 01-04 22:52:44.699 27018-27018/com.google.android.exoplayer.demo D/EventLogger: droppedFrames [2.42, 50]
> 01-04 22:52:46.124 27018-27018/com.google.android.exoplayer.demo D/EventLogger: droppedFrames [3.85, 50]
> 01-04 22:52:48.046 27018-27018/com.google.android.exoplayer.demo D/EventLogger: droppedFrames [5.77, 50]

* codecs used:

> 01-04 22:52:42.352 27018-27018/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.07, OMX.Nvidia.mpeg2v.decode]
> 01-04 22:52:42.358 27018-27018/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.08, OMX.Nvidia.mp2.decoder]

* it could be codec's performance issue, but _MXPlayer_ with **same** codec plays this video properly
* codec related log from ExoPlayer: https://docs.google.com/uc?id=0B4_pcf38WwzYbjEtaHAxaER6RnM&export=download
* codec related log from MxPlayer: https://docs.google.com/uc?id=0B4_pcf38WwzYb0liVnlrM0JSbkk&export=download

**Comment by ojw28** [comment]
This happens because ExoPlayer assumes that there will be at most one video frame per PES packet in the stream. The sample provided packages multiple video frames into each PES packet, which results in us assigning the same timestamp to all of them.

The fix will be to parse the frame-rate from the stream and use of it to increment the frame timestamp in this case.
