### ISSUE TITLE
Video playback exception

### ISSUE THREAD

**Issue by 1eooyang** [google/ExoPlayer#11139]
### Bug

Why I use ExoPlayer to play links: https://online-education.codemao.cn/228/codecamp/e7e744a1933747c5ada76ca79e7fced6.mp4 will be caton the first few seconds, while the player using the system play normally, Please help to provide reasons and solutions.

**Comment by 1eooyang** [comment]
https://user-images.githubusercontent.com/20480296/234748750-0c183680-05d2-4832-9e7d-b27ee62f4248.mp4

**Comment by rohitjoins** [comment]
Hi @1eooyang,

Based on the information provided, which is somewhat unclear, it seems that the issue you are describing pertains to a delay in video playback initiation and when seeking through the media.

The latency you are experiencing when trying to play the video is likely due to the server hosting the media being slow to respond. I have attempted to play the video on multiple media players and experienced the same delay. This issue does not seem to affect all MP4 or media files universally. Therefore, I would suggest verifying this by attempting to play MP4 files hosted on a different server/website.

Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by FongMi** [comment]
這影片前幾秒本來就是定格的畫面，所以EXO沒問題。

https://user-images.githubusercontent.com/3471963/235091226-ee9f7b6c-d297-482c-a26d-29d1cb434613.mp4
