### ISSUE TITLE
Does exoplayer support to play song with multiple URL at same time ?

### ISSUE THREAD

**Issue by keyurgandhi** [google/ExoPlayer#11178]
In my use case, I have multiple URL that includes different music. 
I have to combine all the URLs and play through Exoplayer.
I am able to play the music with a single URL, but not sure how to manage the multiple URL at the same time.

Can someone know me the feasibility of this use case with Exoplayer android? Can someone through light on this ?

I am fairly new to the media player and audio streaming.
I read somewhere that I could use the output channel for individual URL output as well.

**Comment by tonihei** [comment]
Please file new issues in the media3 issue tracker as requested by the template.

Otherwise, I believe you want to play multiple audio stream in parallel? The easiest way to do this is to use multiple players if you don't need very close coordination between the playbacks. Other solutions are more complex and you can find some pointers here: https://github.com/google/ExoPlayer/issues/9876#issuecomment-1017646244 (for example)

**Comment by keyurgandhi** [comment]
Thanks @tonihei , I have already tried the multiple exoplayer instances, but there is a sync issue which breaks the user experience.
Let me checkout the other option you have mentioned.
