### ISSUE TITLE
Duplicate Guava with Firebase Analytics Issue

### ISSUE THREAD

**Issue by Negatives-One** [google/ExoPlayer#11176]
Describe the issue
It is impossible to generate an android build with AVPro Video and Firebase Analytics in the same project. A duplicate classes error occurs, and when I delete the guava-31.1-android from AVPro, the build works, but the videos do not play. What is the best way to deal with this problem?

Your Setup (please complete the following information):

Unity version: 2021.3.15f1
AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video Core
Operating system version: Windows 11 Pro
Device model: Xiaomi Redmi Note 11S
To Reproduce

Install AVPro Video Package
Install Firebase Analytics Package
Try to build for Android

Screenshots

![image](https://github.com/google/ExoPlayer/assets/49993384/b2ce8ad1-56fb-4bde-a7a6-64d5215375a4)

![image](https://github.com/google/ExoPlayer/assets/49993384/77518b19-93e2-409d-a997-1d12989176c1)

Is there any solution for this problem? I have tried all the common solutions and nothing has worked so far.

**Comment by Negatives-One** [comment]
The AVPRO people said it was an Exoplayer requirement when I contacted them: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1525

**Comment by icbaker** [comment]
> The AVPRO people said it was an Exoplayer requirement when I contacted them: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1525

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1525#issuecomment-1533015921 is just saying that ExoPlayer uses Guava 31.1, which is correct. Therefore any app or library that uses ExoPlayer needs to compile with Guava 31.1 (or a new version) too (i.e. this isn't anything special about AVPro).

Given that, it should be possible to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of a very simple app that just depends directly on ExoPlayer and Firebase Analytics and demonstrates the problem.

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this. 

----

This doesn't look like a problem with ExoPlayer, but we can try and offer some suggestions if you can help us to easily repro.

**Comment by Negatives-One** [comment]
Minimal reproducible example submitted

**Comment by icbaker** [comment]
Is it possible to create a minimal example that **doesn't** use Unity? I would expect roughly:

1. Create a new empty Android Studio project
2. Depend on ExoPlayer and Firebase Analytics, and use both in minimal ways in the empty Activity
3. Sync and build the project - expect to see the failure.

That will make it much easier to for us to understand what's going on (because we don't routinely use Unity, so it's an unfamiliar environment to debug in).

If the problem only reproduces in Unity or with the AVPro plug-in then that suggests to me this is more about Unity and/or that plug-in rather than the way ExoPlayer depends on Guava.
