### ISSUE TITLE
ExoPlayer apk ??

### ISSUE THREAD

**Issue by spotanjo3** [google/ExoPlayer#11189]
I tried to download APK version but it was expire at "ACTION". Now I cannot find APK file. Where is it ? Thank you.

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by spotanjo3** [comment]
Okay, I cannot find the apk file to install because you only have the source folders.

**Comment by icbaker** [comment]
ExoPlayer is a library, so we don't really offer "the APK".

You can depend on us via maven or locally: https://github.com/google/ExoPlayer#using-exoplayer

If you're asking about how to build the demo app APK: https://developer.android.com/guide/topics/media/exoplayer/demo-application

I'm going to close this because I believe I've answered the (relatively unclear) question as best I can.
