### ISSUE TITLE
Does ExoPlayer support HbbTV with Dash and SS?

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#11180]
Does ExoPlayer support HbbTV with Dash and SS?

**Comment by tonihei** [comment]
ExoPlayer supports DASH and SS, please see https://developer.android.com/guide/topics/media/exoplayer/supported-formats#adaptive_streaming

**Comment by juanpef** [comment]
Yes, I know. But I'm asking about HBBTV support with these protocols.

**Comment by tonihei** [comment]
Could you explain in a bit more detail what this means? If you are worried about supporting specific elements of a spec, please just try it out and report which elements are not working as you'd expect.

**Comment by juanpef** [comment]
HbbTV is a protocol whose specifications are herre: https://www.hbbtv.org/resource-library/#specifications

I want to include HbbTV support on our app, so we need to know it is supported by ExoPlayer. I need to know it before build all environment.

**Comment by tonihei** [comment]
The linked specification is a huge collection of general media serving requirements and constraints, most of which are not relevant to the player library. At a quick glance, the only reference to DASH is Annex E, which describes a collection of general DASH features and behaviors. I couldn't see anything significant that ExoPlayer doesn't support and I'd encourage  you to report more specific issues with your stream setup if needed. That's because there is little benefit for us going through this list line by line to check if we support it, because most of your actual playback will only use a small subset of the mentioned features.

**Comment by juanpef** [comment]
I'm sorry.
My question is, if MPD (Dash) or manifest (SS), includes HbbTV tag, Exoplayer is able to display red button (over the video) or report it to the app and then open corresponding url.

**Comment by tonihei** [comment]
Can you point me to the red button in the spec? Without knowing any further details, I suspect that has be solved outside of the player in your UI.

**Comment by juanpef** [comment]
Yes, I think so. But I understand that, if ExoPlayer supports it, Exoplayer will report HbbTV info to our UI (app)

**Comment by tonihei** [comment]
I'm not familiar with what HbbTV info is (or the red button you mentioned), so I'm not entirely sure what you are asking for. Could you explain the exact missing feature or point me to the relevant section in the Hbb spec?
