### ISSUE TITLE
ExoPlayer  configuration in landscape format forever

### ISSUE THREAD

**Issue by ssepulveda08** [google/ExoPlayer#11195]
Hello everyone,

I am using ExoPlayer with jetpack compose and I need to create a view that plays the video in landscape always and the user can not change it no matter the device config or the activity, for this I have used several approaches like rotating the main container or directly to StyledPlayerView alguein have an idea of how to solve this. or if it is not possible 😞 

```java
val exoPlayer = ExoPlayer.Builder(LocalContext.current)
        .build()
        .also { exoPlayer ->
            val mediaItem = MediaItem.Builder()
                .setUri(videoUri)
                .build()
            exoPlayer.setMediaItem(mediaItem)
            exoPlayer.prepare()
        }
    DisposableEffect(
        AndroidView(
            modifier = Modifier.fillMaxSize().rotate(90f),
            factory = {
                StyledPlayerView(context).apply {
                    player = exoPlayer
                    useController = true
                    resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FILL
                    layoutParams = FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    )
                }
            })
    ) {
        onDispose {
            exoPlayer.release()
        }
    }
```

**Comment by oceanjules** [comment]
We can't really advise you on Compose details, since this is a generic question not really related to ExoPlayer, and you may get better answers by asking on sites like StackOverflow. A quick search led me to a couple of these links which you might find helpful:


https://stackoverflow.com/questions/11208144/how-to-play-video-in-only-landscape-mode-in-android

https://developer.android.com/reference/android/app/Activity#setRequestedOrientation(int)

https://stackoverflow.com/questions/69079267/disable-landscape-mode-in-compose

https://stackoverflow.com/questions/69230049/how-to-force-orientation-for-some-screens-in-jetpack-compose
