### ISSUE TITLE
frame drops when playing 60fps DASH->4K(MP4,H264,Clear) in Demo app when speeding

### ISSUE THREAD

**Issue by litianjun05090** [google/ExoPlayer#11209]
It is offcial demo app and video. Speed is set as 2x.

My device is Huawei p40pro , is this a device specific problem ? I have tried One plus , still has the problem.  
![微信图片_20230613225450](https://github.com/google/ExoPlayer/assets/37604506/267faef4-af35-453b-892f-6543a6bb8943)

**Comment by litianjun05090** [comment]
vfpo drops immediately when speed is set to 2x , and back to normal when set to 1x.

**Comment by rohitjoins** [comment]
The problem is specifically related to the device being used. When the device's decoding capability is insufficiently fast, there may be frame drops when playing videos at higher speeds. This occurs when the video decoder cannot decode the content quickly enough to match the fast audio.

To illustrate, I tested the same video on a Pixel 6 Pro with the playback speed set to 2x. In this case, the video played smoothly without any frame drops, and the `vfpo` value doesn't drop.

**Comment by litianjun05090** [comment]
So is there a way that I can play it smoothly on some older devices ?  I tried to disable the audio when speeding but no luck.

**Comment by icbaker** [comment]
If the device you're experiencing the problem on is running at least Android 6.0 but less than Android 12, you can try enabling asynchronous buffer queueing to `MediaCodec` (this is enabled by default on Android 12 and above): https://developer.android.com/guide/topics/media/exoplayer/customization#enabling-asynchronous-buffer-queueing

**Comment by litianjun05090** [comment]
Tried `DefaultRenderersFactory renderersFactory =
    new DefaultRenderersFactory(context).forceEnableMediaCodecAsynchronousQueueing();
ExoPlayer exoPlayer = new ExoPlayer.Builder(context, renderersFactory).build();` in Demo app ,but still not work.

**Comment by rohitjoins** [comment]
@litianjun05090,

I'm sorry but doesn't seem we can do anything to improve the situation as it is limited by device capability to decode frames.

**Comment by litianjun05090** [comment]
Thanks though , I will try `MediaPlayer` ,see if I can get any luck.
