### ISSUE TITLE
Skip ads while fast forwarding/ Remove first pre roll ads in resumed content.

### ISSUE THREAD

**Issue by dev-sharma-deltatre** [google/ExoPlayer#11212]
hi,
Is there any way that pre-roll ads can be removed in the condition when the user is resuming the content from the continue watching row?
Also, need to skip the ad when the user if fast forwarding. Is there any way to achieve this.

**Comment by marcbaechinger** [comment]
> Is there any way that pre-roll ads can be removed in the condition when the user is resuming the content from the continue watching row?

I assume you are using  the IMA extension with client-side ads (please add all information initially, so we can be sure to answer for the right thing from the beginning. It for you benefit because the waiting time for a second answer tends to be much longer).

If there is only a pre-roll, then you can simply not add the ad metadata to your media item, when you add it to the player. The stream then plays without ads. If there are further ads to be played I don't think you can drop single ads or ad groups.

> Also, need to skip the ad when the user if fast forwarding

Generally, the player doesn't allow seeking when an ad is playing. You can use skippeable ads, which then can be skipped by the user. With IMA, there is no API to skip over ads other than with skippeable ads.

**Comment by dev-sharma-deltatre** [comment]
@marcbaechinger, thank you for the quick response. 
So there is no way to just remove the pre-roll ad and keep the mid-rolls and post-rolls?
Also, when the user is fast-forwarding the content and mid-rolls are there, then ads cannot be skipped, unless they are skippable ads?
Please confirm.

**Comment by marcbaechinger** [comment]
> So there is no way to just remove the pre-roll ad and keep the mid-rolls and post-rolls?

Confirmed.

> Also, when the user is fast-forwarding the content and mid-rolls are there, then ads cannot be skipped, unless they are skippable ads?

Confirmed when an ad is playing, the user can not seek. If an ad is skippeable, then the user can not seek until the non-skippeable duration is played. Then the user can skip the ad.

I can also confirm that when a user seek across the cue point of an ad, then the player plays the ad and then goes to the  requested seek position.

**Comment by dev-sharma-deltatre** [comment]
Thank you so much for the information.
