### ISSUE TITLE
MediaController.getDeviceVolume() returns 0

### ISSUE THREAD

**Issue by roomtek** [google/ExoPlayer#11225]
### Bug

This affects release 1.1.0-rc01.

The MediaController.getDeviceVolume() returns 0, but the volume changes.

**Comment by roomtek** [comment]
When ExoPlayer.Builder().setDeviceVolumeControlEnabled(true) is set, the proper volume level is returned.

**Comment by oceanjules** [comment]
That is not a bug, but rather intended behaviour going forwards.

The idea is that a player should opt into device volume control - whether you want to increase/decrease/mute or simply get the device volume. 

- setDeviceVolumeControlEnabled(true) sets the control to true
- if deviceVolumeControlEnabled==true, then the following commands will be added to the player:

https://github.com/androidx/media/blob/release-1.1.0/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayerImpl.java#L316-L320

- as you rightly pointed out, the default volume to return is 0, since without device volume control opt-in, we do not have streamVolumeManager and hence cannot extract that information

https://github.com/androidx/media/blob/release-1.1.0/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayerImpl.java#L385-L390

https://github.com/androidx/media/blob/release-1.1.0/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayerImpl.java#L1711-L1718
