### ISSUE TITLE
How to get detail information from VideoChunk in DASH streaming

### ISSUE THREAD

**Issue by joshimaulik** [google/ExoPlayer#1122]
I am playing MPEG DASH streaming using exo player. I need to extract the video chunks and need to know what information are there in video chunks e.g. how long that chunk is, format of that video chunk etc...

I tried to log that information in DemoPlayer.java class's onLoadStarted(int sourceId, long length, int type, int trigger, Format format, long mediaStartTimeMs, long mediaEndTimeMs) method. But it gives me sourceID= 0 & 1, length=-1 and format=com.google.android.exoplayer.chunk.Format@36, @35 & @34. 

Please let me know if I am looking at correct place or is there any other way to extract the chunk information.

Thanks in Advance

**Comment by ojw28** [comment]
I think you're looking in the right place. The format object contains a bunch of additional information you can drill into. The start and end times should be set correctly. The actual size of the content in bytes in most likely unknown at the point when the load is started (this would be true unless it's explicitly specified in the manifest or in a SIDX box in the media), which is why it's not reported. You can use onLoadCompleted to retrieve the number of bytes that were loaded.

So I'm not really sure what you're missing...

**Comment by joshimaulik** [comment]
Okay, let me check and verify in onLoadCompleted event.

Thank You,

**Comment by joshimaulik** [comment]
I checked it today, and seems it gives me all the information which I needed, like how long the chunk is, type of the chunk, etc...

Thank You..
