### ISSUE TITLE
What does Player.release() exactly do?

### ISSUE THREAD

**Issue by Animesh273** [google/ExoPlayer#11236]
If i call player.release for the second time what it will do?
How to make sure player.release is only called if its not called before?

**Comment by microkatz** [comment]
@Animesh273 
Player.release is the interface method use by the implementing class to release any held resources. This is to free up limited resources such as video decoders for use by other applications. The effect of calling release twice depends on how the method was implemented.

ExoPlayer's default implementation, as mentioned above, frees up the limited resources. ExoPlayer's default player implementation's release method is fine to call twice. It just is effectively a no-op the second time around.

In addition, the default implementation's release method is required to run on the Application thread and so the method is thread-safe. Two threads cannot call the release method at the same time.

>How to make sure player.release is only called if its not called before?

If you are using the default ExoPlayer Player implementation then because of the thread safety you can do a simple
```java
public void releasePlayer() {
    if (player != null) {
        player.release();
        player = null;
    }
}
```
Else you can use some Lock on the player instance to make sure release is not called at the same time nor twice.

**Comment by icbaker** [comment]
Regardless of ExoPlayer's current implementation details, the `Player` [interface javadoc is clear](https://developer.android.com/reference/kotlin/androidx/media3/common/Player#release()) that you must not call `release()` twice:
> The player must not be used after calling this method.

i.e. you must not call **any** methods on `Player` after you've called `release()`, including calling `release()` again.

Relying on being able to call `release()` twice might work today, but it might break in future versions of the library.

**Comment by Animesh273** [comment]
Thankyou for your answers @microkatz and @icbaker.
