### ISSUE TITLE
what is the reason of this library getting depreciated ?

### ISSUE THREAD

**Issue by ThreeMinutesFix** [google/ExoPlayer#11243]
i read the quote not to ask new question but this question is related to exoplayer so it wil be logic to ask here? any feature change from this to media3? like previously we had videoview but it has lots of limitation so its good to move to exoplayer but i would like to know the different from this to new androidx media 3 exoplayer library kindly answer and close the issue i just want to know so i can tell others for education purpose.

**Comment by tonihei** [comment]
Media3 ExoPlayer and this stand-alone ExoPlayer project are exactly the same code (= no feature change for ExoPlayer). 

We changed the package names to be more officially part of the AndroidX support library family and provide better stability guarantees in the future. We also moved other media utilities (MediaSession support, Muxing, Transformation) into Media3 too so that all these libraries can work well together and share common code. 

If you already have an ExoPlayer-based project, you can use the automatic [migration script](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#exoplayer) to change all the package name import statements in your code to Media3. We marked all the classes in this project as deprecated to make it clear that all future versions will only be published with the Media3 package name and not in this repository.  For a bit of background reading, you can also refer to this [blog post](https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html) for example.

**Comment by ThreeMinutesFix** [comment]
thank you @tonihei  for answering my question. i understand now thanks once again
