### ISSUE TITLE
Synchronizing playback position for two players

### ISSUE THREAD

**Issue by LikeAnyan** [google/ExoPlayer#11265]
Greetings,
I've got a question about synchronizing the playback position for two players. I have two videos of the same length (front and back views let's say) that should be played at the same time and be synchronized in their playback position (so if video A is resumed at 1:05, ideally video B should be resumed at 1:05 as well)
Currently am ended up using two different player instances, have used ForwardingPlayer to pass all the commands like start / pause / seek to both players instead of one, but playbacks may run with delays in case of using seek function. Wonder what's the best way to achieve playing two videos in the same playback position keeping in mind the seek function.
Thank you in advance.

**Comment by microkatz** [comment]
Hello @LikeAnyan,

In order to synchronize two players, they must be using the same mediaClock. In this way, the videos will be sync'd to present at the same time. Here is a [link](https://github.com/google/ExoPlayer/issues/8644#issuecomment-788788733) to an issue thread discussing a solution for you. Basically the secondary player needs to run a video renderer that implements MediaClock and whose getCurrentPositionUs returns the position of the renderer from the first player.

Hope that helps!

**Comment by LikeAnyan** [comment]
Hey @microkatz 
Thank you so much, ur advice helped me to synchronize both videos by using the `MediaClock` and relying on the other's render position.
Have an awesome day and thank you again.
