### ISSUE TITLE
Wrong unit for current live offset value

### ISSUE THREAD

**Issue by sebimag** [google/ExoPlayer#11277]
### Bug

Hello,

I'm playing a live content with exoplayer and when I call getCurrentLiveOffset method I get 1693330794895 as value

According to the documentation of my CDN the live offset should be around 16 second
getCurrentLiveOffset should return a result in ms.

Is there a setting to specify the correct unit ? 

Thank you for your help

**Comment by tonihei** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not
accepting any new issues in this project. Please file your issue in the
`androidx.media3` GitHub project instead:
https://github.com/androidx/media/issues

When you do this, please also include sample media to reproduce the problem, otherwise it's unlikely we can provide any insights into your problem.
