### ISSUE TITLE
FATAL EXCEPTION: ExoPlayer:Loader:Loader:HlsSampleStreamWrapper

### ISSUE THREAD

**Issue by rahulnainwalttn** [google/ExoPlayer#11278]
### Bug

Getting a crash from exo player - FATAL EXCEPTION: ExoPlayer:Loader:Loader:HlsSampleStreamWrapper
<img width="899" alt="Screenshot 2023-09-01 at 1 07 30 PM" src="https://github.com/google/ExoPlayer/assets/136161024/182a74d7-419a-4ff3-8d66-66f120a44273">

Basically we are using react-native-video and our app is getting crashed with this error log.

We are using  - 
1- 'com.google.android.exoplayer:exoplayer:2.14.1'
2- 'com.android.tools.build:gradle:4.2.2'

<img width="931" alt="Screenshot 2023-09-01 at 1 18 59 PM" src="https://github.com/google/ExoPlayer/assets/136161024/86c9b1c3-543d-41ee-8e7e-d69d9199842b">

**Comment by icbaker** [comment]
`Util.toLowerInvariant` (and all its usages) was removed in https://github.com/google/ExoPlayer/commit/c50084e7baefc92f6222e1624fb716d20d37b160 which was included in 2.14.0.

Reading your stack traced, L296 of `OkHttpDataSource` in v2.14.1 does not invoke this method (which makes sense, since that method was already removed then): https://github.com/google/ExoPlayer/blob/r2.14.1/extensions/okhttp/src/main/java/com/google/android/exoplayer2/ext/okhttp/OkHttpDataSource.java#L296

Walking back through the history of `OkHttpDataSource` it seems you're likely using 2.13.3 of the exoplayer okhttp module: https://github.com/google/ExoPlayer/blob/r2.13.3/extensions/okhttp/src/main/java/com/google/android/exoplayer2/ext/okhttp/OkHttpDataSource.java#L296

This is not compatible with 2.14.1 of the common module where the `Util` class  lives. You must use the same version of all exoplayer libraries (in order to avoid problems like this): https://github.com/google/ExoPlayer/blob/r2.13.3/extensions/okhttp/src/main/java/com/google/android/exoplayer2/ext/okhttp/OkHttpDataSource.java#L296

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file any further issues in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

**Comment by rahulnainwalttn** [comment]
OK - Thanks
