### ISSUE TITLE
RenderersFactory is @UnstableApi. What to do?

### ISSUE THREAD

**Issue by OmidNejadabbasi** [google/ExoPlayer#11292]
The class `import androidx.media3.exoplayer.RenderersFactory` is marked with `@UnstableApi` . What should I use instead? I want to apply some audio effect to the player and modify the audio buffer.

**Comment by icbaker** [comment]
You can use this class, you just need to opt-in as explained here: https://developer.android.com/reference/androidx/media3/common/util/UnstableApi#opting-in-to-use-unstable-apis

The media3 stable API aims to support common developer journeys. We've started off with some relatively simple ones, and anything more complex needs to use the unstable API (note that if you used exoplayer2 in the past, then you were always using an 'unstable API' we just didn't have an annotation for it, since the whole API was the same level of instability).

Modifying the audio buffer is a relatively low-level operation that isn't currently supported by the stable API. If you'd like us to consider it, please file a new isse in the media3 GitHub tracker with full details/context of what you're doing and the media3 APIs you currently use to do it.

You've asked about `@UnstableApi`, which is only present in media3, but you've posted your question on the exoplayer2 issue tracker. The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file any further issues in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

**Comment by OmidNejadabbasi** [comment]
@icbaker  
I want to apply some effect to audio. Can I do that with the `RenderersFactory` and `Renderer` api ? I looked at the docs and that's what I concluded. Correct me if I'm wrong.
I am OK with using `@SuppressLint("UnsafeOptInUsageError")` annotation to get rid of the error.
