### ISSUE TITLE
HLS with frequent updates makes the timer flashing on now playing screen of android auto

### ISSUE THREAD

**Issue by knnthr89** [google/ExoPlayer#11318]
### Bug

HLS live stream that frequently sends updates makes the timer of current position on now playing screen flashing every time on android auto.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

When filing your new issue please provide much more info (as requested in the issue template), otherwise I'm afraid we won't be able to help much.
