### ISSUE TITLE
First Line subtitle was lost .

### ISSUE THREAD

**Issue by vipjml** [google/ExoPlayer#1136]
http://subscene.com/subtitle/download?mac=9vdN541sK3CJzJXlawzukVbLF_YeiqKwsB62_ws6DQGT981Az0vVhZao5RCKs2bY0

The first line subtitle was lost. This subtitle is utf-8 with bom, So the first line is "\uFEFF1",so the parseInt of the first line is failed.  I think the follow code should add a special handle for utf-8 bom file.

SubripParser:74
````java
 // Parse the index line as a sanity check.
 try {
Integer.parseInt(currentLine);
 } catch (NumberFormatException e) {
 Log.w(TAG, "Skipping invalid index: " + currentLine);
continue;
 }
````

**Comment by ojw28** [comment]
Thanks for reporting this. Parsing of this file actually fails even more badly on the dev branch, due to a separate issue. We'll fix that, and then fix the specific issue that you mention (albeit in a different place - in order to handle files starting with a BOM more generally as opposed to fixing the problem only for Subrip).

**Comment by ojw28** [comment]
Fixed on the dev branch.
