### ISSUE TITLE
how make default buildconfig to release I mean how change gradle that by default when build APK on Android Studio always be release by default?

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [google/ExoPlayer#11373]
For Demo application how set the default build config always set as  Release.
I mean how set following       signingConfig signingConfigs.debug  to signingConfigs.release ?

Thanks. 

```

  buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles = [
                    "proguard-rules.txt",
                    getDefaultProguardFile('proguard-android.txt')
            ]
            signingConfig signingConfigs.debug
        }
        debug {
            jniDebuggable = true
        }
    }
```
Sincerely
Kind Regards,

**Comment by oceanjules** [comment]
Please do not abuse the issue tracker by circumventing the deprecation confirmation

`I understand this project is deprecated, that I should file my issue in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) instead of here, and this issue will be closed with no response.`

The issue is not related to the library, but to signing. Please take a look at the following guides:
- https://developer.android.com/build/build-variants#signing
- https://developer.android.com/studio/publish/app-signing

**Comment by pooya-mohammadhossein** [comment]
@oceanjules This is not a valid response.  I have tried to create a Question in this GitHub but the feature of asking question in this GitHub project was not available. 
Bye!

**Comment by oceanjules** [comment]
@pooya-mohammadhossein The message states that you should not be using this **deprecated** Github repo for raising any questions, which is why it didn't work. Head over to [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) for any Media3/Exoplayer related problems.
