### ISSUE TITLE
Fatal signal 5 (SIGTRAP) with UHD media on Samsung Galaxy S6

### ISSUE THREAD

**Issue by jfcogato** [google/ExoPlayer#1140]
- Run the demo
- Select the media with labels name: WV: Secure UHD (MP4,H264)  on WidevineDash: MP4, H264 list.

The app will crash with the next error:
frameworks/av/media/libstagefright/ACodec.cpp:2375 CHECK(def.nBufferSize >= size) failed.
Fatal signal 5 (SIGTRAP), code 1 in tid 6037 (CodecLooper)

We detected that too on our contents with UHD resolutions, and only crash on Samsung galaxy S6.

**Comment by ojw28** [comment]
- We'll take a look at this, thanks.
- As an aside, why are you sending 4K content to a device that has a resolution significantly below 4K, and a screen whose physical size is such that it's debatable that the user will be able to perceive a difference v.s. a lower quality? Isn't that just wasting the user's battery + network? Shouldn't you be restricting stream resolution to 1080p on the S6?

**Comment by jfcogato** [comment]
Yeah, I know, but the api give us all that information. Thanks for all.

**Comment by ojw28** [comment]
Closing because it's unlikely there's anything we can do to resolve this. It's likely the stream significantly exceeds the capabilities of the device, and the device is then not failing in a graceful way. It's unlikely to impact streaming services because they should not be serving UHD content to an S6.
