### ISSUE TITLE
How to suspend buffering?

### ISSUE THREAD

**Issue by NoGirlFriendException** [google/ExoPlayer#1163]
When user switches from wifi to mobile network, I wish to stop buffering. How can this be done? Thanks a lot!

**Comment by AquilesCanta** [comment]
The question is not perfectly clear. For starters, I can tell you need to detect whether connectivity has changed (this may help http://stackoverflow.com/questions/3767591/check-intent-internet-connection). If you just want to stop using the network, then you could release the player.

Otherwise, if you need something more complex, you could think about implementing your own DataSource. Perhaps something like a toggable HttpDataSource. I could be misunderstanding your problem, but I will not be able to solve the application specific issues, unfortunately.

**Comment by NoGirlFriendException** [comment]
thx for the answer!
