### ISSUE TITLE
ogg flac extractor

### ISSUE THREAD

**Issue by iasjennen** [google/ExoPlayer#1175]
@ojw28 thanks for your latest commits

do you plan to add ogg flac support in the near future?
I am looking for a good way to bring lossless audio to an android app, but haven't found a decent solution yet.

**Comment by ojw28** [comment]
This is already tracked by the combination of #1145 and #366.

FLAC is somewhat awkward, because Android doesn't have a FLAC decoder at the platform layer. If I remember correctly it provides an extractor that converts FLAC to PCM, but doesn't expose just the decoder part through MediaCodec. Hence our currentl plan is to support FLAC as an extension, where you'd need to bundle the FLAC decoder as a library inside of your apk. It's something we're working on, but we don't have an ETA.
