### ISSUE TITLE
[HLS] Large ID3-data not supported by parser

### ISSUE THREAD

**Issue by perchrh** [google/ExoPlayer#1181]
ID3 data can be divided into multiple PES packets, according to spec. 
ExoPlayer's Id3Parser doesn't seem to support this case, and fails at ID3 tags longer than 65535 (-header) bytes. See stacktrace below.

Here is an example stream that breaks the parser, 
http://www.pvv.org/~perchrh/large_id3_packet_hls/playlist.m3u8

The relevant piece of HLS documentation seems to be this (section 2.4), https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/2/2.html

"If an ID3 tag is longer than 65535 bytes, it must have more than one PES header. The second and following PES headers must have data_alignment set to 0, and should have the PTS_DTS_flags set to ‘00’ (and hence no PTS)."

<pre><code>
java.lang.ArrayIndexOutOfBoundsException: src.length=65527 srcPos=40914 dst.length=26920 dstPos=0 length=26920
   at java.lang.System.arraycopy(Native Method)
   at com.google.android.exoplayer.util.ParsableByteArray.readBytes(ParsableByteArray.java:149)
   at com.google.android.exoplayer.metadata.Id3Parser.parse(Id3Parser.java:67)
   at com.google.android.exoplayer.metadata.Id3Parser.parse(Id3Parser.java:31)
   at com.google.android.exoplayer.metadata.MetadataTrackRenderer.doSomeWork(MetadataTrackRenderer.java:110)
   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
   at android.os.Handler.dispatchMessage(Handler.java:98)
   at android.os.Looper.loop(Looper.java:211)
   at android.os.HandlerThread.run(HandlerThread.java:61)
   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
</code></pre>

**Comment by perchrh** [comment]
My understanding is that if _data_alignment  = 0_, that means the contents of this PES header is a continuation of the previous.

**Comment by ojw28** [comment]
I agree this is broken, but I'm also confused by the spec. Having read a PES packet how are you supposed to determine whether you have a complete ID3 tag, without having to wait for the next PES packet in the metadata stream and look at its data_alignment_indicator? Waiting doesn't seem viable, since you may have to wait for an indeterminately long period of time. There might not even be a next PES packet, since you might have just read the final ID3 tag in the stream.

One approach would be to assume that you have a complete ID3 tag unless the PES packet was of length 65535. The spec doesn't mandate this, but it's probably a reasonable assumption (and is true for the sample you posted). That still doesn't solve the edge case where an ID3 tag happens to be exactly the length that would result in the wrapping PES packet being of length 65535, however :(.

Thoughts?

**Comment by ojw28** [comment]
I guess we'll just have to parse the ID3 header as well. Which is highly unfortunate, but oh well. Unless you can think of a better way?

**Comment by perchrh** [comment]
Those are good points about the spec. 
When PES packets are handled, the data alignment indicator (DAI) of the packet can be read, and the payloads aggregated until the next packet with DAI = 1 arrives. Then the data can be passed along, to have the ID3 data parsed. 
There might be some part of the spec that says you must make sure to send a PES packet with DAI = 1 to end the final sequence of ID3 data, to address the mentioned edge case. The assumption that non-max size payload in a continuation PES packet mean that this is the last continuation packet, may be safe in practice. 
Regarding the waiting, I don't have any ideas, other than that yes, that seems like a shortcoming of the spec. If PES-packets are not allowed to span TS-files/chunks then the waiting would be less of an issue? I don't know if they are..

**Comment by ojw28** [comment]
Even waiting for the next packet with DAI=1 in the normal case is bad, since you might end up waiting for an arbitrarily long period of time before it arrives. It does seem like a shortcoming.

Fortunately it's actually pretty trivial to read the size of the complete ID3 tag. At the end of each PES packet you can then check whether you've read that number of bytes. We'll do that.

**Comment by perchrh** [comment]
That sounds like a good solution! If the stream doesn't signal an end to the final ID3 data-sequence, that could be considered an error in the stream.
