### ISSUE TITLE
Loader:HLS CPU consumption

### ISSUE THREAD

**Issue by Palethorn** [google/ExoPlayer#1227]
Hi,
it seems like Loader:HLS thread is consuming quite a lot of the CPU resources
`13720 13918  1  23% R 709064K  32016K  fg u0_a67   Loader:HLS      com.google.android.exoplayer.demo`
I've noticed this using top command on shell. Since it's a quad core CPU and consumption shows 23% I would assume that one core is absolutely busy. Problem doesn't manifest with DASH. I'm using master branch version and I also tried 1.5.3, 1.5.4, 1.5.5 versions with the same effect. Android version is 4.4.2. I've tested on 2 different android boxes with the same effect. Furthermore, the playback stops after a few seconds with BehindLiveWindowException and I don't notice anything odd with the source. Could this be related. If you require our sample source please say so and I will send it to your email.

**Comment by ojw28** [comment]
- I'm unsure whether that means one core is 100% busy or whether one core is 23% busy. I would definitely test your assumption though; I've seen stats reported in a way where four cores being busy is reported as 400%. It should be pretty easy to verify one way or another by creating a test app that busy loops 4 threads, or something like that?
- DASH uses a *much* more efficient container format than HLS (fmp4 rather than mpeg-ts). There are significant benefits to switching to DASH; one of which is reduced CPU consumption due to having to do significantly less work extracting the media samples from the container. You can read more about this [here](https://google.github.io/ExoPlayer/2015/05/08/the-benefits-of-dash.html). It may be that we can make optimizations to our mpeg-ts extractor, but CPU consumption will always be higher due to the inherent disadvantages that you incur when using mpeg-ts.
- It's unclear whether the high CPU utilization actually matters. It's definitely not related to `BehindLiveWindowException`. If you search this issue track (including closed issues) then you should find information about that exception.
