### ISSUE TITLE
Problems with streaming MP3 and ExtractorSampleSource

### ISSUE THREAD

**Issue by SvenCarstensen** [google/ExoPlayer#1231]
Hi,

i have some trouble to make ExtractorSampleSource stream MP3 work.

The MP3 URL is "http://stream.klassikradio.de/live/mp3-128/www.klassikradio.de/"

The following Code doesn't work:

Allocator allocator = new DefaultAllocator(4096);
DataSource dataSource = new DefaultUriDataSource(getApplicationContext(), null, "Mozilla/5.0");
ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator, 4096);
audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, MediaCodecSelector.DEFAULT);
player.prepare(audioRenderer);
player.setPlayWhenReady(true);  

This Code works, but shows deprecated warnings:

FrameworkSampleSource sampleSource = new FrameworkSampleSource(this, uri, null);
audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, MediaCodecSelector.DEFAULT);
player.prepare(audioRenderer);
player.setPlayWhenReady(true);

What's wrong with the upper code?

Thanks in advance for your help!

Regards

Sven

**Comment by andrewlewis** [comment]
Try using the allocation and buffer size values from [ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java#L65). In the code snippet you pasted, the player will never be able to make progress because the individual allocation size is equal to the extractor sample source's requested buffer size.

**Comment by andrewlewis** [comment]
The actual cause of the player getting stuck is that the player can't buffer enough data to transition from buffering to ready, because the ExtractorSampleSource requested buffer size is too small.

In case it is of interest, here is what I think is happening in detail: during buffering the (paused) AudioTrack buffer fills with PCM data, and then no more decoded output is handled. Therefore, the decoder can't handle more input, which means that no samples are read from the ExtractorSampleSource, which in turn means that allocated size does not drop below the requested buffer size passed to ExtractorSampleSource. That stops the source buffering any more data, and so the buffered position never exceeds the minimum required buffer size to transition to ready.

The buffer size used in ExtractorRendererBuilder is chosen to be comfortably large enough to let the player keep making progress, though you can probably use a smaller value for audio-only playback. See also #680.

**Comment by SvenCarstensen** [comment]
Hi andrewlewis,

thanks for your help. 
Now it works like a charm!

**Comment by jonas-app** [comment]
Hey guys,
I am currently trying to implement ExoPlayer instead of the MediaPlayer.
The use case would be the same: streaming radio (mp3 [or m3u if that is working]).
@SvenCarstensen can you please provide me a sample which streams mp3 correctly?
I tried to figure it out myself but the link to the ExtractorRenderBuilder is broken.
I am not able to put the settings from the actual example code of the ExtractorRenderBuilder class together with my streaming use case.
Thanks in advance.

**Comment by andrewlewis** [comment]
Here is the updated link: https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java#L65

**Comment by jonas-app** [comment]
Thanks @andrewlewis,
I ended up using the FFmpegMediaPlayer library instead.

**Comment by sanotronics** [comment]
Hi!

I am trying to implement a custom buffer size, and I get that ExtractorSampleSource is a non defined class.

I am using v2.0.4
Is this deprecated in v2?

I also wouldn't know how to adapt the code I am using to use the allocator, since I am using the factories.

My code is as follows, and this works:

```
private void initMediaPlayer() {
        // Measures bandwidth during playback. Can be null if not required.
        defBandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.
        dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "Canalis"), defBandwidthMeter);
        // Produces Extractor instances for parsing the media data.
        extractorsFactory = new DefaultExtractorsFactory();

        // This is the MediaSource representing the media to be played.
        audioSource = new ExtractorMediaSource(Uri.parse(audioURL),
                dataSourceFactory, extractorsFactory, null, null);

        // Prepare the player with the source.
        exoPlayer.prepare(audioSource);
        exoPlayer.setPlayWhenReady(true);
        playerState = PlaybackStatus.PLAYING;
    }
```

could you please help to figure out how to adapt this to use a user-selectable buffer size?

**Comment by sanotronics** [comment]
I did this on the LoadControl declaration:

```
// 2. Create a default LoadControl
LoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(true, BUFFER_SEGMENT_SIZE));
```

I am using the player to play a stream of audio over TCP. Am I wrong to assume that reducing the buffer size, should reduce latency?

I am trying with different buffer sizes but I don't appreciate the difference.

**Comment by andrewlewis** [comment]
ExtractorMediaSource replaces ExtractorSampleSource in v2. As an aside, you might also find the new SimpleExoPlayer class useful for simplifying building the player.

It sounds like you want to control how much media the player buffers before it starts playback. Take a look at [this constructor in DefaultLoadControl](https://github.com/google/ExoPlayer/blob/69af389/library/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L98), and in particular the `bufferForPlaybackMs` parameter. Passing a lower value here should make the player start sooner, but note that there is a tradeoff between startup time and resiliency to transient network slowness.

**Comment by sanotronics** [comment]
Awesome!

That constructor is what I needed to see.

It worked perfectly, thanks a lot @andrewlewis!!

**Comment by sanotronics** [comment]
Another question arises from this. 
How do I reload the LoadControl into the player, given that the user selected in the prefs a different buffer size?
Or, how do I change the bufferForPlaybackMs parameter of the LoadControl I created?
