### ISSUE TITLE
ASS/SSA subtitle track

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#1232]
I'm trying to implement parsing of ASS/SSA subtitles and know specifications of this format and how to parse them... I created new SubtitleParser, but to "canParse" function come only audio and video mimetypes, not for subtitles. How can I get this tracks to render?

**Comment by marcbaechinger** [comment]
Vor Dash and SmoothStreaming TextRenderers are setup in the [DashRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/DashRendererBuilder.java) or [SmoothStreamingRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/SmoothStreamingRendererBuilder.java). 

These are using a TextTrackRenderer [which have SubtitleParsers for various formats registered](https://github.com/google/ExoPlayer/blob/267a870509bb85e2cff839ea162ae5b7c85933aa/library/src/main/java/com/google/android/exoplayer/text/TextTrackRenderer.java) class. So For DASH/SS you need to register your parser there.

For HLS WebVTT and EIA608 is setup in the [HlsRendereBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java)

**Comment by ojw28** [comment]
It sounds like the parser is being registered correctly, since its `canParse` method is being invoked. What you're missing is that whatever extractor(s) you're using also need to support the format. For example, if you're playing MP4s then you'll need to modify `AtomParsers` to create an appropriate format for the track, probably adding an additional `else if` [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java#L536).

Note that if you do this, we'd probably be interested in accepting a pull request if you're able to send one.

**Comment by don11995** [comment]
Most of test videos are MKV.

**Comment by ojw28** [comment]
You will need to update `WebmExtractor` in that case. It's probably pretty trivial to do so; you'll need an extra case in the switch statement in `initializeOutput`, and an additional entry in `isCodecSupported`.

**Comment by ojw28** [comment]
Did you manage to get this working?

**Comment by don11995** [comment]
Now I'm working on ffmpeg player, when I finish it, I'll try to implement this in Exo player.

**Comment by ojw28** [comment]
Ok, thanks for the update! Closing for now.
