### ISSUE TITLE
ChunkSampleSource code question

### ISSUE THREAD

**Issue by DyneInfo** [google/ExoPlayer#1280]
a) What does downstreamPositionUs hold in general ? 
b) Why is the return value downstreamPositionUs when the parsed value matches long min

   return largestParsedTimestampUs == Long.MIN_VALUE ? downstreamPositionUs
          : largestParsedTimestampUs;

https://gist.github.com/DyneInfo/90ffd5290e38cdc04863

**Comment by ojw28** [comment]
(a) This is easy to answer just by looking at the code? It's assigned in four methods. In each place it's assigned the value of a method input argument. In all cases the method input arguments are documented in the Javadoc. From this information, you can conclude that downstreamPositionUs is the current playback position of the player.

(b) getLargestParsedTimestampUs is documented in the Javadoc to return Long.MIN_VALUE in the case that a sample has yet to be received. In other words, there are no samples currently buffered. In such cases it makes sense to return a buffered position equal to the current position, since it would give a buffer duration of (buffered position - current position) = 0.
