### ISSUE TITLE
[QUESTION] Purpose of appending ".secure" to codecName in MediaCodecUtil.java

### ISSUE THREAD

**Issue by kidmiracleman** [google/ExoPlayer#1318]
Hi,

I am currently investigating playback issues with DRM (Widevine) protected content on the Samsung Galaxy Tab 3 (WIFI) device.

I noticed that on devices running older versions of Android  - the getMediaCodecInfo method will append a ".secure" to any codec mimeType that is indicated to support secure playback - (isSecurePlaybackSupported).

If I 'short circuit' this logic for this specific device (resulting in no suffix) - I can playback DRM protected content on this device.  However, I have a few questions around this:

1.)What is the purpose of appending the ".secure" prefix in the first place?  I notice these older devices do not return an explicit secure codec...

2.)What are the consequences of not appending this suffix or indeed trying to 'downgrade' the codec to a 'non-secure' variant on ANY device/OS type  - Are we by-passing the secure video path implementation required for Widevine Security Level 1  for instance ?

**Comment by ojw28** [comment]
Good question. In older versions of Android secure decoders were not explicitly listed, and it was by convention that secure decoders were obtained by taking the regular decoder name and appending ".secure".

In MediaCodecUtil we assume the existence of a secure H264 decoder (only) on these older versions of Android. Note however that MediaCodecTrackRenderer will only attempt to instantiate a secure decoder if the MediaDrm implementation states that it requires one. If this is true, it really should imply that a secure H264 decoder really does exist, because it doesn't make any sense for a device to ship with a MediaDrm implementation that requires a secure decoder if no such decoder exists. Note that H264 was the only codec for which secure decoders were being supported at this point.

My hunch would be that on the affected device the MediaDrm is incorrectly claiming that it requires a secure decoder, when in reality it doesn't. If that's the case then the fix should be to override that, so that no attempt is ever made to instantiate the secure decoder. This should be pretty easy to do, if that's the issue.

To help debug the issue, could you please modify StreamingDrmSessionManager.requiresSecureDecoderComponent to include the following logging:

```
Log.e("DRM", "fingerprint=" + android.os.Build.FINGERPRINT);
Log.e("DRM", 
    "requiresSecureDecoder=" + mediaCrypto.requiresSecureDecoderComponent(mimeType)
    + ", securityLevel=" + getPropertyString("securityLevel")
    + ", mimeType=" + mimeType);
```

Try playing some DRM protected content, and reply to this thread with the logging that gets output.

**Comment by ojw28** [comment]
One other question - I assume you're not doing anything to deliberately lower the security level of the MediaDrm implementation (if you don't know what this means, the answer is no :)).

**Comment by ojw28** [comment]
To answer your second question - You shouldn't do that. There are a number of scenarios where that will cause playbacks to fail unnecessarily. This is true in all cases where the keys require a secure path. It may also be true in cases where they don't, since device manufacturers are not required to support this combination/mode and there are no device certification tests to enforce behavior in this case. Please follow up as per above, and we can figure out a better solution for you :).

**Comment by kidmiracleman** [comment]
Hi,

Thanks for the quick and detailed reply - you have supplied some really useful information.

I now understand that I probably shouldn't try to subvert the DRM/secure codec implementation unless I can prove a OEM specific issue requires that.

I will get the information you need in the next few days (weekends getting in the way of work!).

One point though,  It's my understanding that you are trying to see if there is an incompatibility between the security level reported by the device and the result of the requiresSecureDecoderComponent() method?  I can say that the security level reported is L1 (since I can see that information in my Widevine license proxy). However,  this device requires field provisioning (no factory set root of trust) therefore I am surprised that it is not L3  - maybe this is an indicator?  (or else my understanding is flawed)

**Comment by kidmiracleman** [comment]
Hi,

I have debugged further, I currently believe that this could be related to device and content compatibility.
The Youtube WV DASH content works perfectly on this device, however the content I have does not.  The difference is that the YouTube WV DASH content is:

a.)Not encrypted for the first few fragments
b.) Uses some other type of clear lead?  e.g. specific NALs left in the clear??

The content I have mainly tried is 100% encrypted.  I have also tried leaving the first 2 fragments in the clear when I package some new content and can still see the issue (which is why I suspect the YouTube content leaves specific intra-coded frames in the clear...)

Unfortunately I cannot currently expose a working Widevine license proxy to you - however I can provide the content and the encryption key if that would help?

**Comment by kidmiracleman** [comment]
Hi,

The issue is specific to content encrypted as per CENC version  ISO/IEC DIS 23001-7 3rd Edition
This version specifies partially encrypted NAL units which Intel decoders won't play and some Qualcomm  decoders have issues with when changing from clear to encrypted streams.

The demo content used for ExoPlayer is all encrypted as per an older version on the spec which specifies that only the first 5 bytes of the NAL is encrypted.  This content seems to work on most devices I have tried thus far.

You can close this issue now.   Perhaps you should consider adding Widevine/CENC ISO/IEC DIS 23001-7 3rd Edition content you your list of test vectors?  I'm sure others will also be using this player with similar content as more vendors adopt the latest spec.

I am onsite at Widevine next week so I will also ask them  about this.

Thanks for your help!

**Comment by ojw28** [comment]
It appears that version of the spec was only released a month ago. It doesn't seem too surprising that software that shipped before the standard doesn't fully support it! Please follow up with Widevine directly regarding test vectors. They also have their own set of tests, so if this is something that's expected to be supported they should have tests covering this case.
