### ISSUE TITLE
Unable to play HLS but didn't get an error callback

### ISSUE THREAD

**Issue by liutingdu** [google/ExoPlayer#1356]
My app uses ExoPlayer to play HLS streams, and the streams are transcoded from IP camera using ```nginx-rtmp```.

It works for most of the cameras but is having problem with one of the URLs. It can be reproduced with the demo app, tested on Android 6.0 on Nexus 5, with ExoPlayer 1.5.5. I've sent the link by Email with full bug report attatched.

The problem is, I was expecting the get an error callback in ```DemoPlayer.Listener.onError()``` so that I can handle the error situation in my code, but didn't.

Any idea why it's not captured as an error or is there any other workaround to be notified when the video fails?

Here is the logcat:
```
03-10 12:15:11.633 18361 18361 I ExoPlayerImpl: Init 1.5.5
03-10 12:15:11.635 18361 18361 D EventLogger: start [0]
03-10 12:15:11.635 18361 18361 D EventLogger: state [0.00, false, P]
03-10 12:15:11.636 18361 18361 D EventLogger: state [0.00, true, P]
03-10 12:15:11.695   781   800 I ActivityManager: Displayed com.google.android.exoplayer.demo/.PlayerActivity: +101ms
03-10 12:15:11.716 18361 18405 D OpenGLRenderer: endAllStagingAnimators on 0xa06ff900 (ExpandableListView) with handle 0xab465a30
03-10 12:15:11.782  1266  1266 I Keyboard.Facilitator: onFinishInput()
03-10 12:15:11.787   781   790 I art     : Background partial concurrent mark sweep GC freed 52277(3MB) AllocSpace objects, 7(140KB) LOS objects, 31% free, 35MB/51MB, paused 73.594ms total 221.884ms
03-10 12:15:12.345   196   196 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-10 12:15:14.810   203   818 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
03-10 12:15:14.811   203   818 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
```

**Comment by AquilesCanta** [comment]
I will give it a look!

**Comment by AquilesCanta** [comment]
The issue seems to be that the transport stream does not include any video ts packets(even though video is declared in the PMT). This is a complicated situation, because the transport stream is not valid. It would be ok for us to fail gracefully when you meet an ExoPlayer limitation, but this is not the case. If we add checks of every possible invalid input, we will end up with a very nice multimedia analyzer, but a poor player. If I am wrong, let me know. Otherwise, please check the validity of the input, whenever possible.

**Comment by AquilesCanta** [comment]
One last thing, the error report in this case is not as simple as one would expect. The problem is that the player is not failing. The player is just waiting for the video packets to arrive. At any point you have to ask whether the transport stream is invalid or the awaited packets are about to arrive.

**Comment by liutingdu** [comment]
@AquilesCanta Thanks a lot for spending time on this, it's very helpful. I'll double check the input :)
