### ISSUE TITLE
Mpeg-Dash Widevine encrypted live stream crashes after a while

### ISSUE THREAD

**Issue by hyurtseven81** [google/ExoPlayer#1369]
After watching 5 minutes to 60 minutes encrypted live stream, player crashes with java.lang.IndexOutOfBoundsException error or java.util.HashMap com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.representationHolders error.

java.util.HashMap com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.representationHolders error occures often but IndexOutOfBoundsException occurs less than representationHolders error.

Tried player versions: 1.5.4
It happens almost all kind of devices

I'm attaching logcat logs as txt to the issue and i'm sending content url and proxy url via email

[IndexOutOfBoundsException.txt](https://github.com/google/ExoPlayer/files/171591/IndexOutOfBoundsException.txt)
[NullObjectReference.txt](https://github.com/google/ExoPlayer/files/171592/NullObjectReference.txt)

**Comment by ojw28** [comment]
Sorry this didn't get looked at.

It appears the license proxy returns a status code 400 now, so we're unable to investigate at this point with the information provided. Please provide test content that still works if you wish for us to investigate further. Please also test using a more recent version of ExoPlayer, since if it's a player issue it's relatively likely to have been fixed. Thanks!

**Comment by ojw28** [comment]
Closing due to lack of information.
