### ISSUE TITLE
DASH + Widevine get the default_KID present on the manifest

### ISSUE THREAD

**Issue by jrocharodrigues** [google/ExoPlayer#1376]
Hi we're using ExoPlayer to play MPEG-DASH content protected with Widevine DRM.

Everything is working great, but now as a new requisite we have to send the default_KID that is present on the content manifest to the Widevine License Server.

Is there a away to get this value when executeKeyRequest is called?

Here is the part of one of the manifesst:
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns:cenc="urn:mpeg:cenc:2013"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="static"
     publishTime="2016-03-15T16:25:30Z" 
     mediaPresentationDuration="PT1H54M34.112S"
     minBufferTime="PT1.5S">
<ProgramInformation>
    <Title>media/Vods/LM-2921648/Main/2921648_SD_H.smil</Title>
</ProgramInformation>
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" mimeType="video/mp4" maxWidth="720" maxHeight="400" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="701a9f48-5fc4-467f-b4a9-d417d97b5be1"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" value="Widevine">
            <cenc:pssh>AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISEHAan0hfxEZ/tKnUF9l7W+E=</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate presentationTimeOffset="0" timescale="90000" media="chunk_ctvideo_cfm4s_rid$RepresentationID$_cs$Time$_mpd.m4s" initialization="chunk_ctvideo_cfm4s_rid$RepresentationID$_cinit_mpd.m4s">
            <SegmentTimeline>
                <S t="0" d="900000"/>
                <S d="900000"/>
                <S d="900000"/>
...
```

Thanks in advance.

**Comment by ojw28** [comment]
Given you're doing something that no one else has asked for, the first question should be: Why do you need to do this? It feels like it shouldn't be necessary.

**Comment by jrocharodrigues** [comment]
We use the default_KID to identify the content on the license server when requesting the WIDEVINE license. 
Currently to achieve this we are extracting this value from <cenc:pssh>, but having access to the default_KID would be a cleaner solution.

But i guess it really is something very specific to our use case since no one else has asked for it, as you said.

Thanks

**Comment by ojw28** [comment]
Extracting it from the pssh seems like a reasonable solution to me (at least from the client's perspective).

I am aware of other applications sending up various content ids in their license requests, now you mention the use case. In such cases the content id is typically known in advance of fetching the manifest (because the content id is typically needed to construct the manifest request). Hence the common way to do this is simply to pass the content ids that need to be sent to the constructor of your `MediaDrmCallback` implementation, before even fetching the manifest. The `MediaDrmCallback` can then include the ids in the request when `executeKeyRequest` is invoked.

Not sure if the above works for you, but you could explore that path, or stick with the current solution that you have. Closing in any case, since we don't have plans to pipe this parameter directly into `executeKeyRequest`.

**Comment by jpardogo** [comment]
Vualto, my DRM provider need the default_kid for 'executeKeyRequest' , my only way to get this value at the moment is extracting it from the manifest xml before I try to start playing the stream, as it is dynamic based on the content id. 
There should be a easier way to access the KID as I think it is pretty common use case.

**Comment by jrocharodrigues** [comment]
@ojw28 As i mentioned in https://github.com/google/ExoPlayer/issues/1376#issuecomment-220926018 , currently i'm extracting the default_KID from the manifest to send to the Widevine License Server.

I was doing it on the onLoadStarted callback is called for dataType == C.DATA_TYPE_MEDIA_INITIALIZATION && trackType == C.TRACK_TYPE_VIDEO, but i detected some cases when the executeKeyRequest, of the WidevineMediaDrmCallback, is called before the onLoadStarted.

Is there any callback that is guaranteed to be called before the executeKeyRequest, where i can access trackFormat.drmInitData for the video track?

Is there any place where i can see a diagram of the exoplayer playback cycle? 

Thanks in advance
BRS

**Comment by ojw28** [comment]
I still think the setup being described here is pretty unnecessary. There definitely exist cleaner solutions to this problem. I thought the CENC PSSH data is sent up as part of the license request. If the KID is contained within the PSSH data as implied above, why can't the server just parse and extract it from what's already being sent?

The above aside, it's a little unclear how your current implementation works. What are you actually doing in onLoadStarted currently? Specifically, where are you getting the manifest from? If you're getting it from `ExoPlayer.getCurrentManifest` then you should probably use the `ExoPlayer.onTimelineChanged` callback instead, since this is the earliest point at which the manifest can be retrieved from that method.

I don't think we want to make hard guarantees about the ordering, however, so this is still risky. The only guaranteed way to get data from the manifest before the key request is made would be to extend `DashManifestParser` and retrieve what you need during the actual parsing. You can inject your extended/custom parser into `DashMediaSource` constructors.

**Comment by jrocharodrigues** [comment]
Hi, thanks for the answer.
I'll try to explain a little more in the detail the flow i currently have to acquire the Widevine License:
1st: Extract the default_KID from the manifest (The part i currently do on the onLoadedStarted)
2nd: Make a request for an authentication token using the default_KID and other data 
3rd: Make the request to the Widevine License Server, using the token returned on the 2nd step + default_KID + other data.
The 2nd and 3rd step are both made when executeKeyRequest is called on the DrmCallback.

I agree when you see that the use of the default_KID is unnecessary, at least in the 3rd step, but at least for now, i can't change that. :(

What i'm currently doing on the onLoadStarted, was to extract the defaultKid from trackFormat.drmInitData, when it is called with dataType == C.DATA_TYPE_MEDIA_INITIALIZATION && trackType == C.TRACK_TYPE_VIDEO.

Meanwhile i've been trying some alternatives, and one that i tried and seems to work, was to extend the class DefaultDrmSessionManager, override the acquireSession method, and extract the key there, from drmInitData, before calling super.

Which you think is better, override DashManifestParser as you suggested, or override DefaultDrmSessionManager?

Thanks again

**Comment by ojw28** [comment]
I don't really understand what step (2) is for, either. What does it do that cannot just be rolled in to step (3)? Are you asking whoever is providing the serving side to make things a little less convoluted?

Your approach of extending `DefaultDrmSessionManager` sounds like the simpler and more logical of the two options. Although thinking about this some more, can't you just extract the key directly in `executeKeyRequest`? I think the data in the `KeyRequest` is the pssh box (or just the data within the pssh box on earlier versions of Android, due to [this workaround](https://github.com/google/ExoPlayer/blob/r2.4.0/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L336)). So I think you could do this in `executeKeyRequest`:

```
byte[] requestData = request.getData();
if (Util.SDK_INT >= 21) {
  requestData = PsshAtomUtil.parseSchemeSpecificData(schemeInitData, C.WIDEVINE_UUID);
}
// requestData is now the data within the pssh box; extract the key from it
```

**Comment by jrocharodrigues** [comment]
Hi @ojw28, thanks for the answer,
The step two is basically an an authentication request. I guess it could be rolled in to step 3, i've already exposed that to the team responsible for that, but as i said there's really not much i can do about it.

My first approach was in fact trying to extract the default_KID from the data in the KeyRequest as you suggest. 
The problem i found in that approach is that the position of default_KID, varies depending on the Android Version. 
For example, for Android 6 (tried on Nexus 9 and Nexus 5), the default_KID is starts on byte 311 (counting from the end) but for Android 4.4.4 (tried on Samsung S3) starts on byte 323 (counting from the end).
In the drmInitData the default_KID is always in the last 16 bytes, at least from what i observed.

Is there any rule for the position of the default_KID on the requestData? Or any helper method to help me extract it?


Thanks

**Comment by jrocharodrigues** [comment]
I've been fiddling around, and i'm noticing a pattern on the data that could help extract the default_KID.
On the request data i "always see the following pattern.
0A380A121210 <default_kid_bytes> 10011A20

Are this any kind of separators? can i rely on them to find the position of the default_kid or is it just a coincidence? 

Thanks in advance

**Comment by ojw28** [comment]
Ah, yes, ignore what I wrote in my previous response. The `KeyRequest` is actually generated by the platform (by calling `mediaDrm.getKeyRequest`). It's possible that different OS versions are putting different pieces of data in the request, and I'm not sure it's documented anywhere. Stick to your approach of extending `DefaultDrmSessionManager`, if that's working for you.

**Comment by jpardogo** [comment]
I ended up injecting my extended/custom parser into DashMediaSource constructors and works great. Thanks

**Comment by jrocharodrigues** [comment]
Ok @ojw28, i'll do that.

Thanks for your help.

BRs
