### ISSUE TITLE
Setting headers for streaming hls

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#1377]
How can i set headers with exoplayer and stream hls video from url?

**Comment by andrewlewis** [comment]
If the question is how to set HTTP headers: [DefaultHttpDataSource.setRequestProperty](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/DefaultHttpDataSource.java#L162) can be used to add headers to requests made by the data source. [HlsRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java) in the demo app shows how to set up renderers for playing an HLS stream at a given URL. You can use a DefaultHttpDataSource instead of a DefaultUriDataSource.

**Comment by AlirezaGhanbarinia** [comment]
Actually I need to send a token header, for playing local m3u8 files. I’ve already downloaded the encrypted m3u8 file and all segments, now I need to set token as a header while playing for sending to server at the begining of video play. When I use DefaultHttpDataSource.setRequestProperty for setting the header, and try to play local stored files, Exo can not play the video.

**Comment by andrewlewis** [comment]
Please could you explain in detail exactly what you are trying to do? Your first message did not mention encryption; what scheme are you trying to use? Can you clarify why you are making a request to the server if everything is downloaded?

**Comment by AlirezaGhanbarinia** [comment]
Just ask server to confirm user as a valid one.

**Comment by andrewlewis** [comment]
It's still unclear what you are trying to do. What player component is making the request you need to add headers to? What failure do you see when trying to play the video? Are you using DRM?

**Comment by AlirezaGhanbarinia** [comment]
The player server video is related to ourselves. No error is being displayed and also we do not use DRM.

**Comment by AquilesCanta** [comment]
Hi @AlirezaGhanbarinia, if you could please provide a description of what your problem is, that would be really helpful. Please be specific, provide as much descriptive information as you can. So far, it seems that exoplayer does not have anything to do with this scenario.

**Comment by ojw28** [comment]
Agreed this issue is very unclear. There's no description of which network request this issue is talking about, where it's being made from in code, what it's for or what data needs to be sent in it. Please fully describe what you're trying to do if you wish us to investigate further.
