### ISSUE TITLE
Playing the same song in demo app

### ISSUE THREAD

**Issue by sujitkjha** [google/ExoPlayer#1379]
I am new in android and I have downloaded the exoplayer demo app. I have 5 songs in the list view, 4 songs from server and one from sdcard.

when I start playing first time by clicking the list item, player start playing the song, when I press back button and play another song the same previous song get played.

I have tried to search lot no solution yet, Please help.

**Comment by AquilesCanta** [comment]
Unfortunately, this is not ExoPlayer related: If the same song is being played, it is because the same media URI is being used for playback. This means there is an error in the application's code. This error has not been reproduced in the DemoApp previously, so I find it unlikely that the error comes from the DemoApp out of the box.

 If I were you, I would take a look at any modifications you may have introduced in the DemoApp to find what the mistake is. If you just changed the elements in the DemoApp for your songs (without introducing any new behaviours) make sure you haven't added the same URI twice. If you still have a problem, let me know!
