### ISSUE TITLE
Live channel example

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1395]
Dear ExoPlayer devs,
Our company use ExoPlayer for a wild in order to switch our library to use it. It works fine, however there are some issues that are critical for the production version, such that BehindLiveWindowException and freezing in the buffering state. Both of them described already (more / less) here via different use cases.
BehindLiveWindowException happening quite often and in the beginning of playback, which is very strange. Buffering freezing happening after a long time playing and it is causing by AudioTrack (this issue reported already here by other devs).
What we did is we compare performance of our Live stream with the web player that is provided by Google as well, it is Shaka Player (https://github.com/google/shaka-player), and there are no issues at all, hours streaming without stopping, buffering for a wild, etc ... which is minimizing chances that something wrong with content itself.
Counting all written above, I would like to ask, is there a Live channel available to test from you guys? Like you provided a lot of examples for the VideOnDemand content.
It can be any channel, not necessary a real one, could be stream from web cam, etc ... 
I think a lot of devs need it as well, as ExoPlayer is using not only for VOD content.

Thanks in advance.

**Comment by ojw28** [comment]
We have quite a few live test streams available to us internally, including test streams provided by a range of large media streaming providers and services. We're not able to share such streams because we don't own them and they're provided to us for testing purposes only, but we do not see these issues with the test streams we have, and neither do the partners who provide them.

I'm unclear what you're after here. It's not up to us to provide streams that prove ExoPlayer functions correctly. If you have streams that prove ExoPlayer does *not* function correctly, then it's up to you to provide them to us in the form of clear issue reports, providing the information requested in our issue template, so that we can take a look.

Note that BehindLiveWindowException specifically has been documented quite a lot on this issue tracker. There's currently no evidence to suggest this occurs in any case other than when the provider does not provide a sufficiently large live window for mobile playback (in other words, the chunks exposed in the HLS playlists do not cover a sufficient duration of time). If you have evidence of BehindLiveWindowException occurring for streams where the window is reasonably large, please file an issue as described above.

**Comment by ojw28** [comment]
Note - It's also unclear whether you're talking about HLS, DASH or SmoothStreaming. The failure mode for BehindLiveWindowException is similar in all cases, although in DASH it can be caused by incorrect server/device time synchronization (you would have to provide a test stream exhibiting the issue for us to tell you whether this is the issue).

**Comment by ChernyshovYuriy** [comment]
Hi,
Thanks for the response!
Sorry for my unclearness, the content is MPEGDASH with Widevine protected.
Our content is in test mode still, it is not ready for the production. Both ExoPlayer and MPEGDASH / Widevine are new for us, thus we have a lot of questions :-)
The main concern are BehindLiveWindowException and freezing in buffering state.
Also, Shako player plays well, personally assume that it handles discontinuity in different way then ExoPlayer does. The fact that Shako plays well is main argument of our server team that issue is more likely on ExoPlayer side rather then on server side. But I am personally can not state so.
Another point is that if ExoPlayer has only one renderer enabled (Audio or Video) it consumes content for hours without any issue, but as soon as there are both enabled BehindLiveWindowException or buffering state occur.
I spoke already with the person who is responsible for client - customer communication that we need to provide channel in order for you guys to validate but still have no answer (for the same reason as you did, we do not own these channels).
Anywhere, thanks for the response.

**Comment by ChernyshovYuriy** [comment]
I have some good news from my side.
I investigated content and all callbacks from ExoPlayer more detailed and found that there is an issue with Text data chunks (the ones that application/ttml+xml). They failing constantly on the stream and this was processed by **ChunkSampleSource.java** and it's method:
`void onLoadError(Loadable loadable, IOException e)`
At one point in time, queue with chunk contains only 1 item and there is no attempts to load new ones.
This was a reason for freezing in buffering state.
By disabling text rendering I am able to stream for hours without any problem :-)
