### ISSUE TITLE
ChunkSampleSource and lastPerformedBufferOperation delta

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1396]
Dear ExoPlayer devs,
In the ChunkSampleSource.java there is `lastPerformedBufferOperation` member field. It is using when calculating whether or not it is necessary to perform `doChunkOperation`.
The question is, how you calculate 2000 ms delta? Why it is not 1999 or 2999 ms? Could it be related to BehindLiveWindowException or stacking in buffering state?

Thanks in advance.

**Comment by ChernyshovYuriy** [comment]
I am talking about:
`(now - lastPerformedBufferOperation > 2000)`

**Comment by ojw28** [comment]
The logic to which you refer allows re-evaluation of a previous format selection. This gives the player flexibility to change the evaluation should conditions have drastically changed since it was originally made. The constant controls the rate at which such re-evaluations are allowed to occur. It's value was chosen fairly arbitrarily, however it's not particularly important and should have no impact on issues relating to BehindLiveWindowException or the player getting stuck in a buffering state.
