### ISSUE TITLE
Unable to play 30 seconds local file 

### ISSUE THREAD

**Issue by blueslabs** [google/ExoPlayer#1405]
Unable to play the local file more than 30 seconds. I am using ver 1.5.6. And using ExtractorSampleSource. The parameter requestedBufferSize is 64x1024x32. If I set the requestedBufferSize to 64x1024x256, or some value greater than the video file size, it will work. But this will use a lot of java heap. I can reproduce this with the demo app. And enclosed is the mp4 file having the problem.

More info: I don't get any error. The player state is at STATE_BUFFERING forever. It seems the code hangs in DefaultAllocator.blockWhileTotalBytesAllocatedExceeds().

[flower.mp4.zip](https://github.com/google/ExoPlayer/files/197130/flower.mp4.zip)

**Comment by andrewlewis** [comment]
In the attached file there seems to be more than 10 MB of video sample data before the first audio sample. I think the player is probably loading video samples until it has filled the allocation, but at that point not enough audio has been loaded to let the player transition to the READY state. No more samples are loaded because the allocation is full, so the player is stuck.

For reliable playback you need to produce a file where the samples are better interleaved. You should be able to control this at the encoder. Or you can re-interleave samples in an existing file to make it suitable for playback (for example, you could run `avconv -i flower.mp4 -codec copy flower-interleaved.mp4`).

**Comment by ojw28** [comment]
This is basically exactly the same as #1386 (going from the naming of the file, I'm guessing it's the exact same media file too)?

**Comment by blueslabs** [comment]
Thanks @andrewlewis! I am actually having the same feeling. Thanks for confirming. I am looking into getTrackIndexOfEarliestCurrentSample() now in Mp4Extractor. I will try to load from the other track if the diff of index the tracks are off too much. 

I have no control of the file creation part now. And the file can be played with Android system media player.

**Comment by blueslabs** [comment]
@ojw28, OMG someone named the file same as me! No, it was not me.. guess people loves flowers. :-)

**Comment by blueslabs** [comment]
@andrewlewis, a quick question. What tool do you use to analyze the video file? Specially for Mac? Thanks!

**Comment by andrewlewis** [comment]
@bluelabs I sometimes use avprobe in libav, which appears to be available in Homebrew (`brew install libav`).

**Comment by cvoell-franklyinc** [comment]
@blueslabs I have the same problem as you. Did it work for you to switch the track you are loading from in MP4Extractor when the sampleIndex of the tracks grow too far apart? Did you have to increase buffer size also or no? Thanks!
