### ISSUE TITLE
CPU load optimizations options for HLS

### ISSUE THREAD

**Issue by dbedev** [google/ExoPlayer#1412]
This is not really a bug in the sense that the HLS functionality does not work, but rather options for optimization on the Exoplayer code base.  This based on the analysis of the 1.5.6 code.

So far we have encountered the worst performance to be on HLS aes encrypted content. On our android 4.3, armv7 @ 4x1ghz on gbit eth we only achieve around maximum 5mbit throughput in this mode ,on HLS without aes we reach around 24mbit throughput. 

A:
At base of the higher HLS CPU load seems to be the design choice to do extraction during loading rather then doing extraction during playback. Guess this will also be related to the #1227 question. As far as we could see this would be quite a big change, so we did not investigate how to improve on this. Hopefully you can find an easier trick.

Optimally extraction would be done from memory on a loaded buffer, the raw buffer itself is most optimally loaded with data intervals suiting the actual data source.

Making things worse for HLS is the fact that the TsExtractor does it's input stream requests in 188byte blocks. 

Probably other modes of streaming could also benefit from optimizing this.

B1: 
When using the HLS  AES-128 feature of Exoplayer, Another big performance issue is with the Aea128DataSource.java implementation itself on android 4.x platforms.

The Aea128DataSource uses a cipher is used on Android's CipherInputStream (Aes).  Unfortunately the CipherInputStream as provided by the Android 4.x OS has a terrible throughput performance as it internally does the decryption in chuncks of only 20 bytes towards it's inputstream. It would be advisable to add a better performing ExoPlayerCipherInputStream filter customized to handling the streaming data instead (basically doing much more data in one go):

One can for instance derive it from the later platform version. 
Some examples:
http://androidxref.com/6.0.1_r10/xref/libcore/luni/src/main/java/javax/crypto/CipherInputStream.java
or
https://github.com/facebook/conceal/blob/master/java/com/facebook/crypto/streams/BetterCipherInputStream.java  

B2:
A smaller performance thing seems to be coming from the cipher itself. The Aes128DataSource requests "AES/CBC/PKCS7Padding", which means the app will get the bouncy castle java crypto implementation on android 4.x variants , on later OS versions this is translated to "AES/CBC/PKCS5Padding" by the android OS itself which then results in the faster openssl provider serving the decryption. As such we guess would be more optimal to just request "AES/CBC/PKCS5Padding" in the Aes128DataSource directly.

see: https://android.googlesource.com/platform/external/conscrypt/+/0d1f9b857696946e23046956f8f3484acd9de84b%5E!/

**Comment by ojw28** [comment]
In using HLS (and as a result MPEG-TS) you've made a decision to use a container format that fragments media samples (unnecessarily) into hundreds (sometimes thousands) of pieces, that the client needs to merge back together. You've also chosen to use a container format that includes insufficient metadata, meaning the client has to dig around in the raw media stream to get at what it needs. MPEG-TS is fundamentally inefficiently and sub-optimal for delivery of media to mobile devices for these reasons, particularly at high bitrates. 

ou should think carefully about whether you want to provide an optimal experience (by switching to DASH or SmoothStreaming and as a result using a sensible container format), or just one that's "less bad, but still quite bad", which is what optimization of HLS playbacks in ExoPlayer would achieve.

To address your specific points:

- We have no plans to change where extraction happens. We used to do extraction much later than we do now, and ironically HLS was one of the primary drivers toward us doing the extraction earlier. We frequently see HLS streams where the audio and video samples are poorly interleaved in the media chunks, which made it necessary to perform extraction further ahead in order to play corresponding audio and video samples at the same time. Note that the total amount of work done is the same either way; it's just that doing it earlier doesn't distribute the computation as evenly over time. All of this aside, we just wont be making large structural changes to handle what is essentially a legacy, albeit still widely used, format, particularly given we're seeing more and more large partners migrate to DASH (with excellent results).

- We would likely accept a pull request that optimizes AES decryption, but it's not something we're likely to spend time on ourselves in the near future. Note that any contributions must be accompanied by a CLA (meaning, for example, you can't just copy-paste code from something you've found elsewhere).

**Comment by ojw28** [comment]
Apple have announced that they'll be adding fragmented mp4 and common encryption support to HLS. This should make it possible to deliver HLS content in a far more suitable container format, and using content protection that Android supports efficiently. This move makes it less likely that we'll spend time on this issue, but we'll leave it open for now.

**Comment by ojw28** [comment]
We don't have any plans to optimize this in the near term, so I'm going to close this issue. Please see my other comments above.
