### ISSUE TITLE
[Question] How to invoke exoplayer

### ISSUE THREAD

**Issue by ShoubhikRaj** [google/ExoPlayer#1422]
I am only starting to understand the functioning of exoplayer so please point me the right direction if I have misunderstood anything.
I have two specific questions:
1. Can the exoplayer demo app play media files from local storage (i.e sdcard). If yes, then how to invoke it ?(I have built the app using eclipse and installed it in my phone but I can't understand how to make it play a file) If no, then how to play a media file locally using exoplayer ?
2. I have heard of an engine that runs beneath youtube app which decodes the ".exo" files during runtime. ( The ".exo" files are actually chunks that store the whole video.) Is this exoplayer related to that in any way ?

**Comment by andrewlewis** [comment]
1. Yes. The demo app uses [DefaultUriDataSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java), which delegates to a [FileDataSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/FileDataSource.java) when supplied with a `file://` URI (or a non-asset URI with an empty scheme). If you just want to try out the functionality, you could start by adding the path to the file you want to play to the [samples list](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java) in the demo app (making sure to pick the right type, for example Util.TYPE_OTHER for an MP4 file). Alternatively, you can start the demo player directly, using an intent: `adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d "file:///sdcard/file.mp4"`.
2. It may be related to ExoPlayer, because YouTube uses ExoPlayer for DASH playbacks. I'm not sure what information you are looking for, though. (And the way the YouTube app works specifically is probably off-topic for this issue tracker!)

**Comment by ShoubhikRaj** [comment]
Thank you for answering so quickly.
Let me elaborate the question about youtube. The youtube app when lays a video, it stores the video in the cache as several '.exo' files. Even when a video is saved for offline using the youtube app, it stores it as '.exo' chunks. Since, the ExoPlayer runs behind youtube, can ExoPlayer be used to play '.exo' files.

**Comment by andrewlewis** [comment]
That depends on the implementation details of the YouTube app. I suggest reading through issue #420 and its linked issues to find out more about using caching with ExoPlayer.
