### ISSUE TITLE
Authorization for HLS variants

### ISSUE THREAD

**Issue by igo88** [google/ExoPlayer#1423]
Hello everyone.

I can set an Authorization Header for the request to the HLS master playlist, using something like this:

  HlsPlaylistParser parser = new HlsPlaylistParser();
  HttpDataSource defaultHttpDataSource = new DefaultHttpDataSource(userAgent, null);
  defaultHttpDataSource.setRequestProperty("Authorization", "123456789");
  playlistFetcher = new ManifestFetcher<>(url, defaultHttpDataSource, parser);

The first request to the .m3u8 master goes with the Header, but the next requests...to the other .m3u8 or the key file just doesn´t go with the Header...is there a way to change that behaviour?

Thanks in advance,

Rodrigo

**Comment by Zo2m4bie** [comment]
@igo88 I had some workaround with header. In my case I had to change them on fly. So you can modify [this method](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/DefaultHttpDataSource.java#L384) . All connecting go through it

**Comment by AquilesCanta** [comment]
The issue is that the HttpDataSource you instance there is not the same you use to obtain the chunks. With that DataSource you just obtain the Manifest. You should do the same configuration in the DataSource's used for the streams. Perhaps having a look at HlsRendererBuilder can provide some insight.
