### ISSUE TITLE
.m3u8 plays only audio , no video is shown.

### ISSUE THREAD

**Issue by iRaam** [google/ExoPlayer#1448]
I am using the demo app to test a .m3u8 file. But it only plays audio. 

http://organizer.dvnor.no:1935/TestSmil/smil:10448_266.smil/playlist.m3u8  it only plays audio but when I tried below file, it plays nicely.

http://walterebert.com/playground/video/hls/sintel-trailer.m3u8

**Comment by AquilesCanta** [comment]
The issue is that the first playlist included does not contain ts files but rather aac (audio only files). There are two things I suggest you to try(particularly important is the second one):
1. Try not to list the audio-only playlist first. As a caveat, It is possible that if the player tries to adapt to that option, it will break.
2. And more importantly, see https://tools.ietf.org/html/draft-pantos-http-live-streaming-13. The CODECS attribute **should** be included in the tags, which means you should have a good reason not to include it. This way, exoplayer would handle the audio only playlist itself.
