### ISSUE TITLE
Support for different encryption keys for video and audio AdaptionSets

### ISSUE THREAD

**Issue by kidmiracleman** [google/ExoPlayer#1462]
Hi,

The latest security update from Widevine strongly advises that we need to use a distinct content encryption keys for video and audio tracks.

Furthermore, after discussing directly, it appears that the Chrome CDM will enforce this configuration as mandatory at some point.

I have tested such content against ExoPlayer 1.5.7 and it appears that the player will only currently generate 1 key request per streaming session, regardless of the fact that two different default keyIDs are specified for each AdaptionSet (in my case Audio and Video).

So my questions are 

1. Are my suppositions correct on this?
1. Would you consider adding support for this use-case as an enhancement.  If Chrome forces this, we (and others) could potentially have no choice but to generate content that is not compatible with ExoPlayer...

I will send a private mail with details on the content sample I am using to determine my findings.

**Comment by ojw28** [comment]
Use of distinct keys is not incompatible with having a single key request per session. What's supposed to happen is this:

1. Player extracts pssh from arbitrary stream.
1. Player makes single key request with pssh data.
1. License server responds with *all* of the keys that the user is entitled to for that content. So specifically, the response would include keys to play both the audio and video streams in this case.

The same approach is used today by many providers who use distinct keys for SD v.s. HD streams.

**Comment by ojw28** [comment]
Note also that alternative approaches involving separate key requests are less efficient (more network requests) and more likely to result in playback failure (more chances to fail).

**Comment by kidmiracleman** [comment]
Hi,

Thats the way key management seems to be done if you rely on Widevine cloud services to manage the encryption keys.   

However, what you are suggesting (in my opinion) goes some way to actually mandating how a Non-Google provided key management system must actually work.   In our case, we support multipleDRMs and we expect to get (and handle) requests for a specific KeyID, not just "give me all keys for a specific content instance".

Be aware that other DRMs (e.g. PlayReady) do not support the notion of the 'content_id' field as Widevine does

**Comment by kidmiracleman** [comment]
Note that the CENC spec only seems to define the KeyID as the signalling used to determine what encryption key to request/use  - it would be good that we can keep using a generic key management implementation, and not have to make Widevine specific alterations for this use-case

**Comment by ojw28** [comment]
- I would argue that you should be implementing your key management system to return all keys when handling Widevine requests regardless, simply because it's more efficient and a better way of doing things. I doubt it's much work at all on the license server side to do this (i.e. if there's a content_id then use it and include the extra keys, if there isn't then don't). In which case a small amount of additional complexity seems well worth it. The generic version could require maintaining three DRM sessions simultaneously (SD, HD, Audio). In the case that PSSH data isn't in the manifest the generic case also requires either loading init chunks from all representations up front at the start of playback, or accepting that the first SD<->HD transition may not be seamless. Neither of these is ideal.

- For the specific case of using different keys for audio and video, you can actually trivially achieve this already by using separate `StreamingDrmSessionManager`s for the audio and video renderers (currently `DashRendererBuilder` in the demo app shares a single instance between both, but you could easily create a separate instance for each to get the separate sessions. As above, I'd recommend you don't do this though (and it wont solve the SD/HD video issue).

**Comment by kidmiracleman** [comment]
OK,

I cede the point RE: efficiency.

We are only concerned with audio vs video for now so we will apply the suggested renderer configuration.

Thanks for the detailed explanations and helpful suggestions.
