### ISSUE TITLE
[HLS][EIA608]Exoplayer combine all cc subtitles into one unknown stream

### ISSUE THREAD

**Issue by wachiu** [google/ExoPlayer#1470]
This problem is found when I tried to play a playback link with EIA608 CC subtitles embedded in media chunks. The player simply merge cc from four CEA608 channels into one stream and call it "unknown". When I try to play the subtitle,  it just plays subtitles from all four CEA608 channels.

I was using Nexus 10 for the test and the Exoplayer version is 1.5.7.

The bug report and ftp connection for the test files will be sent to dev.exoplayer@gmail.com.

**Comment by zsmatyas** [comment]
I think the problem is that EIA608 originates from the analog era when they needed to interleave the different languages into a single stream of bytes. With digital content, providers do not broadcast every content to everyone any more, you select a single level of quality of the adaptive streams, a single language for audio and subtitles and download only that one.

EIA608 lets you interleave 4 channels, the first two came on line 21 and usually contained the English and Spanish subtitles. This is rare today, I haven't found a single sample content to test this interleaved transmissions. I implemented only the getters of the channel index, but I don't recall using it anywhere in my change sets. See
public int getPreambleAddressCodeChannel() in 
https://github.com/google/ExoPlayer/pull/1312/files

The second pair of channels would be even more complicated to correctly identify, as the Eia608Parser does not see the source-line information any more.

Unfortunately, Google guys are quite busy, my pull request is pending for a few months now, but please check and comment on my parser and renderer changes if they are making steps into the correct direction to solve your problem.

**Comment by wachiu** [comment]
Hi Zsmatyas,

Do you mean that the current Exoplayer release is not able to render CC correctly? Is there any relevant release notes, bug reports, issues or implementation plan for Exoplayer team?

Thanks,

**Comment by ojw28** [comment]
@zsmatyas - Yes, sorry about the delay with the PR. We're pretty busy working on some major changes for a 2.x release right now.

**Comment by zsmatyas** [comment]
@wachiu 
The features I implemented in the change sets were definitely missing, check the commit messages. Among others, styles like colors, italic, underlining were not implemented. Whatever was on the screen was always stored in a single cue instance, so it was impossible to position multiple sentences independently before (like in a dialogue of two person, one on the left and one on the right side of the screen). Vertical and horizontal positioning also follows the standard after my changes. There are issues still present, like the standard described the exact font size and characters where uniform-width. With todays fonts if you match the position (of the left side of a cue) to the one expected by the incoming data, the right side will be most probably slightly incorrect (even thought the text is easier to read with current much nicer fonts than in the 80s). 

Handling 2 channels correctly is also missing, as I have never seen a single byte stream interleaving to subtitle languages instead of 2 independent streams. You might need multiple changes, like in
ClosedCaptionCtrl.java, where you need to check the channel bits for the commands to appropriately keep track of the channel value for any incoming data.
You might collect every data and skip sending them to the renderer except the selected one, or you might just skip processing the incoming bytes completely that is not matching the selected channel.

**Comment by AquilesCanta** [comment]
Have you managed to reproduce this issue recently? It should be fixed by now, I think.

**Comment by AquilesCanta** [comment]
Do you still have HLS streams with multiple CC services? If so, please send us a link. We are currently working on support for this.

**Comment by wcsiu** [comment]
@AquilesCanta Thanks. I will verify the fix as soon as possible. For the test streams, I don't have them with me right now.

**Comment by AquilesCanta** [comment]
I'll be closing for now. Please open a new issue if you run into any issues with 608/708 issues.
