### ISSUE TITLE
HlsChunkSource cannot detect subtitle tracks without file extensions

### ISSUE THREAD

**Issue by damienoliver** [google/ExoPlayer#1474]
The default HlsChunkSource uses the chunk file extension to detect which extractor to use inside getChunkOperation.
This causes problems when the subtitle playlist is a dynamic URL and does not have an extension (e.g. *.webvtt) ...the subtitle track slips to the last condition(ts chunk) and crashes due to incorrect extraction.
I have implemented a hack to get around this issue: `if(format.codecs == null && !lastPathSegment.endsWith(TS_FILE_EXTENSION) && format.language!=null)` ...but obviously this is not great. Do you have any thoughts on this? Is there another way I can detect the variant type? (audio,video,subtitle)

Many thanks.

**Comment by ojw28** [comment]
- For de-muxed audio and webvtt specifically, it should be pretty easy to do better (i.e. assume AAC or WebVTT respectively if the file extension is missing). It's trivial to explicitly pass `HlsChunkSource` a type indicating whether it's being configured for one of these two cases.
- Another option would be to sniff the media format, but I'm not sure we really want to do that; it seems fairly heavy for this case.
- Note that there's nothing stopping a service from always putting a file extension on the end of the URL, whether it's being generated dynamically or not. It seems preferable that a service should do this, since it makes the client side logic significantly simpler.

**Comment by ojw28** [comment]
Marking as a bug to resolve the first bullet point, although we probably wont do it until we release 2.x. I would suggest reaching out to the stream provider to request that they append file extensions to their URLs as well.

**Comment by ojw28** [comment]
Fixed for WebVtt segments in: https://github.com/google/ExoPlayer/commit/497651c7b9b70ea4d84568506b88a9c682845fe6. https://github.com/google/ExoPlayer/issues/2025 tracks fixing this issue for other segment types.
