### ISSUE TITLE
Question: issue showing vtt subtitles using Dash with recent version(s) of ExoPlayer

### ISSUE THREAD

**Issue by nikbjork** [google/ExoPlayer#1477]
We have been using a old version of ExoPlayer (1.3) that displayed subtitles just fine. When updating to the latest version, the player will only get the callback for subtitles one time and then it stops working.  I have been trying to figure out exactly what goes wrong in the player without any success. 
Here is a sample asset that can be used for testing: http://d2njhtu7w6ua6u.cloudfront.net/reference-source-asset-no-drm/Manifest.mpd

**Comment by AquilesCanta** [comment]
There are two things to mention: The TTML subtitles have an incorrect mime type, we use "application/ttml+xml" for regular ttml, like the one in the provided manifest. The adaptation set uses application/mp4, which we use for a spec that allows ttml embedded in mp4 files. For this reason, the player tries to parse the ttml file as it was an mp4 file. Which results in parsing errors. Leaving this aside...

The WebVTT cues include absolute cue timing, instead of relative timing, which we currently correctly support. **If you want a quick solution**, you can change the cue timing so that if a webVTT file corresponds to the period [x, x + segment_length), the cue starting time will state something of the form:
`
absolute_start_time - x --> absolute_end_time - x
cue text
`
This means you should basically subtract the starting time of each segment to every cue timestamp. So, if you have a cue like
`
0:07:00.000 --> 0:07:15.000
Hello
`
In a WebVTT file that starts at the minute 7 of the playback, it would become:
`
0:00:00.000 --> 0:00:15.000
Hello
`

Concerning absolute timing, we are still deciding what we will do here because we haven't found a specification that addresses this (feel free to point us to one, if available). We are tracking this in [#1493](https://github.com/google/ExoPlayer/issues/1493), so please follow it to see how this turns out.

**Comment by nikbjork** [comment]
Big thanks for the reply it helped us out a lot!
