### ISSUE TITLE
Add auto-retry possibility to DashChunkSource in case of bad connectivity

### ISSUE THREAD

**Issue by lukaszkalnik** [google/ExoPlayer#1478]
While streaming Dash with the DemoPlayer, in case of bad connectivity (e.g. when switching between WiFi and mobile network) we get
```
com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: 
Unable to connect to [url here]
Caused by: java.net.SocketTimeoutException
```
Is there a possibility to add some retry functionality, like setting retry count in the constructor of `DashChunkSource` (as in https://github.com/google/ExoPlayer/issues/120)?

Thanks

**Comment by ojw28** [comment]
Is playback actually failing? We already retry a number of times to handle this case, and I don't have any issues in the demo app switching between WiFi and mobile networks. If you want to retry harder, you can specify a higher-than-default value for `minLoadableRetryCount` when instantiating each `ChunkSampleSource` instance.

**Comment by lukaszkalnik** [comment]
Yes, playback is failing, although it's not so easy to reproduce.
Will try with increasing `minLoadableRetryCount` in `ChunkSampleSource`, thank you!

**Comment by ojw28** [comment]
Right, increasing `minLoadableRetryCount` should fix it in that case. The policy is that we'll retry for as long as we have buffer to be playing, and once the buffer has run out we'll fail only if we've also retried at least `minLoadableRetryCount` times. Note that this means failure is less likely if more of the media is buffered, since you'll most likely be able to fit more retries in before the buffer runs out.

As a final note, increasing `minLoadableRetryCount` will increase the time that it takes for legitimate failures to be propagated to the user (the player will appear as though it's buffering until it gives up in such cases). So you probably don't want to increase it too much.
