### ISSUE TITLE
Allow for non-relative sub-samples in caption chunks

### ISSUE THREAD

**Issue by baconz** [google/ExoPlayer#1493]
I have WebVTT chunks associated with a DASH stream that have non-relative cue timestamps. It would be nice if there were a way to tell my `DashChunkSource` to create a text format with `subsampleOffsetUs` set to 0. I'm not sure what the best design is. Maybe a method that gets the offset given an `adaptationSetType`?

**Comment by AquilesCanta** [comment]
Do you have access to a spec that defines the correct behavior in this case? I mean, "relative timing" and "absolute timing" in, say, WebVTT cues. If you have knowledge of such spec, that would be really helpful.

**Comment by ojw28** [comment]
Note - There doesn't seem to be anything explicit in the DASH IF guidelines about this. The DASH IF test vectors for subtitles are all single segment only, so that doesn't help either. For the latter, I filed a request for multi-segment test vectors [here](https://github.com/Dash-Industry-Forum/Test-Vectors/issues/44), but if it's not actually well defined what the timestamps should be, it's likely that'll need to be clarified somewhere first!

**Comment by ojw28** [comment]
As per the response in https://github.com/Dash-Industry-Forum/Test-Vectors/issues/44, the DASH IOP document indicates that for live you're expected to embed WebVTT in ISOBMFF. According to the IOP non-embedded WebVTT should be used in the single segment on-demand case.
