### ISSUE TITLE
DecoderInfo is not public and cannot be accessed outside of package

### ISSUE THREAD

**Issue by cmdkhh** [google/ExoPlayer#1518]
Just wondering if there was a reason that `DecoderInfo` in `com.google.android.exoplayer` has a non public constructor? When trying to extend `MediaCodecTrackRenderer` to implement my own AudioRenderer it forces some ugly reflection in to create the object in  `protected DecoderInfo getDecoderInfo()` to allow passthrough.  The class is also `final` and does not allow extending.

https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java#L228

I am getting an sample ready for 6.0+ variable playback as it is highly requested and did not want to include the reflection bit. 

Ugly reflection for reference:
Class c = Class.forName("com.google.android.exoplayer");
Constructor<DecoderInfo> constructor = c.getDeclaredConstructor(Object.class);
constructor.setAccessible(true);
DecoderInfo obj = constructor.newInstance(passthroughDecoderName, false);

**Comment by ojw28** [comment]
The reasoning is that creating a `DecoderInfo` for a decoder that doesn't exist wont ever work, and you should be able to get a `DecoderInfo` for any decoder that does exist from `MediaCodecUtil.getDecoderInfo` or `MediaCodecUtil.getDecoderInfos`. Do you get the `DecoderInfo` that you need if you call:

```
MediaCodecUtil.getDecoderInfo(MimeTypes.AUDIO_RAW, false);
```

If so then perhaps we should create a `MediaCodecUtil.getPassthroughDecoderInfo` to formalize this, and use that approach for `MediaCodecAudioTrackRenderer` as well rather than using the approach that only works if you're in the same package.

**Comment by ojw28** [comment]
I think we'll add a `MediaCodecUtil.getPassthroughDecoderInfo` to handle this case.

**Comment by ojw28** [comment]
Added
