### ISSUE TITLE
ExoPlayer fails to playback HEVC/AVC hybrid profile HLS v3 

### ISSUE THREAD

**Issue by wachiu** [google/ExoPlayer#1542]
Exoplayer version: 1.5.7
Device: nexus 10
Exoplayer works perfectly with AVC only or HEVC only playlists. However, following errors occurs when the playlist contains both AVC and HEVC.
1. Audio stream doesn't work for some streams.
2. message "This device does not provide a decoder for application/id3" appears for selecting a few streams.

The bug report and ftp connection for the test files will be sent to dev.exoplayer@gmail.com.

**Comment by ojw28** [comment]
How do you expect players to handle this type of playlist? I think most clients would pick either AVC or HEVC, rather than mixing the two during playback. On Andorid at least, it's not easy to support seamless switching between AVC and HEVC because they use completely different decoders.

If you do expect a client to pick either AVC or HEVC, then why not just have a separate playlist for each?

**Comment by hoimingw** [comment]
Hi ojw28,

Thanks for your response. People might choose HEVC and AVC for high and low profiles, respectively. Decoder has to be reinitialized during stream switching, so why it makes difference for switching between HEVC/AVC and AVC/AVC?

Thanks,

**Comment by ojw28** [comment]
Decoders on Android support seamless adaptive reconfiguration, but switching between AVC and HEVC would require releasing one decoder and acquiring another. The former is likely to be significantly smoother than the latter.

I'm still not entirely convinced about the justification for mixing AVC and HEVC. If a device supports HEVC and if you're going to provide HEVC transcodes, then why would you serve the low quality variants in AVC when you could save a whole bunch of bandwidth by serving them using HEVC too?

**Comment by hoimingw** [comment]
Hi ojw28,

Understood. Thanks for the explanation.

Thanks,
Hoi Ming
