### ISSUE TITLE
Playback stalls HLS manifest with DISCONTINUITY tags

### ISSUE THREAD

**Issue by biodatacomp** [google/ExoPlayer#1546]
http://stitcher.pluto.tv:80/stitch/hls/channel/5268abcd0ce20a8472000114/master.m3u8?device_type=android%2CLGE%2Cmobile&device_make=android%2CLGE%2Cmobile&sid=05192016SomeRandom1

- Load the above master manifest in Samples as HLS source for the Demo app.
- Observation is that around the time it hits DISCONTINUITY tags, the player eventually stalls.
- The same master manifest works fine in Safari and couple other players.

Have seen some similar issues where the observed issue was due to missing 
#EXT-X-DISCONTINUITY-SEQUENCE or #EXT-X-DISCONTINUITY tags.
From an initial analysis in our case those seem to be present as per the HLS Spec.

Any help pointing to any anomaly in the Media playlist, or figuring this out from player perspective would help.

**Comment by biodatacomp** [comment]
Thanks to the timeline analysis from https://github.com/google/ExoPlayer/issues/1541
Was able to test this on 1.5.3 and do not see the same issue.

**Comment by biodatacomp** [comment]
Reverting the PtsTimestampAdjusterProvider logic added in https://github.com/google/ExoPlayer/commit/00f8deda3d7b558794986fcc6be47d49ea3a5b2b ,
seems to have resolved the issue.

(In case someone wants to test the above m3u8 with and without those changes, adding patch that should revert that change on latest master. ) 
[May19ExoPlayer_RevertHlsChanges_RemovingPtsAdjusterProviderLogic.txt](https://github.com/google/ExoPlayer/files/273580/May19ExoPlayer_RevertHlsChanges_RemovingPtsAdjusterProviderLogic.txt)

**Comment by ojw28** [comment]
Although your manifests contain EXT-X-DISCONTINUITY-SEQUENCE tags, they are being incremented incorrectly. I will provide a more complete analysis tomorrow, but I believe this to be a media issue, not an issue with ExoPlayer.

**Comment by biodatacomp** [comment]
@ojw28  would help if you can also point out to the exact piece of code where I can analyze this on the sequence number and understand this better.
Or any pointers to specific deviation from the HLS spec.

**Comment by ojw28** [comment]
I added some debugging lines to `HlsPlaylistParser` to print out data from each manifest as it's received. The playlists being served aren't quite right. Here's a sequence I observed. For each segment line in the logging below, the first number is the assigned discontinuity sequence number. This is defined in the HLS spec as:

> A segment's Discontinuity Sequence Number is the value of the EXT-X
   -DISCONTINUITY-SEQUENCE tag (or zero if none) plus the number of
   EXT-X-DISCONTINUITY tags in the Playlist preceding the URI line of
   the segment.

The second number is the assigned media sequence number.

1. First response. So far so good:

```
EXT-X-DISCONTINUITY-SEQUENCE	0
EXT-X-MEDIA-SEQUENCE	62
(Segment)	0	63
EXT-X-DISCONTINUITY	
(Segment)	1	64
(Segment)	1	65
(Segment)	1	66
(Segment)	1	67
EXT-X-DISCONTINUITY	
(Segment)	2	68
```

2. Second response. `EXT-X-DISCONTINUITY-SEQUENCE` has been incremented without any corresponding removal of an  `EXT-X-DISCONTINUITY` tag. This is invalid. Note that the segments now (incorrectly) have different discontinuity sequence numbers than previously:

```
EXT-X-DISCONTINUITY-SEQUENCE	1
EXT-X-MEDIA-SEQUENCE	63
EXT-X-DISCONTINUITY	
(Segment)	2	64
(Segment)	2	65
(Segment)	2	66
(Segment)	2	67
EXT-X-DISCONTINUITY	
(Segment)	3	68
(Segment)	3	69
```

3. Third response. The  `EXT-X-DISCONTINUITY` tag has now been removed but `EXT-X-DISCONTINUITY-SEQUENCE` has not been incremented:

```
EXT-X-DISCONTINUITY-SEQUENCE	1
EXT-X-MEDIA-SEQUENCE	63
(Segment)	1	64
(Segment)	1	65
(Segment)	1	66
(Segment)	1	67
EXT-X-DISCONTINUITY	2
(Segment)	2	68
(Segment)	2	69
```

I think the problem here is that the `EXT-X-DISCONTINUITY` tag should have been removed in the second response rather than in the third response. Alternatively, `EXT-X-DISCONTINUITY-SEQUENCE` should have been incremented in the third response rather than in the second response. I think you probably want to do the first of these, since it doesn't make sense for an `EXT-X-DISCONTINUITY` tag to appear before the first segment.

**Comment by ojw28** [comment]
Note that in addition to breaking playback in ExoPlayer, this issue likely causes more subtle failures when switching variants during ad breaks across other HLS players.

**Comment by biodatacomp** [comment]
@ojw28 thanks for that useful info. It was indeed the EXT-X-DISCONTINUITY-SEQUENCE that was confusing from the spec and taking care of it seems to have fixed the issue for us.
We have been using mediastreamvalidator as a tool to ensure that we are confirming to HLS spec, but it also spits out lot of noise which hides some real issues. 
Is there any other tool that you would recommend for figuring potential issues like this.

**Comment by ojw28** [comment]
I don't see much noise when I run the test URL through `mediastreamvalidator`. There are quite a few warnings there about incorrect mimeTypes, target durations and bitrate declarations, but it seems to me they're all things you should be fixing rather than ignoring? The bitrate declaration issues appear to be particularly concerning. According to the validator the actual bitrate of each variant is over 2x what the master playlist is declaring?

To answer your question, no, I don't know of another tool that I would recommend. I debugged the issue with discontinuity sequence insertion manually. I would however encourage you to ensure you have regression tests in place to validate correct behavior going forward.
