### ISSUE TITLE
Event When a New DASH Representation's Initial Frame is Rendered?

### ISSUE THREAD

**Issue by mikeswanson** [google/ExoPlayer#1565]
I've spent quite a bit of time with the ExoPlayer source, but I haven't been able to nail down where to add (or find) an event that signals when the first frame of a new MPEG-DASH representation is rendered. For example, when my FormatEvaluator decides to drop to a lower-quality representation, I'd like to know when the initial frame of the new representation is actually rendered. I've looked through DashChunkSource and MediaCodecVideoTrackRenderer, and I feel like I'm in the right area. Can anyone help to focus my search?

**Comment by ojw28** [comment]
If you look in the demo app, the `EventLogger` prints a log line more or less when the representation changes, [here](https://github.com/google/ExoPlayer/blob/dev-1.5.6-rc/demo/src/main/java/com/google/android/exoplayer/demo/EventLogger.java#L120). If you trace this back, you'll see that the event that's fired is `ChunkSampleSource.EventListener.onDownstreamFormatChanged`.

The only difference between this event and exactly what you're asking for is that `onDownstreamFormatChanged` is fired when a new format is *fed* to the decoder, where-as what you're asking for is an event when a new format is *output* from the decoder and rendered on screen. In practice, the difference will be small. If you're just looking to do some logging when the format changes, `onDownstreamFormatChanged` should be more than good enough for your needs. It's probably good enough for most UI changes that you might like to do in response to a format change as well.

If `onDownstreamFormatChanged` isn't suitable for your needs, please describe your use case in more detail. Thanks!

**Comment by mikeswanson** [comment]
Thank you for the fast response and excellent pointer. Indeed, that event is fired just prior to the new format being output from the decoder and rendered on screen.

In my case, though, I need to transform the output surface to coincide with the first frame of the new format, so frame accuracy is important to avoid visual "glitching" during that visual transition. As it stands, the `onDownstreamFormatChanged` event isn't quite accurate enough for this use case. I may be able to use the `positionUs` parameter for better timing, but ideally, I'd like to know when the frame has been output.

**Comment by ojw28** [comment]
What kind of transformation do you need to do?

**Comment by mikeswanson** [comment]
It would be difficult to describe all of the details here, but the short version is that the video is being decoded to a texture in Unity, and the 3D model in Unity needs to be transformed (e.g. rotated) when the format changes. So, the transformation isn't directly related to work that ExoPlayer is performing, but I do need to synchronize the 3D model change with the decoded/output frame.

**Comment by ojw28** [comment]
Sounds fancy ;). I'll try a different question. What information would you need about the format in order to apply the appropriate transformation? Or in other words, if there were an `exactlyWhatYouWantCallback(x)`, what's the minimum amount of information `x` that you need?

**Comment by mikeswanson** [comment]
If fancy == headache, then we agree. :-)

Something like the existing `onDrawnToSurface` on `MediaCodecVideoTrackRenderer` that indicates that the first frame of a new format has been drawn (or buffer perhaps, if the renderer has no direct knowledge of formats). Perhaps `onFormatDrawnToSurface(Format format, Surface surface)`? Ideally, I'd want something that I can associate with a format, and I only need to know that it's been drawn.

**Comment by ojw28** [comment]
Got it. It's somewhat awkward, because detailed information about the format doesn't propagate as far as you need it to. In some cases where the representations are similar formats, the decoder might not even output a format changed event.

I don't suppose your representations happen to be all different resolutions? If so then you could probably use `onVideoSizeChanged`, which should be spat out at the correct time. Note however that since events are delivered to a different thread, you'd still have a somewhat uncertain delay between the event being dispatched and it being processed on the receiving thread.

The best solution is probably going to require you to hook directly into the player's rendering thread. You could, for example, extend `MediaCodecVideoTrackRenderer` by:

1. Override `onInputFormatChanged` to note changes to the input format.
1. Override `onQueuedInputBuffer` to note down the presentation timestamp of the first buffer queued after each input format change.
1. Override `processOutputBuffer` or some of the methods that are called by that method. You should be able to see when a buffer is released whose timestamp is >=* to the one noted for each input format change. At this point, you can fire an event.

* In most cases you'd expect == to work, but you might be unlucky if the first frame is dropped, plus we've seen some funky decoders that like to "tweak" the timestamps a little (we now have device acceptance tests to prevent this, for new devices).

**Comment by mikeswanson** [comment]
Thank you for the detailed response. I sensed that I was trying to intermingle formats and the renderer.

Unfortunately, the representations are all the same resolution, so the `onVideoSizeChanged` event won't work.

I'll try hooking into the rendering thread. Your suggestions are very helpful, and I really appreciate your time and assistance. Thank you for maintaining such a robust player!

**Comment by ojw28** [comment]
Cool, let us know how you get on! I'm not actually sure whether you'll find sufficient information in the format objects that `onInputFormatChanged` receives, so that's something to be aware of. In 2.x this should be resolved (there are no longer separate `Format` and `MediaFormat` classes in 2.x, and the formats propagated to the renderers should include sensible format identifiers).
