### ISSUE TITLE
Player Stuck in Buffering State for Audio Stream

### ISSUE THREAD

**Issue by wajidp** [google/ExoPlayer#1584]
Discontinuity detected [expected 12613060, got 12189160] 
Am getting this buffering problem frequently  Sometimes it recovers but most of the times doesn't. Am using 1.5.8.

http://stream.peaceradio.com:8000/aacsblow

**Comment by andrewlewis** [comment]
How frequently do you see the discontinuity logging? I haven't been able to reproduce the issue so far, having left the stream playing for 10 minutes.

**Comment by wajidp** [comment]
Its happening too frequently, you can try turning of the wifi and back again.

**Comment by andrewlewis** [comment]
This looks the same as #1285. Did you try the workaround there?

**Comment by wajidp** [comment]
There is audio slutter for the mentioned temporary fix, still there is no proper permanent fix for this, its effecting the users in low bandwidth network heavily.

**Comment by ojw28** [comment]
Users with insufficient bandwidth are going to get re-buffering every ~5 seconds or so anyway, even with a permanent fix. So it's not like a permanent fix is going to solve the problem for this class of users. If they fundamentally don't have sufficient bandwidth for the stream, it's not going to play without interruption.

I think (although I'm not 100% certain) this is fixed in a more satisfactory way in 2.x, but it'll be at least another few weeks until we start pushing this version to GitHub, and we have no plans to backport a fix to the current release.

**Comment by wajidp** [comment]
My problem is the stream is not coming back even in sufficient bandwidth, and how can i use in 2.x version as am using r1.5.8 in my gradle

**Comment by ojw28** [comment]
If you use the temporary fix as described in #1285 then the stream will come back. If you don't then it might not, as is clearly documented on that issue. I'm not really sure what your question is. We're going to implement a more permanent fix in 2.x. It's not available on Github yet. Even the permanent fix wont allow users with insufficient bandwidth to play content without interruption.

**Comment by ttencate** [comment]
For those who found this issue through a search engine: if I'm not mistaken, that "more permanent fix in 2.x" is now on GitHub in the dev_v2 branch: https://github.com/google/ExoPlayer/commit/90b70818243bdd1a7758e50f08fcf445c6095d91
