### ISSUE TITLE
Simplified Api & Documentation

### ISSUE THREAD

**Issue by nitro52** [google/ExoPlayer#1590]
This is more general feedback. I've been given the job of investigating how we can implement streaming from Azure Media services using Smooth streaming or Dash with DRM protected content. From their point they simply provide a URL. I've Read that Exoplayer is probably the best bet and i've downloaded the demo, and had a quick read through the documentation. I also watch an intro video that explains that exo player is already a wrapper around some low level api's to try to reduce the entry cost. Well i still feel like there some work needed their. You seem to need some pretty in-depth understanding  of how all the parts fit together and the documentation often has partial code samples. The demo project is hundreds of lines of code. Its really difficult to figure out where to start. 

Surely theirs a way to simplify this more so you have a simple and easy to use api that also provides the ability to replace the parts that you need in more advanced scenarios. 

At the moment they only thing i can do is try to dig through this demo project to try and understand what on earth its doing, what parts i need and what i don't. At the very least it would be nice if the documentation walked you through the complete process of setting up a new project to use excoplayer.

**Comment by ojw28** [comment]
Thanks for the detailed feedback. My best advice to help you get started is to get a test URL for an example of your DASH content, add it to `Samples.java` in the demo app, build and play. So it should be pretty easy to get something that's able to play your content, using the demo app as a starting point.

Your comments on the size of the demo app and its complexity are justified, and this is something we're actively addressing for 2.x The number of classes in the demo app in 2.x currently stands at 6 (previously it was 12), and will likely fall to 5. This is partly achieved by the promotion of the code in the `player` package in the demo app to the library itself, and the creation of a new `SimpleExoPlayer` class.

We'll be pushing 2.x to GitHub soon, and will update this issue once that's done.

**Comment by ojw28** [comment]
Note - To keep track of 2.x updates, you can follow our [blog](https://medium.com/google-exoplayer).

**Comment by brianwernick** [comment]
I'm super excited about the 2.x version of ExoPlayer :) however in the meantime I have a wrapper around the ExoPlayer to simplify standard implementations called [ExoMedia](https://github.com/brianwernick/ExoMedia) that may help you get up and running.

@ojw28: Two things, 
1. I just want to make sure it is alright with you that I'm linking in my library on "issues" like this one.
2. If there is anything I can do to help with the 2.x rewrite let me know (aside from the standard CLA, etc.)

**Comment by rburnham52** [comment]
@ojw28 Thanks for the feedback, I struggled with digging through the demo code/documentation trying to marry them together for a while until i stumbled upon another library that wraps exoplayer. 

https://github.com/googleads/google-media-framework-android

The demo implementation for this project was a lot easier to digest. I as able to add the URL to an existing collection and test it, I found that dash required another url for widevine that was a hard coded value in the demo but easy enough to track down and fix. After this i was able to get my first working example. 

The 2.x focus is defiantly interesting. It sounds like it could be very beneficial. 

@brianwernick 
ExoMedia was one of the main alternatives i was playing with. Although i had some problems getting it to work with our test URL's. I can't remember the exact problem but i think it was just not giving me any exceptions to work with for DASH. I think the documentation was a bit lacking for other scenarios like configuring it for Dash ect. 

Looking back at the problem now it might have been the DRM url that was the issue for DASH playback. I might have another look and ExoMedia because it does seem a bit more complete than Google Media Framework Its been a lot to learn and in general there is very newbie friendly documentation to help you. I would have looked at hundreds of different google search results during the process.

**Comment by ojw28** [comment]
@nitro52 - You can add a URL to an existing collection in ExoPlayer's demo app too. Samples are listed in `Samples.java`, so you just need to modify that. For 2.x this class will turn into a JSON file and it'll be possible to load any such file into the demo app without making any code modifications.

@brianwernick - Sure, feel free to mention it on issues where it's relevant, such as this one ;). It's a cool project!

**Comment by rburnham52** [comment]
@brianwernick Just as a follow up i gave it another go and it looks like it wasn't working because it currently does not support DRM. This is required for us.

**Comment by ojw28** [comment]
The demo app has been significantly reduced in size in ExoPlayer V2. For V1 we had:

```
$ find v1/demo/src/main/java/ -name '*.java' | xargs wc -l
   207 v1/demo/src/main/java/com/google/android/exoplayer/demo/SampleChooserActivity.java
   268 v1/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java
    65 v1/demo/src/main/java/com/google/android/exoplayer/demo/SmoothStreamingTestMediaDrmCallback.java
   213 v1/demo/src/main/java/com/google/android/exoplayer/demo/EventLogger.java
   199 v1/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java
   204 v1/demo/src/main/java/com/google/android/exoplayer/demo/player/SmoothStreamingRendererBuilder.java
   600 v1/demo/src/main/java/com/google/android/exoplayer/demo/player/DemoPlayer.java
    88 v1/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java
   266 v1/demo/src/main/java/com/google/android/exoplayer/demo/player/DashRendererBuilder.java
   762 v1/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java
    62 v1/demo/src/main/java/com/google/android/exoplayer/demo/WidevineTestMediaDrmCallback.java
  2934 total
```

in V2 we have:

```
$ find v2/demo/src/main/java/ -name '*.java' | xargs wc -l
  419 v2/demo/src/main/java/com/google/android/exoplayer2/demo/SampleChooserActivity.java
  336 v2/demo/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionHelper.java
  439 v2/demo/src/main/java/com/google/android/exoplayer2/demo/EventLogger.java
   24 v2/demo/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java
  574 v2/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
 1792 total
```

If you ignore the files that are essentially just scaffolding (i.e. not interesting), the lines of code goes from 2246 to 910.
