### ISSUE TITLE
Audio stream moved to buffering state immediately on disconnection of internet

### ISSUE THREAD

**Issue by wajidp** [google/ExoPlayer#1606]
Am trying to play an icecast stream, when my internet is turned off, the player goes to buffering state immediately. I was wondering why the stream is not getting buffered in the device with the exoplayer.
With mediaplayer api the stream is played for around 1 minute before it dies.
Am i missing somethings my bufferms=4000 and minrefbuffer is 0

http://stream.peaceradio.com:8000/low

**Comment by wajidp** [comment]
I need to get the stream downloaded from the next minute atleast. Is it possible?

**Comment by ojw28** [comment]
This is a feature request to avoid immediate retry for live streams in ExtractorMediaPeriod. It would be better to wait until the player can make no further progress before triggering the retry.

**Comment by BMarton** [comment]
Any progress on this issue?

**Comment by janeriksamsonsen** [comment]
Yeah, is this a prioritized feature? It should be...

**Comment by ojw28** [comment]
This is scheduled to be fixed by end of year (or shortly thereafter).

**Comment by janeriksamsonsen** [comment]
@ojw28  - excellent! 👍

**Comment by viaductit** [comment]
I have tried the r2.5.4, still not working. The issue was reported one year ago and will be fixed next year?? Is no quick fix possible until there is an official fix? This should be a high prio bug becuase it is realy bad for the user experience. We have 500k users and a lot of complains regarding this issue :-S

**Comment by janeriksamsonsen** [comment]
Any more information about when this will be implemented?

**Comment by ojw28** [comment]
I have a change that implements this, but it's so hacky I don't think it can be submitted in its current form. We need a little more time to try and come up with something better.

**Comment by janeriksamsonsen** [comment]
@ojw28, thanks for responding. Is the "fix" available in a feature-branch which I can use until waiting for the final solution?

**Comment by ojw28** [comment]
Not currently, but we should have something to share this week.

**Comment by ojw28** [comment]
This should be fixed in `dev-v2`. Please give it a try.

Note that if the connection is broken, there will always be an audible discontinuity when the retry happens, even if the network is good again at that point. The way these streams work isn't designed to allow seamless re-joins. The best way to deliver audio to mobile devices is to use a more appropriate streaming technology such as DASH or HLS, for which this issue does not apply.
