### ISSUE TITLE
Some HLS stream is not playing video, showing the first frame

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#1623]
I've built the demo ExoPlayer app and deployed to a real device (tablet PC Samsung).
I've added several HLS streams and they work besides one (Spas TV). This one produces sound but video does not move, but shows one frame freezed.
Maybe you could check this case and find out, what is wrong specifically with this stream. 
Thank you.

Link to the stream: http://spastv.cdnvideo.ru/spastv-live/spastv.sdp/playlist.m3u8
Android version: 4.3
Exoplayer version: r1.5.9

**Comment by ojw28** [comment]
@AquilesCanta - This reproduces on latest V2. Unsure why.

**Comment by AquilesCanta** [comment]
@dreich, I have observed that sometimes (I didn't manage to reproduce at first, that´s why I say sometimes), the keyframes in the TS contain invalid PTS values in contrast with (values that map around two and a half hours later) non-key frames. I was able to notice this with other transport stream inspectors and have double checked the PES syntax to corroborate ExoPlayer is not doing something wrong. I think the media is malformed. If you have reason to think otherwise, please let me know. 

As a side note, VLC does play the stream, but this wouldn't be the first time VLC plays malformed media.
