### ISSUE TITLE
Audio is playback but Video is not play in exoplayer

### ISSUE THREAD

**Issue by zaky295** [google/ExoPlayer#1645]
When i run exoplayer for DASH in android devices whose api level is 23 than it runs well but when i run same thing in android device whose api level is between 21 to 19 than only audio is playback whereas video is not.so what should i do.

**Comment by andrewlewis** [comment]
One possible explanation is that the video is in H.264/AVC Main profile. Since Android 6.0, devices must support the Main profile, whereas in earlier versions of the Android compatibility definition only Baseline profile was required. You should serve media in a format that is supported by all devices your app runs on. What is the exact video format?

**Comment by zaky295** [comment]
hi andrewlewis, thank for your response.
the exact video format is .mp4. other than what information should you need?

**Comment by andrewlewis** [comment]
We need more information about the sample format. If you share the sample media (posting a link here, or emailed to dev.exoplayer@gmail.com with the issue number in the subject) we can take a look.

**Comment by ojw28** [comment]
Closing due to lack of information.

**Comment by ghost** [comment]
Hi guys!
I'm also dealing with this issue. I'm playing .mp4 videos. I've noticed the issue happens by playing videos with AR of 16/9. When I'm playing videos with AR of 4/3 it works properly. In addition, the issue happens for http media and not for file media with AR of 16/9.
Any additional information is needed?

EDIT: Also noticed that the issue happens for 1280x960 and not for lower resolutions as 768x432.
