### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by IlyaMyasoedov** [google/ExoPlayer#1648]
- Description : exception is thrown when we add an exoplayer in the service that runs in a separate process
- Steps to reproduce: you have to  add an exoplayer to a service that runs in a separate process .
- version: 1.5.9
  [log.txt](https://github.com/google/ExoPlayer/files/344538/log.txt)

**Comment by AquilesCanta** [comment]
Next time, please provide more context to your question, it is impossible for us to help you with this amount of information. The items of the issue template are not optional unless they don't apply (not the case, now).

This is not related to exoplayer. If you search for "Can't create handler inside thread that has not called Looper.prepare()", the first three entries will probable be helpful. Since no code was provided to recreate, I am not able to tell which. The issue tracker is not for generic programming questions, I'd try stack overflow instead. Good luck!

**Comment by IlyaMyasoedov** [comment]
@AquilesCanta 
The reason is in these lines of DemoPlayer constructor:

```
public DemoPlayer(RendererBuilder rendererBuilder) {
    this.rendererBuilder = rendererBuilder;
    player = ExoPlayer.Factory.newInstance(RENDERER_COUNT, 1000, 5000);
    player.addListener(this);
    playerControl = new PlayerControl(player);
    mainHandler = new Handler();
    listeners = new CopyOnWriteArrayList<>();
    lastReportedPlaybackState = STATE_IDLE;
    rendererBuildingState = RENDERER_BUILDING_STATE_IDLE;
    // Disable text initially.
    player.setSelectedTrack(TYPE_TEXT, TRACK_DISABLED);
  }
```

When i use exoplayer in a separate thread,  i need to write a line "Looper.prepare" before "mainHandler = new Handler();"

**Comment by AquilesCanta** [comment]
I am glad you found the solution!

**Comment by IlyaMyasoedov** [comment]
@AquilesCanta But class DemoPlayer does not permit doing it

**Comment by IlyaMyasoedov** [comment]
@AquilesCanta 
When i use several instances of the player I get an error that says "Looper cannot be prepared several times"

**Comment by AquilesCanta** [comment]
I don't think DemoPlayer has anything to do with your issue, I strongly suggest revisiting your threading model, I would suspect that you are creating several instances of DemoPlayer in the same thread, and that each instance is trying to call Looper.prepare(), then the error is quite self explanatory. You can check that prepare() has been called before, and only call it if needed. You need to solve these issues yourself, as this is not the purpose of the issue tracker. You can find all information you need by searching for these error messages.

**Comment by shysh** [comment]
@IlyaMyasoedov Hello! Do you have some progress with Looper?
