### ISSUE TITLE
mp4 with EIA-608, close caption not showing..

### ISSUE THREAD

**Issue by LukeLinXu** [google/ExoPlayer#1658]
I used the demo to play it, also change the text render in ExtractorSampleSource.java to Eia608TrackRenderer, but still not luck. 

The Text button not showing means, exoplayer identify it as 0 track. 

I have uploaded on my website.
http://www.lalalala.ca/Android_Rock.mp4

By the way, I used MediaInfo to confirm it has EIA-608 cc, and iOS device can show it well.

Thanks,
Luke

**Comment by zsmatyas** [comment]
Your content is:
Format                                   : MPEG-4
Format profile                        : Base Media
Codec ID                                 : isom
Overall bit rate mode                    : Variable
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3.0

On the **2.x experimental branch**, for the files 608 is processed, TsExtractor calls consume() ending up in H264Reader calling SeiReader.consume() that leads to Eia608Parser being initialized.

If I search for H264Reader usage, it is only initialized in TsExtractor. 

**For your content Mp4Extractor is used, it seems that that path needs to be updated so that the caption part is consumed from the stream.** 

The text track seems to be of type "clcp", not one of the supported types: "subt", "sbtl" or "text".

**Comment by AquilesCanta** [comment]
What @zsmatyas says is correct. We can use this issue to track Mp4 + CEA subtitles support. The clcp handler type is also a concern, but I am sure we can add it to the list of supported handlers as an alternative to "subt". However, it will most definitely be added to version 2.

**Comment by LukeLinXu** [comment]
@zsmatyas @AquilesCanta Thanks guys.

**Comment by AquilesCanta** [comment]
This feature will be available soon, in the next v2 release.
