### ISSUE TITLE
When applying an MP4 edit list, preroll and skip samples from a keyframe to the start of an edit

### ISSUE THREAD

**Issue by sanmall** [google/ExoPlayer#1659]
video recorded from ios can not play in front of a few seconds, but the audio is ok.

**Comment by sanmall** [comment]
eg：http://biubiustorage.oss-cn-shenzhen.aliyuncs.com/a7/dc/a7dc023ba53fccb5ded0be16f936266cbca10ac15e202aaa8eee30b1b8e0d048.mp4

**Comment by sanmall** [comment]
@ojw28

**Comment by andrewlewis** [comment]
This file contains an edit list that skips the first video frame, which is a keyframe. Due to a limitation in how we handle edit lists (see [this comment](https://github.com/google/ExoPlayer/blob/a4b4c49446ce4938fe7c6721bb155554a37bd95f/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java#L261)) we don't send the frame to the decoder, which means samples are dropped up to the next key-frame. This is why video starts playing late.

I'll use this issue to track the enhancement of extracting and skipping samples from the latest keyframe at/before an edit up to the start of the edit. I think it's unlikely we will prioritize it in the near future, unless we find that this type of stream is common. Thanks!

**Comment by greyson-signal** [comment]
Hi there, just wanted to say that we're hitting this issue at [Signal](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en&gl=US). Videos recorded by iOS devices that are then sent and played back by ExoPlayer on an Android device will sometimes run into this. It doesn't seem to be _all_ videos transcoded by iOS, but some.

**Comment by rohitjoins** [comment]
This issue has now been [fixed](https://github.com/androidx/media/commit/f133e8d1f237e564f5d067dd25fa78c2929f3082).
