### ISSUE TITLE
Unable to playback hls stream

### ISSUE THREAD

**Issue by sooth-sayer** [google/ExoPlayer#1660]
Hi,

I use exoplayer to play hls live stream 
(http://rt-sth-rd-htlive-lb.cdn.ngenix.net/hls/CH_R03_OTT_STH_RD_1TV/variant.m3u8). 
But the playback state never switches from buffering to ready.
To reproduce the problem I use exoplayer demo app. (r1.5.9)

I tried to playback this on next device models:
- Asus ZenFone2 (5.0)
- Sony Xperia Z (5.1.1)
- Nexus 5X (6.0.1)

ffplay plays this stream without any difficulties.

**Comment by trolik** [comment]
Same bug for me

**Comment by ojw28** [comment]
The link provided gives me a 403 (forbidden) http response. Is it still active? If it is, is it geo-restricted somehow in a way that means we can't access it from the UK? Can you provide a working link that we can reproduce the issue with? Thanks!

**Comment by sooth-sayer** [comment]
@ojw28, thanks for reply. Can you try another one link (http://ec2-54-201-241-103.us-west-2.compute.amazonaws.com/variant.m3u8) ?

**Comment by ojw28** [comment]
The stream doesn't play because it doesn't contain any IDR frames. As per Apple's [technical note](https://developer.apple.com/library/ios/technotes/tn2224/_index.html), streams should have at least one IDR frame in each TS segment.

If you want to manually force ExoPlayer to play this stream, you can do so by ORing `TsExtractor.WORKAROUND_ALLOW_NON_IDR_KEYFRAMES` into `workaroundFlags`, computed in `HlsChunkSource` and passed to the `TsExtractor` constructor. We have no plans to enable this by default though, since it can cause corruption on seeking for compliant streams. The correct fix is to make sure the content includes IDR frames.

**Comment by sooth-sayer** [comment]
@ojw28 Thanks for the explanation!
