### ISSUE TITLE
ExoPlayer demo application question

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#1686]
Please explain how background audio mode works in ExoPlayer demo video player:
When background is off and I get out of activity, video stream is stoped downloading.
Where background is on and I get out of activity, video and audio both are being downloaded in background?

**Comment by ojw28** [comment]
We're removing background support from the demo app in v2 because it's not a fully fledged solution (to do that you'd need to move the player to an Android [Service](https://developer.android.com/guide/components/services.html), which is quite a lot of work).

In the v1 demo app, if the video and audio are demuxed (as is the case for DASH and SmoothStreaming) then the player stops downloading the video component. If they're muxed then there's no way to avoid continuing to download both.

**Comment by dreich** [comment]
Thank you, friend!

I forgot to mention that I meant HLS.

**Comment by ojw28** [comment]
In HLS audio is typically muxed with the video, in which case there's no alternative but to download both with in the background. HLS does also support demuxed streams though, in which case the player would only download the audio. We recommend DASH for this use case, since supported streams are always demuxed.

**Comment by dreich** [comment]
Thanks.

**Comment by saurabhkpatel** [comment]
@ojw28 I am implementing background playback with a help of service, I already moved a player to the service, and when I press back I can hear only audio that's totally fine. But when I come to my video player activity then I am using "setBackgrounded(false)", which enables videoTrack back with help of this line in setBackgrounded function, "setSelectedTrack(TYPE_VIDEO, videoTrackToRestore);" Here I have created loaded activity again so I have new surface view and media controller, So I will setSurface again and MediaController.

Problem : I can only see black view with audio, instead of video with audio, Video frames are not rendering on surfaceView. why? Can you explain to me what other things I need to do to playback my video continuously when user come back to VideoPlayer activity?

In below code, I can see when I set true it will block surface and video rendering.
When I set false, it will render video but not surface, so I need to set surface again but I can see black view only.

  public void setBackgrounded(boolean backgrounded) {
    if (this.backgrounded == backgrounded) {
      return;
    }
    this.backgrounded = backgrounded;
    if (backgrounded) {
      videoTrackToRestore = getSelectedTrack(TYPE_VIDEO);
      setSelectedTrack(TYPE_VIDEO, TRACK_DISABLED);
      blockingClearSurface();
    } else {
      setSelectedTrack(TYPE_VIDEO, videoTrackToRestore);
    }
  }

Please help me to figuring out this issue.

**Comment by saurabhkpatel** [comment]
@ojw28 I figured out issue, issue was about to set visibility of shutterView.

I am having one more problem in the same approach, 

Problem : When I am returning to my video player activity I am setting surfaceView and setBackgrounded(false), but I can see video Frame got stuck for 2-3 seconds and then it starts continuously to play.

What could be the problem? Is there any order to set surfaceView and setBackgrounded(false) ?

**Comment by ojw28** [comment]
@saurabhkpatel - Please file a separate issue, including all of the information requested in the issue template. Closing this one.
