### ISSUE TITLE
Exoplayer seekto does not work for Vorbis audio on Android

### ISSUE THREAD

**Issue by kxun** [google/ExoPlayer#170]
We try to use exoplayer to play VP9+vorbis, when handle the seekto() we find the audio always reset to 0. Debug find that the MediaExtractor native code seems always returns 0 for the sampleTime after reset, is this a generic libarary supporting vorbis issue?

**Comment by kxun** [comment]
We end up with enforce key frames in the encoded webm video, which helps the situation but does not really solve it. Anyone experience similar issue and how do you solve it?

**Comment by vigneshvg** [comment]
More details:

When encoding vp9+vorbis, we enforce key frames every 5s to get the cues; what we observed is: if there is no audio, it works fine, vp9 video can seek exactly to any position; if there both video and audio (vorbis), the seek will reset to the cue point, so video bits will be dropped due to some check in TrackRenderer, and audio can be heard that starts from the cue point; then after the time gap between the cue point and seek position gone, video starts to show.

So the issue seems like: MediaCodecVideoTrackRenderer is discarding frames until the seek point whereas MediaCodecAudioTrackRenderer isn't.

**Comment by vigneshvg** [comment]
I did some digging and here is the behavior i see:

I created a VP9+Vorbis file with a VP9 key frame every 10 seconds. I created a simple app based on latest ExoPlayer dev branch (using the media codec renderers for VP9 and Vorbis). I seeked to 19 seconds as soon as the playback started.

Here's what happened:
  * The video track renderer seeked to 10 seconds, decoded all the frames from 10 through 19 and did not render them. The audio track renderer was idle when this was happening.
  * The audio track renderer seeked to 19 seconds. When the video track renderer start rendering frames at 19th second, the audio track renderer started rendering audio as well starting from the 19th
second.

That is working as intended and hence it seems like i cannot reproduce the issue you are having. Are you sure you are using the latest version of ExoPlayer from the dev branch?

**Comment by ojw28** [comment]
If it's an issue under MediaExtractor (likely) then it may only affect certain versions of Android.

- It would be interesting to know what version of Android you're running, and on what device, so that we can try and reproduce under matching conditions.
- In general we're trying to move away from depending on MediaExtractor, to avoid these kind of version specific issues. DASH playbacks already avoid using MediaExtractor (and support webm/vp9), so if it's feasible, you're much better off going down that path.

Thanks!

**Comment by kxun** [comment]
Appreciate the help, regarding the video file that repro the issue, I sent one copy to Vignesh. It happened to Android version 4 Samsung S4/S5 devices. We did not test them on latest Android 5 though.
And we also noticed that, if the video file does not have audio files, then they can always seek to the exact time position.

**Comment by ojw28** [comment]
One more question - When you see this, are you seeking before starting playback / at the start / during playback? Or does it not make a difference?

**Comment by kxun** [comment]
That does not make any difference. Whether it is a seek during playing back or seek to a position then click on play.

**Comment by kxun** [comment]
vigneshvg, you said it is working fine in your test, could you verify if your device is Android v21 or below. I  tried the latest version of exoplayer, only on devices of v21 the delay (video/audo out of sync) issue is gone. (but I have not tried the libvpx option)

**Comment by vigneshvg** [comment]
kxun, i did my testing in Android L, so it's device v21.

**Comment by ojw28** [comment]
As per my comment 6 above this one, we've been moving away from depending on the platform's `MediaExtractor`. You should now be able to use `ExtractorSampleSource` rather than `FrameworkSampleSource` to play this media, and you should find that this approach works correctly across all devices.
