### ISSUE TITLE
ExoPlayer continues to play a HLS embedded WebVtt when the Video has already ended (The webvtt's duration is longer than the duration of the video)

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#1703]
## Build Info:

-compile 'com.google.android.exoplayer:exoplayer:r1.5.9'
## Sample Url:

> https://cdn.curiositystream.com/system/Encoding/s3_ll_playlists/579215/pixeldust_thedangersofzika_eng_preview-d89004458cdf88c059b02170fa0bf009b6538acf_v4.m3u8
## The Issue:

When a HLS's embedded webvtt's duration is longer than the video's duration, the video stops at its end duration but Exoplayer continues to play the webvtt file.
This issue occurs only when the webvtt file is embedded in the HLS .m3u8 link but **does not occur** when the the webvtt file is added via the HlsRendererBuilder as a SingleSampleSource.

Kindly let me know how to resolve this issue. Thanks!

**Comment by ojw28** [comment]
I think this is working as intended. You're providing the player with various different streams of media of different lengths, and it's playing them until they end, which is what it's supposed to do. If it's not intentional that there's a minute of captions extending past the end of the video, then the content shouldn't include them.
