### ISSUE TITLE
is supporting hevc in android 4.4.4 ? 

### ISSUE THREAD

**Issue by mojjia** [google/ExoPlayer#1718]
ExoPlayer : 1.5.9
Android : 4.4.4, API 19
Device : set top box (broadcom chip)

I have tried to play hevc content.
in Android 5.1, ExoPlayer can play hevc content but can't play same content in Android 4.4.4.
Even Android MediaPlayer can play hevc content in Android 4.4.4.
What is the official android version that supporting to hevc in ExoPlayer ?

**Comment by andrewlewis** [comment]
The [Android Compatibility Definition documents](https://source.android.com/compatibility/cdd.html) specify for each Android version what formats devices must be able to decode.

Support for decoding H.265/HEVC streams has been required since Android 5.0 Lollipop.

Note that OEMs can support whatever formats they want above the minimum requirements of the CDD. So, for example, there may be devices running Android 4.4 builds that can actually decode H.265/HEVC, even though it's not required.

**Comment by andrewlewis** [comment]
@AquilesCanta suggested that this might be an issue with capabilities reporting. You could try stepping through the code in [MediaCodecUtil](https://github.com/google/ExoPlayer/blob/r1.5.9/library/src/main/java/com/google/android/exoplayer/MediaCodecUtil.java#L154) to see if there is decoder for MIME type video/hevc present on this device, and, if so, why it does not have the required capabilities on Android 4.4.
