### ISSUE TITLE
How to make exoplayer fullscreen in the recyclerview

### ISSUE THREAD

**Issue by ShikhaAndroid** [google/ExoPlayer#1745]
I want to make exoplayer fullscreen on orientation change. any idea how to do so.

**Comment by DexterChenLib** [comment]
any solution?

**Comment by ralphpina** [comment]
Can't you just have another version of the layout for landscape? Which has it's own `SimpleExoPlayerView`. Then when you rotate handle `onConfigurationChanged(Configuration newConfig)`. Here switch the `SimpleExoPlayerView` in the player. Make sure to keep track of the current position.

``` java
Timeline timeline = player.getCurrentTimeline();
if (timeline != null) {
    playerWindow = player.getCurrentWindowIndex();
    Timeline.Window window = timeline.getWindow(playerWindow, new Timeline.Window());
    if (!window.isDynamic) {
        shouldRestorePosition = true;
        playerPosition = window.isSeekable ? player.getCurrentPosition() : C.TIME_UNSET;
    }
}
```

Hope that helps some. All that might not be necessary if your `SimpleExoPlayerView` has `android:layout_width="match_parent` and `app:resize_mode="fixed_width"`. Then I would imagine it would just resize automatically. But make sure to take into account all the intricacies of Activity rotation, keeping state and what not. So some parts of the code above will probably be necessary.

**Comment by GeoffLedak** [comment]
To toggle a video to fullscreen, you can programmatically remove the SimpleExoPlayerView from your recyclerview and add it to a new fullscreen dialog after the device has been rotated.

A walk-through is available here: https://geoffledak.com/blog/2017/09/11/how-to-add-a-fullscreen-toggle-button-to-exoplayer-in-android/

You'd basically implement what is described in the above tutorial, except rather than executing the openFullscreenDialog() method when a button is pressed, you'd perform it during device rotation.

You'd also need to maintain a reference to the specific view inside of the recyclerview that the SimpleExoPlayerView should be returned to when the fullscreen dialog is dismissed.

Cheers!

**Comment by hafiz013** [comment]
dear @GeoffLedak , I submit already news issue your library combine with recycle view which you can reffer to this [link](https://github.com/GeoffLedak/ExoplayerFullscreen/issues/1). Please advice what should do or if you could do some tutorial on how to do exoplayer fullscreen (landscape mode when enlarge while shrink in portrait mode) in recycleview (container). thank you.

Note: Those who try to make container (recycleview) exoplayer could has problem when the video not stick to current position when scrolling.

**Comment by hafiz013** [comment]
@HydraChen , I also attach file full zip on how to create exoplayer in recycleview in that link above
