### ISSUE TITLE
How to turn off video renderering?

### ISSUE THREAD

**Issue by giangttpham** [google/ExoPlayer#1769]
I want to test the a feature of the ExoPlayer on an emulator, we need the regular data flow such as feed the input buffer and process the output buffer, but we don't actually need to see playback because it's really slow in the emulator's environment. Is there anyway I can turn off the video rendering part? I don't want to disable the track, I just don't want to show it. I started by setting the surface to null but that didn't work. Sorry I can't be anymore specific because this is an official project we're working on. Any help is appreciated.

**Comment by ojw28** [comment]
Which emulator are you using? I was under the impression ExoPlayer performs pretty well on the official emulator running a recent API level.

If part of the player slow when running on an emulator then I'd guess it's the actual video decode. In which case you're looking for a way to replace the video decoder with something that discards the input buffers and produces dummy output buffers (cheaply). I can't think of a way of doing this without modifying ExoPlayer directly. If you're willing to do make direct modifications, you could change MediaCodecTrackRenderer to call MediaCodec via an interface you define, and then create a dummy decoder implementation of that interface.

**Comment by giangttpham** [comment]
Thanks for the quick response. That's what we had in mind, I was just wondering there's already a way to do that I don't know about.

**Comment by giangttpham** [comment]
@ojw28  Just for some clarification, isn't the function releaseOutputBuffer() in MediaCodec is the one that's doing the rendering to surface and what's I'm supposed to modify?

**Comment by ojw28** [comment]
releaseOutputBuffer renders an already decoded video frame to the surface, and returns the output buffer holding it so that the MediaCodec can re-use it. I don't think you can remove just that call, if that's what you mean. A MediaCodec instance has a fixed number of input and output buffers (see the first diagram [here](https://developer.android.com/reference/android/media/MediaCodec.html)). If you just "stop releasing output buffers" then the MediaCodec wont have any free output buffers available to decode into. This will effectively block the decoder and hence the flow of data that you're trying to retain. Note also that it's unclear what the expensive computation is that you're trying to avoid. I would have thought decoding is the expensive part (i.e. between queueInputBuffer and dequeueOutputBuffer), not rendering (releaseOutputBuffer).

Either way, if you want the flow of data to remain unchanged, you probably need to replace the whole MediaCodec instance with a dummy implementation that you've written yourself.
