### ISSUE TITLE
Device does not provide a decoder - on everything (Android 5.1.1)

### ISSUE THREAD

**Issue by endlessmind** [google/ExoPlayer#1792]
Okey, so I was going to use the ExoPlayer for a simple app to play local mp4-file.
I've used it before to play live HLS-streams without any problem, but I couldn't get it to work this time.

I'm using the latest library and installed the latest demo on my device.
But all the demos just gives me "Device does not provice a decoder for _mime type_".
But if I go into my app that has the live HLS-streams, it works perfectly.

This is an example of the logcat when trying to play a local mp4 file.

```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(1, video/avc, -1, -1, 640, 360, 0, 1.0, -1, -1, null, 135502033, false, 1280, 720, -1, -1, -1)
at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:384)
at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:797)
at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:211)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(1, video/avc, -1, -1, 640, 360, 0, 1.0, -1, -1, null, 135502033, false, 1280, 720, -1, -1, -1)
at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:385)
... 11 more
```

I'm using a Sony Xperia Z1 running stock Android 5.1.1 if it's of any help.

**Comment by ojw28** [comment]
Can you provide a specific example of a sample video that causes this error (whether it's already listed in the demo app or not)? If you've added it to the demo app yourself, please specify how. Please also let us know specifically which version of ExoPlayer you're using ("latest" is ambiguous).

For what it's worth, the MediaFormat in the log above isn't what I'd expect to see for a regular MP4 file, because the maximum dimensions (1280x720) are set differently to the actual dimensions (640x360). This normally occurs for adaptive media only, which a regular MP4 file is not.

**Comment by endlessmind** [comment]
I just added a new sample-item to the Misc-list with the uri to a local file.
I get the same error on the default videos in the demo app.

This is the line that I added

```
new Sample("Random Local MP4 for testing",
    "/storage/sdcard1/DCIM/100ANDRO/MOV_0010.mp4", Util.TYPE_OTHER),
```

With "the latest" I mean the latest release, I downloaded it a few hours ago.
Version 1.5.10

I've tried rebooting my device. Checked in AIDA64 to see if the decoders somehow is gone, but they where all there. I'm totally stumped.

**Comment by endlessmind** [comment]
[A short video demo](https://youtu.be/XY5ewrBNgkE)
In the second app (the one that I mentioned earlier) I open a live HLS-stream from twitch.tv.
And as you can see, it works perfectly.

**Comment by ojw28** [comment]
Thanks. Please can you attach a full bug report (i.e. the complete output of `adb bugreport`) captured shortly after experiencing the error.

**Comment by ojw28** [comment]
Also, is your app (the one that works) using an earlier version of ExoPlayer? Do you know which, if so.

**Comment by endlessmind** [comment]
[buggy_exo.txt](https://github.com/google/ExoPlayer/files/448289/buggy_exo.txt)
Here you go.

Yes, the working app uses Version 1.5.0 of ExoPlayer.

**Comment by ojw28** [comment]
I think our caching of decoder information has led to a lack of useful information in that bug report! Please try disabling caching by modifying [this line](https://github.com/google/ExoPlayer/blob/r1.5.10/library/src/main/java/com/google/android/exoplayer/MediaCodecUtil.java#L121) from:

```
List<DecoderInfo> decoderInfos = decoderInfosCache.get(key);
```

to

```
List<DecoderInfo> decoderInfos = null;
```

Once you've build and installed the demo app updated to include this change, please take another bug report shortly after reproducing (which with any luck will show the root cause!).

**Comment by ojw28** [comment]
Hm, actually, it's not entirely clear that it will show the root cause after you do that. You might want to attach a debugger and work out why `getDecoderInfosInternal` in `MediaCodecUtil` is returning an empty list when called with `key.mimeType` set to `video/avc` (which I think it is doing)?

**Comment by endlessmind** [comment]
Okey,I'll do so. But it's must be on more cases than just with video/avc as it happens with all the other demos as well.

But I'll try to debug `getDecoderInfosInternal`
I've attached the new bugreport if you want to take a look at it anyway.

[buggy_exo_2.txt](https://github.com/google/ExoPlayer/files/448341/buggy_exo_2.txt)

**Comment by endlessmind** [comment]
Okey, so it tried to play a local mp4 and this is what I found.
So when it's looking for `video/avc` if returns 2 decoders:
`OMX.qcom.video.decoder.avc` and `OMX.google.h264.decoder`

Then it tries to find `audio/mp4a-latm` and it returns:
`OMX.google.aac.decoder`

Lastly, it tries to find `video/mp4`, but it returns no decoder for it, and that's when it gives the error.

I'm not sure what the last decoder should be called, but I can see that it checks
one named `OMX.qcom.video.decoder.mpeg4`

**Comment by ojw28** [comment]
It's probably easiest to try with the first test video in the demo app, since then we can reproduce and see exactly what you're seeing. The logs indicate the failure occurs trying to find the `video/avc` decoder. Note `video/avc` in:

```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(1, video/avc, -1, -1, 640, 360, 0, 1.0, -1, -1, null, 135502033, false, 1280, 720, -1, -1, -1)
```

Is it definitely returning a list containing two items for `video/avc`? If so, I don't understand why the failure occurs. Follow the stack up to `MediaCodecTrackRenderer.maybeInitCodec` and work out why it's throwing the error.

**Comment by endlessmind** [comment]
Okey, now I feel stupid. 
While trying to google the error earlier, I must have nicked some key and commented out a line 
in the `maybeInitCodec`. 
While recompiling the library, I blindly click "Yes" on "Do you want to save changed in MediaCodecTrackRenderer.Java"

Well, it all works now, thanks for pointing me back to my oblivious mistake unknowingly :P
Sorry for taking up your time with such a silly mistake :P

**Comment by ojw28** [comment]
:)
