### ISSUE TITLE
how to make more sample videos to test widevine?

### ISSUE THREAD

**Issue by wlc520123** [google/ExoPlayer#1798]
Exo player demo includes some samples to test widevine, e.g.WIDEVINE DASH POLICY TESTS(GTS), WIDEVIND DASH.
How can I make  more videos to add to the exoplayer for  widevine testing? e.g.
-1. How can I make videos that playback using widevine plugin?  What key or server url should I use?
-2. Which test points should be taken care?

**Comment by ojw28** [comment]
This question seems to be starting from a strange point (i.e. thinking there should be additional Widevine test vectors, without knowing what they should be), so it's unclear what the motivation is here really. Widevine created the current test vectors themselves, and so without information suggesting otherwise, I think it should be assumed that they cover the core use cases properly.

**Comment by wlc520123** [comment]
Maybe, I had a bad expression.
I'm trying to explain again here. 
Simply speaking, I want to make videos which playback using  widevine plugin in phones. But I don't know how to make this kind of videos from normal mp4/webm files.  

Same with the sample videos in exo player demo, just for testing, not really use for bussiness.

Thanks.

**Comment by ojw28** [comment]
Right, but why do you want/need to test something if you don't want to use it for any other purpose? It feels like there's little or no value in doing that.

I don't think there's really a bit difference between the path you'd take to produce test and production Widevine content. In fact, if you were using Widevine in production you'd explicitly want the test content to use the same path as the production content. I think you'd probably need to setup your own Widevine license proxy/server. We have test keys/policies/servers, but these are intended for our own test content, rather than being for arbitrary use.

**Comment by wlc520123** [comment]
Thanks very much.
How to setup the  Widevine license proxy/server?  
And how to make videos protected with widevine?

**Comment by ojw28** [comment]
that question is outside the scope of this issue tracker. My understanding is [Shaka Packager](https://github.com/google/shaka-packager) can be used to package Widevine protected content. I'm not sure about setting up a Widevine license/proxy server. I suspect that most people who have a need to do this take Widevine's [CWIP program](http://www.widevine.com/cwip/). Some streaming-as-a-service companies will do the hard work for you.
