### ISSUE TITLE
Do you accept 3rd party test vectors?

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#1812]
We have a fairly modern set of DASH test vectors at https://github.com/Axinom/dash-test-vectors and would be happy to submit a pull request that incorporates them into the ExoPlayer demo app. I thought I would check beforehand, though - is this something you would accept? No "policy reasons" to reject non-Google test vectors?

**Comment by ojw28** [comment]
For ExoPlayer V2, you can create and host a JSON file that defines your test vectors, as described [here](https://google.github.io/ExoPlayer/demo-application.html). You can then simply share a link to this file. Following the link on an Android device with the demo app installed (e.g. by clicking it in the browser or email client) will load your samples into the demo app.

I think we prefer this approach to having all third party test vectors loaded into the demo app by default. If we were to also provide a web page that has links to the files provided by all third parties, that would be very convenient for anyone wishing to try them out. Each third party would be free to update their test vectors by themselves, since it's just a case of modifying the JSON file that they're hosting themselves. What do you think?

Either way, we're definitely interested in being provided with 3rd party test vectors for our own internal testing, particularly if you can do so by defining them in the JSON format to make loading it super convenient for us ;).

**Comment by ojw28** [comment]
Note: If there's no alternative to your `X-AxDRM-Message` header then we can add an optional `drm_headers` field (or repeated `drm_header` field, or similar) to our JSON format for you.

**Comment by sandersaares** [comment]
This approach sounds good to me!

Yes, we would indeed need the ability to pass the X-AxDRM-Message HTTP request header. We will go ahead and make such a JSON file for our content as soon as this capability exists.

**Comment by ojw28** [comment]
The ability to specify headers has been pushed. The following example lists two of the Axinom test streams. If you host this file with a name ending in `.exolist.json`, then clicking a link to it on an Android device should open the ExoPlayer V2 demo app for your content (provided the demo app is installed).

```
[
  {
    "_comment": "Source: https://github.com/Axinom/dash-test-vectors",
    "name": "Third party: Axinom DASH test vectors",
    "samples": [
      {
        "name": "v7 (Clear)",
        "uri": "http://media.axprod.net/TestVectors/v7-Clear/Manifest.mpd"
      },
      {
        "name": "v7 MultiDRM SingleKey (Widevine)",
        "uri": "http://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "http://drm-widevine-licensing.axtest.net/AcquireLicense",
        "drm_key_request_properties": {
          "X-AxDRM-Message": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.4lWwW46k-oWcah8oN18LPj5OLS5ZU-_AQv7fe0JhNjA"
        }
      }
    ]
  }
]
```

We may establish a page containing links to test media provided by third parties, provided we get more than one of them! So please let us know if you host a file somewhere. Thanks!

**Comment by sandersaares** [comment]
Axinom playlist now referenced on https://github.com/Axinom/dash-test-vectors (https://raw.githubusercontent.com/Axinom/dash-test-vectors/master/axinom.exolist.json)
