### ISSUE TITLE
Smooth Streaming with PR fails playback For P7 and P8 with CryptoException

### ISSUE THREAD

**Issue by dobrusev** [google/ExoPlayer#1816]
Hi guys,

I'm trying to play SS with PR and it works fine untill it goes to the HD bitrates - P7 and P8.
Please see attached log file.
[logs.txt](https://github.com/google/ExoPlayer/files/469933/logs.txt)
This looks like a content/license issue but it will be good if I understand what exactly is the issue so I can come back to the content provider with that.
If you are interested further in this issue I can send manifest url and laUrl to the email.
The device that I was able to reproduce this is Sony BRAVIA 4K 2015 ANdroid 5.1.1, API22 with the latest ExoPlayer.

**Comment by ojw28** [comment]
It's hard to diagnose based on the information available in the logs. Decryption is failing but it's unclear why. We'd likely need a full bug report, test content and a working license server to reproduce the issue in order to investigate further. Please share this information here, or email it to `dev.exoplayer@gmail.com` if you prefer. If sending via email, please update this issue when sent so that we know to look for it; thanks!

As an aside, I don't know what "P7" and "P8" mean. They sound like details specific to your media to me?

**Comment by dobrusev** [comment]
Hello,

Sorry for the delayed answer.  
Changes in the license server were made and we can't see this error anymore.
Sorry if I wasn't clear P is for Playback Profile bitrates P7 - 4988000  and P8 - 8170000.

Thank you for your time on this.
