### ISSUE TITLE
Support fixed-width / fixed-height modes for AspectRatioFrameLayout

### ISSUE THREAD

**Issue by amosyuen** [google/ExoPlayer#1827]
I have a SimpleExoPlayerView in a RecyclerView. After loading a video, it has a height of 0 and so doesn't display any video, but you can hear the audio playing.

I've tested the same code in a normal activity and the height adjusts fine, and the video is viewable.

I'm using ExoPlayer v2.0.0 on Android v6.0.1

[bugreport.zip](https://github.com/google/ExoPlayer/files/474798/bugreport.zip)

**Comment by ojw28** [comment]
I don't think SimpleExoPlayerView does anything special. By default it's just `match_parent` for width and height. If you're trying to put the view into something that allows vertical scrolling then I think you need to set an explicit height on the view. Similarly, if you're trying to put the view into something that allows horizontal scrolling then I think you need to set an explicit width on the view.

**Comment by amosyuen** [comment]
Specifically my view is a vertical scrolling list, and the view has match_parent for the width and wrap_content for the height

Adding the height works, but then the video may not fit perfectly depending on the video aspect ratio. I would expect that the aspect ratio frame layout should automatically calculate the height based on the width?

**Comment by amosyuen** [comment]
Ok, so looks like the problem is that the wrap_content makes the height start out as 0, and AspectRatioFrameLayout then tries to calculate the width from the height of 0, which is 0. I think the expected behavior in a 0 height case would be to calculate the height from the width if the width is non zero.

I tested this out locally and that fix works. I've proposed a pull request. https://github.com/google/ExoPlayer/pull/1829

**Comment by ojw28** [comment]
I'm not sure the proposed solution is the right one. `AspectRatioFrameLayout` is intended to resize itself within the bounds available to it, not to resize itself in a way that causes it to exceed those bounds. Treating height==0 as a special case that's allowed to break this contract doesn't feel right to me.

Note also that since the aspect ratio of the video only becomes known asynchronously (once it's been parsed from the stream), the proposed solution would cause the view to resize itself, possibly when the user is interacting with the list, which is likely to be quite a janky experience. If there's an error loading the video then the aspect ratio will never become known and so the view will never gain height.

The best solution probably depends on what your use case is. If you're building something like the Facebook feed, for example, you'd probably want to put the video aspect ratio into the feed data returned from your server. That would allow you to size the views correctly up front, avoiding both the need for any asynchronous resize and the issue described here. If you're building something like a list of movie trailers, it would probably be reasonable to assume 16:9 and accept letter-boxing for wider-than-16:9-trailers. If you have some other case, perhaps neither of these apply.

If you could detail your exact use case, including where the data is coming from that you're using to construct your list of items, that would be good. Thanks!

**Comment by amosyuen** [comment]
The use case is similar to the "Facebook feed," users are uploading videos and I'm showing a list of the user videos. Because the user is uploading the video it may have different aspect ratios. We actually do get the aspect ratio beforehand, which I use so there is no jerkiness for us.

The problem I guess is that I want the AspectRatioFrameLayout to behave such that it fills the available space in one dimension (width) and calculate the other dimension (height) using the aspect ratio.

I could just calculate this manually since I have the aspect ratio data beforehand and then set the AspectRatioFrameLayout size to the calculated size, but then there's no point in using the AspectRatioFrameLayout since I've just reimplemented the AspectRatioFrameLayout behavior in an expanding manner in my recycler view.

**Comment by ojw28** [comment]
Got it. It sounds like we should enhance `AspectRatioFrameLayout` to support this case, but it should probably be something that's requested explicitly, rather than it being assumed if `height == 0`.

We should probably have a mode parameter that can be set to the current behavior (fit within bounds), or to one of two new modes: One that considers the width fixed and resizes the height (which is what you want). The other that considers the height fixed and resizes the width (for horizontal scrolling).

**Comment by ojw28** [comment]
@marcbaechinger - Is this something you'd be able to take a look at? Thanks!

**Comment by ojw28** [comment]
@amosyuen - You can now specify a resize mode on `SimpleExoPlayerView` or `AspectRatioFrameLayout` to achieve the behavior you need. You can do this either in layout xml or programatically. See the change linked above for details.

If you want to place the view into a vertically scrolling container (e.g. a list), you can do so in a way that allows the height to resize as required using:

```
android:layout_width="match_parent"
android:layout_height="wrap_content"
app:resize_mode="fixed_width"
```

For horizontal scrolling you'd use:

```
android:layout_width="wrap_content"
android:layout_height="match_parent"
app:resize_mode="fixed_height"
```

**Comment by amosyuen** [comment]
Awesome thanks!
