### ISSUE TITLE
SuppressLint("HandlerLeak")

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1830]
Dear colleagues,

While ExoPlayer library is providing to us (clients) excellent ability to stream different media contents, I have to notice that there are a lot of inner non static classes being used, some of them has annotation similar to:
`
SuppressLint("HandlerLeak")
`
What was a reason to suppress such warnings and use inner non static classes, opening a hole for the references leaks between inner and it's enclosing classes?

**Comment by ojw28** [comment]
A lot of lint warnings are warnings rather than errors because it's not possible to identify the case they're warning about in a way that avoids false positives. If there were a way to identify this kind of leak without false positives then it would likely be made an error rather than a warning.

In the cases you mention we do not believe there are unintentional leaks. The explicit suppression of the warning via an annotation is an indication that someone thought about it and decided this to be the case. If you know of specific cases where you believe we're preventing objects from being garbage collected that should be eligible for collection, please file an issue including details of the specifics. Thanks!
