### ISSUE TITLE
Audio not playing when only video codec specified in HLS manifest

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#1832]
When manifest for HLS contains codecs declarations and it only specify video codec - ExoPlayer plays video without audio.

`#EXT-X-STREAM-INF:BANDWIDTH=1200000,CODECS="avc1.66.30",RESOLUTION=1280x720,AUDIO="aac"`

Conflicted with  workaround in HlsChunkSource

```
// Sometimes AAC and H264 streams are declared in TS chunks even though they don't really
// exist. If we know from the codec attribute that they don't exist, then we can explicitl
// ignore them even if they're declared.
if (!MimeTypes.AUDIO_AAC.equals(MimeTypes.getAudioMediaMimeType(codecs))) {
   workaroundFlags |= TsExtractor.WORKAROUND_IGNORE_AAC_STREAM;
}
```

**Comment by ojw28** [comment]
It's a violation of the HLS specification for the `CODECS` attribute to omit the audio format. As stated in the [spec](https://datatracker.ietf.org/doc/draft-pantos-http-live-streaming/?include_text=1):

> If an EXT-X-STREAM-INF tag or EXT-X-I-FRAME-STREAM-INF tag contains
>    the CODECS attribute, the attribute value MUST include every media
>    format [RFC6381] present in any Media Segment in any of the
>    Renditions specified by the Variant Stream.

Note that even if the audio is fully demuxed, its format must still be included since the `EXT-X-STREAM-INF` tag specifies demuxed rendition (called `aac` in the case you provide).
