### ISSUE TITLE
Resolution Limit on Dash playlists

### ISSUE THREAD

**Issue by ccdunnyv** [google/ExoPlayer#1836]
This previous and unresolved issue appears to be related:
http://github.com/google/ExoPlayer/issues/491
- Videos with more than 1920x1080 (=1440x1440) pixels fail to play when part of a dash playlist. They play correctly via ExoPlayer as .mp4 (even fragemented .mp4)  but not when dashified. Audio plays in all cases.
- In ExoPlayer demo app, Widevine Dash: MP4, H264: Clear UHD (MP4, H264) does not play, sounds like it might be the same issue? Widevine Dash: MP4, H264: Clear HD (MP4, H264) DOES play. Curiously, Widevine Dash: WebM, VP9: Clear UHD (WebM, VP9) does play as well...
- Sending content via email - links to 4 versions of the same video: one .mp4 at 2048x1024 that plays, one dash .mpd at 2048x1024 that fails to play, one .mp4at 2000x1000 that plays, one dash .mpd at 2000x1000 that plays
  Note that 2048x1024 > 1920x1080 while 2000x1000 < 1920x1080, hence my hypothesis about this being a total pixel count issue. Note that I did try different aspect ratios as well, and they worked as dash playlists when below 1920x1080 total number of pixels and failed above it.
- ExoPlayer 1.5.8
- Samsung Note5, Android 6.0.1
- Having trouble uploading bugreport directly, here is a google drive link: https://drive.google.com/file/d/0B-LOUlV9HOdLWWJvOTdqYklib28/view?usp=sharing

**Comment by ojw28** [comment]
Please could you try with ExoPlayer 2.0.0. Format selection and filtering is implemented consistently across different types of playback, so I'd expect that you'll find the content doesn't play either as DASH or regular MP4 in that case. The demo app will also show you a toast indicating that the format is not supported, if that's the case. Either that or playback will work for both DASH and regular MP4.

If playback doesn't work and you see the toast, this is because the device doesn't advertise support for resolutions that high, so we're "doing the right thing" in that case. In V2 it's not too hard to override the selection and try and play the stream anyway, if you think you know better.

Note also that it's unusual to provide DASH content consisting of a single representation at a very high resolution. Is this actually a real use case? Why aren't there lower resolution alternates?

**Comment by knottb** [comment]
The current version for the demo player is Version 1.5.3 (which we are using). In our experience with this version of the demo player, UHD video will play, but not using DASH. HD will play using DASH, but not UHD.

We are experiencing similar results with our ExoPlayer build (v. 1.5.8)

Our use case is equivalent to providing different views on a given scene, where the user can choose the view. Because UHD would not play, we tested a playlist with a single UHD track, and the video will not play (however audio will). The phone is capable of playing UHD as ExoPlayer could play this track as a video without DASH.

(We are working on transferring our code to an ExoPlayer 2.0.0 build)

I should also note that we want this to be in DASH rather than an mp4 because in our specific application switching time is incredibly important.

**Comment by ojw28** [comment]
The post above appears to say exactly what the original poster says. I'm not sure there's any additional information, so my response above still holds. "Capable of UHD" isn't really well defined. What you really mean is  that the device is capable of UHD the exact way it's encoded in the videos you're playing, which isn't the same thing. If you're at or close the limit then the device may not advertise support (because it might not be possible to reliably determine whether playback will be successful or not).

Either way, as per the response above, please try using V2 (using the demo app is fine) and see what behavior is like with that.
