### ISSUE TITLE
RFC: Extending dash manifest with custom data

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#1838]
This is not a question with ExoPlayer per se but since I know there's a lot of DASH knowledge here I hope I can reach out for some comments.

We're looking for a way to embed custom data into our DASH manifests. Specifically for providing thumbnails for the clients. To me it feels like it would fit very well in the AdaptationSet model.

Consider something like this:

> ```
> <AdaptationSet id="10" contentType="image" mimeType="image/jpeg">
>      <Representation id="0" width="1280" height="720" framerate="100">
>          <BaseURL>http://cdn.example.com/c760d497c55344118cccfbe477e85315/dc806700ec1e4b33d0935f85a36bbf13/sprite_1280_720_100</BaseURL>
>      </Representation>
>      <Representation id="1" width="1920" height="1080" framerate="100">
>          <BaseURL>http://cdn.example.com/c760d497c55344118cccfbe477e85315/dc806700ec1e4b33d0935f85a36bbf13/sprite_1920_1280_100</BaseURL>
>      </Representation>
> </AdaptationSet>
> ```

The only bit that's perhaps a bit awkward is the framerate, which I use to retrofit information of how many thumbnails are encoded in the given jpeg.

We would use our own AdaptationSet id to identify the set and extract the data necessary. This seems to work just fine with ExoPlayer, however Shaka fails to handle the AdaptationSet while parsing the manifest. I'm trying to understand if this is a valid usage of DASH or if we should define our own app namespace in the XML and put the information under a custom element. Going with the latter I would definitely have to modify ExoPlayer a bit or somehow parse the XML a second time which complicates things a bit.

**Comment by ojw28** [comment]
> however Shaka fails to handle the AdaptationSet while parsing the manifest

I think a player should probably ignore an AdaptationSet that it doesn't know how to handle, or at least have the option of doing so. If Shaka is failing for this reason then you should probably open a bug on that project asking if it would be more correct for them to ignore it.

> I'm trying to understand if this is a valid usage of DASH or if we should define our own app namespace in the XML and put the information under a custom element. Going with the latter I would definitely have to modify ExoPlayer a bit or somehow parse the XML a second time which complicates things a bit.

The DASH spec is very permissive (most often you'll find that something is just not defined, rather than being explicitly forbidden). So it feels quite likely that you're not explicitly violating the spec. You'd have to convince yourself though; I didn't look in any depth. On the assumption that you're not explicitly violating the spec, I guess the remaining risk would be that handling of contentType="image" AdaptationSet elements could be defined in some future version of the spec or in the DASH interop guidelines, in a way that's different to what you've done.

Note that if you control server and client side (for all clients), then interoperability becomes less important. There's nothing forcing you to use XML style DASH manifests at all in this scenario. You could use your own binary format (e.g. for efficiency) and include whatever you like. If using ExoPlayer in such a scenario, the extra client work you'd need to do would be to parse your binary format into a DashManifest instance for the player (whilst also doing whatever else you want to do with additional data in the response). Injecting a DashManifest might be awkward (not possible?) in V2 right now, but we'll add that functionality back in as/when someone needs it.
