### ISSUE TITLE
Having both exoplayer v1 and v2 in the same app

### ISSUE THREAD

**Issue by makvasic** [google/ExoPlayer#1842]
This is more a question, rather then issue.

Is it possible to have both versions as stated [here](https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f#.pt2bspkbq)?

I see that v2 is published with same package name as v1, so I'm wondering if it's intentional and you decided not to go with the change?

It is also possible that I'm missing something obvious, please correct me if I'm wrong.

Cheers.

**Comment by ojw28** [comment]
Good question. The package name of the classes in the library _has_ been changed, which allows v1 and v2 to co-exist in an application. We have however published the library using the existing name, which I think is what you're referring to. This makes it awkward to include two versions of the library at once using gradle, which is probably what you're referring to. It is possible, according to [this post on stack overflow](http://stackoverflow.com/questions/29374885/multiple-version-of-dependencies-in-gradle).

This was oversight as much as anything. Internally we use a different build system, and so we didn't encounter this issue. We'll have a think about whether it makes sense for us to adjust things. For now, you can either try and instructions linked above, or you can just get v1 as a jar and include it directly, and reference v2 in your gradle file. The latter is probably the easiest approach, particularly since you'll likely want to freeze the version of v1 that you're using when you start also bundling v2, and since this is a transient state where you'll be removing v1 from future builds once you're satisfied that v2 is stable.

**Comment by makvasic** [comment]
Yes, thank you, I was talking about gradle.
Definitely agree, best way is v1 as jar and v2 via gradle until transition is made.
After reading a [blogpost](https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f#.pt2bspkbq) I was just expecting something like `com.google.android.exoplayer2:exoplayer:r2.0.0` and got confused in the process...

Thanks for clarification.

Gerat job with v2 it's pure gold :+1:

**Comment by blipinsk** [comment]
I had 2 projects that I wanted to migrate from ExoPlayer 1 to ExoPlayer 2 and really did not want to add ExoPlayer 1 as a jar (don't know why really :shipit: ...).

That's why I created [external packagings for all 1.x.x versions](https://github.com/blipinsk/ExoPlayer1).

No code of my own, just ExoPlayer 1 repackaged under different `groupId` and `artifactId`, so you can include both ExoPlayer 1 and ExoPlayer 2 with just two gradle dependencies.
