### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tonggang1308** [google/ExoPlayer#1855]
- Memory Leak.
- I modify the ExoPlayer demo app（r2.0.0）, let it to play local mp4 file. It is OK, it play very smooth. But, when exit the activity, the memory don't restore to normal level. Even though I force the GC, the memory is not released.
- The issue can be reproduced at many android device.

**Comment by philipgiuliani** [comment]
I have upgraded my own project to ExoPlayer 2.0 and even calling player.release() does not release any resources. I am streaming mp4 files.

After opening the player a second time with a mp4 file, it crashes with an OutOfMemory exception.

**Comment by ojw28** [comment]
Please can you provide more information on how this is reproduced in the ExoPlayer demo app?

When I exit the playback activity and force 2x GCs via Android Monitor in Android Studio, the memory level reliably returns to its base level (I'm unsure why 2x GCs are required, but that's more likely a property of how the GC works than of ExoPlayer).

Also, if you do multiple playbacks successively, does the memory level increase indefinitely? I would expect that to happen (eventually resulting in an OutOfMemory failure) if there were genuinely a leak. Please clarify. Thanks!

**Comment by tothvoj-gl** [comment]
Try simpleExoPlayerView.setPlayer(null); in your onDestroy() method.

**Comment by philipgiuliani** [comment]
I am using an instance of SimpleExoPlayer without the SimpleExoPlayerView. The memory drops a little bit when opening the next instance of a player. After 3-4 times it crashes because of OutOfMemory.

I have not tried the demo app, but thats how the memory graph looks in my application:

![leak](https://cloud.githubusercontent.com/assets/5446019/19029818/c0cb3556-8949-11e6-96cb-5b7211ea8aca.jpg)

The memory always increases, it never goes back.

``` java
 @Override
public void onDestroy() {
    super.onDestroy();
    releasePlayer();
}

private void releasePlayer() {
    if (mPlayer != null) {
        mPlayer.stop();
        mPlayer.release();
        mPlayer = null;
    }
}

@Override
public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
    if (mPlayer != null) {
        mPlayer.setVideoSurfaceHolder(null);
    }
}
```

Do i have to call something else?

**Comment by ojw28** [comment]
Please try with the demo app. Without further information, the memory leak you're seeing could be caused by anything in your application. A graph like the one above is not sufficient evidence the leak is ExoPlayer's fault.

As long as you're releasing the player and nulling the reference to it, that should be sufficient. You should do it before `onDestroy` though; doing it there is too late. You should be releasing resources in `onPause`, or `onStop` if the SDK version is 24 or higher. This is what the demo app does.

**Comment by ojw28** [comment]
We've pushed a change to `dev-v2` that will release memory proactively when `release` is called on the player.

Note however that you will only be experiencing this issue in the first place if you're leaking the player instance. We're unable to reproduce this problem in the demo app, and suspect that it's an issue in your own application code. You should work out where this leak is and fix it, since although our change will significantly reduce the size of the leak, the leak will still be there and you may be leaking other objects too.

**Comment by PerkmannM** [comment]
I'm experiencing the same problem with ExoPlayer 2.0.0 in my own project.
Due to this problem I created a new project with the most simple ExoPlayer setup, just to see if the memory still leaks.
And actually it really does.

This app provides four buttons with four different dummy .mp4 files.
By switching them continuously I managed to generate a memory graph like this.

In my opinion the player stops releasing memory after I included the controls.

Could you please check my project and tell me where my problem is?
Thank you!

![bildschirmfoto 2016-10-06 um 17 01 45](https://cloud.githubusercontent.com/assets/22675167/19184165/20f93182-8c7c-11e6-9ea7-0f87c54f01de.png)

https://github.com/PerkmannM/Demo-ExoPlayer

**Comment by ojw28** [comment]
Thanks for the very helpful reproduction steps. I've filed #1908 to track this issue. I'll also post a workaround there.

**Comment by akhilesh006** [comment]
Hi @PerkmannM , I am also facing the same issue with Google Media Framwork, It is internally using Exo Player 1.5.7. Could you please help me if you have resolved the issue as I couldn't track.
