### ISSUE TITLE
Local video playblack failure with Exo 2.0

### ISSUE THREAD

**Issue by hershlag** [google/ExoPlayer#1867]
I am trying to integrate with the new Exo 2.0 and I am having issues playing local videos. The videos are located in the raw assets folder. In attempting to create a new ExtractorMediaSource(mp4VideoUri, ...), if I use a FileDataSourceFactory then it complains of a FileNotFoundException when passing in the local URI, if I use the DefaultDataSourceFactory it complains about the HttpClient failing. I am not attempting to stream or download any videos, all videos will be local to the app. What is the recommended way for local video playback in the new Exoplayer 2.0?

Thanks!

**Comment by ojw28** [comment]
`DefaultDataSourceFactory` is the right thing to be using. It sounds like the `Uri` you're using isn't correctly formatted. Where _exactly_ is the asset located, and what `Uri` are you using to try and play it?

**Comment by hershlag** [comment]
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to android.resource://myapplicationid/2131165663

the asset is located under res/raw/video_1.mp4

When creating the DefaultDataSourceFactory what should I be passing into as the userAgent? Why is it trying to connect to a local resource?

**Comment by ojw28** [comment]
There's some terminology confusion here, because there's also an `assets` directory, which is different to `res`. See [here](https://developer.android.com/studio/projects/index.html):

> Contains file that should be compiled into an .apk file as-is. You can navigate this directory in the same way as a typical file system using URIs and read files as a stream of bytes using the AssetManager . For example, this is a good location for textures and game data.

This folder is generally suitable for media. If that works for you, place your file in that directory and use `DefaultDataSourceFactory`. The Uri should be of the form `asset:///video_1.mp4`.

If you really do need to use `res/raw`, then (1) why?, and (2) you can use the newly added `RawResourceDataSource` class. You'll need to make your own factory for it. You can build a suitable Uri using `RawResourceDataSource.buildRawResourceUri`.
