### ISSUE TITLE
Failed to receive STATE_END after dragging seek bar to end of video (HLS)

### ISSUE THREAD

**Issue by HSY229** [google/ExoPlayer#1897]
Launch ExoPlayer r2.0.0 Demo application,
(Samsun Galaxy S5)
press "HLS" button,
press "Apple 16x9 basic stream" button,
drag the seek bar to end of video,
(duration is 30:00, let current time to be 30:00).

`playbackState` is keep on `buffering` state.
`playWhenReady` is true.
`window` is 0.

But I expect to receive an event for `STATE_END`.

Related (kind of) to #596

**Comment by ojw28** [comment]
This is an interesting edge case. When a seek occurs to the end we always fetch the last chunk of each stream so that we can render the "end state" of the media. In this case demuxed subtitles are also enabled. The subtitles have a shorter duration than the video. This can result in the following happening on seek specifically in the case that there's already an ongoing load of a video chunk:
1. Seek happens. As a result we trigger async cancellation of the ongoing video chunk load.
2. We evaluate which streams we should trigger loads for next. Since we're immediately after a seek both video and subtitle streams are eligible, but we're still waiting for the video chunk cancellation to finish. Hence the subtitle chunk load starts. The video chunk load is deferred to be started when the asynchronous cancellation of the previous load completes.
3. The subtitle chunk load blocks waiting for the video load to start due to the nasty timestamp adjustment necessary for playback of HLS content.
4. The cancellation of the previous video load completes. We evaluate which streams we should trigger loads for next. At this point what should happen is that the video chunk load should start, but the subtitle stream now has a next load position that's earlier than the seek position was. As a result we conclude loading of subtitles is "behind" and that we should avoid loading anything else until it's caught up. The result of which is that we're stuck.

There are a whole bunch of ways we could fix this. TBC which one is best!

**Comment by ojw28** [comment]
Note - This issue only occurs for (a) HLS, (b) with demuxed subtitles enabled, (c) when playing media where the subtitles are shorter than the duration of the video chunks, and (d) when a video load is in progress when a seek happens. (d) is relatively likely given (a), (b) + (c), but that combination is probably fairly rare to start with. So it's not super high priority for us to fix, although regardless we'll get to it soon.

**Comment by HSY229** [comment]
Thanks for your help.

**Comment by lukechang0815** [comment]
seeing the similar issue too

**Comment by mrshih** [comment]
Have the same problem !

**Comment by ojw28** [comment]
@botaydotcom - I think a trivial way to fix this is to allow `CompositeSequenceableLoader` to always continue loading if a loader has `loader.getNextLoadPositionUs() <= positionUs`. Could you confirm this fixes the problem, and that there aren't any bad side effects I'm neglecting ;)? Thanks!
