### ISSUE TITLE
Minimizing Pre buffering time for VOD (MP4) File

### ISSUE THREAD

**Issue by MudasirBhutto** [google/ExoPlayer#1898]
Hi developers,

I am playing remote MP4 files in ExoPlayer. For short duration (like 5 to 10 minutes) MP4 files , time between buffering and ready state is less. But when I am trying to play files with duration more than (1 hour to 3 hours), time between buffering and ready state varies from 20 seconds to 60 seconds according to file size. I want to minimize this time to minimum 10 seconds even for bigger MP4 video files.  I am sharing few mp4 files URL.

http://www.pitelevision.com/vods/movies/PK.mp4 (Video Duration 2 hrs and 32 minutes,  time between buffering and ready state is 40 to 45 seconds)

http://www.pitelevision.com/vods/drama-serials/Zindigikimehek/Ep-02-Zindagi ki Mehek.mp4 (Video Duration 22 minutes,  time between buffering and ready state is 6 to 8 seconds)

Kindly tell me, how to minimize buffering state time  so that minimum buffer time should not be more than 10 seconds. What changes do I've to make in which parameters. Waiting for your reply.

Thanks.

**Comment by ojw28** [comment]
I only looked at the first stream. It starts consistently within a second for me. I think the only explanation for the delay you're seeing is because you have a much lower bandwidth connection.

The reason long duration MP4 files take longer to start is because they contain an sample index in the header at the start of the file. If you have a longer duration video there will be more samples, so the header will be larger. In the case of the first stream the index is about 5.5MB, so the player has to download at least that much data before it can start playback.

There isn't much we can do about that. If you control the media, you can choose a file format that's better suited to the combination of long duration, low bandwidth and fast startup. Specifically, fragmented MP4 (FMP4) distributes the index into smaller fragments within the file to avoid having a huge header at the start. I have a feeling Matroska and WebM do the same, but I could be mistaken.

**Comment by MudasirBhutto** [comment]
Thanks very much @ojw28. Yes, we do control the media, we will look into this issue in details. Can you suggest how to convert existing MP4 video files to FMP4 video files. Do we've to encode all of them again or what?

Thank you very much again.

**Comment by ojw28** [comment]
Packaging of content is outside the scope of this issue tracker. There are plenty of resources on the internet to help with that kinda thing, also!
