### ISSUE TITLE
Group level override for adaptive track selection list

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#1927]
Feature request.

As per the discussion here:  https://medium.com/p/119a2f18ecb7/info/oldest/all

It would be great to have a group level override so a full set of tracks (all representations in an adaptation set) can be set primary for adaptive selection.  Currently we are having to manually build up an index array and check the validity of each track.

**Comment by tonihei** [comment]
We will be closing this issue because there doesn't seem to be a good use case for the requested feature.

Selecting a track group (without specifying a particular track) should be equivalent to specifying a language preference for example. If there are more specific requirements which are not captured by the `DefaultTrackSelector.Parameters`, then having the app specify all tracks seems to be fine. Alternatively, a new feature request for a constraint parameter should be made.
