### ISSUE TITLE
Extractor for "pls" files

### ISSUE THREAD

**Issue by amarkovits** [google/ExoPlayer#1947]
I would like to play a pls stream (using ExoPlayer 2) but it seems that the default Extractors does not support the pls format.
Example of the stream: http://stream2.srr.ro:8000/listen.pls
Is there a way to play pls streams without having to write a custom extractor or to parse the url and get the link from the the file?

**Comment by ojw28** [comment]
It looks like 'pls' is a type of playlist file, rather than an actual media stream. If you download the example link and open it in a text editor, it consists of only the following:

```
[playlist]
NumberOfEntries=1
File1=http://stream2.srr.ro:8000/
```

The underlying stream `http://stream2.srr.ro:8000` plays back fine in ExoPlayer. So it should be possible for you to write a super simple parser for pls files that extracts the underlying stream and passes it to ExoPlayer. This is not something we'll be supporting directly, though, so you'll need to do it in your own application code.
