### ISSUE TITLE
Better handle device not decoding video stream quickly enough

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#1948]
Short: Here is the Android log

https://1drv.ms/v/s!AkhO6W-clkudtBxavDXzZ3uXMZaH

Tested on Nexus 5X, Android 7 (latest update).
## 

I tried demo app on latest release-v2 branch, play the "Tear of steel - Clear HD VP9". I will stops the playback at a random time (I test a couple times and it varies). I suspect it is another memory issue, so I check with Android Studio. My record has the length of 1m45, meanwhile the Video stops playback at about 45s. After I press back button to return, the memory usage doesn't change.

**Comment by ojw28** [comment]
I doubt this is a memory issue. You'd expect a memory issue to cause an out-of-memory failure and result in process death, rather than playback stopping at random. We'll take a look.

**Comment by marcbaechinger** [comment]
While I can repro this on Nexus 5x but it works on a Pixel phone. Not sure this is memory related.

Track: "WV: Clear HD (WebM, VP9)" of the category "Widevine DASH: WebM, VP9".

## Nexus 5X (Android 7.0)

Playback freezes when it tries to render the HD variant. When I restrict playback to the 720p variant by choosing only the smaller variant in the video track selector dialog, it plays fine. 

## Pixel (Android 7.1.1)

HD content plays fine. No issues.

**Comment by ojw28** [comment]
It sounds like the device just isn't capable of playing the 1080p variant at 1x speed. We attempt to filter streams that a device isn't able to play, but it's borderline impossible to get it right all of the time. There are multiple dimensions (resolution, bitrate, profile etc) to consider, and performance of software decoders can depend heavily on what else the device happens to be doing at the time. Even something like temperature can make a difference since it potentially affects CPU throttling.

Going forward, we probably need to start thinking about dynamically tracking whether the device is keeping up, and switching back to a lower quality automatically if not. This will also help automatically drop quality in cases where the playback rate is increased beyond the rate at which the device can decode.

**Comment by eneim** [comment]
I think with the net condition of 20Mbps, Nexus 5X performance, it is hard to believe that It could not be able to perform well on 10000Kbps 1080p. But I hope you were right.

**Comment by ojw28** [comment]
This is unrelated to your network connection. It's to do with the processing capability of the device + decoder. Decoding 10Mbit/s VP9 using a software decoder, which is what will happen on Nexus 5X, is very computationally expensive. IIRC Pixel has a hardware VP9 decoder, so will perform much better.

It should also be noted that 10Mbit/s is excessive for VP9 at 1080p. According to Netflix 5.8Mbit/s is sufficient for excellent quality 1080p streams, and that's using H.264. From memory, I think VP9 is supposed to save ~30% for equivalent quality, so 4Mbit/s should be sufficient. I'll follow up internally to find out why the streams in question are encoded at such a high bitrate.

**Comment by eneim** [comment]
@ojw28 Nice explanation. I missed the VP9 with the previous generation (VP8, AVC, ... lineup) obviously ... handling VP9 should be equal to that of HEVC, which is not trivial. Hope to hear good news.

**Comment by iponkan** [comment]
@ojw28 Can i set less quality output to achive 4x palyback spped? If can,what i suppose to do? #3027

**Comment by ojw28** [comment]
If the media contains video at multiple resolutions (e.g. because it's adaptive DASH, HLS or SmoothStreaming content) then this is something we intend to look into. If the media is non-adaptive (e.g. a regular MP4 file) then no; that's just not how video codecs/decoders work.

This issue is open because we're still looking into various options for better handling this case. We do not have a recommended solution at this time.

**Comment by iponkan** [comment]
@ojw28 Thanks a lot.hope you guys have good solution on it.look forword for it.

**Comment by ojw28** [comment]
Behavior for this case was much improved in 2.6.0. The relevant entry in the release notes is:

> Better playback experience when the video decoder cannot keep up, by skipping to key-frames. This is particularly relevant for variable speed playbacks.

@andrewlewis - This can probable be closed at this point, or duped if there's a still open issue tracking further improvements. Note one idea hinted at in this thread is to automatically switch down to a lower quality if the playback is adaptive. Might be something to add to the list of possible further improvements in this area.

**Comment by andrewlewis** [comment]
Yes, switching down adaptive playbacks if decoding can't keep up is on the list. Thanks.
