### ISSUE TITLE
Mute video change player state to ended

### ISSUE THREAD

**Issue by HugoGresse** [google/ExoPlayer#197]
I'm using switching of audio track when I need to mute/unmute : `player.selectTrack(FullPlayer.TYPE_AUDIO, -1);`

In my app I need to swap the videoSurface to another one depending if I'm on fullscreen or not. So if I mute the video and exit fullscreen, I change the surface attached to the player and play the video after. 
Everything is working fine but when exit fullscreen while muted, the video state change to Ended state. 

I not sur it's an exoplayer bug or implementation issue.

**Comment by ojw28** [comment]
I think the video renderer probably was being disabled internally, which would have led to both audio and video renderers being disabled simultaneously, and hence a transition to the ended state. We've recently updated the logic in DemoPlayer and MediaCodecVideoTrackRenderer so that this doesn't happen, and so the issue should be resolved. The relevant change is here: https://github.com/google/ExoPlayer/commit/61a86295fd3c798e24083acd228d11f832770b68
