### ISSUE TITLE
Add support for container format sniffing in HLS

### ISSUE THREAD

**Issue by jschm1** [google/ExoPlayer#2025]
For the HLS stream below, ExoPlayer fails to display subtitles:  

http://drod05p-vh.akamaihd.net/i/all/clear/download/bd/58049ebc6187a40d7cea30bd/Hammerslag--1-10-_5d30d8de7cab45628de5820ac0d965cc_,309,502,956,2059,2880,.mp4.csmil/master.m3u8?cc1=name=Dansk~default=yes~forced=no~lang=da~uri=https://www.dr.dk/mu/subtitles/playlist/urn:dr:mu:manifest:58049ebc6187a40d7cea30bd?segmentsizeinms=60000%26subtitleType=HardOfHearing

When played in Safari on Mac OS, subtitles are displayed correctly for this stream. 

ExoPlayer seems to recognize the available subtiles and lists them in the subtitle-selection-dialog displayed when clicking the "Text" button. However, selecting the subtiles "da, id:Dansk" and clicking "OK" does not activate the subtitles. No errors are printed in logcat.

ExoPlayer version: DemoPlayer 2.0.4
Devices tested: HTC One m9 & HTC 10
Reproducible every time.

**Comment by AquilesCanta** [comment]
The reason behind this bug is that the vtt segments don't have a .vtt/.webvtt extension. This means that the stream does not get past preparing state for V1. 

I couldn't find any constrains over the extension of the segment URIs in the spec so this is an actual bug. For the time being, if you can rename the webvtt segments so that they end with .vtt, that will fix the issue for you.

**Comment by jschm1** [comment]
Thanks for quick response.
Adding a .vtt extension seemed to do the trick.

**Comment by ojw28** [comment]
Support has been added to 2.9.0.
