### ISSUE TITLE
Tracking information recovered from exoplayer activity

### ISSUE THREAD

**Issue by replystreamingwidevine** [google/ExoPlayer#2028]
Hi all,
We are trying to monitor every streaming session in our app, in order to track (sending data to our server) as much information as possibile about the exoplayer activity. 
We are using MPEG DASH streams and the exoplayer version is 1.5.8.

We would like to track:
•	when the exoplayer increase or decrease the streaming quality (when the player choices a different <Representation>, in an adaptive mode state), tracking the "bitrate layer" selected.
•	the start and end time of every re-buffering event (when player is stopped to fill his empty buffer)
•	detailed information about manifest download
o	manifest size (bytes)
o	manifest download duration (millis)
o	response code (200, 500 … ) of the http request for the manifest 
•	detailed information about every chunk download
o	the layer (<Representation>) the chunk belongs to
o	the remaining buffer size (in seconds)
o	frame per second decoded
o	chunk type (video, audio, text)
o	chunk index
o	chunk full url
o	chunk size (bytes)
o	chunk download duration (millis)
o	http response time (the time elapsed between the start of the request and the arrival of the first byte of the chunk)
o	the IP address of the edge server
o	response code (200, 500 … ) of the http request for the chunk 

There is an easy way (without modifying the exoplayer internal code) to get this kind of information?
thanks in advance

**Comment by ojw28** [comment]
`EventLogger` in the demo app is already a good example of a class that's registered to receive a whole bunch of internal events from the player, so you should take a look at that as a starting point.  Note that in ExoPlayer V2 quite a bit of extra useful information is propagated to `EventLogger`, so if you're really keen on getting as much information as possible then you should think about migrating.

**Comment by replystreamingwidevine** [comment]
Hi ojw28, thank you for the answer. I saw EventLogger demo class but I can’t migrate to V2.
I’m using 1.5.8 exoplayer version, and I’m tracking some informations returned from ExoPlayer.Listener and some Listeners like BaseChunkSampleSourceEventListener, etc.
Actually, the BaseChunkSampleSourceEventListener callback:

void onLoadCompleted(int sourceId, long bytesLoaded, int type, int trigger, Format format,long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs);

returns some information about chunk downloaded, but nothing about:
o the layer (<Representation>) the chunk belongs to
o the remaining buffer size (in seconds)
o frame per second decoded
o chunk full url
o bitrate
o chunk position

Is there an easy way (without modifying the exoplayer internal code) to get these informations?

**Comment by ojw28** [comment]
> the layer () the chunk belongs to

It's unclear what "layer" means here. You get a `Format` via `onLoadCompleted`. Does the `Format.id` provide what you need?

> the remaining buffer size (in seconds)

You can use `ExoPlayer.getBufferedPosition` (subtract the current position to get the buffered duration).

> frame per second decoded

It's unclear what this really means, or what it's for. On average the frames per second decoded is going to be identical to the frames per second of the format.

> chunk full url

The original url is available in V2. It's not available in V1. It shouldn't be surprising that updating to a newer version gets you more functionality ;). Also reporting the redirected url is tracked by https://github.com/google/ExoPlayer/issues/2054 and will be a V2 only feature.

> bitrate

If you're talking about the bitrate of the stream, then same response as for "frame per second decoded" as above. If you're talking about the actual available bandwidth, if you're instantiating a `DefaultBandwidthMeter` then you can pass a listener to it in order to receive bandwidth estimates.

> chunk position

It's unclear what this means. `onLoadCompleted` receives start and end media times for the chunk.
