### ISSUE TITLE
License lifetime handler

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2032]
Dear ExoPlayer team,
I am facing an issue with ExoPlayer when License expired during playback or during period when playback is on pause.
In first case there is "MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded".
In seconds one there is "com.quickplay.google.android.exoplayer.drm.KeysExpiredException".
This is a little bit user unfriendly behavior. User have to restart playback once again in order to trigger all the flow in the DrmSessionManager implementation.
My question is next - do I miss something in ExoPlayer in order to handle this situation?
I was hoped to relay on "HttpMediaDrmCallback"and it's method "executeKeyRequest".
I expected that this callback will be invoked once new license needed during playback, but I was wrong.

Any thoughts about this issue?
In worst case, I have to keep track on License expiry date from application side by some kind of scheduler, but it would be much more convenient to relay on ExoPlayer.

Thanks in advance.

**Comment by ChernyshovYuriy** [comment]
Additional question that I have.
Can keys be loaded (re-loaded) within the same session?
For instance, by implement some kind of timer that trigger "doKeyRequest" of the StreamingDrmSessionManager once license going to be expired during playback?

**Comment by ChernyshovYuriy** [comment]
Ok, for those who interested - it is possible to re-load keys during playback for the same session, this is good news.
Now, back to original question, will it be ever supported by ExoPlayer?

**Comment by ghost** [comment]
This seems like a drm configuration problem rather than a fault with the player.   You should perhaps look at increasing the licence duration to something typically longer than an average viewing session or look at implementing the licence renewal feature offered by widevine

**Comment by ChernyshovYuriy** [comment]
I could be agree to some degree, but it is more then possible that license duration can be several hours (in case of sport event streaming, for instance) and then instead of reload license during stream, in current implementation on ExoPlayer, a channel is simply fails to play.
I am not saying that it is hard to implement, in fact, our own implementation of DrmSessionManager handles it well, but do you guys think that this is 100% a case that must be addressed from client side?

**Comment by ojw28** [comment]
Is this for streaming? If so then I agree this sounds like a (server-side) configuration issue. You can configure a license policy in a way that will cause the `MediaDrm` session to generate an `EVENT_KEY_REQUIRED` periodically before the current keys expire. Each time this event is fired `StreamingDrmSessionManager` will perform a new request, which will then obtain keys valid further into the future.

It's quite common for services to issue keys that are valid for durations far _less_ than the duration of a typical viewing session, and rely on the behaviour described above to have the client periodically obtain fresh keys during playback. For example a movie service may configure their license policy so that keys are valid for 5 minutes, with `EVENT_KEY_REQUIRED` fired every minute. The client will obtain fresh keys every minute and hence the keys it currently has will always be valid for between 4 and 5 minutes into the future under normal operation. If a request fails it will retry a minute later, and it will get 3 further chances before the current keys finally expire and playback fails. This approach allows for an indefinitely long viewing session, whilst also allowing the service provider to revoke the client's access pretty quickly.

If you have a Widevine contact, you'd be best off reaching out to them to get more information about how to configure licenses in the way described above. I think "renewal delay" might be what you're looking for, but I'm not certain. Alternatively, it might be obvious now you know roughly what to look for ;).
