### ISSUE TITLE
Audio artifacts/noises (and video stucks) if audio going through heavy processing

### ISSUE THREAD

**Issue by Kexiliu** [google/ExoPlayer#2045]
To whom it concerns, 
I noticed that if I perform heavy audio processing (we're doing heavy post audio processing from native layer) in handleBuffer function in Audiotrack.java, it starts to produce audio artifacts/noises (and video stucks). 

An easy way to reproduce the problem is that, just before this line in handleBuffer:
bytesWritten = audioTrack.write(temporaryBuffer, temporaryBufferOffset, bytesToWrite);
Add these lines:

```
ByteBuffer.wrap(temporaryBuffer).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(shorts);
	     for(int j = 0 ;j<40;j++){
	    	 for (int i=0;i<shorts.length;i++) {
		    	  shorts[i] *=.9;
		      }
	     }
byte[] bytes = new byte[shorts.length * 2];        
ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(shorts);
bytesWritten = audioTrack.write(bytes, temporaryBufferOffset, bytesToWrite);
```

If possible, can you please give me a pointer of what to do to avoid audio artifacts/noises with heavy audio processing? Or is this the right place to do heavy audio processing?

Thank you very much in advance, we've been stuck in here for several long days :)

**Comment by Kexiliu** [comment]
An even easier way to trigger this issue is that:

In AudioTrack.java, handleBuffer function, right before this line:
`bytesWritten = writeNonBlockingV21(audioTrack, buffer, bytesRemaining);`

Add:

```
      byte[] b = new byte[buffer.remaining()];
      buffer.get(b, 0, b.length);
      ByteBuffer bufferNew = ByteBuffer.wrap(b);
      bufferNew.position(0);
      bytesWritten = writeNonBlockingV21(audioTrack, bufferNew, bytesRemaining);
```

All i did was to convert buffer to array, and convert it back to bytebuffer and write to audioTrack. When i run the app, I hear the audio noise and video is faster... Is this the right place to change audio bytebuffer?

**Comment by ojw28** [comment]
This issue tracker is for issues with the library. We don't have bandwidth to debug your own customizations; sorry. It's your responsibility to make sure you implement customizations correctly and to resolve any issues with them.

That said:

Note that there is no guarantee `audioTrack.write` will actually write all of the data passed to it. That's why it returns the number of bytes written. It's quite likely you're accidentally applying your processing multiple times to the same audio in the case that it doesn't fully consume the data. `handleBuffer` is documented in detail (in V2 at least) explaining the contract and that the same `ByteBuffer` might be passed multiple times in the case that the data is not fully consumed.

In the "easier way" described above, the code is invalid because it will always advance the position of `buffer` by `remaining()`, even though fewer bytes might be written to the underlying platform AudioTrack. If fewer bytes are written, you've advanced the position too far, since the contract of `handleBuffer` is that the position is advanced by the number of bytes that were written successfully.
