### ISSUE TITLE
ExoPlayer 2 Subtitle Control Codes

### ISSUE THREAD

**Issue by bit101** [google/ExoPlayer#2070]
I'm having issues with scrambled subtitles. This MAY be a duplicate of this issue: https://github.com/google/ExoPlayer/issues/1304 but I think it is different.

The particular stream in question is here: https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream.m3u8

To reproduce this issue, add this stream to the streams in the demo exo player from this repo and play it.

There are a few episodes in that stream. Some of them work fine. The subtitles in the Rick and Morty episode get scrambled. 

This stream works fine in various other players, including the Adobe-based Android player. One thing I noticed while playing it in that player is that the subtitles will be positioned at various locations on the video. i.e. if two characters are talking, the captions will be placed near each character's position to show who is seeking. But in the Exoplayer, all captions are centered at the bottom of the video. My suspicion is that the control characters for positioning the captions are not being parsed correctly and putting the caption buffer in a broken state.

The parts of the stream that work fine in Exoplayer do not seem to put the captions in different places in the Adobe player. The parts that are broken in Exo show positioned captions in Adobe. So I suspect this may be the issue.

**Comment by bit101** [comment]
In further research, I've realized that 608 doesn't actually allow positioning of specific titles. Only 708 does. That's likely the issue.

**Comment by zsmatyas** [comment]
608 supports positioning by Row and Column indexing. It is just not implemented in ExoPlayer. See: https://en.wikipedia.org/wiki/EIA-608#Non-Caption_Data
search for "row position indicator" and "tab offset".

These patches should work for ExoPlayer 1.x: https://github.com/google/ExoPlayer/pull/1312/commits
You can refactor these to 2.x easily.

**Comment by ojw28** [comment]
Yes. We don't expect lack of positioning support to cause this kind of issue though.

@bit101 - When you see the captions becoming corrupted, do you find that toggling the text track off and on again resolves the corruption? I think I'm seeing this. 608 is stateful. I suspect the problem is that this stream is really multiple videos separated by #EXT-X-DISCONTINUITY tags, that we need to flush the 608 decoder state when the discontinuity tag is encountered, and that we're not doing this.

**Comment by bit101** [comment]
@ojw28 I'm not working on that app at the moment, but I'll pull it up some time today and try "turning it off and back on again" :) And let you know the results. Thanks for the attention.

**Comment by ojw28** [comment]
I've been unable to reproduce this with the latest from `dev-v2`. It's quite hard to tell whether I've just been lucky or whether the issue is resolved there. Also, the live stream currently seems to be displaying only a static image. Please test using latest `dev-v2` and report back.

As an aside, the server providing this stream seems unable to serve it (to me in the UK at least) fast enough, so the player frequently has to pause and buffer.

**Comment by ojw28** [comment]
We've made some further changes in `dev-v2` around 608 handling, including positioning and some styling support. I'm not able to reproduce this issue any more.
