### ISSUE TITLE
Where to listern video current position change.

### ISSUE THREAD

**Issue by lipangit** [google/ExoPlayer#2090]
In demo I can see a handler postDelayed(updateProgressAction), This is not elegant, and easy to get wrong.

Where to listern progress changed in any listener?

**Comment by ojw28** [comment]
Well, someone has to be posting (or similar) to generate position updates. You're effectively stating that this code should be implemented by ExoPlayer rather than in client code, however logically it's the client that knows the points at which it wants a position update, which may be non-periodic, periodic, periodic at different rates for different pieces of the client etc. Hence it makes sense for the client to be in charge of generating any events that it needs. It's really not that hard or error prone to trigger an event at periodic intervals. The application developer is free to implement it in whatever way they want, if they think some alternative approach is clearer ;).

Note also that ExoPlayer V2 does a lot more for you than V1 does, so if you're looking for an easier API you should probably think about migrating.

**Comment by lipangit** [comment]
I am on branch r2.0.4, I will getCurrentPosition like you.

**Comment by stanmots** [comment]
> logically it's the client that knows the points at which it wants a position update

What if the client just wants to listen to the video current position updates? Constantly checking `getCurrentPosition` (e.g. with the help of `Timer().scheduleAtFixedRate`) is a very inefficient solution. IMHO, it would be great if ExoPlayer had a specialized method for this, somethings like `setCurrentPositionListener` which the developers could use to get notified about the video position changes. 

Since the player manages its own `getCurrentPosition` property it already knows when to emit `onPositionChanged` events. The client can only use the polling technique for this.

**Comment by ojw28** [comment]
> Since the player manages its own getCurrentPosition property it already knows when to emit onPositionChanged events

The player updates its internal position at a very high rate, because this is required for media playback. I doubt you'd want to be spammed with an event every 10-20ms.

> Constantly checking getCurrentPosition (e.g. with the help of Timer().scheduleAtFixedRate) is a very inefficient solution. 

I'm not really sure what this means. You should just query it at exactly the rate you want (e.g. every second). It's in no way inefficient (although I doubt `Timer` is the right thing to use here; `Handler.sendMessageDelayed` seems more appropriate).

**Comment by stanmots** [comment]
>  I doubt you'd want to be spammed with an event every 10-20ms.

Thank you for the quick reply and the explanation. I could use RxJava's `throttle` method to set the required rate though. 

> I'm not really sure what this means. 

I said it is "inefficient" because I thought about the case when the player is stopped and the client continues polling the current position. So the developers also need to monitor the player's stopped states to cancel the timer or remove handler's delayed messages, right?

> although I doubt Timer is the right thing to use here

`Timer` was used just as an example. However, I'm curious, why do you think `Handler` is more appropriate here? Is it related to the code style or the performance?

**Comment by ojw28** [comment]
> I could use RxJava's throttle method to set the required rate though.

Ok, but at this point your request is basically equivalent to asking that we poll you every 10-20ms so that you can ignore us 99% of the time. This is far less efficient than just posting something to yourself to perform updates at the rate you actually need.

> I said it is "inefficient" because I thought about the case when the player is stopped and the client continues polling the current position. So the developers also need to monitor the player's stopped states to cancel the timer or remove handler's delayed messages, right?

You could do that, and it wouldn't be particularly hard, yes.

> Timer was used just as an example. However, I'm curious, why do you think Handler is more appropriate here? Is it related to the code style or the performance?

Search "Timer vs Handler Android" or similar on Google, and you'll probably find that consensus is to use Handler. Aside from any pros/cons, Handler is the "Android way".

**Comment by lipangit** [comment]
Onlookers :)
