### ISSUE TITLE
Adaptive Audio

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2100]
Dear ExoPlayer team,
I have probably "obvious to answer" question.
Does ExoPlayer v1 and v2 supports adaptive audio stream the same way it does for video in case of HLS and DASH? I assume it does, but I need to be 100% sure.
If it does, how algorithm correlates with video adaption, because obviously audio bitrate is much less then video ones?

**Comment by ChernyshovYuriy** [comment]
Quick investigation DefaultDashTrackSelector.java from v1 and DefaultTrackSelector.java from v2 shows that Audio adaptive stream is not supported by default. Client of ExoPlayer have to implement it in its own.
Please confirm / or un-confirm my statement.

**Comment by ojw28** [comment]
We keep audio fixed and adapt the video only. It would be possible (but more complicated) to adapt both at once. In V2 you could do this through implementing a custom `TrackSelection`. We may support this directly at some point, since being able to adapt audio at the same time as video is pretty important for countries where low bandwidth connections are common. We don't have any short term plans, however.

**Comment by ChernyshovYuriy** [comment]
Thanks for info.
