### ISSUE TITLE
v2: HLS live streaming getCurrentPosition can not get correct time position

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#2118]
HLS live streaming getCurrentPosition can not get correct time position, not  increase，only playback hls live stream
ExoPlayer dev-v2 latest code
demo have same problem
dev-v1 work well
![device-2016-11-29-165550](https://cloud.githubusercontent.com/assets/1675131/20703016/037920ec-b655-11e6-87a2-567dcd7e8102.png)

test stream: https://hls.shou.tv/USCA01/583d3410cc45596c7b711ba1/live.m3u8

**Comment by crossle** [comment]
if test link invalid, plz tell me, resend a link

**Comment by ojw28** [comment]
This is an intentional change that is part of adding support for seeking in HLS live, and brings the reported position in line with DASH and SmoothStreaming. `getCurrentPosition` reports the position within the current seek window. Since the seek window is itself moving with time for a live playback, the position will not increase indefinitely. You can read about timelines, windows and periods [here](http://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/Timeline.html).

If you want a time that increases indefinitely then you want the time relative to the start of current period, rather than the current window. You can calculate this in several ways using the `Timeline`, one of which is:

```
long position = player.getCurrentPosition();
// Adjust position to be relative to start of period rather than window.
Timeline currentTimeline = player.getCurrentTimeline();
if (!currentTimeline.isEmpty()) {
  position -= currentTimeline.getPeriod(player.getCurrentPeriodIndex(), period)
      .getPositionInWindowMs();
}
```

Where `period = new Timeline.Period()` is a holder object that you probably want to allocate once and re-use.

**Comment by crossle** [comment]
Thank you

**Comment by aarondib** [comment]
@ojw28, thank you!
However, why position is always starting from 40000 - 70000 ms, rather then 0 ms?
How can we get this starting offset to calculate real time position, as it was in v2.0.2?
