### ISSUE TITLE
Playing YouTube video by using YouTube api with ExoPlayer v2

### ISSUE THREAD

**Issue by Mihuilk** [google/ExoPlayer#2160]
Hi.
I can't find any information about playing YouTube videos with ExoPlayer. I see on demo example app that there is some "YouTube DASH" examples to do so, but on real live there is no legal way to fetch source link of YouTube video.I know there is [YouTube Android Player API](https://developers.google.com/youtube/android/player/) that allow to play video by passing video id. I'am not sure but I think YouTube Android application use ExoPlayer inside it. I would like to stream video from [YouTube Api](https://developers.google.com/youtube/)  but by using ExoPlayer instead of  [YouTube Android Player API](https://developers.google.com/youtube/android/player/). It's possible to stream videos on ExoPlayer by using YouTube Api?

**Comment by ojw28** [comment]
It's not possible to obtain direct links to YouTube videos for playback by ExoPlayer. YouTube's Android Player API is the officially supported way of playing YouTube videos in Android applications.

**Comment by rpattabi** [comment]
Coming here after the watching excellent presentation at Google I/O 2017. Unfortunate to hear the need to use different player to stream youtube videos. This is irony since youtube app is internally using ExoPlayer. Hope Google/Youtube avoids such duplicated efforts. A YoutubeMediaSource will save the developers having to familiarize yet another media player API.

**Comment by TGIO** [comment]
regarding to Google I/O 2017. When/where will new features be pushed? Interested in ImaAdsMediasource especially.

**Comment by ojw28** [comment]
* The IMA MediaSource has been pushed to our `dev-v2` branch [here](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ima). Please note the "known issues" section of the README. It will take a bit of time before it lands in a stable release because those issues still need to be ironed out.
* @rpattabi - ExoPlayer and the YouTube API are pretty different things. I wouldn't say it's duplicated effort. In particular I think YouTube's API uses ExoPlayer internally, and so it's more that YouTube's API is providing a higher level functionality. This is necessary because YouTube has monetization and analytics reporting requirements. I doubt it would be possible to enforce those requirements in a `MediaSource` implementation. In particular, ExoPlayer is so open I suspect it would be fairly trivial for someone using such an implementation just to remove all ads, which would make content producers who've opted to monetize their content on YouTube pretty unhappy.
