### ISSUE TITLE
ExoPlayer 2.x Upgrade Guide

### ISSUE THREAD

**Issue by halibegic** [google/ExoPlayer#2170]
Hi,

Is there any guide to simplify migration of 1.x code to version 2.x? So far I found: 

- https://google.github.io/ExoPlayer/guide.html
- https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f#.jt5k9ruau

**Comment by ojw28** [comment]
We did intend to write a migration guide, but in practice it's difficult to do so because ExoPlayer can be used in so many different ways.

For "standard" use cases it should be pretty easy to figure out what to do by (a) using the resources above, (b) looking at what changed between V1 and V2 in the developer guide, and (c) looking at what changed in the demo app between V1 and V2. The demo app is probably the most useful thing to look at. Since standard use cases don't require too much work, it's also a viable option just to start from scratch with V2. If you just want to get some videos playing, or similar, then it shouldn't be much work at all, and will likely prove easier than trying to figure out the mapping between the two.

For "advanced" use cases it'll probably be the case that you get more or less all the way there but are stuck on some specific point (e.g. a customization that you made to V1 which you can't work out how to migrate across). For those issues, if really stuck, you'll probably have to ask specific questions.
