### ISSUE TITLE
[HLS switch variants] catch the first rendered frame of a new variant

### ISSUE THREAD

**Issue by optimus1130** [google/ExoPlayer#2173]
I'm currently playing with the ExoPlayer r2.0.4.
I noticed that in the HLS implementation, it supports adaptive video track selection. The demo application can seamlessly switching between variants in the HLS master playlist.
While, now I wish I could catch the first frame output by decoder from a new variant and synchronically do some operation when the very frame is rendered onto the screen.
Does ExoPlayer support this behavior? 
I already customized the trackSelection a little bit so that I can arbitrarily switch between self generated variants (all variants have the same format).

**Comment by ojw28** [comment]
Please can you clarify exactly what your use case is? What operation do you want to do, exactly, and how synchronous does it really need to be?

**Comment by optimus1130** [comment]
Thank you. My language is limited, but l'll try my best to clarify my use case:
In my application, the codec output frames are rendered onto an OpenGL shape.  Also, here is a camera in the OpenGL world to "see" the object. What I want is to know from which variant the new frame comes so that I can adjust camera position according the frame source when a frame form a new source (or, using the variable name used in ExoPlayer, a new video variant) is rendered onto the OpenGL shape. 
What I already have is: 
I can seamlessly switch between variants. 
The problem is:
I still can't catch the first frame that comes from a new variant each time when the variant change happens. Since all video variants have a same format, the onOutputFormatChanged method in MediaCodecVideoRenderer.java is never called.

**Comment by ojw28** [comment]
Is onInputFormatChanged called on MediaCodecVideoRenderer? The format on the input side of the decoder has quite a bit of extra data in it, so that's more likely.

If it is then the listener will see an invocation of onVideoInputFormatChanged, which might be good enough. If it's too early, you could do something like:
1. Set a flag in onInputFormatChanged
2. When an input buffer is queued, if the flag is set, clear it and record the timestamp of that buffer. This will be the timestamp of the first buffer after the format switch.
3. When an output buffer is rendered, look at its timestamp. If it matches the timestamp recorded in the previous step then it's the first buffer after the format switch. Generate an event and do what you want in response to it.

**Comment by optimus1130** [comment]
Thank you so much!! I got it done yesterday using exactly the same strategy.
