### ISSUE TITLE
Intercepting audio for playback externally

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#2212]
Hi,

Question...

Is there a way to intercept/grab decoded audio frames/chunks such that they do not get passed onto AudioTrack?  Essentially I am looking to take the decoded audio and be in control of playback myself after some manipulation.

I am using ExoPlayer v2.1.x currently.

Thanks!

**Comment by ojw28** [comment]
You should implement your own audio renderer and use it instead of `MediaCodecAudioRenderer` (or extend MediaCodecAudioRenderer if it's possible to adjust it to meet your use case).

If you're using `SimpleExoPlayer` then the way to pass a custom renderer is to extend `SimpleExoPlayer` and override `buildAudioRenderers` to add your own renderer rather than the ones that are added by default. If you're using `ExoPlayer` directly (via `ExoPlayerFactory.newInstance`) then you just inject it when you create the player instance.
