### ISSUE TITLE
Improvement short seek performance

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2238]
As:   #2237

http://programmingmemojohnchang.blogspot.tw/2016/12/improve-performance-of-short-seek-of.html

**Please read in detail by the link above which includes the result of experimental comparison.**

For streaming, current flow may hit the case where the whole pre-loaded data will be flushed. However, sometimes it is unnecessary to do so.

Once all pre-loaded data is flushed, ex: for 4K movie, a painful delay will happen.
Also, it hurts for users which do not have unlimited network data plan.

Some MPEG DASH links such as YouTube are made by the max interval between key frames about over 5 seconds. Hence the short seek may probably hit the claimed case.

To improve it, we may take the same way applied in GStreamer which filters the decoded-only samples at renderer.

The experimental result shows:

1. We save a lot of data download compared to original flow.
2. The seek response time is near to be the same as seamless; compared to originally it has a noticeable delay.

Please estimate if it works.

Thanks.

**Comment by ojw28** [comment]
It's now possible to optimize short seek performance by providing a `LoadControl` that returns true from `retainBackBufferFromKeyframe`. It's disabled by default because enabling it incurs an additional memory cost, the size of which is dependent on the media being played (specifically, how far apart key-frames may be spaced in the media). Apps that know something about the media they play (e.g. streaming services where the provider also controls the content) may opt to enable the feature.

The alternative solution proposed in https://github.com/google/ExoPlayer/pull/2237 was deemed to add too much complexity.
