### ISSUE TITLE
Couldn't select audio track

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2262]
In previous version r2.0.4 I could select audio track (see https://github.com/google/ExoPlayer/issues/2056), but how can I do this in 2.1.1 version?

**Comment by bene25** [comment]
Any suggestion for this issue?

**Comment by ojw28** [comment]
You can't expect a response when you provide so little information. "Couldn't select audio track" doesn't explain what you're doing. You don't explain what happens when you try and use your previous approach with r2.1.1 (e.g. does it not compile, does playback fail, if so how etc). You have also provided pretty much none of the information requested in the issue template (e.g. a bug report, media to test with, proper reproduction steps etc).

Closing. Please file a new issue containing detailed information if you want us to take a look.
