### ISSUE TITLE
Subtitle timecodes - how are they supposed to work?

### ISSUE THREAD

**Issue by jcable** [google/ExoPlayer#2263]
I've added initial support for ASS/SSA subtitles in my fork https://github.com/jcable/ExoPlayer.

Subtitles render but the timing is weird.

Here is a log print of the timecode received by successive calls to SSASubtitle.getCues. The one at 4234580 renders a correct subtitle timed at 00:00:04.32. What are the small numbers and why aren't the timecodes increasing monotonically?

I/getCues: 9909
I/getCues: 4234580
I/getCues: 7528
I/getCues: 4249523
I/getCues: 9654058
I/getCues: 2857
I/getCues: 4248911
I/getCues: 9632721
I/getCues: 33106077
I/getCues: 4784
I/getCues: 4233990
I/getCues: 9630249
I/getCues: 8185
I/getCues: 9183
I/getCues: 4247210
I/getCues: 9138
I/getCues: 5306
I/getCues: 9410
I/getCues: 4739
I/getCues: 8911
I/getCues: 9546
I/getCues: 1473
I/getCues: 30045
I/getCues: 3424
I/getCues: 12176
I/getCues: 5827
I/getCues: 1473
I/getCues: 4243333
I/getCues: 9610725
I/getCues: 5941
I/getCues: 6530
I/getCues: 9478
I/getCues: 3741
I/getCues: 181
I/getCues: 1111

**Comment by ojw28** [comment]
Good question! Subtitles are really complicated because they can be packaged in different units of granularity and with different ways of conveying timing information. Roughly speaking, an input buffer received by a subtitle decoder consists of a timestamp (`timeUs`) and the subtitle data to be decoded (`data`). There are four cases that can occur:

1. `data` contains all of the cues for the media and also their presentation timestamps. `timeUs` is the time of the start of the media. The subtitle decoder receives a single input buffer.
1. `data` contains a single cue to be displayed at `timeUs`. There are no timestamps encoded in `data`. The subtitle decoder receives many input buffers.
1. `data` contains cues covering a region of time (e.g. 5 seconds) along with their presentation timestamps relative to the start of the region. `timeUs` is the time of the start of the region. The subtitle decoder receives many input buffers.
1. As above, but the timestamps embedded in `data` are relative to the start of the media rather than the start of the region. This case is tricky and best avoided.

For a side-loaded SSA file you'd have case (1). For SSA embedded in MKV, it looks like they way it's embedded means you'd have case (2) if you were to just pass the sample data through without changing it. Note that `timeUs` is being set to `blockTimeUs` already. The changes you're making to the sample data in the extractor appear to be turning it into case (4), since you're also embedding `blockTimeUs` into the sample data. Each region happens to be the duration of a single cue.

What you should do is:

- In the extractor, change the sample data so that you get case (3) rather than (4). It's much easier to handle. This basically means the embedded time should be 0 rather than `blockTimeUs`. If you look at the SubRip case in the MKV extractor you'll see that it does exactly this. The SubRip case also defers writing so that the end time can be set properly, which is something you likely want to copy.
- In the decoder you're supposed to create a new `Subtitle` instance for each decode call, rather than appending to an existing instance. Fix this.

Having made these changes, for the SSA embedded in MKV case you should end up with each call to decode producing a new `Subtitle` with a single cue at time 0. The reason this works is that the event timing in a `Subtitle` is relative to `timeUs` of the buffer, which is being set to `blockTimeUs`. The fact that event timing in `Subtitle`s is relative to `timeUs` is also the answer to your original question ;). When the decoder receives a new input buffer with a larger `timeUs` than the previous one, the value passed to `getCues` will go down.

**Comment by jcable** [comment]
Thanks, that's really helpful. I'll have go at that. I didn't copy the SRT duration processing because I couldn't find it being used anywhere but that's obviously wrong and tied in with me not understanding the difference between timestamps in the subtitle structure and timestamps outside it.

I might be able to get somewhere now.

**Comment by jcable** [comment]
That was exactly the help I needed. It works nicely now. Of course the rendering needs implementing!

**Comment by ojw28** [comment]
Great; glad you're making progress!
