### ISSUE TITLE
minDurationToRetainAfterDiscardMs in AdaptiveVideoTrackSelection

### ISSUE THREAD

**Issue by lioun1729** [google/ExoPlayer#2266]
```
   * @param minDurationToRetainAfterDiscardMs When switching to a track of significantly higher
   *     quality, the selection may indicate that media already buffered at the lower quality can
   *     be discarded to speed up the switch. This is the minimum duration of media that must be
   *     retained at the lower quality.
```

In above comment, I wonder word 'significantly'

What is the precise standard about 'significantly' ?

Please help for this question, Thank you

**Comment by lioun1729** [comment]
#

**Comment by ojw28** [comment]
This question can be easily answered by going and looking at the [source code](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveVideoTrackSelection.java#L211). The whole class is only 250 lines long, and it's easy to see where the variable is used...

As an aside: It's not defined precisely because we don't want to guarantee that the behavior will stay exactly how it is now forever.

**Comment by lioun1729** [comment]
@ojw28 Ok, I confused about that little.. but not now

Thank you for your comment
