### ISSUE TITLE
Support querying unadjusted frame timestamps in MediaCodecVideoRenderer

### ISSUE THREAD

**Issue by bleuf1sh** [google/ExoPlayer#2267]
**Description:**
In MediaCodecVideoRenderer.processOutputBuffer(), when starting to play a video from the beginning, the positionUs and bufferPresentationTimeUs no longer start from 0 (Exo2.0.4). Instead they start from 60000000 (Exo2.1.1).

**Reproduce:**
Make a class which extends MediaCodecVideoRenderer and print the values positionUs and bufferPresentationTimeUs. See that in Exo2.0.4 (and in VideoTrackRenderer of Exo1.5.8) that these start from 0 but in Exo2.1.1 they start from 60000000. Reproducible using: http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4

**Comment by andrewlewis** [comment]
This was an intentional change to avoid having negative buffer timestamps when prerolling media for transitions into clipped periods (see [ClippingMediaSource](https://github.com/google/ExoPlayer/blob/f276eb2/library/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java) and [ClippingMediaPeriod](https://github.com/google/ExoPlayer/blob/f276eb2/library/src/main/java/com/google/android/exoplayer2/source/ClippingMediaPeriod.java)).

Could you explain why this is problematic for your use case? Renderer implementations should not rely on buffer timestamps starting at a particular offset. Thanks.

**Comment by bleuf1sh** [comment]
Our use case is to perform specific actions on the screen when rendering specific frames (time based).

**Comment by andrewlewis** [comment]
If you need a temporary workaround you can make `BaseRenderer.streamOffsetUs` visible to subclasses and subtract it from `positionUs` and `bufferPresentationTimeUs` to get the timestamp of the buffer read from the source.

Note: this won't work perfectly across period transitions if you're playing a playlist, but I doubt this applies because you would have seen output buffer timestamps that are not consistent with the source before this change in that case.

**Comment by bleuf1sh** [comment]
@andrewlewis , thanks. Why do you say "temporary workaround" ? Does that mean that this streamOffset will be removed eventually? 

If my use-case is to run code when a specific frame/time in the timeline is presented, what other options do I have? -Thanks!

**Comment by andrewlewis** [comment]
That workaround doesn't work correctly for playlists, as described above. We'd need to expose the offset or source buffer timestamps in a way that works for all sources to fix this properly.

You could poll the player's current position which should match the source, but maybe you need closer synchronization than that. Or you could implement a custom MediaSource/Renderer and feed samples through the player to offset them, like we do for subtitles (then you wouldn't need to make any modifications to the video renderer for this).

**Comment by ojw28** [comment]
The original frame PTS is propagated to the [render|drop|skip]OutputBuffer methods as an additional argument, as of https://github.com/google/ExoPlayer/commit/88fddb42eca2da65297cfacd1a068aadc47b2614.
