### ISSUE TITLE
Callback multiple times

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2272]
I'm receiving callbacks always multiple times. When the playback is finished, there are two calls to `onPlayerStateChanged` with playbackState `STATE_ENDED`.
Also when seeking `onPositionDiscontinuity` is called twice.

Also when being in STATE_ENDED and calling `seekTo(0,0)` and `setPlayWhenReady(true)` another `onPlayerStateChanged` with playbackState `STATE_ENDED` arrives.

I have tested this with ExoPlayer 2.0.4, 2.1.0 and 2.1.1.

**Comment by ojw28** [comment]
The duplicate `onPositionDiscontinuity` calls are already fixed in the `dev-v2` branch by https://github.com/google/ExoPlayer/commit/4bb8793203ff280189d15849669304ebb138d814.

I cannot reproduce the other cases you mention. In the demo app `onPlayerStateChanged` events are logged to logcat with the tag EventLogger. I only see a single transition to `STATE_ENDED`, and no duplicate when subsequently seeking back to 0. I suspect you're changing `playWhenReady`, which is a state change and will cause `onPlayerStateChanged` to be invoked.

**Comment by PaulWoitaschek** [comment]
What you suspected was right. I was calling setPlayWhenReady(false) upon `StateEnded`.

Thanks for fixing :)
