### ISSUE TITLE
SeekBar id exo_progress accessibility

### ISSUE THREAD

**Issue by b77x** [google/ExoPlayer#2278]
On the demo app's exo_progress, android focusable is set to false. This makes it unable to be controlled without touch screen. 

I created my own UI with facusable set true. When using touchscreen, the progress moves, however when using the keyboard arrows, the seekbar moves, but it gets updated again to the same position.

**Comment by ojw28** [comment]
It's deliberately not focusable. This is because the FF/RW buttons above it are focusable and can be used to seek more easily. TV devices often have controllers with physical FF/RW buttons, and these can also be used.

That said, we should definitely make sure it works correctly if it is made focusable, which isn't currently the case. We may also consider making it focusable by default if this makes seeking in long duration content easier (I'm not sure whether it does or not).
