### ISSUE TITLE
Ffmpeg and some other extension classes declared final 

### ISSUE THREAD

**Issue by kiall** [google/ExoPlayer#2284]
The ffmpeg, opus and vp9 extension classes are declared final, preventing any extension of the classes. The flac extension is not declared final.

In my case, I was looking to add some logging around a few methods to help debug an AC3 audio issue, but couldn't (easily).

Is there any reason for these to be final?

**Comment by ojw28** [comment]
Everything that's *not* final or private is effectively part of ExoPlayer's API, since it can then be overridden. Making everything non-final would hugely increase an already very large API surface area. This is problematic because (a) it adds things to the API that we really haven't given enough thought to, and (b) gives developers many different ways of doing the same thing rather than more strongly pushing them toward what we think is the best way of doing something.

We had problems in the past where application developers would implement features by overriding random methods that were then removed as a result of things like internal code restructuring. In such cases the developer is then stuck being unable to upgrade or having to re-implement their features using more appropriate APIs that already existed for what they were trying to achieve. So I think marking things as final and exerting some level of control over this kind of scenario is a good idea.

If you just want to do some local debugging, why not edit the files directly?

**Comment by kiall** [comment]
Editing the files directly is what I ended up doing, but I *think* I've since come across a case where I really do need to override a ffmpeg extension method.

For AC3 passthrough to work, we need to prevent FFmpeg from accepting the stream (Since it doesn't appear to support passthrough). When the system doesn't have a native AC3 decoder (like the nVidia Shield TV box), ffmpeg will always be considered best as it actually has a decoder.

I believe, and I've not tested this yet or spent too long looking for alternative solutions, but overriding `FfmpegAudioRenderer.supportsFormat()` to return unsupported when we want to perform passthrough is a possible fix. There may be better ways to handle this though.

**Comment by ojw28** [comment]
I'm not exactly sure I follow this. Isn't the order of the renderers important? Can't you just swap them around to prefer one or the other?

**Comment by ojw28** [comment]
Providing a different TrackSelector implementation is also one possible solution to this problem.

**Comment by kiall** [comment]
Swapping the order didn't help, once FFMpeg was included, all AC3 audio tracks on the Shield were handled by it rather than the MediaCodecAudioRenderer's passthrough decoder. Right now, MediaCodec is first, FFmpeg second[1].

I'm not sure a custom TrackSelector helps here, as even where there is exactly 1 audio track, an AC3 track, it's handled by FFMpeg and not passed though. We also already have a TrackSelector[2] which will create a FixedTrackSelection when a different track is chosen via Live Channels.

I can try knock up a proof of concept to demo the issue..

1: https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/java/ie/macinnes/tvheadend/player/SimpleTvheadendPlayer.java
2: https://github.com/kiall/android-tvheadend/blob/develop/app/src/main/java/ie/macinnes/tvheadend/player/TvheadendTrackSelector.java

**Comment by kiall** [comment]
Also - I reckon we're straying into another issue here :) If you believe mediacodec passthrough should be selected over ffmpeg given the info above, I can open a new bug - and we can close this as won't fix due to API concerns.

**Comment by ojw28** [comment]
I'm not sure I follow. I think you should put the MediaCodec based renderer first and always prefer passthrough if available. What issue are you facing when doing that?

**Comment by kiall** [comment]
With MediaCodec first, FFmpeg second and a FixedTrackSelection enforcing the choice of a AC3 track, FFmpeg is selected as the audio renderer, resulting in the AC3 track being transcoded to PCM.

Preferring passthrough doesn't seem to be possible, the ffmpeg audio renderer always wins for AC3 tracks (At least, on the nVidia Shield where there is no native AC3 decoder).

Digging around on GitHub, I've found another similar Android TV project that has needed to override methods on this extension for the same reasons:  https://github.com/pipelka/roboTV/blob/master/app/src/main/java/org/xvdr/player/audio/RoboTvAudioRenderer.java

They've had to duplicate the extension's code though, to remove the final's :(

**Comment by ojw28** [comment]
I'm still not sure I follow this. Isn't a track selection renderer specific already? I'm not sure it makes sense to say you set a track selection and then after that a renderer was selected?

**Comment by ojw28** [comment]
I'm planning to close this next week unless further clarification is provided.

**Comment by kiall** [comment]
Apologies, I've been busy with other things (the app is a side project, so finding the time can be hard!)

I'll re-open if the advice above doesn't solve the problem, once I manage to circle back to this issue.

Thanks again!
