### ISSUE TITLE
Clear all EventListeners

### ISSUE THREAD

**Issue by botondbutuza** [google/ExoPlayer#2337]
More of a question than an issue - I have one or two event listeners set on a SimpleExoPlayer, and I was wondering if it would be possible to remove all of them with one utility method, instead of having to retain instances of the listeners.

**Comment by ojw28** [comment]
This isn't supported, so you'll need to keep references to the instances so that you can pass them to the remove method. Having a method to clear all listeners may end up being more confusing than it is helpful, since components like `SimpleExoPlayerView` add themselves as listeners to the player, and it's quite likely that a developer calling such a method wont realize they're detaching the view from the player by doing so.

**Comment by botondbutuza** [comment]
That's a very good point, thank you for clarifying. :)
