### ISSUE TITLE
Large memory usage even after closing the App

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#2356]
*** PLEASE DO NOT IGNORE THIS ISSUE TEMPLATE ***

- A description of the issue: this is more like a question. My app plays some Videos and I make 3 "heap dump" using Android Studio. The point is the dump after closing the App + manually trigger GC (by AS) still shows a huge mount of memory allocation, where "*.upstream.Allocation" instances present the most. I suppose to catch all place your "free" the Allocations, but should I care about this? Or it has been optimized and my case is just the ART sees the auto GC can be done later?

- Steps describing how the issue can be reproduced: I can provide code later (it is from my library, or even the dump file).

- A link to content that reproduces the issue: the open source Big Buck Bunny, mp4, 720p or less I think, AVC/h264.
- The version of ExoPlayer being used: 2.1.1
- The device(s) and version(s) of Android on which the issue can be reproduced: Nexus 5X, Android 7.1.1

**Comment by ojw28** [comment]
There isn't enough information here for us to help. Please provide detailed reproduction steps with the ExoPlayer demo app if you believe this to be an issue. If the elevated memory issue occurs only in your own app, it's likely an application specific problem (e.g. because you're not properly releasing the player) and you'll need to debug why that is yourself.

**Comment by eneim** [comment]
@ojw28 let me close this, as I could not give necessary info for now.
