### ISSUE TITLE
NullPointerException when creating new SimpleExoPlayer

### ISSUE THREAD

**Issue by Yrlec** [google/ExoPlayer#2378]
For some users of our we're getting NullPointerException when trying to create a new SimpleExoPlayer.

We haven't been able to reproduce it locally but you can see more details here: http://crashes.to/s/c2d534cf144

The method that creates a new instance looks like this:

 ```
protected void render(Uri uri) {
        final DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        final TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
        final TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        final LoadControl loadControl = new DefaultLoadControl();

        player = ExoPlayerFactory.newSimpleInstance(getContext(), trackSelector, loadControl);

        final DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getContext(), Util.getUserAgent(getContext(), "Degoo"), bandwidthMeter);
        final ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        final MediaSource videoSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);

        simpleExoPlayerView.setPlayer(player);

        player.prepare(videoSource);
        player.setPlayWhenReady(false);
    }
```

**Comment by ojw28** [comment]
I think `getContext()` in your application code (above) is returning `null`. You then end up passing `null` to `newSimpleInstance`, which results in a `NullPointedException` when that context is used during player construction.

I'm not certain when `getContext()` returns a null value, but you can start figuring this out [here](http://stackoverflow.com/questions/18154905/why-is-my-context-in-my-fragment-null). I suspect the fragment is either not yet attached, or no longer attached, to the activity when you're executing the code (above).

Closing since this appears to be an issue in application code.
