### ISSUE TITLE
Video rendering on Surface

### ISSUE THREAD

**Issue by Oleur** [google/ExoPlayer#2383]
Hi there!

I am trying to migrate my VR plugin based on ExoPlayer v1 to ExoPlayer v2, but I have an issue with the video rendering on an Android Surface.

I have a SurfaceTexture which represents a screen in a 3D world, but when I create a Surface from this SurfaceTexture (new Surface(surfaceTexture)) and pass it to ExoPlayer in order to render my video nothing appens. This works well with ExoPlayer v1.5.X.

You can reproduce this issue with any video.

- ExoPlayer version used for testing: 2.0.4 and 2.1.1.

- Devices used: Nexus 5X (7.1.1) and Sony Experia Z5 compact (6.0.1).

Thanks!

**Comment by ojw28** [comment]
There's insufficient information provided here for us to efficiently investigate your issue. It sounds most likely to be a bug in application code. Please explain exactly how to reproduce the issue with the demo app, ideally by providing a patch, pull-request or link to a forked version of the demo app that reproduces the issue so that we can see exactly how you're creating and passing the surface.

**Comment by Oleur** [comment]
I sent you an email with a link where you will be able to download the sample app with our plugin. You will be able to reproduce the issue by running the sample app (steps are described in the mail).

If you need anything else, please let me know!

Thanks!

**Comment by ojw28** [comment]
I couldn't see anything obviously wrong, but the app you've provided is pretty complicated and it's not realistic to expect us to fully understand and debug it. I did a quick test modifying the ExoPlayer demo app to use `setVideoSurface(new Surface(surfaceTexture))` and it appears to work fine, so I still think this is an issue with your application code. You can find my test modification [here](https://github.com/google/ExoPlayer/commit/8a3fa03b27fc869e6ca232cf434b613fea32184b).

If you're able to provide a small modification to *our* demo app that more clearly demonstrates there's an issue with the ExoPlayer library rather than your own code, please do so and we'll take a more detailed look. Closing for now as I can't see anything to suggest it's a library issue at this point.

**Comment by ojw28** [comment]
By the way, the surface definitely appears to be passed to the video renderer. The renderer appears to initialize the codec and the logs don't indicate any failures. So if I had to guess I'd say it's more likely than not that the video frames are being rendered to the surface provided, and that it's either the wrong surface, that it's not being rendered properly in the 3D scene, or that it's somehow being occluded by something else. That's where I'd start if I were debugging this, in any case.

**Comment by Oleur** [comment]
Thanks for your answer and hints! I will keep you up to date if I find anything new.
