### ISSUE TITLE
[Question] What's the purpose of priorityTaskManager  & PriorityDataSource? How could I use it?

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2384]
Dear Developers:

What's the purpose of **priorityTaskManager**  & **PriorityDataSource**?

How could I use it?

I happen to see there two classes but it seems that they are not used for now.

Is there anyone know for which purpose it intends? 

Thanks in advance!

**Comment by ojw28** [comment]
If you were making a background service for downloading media, and also wanted to allow streaming of (different) media whilst downloads are in progress, then these components can be used to pause downloads whilst streaming is taking place so that the streaming playback can utilize all of the network. Describing this in detail isn't really possible in a concise way, but we plan to make use of these components in future changes that will start building out more fully featured download functionality.
