### ISSUE TITLE
How to play only video key frames in exoplayer-v2

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#2409]
I have a use case where I only want to play video key-frames.
My plan is to sub-class `DefaultTrackOutput` and override `readData()`.
So something like this:

    public class KeyFrameTrackOutput extends DefaulTrackOutput {
        @Override
        public int readData(FormatHolder formatHolder, DecoderInputBuffer buffer, boolean loadingFinished,
                long decodeOnlyUntilUs) {
            int result = super.readData(formatHolder, buffer, loadingFinished, decodeOnlyUntilUs);
            if (result == C.RESULT_BUFFER_READ
                    && !buffer.isKeyFrame()) {
               //not a key frame so drop immediately to avoid decoding
               result = C.RESULT_NOTHING_READ;
            }
            return result;
        }
    }

Does this approach sound reasonable?

**Comment by ptran-gpfw** [comment]
Hmm... it seems [ExtractorMediaPeriod](https://github.com/google/ExoPlayer/blob/25a966dc2300161448fa74dee5ee98322ff65604/library/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaPeriod.java#L387) is coupled to `DefaultTrackOutput`.

It seems I would have to maintain a copy-pasted version of `ExtractorMediaPeriod` that used my new `KeyFrameTrackOutput `.

What do you think?

**Comment by ptran-gpfw** [comment]
Hi @ojw28, any chance you could take a look at this?

**Comment by ptran-gpfw** [comment]
@ojw28 Hi Oliver, just wondering if you had any thoughts on the approach described above, thanks!

**Comment by ojw28** [comment]
If the end goal is to enable playback at more than 1x speed in a way that doesn't cause video to freeze indefinitely, then I think that should work reasonably well as of `2.6.0` without you needing to do anything special. This is because `MediaCodecVideoRenderer` now automatically skips to key-frames in this kind of case. The relevant line in the 2.6.0 release notes is:

> Better playback experience when the video decoder cannot keep up, by skipping to key-frames. This is particularly relevant for variable speed playbacks.

If you really need to ensure only key-frames are being rendered, then I think customizing the `Renderer` would be a better approach than customizing anything that lives in the `MediaSource`. It shouldn't be too tricky to extend or fork `MediaCodecVideoRenderer` to only render key-frames. You can inject a custom `Renderer` implementation using `RenderersFactory` if using `SimpleExoPlayer`, or directly otherwise.
