### ISSUE TITLE
MediaDrm getKeyRequest throws NotProvisionedException

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2410]
Dear colleagues,

This is a question, a request for advise.
Our reporting system provide us with statistics about NotProvisionedException when getKeyRequest invoked. Based on the java documentation from the method:
```
NotProvisionedException if reprovisioning is needed, due to a problem with the certificate
```
But what does "reprovisioning" means? Is provision data something that receive only once for device? How to do reprovisioning (other way then factory reset)?

Thanks in advance.

**Comment by ojw28** [comment]
Widevine L1 is typically factory provisioned, meaning provisioning wont ever need to happen. When using L3 (either because you've forced an L1 device to L3 or because the device only has L3) provisioning typically happens once. A factory reset should cause re-provisioning. If the device is rooted then you can also cause re-provisioning by doing:
```
adb shell rm -r /data/mediadrm/IDM1013
```
which will reset Widevine modular DRM back to its factory state.
