### ISSUE TITLE
MP4 freezes for the first 4 seconds

### ISSUE THREAD

**Issue by laurencedawson** [google/ExoPlayer#2415]
- When opening the following URL, ExoPlayer draws the first frame and then doesn't update for 4 seconds
  https://thumbs.gfycat.com/HugeAdeptFrigatebird-mobile.mp4

- ExoPlayer r2.2.0
- Android 6P 7.1.1 (but seems to happen on all tested devices)

**Comment by ojw28** [comment]
It looks to me like this is working as intended. The video track in this mp4 file includes an edit list (edts box) that appears to specify this behaviour during playback. If we simply ignore the edit list then playback works fine, and it's likely that other players appear to be playing the content correctly because they don't suppoert edit lists (where-as in fact ExoPlayer is doing what the media really does specify by handling them - and if the media isn't supposed to be paused in this way the edit list should not be present in the media).

I'll leave this open for @andrewlewis (resident edit list expert) to confirm, since I'm not 100% sure on the structure of edit list boxes (the specification is quite vague).

**Comment by laurencedawson** [comment]
Is there a way to always ignore edit lists? Thanks

**Comment by ojw28** [comment]
Not without modifying the ExoPlayer library and then building from source. It's unclear that's really what you'd want to do anyway, given it would result in incorrect playback of all media that *does* have an (intentional) edit list?

**Comment by laurencedawson** [comment]
Sorry I didn't see your reply. 

In this use-case it's for user submitted videos that have been incorrectly bundled with an edit list.
