### ISSUE TITLE
What is different DASH from SmoothStreaming? thanks you

### ISSUE THREAD

**Issue by ihrthk** [google/ExoPlayer#242]

**Comment by ojw28** [comment]
They are both specifications for the adaptive delivery of media. DASH is an ISO standard. The Smooth Streaming specification is controlled by Microsoft. ExoPlayer supports both with Fragmented MP4 only. Given this, in practical terms, they are pretty similar to one another, with the main difference being the different formatting of the manifests. There are many other minor differences.

If you're choosing which one to use then I'd recommend you use DASH, because it's an ISO standard and because it's likely better aligned with where the majority of the industry is heading.
