### ISSUE TITLE
Incorrect zoom 3x2 video on some TV devices. SurfaceView cant be outside screen bounds, cant be lager then screen

### ISSUE THREAD

**Issue by nshutov** [google/ExoPlayer#2448]
Hello!
I use exoplayer:r2.2.0 on Sony BRAVIA 2015 (Android 5.1.1, API 22) android tv device. I try watch 360x240 video with set flag AspectRatioFrameLayout.RESIZE_MODE_FIXED_WIDTH
video: http://www.sample-videos.com/video/mkv/240/big_buck_bunny_240p_1mb.mkv
I have wrond aspect result, Bunny is soo fat) and top and bottom datk rectangles not clipped:
![20170213_174551](https://cloud.githubusercontent.com/assets/6918700/22887878/bca0ad2e-f214-11e6-8aa9-b18367b608e7.jpg)

On emulator work fine, aspect correct, top and bottom dark rectangles is clipped :
![emulator_screenshot_1486996265](https://cloud.githubusercontent.com/assets/6918700/22887889/c75fdf96-f214-11e6-8cac-69143e2adb83.png)

Why it happens? Becouse SurfaceView is bounded in screen.
Negative margins, size in layout params, matrix transformation - no expected effect on this device
SurfaceView can be outside parent ViewGroup but cant be outside screen

PS On mobile devices all work fine
PSPS TextureView fix this issue, but TextureView dont work with Widevine (

Thanks, Exoplayer is really good player)

**Comment by ojw28** [comment]
I'm unsure about sizing a `SurfaceView` larger than the display, but it isn't something I'd necessarily expect to work. Have you tried using `SimpleExoPlayer.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)` together with `RESIZE_MODE_FILL`? I think that probably achieves what you're trying to do whilst sizing the `SurfaceView` to have the dimensions of the display rather than any larger.

Note that `RESIZE_MODE_FILL` is also equivalent to just using a `SurfaceView` directly (i.e. not in an `AspectRatioFrameLayout`), if that's any easier.

**Comment by nshutov** [comment]
I try `setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)` in many places in code(player init, after set data source, player state changed) with `AspectRatioFrameLayout.RESIZE_MODE_FILL` - no effect(((
After chage `AspectRatioFrameLayout` to `FrameLayout `- no effect(((

MediaCodecVideoRenderer.java:
`private static void setVideoScalingMode(MediaCodec codec, int scalingMode) {
    codec.setVideoScalingMode(scalingMode);
  }`
called many times with `scalingMode == 2(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)`

**Comment by ojw28** [comment]
Duplicating to #2677.
