### ISSUE TITLE
How to get currently playing video and audio bitrate 

### ISSUE THREAD

**Issue by bigexxx** [google/ExoPlayer#2474]
How we can get video and audio bitrate (estimated) from currently playing chunk? Not the downloading bitrate, not the bitrate specified at manifest file (in case of hls), but real bitrate of video and audio streams in .ts chunk? Is it possible? 

This data needed for debug window for enduser

**Comment by WeiChungChang** [comment]
I think for getting real bit-rate, you may need to know two parameters.
1. Real size of a particular media chunk.
2. Media chunk's duration.

For 1, The actual size of a particular media chunk could be known by **sampleBytesTransferred** within **DefaultBandwidthMeter**.
In order to get it, I tried to implement the EventListener of BandwidthMeter and create a new API = onTransferEnd() to inform the downloaded media chunk size, as the patch below.
[RealChunkSize.txt](https://github.com/google/ExoPlayer/files/786522/RealChunkSize.txt)
It prints out each media chunk's size when having downloaded it.

It is not good in practice since the function is run on main thread (thread id = 1).
So a rework is in need to make the thread run on internal thread instead.

2 seems to be easier; so I believe a try will simply accomplish it.

**Comment by bigexxx** [comment]
Good, but slightly not what i want. sampleBytesTransferred / chunk duration give us a total bitrate of the chunk = video bitrate + audio 1 bitrate + audio 2 bitrate + maybe some additional data. I want it separate to display on information popup like that:

Video bitrate: 1234 Kbit/s
Audio bitrate: 123 Kbit/s

I think unpaking media stream doing by media codec ?

**Comment by ojw28** [comment]
We don't expose this information. It doesn't sound particularly important, so I suspect you'll just have to manage without ;).
