### ISSUE TITLE
Black video if playing started on hidden view.

### ISSUE THREAD

**Issue by tprochazka** [google/ExoPlayer#2479]
In version 2.0.2 I was SimpleExoPlayerView with visibility = GONE.
And when I reach the ExoPlayer.STATE_READY I changed visibility to VISIBLE.
But after update to 2.2.0 video remain still black after change to VISIBLE, just audio was working.
If I will keep SimpleExoPlayerView visible for whole time it is working correctly.
I don't know if it is bug or feature.

**Comment by khacpv** [comment]
My workaround is set alpha to 0 or 1 instead of set GONE/VISIBLE.

**Comment by gajendrakumartwinwal** [comment]
Getting same issue while removing the exoplayer surfaceview and and adding it to another viewgroup:(

**Comment by ojw28** [comment]
The ability to switch surface is difficult due to underlying platform constraints, as discussed in https://github.com/google/ExoPlayer/issues/677. Making a parent view invisible/gone or detaching it from the view hierarchy will normally cause the surface to be destroyed. A new surface will be created when the view is made visible or reattached to the hierarchy. Hence the use cases described here do result in surface switches and so run into the same underlying constraints.

There's a class called `DummySurface` that we recently added to mitigate this behavior. You currently need to wire it up manually, however. Follow https://github.com/google/ExoPlayer/issues/677 for more details.
