### ISSUE TITLE
SimpleExoplayerView inside recycler view consumes touch event

### ISSUE THREAD

**Issue by djmalkar** [google/ExoPlayer#2508]
I have a recycler view inside which i have embedded SimpleExoplayerView in each list row now when the video is playing and if user needs to scroll by toching SimpleExoplayerView, this view consumes the event and the user can't scroll. For this currently I am using workaround like this-

`mSimpleExoplayerView.setOnTouchListener
(new View.OnTouchListener() 
{              @Override
                public boolean onTouch
(View view, MotionEvent motionEvent) 
{
                    //startMoveFloatContainer(true);
                    mRecyclerView.dispatchTouchEvent(motionEvent);
                    return false;
                }
            });`

but in this case scroll is possible on touch over SimpleExoplayerView but it flickers a lot. Any solution?

**Comment by nitinarv** [comment]
Hi, I have been facing this exact same problem. I have been able to implement play and pause in a different button . But when I scroll up and down it flickers a lot. Is there any solution to it? I had thought it was because of the ExoPlayer was impemented using the surface view. I had come across this ' tools:surface_type="texture_view" ' . And it still persisted. 

@djmalkar  , Were you able to find a solution to this problem? And what did you do eventually to achieve the same kind of user experience of playing inside the RecyclerView?

**Comment by djmalkar** [comment]
No, not got the solution so i just maintain the image in listviee and on
click of that image a new activity will play that video... No playing of
video in listview was achieved

**Comment by tonihei** [comment]
Closing the issue because it sounds as if you found a solution to your problem. If not, feel free to reopen.
