### ISSUE TITLE
Exoplayer2 can not play local mp3 file

### ISSUE THREAD

**Issue by mustafasevgi** [google/ExoPlayer#2510]
Hello,

I can not play this mp3 file with Exoplayer2 demo code. 
Mp3 file: https://drive.google.com/file/d/0B94LXw9lUxoxNHpYU1F6YUFVems/view?usp=sharing

Error: Caused by: com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

Can you help please,
Thank you,

**Comment by andrewlewis** [comment]
The file starts with 426 bytes of XML. The format is detected and the stream plays fine if you trim that from the start of the file, e.g. with `tail -c +426 file.mp3`.

The XML looks like some kind of metadata, but I don't think the stream is valid (you can't prepend arbitrary stuff to an MP3 stream). If this is an official part of MP3 please provide a link to the specification and we can look into supporting it. Otherwise, you'll either need to change the media you're serving so it's valid, or somehow strip the data client-side as a workaround.

**Comment by mustafasevgi** [comment]
thank you @andrewlewis
