### ISSUE TITLE
No sound when playing an MP4 file

### ISSUE THREAD

**Issue by lucas34** [google/ExoPlayer#2523]
Hi,

I have an MP4 file:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'audio.mp4':
  Metadata:
    major_brand     : M4A 
    minor_version   : 512
    compatible_brands: isomiso2iso6
    encoder         : Lavf57.21.101
  Duration: 00:00:10.43, start: 0.000000, bitrate: 63 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

When I try to play this specific file with ExoPlayer 1 or 2, It's seems to play correctly but there is no sound. I tried with other files, I'm able to hear the sound. 

I created a branch on my repo with the file. https://github.com/lucas34/ExoPlayer/tree/issue
The link to the file is hardcoded so any link in the main screen will try to play this file.

If I'm using the android.media.MediaPlayer I can play correctly without problem.

So far, I cannot figured out why there is no sound. Any idea ?

**Comment by andrewlewis** [comment]
The file is identified as a fragmented MP4 file due to the presence of the `mvex` box in the `moov` box, but strangely it contains no `moof` fragments. At first glance it looks like it may technically be allowed to include an `mvex` box in unfragmented files but it seems unnecessary (and we don't support it at the moment). The file plays fine if I force using the non-fragmented `Mp4Extractor`. How did you produce this file?

**Comment by appear88** [comment]
I have the samle problem

**Comment by appear88** [comment]
my mp4 file produce from phone recorded

**Comment by lucas34** [comment]
Hi,

It's an app running on NWJS that communicate with FFMPEG. We were using fragmented mp4, because the output is written to buffer.

Using the MP4Extractor solved the issue. So I created a custom MP4Extractor and modified the sniff function to accept the fragmented MP4 as well. 

Thanks for the quick reply.
