### ISSUE TITLE
"Sometimes" problems with playing stream

### ISSUE THREAD

**Issue by graphcon** [google/ExoPlayer#2532]
Hello,

we are currently trying to _stream a radio station_ that sends 64k aac+. We implemented a service that runs Exoplayer to continue streaming when app is set to background or screen turns off.

Sometimes, that stream doesn't start playing. When we _stop_ the stream and _restart_ it again, audio starts without problem.
I tried to reproduce that problem in Exoplayer demo app, but I wasn't able to reproduce it (yet?).

To give you the detailed information you asked for:
Stream-URL: http://sj64.hnux.com
Devices (at least): HTC One m7 running Android 5.0.2 and Moto XT1096 running Android 5.1
ExoPlayer version according to gradle: com.google.android.exoplayer:exoplayer:r2.0.0

We stop the player setting: player.setPlayWhenReady(false);
We start the player setting:

```java
    mainHandler = new Handler();

    TrackSelection.Factory videoTrackSelectionFactory =
            new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);

    TrackSelector trackSelector =
            new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);

    LoadControl loadControl = new DefaultLoadControl();

    player =
            ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

    eventLogger = new ExoplayerEventLogger();
    mediaDataSourceFactory = buildDataSourceFactory(true);

    String streamUrl = "http://sj64.hnux.com";

    MediaSource mediaSource = new ExtractorMediaSource(
            Uri.parse(streamUrl),
            mediaDataSourceFactory,
            new DefaultExtractorsFactory(),
            mainHandler,
            eventLogger);

    player.setPlayWhenReady(true);
    player.prepare(mediaSource);
```

A logcat file with log output: 
[logcat-201703061730.txt](https://github.com/google/ExoPlayer/files/821755/logcat-201703061730.txt)

**Comment by ojw28** [comment]
You should definitely try updating to 2.2.0 as a first step. The 2.0 release was a pretty huge revision to the library, and was inevitably a little immature as a result. Many issues have been ironed out in the subsequent smaller releases. If you're doing background playbakc then you should also ensure you're holding a wakelock and wifilock as detailed in https://github.com/google/ExoPlayer/issues/930.

The above aside, the snippet of log you attach suggests the decoder is unhappy with the media being fed to it. Unfortunately there is insufficient information for us to debug the issue, which is why we ask for a full bug report in the issue template. Please provide one if you wish for us to investigate further.

**Comment by graphcon** [comment]
Thank you, I will try with updating to r2.2.0 and open a new issue if that didn't help.

Or do you prefer re-opening this issue?

**Comment by ojw28** [comment]
Please just update this one. Thanks!
