### ISSUE TITLE
Reduce memory footprint by disabling ID3 parser

### ISSUE THREAD

**Issue by roccozanni** [google/ExoPlayer#2553]
Hi, 
while I was investigating OOM issues within a podcast player app, I noticed that most of the generated stack traces comes from ExoPlayer. I know that in this case a stack trace only show the location in the code that failed to allocate the memory, and it doesn't necessarily mean that place in the code is the source of the issue, but then I found this: 

```
java.lang.OutOfMemoryError: Failed to allocate a 10023088 byte allocation with 9214813 free bytes and 8MB until OOM
	at java.util.Arrays.copyOfRange(Arrays.java:2671)
	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeApicFrame(Id3Decoder.java:391)
	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeFrame(Id3Decoder.java:276)
	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decode(Id3Decoder.java:87)
	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekId3Data(Mp3Extractor.java:287)
	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:209)
	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.sniff(Mp3Extractor.java:115)
	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:688)
	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

and I found strange that ExoPlayer was trying to allocate 10MB at once, so I checked some of the MP3 files and I noticed that some of them embeds very large images in the ID3 header. For example, this is around 13MB: https://download.ted.com/talks/MeganPhelpsRoper_2017S.mp3

In my case, my app doesn't need any of this data, because we analyze the files on the server-side beforehand, extracting all the metadata that we made available to the app via our API, so parsing the ID3 is totally useless for us and it waste a lot of memory, that on low-end device is quite a big deal.

I checked the code and I couldn't find any clue about a configuration to disabling the ID3 parser in the MP3 extractor. Am I missing something? Is it something possible to integrate in the next releases?

Thanks,
Rocco

**Comment by ojw28** [comment]
I think one way of turning this off in the current release is to extend `SimpleExoPlayer` and override `buildMetadataRenderers` to do nothing. We should add an option to `DefaultTrackSelector` to turn off enabling of the metadata track, as a simpler way of doing this.

**Comment by ojw28** [comment]
Note: Putting a 13MB image at the start of an MP3 file is a pretty bad thing to do (a player will need to download and throw away that 13MB even if it doesn't want it, which will significantly increase startup latency). If you know the content creator, it would be a good idea to suggest they fix this issue.

**Comment by roccozanni** [comment]
Thanks for your reply @ojw28. I tried your workaround and unfortunately it doesn't work, because `Mp3Extractor.peekId3Data` is still  being executed, and here: 

https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/extractor/mp3/Mp3Extractor.java#L284 

you'll see that a new byte[] is allocated to hold the content of the ID3 frame. Then this is decoded and stored into the `metadata` field of the `Mp3Extractor` class.

**Comment by roccozanni** [comment]
A possible solution would be adding a configuration that will be checked here: 

https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/extractor/mp3/Mp3Extractor.java#L283

and will cause the metadata frames to be discarded, like it happens now when the metadata are already parsed. What do you think @ojw28 ?

**Comment by ojw28** [comment]
Oh right, yes, the ID3 data isn't delivered in a metadata track in this case. It's in audio track's `Format` object. We could probably add a `FLAG_DISABLE_ID3_PARSING` to `Mp3Extractor` that you can set if you don't want it.

I think we'd still want to parse at least the gapless metadata, since that's used by the player internally. So in the case of the flag being set we'd probably need to propagate a setting to the `Id3Decoder.decode`, call telling it to only bother parsing frames that are useful (COM/COMM).

I also think the way the metadata is read and parsed is very inefficient. I have a feeling there may be three copies of the data held in memory simultaneously, so if the image is 13MB it might be that we need 39MB of allocation simultaneously to handle it. I'll take a look at reducing that.

**Comment by ojw28** [comment]
The memory allocations are as follows:

1. `DefaultExtractorInput` has an internal peekBuffer. The way this resizes means it currently allocates ~26MB for the problematic file. It's pretty trivial to get this down to ~13MB by making the logic that resizes the peekBuffer more sane. We should also consider having `DefaultExtractorInput` trim its peek buffer after advancing past a large amount of peeked data, so that the remaining 13MB can be reused.
1. `Mp3Extractor.peekId3Data` takes a copy `id3Data` (~13MB). This is short lived but overlaps with the allocations described above and below, so contributes to the peak memory requirement. We can probably eliminate this by providing direct access to `DefaultExtractorInput`'s peekBuffer.
1. `Id3Decoder.decodeApicFrame` takes a copy (~13MB). This is long lived and placed into the `Format`. We can't do anything about this one unless a flag is set on the extractor.

So it should be possible to reduce peak memory requirement from ~52MB to ~26MB, and further down to ~13MB if the flag is set.

**Comment by ojw28** [comment]
The first of the changes above adjusts the `DefaultExtractorInput` peekBuffer resize logic to reduce the peak memory requirement by ~13MB and in-playback requirement by ~26MB for the problematic sample. The second change adds a flag to `Mp3Extractor` that you can set to disable metadata parsing if you don't need it. That'll reduce both the peak and in-playback requirement by a further ~13MB.

We can still improve on (2) mentioned above, but that change will require some more in-depth work. Hopefully the changes we've made will be sufficient to allow you to avoid running out of memory. Leaving this issue open to track (2) as a lower priority item.

**Comment by roccozanni** [comment]
@ojw28 thanks for the effort you're putting into this, I'm impressed to see something moving on so fast. Looking forward to try the new release!

Rocco

**Comment by gemiren** [comment]
How can I use this new FLAG_DISABLE_ID3_METADATA flag in the code? Any example code? Thanks.

**Comment by ojw28** [comment]
When creating an `ExtractorMediaSource`, pass something other than `DefaultExtractorsFactory`. For example if you know your app only has to play mp3 streams, you can instead pass:

```
new ExtractorsFactory() {
  @Override
  public Extractor[] createExtractors() {
    return new Extractor[] {new Mp3Extractor(Mp3Extractor.FLAG_DISABLE_ID3_METADATA)};
  }
}
```

**Comment by gemiren** [comment]
Thanks very much for the sample code!

**Comment by ojw28** [comment]
You can now disable ID3 metadata whilst still using `DefaultExtractorsFactory`, simply by calling `setMp3ExtractorFlags(Mp3Extractor.FLAG_DISABLE_ID3_METADATA)` on your `DefaultExtractorsFactory` instance.

I think we've improved things here sufficiently, and further optimization would be pretty in depth and is not something we're planning to look at any time soon. So I'll go ahead and close this issue.
