### ISSUE TITLE
ExoPlayer and Android TV

### ISSUE THREAD

**Issue by Stalker11** [google/ExoPlayer#2574]
Hi, I am trying to start playing HLS stream in Android TV, but video not playing. Method on PlayerError return IllegaStateException. But this video normal playing on phones and tablets. Why Android TV does not play? How I can fix this broken?

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
