### ISSUE TITLE
failed to Stream Online Video and make it cache able

### ISSUE THREAD

**Issue by sohrabafard** [google/ExoPlayer#258]
Hi,
I'm trying to use ExoPlayer for playback video over HTTP.
My video link is :
http://dl1.sanatisharif.ir/media/29/Hamayesh_Gosasteh_SanatiSharif_11.mp4

I can't Stream it using ExoPlayer,
And I want to save video after video was loaded and play it from cache. How Do implement cache and playback from cache? Can you give me any samples.

I read developer guide for exoplayer, but it's not sufficient for me, I'm new in android programming.

**Comment by ojw28** [comment]
- The stream plays back fine for me on both master and dev branches of ExoPlayer. It does take a long time for playback to start (it took about 30 seconds on my device). This is possibly due to the way the file is encoded, or due to your server having low bandwidth. It took a similarly long time to start when I tried playback with VLC on a laptop.

- Caching/downloading media is something you'd have to figure out and build yourself. Once the content is cached/downloaded, ExoPlayer provides the ability for you to play back from local storage.
