### ISSUE TITLE
Why ExoPlayer2 don't use MediaExtractor?

### ISSUE THREAD

**Issue by cauchywei** [google/ExoPlayer#2580]
When I try to learn ExoPlayer2 source code, I found that it do not using MediaExtractor + MediaCodec as usual rather than implement Mp4Extractor itself. There any problem with MediaExtractor ?

**Comment by ojw28** [comment]
There are a few reasons:

- MediaExtractor uses a threading model that's not well suited to ExoPlayer.
- It also doesn't provide as much control over buffering as we'd like.
- Implementation of the extractors under MediaExtractor varies between versions of Android.
- Extractors under MediaExtractor lack some functionality that we're able to support in ExoPlayer extractors.

Implementing our own extractors avoids all of the above. It also means that we can add new features to the extractors and have them work on all versions of Android, rather than adding them into the platform and have them work on new versions of Android only.

**Comment by cauchywei** [comment]
@ojw28 Thank your for your reply in time.
