### ISSUE TITLE
Volume problem

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2594]
Hello! In my player i want start playback with 0% volume. I set it before setPlayOnReady() but when it starts play for a moment volume is 100%. What should i do to make silence on the start of playback?

`player.prepare(streamSource);
 setVolume(0f);
 player.setPlayWhenReady(true);

private void setVolume(float volume){
        PrintString.printLog("Volume", volume + "");
        if (exist()) player.setVolume(volume);
}
`

**Comment by ojw28** [comment]
This sounds like an issue with your code rather than with ExoPlayer. There's insufficient context for anyone to be able to help (e.g. what is "exists()").

If you believe ExoPlayer doesn't correctly apply a volume set on it prior to playback, please fill out the issue template properly and supply all of the required information, including a bug report and clear reproduction steps.

**Comment by andrewlewis** [comment]
If you file a new issue please provide steps to reproduce in the demo app. I tried adding `player.setVolume(0f)` immediately after creating the player in [PlayerActivity.java](https://github.com/google/ExoPlayer/blob/b98de97/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L262) and audio is silent from the start as expected.
