### ISSUE TITLE
Using seek bar in demo app multiple times makes playback longer than duration of an audio file (mp3)

### ISSUE THREAD

**Issue by mzj** [google/ExoPlayer#2608]
### Issue description
When playing longer mp3 files in demo player, after using seek bar multiple times, playback continues (with normal sound) even after the timestamp gets bigger than duration. Best reproduced on longer, local files.

### Reproduction steps
Download the mp3 file from the following url [https://serialpodcast.org/season-one/3/leakin-park](https://serialpodcast.org/season-one/3/leakin-park), then add it into json playlist file:

`{
    "name": "Playlists",
    "samples": [
      {
        "name": "Cats -> Dogs",
        "playlist": [...]
      },
      {
        "name": "BugList",
        "playlist": [
          {
            "uri": "file:///location-of-a-file/serial-s01-e03.mp3"
          }
        ]
      },`
While the file is playing, use the seek bar to jump around backwards and forwards multiple times, after that jump near the end of the file, and observe how the playback continues even after the timestamp gets bigger than duration. 

### Link to test content
Download mp3 file from here [https://serialpodcast.org/season-one/3/leakin-park](https://serialpodcast.org/season-one/3/leakin-park). Just one of the examples.

### Version of ExoPlayer being used
r2.2.0 and r2.3.1

### Device(s) and version(s) of Android being used
Samsung S7 Edge (Android 7), and Asus ZenPad 10 (Android 5.0.2)

### A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/870713/bugreport.zip)

**Comment by andrewlewis** [comment]
If you're seeing the position increase a few seconds past the duration, it's probably due to the fact that headers in variable bitrate MP3s only provide enough information to see approximately in general: when seeking to a given position we have to interpolate between approximate byte offsets based on the table of contents, which can introduce some error in the timestamps of samples read after seeking. The longer the stream, the more sparse the table of contents, making the potential error larger. To seek exactly it would be necessary to load and parse the entire stream, which is wasteful.

If you're seeing the position increase more than a few seconds past the duration this is likely a different issue, so please provide detailed steps to reproduce. Thanks!

**Comment by mzj** [comment]
Thank you for the reply. 

I've got it on a video. In this case it went 6 seconds over duration. The maxium I've managed to get is around 15 seconds of mismatch.

**[Youtube link](https://www.youtube.com/watch?v=TCdVh7u8K4Y)**

It is probably the interpolating error, but it doesn't hurt to check.
