### ISSUE TITLE
VAST support

### ISSUE THREAD

**Issue by ehsan89** [google/ExoPlayer#2617]
Hi guys,

I'm trying to integrate VAST 3.0 ads into ExoPlayer. I want pre-roll ads which are provided by a server. I didn't find any solution for VAST integration with ExoPlayer. Is there any solution or any plan for future development?

Thank you all

**Comment by andrewlewis** [comment]
We plan to launch an extension wrapping the [Interactive Media Ads SDK](https://developers.google.com/interactive-media-ads/docs/sdks/android/) soon, which will make it possible to play VAST and VMAP ad tags. It's still work in progress but I will make sure this issue is updated once it's submitted to `dev-v2`.

**Comment by priyanshi-gupta** [comment]
Hello,
Any update on this?

**Comment by andrewlewis** [comment]
Please take a look at the [IMA extension](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ima) on the development branch.

**Comment by imarenco** [comment]
Hello @andrewlewis, how many time do you think to be a stable version of ima extension?
thanks! @ojw28

**Comment by ManojJangra** [comment]
Hello @andrewlewis  
How to use  IMA extensions in my application.

**Comment by andrewlewis** [comment]
The [README](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ima) has information on using the extension. Note: this is a preview, and we are still making improvements and fixes.
