### ISSUE TITLE
DASH Live Edge Calculation Erroneous

### ISSUE THREAD

**Issue by bascel** [google/ExoPlayer#262]
In the current ExoPlayer version (dev branch), the live edge for dynamic DASH content is usually calculated as the media end time of that segment, which is the last one described by the DASH manifest. This last described segment is determined as follows:
* (1) In case of a SegmentList, the last segment in the list is used
* (2) In case of a SegmentTemplate:
    * (2.1) If a SegmentTimeline is present, the last one described by the timeline is used
    * (2.2) If the duration field is present:
        * (2.2.1) The last segment in the current Period is used (determined using Period@duration or, indirectly as a default value, MPD@mediaPresentationDuration)
        * (2.2.2) The index is unbound, if no info about the last segment is present. In this case, the MPD@availabilityStartTime is used for determining the live edge.

For most cases, this will always work fine. However, for case 2.2.1 (using Period@duration), this is no correct behavior:
The Period@duration and MPD@mediaPresentationDuration describe the total duration (including the future) of a period or a stream. Meaning, at MPD@availabilityStartTime + MPD@mediaPresentationDuration, the stream will end. A usecase would e.g. be live content, where you don't want to update the MPD. So in this case, the ExoPlayer would set the live edge as the end time of the stream (which might be in the past, present, or future).
The correct approach would be to use the MPD@availabilityStartTime as in case 2.2.2.

Most simple fix i can think of is modifying the function getLiveSeekPosition in com.google.android.exoplayer.dash.DashChunkSource.java to always using the indexUnbounded==true part. (Note that this would apply the method also to cases 1 and 2.1)

More information can be found in the "Guidelines for Implementation: Live Services based on DASH
-IF IOPs" on DASH-IF:
http://dashif.org/w/2014/08/DASH-IF-live-v0.9.pdf

**Comment by ojw28** [comment]
As you've observed, we already handle indefinite live streams where the MPD doesn't need to be updated. The case you describe is different because, although it's a live broadcast, you already know the fixed duration of the broadcast.

One caveat that applies to both cases is that use of availabilityStartTime only works if the device can get a pretty accurate estimate of the server-side clock. Unless you want to assume that the device clock is accurate, this means a UtcTiming element needs to be present in the manifest (we don't currently use it, but will do soon - it's pretty easy to wire it up). Do you include such an element?

**Comment by bascel** [comment]
I also observed this issue (+- a few seconds wallclock time accuracy with NITZ synchronization). I solved this by implementing an SNTP client using several NTP servers from http://www.pool.ntp.org/en . This way, the accuracy improved to ~50ms at worst, which is good enough i guess. I didn't look into UtcTiming elements so far, maybe that's a better approach.

**Comment by ojw28** [comment]
Re your proposed fix - I agree we should use the unbounded case for 2.1 (although with an additional check that we're not trying to request a segment beyond the last index). I don't think we should use it for case 1 though, since my understanding is that in that case, only available segments should be listed in the SegmentList. In this case accurate client/server clock sync isn't supposed to be required, which it would be were we to use the unbounded case for it.

Does that sound reasonable/correct to you?

**Comment by bascel** [comment]
Sounds good to me.

**Comment by ojw28** [comment]
This should be fixed, aside from the need to properly sync using UtcTimingElement. Please verify this fixes the problem for you. Thanks!

**Comment by bascel** [comment]
Problem fixed, thanks a lot! =)
