### ISSUE TITLE
Question - how does the vp9 extension help?

### ISSUE THREAD

**Issue by ethanjyx** [google/ExoPlayer#2636]
Did you run any benchmark on how it performs? 
Does it only affect software decoding capabilities or does it affect hardware decoding capabilities as well? 
Will be helpful for us to have a better understanding of the benefit of using this extension. 

Thanks

**Comment by ojw28** [comment]
That's a complicated question to answer in practice. You're probably interested in performance relative to the VP9 decoder that the platform provides, but the platform decoder varies by device and there's nothing like a (working) platform API for querying how performant a platform decoder is. Performance of both the platform decoder and the one in the extension may be affected differently by things like thermal CPU throttling, what else your app is doing and other processes that are consuming CPU, so relative performance may vary at runtime. Furthermore, what "performance" means really depends on what you want to optimize for. If you're playing 10 second clips there's probably no point optimizing for power consumption. If you're playing full length movies, it's far more important. So it's a really messy topic in practice. We provide the extension as an option, and leave it up to you to evaluate whether it works well for you (e.g. by looking at analytics data gathered from your app, evaluating your priorities and so on).

As some general guidance:

* One advantage of the extension is that you'll be running the exact same decoder software on all devices. This will better isolate you from variation (and possible bugs) in the different platform decoder implementations. If your requirements aren't particularly strenuous (e.g. short, low resolution videos) then performance probably isn't that important, in which case it may well make sense to use the extension just to eliminate this kind of potential variation between devices.
* If a device provides a hardware VP9 decoder then it will probably consume less power than the extension decoder. This is particularly relevant for long duration content. You'd hope it would be more performant in terms of max resolution / frame-rate capability as well, but I'm not sure that's a given. There's no platform API to query whether a decoder is hardware based or not, since in practice the line is quite fuzzy, but if it's called "OMX.google.vp9.decoder" you can pretty safely assume it's a Google provided software decoder. If it's something else then it's probably provided by the system-on-chip vendor and is likely hardware accelerated in some way.
* If the platform decoder is "OMX.google.vp9.decoder" then using the extension is likely to give better performance, particularly when running on older Android releases, simply because the extension will be using a more recent version of libvpx.
* There is of course an overhead in terms of application size when bundling the extension, which is not incurred when relying on the platform decoder.

@vigneshvg - Anything else to add (or anything I've said that's inaccurate :))?
