### ISSUE TITLE
Expose file size in Format for regular on-demand media files

### ISSUE THREAD

**Issue by Teviz** [google/ExoPlayer#2638]
In demo application, PlayerActivity shows how to get format object and use its properties such as bitrate, trackId, resolution and so on.But there is no way to get file size.
In most situation, we may play mp4 file.I can calculate the value of  timescale / duration to get the file size in MP4Extractor#processMoovAtom method, but I don't think its a good idea.

So is there any solution to get file size easily just like using ExoPlayer#getDuration method to get duration? 
Or if not, what's the best way to get file size for the time being.

**Comment by ojw28** [comment]
I'm not sire I agree that it's the player's responsibility to tell you the size of a file. Can't you just query it directly (if it's a local file) or make a HEAD request (if streaming over the network)? What is it that you actually want it for?

**Comment by Teviz** [comment]
Maybe I compare the method to get file size with ExoPlayer#getDuration() method is extreme, what I wish is to have a way to get it.
Because file size and duration is from the same source, such as metadata of videos, so I think they may be on the same level. 
Query twice is ok, but it seems to be a little bit redundant. File size is a part of the media or track, so when I play the media, file size is access to me.
I think there are some situations that this method may be useful, for example, I want to exchange different track not only based on the bandwidth but also concerning in the file size I will download.

**Comment by ojw28** [comment]
> Because file size and duration is from the same source, such as metadata of videos, so I think they may be on the same level.

One thing to consider is that in many cases the file size of a track is undefined (or not possible to determine in a reasonable way). For example in HLS and SmoothStreaming each track is fragmented into many separate files. The same applies to DASH except in certain on-demand profiles. For live playbacks the file size is always undefined. The only case where file size does make sense is playback of regular on-demand media (e.g. an mp3 or an mp4).

> I think there are some situations that this method may be useful, for example, I want to exchange different track not only based on the bandwidth but also concerning in the file size I will download.

I'm not sure I follow this. If you're doing adaptive playback (e.g. DASH, HLS and SmoothStreaming), the `Format` for each track will have the bitrate field set, which you can use as a relative measure of file size. If you're considering multiple tracks not in the context of an adaptive playback, I'm not sure exactly what your use case is.

We could consider add file size just in the case of regular on-demand media playbacks, if the server provides it to us. But I'm still confused about your use case. What is it exactly that you're trying to do? How do you end up with a single media source where track bitrates are unavailable, and where knowing the file size of each track can be used to implement a feature that it's otherwise not possible to build? Thanks!

**Comment by AquilesCanta** [comment]
Have you considered injecting a DataSource that provides what you need? You could intercept the header information yourself in that case. I haven't tried but subclassing DefaultHttpDataSource might work for you.

**Comment by Teviz** [comment]
@AquilesCanta 
Thank you for your inspired suggestion. It's a good idea to get some information which I need. But for file size, it's not defined in header for some media, and content-length may not mean the whole size of the media.

**Comment by Teviz** [comment]
@ojw28 
I admit that file size is no sense in most situations, and for my original use case, there are other ways to achieve it. I'm just some obsessional with the property in response which I can't easily get and interested in discussing it.

I agree that file size make sense only in on-demand media, but I also found that getDuration method works in separate files media and returns the duration of each separate file. File size is undefined in many use case but so it is for duration in some case like live playbacks.
I think file size is similar to duration,  now that some implements of duration exist, why not give them to property file size too.

The way to get file size is not necessary, but it may be convenient. It's just my opinion.
Thank your for your reply, ojw.

**Comment by ojw28** [comment]
It's still somewhat unclear exactly what your use case is. Clearly describing a valid use case might motivate someone to take a look. Without a clearly described or possibly invalid use case this is less likely. Marking this as an enhancement for tracking, in any case.

**Comment by ojw28** [comment]
Closing this as the feature request has never been justified by a particularly valid use case.
