### ISSUE TITLE
Track extension and bitrate

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2641]
I write player and trying to get file extension, bitrate and sample rate. My question is why bitrate always returns -1 and how to get file extension?
P.S. sample rate returns as expected.

@Override
            public void onAudioInputFormatChanged(Format format) {
                StringBuilder builder = new StringBuilder();
                builder.append(format.codecs);
                builder.append(", ");
                builder.append(format.bitrate);
                builder.append(", ");
                builder.append(format.sampleRate);
                builder.append("Hz");
}

**Comment by ojw28** [comment]
- Given you have to tell ExoPlayer the URL (or file) that you want us to play, surely you know what the file extension is already (because you've given it to us)?
- We only report bitrate if it's defined by the media. This is typically true in DASH, HLS and SmoothStreaming where bitrates are specified at the manifest level. It's typically not true for other media, in which case we set the value to -1 as indicated by the documentation.
