### ISSUE TITLE
Issue with HLS text format. 

### ISSUE THREAD

**Issue by AntonAFA** [google/ExoPlayer#2651]
Hello after upgrading to exoplayer 2.3 I started to have following issue. As i see it happens with all the HLS sources. When receiving Tracks data, there is always an additional text track with id: 1/8219 and application/cea-608 value. It is also reproducible in your demo application. In any case, i wanted to understand what is the use-case for this text track and is it a bug?

**Comment by AquilesCanta** [comment]
It has been this way since the beginning of time (or at least since Exo V1). What did change recently is that we assign an id to the track. We proactively declare a 608 track (service 1) because, as you can observe in the Apple sample HLS stream, the manifest does not always declare the CC service. TSs could also declare the track through a caption service descriptor, but often they don't.

The id is not constant however, it is the PID of the containing H264 elementary stream + 8192 (maximum valid PID + 1). I hope this answers your question. If you know that no CC service is provided in the stream, just ignore it.
