### ISSUE TITLE
getCurrentPosition() sometimes returnes 0 when the video is in "pause" state

### ISSUE THREAD

**Issue by jclova** [google/ExoPlayer#2655]
### Issue description
I am calling player.getCurrentPosition() to store current position before onPause() is called. However, it sometimes returns 0 (when the video is paused) so the player starts from the beginning when the app resumes.

### Reproduction steps
1. Seek to somewhere in the middle of the video. (I am testing HLS streaming)
2. Pause the video
3. Press power to turn off the screen and then turn on the screen to resume back to the app. At onPause(),  player.getCurrentPosition() gets called.
4. Repeat step 3, until player.getCurrentPosition() returns 0 onPause().

### Version of ExoPlayer being used
ExoPlayer version: 2.3.1

### Device(s) and version(s) of Android being used
Multiple devices

**Comment by ram992** [comment]
This problem is there even in 2.2.0, can some one post a fix for this

**Comment by ojw28** [comment]
Are you certain `player.getCurrentPosition()` is returning 0? If you've replicated the logic in the demo app, is it possible that the real issue is `player.isCurrentWindowSeekable()` returning false?

I was able to reproduce a couple of times in the demo app, but the problem in that case was `player.isCurrentWindowSeekable()` returning false. This occurs if the steps are performed so quickly that the player doesn't manage to load a timeline between the activity being resumed and paused.
