### ISSUE TITLE
How to detect live streaming vs VOD in ExoPlayer

### ISSUE THREAD

**Issue by shailesh-fusionitechnology** [google/ExoPlayer#2668]
Is there is any method available right now for distinguish between live streaming and VOD?

I have already seen track [#2099](https://github.com/google/ExoPlayer/issues/2099) that is posted on dated Nov 23, 2016. On that time there is no such method available for distinguish between live streaming and VOD.

Since the above post is almost 5 months old. Now I want to conform that **Is there is any method available right now for distinguish between live streaming and VOD**?

I have also try by get duration of video but unable to find distinguish between Live Streaming and VOD?

**Comment by ojw28** [comment]
As described in the issue you reference, you can use [isCurrentWindowDynamic](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#isCurrentWindowDynamic--) for this.

**Comment by Teviz** [comment]
@ojw28 
I found that method #isCurrentWindowDynamic sometimes is not accurate. 
When play **FLV** media, the method isCurrentWindowDynamic returns false because it's a single file media, but it may be live streaming. 

Presently I check the result of [isCurrentWindowDynamic](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#isCurrentWindowDynamic--) && [isCurrentWindowSeekable](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#isCurrentWindowSeekable--) to distinguish between live streaming and VOD. I wonder is there a better way to do that too.

**Comment by ojw28** [comment]
Yes, that's a good point. The method described will only work for DASH, HLS and SmoothStreaming.

You can get on-demand (i.e. non-live) content that's not seekable. You're probably better off looking at the duration (ExoPlayer.getDuration). If it's unknown, that's a pretty good sign that you're dealing with a live stream. So you could try OR'ing this approach with the one based on the window being dynamic.

By the way, did you mean || instead of && in your comment? I don't think && is what you'd want?

**Comment by Teviz** [comment]
Oh yes, sorry for that, I made two mistakes. I was intent to say isCurrentWindowDynamic || !isCurrentWindowSeekable.

By the way, I tried to use getDuration, but in hls live streaming, getDuration returns the duration of .ts file which is an exact number instead of unknown. So it seems to be imperfect too.

**Comment by Teviz** [comment]
Oh yes, sorry for that, I made two mistakes. I was intent to say isCurrentWindowDynamic || !isCurrentWindowSeekable.

So the recommended way is to use isCurrentWindowDynamic || getDuration == C.TIME_UNSET to solve the problem. Thanks you for that.
By the way, in which situation the on-demand content is not seekable?

**Comment by ojw28** [comment]
That approach seems like it would get it right in the vast majority of cases, yes. Give it a try and let us know.

It's actually quite difficult to determine whether a stream is live in the completely general case. If you compared an on-demand stream that doesn't define its duration or seek information and is served from a server that doesn't tell you the content length, that would be impossible to distinguish from a genuine live stream. Admittedly that combination is quite far fetched.

On-demand media isn't seekable in the case that it doesn't define any seek information (e.g. in the media container) to enable the player to perform an efficient seek. Raw MPEG-TS streams are a good example of this (HLS is seekable because the media playlist effectively provides seek information at a higher level).

**Comment by ojw28** [comment]
Given there are lots of properties you could look at to try and determine whether a stream is live, we should probably add an isLive method and implement our best-attempt logic there (which can be updated over time, if needed). Marking as an enhancement.

**Comment by ojw28** [comment]
@tonihei - Reassigning because this touches on `Timeline` and `Player`. It's probably preferable to plumb `isLive` through `Timeline.Window` and having `Player.isCurrentWindowLive`, so that sources can potentially use additional information to control how `isLive` gets set. For example `ProgressiveMediaSource` should probably set to `isLive=false` if the response has a known content length, even if the duration still cannot be determined.

It might be nice to fix this so that we can remove [this not exactly accurate troubleshooting entry](https://exoplayer.dev/troubleshooting.html#how-can-i-query-whether-the-stream-being-played-is-a-live-stream), if it's relatively straightforward. Although perhaps it fits better into the bigger playlist simplification work.
