### ISSUE TITLE
exoplayer subtitles are disappearing when the subtitle come across to start of minute. Ex: 03:00, 25:00 etc. How can i fix this problem.

### ISSUE THREAD

**Issue by BurakDurmus** [google/ExoPlayer#2669]

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
