### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by hare989** [google/ExoPlayer#2676]
Hello,

How would ExoPlayer work with servers which implements Server Name Indication?

**Comment by andrewlewis** [comment]
If you're using `DefaultHttpDataSource` I guess it should just work: it uses `java.net.HttpURLConnection` and, according to this [best practices](https://developer.android.com/training/articles/security-ssl.html) page, the `HttpsURLConnection` subclass supports SNI since Android 2.3 (API level 9, which is lower than ExoPlayer's minimum API version). Have you tried it, and if so was there some issue?

**Comment by hare989** [comment]
Hello,

Thanks for reply. We have tested streaming in ExoPlayer from two secured hosts served from one IP address, both having different SSL certificates, and we can confirm that ExoPlayer/ DefaultHttpDataSource/java.net.HttpURLConnection SNI support is working fine when establishing secure connection to wanted hostname.
