### ISSUE TITLE
unable to play DASH created using bitmovin encoder

### ISSUE THREAD

**Issue by nikhilreprime** [google/ExoPlayer#2690]
I am new at this video player
I used https://bitmovin.com/tutorials/setup-adaptive-bitrate-streaming-dash-hls/
to create DASH for sample video
and placed it on google cloud storage 

created entry in media.exolist.json but player is unable to play the video

  {
     "name": "Nikhil DASH new",
     "samples": [
       {
         "name": "uptown funk Dash new",
         "uri": "https://storage.cloud.google.com/ck-staging/bitmovin/uptown_new/558944_7f4090decfd0b199362e9da25b45c4c6/558944.mpd",
         "extension": "mpd"
       }
     ]
   },

can you please tell if there is something wrong with format or i missed something 

thank you

**Comment by ojw28** [comment]
Your URL appears to be redirecting to `https://accounts.google.com` rather than serving the MPD. It does this even if you simply try and load it in an incognito window in Chrome. So it looks like a problem with the way you're hosting the content.

As an aside, it's recommended that you avoid using underscores in your URLs. Use hyphens instead.

**Comment by nikhilreprime** [comment]
thanks
This was such a blunder
