### ISSUE TITLE
getBufferedPercentage value on what listener ?? onBufferingStart or End does not exist !?

### ISSUE THREAD

**Issue by Khoosham** [google/ExoPlayer#2691]
i need to get the Buffered Percentage of my video when playing.
on what method should i call this function to get the changing value as the video buffers.

i have tried to call it like this but it returns only a single value and does not change as the video buffers.

@Override
  public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        if (playbackState == ExoPlayer.STATE_BUFFERING) {
           bufferpercentage.setVisibility(View.VISIBLE);
           bufferpercentage.setText(String.valueOf(player.getBufferedPercentage()));
       }
}

**Comment by Khoosham** [comment]
i have try to use a timer to update the buffer percentage but it is always 0 
the percentage changes only when seeking the  player and that too it does not report real time values for every 2 sec below. is that a bug on the function that is setting the buffered percentage ?


Timer timer = new Timer();
        TimerTask timerTask;
        timerTask = new TimerTask() {
          @Override
          public void run() {
            runOnUiThread(new Runnable() {
              @Override
              public void run() {
                Log.v("Buffering","update percentage");
                int buffer = player.getBufferedPercentage();
                bufferpercentage.setText(String.valueOf(buffer));
              }
            });

          }
        };
        timer.schedule(timerTask, 0, 2500);

**Comment by ojw28** [comment]
There is no known issue with `getBufferedPercentage`. If you're playing a live stream or a stream with unknown duration then 0 would be expected because it's not possible to provide a percentage when the duration of the stream is unknown. Note that you can use `getBufferedPosition` instead in such cases.

There's insufficient information provided in this issue for us to assist further, and it does not follow the issue template. So I'll go ahead and close this. If you're still having problems, please file an issue that properly adheres to the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by Khoosham** [comment]
but the duration of the video is only known after the buffer is complete at the first time. at the end of the seekbar the end time is displayed. if i try to seek the video after a buffer is complete (at least once) the buffer value changes but its not updating the values as it should as the end time is already known by then. it remains as a fixed value
