### ISSUE TITLE
Add method to SimpleExoPlayer if a surface exists

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2701]
I'm using ExoPlayer in a RecyclerView and I'm clearing the surface in `onViewRecycled`. So I have to set it again in the `onBindViewHolder`.
However doing so each time `onBindViewHolder` is called seems very expensive. So I would like to know if the `SimpleExoPlayer`already has a surface and skip setting it in that case.
I can't simply keep track if I set it as exoplayer seems to remove the surface itself when it gets destroyed.

Also after scrolling a few times up and down the player stops playback. After a manual `seekTo` it works again.

**Comment by ojw28** [comment]
I don't really understand this request. If you pass a `SurfaceView` or `TextureView` then `SimpleExoPlayer` will indeed clear the surface if it's destroyed, but it will also re-instate the surface if it's recreated, which should happen if/when the view becomes visible again. So I don't see `SimpleExoPlayer`s handling of the surface lifecycle as problematic. You can also completely avoid having `SimpleExoPlayer` manage the surface lifecycle by using `setVideoSurface`, passing the surface directly rather than the view that holds it. So I think tracking what you've set yourself should be sufficient.

It's more likely you're running into a pretty fundamental limitation of the underlying platform, which makes it difficult to switch the targeted surface without the player having to skip ahead to the next keyframe in the media. This is discussed in a few issues already on the tracker, for example https://github.com/google/ExoPlayer/issues/318. https://github.com/google/ExoPlayer/issues/677 tracks our efforts to make switching surface smoother. We think we should be able to release a good solution for Marshmallow+ in the near future. For earlier versions of Android there's just not a whole lot we can do.

**Comment by ojw28** [comment]
Note: My comment about skipping ahead to the next keyframe applies to the case where you don't disable the video renderer. If you do disable the video renderer (e.g. as in #2703) then this is not correct, but in that case you take the hit of having to re-buffer instead.

**Comment by ojw28** [comment]
Closing because I still don't understand the request, and clarification has not been provided.
