### ISSUE TITLE
Seekbar lags on Video seek

### ISSUE THREAD

**Issue by wingoku** [google/ExoPlayer#271]
When I try to seek the progressBar to an unbuffered position, the seekbar jumps back to the position from where the seek started. After a couple of seconds (20-30 secs) it moves to the seekd position. The seekbar is being updated on the same thread as player or on UI thread. Any suggesotins to resolve this?

**Comment by ojw28** [comment]
What position does the player actually report if you call getCurrentPosition? If it returns the correct position, then the issue is a UI one, rather than a player bug, and you should fix whatever UI you're using to show the progress bar.

If it's returning an incorrect position, you need to provide more details (e.g. what stream are you actually playing, on what device etc).

**Comment by wingoku** [comment]
@ojw28 I am using MediaController with MediaPlayer to render video. mediaPlayer.getCurrentPositoin() returns current playback position of the player.

**Comment by ojw28** [comment]
If you mean the Android http://developer.android.com/reference/android/media/MediaPlayer.html, then this project is unrelated. I think you'd need to file an issue on the Android issue tracker:

https://source.android.com/source/life-of-a-bug.html
