### ISSUE TITLE
How to get a file from cache?

### ISSUE THREAD

**Issue by Charles-ljc** [google/ExoPlayer#2711]
I use CacheDataSourceFactory to cache some video, but now I want to get the cached file and save to sdcard, What should I do ?

**Comment by ojw28** [comment]
It's not correct to assume that we cache the media as a simple file. We may do things like fragment the media into multiple cache files, for example, so that the cache eviction policy can work with finer granularity than a whole piece of media. We may also arbitrarily change the on-disk cache format at any time.

So there is no direct files access. If you want to read the data from the cache you should do so by instantiating a CacheDataSource instance and then reading from it in the normal way (i.e. calling `open` with a `DataSpec` corresponding to the piece of media, calling `read` to read the data, then calling `close` when you're done). You could write the data into a file as you're reading it, if that's what you really want.
