### ISSUE TITLE
Support for EBU TT D subtittle

### ISSUE THREAD

**Issue by praveen10074** [google/ExoPlayer#272]

**Comment by praveen10074** [comment]
will exoplayer support EBU TT D subtitle parsing and rendering ?

**Comment by nimdokai** [comment]
@ojw28 
could you provide update on situation - will it be supported in the near future?

**Comment by ojw28** [comment]
This is low priority currently, I'm afraid.

**Comment by ojw28** [comment]
As I understand it EBU-TT-D is a profile of TTML, and we support TTML. So I think we can mark this as fixed? If anyone thinks otherwise, please reply here and we'll re-open the issue.

Aside: It's likely we don't support all of the features allowed by the EBU-TT-D profile, but it's also likely that many of those features are never used in practice. It's also likely that the experience degrades in a sensible/acceptable way where features are not supported. If you come across this issue having encountered a specific shortcoming or missing feature that you need, please file an equally specific issue :).

**Comment by nigelmegitt** [comment]
> EBU-TT-D is a profile of TTML, and we support TTML. So I think we can mark this as fixed?

Yes, but no. TTML is extensible, and EBU-TT-D defines some important extensions relative to TTML.

> It's likely we don't support all of the features allowed by the EBU-TT-D profile, but it's also likely that many of those features are never used in practice

The logical conclusion of these two statements is that you don't know if you support all the features allowed by the EBU-TT-D profile. As a point of fact EBU-TT-D is probably the smallest profile of TTML that's in widespread use, and most of the features are likely to be used because someone else (i.e. the [EBU Timed Text group](https://tech.ebu.ch/subtitling)) has already done the selection work for you. (I'm one of the chairs of that group)

A good resource for understanding the usage and importance of the features is the [BBC's Subtitle Guidelines](http://bbc.github.io/subtitle-guidelines/#Example-EBU-TT-D-document).

> It's also likely that the experience degrades in a sensible/acceptable way where features are not supported. 

Generally no, but it depends to some extent on the feature. There may be a small number of features (like 2 or 3) where this would be true. For the rest, you're probably making the accessibility of the content worse if you don't support the feature.

> If you come across this issue having encountered a specific shortcoming or missing feature that you need, please file an equally specific issue :).

Ok fair enough. I think it would also be worth explaining how to contribute tests to check that a feature remains supported and there isn't a regression.

**Comment by ojw28** [comment]
Thanks for the additional information. Just to clarify, we are committed to doing a great job of supporting subtitles, particularly when there are compliance issues involved. We've resolved several specific shortcomings with our EBU-TT-D support recently (e.g. https://github.com/google/ExoPlayer/commit/24b16f34195070794bcd98db27d84e8dc716a3d2, https://github.com/google/ExoPlayer/commit/17abab455e5d9e9008bc266ac48b32bf5345ed6c, https://github.com/google/ExoPlayer/commit/15413548193863a7377fb0326c5cd5e44498f605). We'll continue to resolve issues as they're reported.

The only reason we handle subtitle issues in more of a reactive way is that the proactive approach would be a huge time sink for us, given the number of subtitle formats, differing opinions on which ones are important, and that in practice many features defined by their specifications are rarely used. Given we can't instantly implement all features from all subtitle formats, a reactive approach helps us to focus on the most pressing issues first. If EBU-TT-D is minimal and all features are widely used then the good news is that our reactive approach should do a good job of fully implementing the specification :) (it's possible we're quite close already).

> I think it would also be worth explaining how to contribute tests to check that a feature remains supported and there isn't a regression.

We'd definitely welcome contributions in this area. There's nothing particularly special about contributing tests (vs any other changes). The project already has unit and integration tests (in general; not specific to EBU-TT-D), and we run these tests on every commit internally. So I think it's just a case of adding additional tests for whatever cases you'd like to be covered. If you have a specific test case in mind and are unsure how to implement a test for it, then we'd be happy to provide some guidance to help get you started :).
