### ISSUE TITLE
Why discarding from chunks after a certain chunk instead of discarding a single chunk?

### ISSUE THREAD

**Issue by xushichang0** [google/ExoPlayer#2721]
In ExoPlayer, when network condition becomes better, TrackSelection finds the first chunk with lower quality in the buffer and calls discardUpstreamMediaChunks to discard all following chunks. It is possible that some chunks of good quality are also discarded.

My question is that why ExoPlayer does not check each chunk and only discard the ones with lower quality? Thanks.

**Comment by ojw28** [comment]
Because it's really hard to implement it properly, in a way that neither adds a whole bunch of complexity or makes things less efficient elsewhere.

Note that this code isn't actually active in V2 at the moment (we actually never discard). There's a TODO in ChunkSampleStream to start applying the discard logic again, although in practice it's unclear whether it's that worthwhile. There's an argument to saying that if network conditions were poor and yet you've got a big enough buffer to be discarding from it, you should have probably been requesting a higher quality.

**Comment by xushichang0** [comment]
Thanks for your response.

Could you tell me more about the complexity of proper implementation? I notice the current implementation of ExoPlayer uses a rolling buffer to store the chunks. Is this the main cause why it can not discard a single chunk? Thanks.

**Comment by ojw28** [comment]
That's one reason. We could store each chunk in its own buffer, but there are negative implications to doing so (it's not possible to do this without incurring one of the following: less efficient packing of buffered media in memory, significant additional complexity, additional memory allocations).

There are a few other reasons as well. It's hard to provide an exhaustive list, but as an example (that I haven't thought through particularly carefully, so sorry if this makes no sense :)) suppose your buffering policy wants to place a limit on the size in bytes of buffered media. How would you enforce this limit if it were possible to have to replace chunks from the middle of the buffer? You'd need to (potentially) discard some chunks from the end of the buffer regardless of their quality in order to avoid violating the policy, which would require the discard logic to know about the details of the buffering policy, which would require dependencies between components that are currently unrelated, as well as additional complexity in components like `LoadControl`.

So yeah, there are lots of fairly nuanced trade-offs involved and it's likely not worth the additional complexity/cost.
