### ISSUE TITLE
Bitrate for webM file formats

### ISSUE THREAD

**Issue by senthilkumar2012** [google/ExoPlayer#2735]
Does bitrates are supported for webM file formats?
Tried debugging the library, but the call back never gets triggered.
Not sure whether library issue or file format (webM) does not support bitrates.

**Comment by ojw28** [comment]
Please help us to help you by providing sufficient information when asking questions. "The call back" is not descriptive enough for us to know which callback you're referring to. It's most likely working as intended, however, since bitrate is generally only useful in the context of adaptive (e.g. DASH / SmoothStreaming / HLS) playbacks.

**Comment by senthilkumar2012** [comment]
For formats like
https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-vp9-360.webm
http://demos.webmproject.org/exoplayer/glass_vp9_vorbis.webm, the callback method onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason,
      Object trackSelectionData, long mediaTimeMs) is not triggered by the exoplayer library.
Is this a library issue or webM formats are non adaptive streaming?

**Comment by ojw28** [comment]
A plain WebM file is not adaptive. Adaptive streaming formats are: DASH, HLS, SmoothStreaming.

**Comment by senthilkumar2012** [comment]
thank you for the response. Is there any method to fetch the current bitrate from exoplayer other than the call back onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason,
Object trackSelectionData, long mediaTimeMs)

**Comment by ojw28** [comment]
Estimates of actual link bitrate are available from `DefaultBandwidthMeter`, but that's different from media bitrate. I don't think there's a way of fetching the media bitrate for non-adaptive media.

It's pretty unclear what you're actually trying to do. Saying you want to get the current bitrate doesn't really answer the question, since that's not by itself useful, and it's unclear what you can actually usefully do with the information you're looking for. What is the actual useful user/developer feature that you're trying to implement?

**Comment by tanoj** [comment]
Thanks for your quick response. Let me clarify here.  
Our product reports all metadata such as platform, CDN, asset name, bitrate etc about the video content in real time while it is being played by any User using any player. But in this case,  bitrates are not reported for webM video contents in Exoplayer.
We are trying to find the way  to fetch bitrates for webM content in exoplayer ,so that we can report it in our product dashboard.

**Comment by ojw28** [comment]
What bitrate do you actually want? For WebM I think bitrate would just be considered the file size divided by the duration. Exposing the file size is tracked by https://github.com/google/ExoPlayer/issues/2638. The duration is already exposed, so you'd have enough information to calculate the bitrate at that point.

Also, if you're in control of the content on the server-side then you should already know the bitrate of everything you play, without having the client report it back to you.
