### ISSUE TITLE
when in service play music, setPlayWhenReady(false) is not work 

### ISSUE THREAD

**Issue by huyongli** [google/ExoPlayer#2746]
my service is Foreground service.
when play music in background, i use setPlayWhenReady(false)  to pause music, but it not work. I don't know why? But in activity this is work .

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
