### ISSUE TITLE
Synchronization issue with applying specific effects on HLS video stream using ExoPlayer

### ISSUE THREAD

**Issue by shalin186** [google/ExoPlayer#2753]
Hi,

I am playing an HLS video stream in my android app using ExoPlayer. Everything works fine except for one particular scenario where I suppose it is a synchronization related artifact.

So in my app, I am trying to add some effect (e.g. zoom effect or some rotation effect) on the hls video stream at particular time instants. The video stream I have is 30fps.
For example, each of my HLS segment is 1 second long. And I want to apply such effects starting at HLS segment number 12 or at the starting of 12th second in the stream.

So what I do in my app is, I call getCurrentPosition(), which should return current playback position. I have placed this call inside OnDrawFrame(), which is called every time the screen is refreshed, which is roughly 60 times per second on my S7.

So in my app I have some thing like this:
onDrawFrame(float v) { // called periodically every 0.016666666666667 seconds
// check if current playback position has just crossed 12 seconds mark
    if (player.getCurrentPosition() >= 12000) {
        // code to apply new effects
    }
}

This code works fine for the most part. But I see that the new effect is either delayed or advanced by couple of frames. and not being applied right at the first frame of the 12th segment. This is not always the case but happens roughly 50% of the time. And I see a very quick flicker when this happens.

Any suggestions on what I am missing here? How to make sure that the new effects I am applying are being applied exactly from the first frame of 12th segment?

I see the same behavior on S6, S7 and Pixel.

Thanks a lot in advance.

Shalin

**Comment by andrewlewis** [comment]
As general guidance, to get this to work well I think you'd need to have some code that decides whether to apply the effect based on the frame timestamp before the frame is rendered, rather than polling the player position. The player position is determined by the audio track, but video renderers may show frames (imperceptibly) late or early relative to this position.

To give more specific help it would be useful to know what renderer you're using (e.g., `MediaCodecVideoRenderer`) and how are the effects applied (e.g., using an pixel shader).

**Comment by ojw28** [comment]
Closing due to lack of information.
