### ISSUE TITLE
Get duration without preparing

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2762]
Is it possible to get the duration of a file without preparing the full player? Preparing each single file the user owns takes forever.

So far I was using MediaMetaDataRetriever but that does not handle files that can be handled by exo player extensions.

**Comment by ojw28** [comment]
How would you expect this to work quickly, given at a bare minimum something has to parse some metadata out of each file to extract the duration? If you're dealing with local files, I think the normal solution to this would be to build an index (e.g. stored as a database), so that you only have to do it once.

**Comment by PaulWoitaschek** [comment]
Yes, this is done once. But it takes several minutes. And it's significantly slower than the extractor. 

Is just wondered if there is a quicker way to retrieve the meta data only.

In other threads and commits I read about ID3 tags, but i could not find the method where I can parse the metadata of a file.
Is that possible?

**Comment by PaulWoitaschek** [comment]
I was actually wrong. ExoPlayer is way faster than the MMR.
However it would still be great to have a unified interface for getting the meta data, exo player parses.

**Comment by ojw28** [comment]
ID3 tag metadata defined at the start of a piece of media is always static. The duration of a piece of media may change during playback (for live streams). So I think it's appropriate that they're exposed separately.
