### ISSUE TITLE
Offline DRM Playback Sample

### ISSUE THREAD

**Issue by nosmirck** [google/ExoPlayer#2763]
_I'm not using the template because I'm not filing a bug report or reporting an issue, bur rather requesting a wiki, sample, documentation, or some form of direction_

I'm sorry if this request is not allowed, but since not everyone has a lot of experience with this, it would be great if the sample demo project included an offline playback sample.

I my case, I have no idea on how to request the licence, how I should store on device, what to pass to the player, etc.

So far, I managed to get the direct URL to the encrypted .mp4 from the .mpd, download the file and save it to the device's root folder, from here, I'm stuck, any help would be much appreciated.

Thanks in advance!

NOTES:
- I tried playing the .mp4 with the default player on my phone, it starts the first couple of seconds and then closes with a message saying that it can't play the video, it means the encryption is working (I guess) and that I have the correct file downloaded
- The .mp4 file has the correct size and I get no errors every time I download it.

**UPDATE:**
I've tried to use the [OfflineLicenseHelper Class](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html) with no luck. Adding a sample of how to use it to the demo app would be helpful.

**Comment by ojw28** [comment]
It sounds like you're trying to implement offlining of DRM protected DASH content, by downloading one of the video variants, and presumably one of the audio variants too. We'll be supporting this directly in the future, and this is tracked by https://github.com/google/ExoPlayer/issues/2643. Please follow that issue for updates.

We do not plan to provide a sample or guidance before we add support (since doing so is more or less equivalent, and so is similarly something that's pretty complicated and takes some time to get just right!).

**Comment by m35w** [comment]
@ojw28 Could you please give us some estimates about release date of this feature?
I'm especially interested in offline HLS content (with DRM), but also DASH one (I understand it's the higher priority for you).

I'm about to start implementing similar functionality but, as it happens that ExoPlayer team is working to add this functionality internally, maybe it's worth to wait for it, but I would need to know when can we expect the release (of course I'm aware it's hard to give the exact time, but some estimate would be great)?
