### ISSUE TITLE
player local mp4 use large memory

### ISSUE THREAD

**Issue by leach-chen** [google/ExoPlayer#2771]
**Issue description**

when I use the exoplayer2 play the local mp4 file.it use large memory
if the file is 10M,it will use 20M memory
if the file is 40M,it will use 40M memory,
the file more big, the more memory will use,what wrong with it?

**Reproduction steps**

`Handler mainHandler = new Handler();
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
final LoadControl loadControl = new DefaultLoadControl();
player =ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
player_view.setPlayer(player);
Uri mp4VideoUri = Uri.parse("file://" + Environment.getExternalStorageDirectory().getPath() + "/a.MP4");
DefaultBandwidthMeter bandwidthMeter1 = new DefaultBandwidthMeter();
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,Util.getUserAgent(this, "yourApplicationName"), bandwidthMeter1);
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
MediaSource videoSource = new ExtractorMediaSource(mp4VideoUri,dataSourceFactory, extractorsFactory, null, null);
player.prepare(videoSource);
player_view.setUseController(false);`

**Version of ExoPlayer being used**

r2.3.0

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

This is possibly caused because the file's tracks are poorly interleaved.
