### ISSUE TITLE
Opus reported as non seekable but it is

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2775]
When building the opus extension with the latest Opus version (1.1.4) and ExoPlayer 2.4.0, the player reports [Sample File](https://github.com/google/ExoPlayer/blob/release-v2/extensions/opus/src/androidTest/assets/bear-opus.webm) as not seekable. (Android Emulator API 18)

However it is seekable without any problems. I wonder if there is a general issue with isSeekable for opus.

**Comment by ojw28** [comment]
The fact that the file contains an Opus stream isn't relevant to whether it's seekable or not. The container is what's important, which is WebM in this case. The file is not seekable as it does not contain a Cues element. Note that the [WebM guidelines](https://www.webmproject.org/docs/container/) in effect say muxers are required to include cues data:

> Muxers should treat all guidelines marked SHOULD in this section as MUST. This will foster consistency across WebM files in the real world.

Followed by:

> WebM files SHOULD include a keyframe-only Cues element.

The [Matroska specification](https://www.matroska.org/technical/specs/index.html) also specifies that the Cues element is required, saying this about the Cues element:

> Should be mandatory for non "live" streams.

The sample does not seek without any problems. A forced seek restarts playback from the beginning, regardless of what seek position you pass. Most likely you just don't notice the difference because the whole sample is only three seconds long :)...
