### ISSUE TITLE
Bundling FFmpeg extension without copy/pasting code

### ISSUE THREAD

**Issue by AOrobator** [google/ExoPlayer#2781]
I just got the FFmpeg extension to build and run successfully by copying the ffmpeg folder into my own project. Is there a way to include extensions without copying and pasting the code from the ExoPlayer project? Ideally, I would have something along the lines of 

`compile 'com.google.android.exoplayer:exoplayer-extension-ffmpeg:r2.4.0'`

in my build.gradle so I don't have to manually update the extension every time there is an update to ExoPlayer.

**Comment by andrewlewis** [comment]
I think this is the same request as #1434. Please reopen if not.

**Comment by AOrobator** [comment]
Looks like it is a duplicate. In that case, I'll throw in my vote for a maven dependency.

**Comment by ojw28** [comment]
I don't think we're likely to do this, for a couple of reasons:
- Different apps are going to want to compile FFMPEG to include different decoders, depending on their needs. See the FFMPEG extension section in our [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html) for some of the options. Different apps may also want to provide support for different architectures. We could provide a default extension via jCenter, but it would likely be suboptimal for the majority of applications, either because it's unnecessarily large or because it lacks functionality.
- FFMPEG has some [licensing considerations](https://www.ffmpeg.org/legal.html). The easier we make it to readily bundle FFMPEG into applications, the less likely developers are to find, read and consider these. So it's in part by design that we don't make this really easy.

**Comment by AOrobator** [comment]
That makes sense. Thanks for getting back to me.
