### ISSUE TITLE
How to build one single .jar file

### ISSUE THREAD

**Issue by nosmirck** [google/ExoPlayer#2797]
I'm trying to create an Unity3D plugin with ExoPlayer 2.4.0, but since the libraries are now split into several modules, is there any way to build a single .jar file including the modules I need (or all of them, I don't care as long as it's a single file).

Thanks in advance!

**Comment by ojw28** [comment]
Could you clarify why it being a single file is important? Thanks.

**Comment by nosmirck** [comment]
Yes, basically I'm having issues with the jars colliding when compiling the project with unity, I know it's a problem there, not with exoplayer, but there's not much I can do (unless I'm doing something wrong that I don't know). However, having a single jar file (and the correspondent manifest and folders res, layouts, etc) would help me integrate easier with no libraries collision.

**Comment by ojw28** [comment]
I'm still somewhat confused. Which jars are colliding? If it's an ExoPlayer jar colliding with Unity then how does having a single ExoPlayer jar make things easier vs having multiple jars? Presumably they'll collide either way.

**Comment by nosmirck** [comment]
The 2.3.0 jar works well, as soon as I replace it with the core + dash + hls jars, it breaks :/ like I said, maybe I'm doing something wrong, maybe there is a common dependency between them and Unity is unable to fix it, it's hard for me to say since I'm not very familiar with android libraries and how they work, all I know is that the one single jar from 2.3.0 works and multiple jars from 2.4.0 cause a collision (and Unity doesn't help with the log)

**Comment by ojw28** [comment]
Ok, and where are you getting the jars from and how do you include them in your project? Do you mean aars?

**Comment by nosmirck** [comment]
Yes, aars, sorry, and I'm downloading them from here https://bintray.com/google/exoplayer and I place them in Plugins/Android/ folder inside my unity project + my java plugin jar that I call from a bridge in Unity.

**Comment by ojw28** [comment]
Hm. I'm not sure it would make a difference. Can you provide details of exactly what failure you're hitting? Is there a simple way we can reproduce the issue?

**Comment by nosmirck** [comment]
I'm closing this because I managed to fix it, it wasn't a problem with exoplayer or the libraries, for some reason, when I copied the new libraries and deleted the old one, Unity kept a copy in the Temp and Library folder, every time I tried to compile it was colliding with the old one even though it was deleted. I had to close the project, delete manually the library folder and let unity create it again.

Thanks anyways for the help and let's leave this here in case someone else faces the same problem.

**Comment by gemiren** [comment]
Second this. I'd like to be able to build a single aar file to be used in my project since I use all the four libraries (core, dash, hls, smoothstreaming). It is really inconvenience that I have to copy each individual aar file to my project every time I make the change to ExoPlayer library project. At least provide an option to build a single library would be good enough.

**Comment by ojw28** [comment]
That sounds like an inefficiency with your development setup as much as anything. Why do you need to be copying aar files around in the first place? Can't you just set things up so that your project has the ExoPlayer modules you need included directly? As an example, we don't need to copy/paste aar files around to build our demo app whenever we make a change to one of the modules. Even if you do need to copy aar files, it feels like something you could write a pretty trivial script for.
