### ISSUE TITLE
Getting the current track: getCurrentWindowIndex() returns wrong index

### ISSUE THREAD

**Issue by claust** [google/ExoPlayer#2799]
### Issue description
When you play a list of tracks using the `ConcatenatingMediaSource`, getting the currently playing track seems impossible.
In the `onTracksChanged` callback I call `player.getCurrentWindowIndex()`, but the values returned does not match the expected. It always returns `0, 0, 1, 2, ...` instead of the expected `0, 1, 2, 3, ...`.

The issue seems to match the #2639 issue.

### Reproduction steps
The issue can be reproduced easily using the ExoPlayer demo app. 

1. Add the following log statement in the [`onTracksChanged`](https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L489) method of the [`PlayerActivity`](https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L489):
`Log.d("onTracksChanged", "Window index: " + player.getCurrentWindowIndex());`
2. Build and launch the Demo app
3. Select the `Playlists / Audio -> Video -> Audio` menu option
4. Wait for the three media to finish playing. 
5. Check the log. The indices reported are `0, 0, 1` instead of the expected `0, 1, 2`.

### Link to test content
N/A.

### Version of ExoPlayer being used
The version used is 2.4.0.

### Device(s) and version(s) of Android being used
Google Pixel XL (android 7.1.2, API 25).
LGE Nexus 5 (android 6.0.1, API 23).
Samsung SM-G900F (android 6.0.1, API 23)
Huawei Nexus 6P (android O, API 26) 

### A full bug report captured from the device
A full bug report from the Pixel XL using "adb bugreport" has been emailed to dev.exoplayer@gmail.com including the issue number in the subject line.

**Comment by tonihei** [comment]
You can get the current window index in the [onPositionDiscontinuity](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L170) method. This method is called every time the window or period index changed, so it is guaranteed to contain the new index.

On the other hand, [onTracksChanged](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L132) gets called because the available track selection changed. This more or less happens at the same time as the window index change, but the calls to these two methods are not guaranteed to be in any particular order. In your example, it was before `onPositionDiscontinuity`. Thus, `player.getCurrentWindowIndex() ` still returned the old window index.
