### ISSUE TITLE
HLS stream always starts with the lowest quality

### ISSUE THREAD

**Issue by JanKokalj** [google/ExoPlayer#281]
Is it possible to prefetch/precache stream or set to the player with what stream should it start to stream. I have a problem that I have an excellent wifi connection but my streams starts with the lowest quality for the first couple of chunks (2seconds long). It would not be a problem if I had a long video, but I working with short videos (max 1minute long).

**Comment by andudo** [comment]
@JanKokalj, player always starts why the first variant that is listed in the master playlist, and only then it switches to a more appropriate one. This is by HLS spec. If you want your videos to start with a high bitrate, put a high bitrate on the top of your master playlist.

We currently don't have an additional ability to tell the player which bitrate to use or start with.

**Comment by ojw28** [comment]
If you wanted the add the ability, the place to do it would be in HlsChunkSource. The initial variant to use gets selected at the bottom of the constructor in that class. We'd consider accepting a patch if you can come up with a nice abstraction for this (you're also free to make the modification locally, just for use in your own project). We'll probably add this functionality at some point, if not.

More generally, determining which format to start with is a non-trivial problem, because until you're fetching data, you don't really know what bandwidth you have. You can guess based on the network type, or retain state from previous playbacks or unrelated network requests that your application is making, but in general it's a non-trivial problem, and different developers are likely to have a preference for different approaches. This is why we opted for the simple approach according to the HLS spec, and will continue to do so, but allowing different developers to override this behavior is something that it makes sense to allow.

**Comment by nbruning** [comment]
We have a small patch that allows subclasses of HlsChunkSource to implement a custom algorithm for selecting the initial variant.
http://pastebin.com/9GbnG4n2

**Comment by DavidMihola** [comment]
Is there any chance that this will still be included in the ExoPlayer project? How about passing an additional `InitialVariantSelector` to the `HlsChunkSource`?

**Comment by ojw28** [comment]
In the [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental) HLS uses `FormatEvaluator`, just like DASH and SmoothStreaming. By implementing a custom `FormatEvaluator` it will be possible to change the initially selected format.

**Comment by kshivaram** [comment]
when we use InitializationTrackSelection in 2.x to select the initial variant to be the highest, it switches back to lower format for a few seconds and then back to good quality thereafter. How do I select the all the initial  variants to be of high quality?

**Comment by b95505017** [comment]
How do we change InitializationTrackSelection to another in demo app?
I want to select the middle of the format sorting by bandwidth in the begining instead of the first chunklist in playlist.

It means that we have to call `HlsChunkSource#selectTracks` right before everything start to load.

**Comment by ojw28** [comment]
Fixing the initial selection is now tracked by https://github.com/google/ExoPlayer/issues/2353. Let's use that issue for tracking. Closing this one.
