### ISSUE TITLE
[Question] Do any of the Exoplayer Contents (HLS, DASH...) support thumbnail scrubbing? 

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#2812]
Question/Issue:
- [Question] Do any of the Exoplayer Contents (HLS, DASH, Smooth Streaming and so forth) support thumbnail scrubbing? 
- Is there a way to scrub a video and show thumbnail previews via the Exoplayer UI ? 

Here's a picture that describes the thumbnail scrubbing feature:
![scrub-thumbnail](https://cloud.githubusercontent.com/assets/7673320/25954318/e5bbb074-3633-11e7-97e3-3c65182197f4.jpg)

**Comment by ojw28** [comment]
No. In my experience service providers normally implement this out-of-band. For example by hosting small thumbnail images, and requesting/displaying those during a seek.

**Comment by ojw28** [comment]
Note: The response above is about ExoPlayer's support, rather than about any functionality defined by the standards themselves. I know HLS and DASH have some trick-play functionality defined, which could help with this kind of feature. We don't support it, however, and I'm not hugely familiar with exactly what they define. If you're interested then you'll need to go and read the relevant specs.

**Comment by zegnus** [comment]
I'm also interested in implementing thumbnails while scrolling for Dash DRM protected content.

If the content has to be protected, is the images approach still valid?
If is valid, does the ExoPlayer v2 support vtt as a thumbnails track?

```
00:00.000 --> 00:05.000
/assets/preview1.jpg
```

of with coordiantes
```
00:00.000 --> 00:05.000
/assets/thumbnails.jpg#xywh=0,0,160,90
```

If because of DRM reasons we have to use a separate video track, what would be the recommended implementation and or limitations of the current ExoPlayer?

Thanks
