### ISSUE TITLE
How can I monitor exoplayer progress position?

### ISSUE THREAD

**Issue by lforxeverc** [google/ExoPlayer#2828]
as descibe above

**Comment by AquilesCanta** [comment]
Assuming that what you want is the playback position, you can use `ExoPlayer.getCurrentPosition()`.

**Comment by lforxeverc** [comment]
can I get a callback to listen to the play position change？

**Comment by ojw28** [comment]
It should be pretty easy for you to implement this yourself using `Handler.postDelayed`. The application knows the rate at which it's interested in receiving updates, and so is better placed to implement polling at the desired rate. This issue is also discussed in https://github.com/google/ExoPlayer/issues/2090.
