### ISSUE TITLE
Timebar back color

### ISSUE THREAD

**Issue by arefehiravanchi** [google/ExoPlayer#2845]
I want to customize color and size of seekbar in controlview of player, I overwrite exo_playback_control_view file in my project and set played_color in timebar, it works for played color but it assign on background of timebar too. 
I have this :
![1](https://cloud.githubusercontent.com/assets/7156108/26201897/7d254aea-3bea-11e7-8a85-5890971aca85.png)

And I want something like this:
![2](https://cloud.githubusercontent.com/assets/7156108/26201914/8af17c2a-3bea-11e7-8e90-bc3bea8c5cb5.png)

How can I set 2 different color for background and played color in timebar?

**Comment by tonihei** [comment]
A similar question has been asked here: #2740, please have a look. The next version (2.4.1) will contain separate attributes for played_color and unplayed_color to allow further customization.

In the current version (2.4.0), the name played_color attribute is slightly misleading because it applies to the entire timeline. The left part is rendered opaque while the right part is rendered in the original colour.
For example, if your played_color is set to #33FFA500 (translucent orange), the played part will be painted in #FFFFA500 (opaque orange) while the unplayed part will be painted in the translucent orange. Judging from your screenshot, you are setting played_color to opaque orange, such that the played and unplayed part are both coloured the same.
