### ISSUE TITLE
API Level19  x86 cpu doesn't work

### ISSUE THREAD

**Issue by Congeek** [google/ExoPlayer#2846]
#00 pc 0000b3ef /system/lib/libcutils.so (__android_log_assert+95) [x86]
2 #01 pc 00008c8c /system/lib/libstagefright_soft_ffmpegadec.so [x86]
3 #02 pc 0001d2ca /system/lib/libstagefright_omx.so (android::SimpleSoftOMXComponent::onMessageReceived(android::sp<android::AMessage> const&)+746) [x86]
4 #03 pc 0001d3dc /system/lib/libstagefright_omx.so (android::AHandlerReflector<android::SimpleSoftOMXComponent>::onMessageReceived(android::sp<android::AMessage> const&)+92) [x86]
5 #04 pc 0000d1ba /system/lib/libstagefright_foundation.so (android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)+346) [x86]
6 #05 pc 0000b551 /system/lib/libstagefright_foundation.so (android::ALooper::LooperThread::threadLoop()+289) [x86]
7 #06 pc 00017ab0 /system/lib/libutils.so (android::Thread::_threadLoop(void*)+512) [x86]
8 #07 pc 00017cb6 /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+246) [x86]
9 #08 pc 0000bc8c /system/lib/libc.so (__thread_entry+236) [x86]
10 #09 pc 0003e265 /system/lib/libc.so (__pthread_clone+69) [x86]

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
