### ISSUE TITLE
Player crashes when playing MP4/H264 clips on HTC Desire X 4.1.1

### ISSUE THREAD

**Issue by chenqian1024** [google/ExoPlayer#2901]
### Issue description
Any MP4/H264 videos cannot play on HTC Desire X. It crashes the player.

### Reproduction steps
Go to the Demo app, and click on YouTube DASH -> Google Glass (MP4,H264) clip and observe the player fails to play and crash.

### Version of ExoPlayer being used
Release-V2

### Device(s) and version(s) of Android being used
HTC Desire X 4.1.1 (API 16)

### A full bug report captured from the device
As API 16 doesn't support bugreport, I'm attaching the logcat file in this case.
[log.txt](https://github.com/google/ExoPlayer/files/1048887/log.txt)

**Comment by AquilesCanta** [comment]
I can observe in the provided log that the highest resolution is being selected. Could you please try adding video size parameters to the DefaultTrackSelector so that the lowest resolution is picked? Like so: 

`selector.setParameters(selector.getParameters().withMaxVideoSize(256, 144));`

The logs should show something like:

```
D/EventLogger(14336):     Group:0, adaptive_supported=YES [
D/EventLogger(14336):       [ ] Track:0, id=133, mimeType=video/avc, bitrate=246236, res=426x240, fps=30.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger(14336):       [ ] Track:1, id=134, mimeType=video/avc, bitrate=617173, res=640x360, fps=30.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger(14336):       [ ] Track:2, id=135, mimeType=video/avc, bitrate=1118095, res=854x480, fps=30.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger(14336):       [X] Track:3, id=160, mimeType=video/avc, bitrate=110578, res=256x144, fps=15.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger(14336):       [ ] Track:4, id=136, mimeType=video/avc, bitrate=2270192, res=1280x720, fps=30.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger(14336):     ]
D/EventLogger(14336):   ]
```

We are also pushing a fix to prevent this kind of selections when the tracks exceed codec capabilities.

**Comment by ojw28** [comment]
This is probably fixed by the change ref'd above.
