### ISSUE TITLE
Detect if the video is frozen 

### ISSUE THREAD

**Issue by martinsce** [google/ExoPlayer#2905]
I have a question. Sometimes, in live streams, the image gets frozen while the audio keeps playing without receiving STATE_BUFFERING or any kind of error. I noticed that it happens regardless of the stream type. 
Since there are no errors and everything seems normal in logcat I did not submit it as a proper issue using the issue template.

Is there a way to possibly detect if the surface view is being updated or  just frozen in order to reload the stream when needed? Detecting if there are any frame changes.

**Comment by AquilesCanta** [comment]
I don't think this is normal behavior. I test live streams daily but do not observe the described issue. You can get the amount of skipped and dropped frames in the Demo App's debug overlay on top of the screen under the label sb and db respectively. That's a good starting point. The logcat should also include relevant logging (in the demo app, that is) when a certain amount of dropped frames is reached. This information can be obtained in your app through the different available listeners. Please provide more context for us to evaluate what the issue here is.

**Comment by martinsce** [comment]
The issue is very difficult to reproduce because it rarely happens. I'm closing this for now until I find a proper way to reproduce it.
