### ISSUE TITLE
How to synchronize Exoplayer to HDMI output  

### ISSUE THREAD

**Issue by ErezNe** [google/ExoPlayer#2925]
Hi

I am using the Exoplayer on Android STB which of course has a HDMI output ,at the AndroidTV OS I can synchronize the STB HDMI output to the TV HDMI input with a lot of resolution,interlace or progressive  and sample rate (HZ) options.
For the streaming to the STB I am using DASH+HEVC and alos DASH+AVC,
The encoding frame rate which I encoding is some times 1080p at 25fps and some time 50fps (for example sport shows) .

The Exoplayer output is synchronize to the STB  and working well just when I am streaming 25fps and the STB output is 1080P@25hz ,
the problem is when I play stream of 50fps it  is never synchronize to the STB output even when I configure the STB output to 1080i/p@50hz
The second problem- not all the TVs have 1080 25hz or 50hz so the STB can not synchronize  to the STB at this HZ so even at stream with 25fps I can not see good.

My Q :How can I synchronize the Exoplayer output to STB HDMI output  even if the stream fps is not the same to HZ STB output?

### Version of ExoPlayer being used
Exoplayer 2.1.1

### Device(s) and version(s) of Android being used
AndroidTV version N

Thx 
Erez

**Comment by ojw28** [comment]
This isn't something we support directly, and it's difficult to come up with a general purpose solution. It is possible to manually set the preferred refresh rate, if you want to set it to match the content being played. You can query the available rates using:
```
Display display = activity.getWindowManager().getDefaultDisplay();
float[] refreshRates = display.getSupportedRefreshRates();
```
And set your preferred rate using:
```
Window window = activity.getWindow();
WindowManager.LayoutParams layoutParams = window.getAttributes();
layoutParams.preferredRefreshRate = refreshRates[preferredRateIndex];
window.setAttributes(layoutParams);
```

Note that in practice, most people opt not to do this. TVs often handle mode changes in a very ugly way (e.g. screen flashing black for a while), and of course if you set the refresh rate to something like 24Hz, that means any playback control animations (or whatever) are all going to run at 24Hz too, which is going to look pretty janky. You can mitigate this to some extent by selecting the highest refresh rate that's a clean multiple of the content FPS (so if the content is 24fps you should probably prefer 48Hz to 24Hz, if both are available).

Note that we do some frame release timestamp adjustments inside of the player to do a pretty decent job of mapping 24fps (and other fps values) onto the default 60Hz display refresh. In practice these adjustments do a pretty good job of minimizing the issue.

**Comment by ErezNe** [comment]
where can I change the  mapping of 24 fps with  60hz   to 25 fps witn 50hz?
Thx
Erez

**Comment by ojw28** [comment]
You can look in the `Format`s of the selected tracks to see what their frame-rates are. Alternatively, if you control the serving side of whatever you're developing, you may well be able to deliver the frame-rate in some out-of-band metadata. You can then decide whether you want to switch, and switch as described above.

This is not something we support directly in the library, and so we're not in a position to provide detailed advice.

**Comment by ErezNe** [comment]
OK, understood but where the "**frame release timestamp adjustment**" mechanism is configured?

"Note that we do some **frame release timestamp adjustments** inside of the player to do a pretty decent job of mapping 24fps (and other fps values) onto the default 60Hz display refresh. In practice these adjustments do a pretty good job of minimizing the issue."

**Comment by ojw28** [comment]
In `VideoFrameReleaseTimeHelper`.

**Comment by ErezNe** [comment]
Hi  in VideoFrameReleaseTimeHelper() of VideoFrameReleaseTimeHelper.java file.

in getDefaultFrameRefreshRate() I controlled window params I did the following changes: 

private static float getDefaultDisplayRefreshRate(Context context) {

WindowManager manager =

(WindowManager)context.getSystemService(Context.WINDOW_SERVICE);

if(manager.getDefaultDisplay().getRefreshRate() &gt; 50){

return 50;

}

if(manager.getDefaultDisplay().getRefreshRate() &lt; 24){

return 24;

}

return manager.getDefaultDisplay().getRefreshRate();

}

After this changes my stream which  is 25fps  working fine with 25Hz display refresh and now also with 50HZ display refresh but not with any other display refresh like 60HZ or any display refresh which is not multiplication of complete number of 25 .
can you guide me how to make timestamp adjustments inside of the player to do mapping 25fps onto the  60Hz display refresh ?
Thx

**Comment by ojw28** [comment]
I don't understand what the question is. What does it mean to "work fine" and "not work fine" in this context? Whenever the display refresh rate isn't a clean multiple of the source refresh rate, the player necessarily needs to display some frames for a greater period of time than others. For example a 2:3 pattern is common for playing 24fps content on 60Hz displays. ExoPlayer already contains logic in `VideoFrameReleaseTimeHelper` to do this in a the best way. You shouldn't need to be making any adjustments to the code for these use cases.

**Comment by ErezNe** [comment]
Hi
"Work fine" I mean the video is playing smooth on the TV screen ,"not work fine" the video is not smooth and it looks like I have lost frames on the video stream,The best way to see it when on the video has running news bar or the movies credits is running .
Is there a  logic in VideoFrameReleaseTimeHelper for playing **25fps** content on **60HZ?**

Erez

**Comment by ojw28** [comment]
It's just not possible to perfectly map 25fps content onto 60Hz. The fact 60/25 isn't a clean multiple is a fundamental limitation.

VideoFrameReleaseTimeHelper will cause 25fps content to be played in a 2:3 pattern (e.g. every other frame displayed for 2 display VSYNCs, with the ones in between displayed for 3 display VSYNCs). Periodically it's necessary to insert an extra 2 display VSYNC frame, since the 2:3 pattern still doesn't get you to 60Hz. I think this approach is more or less the best that can be done without actually changing the playback rate of the media. It's not particularly great for 25fps content. Although in practice we tend to see way more 24fps content, which can use a 2:3 pattern without the additional 2 display VSYNC frame insertion.

Some other notes:
- Some devices may do additional smoothing after frame release. This is particularly true of AndroidTV devices. This is not something we control, however.
- AndroidTV devices may implement their own frame-rate conversion logic in tunneled mode (e.g. where they actually generate 30 of 60 frames to render by interpolation).
- Regular Android decoders do not implement frame-rate conversion. Also, some purists would claim frame-rate conversion is fundamentally bad (because it results in rendering frames that the device has created, that aren't part of the original media).
- Some devices support changing of the actual display rate, as already described above in this thread.
