### ISSUE TITLE
jcenter AARs Incorrect for 2.4.0 and 2.4.1?

### ISSUE THREAD

**Issue by mikeswanson** [google/ExoPlayer#2932]
Referencing ExoPlayer 2.4.0 and 2.4.1 via jcenter in my module's build.gradle works just fine. However, when I try to use/deploy jcenter's AAR files (to Unity, in this case), they appear to be incorrect. For example, [ExoPlayer 2.3.1](https://bintray.com/google/exoplayer/exoplayer/r2.3.1#files/com/google/android/exoplayer/exoplayer/r2.3.1) has a 1.08MB AAR while [ExoPlayer 2.4.0 and 2.4.1](https://bintray.com/google/exoplayer/exoplayer/r2.4.1#files/com/google/android/exoplayer/exoplayer/r2.4.1) have sizes closer to ~2.7KB.

**Comment by andrewlewis** [comment]
I think the reason is that from 2.4.0 all the actual code was moved into other libraries, which this AAR depends on. See also this [blog post](https://medium.com/google-exoplayer/exoplayers-new-modular-structure-a916c0874907). Is there an actual problem using them, or was the concern just that they were much smaller?

**Comment by mikeswanson** [comment]
The issue was using them, but I had incorrectly assumed that the top-level **exoplayer-r2.4.1.aar** was all that was needed when referencing the entire library. I now see that referencing everything requires all of the other libraries. Thanks!
