### ISSUE TITLE
Full screen switch Carlton

### ISSUE THREAD

**Issue by panhuiAipami** [google/ExoPlayer#2942]
Full screen switching their implementation, each switch will Caton 2 seconds or so, different devices have this problem, I use SKYWORTH box android5.1.1and exoplayer2.4.1****
[log.txt](https://github.com/google/ExoPlayer/files/1070147/log.txt)

**Comment by panhuiAipami** [comment]
- 

- [ ]

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
