### ISSUE TITLE
Get current track when track changed

### ISSUE THREAD

**Issue by nguyenhoanglam** [google/ExoPlayer#2968]
I've implemented an AdaptiveTrackSelection.Factory for auto resolution feature. 

When the player changed a track (resolution changed due to bandwidth), I want to know which track (group index and track index) is currently playing? I've examine the callback method but can't find a solution.

```java
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
         // I don't know what to do here ?
    }
```

**Comment by goffioul** [comment]
I faced a similar problem and used this as a template:
https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/java/com/google/android/exoplayer2/demo/EventLogger.java#L138

It's not obvious at first, because AFAIK you can't determine the selected tracks from the arguments of onTracksChanged alone. You have to cross-reference them with information from the track selector.

**Comment by ojw28** [comment]
Also asked in #2972.
