### ISSUE TITLE
Lenovo A820t stuck on buffer state

### ISSUE THREAD

**Issue by Teviz** [google/ExoPlayer#2978]
### Issue description
When using Lenovo A820t play some video, the first frame is rendered and then stuck on buffer.

### Reproduction steps
Use the v2.4.0 demo and play any video.

### Link to test content
The source in demo is ok.

### Version of ExoPlayer being used
2.4.0.

### Device(s) and version(s) of Android being used
Lenovo A820t

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by Teviz** [comment]
So which information is omitted?

**Comment by ojw28** [comment]
You've completely omitted the last section of the template, for example (it's probably not hard for you to read through it and see what's missing, rather than us having to do it for you ;)). Thanks.

**Comment by Teviz** [comment]
Sorry for that I'm indeed missed it. In fact the problem is from the user feedback, and I rent the online remote device to test using exo sample which indeed cant play everytime, so the bugreport needs some work to get. Later I found this problem may be similar to #2997, so for the time being the issue keep close.
