### ISSUE TITLE
RTP stream ts file IllegalStateException

### ISSUE THREAD

**Issue by thuongnvan** [google/ExoPlayer#2983]
Dear All,

I try to apply stream ts file(hvec video format) use RTP protocol to ExoPlayer, i have problem with h265reader parser nalunit. following is log file:
[log.txt](https://github.com/google/ExoPlayer/files/1093842/log.txt)
can anybody help me how to solve this problem? I always appreciate for your helping

Thanks,

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
