### ISSUE TITLE
First frame is rendered and then stuck on buffer state.

### ISSUE THREAD

**Issue by Teviz** [google/ExoPlayer#3000]
### Issue description
The first frame is rendered and then stuck on buffer state.
But when using other player or play on ios, it's fine.

### Reproduction steps
Using ExoPlayer demo and play the specific flv live stream

### Link to test content
you can see it in email. 

### Version of ExoPlayer being used
2.4.2

### Device(s) and version(s) of Android being used
I guess every Android OS Device will reproduce.
For example, SM-A9000, 6.0.1 Android Version.

### A full bug report captured from the device
you can see it in email.

**Comment by ojw28** [comment]
I think the problem here is that the stream indicates it includes an audio track, but then doesn't actually contain any audio data. The player is waiting for audio belonging to this track before starting playback, which I think is the right thing to do.

Commenting out [this line](https://github.com/google/ExoPlayer/blob/r2.4.2/library/core/src/main/java/com/google/android/exoplayer2/extractor/flv/FlvExtractor.java#L187) forces the extractor to ignore the audio track, allowing playback to proceed.

Closing on the assumption this is bad media, since the stream should not indicate presence of audio that it does not actually contain. If you know you're playing only this type of stream then you could make the above change in a local copy of ExoPlayer as a workaround for your app.
