### ISSUE TITLE
Support PGS and VOBSUB subtitles

### ISSUE THREAD

**Issue by wischnow** [google/ExoPlayer#3008]
Hello,

### Issue description
From the documentation and the conversations here I expected PGS and VOBSUB subtitles to work in ExoPlayer, but it seems they are not rendered.

### Reproduction steps
Use the ExoPlayer demo app with this sample content from the Kodi repository of samples:

  https://drive.google.com/file/d/0BwxFVkl63-lEVEluSFZ4NlhpLUk/view

### Link to test content
See above, which is a MKV with PGS.

Unfortunately I don't have a sample with a VOBSUB track that I can share, but those tracks aren't rendered either.

### Version of ExoPlayer being used
ExoPlayer version 2.4.2, used via gradle.

### Device(s) and version(s) of Android being used
Nexus Player with Android 7.1.2

**Comment by ojw28** [comment]
I don't think we support either at the moment. Marking as an enhancement. We're unlikely to prioritize this, however, so the most likely path to this being supported would be an external contribution.

**Comment by drhill** [comment]
I had submitted code awhile back for PGS that was rejected because I translated the ffmpeg implementation into java.  

Afterwards I started an implementation from scratch using other sources as documentation.  I implemented it in my video app which can be viewed here:

https://github.com/drhill/homeview/tree/master/app/src/main/java/com/monsterbutt/homeview/player/text/pgs

Anyone who wants to take what I did and integrate it into ExoPlayer is welcome to.

**Comment by ojw28** [comment]
@drhill - If it's just that package (i.e. the three files), and if you could provide a few pieces of test content, then that looks like something we could get merged relatively easily. We'd really need the files sent as a proper pull request from yourself though; it's important that we have a proper attribution trail for all changes we accept. Thanks!

**Comment by drhill** [comment]
PR: https://github.com/google/ExoPlayer/pull/3673

**Comment by ojw28** [comment]
PGS is now supported (thanks @drhill!). Assuming VOBSUB is different, I think we'd add support if and only if someone provides a contribution.
