### ISSUE TITLE
[Question] why MediaSource need to be re-created when Player in playlist mode ?

### ISSUE THREAD

**Issue by NtcWai** [google/ExoPlayer#3025]
When device lost connection, and after re-connected, my Exoplayer not auto resume.
I corrected it by using a BroadcastReceiver. When network be re-connected, method onNetworkAvailable() be called:
```
    @Override
    public void onNetworkAvailable() {
        if (this.playlist == null) {
            return;
        }
        preparePlayerInternal(mediaSource, false, true);
    }

```  
But I have a problem, it worked well when player on single mode, but not in playlist mode, so I fix it by re-creating MediaSource like that:
```
    @Override
    public void onNetworkAvailable() {
        if (this.playlist == null) {
            return;
        }
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, exoPlayerUserAgent, bandwidthMeter);
        MediaSource mediaSource = this.playlist.createConcatSources(dataSourceFactory, mainHandler, mediaSourceEventListener);
        preparePlayerInternal(mediaSource, false, true);
    }
```  
It worked, but I don't understand why ? Please explain for me, thank you!

**Comment by tonihei** [comment]
From the code snippets you provided, it is not quite clear what playlist.createConcatSources and preparePlayerInternal are doing exactly. I assume that the former creates a new ConcatenatingMediaSource and the latter calls ExoPlayer.prepare. 

When calling ExoPlayer.prepare, the whole player is reset and starts preparing a _new_ media source. MediaSources are not designed to be re-used. That means, they may have some internal state which is not reset went using the same media source again. So it may be that it works for one media source in your case because this particular media source happens to gracefully accept the already prepared state without error, while other media sources (like the ConcatenatingMediaSource) are not able to recover. So, your second version is the correct way of re-preparing the player.

From your code, it also seems that you prepare the player whenever a new network becomes available? Re-preparing the player is actually only needed after a player error ([EventListener.onPlayerError](https://github.com/google/ExoPlayer/blob/9f814850535afbe5a0123f7fa8fc2875ba2c5015/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L162)). 

NB: For any further questions or bug reports, please use the issue template.

**Comment by NtcWai** [comment]
Thank for your explain, @tonihei   
Instead of using` player.prepare(source);`  and ConcatenatingMediaSource , which method & class should I use to make player continue playing when internet be re-connected ?

**Comment by tonihei** [comment]
When the player lost connection to its data source for some time, it will issue a player error (EventListener.onPlayerError). In this case you need to use `player.prepare(newSource); ` as you already did. If there only was a short connection outage (without a player error), the player should just continue playing on its own without any intervention.

**Comment by NtcWai** [comment]
I got it, thank you very much (bow)
