### ISSUE TITLE
Memory Leak in SimpleExoPlayerView

### ISSUE THREAD

**Issue by mkaflowski** [google/ExoPlayer#3028]
I use SimpleExoPlayerView in Fragment connected to Service ang get memory leaks after dispatching fragment and NOT killing service which has working player:

![screenshot_1499252767](https://user-images.githubusercontent.com/10148175/27861909-1b73d0f0-6183-11e7-9294-a1caef4da9cf.png)

Should I relese SimpleExoPlayerView somehow?

**Comment by ojw28** [comment]
I'm assuming it's intentional that the player's lifespan is longer than that of the activity, and that it's in a service. In this case yes, you need to detach the view from the player when the activity goes away, else you will leak it in this way. You probably want to do `SimpleExoPlayerView.setPlayer(null)` on the view when the activity is stopped (or some other appropriate point in the activity lifecycle).
