### ISSUE TITLE
Handle connection loss

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#3030]
Hello team,

This is a suggestion for improvements, correct me if I am wrong in my request.
The issue is that when connection interrupts for a short period (few seconds) the Player throws playback exception even though there is buffered data available. Quick example is turn WiFi off and on.
Real use case is when live stream consumes, for instance Internet radio station and vehicle drives via dead zones. Currently, I am handle this case in onPlaybackError callback, however, this is workaround and as soon as buffered data played and even though connection restored, Player dispatch state completed and it is necessary to re-start playback.
Feature request is to handle such cases internally in Player unless there is no buffered data available.

Regards,
Yurii

**Comment by ojw28** [comment]
For DASH, HLS and SmoothStreaming we continue to play the buffered media and recover seamlessly when it's possible to do so.

For other (typically older/legacy) types of live stream, this type of seamless recovery isn't possible. There will necessarily be some kind of discontinuity even if we're able to recover. It is true that we halt playback unnecessarily quickly for these types of streams, rather than fully playing out what's already in the buffer. Fixing this is tracked (at pretty low priority) by https://github.com/google/ExoPlayer/issues/1606.
