### ISSUE TITLE
Update update Play Pause Button

### ISSUE THREAD

**Issue by Kmphitech** [google/ExoPlayer#3035]
play and pause button not updating when video finished...

**Comment by ojw28** [comment]
This is working as intended. It doesn't really make sense to change to the "play" icon either, since playing something from the end doesn't do anything. The icon used reflects whether seeking back to a previous position in the media will cause playback to start or not. Note that you can toggle the icon whilst in the ended state and then seek backward, and the behavior you get is different to the behavior you get if you seek backward without toggling first.

As a final point, if you want different behavior it should be pretty easy to achieve by doing something in `onPlayerStateChanged` when the state changes to `STATE_ENDED`. Specifically, you can call `setPlayWhenReady(false)` to cause the icon to change. You could also call `seekToDefaultPosition()` to reset back to the start of the media, if that's where you'd want playback to resume from if the user toggles again.
