### ISSUE TITLE
How do I implement a custom video renderer/decoder extension?

### ISSUE THREAD

**Issue by kamomil** [google/ExoPlayer#3044]
### Issue description
Hi, I have a video decoder code that has a constructor and a function that receive an encoded frame and returns a decoded frame of yuv 420p format. I have a tester that runs my decoder on ubuntu and produces a raw video file using the decoder.
 
I want to add my decoder as a custom decoder to Exoplayer. I understood that I have to write a class that implements the Renderer interface. Now there is not much documentation for this interface and it's not clear how to use it as a decoder. I looked at LibvpxVideoRenderer.java and MediaCodecRenderer as a reference. I see that they both use a function "drainOutputBuffer" that is not clear what's it purpose. 
 I see that LibvpxVideoRenderer.java also has a function renderBuffer that is not clear to me as well what is it's purpose.

### Version of ExoPlayer being used
release-v2

**Comment by ojw28** [comment]
Implementing a custom renderer is a hard thing to do. Looking at the VP9 extension is a good starting point. I'd suggest you start by taking a copy of the whole extension. Leave `LibvpxVideoRenderer` as it is, at least to start with, and see if you can replace just `VpxDecoder` and `VpxLibrary` with code that bridges onto the custom decoder you're trying to use. Provided you can do this, you shouldn't need to make many (or even any) changes to the `LibvpxVideoRenderer` class. If you get to the point where it's working, you can then go rename everything to make sense for whatever the decoder is that you're using :).

We'd be really interested to know if you manage to do this. If it turns out all parts of the VP9 extension are re-usable except for the decoder and library classes, we can look at promoting the shareable parts of that extension into the video package of the core library. For example `LibvpxVideoRenderer` would become `SimpleDecoderVideoRenderer`. We've done this already for audio, where we have a `SimpleDecoderAudioRenderer` that's used by three extensions. I think we've not done it for video only because we've only made one video extension, and so we've not been able to validate that the code is really is re-usable.
