### ISSUE TITLE
No playback for TS/AVC/AC-3

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#3049]
### Issue description
Demo player stays in buffering state while playing provided sample (no video/audio)

### Reproduction steps
* demo app with problematic sample (based on 2bebd526e1ece801ef53e6daeaaee76b0255ec6d): https://github.com/stari4ek/ExoPlayer/tree/tvirl/issues/568_no_playback
* checked with/without `FLAG_ALLOW_NON_IDR_KEYFRAMES`, `FLAG_DETECT_ACCESS_UNITS`

### Link to test content
* sample itself: https://drive.google.com/file/d/0Bww3WxdHUiM1Z2xKWHRIZExzbmM/view?usp=drivesdk

### Version of ExoPlayer being used
* checked with demo app on release-v1 and release-v2 (2bebd526e1ece801ef53e6daeaaee76b0255ec6d)

### Device(s) and version(s) of Android being used
* checked with NVidia Shield
* reported by user with Sony BRAVIA 4K GB with 7.0
* checked with Samsung S8+ (SM-G955F)

**Comment by brandoncodes** [comment]
Hey I'm not in the project team, but I'm using a SD TS stream that is Mpeg-2/AC3 to build an app with Exoplayer.

For me the audio was a hardware specific issue. You might want to include the ffmpeg extension and compile ffmpeg into the application (Disclaimer: Software decoders are slower, but this could be a sanity check to see if it is a hardware issue or an issue getting the audio stream). 

I really had to walk through it at different levels, check and make sure the data sources work (Create or add some logging stubs in the 'DataSource' you are using). The log files should also give you some sense of what's going on. Once your data source is connected you'll start seeing a bunch of output about Exoplayer looking for the right codec and setting everything up, if you're not getting that then you might not be connecting to the stream.

Did you have any log files?

**Comment by stari4ek** [comment]
@brandoncodes 
Issue I'm talking about isn't device specific and most probably is related to TS extractor.

Your case is pretty common, since Android CTS does not require AC3 support from device manufacturers (https://developer.android.com/guide/topics/media/media-formats.html#audio-formats) so sometime there are no native codecs.

Checked with S8+ (SM-G955F): never leaves buffering state

**Comment by ojw28** [comment]
The stream's PMT appears to declare an entry with PID 5663 which is an English language MPEG audio track. However there are no subsequent TS packets with this PID. We therefore get stuck because we're unable to determine the format of the corresponding track that we generate.

I'm not sure if we're missing something that we should be using to filter this entry out, of if there's some other issue in the extractor, but I can't see anything obvious. My initial thought is that the media shouldn't be declaring this entry as it doesn't actually contain any TS packets that correspond to it.

**Comment by ojw28** [comment]
Note that `mediainfo` does not list this entry. VLC does list it, and selecting it results in no audio.

**Comment by stari4ek** [comment]
in my case only 3rd audio track is playable by desktop VLC.
I can ask user to record bigger slice of stream if it can help to dive into.

**Comment by ojw28** [comment]
I'm going to close this under the assumption that the media is bad. We can't make a track selection (and start playback) until we know the format of every track, since without the track formats we can't determine which tracks are playable. For TS streams there's no quick way to determine which tracks are missing formats so that we can discard them, because there's no cutoff point in the container after which it's no longer possible for the format to be provided (this is not the case for container formats such as MP4). So the only way to determine for certain that a track is missing its format is to parse the entire stream, which might not be possible without exceeding the allowed buffer size.

There are various things we could do to attempt to mitigate the issue, for example assuming a format wont be provided for a track after buffering a certain amount of data (this is arbitrary, however), or if we've buffered all the way to the end (although we may never get that far if we hit the max allowed buffer size). It doesn't seem worth spending any time on though. We have little evidence to suggest this is widespread issue (currently only a single piece of problematic media), and it seems the media is broken.

Note: It may be that TS packets for the pid are present later in the media, but in that case the file is unacceptably poorly interleaved, given the first packet for this pid definitely isn't present in the first 16MB of the stream.

**Comment by stari4ek** [comment]
Got it.

Wanted to add another stream (from same provider) with different tracks layout but the same problem (one of audio track is broken: pl): https://drive.google.com/file/d/0Bww3WxdHUiM1ZkRFa1Z3bW5scG8/view?usp=drivesdk
