### ISSUE TITLE
NullPointer when play exoplayer v2 demo app

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#3057]
When i test our dash stream in the demo app, I found sometimes the app crashed, the log shows nullpointer exception. i checked the source code and find the 2 below lines. 
Class Name: **DashMediaSource**
Line 553:  handler.postDelayed(refreshManifestRunnable, delayUntilNextLoad);
Line 526:  handler.removeCallbacks(simulateManifestRefreshRunnable);
is it necessnary to add checking null logic for handler?

Thanks

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
