### ISSUE TITLE
Question:How to exceed capabilites if event logger show "supported=NO_EXCEEDS_CAPABILITIES"

### ISSUE THREAD

**Issue by JacksonFoo** [google/ExoPlayer#3062]
I tested my app with exoplayer library v2.4.3 with LG G2 phone it able to play until 540 quality. I already set 
trackSelector.getParameters().withExceedRendererCapabilitiesIfNecessary(true)) also unable to exceed. Is able to play when it's been forced the bitrate or select the high quality track.

I attached below logs from event logger.
[https://drive.google.com/file/d/0B74K6PAhBA7UWUVnN3Q3LUdmS1U/view?usp=sharing](url)

**Comment by AquilesCanta** [comment]
Please refer to `exceedRendererCapabilitiesIfNecessary`'s javadoc. Note that it does not apply if it is possible to make a selection without it.

As an example, if your stream has 3 tracks: 1, 2 and 3; 1 and 2 are advertised as supported by the renderer, but 3 exceeds its capabilities. In that case, the selection is going to be 1 and 2 independently of `exceedRendererCapabilitiesIfNecessary`'s value. 

This parameter only applies if all 1, 2 and 3 exceed capabilities. In that case, without `exceedRendererCapabilitiesIfNecessary`, no track will be selected. But with it, the lowest quality one will be selected. Note that this parameter does not affect adaptive selections in any way.

In your case, It might make sense overriding `selectVideoTrack()` in `DefaultTrackSelector`. But make sure you only ignore RendererCapabilities when it's safe to do so. Otherwise your app might crash when it tries to adapt to higher qualities.
