### ISSUE TITLE
Exoplayer dying and closing app on its own

### ISSUE THREAD

**Issue by blennerSilva** [google/ExoPlayer#3087]
Hey guys 

Im having an weird issue with my app, whenever im playing a track and then go to my phone to look at other apps such as facebook or instagram or whatever, exoplayer stops on its own with no logs no nothing, It just stops, so i have to go back into my back and start playback all over again.

can you guys give some insight about this issue?

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

Can you reproduce with the demo app? Maybe your app is being paused/stopped but you are not saving the resume information. The demo app does this, you might want to look there.
