### ISSUE TITLE
Question: Disable the secure codec in exoplayer v2

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#3095]
we are upgrading our app from exoplayer v1 to v2, we need to disable secure codec function in v1 for some device.  we can use the below code in v1.
MediaCodecVideoTrackRenderer.setDisableSecureCodec();

Is there a way that disables the secure codec in exoplayer v2.
Thanks.

**Comment by ojw28** [comment]
I don't think there was ever a setDisableSecureCodec method in ExoPlayer V1. Are you sure you didn't add it yourself (or alternatively, are you sure you're not using a non-official branch of ExoPlayer in which it was added)?

It's probably possible for you to achieve this functionality by implementing your own `MediaCodecSelector` and passing it to `MediaCodecVideoRenderer` via the constructor. You can implement your selector to return null from `getDecoderInfo` if `requiresSecureDecoder` is true, and call through to the default implementation otherwise. Does that achieve the desired result?
