### ISSUE TITLE
DASH: cross-AdaptationSet seamless switching and groupings

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#3097]
Version: dev-v2-r2.5.0

Great to see an implementation for seamless switching.  However, is it correct that the notion of grouping has been lost with the manifest changes to achieve this?  In my use case I have a notion of 'cameras' (basically a camera is defined by an adaptation set, which contains a number of representations).  I would like to use the seamless switching to swap between adaptation sets...and each set then switches representations based on available bandwidth.

Currently I am using MappingTrackSelector.setSelectionOverride with a bunch of tracks grabbed from each group to change set (camera).

To ensure my MPD was/is not entirely at fault, I tried the one put forward in issue #2431, and adaptation sets are still output as one group:

Tracks [
 Renderer:0 [
  Group:0, adaptive_supported=YES [
    [X] Track:0, id=1, mimeType=video/avc, bitrate=726949, res=320x168, fps=30.0, supported=YES
    [X] Track:1, id=2, mimeType=video/avc, bitrate=1632237, res=854x450, fps=30.0, supported=YES
    [X] Track:2, id=3, mimeType=video/avc, bitrate=6541838, res=1280x674, fps=30.0, supported=YES
    [X] Track:3, id=4, mimeType=video/avc, bitrate=16594678, res=1920x1012, fps=30.0, supported=YES
    [X] Track:4, id=5, mimeType=video/avc, bitrate=25130866, res=3840x2024, fps=30.0, supported=YES
  ]
 ]
 Renderer:1 [
   Group:0, adaptive_supported=N/A [
    [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=131690, channels=2, sample_rate=44100, language=en, supported=YES
  ]
 ]
]

Thanks,
Ste

**Comment by ojw28** [comment]
I don't think `urn:mpeg:dash:adaptation-set-switching:2016` is suitable for your use case. The DASH-IF guidelines indicate it's suitable for use where the adaptation sets provide the same content and the segments are time-aligned. In your use case the segments are time-aligned but the content is not the same (because they're different cameras). The relevant part of the guidelines is:

> Representations in two or more Adaptation Sets may provide the same content. In addition, the content may be time-aligned and may be offered such that seamless switching across Representations in different Adaptation Sets is possible. Typical examples are the offering of the same content with different codecs, for example H.264/AVC and H.265/HEVC and the content author wants to provide such information to the receiver in order to seamlessly switch Representations (as defined in ISO/IEC 23009-1, clause 4.5.1).

I think what you really want is just for ExoPlayer to support seamless switching between different track selections, which is already tracked by https://github.com/google/ExoPlayer/issues/2371.
