### ISSUE TITLE
Fast forward first, and then retreat quickly, repeated several times will be unable to play, but you can see the progress bar buffer.

### ISSUE THREAD

**Issue by Sailiy** [google/ExoPlayer#3109]
Fast forward first, and then retreat quickly, repeated several times will be unable to play, but you can see the progress bar buffer.I just modify the example of the play Url

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
