### ISSUE TITLE
Access http headers from manifest requests

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#311]
Is exposing response headers from manifest requests anything you would consider a good addition to the ManifestFetcher? I'm especially interested in the cache control header. Or am I better off writing a custom fetcher to accommodate for this?

**Comment by ojw28** [comment]
That sounds reasonable to me. A couple of notes:

- I'll probably be pushing a change today or tomorrow that refactors ManifestFetcher.ManifestLoadable into a more generic NetworkLoadable class, so probably best to hold off doing anything until that's pushed.
- What do you actually want to do with the cache control header? I don't have experience using it, but it's possible that installing a [HttpResponseCache](http://developer.android.com/reference/android/net/http/HttpResponseCache.html) will give you what you need?

**Comment by pakerfeldt** [comment]
I want pretty much what HttpResponseCache gives me. I.e. caching the responses for as long as the cache-control header allows. However, HttpResponseCache gives very little control since it affects the entire application. Preferably that ManifestFetcher gave this directly but that might be outside of its responsibility. Maybe ManifestFetcher could be re-factored in such a way you could provide your own http client (that could do caching)? That feels more inline with the overall design philosophy of ExoPlayer.

**Comment by ojw28** [comment]
Yeah, HttpResponseCache does seem somewhat lacking in fine-grained control.

I'm not sure we'd want to put caching directly into ManifestFetcher. Given you're (presumably) about to start streaming video and audio over the network, caching the tiny manifest request that you make just before you start doesn't feel like a huge gain. Particularly since the user would have had to attempt to stream the same video beforehand to get any benefit. Could you explain what gain you actually expect, and how significant you expect it to be?

Re the suggestion to allow http stack injection - I wanted to move ManifestFetcher over to use DataSource/DataSpec objects eventually, which is the standard mechanism that would allow you to inject a different network stack for media requests. It's not immediately clear how headers would fit into that model, however, because DataSource doesn't make any assumptions about where the data is coming from (and the concept of response headers doesn't make much sense if the data isn't coming from the network). It might be that we end up changing HttpDataSource to be an interface that extends DataSource and adds in network specific functionality (with the existing HttpDataSource class becoming the default implementation of that). ManifestFetcher would then take a HttpDataSource instance.

**Comment by pakerfeldt** [comment]
I agree putting cache directly into ManifestFetcher is a bit too much. 

The manifest might be tiny in size but it is one extra round trip that causes backend load plus adds an additional startup latency. Simply cutting every millisecond possible to get closer to a feeling of instant playback. Also, if I choose to prefetch a manifest I would need to know for how long I can hold on to this manifest before another http request needs to be done.

**Comment by ojw28** [comment]
We now inject a HttpDataSource for making manifest requests. This should make it pretty easy for you to implement what you want (by implementing and injecting a custom HttpDataSource that does caching).

**Comment by pakerfeldt** [comment]
This hasn't been pushed upstream yet, right?
