### ISSUE TITLE
how to use vp9 extension?

### ISSUE THREAD

**Issue by linyongsheng** [google/ExoPlayer#3118]
What is best way to use vp9 extension。As we know the `SimpleExoPlayerView` class only can manage `TextureView` and `SurfaceView`.But vp9 use `VpxVideoSurfaceView `.

**Comment by andrewlewis** [comment]
The vp9 extension can be used with a plain `SurfaceView` but it's likely to be less efficient than configuring it with a `VpxVideoSurfaceView`, as the color space conversion is done in software rather than using a GL shader. After following the instructions to compile the vp9 extension in its readme, rendering to a `SurfaceView` from `LibvpxVideoRenderer` should just work in the demo app (for samples set to prefer extension renderers).

`SimpleExoPlayer` does not work with `VpxVideoSurfaceView`. There are two main differences to be aware of if you want to switch to `VpxVideoSurfaceView`. Firstly, rather than passing a surface with `C.MSG_SET_SURFACE`, you pass the `VpxVideoSurfaceView` with `LibvpxVideoRenderer.MSG_SET_OUTPUT_BUFFER_RENDERER`. Secondly the `Surface` passed to `VideoRendererEventListener.onRenderedFirstFrame` will be null.
