### ISSUE TITLE
Need a help in HLS customizing 

### ISSUE THREAD

**Issue by tedKim5178** [google/ExoPlayer#3128]
Hello! I am trying to change a bit of code of ExoPlayer. But I have a problem.
In HLS, I found out that ExoPlayer re-download the chunk in specific situation to get better performance. (I guess when it has enough buffer and nice network so that it has enough time to re-download chunk which has better bitrates) But I don't want to re-download the chunk. So I changed little bit of code. 

before

if (previous == null || switchingVariant) {
           // select chunkMediaSequence
}else{
           chunkMediaSequence = previous.getNextChunkIndex();
}

after

if (previous == null) {
           // select chunkMediaSequence
}else{
           chunkMediaSequence = previous.getNextChunkIndex();
}

So my ExoPlayer does not re-download the chunk after bitrate changed. It works well but there is little bit of delay when it goes to next chunk which has different bitrate than previous chunk. Why does it happened and how can I fix it?

Thank you :)

**Comment by tedKim5178** [comment]
For more information, this is an original code 
![2017-08-02 2 44 54](https://user-images.githubusercontent.com/24425221/28859247-39e3e376-7791-11e7-9754-058f47861e7a.png)

**Comment by ojw28** [comment]
HLS doesn't make guarantees about the location of keyframes in segments, so it's always necessary to download overlapping segments when switching between variants. Else you may see delays if the segments do not start with keyframes, because you'll have no overlap and the player will be unable to decode the part of the first segment in the new variant before the first keyframe. You may also see delays if the segments in different variants are not time aligned with one another.

If you use a recent version of ExoPlayer, are playing content where segments are time aligned and start with keyframes, and this latter property is indicated explicitly in the HLS playlist using the `EXT-X-INDEPENDENT-SEGMENTS` tag, then the player will avoid downloading overlapping segments in this case. This is the only case where a player can safely do this.

For DASH and SmoothStreaming we avoid downloading overlapping segments by default, because content in these standards consists of time aligned segments starting with keyframes pretty much as standard.

**Comment by tedKim5178** [comment]
Thank you so much for your reply! ExoPlayer is really helpful to study media Player!! Thank you for making this great media player ! Best player ever!
