### ISSUE TITLE
[Request] Support crop mode in AspectRatioFrameLayout (solution pull request)

### ISSUE THREAD

**Issue by stellabei** [google/ExoPlayer#3155]
### Issue description
How to make movie playing in full screen on devices that has different aspect ratio than the encrypted video content? 
Real life example: use a Samsung S8 or LG G6 (aspect ratio 18:9) to play a movie (usually 16:9). 

### Reproduction steps
Try to play a encrypted movie on Samsung S8 or LG G6. You will see vertical black bars  on the sides. Or playing any movie that has different aspect ratio than the device.

### Link to test content
Can be any encrypted movie (most of them has aspect ratio 16:9)

### Version of ExoPlayer being used
r2.4.1

### Device(s) and version(s) of Android being used
Samsung S8 or LG G6 (Android 7.0)

### A full bug report captured from the device
N/A

### Feature request proposal
There are 2 possible solutions for the aspect ratio incompatibility problem:
1)make the video to fit the size of the screen by stretching it (ignores the aspect ratio)
2)zoom in the video in the way that it maintains aspect ratio but crop images out

Note that I can not use TexturedView to perform those operations since DRMed media content can only use SurfaceView. So my solution is to increase the AspectRatioFrameLayout beyond the actual screen size so it can perform the "zoom in" without jeopardizing the protected SurfaceView.

The current implementation of AspectRatioFrameLayout does not support the "zoom in" (crop) mode. So I did some changes in order to support it. In that way, developer can either directly use AspectRatioFrameLayout itself or use SimpleExoPlayerView with this new resize_mode.
 
[AspectRatioFrameLayout.java.diff.txt](https://github.com/google/ExoPlayer/files/1209550/AspectRatioFrameLayout.java.diff.txt)

Here is my pull request:
https://github.com/google/ExoPlayer/pull/3187

**Comment by ojw28** [comment]
Closing since the pull request was merged. Thanks!

**Comment by Jogan** [comment]
@ojw28 Not sure if this is related but do you know how to enable the floating "crop to fit/fit to screen" button that so many Video apps have (Amazon/Youtube/Hulu). It might just be something baked in by Samsung on the S8 (I dont have other phones to test) when it sees that the phone is a higher aspect ratio.

**Comment by stellabei** [comment]
@Jogan, it is not baked in by Samsung, each video streaming app need to implement it. The PR that was merged is to provide a way to do that if you use exoplayer and the AspectRatioFrameLayout.

**Comment by ojw28** [comment]
The floating button on the Galaxy S8 (and possibly other recent Samsung devices) is a platform feature provided by Samsung, as far as I know. I think they added it because the S8 has a screen that's wider than 16:9, so the ability to crop the top and bottom slightly to remove bars down the side becomes useful for 16:9 content, which of course is very common. I'm not sure what logic they're using to determine when to show the button, but I suspect they've implemented some logic that tries to detect when the foreground activity is showing fullscreen video, and manipulates the dimensions of the surface accordingly if the user toggles the button.

This pull request would allow you to do something similar at the application level, on any device, and is separate to the feature on the Galaxy S8.

**Comment by Jogan** [comment]
Thanks for the help. I've already implemented this feature using this PR as
reference. I was more curious if anyone knew how they were determining when
to show that floating button. It definitely seems like a platform feature.
Hulu/YouTube/Amazon all use the same button so there must be some way to
enable it. I was thinking it was something to do with max aspect ratio set
in the manifest in combination with immersive mode but no luck.
