### ISSUE TITLE
Buffering radio stream

### ISSUE THREAD

**Issue by psedoykin** [google/ExoPlayer#3164]
### Issue description

I use exoplayer for playing radio stream. And I have question related to buffering:
 How to increase it?  

I found the following issue (https://github.com/google/ExoPlayer/issues/2438) but increase DEFAULT_MIN_BUFFER_MS and DEFAULT_MAX_BUFFER_MS doesn't help me. 

Now I have about 20-30 sec buffering when Internet off. I want to increase it to 3 min. 
It is not server issue because Ios client support buffering about 3 min for the same server.

Could you help me ? may be need change another settings ?  

Please see my code: 

  LoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE), 2*DEFAULT_MIN_BUFFER_MS,
                    2*DEFAULT_MAX_BUFFER_MS, DEFAULT_BUFFER_FOR_PLAYBACK_MS, DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS);

            DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(mContext);

            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            mPlayer = ExoPlayerFactory.newSimpleInstance(renderersFactory,
                    trackSelector,
                    loadControl);

            mPlayer.setAudioStreamType(C.STREAM_TYPE_MUSIC);
            mPlayer.addListener(this);

            setWakeMode(mContext, PowerManager.PARTIAL_WAKE_LOCK);

           

### Version of ExoPlayer being used
r2.5.1

### Device(s) and version(s) of Android being used
Galaxy note 5 - Android 6.0.1

**Comment by ojw28** [comment]
We need more complete information to help with issues like this. For example information about the type of stream you're trying to play (and preferable a link to an example).

**Comment by psedoykin** [comment]
Mp3 stream from Internet (for example http://79.174.68.63:7999/luxury). 
I have added file with code related to exoplayer from my project. 
[LocalPlayback.java.zip](https://github.com/google/ExoPlayer/files/1227176/LocalPlayback.java.zip)

Please look at function createMediaPlayerIfNeeded. (But it default init for exoplayer)

**Comment by ojw28** [comment]
If you have a three minute buffer, does that imply three minutes of latency (e.g. the audio the user hears is three minutes behind "live")?

**Comment by djerom** [comment]
I don't see the point to increase so much your buffer size.
Anyway you can customize buffer settings as below:
```java
private static final int DEFAULT_MIN_BUFFER_MS = 5000;
private static final int DEFAULT_MAX_BUFFER_MS = 10000;
private static final int DEFAULT_BUFFER_FOR_PLAYBACK_MS = 3500;

private void createMediaPlayerIfNeeded() {
    if (mExoPlayer == null) {
        mExoPlayer = ExoPlayerFactory.newSimpleInstance(
                new DefaultRenderersFactory(mContext),
                new DefaultTrackSelector(),
                new DefaultLoadControl(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE),
                            DEFAULT_MIN_BUFFER_MS, DEFAULT_MAX_BUFFER_MS, DEFAULT_BUFFER_FOR_PLAYBACK_MS,                      DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS));
        AudioAttributes.Builder builder = new AudioAttributes.Builder()
                .setContentType(C.CONTENT_TYPE_MUSIC);
        mExoPlayer.setAudioAttributes(builder.build());
        mExoPlayer.setPlayWhenReady(true);
        mExoPlayer.addListener(this);
    }
}
```

**Comment by psedoykin** [comment]
@ojw28  I want to implement the following behavior: 
If the Internet should turn off on the phone, then the app should play 3 more minutes.

**Comment by psedoykin** [comment]
@djerom  I have customized the settings but it didn't help me.

**Comment by ojw28** [comment]
As already asked above, does that imply three minutes of latency (e.g. the audio the user hears is three minutes behind "live")?

**Comment by psedoykin** [comment]
No, I want to play "live" and buffering some next time of stream. Is it possible ?

**Comment by ojw28** [comment]
It's fundamentally impossible to be both "live" and have three minutes of media buffered, since that would require you to have buffered three minutes of content from the future. Please clarify the question. Thanks.

**Comment by psedoykin** [comment]
So for what DEFAULT_MIN_BUFFER_MS, DEFAULT_MAX_BUFFER_MS used in DefaultLoadControl ? I think that for buffering media.

**Comment by ojw28** [comment]
They're used [as documented](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html). Note that the "will attempt" part of the documentation is important. If the serving side doesn't allow the client to buffer that much media, then the client wont be able to do so.

I took a look at the stream mentioned earlier in this thread (http://79.174.68.63:7999/luxury). The server allows the client to buffer ~145 seconds of media. Increasing `DEFAULT_MIN_BUFFER_MS` and `DEFAULT_MAX_BUFFER_MS` to this duration or more will cause ~145 seconds of media to be buffered, and this is working correctly. You can verify this by periodically querying the difference between `player.getBufferedPosition` and `player.getCurrentPosition` during playback.

I think the problem you're seeing isn't that the duration of media you want isn't being buffered. It's that the player attempts to reconnect too quickly in the case of a network error, rather than first playing out all of the media that's in the buffer. This issue is tracked by https://github.com/google/ExoPlayer/issues/1606, so you should follow that for updates.

**Comment by psedoykin** [comment]
Ok, Thanks for your help.
