### ISSUE TITLE
Release played mediasources?

### ISSUE THREAD

**Issue by AOrobator** [google/ExoPlayer#3167]
When using a DynamicConcatenatingMediaSource, should I always remove/release played child MediaSources from the DynamicConcatenatingMediaSource? The reason for removing would be to make sure that I'm conserving memory. I'm working with an application that can effectively add infinite items to the DynamicConcatenatingMediaSource and I'm worried about it consuming too much memory. This is why I'm trying to keep the number of child MediaSources at a maximum of two: the current song being played and the next song to be played.

**Comment by ojw28** [comment]
There's obviously some overhead, because they are objects in memory, but I don't think there's any special overhead incurred beyond that. They're not going to be holding onto big chunks of memory for buffering media or anything like that.

So you probably wouldn't want thousands and thousands of them. A hundred is probably fine. If you're concerned, why not just measure the overhead yourself and see?

**Comment by ojw28** [comment]
Note - I'm pretty sure removing a child from `DyanamicConcatenatingMediaSource` releases it for you. You shouldn't have to release it yourself.

**Comment by AOrobator** [comment]
@ojw28 When watching the memory monitor after a song finishes, I always see a large dip in memory usage, maybe a GC? This is without me removing `MediaSource`s from the `DynamicConcatenatingMediaSource`. Looks like memory isn't a concern.

<img width="1379" alt="screen shot 2017-08-14 at 2 37 59 pm" src="https://user-images.githubusercontent.com/4106884/29286009-8032bb2e-80fe-11e7-9dfd-0deef457cb18.png">
