### ISSUE TITLE
Playing Raw PCM

### ISSUE THREAD

**Issue by yydl** [google/ExoPlayer#317]
Assuming I have my own custom decoder that gives me raw 16-bit PCM data, is there any way for me to set up a SampleSource that can feed the data? And if so, what should the mimeType for the TrackInfo be?

**Comment by ojw28** [comment]
It would definitely be possible for you to achieve this. There are multiple ways that you could choose to structure it, so you should settle on whatever makes most sense to you. The problem you need to solve is that ExoPlayer's MediaCodecAudioTrackRenderer currently assumes that the SampleSource provides compressed audio samples, and will always feed those samples through a decoder. Since you don't want this, you can't just implement a SampleSource that provides PCM data, and then wire it up to a MediaCodecAudioTrackRenderer. Possible solutions are:

1. Implement a SampleSource that provides raw 16-bit PCM data, and implement a TrackRenderer that feeds samples directly into AudioTrack without feeding through a decoder first. Ac3PassthroughAudioTrackRenderer on the dev branch actually does exactly this, however is currently specific for Ac3. It's probably straightforward to generalise that class to be a generic PassthroughAudioTrackRenderer. We'll likely do that at some point, but it's not a priority for us. If you were to do it and if it were to work out nicely, then that would be a great potential contribution back to the project.

2. What data do you feed into your custom decoder? Assuming you're feeding something in, one option would be to have a SampleSource provide samples before they're decoded, and implement a custom TrackRenderer that hooks in to your decoder. It's probably more work. You can see an example of hooking in to a custom audio decoder here: https://github.com/google/ExoPlayer/tree/dev-webm-vp9-opus/extensions/opus
