### ISSUE TITLE
xiaomi can not play

### ISSUE THREAD

**Issue by pheart** [google/ExoPlayer#3171]
#######
exoplayer can not play in xiaomi device. 
-----------------------
08-15 09:53:43.503 13653-14608/com.karaoke.singplus.test E/ACodec: [OMX.MTK.AUDIO.DECODER.AAC] ERROR(0x80001005) \
08-15 09:53:43.504 135-14610/? E/MtkOmxAudioDecBase: Decoder Component Dec Error! 
08-15 09:53:43.504 13653-14608/com.karaoke.singplus.test E/MediaCodec: Codec reported an error. (omx error 0x80001005, internalError -1104) 
08-15 09:53:43.516 13653-13734/com.karaoke.singplus.test E/ExoPlayerImplInternal: Internal runtime error. java.lang.IllegalStateException at android.media.MediaCodec.queueInputBuffer(Native Method) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:684) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:507) at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:153) at android.os.HandlerThread.run(HandlerThread.java:60) at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Model number: HM1
Android version: 4.2.1

### Issue description
I suggest add issue in MediaCodecUtil.isCodecUsableDecoder 
`    if (Util.DEVICE.startsWith("HM") && Util.SDK_INT < 18 && "OMX.MTK.AUDIO.DECODER.AAC".equals(name)) { 
      return false;
    }`

**Comment by ojw28** [comment]
Thanks for reporting!
- Can you confirm the check you added fixed the issue and still allowed media to play? It's not necessarily the case that there's another AAC decoder to fall back on, although on most devices there does seem to be.
- The `startsWith("HM")` check is too broad, since it incorrectly captures unrelated devices (e.g. the [Haier G21](http://www.devicespecifications.com/en/model/bddb426d), which has DEVICE set to HM-G303-W). Can you tell us what `Util.MANUFACTURER`, `Util.MODEL` and `Util.DEVICE` are set to for the device, and we'll come up with a suitably targeted rule?

**Comment by pheart** [comment]
@ojw28 
thank u very much!   i have try that i added fixed the issue and will allowed media to play. My device is come from china.
Util.MODEL     2013022 
Util.DEVICE      HM2013022
Util. MANUFACTURER   Xiaomi
