### ISSUE TITLE
Support app specified ad markers in player UI

### ISSUE THREAD

**Issue by tonihuotari** [google/ExoPlayer#3184]
### Issue description
I can't get visible ad markers after upgrading from 2.4.4. I've tried both 2.5.0 and 2.5.1

### Reproduction steps

In exoplayer 2.4.4 you could add the following lines to get visible ad markers:

`TimeBar timeBar = (TimeBar) findViewById(R.id.exo_progress);
long[] adGroupTimesMs = {40000, 60000, 80000};
timeBar.setAdBreakTimesMs(adGroupTimesMs, 3);`

In exoplayer 2.5.0 changes were made to how ad markers are set in the TimeBar. The following code should correspond to the working code in previous versions. However ad markers are not visible.

`TimeBar timeBar = (TimeBar) findViewById(R.id.exo_progress);
long[] adGroupTimesMs = {40000, 60000, 80000};
boolean[] playedAdGroups = {false, true, false};
timeBar.setAdGroupTimesMs(adGroupTimesMs, playedAdGroups, 3);`

I've also tried adding specific colors and width without success:

`<com.google.android.exoplayer2.ui.DefaultTimeBar
            android:id="@+id/exo_progress"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:ad_marker_color="#00FF00"
            app:ad_marker_width="5dp"
            android:layout_toEndOf="@id/exo_position"
            android:layout_toStartOf="@id/exo_duration"/>`

### Link to test content
Use any stream provided in the Exoplayer demo 

### Version of ExoPlayer being used
Affected versions: 2.5.0, 2.5.1
Working version: 2.4.4

### Device(s) and version(s) of Android being used
Samsung Galaxy S7 Edge (Samsung SM-G935F)
Android 7.0, API 24

**Comment by andrewlewis** [comment]
Are you using `PlaybackControlView`? Please could you set a breakpoint in `setAdGroupTimesMs` and check if your ad markers are being overwritten by the player?

**Comment by tonihuotari** [comment]
Yes there seems to be values overwritten when setAdGroupTimesMs gets called in PlaybackControlView.updateProgress

**Comment by andrewlewis** [comment]
Probably this only worked before because we only set the ad group times if the view was showing a multi-window time bar. As of r2.5.0 we always set the ad markers (and ad timelines aren't multi-window any more).

Marking this as an enhancement to let apps specify ad markers that override whatever the player provides. As a workaround for now, you could subclass `DefaultTimeBar` and override `setAdGroupTimesMs` to use your own ad group times (ignoring what's passed in). See the blog post on [customizing UI components](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a) for information on how to use this custom time bar.

**Comment by tonihuotari** [comment]
Your suggested workaround works, I'll use it until it is fixed. Thanks @andrewlewis
