### ISSUE TITLE
Fails to start TS playback due unexpected start code prefix

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#3189]
* stream: https://drive.google.com/file/d/0Bww3WxdHUiM1Y0EzaXAtZWJ6RTQ/view?usp=drivesdk
* checked in demo: 1829d71d29435ca1eb4240d4aed7cb1315e2b606 (2.5.1)
* there're warnings in log:
```
08-17 23:57:53.009 17631-17676/com.google.android.exoplayer2.demo W/PesReader: Unexpected start code prefix: 4202312
08-17 23:57:53.170 17631-17676/com.google.android.exoplayer2.demo W/PesReader: Unexpected start code prefix: 4202312
08-17 23:57:53.331 17631-17676/com.google.android.exoplayer2.demo W/PesReader: Unexpected start code prefix: 4202312
```
As warning states "Packet start code prefix" does not match expected `0x000001`
From ISO:
> packet_start_code_prefix – The packet_start_code_prefix is a 24-bit code. Together with the stream_id that follows it constitutes a packet start code that identifies the beginning of a packet. The packet_start_code_prefix is the bit string '0000 0000 0000 0000 0000 0001' (0x000001).

I'm not sure if stream is incorrectly prepared or exoplayer reads pes header from wrong position for this specific stream.

I've checked stream with _VLC_ and _mplayer_ - both work well

**Comment by WeiChungChang** [comment]
**Tools**
https://sourceforge.net/projects/dvbinspector/

http://www.pjdaniel.org.uk/mpeg/

![image](https://user-images.githubusercontent.com/14846473/29445441-65fd733e-8419-11e7-8db4-a37062ae60ee.png)

we can find there are 4 streams there; one for video & the other 3 for audio.
The audio streams PIDs are : 5634, 5635 & 5636 respectively.


![image](https://user-images.githubusercontent.com/14846473/29452745-0ea7c8ca-843a-11e7-8216-dd1de97ab320.png)

The PID = 5635 seems to be special as the figure above; you can see the type  is PSI.

However, all other streams (include video), type is PES.

It seems that the PID = 5635 is **NOT** of PES so **_it does NOT have start code_**. **_However EXOPlayer expects it has so failed._**

That is why you see  a lot of "Unexpected start code prefix: 4202312"
**_Since 0x401F48 = 4202312 and as you see, it is exactly the start 3 bytes of the packets which are start payload_.**

![image](https://user-images.githubusercontent.com/14846473/29453123-1dae63b4-843b-11e7-9fbc-8f28c8087349.png)
 
I am curious about it & maybe somebody who is familiar with it could provide an explanation.

Thanks~

**Comment by ojw28** [comment]
@ybai001 - The "special track" with PID 5635 looks to be Dolby related. Is this something you're familiar with? Or do you think the type is just incorrect (i.e. should be PES)?

**Comment by ybai001** [comment]
@ojw28 - Conclusion: this stream is NOT correct. The details are:
First of all, from above PMT info, we know the stream_type is 0x6, which means this stream is Dolby AC-3. (BTW, if stream_type is 0x87, the stream is Dolby E-AC-3.)
Secondly, since this is Dolby AC-3 stream, **the type should be PES**. But from above screenshot, that stream's type is PSI. This is NOT correct. 
Thirdly, I created a TS stream with Dolby AC-3 audio. (Usually, we have only TS stream with E-AC-3. So I have to create one by myself.) 
![image](https://user-images.githubusercontent.com/30304609/29648014-bc989bfc-88be-11e7-8f2d-2d85202e9ca5.png)
From above screenshot, you'll find the PID = 36 is Dolby AC-3 and its type is PES.
Any other question, please feel free to let me know.

**Comment by ojw28** [comment]
Thanks for the confirmation. Closing as bad media.
