### ISSUE TITLE
Exoplayer hide PlaybackControlView onClick (not onTouch)

### ISSUE THREAD

**Issue by asadullahrao** [google/ExoPlayer#3194]
![screenshot_20170819-145051 1](https://user-images.githubusercontent.com/429518/29485614-fe59b29e-84ed-11e7-880e-48131b7c2d43.png)

![screenshot_20170819-145045 1](https://user-images.githubusercontent.com/429518/29485609-ee5eef58-84ed-11e7-9156-6a31b6b3b431.png)
My Player hides when i click on player, controls show but player hides. After that when i again click on player it hides controls and show player again...

Using exoplayer:r2.4.0

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
