### ISSUE TITLE
[Question] Are CEA-608 captions supported via HLS?

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#3198]
Does the ExoPlayer v2 HLS stack currently support cea-608 captions embedded in the video stream? 

I've added a `TextRenderer.Output` using `mExoPlayer.setTextOutput(this)`, and haven't seen any calls to `TextRenderer.Output.onCues(List<Cue>)`. 

Am I missing a config step, or is this just not supported?

**Comment by AquilesCanta** [comment]
It is supported. The "Apple 4x3 basic stream" sample in the demo app has CEA608. But you will have to select them manually. What you can do is:

1. Add your sample to the demo app.
2. First try the HLS basic stream to see what the expected behavior is.
3. Run and select manually using the "Text" button. Once you press "Ok", CC will start showing at the bottom of the screen.
4. Try your stream and repeat the selection process. If it works, you can follow the DemoApp to implement this in your app. [This post](https://medium.com/google-exoplayer/exoplayer-2-x-track-selection-2b62ff712cc9) should also be helpful.
5. If it doesn't work, it is possible that your stream does not include CC in the accessibility channel 1 and it is not signalling this correctly to the player. In that case, you should probably update your media to include a EXT-X-MEDIA tag to your master playlist.

**Comment by fougere-mike** [comment]
Got it, thanks!

**Comment by ebr11** [comment]
We have streams with CEA subs as well.  The tracks show up in Exo and can be selected using the normal track selection methods (see track output below).  However, the subs do not appear on the player.  Other types of text tracks display fine.

We are using the SimpleExoPlayer as our UI surface.  Is there something else we need to do to make these show properly?

```
 I/System.out: Tracks [
 I/System.out:   Renderer:0 [
 I/System.out:     Group:0, adaptive_supported=N/A [
 I/System.out:       [X] Track:0, id=0, mimeType=video/avc, bitrate=8265875, supported=YES
 I/System.out:     ]
 I/System.out:   ]
 I/System.out:   Renderer:1 [
 I/System.out:     Group:0, adaptive_supported=N/A [
 I/System.out:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, supported=YES
 I/System.out:     ]
 I/System.out:   ]
 I/System.out:   Renderer:2 [
 I/System.out:     Group:0, adaptive_supported=N/A [
 I/System.out:       [X] Track:0, id=1/8448, mimeType=application/cea-608, supported=YES
 I/System.out:     ]
 I/System.out:   ]
  I/System.out: ]

```

**Comment by AquilesCanta** [comment]
You mean SimpleExoPlayerView? If it works with "other types of text tracks", then there is nothing else you need to do UI-wise. But you should make sure the stream actually contains CC.

**Comment by ebr11** [comment]
Yes, I meant the SimpleExoPlayerView.  Thanks.
