### ISSUE TITLE
Why shouldn't AdaptiveMediaSourceEventListener be used to cutomise player behaviour, and what alternatives are there?

### ISSUE THREAD

**Issue by emdash-ie** [google/ExoPlayer#3199]
In [this issue](https://github.com/google/ExoPlayer/issues/2909), @ojw28 says that the AdaptiveMediaSourceEventListener shouldn't be implemented in order to change the behaviour of the player.

Why is that? Is there an alternative way to get the same information and then use it? I need to implement video adaptation algorithms that depend on the media duration, size, bitrate, and load duration of recently downloaded DASH chunks when updateSelectedTrack() is called on a TrackSelection.

I've looked at using a customised TransferListener and a DashChunkSource, but those still don't get me what I need.

At the moment I'm thinking I'll need to fork the library and modify ChunkSampleStream to take an additional AdaptiveMediaSourceEventListener that it could call methods on directly, rather than using an event dispatcher as it does with the current listener - does this make sense?

**Comment by ojw28** [comment]
> In this issue, @ojw28 says that the AdaptiveMediaSourceEventListener shouldn't be implemented in order to change the behaviour of the player. Why is that?

It's just not intended for that purpose. One example of a way in which this interface is not designed for the purpose you describe is that events are posted to the listener on a specified looper thread. If it were intended to be used by playback logic then the listener would be called directly on the playback thread and/or expose getters suitable for calling directly from the playback thread. Another example is that you can only set one listener, where-as if it were intended to drive playback logic (in addition to logging / debugging / analytics, which is what it's actually designed for) then we'd allow more. Having said all this, if it works for you regardless then there's nothing stopping you from using it... ;).

> At the moment I'm thinking I'll need to fork the library and modify ChunkSampleStream to take an additional AdaptiveMediaSourceEventListener that it could call methods on directly, rather than using an event dispatcher as it does with the current listener - does this make sense?

In general the approach will be to extend or fork whatever components you need so that you can add hooks for obtaining the required information. If `ChunkSampleStream` is the best place to access the information you need, then yes this makes sense.

**Comment by emdash-ie** [comment]
Cool, thanks for the detailed answer – I appreciate the explanation :)
