### ISSUE TITLE
Stream pauses when moving from wifi to data and vice-versa

### ISSUE THREAD

**Issue by bolder5** [google/ExoPlayer#3202]
### Issue description
When running a stream in the exoplayer demo, when I switch from WiFi to data, the stream always pauses for a second or so.  An example stream I've been using is: https://cms.stream.publicradio.org/cms.mp3
When I use just the Android MediaPlayer to run the stream, switching between WiFi and data causes no pause in playback.  Is there anyway to stop exoplayer from causing this issue? 

### Reproduction steps

1. Add https://cms.stream.publicradio.org/cms.mp3 to the demo app.
2. Select and run stream.
3. Turn off wifi.
4. Stream pauses
5. Turn on wifi.
6. Stream pauses

### Link to test content
https://cms.stream.publicradio.org/cms.mp3

### Version of ExoPlayer being used
r2.5.1

### Device(s) and version(s) of Android being used
LG G3 6.0, Galaxy s5 5.0, Galaxy s7 6.0

**Comment by soadri** [comment]
Have you checked the buffer of player? (Both ExoPlayer and Android MediaPlayer)

**Comment by ojw28** [comment]
I think you'll always get a slight discontinuity in playback at some point (possibly up to several minutes after the network switch), since there's no way that I'm aware of for a player to seamlessly reconnect to a live mp3 URL.

The reason the discontinuity occurs at the time of the network switch, and is more severe than MediaPlayer, is tracked by https://github.com/google/ExoPlayer/issues/1606.
