### ISSUE TITLE
ExoPlayer.getDuration() doesn't work after preparing a DynamicConcatenatedMediaSource

### ISSUE THREAD

**Issue by keyboardr** [google/ExoPlayer#3205]
getDuration() returns TIME_UNSET until setPlayWhenReady(true) is called even when the first window is a fixed size. The various seekTo() methods similarly don't work even when the first window should be seekable. Suspect this is related to the use of DeferredTimeline.

**Comment by tonihei** [comment]
Thanks for using a new issue :)

You're right that getDuration() will return TIME_UNSET first when the actual duration is not available yet. However, I suspect you get a second timeline update (listener.onTimelineChanged) soon after where everything is set correctly. setPlayWhenReady(true) shouldn't have any influence on this. Maybe that's just a coincidence because you call it soon after player.prepare(mediaSource)?

As further explanation: This behaviour is caused by the DeferredTimeline class you have mentioned (although you shouldn't bother about this one as it is internal only) and ensures that our timeline mirrors the playlist immediately even though we don't have all the information to play the media yet.
