### ISSUE TITLE
Exoplayer skips so reluctantly switched to VideoView player for smooth playback

### ISSUE THREAD

**Issue by TvstartupConsultant** [google/ExoPlayer#3208]
### Issue description

Deployed Amazon's Fire TV Builder app, but discovered ExoPlayer would not provide smooth playback on full HD.  Tested another application that uses VideoView and playback is smooth.  Reluctantly switch to other application.  Downlink speed is 12mbps and bitrate of video is 4mbps so smooth playback is expected.

### Reproduction steps
Build Amazon's Fire TV Builder app; and test using Full HD at 4m bitrate.

### Link to test content
A video feed link is available privately; upon request: to be mailed to
dev.exoplayer@gmail.com including the issue number in the subject line.

### Version of ExoPlayer being used
ExoPlayer Version is that used in Amazon Fire TV Builder.

### Device(s) and version(s) of Android being used
Tested on First and Second Generation Fire TV Stick, and current generation Fire TV.

### A full bug report captured from the device
Upon request the captured full bug report using "adb bugreport" will be sent to dev.exoplayer@gmail.com including the issue number in the subject
line. After Issue Number is provided.

**Comment by TvstartupConsultant** [comment]
Issue occurs using a live stream, but not using VODs.  Also concerned about possible issue at CDN, two CDNs were tested, but result was the same.  The variable is ExoPlayer vs. VideoView.  The goal is smooth playback.

**Comment by ojw28** [comment]
You should report this issue to Amazon rather than here. It's hard to tell what version is being included in the Fire TV Builder app, but a search of their repository suggests it's ExoPlayer V1, which is really quite old at this point. They may also have added their own changes to the library. See also the note [here](https://google.github.io/ExoPlayer/supported-devices.html) about Amazon devices.
