### ISSUE TITLE
How To Easily Implement Subtitles And Sound Channels؟؟

### ISSUE THREAD

**Issue by sherafatpour** [google/ExoPlayer#3213]
How To Easily Implement Subtitles And Sound Channels؟؟

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

I would also suggest you take a look at our demo app, which includes subtitle and track selection and should serve as a good starting point.
