### ISSUE TITLE
The temporary keys authenticated .m3u8 vod using exoplayer

### ISSUE THREAD

**Issue by rofeifei** [google/ExoPlayer#3222]
Hi,
I want to play the authenticated .m3u8 vod using exoplayer,to authenticate we append our secure token then the server generated temporary keys(timestamp,and client id) as parameters to the query requested in exoplayer ,the url looks like the follow:
ex:https://xxxxxxxxxxxxxx/video/accounts?timestamp={timestamp}&clientId={clientId}&token={token} ,so i can play it&it works fine.but,once the secure token authentication expired when i try to replay the video ,the server returns an access denied because the token is no valid,please how i can use secure token authentication in exoplayer,i found Digital Rights Management (DRM) please what is the easy way to do this???
thank you.

**Comment by ojw28** [comment]
Does your authentication mechanism work correctly with other players or platforms? If so, please could you clarify what they do differently that you think ExoPlayer isn't doing?

It sounds a bit like an application or configuration issue to me. You can presumably obtain a fresh URL before starting playback, to handle the case where the app has been in the background for a long period of time since it obtained a URL for some previous playback. If you're obtaining a fresh URL and seeing it expire during a single playback, then it feels like your URLs are expiring too quickly for the scheme you describe to work.

**Comment by rofeifei** [comment]
Thanks for your response.The hls url(https://xxxxx/video/accounts.m3u8?timestamp={timestamp}&clientId={clientId}&token={token}) token is valid for 4 minutes, Actually we try to use  backend application to generate and update this url every 4 minutes in exoplayer url.

**Comment by ojw28** [comment]
As above, does this approach work seamlessly with other players or platforms? It just doesn't sound like a good idea to me...

**Comment by AquilesCanta** [comment]
@rofeifei, could you please provide a full example of how the authentication works? I mean, detailing every server request and response. 

I don't think this is something the spec seems to contemplate.

That being said, what could potentially work is injecting your custom DataSource for playlists that wraps around a default one. And when open is called for a data spec with an outdated url token, you update the token with a new one. The ExoPlayer HLS module doesn't need to know about your authentication mechanism.

**Comment by ojw28** [comment]
Closing due to actionable information. If you're able to provide full answers to the two posts above, please do so here and we'll re-open the issue.
