### ISSUE TITLE
GroupTrack issue regarding subtitle

### ISSUE THREAD

**Issue by MuhammadFarooq** [google/ExoPlayer#3242]
In the example the class ExoPlayerImp.java TrackGroups are show the values but when i integrate the library in my project TrackGroup is showing null value , i am just stuck can you please guide out of this issue ?

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
