### ISSUE TITLE
DASH WEBB-VP9 with ShakaPackager and Encrypting through a 3rd party Widevine vendor not playing in Exoplayer

### ISSUE THREAD

**Issue by Shyri** [google/ExoPlayer#3254]
Hi,
We are currently trying to use WEBM-VP9 using ShakaPackager and 3rd party WideVine vendor.
For some reason it's not playing properly in Exoplayer. It is throwing this exception when trying to build the key request:
[bugreport-2017-09-11-12-14-55.txt](https://github.com/google/ExoPlayer/files/1292176/bugreport-2017-09-11-12-14-55.txt)

> com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2943

Also, we are seeing this other log:

> WVCdm   : OEMCrypto_Initialize Level 1 success. I will use level 1.
WVCdm   : CdmEngine::QueryKeyControlInfo
WVCdm   : CdmEngine::GenerateKeyRequest
WVCdm   : CdmSession::GenerateKeyRequest: init data absent
WVCdm   : CdmEngine::GenerateKeyRequest: key request generation failed, sts = 58

We couldn't find any clue about what -2943 error is. We created an issue for ShakaPackager too but it seems packaging is done correctly, you can check it here.
https://github.com/google/shaka-packager/issues/267

Attached you can find bugreport file

**Comment by ojw28** [comment]
I think the PSSH data in your manifest is not what the Widevine CDM expects. The PSSH data is:
```
0, 0, 0, 52, 112, 115, 115, 104, 1, 0, 0, 0, // Full atom header (version 1)
-19, -17, -117, -87, 121, -42, 74, -50, -93, -56, 39, -36, -43, 29, 33, -19, // Widevine UUID
0, 0, 0, 1, // KeyIdCount (1)
108, -20, -77, 91, 37, -93, -71, 48, 64, -12, -31, -6, -72, 32, 52, 30, KeyId
0, 0, 0, 0 // DataSize (0)
// No scheme specific data here
```
I think `CdmSession::GenerateKeyRequest: init data absent` suggests that the Widevine CDM expects some scheme specific data at the end of the box. You should follow up with Widevine to work out exactly what the PSSH box should look like.

**Comment by ojw28** [comment]
It looks the the expected format for the scheme specific data is a serialized protocol buffer, as defined on page 10 of [this doc](https://storage.googleapis.com/wvdocs/Widevine_DRM_Encryption_API.pdf). If you set the scheme specific data correctly then it's likely this will resolve your issue. It may or may not also be the case that you need to use version 0 pssh atoms, although I'd hope both version 0 and version 1 atoms work correctly.

**Comment by pscplayco** [comment]
We've been able to advance a bit on this issue. Basically, we built correctly (hope so) the PSSH information according the last points discussed in the ShakaPackager thread indicated above, and now the player is able to make a successful license request to the License server. This is the Manifest used:

http://dev-cdn-lb.parsifalentertainment.com/Tests/SHAKA_LUTHERSERIESVP9WEBM3/LUTHERSERIESVP9WEBM3_upperCase.mpd

Nevertheless, then we get a decoder error like this:

com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(1, video/x-vnd.on2.vp9, -1, -1, 640, 360, -1, 1.0, -1, -1, null, 3144240000, false, 1280, 720, -1, -1, -1)

Same VP9/WEBM video plays correctly when No DRM is applied, but probably because different libraries are used? Is that error giving anyone any hint about what could be the problem?

Thanks!

**Comment by ojw28** [comment]
Without complete information as requested in the issue template, there is nothing we can do to help with this. Please also verify that the content plays correctly in Shaka player. If it doesn't, your content is probably still broken.

**Comment by pscplayco** [comment]
Just to update this thread, this test is failing in Exoplayer V1 with error stated above, while it's decrypting and playing fine in Exoplayer V2.

**Comment by ojw28** [comment]
Good to hear!
