### ISSUE TITLE
Error: This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by hooked82** [google/ExoPlayer#3263]
### Issue description
After pulling down the latest code from the release-v2 branch (r2.5.2), you will receive a gradle error stating the Gradle plugin requires Studio 3.0 minimum.  This may only be an issue if you are on anything lower than Android Studio 3.0.0-Alpha 4, which I am on Android Studio 2.3.3.

I found this was also happening in the Firebase project, which they have resolved:
https://github.com/firebase/quickstart-android/issues/294

I was able to get around the problem by updating the ExoPlayer project Gradle
from:
`    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta4'
        classpath 'com.novoda:bintray-release:0.5.0'
    }`

to:
`    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.novoda:bintray-release:0.5.0'
    }`

### Reproduction steps
- Ensure you're on Android Studio 2.3.3
- Update the ExoPlayer project to release-v2 (r2.5.2)
- Build the project
- See the error in the console.

### Link to test content
N/A

### Version of ExoPlayer being used
r2.5.2

### Device(s) and version(s) of Android being used
Google Pixel with Android 7.1.2

### A full bug report captured from the device
N/A (Project does not build)

**Comment by ojw28** [comment]
This is intentional. Sorry, you will just have to use a newer version of Android Studio.

**Comment by hooked82** [comment]
Wait, what!?  You're saying it is intentional to force us to use a product that is not released and currently in Alpha!?  Please reopen and fix this, I can not use unstable alpha builds and should not be forced to by this project

**Comment by andrewlewis** [comment]
I think this change was necessary because one of the our build variants depends on a library that needs to be desugared. The build was broken without the update.

**Comment by hooked82** [comment]
As mentioned above, changing it to 2.3.3 resolves the issue though.

**Comment by ojw28** [comment]
I'm not sure we're forcing you to do anything. You can make a local change until AS3 is stable. Or just checkout a slightly older release. There are fairly easy ways for you to get around this issue.

The reason we did this relates to de-sugaring Cronet when using the Cronet extension, and some additional modules that we have internally. I agree it's somewhat unfortunate, particularly since the reason isn't visible in the open source project. Let us find out how long it's going to be until a stable AS3 release. If it's soon, then this problem is pretty transient. If it's still a way out, we can look at moving the open source project back (which is possible, but is likely to complicate things a little for us internally).

As an aside, the beta releases of AS3 have proven at least as stable as AS2.3 for me (and faster, and with some cool new features). Perhaps you're not able to install it for policy reasons, but if you are able to, I'd encourage you just to install it and give it ago. It's possible to install alongside AS2.3 and have them co-exist on the same machine.

**Comment by ojw28** [comment]
Given absence of other complaints, plus AS3 being *very* close at this point, I think we're going to leave things how they are and push through. Sorry!
