### ISSUE TITLE
Video 4K render black on the surface texture

### ISSUE THREAD

**Issue by DavidNguyen2017** [google/ExoPlayer#3267]
- I had tested source code from "release-v2-surfacetexture-experiment" branch, it is work well with video 2k, but with video 4k it can not play, show shake black screen.

- I am testing on Amlogic setup box, Android 6.0.1 API 23

- Can you help check this problem?

Thanks,

**Comment by ojw28** [comment]
That's an experiment, as opposed to being an officially supported branch. Do you have any issues using the proper release branch?

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Thank you for your supporting,

On the release branch player work well with video 4k, but in the my project i want to use Exoplayer to play video 4k with gl surface view. So i want work around on this problem, but i do not have any ideas how to fix it. do you have any advise for me?

Thanks,

**Comment by ojw28** [comment]
Unfortunately this falls beyond the scope of this issue tracker, as it's not something we're currently supporting. I suspect you're hitting a platform limitation. It might also be worth patching the changes in the experimental branch on top of the latest `release-v2` branch, in case some fixes made to V2 since the experimental branch was forked resolve the problem. Good luck!
