### ISSUE TITLE
Ad Load Error

### ISSUE THREAD

**Issue by jkellysbgtv** [google/ExoPlayer#3279]
### Issue description
Ad audio plays but video does not.  Both should play. Seems similar to the issue fixed in #3180 

### Reproduction steps
Use emailed links with "ima sample ad tags" in demo app. Occurs on a galaxy S3 mini on Android 4.4.2, possibly other devices.

### Link to test content
sent via email

### Version of ExoPlayer being used
2.5.3

### Device(s) and version(s) of Android being used
Occurs on a galaxy S3 mini on Android 4.4.2, possibly other devices.

### A full bug report captured from the device
sent via email

**Comment by andrewlewis** [comment]
The bug report doesn't contain a full stack trace for the load error. Please could you add some logging for this in, e.g., the EventLogger, reproduce the error and paste the full stack trace?

I wasn't able to reproduce the error on a Pixel device, but when I tried on a Samsung Galaxy S3 Mini I initially saw a load error due to the device clock being wrong, which breaks the SSL handshake.

After setting the device clock, the load error was fixed but playback was not smooth and there was a segmentation fault when playback of the ad completed. It looks like this device isn't fast enough to decode VP8 format video in software at 640 * 360. If you have control over the ad format, you could try sending H.264/AVC video which seems to play better on this device.

**Comment by jkellysbgtv** [comment]
Ok, I emailed in the logcat output when the error is occurring.

**Comment by kinhdang** [comment]
Hello all !

I have the same issue, occurpation in Android Box, sometime after play ads, to play audio only and no video.

Thanks.

**Comment by andrewlewis** [comment]
The logcat contains `E/ACodec: dequeueBuffer failed.` and some logging about dropped frames.

To make progress on this, it would be useful to have a full bug report captured using `adb bugreport`, attached here or emailed, then we can investigate further. Thanks.
