### ISSUE TITLE
 Resize mode not working properly with multiple video

### ISSUE THREAD

**Issue by Anilugale** [google/ExoPlayer#3291]
```
playerView.setResizeMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);
```

![screenshot_2017-09-25-12-39-04](https://user-images.githubusercontent.com/9414411/30797049-353e5d66-a1f2-11e7-80a3-acdeca1339a0.png)

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
