### ISSUE TITLE
Offline license helper release and renew license

### ISSUE THREAD

**Issue by skyshine999** [google/ExoPlayer#3295]
I am playing offline drm videos in my application, i wanted to  handle renew and release license,should i need to handle from server side or from client side,renew license returning new byte array but release license not returning anything

 offlineLicenseHelper.release(offlineAssetKeyId);
 offlineLicenseHelper.renew(offlineAssetKeyId);

**Comment by ojw28** [comment]
The release method is documented not to return anything. What would you need/expect to be returned? We really can't help you if your issue reports do not fully describe the problem or question. Please clarify. Thanks.

**Comment by skyshine999** [comment]
Actually i wanted to know what exactly renew and release license doing, how i need to do handle these things

**Comment by ojw28** [comment]
* Renew makes a license request to renew the offline license. This is useful if the offline licenses you issue are only valid for a limited period of time (e.g. 30 days). You might want to renew periodically (e.g. every 7 days), so that the user always has a fairly large period of remaining license validity (e.g. 30 - 7 = 23 days).
* Release releases the license and makes it unusable on the device.
* Both involve network requests: Renewal to extend the new extended license, and release because your server might need to know the license has been released, for example if your policy is to allow an offline license to be held by only one N user devices at once.
* Both communicate license usage information back the the server. This is useful if your license has a short clock (e.g. 30 day validity, but only 2 days validity from the point at which the user starts watching), because it will tell the server whether the short clock was activated.
