### ISSUE TITLE
Is exoplayer able to play video in reverse - question

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#3296]
Hi, I am trying to make a feature in app, so user can play video in reverse order to seek to desired video position. So far, I have implemented the functionality to get player current position and decrease it by e.g. 10s. And it works fine but appearance is little bit choppy, so I am looking for feature to play video in reverse order(like we did in 90's with VHS).
Dose exoplayer support this or is there a way to achieve this?

thanks

**Comment by tonihei** [comment]
That's not something that can be done easily with a player, because video encodings make use of redundancies in the video frames and compress the data such that you need to decode the video in forward direction from a key frame to reconstruct the original frames. The choppy behaviour you see is the player constantly decoding everything from the last key frame to your requested position (which takes some time). The only way to do this is to re-encode your video in reverse order.

**Comment by lazarvgd** [comment]
I thought that is much easier. Thank you, I will close this one.
