### ISSUE TITLE
HLS - Provide easy way to access current bitrate

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#3297]
What's the correct way to get the "current bitrate" of the video track been played ? I understand one may refer to the hls/dash bitrate written in the playlist or the actual bitrate shown by the renderer. I am interested in both. I am using v2 and issues like #646 and #3006 are not helping much on this front.

**Comment by soadri** [comment]
player.getVideoFormat().bitrate

may be in the playlist

**Comment by davibe** [comment]
@soadri as mentioned in #3006 that's for internal usage only and I always read `-1`in my cases (mostly hls)

**Comment by ojw28** [comment]
@AquilesCanta - Do you think we could/should push the bitrate into the video formats that are consumed by the video renderer (or the audio formats, in the case of audio only streams)? It's probably going to remove some confusion here.

**Comment by AquilesCanta** [comment]
Sorry, hadn't seen this. Will look into it.

**Comment by seiji-fli** [comment]
any progress on this? could really use this for analytics

**Comment by AkivaGit** [comment]
I have the same problem, can't see the current bitrate, and it seems that the player doesn't play the highest bitrate available, even when connection is good. Please advise

**Comment by ojw28** [comment]
I can propagate the bit-rate through as part of a related change.

**Comment by AkivaGit** [comment]
That would be really helpful, since now I can't even debug the bitrate.
Also if I try to use  trackSelector.getParameters().withForceLowestBitrate(true)
the player doesn't play anything, and I get onLoadCanceled.
In general, I'm trying to control the bitrate according to our needs by using
trackSelector.getParameters().withMaxVideoBitrate(), but can't make it to take higher bitrate.
Maybe to lower it will go. didn't try yet.
I don't really want to go the the path of customing TrackSelector before I use simpler solutions.

Can you approximate please when can we expect to such change to happen?
Thanks

**Comment by AkivaGit** [comment]
Sorry for bothering you again, but I need some help with this.

I decided to customize TrackSelector so now I can log the auto-selected bitrate of the track, or can force to choose a track with desired bitrate.
1. What is the difference between AdaptiveVideoTrack and FixedVideoTrack, defined in the Trackselector?
2. What class or other object should I customize if I want to log the switching between different bitrates, when connection quality changes, during playback, after the initial video track was chosen?

Thanks in advance

**Comment by ojw28** [comment]
This issue is tracking propagating the bit-rate, not generally debugging application specific issues. Please file a new issue instead. Please also keep in mind statements like "player doesn't play anything" are not specific enough for us to help, so please try and be as specific as possible and provide concrete reproduction steps.

**Comment by ojw28** [comment]
Bit-rate should be propagated in `dev-v2` now.
