### ISSUE TITLE
Cannot Play 1920x1080 Live Stream - SamSung Galaxy T285

### ISSUE THREAD

**Issue by hiepnm** [google/ExoPlayer#3300]
I have a live stream (HLS) exposed by AceStreamEngine (P2P stream engine). It has resolution: 1920x1090.
I'm using ExoPlayer to play that stream on my device (Tablet: Samsung Galaxy T285). But it cannot play above stream.
I try with another HLS stream (exposed by Ace too) with lower resolution. And They played OK.
I think my issue related to this issue topic: https://github.com/google/ExoPlayer/issues/886
But when I play that stream with MxPlayer. It can play on it.

_I want to play high resolution stream on my device._ How to deal with problem?

**Comment by hiepnm** [comment]
My device has:
MediaCodecUtil.maxH264DecodableFrameSize() = 2097152
I think it's enough for 1920x1080 frame size

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
