### ISSUE TITLE
ExoPlayer playback mp4 setRepeatMode buffering

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#3301]
### Issue description
Use demo playback mp4, setRepeatMode All, when playback not to end buffering

### Reproduction steps
ExoPlayer Demo app, setRepeatMode, use this url send to your email

### Link to test content
send to your email

### Version of ExoPlayer being used
master brash and  r2.5.3

### Device(s) and version(s) of Android being used
Galaxy s8+ and Nexus 5, should all Android device

**Comment by tonihei** [comment]
The issue is probably related to #1874. Please ensure that the audio and video streams in your media have the same duration to prevent this from happening as long as we don't have an internal workaround for #1874.

**Comment by guness** [comment]
note to @tonihei , I have downloaded different videos from internet, almost none of them has exact match. 
bad news: all of them loops fine on desktop (end users will not know if the media is broken),
bad news $2: only some of those video files have or show this problem.

**Comment by tonihei** [comment]
@guness For bad news $2: A small difference between the audio and video duration is fine and playback should loop without problems. The problem only arises for larger differences - that's why you only some of your videos show this problem. 
For bad news $1: Whatever you're using to play these files on desktop, they are probably doing something different (e.g. keeping a much larger buffer or actively ignoring the problem). We are aware that the desired behaviour for most people is to ignore the different durations and just play out both streams, that's why the issue tracker #1874 is marked as bug.
