### ISSUE TITLE
Video title, duration, description and image

### ISSUE THREAD

**Issue by mmfaragallah** [google/ExoPlayer#3312]
### Issue description

How to get the video title, duration, description and image ?

**Comment by ojw28** [comment]
Please provide a more complete description of what you're trying to do. Is this during playback, or not? What kind of media is it? Etc.

**Comment by mmfaragallah** [comment]
Sorry for inconvenience.

I am asking a general question for any HLS or DASH video. I am downloading those files and need to get these information about the video I am working on. Info like title, description, duration and image. 

How can I get information like this ?

Shall I wait till download all the files, then extract those info from the downloaded file or what ?

Thank you.

**Comment by ojw28** [comment]
ExoPlayer is currently focused on playback rather than metadata extraction (although we do support metadata during playback for MP3 and MP4 files). We may support metadata extraction outside of playback at some point in the future, but we have no firm plans at this time.

By the way, I wouldn't expect HLS and DASH streams to even contain this type of metadata, so I'm not really sure that what you're asking is even possible. Normally when HLS and DASH streams are being played, a single provider owns both the serving side and the client side app, and they will expose this kind of information to their app through a completely separate API.

**Comment by mmfaragallah** [comment]
Thank you for your kind help and reply. Appreciated 👍
