### ISSUE TITLE
Getting video duration problem (DASH)

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#3317]
I'm reproducing a DASH video with exoplayer and I get a duration smaller than the real duration of the content by calling the method SimpleExoPlayer.getDuration(). When I seek to the duration returned by exoplayer the video still reproduces its content for 3 minutes more.

If I get the duration from DashManifest (field "mediaPresentationDuration"" at the manifest field) I get the real duration of the content.

So the question is, Why is the exoplayer getting the duration of the content by obtaining the firstPeriodSeekInfo and the lastPeriodSeekInfo by surfing the different AdaptationSets instead of returning the one shown at the manifest?

Exoplayer version is 2.4.4

I'm using a mobile phone with model SM-G920F with android version 6.0.1

**Comment by ojw28** [comment]
Please provide all the information requested in the issue template. There is nothing we can do to investigate this issue without a link to the affected content.

**Comment by laurafuente** [comment]
The problem is that the content I'm using is not clear

**Comment by ojw28** [comment]
We may well be able to tell what's wrong just from the manifest in this case, without needing to play the content. For the symptoms you describe, it's most likely the manifest is incorrect.

If you could provide the manifest, what you believe the "correct" duration to be, what getDuration() returns, and how long the player actually plays for (presumably equal to the "correct" duration), we can take a look.

**Comment by laurafuente** [comment]
Hi,
I've attached the manifest of the problematic video:  
[manifest.mpd.zip](https://github.com/google/ExoPlayer/files/1356679/manifest.mpd.zip)

The duration I get from exoplayer is: 5187682
The correct duration is: 5431835 that is the one show at the manifest by the field mediaPresentationDuration="PT1H30M31.835708S" or the field Period duration="PT1H30M31.835708S"

The expected duration (5431835) is the one that I get from shaka-player.

Thanks, Laura

**Comment by ojw28** [comment]
The reason this happens is because the text adaptation track only defines 5187 seconds of content:
```
<SegmentTimeline>
    <S t="0" d="60000" r="85" />
    <S d="27682" />
</SegmentTimeline>
```
Do you know why that is? In general, I think that the sum of the segment durations should match the duration of the period.

**Comment by soutua** [comment]
We have the same issue with ExoPlayer and DASH streams. Some of the content provided to us by studios have text tracks that don't actually have any text and the content provider has set the length of these tracks to 1 minute. And ExoPlayer apparently returns the smallest duration of any track as the duration of the stream, hence returning 60 seconds as the duration.

Here is an example stream that can be used to demonstrate the problem: http://viihde-amfcache8.pa.saunalahti.fi/netpvr/v2/bbb_test/index.mpd

**Comment by ojw28** [comment]
I think you should get the media fixed.

1. If there are subtitles but they end early, which is true in the first case, there should be a final segment or segments that are empty subtitle chunks extending to the media duration.
1. If there are no subtitles, which I think is true in the second case, there should definitely not be a corresponding AdaptationSet. Including one is bad for the user, because the client will allow selection of a subtitle track that doesn't actually exist.

It should be pretty easy to write a script that detects these kind of issues just from scanning the manifest, so it seems like something you could easily flag up during media ingestion.

**Comment by jerenieminen** [comment]
I work with soutua and I agree that we should fix the media. However I'm still wondering that why is Exoplayer calculating the duration of the media instead of just using the value given. Even the DASH implementation guidelines says following:

The presentation duration is determined through either the @mediaPresentationDuration attribute or if not present through the sum of the PeriodStart and the Period@duration attribute of the last Period in the MPD.

http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf
page 88

**Comment by ojw28** [comment]
What we're really calculating is the duration of the media that's available to the user. For on-demand streams we'd expect this to be the same as the presentation duration, but for live streams this is not the case (the presentation is typically unknown). The logic we use to calculate the duration works in both cases, where-as just taking the presentation duration does not.

**Comment by jerenieminen** [comment]
However in the end you are not getting the media duration but the length of the shortest segment timeline as the logic doesn't care about the presentation timeline. To my understanding nothing in DASH guidelines state that segment timelines should have the same duration or even the same start time.

**Comment by ojw28** [comment]
I'm not sure about the spec mandated guarantees, but having one shorter than another doesn't feel like something someone would sensibly decide to do on the serving side. None of the streaming providers we've worked with to date have this issue, either.

**Comment by jerenieminen** [comment]
I'm not saying it is sensible to have different durations or in perfect scenario that should be the case. However none of the other DASH players we worked with have issues with this. 

Also looking at the code you are putting a lot of effort on finding maximum start time and minimum end time across AdaptationSets within a Period: 
https://github.com/google/ExoPlayer/blob/deb9b301b2c7ef66fdd7d8a3e58298a79ba9c619/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L586

So if there are no issues with different durations why loop through all the AdaptationSets and seek for the minimum period available across all when you could just look the duration from the first one?

Or if you don't believe that AdaptationSet segment timelines are identical, I believe you should seek for the maximum availability period instead of the minimum to determine the duration.

**Comment by ojw28** [comment]
For live streams, adaptation sets will legitimately have slightly ragged start and end positions (and hence different durations). This is inevitably the case unless you mandate that all adaptation sets must use exactly the same segment durations.

The logic is designed to find the window for which media is available in all of them (i.e. the maximum start time, and the minimum end time). I would argue this is the right thing to do, because it means that when a user performs a seek within the window we're going to be able to request the corresponding media to fulfill that seek operation immediately. If we were to take the maximum end position as you suggest, it would allow the user to seek to a position where we don't have media for all adaptation sets yet. We'd then have to wait until that media became available via a manifest refresh prior to being able to satisfy the seek.
