### ISSUE TITLE
ExoPlayer downloaded encrypt video suddenly quitting in samsung Tablet

### ISSUE THREAD

**Issue by subu1** [google/ExoPlayer#3321]
This error came while playing next downloaded AES encrypt video. **A/libc: Fatal signal 11 (SIGSEGV) at 0x6d594634 (code=2), thread 22625 (Loader:Extracto)** pls help me anyone knows already i spent more time, but no-one giving proper solution.(In mobile it's working perfectly)

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
