### ISSUE TITLE
Exoplayer unable to play video on real devices. like xiaomi redmi note 3.

### ISSUE THREAD

**Issue by csahu42** [google/ExoPlayer#3325]
Video smoothly play on virtual device but couldn't play on physical devices.  i used Xiomi Redmi Note 3 device.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
