### ISSUE TITLE
Large video file taking more delay(6 secs) to prepare readystate in tablet

### ISSUE THREAD

**Issue by subu1** [google/ExoPlayer#3329]
I'm using android exoplayer for playing encrypted videos. below is the code for playing and i had faced a problem in tablets like Fatal Exception and taking more delay for loading a video from local folder sd-card. Mobile devices readystate called within one or two seconds

```
      try {
	SecretKeySpec mSecretKeySpec = new SecretKeySpec(ConstantKey.ENCRYPT_PWD.getBytes(), ConstantKey.AES_ALGORITHM);
  	IvParameterSpec     mIvParameterSpec = new IvParameterSpec(ConstantKey.ENCRYPT_IV.getBytes());

         Cipher   mCipher = Cipher.getInstance(ConstantKey.AES_TRANSFORMATION);
            mCipher.init(Cipher.DECRYPT_MODE, mSecretKeySpec, mIvParameterSpec);

            dataSourceFactory = new EncryptedFileDataSourceFactory(mCipher, mSecretKeySpec, mIvParameterSpec, BANDWIDTH_METER);
            extractorsFactory = new DefaultExtractorsFactory();

 	 exoPlayer.prepare(new ExtractorMediaSource(Uri.parse(mFilePath), dataSourceFactory, extractorsFactory, new Handler(), null));
	 exoPlayer.setPlayWhenReady(true);
      
	  } catch (Exception e) {
            e.printStackTrace();
        }
```

Note: Mobile devices readystate called within one or two seconds

**Comment by ojw28** [comment]
It seems most likely that this issue is a result of the encryption scheme you're using, and the associated code you're using for decryption. I think `EncryptedFileDataSourceFactory` and the `DataSource` instances that it creates are custom to your app (or at least, not provided by the ExoPlayer library). Is that correct? If this issue happens only when using those components, and not when playing content that's not encrypted, then this is an application issue that you'll need to debug yourselves.

Please clarify.

**Comment by subu1** [comment]
public class EncryptedFileDataSourceFactory implements DataSource.Factory {

    private Cipher mCipher;
    private SecretKeySpec mSecretKeySpec;
    private IvParameterSpec mIvParameterSpec;
    private TransferListener<? super DataSource> mTransferListener;

    public EncryptedFileDataSourceFactory(Cipher cipher, SecretKeySpec secretKeySpec, IvParameterSpec ivParameterSpec,
                                          TransferListener<? super DataSource> listener) {
        mCipher = cipher;
        mSecretKeySpec = secretKeySpec;
        mIvParameterSpec = ivParameterSpec;
        mTransferListener = listener;
    }

    @Override
    public EncryptedFileDataSource createDataSource() {
        return new EncryptedFileDataSource(mCipher, mSecretKeySpec, mIvParameterSpec, mTransferListener);
    }
}
ExoPlayer Library : compile 'com.google.android.exoplayer:exoplayer:r2.5.3'

Note: provide me sample for playing encrypted video file from local path

**Comment by ojw28** [comment]
We don't know what `EncryptedFileDataSource` is either. And in any case, this is your code and it's not our responsibility to debug it.

If you can reproduce the problem with unencrypted  content, please let us know on #3326. If the problem only reproduces when using encrypted content and your custom `DataSource`/`DataSourceFactory`, then the issue is most likely with that code, and you'll need to work out what's going wrong there.
