### ISSUE TITLE
Issue with 60fps high-res videos playback

### ISSUE THREAD

**Issue by hrugames** [google/ExoPlayer#333]
I was trying to play a high-res video (2560x1440) with 60fps locally from SD Card using ExoPlayer. And I saw issues with sound and video. After a few days I discovered a magic number encoded in the default MediaCodecVideoTrackRenderer: https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L447

Seems it delays the frame rendering for too long, so it causes jitteriness for the audio and video. I tried to change the 11ms to 20ms and it helped in my case. 

Is there a better solution than manipulating this constant?

Device: Samsung Note 4
Version: 4.4.4
Example of video at 2560x1440 at 60fps: https://www.youtube.com/watch?v=bfUeocvzApg
Note that the video needs to be re-encoded to have hardware support on Note 4.

Video format from ffprobe that was used for test:
Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.15.102
  Duration: 00:06:37.83, start: 0.046440, bitrate: 20540 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 2560x1440 [SAR 1:1 DAR 16:9], 20410 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler

**Comment by ojw28** [comment]
It's (in my opinion) debatable whether or not 60fps content makes sense for pre-Lollypop devices, because there was no way of telling the decoder release an output buffer with any kind of a guarantee about which display VSYNC that buffer would actually hit the screen on. Timing of the frame release had to be done from Java, which limits accuracy somewhat (and required a hack - which is the Thread.sleep call that you found). Even when the frame is released, there aren't any strong guarantees going down the stack about how that will map onto VSYNC. The net result is that although you may find high end devices running pre-Lollypop are capable of 60fps decoding, it's doubtful whether the stack is capable of smoothly releasing one frame for each display cycle (assuming the display is 60Hz). And if it's not, there' not so much point in sending 60fps content, and you may as well save on bandwidth.

In Lollypop there's a new timed frame release API. If you look at MediaCodecVideoTrackRenderer, you'll see that there's a different code path on Lollypop that makes use of the new API and avoids the sleep call. So 60fps content should work without modification on Lollypop devices.

If you do want to enable 60fps content on pre-Lollypop then you're right, you'll need to tweak those constants, or remove them, or re-architect the way frame release works to be on a different thread. I suspect you'll end up subtly breaking something though, so my recommendation would be to target Lollypop for 60fps, and use 30fps for older devices.

**Comment by ojw28** [comment]
p.s. I thought the Note 4 got a Lollypop update already. Although perhaps it's carrier specific and/or you didn't accept it.
