### ISSUE TITLE
[Question]How to contorl volume in each channel?

### ISSUE THREAD

**Issue by xdestiny110** [google/ExoPlayer#3335]
Accroding to #2659, I implement my `AudioProcessor` and `TrackRenderersFactory` to adjust volume in each channel.
In `AudioProcessor`
```
    override fun queueInput(buffer: ByteBuffer) {
        val position = buffer.position()
        val limit = buffer.limit()
        val size = limit - position

        if (m_buffer.capacity() < size)
            m_buffer = ByteBuffer.allocateDirect(size).order(ByteOrder.nativeOrder())
        else
            m_buffer.clear()

        when(m_encoding){
            C.ENCODING_PCM_16BIT->{
                for(i in position until limit step 2){
                    m_buffer.putShort((buffer.getShort(i) * volume[m_ch++]).toShort())
                    m_ch %= m_channelCnt
                }
            }
            else->{
                throw IllegalStateException()
            }
        }
        buffer.position(limit)
        m_buffer.flip()
        m_outputBuffer = m_buffer
    }
```
Volume of each channel is saved in array `volume`.

I play with AAC 7.1 to test it. 1st, 2nd, 5th, 6th, 7th and 8th channel work well(which means I only hear voice from one side of headphone). But 3rd and 4th channel does not work( I can hear voice from both side of head phone).

My device is Samsung Galaxy S6. OS is Android 7.0.
Is there something I ignored? Can someone help me?

**Comment by ojw28** [comment]
This is a duplicate of https://github.com/google/ExoPlayer/issues/2659, I think?

**Comment by andrewlewis** [comment]
I think this is an attempt to implement the AudioProcessor suggested on that issue.

The code looks reasonable at first glance. To debug further I'd probably have a look at the data coming out of this AudioProcessor to make sure the channel volumes are changed as expected in the output PCM data.

We saw problems with Samsung Galaxy S6 when decoding multi-channel media (see `MediaCodecAudiorenderer.codecNeedsDiscardChannelsWorkaround`). That workaround shouldn't affect this specific issue, though, because the input has eight channels. It might be worth testing on another device if you have one available, just to verify that this isn't a device-specific issue.

**Comment by xdestiny110** [comment]
I can reproduce this issue on Samsung Galaxy S6 and XiaoMi 5S. 

I think output PCM data from AudioProcessor is corret because my code work well on AAC 4.0. I find it does not work on any audio format with .1 such as 5.1 or 7.1.

**Comment by andrewlewis** [comment]
It sounds like we can be reasonably confident that the AudioProcessor is working correctly, because it works with 4 channel input.

Is the actual issue with how the audio is getting downmixed to stereo (unrelated to the AudioProcessor)? Could you provide a bit more detail/clarification on what is broken? I'm not sure I understand "3rd and 4th channel does not work( I can hear voice from both side of head phone).". If you use your AudioProcessor to selectively unmute each channel in turn, what do you hear each time?

**Comment by xdestiny110** [comment]
Sorry I did not explain clearly...
I adjust volume of each channel by setting array `volume` in code. 
When I set `volume[0]` to 1.0 and `volume[1..7]` to 0, I can hear 1st channel voice from left side of headphone. Similarly, when I set `volume[1]` to 1.0 and `volume[0, 2..7]` to 0, I can hear 2nd channel voice from right side of headphone.
But when I set `volume[3]` to 1 and other to 0, I can hear 3rd channel voice from both side of headphone.

As for downmixed, where I can find code releate to it?

**Comment by andrewlewis** [comment]
That might be working as intended (though I'm not sure what channel index 3 maps on to). I think I'd expect a rear center or front center speaker channel to play out of both left and right after downmixing to stereo, for example.

If that's not the behavior you're looking for, perhaps you could investigate doing the downmixing to stereo as part of your audio processor.

**Comment by xdestiny110** [comment]
As you say, I write downmixing in my audio processor and it work as I wish.
Thank you for your advices! Although I still wonder why default downmixing result is different from what I think...
