### ISSUE TITLE
Exoplayer is not request the media fragments after refresh the playlist

### ISSUE THREAD

**Issue by parthialu** [google/ExoPlayer#3344]
In our origin project we are using the Exoplayer 2.3.0 to play the dash live contents in Andriod mobile. In the manifest.mpd the attribute minimumUpdatePeriod="PT8S" and minBufferTime="PT10S".  They are two issues we are seeing here

Issue 1: 
Sometimes the origin is not able to create new live fragments within minimum update period 8secs so it will return the last old manifest file without any updated fragments. In that case the exoplayer is got the old manifest file and it lead to buffer under run in the player, so we are getting video buffering.  In the next refresh it got the updated manifest file and start playing the video. 

In the problematic cases like if it receives the same manifest file for 8secs refresh period or buffer under run is there any mechanism in the exoplayer to refresh manifest file frequently ( for example refresh at every ~300ms)? .

I have attached the fiddler capture issue_1.saz for your analysis. (Check the packet no 10 and 11)
[issue_1.zip](https://github.com/google/ExoPlayer/files/1378919/issue_1.zip)

Issue 2:
The origin gives the updated manifest file for each refresh period. But the exoplayer is not requesting the fragments sometimes between two manifest refresh period. We didn't see any problem in video playback, but the live latency is increasing.  Why it is not requesting the fragments between the manifest refresh?

I have attached the pcap file for your analysis issue_2.pcap (packet no 97 and 191)
[issue_2.zip](https://github.com/google/ExoPlayer/files/1378948/issue_2.zip)

### Reproduction steps
Simply play the live content with the minimumUpdatePeriod="PT8S" and minBufferTime="PT10S". They problem will reproduce after ~ 1-2 hrs.

### Link to test content
Any content

### Version of ExoPlayer being used
Exoplayer 2.3.0

### Device(s) and version(s) of Android being used
Mobile : Redmi Note 4 
Andriod version : 7.0 NRD90M

### A full bug report captured from the device
issue_1.saz
issue_2.pcap

**Comment by parthialu** [comment]
can anyone please reply for the query?

**Comment by botaydotcom** [comment]
@parthialu :
- For issue 1: I don't think there's an easy way to customize/set minimum update period, other than the current way of parsing from MPD file. I think one workaround you can do is to subclass `DashManifestParser`, override `buildMediaPresentationDescription` and construct the new `DashManifest` with whatever `minUpdateTimeMs` value you would like to use (this will override the value parsed from the Dash manifest). Other than that, I'm not sure if this is something we would like to change / provide another way to override this value.

- For issue 2: The reason is because every time after the player finishes loading a new manifest, it will calculate the list of available segments until that point. So if before the next manifest update point, the player has already finished loading all the available segments calculated from previous update, it will not load any more segment. One caveat is in certain cases (I think live streaming case might be one of them), in addition to the fetching after min-update-time loop, `DashMediaSource` also has a built in timer that will periodically update the list of available segments without fetching new manifest (it simulates a manifest update using the old manifest). Currently the timer runs every 5s.
