### ISSUE TITLE
Is there a way to set video sound to a certain dB level(a sound normalizer) while video is playing?

### ISSUE THREAD

**Issue by shirensong** [google/ExoPlayer#3349]
I have a video list playing in the loop, but the sound level of some videos is high and the sound of the others is low. 
I found ffmpeg has a command to normalize a video to a new dB level.
https://github.com/slhck/ffmpeg-normalize
So my question is : 
 Is there a way to set the all videos' sound to a certain dB level while playing and how?

**Comment by andrewlewis** [comment]
There is currently no way to have ExoPlayer automatically adjust the audio volume to normalize the volume of songs in a concatenation, and I doubt we will implement this functionality as we'd need to scan and analyze all media that will be played to do the normalization. So for now I'm going to close this as it's infeasible.

If possible I'd suggest re-encoding the tracks so that their volumes are normalized. If that's not possible but you do know the relative gains of the songs, you could look into adjusting the output volume when transitioning between songs. To make this work perfectly you'd need to set the volume in an AudioProcessor to ensure the volumes are set correctly either side of a gapless song transitionin (see also #3657).
