### ISSUE TITLE
How to check a video format whether is possible to render on a specific device?

### ISSUE THREAD

**Issue by hiepnm** [google/ExoPlayer#3350]
Hi, ExoPlayer Developers.
I see so many issues with "device specific issue" tag. Almost it can't render video because of device capabilities < video format. I and many developers are working with this issue.
So I have one question:
If I have a given video format (width, height, bitrate ...). Which helper functions to check it whether is possible render on a specific android device? And how to do that before I play my video?

**Comment by ojw28** [comment]
A device not supporting playback of a certain (width, height, bitrate) because it exceeds the device's capabilities is different to a device specific issue. The first is expected, because every device has an upper bound on what it's capable of doing. The second is not expected. A good example of the second would be a broken platform decoder.

By default ExoPlayer already avoids selecting tracks that exceed the device's capabilities, unless such a track is the only option (e.g. a regular MP4 with only one video track to choose from). If a track that exceeds the device's capabilities is the only option we default to trying to play it, since the within-capabilities/exceeds-capabilities boundary is fuzzy in practice (there's no such thing as a hard limit on supported bitrate; it depends on many other factors such as how the bitrate varies through the media, what other apps are using CPU on the device, etc). If the device really can't handle it, playback will fail.

Is there an actual concrete issue that you're hitting that you'd like us to look at?

**Comment by pradeep-vernekar** [comment]
Exo Player 2+ bitrate filter logic is dependent on device codec capability.
Prior to Exo Player 2, the bitrate filter logic is not based on the device codec and was just checking the resolution and frame rate compatibility. 
What is the best way to bypass the CODEC check in Exo Player 2+. is there any risk by doing this?
