### ISSUE TITLE
[Question] Accessibility - DefaultTimeBar and readout text

### ISSUE THREAD

**Issue by nimdokai** [google/ExoPlayer#3352]
I have a problem with `DefaultTimeBar` (also with `SeekBar`) while accessibility mode ON.

I have modified the readout text by using `host.setContentDescription(CharSequence contentDescription)` in `AccessibilityDelegateCompat.onPopulateAccessibilityEvent(View host, AccessibilityEvent event)`.
Even though the text is set, it is always reading out actual position of the video - in example 'three-oh-five".
Question 1: Is it possible to change the read out text for `DefaultTimeBar`?

Secondly, the read out text goes on, like "three-oh-five three-oh-six three-oh-seven" until the SeekBar is no longer visible or focused.
Question 2: Is it possible to read out only once actual position?

Above problems occurs only for `DefaultTimeBar` and `SeekBar`. For other Views there is no such problem. I have also `TextView` for `@id/exo_position`, and it works fine.

**Comment by andrewlewis** [comment]
For `DefaultTimeBar` we try to do approximately what `SeekBar` does with regard to accessibility. I think it's intentional that the playback position is read out repeatedly. If you need do to something different, I suggest forking this class and implementing whatever behavior you need there. If you have a concrete suggestion for an improvement, please send a pull request and we can consider it. Thanks!
