### ISSUE TITLE
Support AV1 codec

### ISSUE THREAD

**Issue by ohenepee** [google/ExoPlayer#3353]
The still-in-development replacement for VP9 (.webm) would be cool to test, but is it supported by ExoPlayer? Tried to find answers on Google Search but Google keeps assuming I meant **avi** so I guess that's bad naming right there.

**Comment by andrewlewis** [comment]
It's not supported yet. It's being developed as part of libvpx so it might be straightforward to add it to the vp9 extension at some point.

**Comment by andrewlewis** [comment]
I'll actually leave this open to track adding support but it's unlikely we'll get to it soon. Thanks!

**Comment by jeeb** [comment]
AV1 is part of [libaom](https://aomedia.googlesource.com/aom/), so I'm not sure if it will be part of libvpx at any point. Although it is true that the two share histories up until VP10 (where libvpx was used as the base to start AV1 reference development off of). Libaom seems to have recently switched to cmake, so building it shouldn't be a large endeavor.

The initial soft freeze of the format is supposed to happen at the 31st of October, although what this exactly will mean is still somewhat open according to Timothy ([link to talk](https://bambuser.com/v/6908002#t=2416s), unfortunately due to how the setup was done the audio volume is very low). When the final bit stream freeze for AV1 will happen is still up in the air.

**Comment by ohenepee** [comment]
Is this happening anytime soon since the latest release of AV1?

**Comment by utack** [comment]
Bitstream is not even frozen yet,no need to jump the waterpistol quite yet

**Comment by andrewlewis** [comment]
I started looking into this, but am having trouble getting the build step to work: libaom is seems to cross-compile for the various Android architectures successfully using CMake, but then gradle complains that the compile commands JSON files were not actually generated and the build fails. If anyone has pointers to how to make this work that would be useful!

**Comment by ohenepee** [comment]
@andrewlewis I guess you can open an issue here https://bugs.chromium.org/p/aomedia/issues/list

**Comment by ohenepee** [comment]
@andrewlewis Any progress?

**Comment by utack** [comment]
Android Support is coming in Android Q  
https://www.youtube.com/watch?v=iTC3mfe0DwE&t=13m40s

**Comment by MuVen** [comment]
.AV1 file arent still supported by exoplayer yet ?

**Comment by ohenepee** [comment]
It would be really helpful if the *dav1d* release is integrated into ExoPlayer

**Comment by sofijajvc** [comment]
ExoPlayer AV1 extension has now been published. You can read more about the extension [here](https://medium.com/google-exoplayer/playing-av1-videos-with-exoplayer-a7cb19bedef9).
