### ISSUE TITLE
EXO player out of sync between video&audio (HLS)

### ISSUE THREAD

**Issue by jungjaid** [google/ExoPlayer#3390]
We faced Exo player out of sync between video&audio, we used HLS and we combined video and audio in the same chunk. Our device used SDMC amlogic shipset, and we found some logcat **"D/AmlogicVideoDecoderAwesome( 3818): checkout pts___!!_mLastTimeStamp=2345125, mPtsRecoveryCount=3"**. Any idea for this case, it is cause of our media content or not ?

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
