### ISSUE TITLE
The problem of handling abnormality of the player

### ISSUE THREAD

**Issue by androidengineer** [google/ExoPlayer#3398]
Hello, we use Exoplayer to play the video of HLS format in our development, but there are some anomalies in operation:
When set the playlist in the player, one of them fails to be decrypted. Then the player will call error monitoring, and the player will stagnate. Could you tell me that how can I set the player to skip the wrong resource and continue playing the next audio/video?
In the error monitoring, I can only get the parameter ExoPlaybackException. How can I judge the position of this wrong resource. It seems to handle this through the error. Using getdataSpec. uri to matche is incorrect. If parsing fails, the result is the decrypted link not the video address.
 
Thank you!

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
