### ISSUE TITLE
Problem playing videos in api below 21

### ISSUE THREAD

**Issue by asidahan** [google/ExoPlayer#3404]
We have videos with ads in our app. When we play video it plays well for the first times, but if we play the same video many times, eventually it will get stuck at some point and won't play anymore. 
After the ad finishes the video don't play and it won't play again until we remove the app or clear the cache. it happens on random videos.
The last thing that we see in the log is "Destroying NativeAdDisplay" and the video don't play anymore.
It happens only on devices with api 21 or below. on devices with higher api there is no problem.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by asidahan** [comment]
Hi,
can you please tell me what is missing because I red the template and I
don't know what is missing?

<http://www.gini-apps.com/>

**Comment by ojw28** [comment]
Pretty much everything:

### Issue description
Describe the issue in detail, including observed and expected behavior.

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com including the issue number in the subject line.

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com including the issue number in the subject
line.
