### ISSUE TITLE
Play video with wrong PresentationTimeUs

### ISSUE THREAD

**Issue by kingstone59** [google/ExoPlayer#3415]
I try to read some mp4 file with wrong (async) PresentationTimeUs (audio sample start after video) it's work correctly with native mediaplayer and VLC (those players use PTS for playing video correctly).

Is it a know issue ?

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
