### ISSUE TITLE
White screen on sample

### ISSUE THREAD

**Issue by jagiellonczyk14** [google/ExoPlayer#3436]
### Issue description
While starting the sample app from 
https://github.com/google/ExoPlayer
The same with https://github.com/Nksonsit/Learning_ExoPlayer
The audio is working hovewer video does not (white screen), I had tried to open couple videos, wait for them to buffer, but nothink helps the screen is blank.
### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

I am Using nexus 5x api 26 android studio 3.0 emulator for tests

P.S I am also looking for a way to adapt the projected video to SimpleExoPlayerView size (it is relatively wide) I know that it will distort the video but i am fine with that.

**Comment by AquilesCanta** [comment]
We will need more context here. If the demo app has a problem with rendering any kind of video, we will notice. I use a 5x for daily development. Usually emulators are not ideal, but I don't think it is the problem here (though trying a physical device wouldn't hurt, if you have one). Please fill the issue template below, and we will look into it. Note that this is most likely a problem in the application code.

**Comment by jagiellonczyk14** [comment]
Honestly I do not know what To add I just dowloaded the sample app and tried to run it, I had not modified It at all.
