### ISSUE TITLE
Assertion error in SampleMetadataQueue

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#3441]
### Issue description
This is unfortunately the kind of issues I don't enjoy creating since it's hard for me to gather relevant information but I'll do my best. 
During a test session after migrating from ExoPlayer v1 to v2 we noticed one single occurrence of failing assertion here: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/SampleMetadataQueue.java#L118

The issue seemed to have happened after a failing load request and even though we tried with broken videos we have been unable to re-produce this issue. 
Now when this is being rolled out to a bigger audience I do see more of these failing assertions in Fabric which worries me a bit.

It should be noted that we are not using the dash component. Instead we have our own implementations of `MediaSource` and `ChunkSource` with friends and I'm open to the possibility of having some bug in our code. However, I'm not sure where or how to further troubleshoot the issue.

Unless you would immediately have an idea of what the root cause might be, maybe some elaboration around how `discardUpstreamSamples` works and why `discardCount` might end up being invalid to work our way backwards.

### Reproduction steps
Unfortunately we have not yet found any re-pro steps.

### Link to test content
None

### Version of ExoPlayer being used
exoplayer-core r2.5.3
exoplayer-okhttp r2.5.3

### Device(s) and version(s) of Android being used
From what I can see this issue spans between _at least_ android versions 4.4.4 and 7.1 on various devices including Samsung Galaxy S6 Edge and Nexus 6.

### A full bug report captured from the device
Here's a stack trace:
```
10-26 14:11:48.749  9537  9695 E AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
10-26 14:11:48.749  9537  9695 E AndroidRuntime: Process: com.spotify.music.debug, PID: 9537
10-26 14:11:48.749  9537  9695 E AndroidRuntime: java.lang.IllegalArgumentException
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.source.SampleMetadataQueue.discardUpstreamSamples(SampleMetadataQueue.java:118)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.source.SampleQueue.discardUpstreamSamples(SampleQueue.java:147)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.onLoadError(ChunkSampleStream.java:318)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.onLoadError(ChunkSampleStream.java:38)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:387)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-26 14:11:48.749  9537  9695 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ojw28** [comment]
That type of failure is indicative of trying to discard data from the write side of the queue that's already been consumed from the read side. I think the key piece of code is in `ChunkSampleStream`, and looks like:
```
boolean cancelable = !isMediaChunk || bytesLoaded == 0 || mediaChunks.size() > 1;
boolean canceled = false;
if (chunkSource.onChunkLoadError(loadable, cancelable, error)) {
  <load gets canceled and any samples loaded get discarded>
```
The `cancelable` boolean is supposed to evaluate whether it's _possible_ to cancel the chunk and discard what we've already loaded from it on the write side. If the chunk is already being consumed on the read side this should evaluate to false, because it's a lot more difficult to replace the chunk in this case. We then call `ChunkSource.onChunkLoadError` to find out whether it would actually like to cancel the chunk, passing `cancelable` as an argument. We invoke this method regardless of whether the chunk is cancelable, because a `ChunkSource` may want to know about errors even for non-cancelable chunks.

What's not ideal here is that we're relying on `ChunkSource.onChunkLoadError` returning false if `cancelable` is false. We should probably add a `cancelable` check directly into the condition in `ChunkSampleStream`, so that we ignore a `ChunkSource` trying to cancel a non-cancelable load rather than trying to cancel it and ending up failing.

What I'd suggest you do on your side is take a look at your `ChunkSource.onChunkLoadError` implementation. If you're ever returning true when the `cancelable` argument is false, you shouldn't do that and that's the root cause. Please let us know what you find. On our side we'll add in the extra check as described above.

**Comment by ojw28** [comment]
There was also an edge case where we evaluated `cancelable` to true when it should have been evaluated to false, which was fixed in https://github.com/google/ExoPlayer/commit/d90d04190e3643435fd4b4a3515cbd9fbe784cc1. I think it would only cause a problem if you have embedded sample queues turned on though, which I doubt is the case (the stack trace indicates the failure is discarding from the primary queue). I think it is possible to cause a problem when you only have a primary queue too, but only if you get *very* unlucky (i.e. the error occurs having loaded exactly one sample, with the renderer having read the sample but not having polled to try and read another one). I suspect the probability of that ever happening is vanishingly small in practice.

**Comment by pakerfeldt** [comment]
Thank you, this was exactly what we needed. We do indeed send `true` in `onChunkLoadError`, possibly when `cancelable` is false. Now that I read through the javadoc it's pretty clear, somehow we missed that part. Will go through our implementation again tomorrow and report back. Thanks!

**Comment by pakerfeldt** [comment]
We use the return value in `onChunkLoadError` to force a new request for failing ones in order to try on a different base url (or CDN).

Let's consider the case where a CDN suddenly fails and the client ends up with a chunk that isn't cancelable. Let's also assume we have another CDN that is successfully providing future chunks. The chunk that isn't cancelable will continue re-trying the same URI. Even though future chunks downloads fine will playback fail in this case?

Out of curiosity we tested returning `false` always in `onChunkLoadError` (I know this isn't a proper implementation) and noticed that it seems to retry forever. Even after we get `onPlayerError` the chunk loader keeps re-trying.

**Comment by ojw28** [comment]
> Out of curiosity we tested returning false always in onChunkLoadError (I know this isn't a proper implementation) and noticed that it seems to retry forever. Even after we get onPlayerError the chunk loader keeps re-trying.

Pretty sure that doesn't happen in vanilla ExoPlayer. When `onPlayerError` occurs `DashMediaSource.releasePeriod` is called to release the period. This calls `DashMediaPeriod.release`. This calls `SampleStream.release`. This cancels any ongoing loads. If you're able to reproduce with vanilla ExoPlayer please let us know. Else you've likely broken this flow in your custom components.

**Comment by ojw28** [comment]
> We use the return value in onChunkLoadError to force a new request for failing ones in order to try on a different base url (or CDN). Let's consider the case where a CDN suddenly fails and the client ends up with a chunk that isn't cancelable. Let's also assume we have another CDN that is successfully providing future chunks. The chunk that isn't cancelable will continue re-trying the same URI. Even though future chunks downloads fine will playback fail in this case?

The chunk ending up not being cancelable is probably fairly unusual. If the server is broken at the start of playback or at the start of any individual chunk request, then none of the chunk will have been loaded and so the load will be be cancelable. The load will also be cancelable in all cases where the server just doesn't have the chunk (e.g. 404s), since again none of the chunk will have been loaded. For a chunk to be non-cancelable you need it to have been partially loaded and for the amount of media in the buffer to be less than one chunk. So it's unclear how much you really need to focus on this. You should at least get some data about how many users end up with avoidable playback failures as a result of ending up in this state, before worrying about it too much.

I'd also argue that if you have partially loaded the chunk and want to retry loading the same chunk from another server, you should find a way of doing that without canceling the load or discarding anything (it's more efficient just to continue loading the chunk from the new server than it is to throw away what you've loaded and re-load the whole chunk again). YouTube do something like this in a custom `DataSource`. You might also be able to do it by adjusting the `MediaChunk` to use some other `Uri` in `onChunkLoadError` somehow, but not actually canceling it.

If you want to not load the chunk that's failed and load a different chunk, that's pretty difficult for us to support in the non-cancelable case, since it would introduce a discontinuity into the media being consumed by the renderers. We're unsure it's worth spending time on this, because we don't see this case as something that should occur often.

**Comment by pakerfeldt** [comment]
Thanks Oliver! I think we have all the information we need now. 👍

**Comment by ojw28** [comment]
FYI, the change above will ignore cancelation requests for non-cancelable loads (and log a warning).

**Comment by pakerfeldt** [comment]
👍 We have dealt with our issue as well.
