### ISSUE TITLE
Simpleexoplayerview and black screen

### ISSUE THREAD

**Issue by sn32247** [google/ExoPlayer#3448]
I have musicplayer with notification bar in service that use exoplayer. Myapp have an musicplayerActivity and an musicservice for notification.
When i click on notification, call musicplayeractivity and exoplayer screen is black.
I dont want refresh or reset player.i want only show musicplayerActivity and player without any change.please help me

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
