### ISSUE TITLE
Exoplayer throws an exception after Ads

### ISSUE THREAD

**Issue by Gobi1989** [google/ExoPlayer#3462]
Hi All,

I'm using Exoplayer (r2.5.4) for playing DRM content along with Ads. As the player starts well with Ads and resume back to content video. We are getting an error while resume the DRM content video after 2nd/3rd AD.

Steps to Reproduce:-

Start the Drm content video along with Ads (pre Ads, 3 mid Ads and post Ads). After pre AD the content video starts to play as expected, now wait for second AD. The second Ad also will play as expected. The issue is after the second Ad (at some cases at after third AD) while resume back the content video the the Exoplayer throws an Exception as attached. 

Note:- The same value we are using in iOS Fair play and its working there. I had suppressed the AD and played the DRM content video its working fine at first time, i can able to play the whole video. While playing the same DRM content video again by clicking the play button at 2nd or 3rd try it fails with same exception. 

I'm using Samsung s8 with 7.0 android version

[ads_error_log.txt](https://github.com/google/ExoPlayer/files/1474076/ads_error_log.txt)

**Comment by tonihei** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
