### ISSUE TITLE
(Android 8.1 ONLY) When stacking 2 SimpleExoPlayerView and playing both, one is transparent, but audio still works.

### ISSUE THREAD

**Issue by jedashford** [google/ExoPlayer#3477]
EXAMPLE OF BEHAVIOR (short Video):  https://www.youtube.com/watch?v=hJnI-vlvI-0
This is API 25 and API 27. API 27 has the issue described where the 2nd SimpleExoPlayerView on top of another SimpleExoPlayerView is just blank.
 
### Issue description
In API 27 (could be 26 also, but we didn't test) when we 'stack' two SimpleExoPlayerView on top of each other (one smaller like a Picture-in-Picture), the SimpleExoPlayerView on top highest z order) appears to go completely transparent. Audio continues, but video is gone.

We are using HLS streams.

In API 25 the behavior is NOT present. All aspects function as expected and the video plays (see attached youtube video (https://www.youtube.com/watch?v=hJnI-vlvI-0)

### Reproduction steps
Using a relative layout, stack two different SimpleExoPlayerView on top of each other play them both at the same time. (one smaller on top of the other larger (see video for the details)

### Link to test content
I have only a video and can build this into the demo if needed:
https://www.youtube.com/watch?v=hJnI-vlvI-0

### Version of ExoPlayer being used
2.1.1 is what we have in production. We have also tested with 2.5.4 with the exact same issue present in API 27.

### Device(s) and version(s) of Android being used
Pixel, Pixel XL, api 25 and api 27

### A full bug report captured from the device
[bugreport-sdk_gphone_x86-OPM1.171004.001-2017-11-17-23-05-53.zip](https://github.com/google/ExoPlayer/files/1484390/bugreport-sdk_gphone_x86-OPM1.171004.001-2017-11-17-23-05-53.zip)

**Comment by erseno** [comment]
Hey, 
Apologies, I do not have any answers to your question but some findings because I encountered the same issue and found your question when searching.
I do not think this is ExoPlayer issue. I use a third party video library and that uses MediaPlayer. I have a similar picture-in-picture feature. On Oreo, I get the same issue as you but anything pre-Oreo is fine
I think it might be a bug with surface view on Oreo because that is what the third party library uses.
I'll let you know if I find out more
Cheers

**Comment by erseno** [comment]
here is a video of my issue.
Notice that the first video which is minimised to the corner becomes transparent when the first starts playing. This only happens on Oreo

https://youtu.be/AAklKU4lB6g

**Comment by jedashford** [comment]
@erseno Yup, thats our same behavior. I suspect google changed something that the Team here will need to look into. We don't have any third party libraries in the mix here. Can you share your codebase here with the Exoplayer team? I was planning on trying to implement this with their example project, but time has been limited.

**Comment by erseno** [comment]
Sure, I'll upload my sample and provide a link

**Comment by erseno** [comment]
Here is the link

https://www.dropbox.com/s/2xtvy620d31vhli/OoyalaPictureInPictureSample.zip?dl=0

**Background**
I use the third party library called Ooyala 
Ooyala can use the ExoPlayer if you tell it to.
I use MediaPlayer for a specific reason 
Ooyala can use Exo 2.5.3
Go to VideoFragment.Java. Line 54. 

The line 

new Options.Builder().setUseExoPlayer(false).build()

Pass in true to use Exo. False to use MediaPlayer

Right now it is on False

**Comment by erseno** [comment]
Hi Jedashford
Were you able to work around this issue in some way ?
I think this might be AOSP bug with surface view . Was thinking that my project might not be appropriate for submission because debugging might be tricky due to core code hidden behind the Ooyala third party lib . I was thinking of replicating the issue using just exo player , do you think that might be enough for them to debug ?
Cheers

**Comment by andrewlewis** [comment]
It sounds likely that this is an issue with `SurfaceView`.

With `SimpleExoPlayerView` you can set the attribute `surface_type="texture_view"` to use a `TextureView` instead. That may resolve the issue, but please note that this can result in higher battery drain and won't work for DRM content that requires a secure output path.

**Comment by ojw28** [comment]
It's also worth having a play around with [setZOrderMediaOverlay](
https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderMediaOverlay(boolean)) and [setZOrderOnTop](
https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderOnTop(boolean)) to see if those help at all.

Closing, since this isn't an ExoPlayer specific issue. It feels like a general platform issue related to having multiple `SurfaceView`s placed on top of one another.

**Comment by erseno** [comment]
Hi Jedashford

The third party SDK I used recently updated to Exo Player 2.6.1 which resolved the issue for me. Check if that is the case for you is well?

Cheers
