### ISSUE TITLE
player.getCurrentManifest returns null in DefaultTrackSelector.selectTracks

### ISSUE THREAD

**Issue by sergiomartinez4** [google/ExoPlayer#3489]
Question:
I'm implementing a custom Track Selector by extending the DefaultTrackSelector and overriding the selectTracks(...) method.
Inside the selectTracks method I need to access the DASH manifest so I call exoPlayer.getCurrentManifest(), but the getCurrentManifest() method sometimes returns null.
By debugging the code I notice that there's a race condition where the selectTracks method is sometimes called before the manifest is set (therefore before the onTimelineChanged callback). I see the onTimelineChanged callback happens on the main thread and the selectTracks on a different thread.

So, is there a way to make sure I get a valid Dash manifest by the time the selectTracks is called?

**Comment by AquilesCanta** [comment]
The DefaultTrackSelector is intended to have all the information it needs in the TrackGroups. Could you explain a little bit more about your use case? This could either be an enhancement opportunity or maybe the track selector is not the right place to do this (maybe you need to write your own AdaptiveTrackSelection).

> So, is there a way to make sure I get a valid Dash manifest by the time the selectTracks is called?

I doubt it. But maybe someone from the team can confirm. Worst case scenario, you could make a selection without the manifest, and later (when onTimelineChanged is called) pass the manifest to your selector and call invalidate().

**Comment by sergiomartinez4** [comment]
The use case is to select the previously downloaded Dash Representation as a FixedTrackSelection, and we currently need the Representation url from the Manifest object as the reference.
It'll be great to be able to access the manifest by that time, but I think now I have a couple of options to try.
Thanks for the information @AquilesCanta

**Comment by ojw28** [comment]
If this is for playback of offlined content, it's preferable to filter the other representations out of the `DashManifest`, so that there's only one representation available for selection by the time the track selector gets involved. The offlined representation will then be selected without you having to do anything non-standard on the track selector side.

If you're injecting the `DashManifest` directly into `DashMediaSource` through the constructor, construct a filtered manifest prior to injection. [DashManifest.copy](https://github.com/google/ExoPlayer/blob/r2.5.4/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifest.java#L92) is useful for doing this. If you're passing a manifest uri to `DashMediaSource` then pass a custom manifest parser that wraps the regular one and returns a copy of the parsed manifest with all but the offlined representations filtered out. A filtering manifest parser looks something like (thanks @erdemguven !):

```
  private static class FilteredDashManifestParser implements Parser<DashManifest> {

    private final DashManifestParser wrapped;
    private final ArrayList<RepresentationKey> filter;

    private FilteredDashManifestParser(ArrayList<RepresentationKey> filter) {
      this.wrapped = new DashManifestParser();
      this.filter = filter;
    }

    @Override
    public DashManifest parse(Uri uri, InputStream inputStream) throws IOException {
      DashManifest manifest = wrapped.parse(uri, inputStream);
      if (filter != null) {
        return manifest.copy(filter);
      }
      return manifest;
    }
  }
```

**Comment by sergiomartinez4** [comment]
That's a great idea @ojw28 I'll try this out. Thanks a lot!
