### ISSUE TITLE
Question: Tunneled video playback and Bluetooth audio output

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#3506]
Hi,

I'm using Tunneled video playback with Exoplayer 2.4 and Android Tv 7.1

Can you confirm if is there any known Android restriction/limitation when using  Tunneled video playback and Bluetooth audio output?

I'm doing that with a device that is still "under development" and I'm facing the following issues:
- No audio playback at all: Not on the Tv Set (HDMI) nor on the Bluetooth device.
- Video playback is not stable.

If I disable Tunneled video playback or Bluetooth output (just one of them or both), everything works ok.

Thank you!
Alfonso

**Comment by andrewlewis** [comment]
This seems to be a known limitation. [Internal reference: b/33260579]

"[...] the default Android audio policy manager doesn't support routing a direct output to a2dp. When doing video tunneling, Android routes the audio to the HAL using a direct output instead of the default mixer output. This is necessary because the audio HAL used for tunneling needs to read the audio timestamps provided by the application in order to do audio/video sync. The default Android policy manager only supports routing the primary output (mixer) to a2dp, that's why this use case only works when tunneling is disabled."
