### ISSUE TITLE
exoplayer #EXT-X-VERSION:3 loop

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3515]
Hello friends I have an m3u8 file with the following config below:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:61060
#EXTINF:6.000
70.ts
#EXTINF:6.000
70.ts
#EXTINF:6.000
70.ts
#EXTINF:6.001
70.ts

The exoplayer executes the normal parts but when it arrives on the last line after executing it for once, he wanted it to execute in an infinite loop thus always playing live live.

Thank you...

**Comment by AquilesCanta** [comment]
Please provide a link to reproduce the issue. Also, please explain what the expected and observed behaviors are.

Note: It is a bit weird that every segment points to the same file, but I don't see why it would be a problem (besides the efficiency concern).

**Comment by admobwebmaster** [comment]
The problem is that when it plays the last line it stops playing.
I want to make it always reproduce so when it reaches the last line it automatically goes back to the first one and starts again being like an infinite loop understands.

**Comment by AquilesCanta** [comment]
As @ojw28 correctly pointed out, having every segment pointing to the same file means you need to signal a discontinuity everytime (otherwise, PTSs are going to be wrong). It was not clarified above, but the manifest also needs to be modified by adding segments if you want exoplayer to keep playing, if not, it will eventually get stuck in buffering state (i.e.: It will stop playing). Please be more specific in descriptions.

> it stops playing

is not clear enough to understand what's going on. 

In any case, if you want the file to loop indefinitely, you are better off just looping 70.ts using a `ExtractorMediaSource` in a `LoopingMediaSource`.

**Comment by admobwebmaster** [comment]
Hi, thanks for the help!
  So how do I create the # EXTM3U?

Could I pass the correct command?
