### ISSUE TITLE
Change surfaceView through java 

### ISSUE THREAD

**Issue by BioGram** [google/ExoPlayer#3519]
### Issue description
changing surfaceView type through java code is not avaliable,
for change surfaceView type to TextureView we must use XML layout to change it through xml

### Version of ExoPlayer being used
1fdc11f2b30547392c6fe6d2485493837d8f41a2

**Comment by andrewlewis** [comment]
I'm not sure I follow what the question is exactly, but in case it helps: you can include both a SurfaceView and TextureView in your layout then show/hide them as required. Call `SimpleExoPlayer.setVideoSurfaceView` or `SimpleExoPlayer.setVideoTextureView` when you switch views.

**Comment by ojw28** [comment]
It's intentional that `SimpleExoPlayerView` does not support switching surfaceView type through code. Supporting dynamic changes to the surfaceView type is difficult, which is not true of the other parameters that we do support changing through code. As @andrewlewis notes, you can try implementing your own layout if you require this functionality.

**Comment by BioGram** [comment]
By the way,
I've implement my own custom SimpleExoPlayerView.java to handle it.

what i was trying to do was:

```
SimpleExoPlayerView ViewVideo = new SimpleExoPlayerView(context);
ViewVideo.setLayoutParams(new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, 500));
ViewVideo.setSurfaceView(ViewVideo); // this is avaliable in XML
```

https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/SimpleExoPlayerView.java#L283
