### ISSUE TITLE
AdaptiveTrackSelection issue

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#3531]
### Issue description
AdaptiveTrackSelection doesn't change quality increase fast enough 

### Reproduction steps
I tried to changed the value of 
DEFAULT_MAX_INITIAL_BITRATE to 0 instead of 8000,
DEFAULT_MIN_DURATION_FOR_QUALITY_INCREASE_MS to 0 (so he can increase way faster),
DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS,
DEFAULT_MIN_DURATION_TO_RETAIN_AFTER_DISCARD_MS,
DEFAULT_BANDWIDTH_FRACTION,
DEFAULT_BUFFERED_FRACTION_TO_LIVE_EDGE_FOR_QUALITY_INCREASE to 0.25f instead of 0.75f

but it's not adapting fast enough and our ts segments are 10secs long.

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Nvidia Shield TV

### A full bug report captured from the device
I want my HLS or DASH playlist to adapt way faster then 15-20seconds everytime i'm inserting a new playlist.

**Comment by linhai326** [comment]
what's DEFAULT_BUFFERED_FRACTION_TO_LIVE_EDGE_FOR_QUALITY_INCREASE? 
if you mean DEFAULT_BANDWIDTH_FRACTION, which is 0.75f, and you change it to 0.25f, that will take only 25% of the bandwidth meter value. it won't increase the shifting time.

**Comment by linhai326** [comment]
also, DEFAULT_MAX_INITIAL_BITRATE set to 0 will start the streaming with the lowest feed. It won't help to shift up either (will not start with highest feed).

**Comment by botaydotcom** [comment]
@jboisjo Is your content live streaming content? If you can provide some links to the content, that would be very helpful.


DEFAULT_BUFFERED_FRACTION_TO_LIVE_EDGE_FOR_QUALITY_INCREASE only works for live streaming playbacks. It is the fraction of the duration from current playback position until the live edge that has to be buffered before the player can switch up.

If DEFAULT_MAX_INITIAL_BITRATE = 0, it means initially the player will always select the lowest quality possible when bandwidth estimation is not available. If your segments are 10s long, then probably you have to play through that until the up-switch.

I think one possible way to help boosting up the initial quality when you play new playlist / content is to reuse the previous (Default) BandwidthMeter instance that you were using. In such case only the very first time you play some content, the player will use DEFAULT_MAX_INITIAL_BITRATE. Subsequent playbacks will use the bandwidth estimation from previous playbacks.

**Comment by jboisjo** [comment]
Yes it is live streaming content. We don't want to keep the bitrate from the user bc it takes a certain delay before the first frame is showed and that's why we are resetting the bandwidth every time a new playlist has been inserted. Also, we created a func in AdaptiveTrackSelection to not wait until the segment is over to choose the right profile.

see the example below...

 ```
 @Override
    public void updateSelectedTrack(long playbackPositionUs, long bufferedDurationUs, long availableDurationUs) {
        int currentSelectedIndex = selectedIndex;
        selectedIndex = determineBestSelectedIndex();
        if (selectedIndex == currentSelectedIndex) {
            Log.e(TAG, "Determined that the best track is playing");
            return;
        }
        Format currentFormat = getFormat(currentSelectedIndex);
        Format selectedFormat = getFormat(selectedIndex);
        if (selectedFormat.bitrate > currentFormat.bitrate
                && bufferedDurationUs < minDurationForQualityIncreaseUs) {
            // The selected track is a higher quality, but we have insufficient buffer to safely switch
            // up. Defer switching up for now.
            selectedIndex = currentSelectedIndex;
        } else if (selectedFormat.bitrate < currentFormat.bitrate
                && bufferedDurationUs >= maxDurationForQualityDecreaseUs) {
            // The selected track is a lower quality, but we have sufficient buffer to defer switching
            // down for now.
            selectedIndex = currentSelectedIndex;
        }
        // If we adapted, update the trigger.
        if (selectedIndex != currentSelectedIndex) {
            reason = C.SELECTION_REASON_ADAPTIVE;
        }
    }

private int count = 0;
    private int max = 0;
    private int determineBestSelectedIndex() {
        if(count > max){
            return 0;
        }else{
            count ++;
            return length -1;
        }
    }
```

this makes the Adaptive more fast and doesn't wait a whole segment to changed the selectedIndex, but when the bandwidth isnt very good...this doesn't work.

**Comment by ojw28** [comment]
The parameter you need to reduce to enable faster switching is `minDurationForQualityIncreaseMs`. When I set that to a much smaller value than the default, I see much faster up-switching in the ExoPlayer demo app when playing the Apple HLS test streams (within ~2-3 seconds). If you want to reproduce this, note you'll need to either kill the demo app's process between each attempt, or modify it to create a new bandwidth meter each time, since the demo app will re-use a single instance by default.

How fast your own streams switch really depends on how the content is being produced. The player can only switch at a key-frame in the higher quality stream. So if you want to be able to switch mid-segment, you need to make sure your content has enough IDR frames in it to enable this. If your segments only have one IDR frame at the very start, that limits switching points to segment boundaries. Switching not at an IDR frame would require the player do either perform the switch non-seamlessly or make simultaneous use of multiple decoders, which is inefficient and error prone (and not supported by all hardware), so we will not be supporting this.

You should also consider using a shorter segment duration. I'm not sure anyone still recommends segment durations as long as 10 seconds. Apple used to, but I think now recommend 6 seconds. Anecdotally, 5 seconds seems fairly common.

**Comment by ojw28** [comment]
This [article](https://bitmovin.com/mpeg-dash-hls-segment-length/) recommending 2-4 second segment duration may also be of interest.

**Comment by jboisjo** [comment]
ok thank you, ill try to reduce our ts segment for HLS and samething for DASH. Ill let you know :)

Have a great day.
