### ISSUE TITLE
DefaultBandwidthMeter#getBitrateEstimate returns wrong values

### ISSUE THREAD

**Issue by alessandrojp** [google/ExoPlayer#3540]
### Issue description
Due to onTransferStart being called after the file is downloaded, the load process is being calculated on after the transfer is finished. In my case it finishes in less than 20ms, returning a huge bitrate making the player always uses the highest bitrate available.

Checking `OkHttpDataSource#open`
```
if (listener != null) {
  listener.onTransferStart(this, dataSpec);
}
```
onTransferStart is being called in the end of `open()`

```
try {
  response = callFactory.newCall(request).execute();
  responseByteStream = response.body().byteStream();
} catch (IOException e) {
  throw new HttpDataSourceException("Unable to connect to " + dataSpec.uri.toString(), e,
  dataSpec, HttpDataSourceException.TYPE_OPEN);
}
```
`callFactory.newCall(request).execute()` will block the thread until the download is done.
Also it happens on `DefaultHttpDataSource` .

### Reproduction steps
1- Download any file that would take more than 5 seconds.
2- Check the estimate bitrate on `onBandwidthSample`

### Link to test content
Sorry, I'm not allowed to publish a link

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Model: Google Pixel 
OS: 8.0.0

### A full bug report captured from the device
I'm using CharlesProxy to set the internet speed at 256kbps
It always downloads the highest bitrate in my case 320kbps.

```
Player: onBandwidthSample elapsedMs:219, bytesLoaded:16, bitrate:-1
Player: onBandwidthSample elapsedMs:155, bytesLoaded:457404, bitrate:23607948
Player: onBandwidthSample elapsedMs:130, bytesLoaded:454772, bitrate:27985968
Player: onBandwidthSample elapsedMs:202, bytesLoaded:453268, bitrate:17951208
```

By moving onTransferStart to be called before `callFactory.newCall(request).execute()`
It returns the correct bitrate and elapsed time for a 320kbps file at 256kbps.

```
Player: onBandwidthSample elapsedMs:517, bytesLoaded:16, bitrate:-1
Player: onBandwidthSample elapsedMs:15574, bytesLoaded:455904, bitrate:234187
Player: onBandwidthSample elapsedMs:15523, bytesLoaded:456288, bitrate:235154
Player: onBandwidthSample elapsedMs:15249, bytesLoaded:455152, bitrate:238783
Player: onBandwidthSample elapsedMs:15336, bytesLoaded:454784, bitrate:237237
```

**Comment by ojw28** [comment]
I don't think CharlesProxy throttles connections in a way that's realistic (i.e. how a genuinely slow network would behave).

**Comment by alessandrojp** [comment]
I also have ran a speed test on speedtest.net and I confirmed that the speed connection is running at 256kbps.
You can check the `callFactory.newCall(request).execute()` blocking the thread until the file is downloaded, which causes a wrong elapsed time.

**Comment by alessandrojp** [comment]
Also it is commented here
https://github.com/square/okhttp/blob/64e84e382efb80426cef301c9750833954c7fbbc/okhttp/src/main/java/okhttp3/Call.java#L29

**Comment by ojw28** [comment]
If `execute()` behaves as you describe, that would mean that in order to begin playback of a 2GB video, the network stack would have to fully download the entire stream (presumably stashing it all in RAM). I don't think it's likely the network stack behaves in that way, and this is not the behavior observed when using our demo app with the OkHttp extension. If the network stack did behave that way, it would be pretty unusable for streaming media. I think "until the response can be processed" means "until there's a response code", not "until the whole response has been downloaded".

I think what happens here is that CharlesProxy throttles in a way that delays sending the response code, and then serves the remainder of the media as quickly as possible. What I'm saying is that this is not realistic of how a normal 256kbps network would behave. What's important is that our bandwidth estimator behaves properly on real networks, not poor simulations of them. This is not to say there aren't improvements we can make. It's more to say that this particular use case is not what we should be targeting improvements at.

**Comment by alessandrojp** [comment]
I see.
Would you know a better way to test it not using CharlesProxy?

**Comment by ojw28** [comment]
Not that's publicly available. I'm sure there must exist decent tools for doing this though. I suggest you do some research. Good luck!

**Comment by alessandrojp** [comment]
Thanks!
