### ISSUE TITLE
Skip buttons disappear after a second on wear notification with extension-mediasession

### ISSUE THREAD

**Issue by joelphilippage** [google/ExoPlayer#3559]
### Issue description
When using the media connector with exoplayer on android wear, the skip notifications appear for a second whenever the notification is built and then disappear. I expect the skip buttons to appear at all times on the notification. This has never worked for me with exoplayer.
[Here is a video of the issue.](https://photos.app.goo.gl/QD8K2gsDy8OJ22YL2)

### Reproduction steps
-Install NavCasts
-Search or select a podcast
-Subscribe to podcast by clicking the (+) icon
-Navigate to the podcasts view by pulling down the navigation menu
-Select the podcast
-select an episode
-Press play
-Press the home button
-Pause or play the notification to display the skip buttons for a second.

### Link to test content
I will email the apk to the app in question along with the source code.

### Version of ExoPlayer being used
Version 2.6.0

### Device(s) and version(s) of Android being used
-Moto 360 Sport Android Wear 2.6.0.17
-Any version of the Android Wear Emulator with Android studio

### A full bug report captured from the device
Nothing with exoplayer is crashing but the notification is not displaying correctly

**Comment by marcbaechinger** [comment]
Thanks for reporting. I'll look into this.

**Comment by marcbaechinger** [comment]
I looked into this and this seems to work for me.

The media session extension does not include the code for creating a Notification. So this is part of your app. Does this only happen on the watch or does this also happen in the notification in the notification drawer?

With my test app this works fine with MediaStyleNotifications in the drawer as well as on my Wear watch.

**Comment by joelphilippage** [comment]
I am trying to use this in a standalone wear app so I don't know if I would get the same problem on an Android Phone. What sample app are you using? I remember referencing a sample when I built my media service, but don't remember which one. Could you provide a sample that is building a notification so I could try to reproduce it?

Thanks!

**Comment by marcbaechinger** [comment]
I looked into this some further.

It seems to me that the wear playback control UI is entirely built from the media session information while not considering the notification setup as I suggested above. Even when I remove the skip next/previous actions from the notification UI on the watch is still correct:

<img width="465" alt="wear-screenshot" src="https://user-images.githubusercontent.com/584321/33858211-bbd1f430-dec6-11e7-8c78-47f578a15448.png">

This works in all samples I'm having with MediaSessionConnector. In your app you need to make sure that:

- you use a MediaStyleNotifucation with the session token:

```
notifBuilder.setStyle(new android.support.v4.media.app.NotificationCompat.MediaStyle()
            .setShowActionsInCompactView(new int[]{playPauseButtonPosition})
            .setMediaSession(mSessionToken))
```

- you provide a QueueNavigator (via connector.setQueueNavigator) and maintain the queue of the media session properly. The recommended way to maintain the queue is to use the TimelineQueueNavigator which maps the timeline to the queue for you (DynamicConcatenatingMediaSource).

- your QueueNavigator does support and expose the actions PlaybackStateCompat.ACTION_SKIP_TO_QUEUE_ITEM,  PlaybackStateCompat.ACTION_SKIP_TO_NEXT and PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS. Again the TimelineQueueNavigator does this for you.

I'm closing for now. Thanks for reporting and please reopen if you think the connector does not maintain the session state properly hindering Wear to work.

**Comment by marcbaechinger** [comment]
Upppps. Sorry, I haven't seen your reply :)

The Notification I created ist mostly what you find in the NotificationManager of the UAMP sample app:

https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MediaNotificationManager.java

The manager maps the media session information to the notification and retrieves actions and call the transportControls of the MediaController.

**Comment by joelphilippage** [comment]
Okay. I figured out the problem. I was setting the event listener for exoplayer before  initializing the mediasession connector with the player. I guess that removed the listeners so my PlaybackStateCompat was not being updated on state change.

Is this still a bug or am I not using it as intended?

**Comment by ojw28** [comment]
`ExoPlayer` can handle multiple listeners, so that's not a problem.

I think the problem might be that your `MediaPlayerService` class appears to be replicating a lot of the glue functionality that `MediaSessionConnector` provides for you, in a way that looks like it might cause conflicts to arise. For example your code is setting a `NavSessionCallback` directly on `mediaSession`. `MediaSessionConnector` sets its own callback on the `mediaSession` that implements quite similar logic. It looks like only one callback can be registered on a `MediaSession`, so I think the last caller will win. Both your code and `MediaSessionConnector` also set the playback state directly on `mediaSession`. It's unclear to me whether they should both be doing this? Perhaps @marcbaechinger, who knows this code better, can comment.

I'd suggest you take a look at the `MediaSessionConnector` [source code](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java) to see what it's doing. I think the right thing to do is probably to leave it to that class to implement the glue functionality, or if it doesn't do what you want, implement your own and don't use it (optionally filing feature requests so we might support your use case better in the future). It looks a bit like your current approach is somewhere in-between, and it's possible that's causing problems.

**Comment by marcbaechinger** [comment]
Sorry for my late reply. 

As Olly mentioned mediaSession.setCallback() allows only one callback to set. The MediaSessionConnector sets this callback when the player is set. So other callbacks will be overriden. The same applies when someone set a callback after the player has been set to the connector: the connector;s callback will be removed. 

Are you setting your own MediaSessionCompat.Callback? If so you shuld only rely on the MediaSessionConnector which does delegate all media actions to you via the various interfaces it provides. 

Please let me know whether this is the case.

**Comment by joelphilippage** [comment]
Yes. The way I am writing my code is to

- Make a MediaSession
- Make a MediaSessionConnector
- Set the player to the MediaSessionConnector
- Set a custom callback to the media session

I believed using a MediaSessionConnector was the only way to get a MediaSession from an ExoPlayer instance. Is there another way to get the MediaSession without using MediaSessionConnector?

Thanks!

**Comment by marcbaechinger** [comment]
You need to create the MediaSessionCompat yourself in either case. You create it an then pass it to the connector:

```
mediaSession = new MediaSessionCompat(this, "exoplayer.mediasession.demo");
mediaSessionConnector = new MediaSessionConnector(mediaSession);
```

So you should not do the last step or you disconnect the connector from the media session. You can instead do:

1. Create a MediaSessionCompat
2. Create a MediaSessionConnector
3. Set the player to the MediaSessionConnector

At this point the MediaSessionConnector has set the callback to the media session which should not be overriden by your own. The connector receives all media actions and delegates them to collaborators which you can register instead of using your custom MediaSessionCompat.Callback. With this you can achieve the same as you can receive all actions yourself while still having the connector doing the heavy lifting for you.

Taken from the [medium blog post](https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d):

**MediaSessionConnector.PlaybackPreparer**
ACTION_PREPARE, ACTION_PREPARE_FROM_MEDIA_ID, ACTION_PREPARE_FROM_SEARCH, ACTION_PREPARE_FROM_URI, ACTION_PLAY_FROM_MEDIA_ID, ACTION_PLAY_FROM_SEARCH, ACTION_PLAY_FROM_URI

**MediaSessionConnector.PlaybackController**
ACTION_PLAY_PAUSE, ACTION_PLAY, ACTION_PAUSE, ACTION_SEEK_TO, ACTION_FAST_FORWARD, ACTION_REWIND, ACTION_STOP

**MediaSessionConnector.QueueNavigator**
ACTION_SKIP_TO_QUEUE_ITEM, ACTION_SKIP_TO_NEXT, ACTION_SKIP_TO_PREVIOUS, ACTION_SET_SHUFFLE_MODE_ENABLED

**MediaSessionConnector.QueueEditor**
ACTION_SET_RATING and all commands defined through MediaSessionCompat.Callback when the flag MediaSessionCompat.FLAG_HANDLES_QUEUE_COMMAND is set.

**MediaSessionConnector.CustomActionProvider**
Handles custom media actions specified by the app.

**Comment by joelphilippage** [comment]
Okay. Let me explain why I want to use my one playback. Since this is a podcast app, I would like the notification to have seek to buttons that skip 30 seconds forward or backwards. I haven't been able to find a way on Android Wear to replace the skip action buttons on the notification with custom buttons. I have a custom callback that replaces the skip actions with a fast forward action.

I guess I still don't understand. Is there a way to change the actions without replacing the callback or is there a way I can get a media session from ExoPlayer without using the connector?

**Comment by marcbaechinger** [comment]
I actually recommend figuring out how to change the buttons on Wear to replace the skip with a fastforward button. Users might be confused when you change the behaviour of well known buttons/icons.

However, instead of using a custom callback you create and register a `QueueNavigator`. When `ACTION_SKIP_TO_NEXT` or `ACTION_SKIP_TO_PREVIOUS` is sent to the session the methods `onSkipToPrevious(player)` or `onSkipToNext(player)` are called. So if you really want to do that you can then place your custom code there:

```
public PodcastQueueNavigator implements QueueNavigator {
   public void onSkipToNext(Player player) {
      // do whatever you want, like
      player.seekTo(player.getCurrentPosition() + (30 * 1000));
   }
  // ... more methods to implement
}
```
You can register your queue navigator like so:

`mediaSessionConnector.setQueueNavigator(new PodcastQueueNavigator());`

As mentioned it's much more preferable to make Wear show the correct buttons.

**Comment by joelphilippage** [comment]
Great! It seems like wear notifications don't work the same as they do on mobile. The same code that works on mobile doesn't work on wear for setting custom buttons. I'm only able to set the primary center button to something custom. Other apps such as PocketCasts do not display any side buttons but I would prefer to display the skip buttons rather than having a blank space. I will try to ask the community if there is a method for doing this but will implement your method in the meantime.
Thanks!
  
Edit: for future reference this seems to be the correct way to set actions on wear: https://developer.android.com/reference/android/support/wearable/media/MediaControlConstants.html
Edit 2: actually I tried this and it only shows the actions in the media content view and not on the main notification so it doesn't really accomplish what I'm looking for
