### ISSUE TITLE
Error when video track is missing

### ISSUE THREAD

**Issue by pedromfmachado** [google/ExoPlayer#3560]
### Issue description
In my product I have two possibilities: sometimes there's HLS and when it is not available I have several MP4 tracks. I'm using `MergingMediaSource` in order to pass all of the available tracks + subtitles. I have two questions:

- When one of the tracks is missing (response code 404) the player fails, even though all the other tracks are available (it might be somehow related to #3140). Is there a way to ignore a missing track without a complete failure of the playback?
- If both HLS and MP4 tracks are available is it ok to create a `MergingMediaSource` with all of them or is there a better way of taking care of this?

### Version of ExoPlayer being used
2.6.0

**Comment by botaydotcom** [comment]
Hi @pedromfmachado ,
I think your case is a bit different than the one in #3140 . If a video track is selected for playback & it's missing, I think it's a real playback error - the player should not continue to play in such case, because there's no video output.
So in this case, I think a better solution for you would be to check the track URL beforehand to see if it's valid or not before sending it to the player. `MergingMediaSource` is not designed to handle automatically fall-back in the case when the track to be played is missing.
Another option you can do is to listen to such error (if the player reports), and do fall-back yourself by retrying with other tracks.

**Comment by ojw28** [comment]
`MergingMediaSource` is intended for legitimate merging of available content (e.g. a side-loaded subtitle or demuxed alternate audio track).

For fallback cases such as yours, you should do as described above: Either find a way of working out which URL is valid beforehand, or try to play one URL and if playback fails try the other as a separate playback attempt.
