### ISSUE TITLE
Use programatically created VMAP file for IMA Ad request

### ISSUE THREAD

**Issue by jazimm** [google/ExoPlayer#3562]
Is there currently a method of using a VMAP file produced on the client for Ad requests rather than entering a URI to a VMAP or VAST file on a remote location? In the former method you could use AdsRequest.setAdsResponse (VMAP String) to do so but with the ImaAdsLoader on v 2.5 it seems it will only accept a Uri. I could try programatically generating a file locally for each call with a Uri pointing to it  as the file changes for each video but I was hoping a String was possible and I'm guessing a local file would not be a valid Uri in this case? Thanks

**Comment by andrewlewis** [comment]
I think this is the same as #3548: the requested enhancement is to be able to call [AdsRequest.setAdsResponse](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdsRequest.html#setAdsResponse(java.lang.String)) instead of loading an ad tag by URI. Please reopen if not. Thanks!
