### ISSUE TITLE
Explanation of stopInternal() call on IO-Exception

### ISSUE THREAD

**Issue by christianruppert** [google/ExoPlayer#3578]
Hello,
I am trying to improve the playback (buffer behavior) when streaming an AAC audio file (webradio).

I am using a CustomLoadControl, which works as expected (triggers loading below 20 seconds until buffer reaches 30 seconds). Now there is a case where the player behaves in an unexpected way (but the source code tells me it is intended behavior) - maybe somebody can clarify the motivation and give me a hint on how to solve this.

As long as the LoadControl tells the player that it **does NOT need to continue loading**, the playback **keeps running (depleting the buffer, which is fine)** even if I enter airplane mode (which is what I would expect).

Now the buffer falls under the lower threshold (20 seconds) and the LoadControl tells the player to start loading - which will cause an IO Exception within the DataSource. So far, so good.

Now this **IO Exception triggers a call to stopInternal()** - you can see it in the source of ExoPlayerImplInternal around line 350

This will **cause the player to stop immediately (audio playback)** instead of continue to play the buffered 20 seconds still available.

What is the motivation for this, and which approach would be most in line with the overall architecture?

My ideas are:

- Catch IO within my datasource and retry (but this seems to circumvent already existing retry options)
- Check in loadControl if network is connected (feels wrong, the data source should try by itself)
- Hacking around in the ExoPlayerImplInternal (feels even more wrong)
- Any magic you come up with :-)

Thanks for your feedback,
Chris

**Comment by ojw28** [comment]
The player stopping immediately in this case is a bug, which is tracked by https://github.com/google/ExoPlayer/issues/1606.

Note that completely seamless recovery in this case wont be possible (you should use DASH or HLS streams if this is a requirement, since they're designed to properly enable recovery). We should continue playback until the buffer is depleted, however, and then at that point try and splice back into the stream as seamlessly as possible if we've managed to successfully open it again.

Closing / Marking as duplicate.
