### ISSUE TITLE
[Question]How to avoid judder?

### ISSUE THREAD

**Issue by xdestiny110** [google/ExoPlayer#3579]
When I play a [test video](https://pan.baidu.com/s/1slFlDb3) by exoplayer demo, it judder slightly(very slightly so you would not notice if you don't stare it) every few seconds especially in landscape mode.
Any one can give me a suggesstion?

**Comment by erdemguven** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
