### ISSUE TITLE
Stuck video on viewPager

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3587]
Hi . I'm using `exoPlayer 2.6.0` in my application . in my recycleView it worked without any problem . but with the same code in viewPager and fullscreen size it's stuck  . 

`      BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
       
      TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        
      TrackSelector trackSelector =
                new DefaultTrackSelector( videoTrackSelectionFactory );
        
      SimpleExoPlayer player =
                ExoPlayerFactory.newSimpleInstance( getContext() , trackSelector );
        
      player.addListener(this);
        
       this.video.setPlayer(player);
       DefaultBandwidthMeter bandwidthMeter1 = new DefaultBandwidthMeter();
        
       DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, context.getString(R.string.app_name)), bandwidthMeter1);
        
       ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        
       MediaSource videoSource = new ExtractorMediaSource( Uri.parse(path) ,
                dataSourceFactory, extractorsFactory, null, null);
        video.getPlayer().prepare(videoSource);

        player.setPlayWhenReady(true);`

Pay attention : in my uri is external storage path , this is not url . 

any one can help me ?

**Comment by erdemguven** [comment]
Please provide more information (especially a bugreport).

This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
