### ISSUE TITLE
Is there any way to implement different layout at runtime

### ISSUE THREAD

**Issue by varun7952** [google/ExoPlayer#3588]
As exoplayer comes with customized UI and it can work well but is anyway that we can change different layout for Exoplayer for different media. 

For example: Different layout when playing video and different when audio is playing.

**Comment by nimdokai** [comment]
You can check what type of media (for example in: `onTracksChanged`) is playing and based on that define change the layout that should be used by `setContentView`.
Also take a look at: 
https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a

**Comment by varun7952** [comment]
setContentview is android activity method to inflate layout inside onCreate. You can't play much with setContentView method cuz its only use to inflate default layout of activity. We need to make it something like runtime method which we can change on click of button.

**Comment by ojw28** [comment]
You can build whatever UI you want to use with `ExoPlayer`, since at a low level all you need to provide is the `Surface`/`SurfaceView`/`TextureView` to `SimpleExoPlayer`. If you opt to build a custom UI, you can obviously adjust it however you want, whenever you want.

We also provide some out-of-the-box UI components, for example `SimpleExoPlayerView`. They can be reconfigured at runtime to the extent that their public APIs allow. These APIs are relatively well documented [here](http://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/ui/package-summary.html). If you need further customization beyond what's available, you should implement your own custom UI as explained above.

**Comment by varun7952** [comment]
Can i do it on Runtime?
