### ISSUE TITLE
help to implement token in video links

### ISSUE THREAD

**Issue by xoceunder** [google/ExoPlayer#3590]
help to implement token in the video links for the token to change to an x time in order to protect my links
thanks in advance

@willnorris @canatella @kiall @talklittle @edwinwong

**Comment by sandersaares** [comment]
You may be interested in reviewing the document "DASH-IF IMPLEMENTATION GUIDELINES: TOKEN-BASED ACCESS CONTROL FOR DASH (TAC) V1.0" at http://dashif.org/guidelines/

I am not saying this mechanism is necessarily implemented by ExoPlayer (I do not know what ExoPlayer implements) but perhaps it gives you some background information.

**Comment by xoceunder** [comment]
is that my project is already working with this function
@sandersaares

**Comment by ojw28** [comment]
This is too vague for us to do anything with. If you still need help, please reply here describing in far more detail what you're trying to do. Thanks.

**Comment by xoceunder** [comment]
I want to be able to make my url get a token to protect and can change automatically when the token time expires

Example:
http://dashboard.jwplatform.com/videos/nPripu9l.mp4?6

and when it expires change this automatic

exp=1271760610&key=b59b91370f4faf4815b6736db10e5041

from the video url

**Comment by ojw28** [comment]
There is still not enough information here for us to help. Please bear in mind we don't know the details of the expiration mechanism that you're using. Specifically things like:
1. How the server indicates to the client that the link has expired. Presumably a 403?
1. How can the client generate a new (valid) link. Presumably your code needs to do this, since if it's possible for us to re-generate a valid URL internally then the URL expiration isn't really achieving anything.
1. How this mechanism works with other standard players, for example Android's MediaPlayer API.

**Comment by xoceunder** [comment]
is that I want that at the expiration of the fecHA CHANGE CODE NEW SO I KEEP WITHOUT LOSING THE VIDEO OR THAT IT IS GOING TO PENGATE AGAIN
