### ISSUE TITLE
1080p not playing with AC3 audio

### ISSUE THREAD

**Issue by tsmathavan** [google/ExoPlayer#3603]
1080p not playing with AC3 audio

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
