### ISSUE TITLE
OMX.ffmpeg.ac3.decoder ExoPlayer

### ISSUE THREAD

**Issue by xoceunder** [google/ExoPlayer#3605]
help please with the .mkv file problem

OMX.ffmpeg.ac3.decoder ExoPlayer

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
