### ISSUE TITLE
Is it possible to pre load preroll ads using ImaAdsLoader in a video list?

### ISSUE THREAD

**Issue by alonaviram** [google/ExoPlayer#3636]
I see that in `ImaAdsLoader` there is a pre loading implementation, but it gets called only on `onAdsManagerLoaded` that gets called only after requesting ad (i think).
I want to pre request ads and when the user scroll to a video item show the preroll only if it's already loaded (and not wait for ad to download).
thanks!

**Comment by andrewlewis** [comment]
Call [`ImaAdsLoader.requestAds`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.6.1/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L330) to request the ad tag before preparing the player

In case you want to play just the content if the ad tag hasn't loaded by the time you need to prepare the player: you could call `ImaAdsLoader.getAdsLoader`, attach your own `AdsLoadedListener` and then handle `onAdsManagerLoaded`. At the time of preparing the player, if that method has been called you know to proceed with playback with ads. Otherwise you can prepare the player with a content media source and release the ads loader.
