### ISSUE TITLE
Is there a trick to speeding up buffering?

### ISSUE THREAD

**Issue by Aditya94A** [google/ExoPlayer#3651]
### The issue

When the playback begins or when you seek to a position, there's a very noticeable lag of a few hundreds of milliseconds. After jumping through several stack overflow questions and github issues and blog posts and what not, apparently this is because ExoPlayer (or rather any video player) needs to build the seeked frame from the previous key frame.

My question is, how do popular video players such as [MX player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) have near instant playback on startup and on random seeks? What are they doing better than ExoPlayer? Is there a way to make ExoPlayer buffer faster?

This isn't a specific issue with some particular version or input file or codec or device, but exoplayer's performance on the whole seems a bit slower than the competition.

### How to reproduce

Open a video in any popular android video players, e.g: MX Player, VLC etc. Now open the same file in a boilerplate surface (or `SimpleExoPlayerView`) backed by exoplayer. The buffering, controls, seek etc. nearly all operations are significantly slower than the "competition".

**Comment by ojw28** [comment]
> My question is, how do popular video players such as MX player have near instant playback on startup and on random seeks? What are they doing better than ExoPlayer?

They are probably seeking to the nearest keyframe, rather than the nearest frame (i.e. less accurate, but faster).

> Is there a way to make ExoPlayer buffer faster?

Work is actively underway to support keyframe accurate seeking in ExoPlayer, and is already functional in the `dev-v2` branch when playing regular progressive media files. This work is being tracked in https://github.com/google/ExoPlayer/issues/2882, so closing this as a duplicate.
