### ISSUE TITLE
DynamicConcatenatingMediaSource with non reusable URLs 

### ISSUE THREAD

**Issue by OfekRegev** [google/ExoPlayer#3661]
I'm using DynamicConcatenatingMediaSource. I'm loading a playlist from SQL and adding all the URLs (expired or not) to the player.
The problem is : 
My URL which contains the file expire 4 hours after  the request. I need a way to check before the player loads each MediaSource if the MediaSource's URL is expired or not and if so the player should stop the media source loading and request a new URL for the file from the server   

Important: 
The solution of checking if the URL expired when I am getting them from the database and request for a new URL if the current is expired isn't good because the request takes in average 1.3 seconds (the request time isn't depends on me). So let's say I have 50 songs to request for a new link it will take more than a minute to get all the new URLs and in the meanwhile the playlist is blocked/semi blocked.

**Comment by tonihei** [comment]
Based on the information you provided, I think you can solve your problem by using a custom `DataSource`  implementation which wraps the actual data source and takes care of the URL update.

Some background: `DynamicConcatenatingMediaSource` calls `mediaSource.prepareSource` for each  playlist item immediately after adding the item. So, as you pointed out, this is not a good place to make this check as the media might not be played soon and all checks would happen at once. It also calls `mediaSource.createPeriod` just before it starts loading each playlist item. However, this method is called on the main playback thread and shouldn't block. Internally all media periods (the instances created to load the media) use a `DataSource` to open the connection to an URL and to load the data. The methods of this interface can block as long as needed are thus a good place to do additional stuff just before the media is being loaded.

So to do your check you would need to do something like:
```
public final class UrlUpdatingDataSource implements DataSource {
  
  public static final class Factory implements DataSource.Factory {

    private final DataSource.Factory realFactory;

    public Factory(DataSource.Factory realFactory) {
      this.realFactory = realFactory;
    } 

    DataSource createDataSource() {
      return new UrlUpdatingDataSource(realFactory.createDataSource());
    }
  }

  private final DataSource realDataSource;
  private DataSpec updatedDataSpec;

  private UrlUpdatingDataSource(DataSource realDataSource) {
    this.realDataSource = realDataSource;
  }

  @Override
  public long open(DataSpec dataSpec) throw IOException {
    updatedDataSpec = dataSpec 
    if (urlExpired(dataSpec.uri)) {
      updatedDataSpec = makeCoyOfDataSpecWithNewUri(dataSpec);
    }
    realDataSource.open(updatedDataSpec);
  }

  @Override
  public int read(byte[] buffer, int offset, int readLength) throws IOException {
    return realDataSource.read(buffer, offset, readLength);
  }

  @Override
  public Uri getUri() {
    return updatedDataSpec == null ? null : updatedDataSpec.uri;
  }

  @Override
  public void close() throws IOException {
    realDataSource.close();
    updateDataSpec = null;
  }
}
```

You can use this custom `DataSource.Factory` when you set-up your playlist item `MediaSource`s.

As a result, you shouldn't even notice a difference to buffering because the player starts loading the next playlist item way before the previous one finished. So even if the update takes more than 1 second, the playback should continue smoothly.

**Comment by OfekAshkenazi** [comment]
Thanks a lot!
That's exactly what I was loo

**Comment by OfekRegev** [comment]
Thanks a lot!
That's exactly what I was looking for.

**Comment by tonihei** [comment]
Closing for now as your question seems to be answered. Feel free to reopen if necessary.

**Comment by tonihei** [comment]
We now added a `ResolvingDataSource` to the library to achieve the task above in an easier way. See https://github.com/google/ExoPlayer/commit/9aeaf2dbb098e58c9350b6f9014d53ce98b6d6b1 for details.
