### ISSUE TITLE
Run this type of link

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3665]
Hello, how are you!
Friend how do I make my exoplayer accept wheel the link below?

**Comment by tonihei** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
