### ISSUE TITLE
My url is video ,but I play it using exoplayer ,it just audio

### ISSUE THREAD

**Issue by TigerYao** [google/ExoPlayer#3671]
HI, 
All Android device
Exoplayer 2.6.1
Url:http://cdn7.ushareit.cn/sz2/h_v/mOegu_240p.m3u8
My url is video ,but I play it using exoplayer ,it just audio,I do not why;

**Comment by giladna** [comment]
@TigerYao 
@AquilesCanta 

This is the current m3u8

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=338000,RESOLUTION=320x180,CODECS="mp4a.40.2"
mOegu_240p/.m3u8

If your file will be created as below  without the CODECS="mp4a.40.2" it will work I guess this signs that stream is audio only that is why only audio plays

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=338000,RESOLUTION=320x180
http://cdn7.ushareit.cn/sz2/h_v/mOegu_240p/.m3u8

**Comment by AquilesCanta** [comment]
@giladna's comment is correct. The [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23) states:

 ```
   If an EXT-X-STREAM-INF tag or EXT-X-I-FRAME-STREAM-INF tag contains
   the CODECS attribute, the attribute value MUST include every media
   format [RFC6381] present in any Media Segment in any of the
   Renditions specified by the Variant Stream.
```

ExoPlayer ignores the video stream because the master playlist only includes the audio codecs. The fix here is to add the video codec in the CODECS attribute. 

Alternatively, you could work around this issue by either removing the CODECS attribute (not recommended) or creating your own HlsExtractorFactory which does not apply DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM.
