### ISSUE TITLE
How to set End/Total Duration manually in ExoPlayer PlaybackControlView

### ISSUE THREAD

**Issue by Gobi1989** [google/ExoPlayer#3678]
Hi All,

  **Issue description**
 Want to set End/Total Duration manually in ExoPlayer PlaybackControlView.

 **Reproduction steps**
- In our application the total duration displaying in PlaybackControlView is wrong for some videos. 
- With some contents, in the video player it shows a wrong end time (49:47) while the proper end time is 49:59 (50 mins in the content description). 
- It plays until the proper end time anyways, but it's confusing for the user. 
- So from our back end they are sending the total duration so that we can set it manually for the videos.

**Version of ExoPlayer being used**
com.google.android.exoplayer:exoplayer:r2.5.4
com.google.android.exoplayer:exoplayer-core:r2.5.4
com.google.android.exoplayer:exoplayer-dash:r2.5.4
com.google.android.exoplayer:exoplayer-ui:r2.5.4
compile 'com.google.ads.interactivemedia.v3:interactivemedia:3.7.4'

**Device(s) and version(s) of Android being used**
Samsung GALAXY Note4, Android 6.0.1

Please let me know the implementation of above feature.

**Comment by ojw28** [comment]
Do you understand why the duration ends up being incorrect? Is the source media broken, or is ExoPlayer's parsing of the source media broken? The best solution would be to fix whichever of those is broken, rather than papering over the problem at the UI layer.

If you're not sure, could you provide a piece of sample media so we can take a look? Thanks!

**Comment by Gobi1989** [comment]
Hi @ojw28 ,

As i'm not aware about why the duration ends up being incorrect. I have send the media details via email with subject as **REG | ISSUE NO #3678| How to set End/Total Duration manually in ExoPlayer PlaybackControlView**.

Thank you.

**Comment by ojw28** [comment]
This is the same issue as https://github.com/google/ExoPlayer/issues/3317. The best thing to do is to get the media fixed so that each AdaptationSet has the same duration, which should equal the duration of the media. The text AdaptationSet in the stream provided has a significantly shorter duration currently, which can be easily avoided when generating content.

We don't support manually overriding the duration, although it would definitely be possible to do so if you dug deep enough into the source code. Depending on what layer you want to override it at, forking the UI components and modifying them to allow side-loading the duration may be sufficient.
