### ISSUE TITLE
Distinguish between live and DVR

### ISSUE THREAD

**Issue by kelmer44** [google/ExoPlayer#3679]
I want to implement a player that can support live with DVR functionality.

I tried with ExoPlayer and I saw that this seems to be supported, which is awesome: I can play the live stream and I can also seek to an earlier time.

However theres two things im uncertain about:

When playing live the thumb on the seekbar is usually always at the end of the seekbar. Check how youtube does for instance:

https://www.youtube.com/watch?v=2uA0rXgC4H4

However with exoplayer the thumb is always "almost at the end". Is it possible to fix this?

Also, is there a way to find out whether the player is "live" or on DVR? I want to put a "back to live" button that changes to "live" when the stream is live, the way youtube does. Is this possible?

**Comment by ojw28** [comment]
Assuming you're dealing with DASH, HLS or SmoothStreaming, you should be able to use [isCurrentWindowDynamic](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#isCurrentWindowDynamic--) to determine whether the stream is live or DVR. True == Live, False == DVR/VOD.

Regarding the thumb, we're accurately representing how the media is being made available from the server. It is of course possible to make an alternative UI that doesn't do this, but presents something more consistent with what a user might "expect". It's not something we support directly at this time, however you are free to build your own UI components rather than relying on those provided by the library (you are also free to fork the source code of those provided by the library and customize them to better match what you want).
