### ISSUE TITLE
[Question] about reuse same SimpleExoPlayer instance for different MediaSource

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3705]
~~ignored all issue creation suggestion, this is a question ^^!~~.

Hope the title tells the background. The detail is:

- In order to create a SimpleExoPlayer instance, I must provide a TrackSelector (in this case, a DefaultTrackSelector which in turn built on a **DefaultBandwidthMeter** (calling this is **Meter1**, here it is a "BandwidthMeter") to support adaptive track selection).

- In order to build new MediaSource from Uri (taken from intent, or online stream), I need a DataSourceFactory (in this case, a DefaultDataSourceFactory and this also built on a **DefaultBandwidthMeter** - **Meter2**, also here it is a "TransferListener")

The questions are:

- Should **Meter1** and **Meter2** be the same instance? As I suppose that it should use the information provided by TransferListener's functionality in DataSourceFactory for the Track selection judgement in DefaultTrackSelector?

- When I want to reuse that SimpleExoPlayer instance for different MediaSource, should I reuse the DataSourceFactory above to create other MediaSource? I'm afraid that reusing it (and in turn, the DefaultBandwidthMeter) will cause the confusing between Track selection because DefaultBandwidthMeter is not-stateless, and an update on the load of an MediaSource using it may effect the **track selection** of another MediaSource also using it.

Thanks in advance. Also, an example showing how to re-use the ExoPlayer instance across MediaSource as well as configuration (DrmSessionManager, extension mode, etc) is highly expected.

**Comment by ojw28** [comment]
> Should Meter1 and Meter2 be the same instance? As I suppose that it should use the information provided by TransferListener's functionality in DataSourceFactory for the Track selection judgement in DefaultTrackSelector?

Yes, correct. It's not ideal that you need to pass the bandwidth meter around in this way, in particular because it's quite easy to make the mistake of not passing the same instance. This is something that I think we're planning on addressing at some point.

> When I want to reuse that SimpleExoPlayer instance for different MediaSource, should I reuse the DataSourceFactory above to create other MediaSource? I'm afraid that reusing it (and in turn, the DefaultBandwidthMeter) will cause the confusing between Track selection because DefaultBandwidthMeter is not-stateless, and an update on the load of an MediaSource using it may effect the track selection of another MediaSource also using it.

It's fine to re-use the `DataSourceFactory` (and `DefaultBandwidthMeter`) when playing through a sequence of videos. Note that this means the bandwidth estimate from the end of one playback is carried forward to the start of the next playback. We see this as desirable, compared to the alternative in which each playback starts with no bandwidth information. Note that the main demo app uses a single `DefaultBandwidthMeter` instance, which is why playbacks after the first one tend to start immediately in high quality (assuming you have a good WiFi connection), where-as the first one will tend to start in a lower quality and adapt up.

As an aside, the one case where confusion would arise is if you were to have two players using the same bandwidth meter whilst playing simultaneously.
