### ISSUE TITLE
Decoder fails to instantiate on Asus zenfone 2

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#3707]
### Issue description
When trying to playback video recorded by device camera, the error occurs.

### Reproduction steps
Just use a video recorded on device. It is probably due to the decoder used.

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Asus_z00ad, android 5.0

### A full bug report captured from the device
[zenphone2.txt](https://github.com/google/ExoPlayer/files/1632047/zenphone2.txt)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it **omits information requested in the issue template** that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by b0g8** [comment]
@AquilesCanta, could you explain what is missing?

**Comment by AquilesCanta** [comment]
A full bugreport and a piece of content to reproduce the issue with.
