### ISSUE TITLE
SimpleExoPlayerView being black when reopen activity and music is playing

### ISSUE THREAD

**Issue by sn32247** [google/ExoPlayer#3739]
The com.google.android.exoplayer2.ui.SimpleExoPlayerView widget going black and don't show nothing if close and re open activity while music is playing and the user should touch the black box to visible it. but when new music selected and player.prepare() call, every thing is ok. the problem is when music is playing and the widget most show the current state of music after activity re launch. how can I fix this?
The lib version is 2.6.1

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
