### ISSUE TITLE
getRendererException

### ISSUE THREAD

**Issue by OfekRegev** [google/ExoPlayer#3748]
just got this crash from my crashlytics

com.google.android.exoplayer2.util.Assertions.checkState (Assertions.java:79)
com.google.android.exoplayer2.ExoPlaybackException.getRendererException (ExoPlaybackException.java:120)
com.music.ofek.iplay.Services.ExoPlayerService.onPlayerError (ExoPlayerService.java:395)
com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:517)
com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:100)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6123)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

anyone can help to put some light on what it means?

**Comment by botaydotcom** [comment]
Hi @OfekAshkenazi : Your stack trace only shows a general playback error in a renderer.

We can't provide any help with this limited information. Please try to reproduce this error in our Demo app, and provide required information based on our issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by botaydotcom** [comment]
@OfekAshkenazi 
After checking this again, your exception is because you are trying to call: `ExoPlaybackException.getRendererException()` from your `com.music.ofek.iplay.Services.ExoPlayerService.onPlayerError()` when the type of the playback exception is not `TYPE_RENDERER`.

To fix this: Please check if the exception type is `TYPE_RENDERER` before calling `getRendererException()`. You can refer to our `PlayerActivity.onPlayerError()` for an example.

**Comment by OfekRegev** [comment]
Silly me, it was right under my nose xD. thanks anyway!
