### ISSUE TITLE
Can't create a custom skipp-ad button

### ISSUE THREAD

**Issue by brinkkemper** [google/ExoPlayer#3759]
### Issue description / feature request description
The data of a loaded add is not exposed outside of the extention. There is no `AdLoaded(Ad)` event for instance. Or a `public Ad getLoadedAd() ` to retrieve the Ad data when playback has started. Because of this, a react-native-app can't display a button to skipp an ad.

### Version of ExoPlayer being used
Im using 2.5.4, but the same issue goes for 2.6.1 (current latest)

I've created [this question on stackoverflow](https://stackoverflow.com/questions/48464895/how-to-add-a-skip-ad-button-to-exoplayer-with-ima-extention-using-react-native-v). Perhaps I'm missing something?

**Comment by ojw28** [comment]
The underlying IMA library that our extension wraps already displays a skip button during playback, as demonstrated in our demo app. I believe it's intended that this UI is standard, rather than being customized on a per app basis. Are you deliberately not attaching the existing UI, or is it not being displayed?

**Comment by ojw28** [comment]
Closed due to lack of information.
