### ISSUE TITLE
Unable to play AES-256 encrypted MP4 audio files

### ISSUE THREAD

**Issue by vikas3121** [google/ExoPlayer#3766]
Hi All,
I am unable to play AES 256 encrypted mp4 files, with AES 128 it works fine, however it is giving "UnRecognizedInputFormatException". Please suggest, I am using "PBKDF2WithHmacSHA1" and CBC/PKCS5Padding.

**Comment by ojw28** [comment]
How are you playing AES 128 streams? I don't think we (intentionally) provide direct support for that. Are you using a custom `DataSource` component from somewhere outside of the core library? If not, could you provide an example AES 128 stream that plays successfully?

**Comment by vikas3121** [comment]
I am using custom implementation of the Datasource, to play encrypted files on the fly using exo player. However I got stuck with AES 256, all the time exo player is not able to recognize the input. It took me some time to ply encrypted files by building custom datasource to play AES 128. Please suggest if AES 128 is safe enough to go with??

**Comment by ojw28** [comment]
If ExoPlayer isn't recognizing the input then your custom `DataSource` isn't decrypting AES 256 media correctly. This isn't library code of an officially supported use case, so unfortunately you'll need to debug the problem yourself (e.g. try writing some comprehensive unit tests for your `DataSource` to validate it's really doing decryption correctly, even when requests are made to non-zero start positions).

It's up to you to decide what's "safe" enough for your use case. It really depends how high value your content is, how it's served (streaming vs from-disk), what attacks you're attempting to protect against and so on.

Closing, since this is an issue with a custom component, not with the ExoPlayer library.

**Comment by merby04** [comment]
Can you explain me @vikas3121 how to implement it  ? I need it to play encrypted audio files... any refference ?
