### ISSUE TITLE
Widevine L3 licence duration limitation

### ISSUE THREAD

**Issue by lkcanal** [google/ExoPlayer#3770]
Hi there,

There may be a limitation when dealing with Widevine licences using level 3 security mode.
Licences with a duration that are greater than 68 years throw a decryption error in the CDM trace log.
`E/WVCdm: Decrypt error result in session sid74 during encrypted block: 5`

Using the same kind of Widevine licence using level 1 security mode works just fine.

After thinking a bit, it seems a lot like Widevine level 3 Cdm handle the licence duration using an integer. Example: 69 * 365 * 86400 is greater than the max value of an integer.

So this is really bad, because a major part of the Android devices ecosystem only have Widevine level 3 Cdm.
Sometimes, rights holders asks entertainment companies to deliver licences for more than 68 years, for a TVOD EST purchase for example.

I know it's not an Exoplayer issue but a Widevine one. I wanted to share this with the community.

Thx.

**Comment by fredgc** [comment]
This has been fixed in Android O.   To avoid future problems, we will make changes to the server to restrict duration to 50 years.

We will also update the documentation to make it clear that a key duration of 0 means unlimited.  In practice, a duration of more than a few weeks is probably an error.   Key duration is intended to restrict playback times, so a very large value is probably not what the content owner/provider really wants.
