### ISSUE TITLE
Why am I getting an error when working with the guidelines?

### ISSUE THREAD

**Issue by Ngmong** [google/ExoPlayer#3793]
1.    mMainHandler = new Handler();
2.    context = getApplicationContext();
3.   DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
4     DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, 
5.     Util.getUserAgent(context, "yourApplicationName"), bandwidthMeter);
6.     MediaSource videoSource = new
7.     ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(mp4VideoUri);
8.     player.prepare(videoSource);

I want to work with actionCam

An error occurs in the 7th line Factory part of my code

What is the problem?

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
