### ISSUE TITLE
A/ACodec + A/libc

### ISSUE THREAD

**Issue by SnailRabbids** [google/ExoPlayer#3794]
Hi guys. I have such a problem: I have an Android game (the essence of the game in choosing the right answer to the question) that occasionally casts up with such a lag, then white screen and then continues to work but from the previous question. This is not happening on all devices, this happens very rarely on the emulator (Android version 6.0), and on my old Lenovo (4.1.2) - often. Help please, I can not understand what's going on for a very long time :(
![image](https://user-images.githubusercontent.com/36141552/35784106-a2a35288-0a13-11e8-81a0-01f4717d4e28.png)

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
