### ISSUE TITLE
Exoplayer not work correct

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#3811]
I have a video with two language (Russian and Japanese) 
In VLC when I select stereo mode: 
- Default: two language use
- Left: Russian 
- Right: Japanesse
I want to implement that on Exoplayer

```
    @Override
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
        audioTracks = new HashMap<>();
        for(int x=0;x<trackGroups.length;x++){
            if(trackGroups.get(x).getFormat(0).sampleMimeType.contains("audio")){
                audioTracks.put(trackGroups.get(x).getFormat(0).language, false);
            }
        }
    }
```

```
    public void switchPreferredAudioLanguage(String language){
        if (!audioTracks.get(language)) {
            trackSelector.setParameters(trackSelector.getParameters().withPreferredAudioLanguage(language));
        }
    }
```

But I see that audioTracks have no Japanesse language or Russian language, and switchPreferredAudioLanguage not work.

**Comment by AquilesCanta** [comment]
Hi, I don't understand the idea. I don't know too much about what VLC offers, so please provide precise steps of what you would like to do.

If what you want to do is just to select the language, then you just need this line

`trackSelector.setParameters(trackSelector.getParameters().withPreferredAudioLanguage(language))`

However, in order for this to work, you need to make sure the language is being correctly declared in the media. For these cases, it is helpful if the media is sent to us somehow, to prevent back-and-forth communication.

**Comment by mdtuyen** [comment]
Hi @AquilesCanta
Could you check [this video](https://www.dropbox.com/s/n9hz2p02r5bhu66/bs102_2_.mp4?dl=0)

In the video when play with any player you can hear two language nested (japanesee and russian) 
However I can't hear only japanesee or russian by change stereo mode in vlc ( Audio > Stereo audio mode > lef/right)

I see that exoplayer I can setup preferred audio language with function:
`trackSelector.setParameters(trackSelector.getParameters().withPreferredAudioLanguage(language))`

But It not work with my video.
I do not know if I have misunderstood or  implement wrong

**Comment by AquilesCanta** [comment]
I see now. Relevant: #2659 (thanks to @andrewlewis). This is a single audio track which contains both languages, so the default track selector will not be of any help. As correctly pointed out in the referred issue, you can use a [ChannelMappingAudioProcessor](https://github.com/google/ExoPlayer/blob/e87e231/library/core/src/main/java/com/google/android/exoplayer2/audio/ChannelMappingAudioProcessor.java) to map a single input channel to both output channels. To inject the ChannelMappingAP, you can override buildAudioProcessors if using a DefaultRenderersFactory instance. You can redirect an input channel to both output channels by invoking `setChannelMap(new int[] {0, 0} /* or {1, 1*/)`. This does not solve the language detection issue, though. I could not find any information in the file that signaled the language of each channel so that is something ExoPlayer cannot help with. If the file does include language information per channel, please let me know. 

As a side note, if you control the media, it'd be cool to remux the media into a video track + 2 audio tracks, including the relevant language information. Please give the proposed solution a try, and let us know if you run into issues.

**Comment by mdtuyen** [comment]
Hi @AquilesCanta,

Could you help me a sample for this case, please ?
