### ISSUE TITLE
Exception when Merging Multi-Period DASH and SingleSampleMediaSource subtitle.

### ISSUE THREAD

**Issue by richardissuperman** [google/ExoPlayer#3812]
### Issue description

we are trying to use a ```MergingMediaSource``` and merge one ```DashMediaSource``` with multiple subtitles using ```SingleSampleMediaSource```. 

The problem is that the ```DashMediaSource``` is pointing to a mpd file which contains 2 periods. So the Player will throw an ```IllegalMergeException(IllegalMergeException.REASON_PERIOD_COUNT_MISMATCH)``` in the 
```checkTimelineMerges()``` method in ```MergingMediaSource```, since the period count is mismatched. Dash has 2 while ```SingleSampleMediaSource``` has only one.
### Reproduction steps

the following few lines of code will easily reproduce the bug

```java
 MediaSource[] mediaSources = new MediaSource[subtitleHolder.getSubtitleMap().size() + 1];
            mediaSources[0] = new DashMediaSource();

            int i = 1;
            for (Map.Entry<String, Uri> subtitleEntry : subtitleHolder.getSubtitleMap().entrySet()) {
                Format textFormat = Format.createTextSampleFormat();
                SingleSampleMediaSource originalSource = new SingleSampleMediaSource();
                
                mediaSources[i] = originalSource;

                i++;
            }

            return new MergingMediaSource(mediaSources);


```

### Version of ExoPlayer being used

we are using **rc6**
### Device(s) and version(s) of Android being used

doesnt matter what device

**Comment by AquilesCanta** [comment]
Hi, this is a limitation of the MergingMediaSource, but also working as intended. 

Given multiperiod content, there is no single way of mapping samples from a single period media source to it. The only correct way would be to have the content creator to do the mapping, and include it in the manifest. If you control the content, that'd be the right (and easiest) thing to do. Otherwise, you could split the subtitle content into two periods to match the main content, though it will require a bit of work.
