### ISSUE TITLE
MediaClock and render position offset

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#3813]
When using a custom MediaClock, is it true that I have to manually adjust the position given by the clock with the render offset position defined in [ExoPlayerInternalImpl.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L96)? I seem to have to compensate for this offset because media starts at 60s and the time returned by MediaClock is used as the render position.

**Comment by andrewlewis** [comment]
`Renderer.replaceStream` takes a time offset that should be added to sample timestamps read from the sample stream (`BaseRenderer.readSource` does this). If your renderer is a `MediaClock` its position needs to include the offset, so that the position matches up with the offset input sample timestamps.

When the renderer is first enabled the time offset will be 60 seconds, matching the constant in `ExoPlayerImplInternal`, and subsequent streams will have an offset equal to 60 plus the sum of the durations of previously played media periods (assuming zero start positions).

To give some background: we originally added this 60 second offset so that an initial `ClippingMediaSource` could provide samples with negative timestamps when prerolling from a keyframe preceding the start position while avoiding feeding negative timestamps to the renderer; we are assuming the keyframe interval won't be greater than 60 seconds.

**Comment by pakerfeldt** [comment]
What we have right now is just a subclass of `MediaCodecVideoRenderer` where we pass a `MediaClock`. If I understand you correctly, we would override `Renderer.replaceStream` in our renderer to hijack the offset and use it in our `MediaClock`, right?

**Comment by andrewlewis** [comment]
Yeah, that sounds right.

**Comment by pakerfeldt** [comment]
Thanks!

**Comment by pakerfeldt** [comment]
Turns out `BaseRenderer.replaceStream` is final so that didn't help. Should we make it non-final or perhaps allow for accessing the offset by some other, more explicit, means?

**Comment by andrewlewis** [comment]
Does `BaseRenderer.onStreamChanged` work instead?

**Comment by pakerfeldt** [comment]
True, that should do it.
