### ISSUE TITLE
Failure to download webvtt caption when seek operation performed.

### ISSUE THREAD

**Issue by arjun-redspace** [google/ExoPlayer#3819]
**Stream Info:** Send to the email dev.exoplayer@gmail.com

When playing above stream with caption ON (MimeTypes.TEXT_VTT), performing seeking operation stalls the player. `onPlayerStateChanged` was observed for BUFFERING state when seek process started and upon completion READY state wasn't observed after downloading chunks (verified with Charles). This is not observed when caption is turned off.

Also, the same stream could be played with captions ON without any issues in chrome browser (laptop or android mobile device). 

**Code details:** 
Under `ExoPlayerImplInternal` class,  function `haveSufficientBuffer(boolean rebuffering)` returns incorrect value because of incorrect value obtained from `loadingPeriodHolder.mediaPeriod.getBufferedPositionUs()`. 

There were two `HlsSampleStreamWrapper` objects and looks like one for chunks and other for caption. Chunks wrapper had correct buffered position but caption wrapper had incorrect buffered position (start value of seek position).

As a result, player assumes that it hasn't downloaded necessary details to continue playing and stays in BUFFERING state.

**ExoPlayer version:** r2.4.1

**STR:**
1. Open player 
2. Load above stream.
3. Turn caption ON.
4. Perform Seek (forward).

**Actual:** Video playback stalled indefinitely.
**Expected:** Video playback continues playing after downloading necessary chunks and captions.

**Tested devices:** 
Samsung Galaxy S5, 6.0.1
Samsung Galaxy S4, 5.0.1

**NOTE:** Stream information/url, bug report and logcat are supplied via email.

**Comment by AquilesCanta** [comment]
The problem here is that the variant streams contain discontinuities, but the subtitle rendition stream does not. Due to this, ExoPlayer is blocked waiting for the timestamp adjuster to be initialized, but it never is because of described condition. The [HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.3.3) states:

> Matching content in Variant Streams MUST have matching timestamps. This allows clients to synchronize the media.

> Matching content in Variant Streams MUST have matching Discontinuity Sequence Numbers - see Section 4.3.3.3.

Arguably, the spec does not enforce discontinuity matching on alternative renditions (like subtitles), but I cannot think of a scenario where without matching discontinuities, content is "synchronizable". I will contact the specification authors to ask for a clarification.

In the meantime, the fix would be adding the EXT-X-DISCONTINUITY tags to the subtitle playlist.

**Comment by AquilesCanta** [comment]
Hi @arjun-redspace, I can confirm the discontinuity tag is spec-required to appear in every media playlist.

**Comment by arjun-redspace** [comment]
Thanks a lot for the detailed explanation, @AquilesCanta!
