### ISSUE TITLE
how to rotate video without losing current loaded data 

### ISSUE THREAD

**Issue by abvaalgit** [google/ExoPlayer#3843]
i am trying 3 months to create video player in exoplayer 
everything is good but one thing 
when i change portrait to landscape activity is created again and i lost previous  loaded data and gesture .
and  every thing continue from first and it is very bad Trouble for end user is not beautiful

**Comment by RamIndani** [comment]
This is not really a bug, you should redirect your question to stackoverflow.

**Comment by eneim** [comment]
@abvaalgit There is no way to retain the Surface, but the playback state is possible. I have my own solution (under testing though). If you are interested in, I can share a bit.

**Comment by tonihei** [comment]
Please have a look at our demo app where you can rotate the video without losing any data. The player is independent of the UI, so it is sufficient to keep the player instance around and not recreate it.

**Comment by botaydotcom** [comment]
I'm afraid there's not one easy and best way to do this.
- One way (you may call cheating) is what ExoPlayer's Demo app is doing, which is to retain the `Activity` on config change. This makes everything simpler at first, but if you UI is really complicated, and you have significant different UI between landscape & portrait mode, it's not easy to get everything right in  `onConfigurationChanged`.
- A second way: is to separate the UI and the player. So you can have something like an UI `Fragment`, which hosts the view and the player surface. This UI fragment can be destroyed & re-created on config change. The player has to live somewhere that's not destroyed - for example on a retained `Fragment`. Then when the UI fragment is created and the `Surface` is ready, then you reattach it to the player, and continue to play from the previous playback position. This method has the benefit that things are separated cleanly, and you don't have to cheat (retaining activity on config change using `onConfigurationChanged` is kind of cheating, which is discouraged on Android). However, reattaching the `Surface` to `MediaCodec` is really error prone, especially on older version of Android. You can encounter all sort of problems, from `MediaCodec` failure, which leads to playback failure, to device hangs/reboots etc (these are devices specific). One more common issue (for which there is no easy solution) is key frame skipping: Before you re-attach the new `Surface`, the player has sent the previous frame to `MediaCodec`, which has already decoded and displayed it; after you re-attach, the player will send the next key frame to `MediaCodec` for rendering. So if you pause your playback and rotate it, the frame will keep jumping forward.
- Another solution I can think of (which is totally different from the other two) is to use Caching. So you have some kind of `Cache` for your player, and you let your `Activity` destroy and recreate the player on config change, then save the playback position and restore it on resume. Due to the `Cache`, the player will resume playback much faster than without one.

**Comment by eneim** [comment]
@botaydotcom Good points about the MediaCodec. I think the ultimate goal is to reuse the setup without the need of warming it (the native codec) up again. 

I do a search around and turn to this example (which is quite famous I suppose): [DoubleDecodeActivity.java](https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/DoubleDecodeActivity.java). Not have a deep investigation on this, but how do you think?

**Comment by botaydotcom** [comment]
I didn't know that example before.

Anw, briefly read the code. What it does is reusing a `SurfaceTexture` on a `TextureView` (save it, then reattach the `SurfaceTexture` after rotation). I guess this works, but with a few limitations:
- It only works if you use `TextureView` instead of `SurfaceView`. Unfortunately `TextureView` is much less efficient as compared to `SurfaceView`, and I believe playbacks using `TextureView` use more CPU/battery than `SurfaceView`.
- It does not works for DRM-protected playbacks, at least on older Android version.

Anw, I think this is the reason ExoPlayer introduced `DummySurface` (to make this kind of surface switching seamless). Unfortunately, it will only work for newer SDK (23, 24+), and may encounter problems on certain devices.

**Comment by abvaalgit** [comment]
thanks from all of you ...
you helped me a lot ,,,,
i will study demo app and my answer there 
thanks all one by one
