### ISSUE TITLE
Stream never reaches end with repeatMode

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#3847]
### Issue description
I don't believe this is necessarily a bug with ExoPlayer but what I find is that our player does not loop when setting `repeatMode` to either `REPEAT_MODE_ONE` or `REPEAT_MODE_ALL`. In fact, `MediaCodecRenderer` never reaches `processEndOfStream()`. The player overshoots the duration of the video and keeps calling `drainOutputBuffer()` in the renderer where `outputIndex` settles on -1 for all subsequent calls after stream should have ended, freezing on the last frame.

We were running r2.5.3 previously and I noticed the player entering rebuffering state when video should have ended. I bumped to 2.6.0 and now the player does not enter the buffering state but it still overshoots the render position and never finishes.

In our implementation we are using custom `MediaPeriod`, `MediaSource` and `ChunkSource` implementations. Maybe there are some expectations on these we are not fulfilling. They are however fairly similar to the `exoplayer-dash` ones.

My current test video is 13s long which is correctly reported in the timeline (`periodDurationUs` and `windowDurationUs`. When video should end render position is at some 74295000 us and keeps counting.

I tried disabling the audio stream and only do video but without success. Video finishes normally without `repeatMode` though. 

### Version of ExoPlayer being used
2.6.0 (exoplayer-core and extension-okhttp)

### Device(s) and version(s) of Android being used
Google Pixel 2 (8.1.0)

### Link to test content
Since our content is not in MPEG-DASH I am unable to verify it with the reference application.

Would truly appreciate some pointers in how to further trouble shoot our issue. Thanks!

**Comment by tonihei** [comment]
It's a little bit difficult to guess what's wrong with your code. But here are a few thoughts based on the things you reprorted: 
- The difference between repeating and not repeating for the media streams is that the sample stream is marked as final if it's the last one. Streams marked as final just play to their last sample and playback ends as soon as all streams report that they have ended. When the stream is not marked as final (e.g. when repeating), the end of stream signal is suppressed, that's why you don't see the processEndOfStream(). Instead, we wait until the renderer position passes the required offset to start the next playlist item to continue playing the next item.
- The transition to the next item happens [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L1288). It might be this `rendererPositionOffsetUs` of the next item is wrong and that's why this transition never takes place. This value is based on the duration of the current item and the returned value of `MediaPeriod.selectTracks` (which might be wrong in your custom implementation). 
- Alternatively, this transition may not take place because we never started reading the next playlist item. At some point all the renderers should report that they read their stream to end ([see here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L1307)) that the player continues reading with the item. 

Can you debug through the mentioned places and check whether anything looks suspicious?

**Comment by pakerfeldt** [comment]
Thank you. I will go through your comments and report back. A quick note though. I *do*  see `processEndOfStream()` being called in your reference app right before the stream starts over from the beginning. It sounds from your first comment that this should not be the case?

**Comment by tonihei** [comment]
I don't see this happening in our demo app and the current dev branch. Seems like a thing to investigate how you end up in there.

**Comment by pakerfeldt** [comment]
I tried first with release-v2 and now dev-v2. The only change is adding `player.setRepeatMode(Player.REPEAT_MODE_ONE);` to line 313 in `PlayerActivity.java` (dev-v2). I tried with both `REPEAT_MODE_ONE` and `REPEAT_MODE_ALL`. My breakpoint in `processEndOfStream` triggers right before video loops.

**Comment by pakerfeldt** [comment]
Maybe I actually came across a bug after all. Not sure. Thanks to your guidance it became evident that our misc renderers is not allowing the stream to finish. We have two of them which doesn't really render anything. They exist for other purposes. They extend `BaseRenderer` and when ExoPlayer asks if they `hasReadStreamToEnd()` they answer `false`. It does not matter that our renderers override `isEnded()` to return `false` either. I guess we could implement `Renderer` directly and avoid using `BaseRenderer` but I wonder if this behavior we're seeing is expected or considered a bug?

**Comment by tonihei** [comment]
Yes, you're right. processEndOfStream is still called (my debugger played tricks on me and didn't stop there even though it was called).

I'm glad you found the reason for the problem you're seeing. This behavior is expected because the player waits for all renderers to end. These other renderers could return true in hasReadStreamToEnd, especially if there are not reading anything.

**Comment by pakerfeldt** [comment]
Well, `hasReadStreamToEnd()` is final in `BaseRenderer` so I can't override it. However, I will implement our own base renderer for this purpose and avoid using `BaseRenderer`.  

Will `render` still be called even if the renderer suggests we've reached end of stream? In that case I have another problem.

**Comment by tonihei** [comment]
There is also a `NoSampleRenderer` which can be used if your renderer is not supposed to read any samples. This class simplifies some of the issues you may have when you try to write a Renderer from scratch.

**Comment by pakerfeldt** [comment]
Thanks. Appreciate the guidance!
