### ISSUE TITLE
[Question] How to run the test cases in Android Studio (1.1.0)?

### ISSUE THREAD

**Issue by mine260309** [google/ExoPlayer#387]
Hi All,

  This may be a silly question, but I failed to execute the test cases under `library/src/test/` in Android Studio 1.1.0, which always reports `Empty test suite.`

  I tried to add `Android Tests` configuration for `library` module, but it always report "Empty test suite." during execution.
  I have googled the problem and tried several possible solutions, but none of them works.

  If you happen to know how to make it work in Android Studio, could you kindly share your steps to execute the test cases?

  Thanks!

**Comment by ojw28** [comment]
I think this should be fixed by https://github.com/google/ExoPlayer/commit/48826836d15d7ea57a4ea55fb48d1823b95a93e4, which relocated the tests under the androidTest directory. After this change I was able to run the tests in Android Studio. Please sync to latest dev and give it a try.

Marking as closed, but please reply here if you're still having issues, and we can open it again if needed.
