### ISSUE TITLE
First frame of the video not visible when onPlayerStateChanged(boolean playWhenReady, int playbackState) with playbackState equal to Player.STATE_READY is called

### ISSUE THREAD

**Issue by GauthierChan** [google/ExoPlayer#3870]
### Issue description
onPlayerStateChanged(boolean playWhenReady, int playbackState) with playbackState equal to Player.STATE_READY is called but the first frame is not rendered and the play button doesn't start the video instantly.

### Reproduction steps
I created a test project here https://github.com/GauthierChan/ExoPlayerBlackBlink to reproduce the issue.
The issue is particularly visible when doing a SharedElementTransition from a video thumbnail to the actual video player as such:
![enter](https://user-images.githubusercontent.com/14746791/36441162-1220020e-1672-11e8-89f2-b5635c134d10.gif)

Reproduction steps:
1) Create 2 Activities in order to have a SharedElementTransition between an ImageView in Activity A and an ImageView in Activity B. In Activity B, the ImageView will be above a SimpleExoPlayerView to act as a placeholder while the video is loading (in the test project we have MainActivity and DetailActivity respectively).
2) When the EnterSharedElementTransition finishes in Activity B, prepare the SimpleExoPlayer with the video. Add a Player.EventListener to the SimpleExoPlayer
3) Override onPlayerStateChanged(boolean playWhenReady, int playbackState) so that we hide the ImageView acting as a placeholder when playbackState is equal to Player.STATE_READY

You should see a short black screen with the video controls before the first frame of the video becomes visible

### Version of ExoPlayer being used
2.6.1

### Devices and versions of Android being used
Pixel 2 XL on 8.1.0
Nexus 6P on 8.1.0
Samsung Galaxy S6 (SM G_920F) on 7.0
TCL 9030G on 6.0.1

**Comment by andrewlewis** [comment]
By default `SimpleExoPlayerView` will show video frames in a `SurfaceView`. Because of the way `SurfaceView` works, if you set a non-opaque alpha value it will just show up as a black rectangle. So possibly what's going on is that the player really has rendered at a frame at the point when it becomes ready, but it gets shown as a black rectangle because the transition tries to make the `SurfaceView` not opaque.

One easy way to fix this is to use `TextureView` instead, by setting `app:surface_type="texture_view"` on your `SimpleExoPlayerView`. This view can be translucent, but video playback will drain a bit more battery compared to using `SurfaceView` as there is an extra level of indirection (probably not an issue for short form content though). Also, `TextureView` doesn't support secure output, in case you are using DRM. Alternatively, you could try making the transition not modify the opacity of the view. This is similar to #1160.
