### ISSUE TITLE
No config update for Formatter in DefaultTimeBar when config change?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3899]
This is rather a question than a issue report, although if this is unexpected, it should be an issue.

As I see in the implementation of **DefaultTimeBar**, there is a **Formatter** in used, it is final, and initialized with default Locale. The concern is: when application's config change, this formatter is not updated, in fact, as it is a final member it will not be re-initialized on such event (I know creating one instance of this is expensive).

The questions/problems ares: 

- Latest Android version uses ``LocaleList.getDefault()`` (from Android 24) instead of ``Locale.getDefault()`` for modern devices. Should ExoPlayer follows this with a fallback for older API?

- I see the formatter is used to update the content descriptions only, not impact the visual result. But as the concern, should the formatter also be updated following the application's config change? (in View class, there is ``onConfigurationChanged`` for this purpose, and a usage reference can be found in TextView implementation).

If the problems above are taken into account, and implemented by intent, it is fine :D. Otherwise I'm open for a PR.

**Comment by erdemguven** [comment]
I guess the same questions apply to PlayerControlView.

**Comment by ojw28** [comment]
Activities are normally recreated if the locale changes, which makes this a non-issue. The app developer would have to explicitly disable activity recreation on locale change with `configChanges=locale` in their manifest for it to be a problem, which feels like something app developers wont (or shouldn't) be doing. The user would also have to change the device locale in the first place, which seems like an edge case.

Closing, since I don't think this is a real issue in practice. Note also that if activity recreation is disabled for locale changes then other stuff in ExoPlayer's UI components will also end up being wrong (e.g. the content description strings may be in the wrong language).
