### ISSUE TITLE
Getting The Body of an 403 response after an HttpDataSource.InvalidResponseCodeException

### ISSUE THREAD

**Issue by jrocharodrigues** [google/ExoPlayer#3920]
Hi,

When playing DASH + widevine content, when acquiring the license for the content, in some situations the license server answers with a status code 403 and in the body it sends the reason for the that status (example: When the content is being played on another Device with the same login).

Since there are multiple reasons for the server to answer with 403, i need to parse the body to check the reason and show the appropriate error message to the user.

Is there an easy way to get access the error stream from the connection used on DefaultHttpDataSource after getting an HttpDataSource.InvalidResponseCodeException? Or do i need to extend the DefaultHttpDataSourceFactory and the DefaultHttpDataSource classes and use them instead of the default ones  on the HttpDrmCallback?

Thanks in advance

BRs

**Comment by ojw28** [comment]
In another production system I've seen the license server will respond with a 200 in this case, with the reason for refusal in the body. You can then implement your own `MediaDrmCallback` that's like `HttpMediaDrmCallback`, but with some additional parsing of the response in `executeKeyRequest` that will parse any refusal reason from the response and, if there is one, throw a corresponding exception. This will eventually end up being propagated all the way to your player's `EventListener` if playback ends up failing.

You can do roughly the same thing in your case as well, except that you'll need to do a bit more work in your custom `MediaDrmCallback` implementation. In particular you wont be able to use `HttpDataSource` like `HttpMediaDrmCallback` does, because it doesn't provide access to the body in the case of a 403. So you'll need to access the network stack directly in your implementation.

**Comment by jrocharodrigues** [comment]
Thanks for the answer @ojw28 
That was the impression i had. 
I Will proceed with a custom HttpDataSource implementation.

Brs
