### ISSUE TITLE
Exoplayer keeps stopping my live stream

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3936]
Hello friends!
What is happening is the following while watching my live stream and after a few seconds he stops and I have to press the play again for him to continue.

Would I have some method for autoplay when I stop running my live stream?

I'm using version 2.7

Thank you!

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
