### ISSUE TITLE
Best Practices Question

### ISSUE THREAD

**Issue by directable** [google/ExoPlayer#3948]
We have an application that cycles through potentially many videos and runs for days/weeks. In some instances the videos only play for 10 seconds. All the videos are always copied to the device before we ever play them.  In some cases more than one video is played at the same time.

We wanted to ask your advice on best practices for how to use the exoplayer components. Today we create/destroy an instance of PlayerView and SimpleExoPlayer as well as a datasourcefactory and mediasource.  Is what we are doing ok, or do you recommend creating and holding onto sufficient instances of everything for the number of concurrent videos we play (other than the MediaSource, which we have read should not be resused).

Thank you so much

**Comment by botaydotcom** [comment]
Hi @directable ,
I don't think there's any problem create/destroy/recreate player instances repeatedly, except maybe for performance - so if your app is running fine, not slow, janky etc..., that might not be an issue, and you can continue use your current approach if it works. In some cases (activity goes into background, onStop/onStart), it might even be advisable to destroy and recreate the player instance again.
If you play multiple online streams (although it seems it's not the case for your use-case) one thing I would recommend reusing is the `BandwidthMeter` instance, because it will help the new players to adapt to network condition faster. This is what we do in our Demo app.

With that being said, I think you can also use the same player instance to play different `MediaSource`s. At the moment, I think  there are only minor performance gain for doing that, but I have never done any performance comparison between these 2 setups (re-creating multiple players to play multiple streams repeatedly vs using the same player), or work on similar use case to comment on the actual result. You may need to try out and compare it yourself.

In the (near) future, we plan to add some features that will help to keep certain useful things when switching streams in one player (for example: keeping the system codecs instead of releasing/creating new ones). That might bring in a bigger performance gain, especially for local playback use-case.

**Comment by directable** [comment]
Thank you so much, this is very helpful.
