### ISSUE TITLE
exoplayer updation issue

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#3951]
hi everyone,
There is exoplayer demo app version 2.7.0 with packages  called **demo** , **democast**, **demoima** in which similar files are there demoutil and player manager , can  anyone explains the use of these files and explains the purpose of these files in different package. Let me know if u want more clarity for my doubt.

**Comment by pals-ric** [comment]
can anyone explain functionality of these packages.

**Comment by ojw28** [comment]
All of these packages have README files ([here](https://github.com/google/ExoPlayer/tree/release-v2/demos/cast), [here](https://github.com/google/ExoPlayer/tree/release-v2/demos/ima) and [here](https://github.com/google/ExoPlayer/tree/release-v2/demos/main)). Furthermore, the files you refer to have Javadoc, for example [PlayerActivity](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java), that explain what they're for. It should also be possible to work it out be reading the code and running the apps to see what they do. I suggest you do these things as a starting point.

Please could you also redirect questions like this to StackOverflow rather than this issue tracker? Thanks.
