### ISSUE TITLE
[Question] M worked Exoplayer Secure Playback not working on N

### ISSUE THREAD

**Issue by kenlsoft** [google/ExoPlayer#3956]
Hi,
I am a DRM solution developer and now I am trying with Clearkey and make it play streams with secure codec support.
In M I just modified DrmPlugin.h to let requiresSecureDecoderComponent() return true; and implement my codec with ".secure" suffix and then everything works. Surfacefligner part needs to be updated too but that is not the point where problem is.
And after I moved all these changes into Andorid N with same built Exoplayer then everything does not work; seems Exoplayer on N won't assume a secure codec by adding  a ".secure" suffix; and Clearkey  DrmInitData:: requiresSecureDecryption is set to false; requiresSecureDecoderComponent() in DrmPlugin.h is never get called so secure codec is not initialized and finally an OMX.Vendor.decoder not supported appear, playback just fails.

So my question is, how could I make everything work on N? Where is the DrmInitData firstly get initialized for Clearkey?

This question bothers me quite a while and I am lost in Exoplayer sources; if anyone could give a quick hint it would be great helpful...
Thanks.

**Comment by ojw28** [comment]
Prior to API level 21 the application layer had to guess the existence of a secure decoder by adding the ".secure" suffix to a decoder name and trying to instantiate an instance. From API level 21 onward secure decoders were instead supposed to be explicitly listed as separate entries in `MediaCodecList`, so that the application layer could query their existence and capabilities. Because it took a while for device manufacturers to reliably do this, we still fall back on trying to blindly add the ".secure" suffix up to API level 23 (M), and disabled this code path on API level 24 (N).

So your problem is probably that your secure decoder isn't exposed via `MediaCodecList`, or that it's not advertising support for secure playback. Fixing this may be as simple as adding an entry to `media_codecs.xml`. Here's a random example I found:

https://github.com/mozilla-b2g/device-asus-fugu/blob/master/media_codecs.xml#L115

Note `<Feature name="secure-playback" required="true" />`, which is important to indicate that the decoder is secure.

**Comment by kenlsoft** [comment]
Thanks.
