### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [google/ExoPlayer#3968]
It's auto report from crash-reporting-tool. The bug in recent versions. It's will let app crash.

Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource$Listener.onSourceInfoRefreshed(com.google.android.exoplayer2.source.MediaSource, com.google.android.exoplayer2.Timeline, java.lang.Object)' on a null object reference

1 com.google.android.exoplayer2.source.ExtractorMediaSource.notifySourceInfoRefreshed(ExtractorMediaSource.java:380)
--
2 com.google.android.exoplayer2.source.ExtractorMediaSource.onSourceInfoRefreshed(ExtractorMediaSource.java:372)
3 com.google.android.exoplayer2.source.ExtractorMediaPeriod.maybeFinishPrepare(ExtractorMediaPeriod.java:555)
4 com.google.android.exoplayer2.source.ExtractorMediaPeriod.access$000(ExtractorMediaPeriod.java:51)
5 com.google.android.exoplayer2.source.ExtractorMediaPeriod$1.run(ExtractorMediaPeriod.java:153)
6 android.os.Handler.handleCallback(Handler.java:751)
7 android.os.Handler.dispatchMessage(Handler.java:95)
8 android.os.Looper.loop(Looper.java:159)
9 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pallavirichhariya22** [comment]
hi i
 am not able to find subtitle layout class in exoplayer 2.7.0 . can anyone tell what is the replacement for subtitle layout class in updated version.

**Comment by ojw28** [comment]
You're probably experiencing this NPE because your app is probably re-using `MediaSource` instances. As per the [developer guide](https://google.github.io/ExoPlayer/guide.html#mediasource), you should not do this, although we will be removing this restriction in future versions (probably from 2.8.0).

Alternatively, it's possible that you're app is hitting https://github.com/google/ExoPlayer/issues/3796, which was fixed in 2.7.0.
