### ISSUE TITLE
When i'm choosing next clips or videos in m3u8 format that time i'm seeing previous Closed caption tittle not showing current tittle

### ISSUE THREAD

**Issue by sathishkumar1392** [google/ExoPlayer#3974]
For Example : I having 3 videos clips

When i'm playing first video currently showing first clips closed caption. When i choose second clips that time showing first clips closed caption only in Exoplayer. Previous Closed caption not clearing.

**Comment by botaydotcom** [comment]
Hi @sathishkumar1392,
I tried to reproduce this on the Demo app, but couldn't reproduce it:
- Played 3 HLS (m3u8) streams in a playlist.
- Turned on caption for the first clip.
- Waited until the player played the second clip (also tried to skip to the second clip). Caption for the first clip was cleared properly.

Please try to reproduce this issue in our Demo app if possible, and provides us with more information according to our [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE), including: which version of ExoPlayer you used, which device/Android version you used, links to the test content, and bug report captured immediately after you can reproduce the issue. Thank you very much.

**Comment by sathishkumar1392** [comment]
hi @botaydotcom 
* It played well when the first clips ended and then second clips started it will load second Caption.
* But scenario is When first clips is playing and Caption also playing that time working perfectly. When  I skipped the  Second Clips that time first clip Caption is Showing in second clip.that issue exactly.

**Comment by botaydotcom** [comment]
Hi @sathishkumar1392 ,
Thanks for the update, but that doesn't provide us with enough information. As mentioned in previous comment, I also tried to skip from 1st clip to 2nd clip while playing with captions, and the captions were cleared properly, so I couldn't reproduce this issue.

Please try to reproduce this issue in our Demo app if possible, and provides us with more information according to our [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). Otherwise, I will have to close this issue. Thank you very much.

**Comment by sathishkumar1392** [comment]
Can i get sample code for clearing caption

**Comment by botaydotcom** [comment]
If you are using the default `SubtitleView`, you can use: `subtitleView.setCues(null);`.

**Comment by sathishkumar1392** [comment]
I fixed that  issue its Working fine Thanks for support lot
