### ISSUE TITLE
version conflicts

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#3988]
currently we are using exoplayer  version  2.3.1. i want to include exoplayer version 2.7.0 in same project how can we do that without conflict?

**Comment by botaydotcom** [comment]
Hi @pallavirichhariya22 ,
Can you provide the reasoning why you would like to do this? I think this is more of a general question with Gradle dependency, rather than ExoPlayer, which should be asked on StackOverflow instead.

Anw, I did a quick check [from SO](https://stackoverflow.com/questions/29374885/multiple-version-of-dependencies-in-gradle), and it seems this is not feasible (Gradle will use a conflict resolution strategy to use 1 single version of the library). If any one else can provide a better recommendation, please do. Otherwise, I will close this issue.
