### ISSUE TITLE
Metadata track not selected when allow chunkless preparation is true

### ISSUE THREAD

**Issue by scottfennell** [google/ExoPlayer#4016]
### Issue description
When utilizing the `setAllowChunklessPreparation(true)` for an HLS source timed ID3 metadata is not identified and the onMetadata callback is never called. It appears that a metadata source track is never identified when no sample chunks are downloaded. The DefaultTrackSelector.selectTracks output does not contain any metadata tracks and the Metadata renderer is never enabled.

### Reproduction steps
Create a player that utilizes the setAllowChunlessPreparation for HLS with a onMetadata callback on the player - the onMetadata callback will never get called
```
new HlsMediaSource.Factory(dataSourceFactory)
    .setAllowChunklessPreparation(true)
    .createMediaSource(uri, mainHandler, eventLogger)
```

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
Pixel 2 XL Oreo + various emulators

**Comment by AquilesCanta** [comment]
Hi @scottfennell, great to know you are using chunkless preparation. This is a known limitation, listed in our [medium post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6):

> _ID3 tracks are not supported (there is no spec-defined way to declare ID3 tracks in playlists)._

I will mark this as an enhancement, since one of the options we considered was preemptively declaring a track, like the TS extractor does. A commit ref will appear here once we push the workaround.

**Comment by ojw28** [comment]
I believe this can be marked as fixed (@AquilesCanta - Please re-open if there's more to do)

**Comment by AquilesCanta** [comment]
Please let us know if you run into any issues with ID3 while using chunkless preparation.
