### ISSUE TITLE
EventDispatcher should not be part of MediaSourceEventListener

### ISSUE THREAD

**Issue by taryodor** [google/ExoPlayer#4026]
https://github.com/google/ExoPlayer/blob/b704a1d6436ba64a0d6fab2868d36a6b47030fdc/library/core/src/main/java/com/google/android/exoplayer2/source/MediaSourceEventListener.java#L214

If I create my own listener that implements this interface and pass it to MediaSource factory, app will crash on NullPointerException because EventDispatcher that is hidden inside interface will be missing.
Is that desired feature? It makes sense to me to separate listener's interface and EventDispatcher.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by AquilesCanta** [comment]
Which media source factory are you passing the listener to? Could you also provide context on where the NPE is thrown?

**Comment by tonihei** [comment]
Also, technically, these are separate classes as EventDispatcher is a public static final inner class and thus not hidden in any way. 

Getting a NPE sounds as if you forgot to pass in a `Handler` to the media source you are using?

**Comment by taryodor** [comment]
@tonihei you are right. My bad. Thank you and sorry.
