### ISSUE TITLE
HLS additional audio in manifest isn't visible in r.2.7.1

### ISSUE THREAD

**Issue by peyoh** [google/ExoPlayer#4028]
Hello. 

After upgrade from r.2.6.1 to 2.7.1, additional audio track (in the example AAC track) in the manifest isn't shown in the demo player. Is this expected behaviour in 2.7.x?

Here is the playlist:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="aac",DEFAULT="YES",AUTOSELECT="YES",URI="liveapp/627_2_out/chunks.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=8187422,RESOLUTION=1920x1084,CODECS="avc1.640028,ac-3",AUDIO="audio"
liveapp/627_1080_2_out/chunks.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2612405,RESOLUTION=1280x728,CODECS="avc1.640020,ac-3",AUDIO="audio"
liveapp/627_2_ac3_out/chunks.m3u8
```

**Comment by AquilesCanta** [comment]
I don't know what my cause this. Would you kindly provide the information requested in the issue template?

**Comment by peyoh** [comment]
### Issue description
After upgrade from r.2.6.1 to 2.7.1, additional audio track (in the example AAC track) in the manifest isn't shown in the demo player's AUDIO selection dialog.
In r.2.6.1  [release 2.6.1](https://github.com/google/ExoPlayer/commit/2b20780482a9c6b07416bcbf4de829532859d10a)  it is shown

### Reproduction steps
Use this HLS manifest:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="aac",DEFAULT="YES",AUTOSELECT="YES",URI="liveapp/627_2_out/chunks.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=8187422,RESOLUTION=1920x1084,CODECS="avc1.640028,ac-3",AUDIO="audio"
liveapp/627_1080_2_out/chunks.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2612405,RESOLUTION=1280x728,CODECS="avc1.640020,ac-3",AUDIO="audio"
liveapp/627_2_ac3_out/chunks.m3u8
```

### Link to test content
Manifest is already provided

### Version of ExoPlayer being used
[Release 2.7.1]( https://github.com/google/ExoPlayer/commit/b6155d2e08580dc07cd249d6439beacd99ca08b2 )

### Device(s) and version(s) of Android being used
Android studio device emulator,
Nexus 9, 
Lenovo K920,
Amlogic S905,
Android 5, 6, 7

### A full bug report captured from the device
[bugreport.tar.gz](https://github.com/google/ExoPlayer/files/1842025/bugreport.tar.gz)

**Comment by peyoh** [comment]
Example URL was sent to a developer's email.

**Comment by AquilesCanta** [comment]
Something is strange here. From the provided bugreport:

```
...
Renderer:1 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=1/129, mimeType=audio/ac3, channels=6, sample_rate=48000, supported=YES
     ]
   ]
...
```

Which means the track was detected and has codec support. Did you provide a bugreport from a different device? 

> isn't shown in the demo player's AUDIO selection dialog

Is the audio not shown, or is it greyed out? Here is a wild guess, just in case. If the audio option is actually greyed out (instead of missing), this most likely means the devices don't provide decoding support for ac-3. If so, maybe you were using the ffmpeg extension with 2.6.1, whose compiled binaries got removed when you upgraded the version. It might be worth making sure ffmpeg is compiled, if so.

Note: I cannot reproduce, the demo app is working as intended for me.

**Comment by peyoh** [comment]
Hi, 
the device is the same. Let me clarify:

In the demo app with **r.2.6.1**, AUDIO dialog shows **both** AC3 audio **and** AAC audio and the player is able to play both codecs.

in **r2.7.1** the AUDIO dialog shows **only** AC3 audio, **without** AAC audio (even it is declared in the manifest). The demo app **successfully plays** AC3 audio.
```
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="aac",DEFAULT="YES",AUTOSELECT="YES",URI="liveapp/627_2_out/chunks.m3u8"
```
Please ask me for any additional info you need.

**Comment by AquilesCanta** [comment]
Ok, I have had a look at it. The issue here is that the stream is malformed. You observe this regression because we now propagate the codecs attribute to audio variants. Which means that the audio rendition inherits the ac-3 codec from the STREAM-INF tag. This in turn causes the TS extractor to ignore the AAC track (this is an [old workaround](https://github.com/google/ExoPlayer/blob/r2.7.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java#L95) to support other malformed HLS streams). The solution is to either fix the media (strongly encouraged) or implement your own HlsExtractorFactory, which does not ignore the aac track. Also note that the EXT-X-MEDIA segment stream includes a video track, which gets completely discarded (same workaround), whereas only audio should be included in that rendition, otherwise, this incurs in a waste of bandwidth.

The relevant [piece of spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.2.4) due to which this is non-spec-compliant is:

```
If an EXT-X-STREAM-INF tag or EXT-X-I-FRAME-STREAM-INF tag contains
the CODECS attribute, the attribute value MUST include every media
format [RFC6381] present in any Media Segment in any of the
Renditions specified by the Variant Stream.
```
In this case, the stream is missing the AAC codec.
