### ISSUE TITLE
Content Duration for DASH is based on the shortest duration which in this case is the caption track

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#4029]
### Issue description
DASH duration reported to be the shortest representation, which in the Shaka Packaged content happens to be the text track.

### Reproduction steps
1) Content URL: https://cbsentallaccess.akamaized.net/intl_vms/2014/05/29/269373507506/1351917_cenc_dash/stream.mpd
2) The Representation id="0" codecs="wvtt" is 2650 secs. The Video representations are 2680. 
Exoplayer reports 2650 as the content duration. So the content playback stops at 2650 secs.

### Link to test content
1) Manifest URL: https://cbsentallaccess.akamaized.net/intl_vms/2014/05/29/269373507506/1351917_cenc_dash/stream.mpd

Emailed the license key url to "dev.exoplayer@gmail.com"

### Version of ExoPlayer being used
Tested with Exo 2.5.4 and also 2.6.1

### Device(s) and version(s) of Android being used
Any Android device

**Comment by zshenker** [comment]
@kqyang ^ Including you on this, as from our discussions you were suggesting that padding out the captions track to be the same duration as the audio/video tracks may be out of spec in DASH?

**Comment by kqyang** [comment]
@zshenker Yes, ExoPlayer's requirement is not DASH compliant. I wish this issue could be addressed in ExoPlayer. In the mean time, we'll look into handling it in Shaka Packager: https://github.com/google/shaka-packager/issues/356.

**Comment by ojw28** [comment]
I've filed https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/178 to request clarification on whether short representations are permitted. I haven't yet found part of the DASH spec or DASH IF recommendations that say either way whether they're allowed or not. Either I've missed the relevant section, in which case please direct me to it, or this feels like an omission. If the latter, I don't think it's fair to assume it's permitted just because the spec doesn't explicitly forbid it. If we adopted that approach in general then implementing a DASH client would be fairly unworkable. I've also posted some reasons on the clarification request why I think padding such representations to have the same duration of the period would be a good idea.

**Comment by ojw28** [comment]
@zshenker - Padding out the captions track with empty segments is definitely not "out of spec". It's definitely allowed. The clarification I've asked for is about whether _not_ doing this is also allowed.

**Comment by ojw28** [comment]
Discussed this with @joeyparrish. It looks like the DASH-IF discussion is headed in the direction of recommending padding segments to avoid short representations. However, given the time that will be required to update packagers, and that there's existing content with short representations, will will endeavor to support this case in ExoPlayer assuming a relatively low cost and side-effect free change can be made to do so.
