### ISSUE TITLE
getcurrentposition() issue

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#4058]
hi
 In my app we have live channels in which we are using player.getCurrentposition() to get the current played duraion but its returning unexpected values, for example we played video for 40 seconds but its returning 1 seconds or some random values.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by tonihei** [comment]
Please also take a look at this [documentation](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Timeline.html). You are most likely seeing the position in the current live window, which will update from time to time.
