### ISSUE TITLE
File Type checking is wrong for some files (Makes a best guess to infer the type from a file name.)

### ISSUE THREAD

**Issue by mahesh2015** [google/ExoPlayer#4060]
```
  @C.ContentType
  public static int inferContentType(String fileName) {
    fileName = Util.toLowerInvariant(fileName);
    if (fileName.endsWith(".mpd")) {
      return C.TYPE_DASH;
    } else if (fileName.endsWith(".m3u8")) {
      return C.TYPE_HLS;
    } else if (fileName.matches(".*\\.ism(l)?(/manifest(\\(.+\\))?)?")) {
      return C.TYPE_SS;
    } else {
      return C.TYPE_OTHER;
    }
  }
```

Method unable to get file type and always return C.TYPE_OTHER.
I have follow to fix this By
`uri.toString().toLowerCase(Locale.getDefault()).contains("m3u8")`
is this correct ?

I am will send a mail for the same with my uri value.

**Comment by ojw28** [comment]
We cannot use a "contains" check as proposed because non-HLS urls have also been known to contain that string. Note that `inferContentType` is never called directly by any library components. It's only called from the demo applications. If you wish to use different logic to infer the content type for your application, you can define your own method and use that one instead.

Ideally the library would automatically sniff the content type for all media types, rather than relying on the extension. This is tracked by https://github.com/google/ExoPlayer/issues/3165.
