### ISSUE TITLE
VIDEO FRAME PAUSE on 2.0x speed

### ISSUE THREAD

**Issue by vishal105** [google/ExoPlayer#4061]
I am using  2.7.2 exoplayer library.

In PlayerActivity::initializePlayer(), add
player.setPlaybackParameters(new PlaybackParameters(2.0f, 1.0f));

Then build and install the demo app on a Google Pixel Phone with Android 7.1 and some other device also, run the demo app, and play a 1080p video, for example, Misc -> Screens 1080p (FMP4, H264, No Audio)

please help.

**Comment by andrewlewis** [comment]
This is probably just a case of the decoder not being able to keep up. By setting the speedup to 2 you're doubling the frame rate of the video. You can verify this by looking at the counters at the top of the screen in the demo app. The number labeled 'db' shows the number of buffers that were dropped due to being late.

If you find that something else is going on please provide more information and I'll reopen the issue.

**Comment by vishal105** [comment]
but Its happen in some devices not all devices. If any other method to set a speed playing in exoplayer  then suggest me.
Thanking You.

**Comment by andrewlewis** [comment]
Some devices can play video a higher frame rates. For example, this plays smoothly for me on a Pixel 2 but not on a Nexus 6P. You could try playing a lower resolution video, which should be less computationally expensive.
