### ISSUE TITLE
SimpleCache for parallel download and playback

### ISSUE THREAD

**Issue by FD-** [google/ExoPlayer#4062]
I'm using the `Downloader`s to download media into a `SimpleCache`. At the moment (using ExoPlayer 2.7.1), this allows to start playback of the media while it is still being downloaded. 

However, I noticed commit [371f3acea87f6685ee65173ae30cbba5f2b6dd6b](https://github.com/google/ExoPlayer/commit/371f3acea87f6685ee65173ae30cbba5f2b6dd6b#diff-712fc451bc94c196ac662379ea2f71a3) will change `SimpleCache` to only allow one instance per folder.

In my use case, I create two `SimpleCache` instances on the same folder, but only one is used for writing (the downloading one), the other one is used read-only (the one for playback). It seems the change mentioned above would break that use case.

How would concurrent download and playback (of the same media) work with the change applied? Would I have to use a global static map of folder path -> cache instance? Does using the same `SimpleCache` instance (not just the same folder) work for concurrent read and write access?

**Comment by ojw28** [comment]
It's fundamentally unsafe to have two instances using the same directory at the same time (e.g. you can end up with cache corruption). You should use a single instance. This has always been the case, and the only change is we're now enforcing it.

> Would I have to use a global static map of folder path -> cache instance?

It's unclear why you need to consider more than one path. If you're using a different path for each piece of content, you should consider not doing that and using a single path for all content instead. Then you just need a singleton. If you do need multiple paths, then yes, you probably need a map to hold a singleton per path as you describe.

> How would concurrent download and playback (of the same media) work with the change applied? Would I have to use a global static map of folder path -> cache instance? Does using the same SimpleCache instance (not just the same folder) work for concurrent read and write access?

I don't think two cache instances work properly for concurrent read/write in the first place. I don't think the read instance will see anything that's newly cached by the write instance. Perhaps you're aware of this, but it seems to defeat the purpose of downloading and playback occurring concurrently.

A single instance will work correctly for concurrent read/write, although there is locking at the file level. This means that if a file is currently being written, it cannot be simultaneously read. By default the reading side will behave as though a cache miss occurred (i.e. nothing bad will happen). If you're downloading non-fragmented media streams (i.e. the media stream is a single large file) then consider setting `maxCacheFileSize` on the `CacheDataSource` instances (see [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheDataSource.html#CacheDataSource-com.google.android.exoplayer2.upstream.cache.Cache-com.google.android.exoplayer2.upstream.DataSource-int-long-)). The value you choose is a trade-off (smaller allows more concurrency, but incurs more overhead because the cache needs to track each file individually). Consider choosing a value that will cause segmentation into ~10s segments.

**Comment by ojw28** [comment]
You may also want to look at `CacheDataSource.FLAG_BLOCK_ON_CACHE`, which can be used to get blocking behavior rather than ignoring the cache in the case that the part of the media being read is locked.
