### ISSUE TITLE
Correct GetDuration/Seeking for VBR Mp3 files without seek headers (XING/VBRI).

### ISSUE THREAD

**Issue by axet** [google/ExoPlayer#4071]
Hello!

ExoPlayer 2.7.2

With following file, ExoPlayer detect current playing position (getCurrentPosition()) incorrectly for about 2 times. As result it create silence about track length and does not triggers end of playing event (nor onPlayerStateChanged or onPlayerError).

Track length is 10:04, after about 6:23 it starts playing silence. If I move current position by calling seekTo() works fine, and seems understand correct file length. Problem occures only if playing from begining of the file. VLC goes crazy for this file (whole audiobook), but does not create silence with this file, and detect length correctly 5:07

https://drive.google.com/open?id=1iEIR0PMkNhgoCFuqPmUAgI2xYAww1rvm

**Comment by ojw28** [comment]
I suspect the media is bad -> @botaydotcom to take a look, since this is likely under extractors.

**Comment by botaydotcom** [comment]
In this case, the media just doesn't have the correct headers (Xing/VBRI) to construct a correct seek map. ExoPlayer then assumes that the media file has constant bit rate, and falls back to use `ConstantBitrateSeeker`. However, in this case, this assumption is not correct (the file has variable bit-rate - VBR - frames), so the estimated duration (10:04) from ExoPlayer is wrong. The real duration of the file is 05:04.

Therefore:
- The reason ExoPlayer plays silently after 05:04 is because the file actually ends there. The displayed duration (10:04) is incorrect.
- Given the previous point, the reason ExoPlayer can still play the media when you attempt to seek to a position even after 05:04, is because it actually interpolates an incorrect position from the media, and plays from an incorrect position. For example: when you try to seek to and play from 07:00, what actually happens is ExoPlayer will start play from ~03:30 instead (even though the UI shows 07:00).

These issues (incorrect duration & incorrect seek position for VBR Mp3 without seek headers) are all known issues. Unfortunately these are not trivial issues and we won't be able to provide a solution soon (to solve this, it may require ExoPlayer to read through the whole file and build up a seek index). This is something we have thought about, but it is at a low priority, because the number of media like this is quite small. We can't provide any estimated time frame when such feature maybe implemented unfortunately.
