### ISSUE TITLE
Subtitle of a dash stream not shown properly

### ISSUE THREAD

**Issue by griygagns** [google/ExoPlayer#4083]
### Issue description
I have a live dash stream with multiple subtitle tracks. While they can be correctly recognized as TTML, nothing is shown during playback. Also, it is worth noting that shaka player is able to display them properly. 

I wonder if it is a bug of exoplayer or something else currently not supported by exoplayer. 

### Reproduction steps
Sent to dev.exoplayer@gmail.com

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
dev-v2-r.2.7.3

### Device(s) and version(s) of Android being used
NA

### A full bug report captured from the device
NA

**Comment by ojw28** [comment]
It appears that `track_ID` is set incorrectly in the subtitle track initialization segments. The `track_ID` in `moov -> trak -> tkhd` (in the initialization segments) and `moof -> traf -> tfhd` (in the media segments) should match, however are `0` and `1` respectively.

Note also that `0` is an invalid value. As per 14496-12:

> track_ID is an integer that uniquely identifies this track over the entire life-time of this presentation. **Track IDs are never re-used and cannot be zero**.

So I think your packager is probably forgetting to set `track_ID` to `1` when it generates the initialization segments?

It's likely some other DASH players ignore `track_ID` when extracting FMP4, since you'd only expect 1 track per stream for DASH playbacks. In this case playback will succeed. ExoPlayer doesn't do this because we also support multiple track FMP4 playback (not in the context of DASH), for which track ids are obviously important.

The correct fix for this is to fix the content. Please let me know if you disagree with this analysis. Thanks!

**Comment by griygagns** [comment]
Thank you for your detailed analysis. I wrongly guessed that it may be a problem of exoplayer, when I found that shaka player works fine with those subtitle tracks. Anyway, it would be better to close this issue, 
which seems to be not related to exoplayer. Thanks again.

**Comment by tonihei** [comment]
Just to let you know: We pushed a workaround for this issue to ignore the track ids if there is only one track.
