### ISSUE TITLE
Audio goes in background when the exoplayer view is closed.

### ISSUE THREAD

**Issue by aldocano** [google/ExoPlayer#4099]
I am playing a list of videos in exoplayer and when i close the view the playlist audio still plays until the whole playlist is finished. The problem doesnt happen when i only play a single video.

What i have tried  till now is 

                player.setPlayWhenReady(false);
                player.stop();
                player.seekTo(0);
                player.release();

**Comment by aldocano** [comment]
Nevermind i solved it by adding 

                player.clearVideoSurface();

Thank you.

**Comment by aldocano** [comment]
Still the issue exists i was wrong, when i tried in another device.

**Comment by erdemguven** [comment]
Could you try the same playlist with the latest version of ExoPlayer Demo app, on different devices and let us know the result.

**Comment by ojw28** [comment]
In past cases where people have reported similar issues, it's transpired they actually had multiple player instances at once, and were either releasing the wrong one or incorrectly playing the content using multiple instances.

So it seems most likely this is an application issue, rather than an ExoPlayer bug. I'd suggest debugging your app with the above in mind. If you've ruled out these possibilities and still have the issue, please reply here providing clear and concrete steps that will allow us to reproduce the issue. Until then, I'll close this. Thanks!
