### ISSUE TITLE
ExoPlayer 2.7.0 doesnt allow volume change on surround playback source

### ISSUE THREAD

**Issue by nenjack** [google/ExoPlayer#4111]
### Issue description
ExoPlayer 2.7.0 doesnt allow volume change on surround playback source

### Reproduction steps
1. Download Demo App
2. Replace `media.exolist.json` contents with
```
[
  {
    "name": "prozi test",
    "samples": [
      {
        "name": "prozi test dolby 4k",
        "uri": "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4",
        "extension": "mp4"
      }
    ]
  }
]
```

### Link to test content
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
Xiaomi MiBox - Android v.6.0.1
NVidia Shield - Android v.7.0

### A full bug report captured from the device
There is no crash or other stuff like that
If you change the audio source to 2 channel it works but it is still a big issue that I cant control the volume on surround sound :(
[report.txt](https://github.com/google/ExoPlayer/files/1898655/report.txt)

**Comment by zsmatyas** [comment]
Did this work with any other exoplayer versions?

I would expect any encoded content not having the notion of volume unless it is decoded. So for example, if you play Dolby audio, your device is set to pass-through and the sink is decoding it only, then you have no way to influence the volume on the device. Only the sink is interpreting the audio data.

There are a few platforms that can decode, change the volume and re-encode to the selected format, but these devices usually have a setting for picking the output format and it will be forced for any content. So they can decode any kind of content and re-encode it to match your sink's expected input. But it is rare, as far as I know, just a few device types have various audio encoders available.

So I would think this issue is not ExoPlayer, but platform dependent.

**Comment by andrewlewis** [comment]
Closing on the assumption this is using passthrough, given the logging from `AudioSPDIF` in the provided bug report.
