### ISSUE TITLE
IMA Extension Memory Leak

### ISSUE THREAD

**Issue by MajDroid** [google/ExoPlayer#4114]
### Issue description
Using IMA Extension and in the sample main demo app, a memory leak happens when you serve a VMAP and quit the player activity during content playback and after ad/pods playback.

In my opinion, it's an IMA problem and managed to reproduce the issue even without an IMA Extension and following exactly their integration guide but according to them they're claiming it's an IMA-Extension problem and not theirs
https://groups.google.com/forum/#!topic/ima-sdk/ZM-WsPL1xdQ

### Reproduction steps
- In the Main Demo app, use any video and set the following sample adtag uri:
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=
- When pre-roll finishes and content video plays for few seconds, press back to return to the home screen, PlayerActivity gets leaked

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

### Version of ExoPlayer being used
V2.7.3

### Device(s) and version(s) of Android being used
Tested on Pixel XL (Oreo 8.1), Xperia XZ (Oreo 8.0) but can be reproduced on any device

**Comment by andrewlewis** [comment]
I'd expect the ads loader to be destroyed and free all its resources when the player activity is destroyed, but not when it's just backgrounded. We need to keep state for the IMA SDK in memory while in the background so that it's possible to resume ad playback. Are you seeing that IMA objects have leaked after the player activity's `onDestroy` lifecycle method has been called?

I understand that you're not using the ExoPlayer IMA extension in your app, but this is just a way to reproduce the issue. Are you seeing that objects have leaked after calling `AdsManager.destroy` in your own integration?

Maybe related: we have seen an issue where IMA leaks its `WebView` when playing an expired ad tag even if the ads manager is destroyed [internal reference: b/64388488]. But if your ad tag hasn't expired this shouldn't apply.

**Comment by MajDroid** [comment]
The issue is easily reproducible in the [main demo sample app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) which uses IMA Extension; PlayerActivity leaks and remains in memory once you serve an ad as explained in my original post.

However, the good news is that it seems an IMA issue and not IMA-extension, you can find a response from IMA team confirming it:
https://groups.google.com/d/msg/ima-sdk/ZM-WsPL1xdQ/by98SaAcBAAJ

**Comment by andrewlewis** [comment]
[Internal reference: b/77574091]
