### ISSUE TITLE
Do not work on Meizu(Android 7.1),the log info is shown below

### ISSUE THREAD

**Issue by onecoders** [google/ExoPlayer#4127]
Do not work on Meizu(Android 7.1),the log info is shown below
![99e227075ff366b7da1bdda15934cc43](https://user-images.githubusercontent.com/3477738/38798454-3c96e168-4194-11e8-8d03-bdc8b8c52b37.png)

**Comment by botaydotcom** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by botaydotcom** [comment]
Another thing is this seems highly likely that this issue is a device specific one. It would be more appropriately reported to the device manufacturer than to ExoPlayer. Thank you very much.
