### ISSUE TITLE
How to a delete a offline license ? 

### ISSUE THREAD

**Issue by Airforce327** [google/ExoPlayer#4129]
I use OfflineLicenseHelper to download the offline license, I store the offlineKeySetId in a local file . it works fine.  Now i want to delete the offline video  , I delete my local file which stores the keySetId.   Should  I have to do anything else to remove the license ?   And how can I do it ?

**Comment by ojw28** [comment]
It depends a bit on your security requirements and license policies. Deleting your local file doesn't remove the underlying license, so if someone had somehow gotten hold of the keySetId, they could still use it to access the license. It also doesn't communicate to your server that the offline license is no longer held, which may be required if you're trying to enforce policies such as "content can only be downloaded on N devices at a time".

To remove the license properly, you can pass the keySetId to `OfflineLicenseHelper.releaseLicense`. If I remember correctly (and you should probably validate behavior is really as described, because I'm going by memory):

* That call should immediately render the license unusable.
* The call will also notify the license server that the license is no longer held. The call fail (throw an exception) if this is not possible (e.g. due to lack of network connectivity). The license will be unusable either way.
* If notifying the license server that the license is no longer being held is important to your use case, and if the call fails, then you can keep the keySetId and implement some retry logic for calling `releaseLicense` until it succeeds.
