### ISSUE TITLE
Monitor playback duration

### ISSUE THREAD

**Issue by VadimWelldone** [google/ExoPlayer#415]
Hi, guys!

Is there some functionality to monitor playback duration? For example, callback method that will be fired up each second of playback. 

Thanks in advance,
Vadim

**Comment by andreimarinescu** [comment]
I haven't found one. My approach is to have a timer and call getCurrentPosition() each second on the player instance, just as I did with MediaPlayer.

**Comment by ojw28** [comment]
Yeah, you should call getCurrentPosition() when you need the position. If you need it periodically then call it periodically.

It's better to have the application code control this kind of thing, rather than the player, because the application code knows what it actually needs the position for / how frequently it needs it / when it no longer needs it etc.

**Comment by VadimWelldone** [comment]
Thanks a lot, guys.
