### ISSUE TITLE
Live video is getting struck in the middle

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#4154]
Hello,

   While I am playing video it is showing below errors. Could you please help me out. I am trying to play hls stream using exoplayer in android mobile.

# **E/ACodec: cannot find aac bit rate
Surface: getSlotFromBufferLocked: unknown buffer: 0x7f2804ffa0**

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
