### ISSUE TITLE
Surface Texture Size different than expected.

### ISSUE THREAD

**Issue by cool-benson** [google/ExoPlayer#4171]
First of all, big thumbs up for ExoPlayer. It's really easy to fiddle with when you consider the things need to be done. 
Here goes the problem. I'm playing DASH video(with multiple resolutions)  with ExoPlayer into video surface(GL_TEXTURE_EXTERNAL_OES), then used for OpenGL draws. And I assume, I can use one SurfaceTexture to hold different resolution(i.e. Only call `surfaceTexture.setDefaultBufferSize()` once with the largest resolution). And what happened is the texture I got in the largest resolution is correct, but the texture for the lowest resolution was wrong. I'm expecting `1080x540`, but what I got was `1088x544`, from GAPID I found that the pixel was copied. I'm not sure if this is a bug or I'm doing it wrong. And I've tested on two different Android phones, with different vendor, and android version, the behavior is completely the same. 
![bug](https://user-images.githubusercontent.com/11672970/39155560-5c2e5254-4707-11e8-9741-8783ad5a7879.PNG)
 Any pointer will be appreciated.

Version: 1c6149b4d Merge pull request #4054 from google/dev-v2-r2.7.2

**Comment by ojw28** [comment]
It's probably relevant that video decoders typically operate using output buffers that are a whole number of blocks (vertically and horizontally). I'm guessing that in this case the block size is 16, which would explain why 1080x540 is rounded up to 1088x544. The decoder will also output cropping information that tells you how to crop the buffer back to the proper video resolution.

If you look in `MediaCodecVideoRenderer.onOutputFormatChanged`, you can see where this cropping information arrives back from the decoder in ExoPlayer. I think this cropping information also gets sent to the `SurfaceTexture` as buffers are released. I'm not 100% certain, but I believe the way you obtain the cropping information for the current frame is to call `SurfaceTexture.getTransformMatrix`. Your bug is likely that you do not apply this transform matrix when rendering, when you should be doing so.

As an aside, I don't think you ever need to call `SurfaceTexture.setDefaultBufferSize`.

**Comment by cool-benson** [comment]
Yes, I believe you're right, I've changed my video size to power of 2(i.e. 1024*512), and the problem is solved. I'll definitely apply `SurfaceTexture.getTransformMatrix` just in case. Thanks!

**Comment by ojw28** [comment]
Just in case it's not clear (I'm pretty sure it is; but no harm in making sure): You can use any video size. You just need to apply the transform matrix to crop away any padding that was added to get the buffer up to being a whole number of blocks.
