### ISSUE TITLE
Solve track selection for downloads/offline

### ISSUE THREAD

**Issue by starchey** [google/ExoPlayer#4177]
Following steps outlined in the blog post here, https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95, we're successfully downloading and playing downloaded HLS streams in our app. We want to offer users download quality preferences, and based on this select the appropriate streams to download. Using HlsDownloadAction, is it possible to set a minimum BPS and have the DownloadService only download a single variant >= to this BPS (or something similar to accomplish this)?

**Comment by ojw28** [comment]
When creating the `HlsDownloadAction` you can specify the renditions that you want to be downloaded (the varargs argument at the end of the constructor). Although this is quite complicated, since you need to (a) know what the renditions are, and (b) implement logic for choosing which ones you want.

(a) can be solved by instantiating a `HlsDownloader` directly from app code, and calling `getManifest` and `getAllRepresentationKeys` on it. If you just want to select by bitrate then you can probably do (b) pretty easily. You can then build a `HlsDownloadAction` containing the representation(s) you want to send to the service.

Obviously this approach isn't ideal. Doing (a) is annoying, but kind of necessary in the general case because some apps may want to show UI to the user to let them choose from an actual variant list. Doing (b) properly is a more problematic, since doing it properly normally requires taking into account things like device capabilities. This is (mostly) solved for the streaming case, through `DefaultTrackSelector`/`RendererCapabilities`.

I think what we need to do here is probably:

* Make (a) much easier.
* Solve (b) by allowing offline track selections to use `TrackSelector` implementations, or if that's not possible, something provided by the library that's just as good.

Does that sound right?

Aside: You'd probably rather skip (a) entirely for your case, but from my point of view I think it would be preferable for us not to have to maintain multiple code paths :).

**Comment by starchey** [comment]
Yeah, that sounds right. Thanks for the thorough response.

**Comment by ojw28** [comment]
The `dev-v2` branch has `DownloadHelper`, which enables use of `DefaultTrackSelector` for offline track selections and solves this problem. This will be part of `2.10`.
