### ISSUE TITLE
MediaCodec_looper(1454) SIGSEGV(SEGV_ACCERR)  Crash in Android 5.1

### ISSUE THREAD

**Issue by 82367825** [google/ExoPlayer#4183]
### Crash Report

```
MediaCodec_looper(1454)
SIGSEGV(SEGV_ACCERR)

1 #00 pc 000146a0 /system/lib/libc.so (strlen+43) [armeabi-v7a]
--
2 #01 pc 0000d64d /system/lib/libstagefright_foundation.so (android::AMessage::setString(char const*, char const*, int)+30) [armeabi-v7a]
3 #02 pc 00094a1d /system/lib/libstagefright.so (android::ACodec::getPortFormat(unsigned int, android::sp<android::AMessage>&)+4060) [armeabi-v7a]
```

### Issue description
Sometimes i using it to play audio in Android 5.1, there will be a crash.

My model is Meizu note3, and android version is 5.1.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
