### ISSUE TITLE
HLS - Play successfully but frozen when press forward button in demo

### ISSUE THREAD

**Issue by dannyZhou** [google/ExoPlayer#4184]
### Issue description
Play successfully when start from 00:00,
but when I press forward button, frozen occurred.

### Reproduction steps
1. Clone project.
2. Change branch to `dev-v2`.
3. Import project to Android Studio.
4. add these codes to `media.exolist.json`.
```json
      {
        "name": "HLS Test",
        "uri": "http://192.168.2.109/video.m3u8"
      }
```
5. Connect phone and run demo project.
6. Play demo, waiting play successfully and press forward button. 
7. Frozen will occurred.

### Link to test content
https://drive.google.com/file/d/1X8mlM_uccEHJJPAF235xQSYIsgb3KYSA/view?usp=sharing

### Version of ExoPlayer being used
d4eb2e5b8571f57169126a155c98af775f14b4ad

### Device(s) and version(s) of Android being used
Test Device: 
- Mobile Version: Mi-4c 
- MIUI Version: MIUI 9 8.4.12 development version
- Android Version: 7.0

**Comment by AquilesCanta** [comment]
The issue here is that only the first segment contains an IDR frame. You should fix the content by including an IDR frame at the start of each segment, as requested by the [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23):

> `any Media Segment containing H.264 video SHOULD contain an IDR`

You can also work around this by creating your own HLS Extractor factory and passing in FLAG_ALLOW_NON_IDR_KEYFRAMES.
