### ISSUE TITLE
How does Exo calculate the live edge?

### ISSUE THREAD

**Issue by chrisfillmore** [google/ExoPlayer#4202]
I'm troubleshooting an issue with a live stream which doesn't play in Shaka player. See https://github.com/google/shaka-player/issues/1430 for analysis.

This manifest:
https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(ECTV-2819.dfw.480.mobile)/manifest.mpd

plays in Exo, but not in Shaka. It also doesn't play on Roku.

On inspection, it appears that the segments described in the manifest are 3 weeks ahead of the live edge. I'm not familiar with Exo's logic for calculating live edge. In particular, I'm not sure what this check means in `DefaultDashChunkSource#getNextChunk`:

```
if (availableSegmentCount == DashSegmentIndex.INDEX_UNBOUNDED) {
```

In what circumstances would this be true? I'm not sure what this condition implies. I'm told by a colleague that Exo ignores device time for `SegmentTimeline`. Does this mean that Exo will calculate the live edge based on the end time of the last available segment?

Thank you for any help!

**Comment by linhai326** [comment]
According to document, if neither SegmentTimeline nor period duration is available, it will be true:

"
  /**
   * Returns the number of segments in the index, or {@link #INDEX_UNBOUNDED}.
   * <p>
   * An unbounded index occurs if a dynamic manifest uses SegmentTemplate elements without a
   * SegmentTimeline element, and if the period duration is not yet known. In this case the caller
   * must manually determine the window of currently available segments.
   *
   * @param periodDurationUs The duration of the enclosing period in microseconds, or
   *     {@link C#TIME_UNSET} if the period's duration is not yet known.
   * @return The number of segments in the index, or {@link #INDEX_UNBOUNDED}.
   */
  int getSegmentCount(long periodDurationUs);
"

**Comment by linhai326** [comment]
btw, your manifest link seems not working: i got 404 error.

**Comment by chrisfillmore** [comment]
The stream was restarted, and works now in both players.

Thanks for pointing out the documentation -- I hadn't seen that.

**Comment by ojw28** [comment]
In this case I'm pretty sure we just look at what media is actually there (i.e. declared in the timeline) and then start playback from the end (minus the amount we want to be able to buffer).

We only rely on knowing the current time for cases where it's necessary to do so. IIRC this can be necessary when SegmentTemplate is used instead of SegmentTimeline. Even in this case, we'll use a UTCTiming element rather than the device clock, if one is included in the manifest. Which it really should be in this case, since there's no guarantee that a device clock will be set correctly.

**Comment by chrisfillmore** [comment]
@ojw28 Thanks for the info :)
