### ISSUE TITLE
RemoveListener does not work sometimes

### ISSUE THREAD

**Issue by brunolens34** [google/ExoPlayer#4210]
-----------------------
### Issue description
We have reconnect function in our app, it means when the streamServer is invalid, it goes to next playback url.
We detect on  **onPlayerError(ExoPlaybackException error)**  whether streamServer is alive, or NOT.
Before going to next playback url, we release the player surely.
        

if (player != null) {
            player.removeListener(playerEventListener);
            player.stop();

            player.release();
            player = null;
 }
While it is on reconnecting status ( checking the next playback urls one by one), we click the back button on android.
Then the app releases the player.
But sometimes it is NOT releasing the player correctly, it seems the app is receiving the onPlayerError notification.
So in this case, we can hear the audio though we are not on player screen.
I think this is because of removeListener is not working sometimes.

### Reproduction steps
1. you play something, and stop the stream server
2. app should go to next play back url.
3. you close the player screen. 
4. Sometimes you can hear the audio, it means player is not released correctly.

### Version of ExoPlayer being used
exoplayer 2.7.3

### Device(s) and version(s) of Android being used
android TV 6.0 (mibox)

**Comment by ojw28** [comment]
It's very hard to see how a [one line method](https://github.com/google/ExoPlayer/blob/r2.7.3/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L149) could be broken. I think it's more likely that something else is going on, and that this is a bug in your application code.

If you discover something concrete that indicates otherwise, please reply here with proper concrete reproduction steps (i.e. good enough that someone with no knowledge of your specific application could follow them and reproduce the issue).
