### ISSUE TITLE
Cancel a sent message created by createMessage()

### ISSUE THREAD

**Issue by johndevthings** [google/ExoPlayer#4230]
Hi, how do I cancel a created message. Here is my code to create the message:

    myPlayer.createMessage( new PlayerMessage.Target() { 
    @Override public void handleMessage(int messageType, Object object)
    {
        // do stuff
    }
    }).setPosition(position).send();

I tried looking for something in the documentation without luck.

Thanks for your time.

Edit: I have tried getting a reference to the created message. Then, doing:

    myPlayerMessage.markAsProcessed(true);

That did not help.

**Comment by botaydotcom** [comment]
Hi @johndevthings :
I don't think there's an easy way (if any way) to remove the message. @tonihei maybe able to answer that better.
AFAIK, `myPlayerMessage.markAsProcessed();` is not designed for this purpose. It is to be called by the message `Sender` (in most cases, the internal player), rather than application code.

A way to workaround this, if the message you send is a customer message and you control the handler (the `PlayerMessage.Target`), is to add a filter flag as a field of the message payload. You can change the flag yourself if you want to cancel the message. Then the handler can check the flag and decide whether to handle the message, or just ignore it.

**Comment by johndevthings** [comment]
So, you mean I should go ahead and do setPlayload(STATICVALUE).send(). I was hoping I would not have to do that. I really appreciate the information, though.

**Comment by botaydotcom** [comment]
Yeah, that's the only solution I can come up with for now. Maybe we should add an API for making this task easier. Over to @tonihei to see if that's something we should do in a future release.

**Comment by tonihei** [comment]
Indeed, we currently don't have method to cancel a message once sent. 
However, this is easy to implement and I'll mark it as an enhancement for one of our next releases.

In the meantime, you can easily implement a similar solution (as @botaydotcom already pointed out) by checking whether a boolean variable in your message handler is still true. And then you can set it to false to 'cancel' the message.
