### ISSUE TITLE
Dismiss/Pause notification when the track has ended

### ISSUE THREAD

**Issue by skyler-b** [google/ExoPlayer#4238]
### Issue description
I am displaying a notification for my player when the app is backgrounded. When the video ends, the state of the notification does not update (apart from the counter ending). 

For my use case, I'd like to just cancel the notification, but I could also see a case for leaving it, but moving it to a 'paused' state (enabling the play button, instead of pause).

I attempted to cancel the notification myself:
In my own `onPlayerStateChanged` when state reaches `STATE_ENDED` I tried calling `playerNotificationManager?.setPlayer(null)`, however when `PlayerNotificationManager`s internal listener runs, I get a crash:

```
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.android.exoplayer2.Player.isPlayingAd()' on a null object reference
        at com.google.android.exoplayer2.ui.PlayerNotificationManager.createNotification(PlayerNotificationManager.java:802)
        at com.google.android.exoplayer2.ui.PlayerNotificationManager.updateNotification(PlayerNotificationManager.java:703)
        at com.google.android.exoplayer2.ui.PlayerNotificationManager.startOrUpdateNotification(PlayerNotificationManager.java:709)
        at com.google.android.exoplayer2.ui.PlayerNotificationManager.access$900(PlayerNotificationManager.java:94)
        at com.google.android.exoplayer2.ui.PlayerNotificationManager$PlayerListener.onPlayerStateChanged(PlayerNotificationManager.java:942)
```
I believe that this exception is a race condition wherein my setting the player to null in my callback (which in turn removes the internal player listener), is happening at the same time that PlayerNotificationManager's listener is executing.

For now my workaround is to delay my cancelation:
```kotlin
override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
    if (playbackState == Player.STATE_ENDED) {
        Handler().postDelayed({
            playerNotificationManager?.setPlayer(null)
        }, 1000)
    }
}
```

### Reproduction steps
Demo apps are not using the PlayerNotificationManager.

### Link to test content
N/A

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Emulator, 100% reproducible

**Comment by ojw28** [comment]
I think that your solution of posting the call to `setPlayer(null)` will work reliably without the 1000ms delay. Just posting with zero delay should be sufficient. This is because I don't think it's really a race condition as such. I think everything is on a single thread, that it's just an ordering problem, and that posting the call will get the operations into the correct order.

In terms of making it so that posting the call isn't necessary, we could probably add checks for `player == null` in `PlayerNotificationManager.PlayerListener`. It's likely we need to do the same thing in `MediaSessionConnector` as well.

Longer term, this issue could be avoided by having the player pass itself to all listener methods, so `PlayerNotificationManager` could use the passed instance rather than relying on its own player reference.

Marking this as a bug, probably to add the null checks, however I think it should be pretty straightforward for you to work around the issue, as described above.

**Comment by skyler-b** [comment]
You're right, simply `post()`ing it works too, as you said, it must just be the order that the listeners are executed in.
