### ISSUE TITLE
Playing locally stored MPEG-CENC encrypted mp4 file

### ISSUE THREAD

**Issue by rd7773** [google/ExoPlayer#4250]
Is it possible to play MPEG-CENC encrypted mp4 files that are locally stored by initialising player with actual decryption key, instead of drm url and key-id. We intent to encrypt our content on our own without any DRM and then do its playback by giving the actual decryption key to the player.

**Comment by AquilesCanta** [comment]
I think the closest scheme we support is _Clear key_. It is worth noting that this has API level restrictions. We do not have support for in-library subsample decryption though, and it is currently not in our roadmap. You could try implementing your own renderer (potentially wrapping the existing ones) that decrypts samples before committing for decoding.

**Comment by AquilesCanta** [comment]
Relevant: #378.

**Comment by rd7773** [comment]
@AquilesCanta ok actually i used ffmpeg to encrypt the video with cenc-aes-ctr encryption scheme which encrypts samples in between not the whole file and writes the iv to senc box of mp4. What i would need to do is **parse the mp4, extract the iv and decrypt the individual samples** as not the whole file is encrypted. It would be helpful if you could suggest how to do that in Exoplayer if it supports such thing.

**Comment by AquilesCanta** [comment]
I have to warn you this might be a challenging task.

The container part is already supported. Although you might need to tweak a few parts, for example to add a protection scheme 4CC. Otherwise, the samples should be output correctly with their own encryption data. There should not be that much work required on the decryption data extraction side. However, it would be a bad idea to decrypt the samples on the playback thread (that is, the thread on which Renderers run on), so you might consider doing it on extraction as well: All data required is available as a prefix of the sample data (initialization vector and subsample encryption data, if any) and as part of the sample metadata (see CryptoMode). In your case, the key probably needs hardcoding for an initial version.

**Comment by sarabjit-rupaal** [comment]
Surely [Exoplayer Supported formats](https://google.github.io/ExoPlayer/supported-formats.html) include support for standalone MP4 files.
Also, Exoplayer supports CENC scheme from API 19+.

What are the possibilities for achieving playback of CENC encrypted mp4 files?

If not CENC, does Exoplayer support playback of any other type of content Encryption for mp4 files ?

**Comment by AquilesCanta** [comment]
> What are the possibilities for achieving playback of CENC encrypted mp4 files?

If you are using a platform CDM, e.g. widevine, then not much is required. But you'll need to find out how to serve licenses.

> If not CENC, does Exoplayer support playback of any other type of content Encryption for mp4 files ?

You could use full-file AES encryption (this is used by HLS, for instance). The relevant class here is Aes128DataSource. I am not sure whether you might run into issues with seeking.

Keep in mind that application-level DRM implementations will most likely not be as secure as platform supported ones.
