### ISSUE TITLE
Not able to clear notification while playback is paused for audio playback.

### ISSUE THREAD

**Issue by tuhin10** [google/ExoPlayer#4256]
### Issue description
Not able to clear notification while playback is paused for audio playback. Even setting the  playerNotificationManager.setOngoing(false); is also not working.

### Reproduction steps
Use the audio app
https://github.com/google/ExoPlayer/tree/io18

### Link to test content
https://github.com/google/ExoPlayer/tree/io18

### Version of ExoPlayer being used
v2.8.0

### Device(s) and version(s) of Android being used
Name: Google_Pixel  
API level 27

### A full bug report captured from the device
NA

**Comment by marcbaechinger** [comment]
The sample audio app deploys a stop button to remove the notification. This is a simpler approach than the one you want to do.

The reason for which you can't remove the notification is because it is attached to the service which runs in foreground. If you want to achieve the behaviour you are describing you need to do the following:

1. Add a listener to the player instance in your service.
2. Listen in the onPlayerStateChanged callback of the listener. When the playWhenReady flag is set to false you need to call [stopForeground(false)](https://developer.android.com/reference/android/app/Service#stopforeground) method. 
3. Conversely, when the player starts playing again (playWhenReady=true) you need to call startForeground again to make sure the system won't kill the service.

We are considering to add this functionality to the sample app.

**Comment by tuhin10** [comment]
Thanks @marcbaechinger. My bad, did not realized that its working fine now.

**Comment by DKillWorld** [comment]
Then, If we pause playback for some minutes with stopforeground(false) in event listener, then our service is killable by system till we again start playback and startforeground is triggered back? Correct me if I am wrong.

**Comment by DKillWorld** [comment]
Off topic Tip- The notification returns back automatically after few mins when the app is cleared from memory.
Probably because we return Start_sticky in onstartcommand. Just replace it with Start_non_sticky and it will not returnback.

**Comment by ojw28** [comment]
It sounds like this issue was resolved. I don't think we need issues to track modifications to the IO demo apps, although feel free to modify them to do this if you like :).
