### ISSUE TITLE
LoopingMediaSource cause rebuffering everytime

### ISSUE THREAD

**Issue by xiaopao2014** [google/ExoPlayer#4286]
### Issue description
In some case ,we want to play video looply.
When we use MediaPlayer , it's easy by "setLooping(isLooping)"
As i know, in EXOPlayer, we could use LoopingMediaSource or setRepeatMode.
But we found a problem that it will cause the video rebuffering when it play looply.
Is there any way that we could play a video looply without rebuffering.
Thanks for yout help.

### Reproduction steps
        if (isLooping) {
            mediaSource = new LoopingMediaSource(new ExtractorMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(uris, mediaHandler, eventLogger));
        } else {
            mediaSource = new ExtractorMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(uris, mediaHandler, eventLogger);
        }

### Version of ExoPlayer being used
 2.7.3

**Comment by tonihei** [comment]
Could you please provide example media such that we can reproduce the problem?

**Comment by xiaopao2014** [comment]
http://res.mrsphone.com/video/2018/04/28/r_2576788/1/av_2576788_01.mp4
we use mp4 video file.

**Comment by tonihei** [comment]
The file loops perfectly fine for me in our demo app. Both with the repeat mode and the LoopingMediaSource. 

I added 
```
{
  "name": "Tetst",
  "uri": "http://res.mrsphone.com/video/2018/04/28/r_2576788/1/av_2576788_01.mp4"
},
```
to `media.exolist.json` and set `player.setRepeatMode(Player.REPEAT_MODE_ONE)` in `PlayerActivity.java`. 

Can you try to reproduce the issue in our demo app and tell us what else you changed to see if there is another reason for the buffering?

**Comment by xiaopao2014** [comment]
Um, there must be some misunderstanding. By my side, both repeat mode and LoopingMediaSource could loop play that video. But as we check the http reqeust by fiddler or charles tool, we could found that when exoplayer loop play, it would request the video url everytime.
On the other side, we check the Media Player , it works fine, even if we loop play ,it just request that video url for one time.
So, is there any magic way could do that in exoplayer ? ^^

**Comment by xiaopao2014** [comment]
![5227f943-3442-49ce-9de1-9223b9a42fa6](https://user-images.githubusercontent.com/7996455/40414008-ccec6314-5ea9-11e8-9e49-ad0c44024a30.JPG)

This is the fiddler history. We have test that in ExoPlay Demo , it works the same

**Comment by tonihei** [comment]
Yes, that's correct. We reload the media when looping. The reason is that we keep only a certain amount of media in the buffer and delete the buffer behind the playing position. So at the time we reach the end of the video, we need to load the video again. Note that this may not be necessary for such a short video as in your example, but it's needed for longer videos to prevent excessive memory usage.

To prevent this, you could use a [`CacheDataSourceFactory`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheDataSourceFactory.html) to wrap your existing `mediaDataSourceFactory`. This allows you to save the loaded media to disk and use the cache when looping the same file again.

**Comment by xiaopao2014** [comment]
Yes, using cache almost fits that.Thanks!
