### ISSUE TITLE
DashMediaSource.Factory  setMinLoadableRetryCount  - Unexpected results

### ISSUE THREAD

**Issue by 0c6a183d** [google/ExoPlayer#4322]
Hello.

When using the setMinLoadableRetryCount, I have noticed the following two behaviors and wanted to check if it was java or Exoplayer design or bugs.

1. When setting setMinLoadableRetryCount value 0 has no effect - the TCP connection is always retried twice - in effect, an 8000ms connect timeout (connectTimeoutMillis) always takes 16000ms to throw the exoplayer timeout source_error.

2. As each TCP connection is retired, the TCP timeout increments by 1 second until 13 is reached which makes  the value in connectTimeoutMillis incorrect.

For example: setMinLoadableRetryCount(10) with connectTimeoutMillis:8000 takes ~122 seconds to timeout in Exoplayer, not ~88 as I would expect.

I have captured the below packets on a firewall and viewed in wireshark, as you can see only the value of 1 and higher seem to have any effect and my connectTimeoutMillis:8000 creeps towards 13000 with each new packet....
setMinLoadableRetryCount(0)   =  2 TCP tries + 3 TCP-Retransmissions  (Initial connect try)
setMinLoadableRetryCount(1)   =  2 TCP tries + 3 TCP-Retransmissions  (Retry ~9 seconds later)
setMinLoadableRetryCount(2)   =  3 TCP tries + 3 TCP-Retransmissions  (Retry ~10 seconds later)
setMinLoadableRetryCount(3)   =  4 TCP tries + 3 TCP-Retransmissions  (Retry ~11 seconds later)
setMinLoadableRetryCount(4)   =  5 TCP tries + 3 TCP-Retransmissions  (Retry ~12 seconds later)
setMinLoadableRetryCount(5)   =  6 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)
setMinLoadableRetryCount(6)   =  7 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)
setMinLoadableRetryCount(7)   =  8 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)
setMinLoadableRetryCount(8)   =  9 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)
setMinLoadableRetryCount(9)   =  10 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)
setMinLoadableRetryCount(10)  = 11 TCP tries + 3 TCP-Retransmissions  (Retry ~13 seconds later)

This is an audio only stream so buffering for 45-90 seconds while driving through a network black spot I  feel is acceptable hence the testing of high values...

Thanks for your help.

**Comment by botaydotcom** [comment]
Hi @0c6a183d,
I think in our retry logic, we have a back-off timeout in milliseconds before retrying, which is calculated as:
```
 delayBeforeRetry = min((errorCount - 1) * 1000, 5000)
```
Add 8000 millis from connectTimeoutMillis on top of that and you can arrive at the retry pattern you observed.
I think there is a minor issue with minLoadableRetryCount = 0, which leads to it always retry once. I'm not sure this is something we will need to fix though, and it will be very low priority in our list.

**Comment by 0c6a183d** [comment]
Hi. 

Thanks for the reply and information.

You have stated that there is a bug in minLoadableRetryCount that is effectively _doubling_ the HTTP timeout value set by the developer.

Are you saying it will _not_ be fixed, or that it is a low priority?

Thanks

**Comment by ojw28** [comment]
I think you're conflating a few things together:

* The HTTP timeout. I.e. For a particular connection attempt made by the network stack, how long will it wait before timing out.
* The minimum number of retries. I.e. If the network stack says it's failed to connect, what's the minimum number of times we'll attempt to retry.
* Back-off between retry attempts.

All three of these affect the total time that will elapse before a playback fails in the case that every HTTP connection attempt times out, so just setting the timeout to a particular value does not guarantee that's the time that will elapse before failure.

The mentioned "bug" is not related to the HTTP timeout value not working correctly. The bug is specifically about minLoadableRetryCount. In particular, if set to 0 then we'll always retry at least once, rather than 0 times. This is a low priority issue because (a) setting minLoadableRetryCount to 0 isn't sensible for an app that wants to deliver a robust playback experience, and probably virtually no-one is doing this, and (b) the value is a lower bound; the player is allowed to retry more than the specified number of times without violating the contract of the API.

As an additional point, the underlying network stack may do multiple retries in its own layer if the address being connected to resolves to multiple IP addresses, so even when an app uses `HttpUrlConnection` directly to make any network request, the specified timeout does not guarantee failure after only that period of time.

If you really have a hard limit at which you want the player to give up and fail (which seems strange), then I'd suggest you implement this yourself in the application layer (i.e. post a delayed message to yourself when the player starts buffering, and if it's the player is still buffering when that message is delivered back to you, give up).

**Comment by 0c6a183d** [comment]
@ojw28 - Thank you for your detailed reply. That has clarified things for me plus added some useful tips. Cheers.
