### ISSUE TITLE
Chunk download http 404 after changing video track few times

### ISSUE THREAD

**Issue by dmazar** [google/ExoPlayer#4336]
### Issue description
Playing of live stream with timeShiftBufferDepth of 60 secs fails (chunk download http 404) after changing video track few times. The stream producer uses it's own in-house player and claims that everything is fine with the stream.

I have noticed that hacking the manifest on the ExoPlayer side by changing timeShiftBufferDepth to 30 secs eliminates the issue. I am suspecting that server is publishing chunks which are already destroyed. There is some discrepancy between server and ExoPlayer about chunks being available, but need some expert info on this.

Thanks in advance.

### Reproduction steps
Play stream with ExoPlayer demo app and switch through video tracks several times. Or use seekbar to go back in the given time window.

### Link to test content
Sent by email.

### Version of ExoPlayer being used
2.6.1 and 2.8.1

### Device(s) and version(s) of Android being used
Any

**Comment by tonihei** [comment]
Can you please provide us with example media to reproduce the issue? Or send it to dev.exoplayer@gmail.com with "Isse #4336" in the subject if you don't want to post it publicly.

**Comment by dmazar** [comment]
Email sent.

**Comment by tonihei** [comment]
I can basically confirm what you already said. The chunks at the beginning of the published 60 second window fail to load with HTTP 404 errors. But the chunks closer to the live edge work fine. 

Can you check back with the publisher of the streams? If their in-house player plays fine, it probably only offers 30 seconds of live window or does not support seeking. For example, if they start showing the stream from a default load position closer to the live edge, they'll never encounter the problem you just described.

If you just want to workaround the issue, you can clip the media source to the valid area by using something like this:
```
mediaSource =
    new ClippingMediaSource(
        mediaSource,
        /* startPositionUs= */ 45 * C.MICROS_PER_SECOND,
        /* endPositionUs= */ C.TIME_END_OF_SOURCE,
        /* enableInitialDiscontinuity= */ true,
        /* allowDynamicClippingUpdates= */ true,
        /* relativeToDefaultPosition= */ false);
```
Note that this will only work properly from 2.8.0 onward because ClippingMediaSource didn't support live streams before that.

**Comment by dmazar** [comment]
Thanks for looking into this.

> Can you check back with the publisher of the streams? If their in-house player plays fine, it probably only offers 30 seconds of live window or does not support seeking.

Unfortunately, I do not have access to that in-house player and can not check how it loads segments in Wireshark. We have tried the same stream in Shaka player and it ends up with 404 error also, although it requires much more video track switches until the error.

About seeking: Our app uses ExoPlayer and our overlay controls. We are treating that stream as live stream without time shift in our app UI and seeking is not enabled (only progress bar is shown). Some other streams have time shift with 2 hour window and seeking and track switching works fine for those (or probably fails at the start of the window - did not come to that yet).

I have tried to set the time 1 min back on the phone and I get 404 from the start. Is it true that time difference between the client and the server can cause the issue? Does dash standard specifies some time buffer in which server must keep expired segments to allow for the client/server time difference?

If I will be asked to further check and prove that segments which are published to be available are actually not available, is this formula correct?

`presentation time = availabilityStartTime + (segment number - 1) * segmentDuration - presentationTimeOffset`

And then to require that segments between `presentation time = NOW` and `presentation time = NOW-timeShiftBufferDepth` be available for download?

If those questions are out of your debugging scope, feel free to close the issue/questions.
Thanks for your time.

**Comment by ojw28** [comment]
> I have tried to set the time 1 min back on the phone and I get 404 from the start. Is it true that time difference between the client and the server can cause the issue?

The fact that the stream is relying on the client and server having synchronized clocks is a fundamental problem. The manifest needs to include a `UTCTiming` timing element to allow the client to synchronize with the server's clock, however no such element is present. Alternatively, the manifest should use `SegmentList` instead of `SegmentTemplate`, in which case synchronized clocks aren't required, however this approach is significantly less efficient as it requires the client to frequently reload the manifest as the list of available segments updates.

> If I will be asked to further check and prove that segments which are published to be available are actually not available, is this formula correct? ...

I don't think `presentationTimeOffset` is relevant, since that parameter is only for adjusting timestamps within the media segments to their correct values; it shouldn't affect which segments are requested. I think it's as simple as:

1. Calculate elapsed duration since the stream started.
1. Divide by segment duration to get the index `c` of the "current" segment .
1. Segment `c-1` should be available, as should segments up to `timeShiftBufferDepth` before it. In a robust system I'd also expect some leeway (i.e. the server also providing segments going some duration further behind the live edge than the manifest advertises), to handle any minor discrepancies between client and server time.

**Comment by dmazar** [comment]
Thanks. It looks like you are correct. I checked in Wireshark what ExoPlayer is picking up for the first segment in that test stream and it is the segment 14th segment (28 secs) before the last one. Calculate it with your instructions. Sounds good.

Although I'm still little bit confused with timings. Yesterday I found this doc:
https://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf
and in general algorithm for calculating segment availability time on page 37 they are using:

`SAST[k,i,r] = PSwc[i] + (t[s,i,r] + d[s,i,r] - o[i,r])/ts
`
where o[i,r] is presentationTimeOffset if I got it correctly.

But then, in chapter "4.3.3.3. Content Offering with Periods" they are not using it in the example of Period 3. Period 3 has presentationTimeOffset.

Regarding the original 404 issue, I'll report to the stream producer that they need to extend the availability of segments on the server. If nothing else, I can use the workaround (custom DashManifestParser and change timeShiftBufferDepth to 30 secs).

Thanks.
