### ISSUE TITLE
Control buttons moving issue

### ISSUE THREAD

**Issue by strikemansan** [google/ExoPlayer#4346]
I have a simple exo player view in my root frame layout. I changed height of player like wrap_content and set layout_gravity=center.

<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center"
    android:focusable="true"
    android:keepScreenOn="true">

    <com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:focusable="true"/>

</FrameLayout>

I use standart layout for playback controller. After the activity is started, the control buttons are located at the bottom (before player preview loading), and then move to the center (as I need).

Why is this happening and how to solve this problem?

**Comment by ojw28** [comment]
I'm not sure exactly what you mean, but the view will resize when the video dimensions become known. The video dimensions are not known until the start of the video has been successfully requested, so this does not happen immediately.

I don't really see how you can avoid this. Perhaps you should be using a fixed height in `dip` rather than `wrap_content`?

**Comment by strikemansan** [comment]
@ojw28 you're right.
After change wrap_content to fixed size in dp, buttons are located where i need, but are there any other ways?

**Comment by ojw28** [comment]
> I use standard layout for playback controller. After the activity is started, the control buttons are located at the bottom (before player preview loading), and then move to the center (as I need).

To clarify, the player controls are always at the bottom of the `SimpleExoPlayerView`. The `SimpleExoPlayerView` initially occupies the whole height of the parent `FrameLayout`, so you see the player controls at the bottom. The `SimpleExoPlayerView` resizes to occupy a smaller space when the aspect ratio of the video becomes known, so you see the player controls still at the bottom of the `SimpleExoPlayerView`, but the `SimpleExoPlayerView` itself is now not occupying the full height of the parent `FrameLayout`.

This is working as intended. The only other option would be for us to initially size the `SimpleExoPlayerView` to be only as high as the controls, but it would still resize when the aspect ratio of the video becomes known. The difference would be that in this case the view would get taller rather than shorter. The controls would still jump in position as a result, and so the user experience would still not be a good one. To avoid the controls moving you really need to fix the height of the `SimpleExoPlayerView`, either in the layout file, or in code if you want to calculate a height based on the view's width and a fixed aspect ratio.
