### ISSUE TITLE
06-11 15:26:24.432 30788-30919/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mpeg2

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4367]
06-11 15:26:24.432 30788-30919/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mpeg2

I am getting this line in my logs of exoplayer. What does this mean that mpeg 2 is not supported by exoplayer?

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by andrewlewis** [comment]
I think this logging is expected and doesn't indicate that MPEG 2 is not supported. (It may actually indicate that an MPEG-2 decoder is present, though I haven't verified this.) See where it's logged in [MediaCodecInfo.java](https://android.googlesource.com/platform/frameworks/base/+/master/media/java/android/media/MediaCodecInfo.java#1127).

**Comment by anandsingh2903** [comment]
Yes mpeg2 is working in exoplayer. Thanks guys.
