### ISSUE TITLE
[DASH]EmbeddedSamples getting ignored in case of multiple AdaptationSets 

### ISSUE THREAD

**Issue by juechemparathy** [google/ExoPlayer#4376]
Facing issue on processing metadata samples by MetadataRenderer for a stream with multiple AdaptionSets.

On preparing PrimarySampleStreams in DashMediaPeriod, we see only the last AdaptationSet is getting considered. Because of this selectEmbeddedSampleStreams is injecting EmptySampleStream which later cause to ignore all subsequent embedded samples by MetadatRenderer. 

https://github.com/google/ExoPlayer/blob/000f3f23056aae30a98ac74fb30e484844548b3e/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaPeriod.java#L290

https://github.com/google/ExoPlayer/blob/e7c60a2a234ab11bc75335453a7836fef9509610/library/core/src/main/java/com/google/android/exoplayer2/metadata/MetadataRenderer.java#L118

Could you also take a look at the mpd file which assumes multiple AdaptionSets for the same track but with different resolutions? Thanks.

@ojw28 @andrewlewis 
Stream info is emailed to dev.exoplayer@gmail.com.

**Comment by ojw28** [comment]
Using separate AdaptationSets for different resolutions, as in the sample manifest, will prevent the client from switching from one resolution to another. This is because there's nothing in the manifest that indicates to the client that switching between the AdaptationSets is valid (e.g. they could contain completely different content). I doubt that's intentional, which suggests that one of the following should be true (probably the second one in this case):

1. There should only be one video AdaptationSet.
1. There should be multiple video AdaptationSets, but they should have ids and be annotated with the `urn:mpeg:dash:adaptation-set-switching:2016` supplemental descriptor so that the client knows it's safe to adapt between them. This is described in the [DASH IF Guidelines](https://dashif.org/wp-content/uploads/2018/04/DASH-IF-IOP-v4.2-clean.pdf) section 3.8.

Either of these content modifications solves the problem you describe. I've emailed you a version of the manifest you provided modified as in (2), which works correctly. So:

1. I'd urge you to get your content fixed as suggested above, unless it really is deliberate that adaptation between the AdaptationSets is supposed to be disallowed.
1. If the content really is intended to be the way it is, please could you let us know and describe the use case for which such content would make sense? We can investigate further in that case.

Thanks!

**Comment by chemparathy** [comment]
@ojw28 - Thanks much for the quick response.
We will be updating the content to comply with 1 or 2. Thanks for the pointer.

**Comment by juechemparathy** [comment]
@ojw28 - Thanks much for the quick response.
We will be updating the content to comply with 1 or 2. Thanks for the pointer.
