### ISSUE TITLE
mp4 buffering issue

### ISSUE THREAD

**Issue by dolphylimitinf** [google/ExoPlayer#4386]
When I go back from current seek position it starts to download again but when I go forward from the current position everything works fine in case of mp4 mime type.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
