### ISSUE TITLE
Can not play Dash for Number Range (in dev branch)

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#440]
The test link is https://sites.google.com/site/oodtsen/dash_ch1.mpd
This is a Number Range Dash link.

But ExoPlayer parser will consider it as Time Range.

We will get the HTTP-404 exception.
>E/ExoPlayerImplInternal(11993): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404,uri: https://0ecbb47e-a-62cb3a1a-s-sites.googlegroups.com/site/oodtsen/segment_1-17727973.m4s
E/ExoPlayerImplInternal(11993):     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:509)
E/ExoPlayerImplInternal(11993):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:403)
E/ExoPlayerImplInternal(11993):     at 

The segment list should be as follow.
>https://0ecbb47e-a-62cb3a1a-s-sites.googlegroups.com/site/oodtsen/segment_1-1.m4s
>https://0ecbb47e-a-62cb3a1a-s-sites.googlegroups.com/site/oodtsen/segment_1-2.m4s
>https://0ecbb47e-a-62cb3a1a-s-sites.googlegroups.com/site/oodtsen/segment_1-3.m4s
>...

**Comment by ojw28** [comment]
The player is behaving correctly. This manifest declares itself as a dynamic (i.e. live) presentation that started in 2014-10-14. Approximate 17727973 segment durations had elapsed since then. The player is trying to join the live end of the stream and so is requesting segments starting at this segment number, which is the right thing to do.

By overriding the manifest to declare itself as static I was able to see the first frame of video. Something else went wrong. I think there are issues with this stream in general.

**Comment by Ood-Tsen** [comment]
Hi @ojw28 , I am not sure this mpd format is correct or not since I am not the expert of mpeg.

But I do play this link by [GPAC OSMO4 Player](http://gpac.wp.mines-telecom.fr/player/) .

**Comment by ojw28** [comment]
I'm 99% sure it's not correct. If it's not a live stream then it shouldn't declare itself as such. If it is, then it should make the segments available.
