### ISSUE TITLE
com.google.android.exoplayer2.source.UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by westlakestudent** [google/ExoPlayer#4417]
hi：
i have got a problem from my users, they can not play video with exception below, 
please help me, thanks very much!

"Url:http://stimg-bj.qbb6.com/2548665190_754c3ab942c2.mp4 LocalFile:/storage/emulated/0/.bt/files/2548665190_754c3ab942c2.mp4 FileMD5:null RemoteHost:stimg-bj.qbb6.com RemotePort:-1 Exception:type=0 renderIndex=-1 cause:com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.\n\tat lo$b.a(SourceFile:774)\n\tat lo$a.load(SourceFile:697)\n\tat com.google.android.exoplayer2.upstream.Loader$a.run(SourceFile:315)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\n\tat java.lang.Thread.run(Thread.java:776)\n

**Comment by ojw28** [comment]
We're not detecting it as a valid MP4 (possibly because it's not). There is nothing we can do to debug this issue without having access to the problematic media file. Please mail the file to `dev.exoplayer@gmail.com` if you have it, with "#4417" in the subject line, and update this issue to say it's been sent.

If you're unable to provide the file then we'll probably have to close the issue. Thanks!

**Comment by westlakestudent** [comment]
it's been sent. thank you very much

**Comment by westlakestudent** [comment]
is there any help?

**Comment by ojw28** [comment]
The video plays fine in the ExoPlayer demo app. If you're using an old version of ExoPlayer then I'd suggest you update to the latest version, in case a fix was made.
