### ISSUE TITLE
addVideoListener in simpleExoPlayerView

### ISSUE THREAD

**Issue by jemjov41** [google/ExoPlayer#4424]
i got error while <pre>simpleExoPlayerView.setPlayer(simpleExoPlayer)</pre> its show me this error in logcat

<pre>
NoSuchMethodError: No virtual method addVideoListener(Lcom/google/android/exoplayer2/SimpleExoPlayer$VideoListener;) 
</pre>
so i adding 
<pre>
<code>
simpleExoPlayer.addVideoListener(new VideoListener() {
            @Override
            public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
                Log.d("asdqwe",String.format("play video listener video size changed"));
            }
            @Override
            public void onRenderedFirstFrame() {
                Log.d("asdqwe",String.format("play video listener render first frame"));
            }
        });
</code></pre>
but the error still appear, i read the doc and SimpleExoPlayer.VideoListener is deprecated so i'm using Video.VideoListener

anyone can tell me where im wrong? and how to fix this?

**Comment by ojw28** [comment]
Please try adding the exact same code into our demo application's `PlayerActivity`, and running that. If everything works there, this seems like an issue with your application's build setup rather than an issue with the ExoPlayer library.

I wonder if your app is somehow pulling in multiple different versions of ExoPlayer.

**Comment by jemjov41** [comment]
im sorry its fully my fault im using version 2.5.2 and its not the new one so i update to the newest and its solve

thanks
