### ISSUE TITLE
Subtitle language always set to Unknown

### ISSUE THREAD

**Issue by jeanvcastro** [google/ExoPlayer#4436]
Subtitle languages ​​are always set to Unknown when running the demo project using other mp4 video sources (I have not tested other formats). When debugging, I noticed that the language is being decoded as "```", probably this is the cause of the problem. The subtitles work perfectly, the Exoplayer was very good in the last ones and this is the only problem that is preventing me from migrating from vlc-player to it.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by jeanimator** [comment]
Tested in Demo App using this link: http://23.111.172.34:21500/movie/a@a.com.br/zzzz/2201.mp4
Version of ExoPlayer: 2.8.1
Device: Android Emulator with API 27

**Comment by AquilesCanta** [comment]
Hi @jeanimator, for some reason I received an e-mail with the required info but the comment is not available here. 

I have looked at the media and the language defined in mdhd, as you point out,  is "```". I checked with MP4Box and it also states 

> Media Info: Language "Undetermined (und)"

Mediainfo on the other hand, reports English for both tracks. I don't know whether there is another source of information for the language, or it's just falling back to English by default. I am tempted to say this is working as intendend. 

I guess we could potentially replace "```" with und, as MP4Box does, but I doubt that'd be more than a workaround. If can point us out to a different language source, that'd be ideal. If so, I'll reopen.

**Comment by ojw28** [comment]
Agreed this is working as intended. The file does include language, but it's hidden under `trak->udta->name`, which is not a normal place for the language, or even for a track name as far as I can tell.
