### ISSUE TITLE
ExoPlayer creates fake text track whenever HLS master playlist contains "subtitle" tag but no "closed captions" tag

### ISSUE THREAD

**Issue by Lingviston** [google/ExoPlayer#4451]
### Issue description
Whenever one tries to play an HLS video, which master playlist contains "subtitle" tag but no "closed captions" tag, he'll see an "unknown" or "1/8219" captions entry. Selection of this entry just does nothing, because it is fake. AFAIK ExoPlayer creates it to cover the CC608 captions scenario (see https://github.com/google/ExoPlayer/issues/2651), but it really confuses users in other cases.
This change https://github.com/google/ExoPlayer/commit/3fc3349e9535d8763f9a4c34c1d9a9e2ce7024a3 introduced the issue (see `DefaultTsPayloadReaderFactory` changes)

### Reproduction steps
Play the test content in the ExoPlayer demo app.

### Link to test content
https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/playlist.m3u8

### Version of ExoPlayer being used
2.6.1, 2.8.1

### Device(s) and version(s) of Android being used
Reproduced on any Android version and any device. Tested on SGS 7 Android 8.0.

### A full bug report captured from the device
N/A

**Comment by AquilesCanta** [comment]
I doubt we'll change the default behavior on HLS captions at this point. The bright side is that there are a few things that can be done to prevent the spurious 608 track:

- **Simplest (probably best)**: Add CLOSED-CAPTIONS=NONE to your playlist variants.
- **Pure client-side change**: Implement your own HlsExtractorFactory which instantiates the DefaultTsPayloadReaderFactory by overriding the caption formats with an empty list.

Let me know if you can think of a better solution and we'll reopen.

**Comment by Lingviston** [comment]
@AquilesCanta Unfortunately the first option is not an option for us.

About the second one: how in this case we can detect the streams, which do have CC608 captions but don't have them declared in HLS manifest?

**Comment by AquilesCanta** [comment]
Depends on the media. Does the transport stream signal the presence of closed captions in any way? One  way of doing this is using descriptors.

Without any signaling information, ExoPlayer cannot do much about it in its current state.

**Comment by Lingviston** [comment]
@AquilesCanta currently I'm interested only in HLS. I believe the only way to signal about the CC there is via some tags in master playlist? Or item playlists.

**Comment by AquilesCanta** [comment]
I am not sure I understand the question.

You can signal stuff either in the playlists or in the media. Due to ExoPlayer limitations, if you want to use chunkless preparation (recommended), track information needs to be [signaled in the playlist](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2).

If you can only signal it in the media, then you need traditional preparation. 

Track information cannot be added on the fly as things are now, unfortunately.

**Comment by Lingviston** [comment]
Ok, so if I use traditional preparation and CC tracks only being signalled in the media will it make ExoPlayer to not add this fake CC track item? Or it'll still be added but I'll have the way to detect it and remove from the list by myself?

**Comment by AquilesCanta** [comment]
> so if I use traditional preparation and CC tracks only being signalled in the media will it make ExoPlayer to not add this fake CC track item?

You'll need to:
1. Wait until a commit gets referenced below this comment and pick up that change.
2. Implement your own HlsExtractorFactory and use it to create your HlsMediaSource.
3. When creating your DefaultTsPayloadReaderFactory, pass an empty list but DO NOT enable FLAG_OVERRIDE_CAPTION_DESCRIPTORS.

This will not generate any 608 tracks, unless there is a closed captions descriptor in the TS. An alternative would be fixing this in the app code, but up to you.

**Comment by rgrk11** [comment]
My use case is to play some TS streams from tvheadend using Exoplayer. With r2.8.4, I was able to disable the redundant empty CEA-608 text track by enabling FLAG_OVERRIDE_CAPTION_DESCRIPTORS via DefaultExtractorsFactory, though I understand that it may not be a right way of using this flag. 

Anyway, this trick no longer works for my use case after the above commit. From r.2.9.0 onwards, I may have to duplicate several classes to just pass an empty list to DefaultTsPayloadReaderFactory, as per the above suggestion. This seems to be a bit inconvenient because I may then have to monitor the changes of these duplicated classes when updating Exoplayer.

As an alternative, would you please consider adding a proper TS extractor flag which can provide an option to disable the redundant CEA-608 text track if needed? Together with the recent commit in [2a50621](https://github.com/google/ExoPlayer/commit/e50214a5a1fd378d66db0ab088f1d9a4f2ccb2d9) for DefaultHlsExtractorFactory, the proposed flag may also offer a simpler client-side solution than the above suggestion.

**Comment by AquilesCanta** [comment]
Hi @rgrk11, 

> I may have to duplicate several classes 

Don't you just need your own ExtractorsFactory implementation?

**Comment by rgrk11** [comment]
Yes, you are right. I overlooked that one of the TsExtractor's constructors also accepts custom TsPayloadReaderFactory. 

Nevertheless, I still think that maintaining such custom ExtractorFactory as well as HlsExtractorFactory would be inconvenient if I want to keep updating Exoplayer. It would be very helpful if Exoplayer can support this feature in a more convenient manner. Please re-consider, thank you.
