### ISSUE TITLE
SeekTo does not work in live mp3

### ISSUE THREAD

**Issue by helloseyedjafari** [google/ExoPlayer#4452]
Whenever I try to play a live mp3 using default settings it plays just fine but the TimeBar and `seekTo ` method does not work. 

so when I try to rewind to a few seconds ago the player just stops the playback and start buffering and playing right from the live edge again.

I pretty much tried every media source (ConcatinatingMediaSource, ExtractorMediaSource) and every way (creating a simple m3u8 file and adding the sole mp3 to the file and playing it as HLS) I could use the player but no luck yet.

I have created a [sample project](https://github.com/worldsnas/ExoPlayerTest) to explain the issue further. in the project, I used the latest Progressive download Feature.

the last thing I could think of was to download chunks of the live mp3 manually and create a ConcatinatingMediaSource and add every chunk to the source whenever its 1000 bytes. so the player can handle seeking and loading the files properly. but this way makes a lot more issue.

so would please tell me if there is a better way to manage this playback with seeking feature enabled?

**Comment by andrewlewis** [comment]
The short answer is that there is no easy way to get this to work client-side because whenever you reconnect to the server it's going to give the stream starting at the live edge. Even if you store the stream as it loads, so that old data is available, you won't have a time to byte mapping. That would also be needed to make the stream seekable.

If you have control over the stream, you should switch to another format like DASH or HLS where we do support seeking in live streams.

If you can't control the stream and are willing to put time into making this to work, there are a few options but it's beyond the scope of this issue tracker to go into much detail. For example, you could split the incoming stream into chunks and create a live HLS stream out of those. This is non-trivial because the chunks need to be split on audio frame boundaries and you'll need to associate a timestamp with each chunk.
