### ISSUE TITLE
Next button to skip all looping videos and play the next MediaSource in a ConcatenatingMediaSource

### ISSUE THREAD

**Issue by joecizac** [google/ExoPlayer#4459]
Hi, 
I have my ConcatenatingMediaSource with looping and non-looping videos.
When I click the next button on a looping video, it moves to the next iteration of the loop and plays the same video again. So I have to press the loop 'n' times to actually move to the next video. 
How can I achieve moving to the next MediaSource skipping the LoopingMediaSource

Below is my implementation:
```
val videoSource = ConcatenatingMediaSource()
if (it.reps > 1) {
    videoSource.addMediaSource(LoopingMediaSource(ExtractorMediaSource.Factory(
            CacheDataSourceFactory(downloadCache, factory, 
                    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)).createMediaSource(url), it.reps))
} else {
    videoSource.addMediaSource(ExtractorMediaSource.Factory(
            CacheDataSourceFactory(downloadCache, factory, 
                    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)).createMediaSource(url))
}
```

**Comment by tonihei** [comment]
I assume you are using ExoPlayer's UI components and specifically [`PlayerControlView`](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java).

Whenever you click next in this control view, the player seeks to the new playlist item. In your case, this is each single loop iteration, and only after that, the next video. This is a sensible default behavior and we are unlikely to change this.

However, there are at least two ways to customize the behaviour to your needs:
1. Provide your own custom player control view. You could do this by copying our class and then customize the `next()` and `previous()` methods. You'd need to use `player.seekTo(windowIndexOfNextVideoAfterLoops, C.TIME_UNSET)`  to skip to the next video after the remaining loops. You can get this window index by repeatedly calling `player.getNextWindowIndex()` until the index actually changes.
2. Change your media structure to not use `LoopingMediaSource`. Instead, set the repeat mode of the player to `REPEAT_MODE_ONE` which loops the current item endlessly. To eventually transition automatically to the next item, you can count the loop iterations in `Player.EventListener.onPositionDiscontinuity` and then turn off the repeat mode temporarily until the player reached the next item in your playlist. Make sure to only use position discontinuities where the reason is DISCONTINUITY_REASON_PERIOD_TRANSITION.

**Comment by joecizac** [comment]
Thanks @tonihei for the quick reply and the solution. 
I was thinking that in the ConcatenatingMediaSource every source is considered as one whereas here even the subset of the LoopingMediaSource is counted as a source.
Anyways I am going with the second suggestion.
Thanks once again.
