### ISSUE TITLE
Request: provide various video scaling types, even without being attached to a View

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4464]
As the title says...

**Comment by ojw28** [comment]
I don't think we're going to support this. It's a very specific use case (as an aside, playing video in a live wallpaper doesn't sound like a great idea from a battery drain perspective).

More importantly, there's no way we can easily support this without underlying platform support, and if the underlying platform support were there we'd have support "for free". So what you really need is `MediaCodec.setVideoScalingMode` to support whatever mode(s) you need. You'll need to file an issue on the Android issue tracker for that, rather than here.

**Comment by AndroidDeveloperLB** [comment]
Why close this?
You said you'd consider it ... :(

And why do you think it can't be in a live wallpaper?
Battery drain is the same as watching a video on a normal app, and it should pause when not being shown.
And, as you guys told me, not all scaling types are available in this case, which is why I've requested it here...

**Comment by ojw28** [comment]
> Why close this?

Because you need this implemented in the platform, not in ExoPlayer. As above, your request is equivalent to requesting additional scaling mode functionality for `MediaCodec.setVideoScalingMode`, which is not an ExoPlayer component. So you need to file an issue on the Android issue tracker.

**Comment by AndroidDeveloperLB** [comment]
You mean this:
https://developer.android.com/reference/android/media/MediaPlayer.html#setVideoScalingMode(int)
?
Isn't there any workaround for ExoPlayer around this?

**Comment by AndroidDeveloperLB** [comment]
Anyway, here's the request:
https://issuetracker.google.com/issues/111096412

Please do consider adding it.
