### ISSUE TITLE
Inputs in configuring mediacodec from exoplayer application

### ISSUE THREAD

**Issue by resmi** [google/ExoPlayer#4481]
I need to configure the video mediacodec using configure() API with a MediaFormat for video, from an exoplayer application. This is to expose a codec control to the user, so that the user can enable/disable a feature that our codec component provides. 

I want to use the exoplayer demo app and build upon it. Not seeing a configure API in the default APIs of MediaCodecVideoTrackRenderer.java which requires only the format to be input. configureCodec() API expects the codec instance as well, which is not available to the application. 

Does this mean that I can extend MediaCodecVideoTrackRenderer and add this API, so that the extended class can call codec.configure() on the video codec instance created internally?

Or can I extend and add an API to return the codec instance to the application?

Please let me know if this thought process is correct, or if any other suggestions?
Kindly excuse any simple misses, I am not well-versed at all in Android application development.

**Comment by botaydotcom** [comment]
Hi @resmi,
Since you are using `MediaCodecVideoTrackRenderer`, are you using ExoPlayer V1? I think for V1, we are not adding anymore feature, so extending the class and adding this functionality yourself seems to be the correct choice, especially given `MediaCodecVideoTrackRenderer.configureCodec()` is designed as `protected` so that extended classes can add more functionalities as they want.

If you are using (or migrating to) ExoPlayver V2 (soon), the corresponding class will be `MediaCodecVideoRenderer`. I think for this specific case, it's also similar, and you should add this feature yourself. However, for V2, you can always file new request on the issue tracker to see if your specific feature is something that should be used by many developers, in which case we will probably add support directly in the library.
