### ISSUE TITLE
Failed to resolve: play-services-ads bug

### ISSUE THREAD

**Issue by dzboot02** [google/ExoPlayer#4485]
On latest Android Studio, this error pops up when syncing gradle for ExoPlayer:

`Failed to resolve: play-services-ads`

It's probably a bug in Android Studio or Gradle plugin.
To solve it, you need to put `google()` first in both repositories lists of the project level gradle. I don't know how to use Github yet, so please fix this.

Thank you

**Comment by botaydotcom** [comment]
Hi @hiddeneyes02, 
Thanks for reporting. This is already mentioned in ExoPlayer project's [README](https://github.com/google/ExoPlayer).

**Comment by botaydotcom** [comment]
Hi @hiddeneyes02,
I think your issue is similar to: #4353. It seems in that case the other reporter found their issue to be resolved after a while, without any action from us. That seemed to be an issue with bintray.
We will monitor this issue to see if it pops up more often and see if we need to take any action.
