### ISSUE TITLE
How change hls stream source on the fly?

### ISSUE THREAD

**Issue by ghd3** [google/ExoPlayer#4498]
Hello.
My application use ExoPlayer for hls video playback. Sometimes, my stream source works bad (can throw http error or can have long response time), as result playback can stuck for a short time.

In order to overcome this problem my backend provides several instances of the same stream hosted on the different servers. The structure of those instances (playlists, chunk lists, chunks) are absolutely equal.

I’m aiming In case of errors to change those streams on the flight (e.g. take one chunk from server 1, the next one from server 2 and so on), without recreation of the ExoPlayer object. So, my questions are:

1. Does ExoPlayer provides desired functionality (or at least part of it) out of the box?
2. If not, which way can be better:
- implement custom hls data source?
- or better starts from ConcatenatingMediaSource?
- something else?

**Comment by AquilesCanta** [comment]
> Does ExoPlayer provides desired functionality (or at least part of it) out of the box?

It kind of does if you provide all your alternative variants in the master playlist and the server returns 404/410 for any of them. ExoPlayer will blacklist them and switch to a different one. Latency increases will probably be observed as decreases in the bandwidth. More info on network errors below.

> or better starts from ConcatenatingMediaSource

Is unrelated as far as I can see.

> implement custom hls data source

This could help, but depending on how the load balancing works, could get messy. Have a look at HlsDataSourceFactory and DataSource to see what you can potentially do with them. If you have more specific questions do ask.

> something else

Have a look at providing all your available media playlist URLs in the master playlist and implement your own TrackSelection.Factory so that you pick a different media playlist when you notice an increase in latency, also potentially blacklisting specific network errors (this is being tracked by #2981).

Hope this helps. Let me know if you have specific questions.

**Comment by ojw28** [comment]
I thought you were supposed to just list all of the available options in the HLS master playlist to achieve this. For example:

```
#EXTM3U

#EXT-X-STREAM-INF:BANDWIDTH=1280000,AVERAGE-BANDWIDTH=1000000
http://server1.com/low.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=7680000,AVERAGE-BANDWIDTH=6000000
http://server1.com/hi.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1280000,AVERAGE-BANDWIDTH=1000000
http://server2.com/low.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=7680000,AVERAGE-BANDWIDTH=6000000
http://server2.com/hi.m3u8
```

ExoPlayer will automatically blacklist a stream for some period of time whenever it encounters an error, and therefore switch to the alternate.
