### ISSUE TITLE
Is this possible to get full duration in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by harshmittal2810** [google/ExoPlayer#4500]
I have seen so many issues based on this but none of this working for me.
I have added multiple media source in ConcatenatingMediaSource.
When trying to use showmultitimebar also not working.
I want one seekbar for whole playlist and total playlist duration based on ConcatenatingMediaSource data.
Please help out on this.

**Comment by botaydotcom** [comment]
I'm not sure about your specific setup, but I think your situation is most likely like this (correct me if I'm wrong):
- You have a `ConcatenatingMediaSource`, which consists of several `ExtractorMediaSource`.
- You turn on `showMultiWindowTimeBar`.
- You observe that the time bar is still not updated to show the whole timeline for the playlist.

We kind of know about the situation, but unfortunately this is something not easy to fix. The problem is for `showMultiWindowTimeBar` to work, it has to know the duration of all the media in the playlist. However, this doesn't integrate nicely with `ExtractorMediaSource`.
Currently, our model of preparing `ExtractorMediaSource` is broken down in 2 steps. The first step is just acknowledging that this media source is an `ExtractorMediaSource`, with duration = UNSET (not loaded), and unseekable (also not loaded). So at the beginning, your `ConcatenatingMediaSource` doesn't know the duration of all its children, and the multi-window time bar is not available. Then, the second step, right before each stream is about to play, is to actually load the media, examine the stream to see what tracks are available in the stream as well as reading the duration of the stream (note that [certain formats are not seekable/duration are not available](https://google.github.io/ExoPlayer/supported-formats.html), and playlist with these formats will result in multi-window timebar not available).
The reason it's broken down into 2 steps like this is to reduce the initial loading time for playlist case, because for certain formats, examining the streams for its track & its duration takes some time. Therefore, only after you have played until your last item in the playlist, then all `ExtractorMediaSource` in the list can know about their duration, and the `ConcatenatingMediaSource` will know about all its child. At that point, you will see the time bar changed into a multi-window bar.

Agree that this behavior is not ideal, and we are looking into ways to improve this, however this is not a easy problem.
There is a workaround that you might try (it's not applicable for all cases). If you know the duration of all the media in the playlist via some other means (for example: you have played the file/uri before, and store their duration in a DB), or you have the duration sent from some  servers, what you can do is using one `ClippingMediaSource` to wrap each `ExtractorMediaSource`, and clip the end to the duration of that stream. Then having your `ConcatenatingMediaSource` to concatenate these `ClippingMediaSource`. I haven't tried, but I believe your multi-window bar will be shown from the beginning in such case.

**Comment by harshmittal2810** [comment]
I am trying to play two clipping media source but that is not working properly.
Video is not playing next to last and seekbar also not behaving in that way. Help me out in this.

**Comment by tonihei** [comment]
@mittalharsh2810 Is that still an issue or was your question answered by @botaydotcom above? Please reopen if you have follow-up questions.
