### ISSUE TITLE
Decrypting HLS Video Encryption Key!

### ISSUE THREAD

**Issue by blessonabraham** [google/ExoPlayer#4507]
I have passed a m3u8 playlist url to Exoplayer, The url will return the manifest file after proper authentication. Then the Exoplayer requests for Decryption Key, The decryption key will be provided again after proper user authentication, Its all fine, But my problem is the video decryption key which receives can be seen with any network analysis tool like fiddler. So i thought about Encrypting the video Decryption key and send it to app from server. So the HTTP response for video Decryption key is an Encrypted response! how can i decrypt this response and pass it to Exoplayer. I was thinking about giving a specific header tag for that HTTP response so that we can decrypt just that response and bypass all the responses. How can i achieve this! Or is there a better solution out there other than expensive DRMs.

**Comment by ojw28** [comment]
Why don't you just use https?

**Comment by blessonabraham** [comment]
@ojw28 If my authorised user is a hacker, he can analyse his traffic even if its HTTPS. So by Encrypting the video decryption key, i can slow him down!
Please Help!

**Comment by ojw28** [comment]
If you're really concerned about authorized users extracting the content then you need to use proper DRM with underlying platform support (on Android, you'd probably need to use Widevine).

I don't think there's much point in preventing the specific attack you describe, since there are other attacks such a user could do instead, some of which are probably easier. For example they could make a small modification to Android to capture the decrypted but still compressed media being fed into the audio and video decoders, flash a device with the modified build, and extract the content that way.

It's worth thinking about how realistic the attack you describe (and the one I describe, and others) really are. It seems pretty unlikely to me that someone would go to such lengths. If you disagree, as above, I think your only real option is to use Widevine.
