### ISSUE TITLE
HLS - switching the bitrate during playback

### ISSUE THREAD

**Issue by AkivaGit** [google/ExoPlayer#4528]
I understand that after an adaptive video track is chosen, with some initial bitrate value, the player will auto-adjust the bitrate to match the quality of internet connection.
Is it possible to force the player to switch to another bitrate according to user choice, and stay on it, or make the player go back to auto mode? I mean to do it DURING playback, not when starting playback. 
(For when starting playback, I customize TrackSelector and make it choose the desired fixed video track. )
What other class can I customize to achieve that? Or is there other way?

**Comment by ojw28** [comment]
You can use track selection overrides, as described in [this Javadoc](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html), however when an override is made the switch will be immediate and therefore require a short period of re-buffering.

I'm not sure if that's what you want (possibly you do if there's user input involved, since delayed switching in that case can be confusing). If you want the switch to still be seamless, supporting that is tracked by https://github.com/google/ExoPlayer/issues/2250.
