### ISSUE TITLE
Some h264 files will not render any video

### ISSUE THREAD

**Issue by tmm1** [google/ExoPlayer#4538]
### Issue description

Some H264 videos (ones that use PAFF interlacing it appears), do not play in ExoPlayer on any device. Other players (like VLC) which also use MediaCodec are able to play these same videos.

`mediainfo` shows this about the affected files:

```
Scan type                                : Interlaced
Scan type, store method                  : Separated fields
Scan order                               : Top Field First
```

### Reproduction steps

Add https://s3.amazonaws.com/tmm1/uk-interlaced-h264.ts to `media.exolist.json` and try to play it.

### Version of ExoPlayer being used

r2.8.2 (f7ed789fc3841b2536f5629c6bb10f4cb4ee5130)

### Device(s) and version(s) of Android being used

Tested on SHIELD running API 26, and Amazon FireTV 3rd generation running API 25

### A full bug report captured from the device

Happy to provide if necessary, but the issue reproduces easily on any device.

**Comment by ojw28** [comment]
Please see: http://google.github.io/ExoPlayer/faqs.html#why-do-some-mpeg-ts-files-fail-to-play

**Comment by tmm1** [comment]
> ExoPlayer will appear to be stuck in the buffering state when asked to play an MPEG-TS file that lacks AUDs or IDR keyframes.

Thanks for the pointer. I confirmed that this sample is missing IDR slices, and setting `FLAG_ALLOW_NON_IDR_KEYFRAMES` fixes the playback issue.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
