### ISSUE TITLE
ExoPlayer Video Blur issue

### ISSUE THREAD

**Issue by LaddhaShubham** [google/ExoPlayer#4545]
Hi, 

In exoplayer, I trying to play video but some videos work fine and some video gone blur.

I made videos application and in that i see all uploaded videos but when I upload video from my android device then video work fine but when i upload video from iOS device then video gone blur.
Can you please suggest where I have to change into code?

![img_2018](https://user-images.githubusercontent.com/41472415/43040837-1592cd4c-8d6c-11e8-96b8-55c04271fc17.png)

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found here.

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by LaddhaShubham** [comment]
my means, I have two videos...one is upload from android and second is upload from ios and i downloaded both video from server url. but in my mac I saw that ios video get info shows "Color Profile: HD(1-1-1)" but for android video not get key of "Color Profile". that means ios do capture HD video and which is not supported by exoplayer.

This is of iOS video info:
![screen shot 2018-07-23 at 6 42 46 pm](https://user-images.githubusercontent.com/41472415/43078609-98bf4668-8ea8-11e8-8c9c-31a57184655d.png)

This is of Android video info:
![screen shot 2018-07-23 at 6 42 54 pm](https://user-images.githubusercontent.com/41472415/43078634-a50d00ae-8ea8-11e8-8ea1-a2b6a00c99f1.png)

So please can you help me to solve it out these issue?

**Comment by ojw28** [comment]
The issue template clearly defines what information we need to help. If you can provide the information requested in the template, we will help you to solve the problem.

**Comment by LaddhaShubham** [comment]
This player doesn't supports HD Videos. Check in your end.
I didn't get you. What kind of more info you need from me. let me know..

**Comment by ojw28** [comment]
When you file an issue, the issue is pre-populated with a template that lists what information we need. I've also copied it below.

--------------------------------------------

When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### Issue description
Describe the issue in detail, including observed and expected behavior.

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234".
