### ISSUE TITLE
Support seeking in AAC

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#4548]
Hi , i've tried  to seek into AAC files but they won't 
Please is there a way to let AAC file seekable.
Can you add this option in the futur ?
Thanks

**Comment by ojw28** [comment]
We may add approximate seeking using a constant bitrate assumption, at some point in the future.

That said, if you need seeking, you should really be using a container format that's better able to support it (e.g. MP4).

**Comment by satyres** [comment]
Thanks so much for your answer.
Can you tell me how to put it in MP4 container ?
by the way , ts file (from HLS streams) won't play using Exoplayer aswell (local file not stream)
Best regards

**Comment by ojw28** [comment]
Approximate seeking is now supported in the `dev-v2` branch, if you specify the `FLAG_ENABLE_CONSTANT_BITRATE_SEEKING` whe constructing an `AdtsExtractor`.

> Can you tell me how to put it in MP4 container ?

Advising on how to prepare content is beyond the scope of this issue tracker. Tools such as ffmpeg and mp4box probably help with this.

**Comment by satyres** [comment]
Hi , Thanks ojw28 , so Seeking will be available in the next release ?
Thanks

**Comment by ojw28** [comment]
It will be available in 2.9.0 (which may or may not be the next release, depending on whether there's a 2.8.4).

**Comment by satyres** [comment]
Thanks so much ojw28 for your time.
Have a nice day.
Best regards

**Comment by satyres** [comment]
Hi , Thanks for all your work
but the problem for AAC has not been fixed.
the duration and seeking are not working.
in 2.9.0 and 2.9.2 
please is there something we can do ?
Regards

**Comment by ojw28** [comment]
Are you using the `FLAG_ENABLE_CONSTANT_BITRATE_SEEKING` as mentioned as being required further up this thread? Please see [this faq](https://google.github.io/ExoPlayer/faqs.html#why-are-some-media-files-not-seekable) for information on how to use it.

I'm not going to re-open this issue because it does not contain the information requested in the issue template (e.g. a sample file so we know exactly what type of media you're playing). If you're using the flag and this is still a problem, I'd suggest filing a new issue where you fill in the issue template completely. Thanks.

**Comment by satyres** [comment]
Hi ojw28,
Thanks so much for your reply.
enabling FLAG_ENABLE_CONSTANT_BITRATE_SEEKING   did it , and it's working.
but not on all AAC files ,if you want i will send you a file to test on it.
Best regards

**Comment by ojw28** [comment]
Please send a test file to `dev.exoplayer@gmail.com`, and respond here to indicate that you've done so. Thanks!
