### ISSUE TITLE
Subtitles Toggle

### ISSUE THREAD

**Issue by vinayjoglekar** [google/ExoPlayer#4570]
I am using exoplayer 2.8.2. 
```
if (object.getSubtitles().size() > 0) {
            MediaSource[] mediaSources = new MediaSource[object.getSubtitles().size() + 1];
            mediaSources[0] = videoMediaSource;
            int i = 1;
            for (String language : object.getSubtitles().keySet()) {
                String subtitleUrl = object.getSubtitles().get(language).get(0).getSrc();
                Format subtitleFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, C.SELECTION_FLAG_DEFAULT, language);
                mediaSources[i] = new SingleSampleMediaSource.Factory(new DefaultHttpDataSourceFactory(userAgent, BANDWIDTH_METER)).createMediaSource(Uri.parse(subtitleUrl), subtitleFormat, C.TIME_UNSET);
                i++;
            }
            mMergedMediaSource = new MergingMediaSource(mediaSources);
        }
```

```
MappingTrackSelector.MappedTrackInfo mappedTrackInfo =mDefaultTrackSelector.getCurrentMappedTrackInfo();
TrackGroupArray rendererTrackGroups = mappedTrackInfo == null ? null : mappedTrackInfo.getTrackGroups(SUBTITLE_TRACK_GROUP_INDEX);
DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(SUBTITLE_TRACK_GROUP_INDEX, mCaptionsTrackIndex);
mDefaultTrackSelector.setParameters(mDefaultTrackSelector.buildUponParameters().setSelectionOverride(SUBTITLE_TRACK_GROUP_INDEX, rendererTrackGroups, selectionOverride));
```

In above code, SUBTITLE_TRACK_GROUP_INDEX is 2 which is track group number from trackselector for subtitles and mCaptionsTrackIndex is index within rendererTrackGroups which needs to be selected. The above code always shows english subtitles and not others in array.

**Comment by AquilesCanta** [comment]
Hi @vinayjoglekar, the issue tracker is not intended for general ExoPlayer Q&A, unfortunately. You'll have better luck in a general Q&A site like StackOverflow. Make sure you provide as much context (and examples) as possible in your questions in order to avoid luring people away with the required guesswork. 

Looks weird to me that you are creating a SelectionOverride with a constant track group, though. Remember that each subtitle will provide a different TrackGroup (this might explain the issue). Also strange that getTrackGroup gets passed a TRACK_GROUP_INDEX, when it should take a renderer index. Anyway, good luck!
