### ISSUE TITLE
Auto Adaptive bit-rate in Exoplayer stuck lowest resulotion

### ISSUE THREAD

**Issue by luckylook** [google/ExoPlayer#4581]
hi
i am playing 2 formats
<Representation id="trickmodedzEAACif" bandwidth="2621440" codecs="avc1.4d4029" width="720" height="576" frameRate="1" sar="1:1" maxPlayoutRate="25"/>
<Representation id="trickmodedzGZmUmf" bandwidth="4823449" codecs="avc1.64002a" width="1920" height="1080" frameRate="1" sar="1:1" maxPlayoutRate="50"/>

and my player stuck in lowest resuloation all the time?? when i remove the 720 format its play ok on 8 mb but with 2 formats it takes the lowest and stay...
i also checked  #3320 issue doesnt help me
iam using : exoplayer:2.8.2
play : widewine dash
thx

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
