### ISSUE TITLE
not playing Youtube URL 

### ISSUE THREAD

**Issue by sreereddymenon** [google/ExoPlayer#459]
I am using  exo player. how can i play youtube url . please let me know exoplayer doesnt support for yutube urls. so that i can use video player..

my url .

https://www.youtube.com/watch?v=OZScqcKFK_E

**Comment by ojw28** [comment]
This is already answered in #455. A YouTube embed URL is not a media file. It's an html web page. There is no way for any third party media player to play that. You need a web browser.

**Comment by crossle** [comment]
Maybe your can use https://github.com/hellozimi/HCYoutubeParser, get video player url

**Comment by andreimarinescu** [comment]
Honestly, I think you might be better off by using this: https://developers.google.com/youtube/android/player/ if the API level limitations are compatible with your use-case (they probably are since you're looking @ exo player). Personally, I'm using this for youtube playback and ExoPlayer for the rest.
