### ISSUE TITLE
Problem with DASH multi period.

### ISSUE THREAD

**Issue by valdeci** [google/ExoPlayer#4605]
I have a use case where the file xml/mpd (DASH) with multi-period don't have a start period neither the duration, this way the player run only the first period and is paused, and it's not run the period next. It's look like that the DashMediaSource don't know the way to concatenate the periods without start e/or duration. 

Version: exoplayer-dash:2.8.2
MPD type is dinamic

Example of the mpd file, this is a present content in the url to create the media source.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" minBufferTime="PT1.0S" timeShiftBufferDepth="PT88H46M53.0S" minimumUpdatePeriod="PT5S" availabilityStartTime="2018-06-22T16:54:13Z" profiles="urn:mpeg:dash:profile:isoff-live:2011" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" type="dynamic">
   <Location>https://hostname.com.br/live/BJHCfrVxm.stream/manifest_dvr.mpd?nimblesessionid=3773</Location>
   <Period start="PT0.0S" id="2817">
      <AdaptationSet id="1" startWithSAP="1" segmentAlignment="true">
         <Representation id="v0" bandwidth="887013" height="720" width="1280" codecs="avc1.4d001f" mimeType="video/mp4">
            <SegmentTemplate initialization="dvr_i_p2817.m4mv?nimblesessionid=3773" media="dvr_v_p2817_$Time$.m4s?nimblesessionid=3773" timescale="90000">
               <SegmentTimeline>
                  <S d="515700" t="4493700" />
               </SegmentTimeline>
            </SegmentTemplate>
         </Representation>
      </AdaptationSet>
   </Period>
   <Period id="2818">
      <AdaptationSet id="1" startWithSAP="1" segmentAlignment="true">
         <Representation id="v0" bandwidth="887013" height="720" width="1280" codecs="avc1.64001f" mimeType="video/mp4">
            <SegmentTemplate initialization="dvr_i_p2818.m4mv?nimblesessionid=3773" media="dvr_v_p2818_$Time$.m4s?nimblesessionid=3773" timescale="90000">
               <SegmentTimeline>
                  <S d="713700" t="0" />
                  <S d="150300" t="713700" />
               </SegmentTimeline>
            </SegmentTemplate>
         </Representation>
      </AdaptationSet>
   </Period>
   <Period id="2819">
      <AdaptationSet id="1" startWithSAP="1" segmentAlignment="true">
         <Representation id="v0" bandwidth="887013" height="720" width="1280" codecs="avc1.4d001f" mimeType="video/mp4">
            <SegmentTemplate initialization="dvr_i_p2819.m4mv?nimblesessionid=3773" media="dvr_v_p2819_$Time$.m4s?nimblesessionid=3773" timescale="90000">
               <SegmentTimeline>
                  <S d="702000" t="0" />
                  <S d="540000" t="702000" />
                  <S d="528300" t="1242000" />
                  <S d="540000" t="1770300" />
                  <S d="270000" t="2310300" />
               </SegmentTimeline>
            </SegmentTemplate>
         </Representation>
      </AdaptationSet>
   </Period>
</MPD>
```

**Comment by ojw28** [comment]
I think it would be incorrect for a DASH client to start playing the second period in this case. ISO 23009-1 defines a period whose start time cannot be determined either by (a) `@start` being present on the period, or (b) `@duration` being present on the previous period and the previous period's start time being known, as an "Early Available Period".

An Early Available Period appears to be a special type of period, which can be used to advertise resources before the period becomes eligible for playback, so that the client can request them ahead of time. I don't think clients are supposed to start playback of such periods, in particular because it's permitted for them to be removed entirely, out of order, from the manifest.

I very much doubt the manifest in this case is supposed to be defining the second and third periods as Early Available Periods, so effectively it's not implementing the DASH spec correctl (i.e. `@start` or `@duration` should be specified).
