### ISSUE TITLE
IllegalClippingException when using ClippingMediaSource(LoopingMediaSource(limitedLoops))

### ISSUE THREAD

**Issue by robin2046** [google/ExoPlayer#4626]
Tested on r2.8.2.
Following code will generate IllegalClippingException  when playing.

```
Uri uri = Uri.fromFile(new File(TEST_MEDIA_FILE));
ExtractorMediaSource extractorMediaSource = new ExtractorMediaSource.Factory(new 
        DefaultDataSourceFactory(this, "TEST APP")).createMediaSource(uri);
LoopingMediaSource loopingMediaSource = new LoopingMediaSource(extractorMediaSource, 3);
ClippingMediaSource clippingMediaSource = new ClippingMediaSource(loopingMediaSource, 0, C.TIME_END_OF_SOURCE);
mPlayer.prepare(clippingMediaSource);
```

However, create looping media source with loop limit = INT_MAX will not generate the exception.
What is more, using LoopingMediaSource to wrap a ClippingMediaSource will also avoid this issue.

Is it a bug or some sort of limitation?

**Comment by andrewlewis** [comment]
The limitation is that `ClippingMediaSource` will only clip a single-period/window source, but looping results in a multi-period timeline. What result are you aiming for? In the code snippet you're trying to clip from zero to the end of the source, which is like not having a clip at all.

**Comment by robin2046** [comment]
Use limited clip still reproduces the error:

```
        Uri uri = Uri.fromFile(new File(TEST_MEDIA_FILE));
        ExtractorMediaSource extractorMediaSource = new ExtractorMediaSource.Factory(new DefaultDataSourceFactory(this, "TEST APP")).createMediaSource(uri);
        LoopingMediaSource loopingMediaSource = new LoopingMediaSource(extractorMediaSource, 3);
        ClippingMediaSource clippingMediaSource = new ClippingMediaSource(loopingMediaSource, 0, 3000000);
        mPlayer.prepare(clippingMediaSource);
```

I understand that I may/should not use ClipSource to wrap a LoopSource, which does not sound correct as you said. But maybe throw a illegal argument exception is better because I don't know the limitation of ClipSource(can not clip multi-period timeline) before you explained it.

One more question, why ClipSource(LoopSource(ExtractSource, INT_MAX)) is OK?

**Comment by andrewlewis** [comment]
What are you actually trying to accomplish here? There's probably a way to do it using concatenation and clipping but it's not clear what result you're aiming for. If the goal is to loop some content until a certain duration and you know the content's duration, you could do this by looping the entire content `floor(total duration / content duration)` times then concatenating the result with a clip for the remainder.

At the time of creating the `ClippingMediaSource` we don't know the structure of the child source, so we can't throw an `IllegalArgumentException` from the constructor (if this is the suggestion).

It looks like `InfinitelyLoopingTimeline` doesn't declare multiple periods at the moment, which is why this works, I think. Setting a repeat mode on the player instead of using `LoopingMediaSource` may be a better way to loop indefinitely, depending on your use case.

**Comment by robin2046** [comment]
I use loop source to make the content playing for a limited loops.
Anyway, thanks a lot for your explanation. They are all clear to me now.
Really appreciate your great work.
