### ISSUE TITLE
AdsMediaSource doesnt play ads when device connected to 3g, but it plays ads on wifi.

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#4633]
Hello, I am using the last version of exoplayer and ima extension in my app:

```
implementation 'com.google.android.exoplayer:exoplayer:2.8.2'
implementation 'com.google.android.exoplayer:extension-ima:2.8.2'
```

For implementing ads into my video i use the next code:

```
 ImaSdkSettings imaSdkSettings = ImaSdkFactory.getInstance().createImaSdkSettings();
        imaSdkSettings.setAutoPlayAdBreaks(true);
        ImaAdsLoader adsLoader = new ImaAdsLoader.Builder(getActivity())
                .setImaSdkSettings(imaSdkSettings)
                .buildForAdTag(Uri.parse("ads url here"));

        AdsMediaSource adsMediaSource = new AdsMediaSource(
                buildMediaSource(uri),
                this,
                adsLoader,
                exoPlayerOnline.getOverlayFrameLayout());

        return adsMediaSource;
```

And it works well when device is connected to wifi. But after i change connection to 3g, ads doesnt load, i see only video without ads. How to resolve this problem? Thanks.

**Comment by andrewlewis** [comment]
If network connectivity is poor then ads may timeout or otherwise fail to load, in which case content will be played. You can try increasing the timeouts in [ImaAdsLoader.Builder](https://github.com/google/ExoPlayer/blob/ed18be4/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L128). If you set `ImaAdsLoader.DEBUG` to true and attach a bug report or logcat we should be able to confirm that timing out is the cause of ads not playing.
