### ISSUE TITLE
ClippingMediaSource is too much unprecise

### ISSUE THREAD

**Issue by igormisha** [google/ExoPlayer#4676]
I try to play short piece of mp3 audio (44100 samples rate) with exoPlayer using it's ClippingMediaSource but it cuts the start of the piece for about 250 milliseconds, it's too much, is it possible to make it more precise? 

I start exoplayer like this:

```
dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "org.imagency.repeatplayer"));
Uri uri = Uri.fromFile(new File(path));
MediaSource audioSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
ExoPlayer exoPlayer = ExoPlayerFactory.newSimpleInstance(context, new DefaultTrackSelector());
exoPlayer.setPlayWhenReady(true);
ClippingMediaSource clip = new ClippingMediaSource(audioSource, 7_225_000, 8_175_000);
exoPlayer.prepare(clip);
```

**Comment by ojw28** [comment]
MP3 isn't a good format choice if you need accurate seeking (clipping included). If you need accurate seeking then you should really consider using MP4 instead, which does a much better job of supporting sample accurate seeking. Do you see the same issue when using MP4?

**Comment by igormisha** [comment]
I'll try with MP4 file and give you feedback but shouldn't mp3 play with presicion of one mp3 frame, which is typically 1152 samples length (my mp3 file's frames have exactly 1152 samples) and with sample rate of 44100 in worst case it should eat maximum 0.027 seconds but not 0.25 seconds.

**Comment by ojw28** [comment]
The problem isn't the frame size, but the way in which MP3 files index their content (they don't do a particularly good job of it). It's worth noting that MP3 is considered obsolete even by those who created it ;).

Please try with MP4 files, since that will allow us to determine whether this is a result of the file format you're using, or whether there's more of a genuine issue. If you can reproduce with MP4 files, please provide complete reproduction steps, and sample content that will allow us to reproduce what you're seeing. Thanks.

**Comment by igormisha** [comment]
I've checked playing same clip with MP4 file and it played precisely.

**Comment by igormisha** [comment]
May be mp3 format is obsolete but it's still widely used.. I'd like to support it in my app.

**Comment by igormisha** [comment]
Also I've made a composition of LoopingMediaSource with that clip (play 3 times) and in case of MP4 file everything worked as expected and with MP3 file it even didn't play 3 times, just a couple of parts of the clip and these parts were not the same.

**Comment by ojw28** [comment]
We do support MP3. We just don't support accurate seeking in MP3. How accurate seeking in an MP3 is will depend quite a lot on the file. There are multiple different ways in which MP3 files can choose to support seeking (it's a bit of a mess), and the accuracy varies between them. It is of course possible to seek accurately by scanning the entire file beforehand, since by doing that you can build up a complete mapping from time to byte-offset. We have no plans to support doing this, however, and it does also require reading the whole file in advance.

> with MP3 file it even didn't play 3 times, just a couple of parts of the clip and these parts were not the same.

If you provide proper reproduction steps and test content, we'll take a look.

**Comment by igormisha** [comment]
**The exoplayer version:** 
com.google.android.exoplayer:exoplayer-core:2.8.3

**Devices:** 
Emulator:
Default Android Studio Emulator (API 28), 
Real devices: Lenovo 903N, Xiaomi 3S.

**The code to create a looping media source and play it is:**

```
String path = Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "mono.mp3";
Context context = getApplicationContext();
dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "org.imagency.repeatplayer"));
Uri uri = Uri.fromFile(new File(path));
MediaSource audioSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
ExoPlayer exoPlayer = ExoPlayerFactory.newSimpleInstance(context, new DefaultTrackSelector());
exoPlayer.setPlayWhenReady(true);
ClippingMediaSource clip = new ClippingMediaSource(audioSource, 7_225_000, 8_175_000);
LoopingMediaSource loop = new LoopingMediaSource(clip, 3);
exoPlayer.prepare(clip);
```

T**he link to mp3 file:** https://files.fm/u/kz3xzwwj . 
If played correctly it should play say the phrase "Let me take you on the journey" 3 times. But it's not.

**Comment by ojw28** [comment]
Thanks. The issue is basically as described above (i.e. mp3 files not supporting accurate seeking). The reason you see the inconsistent behavior is as follows:

* MP3 files do not do a good job of supporting accurate seeking. Hence full seeks will not be accurate.
* ExoPlayer has two code paths that it can follow when a seek occurs. It will first attempt to seek into the already buffered media, for efficiency. If it can't do this, it'll do a full seek that includes re-buffering.
* The inconsistent behavior you're seeing arises from some seeks following the in-memory path, and others following the full seek path. The in-memory path is likely to be accurate, because it's equivalent to having build up a complete time to byte-offset mapping of the file up to the seek position. Whether the player has time to do this before the seek occurs is effectively a race, and dependent on things like how far into the file the starting position is of the clipped region, the buffering policy, etc. The full seek path is likely to be inaccurate.
 
In any case, using a file format that's better suited to support accurate seeking resolves the issue, and should give identical results along both paths. I don't think we're going to spend any time "fixing" this, sorry.

**Comment by igormisha** [comment]
Thanks for the explanation, I thought that as far as exoplayer is built upon mediaExtractor, mediaCodec and audioTrack and mediaExtractor has method seekTo(long position, int mode) where mode is one of SEEK_TO_CLOSEST_SYNC, SEEK_TO_NEXT_SYNC and SEEK_TO_PREVIOUS_SYNC which I supposed can seek precisely to the beginning of previous or next mp3 frame (frame size is 1152 sample) which means that the maximum deviation from defined clip start position shouldn't be more than 0.027 sec for 44100 sample rate mp3 audio.

**Comment by ojw28** [comment]
ExoPlayer does not use `MediaExtractor`. I think the `SEEK_TO_*` constants you reference are in practice caveated with "as far as is reasonably possible". If the format doesn't support seeking in the way those constants specify, then I believe you'll get a best effort instead. If and when `MediaExtractor` is able to seek more accurate than ExoPlayer, the implementation almost certainly trades off efficiency (e.g. by requiring the whole stream to be downloaded in advance of playback starting) to achieve the higher accuracy level. Some formats just have fundamental limitations, which is why new and better formats have been devised to replace them ;).
