### ISSUE TITLE
How to change app:controller_layout_id programmatically

### ISSUE THREAD

**Issue by fongfuse** [google/ExoPlayer#4700]
I would like to set `app:controller_layout_id` programmatically?
thanks!

**Comment by ojw28** [comment]
It is not possible to dynamically change the layout id (i.e. after `PlayerView` has been constructed). If that's what you're trying to do then it's not something we support, and you may have to look at implementing your own UI components to support your use case.

If you're just trying to specify the layout id when a `PlayerView` is being instantiated, then that's probably possible, although I'm unsure why you'd need to do that, since I think you could just inflate a `PlayerView` from a layout xml to achieve the same thing.

Please clarify your exact use case.

**Comment by ojw28** [comment]
Closing as answered, but if you have follow up questions please feel free to respond here anyway, and we'll do our best to answer them.
