### ISSUE TITLE
question: difference between Player.EventListener() and AnalyticsListener().

### ISSUE THREAD

**Issue by jessloran** [google/ExoPlayer#4703]
Hi. I am adding a listener to my player instance like:

`player.addListener(new Player.EventListener() {...});`

and I am using:

```
public void onPlayerStateChanged(boolean playWhenReady, int playbackState)
public void onPlayerError(ExoPlaybackException error)
```

To do some processing on starting/stopping the audio track and encountering errors.

I have decided to work on an equalizer. I have discovered that there is not a way to acquire the audio session id through Player.EventListener() and it is available in AnalyticsListener() only. So, I have added AnalyticsListener/used onAudioSessionId plus DecoderDisabled:

`player.addAnalyticsListener(new AnalyticsListener(){});`

and it works fine. Though, on one of so many tries, the code on onPlayerStateChanged was not carried out on Player.EventListener(). I have noticed that AnalyticsListener() also contains onPlayerStateChanged and onPlayerError. So, I have some questions.

1. Can Player.EventListener and AnalyticsListener events conflict with one another? I am only using onPlayerStateChanged and onPlayerError on Player.EventListener only and not on AnalyticsListener.
2. Can I safely move the code from the events on Player.EventListener into associated events in AnalyticsListener without causing any issues then get rid of the Player.EventListener() listener?
3. Since onAudioSessionId is part of the equalizer requirement. Why is not available in Player.EventListener and any chance it would be moved to Player.EventListener later on?
4. Can using the equalizer have any performance/speed impact on onPlayerStateChanged/onPlayerError events at all?

Thank you so much for taking the time to read this. I appreciate it.

**Comment by ojw28** [comment]
> I have discovered that there is not a way to acquire the audio session id through Player.EventListener() and it is available in AnalyticsListener() only.

It's available through `AudioListener`, and you should use this for what you're trying to do, rather than `AnalyticsListener`. You can add an `AudioListener` by calling `addAudioListener` on your `SimpleExoPlayer` instance.

> Can I safely move the code from the events on Player.EventListener into associated events in AnalyticsListener without causing any issues then get rid of the Player.EventListener() listener?

`AnalyticsListener` is really intended for logging/analytics, rather than potentially user visible application logic. You should use `EventListener` and `AudioListener` instead.

> Can using the equalizer have any performance/speed impact on onPlayerStateChanged/onPlayerError events at all?

I'm not really sure what this means, but I don't think so.

**Comment by jessloran** [comment]
Thank you so much for information, @ojw28. I have tried using addAudioListener on my player instance but it I could not find it. I have referred to the documentation for SimpleExoPlayer:

https://google.github.io/ExoPlayer/doc/reference/

Though, all I could find is addAudioDebugListener which is deprecated in favor of addAnalyticsListener(AnalyticsListener).

My current ExoPlayer version is 2.8.2 I do not know if that matters or not.

**Comment by ojw28** [comment]
Ah, `addAudioListener` is only available in the `dev-v2` branch currently. It'll be part of 2.9.0. Given the end goal of using `EventListener` and `AudioListener`, I'd be tempted to use `EventListener` the the deprecated `addAudioDebugListener` for now, and switch the latter over to `AudioListener` when available.

**Comment by jessloran** [comment]
Thank you for the advice. I will follow it. I suppose onAudioDisabled on AudioDebugListener is the equivalent of onDecoderDisabled where I release the equalizer?

**Comment by ojw28** [comment]
Yep!

By the way, only alternative model is to extend `MediaCodecAudioRenderer` and override `onAudioSessionId` (and I guess `onDisabled`). Then make it so your extension renderer is used rather than the standard one when building the player. The benefit of this approach is that the equalizer logic becomes "part of the player", which conceptually makes sense. These methods are also called on the playback thread, rather than the main thread, which guarantees you wont ever process the audio session id later than you wanted to.

**Comment by jessloran** [comment]
Thank you so much for the valuable information, ojw28.
