### ISSUE TITLE
I want to play two audio simultaneously using exoplayer. Non of media source working with this case. How i can achieve this?

### ISSUE THREAD

**Issue by lokeshdesai403** [google/ExoPlayer#4713]
I have override buildAudioRenderers in DefaultRenderersFactory, and getMediaClock in MediaCodecAudioRenderer. Also I implement TrackSelector. In that way I can play all audio track simultaneously. But issue is i can only add upto 10-20 tracks after that Exoplyer stop working.

**Comment by ojw28** [comment]
This is likely due to underlying platform limitations (e.g. on the amount of `AudioTrack` buffer space that the device can allocate). Your use case sounds quite unusual, but I think to do what you're trying to do, you probably need to do some mixing of the audio prior to it entering `AudioTrack`, so that you only have one `AudioTrack` instance. This is not something we support directly.

**Comment by lokeshdesai403** [comment]
If one audio is already playing using one AudioTrack instance. than for playing another audio file i have to make another instance. Isn't it?

**Comment by ojw28** [comment]
There's nothing stopping you from mixing the audio yourself before it's fed into `AudioTrack`. Such an approach would let you play an arbitrarily large number of streams using a single `AudioTrack` instance. As above, this isn't something we support directly, so you'd need to figure out how to implement it yourself.
