### ISSUE TITLE
Support Shoutcast Icy protocol

### ISSUE THREAD

**Issue by mingfai** [google/ExoPlayer#473]
the solution that works in the previous dev branch doesn't work in the latest r1.3.2 release
https://github.com/google/ExoPlayer/issues/389#issuecomment-93034317

The code that fail to run is similar to the following
```
new Sample("Icy",
        "icy://HOST_NAME:8128/;?stream.mp3",
        DemoUtil.TYPE_MP3),
```

result as exception:
```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.DefaultUriDataSource$UnsupportedSchemeException: Unsupported URI scheme: icy
```

if i change the url to http://, it doesn't work in a test Android 4.3

Is there any way to use Icy protocol?

**Comment by ojw28** [comment]
The problem is that DefaultUriDataSource now only allows specific URI schemes, and icy isn't one of them because it's not supported directly by the library. I'm not really sure what the "right" solution to this is, but to get things to work in the meantime you should either:

- Use DefaultHttpDataSource directly, instead of DefaultUriDataSource.
- Add a `SCHEME_ICY.equals(scheme)` check to select DefaultHttpDataSource at [this line](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java#L144).

**Comment by mingfai** [comment]
thx. when i changed to DefaultHttpDataSource, the previous solution (https://github.com/google/ExoPlayer/issues/389#issuecomment-93034317) works again.

**Comment by ojw28** [comment]
Great. For the next release, I think it makes sense if we have DefaultUriDataSource delegate to DefaultHttpDataSource by default if it doesn't recognize the scheme (which would have worked for this case).
