### ISSUE TITLE
Renderer Error in SimpleExoplayer.onPlayerError() for Android API 19 

### ISSUE THREAD

**Issue by pagrawal1407** [google/ExoPlayer#4751]
I am getting a renderer error in the SimpleExoPlayer.onPlayerError() method. 
In the ExoPlaybackException object the the rendererIndex is -1 and it shows cause as java.lang.IllegalStateException.

Is this related to the length of video (The video I am playing is 11 mins long) or is it something else?

<img width="1677" alt="screen shot 2018-08-29 at 12 19 40 pm" src="https://user-images.githubusercontent.com/10719473/44810233-f721fd00-ab85-11e8-8b76-870ca9ad3ae3.png">

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
