### ISSUE TITLE
Sound and video are out of sync when playing multiples

### ISSUE THREAD

**Issue by feiyang1235** [google/ExoPlayer#4759]
In some custom rom. Sound and video are out of sync when playing multiples, the video and sound is stuck.
I am a newbie。could anyone give me some advice?

**Comment by feiyang1235** [comment]
i use the media source is HLS

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
