### ISSUE TITLE
Widevine provisioning failing on Android 9 Pixel 2 device

### ISSUE THREAD

**Issue by spakanati123** [google/ExoPlayer#4772]
We are trying to validate our existing production app on Android 9 device(Pixel 2) but the playback getting failed with the following stack trace:

```
Failed to handle provision response: General DRM error(com.quickplay.plugin.player.exoplayer:10403) - see exception  for the detail.\
    Exception:android.media.MediaDrm$MediaDrmStateException: Failed to handle provision response: General DRM error\
        at android.media.MediaDrm.provideProvisionResponseNative(Native Method)\
        at android.media.MediaDrm.provideProvisionResponse(MediaDrm.java:973)\
        at com.quickplay.google.android.exoplayer.drm.FrameworkMediaDrm.provideProvisionResponse(:138)
```
Version of ExoPlayer
2.6.1

Device:
Pixel 2

Android Version:
9.0

Content: WIDEWINE + DASH

Full bug report: emailed to dev.exoplayer@gmail.com

issue observed only on Android 9, lower versions playback is fine.

**Comment by tonihei** [comment]
Could you please provide us with an example file and Widevine license to reproduce the problem? Thanks!

**Comment by sp8004** [comment]
@tonihei the content has geo-restriction and also authorization restriction,
 is the bug report not help out ??

**Comment by tonihei** [comment]
Unfortunately the bug report doesn't contain much more information than what you already posted above. So it would be great if we could reproduce the issue ourselves.

**Comment by sp8004** [comment]
Hi Tonihei,
Thanks for the reply, we did more analysis from our side and found the root cause for the issue.
The issue seems to be Device DRM Session Manager throwing DRMStateException for the provided Provision Response.

We have our own Library(SDK) for playback and we have the sample app which demonstrate the our library features. The Provision Response working fine our sample app application id(playback success) but we have clients who are using our Library but for their application id’s Provision Response DRM Session Manager throwing DRMStateException.


09-10 18:02:54.769  9787  9979 D VSTB    : PlayerRequestManager.ॱ(749)              Player Request Disassocited: PlaybackManagerPlayerAgentAssociator@224113871[PlaybackController@244948310{mPlaybackItem=PlaybackCatalogItem{mContentItem=[ContentItem(900273, null, )], mUsesServerDefaults=false}, mState=PREPARING},ExoDRMAgentService@138325646{Opened},ExoPlayerVstbImpl@208607932{CLOSED}] due to VSTBErrorInfo@2e5b2ed[errorCode=1009,domain=com.quickplay.vstb.core,errorDescription=Error from Internal Player: com.quickplay.vstb.plugin.player:9290/DRM Session Manager Error Failed to handle provision response: General DRM error(com.quickplay.plugin.player.exoplayer:10403) - see exception  for the detail.
09-10 18:02:54.769  9787  9979 D VSTB    : Exception:android.media.MediaDrm$MediaDrmStateException: Failed to handle provision response: General DRM error
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.media.MediaDrm.provideProvisionResponseNative(Native Method)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.media.MediaDrm.provideProvisionResponse(MediaDrm.java:973)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.google.android.exoplayer.drm.FrameworkMediaDrm.provideProvisionResponse(:138)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager.ॱ(:485)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager.ˊ(:57)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager$ᐝ.handleMessage(:685)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.Handler.dispatchMessage(Handler.java:106)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.Looper.loop(Looper.java:193)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.HandlerThread.run(HandlerThread.java:65)


Please help us to proceed further to fix this problem.
I attached the Charles to verify the Provision request and response for the failed application id.



Thanks
-satya

**Comment by sp8004** [comment]
Hi Tonihei,
Thanks for the reply, we did more analysis from our side and found the root cause for the issue.
The issue seems to be Device DRM Session Manager throwing DRMStateException for the provided Provision Response.

We have our own Library(SDK) for playback and we have the sample app which demonstrate the our library features. The Provision Response working fine our sample app application id(playback success) but we have clients who are using our Library but for their application id’s Provision Response DRM Session Manager throwing DRMStateException.


09-10 18:02:54.769  9787  9979 D VSTB    : PlayerRequestManager.ॱ(749)              Player Request Disassocited: PlaybackManagerPlayerAgentAssociator@224113871[PlaybackController@244948310{mPlaybackItem=PlaybackCatalogItem{mContentItem=[ContentItem(900273, null, )], mUsesServerDefaults=false}, mState=PREPARING},ExoDRMAgentService@138325646{Opened},ExoPlayerVstbImpl@208607932{CLOSED}] due to VSTBErrorInfo@2e5b2ed[errorCode=1009,domain=com.quickplay.vstb.core,errorDescription=Error from Internal Player: com.quickplay.vstb.plugin.player:9290/DRM Session Manager Error Failed to handle provision response: General DRM error(com.quickplay.plugin.player.exoplayer:10403) - see exception  for the detail.
09-10 18:02:54.769  9787  9979 D VSTB    : Exception:android.media.MediaDrm$MediaDrmStateException: Failed to handle provision response: General DRM error
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.media.MediaDrm.provideProvisionResponseNative(Native Method)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.media.MediaDrm.provideProvisionResponse(MediaDrm.java:973)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.google.android.exoplayer.drm.FrameworkMediaDrm.provideProvisionResponse(:138)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager.ॱ(:485)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager.ˊ(:57)
09-10 18:02:54.769  9787  9979 D VSTB    :            at com.quickplay.vstb.exoplayer.service.drm.CachedDrmSessionManager$ᐝ.handleMessage(:685)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.Handler.dispatchMessage(Handler.java:106)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.Looper.loop(Looper.java:193)
09-10 18:02:54.769  9787  9979 D VSTB    :            at android.os.HandlerThread.run(HandlerThread.java:65)


Please help us to proceed further to fix this problem.
I attached the Charles to verify the Provision request and response for the failed application id.



Thanks
-satya

**Comment by sp8004** [comment]
@tonihei Please check email reply to dev.exoplayer@gmail.com with our analysis.

**Comment by tonihei** [comment]
Looks like you are using a custom class called CachedDrmSessionManager to call the ExoPlayer FrameworkMediaDrm. methods. Could you please verify you are seeing the same error with ExoPlayer's default drm session manager? If not, this is likely a problem in the CachedDrmSessionManager class and needs to be fixed there.

**Comment by sp8004** [comment]
@tonihei  We are using the CachedDrmSessionManager just to cache the license and the remaining logic is same as DefaultDrmSessionManager, i tried with DefaultDrmSessionManager but still i can observe the issue.

Please let me understand me on the point that,
- when OS upgraded the Provision Request going on and the response validated successfully for one application id but if i change to any other application id's response validation getting failed, what will be the reason?

**Comment by kartdroid** [comment]
@tonihei we are facing problems during  provisioning itself. (not during content specific Key request/loading)

Here is the problem we are facing

-  Upgraded Pixel 2 to Android 9
- We tried playing a content and a Provisioning Request is triggered (we had the **package name as x.y.z**) and the provisioning response was provided to the DRM Framework without any issues / exceptions 
- **We changed the package name to "a.b.c"** and then tried playing the content. And now the provisioning request is successful but fails when we provide the response to DRM Framework 

Does the Provision Request Payload include package name and does that impact the response given back by the provisioning server ?
Does the pakage name impact provisioning in any way.

**Comment by ojw28** [comment]
> We are using the CachedDrmSessionManager just to cache the DRM keys

What does this mean exactly? It's not valid to cache key responses (probably provision responses too, although I'm not certain about that). Each response is tied to the corresponding uniquely generated request.

**Comment by sp8004** [comment]
@ojw28 we cache the license to avoid the multiple license call for the same content and it's not intended for provision response.
The problem is, on lower android versions all our application id's working fine when we provide the Provision response to DRM Framework but on Android 9 only one application id working.
This problem we are facing only Pixel 2 whereas on Pixel 1 it's working fine.

We want to understand, how the application id(package name) impact provisioning.

**Comment by kartdroid** [comment]
@ojw28  am from the same team as @sp8004 .
The issue is reproducible even if we use DefaultDrmSessionManager (with a clean install of the application) 

Kindly help us in understanding more on Provisioning request/response flow as mentioned in 
https://github.com/google/ExoPlayer/issues/4772#issuecomment-420348714

Thanks !

**Comment by ojw28** [comment]
My understanding of provisioning was that it happened once for the whole device (i.e. as soon as some app has provisioned, that should be all that's required). I also thought devices with Widevine L1 didn't need provisioning at all, since they're provisioned in the factory. Guess I'm wrong though. Or perhaps something changed in P.

@paf-wv - Could you shed some light on this? Thanks!

**Comment by spakanati123** [comment]
**this is the output from Kaltura Device Info app to check device DRM status info:**
```
{
    "meta": {
        "versionName": "1.3.1",
        "versionCode": 16,
        "timestamp": "2018-09-12T11:03:08Z"
    },
    "system": {
        "RELEASE": "9",
        "SDK_INT": 28,
        "BRAND": "google",
        "MODEL": "Pixel 2",
        "MANUFACTURER": "Google",
        "DEVICE": "walleye",
        "BOARD": "msm8998",
        "TAGS": "release-keys",
        "FINGERPRINT": "google/walleye/walleye:9/PPR2.180905.005/4928864:user/release-keys",
        "ARCH": {
            "os.arch": "aarch64",
            "SUPPORTED_ABIS": [
                "arm64-v8a",
                "armeabi-v7a",
                "armeabi"
            ],
            "SUPPORTED_32_BIT_ABIS": [
                "armeabi-v7a",
                "armeabi"
            ],
            "SUPPORTED_64_BIT_ABIS": [
                "arm64-v8a"
            ]
        }
    },
    "drm": {
        "modular": {
            "widevine": {
                "properties": {
                    "vendor": "Google",
                    "version": "14.0.0",
                    "description": "Widevine CDM",
                    "algorithms": "AES/CBC/NoPadding,HmacSHA256",
                    "securityLevel": "L1",
                    "systemId": "7351",
                    "privacyMode": "disable",
                    "sessionSharing": "disable",
                    "usageReportingSupport": "True",
                    "appId": "",
                    "origin": "",
                    "hdcpLevel": "Disconnected",
                    "maxHdcpLevel": "HDCP-2.2",
                    "maxNumberOfSessions": "50",
                    "numberOfOpenSessions": "1",
                    "deviceUniqueId": "WuHlI2w45eRzhWVib5ALww6z2fAcf+UW452xPNepVL4=",
                    "provisioningUniqueId": "pR4a3JPHGhuMepqdkG/0PPFMJg/jgBrpHGJOwyhWq0E=",
                    "serviceCertificate": ""
                },
                "events": [
                    {
                        "Exception(openSession)": "android.media.NotProvisionedException: Failed to open session"
                    },
                    {
                        "event": 1,
                        "extra": 0
                    }
                ]
            }
        },
        "classic": {
            "engines": [
                "OMA V1 Forward Lock"
            ]
        }
    },
    "display": {
        "metrics": "DisplayMetrics{density=2.625, width=1080, height=1794, scaledDensity=2.625, xdpi=442.451, ydpi=443.345}"
    },
    "media": {
        "decoders": {
            "OMX.google.aac.decoder": {
                "supportedTypes": [
                    "audio/mp4a-latm"
                ]
            },
            "OMX.google.amrnb.decoder": {
                "supportedTypes": [
                    "audio/3gpp"
                ]
            },
            "OMX.google.amrwb.decoder": {
                "supportedTypes": [
                    "audio/amr-wb"
                ]
            },
            "OMX.google.flac.decoder": {
                "supportedTypes": [
                    "audio/flac"
                ]
            },
            "OMX.google.g711.alaw.decoder": {
                "supportedTypes": [
                    "audio/g711-alaw"
                ]
            },
            "OMX.google.g711.mlaw.decoder": {
                "supportedTypes": [
                    "audio/g711-mlaw"
                ]
            },
            "OMX.google.gsm.decoder": {
                "supportedTypes": [
                    "audio/gsm"
                ]
            },
            "OMX.google.mp3.decoder": {
                "supportedTypes": [
                    "audio/mpeg"
                ]
            },
            "OMX.google.opus.decoder": {
                "supportedTypes": [
                    "audio/opus"
                ]
            },
            "OMX.google.raw.decoder": {
                "supportedTypes": [
                    "audio/raw"
                ]
            },
"OMX.google.vorbis.decoder": {
                "supportedTypes": [
                    "audio/vorbis"
                ]
            },
            "OMX.qcom.video.decoder.avc": {
                "supportedTypes": [
                    "video/avc"
                ]
            },
            "OMX.qcom.video.decoder.avc.secure": {
                "supportedTypes": [
                    "video/avc"
                ]
            },
            "OMX.google.h264.decoder": {
                "supportedTypes": [
                    "video/avc"
                ]
            },
            "OMX.qcom.video.decoder.h263": {
                "supportedTypes": [
                    "video/3gpp"
                ]
            },
            "OMX.google.h263.decoder": {
                "supportedTypes": [
                    "video/3gpp"
                ]
            },
            "OMX.qcom.video.decoder.hevc": {
                "supportedTypes": [
                    "video/hevc"
                ]
            },
            "OMX.qcom.video.decoder.hevc.secure": {
                "supportedTypes": [
                    "video/hevc"
                ]
            },
            "OMX.google.hevc.decoder": {
                "supportedTypes": [
                    "video/hevc"
                ]
            },
            "OMX.qcom.video.decoder.mpeg4": {
                "supportedTypes": [
                    "video/mp4v-es"
                ]
            },
            "OMX.google.mpeg4.decoder": {
                "supportedTypes": [
                    "video/mp4v-es"
                ]
            },
            "OMX.qcom.video.decoder.vp8": {
                "supportedTypes": [
                    "video/x-vnd.on2.vp8"
                ]
            },
            "OMX.google.vp8.decoder": {
                "supportedTypes": [
                    "video/x-vnd.on2.vp8"
                ]
            },
            "OMX.qcom.video.decoder.vp9": {
                "supportedTypes": [
                    "video/x-vnd.on2.vp9"
                ]
            },
            "OMX.qcom.video.decoder.vp9.secure": {
                "supportedTypes": [
                    "video/x-vnd.on2.vp9"
                ]
            },
            "OMX.google.vp9.decoder": {
                "supportedTypes": [
                    "video/x-vnd.on2.vp9"
                ]
            }
        }
    },
    "root": {
        "existingFiles": []
    }
}
```

I can see **NotProvisionedException** on Pixel 2 but on Pixel 1 and Pixel XL i can't see this exception.

**"Exception(openSession)": "android.media.NotProvisionedException: Failed to open session"**

**Comment by fredgc** [comment]
Devices need to be provisioned with a DRM Certificate.  This DRM certificate is used by the license server to verify the device.  Previously, there was one DRM certificate on the device, so any application could provision for the whole device.
Now, each application, or origin, will have a separate DRM Certificate.  If you change the application package you should expect a new "needs provisioning" exception.  Also, if there is some error on the device, we might also wipe out the certificate and you will need to provision again.

**Comment by ojw28** [comment]
In that case, please could you look at why provisioning is failing in this case? Thanks

**Comment by fredgc** [comment]
If you are trying to play the content using package "a.b.c", then you need to provision using package "a.b.c".  You cannot provision with package "x.y.z" and then play with "a.b.c".

**Comment by ojw28** [comment]
I think the problem is simply that when the package is "a.b.c" (I assume this isn't the real package name), provisioning is failing. So the question is why.

**Comment by fredgc** [comment]
@spakanati123, can you verify that you are attempting playback from the same package that you used to provision?  If provisioning is failing, can you send us a logcat that covers the entire session -- i.e. start gathering logs before you attempt playback, and keep gathering logs until the provisioning fails.

**Comment by fredgc** [comment]
Also, make sure you provide the provisioning response to the same object/session that you used to generate the provisioning request.  State data is held in a session for that object, and it is not shared with other sessions -- this is by design to prevent replay attacks.

**Comment by spakanati123** [comment]
@fredgc we sent full bug report while raising the bug initially.
can u please check initial email sent to dev.exoplayer@gmail.com

**Comment by fredgc** [comment]
Please check that your code is only creating one provisioning request, and is processing the response from that request.  I see in the logs:
09-04 11:01:17.816 ... CdmEngine::GetProvisioningRequest
and shortly after a second request:
09-04 11:01:17.981 ... CdmEngine::GetProvisioningRequest
with the error about a replay attach here:
09-04 11:01:19.261 ... OEMCrypto_RewrapDeviceRSAKey fails with 32

If you are sure you only create one request, I can try to reproduce it.  Can you send us code samples that reproduces the problem?

**Comment by spakanati123** [comment]
@fredgc 
Doing provisioning request is part of the Exo Player code.
Please refer DefaultDrmSession.java# openInternal()

```
private boolean openInternal(boolean allowProvisioning) {
    if (isOpen()) {
      // Already opened
      return true;
    }

    try {
      sessionId = mediaDrm.openSession();
      mediaCrypto = mediaDrm.createMediaCrypto(sessionId);
      state = STATE_OPENED;
      return true;
    } catch (NotProvisionedException e) {
      if (allowProvisioning) {
        provisioningManager.provisionRequired(this);
      } else {
        onError(e);
      }
    } catch (Exception e) {
      onError(e);
    }

    return false;
  }

  Since initially device not provisioned calling sessionId = mediaDrm.openSession() will throw NotProvisionedException and from here provision request triggered.


  DefaultDrmSessionManager.java

    @Override
  public void provisionRequired(DefaultDrmSession<T> session) {
    provisioningSessions.add(session);
    if (provisioningSessions.size() == 1) {
      // This is the first session requesting provisioning, so have it perform the operation.
      session.provision();
    }
  

  @Override
  public byte[] executeProvisionRequest(UUID uuid, ProvisionRequest request) throws IOException {
    String url =
        request.getDefaultUrl() + "&signedRequest=" + Util.fromUtf8Bytes(request.getData());
    return executePost(dataSourceFactory, url, new byte[0], null);
  }

```
  Please check the Exo player code of above to classes for further clarification on getting provision req url from framework media drm.

cc: @ojw28

**Comment by ojw28** [comment]
@fredgc - Can you tell from the logs whether the provisioning requests were generated for different `MediaDrm` instances, or from the same instance?

* If both requests are generated by the the same `MediaDrm` instance, then that would probably be an ExoPlayer bug. We do have logic that's supposed to make sure only one provisioning request is ever in flight, however, and I can't spot much wrong with it (ref: `DefaultDrmSessionManager.provisionRequired`). That logic was in place in 2.6.1, which is the version being used.
* If the requests were generated by different `MediaDrm` instances, then I'd expect the platform to handle that. For example if instance A generates request X, instance B generates a request Y, and then the response for X is provided back to instance A, I'd expect that to work. I'd also expect the response for Y being provided back to instance B to appear as though it succeeds, even if it's a no-op in practice because the device is already provisioned at that point. If the platform doesn't support that then applications would be required to implement a global lock around anything that could generate a provisioning request, which is not really feasible (e.g. suppose code that might generate such requests is contained within two libraries on which an application depends). Could you confirm whether or not this case is handled by the platform?

**Comment by ojw28** [comment]
Some further findings:

* I tried simulating the different `MediaDrm` instances sequence described in my second bullet point above, and provisioning worked as expected.
* I tried using the ExoPlayer 2.6.1 demo app on Pixel 2 running Android 9. Only a single provisioning request was made and provisioning worked as expected.

@spakanati123 - Are you certain you're using vanilla ExoPlayer 2.6.1, without any modification? The generation of two provisioning requests as Fred has noted in the logs does not seem to happen when using ExoPlayer 2.6.1 for me. Are you able to reproduce using the ExoPlayer demo app (possibly with its package renamed to whatever you're finding causes provisioning to fail)? If you really think it's specific to having a particular package name, you'll likely need to share with us what that particular package name is.

**Comment by ojw28** [comment]
Our best guess is still that the application is doing something unusual here:

* It's hard to be sure, but the bug report you've provided suggests that non-ExoPlayer code in your app may be instantiating a `MediaDrm` and generating a provisioning request from it. Are you aware of any code that does this? Are you using ExoPlayer wrapped within inside a third party library that could be doing this?
* Our best hypothesis (pretty much just an educated guess) is that app code is somehow feeding the provisioning response intended for that `MediaDrm` instance into a different `MediaDrm` instance that's used by ExoPlayer. Perhaps as a result of some response caching in or under `MediaDrmCallback.executeProvisionRequest`.

We remain unable to reproduce this using the ExoPlayer demo app, running on a Pixel 2 with Android 9. This also suggests an app specific issue.

For us to investigate further, I think we'll need some concrete reproduction steps.

**Comment by spakanati123** [comment]
I have tried to reproduce the issue on Exo player demo app but i can't see the issue on 2.6.1 as well on latest. We have plans to upgrade the Exo Player to 2.8.* so please lock the conversation as of now and we will try to get more info once we upgrade to latest Exo Player ver.
-Thanks for the support.

**Comment by fredgc** [comment]
OK. I'll mark this as closed. Please re-open if there is more on this issue that you need from us.
