### ISSUE TITLE
Did something change with audio track sync from 2.8.2 to 2.8.4?

### ISSUE THREAD

**Issue by ebr11** [google/ExoPlayer#4774]
We recently upgraded from 2.8.2 to 2.8.4 and now have some content where audio plays out of sync with the video.  Move back to 2.8.2 and the sync issue is gone.

I can try to provide a sample if needed but wanted to check if there is some known change that we can adjust to.

Thanks.

**Comment by tonihei** [comment]
We are not aware of any change which causes synchronization problems. Also depends on the type of media you are using to answer that question. Can you provide us with an example? If you don't want to post it publicly, please send it to dev.exoplayer@gmail.com with "Issue #4474" in the subject.

**Comment by ebr11** [comment]
Sample emailed.

Thanks.

**Comment by tonihei** [comment]
Thanks for the sample. It seems [this commit of 2.8.3](https://github.com/google/ExoPlayer/commit/0a46e74105eb51f3499ec544260e25a2ac2f6848) fixed #4348 but broke your sample. 

The reason is that in both cases the file contains edit lists which do not start from a keyframe.
1) In your case, it's the first (and only) edit list. Although we don't properly support this, we can safely ignore the problem. It only means that at the very beginning there is only audio and a frozen video until the time of the first video keyframe is reached. This is barely noticeable in your case.
2) In the case of #4348, the second edit list also doesn't start with a keyframe. In that case, we can't just ignore it because the video decoder will mix up all samples and seriously distort the video because there is no valid keyframe at the beginning of the second edit list.

Will push a fix which keeps the edit lists disabled for cases as in #4348, but keeps them if only the first edit list doesn't start with a keyframe.

**Comment by ebr11** [comment]
Thanks very much.

**Comment by ebr11** [comment]
Hi.  Has this been addressed yet?

**Comment by tonihei** [comment]
Yes, it will be part of the next release.

**Comment by ebr11** [comment]
Okay, thanks.  Just out of curiosity, can you point me to the commit :).

**Comment by ojw28** [comment]
The commit will appear in this thread when it's pushed to GitHub.
