### ISSUE TITLE
padding right and left DefaultTimeBar

### ISSUE THREAD

**Issue by aderinto05** [google/ExoPlayer#4775]
Can we remove paddingRight and paddingBottom in DefaultTimeBar?

![screenshot_20180831-233536_mivo](https://user-images.githubusercontent.com/40485371/45074649-7bd4c400-b10e-11e8-9242-24b3ced691bf.jpg)

I use this library:
    compile 'com.google.android.exoplayer:exoplayer:r2.5.4'
    compile 'com.google.android.exoplayer:exoplayer-core:r2.5.4'
    compile 'com.google.android.exoplayer:exoplayer-dash:r2.5.4'
    compile 'com.google.android.exoplayer:exoplayer-ui:r2.5.4'

**Comment by ojw28** [comment]
The gap you see is exactly the size required so that the scrubber (the round dot that indicates the current position, and that can be dragged by the user) can be centered on the start and end of the progress bar without being clipped. In other words, the gap is equal to the radius of the scrubber in its largest mode. We don't add any extra padding beyond this, and removing what padding is there would cause the scrubber to be incorrectly clipped.

If you don't need to scrubber at all, you can remove the padding by giving the scrubber a size of 0 in all modes, which you can do by specifying the following on a `DefaultTimeBar` in layout xml:
```
app:scrubber_enabled_size="0dp"
app:scrubber_disabled_size="0dp"
app:scrubber_dragged_size="0dp"
```
You should probably also call `setEnabled(false)` on the `DefaultTimeBar` to actually disable the scrubbing functionality.

If you just want the scrubber to align in a different way with the bar, to allow the padding to be removed, then this is not something we support. You'd need to implement your own `TimeBar` to achieve that behavior.
