### ISSUE TITLE
ExoPlayer merge audio with video

### ISSUE THREAD

**Issue by ValeraC** [google/ExoPlayer#4793]
Is it possible merging audio with video to play them simultaneously?
I have video(mp4) with empty audio source, and i also have audio(ogg or mp3) that i want play with video.
Both have same length and periods. 

I am trying to marge them. Code:
```
DataSource.Factory dataSourceFactory =
                  new DefaultDataSourceFactory(this, Util.getUserAgent(this, "MyApp"));
 ConcatenatingMediaSource concatenatedSource = new ConcatenatingMediaSource();
    
MediaSource videoSource =  new ExtractorMediaSource.Factory(dataSourceFactory)
                         .createMediaSource(Uri.parse(videoUrl));
 MediaSource audioSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(Uri.parse(audioUrl));

 concatenatedSource.addMediaSource(new MergingMediaSource(videoSource, audioSource));
```

But the result is: only video plays. If  add just the audio source - audio will play...

How can I solve this problem?

**Comment by AquilesCanta** [comment]
EDIT: Ignore my previous response.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by ojw28** [comment]
Probably the video stream defines a silent audio track, which ends up being selected by default for playback. If you're in control of the creation process for the media, you should make the video stream so that it doesn't contain an audio track at all. If you're not in control of the creation process, you'll need to find a way to explicitly select the other track (take a look at `DefaultTrackSelector`).
