### ISSUE TITLE
Enable/ disable captions

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#4811]
Hi 
How can I enable and disable captions 
caption file is .srt and video format is hls and mp4.

**Comment by ojw28** [comment]
The snippet of code doesn't appear to be related to the question. Closing because the question is unclear, but please read the [relevant part of our developer guide](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file) and also take a look at the demo app. There should be enough information in these resources for you to figure this out.
