### ISSUE TITLE
Selectively creating renderers in ExtractorRendererBuilder

### ISSUE THREAD

**Issue by srikieonline** [google/ExoPlayer#482]
Currently, in ExtractorRendererBuilder, both audio and video track renderers are created irrespective of whether the underlying container contains audio/video media data or not.

Are there specific plans to enhance the design such that the app has the ability to create only the required renderer or disable a renderer that is not needed after prepare?.

**Comment by ojw28** [comment]
If you know up front that your media doesn't contain certain media types, you can pass null instead of creating a renderer. In the case that you don't know up front, but it turns out to be the case that a certain track type isn't present, the renderer will simply transition to the IGNORED state at pretty much zero cost. So I don't think there's any need to enhance the design here.

**Comment by ojw28** [comment]
Caveat - If you do avoid creating a video renderer, for example, then you do need to adjust the fourth parameter passed to ExtractorSampleSource to be 1 instead of 2. It's simpler just to create all of the renderers and allow them to transition to the IGNORED state, as is currently the case.
