### ISSUE TITLE
Will speed changing be more faster?

### ISSUE THREAD

**Issue by glorinli** [google/ExoPlayer#4826]
I try to changing speed during playback, and it will took about 400-500 milliseconds before new speed applied, I hope that new speed can take effect as soon as possible (immediately for best), because I am developing an video editing app with ExoPlayer, and the speed changing should be instantly, or a separated music player cannot keep pace with the video.

**Comment by andrewlewis** [comment]
Note: discussion started in [this medium comment](https://medium.com/@glorinli/hello-andrew-i-try-to-make-the-setting-speed-action-taking-effect-faster-now-it-will-need-about-3beca915230e).

**Comment by andrewlewis** [comment]
To summarize the discussion:
- There's currently no built-in way to apply new playback parameters immediately and seamlessly.
- Resetting `DefaultAudioSink` when getting new playback parameters will cause new parameters to take effect immediately rather than playing out audio at the old speed, but will introduce a discontinuity in audio.
- To get this to work seamlessly it would be necessary to keep in memory a copy of the input queued to audio processors and not yet output, then to flush audio processors and re-queue this input when switching parameters.
