### ISSUE TITLE
SmoothStreaming: Assume subtitles are not DRM'd in protected streams

### ISSUE THREAD

**Issue by hereisclient** [google/ExoPlayer#4838]
hi 

### Issue description
i reported subtitle issue
https://github.com/google/ExoPlayer/issues/4824

above link is my old issue link.
i checked commit contents today and i checked if this issue was solved.
my opinion about my old issue is "YES" .
Trackselector gets subtitle information properly.

but  subtitle list is disable  because getTrackSupport function returns subtitleRendererCapabilities.FORMAT_UNSUPPORTED_DRM

so i couldn't change subtitle language.

my test contents is just non-drm smooth streaming with subtitles.

### Link to test content
i will send you my test link.

### Version of ExoPlayer being used
2.8.3

### Device(s) and version(s) of Android being used
version : 8.0
device : xiomi mibox3

**Comment by ojw28** [comment]
> my test contents is just non-drm smooth streaming with subtitles.

It looks like at least the audio and video are DRM'd. Are you referring only to the text streams? If so then I see your point, but it's unclear to me how the player should determine that the text streams are not DRM protected as well. The manifest structure looks a bit like:
```
SmoothStreamingMedia
    Protection
    StreamIndex(video)
    StreamIndex(audio)
    StreamIndex(text)
```
Which we interpret as the `Protection` element applying to all of the `StreamIndex` elements, including the text one. The player then decides the text stream is not supported, because we don't support DRM protected text.

Are you aware of anything in SmoothStreaming specification that defines which `StreamIndex` elements a `Protection` element should apply to? We could "fix" the problem by not applying it to elements with `Type="text"`, but I can't see it defined anywhere that this is correct client behavior, so it's somewhat unclear whether that's the right thing to do. Any ideas?

**Comment by hereisclient** [comment]
I don't know exactly about mss spec.
But my client gave me this url for test.

I didn't tell you whether manifest is the right format or not.

At first i'll check mss spec if i find anything, i'll send you with the
docment.
And i'll ask my client if this format is right.

Thank you for your efforts.

2018년 9월 20일 (목) 오전 2:48, ojw28 <notifications@github.com>님이 작성:

**Comment by ojw28** [comment]
Did you receive any update from your client? Also, could you confirm that the video and audio are intentionally DRM protected in the provided sample, and that it's just the text stream that's not protected?

**Comment by hereisclient** [comment]
i'm so sorry to be late reply  because i was in vacation by yesterday.

i didn't any answer from my client about sample content. but i guess sample i was provided was not encrytped.  just that used url redirection. if this sample was encrypted,  before playing this , i must need customdata or somthing else.   
and 3rd party player can easily play sample with subtitle. 

but this is just only my opinion. if i get the another information from my client. i will notify you.


thank for  a lot of your effort.

**Comment by ojw28** [comment]
We probably need to assume subtitles are not protected. Marking as a bug.
