### ISSUE TITLE
Decoder init failed: OMX.qcom.video.decoder.avc on Nexus 7, Android 6.0.1

### ISSUE THREAD

**Issue by jonahwh** [google/ExoPlayer#4859]
### Issue description
Playback is failing on Nexus 7, Android 6.0.1 with the error:
Decoder init failed: OMX.qcom.video.decoder.avc

### Reproduction steps
1. Launch the Demo app
2. Attempt to play any of the following:
   * YouTube DASH: Google Glass (MP4,H264)
   * SmoothStreaming: Super speed
   * HLS: Apple 4x3 basic stream
   * Playlists: Cats -> Dogs
   * more, but that should be enough of a list

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
Nexus 7 (2013), Android 6.0.1
### A full bug report captured from the device
Emailed

**Comment by erdemguven** [comment]
I can not reproduce the issue. @jonahwh does it reproduce always for you? Even after reboot?

**Comment by jonahwh** [comment]
Yeah. I just remembed that my device is rooted (I haven't used it in a long while), so perhaps that's interfering?

**Comment by ojw28** [comment]
Rooting the device shouldn't in itself be a problem, provided you're not using a custom ROM, which I don't think you are. It looks like playback is failing because something else is holding the resources that ExoPlayer needs:

> OMXNodeInstance: useBuffer(4f:qcom.decoder.avc, Output:1 1433600@0xb4670140) ERROR: InsufficientResources(0x80001000)

If I had to guess, I'd say [this app](https://play.google.com/store/apps/details?id=com.crazydog.blackviewer) is behaving badly on your device. You could try uninstalling it (obviously don't do this if it'll cause you to lose data - at least not without backing it up first), rebooting, and trying again.

Aside: Newer releases of Android have better resource management to avoid this kind of thing (e.g. a foreground app can take limited resources away from an app that's being poorly behaved in the background).

**Comment by jonahwh** [comment]
I'm actually the developer of that app. You're right, and here's what was happening:
• My app you linked above attempts to play two videos at once
• Older devices (such as the Nexus 7) can't handle playing more than one video at once (I found this out back in September)
• I was debugging this back in September, but I wasn't releasing the player when there was an error (oops), so exoplayer would simply stop working until I rebooted the device (which I didn't find out until now).
