### ISSUE TITLE
Question: When these callbacks onTimelineChanged() or onPositionDiscontinuity() or onTracksChanged() is called? 

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4875]
@ojw28  I find many issues about what things can cause a discontinuity or timeline changed or track changed ? Hope you can give more examples to explain when onTimelineChanged() or onPositionDiscontinuity() or onTracksChanged()? and what we can do in those callbacks? In my opinion ,it's not easy for the users to understand,but these informations is very important to use the ExoPlayer correctly. Thanks!

**Comment by ojw28** [comment]
The things that can cause these events are documented in the corresponding "reason" constants, [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html). Note that you receive one of these constants when these methods are called. Specifically, look at the `DISCONTINUITY_REASON_*` and `TIMELINE_CHANGE_REASON_*` constants and their descriptions.

@tonihei has made some Javadoc improvements that'll go live with the `2.9.0` to better link the method Javadoc to the relevant constants, since the way the Javadoc is currently doesn't properly link them together. I think there's a plan to further improve this also.
