### ISSUE TITLE
Is it possible to play one ExoPlayer instance at two PlayerView at the same time?

### ISSUE THREAD

**Issue by ShkurtiA** [google/ExoPlayer#4880]
### Task description
Show two views that play the same stream and are synchronized with each other

### What I have currently achieved so far
Create 2 instances of ExoPlayer  with the same stream Uri and for each of them I set the respective PlayerView, the issue with this solution is that there is a small difference(best case) between 2 videos being played

### Question
Is it possible to use only one instance of the ExoPlayer for two different PlayerView (or maybe another way to have 2 Views that play the same stream synchronized)?

#### UPDATE:
I found this issue related to my question: #2855 Is there any update that this can be achieved more easily?

**Comment by ojw28** [comment]
There is now easy way to do this, unfortunately. This is primarily due to platform limitations (specifically, that a decoder can only output to one surface).

Note that your use case is slightly different to the one in the related issue you found. That issue was about playing different (albeit related) videos in a synchronized way. It sounds like you want to output the exact same video to two views.

You could opt to follow a similar approach as suggested in the related issue, however you'll be unnecessarily streaming the same content twice if you do this. An alternative and simpler approach would be to have the player output to a `SurfaceTexture`, and then having multiple views make use of the texture. It's definitely not straightforward, however, and figuring out exactly how to do this is beyond the scope of this issue tracker.

**Comment by ShkurtiA** [comment]
Ok thanks for you valuable feedback. I am closing it for now and maybe in the future I will comeback here again with some results
