### ISSUE TITLE
SCTE35 messages are not parsed in DASH manifest

### ISSUE THREAD

**Issue by jankowskib** [google/ExoPlayer#4922]
### Issue description
I have a live stream sends scte35 messages in DASH manifest, however they aren't parsed by EventMessage handler and sent to onMetadata() callback. As I can see in code ExoPlayer can parse these messages - SpliceCommand decoder is implemented.
Even I decode message manually I have a problem how to convert PTS time of the SCTE35 message to us time to sync messages with timeline.

### Reproduction steps
1. Init player with https://gist.github.com/jankowskib/45e7c54f7326a72595e0af3027ca5d11/raw/a2c970ea8c4a8d802901466a27d020326435c1f9/manifest.mpd
2. Hook onMetadata callback
3. Message is received but is not in expected form (EventMessage instead of SpliceCommand)

### Version of ExoPlayer being used
2.8.1

**Comment by tonihei** [comment]
Looks like we could set the mime type to be "application/x-scte35" instead of "application/x-emsg" based on the scheme id when parsing the format from the DASH manifest. This would decode the data as a TimeSignalCommand instead of a generic EventMessage. @ojw28 may know about whether this is a suitable approach. 

To get some background: Why do you need to convert the PTS time yourself? When you register the metadata listener, you'll already receive the event at the right time.

**Comment by tonihei** [comment]
Closing, as there wasn't any further input as to why this is needed. Please reopen if you can add new information.
