### ISSUE TITLE
Does ExoPlayer supports such kind of DASH streams?

### ISSUE THREAD

**Issue by PavelGP** [google/ExoPlayer#4923]
### Issue description
In demo app stream returns negative values for current position. Video is playing.

### Reproduction steps
Just setup provided stream to ExoPlayer demo app.
### Link to test content
Provided to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.9.0, 2.8.1

### Device(s) and version(s) of Android being used
Nokia 8, Android 8.1

### A full bug report captured from the device
Sent to email

**Comment by tonihei** [comment]
This behaviour looks correct to me given the manifests you provided.

Note that if the current playback position falls behind the start of the current available window, ExoPlayer keeps playing the already loaded media but shows a negative position. 

Also note that you always end up in this situation because the initial manifest you provide currently has 74 periods with very small durations. The initial window starts 41 seconds from the end, that is roughly the 60th period. After reloading the manifest with the url in the "Location" field, all but the last period disappeared. So the playback ends up at around 36 seconds before the start of the remaining period.

**Comment by tonihei** [comment]
Closing because the question was answered.
