### ISSUE TITLE
Flutter - Can't play RTMP Source

### ISSUE THREAD

**Issue by byeze** [google/ExoPlayer#4926]
### Issue description
When trying to play RTMP Stream in Flutter, ExoPlayer throws Source error.

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Android 9

### A full bug report captured from the device
https://pastebin.com/grw8ZrDZ

**Comment by ojw28** [comment]
We don't support RTMP unless using the [RTMP extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/rtmp), which I'm guessing the Flutter team are not using. So I think you probably need to report the issue to them rather than to us. They may consider it working as intended. Does Flutter claim to support RTMP?

Note that even when using the RTMP extension, there are some known issues due to [unaddressed bugs in LibRTMP](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22bug+in+dependency%22+rtmp).
