### ISSUE TITLE
how to pass array of songs to exoplayer

### ISSUE THREAD

**Issue by Dkoran** [google/ExoPlayer#4944]
I wanted to implement eco player into my music streaming application, so I followed google iOS 18 exoplayer tutorials but when I pass array to the service the app crushes, I need help In solving the issue.

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
