### ISSUE TITLE
Disable forward seeking while enabling previous seek

### ISSUE THREAD

**Issue by Faiyyaz** [google/ExoPlayer#4945]
Hello,

Thank you for such an amazing library

Though i have requirement which i am not able to see in the current version. The requirement is suppose i have watched the video till 1 min so i can seek to 0 min and watch it again but i cant take it from 1 min to 2min i.e i want to disable seeking beyond the time user viewed the video. So please help me how can i achieve it. Since i m not able to catch seek change listener

**Comment by ojw28** [comment]
All seek calls on the player originate from application code or ExoPlayer's UI components. ExoPlayer's UI components generally have `setControlDispatcher` methods that you can use to set a component capable of intercepting and modifying calls to the player. So you can implement a class like this:
```
public class PositionLimitingControlDispatcher extends DefaultControlDispatcher {

  private long maxPlayedPositionMs;

  // Needs to be called from application code whenever a new playback starts.
  public void reset() {
    maxPlayedPositionMs = 0;
  }

  // Note: This implementation assumes single window content. You might need to do
  // something more complicated, depending on your use case.
  @Override
  public boolean dispatchSeekTo(Player player, int windowIndex, long positionMs) {
    maxPlayedPositionMs = Math.max(maxPlayedPositionMs, player.getCurrentPosition());
    player.seekTo(windowIndex, Math.min(positionMs, maxPlayedPositionMs));
    return true;
  }

}
```
then create an instance, and pass it to any UI components you use. For example:
```
playerView.setControlDispatcher(controlDispatcher);
```
For any seek calls your application code makes directly, route them through the same `controlDispatcher` instance rather than making seek calls directly on the player.

**Comment by Faiyyaz** [comment]
Ok thanks a lot i will try this in some day and will get back to you
