### ISSUE TITLE
Exoplayer stucks at Discontinuity tag. 

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4961]
Exoplayer gets stuck at Discontinuity tag and then I had to seek forward or backward to play video.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
