### ISSUE TITLE
Exoplayer play udp stream

### ISSUE THREAD

**Issue by GongKuiJun** [google/ExoPlayer#4976]

**Comment by andrewlewis** [comment]
It's not clear what the problem is. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by andrewlewis** [comment]
Following up on the email: it sounds like you are seeing error concealment artifacts when playing the UDP stream, which can happen if packets are dropped or reordered. To avoid this you need to make sure the video decoder receives a valid bitstream by making sure you feed it all the video frames in the right order. The easiest way to do that may be to switch to a reliable protocol instead of UDP.
