### ISSUE TITLE
PlayerNotificationManager with Service on Android O+

### ISSUE THREAD

**Issue by png6** [google/ExoPlayer#4988]
I'm leveraging the the PlayerNotificationManager in a Service to implement background audio playback and I'm seeing an issue based on the Android O+ limitations. From what I understand, O+ devices should call `Context.startForegroundService()` to start the service and subsequently call `Service.startForeground()` with a notification to keep the service in the foreground so it's not killed.

For my implementation, I start my service with `ContextCompat.startForegroundService()` which does the API 26 check to call `Context.startForegroundService()`. I tried to create my PlayerNotificationManager and add the NotificationListener both in `Service.onCreate()` and `Service.onStartComment()` and never seem to see the call to `NotificationListener.onNotificationStarted()` which is meant to call `Service.startForeground()` but instead get an ANR due to: 

> android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

Is there an order that needs to be done so that I ensure that I call `Service.startForeground()` as as as possible? Or is there a proper way to implement this in order to support Android O+ devices as a foreground service?

**Comment by png6** [comment]
Okay, I resolved the issue and found some interesting gotchas I'd like to share.

- `PlayerNotificationManager.setNotificationListener()` needs to be called immediately after the manager instance is created since internally `PlayerNotificationManager.startOrUpdateNotification()` is called if there are changes to the notification. This is extra important if you intend to create a foreground service and use `Context.startForegroundService()`. @ojw28 do you think this should be enforced as an argument for the constructor instead of an optional item?
- It was actually a coincidence that the ANR appeared and it was mainly due to Android P specific change where it now requires that you have the permission declared `android.permission.FOREGROUND_SERVICE` in the manifest.

Hopefully anyone running into similar issues find this useful.

**Comment by ojw28** [comment]
@marcbaechinger or @andrewlewis are the right people to comment on this.

**Comment by marcbaechinger** [comment]
@png6 Sorry for the late response. 

Yes, you are correct. You should call the PlayerNotificationManager.setNotificationListener just after you create the PlayerNotificationManager, or, more precisely, before you do setPlayer(player) which may trigger NotificationListener. onNotificationStarted(int, Notification) immediately. 

Once you receive the onNotificationStarted(int, Notification) you can call on Service.startForground(int, notification)

**Comment by andrewlewis** [comment]
Yes. There is an issue at the moment where if you call `PlayerNotificationManager.setNotificationListener` after `startOrUpdateNotification` has been called internally (which can happen as a result of setting a non-idle player or having the player trigger events) then you won't get `onNotificationStarted` because `isNotificationStarted` will have been set to true already.

I think it'd be fine to have require the listener to be passed in to the constructor and factory methods. @marcbaechinger Is there any reason it needs to be kept separate? Alternatively it looks like we could call the notification listener in `setNotificationListener` if we have already started a notification. That would allow calling the methods in either order.

It looks like there is another potential issue (maybe less likely to happen in practice) where if you set an idle player and it doesn't trigger `startOrUpdateNotification` within the five second limit after `startForegroundService` imposed by the system then `onNotificationStarted` wouldn't be called and you'd get the error about not calling `startForeground`. Perhaps we ought to show a notification even if the player is idle or null to handle that case. Or maybe this can be ignored because it would be strange to set up a player notification manager without having anything to play.

**Comment by marcbaechinger** [comment]
> Or maybe this can be ignored because it would be strange to set up a player notification manager without having anything to play.

In any case it would be sufficient to have an ordinary service instead of the foreground service whilst not doing playback. This way the system can kill our service if we are not actually playing and resources become scarce. It might take some time to setup the service again, but it does not really hurt and is good citizenship. Actually, it might even make sense to  remove the service from the foreground when the player is paused and call `startForeground` again when the player resumes playback.

**Comment by png6** [comment]
@andrewlewis regarding,

> It looks like there is another potential issue (maybe less likely to happen in practice) where if you set an idle player and it doesn't trigger startOrUpdateNotification within the five second limit after startForegroundService imposed by the system then onNotificationStarted wouldn't be called and you'd get the error about not calling startForeground. Perhaps we ought to show a notification even if the player is idle or null to handle that case. Or maybe this can be ignored because it would be strange to set up a player notification manager without having anything to play.

I think I'm running into this scenario. If I lose network in app and I try to restart my service that houses the PlayerNotfiicationManager no notification starts because I assume it's in idle state and I won't get a callback with in the 5 second foreground rule. Is there a way to work around or should I fork the PlayerNotificationManager?

**Comment by marcbaechinger** [comment]
@png6 What would be the behaviour you have in mind when you fork? 

As of now, when the player is in idle state, it is not prepared, which means the timeline is empty. So in this case there is no information available about the currently playing item, which is usually shown in the notification. 

What you can do without a fork is to just create your own notification an call startForeground(int, Notification) with it. The when you start playing, the NotificationListener.onNotificationStarted(int, Notification) is called. At this point you can just call startForeground with the new notification provided by the PlayerNotificationManager. Would that work for you?

**Comment by png6** [comment]
@marcbaechinger for the time being, the fork I did simply omits the check for when the player is in the idle state. The use case is that I have the requisite metadata to display and I don't want to not have a notification shown. A bit of an odd case but I may keep the fork since I would like to look into why there are flickering in the notification when action buttons are pressed.

In regards to using a "pre-notification" for startForeground(), that would potentially work and mitigate all these foreground service requirements.
