### ISSUE TITLE
Exoplayer crash when it  switch between dynamic playlist to static playlist.

### ISSUE THREAD

**Issue by ErezNe** [google/ExoPlayer#5000]
### Issue description
I have a feature on my app to play  Catchup and startover of programs from live channel 
in order to support this features  I am saving on the backoffice platform rolling buffer  of X days 
and to play the catchup I am sending to backoffice session with start_date and end_from the rolling buffer 
for example 
```
http://9.9.9.9/live1.mpde?beginDate=<time in the past when the program start>&endDate=<begin+X hours>
```

If I perform a StartOver\Catchup  with a endDate in the future, the playlist will be dynamic grow until the end of the program. Here, when we know all the chunks are known, the playlist becomes static with all the chunks/information necessary.
At this exact point of playlist type switch Exoplayer freeze ( what ever playback position is).
 
On exoplayer 2.5.4 standalone the freeze is followed by a continuous memory increase which makes android goes to an Out of memory state.
all my test played with DASH stream 

Do you familiar  with such an issue?
 
### Reproduction steps
Play a DASH  link which its manifest durring playbach changing from dynamic to static

### Link to test content
Please send me if you need link to content and I will forward you on private 

### Version of ExoPlayer being used
Exoplayer ver 2.5.4 and  2.8.4

### Device(s) and version(s) of Android being used
Technicolor AndroidTV STB N version 

Attached you can find trace I think relevant when it happen :
```
memory_exoplayer.txt: taken on exoplayer 2.5.4, shows the memory increase of exoplayer in that case and out of memory error :+1: 10-17 10:16:14.147  1146  1158 E System  : java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

Thx
Erez Negbi

**Comment by ErezNe** [comment]
[memory_exoplayer.txt](https://github.com/google/ExoPlayer/files/2505965/memory_exoplayer.txt)

attach memory_exoplayer.txt log file

**Comment by ojw28** [comment]
We need test content. Please also try with version 2.9.0.

**Comment by ErezNe** [comment]
Hi 
Please share with me on private your IP so I whitelist on my system which is geoblocking enable  and I will send you link to test content 
Thx

**Comment by ojw28** [comment]
You'll need to find a way to provide a publicly accessible test stream, sorry.

**Comment by ErezNe** [comment]
Hi
Please send to my private email your private mail so I will share with you streaming link with catchup instruction

Thx
Erez

**Comment by tonihei** [comment]
Please send the link to dev.exoplayer@gmail.com with "Issue #5000" in the subject.

**Comment by ErezNe** [comment]
Hi 
I sent the link to  dev.exoplayer@gmail.com  mail
Thx

**Comment by ojw28** [comment]
Both the dynamic and static versions of the manifests generated look fine in isolation, but the transformation between the two doesn't seem valid.

The setup of the dynamic manifest is such that the first period starts at the epoch, and so has a very long (and still growing) duration. Only the very end of it (i.e. the part since the requested start time) is available to the client. This is all fine.

When the manifest transitions to static, the period changes to only having a duration equal to the requested end time minus the requested start time. `Period@duration` is added to reflect this, and `presentationTimeOffset` is added to shift the media into this new and different timeline.

I don't think this is a valid transformation to make in a manifest update. Period start times shouldn't move, period durations shouldn't get shorter (unless media is genuinely being removed from the end, which isn't the case here), and values of `presentationTimeOffset` shouldn't change across manifest updates. I think the correct transformation would involve setting `Period@duration` to be the end time relative to the epoch, since that's when the period started in the previously requested dynamic manifests. If you do this then `presentationTimeOffset` doesn't need to be added anywhere either. I suspect `availabilityStartTime="1970-01-01T00:00:00Z"` should probably not be removed, although I'm not certain about that.

Additional notes:
* For a client that hasn't been playing the content as live, the static manifest in its current form is perfectly valid (and probably preferable). It's specifically the manifest transformation for clients that were playing the content as live that I think is invalid here.
* Testing with 2.9.2, ExoPlayer transitions to the ended state and doesn't crash, freeze or leak memory. It's possible it gets confused and/or plays out some wrong media around the end though, due to the issues described above.
