### ISSUE TITLE
No sound in certain HLS stream but VideoView has sound

### ISSUE THREAD

**Issue by andhie** [google/ExoPlayer#501]
When using ExoPlayer to play some HLS stream, there is video but no sound. However, playing the same stream in VideoView, there is video and sound. 
ExoPlayer does throw an exception when it fails to play video, but there is no way to know if video is ok and audio fails. If there is such indicators, at least i could still fallback to VideoView.
VLC Player indicates the audio codec used is MPEG Audio Layer 1/2 (mpga).

http://198.50.176.179:1935/live/ktvlive.sdp/playlist.m3u8

**Comment by ojw28** [comment]
This is because we don't handle the following stream types:

0x03 ISO/IEC 11172-3 Audio
0x04 ISO/IEC 13818-3 Audio

We handle 0x0F (AAC) for audio. It's unclear to me whether 0x03 and 0x04 are even valid in HLS (they're valid in the MPEG-2 transport stream, but HLS places additional restrictions on the allowed stream types, which would seem to exclude these types).

**Comment by andhie** [comment]
Is there a way for me to know if audio failed to play so I can switch over to VideoView?

**Comment by ojw28** [comment]
No massively easy way. Internally in MediaCodecTrackRenderer, the audio renderer will transition to the STATE_IGNORE state after doPrepare. So one option as a temporary solution would be for you to expose that and query it.

Things this issue now tracks:

1. Provide an API to allow easy querying of whether a renderer is in STATE_IGNORE.
2. Supporting MPEG-1/MPEG-2 audio in HLS. Since it appears VideoView supports it, I guess we should too.

**Comment by andhie** [comment]
I also wonder how did you get the `0x03 ISO/IEC 11172-3 Audio`, `0x04 ISO/IEC 13818-3 Audio`?
Based on the HLS draft, they are mention to support these codecs 

https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#page-5
Each Media Segment MUST be formatted as an MPEG-2 Transport Stream [ISO_13818], a WebVTT [WebVTT] file, or a Packed Audio file, which is a file containing packed encoded audio samples and ID3 tags, such as AAC with ADTS framing [ISO_13818_7], MP3 [ISO_13818_3] or AC-3 [AC_3]. Transport of other media file formats is not defined.

**Comment by ojw28** [comment]
Yup, thanks. Updated the comment above. We should aim to provide support (not a huge priority for us though).

**Comment by nurne** [comment]
@andhie can you please post a snippet of your solution based on @ojw28 's suggestion to expose MediaCodecTrackRenderer's state transition?

I need the exact same mechanism, but for when there is only audio and no video

Thanks!

**Comment by ojw28** [comment]
MP3 support has been added to HLS in the dev branch. The stream linked in this bug is dead, so I don't know whether it works, but closing anyway. Please file a new issue with a working stream if you find any problems.
