### ISSUE TITLE
Problem playing multi-period Dash with redirects

### ISSUE THREAD

**Issue by jrw95** [google/ExoPlayer#5017]
### Issue description
The manifest linked below has 7 periods, which correspond to the following:
Period 0: the 5-second preroll ad
Period 1: the first 10-second content block
Period 2: the first 5-second midroll ad
Period 3: the second 10-second content block
Period 4: the second 5-second midroll ad
Period 5: the third 10-second content block
Period 6: the 5-second postroll ad

The problem that occurs is that after period 2, the periods that correspond to the content blocks (so, periods 3 and 5) do not play normally; instead, only the last segment in the period's sequence will be requested and played, after which the period corresponding to the ad that follows *will* play normally.

### Reproduction steps
Add the URL below to the "Widevine DASH: MP4,H264" sample array in the media.exolist.json file.
Build the demo with the noExtensionsDebug build variant.
Load the demo app on a device.
Select the test manifest from the "Widevine DASH: MP4,H264" menu.
Content starts playback when the player loads

Expected:
After Period 2 finishes, Period 3 starts without issues, and requests segments starting at the startNumber values in the manifest.
Subsequent periods play as expected, and the video completes successfully.

Actual:
The viewing experience is this:
* The preroll period plays
* The entire first content block plays
* The entire first midroll plays
* In some cases, with either the S8 or Pixel, the player would appear to freeze for a few seconds
* Perhaps a second of the second content block plays
* The entire second midroll plays
* In some cases, again with either the S8 or Pixel, the player would appear to freeze for a few seconds
* Perhaps a second of the third content block plays
* The entire postroll plays

### Link to test content
Test content:
https://ssaiplayback.prod.boltdns.net/playback/once/v1/dash/live-timeline/clear/4800266849001/64b364f4-c077-46d8-a9c4-94c3633e82bf/9d16e610-068a-44ab-8042-980ea9409eb3/88a89cde-886f-46ab-ad7e-d7ec000c8a9f/manifest.mpd?bc_token=NWJmODFmMTlfMjA1Y2JiN2M1Zjc1YTJhYTZhZjFhYjk4Mzk1MGNmM2Q3YjRlNTU3NjRhYzNlMGRkMDg2YTZjYzAxZDI5NTM2Ng%3D%3D

Content will be testable for 30 days. Please let me know if you need a refreshed URL.

### Version of ExoPlayer being used
2.7.0
2.9.0

### Device(s) and version(s) of Android being used
Samsung phones: S8, running Android 8.0 and SM-G532F running Android 6.0.1
Google Pixel running Android 9.0

### A full bug report captured from the device
Bug reports from:
Samsung S8:
[bugreport-2018-10-26-13-02-44.zip](https://github.com/google/ExoPlayer/files/2520798/bugreport-2018-10-26-13-02-44.zip)

Google Pixel:
[bugreport-sailfish-PPR2.180905.006-2018-10-26-15-55-56.zip](https://github.com/google/ExoPlayer/files/2520801/bugreport-sailfish-PPR2.180905.006-2018-10-26-15-55-56.zip)

**Comment by ojw28** [comment]
I think the manifest is malformed due to missing `@t` values in the periods that declare a `presentationTimeOffset`. I've attached a corrected manifest that appears to work fine.
[corrected.txt](https://github.com/google/ExoPlayer/files/2526509/corrected.txt)

**Comment by sergiomartinez4** [comment]
@ojw28 I think it's worth mentioning that the media plays in Shaka Player:
https://shaka-player-demo.appspot.com/demo/#asset=https://ssaiplayback.prod.boltdns.net/playback/once/v1/dash/live-timeline/clear/4800266849001/64b364f4-c077-46d8-a9c4-94c3633e82bf/9d16e610-068a-44ab-8042-980ea9409eb3/88a89cde-886f-46ab-ad7e-d7ec000c8a9f/manifest.mpd?bc_token=NWJmODFmMTlfMjA1Y2JiN2M1Zjc1YTJhYTZhZjFhYjk4Mzk1MGNmM2Q3YjRlNTU3NjRhYzNlMGRkMDg2YTZjYzAxZDI5NTM2Ng%3D%3D;lang=en-US;build=uncompiled

any thoughts on what could Shaka player be doing to play that media successfully?

**Comment by ojw28** [comment]
Yes, I noticed that. However, either the stream is spec compliant or it's not. If it's not then there's little reason for us to spend time working around the issue, unless the issue is widespread in existing content, which we don't have evidence of at this point. It's also worth noting that, at least by my interpretation of the spec, Shaka is actually presenting media at the wrong time during the presentation. When playing spec compliant media that may be a bug they need to fix (and if they were to fix it, it's likely that playback of this content would break).

The parts of the DASH spec (second edition / 2014) I'm looking at are:

1. **5.3.9.6.1** states “The value of the `@t` attribute minus the value of the `@presentationTimeOffset` specifies the MPD start time of the first Segment in the series”
1. **A.3.3** states the same thing in code: `MediaSegment[N].startTime = t[s] - o`, where `t[s]` is an `@t` value, and `o` is `@presentationTimeOffset`
1. **5.3.9.6.2** states that if @t is not present, "then the value shall be assumed to
be zero for the first S element".

You want `MediaSegment[N].startTime == 0` for the first segment in the timeline, so you need `t[s] == presentationTimeOffset`, rather than the default `t[s] == 0`.

**Comment by ojw28** [comment]
By the way, the [DASH IF reference client](https://reference.dashif.org/dash.js/v2.9.1/samples/dash-if-reference-player/index.html) also gets stuck entering the first period I'm claiming to be broken (I didn't try with my adjusted manifest).

**Comment by jrw95** [comment]
@ojw28  I just tried the DASHIF reference player with your adjusted manifest, and it played all the way through.
