### ISSUE TITLE
unable to play hls stream

### ISSUE THREAD

**Issue by menglinxiyi** [google/ExoPlayer#5018]
We are creating a player to play HLS live streams(http://open.ls.qingting.fm/live/386/64k.m3u8),  I also try it on the demo, still can not play

**Comment by menglinxiyi** [comment]
and i check the log, there is no error!

**Comment by marcochin** [comment]
I don't know if this is the same issue we're having, but we have multiple reports of customers who are also unable to play videos/ stuck in a long or infinite buffering states. We mainly use hls too. We can't reproduce it with any of the devices we have. Supposedly happening on both FireTV and AndroidTV. Just wanted to know if the exoplayer team has had any other similar reports? It's hard to provide information as we can't reproduce it ourselves. Don't think it's a connection speed issue as customer supposedly has a 1Gbps connection.
Like @menglinxiyi says there are no errors being thrown.

At this moment 2.8.4 is having the issue, can't confirm if 2.9.0 is having the issue yet.

**Comment by ojw28** [comment]
I think the problem is that the TS segments in the stream claim to have an H264 video stream, when this is not actually the case. ExoPlayer gets stuck in the buffering state because it's waiting to see the first pieces of data belonging to the declared stream (to determine its format), and this data never arrives. I don't think TS segments should declare a stream and then provide no data for it.

If you know you only have to deal with this type of stream, and want a quick client side workaround, you can call the following on the `HlsMediaSource.Factory` to manually ignore the H264 video stream:
```
.setExtractorFactory(
    new DefaultHlsExtractorFactory(
        DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM))
```
In the demo app you'd modify [this code block](https://github.com/google/ExoPlayer/blob/r2.9.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L492) to be:
```
case C.TYPE_HLS:
  return new HlsMediaSource.Factory(dataSourceFactory)
      .setPlaylistParserFactory(
          new DefaultHlsPlaylistParserFactory(getOfflineStreamKeys(uri)))
      .setExtractorFactory(
          new DefaultHlsExtractorFactory(
              DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM))
      .createMediaSource(uri);
```
