### ISSUE TITLE
How to prevent and force focus to "skip button" manually use IMA extension

### ISSUE THREAD

**Issue by anhlevfx** [google/ExoPlayer#5019]
### Issue description
In android TV. Video with ads use exoplayer-IMA extension version 2.8.4 have some codes to focus skip button on skippable ads. I have modified ima extension to can prevent focus or force focus skip button. Because our UX require that behavior. Everything work as I expected. But, when update to version 2.9.0, I can't do that.

### Reproduction steps
In version 2.9.0 don't have this declare

```
 private static final String FOCUS_SKIP_BUTTON_WORKAROUND_JS = "javascript:"
      + "try{ document.getElementsByClassName(\"videoAdUiSkipButton\")[0].focus(); } catch (e) {}";
```

In version 2.8.4 have this code
```
case STARTED:
        if (ad.isSkippable()) {
          focusSkipButton();
        }
        break;
```
so I can prevent focus to button by don't call focusSkipButton(), and call it when I need.

But in version 2.9.0
 `case STARTED:`
it's empty. I guess focus skip button is auto and work without trick like before.

### Link to test content
Not provided

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Android TV version 8, 7.1.

### A full bug report captured from the device
Not provided

**Comment by andrewlewis** [comment]
The IMA SDK takes care of focusing the skip button automatically on Android TV as of IMA SDK version 3.9.4.

At the moment it's not possible to customize the default behavior (focusing the button) because this needs to be set on [AdsRenderingSettings](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdsRenderingSettings) and `ImaAdsLoader` creates this internally. I'll make a change so apps can pass in a value for `setFocusSkipButtonWhenAvailable`. (That said, I find it difficult to imagine a case where you wouldn't want the default behavior!)

**Comment by anhlevfx** [comment]
Thanks you and waiting for your change. In my case, I have layout with a preview video (live tv) in top-right with about 60% width and 40% height of screen. 50% height below for list RowFragment, the list channel. When use press center button on D-pad video preview with resize full screen. But when user still focus to item in list channel and they don't press center button (they maybe press left/right/up/down button to find the channel they want). So, I don't want auto focus skip button when video in preview mode. It's will make loss focus current item in the list and user will be confused.
