### ISSUE TITLE
Can Exoplayer Stream mp3 Without Downloading File?

### ISSUE THREAD

**Issue by adam-hurwitz** [google/ExoPlayer#5028]
# Issue
If a mp3 file is saved to the cloud, ie:Firebase Storage / Google Cloud Storage, can the file be streamed from Exoplayer without needing to download the full file size? If the mp3 can be streamed directly from Cloud Storage roughly what percentage of memory of the file is used in the transfer of the stream since the file itself is not being downloaded?

The objective is to avoid data transfer costs which are more expensive than data storage costs.

# Possible Solution
Per @erdemguven's Medium Post, [Downloading Streams](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95), it looks like the **DataSource** may handle hosted mp3 files without downloading the file.

**Comment by ojw28** [comment]
> If a mp3 file is saved to the cloud, ie:Firebase Storage / Google Cloud Storage, can the file be streamed from Exoplayer without needing to download the full file size?

Yes. That's just what happens by default when you use ExoPlayer to play a stream.

> If the mp3 can be streamed directly from Cloud Storage roughly what percentage of memory of the file is used in the transfer of the stream since the file itself is not being downloaded?

You can configure this by instantiating your own [DefaultLoadControl](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html), which you can pass to `ExoPlayerFactory.newSimpleInstance` when building the player. You can also implement your own `LoadControl` from scratch if you need more control.

Note that whilst buffering less far ahead saves on data transfer costs, it also makes re-buffers more likely to occur because the player will be less able to ride out temporary network connectivity issues.
