### ISSUE TITLE
Method getduration return TIME_UNSET value.  I tried TsExtractor three modes.

### ISSUE THREAD

**Issue by crook3** [google/ExoPlayer#5051]
This is Video info obtained by Exoplayer.

Format(1/256, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
Format(1/8448, null, application/cea-608, -1, null, [-1, -1, -1.0], [-1, -1])
Format(1/257, null, audio/mp4a-latm, -1, und, [-1, -1, -1.0], [2, 48000])

Can any one help me , Thanks.

**Comment by ojw28** [comment]
You may well find this issue can be resolved by updating to 2.9.0, if you're currently using an older version. That aside, this issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
