### ISSUE TITLE
Question about SCTE-35 stream not getting next chunk

### ISSUE THREAD

**Issue by hleh** [google/ExoPlayer#5057]
Hello,
I'm having a problem with Exoplayer and a specific SCTE-35 live DASH stream.

### Issue description
I'm developing a new feature which is using a new type of stream on our end. The stream is supposed to be identical to our other live DASH streams which work fine with Exoplayer, with the exception of having defined EventStream cue points. This stream is working with a dash-player on browsers, but with Exoplayer the stream just stops at the 15 minute mark. It seems like Exoplayer is unable to get the next chunk from that point forward.

Would you be able to give any advice as to why Exoplayer is unable to process the stream further?

### Reproduction steps
I was able to reproduce this with the Exoplayer demo app with version 2.9.0. Can be reproduced with the test stream.

### Link to test content
Link to test stream
https://mtvdashliveusptest1-a.akamaized.net/live/ETEST/ETEST.isml/1000690.mpd

### Version of ExoPlayer being used
Can be reproduced with version 2.9.0.

### Device(s) and version(s) of Android being used
Huawei P8 Lite Android 6.0
Sony D6502 Android 6.0.1
Nexus 5x Android 8.1.0

### A full bug report captured from the device
I was unable to pinpoint logs that could help with the issue as nothing seems to crash.

**Comment by AquilesCanta** [comment]
I suspect that the SegmentTimeline is not being updated correctly for ExoPlayer to fetch the newer chunks. 
@ojw28 mind having a look?

**Comment by hleh** [comment]
It was brought to my attention that sometimes the stream is unavailable. If you are able to take a look, I can make a request to keep the stream available for a fixed period of time. Just let me know of the when.

**Comment by ojw28** [comment]
I think there are a few things not right with the way the manifest is updating:
1. `SegmentTemplate@presentationTimeOffset` values should not change across manifest updates. I think in this case they should probably be set to 0 (or omitted completely), given how the media is otherwise setup.
1. I think the manifest should have `SegmentTemplate@startNumber` attributes that do increment across manifest updates as segments are removed from their contained timelines. Otherwise the manifest update appears to the client as though the same segments are still present, but their timestamps have changed. Rather than it appearing as though some segments have been removed, and new segments have been added.

**Comment by hleh** [comment]
Thank you for the info, I've forwarded it to our streaming unit.
