### ISSUE TITLE
How to play .ts video file from sdcard in exoplayer?

### ISSUE THREAD

**Issue by majidebrahimii** [google/ExoPlayer#5090]
I use Exoplayer 2.9.0, I want to show the .ts video file on the sdcard in the Exoplayer. How can this work?(I downloaded all segment of m3u8 and integrated them in one file)

**Comment by AquilesCanta** [comment]
There is no difference with what you'd do for any other file, other than the permission requirement to read external storage. I'd suggest you add your file path to the demo app sample list, and go from there. Since the permission require runtime handling, that might be the harder bit. Remember that what you are trying to play is no longer HLS, but rather a progressive playback, so the media source should be ExtractorMediaSource.

**Comment by majidebrahimii** [comment]
@AquilesCanta  I use ExtractorMediaSource and play a video but thumbnail seekbar and total time not showing when playing video.

**Comment by ojw28** [comment]
The seek scrubber and total time should display as of 2.9.0 (but not earlier versions).

A two sentence issue description is almost by definition not sufficient for us to help you. Please provide complete information as is clearly requested in the issue template. For this particular issue a piece of sample media (i.e. the TS file after you've merged the chunks together) would help us to easily reproduce the issue.

**Comment by majidebrahimii** [comment]
@ojw28 I use exoplayer 2.9.0 . Need special settings for displaying total time and Seek Bar? This link file is made from downloaded parts:

https://files.fm/f/2wjhpj6h

I play this file in MX Player and defualt player my phone without problem( Samsung Galaxy Note 3).
Tell me if you need to code. Thank you for your help.

**Comment by ojw28** [comment]
Your issue is a duplicate of #5097.
