### ISSUE TITLE
HLS problem on streams without ext-x-endlist tag.

### ISSUE THREAD

**Issue by Guro** [google/ExoPlayer#510]
Hello we are testing exo-player for HLS and came across problem on streams that does not have
ext-x-endlist tag.
Exo player is unable to seek inside this kind of streams, can you suggest anything how we can fix this issue?

**Comment by Guro** [comment]
Oh as i am seeing, its an issue #87 
Can you get any approx date when it will be implemented? or any guide how we can implement this functionality on our own?

**Comment by Guro** [comment]
anyone? :) 
its really important for us, please give some estimates

**Comment by ojw28** [comment]
We can't provide an estimate at this point, sorry. You could look at trying to implement this yourself, but we're not in a position to help figure out how to do it.

Note also that we'll be prioritizing seeking in live streams for DASH and SmoothStreaming before HLS, as per https://google.github.io/ExoPlayer/2015/05/08/the-benefits-of-dash.html.

Closing this, since the request is tracked by #87.

**Comment by Guro** [comment]
are there any estimates for DASH?

**Comment by ojw28** [comment]
"Soon" is the hope. We pushed some limited support to the dev branch recently, but had to revert it because it didn't work quite right. We hope to push again soon.

**Comment by Guro** [comment]
Ok, thanks for info.
