### ISSUE TITLE
Playback of offline downloaded video

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5142]
Hi i would like to play the offline downloaded video from my local storage.I have followed the example given by you in the demo app.But i am not able to find a way to play the downloaded content.Could you please share an example.I am downloading a hls format video

**Comment by andrewlewis** [comment]
Are you using ExoPlayer's downloading support as described in this [blog post](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95)? If so, the last section there describes how to play the stream: you play the original content URL used to download the content. The data source will load from the cache to read the downloaded data rather than going to the network.

**Comment by karandeep26** [comment]
I can't find equivalent of `DefaultDashChunkSource.Factory ` for hls media. Could you please help?

**Comment by andrewlewis** [comment]
Closing as the question was answered.
