### ISSUE TITLE
Audio Tracks FORMAT_EXCEEDS_CAPABILITIES

### ISSUE THREAD

**Issue by gerardiandrea** [google/ExoPlayer#5145]
### Issue description
Hi, 
I'm implementing the audio track selection on my app using 'TrackSelectionView' as done in the demo app.
Everything works correctly except on some devices where the control to make the audio track selectable or not "trackInfo.getTrackSupport (rendererIndex, groupIndex, trackIndex)" returns me 2 (that is FORMAT_EXCEEDS_CAPABILITIES).

I specify that the default audio track is played correctly on these devices too.

I tried to customize the 'TrackSelectionView' class by removing this control and leaving all the audio tracks selectable; the result was that even on devices that previously did not allow to select audio tracks, these are now played correctly without apparent errors.

I wanted to ask you:
1 - Because leaving the standard implementation I can not select these audio tracks that are reproducible by the device?

2- Using my workaround, what problems could I encounter?

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
Samsung A3 with Android 6.0
Samsung S3 Neo Android 4.4.2

**Comment by ojw28** [comment]
The problem you could encounter is playback failure, if the user selects a format that genuinely isn't supported by the device.

It sounds like a case of these two devices under-reporting their true capabilities. If you're able to provide us with sample media that reproduces the issue, and ideally a bug report captured from one of the affected devices, then we can look at adding a workaround in ExoPlayer.

**Comment by cyrillrx** [comment]
Hi,

We experience the same issue since we migrated from ExoPlayer v2.8.4 to v2.9.1.

The problem occurs on several devices: Samsung Galaxy J5, Honor 5X, Xiaomi Redmi 4A, Amazon Fire Stick.

In the case of the Amazon Fire Stick, the problem is that "decoder.isCodecSupported(format.codecs)" returns false

decoder.name = "OMX.google.aac.decoder"
decoder.mimeType = "audio/mp4a-latm"
format.codecs = "mp4a.40.2"

If I override the method to return true, it works perfectly... 

@ojw28 , are the audio capabilities more strict in the new ExoPlayer version?

**Comment by andrewlewis** [comment]
@cyrillrx I think this might be caused by 80f5b7e7b2743e6b51b1f9b2b2d4343c7f57cbeb, which added a check on the `CodecProfileLevel`s reported by the decoder for audio. Either capabilities are being underreported (we have seen this for video decoders too) or the profile/level check is buggy. It would be interesting to see what capabilities are reported on these devices (`MediaCodecInfo.getProfileLevels()`).

**Comment by gerardiandrea** [comment]
I confirm that even on my devices (Samsung A3 with Android 6.0, Samsung S3 Neo Android 4.4.2) I have no problems with the version ExoPlayer v2.8.4
