### ISSUE TITLE
Is it possible to use exoplayer to stream an encrypted video locally in android?

### ISSUE THREAD

**Issue by svidata** [google/ExoPlayer#5146]
So after I allow users to download videos to their devices I will encrypt the videos with AES, now the problem comes when I want to read the encrypted video file. As exoplayer is well known for streaming online is it possible to use exoplayer to stream encrypted videos offline?

**Comment by andrewlewis** [comment]
> So after I allow users to download videos to their devices I will encrypt the videos with AES

It sounds like you are encrypting the video yourself, and want to decrypt it in a streaming way (rather than decrypting the whole stream and passing the clear stream to ExoPlayer). Please have a look at `AesCipherDataSource`. Depending on how you encrypted the stream you may need to make a custom `DataSource` based on it.
