### ISSUE TITLE
Limit of ByteBuffer at queueInput (AudioProcessor)

### ISSUE THREAD

**Issue by urbanovichwork** [google/ExoPlayer#5159]
Hello!
I currently using ExoPlayer v2.7.3 and try to write custom AudioProcessor. For my processing method i should know exactly how much samples of audio i will get before queueInput send me this amount of data, but i can't understand the way it generates.
(I using MPEG-DASH streaming)

For ex.: If i play some video with two audio channels queueInput will return me 8192 bytes of data (4096 PCM16 values, so 2048 on one channel), but if i play video with six channels it return me 12288 bytes (6144 PCM16 values, so 1024 on one channel).

How get this value for one channel before queueInput will give me data? or how set default value for one channel at 1024 or 2048 samples?

Best Regards!

**Comment by andrewlewis** [comment]
The input buffer's size is the size of the audio decoder output buffer written to the sink (if this is the first audio processor), or the size of output buffer from the preceding audio processor (otherwise). When using `MediaCodecAudioRenderer` I don't think there's a guarantee that the audio decoder output buffer will have a particular size.

Audio processors can consume the input partially or fully without producing output. If you do that perhaps you can avoid making assumptions about the size of input buffers. Could you give a bit more detail about what you're trying to do?

**Comment by andrewlewis** [comment]
To give a concrete example: let's say you want to process batches of 2048 samples (for example). You can make an internal buffer that's big enough to store up to 2047 samples, and then when you receive more input you can process anything that's in your internal buffer followed by anything that was input up to a multiple of 2048 samples, then store anything that remains in the internal buffer. When `queueEndOfStream` is called you need some way to handle any data that remains in the internal buffer.

**Comment by urbanovichwork** [comment]
> To give a concrete example: let's say you want to process batches of 2048 samples (for example). You can make an internal buffer that's big enough to store up to 2047 samples, and then when you receive more input you can process anything that's in your internal buffer followed by anything that was input up to a multiple of 2048 samples, then store anything that remains in the internal buffer. When `queueEndOfStream` is called you need some way to handle any data that remains in the internal buffer.

Thanks for advice, did it in this way and everything is good.

Actualy, i have one more question. Maybe you can help me with playing audio from ExoPlayer at specific AudioSource of Unity3D? Is it possible and maybe it covered somewhere?

**Comment by andrewlewis** [comment]
I don't think this is covered anywhere and I haven't tried it, but I think it's in theory possible to create a custom `AudioSink` implementation that outputs to a Unity audio source instead of writing to a platform `AudioTrack`. If you try this and manage to get it to work it would be cool if you could let us know here. Thanks!
