### ISSUE TITLE
[Question] Output multiple subtitle tracks simultaneously

### ISSUE THREAD

**Issue by Rhuagh** [google/ExoPlayer#5192]
We have a use case where we want to be able to output multiple subtitle tracks at the same time (stacking). Is this possible with exoplayer, and how would be go about doing this if so?

We have a working implementation of doing this in an HTML5 player, and we're currently evaluating if we should use that in a webview or if we should use exoplayer instead.

**Comment by erdemguven** [comment]
It's possible but you need to modify some of the library classes. 
You need to create multiple TextRenderers and TextViews.
There are couple of ways to enable multiple TextRenderers at the same time:
- Tweak MappingTrackSelector.
- Define a new track type (TRACK_TYPE_TEXT_SECONDARY) and make sure the content has this type.

Alternative content side recommendation:
- Merge text tracks.

**Comment by Rhuagh** [comment]
Can you show any number of cues simultaneously if you merge the text tracks, or is there a limitation (except for screen space)?

**Comment by erdemguven** [comment]
There is no limit defined for the maximum number of cues to be displayed simultaneously.

**Comment by ojw28** [comment]
As a bit of extra context:

The use case that we've normally seen this question come up is around forced vs optional subtitles. For example if there's a sci-fi film where an alien says something in their alien language, the corresponding subtitle should _always_ be shown (assuming it's intended that the viewer understand what's being said). Where-as when a human says something in a human language, the corresponding caption/subtitle is probably optional depending on the user selection.

I've seen it argued both ways whether the forced subtitles should be included in the optional caption/subtitle tracks. If they are then the player only ever needs to enable a single track (the user selection if there is one, or the track containing only the forced subtitles otherwise). If they aren't then the player needs to enable either one or two tracks, depending on user selection. I think our suggestion/preference is that they should always be included. It seems much simpler. If there's some other use case for which this suggestion/preference doesn't work well, it would be interesting to know what it is.

**Comment by Rhuagh** [comment]
That's a part of it, but we're basically building a frame accurate QA tool, that is used to verify that audio and subtitles are in sync with the video. One of the requirements is the ability to verify multiple audio/subtitle tracks simultaneously to save time.

**Comment by MuVen** [comment]
@ojw28 How can i force subtitles selected from the internal storage to be shown instead of captions displayed while aliens speak their language.

can you help me where to tweak in the code please ...

**Comment by ojw28** [comment]
@MuVen - Off topic and already tracked in #5393. Please keep using that issue for your question.
