### ISSUE TITLE
Comlex unit tests in Android Studio

### ISSUE THREAD

**Issue by zsmatyas** [google/ExoPlayer#521]
I am trying to create more complex unit tests (to run them on my device), for example open a real stream, seek into it and check to result. The provided sample unit tests only seem to check functionality of stand alone functions in ExoPlayer using local media.

I tried multiple approaches, but lot of the descriptions currently available on the Internet are contradictory and probably outdated. Using the latest Android Studio the provided unit tests are easy to run, but I am not sure, how to extend to achieve my current goal.

I think I should use AndroidTestCase to have correct context. My simple test function tries to create:
- DemoPlayer.RendererBuilder instance to play the google mp3 sample. 
- DemoPlayer instance using the RendererBuilder.
- Sets up the listeners to get updated about state changes.
- calls prepare() and setPlayWhenReady()
- Starts waiting for state changes.

I get the state change about STATE_PREPARING, but nothing else after. Breakpoints seem to be hit correctly in Mp3Extractor.

Do I need some other additional steps to get the other events the demo player is receiving, or are there maybe other limitations (context differences, threads etc)?

Did anyone successfully create complex test cases?

**Comment by ojw28** [comment]
We're actually just in the process of writing a separate test project for playback tests. We found ActivityInstrumentationTestCase2 does the trick, but it is necessary to do a bit of slightly awkward thread jumping to get everything working correctly on the right threads.

The project we're creating will provide a little framework for making such tests relatively easy to write (it'll take care of the threading for you, let you schedule events like seeking/pausing to be performed during the test, and provide a convenient method for the end of a test run where you can validate that playback worked as expected).

So, if you want to experiment now, look at ActivityInstrumentationTestCase2. Otherwise, we'll try and get the initial version of the new project pushed to dev in the next couple of weeks.

**Comment by Arqu** [comment]
Here's a small sample of what I did to do the same thing a couple of days ago, it uses a slightly modified version of the demo app/player but it should be enough to get you going.

```
package devlogic.hlsvideoview;

import android.content.Intent;
import android.test.ActivityInstrumentationTestCase2;
import android.test.ActivityUnitTestCase;
import android.test.InstrumentationTestCase;
import android.util.Log;

/**
 * <a href="http://d.android.com/tools/testing/testing_android.html">Testing Fundamentals</a>
 */
public class ApplicationTest extends ActivityInstrumentationTestCase2<MainActivity> {

    /*
        Testing might fail if low end device is used or the connection is spotty due
        to slow response and loading because syncing is done via Thread.sleep() since there is
        no reliable way to hook into listeners and callbacks of an activity.
     */
    private MainActivity activity;

    public ApplicationTest() {
        super(MainActivity.class);
    }

    //HLSVideoUtil
    public void testVideoUtil(){
        //User Agent
        //assertEquals("HLSVideoPlayer/1.0 (Linux;Android 4.4.4) ExoPlayerLib/1.3.2", HLSVideoUtil.getUserAgent(activity.getApplicationContext()));
        //ExoPlayer Type
        assertEquals("3", HLSVideoUtil.getType());
    }

    public void testPlayback(){
        //Wait for video to start
        try{Thread.sleep(3000);} catch(Exception e) {}

        //Test video plays
        boolean playbackstate = activity.player.getPlayWhenReady();
        assertTrue("Playback", playbackstate);

        //Test if video seeks
        activity.player.seekTo(15000);

        try{Thread.sleep(1000);} catch(Exception e) {}

        assertTrue("Seeking to 15000, current position: " + activity.player.getCurrentPosition(), activity.player.getCurrentPosition() > 12000);

        //Test video pause
        activity.player.pause();
        assertTrue("Pause", !activity.player.getPlayWhenReady());
        long currentPosition = activity.player.getCurrentPosition();

        //Test video continue
        activity.player.play();
        assertTrue("Play", activity.player.getPlayWhenReady());
        try{Thread.sleep(5000);} catch(Exception e) {}
        assertTrue("Playing @ " + currentPosition + " " + activity.player.getCurrentPosition(), currentPosition < activity.player.getCurrentPosition());

        //Change Video
        activity.player.stop();
        activity.player.seekTo(0);
        activity.player.release();
        activity.player = null;

        activity.preparePlayer("http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8");

        try{Thread.sleep(3000);} catch(Exception e) {}

        //Test video plays
        playbackstate = activity.player.getPlayWhenReady();
        assertTrue("Playback", playbackstate);

        try{Thread.sleep(1000);} catch(Exception e) {}
    }

    @Override
    protected void setUp() throws Exception {
        super.setUp();

        activity = getActivity();
    }
}
```

**Comment by zsmatyas** [comment]
Thank you for the suggestions.

I got a basic ActivityInstrumentationTestCase2 working based on Arqu's example.
This method needed some modifications in the PlayerActivity demo, as the PlayerActivity.onPause() is called at the end of getActivity(), so the player instance got released before the real tests start. 

CountDownLatch seems to be a relatively easy way to wait for the events (instead of Thread.sleep()) as described here:
http://www.vogella.com/tutorials/AndroidTesting/article.html

One more question:
Is there a way to test a player instance without an activity instance? I mean I would like to focus on the playback functionality and less on activity lifecycle if possible. That is why I started with InstrumentationTestCase and not ActivityInstrumentationTestCase2 previously, trying to directly instantiate a player. I do not see the limitation yet, why is the presence of a real activity necessary. But of course, as this is the first time I got the player instance behaving correctly, I do not mind creating new test activity classes.

Thank you!

**Comment by ojw28** [comment]
For video playbacks it's best to have an activity, because having an activity is the easiest way to get a valid surface that you can render into (and more accurately reflects common usage). Given we need playback tests for video, our test project is going to use an activity for all test cases. We'll be abstracting away the activity lifecycle so that you wont need to think about it when writing tests.

If you only want to test audio playback then it should be possible to run tests without an activity. The reason you don't see events being delivered is that you need to create an ExoPlayer instance on a thread that has an associated [Looper](https://developer.android.com/reference/android/os/Looper.html). You'd need to setup such a thread and use it to create and interact with the player. [HandlerThread](http://developer.android.com/reference/android/os/HandlerThread.html) might be useful.

**Comment by zsmatyas** [comment]
Thank you! I give an attempt to test audio streams without an activity involved, and I am also waiting forward to your test projects on the dev branch!
