### ISSUE TITLE
[Question] How to crop video that goes beyond some aspect ratio bounds? 

### ISSUE THREAD

**Issue by natario1** [google/ExoPlayer#5221]
I have the requirement that videos should be cropped to not exceed some minimum aspect ratio (say 9:16) and some maximum aspect ratio (say 16:9).

I am not familiar with the source and am wondering what is the efficient solution to this.
As I see it the first thing is to set `videoComponent.videoScalingMode = C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` which I have done.

The second thing would be hook into `AspectRatioFrameLayout` measuring, ideally, override the `setAspectRatio` method and apply my constraints. But the class is final. Tried to override the caller, which is the `ComponentListener` inside `PlayerView`, but there's no way to do that.

If this is the case, could `AspectRatioFrameLayout` be made non-final to support this simple use case?

I guess there are other ways,

- use a custom `SurfaceView` for example, but this requires dropping the `PlayerView`
- add an external video ratio listener, get the ratio, then call `AspectRatioFrameLayout.setAspectRatio()` with the desired value. This is inelegant, it's not sure that this listener would be called after the player  `ComponentListener`, and in any case this means calling setAspectRatio() twice, which means two layouts.
- work with `PlayerView.onMeasure` so it drives AspectRatioFrameLayout measuring? This shares most of the issues with previous idea, because we must wait for the ratio before eventually performing a new layout. This would also affect the player control view which is not what we want. 

Any help?

**Comment by AndroidDeveloperLB** [comment]
Isn't this a good solution: `app:resize_mode="zoom"` 
?

**Comment by natario1** [comment]
@AndroidDeveloperLB if I had a fixed aspect ratio like 1:1, I could set the frame to that ratio and use `resize_mode="zoom"`, I think?

But I have a minRatio and maxRatio, so the final aspect depends on the video. I want `AspectRatioFrameLayout` to take this coerced value directly instead of waiting for my call, because while waiting, it will draw the full video for a few frames and that is noticeable.

I think that a non-final `AspectRatioFrameLayout` would not hurt the library. But there might be other ways to do what I want that I am missing.

**Comment by AndroidDeveloperLB** [comment]
I don't know. Thought maybe it could help you.
Maybe given the aspect ratio that you got, and the limitations you want to apply, you could set the size of the SurfaceView to what it should be, and the "zoom" will suffice.

It's too bad there are only a few ways to set the scaling, and there is no way to overcome the need to use any kind of View (for example, to be used on Live Wallpaper app).

**Comment by ojw28** [comment]
> Use a custom SurfaceView for example, but this requires dropping the PlayerView

Currently, I would suspect this is the best (only?) viable approach.

> Could AspectRatioFrameLayout be made non-final to support this simple use case?

We could easily do this, but how would you use it with `PlayerView`? The only way I can think of would be to provide a custom `exo_player_view.xml` layout, which would be a copy of the one we provide but with the `AspectRatioFrameLayout` replaced with your extending class. That seems pretty awkward (and you'd probably want to keep your layout otherwise in sync with ours, which is easily forgotten and extra work). Do you see a simpler way? If there is a simpler way then let us know what it is, and we can go ahead and make `AspectRatioFrameLayout` non-final.

> Tried to override the caller, which is the ComponentListener inside PlayerView, but there's no way to do that.

If there isn't a simpler way of using your extended `AspectRatioFrameLayout`, then making it possible to override the caller seems like a better approach. We could move the implementation of `PlayerView.ComponentListener.onVideoSizeChanged` into a protected method in `PlayerView`, and have `PlayerView.ComponentListener.onVideoSizeChanged` just call that protected method. You'd then be able to extend `PlayerView`, which is already non-final, and override the protected method. I don't think doing that in itself is quite sufficient, since your overriding implementation would need access to some variables (e.g. at least `contentFrame`). If you think this approach is the way to go, please figure out exactly what would be needed, and verify that it does indeed solve your use case end to end. With this information, I think we could make a supporting change (or, possibly easier, you could send us what needs to be done in the form of a pull request that edits `PlayerView`).

**Comment by natario1** [comment]
Hey @ojw28 , right, I am already using a custom xml layout so that seemed straight forward to me.

I would open the `AspectRatioFrameLayout` because
- What I need is get into the measuring process, and `AspectRatioFrameLayout` seems to be the responsible component, not the player
- Making it non-final would let us override onMeasure or any other method, giving us full control over the surface container
- There's no reason for it to be final? Other than block people from messing with measuring, which is what I was trying to do. In this sense the fact that it is not straightforward (requires custom xml) might be a pro?

If you still prefer a `PlayerView` protected method, I will do some tests and get back to you!

**Comment by ojw28** [comment]
I'm fine with either approach. I just want to make sure what we do actually solves your problem :). If making `AspectRatioFrameLayout` non-final is definitely enough for you, then we can just go ahead and do that.

**Comment by natario1** [comment]
The protected method might work as well @ojw28 , I have applied my constraints and measuring is working fine, however the image is distorted.

I have checked that `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` is set and the media codec video renderer is being used. Do you have any idea?

For example, if I force a 16:9 video to be 1:1, I see a 1:1 frame but most of the times it has the full image compressed horizontally. As if `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` was not set.

**Edit**: found the cause in MediaCodec docs.
```
* As of {@link android.os.Build.VERSION_CODES#N} release, this mode may not work if
* the video is {@linkplain MediaFormat#KEY_ROTATION rotated} by 90 or 270 degrees.
```

Not sure if you want to add this to your docs.
