### ISSUE TITLE
Exoplayer proxy/firewall question

### ISSUE THREAD

**Issue by aaronbox** [google/ExoPlayer#5235]
This is a question not an issue.

Does Exoplayer have to any network/ports open to properly work. We are trying to use this through a corporate firewall. When i have allow any/any on the player opens and the content works. When i switch the firewall back to restricted I dont see any requests to the firewall, but the content never loads.

**Comment by ojw28** [comment]
I think for nearly all normal use cases, ExoPlayer is simply making regular http(s) requests the same as a web browser would. I don't think we have any special requirements.

**Comment by ICEGot** [comment]
Does it reach out to google for some type of verification? Saw some odd traffic going to 1e100.net and thought it might be related.

Thanks!

**Comment by ojw28** [comment]
ExoPlayer doesn't do make any "phone home" style network requests (and since it's open source, it's not too hard to check this if you're sufficiently motivated to do so). The only case I'm not sure about would be if you're using the IMA extension, which depends on the IMA SDK, which is not open source. You can find information about the IMA SDK [here](https://developers.google.com/interactive-media-ads/docs/sdks/android/), but unless you're using it this is irrelevant.

Closing because I think the question is answered by my initial response above.
