### ISSUE TITLE
Provide OkHttp variant of HttpDataSource

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#524]
Hi,
As title, I create this small class. Not sure could merge this into demo module?
https://gist.github.com/b95505017/09b8da221af7f14740b7

Thanks!

**Comment by b95505017** [comment]
Look like this when trying to play HLS sample in demo app
![2015-06-07 5 53 36](https://cloud.githubusercontent.com/assets/320815/8023535/11d6d4da-0d42-11e5-8e02-cdbb85276147.png)

**Comment by Ood-Tsen** [comment]
Just want to know what the tool is ?

**Comment by b95505017** [comment]
You mean Chrome dev tools or Stetho?
Stetho is developed by Facebook
http://facebook.github.io/stetho/
It could easily integrated with OkHttp to monitor all request in Chrome dev tools.

**Comment by Ood-Tsen** [comment]
@b95505017 Cool, thanks for the information.

**Comment by jpshelley** [comment]
+1 this would be really awesome to have.

**Comment by ojw28** [comment]
Is it easy to use stetho with DefaultHttpDataSource as well? It looks like stetho supports urlconnection in some form at least (I didn't look in detail).

**Comment by b95505017** [comment]
Not as easy as using OkHttp
> If you are using HttpURLConnection, you can use StethoURLConnectionManager to assist with integration though you should be aware that there are some caveats with this approach. In particular, you must explicitly add Accept-Encoding: gzip to the request headers and manually handle compressed responses in order for Stetho to report compressed payload sizes.

**Comment by ojw28** [comment]
I don't think we want this in the core library or demo app, since we don't want to mandate that developers include the okhttp network stack in their applications. This is definitely useful as an optional extension though, particularly for developers who already include okhttp in their applications anyway.

If you were to package it up as a standalone extensions project in the [extensions](https://github.com/google/ExoPlayer/tree/dev/extensions) directory, then we'd happily merge it there so that developers who do want it can get access to it.

**Comment by ojw28** [comment]
Note - I've updated the title of this issue to correspond more closely to what it's tracking. This is really tracking providing an okhttp variant of HttpDataSource, and the primary use would be to allow applications to use okhttp as the network stack. The fact that you can debug using Stetho when you're using it is more or less just a (very nice) added bonus!

**Comment by ojw28** [comment]
This is merged in dev. Thanks!
