### ISSUE TITLE
[question] Load and render samples as fast as possible

### ISSUE THREAD

**Issue by natario1** [google/ExoPlayer#5249]
I am exploring the possibility of leveraging ExoPlayer to do video transcoding for local video files. It would be cool to demux and decode using ExoPlayer internals then go on with components that I already have (to mux again and save to file).

It seems that
- for audio we would need a custom `Renderer`? or some other component
- for video we should just pass the appropriate `Surface`. This is not an issue.

However, it's not clear to me how we should configure the player (or any other lower level component) to load and render audio/video samples as fast as possible, without dropping any. When my encoder consumes a video sample, for example, I would need to call something like `exoPlayer.loadNextFrame()`. How to do this?

**Comment by ojw28** [comment]
Do you actually want to decode and re-encode the media samples themselves? Or do you just want to change them from being in one container format to another?

Also, what type of media is the source content? Are they regular media files, or will you ever have to deal with adaptive (DASH/SS/HLS) input?

**Comment by natario1** [comment]
Yes, I need to decode them too (will reencode and mux using MediaCodec and MediaMuxer). And source content will be regular media files, read from local disk. Is this possible?

**Comment by tonihei** [comment]
Just for the part about "load and render audio/video samples as fast as possible":
You should be able to inject a `Clock` into `SimpleExoPlayer`. I think you need to subclass `SimpleExoPlayer` and call the protected constructor taking a `Clock` as argument to do that. If you use an `AutoAdvancingFakeClock` (which is in the testutils) you can run the internal player loops as fast as possible.

Note that you most likely need a custom Renderer for audio and video (or a fork of our defaults) to get this to work correctly because the second argument of `Renderer.render(positionUs, realTimeUs)` is still the actual real-time and will probably cause our default renderers to drop most of the frames. [Untested]

**Comment by ojw28** [comment]
`ExoPlayer` itself doesn't seem that well matched to what you're trying to do. In trying to use it you'll be pulling in a lot of logic related to playback (e.g. playing at a particular speed, as mentioned above) that you'll then be looking for ways to disable or fudge to do what you need.

I'd be tempted to try and use `ExtractorMediaSource` directly from your own code (but nothing higher level than that).
