### ISSUE TITLE
[Demo app] Add networkSecurityConfig to allow http connections on Android Pie

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#5311]
Since Android Pie, an application has to explicitly list the domains to which it can connect via insecure http. The demo app is commonly used to diagnose playback issues, and at least in development period it's very common to host assets and/or the DRM server on insecure servers.

It's easy to add, but it would be nice if it worked out of the box (or, at least, I'd just have to add my domain to the xml file instead of having to create the entire setup).

**Comment by AquilesCanta** [comment]
I'll have a look.

**Comment by AquilesCanta** [comment]
This is done internally. @andrewlewis, any reason not to apply by default on the external demo app?

**Comment by ojw28** [comment]
It's not done because we want our demo app to encourage best practice. This is particularly true given less experienced app developers sometimes fork it and use it as the starting point for building real applications. A developer who does this is unlikely to remove a permissive network security configuration.

I don't think there's a whole lot of difference in terms of effort between what a developer has to do now and what they'd have to do if there were already an xml file for them to edit (obviously it's less work if the file is already there, but it's a one minute job either way). So my preference would be to leave it how it is now.
