### ISSUE TITLE
ClippingMediaSource doesn't work for some text and metadata formats

### ISSUE THREAD

**Issue by MuVen** [google/ExoPlayer#5317]
### Issue description
Load a video with a certation duration. Example 3 secs. Load subtitles .srt file which has content till 50 secs. now play the video.

After playing for 3 secs video stops.  But the video duration (exo_position) keeps on updating and the player loads all the subtitles till 50 secs.

Ideally once the video stops, onCueChanged should be called.

**Comment by ojw28** [comment]
This is working as intended currently. Subtitles are considered media. If you've provided 50 seconds of subtitles, then there's 50 seconds of media for us to play.

The normal solution to this would be to wrap the "long" source in a `ClippingMediaSource` before putting it into the `MergingMediaSource`. Unfortunately I don't think that works currently, due to the way subtitles are handled through the player. Metadata has a similar issue.

I'll mark this as a bug to resolve that issue, but I don't think it'll happen any time soon, and is quite a big change to make.

**Comment by ojw28** [comment]
More details about what this is tracking;

`ClippingMediaSource` clips media to a particular end position by not outputting any samples beyond the specified point. However some subtitle and metadata formats pack multiple sub-samples into a single sample, which can span a long period of time. For side-loaded subtitles it's common for there to be only a single subtitle at `t=0`, containing sub-samples that span the entire duration of the content. Hence clipping has no effect.

We should re-structure things to fix this. The presence of sub-samples also requires `Format.subsampleOffsetUs`, which adds extra complexity. If freasible, we should probably consider removing the notion of a sub-sample completely, and have what are currently sub-samples delivered from the sources as regular samples instead. This is quite a big change. We currently consider a subtitle file as a sample that needs decoding. After such a change we'd be treating it more like a container of multiple samples that needs extracting.

**Comment by icbaker** [comment]
This is now resolved on the dev-v2 branch by the commit linked above. It should be included in the next minor release.
