### ISSUE TITLE
Unicode Character (Emoji) in Video URL Isssue

### ISSUE THREAD

**Issue by adapana** [google/ExoPlayer#5334]
I have video urls stored in db, and some url has emojis in URL. 
But Exo player failed to play video which has these Unicode characters.

This video is playing in browser but exo player failed to load.

Sample URL:
https://statusvid.sgp1.digitaloceanspaces.com/video/When%20degree%20boys%20enters%20in%20the%20college%20--%20Attitude%20WhatsApp%20status%20for%20legends%20✌%20-%20YouTube.mp4

Please give some solution how can I play videos like this.

**Comment by tonihei** [comment]
The provided link plays fine in our demo app. This suggest that it's an issue in your app or database rather an ExoPlayer issue. Also worth checking if it's device-specific by trying to play the video on another device.

**Comment by ojw28** [comment]
Aren't URLs only supposed to have ASCII characters in them? Since Toni says the demo app can play the link fine, I guess something in the network stack must handle encoding the character into ASCII before the request is made.

However, if you're seeing an issue with a particular network stack or version(s) of Android, then it's possible you need to encode the character yourself before passing it to ExoPlayer. I think it should be encoded to `%E2%9C%8C`. It also seems weird (I'd go so far as to say that it's incorrect) that the sample URL has the spaces already URL encoded, but not the ✌.

**Comment by adapana** [comment]
Thank you @tonihei  and @ojw28 for quick reply.

I tried above URL in different android version, Video is not playing in v5.1(Lollipop) but playing fine in 8.0(Oreo).

**Comment by ojw28** [comment]
Were you able to resolve the issue by encoding the character, as suggested above?

**Comment by adapana** [comment]
@ojw28  yes its working with character encoding to UTF-8. Thanks for your suggestion.
