### ISSUE TITLE
Why is max buffer to switch down so big?

### ISSUE THREAD

**Issue by JanKokalj** [google/ExoPlayer#534]
Hi,

why is DEFAULT_MAX_BUFFER_TO_SWITCH_DOWN_MS (HlsChunkSource) in demo so big (20000)? Should't be smaller so player can switch faster if there is a problem in streaming or am I missing something? I am doing tests on 2g/3g cellular network and find this quite anoying. Is it safe to lower that value?

**Comment by ojw28** [comment]
I think you've misinterpreted what the constant means. It basically means "don't switch to a lower quality if we have 20 seconds or more media in the buffer". Its purpose is to avoid flapping between high and low qualities whilst the buffer is relatively full, which would otherwise happen if bandwidth were to temporarily drop.

Note that setting it to a smaller value actually delays possible switching to a lower quality stream for longer (because more of the buffer has to drain). It wont make anything faster.

**Comment by JanKokalj** [comment]
Thanks for the explanation. Can I suggest an update to the parameter documentation in code, I can imagine that others might have trouble understanding too.

**Comment by Arqu** [comment]
That shouldn't happen at all, as for HLS at least, once the master playlist is loaded the individual media playlists are added to a "variants" list which is later checked to see which formats are enabled and lastly they are sorted and the first one (the one with the lowest bandwidth required) is returned. You can look further at it here: https://github.com/google/ExoPlayer/issues/281, it also explains how you can approach it to make your own "selecting logic". In your case I would examine the BANDWIDTH parameter assigned to your streams and make sure they are correct.

**Comment by ojw28** [comment]
What shouldn't happen at all?!

**Comment by Arqu** [comment]
The player doesn't pick up the first stream in the list but the stream with the lowest bandwidth requirement, thus the solution in JanKokalj's edit of his last comment should have no impact at all as it is not supposed to work that way. Hope that clarifies that.

**Comment by ojw28** [comment]
Ah. The player does actually pick up the first stream in the list as its initial quality, as recommended by the HLS specification. See the part of HlsChunkSource commented as "Select the first variant from the master playlist that's enabled".
