### ISSUE TITLE
Exoplayer too aggressive when fetching dash segments in live streaming

### ISSUE THREAD

**Issue by levyshachar2** [google/ExoPlayer#5403]
Hi , we experience an issue when trying to play live dash stream using Exoplayer v2.
Our scenario and setup is as follows:
We have a local PC running FFMPEG that captures video from a capture card , streaming it in mpegts in TCP to remote Amazon EC2 computer.
The EC2 computer receive the stream using TCP connection in FFMPEG and transmux the content from mpegts to DASH.
After that we want to copy the segmented DASH output to S3 and Cloudfront.

The issue:
Exoplayer shows "Playback failed" after a couple of minutes of playback.
In the logs we can see a lot of 404 errors.
It looks like that Exoplayer tried to load segments that are not quite available yet at Cloudfront.
The playback stops and exists with playback failed error.
Our expected will be that exoplayer will be less aggressive in retrieving segments in live streaming and will not stop playing even if he receive 404 error.

The issue does not occur when we try to play directly from the EC2 server (using simple HTTP server)
It looks like there is small latency until the segments are actually available at the Cloudfront server, which are not taken in consideration when playing live.
I looked a little bit at the dash specifications , something that caught my eye was

> A DASH client should avoid being too aggressive in requesting segments exactly at the computed segment availability start time, especially if it is uncertain to be fully synchronized with the server. 
If the DASH client observes issues, such as 404 responses, it should back up slightly in the requests.

https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf
4.3.6

The issue can be produced in the following steps:
1) add the following URI to the medialist..json file (sent privately to the developer Gmail)
2) Run Exoplayer demo with the following URL
3) wait for a few minutes , you should receive an error "Playback failed"

Link to reproduce:
sent in email.

Version of Exoplayer:
2.9.2

Android device:
We use a generic android box - Himedia Q10 pro running Android 5

I didn't provide adb logs as I think it's not relevant , can send if it's needed

**Comment by ojw28** [comment]
This kind of issue can be quite tricky to debug, but there are multiple really weird things happening with this stream:

* Occasionally the manifest XML is just invalid, causing errors like ` org.xmlpull.v1.XmlPullParserException: Unexpected EOF (position:START_TAG <UTCTiming schemeIdUri='urn:mpeg:dash:utc:http-xsdate:2014' value='http://time.aka'>@768:84 in java.io.InputStreamReader@d0e4ec0)`. When I saw this failure I was also playing the stream with the [DASH-IF reference player](https://reference.dashif.org/dash.js/v2.9.2/samples/dash-if-reference-player/index.html), and it failed simultaneously with a parsing error, indicating this is a stream issue rather than a problem with ExoPlayer.
* I'd expect to see segments being added to the `SegmentTimeline` gradually over time, but they appear to be added in big blocks of about a minute and a half. Furthermore, if you seek to the end shortly after one of these updates, the segments you get back don't appear to have timestamps that are properly aligned with the timeline. Again, I tried with the DASH-IF reference player and saw some issues seeking near the end of the stream there as well.

I was not able to reproduce the 404 issue, but my broader conclusion is that the stream is not behaving correctly. To address the specific point about 404s: If you're using a `SegmentTimeline` then I would have thought segments should just not be present in the timeline before you know they're going to be available to the client, which would make it impossible for a client to get this wrong. I also think that on the serving side, you need to be making sure segments really are available when they should be, so if you're using a distribution mechanism that doesn't guarantee that, you might have a fairly fundamental problem. The part of the DASH-IF document you're quoting seems to be primarily for handling inaccuracy in the client's clock, not availability problems on the serving side.

**Comment by levyshachar2** [comment]
Hi , thank you for your comment.
We investigated a little more and it seems like that issue probably related to awscli sync and less related to exoplayer.
I'm closing this issue , thank you
