### ISSUE TITLE
Request: update docs about when `player.videoFormat.width`  could return `NO_VALUE`

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5409]
It only says there about `NO_VALUE` that :

>  value for various fields to indicate that the field's value is unknown or not applicable.

But it doesn't say when it occurs.
If I open an MP4 file from a server, could it occur  ?

How could it be that it's about to show a video, but doesn't know what is the size of the video? I don't understand what are the possible scenarios for this...

Or is it just when the video wasn't decoded at all yet? But this might be what "not applicable" means, no? What about "unknown" ? 

Please update the docs about it. Should we handle such weird cases even in [VideoListener.onRenderedFirstFrame](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/video/VideoListener.html#onRenderedFirstFrame--) callback?

**Comment by ojw28** [comment]
If you need to size something (e.g. a UI component) then you should use `VideoListener.onVideoSizeChanged`, which isn't documented as receiving `NO_VALUE`. This is what `PlayerView` does, for example. This callback gets the size on the output size of the decoder, which is the actual size of the decoded video buffers.

> Or is it just when the video wasn't decoded at all yet? But this might be what "not applicable" means, no? What about "unknown" ?

* Not applicable would normally mean it's not a video `Format` (e.g. resolution is not applicable to audio formats).
* Unknown means it is a video `Format`, but the dimensions are unknown. It's somewhat hard to document the cases because `Format` objects are used throughout the codebase. As an example, a `Format` derived from an HLS manifest that doesn't use resolution tags would end up falling into this category. An attempt to document all such occurrences centrally in `Format` Javadoc would inevitably code rot. An attempt to document them in a distributed way wouldn't really work, because no-one would find it. The extent to which pieces of the player can be customized also poses a further challenge.

In practice I think `SimpleExoPlayer.getVideoFormat` will always return a `Format` with set resolution by the time `onRenderedFirstFrame` is set, but as above, you should use `VideoListener.onVideoSizeChanged` to be sure.

**Comment by AndroidDeveloperLB** [comment]
About `VideoListener.onVideoSizeChanged` and `onRenderedFirstFrame` , ok, but I'm still curious:

How could a video have an unknown resolution? Does it have a changing resolution as you play it?

Is it possible to get just the video specs without really playing it? Or is the normal, Android framework API good enough for this, as shown [here ](https://stackoverflow.com/a/33770238/878126) for example? Which is more recommended? Does ExoPlayer support more ? Is it more reliable? I can see that this API is for files, but I wonder if it's also for other types ...

Anyway, I suggest to mention the `onVideoSizeChanged` in the docs for this, as a suggestion of where to get this information, when it's safe.

**Comment by ojw28** [comment]
The video resolution is always known when the output buffers come out of the decoder. As above, use `VideoListener.onVideoSizeChanged` to get it.

> Is it possible to get just the video specs without really playing it? Or is the normal, Android framework API good enough for this, as shown here for example? Which is more recommended? Does ExoPlayer support more ? Is it more reliable? I can see that this API is for files, but I wonder if it's also for other types ...

ExoPlayer doesn't currently support this use case (although with enough ingenuity it would be possible to implement with the various components that ExoPlayer provides). Providing direct support is tracked by https://github.com/google/ExoPlayer/issues/3609.

**Comment by AndroidDeveloperLB** [comment]
I see. 
The link you provided seems like the exact question I asked, right? Though, it is said about audio and not video... So I've asked about it there too :)

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Were the docs updated, then? Is it now clearer?
