### ISSUE TITLE
Bug: unable to play video just once for files that are inside of the app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5434]
For some reason, even though I set  `player!!.repeatMode = Player.REPEAT_MODE_OFF` , I keep seeing the player playing in an infinite loop.

Trying to have a workaround for it using `player!!.playWhenReady = false` inside the callback of  `onPositionDiscontinuity` , it pauses after it already started the new loop.

I think this is a bug, because it seems all of the `repeatMode` values do the same thing.

Also, if I choose to play a video from the web, it works fine...

Attached sample project to show issue. 

[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2792326/ExoPlayerTest.zip)

**Comment by ojw28** [comment]
It's looping because you're using `LoopingMediaSource`. Which you're not using when playing from the web.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 I see, so what's the point of having the `repeatMode` in this case ? And what should I use instead?
Why is there `LoopingMediaSource` , if it ignores  `repeatMode` ? I thought that it just allows it ...

**Comment by AndroidDeveloperLB** [comment]
EDIT: I think this solves it:

`prepare(LoopingMediaSource(ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.uri),1))`

Is it correct?
But then when can I use `repeatMode` ?

**Comment by ojw28** [comment]
You don't need to be using `LoopingMediaSource` at all. Just use repeat modes. Repeat modes should normally be preferred as per the special box on this subject in the [developer guide](http://google.github.io/ExoPlayer/guide.html#looping-a-video). `LoopingMediaSource` may be useful for certain niche use cases where you want to repeat a fixed number of times (without having to count them yourself).

**Comment by AndroidDeveloperLB** [comment]
It's actually a bit weird for me. Why not letting the `repeatMode ` handle all of those cases? Meaning it can take number of looping iterations: 0 - infinite, 1 - just one iteration, and so on?

Also, what should I use instead of `LoopingMediaSource` ? 

Just this:

`prepare(ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.uri))` ?

Seems to be correct.

I don't understand then. Why have 2 classes that can do the same thing, and collide with each other? Is it for wrapping special cases?

**Comment by ojw28** [comment]
> Just this

Yes. Just provide an `ExtractorMediaSource` and use repeat modes.

> Why have 2 classes that can do the same thing, and collide with each other?

`LoopingMediaSource` predates the more flexible repeat modes. There are still some niche use cases where it's easier to use it instead of repeat modes, such as repeating a fixed number of times without having to count them yourself.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Isn't `LoopingMediaSource`  more powerful? It allows no repeating, infinite repeating, and specific-loop-iterations of repeating.
What's more is there? And if `repeatMode ` replaces it, why doesn't it have the specific count of repeating? 
I don't get why have 2 mechanisms for repeating. Because of this it didn't work for me as I was confused about using them both ...
Could you please at least update the documentations for both, to have a warning that using both of them might result in unexpected results?

**Comment by ojw28** [comment]
> @ojw28 Isn't LoopingMediaSource more powerful?

No, because it doesn't allow turning repeating on and off during playback (e.g. to build a UI toggle), and because it doesn't have the concept of `REPEAT_MODE_ONE` vs `REPEAT_MODE_ALL`.

> Could you please at least update the documentations for both

It doesn't make any sense to use both at once, and there's no evidence that developers in general are confused by this issue. `LoopingMediaSource` is already documented reference using `setRepeatMode` instead, as is the `LoopingMediaSource` section of the developer guide. We will add the word "instead" explicitly to the former, but i don't see any reason to do anything beyond that.

> to have a warning that using both of them might result in unexpected results?

The results are not unexpected. If you use any feature that enables looping, you will get looping.
