### ISSUE TITLE
Multiple video adaptation sets

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#5457]
Hello,
I need to change AdaptiveTrackSelection to select track by my private logic.
There is no issue with that.
BUT(!), I want to select track from ALL tracks (from all video adaptation sets) and i cant find the right way to do that.
In DefaultDashChunkSource, the 'adaptationSetIndices' member is only {0} so my other video adaptation set just disappear?

Please advise.

**Comment by AquilesCanta** [comment]
I think you should put them in the same adaptation set. 

Adapting between different groups is not something that ExoPlayer supports. Implementing this might require a lot of work. I cannot think of a correct and simple enough way for me to explain in a few lines here. Maybe @ojw28 can help.

**Comment by ojw28** [comment]
Your DASH manifest should include sufficient signalling to tell the player which representations it can adapt between. See https://github.com/google/ExoPlayer/issues/5270 for information about how DASH manifests can signal that adaptation is allowed between `AdaptationSet`s. ExoPlayer does support this provided the signalling is present.

Without sufficient signalling, the player is correct in not adapting between different `AdaptationSet`s, because it has no way of knowing that the representations are of the same content (rather than entirely different video streams).
