### ISSUE TITLE
Question regarding CastPlayer and MediaSession

### ISSUE THREAD

**Issue by JesperQv** [google/ExoPlayer#5461]
Hi Team,

I'll get right to the issue at hand. I'm trying to use CastPlayer to be able to Chromecast audio. I've gotten it to work. However, my MediaControllerCompat.Callback doesn't seem to get any onMetadataChanged function calls. It works fine when I'm using the SimpleExoPlayer but as soon as I toggle the player to the CastPlayer the metadata doesn't update.

If possible I'd like some clarifications regarding what to do when toggling between players to get it to work with MediaSession. 

Right now I have a custom player class that implements Player and wraps both players while listening to CastSessionAvailability and sets the right one as the "currentPlayer", kind of like how it looks like in the cast demo. I have a MediaSessionConnector where I've used setPlayer with my player and PlaybackPreparer and QueueNavigator. Is this the right way to proceed? Or do I need separate PlaybackPreparers and QueueNavigators for both my players?

Thankful for all help I can get,
Jesper

**Comment by AquilesCanta** [comment]
As discussed, could you take a look, @marcbaechinger?

**Comment by marcbaechinger** [comment]
Your setup sound about right and is intended to work like you say.

In case you are using the `TimelineQueueNavigator` it should work with both player implementations, so you can use the same in case you want to support the same `PlaybackStateCompat.ACTION_SKIP_*` actions with both players (which I assume you want to). 

It's different for the PlaybackPreparer. It's methods are called to prepare a player for a given media item. So if a `MediaControllerCompat` request a `ACTION_PLAY_*` or `ACTION_PREPARE_* `for a given media item the preparation needs to be done for the player currently in use. For the `CastPlayer` you would have to fill the remote queue for that with `castPlayer.loadItems(...)` and for the `SimpleExoPlayer` you would have to call `simpleExoPlayer.prepare(concatentingMediaSource)`. So if you are going to change the player you need to either have a separate PlaybackPreparer for each player and change to it when setting the player to the connector, or a single PlaybackPreparer needs to be aware what player is currently in use an prepare either one or the other.

(Note: you only need a PlaybackPreparer if you want to support ACTION_PLAY_* and ACTION_PREPARE_* from MediaControllerCompat clients.)

I think for your custom Player class which wraps both player (similar to the PlayerManager of the CastDemo app), you would to set a new PlaybackPreparer at the moment when you are, in your words, """ listening to CastSessionAvailability and sets the right one as the 'currentPlayer',""".

**Comment by JesperQv** [comment]
Thanks for your answer @marcbaechinger 

The way I built my custom Player I added a custom prepare function that takes both a 
`ConcatenatingMediaSource` for the `SimpleExoPlayer` and also an array of `MediaQueueItem` for the CastPlayer. Then internally I use the proper one depending on which player is active at the moment. 

[Here's](https://github.com/JesperQv/Listn/blob/improvement/player_refactoring/device/src/main/java/com/jesperqvarfordt/listn/device/player/ListnPlayer.kt#L48) a link to my prepare method in case you want to see for yourself.

The player in itself is working pretty good as of now, I can actually swap between `ExoPlayer` and `CastPlayer` seamlessly. However when using the `CastPlayer` I'm not getting `onMetadataChanged` updates as mentioned earlier.

Since my custom player is actually a Player I'm only using `MediaSessionConnector.setPlayer` once with my custom player + `PlaybackPreparer` (found [here](https://github.com/JesperQv/Listn/blob/improvement/player_refactoring/device/src/main/java/com/jesperqvarfordt/listn/device/player/ExtendedPlaybackPreparer.kt)). 

Is this ok to do or should I use `setPlayer` with cast/exo-player every time I toggle?

**Comment by marcbaechinger** [comment]
Oh, I did not realize you are passing your custom player to the connector.

I think then the problem is with your implementation of addListener(). When you do `mediaSessionConnector.setPlayer(player,...)`, the connector does add a listener to the player. Then the connector updates the metadata each time this listener is called with `onTimelineChanged` or `onPositionDiscontinuity(PERIOD_TRANSITION)`.

So you need to make sure that the calls to the listener of each, the `SimpleExoPlayer` and `CastPlayer` are delegated to the connector. Easiest to do this would be to call `connector.setPlayer(player)` again, because then the listener is removed and added again which, according to your implementation would add the listener to currentPlayer.

If you do not do setPlayer(player) again, the listener is only on the currentPlayer of at the time you initially passed it to the connector.

**Comment by JesperQv** [comment]
Hi @marcbaechinger 

I had the weekend to play around with this and trying out different solutions. It seems like you were right that I have to call `setPlayer` every time I switch the players, so I added a `onPlayerToggled` callback that handles that.

I am however still having a little trouble. When using the `SimpleExoPlayer` it seems each `Window` within the `Timeline` corresponds 1 to 1 to a audio track (my app is a music player, so I have a playlist of several tracks). However, when I use the `CastPlayer`, regardless of if I start with it or switch to it mid-stream the `getWindowCount` function always returns different values that always seem to be lower than expected. I looked at your issue tracker and if I understand it correctly this is a known issue?

**Comment by marcbaechinger** [comment]
@AquilesCanta to comment on cast issues.

**Comment by AquilesCanta** [comment]
Hi @JesperQv, please look around the issue tracker for existing issues. For example, see #4964. There are some shortcomings in the cast extension which we aim to solve in the few coming weeks with the release of a custom receiver. You are welcome to try working around these as suggested in the different github issues, or you can wait a bit until we release the custom receiver. I'll close since the original reported issue has been resolved.
