### ISSUE TITLE
Question: Extension FFmpeg, Using Video soft decoders, drop frames seriously on some old devices!

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#5463]
We extended the FFmpeg extension. Using the soft video decoder to robust the player.But there are decoding efficiency problems on some old tv devices, resulting in serious frame loss. 
Maybe this is not an issue of ExoPlayer,  but we hope you could give me some advice how to optimize.
such as how to implements a neno-optimized FFmpeg decoder. If possible, help you could give a build script, so we could easily compile the dynamic library. Thanks!

**Comment by andrewlewis** [comment]
One thing that might be helpful: you could look at how the vp9 extension uses OpenGL to do color-space conversion on software video decoder output frames. You may want to apply the same approach if you are not doing it already. We don't have time to provide more detailed guidance since, as you say, this is not an ExoPlayer issue, so I will close this.
