### ISSUE TITLE
Player returns STATE_ENDED after loading the stream. 

### ISSUE THREAD

**Issue by gabrysgab** [google/ExoPlayer#5473]
### Issue description
When starting the stream player returns state_ended. I tried to pinpoint the exact issue and got to the code changes in issue #4185 . Our stream is static and the segment timeline is defined by timestamps, it seems that in that situation the check
`  if (periodDurationUs != C.TIME_UNSET
        && representationHolder.getSegmentStartTimeUs(segmentNum) >= periodDurationUs) {
      // The period duration clips the period to a position before the segment.
      out.endOfStream = true;
      return;
    }`
in DefaultDashChunkSource.java is always true and makes the player to return state_ended. 

### Reproduction steps
Loading the stream results in STATE_ENDED. 
[Manifest.zip](https://github.com/google/ExoPlayer/files/2831260/Manifest.zip)
I'm adding the stream manifest that's having that issue. 
I've successfully reproduced the issue in demo app. 

### Link to test content
I've sent the link to test content on the provided mail address. Please check if your IP needs to be white-listed to get the content to work.  

### Version of ExoPlayer being used
Exo player version 2.8.4 was handling that kind of streams without problem. After updating to 2.9.x the streams aren't working. 

### Device(s) and version(s) of Android being used
The issue is unrelated to the Android version or device. I've reproduced it on Google Pixel (Android 9) and on Samsung SM-G357FZ (Android 4.4.4) 

### A full bug report captured from the device
There aren't any logs that would suggest what causes this behavior. Not a single error in the exo log output during stream loading.

**Comment by tonihei** [comment]
That might be an issue with the manifest as the total duration is not in the same time scale as the segment durations (total duration: absolute duration of about 1h, but segment timeline times with unix timestamps).

@ojw28 Should that be supported by the player or is that a malformed manifest?

**Comment by ojw28** [comment]
The manifest looks incorrect to me:

* `MPD@duration` is the total duration of the presentation.
* `Period@start` is the start time of a period relative to the start of the presentation. In this case the single period has the default `Period@start = 0`.
* `S@t` is the start of the segment relative to the start of the period. The first `S@t` is a very large value (time since the epoch).

This effectively means the first segment is approximately 49 years after the specified end of the presentation. DASH clients are supposed to clip media beyond the end of each period (or the presentation), therefore it's correct that we're clipping it and transitioning straight to the ended state.

**Comment by ojw28** [comment]
[Note: I updated my reply above to make more sense]
