### ISSUE TITLE
Compilation problem when updating from 2.8.4 to 2.9

### ISSUE THREAD

**Issue by Arnaudp767** [google/ExoPlayer#5475]
Hello,

I trying to update my exo project from 2.8.4 to 2.9.
I changing my compile option (compile 'com.google.android.exoplayer:exoplayer:2.9.0'), adding targetCompatibility JavaVersion.VERSION_1_8 and jackOptions.
But I'm getting this error when I run the project : 
ERROR: HlsSampleStreamWrapper.java:174-175: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable.

Any ideas ?

**Comment by tonihei** [comment]
Can you try to clear the caches and rebuild the project? Sounds as if there is some configuration leftover which didn't migrate correctly.

**Comment by Arnaudp767** [comment]
Yes ! I think it's work after full sync and rebuild. 
Changing classpath 'com.android.tools.build:gradle:2.2.2' to classpath 'com.android.tools.build:gradle:3.0.1' solve my problem.

My project seems ok except this : 
`mediaDataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "mediaPlayerSample"), (TransferListener<? super DataSource>) bandwidthMeter);`

error: type TransferListener does not take parameters

Any change on DefaultDataSourceFactory constructor ?

**Comment by tonihei** [comment]
You don't need to provide the `BandwidthMeter` to the `DataSourceFactory` and the `TrackSelectionFactory` anymore. That gets handled automatically by the player. See this [blog post ](https://medium.com/google-exoplayer/https-medium-com-google-exoplayer-simplified-bandwidth-meter-usage-17d8189f978b) for details.

(And we also removed the template parameter from `TransferListener`. That's why the compiler is complaining specifically).

**Comment by tonihei** [comment]
Closing as answered.
