### ISSUE TITLE
HEVC 4K content with 30/60fps variants causes green pixelation on certain devices

### ISSUE THREAD

**Issue by Jogan** [google/ExoPlayer#5483]
**Issue description**
While playing 4K HEVC content with multiple fps variants, during a variant switch going from a variant with 30fps/4K to a variant with 60fps/4K. Green pixelation occurs and never recovers.

**Reproduction steps**
Add the provided url to sample chooser.  Launch content in demo player and wait for variant switch.

**Expected behavior**
The player plays the video and audio. No artifacts or pixelation occurs.

**Actual behavior**
The screen is green and pixelated.

**Link to test content**
Will be sent to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with a subject "Issue #5483".

**Version of ExoPlayer being used**
Tested on both:
- r2.8.4
- r2.9.4

**Device(s) and version(s) of Android being used**
FireTV 4K Stick (AFTMM - Android 7.1.2) -> ISSUE OCCURS 
Sony BRAVIA 4K (XBR-43X800E - Android 7.0) -> ISSUE OCCURS 
Samsung Galaxy S9+ (SM-G965U - Android 8.0) -> ISSUE DOES NOT OCCUR

**A full bug report captured from the device**
No visible issues in logs. When the change occurs the logs look "normal" (no warnings/errors).

**Comment by andrewlewis** [comment]
I reproduced this issue on a Sony Bravia 4k TV. As you indicate, it looks like no useful diagnostics are output to logcat when the problematic adaptation occurs.

If I set track selection parameters to force selection of only the 4k/60fps stream, it plays fine. It looks like the corruption occurs only when adapting from 4k/30fps to 4k/60fps only (and goes away after adapting back down). For reference, the problematic adaptation is from `hvc1.1.6.L150.11` to `hvc1.2.4.153.11`. We are feeding a keyframe after the adaptation and I didn't spot any issues with how we are reconfiguring the decoder.

We've seen devices in the past where adaptations between formats with particular properties caused visual corruption. In this case I think it's likely that there's a decoder bug that causes some state not to be cleared because the resolution of the video is not changing. I wouldn't be surprised if adaptation from profile 1 to profile 2 (main 10) requires some extra state to be cleared but this isn't happening.

To work around the immediate issue, I think the best fix is (unfortunately) to set up the representations differently so that the resolution changes, and check whether this avoids the visual corruption. It would be good if you could try that out. If it doesn't fix it we should investigate a bit deeper and follow up with Sony in case they can help determine what is going wrong. You could also try using the same profile to see if that avoids the problem.

If this is indeed a decoder bug present on these two devices we should also follow up with the OEMs to fix that. This is likely to take a long time to get into production as it will require system updates. To proceed with this, it would be useful to have a stream that can reproduce the issue and doesn't expire, and the result of any investigations regarding what adaptations do succeed.

**Comment by Jogan** [comment]
Just adding a few more details:
- This occurs on both HLS and DASH
- The issue is present when going from a 1080 resolution up to 4K as well
- When manually selecting the variant (using track selector) the issue IS NOT present.
- Like @andrewlewis said by forcing the selection to only one variant, the content will play fine.

It's not exclusively a Sony issue this also happens on the new FireTV sticks (AFTT). Both of these devices (the Bravia TVs and the Fire sticks) use different hardware decoders.

I think we will need to follow up with each OEM to resolve the issue. In the meantime there are workarounds described above that can be done to alleviate the issue.

**Comment by andrewlewis** [comment]
- Going on the assumption that this is a decoder bug in the MTK chpisets: it's worth trying out different configurations for the encoder, or different encoders, to try to find a set of options that do not trigger the decoder issue. For example, use the same Profile for all qualities if not doing that already. It is difficult to know exactly what aspect of the adaptation is problematic given that we don't have any logging about the error, but it might be possible to track down the issue by experimenting.
- We have a workaround that releases the decoder instead of trying to adapt it (see [`codecNeedsReconfigureWorkaround`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.10.0/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1746-L1759)). However, the adaptation is probably not going to be seamless when using the workaround, so this may not be a viable option.

**Comment by bkodirov** [comment]
Updates regarding the issue:
- I could reproduce the issue on the OnePlus [6T device[](https://en.wikipedia.org/wiki/OnePlus_6T) which used `OMX.qcom.video.decoder.hevc`. This device has a Qualcomm chip on it.
- When the error happens(Green screen) application's UI thread is barely responding. It gets very 

Regarding `codecNeedsReconfigureWorkaround`. Can you clarify please what is the correct usage of this should be? Looks like it a private API(method)

**Comment by ojw28** [comment]
`codecNeedsReconfigureWorkaround` is a private API and not normally intended for use by app developers. The idea is for you to experiment with having it return true, which forces decoders to be recreated from scratch rather than reconfigured, to see if the issue still reproduces in that case. You will need to build from source to do this. Once you have a test stream that doesn't expire or require authentication, it's pretty easy to check the project out as source and then use the included ExoPlayer demo app for testing.

**Comment by andrewlewis** [comment]
Did you find a workaround for this or diagnose any issues with the stream in the end?

**Comment by stevemayhew** [comment]
@Jogan might also try the tunneling decoders (pretty sure FireTV 4k supports this, maybe not for non-secure though) and see if it happens there too.
