### ISSUE TITLE
Subtitles in Live Dash stream not working

### ISSUE THREAD

**Issue by icetronics** [google/ExoPlayer#5485]
### Issue description
Subtitles are not rendering in *Live* streaming that uses MPEG-DASH with PlayReady.

### Reproduction steps, links, bug report
Sent resources via email.

### Version of ExoPlayer being used
2.9.4

### Device(s) and version(s) of Android being used
FireTV (any generation)
FireOS 5.2.6.8

Thanks in advance!

**Comment by ojw28** [comment]
The stream is so unstable it's virtually impossible to debug. Requests that I think should succeed repeatedly 404, and the stream seems to randomly flip between having content protection and not having any. I did manage to download one of the subtitle segments. It looked either empty or malformed, although I'm not 100% sure of this.

It would be good if you could validate some other players are able to successfully play the content.

**Comment by icetronics** [comment]
Hi @ojw28, sorry, I have no idea why the stream is jittery for you.

I have now attached a zip that contains an m4s subtitle chunk which is not getting rendered by ExoPlayer. The time interval does look suspicious:
`begin="430719:29:18.195" end="430719:29:19.526"`

Can such values be handled properly by ExoPlayer or do we need to do anything special? We've tried on other platforms (eg. Chromecast) and the subtitles are rendering correctly.

Thanks for your help in advance!

[subtitles.zip](https://github.com/google/ExoPlayer/files/2880901/subtitles.zip)

**Comment by nigelmegitt** [comment]
Sorry for the drive-by comment, but a media time expression with 430719 hours in it would not be at all suspicious for a media timeline that is set to begin at the UNIX epoch at the beginning of 1st Jan 1970 - indeed it's about right on a rough calculation. This is a reasonable pattern to use for ongoing live streams.

**Comment by ojw28** [comment]
@nigelmegitt - Does the file itself look sensible to you (e.g. if you open it in a text editor)? To me it doesn't look like the file is either ISO/IEC 14496-30 or raw TTML, but I'm just going by memory here so I could be mistaken.

**Comment by nigelmegitt** [comment]
@ojw28 I'm not on a machine with an m4s extractor installed right now but in a text editor I can see typical ISOBMFF header and a vaguely reasonable TTML in there. The TTML is claiming to need the "DFXP-full" profile which is unusual these days but anyway it presents fine as IMSC Text Profile. So yeah, looks sensible on a quick glance.

**Comment by nigelmegitt** [comment]
However a note of experience here - I've had live TTML in ISOBMFF presentation issues with other players in the past because the times in the TTML document actually ended up falling outside the sample interval for the MP4 fragment it was placed in. The playback behaviour was spec-compliant but the source data was effectively wrong, in other words it was an encoding and packaging fault. @icetronics is that something you checked?

**Comment by icetronics** [comment]
Thanks for the insights, @nigelmegitt.
Actually we have verified playback using stream testing websites (Bitmovin, JWPlayer) and the subtitles were rendering correctly.

**Comment by ojw28** [comment]
I figured this out. The problem is that the ISOBMFF packaging is done in a way such that none of the samples are marked as sync samples, where-as it should be that all samples are marked as sync samples. ExoPlayer ends up dropping all of the samples as a result.

So technically the content is broken. It could be argued that we should just assume every sample is a sync sample for TTML, but given the container does carry the information, it should really be set correctly rather than requiring that players hardcode this knowledge.

**Comment by icetronics** [comment]
Thanks @ojw28!
However, our backend provider came back to us saying that the ISOBMFF standard explicitly states that the sync sample box is not mandatory and:
> If the sync sample box is not present, every sample is a sync sample.

Can you please advise? Thanks very much

**Comment by ojw28** [comment]
My understanding is that the `stss` (sync sample box) is only relevant for non-fragmented MP4, where all sample information is carried within the `moov` atom. For fragmented MP4, as is used here, the `sample_flags` mechanism is used to indicate which samples are sync samples. `sample_flags` are a little complicated because they can be defined at multiple levels:

* The `trex` can define top level `default_sample_flags`
* The `tfhd` can override the `trex` by defining `default_sample_flags`
* The `trun` can define `first_sample_flags`, or `sample_flags` for each sample

But the end result must be that the sample flags computed for each sample have `sample_is_non_sync_sample` set to 0, which is not the case in the stream provided.

**Comment by icetronics** [comment]
Thanks again, I have conveyed this to our provider and we'll see what happens.

**Comment by icetronics** [comment]
Hi @ojw28! :)

According to section 8.8.3.1 of the standard:

> The flag sample_is_non_sync_sample provides the same information as the sync sample table
[8.6.2]. When this value is set 0 for a sample, it is the same as if the sample were not in a movie
fragment and marked with an entry in the sync sample table (or, if all samples are sync samples, the
sync sample table were absent)

We have managed to get the subtitles working by setting each and every sample in the `sampleSyncTable` to `true` in the FragmentedMp4Extractors. Without this modification only the first sample got the sync flag. As per understanding, if the `sample_is_not_snyc_sample = 0`, then the entire content of the **trex** box should be considered as sync samples, and should be handled as such by the player.

Do you think the above reasoning could justify a fix in the player? Thanks a ton for your time.

**Comment by icetronics** [comment]
Dear @ojw28, could you please take a moment to ponder on the above? Thanks in advance

**Comment by ojw28** [comment]
> Do you think the above reasoning could justify a fix in the player? Thanks a ton for your time.

I don't understand what you think needs fixing. If I remember correctly, the problem in the stream is exactly that `sample_is_not_snyc_sample` is *not* ending up set to 0 for every sample (when it should be).

As per my comment above, note that sample flags can be defined at multiple levels. You can't just stop at the `trex`. You need to check the `tfhd` and `trun` as well.

**Comment by ojw28** [comment]
To provide a little more detail, in your stream, for the subtitle representation, right now, I'm seeing:

* The `trex` sets `default-sample-flags = 0`
* The `tfhd` defines `default‐sample‐flags‐present = true` and `default-sample-flags = 0x02000000`, overriding the defaults in the `trex`
* The `trun` defines `first‐sample‐flags‐present = true`, `sample‐flags‐present = false` and `first-sample-flags = 0x01010000`, hence overriding the defaults in the `tfhd` for the first sample only

So the sample flags for the samples in each segment are `0x01010000` for the first sample, and `0x02000000` for all other samples. Which makes `sample_is_not_snyc_sample = 1` for the first sample and `sample_is_not_snyc_sample = 0` for all other samples. This is not what you want, since you want it set to 0 for all samples. Furthermore, right now I'm only seeing one sample in each segment, so effectively no samples are sync samples, which is the opposite of what you want.

**Comment by ojw28** [comment]
Edited the response above to make more sense.
