### ISSUE TITLE
Exoplayer enters endless buffering state when encountering discontinuity flag

### ISSUE THREAD

**Issue by fitznd** [google/ExoPlayer#5488]
### Issue description
When playing a VOD (not live) HLS playlist, exoplayer is sometimes getting stuck in buffering state after encountering a discontinuity flag, and never recovers.

Playlist plays fine in other players.

### Reproduction steps
Seek to 29:25 in the playlist url (sent separately).  Let it play for 4 seconds.  The freeze occurs at 29:29.

It's also easy to reproduce by seeking around the file a bunch.

### Link to test content
Sent separately

### Version of ExoPlayer being used
r2.9.4

### Device(s) and version(s) of Android being used
Reproducible on both Android TV using NVidia Shield w/ Android version 8.0.0 and Amazon FireTV.

### A full bug report captured from the device
Sent separately

**Comment by AquilesCanta** [comment]
Hi, I can see that the PMT's CRC checks are failing. Disabling the checks will make the stream work normally.

This doesn't necessarily mean that the CRC itself is wrong, but rather something in the packet structure. 

The issue reproduces in VLC for me. I also get a packet size related warning from dvbsnoop. I will close under the assumption that this is malformed media. If you have evidence suggesting otherwise, please post it below and I will reopen. Good luck.
