### ISSUE TITLE
generate local video thumbnail

### ISSUE THREAD

**Issue by fishforest** [google/ExoPlayer#5519]
How to generate thumbnails like Android ThumbnailUtils.createVideoThumbnail(), I looked for a similar problem #1670, but failed to solve the problem. I want to extract a certain frame of a video file directly through exoplayer. You don't need ui to participate. Can you give a suggestion? Thank you

**Comment by marcbaechinger** [comment]
You can render the video on a surface and then get the bitmap from there.

This can be done by using a TextureView which provides a [getBitmap()](https://developer.android.com/reference/android/view/TextureView.html#getBitmap(int,%20int)) method or alternatively since Android N (API 24) there is the [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) class which works on a surface view as well.

Please see also #418 where some people discussed how to do that.
