### ISSUE TITLE
Playlist has been refreshing when player is paused

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#5521]
### question description
When playing live video of m3u8.  Playlist has been refreshing when player is paused.
Can I stop refresh the playlist when player is paused by blocking the execution of loadPlaylistImmediately.
Then when player is started, I continue to execute the method.

### Reproduction steps
1. play live video.
2. pause the player 

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
VIVO X20

**Comment by ojw28** [comment]
It's working as intended that the playlist is refreshed when the player is paused. The player needs to do this to update the seekable window, detect if a live stream ends, and so on. If you want to avoid this you can stop rather than pause, and then re-prepare the player when you want to resume playback.
