### ISSUE TITLE
TTML positioning (tts:textAlign) not working

### ISSUE THREAD

**Issue by jcmore2** [google/ExoPlayer#5528]
### Issue description

We are using TTML subtitles that are including positioning information like _tts:displayAlign="center"_ _tts:textAlign="center"_ , but Exoplayer is not taking those values into account.

### Reproduction steps
Using Dash Stream with this TTML, subtitles are not appearing in the correct position that the ttml is saying. The TTML is defining the position of each paragraph moving it between Top, Medium and Bottom of the screen. Thats is respected but the text alignment is always at the left side and the style is defined to center the text.

### Link to test content

[TESTTTMLPOS06.ttml.zip](https://github.com/google/ExoPlayer/files/2876292/TESTTTMLPOS06.ttml.zip)

### Version of ExoPlayer being used

Exoplayer 2.9.4

### Device(s) and version(s) of Android being used

Device: Samsung S8 (SM-G950FD)
OS: Android 8.0

Device: Google Pixel 2 XL
OS: Android 9

**Comment by marcbaechinger** [comment]
I see that we do not parse the `tts:displayAlign` which is part of the styles definition in the header. 

When I play a stream while sideloading your ttml file, the text is centered as expected though because the `textAlign` attribute is used and honored. Subtitles are centered. The first at the top, then in the middle and finally at the bottom of the player view. 

![screenshot_20190218-173702](https://user-images.githubusercontent.com/584321/52968115-2f233380-33a4-11e9-99b8-3b4ff303f880.png)

Does this match your expectation? Are you able to reproduce the problem in the demo app?

**Comment by jcmore2** [comment]
Hi,

after your comment we were reviewing our code and we found there was a problem in our **_SubtitlePainter_** class, that we were customising.

Thanks for your quick help. This ticket can be closed.
