### ISSUE TITLE
Remove the frame when disabling video renderer

### ISSUE THREAD

**Issue by musooff** [google/ExoPlayer#5563]
In my ExoPlayer I have audio/video switching mode where user can disable video and just listen. 

To switch between audio and video I use below code

```
    fun setRendererDisabled(isDisabled: Boolean) {
        var indexOfVideoRenderer = -1

        mExoPlayer?.let {
            for (i in 0 until it.rendererCount) {
                if (it.getRendererType(i) == C.TRACK_TYPE_VIDEO) {
                    indexOfVideoRenderer = i
                    break
                }
            }
        } ?: return

        val parametersBuilder = trackSelector.buildUponParameters()
        parametersBuilder.setRendererDisabled(indexOfVideoRenderer, isDisabled)
        trackSelector.setParameters(parametersBuilder)
    }
```

Whenever I switch to audio mode, video will be disabled and audio will keep playing. But the problem is while playing audio ExoPlayer shows the frame at a moment when disabled video rendering.

My question would be how can I remove that frame and show black screen instead?

Using `default_artwork` definitely is not a solution, because I already use `default_artwork` and with an artwork it just sets a default image on top of that frame. So, if I have slightly transparent artwork, I can still see the frame. So I need to totally remove that last frame.

**Comment by AquilesCanta** [comment]
What ExoPlayer version are you using?

**Comment by musooff** [comment]
> What ExoPlayer version are you using?

I am using 2.8.2 version of ExoPlayer

**Comment by ojw28** [comment]
It looks to me like this should already happen, since we close the shutter when video is disabled ([here](https://github.com/google/ExoPlayer/blob/r2.8.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L1021)). Have you done anything special to your `PlayerView`? For example providing a custom layout, removing the shutter, or changing the shutter color?

If you disable video in the ExoPlayer demo app then the output turns black as desired, which I think indicates that this is already working correctly.

**Comment by musooff** [comment]
Apparently I was getting such behavior because I have set 
```
playerView?.setShutterBackgroundColor(Color.TRANSPARENT)
```

Thanks, solved
