### ISSUE TITLE
string mpd

### ISSUE THREAD

**Issue by frfmmdreza** [google/ExoPlayer#5565]
hi, i want to play a dash stream from a mpd string (not url), but i didn't find any guide in the documentation, can you help me?

**Comment by AquilesCanta** [comment]
I think the best option you can go with is passing the [DashManifest](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/manifest/DashManifest.html) representation of your string to [DashMediaSource.Factory#createMediaSource](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#createMediaSource-com.google.android.exoplayer2.source.dash.manifest.DashManifest-). In order to convert the string to a DashManifest you may need to use [DashManifestParser#parse](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.html).

**Comment by frfmmdreza** [comment]
thanks for your help but still DashManifestParser.parse require an uri parameter

**Comment by AquilesCanta** [comment]
That's the url of the manifest to resolve internal relative URLs. If urls contained in the manifest are all absolute, then you can use an empty URL. However, if there are relative URLs in you manifest, you'll need to pass the base URL in there.
