### ISSUE TITLE
Widevine cenc mp4 Playback fails on Nexus Player

### ISSUE THREAD

**Issue by ZygmuntMalek** [google/ExoPlayer#5568]
### Issue description
Encrypted Widevine cenc mp4 Playback fails on Nexus Player

### Reproduction steps
ExoPlayer demo app with media.exolist.json pointing to content uri and drm_license_url
repro rate: 100%

Orginal media.exolist Widewine examles for mp4 (h264, h265) could be played without issue, but after issue try to play our content, playback examples for mp4 h264 also failing and there is need to eg. device restart.

### Link to test content
Link to test content will be send by email to: dev.exoplayer@gmail.com after provider approval 

### A full bug report captured from the device
Will be send by email to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.8.4

### [REQUIRED] Device(s) and version(s) of Android being used
Nexus Player, Android 8.0.0

**Comment by AquilesCanta** [comment]
Hi, I'll reopen the issue once content is provided. Please update below.

**Comment by ZygmuntMalek** [comment]
Content sent by email to dev.exoplayer@gmail.com

**Comment by AquilesCanta** [comment]
This has been reported to the DRM team. [Internal ref: b/127808458].

**Comment by AquilesCanta** [comment]
It's worth noting that the two lower resolutions seem to work ok.

**Comment by ZygmuntMalek** [comment]
Could you provide update about this issue state ?

**Comment by AquilesCanta** [comment]
The situation is that fugu is over-reporting capabilities. However, we cannot expect an update to fix this issue because it is no longer maintained.

I am not aware of ExoPlayer blacklisting tracks due to spurious capabilities reporting. @ojw28 may be able to comment on this.

I can advise you to try and implement a custom track selector (that potentially subclasses [DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html)) that filters out tracks that are known to be unsupported. I don't think it's a good idea to maintain a similar list on ExoPlayer.

**Comment by ojw28** [comment]
I think it's more likely that Fugu has different secure and non-secure capabilities. ExoPlayer always queries the non-secure ones during track selection, and in this case ends up using the less capable secure path for playback. This is not a problem on most devices, since it's not particularly common for secure and non-secure capabilities to be different (performance may be different, but actual hard limits on what is playable are normally the same for both paths).

Fixing ExoPlayer's track selection logic to use the capabilities for the correct path is unfortunately not straightforward, because Android's underlying DRM APIs make it hard to efficiently query whether content is going to end up playing with the secure path or not at the point of track selection. We can probably hardcode some knowledge about the Widevine+Video case though, which in practice will resolve this issue in nearly all cases.
