### ISSUE TITLE
Bug in ExoPlayer with incomplete dash manifests

### ISSUE THREAD

**Issue by m-franco** [google/ExoPlayer#5577]
I can't reproduce some drm contents in Exoplayer 2.9.0 and higher (2.9.6 included).
In the playerActivity the player fall in the OnPlayerError event, with the message Invalid UUID.

Debbuging the code, I saw there is a crash with the parse of the manifest.

Profiling app with the 'Profiler Tool' sniffing the requests and the responses, I noticed that in the response the manifest is arriving incomplete.
For any reason the player is failing in the request of the manifest.

By other way.
With Exoplayer 2.1.1 integrated locally (and not since gradle file)  , the same content reproduces ok, and the manifest arrive complete.

The version Android is irrelevant.

I hope you can correct this bug and release a new version of ExoPlayer.

If you need the code and the links, send me and email account to send the information in a private way.

Thanks

Link to test content
A full bug report captured from the device
- I send it by email.

Version of ExoPlayer being used
- 2.9.6

Device(s) and version(s) of Android being used
- Huawei P8 - Android 6.0

**Comment by AquilesCanta** [comment]
As far as I can tell, the issue is pretty obvious from the logcat message: the default_KID value is not correctly formed. A UUID is expected, whereas the existing value [does not contain any groupings](https://en.wikipedia.org/wiki/Universally_unique_identifier), it is just a plain string. If I remove the default_KID value from the manifest the content plays correctly. I think default_KID parsing has been added after ExoPlayer 2.1.1, which is the reason it only fails on newer versions.

You should either customize the manifest parser to ignore/correct the malfromed value, or fix the content.

**Comment by m-franco** [comment]
The "invalid UUID" message is a consequence of the problem of the manifest is not received completely because of the method that do the http petition. I can´t override the internal manifest parser, because the class that contains this method is inside Exoplayer library.

Could you show me an example solution?

**Comment by AquilesCanta** [comment]
> Could you show me an example solution?

You can inject a custom DashManifestParser using [DashMediaSource.Factory#setManifestParser](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#setManifestParser-com.google.android.exoplayer2.upstream.ParsingLoadable.Parser-).

Do you have any evidence that supports this:

> The "invalid UUID" message is a consequence of the problem of the manifest is not received completely

?
