### ISSUE TITLE
Restart streaming on player error

### ISSUE THREAD

**Issue by jinfanzon** [google/ExoPlayer#5584]
### [REQUIRED] Searched documentation and issues
My first implementation on the stream recovery was based on the following posts:

* https://stackoverflow.com/questions/32005855/how-to-restart-video-on-exoplayer-after-exoplayer-state-ended
* https://stackoverflow.com/questions/43959176/how-i-get-exoplayer-to-resume-a-video-in-my-activitys-onstart-method
* #3490

### [REQUIRED] Question
I'd need a way to restart an HLS stream on any player error, and have indefinitely retries. I'm being unable to always recover/restart the sream and keep playing on any error like BehindLiveException among others. I've achieved to restart the stream, but looks like not always it recovers. I need the app to indefinitely retry to play the stream until it starts.

I've set the following DefaultLoadErrorHandlingPolicy:

`public class StreamerErrorPolicy extends DefaultLoadErrorHandlingPolicy {

```
private static int MIN_ERROR_RETRY = 2000;

@Override
public int getMinimumLoadableRetryCount(int dataType) {
    return MIN_ERROR_RETRY;
}
```
}`

I'm not sure if I've to have the restart the stream in the implementation of the AnalyticsListener in:

` @override
public void onPlayerError(EventTime eventTime, ExoPlaybackException error) {

```
    }
```
`
Thanks

**Comment by AquilesCanta** [comment]
I'll split the answer in two parts:

The `LoadErrorHandlingPolicy` is supposed to handle [Loader](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/Loader.html) errors. Loaders are used to download any resource, so the load error handling policy may get errors like 404s or FileNotFoundExceptions. I think the best place to start with the load error handling policies is our [medium post](https://medium.com/google-exoplayer/load-error-handling-in-exoplayer-488ab6908137), and [the documentation](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/LoadErrorHandlingPolicy.html).

BehindLiveWindowException (BLWE) signals an error condition that is detected before loading a chunk/segment. In our case, HLS segment. There is a lot of material in this issue tracker about BLWE. To sum up: In order to continue playback, the player needs to play a chunk that is no longer advertised by the server. The issue is irrecoverable. Once the exception is thrown, the only thing you can do is reprepare the player. This is done in the demo app. Look for the `isBehindLiveWindow` method in the Demo App's player activity. It's possible that you'd rather take a more preemptive approach.  For example, seeking forward before hitting BLWE or increasing the playback speed slightly.

Have a look in the issue tracker. For example, #4723 and #4009. Good luck.
