### ISSUE TITLE
Playback of MPD never switches to a higher bitrate

### ISSUE THREAD

**Issue by janeriksamsonsen** [google/ExoPlayer#5595]
### [REQUIRED] Content description
Adaptive bitrate switching not working for Dash manifest. The video plays, but it's never switching to a higher bitrate. Using profiler in Android Studio it seems like the memory consumption is going up forever allocating a massive amount of byte[] objects (segments?). The buffer appears to be filling up without respecting its constraints. The memory issue can be managed by setting prioritizeTimeOverSizeThresholds to false, but unfortunately the bitrate still stays at the lowest.  The problem is easily reproducible in ExoPlayer demo app. Trying to play the same stream in VLC is working as expected when it comes to switching bitrates.

### [REQUIRED] Link to test content 
http://213.167.98.71/wh7f454c46tw2551865891_118555674/TVOD/88888888/224/3221226688/3221226688.mpd?zoneoffset=60&servicetype=3&recType=3&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&playseek=20190301135800-20190301143300&timezone=UTC

### [REQUIRED] Version of ExoPlayer being used
2.9.6 (but problem has also been seen on all 2.9.x versions)

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3 XL with Android 9.
Nvidia Shield TV with Android 8
(never seen a device or Android version where it's working as expected)

**Comment by ojw28** [comment]
The content doesn't correctly adhere to the DASH timing model. This is also why the position displayed in the ExoPlayer demo app during playback is a huge value, where-as it should start from 0 and increase up to the stream duratoin of 35:01.

The particular problem is that the presentation timestamps in the media must start at 0 and increase up to 35:01, either because the media contains those timestamps naturally, or because the manifest specifies `presentationTimeOffset` values to adjust the timestamps to be in the required range.

I was able to add correct `presentationTimeOffset` values into the manifest and get it to play correctly. Please see the manifest attached. The only other change I've made is to make the URLs in the manifest absolute, which is just to get it playing with the modified manifest being in another location.

[3221226688.xml.zip](https://github.com/google/ExoPlayer/files/2930881/3221226688.xml.zip)

**Comment by janeriksamsonsen** [comment]
OK, thanks, let me try and see if i can modify it programatically in real-time using a custom manifest parser. 👍

**Comment by ojw28** [comment]
You should really be getting this fixed on the serving side.

**Comment by janeriksamsonsen** [comment]
Absolutely. Can i ask you how you calculated presentationTimeOffset to 93670681020000?

**Comment by ojw28** [comment]
I attached a debugger and used it to get the presentation timestamp of the first sample in the stream.

If you're OK to assume that segments with $NUMBER$=0 start at t=0, then you can also calculate it from the manifest as `(@duration * @startNumber) = (20000000 * 4683535)`, which I think gives you the same value. There's no guarantee in the DASH timing model that this will be true, however.

**Comment by janeriksamsonsen** [comment]
OK, thanks again. I'll try to convince the backend guys that our dash-timings are not correct.
