### ISSUE TITLE
Url streaming (http streaming) requested twice during song playing 

### ISSUE THREAD

**Issue by ithustle** [google/ExoPlayer#5608]
**[REQUIRED] Issue description**
Playing music (streaming) with low bandwidth cause streaming stutter and playback state throw buffering frequently, till here its normal.
But after a few seconds, seems that the url is requested again and forces music to restart in the middle of song playing.

But I'm wondering why its not happens on Youtube, Google Play Videos and others platforms that use ExoPlayer as well.

On my streaming server, I'm using ffmpeg with node-fluent-ffmpeg to transcode songs on fly and offers a better experience of streaming to my users. Is this behavior caused by my server or is it possible prevent a url request while ExoPlayer is buffering the song?

I really really appreciate any help because I'm a couple months struggling with this.

**[REQUIRED] Version of ExoPlayer being used**
2.9.2

**Comment by ojw28** [comment]
The URL will generally be requested a second time if the first request fails for some reason. For example because it times out or because there's a connection drop (which is of course more likely to happen in a low bandwidth scenario). An additional request is typically also made if the user performs a seek, since the player needs to start requesting data from a different position in the stream.

In the normal case the player will make a subsequent request with a Range header, to request data from the byte offset that it needs. So in the case that a request fails, it'll set the Range header to request data from the point it got to before the failure. In the seek case, it'll set the Range header to request data from the byte offset corresponding to the seek time.

If you're seeing the song restarting in the middle then it's likely that your server is not correctly handling range requests, which would be a server side issue.

**Comment by ithustle** [comment]
@ojw28 many thanks.
