### ISSUE TITLE
HLS stream not playing in Pie but works in older versions

### ISSUE THREAD

**Issue by Aravindraj93** [google/ExoPlayer#5611]
HLS stream not playing in Pie mobile phones. Even the demo exoplayer is also not working. 

ExoPlayer version "2.9.6"

RedMi Note7 version pie(9)

**Comment by AquilesCanta** [comment]
Is this related to #5103?

**Comment by adjustnox** [comment]
My team ran into this issue when our users were forced to Android 9 during the Feb Samsung Galaxy S9/9+ update. Many are reporting the player is simply blank. Could this be related?

**Comment by AquilesCanta** [comment]
> My team ran into this issue when our users were forced to Android 9 during the Feb Samsung Galaxy S9/9+ update. Many are reporting the player is simply blank. Could this be related?

Impossible to be sure with the available information, unfortunately. Could be.

**Comment by adjustnox** [comment]
> > My team ran into this issue when our users were forced to Android 9 during the Feb Samsung Galaxy S9/9+ update. Many are reporting the player is simply blank. Could this be related?
> 
> Impossible to be sure with the available information, unfortunately. Could be.

Here is some additional info, including client description:

Customers with the Samsung Galaxy S9/S9+ are reporting there was an update (information on update below) that has since caused video to not show up within the app, clients state that there is just a large white space where the video/image should be and do not have an option to play video.
 
Update details:
Android 9 Pie
Release date: 02/25/2019
Android Security Patch Level: February 1, 2019
Software Version: PPR1.180610.011.G960USQS3CSAG

**Comment by AquilesCanta** [comment]
Please file a fresh issue including all the information required in the template that will appear when you start. Don't skip any items, please.

**Comment by AquilesCanta** [comment]
I'll close this due to lack of activity from the original issue creator. @adjustnox posted #5634.
