### ISSUE TITLE
Forcing ExoPlayer to close previous TCP session after a channel switch

### ISSUE THREAD

**Issue by mvrazi** [google/ExoPlayer#5650]
### [REQUIRED] Searched documentation and issues
- https://github.com/google/ExoPlayer/issues

### [REQUIRED] Question
Tested using:
- ExoPlayer/2.9.6
- WowzaStreamingEngine/4.7.6

We're having a problem when switching between channels. 
After switching to another channel it is to expect from a player side that the last ACT to close the previous session is sent to the server streaming engine.

https://en.wikipedia.org/wiki/Transmission_Control_Protocol#/media/File:TCP_CLOSE.svg

Mentioned is not happening when using ExoPlayer and I need a confirmation if that can be somehow forced?

**Comment by tonihei** [comment]
ExoPlayer is definitely closing all connections when they are no longer used. Besides that, it sounds like a fragile setup if the server can't handle multiple open connections? 

If you have the feeling that ExoPlayer is not closing its connections, please provide more detailed reproduction steps and explanations how you came to that conclusion so that we can take a look. Closing the issue for now, but feel free to reopen if you have new information.

**Comment by indritj** [comment]
Hello I have the same issue using ExoPlayer /2.9.5/2.9.6. Player keeping two or more  connections between the EXOPlayer and streaming server. It does not close the previous session to streaming server for the previous stream.
This issue not happen using others players like NatvePlayer of STB etc.

**Comment by tonihei** [comment]
@indritj Please see my comment above. We need more detailed information to do anything about it. 
It would also be good to know what the issue with the open connections actually is. That is, what kind of problem does that cause?

Note that it may also be the system decides to leave the connection open for a while in case it needs to be reused.

**Comment by indritj** [comment]
This does not affect the player side but the server it increasing the number of connections on the Streaming server also increasing CPU of server. In this time the streams start to have disconnections and freezes
