### ISSUE TITLE
Exoplayer plays  the ads from a radio and then stops

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#5658]
Hi , 
this stream is working fine .
 **Radio Company Italyamo**
https://ice03.fluidstream.net/companyitalia.mp3
when you start it ,it plays the audio ads from the station and then stops
when you tap again it starts playing fine.
why the stream won't play after the ads.
Regards

**Comment by tonihei** [comment]
There seem to be two issues here:

First issue is a bug in our implementation. It seems our recently added support for ICY metadata ignores that streams do not always start at position zero. The difference between the first and second iteration is that the first time we start at position zero and everything sounds fine. The second time, we do a seek back to position 0 which gets resolved to a non-zero stream position based on the XING seek map we already know. That's why we play distorted audio as we try to read the ICY metadata from the wrong places and play back the actual metadata as audio data. We'll provide a fix for that.

Second issue is that the mp3 contains a XING seek map which indicates that the stream ends after the initial ad. We introduced a special check as a result of #4954 which ensures we don't read beyond the end of the XING seek map. That's why we stop playing in this case instead of continuing with the rest of the stream. It seems unusual to define a seek map for the first part only and then stop supporting seeking. Do you control the content? If so, it may be worth removing it, as I don't think this stream is intended to be seekable at all.

**Comment by tonihei** [comment]
We are going to fix the first issue by disabling seeks entirely if ICY metadata is present, because they just don't together very well.

**Comment by satyres** [comment]
Thanks so much for taking time to explain and fix the issue
Best regards

**Comment by tonihei** [comment]
Closing the issue because the questions has been answered.
