### ISSUE TITLE
Show background image when FF and Rewind

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#5682]
Hi,
I'm trying to find a way of showing a background HTTP image while the player is rewinding and fast-forwarding. I'm trying to use the `exo_simple_player_view.xml` and the `exo_artwork` ImageView. However this only appears at the start of playback. As soon as the player starts the `exo_artwork` is gone. Is there a way to make the `exo_artwork` appear again?

Or is there a way to show the last playback frame when FF or rewinding?

Many thanks.

**Comment by marcbaechinger** [comment]
If the video renderer is enabled the artwork is hidden as soon as the player starts rendering. When the user seeks the last rendered frame is left on the surface and will be replaced by the next frame which is rendered. In between the surface is kept visible, so the user sees the last frame rendered. 

The player view does not provide an API to hide/show the artwork. The behaviour follows an internal logic which appears to be useful and keeps the surface visible as far as it can be expected that the surface correctly shows the last frame rendered. 

You may want to try to hide/show the artwork yourself while listening to a Player.EventListener.

**Comment by rs146** [comment]
Thanks for the reply. I have found a way to create my own ImageView behind the player. 
However, I would like to do the following:
- When the FF/rewind occurs, grab current bitmap of the player at that moment.
- Add the bitmap to the background Image view.

I was thinking of something like this, but I get a black background still:

```
PlayerView playerView = findViewById(...);
ImageView playerBackground = findViewById(...);

if (surfaceView instanceof SurfaceView) {
    SurfaceView textureView = (SurfaceView) surfaceView;
    Bitmap currentFrame = getBitmap(textureView);
    playerBackground.setImageBitmap(currentFrame);
}
```
This is my `getBitmap()`:
```
 private Bitmap getBitmap(SurfaceView surfaceView) {
     surfaceView.setDrawingCacheEnabled(true);
     surfaceView.buildDrawingCache(true);
     final Bitmap bitmap = Bitmap.createBitmap(surfaceView.getDrawingCache());
     surfaceView.setDrawingCacheEnabled(false);
     surfaceView.destroyDrawingCache();
     return bitmap;
}
```
I wonder if there is something I'm missing.

**Comment by marcbaechinger** [comment]
I'm a little confused now. :) Isn't this what you would expect the player is doing? 

When seeking (ffwd/rewind) starts, the last frame rendered is still on the surface. As soon as seek ends, the player renders the first frame of the new playback position to the surface. So from what I understand that's what you are rebuilding with the approach of the background image. Are you seeing a different behaviour?

As for getting a bitmap from a surface, you can't use `getDrawingCache` because the surface draws outside of the normal view hierarchy. It's kind of a space for where hw accelerated drawing happens and it's not normal UI component.

Since API 24 you can use PixelCopy to grab a bitmap from a SurfaceView: https://developer.android.com/reference/android/view/PixelCopy . Alternatively you can use a TextureView for rendering the video which allows getting a bitmap with [TextureView.getBitmap](https://developer.android.com/reference/android/view/TextureView.html#getBitmap(int,%20int))
