### ISSUE TITLE
IMA force skippable

### ISSUE THREAD

**Issue by thuantran** [google/ExoPlayer#5689]
### [REQUIRED] Searched documentation and issues
Hi there,
I'm using exoplayer-ima in our application. I have searched exoplayer documents, issues and FAQs and IMA respective documents but I haven't found a way to force the skip button in IMA overlay to appear.

### [REQUIRED] Question
So my question is:
1. Is there a way to force the skip button to appear for ads tag that does not have this enabled?
2. Otherwise is there a way to check if the ads tag is skippable? We plan to add our own button in the case the ads tag does not have it.

Best regards,
Thuan

**Comment by thuantran** [comment]
Issue edited

**Comment by marcbaechinger** [comment]
Thanks for your question. 

I'm actually not sure whether I can give you an answer here. While I could do that from a technical point of view, I think I should not comment on this just because I'm not entirely sure whether this is something which violates IMA policies. 

For 1) I'm pretty sure that if an ad tag does not declare an ad to be skippable, then the ad must not be skipped by the user as per definition in the ad tag. I think what you should do is define the ad tag accordingly so that the ad is skippable. That would make your life much easier.

For 2) I think to know about policies that an app is not allowed to have a custom overlay on top of an ad. Your custom button you are mentioning would imo be some kind of such a custom overlay. 

I guess that's not the answer you wanted to hear. Sorry about that :( Can you convince me that this is something which is fine to do according to IMA policy?

**Comment by ojw28** [comment]
> For 1) I'm pretty sure that if an ad tag does not declare an ad to be skippable, then the ad must not be skipped by the user as per definition in the ad tag. I think what you should do is define the ad tag accordingly so that the ad is skippable. That would make your life much easier.

I agree with that interpretation. If the ad isn't skippable, it shouldn't be skipped. If you only want skippable ads then you need to make sure that your ad campaign only contains skippable ads.

**Comment by thuantran** [comment]
Hi Marc,

This is a request from our biz side, so I'm looking into the technical feasibility of it. But as you said, that explains why I couldn't find any document on it. Can you point me to the specific policy disallowing such practice, that would be helpful.

I will get back here after checking it with the team if it's legitimate usage.

Best regards,
Thuan

**Comment by ojw28** [comment]
> For 1) I'm pretty sure that if an ad tag does not declare an ad to be skippable, then the ad must not be skipped by the user as per definition in the ad tag. I think what you should do is define the ad tag accordingly so that the ad is skippable. That would make your life much easier.

I agree with that interpretation. If the ad isn't skippable, it shouldn't be skipped. If you only want skippable ads then you need to make sure that your ad campaign only contains skippable ads.

> Can you point me to the specific policy disallowing such practice, that would be helpful.

I don't think that's the right way of looking at it. Common sense would suggest that it's not OK to skip a non-skippable ad, so that should be the default understanding unless you can find a specific policy allowing such practice.

**Comment by thuantran** [comment]
That's what I told the biz side as well. But any public document would be better evidence to the issue at hand and appreciated. Can you point me to any?

**Comment by ojw28** [comment]
Nope, sorry. If your biz side wants only skippable ads, it seems fairly obvious they can and should make sure their ad campaign contains only skippable ads?

Why would it be OK to take an advertiser's ad that they haven't designed to be skippable, and unilaterally decide to make it skippable? It's pretty obviously not the right thing to do.

**Comment by thuantran** [comment]
The problem is they can't because we got ads tag from a partner, which might or might not send us skippable ads.

Our management find it user alienating to have long non-skippable ads. For now they haven't been able to work it out with our partner thus forcing the tech team to find a solution. 

As I said if there's a document for that it would be easier to tell the biz team to find alternative approach such as working directly with DFP or any SSP to set skippable ads.

I'm in a bind here as the tech guy you see, help on this is appreciated.

**Comment by ojw28** [comment]
Your management shouldn't be trying to unilaterally ignore the wishes of the ads being served via the partner. I'd suggest you point your management to this thread.
