### ISSUE TITLE
High Resolution video(2nd highest resolution ) is playing first when open and close and reopen video.

### ISSUE THREAD

**Issue by patelheggere** [google/ExoPlayer#5690]
High Resolution video(2nd highest resolution ) is playing first when open and close and reopen video. that too in 2G network. It is happening sometimes not every time. can you please brief how exoplayer2 will be selecting video resolutions and on what basis it will change and how frequently and if it is based on bandwidth how it will be calculating.?

**Comment by marcbaechinger** [comment]
The `DefaultBandwidthMeter` does listen to network transfers and roughly speaking calculates the bitmap estimate out of a sliding window of network traffic in the past. 

Obviously, this can't be done accurately if your app has just started and the BandwidthMeter does not have past network traffic out of which the bitrate estimate is calculated. As you are keen on the abr functionality I think you've already seen the changes in the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) in that area since v2.9.0. There have been quite a few changes in there so the following assumes that you are using the latest ExoPlayer version. 

Firstly, if no data is available for sensibly calculating an estimate, a statically set initial bandwidth estimate is used. This value is set by the `DefaultBandwidthMeter.Builder` based on country and the network type your app is running in. [Please have a look into the builder to get more detailed information of the values used](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.java#L98). You may configure your own initial bandwidth estimation by setting the appropriate field in the `DefaultBandwidthMeter.Builder`.

Secondly, in your app you should reuse a bandwidth meter across playbacks and not create a new one for each playback. This way the bandwidth meter can estimate based on the past playbacks and does not start from zero for each playback. The demo app does demonstrate this and I assume you have figured out this already. Easiest is having the bandwidth meter in a static field for reuse. If you are on a TV you may even store the estimate when your app is terminated, so when your app is restarted you can reinitialize the bandwidth meter accordingly.
