### ISSUE TITLE
Need help to setup pssh box for play Widevine DASH on Android 5.x

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#5691]
### [REQUIRED] Content description
The player crashes by playing Widevine DASH DRM content on Android 5.x. The same issue was already discussed  here. https://github.com/google/ExoPlayer/issues/4404. I understand the issue complete but I need help to setup the pssh box correct. Can you please help me with this issue?
### [REQUIRED] Link to test content
A link to the test content was send to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Android Devices running Android 5.X

**Comment by marcbaechinger** [comment]
From what I understand from the issue you referenced, reading the specs (I don't have experience with packaging myself) and the pssh box parsing code, I see that the error 

```
CdmEngine::ExtractWidevinePssh: PSSH flags not zero
```
is thrown because the flags of the full box header (bytes 9-12) is not zero.

[According to the spec](https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html#common-system) the first 12 bytes should be something like the following. The flags is in the third line:

0x00, 0x00, 0x00, 0x44,  // size=68
0x70, 0x73, 0x73, 0x68,  // 'pssh'
0x01, 0x00, 0x00, 0x00, // version, flags
...   // System ID

The example above is from the spec which can be found here:
https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html#common-system

Please let me know whether this helps you some further or whether I need to loop in some DRM folks to verify/clarify.

**Comment by ojw28** [comment]
Closing this because it's not an ExoPlayer issue. You should direct such questions to whoever provides you with the packager you're using to generate your content.
