### ISSUE TITLE
IMA Extension capture click on Ad

### ISSUE THREAD

**Issue by DasJhaman** [google/ExoPlayer#5699]
Before filing a question:
-----------------------
- This issue tracker is intended ExoPlayer specific questions. If you're asking
  a general Android development question, please do so on Stack Overflow.
- Search existing issues, including issues that are closed. It’s often the
  quickest way to get an answer!
- Consult our FAQs, developer guide and the class reference of ExoPlayer. These
  can be found at https://google.github.io/ExoPlayer/.

When filing a question:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Searched documentation and issues
Tell us where you’ve already looked for an answer to your question. It’s
important for us to know this so that we can improve our documentation.
NA

### [REQUIRED] Question
Describe your question in detail.
Hi to all, i am using IMA extension for Ads in Exoplayer, could you please let me know how can i fire a event when click on Ad. Your response on this matter highly appreciated.
Thanks in Advance

**Comment by marcbaechinger** [comment]
I think this could be difficult because as far as I know, the IMA library is using a webview to overlay the video. So these events may be consumed by the webview and not enter Android at all. 

I don't know exactly your use case, but I think you would find listening to `AdEvent`s useful, which are fired by the IMA library. I quickly checked and there is an [AdEventType.CLICKED](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdEvent.AdEventType) which might be what you need. This way you are using an official API and you are sure to not to accidentally confuse IMA when hooking into the UI dispatch flow. 

You can provide your listener to the builder when you build your `ImaAdsLoader`.

```
ImaAdsLoader imaAdsLoader = new ImaAdsLoader.Builder(context)
  .setAdEventListener(youAdEventListener)
  ...
  .buildForAdTag(adTagUri);
```
