### ISSUE TITLE
MediaDrmCallback for offline content (widevine) - official documentation request

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#5704]
Hello,
I noticed there is no official documentation or sample showing how to implement a MediaDrmCallback without HttpDataSource using a offlineLicenseKeySetId for a Widevine protected content.
Could you please share an example or give guidelines?
(Conditions: device not connected to internet, player uses CacheMediaSource)

This is not an issue, but just an information request. 
Our own implementation works perfectly so far with all the mentionned conditions. 
I just need this information from you to help me confirm a device specific issue case I am working on.

By the way I can even make it work with LocalMediaDrmCallback, but it is written in the documentation that this class is not suitable for Widevine content, do you have an explanation?

Thanks

**Comment by kushalgupta0565** [comment]
Hi,

there is no need to use `LocalMediaDrmCallback` in the case of Widevine, you can simply download the widevine license offline, and pass the downloaded license in `DefaultDrmSessionManager`

The code for downloading the license is 
```
public byte[] generateOfflineLicenseKeySet() {
        try {
            byte[] offlineLicenseKeySet = licenseComponent.getOfflineLicenseHelper().downloadLicense(getDrmInitData(licenseComponent.getDataSourceFactory()));
            saveOfflineLicenseKeySet(mpd_path, offlineLicenseKeySet);
            return offlineLicenseKeySet;
        } catch (DrmSession.DrmSessionException e) {
            e.printStackTrace();
        }
        return null;
    }
```

and setMode for `DefaultDrmSessionManager` _(i.e passing offline license to DRMSessionManager)_

`drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK,AppUtils.StringToByteArray(offlineLicenseKeyStr));`

**Comment by kvillnv** [comment]
Hi @kushalgupta0565, thanks for your insight.

My specific request was to obtain from the exoplayer team an official documentation about the MediaDrmCallback during PLAYBACK with offlineDrmLicense. 
We already have a downloader and a playback implementation working on many devices for almost 1 year.
We need an official documentation from exoplayer in order to help a manufacturer working on a device specific issue, I do not have more details on the issue, that is why I did not open an issue but a question to obtain an official documentation.  (I have renamed the title)

* Maybe my request was not precise enough, but I believe the required documentation is about how the MediaDrmCallback should be implemented without using an actual HttpMediaDrmCallback, as the device is totally offline, it should not use a HttpDataSource and the content is local (CacheDataSource).
* Or can exoplayer confirm that the HttpMediaDrmCallback is made to work 100% offline as long as we use a DefaultDrmSessionManager in MODE_PLAYBACK with an offlineLicenseKey. Or if the MediaDrmCallback should be customized, how should it be?

* And also I mentioned that there is something strange about LocalDrmCallback: it works when it should not: in the documentation it is written that it should not work with widevine, but it actually does work with offline Widevine license. I would like to know why? and why the documentation says that it should not?

@erdemguven, I believe you might have information about that. Your help would be appreciated!

Thanks

**Comment by ojw28** [comment]
For offline playbacks where you're providing an `offlineLicenseKeySetId` via `DefaultDrmSessionManager.setMode`, the `MediaDrmCallback` you're using should never be called. This is because the manager doesn't need to perform any key requests;it can load the keys directly with the `offlineLicenseKeySetId` you've provided.

So you can provide any implementation of `MediaDrmCallback`. It should never be called. If the `MediaDrmCallback` _is_ being called on the problematic device, that's probably related to whatever the device specific issue is that you're trying to track down. If you try on a correctly functioning device then you should not see this happening.

**Comment by ojw28** [comment]
Note that if the `MediaDrmCallback` _is_ being called on the problematic device, that's probably related to whatever the device specific issue you're trying to track down is. If you try on a correctly functioning device then you should not see this happening.

**Comment by kvillnv** [comment]
Ok, so you think it is a device specific issue, and even if I remove or try to implement another MediaDrmCallback it will not change anything.
It would be interesting to add this information in the DefaultDrmManager class and make a new constructor without MediaDrmCallback

This is correct for offline playback? It actually does work, but with your approval I will be able to strengthen my case with the manufacturer.

```
DefaultDrmSessionManager.newWidevineInstance(/*callback*/ null, /*optionalKeyRequestParameters*/ null)
                .apply { setMode(DefaultDrmSessionManager.MODE_PLAYBACK, offlineLicenseKeySetId) }
```

And to your knowledge, is there anything new in Android P that could be the cause?

Thanks @ojw28 .

**Comment by ojw28** [comment]
> Ok, so you think it is a device specific issue, and even if I remove or try to implement another MediaDrmCallback it will not change anything.

I don't know because you haven't provided a description of the issue. I see you filed https://github.com/google/ExoPlayer/issues/5730 though, which I'm guessing is the issue you have. That looks like a problem with the underlying DRM implementation, and is assigned to the right person to take a closer look.

> It would be interesting to add this information in the DefaultDrmManager class and make a new constructor without MediaDrmCallback

Actually, the `MediaDrmCallback` may be called if the offline keys have expired (whether they can expire depends on the license configuration). It also doesn't make sense to have a constructor without the callback given the mode can be changed dynamically via `setMode`.

Closing this as answered. It seems #5730 probably tracks your actual issue.
