### ISSUE TITLE
No metadata when playing m4a files

### ISSUE THREAD

**Issue by opaquewarellc** [google/ExoPlayer#5728]
Question:
I have searched the current issue here, and found nothing about m4a metadata.

I was able play mp3 files and see the embedded bitmap on the PlayerView. But when playing m4a files, only sound are being play. I know the m4a file do have valid metadata. 
I am using DefaultDataSourceFactory and DefaultRenderersFactory. Not sure if I am not doing it right or there are issue with extracting metadata from m4a files.

Exoplayer version 2.9.6 lib

**Comment by andrewlewis** [comment]
It looks like we support getting cover art stored in a `covr` metadata element in M4A. Can you describe exactly how the cover art is stored in the files you're trying to play? Or share the media here or via email to `dev.exoplayer@gmail.com` with subject "Issue #5728"?

Note: it's possible that this is fixed in the development branch where we now parse `meta` elements outside `udta`.

**Comment by opaquewarellc** [comment]
I was able to play the same m4a file in Google Play music app with the cover art shown.
But I have other m4a files that do works with the current Exoplayer lib. So I have decided it is not worth the time to find the root cause of this issue at the moment. Perhaps I'll re-visit this later. 
Thanks,
