### ISSUE TITLE
HLS: Make it easy to assume no captions if playlist omits CLOSED-CAPTIONS attribute

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#5736]
Hi
Can you please let me know how we can avoid exoplayer inserting empty cea-608 tracks if source content doesnt contain the CC tracks?

**Comment by ojw28** [comment]
Is this specifically related to HLS? If so, an HLS master playlist can explicitly indicate that variants don't contain CC tracks by marking `EXT-X-STREAM-INF` tags with the `CLOSED-CAPTIONS=NONE` attribute. For content that does this, we do not insert CEA608 tracks. For content that omits the attribute and makes inclusion of CC tracks ambiguous, we assume they may be present and so generate a track.

The correct way of avoiding this is to have the master playlist explicitly indicate what the content contains.

**Comment by himaswetha** [comment]
Instead of mentioning CLOSED-CAPTIONS=NONE in master playlist any other way is there to avoid inserting cea608 empty tracks?

I need to handle both for HLS and DASH. Some flag is there? FLAG_OVERRIDE_CAPTION_DESCRIPTORS?
How to use this flag for DASH?
How to use this flag for HLS?

**Comment by ojw28** [comment]
For DASH we don't ever generate a CEA608 track unless the content explicitly indicates that one is present, so I don't think your question is relevant to the DASH case.

For HLS, we generate a CEA608 track if the content doesn't explicitly indicate either way whether one is present. The default is different for HLS because lots of legacy HLS content didn't include the CLOSED-CAPTIONS tag despite containing captions. It's not very easy, but it is possible to turn this off and have the same behavior as for DASH by building your `HlsMediaSource` like this:

```
HlsExtractorFactory hlsExtractorFactory = new HlsExtractorFactory() {
  DefaultHlsExtractorFactory delegate = new DefaultHlsExtractorFactory();
  @Override
  public Result createExtractor(
      Extractor previousExtractor,
      Uri uri,
      Format format,
      List<Format> muxedCaptionFormats,
      DrmInitData drmInitData,
      TimestampAdjuster timestampAdjuster,
      Map<String, List<String>> responseHeaders,
      ExtractorInput sniffingExtractorInput)
      throws InterruptedException, IOException {
    if (muxedCaptionFormats == null) {
      // If playlist doesn't tell us anything about captions, behave as though
      // it explicitly told us there were none.
      muxedCaptionFormats = Collections.emptyList();
    }
    return delegate.createExtractor(
        previousExtractor,
        uri,
        format,
        muxedCaptionFormats,
        drmInitData,
        timestampAdjuster,
        responseHeaders,
        sniffingExtractorInput);
  }
};
return new HlsMediaSource.Factory(dataSourceFactory)
    .setStreamKeys(offlineStreamKeys)
    .setExtractorFactory(hlsExtractorFactory)
    .createMediaSource(uri);
```

@AquilesCanta - I wonder whether we should make it easier to configure HLS to behave the same as DASH (e.g. via `HlsMediaSource.Factory`, or at least `DefaultHlsExtractorFactory`)? Marking as an enhancement, but if you disagree (or if there's already an easier way to do this) feel free to change :).

**Comment by himaswetha** [comment]
FLAG_ENABLE_CEA608_TRACK - is this flag removed in FragmentedMp4Extractor.java file? is this flag responsible for inserting empty CC tracks in Dash content?

**Comment by himaswetha** [comment]
FLAG_ENABLE_CEA608_TRACK - is this flag removed in FragmentedMp4Extractor.java file in newer version of code? is this flag responsible for inserting empty CC tracks in Dash content?



I can see some of the code for dash in FragmentedMp4Extractor.java file in latest version of code. Is this related to inserting empty cc tracks for dash content?
    if (cea608TrackOutputs == null) {
      cea608TrackOutputs = new TrackOutput[closedCaptionFormats.size()];
      for (int i = 0; i < cea608TrackOutputs.length; i++) {
        TrackOutput output = extractorOutput.track(trackBundles.size() + 1 + i, C.TRACK_TYPE_TEXT);
        output.format(closedCaptionFormats.get(i));
        cea608TrackOutputs[i] = output;
      }

**Comment by ojw28** [comment]
As I already said above, we don't ever generate empty CC tracks in DASH content. If you're seeing this on any version of ExoPlayer, please file a DASH specific issue providing sample content for which you see this. I'm going to mark the last two posts as off topic, since we're using this issue to track the topic for HLS now.

**Comment by AquilesCanta** [comment]
A flag to disable the preemptive 608 track will be exposed in the next release (2.10), and a commit ref will appear below once it's available in the dev-branch. In the meantime, you can just use the approach described above by @ojw28.
