### ISSUE TITLE
Concatenated Media source playing issues on certain Android Box - MXQ Pro

### ISSUE THREAD

**Issue by monsterbrain** [google/ExoPlayer#5741]
### [REQUIRED] Content description
Android App employing exoplayer 2, to play sequence of ogg files in the assets folder.
(for eg. Token_num.ogg + num_1.ogg + num_2.ogg+ num_3.ogg). I'm using the ExtractorMediaSource
array map to keep track of the token numbers. On playing a certain sequence, I'm adding
the media sources to an array and initialize with ConcatenatingMediaSource. Two issues occur
on a particular device MXQ pro TV Box with Android 7.1.1 (No issues in the Android 6 version).

1. On playing first few hundred milliseconds of the first file get's cut off. Also there's 
a delay in preparing and playing the media for the first time.

2. On playing the second media file, there's a audible scratch / noise just before playing 
that file.

There was already some issues with using SoundPool in that device.

No issues in playing observed on Galaxy Tab Pro (Android 4.4.2).

### [REQUIRED] Link to test content
Sample media files can be found here : [Sample Assets Folder](https://drive.google.com/drive/folders/1PZC83HdRSSc5qmuq8aeJkrVjhh7kuCX0?usp=sharing)

### [REQUIRED] Version of ExoPlayer being used
Exoplayer version : 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
MXQ Pro Android TV Box - Android version 7.1.1

**Comment by tonihei** [comment]
Based on the information you provided, it sounds as if this TV Box has a platform codec problem especially because the same issues occur with SoundPool. There is not much we can do about that and if you have a large user base on these devices it may be best to reach out to the manufacturer to check if they plan to provide system updates.

Alternatively, please consider using our [FFMPEG extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) which bundles the FFMPEG software decoder to play some audio formats (including ogg). This will likely increase your APK size but provides a more reliable performance across devices.

**Comment by monsterbrain** [comment]
Thanks for your kind reply. And thanks for pointing to the extension, I'll try to integrate that and test with it and will hopefully, post results here, if I can make it work properly. Thanks again.

**Comment by tonihei** [comment]
Closing as the issue was probably solved.

**Comment by monsterbrain** [comment]
As mentioned be @tonihei I tried the same with the mp3 files and it works OK (but still a few starting delay was there, which was solved by adding silent 200ms to the audios). Maybe the ogg decoder wasn't working with the android TV Box.
