### ISSUE TITLE
MEDIA_TIMESTAMP regex in WebvttParser is not accurate

### ISSUE THREAD

**Issue by ferrytanu** [google/ExoPlayer#575]
Current:
MEDIA_TIMESTAMP = Pattern.compile("MPEGTS:\\d+");

Should be:
MEDIA_TIMESTAMP = Pattern.compile("MPEGTS=\\d+");

Based on the sample in the specification (http://tools.ietf.org/html/draft-pantos-http-live-streaming-09#section-4):
X-TIMESTAMP-MAP:LOCAL=00:00:00.000,MPEGTS=900000

**Comment by ojw28** [comment]
The RFC was incorrect in revision 9 (which was the first revision to include a description of the X-TIMESTAMP-MAP header). It was corrected in revision 10, and the latest revision is [16](https://tools.ietf.org/html/draft-pantos-http-live-streaming-16).

**Comment by ferrytanu** [comment]
Thanks @ojw28 , due to the error on RFC, shall we make it "backward" compatible?

MEDIA_TIMESTAMP = Pattern.compile("MPEGTS[:=]\\d+");

**Comment by ojw28** [comment]
I don't see any reason to do so at this stage. Revision 9 was the newest revision for less than a month. Revision 10 could have defined the pattern to be backward compatible, but didn't (if backward compatibility was to be expected, it should have been defined as such in the newer revisions of the RFC).

If it turns out there are lots of files in the wild that happen to use the alternate pattern than of course we can do this, but until there's evidence it doesn't seem worth doing.

**Comment by ferrytanu** [comment]
I couldn't provide the evidence, however both formats work on iOS platform.
