### ISSUE TITLE
Using player in RecyclerView triggers java.lang.IllegalStateException: sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by andreififiita** [google/ExoPlayer#5751]
### [REQUIRED] Searched documentation and issues
I have found this that is related: https://github.com/google/ExoPlayer/issues/590 saying that the player was already released at the time play was called.
The problem is that I do not think my player was released, as I reconstruct it each time the adapter updates / binds the view

### [REQUIRED] Question
I am using a SimpleExoPlayer in a RecyclerView and sometimes there is an error when calling                     

`simplePlayer.setPlayWhenReady(true);`

The video player remains blank and the moments when the issue appears are not always the same (I did not find an exact way to simulate this)

Exception: 

```
java.lang.IllegalStateException: Handler (android.os.Handler) {edbfbdd} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
            at android.os.Handler.enqueueMessage(Handler.java:662)
            at android.os.Handler.sendMessageAtTime(Handler.java:631)
            at android.os.Handler.sendMessageDelayed(Handler.java:601)
            at android.os.Handler.sendMessage(Handler.java:538)
            at android.os.Message.sendToTarget(Message.java:418)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:183)
            at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:245)
            at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1188)
            at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:896)
```

My code runs inside a custom view (updated in recycler view adapter):

    MyView h = this;
    h.playerView = new PlayerView(getContext());
    h.playerView.setVisibility(View.GONE);
    h.postFrameLayout.addView(h.playerView, 0);
    h.postFrameLayout.getLayoutParams().width = swidth;
    h.postFrameLayout.getLayoutParams().height = (int) (swidth ); 
    h.playerView.getLayoutParams().width = swidth;
    h.playerView.getLayoutParams().height = (int) (swidth  ); 

    if (player != null){
                player.release();
    }

    DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
                    .setBufferDurationsMs(1100, 2000, 1000, 1000).createDefaultLoadControl();
    final SimpleExoPlayer simplePlayer = ExoPlayerFactory.newSimpleInstance(getContext(), trackSelector, loadControl);
    h.playerView.setUseController(false);

    h.playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIXED_WIDTH);
    h.playerView.setPlayer(simplePlayer);

    simplePlayer.addListener(new Player.EventListener() {
                @Override
                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                    if (playbackState == Player.STATE_ENDED) {
                        h.videoPlay.setVisibility(View.VISIBLE);
                        h.postImage.setVisibility(View.VISIBLE);
                        simplePlayer.setPlayWhenReady(false);
                        simplePlayer.seekTo(0);
                    }
                }
            });
    Uri uri = Uri.parse(videoUrl);
    final MediaSource audioSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(uri);
    simplePlayer.prepare(audioSource);

    h.player = simplePlayer;

    h.videoPlay.setVisibility(View.VISIBLE);
    h.videoPlay.setOnClickListener(new View.OnClickListener() {

                @Override
                public void onClick(View v) {
                    displayArticles(false, post.getPhotoItems(), h);

                    h.videoPlay.setVisibility(View.GONE);
                    h.postImage.setVisibility(View.GONE);
                    h.playerView.setVisibility(View.VISIBLE);
                    simplePlayer.setPlayWhenReady(true);

                }
            }); 

I release the player on detaching from the window (when recycler view calls onDetachedFromWindow() on my custom view):

  
 ```
 if (player != null) {
            videoPlay.setVisibility(View.VISIBLE);
            postImage.setVisibility(View.VISIBLE);
            player.release();
            player = null;
    }
```

Is there a way to avoid this issue by checking if the player was released or make retries when the player is started?

Version of ExoPlayer being used: 2.9.3
Android 8.1 - Samsung Galaxy J7

**Comment by marcbaechinger** [comment]
It's hard to say what happens here, because I'm not quite sure where the code above lives and when/how it is executed. 

In general I think that the approach of creating, preparing and releasing the player inside a custom view is an approach which is difficult to master. You don't actually know when the view is going to be created by the system, how many instances of that view the `RecyclerView` creates and reuses. I think you will pretty soon run into problems because the recyclerview has created multiple of your custom views and hence you have created and prepared multiple ExoPlayer instances.

I'd recommend that you have only one player instance, which you create at the begin when the activity is started. You can still have your custom view which contains a `PlayerView`. The tricky part with the recycler view is knowing which of the PlayerViews, which are currently attached to the window, should have the player set and prepared. Given that there can be more than one of your custom views attached to the window, you need to evaluate which of these views are currently visible and then prepare the player and attach the player to the visible `PlayerView`. You need to be aware that it is even possible to have multiple of your custom views visible at the same moment in time. In this case you probably need to use a [RecyclerView.OnScrolllListener](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.OnScrollListener) to evaluate which `PlayerView` should own the player.

**Comment by ojw28** [comment]
In addition to Marc's answer above:

> The problem is that I do not think my player was released

The stack trace you've provided means `setPlayWhenReady` was called on a released player. I think we're pretty certain of that.

> Is there a way to avoid this issue by checking if the player was released

You both instantiate and release players in your application code, so it should be possible for you to track this without any support from the library.

It's also unclear what the actual issue is here, since "sending message to a Handler on a dead thread" errors are normally harmless. The stack gets printed to logcat, but such errors do not result in your process crashing. It simply means that the command isn't processed by the player, which makes sense in the case that it's already been released.

Closing as answered, but if there's more to discuss feel free to respond here! Thanks.
