### ISSUE TITLE
Multiperiod live DASH seeking issue

### ISSUE THREAD

**Issue by altrg** [google/ExoPlayer#5755]
### [REQUIRED] Content description
Seeking does not work properly for multiperiod dynamic DASH stream. The seek bar shows incorrect timeline and updates to wrong position.

### [REQUIRED] Link to test content
Sent by email

### [REQUIRED] Version of ExoPlayer being used
demo player 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Huawei FIG-LX1 Android 8.0.0

**Comment by ojw28** [comment]
The first manifest provides a live window of around 1 hour. It also includes a `<Location>` element, which tells the player where to load the manifest from the next time it does a refresh. When we do this, we get a manifest back that only contains a tiny live window. Hence the player reduces the live window down to around 10 seconds on the first manifest refresh. I think this is working as intended, because that's what the content is telling us to do. The source content should either not contain `<Location>` elements, or they should point at manifests that have the duration of live window that you want.

Notes:
* You can easily see this behaviour by downloading a manifest manually (e.g. in a browser), looking at the `<Location>` element, and then downloading that and looking at what it contains.
* If you observe that some other players handle this stream "correctly", it's most likely because they do not parse the `<Location>` element at all. If I manually disable parsing the `<Location>` element in ExoPlayer then it also works as you'd expect.
