### ISSUE TITLE
How to detect a media already is downloaded?

### ISSUE THREAD

**Issue by makazemi** [google/ExoPlayer#5770]
I am using DownloadTracker and DemoDownloadService class of demo app for downloading feature in my app. I want to detect if a media already is downloaded, prevent downloading again it.In the demo app exist a isDownloaded method but when a file already is exist, didn't detect and again download the media. how to implement it ?

**Comment by ojw28** [comment]
You should probably wait until `2.10`, which is fairly close to release now (approx 1 or 2 weeks) and improves download functionality significantly. This includes having the library keep track of downloads, so application code doesn't have to.

You can have a play around with the `dev-v2` branch if you want to see what the current state is.

**Comment by makazemi** [comment]
I put my code in Github. https://github.com/makazemi/basicExoPlayer

**Comment by bychkovdmitry** [comment]
Can we expect 2.10 release this week? Really looking forward to this release. Thanks.

**Comment by makazemi** [comment]
@ojw28 : Before 2.10 version, I asked this question #5640. Now I use of new version of exoplayer. The onDownloadChanged of DownloadManger listener only be called three or four times. In the first two times, PercentDownloaded is zero and only in the one before the last and last time PercentDownloaded  has non zero value. So My progress bar don't update. I try for large file but no difference. I want put this comment on #5640 question but this was closed.

**Comment by makazemi** [comment]
@ojw28 : If user manually delete .exo downloaded file, isDownloaded method of 2.10 version can't detect it. How to detect it?

**Comment by ojw28** [comment]
> Now I use of new version of exoplayer. The onDownloadChanged of DownloadManger listener only be called three or four times. In the first two times, PercentDownloaded is zero and only in the one before the last and last time PercentDownloaded has non zero value. So My progress bar don't update. I try for large file but no difference. I want put this comment on #5640 question but this was closed.

Progress updates do not trigger `onDownloadChanged` because progress is changing continuously. Instead, you should poll the progress at whatever rate you want. `DownloadService` contains an example of doing this, which is how the notifications update with progress in the ExoPlayer demo app, so please take a look at that if it's unclear what to do.

Note this is analogous to playback position advancing during a playback. We don't continually fire events for that either, but instead application code can poll the current position at whatever rate it wants.

> If user manually delete .exo downloaded file, isDownloaded method of 2.10 version can't detect it. How to detect it?

We think it's very unlikely that users will do this in practice, and so do not think that it's important to handle this case.
