### ISSUE TITLE
Is it necessary to re-download a DASH stream if/when part of the cache was deleted by the LRU Cache Evictor?

### ISSUE THREAD

**Issue by Gensoukyou1337** [google/ExoPlayer#5823]
### [REQUIRED] Searched documentation and issues
Medium post about Downloading Streams and Downloading Adaptive Streams, and the Exoplayer demo source code

### [REQUIRED] Question
I've figured out how to download the stream, and my cache's using the `LRUCacheEvictor` with a maximum size of 20 MB. However, I'm facing the issue that when the user downloads one stream while the cache is near-full, parts of the first/previous downloaded stream(s) would be deleted, forcing the `CacheDataSource` to get the data from the upstream/server, meaning some bandwidth usage, and my goal is to zero-out the bandwidth usage (from fetching the DASH segments) after downloading the video the first time.

One solution I can think of for this is to re-download the stream, meaning removing the stream's cached parts and downloading the entire thing again. But then again that would run counter to my objective. Should I do that, or is that a bad practice and I should just use the `NoOpCacheEvictor`?

Related question: What would be the best practices when it comes to caching content/streams?

**Comment by tonihei** [comment]
When you are using an `LRUCacheEvictor`, it deletes the "least recently used" streams from the cache as the name already suggests. That means you need to download them again if you want to play them offline.

Our recommendation for downloading is to use a `NoOpCacheEvictor` so that downloaded streams are never deleted. The main usage of the `LRUCacheEvictor` is caching during online playback where the cache is used while seeking through the media and replaying content while the app is still active.

**Comment by Gensoukyou1337** [comment]
Would a Youtube-like solution (re-downloading every 30 days or so) work better for this case?

Or, is there any way to detect when the cache of a downloaded stream is partly deleted/incomplete? This is in case I have to go for the re-downloading approach.

**Comment by tonihei** [comment]
The retention policy of when to delete or re-download depends on what your app is trying to do and ExoPlayer imposes no restrictions/recommendations on that.

Up until 2.9.6 there is the `CacheUtil.getCached` method to query the state for a particular piece of content. However, it's relatively difficult to use because you need the set-up the `dataSpec` for example, which requires knowledge of the DASH manifest.

From 2.10.0, we added better support for downloading, especially tracking the state of each download. There will be a page on our developer guide explaining how to use it (once 2.10.0 is released which should happen next week at the latest).

**Comment by Gensoukyou1337** [comment]
So in 2.10.0, I'll have the ability to track whether the cache has all the pieces of a particular downloaded stream?

**Comment by Gensoukyou1337** [comment]
For now I've developed the following workaround:

```
fun verifyCache(dashManifestURL: Uri) : Boolean {
        val commonKey = dashManifestURL.lastPathSegment!!.substringBefore(".mpd")
        val sourceKeys = downloadCache.keys
        val keys = mutableListOf<String>()
        sourceKeys.apply {
            for(x in this) {
                if(commonKey in x && !x.endsWith(".mpd")) {
                    keys.add(x)
                }
            }
        }

        var shouldRedownload : Boolean = keys.isEmpty()

        for (key in keys) {
            val spans = downloadCache.getCachedSpans(key)
            var totalLength : Long = 0
            for(span in spans) {
                totalLength += span.length
            }

            if(!shouldRedownload && (totalLength != downloadCache.getContentLength(key))) {
                shouldRedownload = true
            }
        }

        return shouldRedownload
    }
```

This basically checks for all the keys/track URLs in the cache containing the last segment in the DASH manifest (assuming all of the track URLs contain said segment like mine does), gets all their spans, sums all of their lengths, then compares said sum with the registered length in the cache. It returns False if they match, and True if they don't, signifying the need to redownload.

**Comment by tonihei** [comment]
That could work, but may depend on your manifest set-up. We can't debug your app code to verify that and we now also have an official way to check the state of a download in 2.10. Please see the documentation [here](https://exoplayer.dev/downloading-media.html) for details.
