### ISSUE TITLE
Removing and re-adding PlayerView/SurfaceView squashes video and displays the bottom line mulitple times

### ISSUE THREAD

**Issue by splrs** [google/ExoPlayer#5825]
### [REQUIRED] Issue description
Removing the player's PlayerView from its parent, and then adding it again - for example as part of onConfigurationChanged() - will cause the video to be slightly vertically squashed. The bottom line of the video is then repeated to fill the remainder of the SurfaceView.

![Screenshot_20190502-171410 1](https://user-images.githubusercontent.com/7551963/57133327-55991e00-6d9a-11e9-84e3-e5890e2748ab.png)

### [REQUIRED] Reproduction steps
Add the following to PlayerActivity in the demo app:

```java
@Override
public void onConfigurationChanged(Configuration newConfiguration) {
  super.onConfigurationChanged(newConfiguration);
  if (playerView.getParent() != null) {
    ViewGroup parent = (ViewGroup) playerView.getParent();
    parent.removeView(playerView);
  }
  FrameLayout rootView = findViewById(R.id.root);
  rootView.addView(playerView);
}
```

1. Play either of the streams below
1. Rotate the device
1. Observe the issue
    - Note: Of course, the lower the res, the more visible the issue

### [REQUIRED] Link to test content
* Widevine DASH: MP4,H264 -> WV: Clear SD (MP4,H264)
    - Restrict res to 320 x 142
    - 6:15-6:20 show it fairly clearly
* HLS -> Apple 16x9 basic stream

### [REQUIRED] A full bug report captured from the device
Emailed to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.9.3

### [REQUIRED] Device(s) and version(s) of Android being used
- Samsung Galaxy S6 (SM-G920F)
- Android 6.0.1

**Comment by tonihei** [comment]
I'm able to reproduce the problem on a Galaxy S6 and also on all other devices which run Android Marshmallow. It seems to be related to using a internal DummySurface which is used while the actual surface is not available during the short period in which the view has no parent. When I disable the DummySurface usage, the problem disappears but playback needs to wait until the next keyframe after re-adding, because a new decoder is created internally.

Given that it seems to affect all Marshmallow devices, but is so far only known to happen in this slightly unusual pattern, I see the following options: 
1. Ignore the problem because the pattern causing the problem seems to be unusual and this is the first complaint about this although we've been using the DummySurface for quite a while now.
2. Disable DummySurface usage on API 23. This will make surface transitions on these devices slower and worse, but prevents all platform problems related to setting a DummySurface (like this one).

Just for clarification: Do you use this exact pattern in your app? And if so, what are you trying to achieve with it? It would be good to know whether this is a common problem occurring in practice.

**Comment by ojw28** [comment]
@splrs - Please could you respond to the clarification questions asked above? Thanks!
