### ISSUE TITLE
When will decoderCounters. droppedBufferCount increase?

### ISSUE THREAD

**Issue by linshuxian2019** [google/ExoPlayer#5830]
### [REQUIRED] Searched documentation and issues
When will decoderCounters. droppedBufferCount increase?

### [REQUIRED] Question
I want to verify the ability of hardware decoding. I wonder if decoderCounters.droppedBufferCount's increase is due to decoding failure. More precisely, I wonder where the number of output buffers that fail to decode will go.

**Comment by ojw28** [comment]
The definition of a dropped buffer is pretty clearly defined in [Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/decoder/DecoderCounters.html#droppedBufferCount):

> The number of dropped buffers.
> 
> A dropped buffer is an buffer that was supposed to be decoded/rendered, but was instead dropped because it could not be rendered in time.

We would normally expect all frames to be decoded successfully, so I'm not sure what you're trying to count exactly. If a decode failure occurs then most likely the decoder will throw an exception and playback will fail.

**Comment by linshuxian2019** [comment]
I want to know if the page has many windows to play local video, and the new window shows black screen, is it because the decoder can not solve it?
I printed the log and found that the data of the newly added window remained unchanged on the black screen. DecoderCounters.inputBufferCount=4, and outputBufferCount=0

**Comment by ojw28** [comment]
I don't think decoder counters are relevant here. If you try and use too many players at once then one or more of them may fail at the start of playback because the underlying system doesn't have sufficient resources to allocate the decoders it needs. However in this case you will get a player error reported. See [this guide page](https://exoplayer.dev/listening-to-player-events.html) for details on listening to player errors. So you should take a look for those instead.

**Comment by linshuxian2019** [comment]
Thank you! That is enough.
