### ISSUE TITLE
After a long pause and resume, the player catches the error after +/- 1 minute of streaming.

### ISSUE THREAD

**Issue by patrykcyrzan** [google/ExoPlayer#5844]
### Content description
After a long pause and resume, the player catches the error after +/- 1 minute of streaming. Error is BehindLiveWindowException (and the player skips to live streaming), but it's not always the case (sometimes I don't see any errors). The stream works properly in Google Shakaplayer.

### Link to test content
I've sent the link to test content on the provided mail address.

### Reproduction steps
Pause the stream and wait for a moment (2 minute is enough). Then resume the stream and wait +/- 1 minute

### Version of ExoPlayer being used
2.9.4, 2.9.6

### Device(s) and version(s) of Android being used
I've reproduced it on Google Pixel (Android 9), Huawei P9 (Android 7.0)

**Comment by tonihei** [comment]
ExoPlayer buffers 50 seconds ahead by default. So when you pause playback and wait for a while, you still have these 50 seconds of media to play when you resume. However, if the live window is very short, there is no way we can load new media after that because there will be a gap between the end of the already buffered media and the start of the live window. 

If that's a common use case you want to support, you should consider increasing the size of the live window if you control the content creation. Otherwise you can also try to increase the buffer size, but there are obviously limits to how much data can be buffered in memory.

**Comment by patrykcyrzan** [comment]
@tonihei I'll describe problem in diffrent way. Our stream (provided in mail) starts playing from the timestamp which is <1 hour from the live moment. It looks correct and it starts playing from this timestamp, and seeking is also available but after few second the stream goes to the live moment.
As I mentioned earlier, ShakaPlayer can handle it.

**Comment by tonihei** [comment]
This effect is caused by the Location element in the manifest which redirects to another manifest. This other manifest doesn't have the long available live window, but only 12 seconds of live window. 

The original problem you described above is then caused by what I already explained: Playback falls back behind the 12 second live window and if it's paused for a long time, playback can only continue in the already buffered part and then needs to jump back to the live window.

**Comment by ojw28** [comment]
Note: This is the same as https://github.com/google/ExoPlayer/issues/5755. Shaka handling the stream "properly" most likely just means they haven't implemented support for Location elements yet. If/when they were to implement support, you'd likely see the same behavior when using Shaka as well.
