### ISSUE TITLE
Video freezes during playback

### ISSUE THREAD

**Issue by malwinder-s** [google/ExoPlayer#5858]
### Content description
Hello,

I am trying to build application with video player in it. I want to display `PlayerView` on Fragments present in `ViewPager`.

I am using following code:

Layout:

    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="zoom"
        app:shutter_background_color="@android:color/transparent"
        app:surface_type="texture_view"
        app:use_controller="false" />

Kotlin code (Inside Fragment):

    private fun initializePlayer(uri: Uri) {
        val mPlayer = ExoPlayerFactory.newSimpleInstance(requireContext())
        mPlayer.repeatMode = REPEAT_MODE_ALL
        val mediaSource = buildMediaSource(uri)
        mPlayer.prepare(mediaSource, true, false)
        videoView.player = mPlayer
    }

    private fun buildMediaSource(uri: Uri): MediaSource {
        return ProgressiveMediaSource
            .Factory(
                    DefaultHttpDataSourceFactory("user-agent")
            )
            .createMediaSource(uri)
    }

I am using `app:surface_type="texture_view"` because I don't want to show default black screen when player is loading video.

I am running another instance of `SimpleExoPlayer` in a Service simultaneously. It is used for audio purpose only.

I am getting following result:
When video is played (when device is on Mobile Data) it freezes for 15-30 seconds before resuming playback.

I read #4559  and have even added following:

        var factory = DefaultExtractorsFactory()
        factory = factory.setMp4ExtractorFlags(FLAG_WORKAROUND_IGNORE_EDIT_LISTS)

But still I am getting same issue.
### Link to test content
URL: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

### Version of ExoPlayer being used
2.10.0

### Device(s) and version(s) of Android being used
OnePlus 6 running Android 9.0.5

Thank you.

**Comment by malwinder-s** [comment]
I have provided all required details and have updated the comment.

**Comment by malwinder-s** [comment]
I have provided all required details and have updated the comment.

**Comment by marcbaechinger** [comment]
I understand the issue is that it takes about 15 seconds to start playback when you are playing the video with the device on a mobile data network, while another player is playing audio in a service.

Can you please try to reproduce the behaviour by ruling out some variables like connectivity or bandwidth issues:

- does this happen when you are playing the video from local disk or when on a wifi network?
- does this happen when the player in the service is not playing?

**Comment by parulgarg004** [comment]
@marcbaechinger when we want to replay the same video in a loop it again takes the same time to load.

**Comment by marcbaechinger** [comment]
When the video starts again, it needs to load the data again unless you have caching enabled (see below).

As per my comment above: Does it take 15 seconds when the video is loaded from disk (in the assets folder) or when loaded from WIFI?

If it's only because the video needs to load over a slow mobile network you may want to wrap a [CacheDataSource](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java) around your data source to cache the video. Then it is loaded only once and when played for a second time, the data is read from the cache.

**Comment by parulgarg004** [comment]
It takes time to load when loaded from WIFI or Data Connection. Videos are coming from a web URL. I have to play a video in an infinite loop.

**Comment by marcbaechinger** [comment]
Can you please provide me with the url to the content? If you do not want to post this in public you can send it to dev.exoplayer@gmail.com with the subject "Issue #5858" so we can check.

**Comment by parulgarg004** [comment]
@marcbaechinger check below URL
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by parulgarg004** [comment]
I will try to implement cache policy

**Comment by parulgarg004** [comment]
@marcbaechinger can you please help us in this issue.

**Comment by marcbaechinger** [comment]
When playing that uri on a WIFI network, with the demo app without caching it starts kind of immediately:

```
com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [1.24, 0.00, window=0, period=0, Surface(name=null)/@0x7e887de]
```

The first frame is rendered after 1.24 seconds after the player has been created. This seems reasonable to me for the stream provided. When the video is at the end and repeats this happens without rebuffering which meets my expectation as well.

If you are seeing a join latency of 15-30 seconds I think this is really a bandwidth or another problem.

I think my advice on caching won't actually help, sorry for this. The player is supposed to pre-buffer nicely when repeat mode is on. Caching certainly will help in reducing the amount of data downloaded, which might be something your user benefit from when on a mobile network (data plan).

If you want to use an `EventLogger` and then create a bug report right after playback has started (like after 30 seconds after the player has been started) I can look into this some further by looking into the logs.

**Comment by parulgarg004** [comment]
Ok, I will provide you the logs, the problem comes with the data connection.
