### ISSUE TITLE
Support for seamless track selection between adaptive multi-angle videos (DASH/SS/HLS)

### ISSUE THREAD

**Issue by WassimErriha** [google/ExoPlayer#5861]
I am working on a project where the user is able to switch between different camera angles during playback. At the moment, Exoplayer is capable of making a seamless switch between HLS variants. The solution for doing so is mentioned in #2250. Also, from the commit references in #2600 it looks like there is going to be support for HLS video renditions in the next release.
My question is; 
Is it going to be possible to make a seamless switch between renditions the same way it is possible to switch between variants ?
Also, from your experience , will this be easier to implement with DASH or SS content as apposed to HLS ?
Any pointers to how I could achieve this will be much appreciated !
Thank you !

**Comment by marcbaechinger** [comment]
@AquilesCanta May I ask you to comment on the HLS variants/rendition question?

**Comment by WassimErriha** [comment]
Any comments about this ?

**Comment by WassimErriha** [comment]
@AquilesCanta I can provide more details if the question is vague.
Thank you!

**Comment by AquilesCanta** [comment]
Apologies for the delay.

> Is it going to be possible to make a seamless switch between renditions the same way it is possible to switch between variants ?

Can you clarify what you mean by seamless?

There are two dimensions to the question:
- Doing seamless track selection. For in-adaptive-group track selection, you can track #2250. However, I understand you want track selection between tracks in different TrackGroups. If that's the case, I think the best approach is implementing a custom media source that changes the source of the samples directly, so that the rendererer never perceives a SampleStream replacement. This would be equivalent to the media source adapting between variants, except in this case, the adaptation would happen between chunk sources.
- Support for multiple video track groups. Already supported in DASH. For HLS, multi-video-group support is tracked by #2600.

Does this answer your question?

**Comment by WassimErriha** [comment]
Excuse me if I am using the wrong terms :)
What I meant by seamless is that when you force the player to switch between variants, re-buffering occurs. I used the solution you mentioned in #2250 to make the switch between variants without a re-buffer. My understanding was that if I can switch between variants in this way, I should be able to switch between renditions (or camera angles) without re-buffering as well.
Your second bullet point suggests that multiple video track groups is already supported in DASH. Does this mean that if I change my content from HLS to DASH, I can then  use a custom `AdaptiveTrackSelection` to switch between camera angles (or adaptations) ?
If not, then your first suggestion should be what I'm after.

**Comment by AquilesCanta** [comment]
> Does this mean that if I change my content from HLS to DASH, I can then use a custom AdaptiveTrackSelection to switch between camera angles (or adaptations) ?

No, unfortunately. The reason is DashMediaSource (or any MediaSource) will not put non-inter-adaptive tracks in the same TrackGroup, which means that the AdaptiveTrackSelection (which has information of a single group) will not be able to adapt between them.

That is why you will most likely need changes in the MediaSource.

**Comment by ojw28** [comment]
I'm curious how you would envisage "user is able to switch between different camera angles during playback" working in practice. To get it seamless you would either have to:

1. Not switch immediately. This can be confusing from a user perspective, because they've pressed a button and a couple of seconds later they can still be waiting for something to happen. I guess this can be mitigated to some extent with a UI component that shows the switch is "in progress", or something like that.
1. Be downloading all of the different camera angles all of the time, so that you have buffered media just in case the user switches.

**Comment by WassimErriha** [comment]
@ojw28
Yes, your first point is what I had in mind.
The idea is that the player will be switching at random between streams (angles) at a 10sec interval for instance. But at the same time, the user has the option to override the automatic selection. In this case a UI component can be shown during transition between track.

My initial though was to use a custom trackselector to achieve this, but as @AquilesCanta suggested, I need to create a custom media source instead.
At the moment, I'm still trying to understand the sub-components of the mediasource and how they interact with each other to change the source of the samples directly( as was suggested).
I haven't been successful, but I was avoiding asking too many questions here because I dont't want to risk having this issue closed for being out of scope.
Is it possible to elaborate on how I should go about doing this at a high level ? Like what methods I should be looking at and what classes I might need to customize ...

Thank you !

**Comment by ojw28** [comment]
Got it, thanks. This request is effectively a combination of https://github.com/google/ExoPlayer/issues/2600 (specifically for HLS) and https://github.com/google/ExoPlayer/issues/2250 (which is what you're requesting here). Hence I think we can close this as a duplicate, primarily of the second of these.

**Comment by WassimErriha** [comment]
I was intacipating a work around that I can implement in the meantime if this is not too much of a hassle.
Is this on the roadmap yet ?
Thanks for your time !

**Comment by ojw28** [comment]
It's not prioritized as part of our current roadmap. It's also not possible for us to provide detailed guidance on this kind of workaround without it consuming an unreasonable amount of time, sorry.

**Comment by WassimErriha** [comment]
Thanks for your time anyway.
