### ISSUE TITLE
Support for .srt subtitle format

### ISSUE THREAD

**Issue by aravinds03** [google/ExoPlayer#587]
Hi,
Is there any support for srt subtitle parser in exoplayer?
If yes, can you please provide example code snippet?
If no, can you please provide alternate solution?

**Comment by ojw28** [comment]
SRT is supported, but the setup is a little convoluted. I'm working on making it at least a little bit simpler, and will update this bug in a couple of days once the necessary changes are pushed.

**Comment by andreimarinescu** [comment]
Is there any example of SRT implementation? I'm trying to work with the one for WebVTT in #39, but I seem to be missing the proper knowledge of working with the API, and also things seem to be slightly changed since that example. Thanks!

**Comment by ojw28** [comment]
Sorry for the delay in simplifying this. We're getting closer.

**Comment by aravinds03** [comment]
Hi, Any update here?

**Comment by ojw28** [comment]
On the dev branch, you should now be able to load and play a subtitle file like:

```
DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
SingleSampleSource textSampleSource = new SingleSampleSource(textUri, textDataSource,
    MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US));
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player,
    player.getMainHandler().getLooper());
```

**Comment by aravinds03** [comment]
Hi,
Is this change released in 1.4.2 ?

**Comment by ojw28** [comment]
Yes.

**Comment by sachinbhanot** [comment]
How to give the path of SRT file to exoplayer.? Is there any demo code for
use it?

**Comment by ojw28** [comment]
textUri in the sampe code above is the path of the file. Have you tried using that code? The change also shows you which branches and release tags it's in, if you click on it.

**Comment by sachinbhanot** [comment]
Actually I m following this thread long time... Never tried yet... I have
subtitle file downloaded from internet. I want to use with my HLS stream
... So I will try it and let u know thanks

**Comment by pratikjk** [comment]
@ojw28 
I have a timed text in a non standard format, I have parsed this into subrip format. Now I don't want to write this subrip to disk, instead directly use it in the ExoPlayer. I tried using ByteArrayDataSource with the subrip string and SingleSampleSource with Uri.Empty. This doesn't seem to work. any pointers?

**Comment by Kening** [comment]
Hi @ojw28, I am using this SingleSampleSource class to load a TTML subtitle file, it works except for one thing, it's related to that #707 issue, not getting STATE_ENDED when the video is finished. 

This is using the code from the tag r1.4.2.

In TextTrackRenderer's doSomeWork(), it's calling readData() on the sample source, and will set inputStreamEnded to true only if readData() return SampleSource.END_OF_STREAM. And inside SingleSampleSource's readData() implementation, it will return END_OF_STREAM only if pendingSample is true. This flag pendingSample will be set to true when seekToUs() is called, that's why whenever we seek, the video will never get back to  STATE_ENDED state.

Wonder if there's an easy solution for this problem.

**Comment by ojw28** [comment]
END_OF_STREAM is sent if pendingSample is false, not if it's true...?

**Comment by Kening** [comment]
my typo, END_OF_STREAM is sent if pendingSample is false. 

pendingSample will be set to true after enable() is called (it will be set to true also when seekToUs() is called), so actually even without seeking, i will face the same problem since the sample source will be enabled when the TextTrackRenderer is enabled, and I will never have a chance to set it back to false unless I call disable() on it.

**Comment by ojw28** [comment]
Ah, I see the problem. I think this is fixed already on the dev branch.

**Comment by Kening** [comment]
I see the change in SingleSampleSource, that should fix this problem, however there is now another problem related to seeking while I pull in dev branch. I am not able to seek properly while playing HLS video, the seekbar and progress indicator is no longer working.

And if I run ExoPlayer's demo app, I see similar issue, when I play HLS video in the ExoPlayer demo (any video in the HLS section), the media controller is not working properly, don't see any progress on the seekbar and the position is not updating, seeking is not working. Maybe a known issue, or maybe another issue to track it?

**Comment by Kening** [comment]
@ojw28 I am able to pull the change in SingleSampleSource and just that on top of r1.4.2.

I run into one problem, in SingleSampleSource.java there's this line:

private void maybeStartLoading() {
    if (loadingFinished || state != STATE_END_OF_STREAM || loader.isLoading()) return;
    ....
}

the check of state != STATE_END_OF_STREAM is preventing loader.startLoading from happening, since the state is not initialized to STATE_END_OF_STREAM but 0, which is STATE_SEND_FORMAT, so I add a line:

 if (loadingFinished || (state != STATE_END_OF_STREAM && state != STATE_SEND_FORMAT) || loader.isLoading()) return;

this fix my problem, now I am able to get STATE_ENDED on the player when a video with closed caption is finished playing. 

Thanks for your help.

**Comment by ojw28** [comment]
Thanks for the feedback.

- It should be ```state == STATE_END_OF_STREAM``` (== rather than !=). I'll get this fixed on the dev branch.
- Yes, seeking is currently broken for HLS on the dev branch. I'll take a look and get it fixed.

**Comment by ojw28** [comment]
The issues on the dev branch should be fixed by the change above. Note that dev is a little unstable in general at the moment, due to work on #514.

**Comment by aravinds03** [comment]
Thanks for srt support. It worked perfectly.
For those who are looking for sample code, here it is,

//text renderer.
DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
SingleSampleSource textSampleSource = new SingleSampleSource(Uri.parse("http://path.srt"),
                    textDataSource,
                    MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US));
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player,
                    player.getMainHandler().getLooper());

TrackRenderer[] renderers = new TrackRenderer[DemoPlayer.RENDERER_COUNT];
renderers[DemoPlayer.TYPE_TEXT] = textRenderer;
player.onRenderers(null, null, renderers, bandwidthMeter);

//text renderer is disabled by default initially. So, enable it after clicking CC button.
player.selectTrack(DemoPlayer.TYPE_TEXT, DemoPlayer.PRIMARY_TRACK);

//disable subtitle
player.selectTrack(DemoPlayer.TYPE_TEXT, DemoPlayer.DISABLED_TRACK);

**Comment by aravinds03** [comment]
The above code snippet is not working for .vtt file. 
Do I need to modify anything?

**Comment by dhinx** [comment]
do you have full code ?

thanks

**Comment by JoelSjogren** [comment]
The code posted by ojw28 on Jul 29 does no longer work since MediaFormat.createTextFormat has changed signature. Could someone translate it? Is the new trackId parameter arbitrary?

**Comment by JoelSjogren** [comment]
After being stuck for three hours I finally solved my problem. See a working example of TextTrackRenderer below. My problem was that I had the line
> Uri uri = Uri.parse("android.resource://joel.moresubtitles/" + R.raw.german);

instead of the one below. I have since switched to saving my srt as assets/german.srt instead. Actually, enter a random string after android.resource:// and TextTrackRenderer won't complain even though the file cannot be opened. I think there should have been some error message.

Here's my working code (using version 1.5.3):

    MediaFormat mediaFormat = MediaFormat.createTextFormat("0", MimeTypes.APPLICATION_SUBRIP, MediaFormat.NO_VALUE, C.MATCH_LONGEST_US, null);
    Uri uri = Uri.parse("file:///android_asset/german.srt");
    SingleSampleSource textSampleSource = new SingleSampleSource(uri, new AssetDataSource(this), mediaFormat);
    TrackRenderer renderer = new TextTrackRenderer(textSampleSource, this, getMainLooper());

    exo = ExoPlayer.Factory.newInstance(1);
    exo.addListener(this);
    exo.prepare(renderer);
    exo.setPlayWhenReady(true);

**Comment by zue666** [comment]
@JoelSjogren can you please upload the code to wetransfer?

**Comment by JoelSjogren** [comment]
@zue666 I hope this version is good (the project was never finished): http://we.tl/PVoheshAkr (wetransfer), https://goo.gl/V07Mmu (drive). The relevant file is OverlaidSubtitles.

**Comment by zue666** [comment]
@JoelSjogren thank you very much, i'll try it

**Comment by Hitexroid** [comment]
@JoelSjogren 

hi , thank you very much but this line of code : 

`TrackRenderer renderer = new TextTrackRenderer(textSampleSource, this, getMainLooper());`

 returns this Error : 

> The constructor TextTrackRenderer(SingleSampleSource, SampleChooserActivity, Looper) is undefined

**Comment by JoelSjogren** [comment]
Did you perhaps not implement TextRenderer in your activity like I did? The second argument needs to be a TextRenderer.

**Comment by Hitexroid** [comment]
oh sorry i had forgotten that !

i write this code in the end of `onCreate`  of  `PlayerActivity`

`    File file = new File("storage/emulated/0/01.srt");

```
Uri uri = Uri.fromFile(file);
SingleSampleSource textSampleSource = new SingleSampleSource(uri, new AssetDataSource(this), mediaFormat);
TrackRenderer renderer = new TextTrackRenderer(textSampleSource, this, getMainLooper());

ExoPlayer exo = ExoPlayer.Factory.newInstance(1);
exo.addListener(this);
exo.prepare(renderer);
exo.setPlayWhenReady(true);`
```

But not showing anything ...

**Comment by JoelSjogren** [comment]
My best guess is that file loading fails silently. Maybe a '/' is missing before "storage".

**Comment by Hitexroid** [comment]
i inserted '/'   `File file = new File("/storage/emulated/0/01.srt");`
but did not changed
not showing anything

i loged file.exists
thats True

sorry for my English

**Comment by JoelSjogren** [comment]
Then I don't know.

**Comment by Hitexroid** [comment]
oh nooooo :(
i really need to show subtitle on movie
please help me
