### ISSUE TITLE
Problem with hasNext() and hasPrevious() for ConcatenatingMediaSource

### ISSUE THREAD

**Issue by tomislavturcic** [google/ExoPlayer#5872]
### [REQUIRED] Searched documentation and issues
Couldn't find an answer for this in source or on the Web so here it goes.

### [REQUIRED] Question
Currently I am using ConcatenatingMediaSource to play a number of tracks. I use onPositionDiscontinuity to get notified when a new track is played. Then, I wish to update my UI with current track info and enable / disable previous and next buttons depending on the return values of SimpleExoPlayer's hasNext() and hasPrevious() methods. However, first time I set a new ConcatenatingMediaSource and call exoPlayer.prepare(), onPositionDiscontinuity gets called, but hasNext() and hasPrevious() return false because those window indexes haven't been set yet. Any workaround for this?

**Comment by tonihei** [comment]
I think you can solve the problem by also listening to `onTimelineChanged` and updating the UI in there as well. 

This is because a timeline change may include a position discontinuity (mentioned in the documentation [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onTimelineChanged-com.google.android.exoplayer2.Timeline-java.lang.Object-int-)) and the first update specifically, which initialized the playlist after `player.prepare`, is a timeline change event.

Not sure if relevant for your app, but it's also a good idea to update the UI in `onRepeatModeChanged` and `onShuffleModeEnabledChanged` because this may influence whether a next or previous item is available. Please also compare with the ExoPlayer playback controls UI and all the callbacks where `updateNavigation()` is called in [this listener](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1106).

**Comment by tomislavturcic** [comment]
Ok, thanks for clearing that up! That definitely helps.
