### ISSUE TITLE
Decoder reuse in MediaSessionConnector

### ISSUE THREAD

**Issue by AndrazP** [google/ExoPlayer#5891]
### [REQUIRED] Searched documentation and issues
Recent [Improved decoder reuse in ExoPlayer](https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d) blog post explains how to make sure your app benefits from decoder reuse:

> When re-preparing the player with a different video, call prepare() with the new MediaSource without calling stop() first. This is because by default, ExoPlayer will still release decoders when stop() is called.

I noticed MediaSessionConnector.java calls [stopPlayerForPrepare(boolean playWhenReady) ](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L837)before preparing new source.

### [REQUIRED] Question
Is there a reason why MediaSessionConnector calls player.stop() before preparing new source? Is this not against best practices for decoder reuse?

**Comment by ojw28** [comment]
Good question ;). I doubt there's a good reason... @marcbaechinger - Think we can safely remove the `stop()` call, and rename `stopPlayerForPrepare` to `setPlayWhenReady`? Or is there a reason those calls are there?

**Comment by tonihei** [comment]
Just to document the potential change in behavior after this change: A `PlaybackPreparer` which tries to start from a non-default start position may now fail if does not call `player.stop()` itself:
```
public void onPrepare() {
  player.seekTo(startPosition);
  player.prepare(newMediaSource, /* resetPosition */ false, /* resetState */ true);
}
```
That is because this seek will be treated as a seek in the old media due to the missing stop operation. This may (or may not) cause unexpected effects for the start position in the new media even if we keep the position. If that problem occurs, it can be fixed by calling `player.stop(true)` first in `PlaybackPreparer` methods.

**Comment by ojw28** [comment]
As discussed, we need a slightly bigger change to correctly handle all cases. Reopening.

**Comment by loki666** [comment]
I know this now closed, but I have an issue after updating to 2.10.2.

My music applications prepare the player with the latest playing queue when it starts, but now my "play" buttons (which uses the MediaControllerCompat.TransportControls) fails because the player is in READY state, so the onPlay() callback in MediaSessionConnector does nothing

this is because the setPlayWhenReady() has been removed from onPlay()

funny thing, if I use the play button in the Notification from the PlayerNotificationManager, it works since the onReceive calls dispatchSetPlayWhenReady()

how to solve this? TIA

**Comment by tonihei** [comment]
@loki666 Could you please open a new issue to discuss this question/problem?

**Comment by loki666** [comment]
#6093
