### ISSUE TITLE
Stop forever after buffering after playing 43 minutes

### ISSUE THREAD

**Issue by ItsRay** [google/ExoPlayer#5904]
[REQUIRED] Content description
After I played my HLS content for 42:59 (minute:second), the player state turned to STATE_BUFFERING and stopped in this state forever.

No matter where the start time is, the player goes to STATE_BUFFERING after playing about 42 minutes and 59 seconds.

[REQUIRED] Link to test content
provided by email.

[REQUIRED] Version of ExoPlayer being used
2.10.
By the way, I tested this in version r2.5.2 and the player stopped after playing about 13 minutes.

[REQUIRED] Device(s) and version(s) of Android being used
Devices:
Samsung Galaxy S6 (Android 7.0)
Pixel 2 (Android 9)

**Comment by ojw28** [comment]
This is similar to #2233. The root cause is that the segment durations listed in the media playlists are rounded to integer precision. The sum of the durations then drifts over time. This means that the further down the media playlist you go, the greater the drift between the media the playlist claims is in a segment, and the media that the segment actually contains. This causes ExoPlayer's buffering logic to get into a state where it thinks it has media in the buffer, even though it's actually exhausted it.

The HLS specification has had the option of floating point segment durations (which are not susceptible to drift in the same way) for ~8 years now, and you should really be using them. Integer segment durations are fundamentally sub-optimal (particularly for seek operations). I don't think we see enough content that has this issue for it to be worth us spending any time on improving the way we handle it. My response in https://github.com/google/ExoPlayer/issues/2233#issuecomment-268298490 applies to this issue too.

**Comment by KelvinJin** [comment]
@ojw28 Hey, sorry for commenting on a close issue. I'm having some issue very similar to this so just want to double check what it means by `integer precision` segment duration rather than open a duplicated issue.

My stream has the following tag:

```
#EXT-X-TARGETDURATION:10
#EXTINF:10.000,
...
#EXTINF:10.000,
...
```

Would you consider the above durations rounded to integer precision?

Thanks!

**Comment by ojw28** [comment]
> Would you consider the above durations rounded to integer precision?

Yes (unless each segment really is exactly 10 seconds).

**Comment by ItsRay** [comment]
thanks!
