### ISSUE TITLE
How to extract timed metadata from HLS stream?

### ISSUE THREAD

**Issue by stevendesu** [google/ExoPlayer#5936]
### [REQUIRED] Searched documentation and issues
I've searched through [the ExoPlayer documentation](https://exoplayer.dev) and on StackOverflow, and I've done a significant amount of experimentation to try and guess my way to a proper answer

### [REQUIRED] Question
I have an HLS video (sometimes live, sometimes not) and I wish to extract timed ID3 metadata frames from it.

The content can be viewed here: https://vcloud.blueframetech.com/file/hls/13836.m3u8

Alternatively, just the ID3 metadata packets can be seen in each TS file: `ffprobe -show_packets https://di2g5yar1p6ph.cloudfront.net/E1F739AA-875B-ADA2-136F-547295B39A3A/540p-lo.hls/D42131AB2276_0000016375.ts | grep "codec_type=data" -A 16 -B 1`

My goal is to trigger an event in my app when we hit this metadata. Here is what I've tried so far:

```java
package com.test.exoplayermetadatatest;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.metadata.Metadata;
import com.google.android.exoplayer2.metadata.MetadataOutput;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.ProgressiveMediaSource;
import com.google.android.exoplayer2.source.TrackGroup;
import com.google.android.exoplayer2.source.TrackGroupArray;
import com.google.android.exoplayer2.source.hls.HlsMediaSource;
import com.google.android.exoplayer2.text.Cue;
import com.google.android.exoplayer2.text.TextOutput;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory;
import com.google.android.exoplayer2.util.Util;

import java.util.List;

public class MainActivity extends AppCompatActivity implements MetadataOutput, TextOutput, Player.EventListener
{

	@Override
	protected void onCreate ( Bundle savedInstanceState )
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		Context context = getApplicationContext();

		SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(context);

		PlayerView view = findViewById(R.id.player);

		view.setPlayer(player);

		DataSource.Factory dataSourceFactory =
			new DefaultHttpDataSourceFactory(Util.getUserAgent(context, "app-name"));

		HlsMediaSource hlsMediaSource =
			new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse("https://vcloud.blueframetech.com/file/hls/13836.m3u8"));

		player.addMetadataOutput(this);
		player.addTextOutput(this);
		player.addListener(this);

		player.prepare(hlsMediaSource);

		player.setPlayWhenReady(true);
	}

	@Override
	public void onTracksChanged( TrackGroupArray trackGroups, TrackSelectionArray trackSelections)
	{
		for ( int i = 0; i < trackGroups.length; i++ )
		{
			TrackGroup trackGroup = trackGroups.get(i);
			for ( int j = 0; j < trackGroup.length; j++ )
			{
				Metadata trackMetadata = trackGroup.getFormat(j).metadata;
				if ( trackMetadata != null )
				{
					Log.d("METADATA TRACK", trackMetadata.toString());
				}
			}
		}
	}

	@Override
	public void onMetadata ( Metadata metadata )
	{
		Log.d("METADATA", metadata.toString());
	}

	@Override
	public void onCues ( List<Cue> cues )
	{
		Log.d("CUES", cues.toString());
	}

}
```

The `METADATA TRACK` log is happening a single time (when the video starts). The `METADATA` and `CUES` logs never happen.

**Comment by ojw28** [comment]
The problem is that the stream is broken. As per the [specification](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/2/2.html), `data_alignment_indicator` must be set to `1` if the PES packet contains the start of the ID3 tag. It appears that the indicator is always set to 0 in the stream you've provided. Hence the player correctly treats all packets as a continuation of some ID3 tag that must have started prior to the data that's been fed to it, and ignores them because it doesn't think it has the start of the tag.

You can verify that this is the problem by commenting out [this check](https://github.com/google/ExoPlayer/blob/r2.10.1/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/Id3Reader.java#L69) and then trying to play your stream again. Note that this isn't actually a proper solution, because it can cause the player to incorrectly try and parse just the end of an ID3 tag, which it should not do. The proper solution is to fix the content.

I also tested with Apple's test stream (`http://devimages.apple.com/samplecode/adDemo/ad.m3u8`) for which `data_alignment_indicator` is set correctly, and validated that ExoPlayer does deliver the metadata in that case (to `MetadataOutput.onMetadata`).
