### ISSUE TITLE
Question : UnexpectedLengthException was removed from HttpDataSource.

### ISSUE THREAD

**Issue by VishwanathPatil** [google/ExoPlayer#594]
I am unable to get the reason for removing UnExpectedLengthException from HttpDataSource Load method or not adding it in DefaultHtppDataSource load method. can i know  why was that removed , because i have seen earlier with ExoPlayer for Playready Clear streams i got that Exception , that was handled throuh retry.

**Comment by ojw28** [comment]
Previously there were two cases where this error could occur.

1. When the server doesn't support partial range requests. In this scenario ExoPlayer would make a request, have it fail part way through (for any reason), and then make a partial range request for the data it didn't receive. The server would provide a non-partial response whose length didn't match the expected length of the partial request, and so ExoPlayer would throw UnexpectedLengthException.

2. The server is fairly badly broken. Specifically, the server cleanly closes the connection claiming to have served all of the response, when in fact it's served only part of it, or more data than it was supposed to.

We fixed (1) by correctly handling a non-partial response in this case. We removed the exception at the same time because it was adding unnecessary complexity, and because we don't expect (2) to ever happen. Hopefully you've experienced case (1) in the past, in which case we've fixed the underlying issue.

If you're seeing failures that you suspect are related to the removal of the exception then please let us know. It's probably a server issue if you are, however.
