### ISSUE TITLE
Audio starts before Video.

### ISSUE THREAD

**Issue by cemkacmaz** [google/ExoPlayer#595]
Hi,

We are having problems about the player. 

We only play mp4 files.

When there is low internet connection, audio starts before the video and the video starts playing after 2-3 seconds. There is no synchronization problem meaning when video appears the audio and video synchronized. But there is a latency with the video.

What can we do about this?

**Comment by ojw28** [comment]
Are you using FrameworkSampleSource or ExtractorSampleSource when you build your player?

**Comment by cemkacmaz** [comment]
I am using DemoPlayer example in my project. It uses ExtractorSampleSource when building the player.

**Comment by cemkacmaz** [comment]
Hi, Andrew. Do you have any solutions about the latency of the video?

In devices with good connection the video opens up really quickly (below one second). But for devices with bad connection we have the problem that I mentioned at above.

For those devices that have low internet connection, we want to start the player a bit later (so that it loads some part of the video first, otherwise it either freezes too much or there are latency with the video). How can we change the start time of the video?

**Comment by andrewlewis** [comment]
The player should enter the ready state only when it has enough audio and video buffered to begin playback immediately.

I tried playing back a sample MP4 video in the demo app over a slow internet connection, and saw the expected behavior: the state changed from preparing to buffering (showing the first frame of video) then ready. The audio and video streams started at the same time on the transition to ready, and were synchronized. Then the player rebuffered after a short time, due to the slow connection.

Do you see video start late on all videos or only on certain streams? Can you reproduce the issue in the demo app? Thanks.

**Comment by cemkacmaz** [comment]
Hi Andrew,

When we use the streams in the demo app (like http://html5demos.com/assets/dizzy.mp4), it works fine video and audio synchronized. But when we try to play our streams (like http://dlfqdwwyrnn04.cloudfront.net/videos/odd20150709173759752774) the video always starts late. 

What could be the reason for this.

All of our videos are mp4 and codecs are AAC, H.264.

**Comment by andrewlewis** [comment]
The reason audio starts before video when playing that stream seems to be related to interleaving: the player thinks it is ready after it has loaded enough data, but the buffer does not include video frames at that point, as they are coarsely interleaved with audio frames. You may be able to get those streams to play just by reinterleaving them.

We will address the bug in ExoPlayer that causes the video track to be treated as ready before it has loaded data.

**Comment by ojw28** [comment]
Note - To minimize initial buffering time and reduce the probability or re-buffering events you should still aim to encode content such that the audio and video are evenly interleaved.
