### ISSUE TITLE
Not sure if "decoder reuse" works as expected

### ISSUE THREAD

**Issue by patrykcyrzan** [google/ExoPlayer#5953]
### [REQUIRED] Searched documentation and issues
This article -> https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d

### [REQUIRED] Question
How can I be 100% sure that decoders are reused? I’m doing everything just like in the article, yet AnalyticsListener is giving me those confusing callbacks like onDecoderDisabled and onDecoderInitialized every time i’m calling prepare on the player with new MediaSource without changing the player instance.

When player is being prepared, onDisabled is being called in MediaCodecRenderer and then :

```
protected void onDisabled() {
  inputFormat = null;
  if (sourceDrmSession != null || codecDrmSession != null) {
    // TODO: Do something better with this case.
    onReset();
  } else {
    flushOrReleaseCodec();
  }
}
```
sourceDrmSession is not null , codecDrmSession isn’t null also and onReset is called where codec is being released. That's why canKeepCodec method is not being called. 

Did I miss something?

**Comment by ojw28** [comment]
As in blog post:

> The full story is significantly more complicated, with multiple modes of decoder reuse and conditions for each one.

Currently decoders are not re-used for DRM protected content. As per the TODO, we need to improve this case. It was not one of the initial targeted cases because (a) it's complicated to get right, and (b) most of the use cases where fast switching between videos is a requirement do not also involve DRM.
