### ISSUE TITLE
Multi-Period DASH - No Captions after Period transition or seek past a Period boundary.

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#5976]
**Issue description:**

Captions not working after a Period transition (or seeking past a period boundary) in Multi-Period DASH.

**Reproduction steps**

1) Play the Test Content indicated below & Enabled Captions Track.
2) Seek to around 16:30 position and let it play through. The Period transition will be around 17:00
3) Observe that after the period transition, there's no Captions. The Captions selection has also reverted.

Tested on Google Exoplayer 2.7.1, 2.9.6, and 2.10.1

**Link to test content**

Content (DASH) Url:  https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/01/27/1432585795763/49269_cenc_precon_dash/stream.mpd

WV LA URL:  https://cbsi.stage.ott.irdeto.com/widevine/getlicense?CrmId=cbsi&AccountId=cbsi&SubContentType=Default&ContentId=fC0UP1UhEHgJ8mCae5pEb7Iu_r8OJbMQ

NOTE: The LA URL is good till next week. After that please let us know, and we can provide a new LA URL that will be good for another week.

**Version of ExoPlayer being used**

Tested on Exoplayer 2.7.1, 2.9.6 and 2.10.1

** Workaround **

As a workaround, what we implemented is to re-select the previously selected caption track after a period transition.

**Comment by ojw28** [comment]
Please see [this Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). In particular, see the second benefit of using constraint based track selection rather than a specific selection override:

> Constraints can be applied consistently across all periods in a complex piece of media, even if those periods contain different tracks. In contrast, a specific selection override is only applied to periods whose tracks match those for which the override was set.

The problem with using a specific selection override in this case is that the format of the subtitle representation in the second period isn't identical to the one in the first representation (e.g. its bitrate is different). So the player doesn't know whether the specific selection override should still be applied, and so does not apply it.

Constraints avoid this problem by expressing intent as part of the selection (e.g. "select English subtitle"). You should use them ;).

**Comment by ssenanayake** [comment]
Thanks :)   Implemented the suggestion and verified as working.
