### ISSUE TITLE
Segments failing to load when phone time out of sync

### ISSUE THREAD

**Issue by oseparovic** [google/ExoPlayer#5979]
I've been using Exoplayer for a while for Dash broadcasts. Recently I noticed that my personal device stopped loading streams. When I looked through logs I noticed that I was getting a 410 from the server because the segments that were being loaded had already been removed. On other devices I didn't have this problem.

As I dug deeper into the issue I noticed that my personal device's System time was out of sync by about 4 minutes. When I fixed this the streams suddenly started loading again. From what I can tell the server that I'm loading segments from deletes them after ~2-4 minutes so it would occasionally start playing the streams but it was rare that they hadn't already been cleaned up.

### [REQUIRED] Searched documentation and issues

I've been looking through the DashMediaSource file and in `processManifest` it looks like several variables are set to be relative to `getNowUnixTimeUs()` which uses System time for dynamic streams (as is my case)

      long liveStreamDurationUs = getNowUnixTimeUs() - C.msToUs(manifest.availabilityStartTimeMs);

### [REQUIRED] Question

Aside from informing the user that their System time has drifted is there anything I can do to mitigate this issue?

Note: this is a 3rd party app I'm working on. I do not have control over the server side.

**Comment by ojw28** [comment]
DASH manifests that require the client to have an accurate clock should include a `UTCTiming` element, so that the client can synchronize itself with the server. If a `UTCTiming` element is included then ExoPlayer will not rely on the device clock.

Marking as "bad content" on the assumption that there is no `UTCTiming` element. You should request that the third party fix this. The only other option I can think of would be to obtain an accurate time via some other mechanism in application code (e.g. by querying a time server).

**Comment by oseparovic** [comment]
Ah that makes sense. Thank you for the suggestion!
