### ISSUE TITLE
Passing query parameters to every segment request and manifest in MPEG DASH

### ISSUE THREAD

**Issue by sam2007** [google/ExoPlayer#598]
Hi Guys,

Is there a way to cleanly pass query parameters on all segment and manifest request that the exoplayer will do? This query string parameters will  not be included in the manifest.mpd but we would like to dynamically add them to each request.

Using the dev branch, we are looking at modifying UriUtil.java to achieve this but is there a cleaner solution?

Regards,

Sam

**Comment by ojw28** [comment]
The way that URL resolution works should allow you to set query parameters on the initial MPD request URL and have these parameters be included on subsequent segment URL requests. I think for this to work, the segment URLs need to not contain any query parameters of their own.  You'll need to consult the [RFC](http://tools.ietf.org/html/rfc3986#section-5.2.2) for the gory details, which is what ExoPlayer implements. Alternatively, you could setup your manifest server so that it takes the query parameters from the request URL and incorporates them into the manifest that's returned.

Whatever you do, you should (in my opinion) do something inside of the DASH spec. There's no provision that I'm aware of for manually side-loading query parameters into each request URL, and there are better ways to do this (such as the suggestions above).

**Comment by sam2007** [comment]
Hi Ojw,

Thanks a lot for the reply.

So in theory by default exoplayer should already carry out the query
parameters passed with the initial manifest request to the subsequent
segment request?

The URLs inside our manifest.mpd for the segment doesn't actually have any
query parameters included so if the query parameters from the initial
request will be passed by default then the default implementation might
already be sufficient with what we need.

We are quite novice with the implementations in exoplayer. Could you tell
me in which part of the code can i verify this implementation and make
changes if needed?

Regards,

Sam

**Comment by ojw28** [comment]
UriUtil does URL resolution according to the RFC linked above. The rules about how resolution works are pretty complicated (see the RFC for details), but I seem to remember it being possible to get the query parameters carried through to the resolved segment URLs.

**Comment by ojw28** [comment]
Hm. Actually, looking at the "Normal Examples" in 5.4.1 of the RFC, is appears that the query parameters (?q in the examples) don't end up being included in the resolved URLs in any useful cases. In which case the correct approach is probably to have the manifest server return a manifest with the query parameters included.

**Comment by sam2007** [comment]
It might get complicated to convince the dev team of the server to have
them include the query parameters inside the segment url of the manifest
but we will try. Besides, I totally agree with you that to comply fully
with the standard it has to be that way. We'll try to contact the server
provider.

Thanks for the info, ojw.
