### ISSUE TITLE
Decoder init failed after long time playing

### ISSUE THREAD

**Issue by sneltyn** [google/ExoPlayer#5980]
### Searched documentation and issues
I did not find a similar problem related to long-term playback. Documentation not found this problem description.

### Question
After a long continuous operation of the player (5 days), the decoder stops initialization with the following exception:

```
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: 
Decoder init failed: 
OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, 
[1920, 1080, -1.0], [-1, -1])
```

It is worth noting that the same content was played without any problems. But after 5 days, he no longer played. After rebooting the device, the content is played again.

What could be the problem? How to fix this?

**ExoPlayer**: 2.9.6

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

If this issue is device specific, it may be worth contacting the device manufacturer, since there is not much we can do on our side to help with this.

**Comment by sneltyn** [comment]
@AquilesCanta sorry, i selected questions template. Change to bug?

**Comment by sneltyn** [comment]
Well, I'll find out how this problem manifests itself on other devices. I will open the task if there is a problem on different devices.

**Comment by SafaAkbulut** [comment]
I have same problem with my Xiaomi Mi Box Android TV App
