### ISSUE TITLE
DASH MPD stream: ShouldStartPlayback of DefaultLoadControl returns false due to bufferedDurationUS become negative

### ISSUE THREAD

**Issue by arasan81** [google/ExoPlayer#6015]
### [REQUIRED] Content description
We are using Exoplayer for streaming ATSC 3.0 standard DASH live contents using Dektek. But we face a random issue with initial playback, that is a glitch for few seconds ( around 1 or 2 seconds) exists before playback after the first frame is rendered. This is a random issue, happens for 5/10 times, and the playback starts after the hiccup. 

When I debug , I observed
ShouldStartPlayback of DefaultLoadControl returns false due to bufferedDurationUS become negative that fails the condition 'bufferedDurationUs >= minBufferDurationUs'. 

Could you please let me know if this is a known issue and any possible way to fix this scenerio.

Version of ExoPlayer being used : 2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
NVidia Shield TV 2017 version, Android 8.0.0

**Comment by tonihei** [comment]
Could you please provide us with an example stream to test with? Also, it would be good to know whether this issue is specific to the NVidea Shield TV or does it happen on other devices as well?

Finally, it's slightly unclear what the expectation is. The default configuration requires at least 2.5 seconds of buffered media anyway before starting playback. With this configuration it wouldn't make a perceivable difference.

**Comment by arasan81** [comment]
I used DefaultLoadControl in our PlayerActivity as shown below.
DefaultLoadControl loadControl = new DefaultLoadControl.Builder().setBufferDurationsMs(32* 1024, 64* 1024, 512, 512).createDefaultLoadControl(). 

Initially it takes around 4 to 5 seconds for buffering( the delay is little more than what we expected, we would like to have max 3 seconds delay) and after playback starts we can observe the glitch in a second or two sometimes.  We have not tried any other device apart from Nvidia shield TV.

The stream is playing fine if we store the segments locally in file system and play. We observe the issue when we play the stream using dektek (segments stored onto pcap) or with http server for simulating live streaming.
Please let me know how to share the stream. Can we share privately?

**Comment by tonihei** [comment]
You can share information to dev.exoplayer@gmail.com using "Issue #6015" in the subject. 

Not sure if we are able to reproduce the negative timestamps, but it sounds in general as if starting with a very low buffer of 512 ms may mean that you start playback quickly, but will rebuffer soon after starting playback because the player hasn't loaded enough new data to continue playback. Could it just be that kind of behavior?

**Comment by arasan81** [comment]
@tonihei ,
You are right. It re-buffers soon after starting the playback, it seems it is due to buffer depletion. Also, for initial playback, the exo-player takes around 4 to 5 seconds. I have shared the stream using google drive and sent an email with the details of shared path and titled 'Issue #6015' to dev.exoplayer@gmail.com. Please check and let me know.
Thanks

**Comment by tonihei** [comment]
I can't reproduce the negative buffered duration values, but I think they may happen because the buffered duration is calculated as `bufferedPosition - rendererPosition` and `rendererPosition` is set by the audio renderer only, whereas the `bufferedPosition` is the minimum of the buffered position of audio and video. So if the video samples deplete first, then the audio renderer may have read slightly ahead, leading to `rendererPosition > videoBufferedPosition`. Our [code](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L513) to return the total buffered duration already takes the maximum of 0 and calculated value for this reason.

We'll make a change to ensure the same logic is applied for the value forwarded to the LoadControl to avoid unexpected behavior in custom implementations.

**Comment by arasan81** [comment]
Thanks @tonihei @ojw28 for the details. Now I understood why the bufferedDuration became negative. Let me also check the buffering behaviour with this source code change.
