### ISSUE TITLE
Mixing content from two stream urls

### ISSUE THREAD

**Issue by ThomasCZ** [google/ExoPlayer#6027]
### Content description
I have two dash streams with different languages. I am using MergingMediaSource for these two DashMediaSource. ExoPlayer provides me two languages and many video resolutions. Lets say, ExoPlayer will start with language A, I will change language to B, but ExoPlayer is still streaming video from A stream and audio from B stream.

### Link to test content
Sent to email

### Version of ExoPlayer being used
2.9.6

### Device(s) and version(s) of Android being used
5.0 - 9.0

**Comment by tonihei** [comment]
Can you describe what the expected behaviour is? You can freely select any video or audio stream from the merged sources and if both have the same content, it shouldn't be a problem to mix the video from one with the audio of the other?

As a more general point, if you control the content creation, it would make much more sense to put both audio languages in one manifest to avoid the merging process.
