### ISSUE TITLE
when does audio underrun occur ?

### ISSUE THREAD

**Issue by NayaneshGupte** [google/ExoPlayer#6033]
Documentation for [onAudioUnderrun](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onAudioUnderrun-com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime-int-long-long-) isn't enough to understand when does it occur. 

I'm analysing buffering and failure issues in my app and noticed that many times before player gets into buffering state `EventLogger` has reported audio underrun event. Not sure if buffering is associated with audio underrun but would like to understand in what all cases audio underrun occurs for HLS and DASH streams.

**Comment by tonihei** [comment]
For an explanation of the general effect, you could read the Wikipedia article: https://en.wikipedia.org/wiki/Buffer_underrun

And more specifically for ExoPlayer, it's the problem when the AudioSink needs new audio samples to continue playing continuously, but no new buffer has been read yet. You can hear this as a kind of audio stutter. This callback is meant to indicate audio underrun issues during active playback, i.e. when we actually have enough buffer available, but the device/player isn't fast enough to feed in new samples. If the AudioSink runs out of data because we haven't buffered any data, we would expect just the state change to STATE_BUFFERING. In this sense, it's not expected to get this for every change to buffering. How often do you see that? If it's easy to reproduce, can you try to provide an example stream and reproduction steps? So that we can see why this event is triggered and if we should avoid it somehow.

**Comment by NayaneshGupte** [comment]
Thanks @tonihei !
Will dig into more details and will get back to you.
