### ISSUE TITLE
mp3 file is playing only first few seconds instead of full file

### ISSUE THREAD

**Issue by Kamil-H** [google/ExoPlayer#6037]
### Content description
Audio plays only for about 2 seconds. In other apps like Google Play Music or Samsung's default player it's working as expected, so whole audio is being played. It should play about 11 minutes.

### Link to test content
https://wetransfer.com/downloads/40a45c5d7590e2cca8072cf76690079f20190614115726/d426d6
(I'm not using this URL to play this audi in the app. I'm using API url, I can't publish here).

### Version of ExoPlayer being used
ExoPlayer 2.9.0

### Device(s) and version(s) of Android being used
Samsung Galaxy S7, Android 8.0.0

**Comment by poloolop** [comment]
There is a warning thrown by Exoplayer -

> W/XingSeeker: XING data size mismatch: 5660252, 13835

Default player detects the duration as ~2 seconds, however continues playback till end of file. It doesn't allow one to seek though.

FFProbe gives following warning -

> invalid concatenated file detected - using bitrate for duration
> Estimating duration from bitrate, this may be inaccurate

For this warning, if we disable seek in XingSeeker, Exoplayer will calculate duration from bitrate and play entire file. This is not a solution for this issue though.

```
    if (inputLength != C.LENGTH_UNSET && inputLength != position + dataSize) {
      Log.w(TAG, "XING data size mismatch: " + inputLength + ", " + (position + dataSize));
      tableOfContents = null; // Disable Seek, forcing isSeekable() to false
    }
```

The solution could be to allow playback to continue. Seek bar will show 0-2 seconds, and seek will be limited to this range. The default player exhibits this behavior.

**Comment by ojw28** [comment]
As you've observed with other players, the experience is always likely to be suboptimal one way or another when trying to play this type of broken content. The solution is to fix the broken media.

I don't think it's a good idea for us to try and patch things up when dealing with this kind of content, particularly since it's fairly likely that doing so would break playback of other malformed media (or possibly even valid media). For example, just continuing to try and play the data may cause issues where non-audio data has been appended onto the end of the file, and then excluded from playback by specifying an earlier end to the content in the XING header.

**Comment by Kamil-H** [comment]
Thank you for information.
