### ISSUE TITLE
With PlayerNotificationManager not able to dynamically define CustomActions

### ISSUE THREAD

**Issue by jukkagrao** [google/ExoPlayer#6038]
### Use case description
Actually if you check the code of `getActions` in `PlayerNotificationManager` you'll see that actions play/pause are dynamically selected to display, but if you want to do the same with yours CustomActions it will not work, because `getCustomActions` calls only once and result of the function assigned to `private final Map<String, NotificationCompat.Action> customActions;` which will not update by `invalidate()` as soon as by `startOrUpdateNotification()` of `PlayerNotificationManager`.

### Proposed solution
I guess the behavior of CustomActions and Actions should be the same, so 
`getCustomActions` should be called when Player state is changed.

**Comment by marcbaechinger** [comment]
The `CustomActionReceiver` has two methods: `createCustomAction` and `getCustomActions`. The first one is called once as you describe, it gets all actions a `CustomActionReceiver` may include when the `PlayerNotificationManager` is created. The second method `getCustomActions` is called each time invalidate is called.

At this moment `getCustomActions` is called from [getActions()](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1103). This happens each time the notification is updated because the player state has changed or invalidate is called.

Can you provide more details why you are thinking `getCustomActions():List<String>` is called only once?

**Comment by jukkagrao** [comment]
Yes you are right, it's behaives like you discribe.
Unfortunatly I have no code sample anymore, probably there wasn't `createCustomActions` implemented.
