### ISSUE TITLE
PlayerNotificationManager should keep creating notifications after calling stop(false)

### ISSUE THREAD

**Issue by jukkagrao** [google/ExoPlayer#6041]
### Issue description
Please take a look on this lines:

https://github.com/google/ExoPlayer/blob/ecb7b8758cd6a700b72275a56d22b3dc56959764/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L918-L922

and then to this:
https://github.com/google/ExoPlayer/blob/ecb7b8758cd6a700b72275a56d22b3dc56959764/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L969-L972

It means that player notifications will be unregistered when e.g. user press stop button, so user can not start playing again, select next or previuse track or do something else despite that notification with buttons can be displayed in menu for example when it's foreground service.

**Comment by ojw28** [comment]
I think you'd normally use pause rather than stop if you want the notification to stay visible. @marcbaechinger - What do you think?

**Comment by marcbaechinger** [comment]
If an app expects that the user resumes playback soon, set `playWhenReady` should be set to `false` instead of calling `stop`. Calling `stop` does release resources and transitions the player into `STATE_IDLE`. In this state the player notification manager can not normally provide the data for a media styled notification unless you've called stop(false).

The `PlayerNotificationManager` behaves like that. The stop button is supposed to stop the player and remove the notification, while the pause button just pauses the player and leaves the notification in the drawer in a dismissible state. If the player is hosted in a service, the service should be taken into background at this moment.

Does pausing the player only solve the problem for you? If not can you elaborate a bit on the use case of having a notification when the player is in `STATE_IDLE`?

**Comment by jukkagrao** [comment]
Hi Marc, and thank you for answering. 
It's not a question because I've already solve my problem with workaround and of course using pause instead stop didn't solve that, otherwise there is no issue... With pause it's works as expected, but with stop I met this unexpected behavior.

Why stop button shouldn't remove notification? Because there is some cases with streaming media when you might want stop instead of pause, because when some radio on pause it continues buffering of stream and after pressing play you will listen to old information instead of actual one. 
Another case you want to stop playing then without opening app you want to manage your playlist or just start playing from beggining again.

I'm not sure, but is it connected to MediaSession too? Then what happens when somebody press stop? 

For me it's obviously unexpected behavior. If I want to dismiss notification I can use ControlDispatcher to redefine stopAction. But by default it should not unregister notification listener at least when notification is still displaying, because buttons still here and you can't use it anymore ...

At the end `stop` not equals `dismiss`.

PS Yes, I used `stop(false)`

**Comment by marcbaechinger** [comment]
I see your point and I think that's a valid use case. I changed the issue type to enhancement.

I quickly looked into this. I changed `createNotification` to return `null` only when `IDLE` and the timeline is empty:

```
if (player.getPlaybackState() == Player.STATE_IDLE && player.getCurrentTimeline().isEmpty()) { 
   builderActions = null; 
   return null; 
 } 
```

This leaves the notification as it is when `stop(false)` is called. Ffwd, rewind and the skip buttons still work as expected. However, the app needs a `PlaybackPreparer` set to the player notification manager to call `exoPlayer.retry()` when the user hits the play button in the notification. (Note: `retry()` is not part of the `Player` interface which the `PlayerNotificationManager` uses).

That's seems to be a viable way to do it, but it needs a little bit more investigation, so I don't introduce problems for other use cases. 

We'll update this issue when we've changed something.
