### ISSUE TITLE
Getting informed about user actions

### ISSUE THREAD

**Issue by Kamil-H** [google/ExoPlayer#6057]
### Searched documentation and issues
Official ExoPlayer documentation and source code of `MediaControllerCompat`, `MediaSessionConnector`, `MediaSession` classes.

### Question
Is it possible to get notified about user actions? I'm using `ExoPlayer` and `MediaSessionConnector` for handling MediaSession, so I'm not able to register `MediaSession.Callback`, that would have solved my problem, because it can be registered only once and it is done inside of `MediaSessionConnector` class.

I would like to be informed about user actions like "PLAY", "PAUSE", "SKIP TO NEXT", "SKIP TO PREVIOUS" etc. The only way to do it, I have found, is to register `MediaControllerCompat.Callback`, that has `onPlaybackStateChanged` method. The problem is that after testing it, I have found that only states that are dispatched to this method are `STATE_NONE`, `STATE_PAUSED`, `STATE_PLAYING` and `STATE_BUFFERING`. There are other states like `STATE_SKIPPING_TO_PREVIOUS`, `STATE_SKIPPING_TO_NEXT` I would like to be notified about, but it never happens.

**Comment by marcbaechinger** [comment]
Do you need to be aware of skip to next/previous in the app which has access to the `SimpleExoPlayer` instance or does it need to be reported to external client via `MediaControllerCompat.Callback`? From your comment above I understand it's the app (because the `MediaSession.Callback` would help which is in the app).

If it's the app, you can 

1) add a listener by using `player.addListener(EventListener)`. When the player transitions from one item to the next, the `onPositionDiscontinuity(int reason)` is called with `reason==DISCONTINUITY_REASON_PERIOD_TRANSITION`. This will be called if the user does skip as well as when playback automatically transitions to the next period in the timeline. In the callback method you can use `player.getCurrentWindowIndex()` to check whats the new item.

2) Another option is just provide your own ControlDispatcher with connector.setControlDispatcher() and intercept dispatchSeekTo() calls.

If you need to know about this in a `MediaControllerCompat.Callback`, you are right that the `STATE_SKIPPING_TO_PREVIOUS, STATE_SKIPPING_TO_NEXT` states are not published by the connector. 

I see two options:

1) If you are using a `TimelineQueueNavigator` the `PlaybackStateCompat` has a method `getActiveQueueItemId()` which returns the current window index.

2) If the active item changes `MediaControllerCompat.Callback.onMetadataChanged(MediaMetadataCompat metadata)` is called with a new metadata object when the player transitions to the next or previous item.

Let me know if one of these options help.

**Comment by Kamil-H** [comment]
Thank you @marcbaechinger for quick replay. 
I need this data for statistics purpose. I would like to get to know how users use my app and eventually improve some part of content/app.
To be more specific, I'm using ExoPlayer in `MediaBrowserServiceCompat`, I have access to both `ExoPlayer` and `MediaControllerCompat.Callback`.
Currently I'm using something you also mentioned: `MediaControllerCompat.Callback.onMetadataChanged` to detect that media item has been changed and it works pretty well. Unfortunately I don't see an option to distinguish skipping by user and the fact that one media has been finished and another started playing and this is something crucial in my case.

**Comment by marcbaechinger** [comment]
I think in this case it's best to register an `EventListener` with `player.addListener(eventListener)`.

The player will call `onPositionDiscontinuity(int reason)` and pass a reason. If it's a seek by the user (skip is a seek) the reason is `Player.DISCONTINUITY_REASON_SEEK`. If playback transitioned automatically the reason is `Player.DISCONTINUITY_REASON_PERIOD_TRANSITION`.

You may also want to look into `AnalyticsListener` if you want to collect other events. You can add it by using `SimpleExoPlayer.addAnalyticsListener(AnalyticsListener)`.

**Comment by Kamil-H** [comment]
I was able to play with `onPositionDiscontinuity(int reason)` a little bit and it seem like it will solve my problem. 
Thank you!

**Comment by marcbaechinger** [comment]
Great to hear. I'm closing this issue. Please re-open if needed.
