### ISSUE TITLE
Max Resolution of VideoFIle

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#608]
I tried to open a File with Resolution (2048, 1152) which ends in an exception:

Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 2048, 1152, 1.0092592, -1, -1, 4040000, -1, -1)

Is the maximum size a video can have 1920 x 1080? If i try to use anything higher than this resolution, it crashes. Is this a known issue?

**Comment by andrewlewis** [comment]
The maximum decodable frame size can depend on the device capabilities and the exact format of the video.

All Android devices should support the format/resolution combinations listed in the [CDD](https://source.android.com/compatibility/android-cdd.pdf). There is also a summary of what formats can be decoded in [Supported Media Formats](https://developer.android.com/guide/appendix/media-formats.html).

Many devices do support much higher resolutions, so it's worth querying capabilities using the utility class MediaCodecUtil. This wraps the functionality in MediaCodecInfo.VideoCapabilities and CodecCapabilities. Since your input video format is H.264/AVC, you should be able to use maxH264DecodableFrameSize(), or isSizeAndRateSupportedV21() on platform API version 21.

**Comment by Schizo** [comment]
Oh Great, thank you very much for the detailed Answer.
