### ISSUE TITLE
Is ExoPlayer rendering tied to apparent Android TV resolution?

### ISSUE THREAD

**Issue by michelforget** [google/ExoPlayer#6083]
### [REQUIRED] Use case description
On many Android TV devices, such as Sony Bravia 4K televisions, the only display resolution reported to the application is 1080/60.

If you play a 4k file, the ExoPlayer overlay shows "3840x2160" for video size, but it isn't clear if that is the output (displayed resolution) or if its the input (the resolution of the media file).

Does ExoPlayer render its output "inside" the application's apparent canvas (ie: 1080/60 in this case) or would it be using the hardware and rendering at full resolution?

### Proposed solution
If the rendering resolution is different from the source resolution, it would be nice if it clearly indicated that downscaling is happening or that there is a difference.

### Alternatives considered
n/a

**Comment by andrewlewis** [comment]
If you're using `SurfaceView` (which is the default if you're using `PlayerView`), it will render at full (4k) resolution even though the UI is rendered at 1080p. See also #800.

**Comment by tonihei** [comment]
>  it would be nice if it clearly indicated that downscaling is happening or that there is a difference.

We already have two callback for both sides of the process:
`onVideoSizeChanged` is called when the input media resolution is first set or is changed.
`onSurfaceSizeChanged` is called when the output surface resolution is first set or is changed.

**Comment by ojw28** [comment]
Added `documentation candidate` label because we should add something to the [Choosing a surface type](https://exoplayer.dev/ui-components.html#choosing-a-surface-type) section of our dev guide to indicate that `SurfaceView` should be used to output 4K when the main UI is rendered at 1080p (e.g. on AndroidTV devices).

Asides:
1. We're not sure what actually gets reported via `onSurfaceSizeChanged` in this case (i.e. whether it reports that the surface is sized for 4K, or whether it reports the size scaled to be consistent with the main UI resolution). It should be easy to check though.
1. You can check whether 4K is actually being shown at runtime by looking at the output of `adb shell dumpsys SurfaceFlinger`.
