### ISSUE TITLE
AudioProcessor for ReplayGain

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#6090]
### Use case description
I have bunch of HLS streams and i have to apply ReplayGain on them (it's value from REPLAYGAIN_TRACK_GAIN header, taken from source audio file). I'm using AAC and MP3 codecs.
I know that this header gets lost while HLS generating, but i'm able to get it from API, so my use case assume that i have stream to play and replaygain value in some variable.

### Proposed solution
As far as i understand - calculation of delta is pretty easy. It's `10 ^ (REPLAYGAIN_TRACK_GAIN  / 20)` (taken from [ReplayGain Specification](http://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Loudness_normalization)) . All it's left to do is to multiply every single sample by this value. Here where it gets more complicated. I'm not really into audio, so i may understand something wrong. If i were to use some uncompressed audio i could just check PcmEncoding in `AudioProcessor` and then get short or int (depending on PcmEncoding of the track), multiply it by my delta and write to output buffer. But AAC/MP3 are compressed, so accessing samples wouldn't be that easy to do?

I would love to do PR here, but i'm affraid that my audio knowledge is lacking a bit... If you could point me to solution when i can access every sample without worrying about codec i could create such `ReplayGainAudioProcessor`.

### Alternatives considered
I also tried to calculate volume value relatively to some base value.
For example. I assumed that 0.8 would be my "base value". When i get `REPLAYGAIN_TRACK_GAIN  ` i then apply this calculations: `80 * 2 ^ (REPLAYGAIN_TRACK_GAIN / 10)`. I found that formula somewhere, but i'm not that sure it's correct one.

Another alternative i considered is `LoudnessEnchancer` built in Android. But i couldn't find any information if it works with negative decibel values.

**Comment by andrewlewis** [comment]
Audio processors apply after decoding so they operate on PCM data. You shouldn't need to worry about dealing with compressed data and the approach you're suggesting of multiplying the samples should work. One potential pitfall is that your audio processor will be used by `DefaultAudioSink` on the playback thread, which is probably not the same thread you use to extract headers.

Regarding using audio effects for this, if you can rely on API 28 you could look at [`DynamicsProcessing`](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing.html) which seems to be quite flexible (but I haven't tried it). I don't know of other options that would work on earlier Android versions.

**Comment by jakoss** [comment]
The idea i'm looking at is one that i have `REPLAYGAIN_TRACK_GAIN` value out front - i don't have to extract headers from audio. So the thing i'll try to do is to create `AudioProcessor` that takes gain value as parameter. Then, for every track, i would create new `AudioProcessor` with gain value for that track. Does it seem possible?

Unfortunetely, relying on api 28 doesn't work for me.

**Comment by jakoss** [comment]
Ok, so i came up with this:
```
class ReplayGainAudioProcessor : BaseAudioProcessor() {

    var active: Boolean = false
    var gain: Float = 0.0f

    override fun configure(sampleRateHz: Int, channelCount: Int, encoding: Int): Boolean {
        if (encoding != C.ENCODING_PCM_8BIT && encoding != C.ENCODING_PCM_16BIT
            && encoding != C.ENCODING_PCM_24BIT && encoding != C.ENCODING_PCM_32BIT
        ) {
            throw AudioProcessor.UnhandledFormatException(sampleRateHz, channelCount, encoding)
        }
        return setInputFormat(sampleRateHz, channelCount, encoding)
    }

    override fun queueInput(inputBuffer: ByteBuffer?) {
        if (inputBuffer == null) return

        val position = inputBuffer.position()
        val limit = inputBuffer.limit()
        val size = limit - position
        val buffer = replaceOutputBuffer(size)

        // if not active - just pass buffer without gain
        if (!active) {
            for (i in position until limit) {
                buffer.put(inputBuffer[i])
            }
            inputBuffer.position(inputBuffer.limit())
            buffer.flip()
            return
        }

        if (encoding == C.ENCODING_PCM_16BIT){
            for (i in position until limit step 2){
                val sample = ByteBuffer.wrap(byteArrayOf(inputBuffer[i+1], inputBuffer[i])).short
                val delta = 10.0f.pow(gain / 20.0f)
                val targetSample = (sample * delta).toShort()
                val dbuf = ByteBuffer.allocate(2)
                val arr = dbuf.putShort(targetSample).array()
                buffer.put(arr[1])
                buffer.put(arr[0])
            }
            inputBuffer.position(inputBuffer.limit())
            buffer.flip()
        }
    }
}
```
I create this AudioProcessor once and keep the reference to it. Then, for every track, i set gain value to the right value (or i deactivate it). Does this solution make sense?

It seems to be working fine (although for now only on PCM_16BIT). Could you look at it and advise on what i could do better? I'll do a PR once i'm done with it

EDIT: Is there a way to pass buffer without any alterations more efficient? I don't think this empty loop (when `active` is false) is gonna be good for battery life.

**Comment by andrewlewis** [comment]
Looks like it's along the right lines. A few things to note:

- Please make sure you are handling transitions from one track to the next correctly. From your sample code I'm not sure how you've done this but it may involve communicating from an app thread to the playback thread where the audio processor is used. There is also the question of how you ensure that the new gain is applied at the exact moment of transitioning from one track's samples to the next.
- Regarding copying while not active, please see `AudioProcessor.isActive`. If the audio processor isn't active it won't be used by the audio sink. It can become active when `configure` is called again. For an example see `ResamplingAudioProcessor`.
- In case performance is an issue, it looks like you may be able to make some optimizations to the code in the for loop. For example, you may want to read/write the values using bit masking/shifting instead of ByteBuffer operations (I'd expect it to be significantly faster).

Regarding a pull request for this functionality: do you think this will be generally useful to others, and if so, could you link to any standards documents or specifications about replay gain? Also, our current policy is not to use Kotlin in the core library. Thanks.

**Comment by jakoss** [comment]
Is there a way to handle transitions from one track to the next in safe manner? Right now i'm doing it like this:
```kotlin
exoPlayer.addListener(object: Player.EventListener {
    override fun onPositionDiscontinuity(reason: Int) {
        val currentWindow = exoPlayer.currentWindowIndex
        if (currentPlayingWindow != currentWindow) {
            // update tracks views
            tracks.forEach {
                it.playing = it.id == currentWindow
            }

            currentPlayingWindow = currentWindow

            val track = tracks[currentWindow] // tracks indexes are lined-up with exoPlayer window
            setGain(track.gain)
        }
    }
})
```
I haven't notice any volume spikes in bad spots and (based on logging) change in gain is pretty much lined up with track transition.

Second point - is `configure` called between tracks in `ConcatenatingMediaSource`?

Third point - i'm aware that casting bytes like that is not perfect, but multiplying byte array by float value is out of my league. But i'm trying to get some help in that matter from my collaguages, so in traget solution it will be done `the right way`.

I think ReplayGain is pretty widely used, so such AudioProcessor could benefit some of your users. Specification can be found here: http://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Loudness_normalization

After i will end up with target solution i'll try to strip code from any project-specific details, port it to java and do a PR.

**Comment by andrewlewis** [comment]
Thanks for the information.

I think ideally we'd extract replay gain metadata from each container format we support, store it in ExoPlayer's `Format` type, then pass this to the sink so it can reconfigure its audio processor at the point of the replay gain changing. This is similar to how trimming audio for gapless playback works. Unfortunately this is quite a substantial change compared to your current approach but does ensure the gain is applied 'perfectly'.

Regarding your approach:
- Unless you've done it already, I think you need to synchronize access to the gain field as `onPositionDiscontinuity` is generally called on the main thread while your audio processor accesses the field on the playback thread. Setting the gain will approximately line up with the transition, but it's unlikely to be exactly on the sample boundary. That may or may not be an issue depending on the use case, I guess.
- For `configure`, if I remember correctly we don't reconfigure if the format is exactly the same before/after the transitions which may be a problem for you. If that's correct, this is a reason to include it in the `Format` as described above. Thinking about it more, having the processor always be active and copying samples isn't really that bad, but it would be better to use a [bulk put method](https://developer.android.com/reference/java/nio/ByteBuffer.html#put(java.nio.ByteBuffer)) rather than copying bytes one by one as in the code above.

**Comment by jakoss** [comment]
Ok, i think i know everything i need for now. I'll try to come back with PR when my solution will be ready. Thanks for the help!

**Comment by andrewlewis** [comment]
Ok. We are grateful for contributions, but please bear in mind that we can't commit to merging a PR in advance (we need to see how much complexity it would add, and probably also confirm there is demand for the feature to justify including it). Also, for this specific case I think we'd want the gain to be applied perfectly on the sample boundary as described in my previous comment, which may be different to what you need for your app. Thanks!
