### ISSUE TITLE
How to measure HLS live stream latency

### ISSUE THREAD

**Issue by minhbnt-1512** [google/ExoPlayer#6099]
### [REQUIRED] Searched documentation and issues
I haven't seen an answer in your documentation

### [REQUIRED] Question
Hello,
I'm working on a live stream application with Exoplayer v2.9.5. I need to calculate LiveStream Latency by `System.currentTimeMillis()` - the value of `#EXT-X-PROGRAM-DATE-TIME` tag in `HlsMediaPlaylist`. I had HlsMediaPlaylist object but I can't get the value of `#EXT-X-PROGRAM-DATE-TIME` tag. Ex: 2010-02-19T14:54:23.031+08:00. Please tell me how to get the value of `#EXT-X-PROGRAM-DATE-TIME` tag by Exo library.

**Comment by andrewlewis** [comment]
@AquilesCanta Please could you comment on the best way to do this?

**Comment by AquilesCanta** [comment]
Useful read #2930.

Regarding getting the current position from the epoch, as advertised by EXT-X-PROGRAM-DATE-TIME, you can use [Player.getCurrentPosition()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getCurrentPosition--). To get milliseconds since epoch you should add the current window's [windowStartTimeMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html#windowStartTimeMs). That will yield the current position in the same timebase as the EXT-X-PROGRAM-DATE-TIME tags. However, for latency measurement you should still synchronize a clock with the server, since currentTimeMillis() is certainly not necessarily synchronized with the server. 

One way I can imagine you can use to synchronize the server is including a tag in the media playlist that advertises the server's current millis since epoch, and then add the latency to that.

Hope this helps.
