### ISSUE TITLE
Why is `MediaSessionConnector.PlaybackController` gone in v2.10.0?

### ISSUE THREAD

**Issue by georgi-neykov-hub** [google/ExoPlayer#6106]
### [REQUIRED] Searched documentation and issues
There isn't a single word about the API change, nothing for the `DefaultPlaybackController` removal or the modified `MediaSessionConnector` constructor. As a user jumping in from v2.6.x it's not a good experience at all. Understanding what's going on involves digging through the tags, or playing with the search to craft a meaningful query, which eventually leads to [this commit](https://github.com/google/ExoPlayer/commit/063f5704cd80a733bf770375d8fbf402a6c5d958)

### [REQUIRED] Question
@ojw28, is it really justified to remove a public interface (`MediaConnector.PlaybackController`) due to personally not finding a meaningful usage? With implementations of `PlaybackController` 
 I was able to manage in a same way via composition the audio focus and media service controls. Wouldn't it be more appropriate to add a new constructor with less parameters doing the job of setting up a proper default value for the `PlaybackController` argument? Every braking change should be documented or at least mentioned somewhere in the release notes, I am not even talking about laying out some words about migration.

Having a pluggable way to control/observe certain actions in `MediaConnector` was a good thing, and again, making assumptions on how code, part of a public, no-alternative, library ends up being used is not a matter of  just "not being sure". So, is there any chance of having the `MediaSessionConnector.PlaybackController` and `DefaultPlaybackController` returing to the APi of the media session extension?

**Comment by ojw28** [comment]
`PlaybackController` was removed because it did pretty much the same thing as `ControlDispatcher`, and all other UI components were already using the latter. Some developers were having to implement the same thing twice as a result of this discrepancy, so we moved `MediaSessionConnector` over to use `ControlDispatcher` as well. You can probably use `MediaSessionConnector.setControlDispatcher` for your use case. If not, please describe exactly what it is you're trying to do, and why this is not possible.

For the more general points:
1. We've always followed a policy of making breaking changes where necessary for API sanity and forward progress. You can argue that we should only ever add, but that doesn't help a new developer who comes along and finds a messy API with multiple ways of doing the same thing, because nothing has ever been removed. Developers who argue for API stability also tend to change their mind as soon as it's the new feature that _they_ want which can only be sanely implemented by breaking what's already there ;).
1. We're aware that upgrades can be painful. One thing we're looking at is to annotate which parts of the API we believe should be stable (this would have been one of them), and make sure all breaking changes to that part of the API surface are properly documented in our release notes. So you will hopefully see some improvements coming down the line.

**Comment by georgi-neykov-hub** [comment]
@ojw28 , thank you for the quick answer. The annotation-based idea is close to what RxJava has adopted for experimental and beta features and works pretty well. I will stick to `ControlDispatcher` and migrate the current logic. 
API stability is not a big deal for me as long as changes are well documented and there are some insights what is replacing missing methods/interfaces/...

I'm closing the issue, I have some other questions on `androidx.media2`, but I'll open another ticket.
