### ISSUE TITLE
How force use IOMX on Android 4.4 (how use flint in turbo jet engine)

### ISSUE THREAD

**Issue by nshutov** [google/ExoPlayer#6115]
I want try to use IOMX instead MediaCodec. Its possible?
My device is android 4.4 amlogic cpu stb.

**Comment by andrewlewis** [comment]
As you're probably aware, ExoPlayer's core library uses the public Java `MediaCodec` API rather than interfacing with OMX directly.

If you want to integrate with a different API (e.g., via the NDK) you can try to do that via a custom renderer implementation, but I'm afraid we don't have resources to provide support on that. Out of interest, what use case requires direct integration with OMX?

**Comment by nshutov** [comment]
>Out of interest, what use case requires direct integration with OMX?

No real use case, just experiment

Thanks for answer
