### ISSUE TITLE
ExoPlayer doesn't download DRM assets

### ISSUE THREAD

**Issue by AlinaVoronkovaEpam** [google/ExoPlayer#6129]
### Issue description
I updated ExoPlayer from 2.9.3 ver. to 2.10.2 ver.
Previously with ExoPlayer 2.9.3, I was able to download DRM content (DRM license is also downloaded to play DRM content).
After the update, no audio/video tracks for downloading is seen in TrackSelectionDialog.

### Reproduction steps
- Open demo app
- Put **Asset** to `media.exolist.json`
- Try to download the asset

#### Observation
There are no audio/video tracks to be downloaded.
For text purposes I added the following code to `onPrepared(DownloadHelper helper)` callback:
```
for (int periodId = 0; periodId < downloadHelper.getPeriodCount(); periodId++) {
				downloadHelper.clearTrackSelections(periodId);

				for (int renderId = 0; renderId < mappedTrackInfo.getRendererCount(); renderId++) {
					TrackGroupArray trackGroups = mappedTrackInfo.getTrackGroups(renderId);

					for (int groupId = 0; groupId < trackGroups.length; groupId++) {
						TrackGroup trackGroup = trackGroups.get(groupId);

						for (int trackId = 0; trackId < trackGroup.length; trackId++) {
							Format format = trackGroup.getFormat(trackId);
							int trackType = inferPrimaryTrackType(format);

							if (trackType == C.TRACK_TYPE_VIDEO) {
								video.add(new Representation(format.bitrate, periodId, renderId));
							} else if (trackType == C.TRACK_TYPE_AUDIO) {
								audio.add(new Representation(format.bitrate, periodId, renderId));
							}
						}
					}
				}
			}
```
`audio` and `video` lists are filled out as expected.

```
private void addMediaToDownload(List<Representation> representations) {
      if (representations == null || representations.isEmpty()) {
        return;
      }
      // Integer.MAX_VALUE - is a requested bitrate here.
      // Auto download based on a requested bitrate is used instead of TrackSelectionDialog
      int bitrate = getBitrateToDownload(representations, Integer.MAX_VALUE);
      for (Representation representation: representations) {
        if (representation.bitrate == bitrate) {
          downloadHelper.addTrackSelectionForSingleRenderer(
              representation.periodIndex,
              representation.renderIndex,
              DownloadHelper.DEFAULT_TRACK_SELECTOR_PARAMETERS,
              Collections.emptyList());
          return;
        }
      }
    }
```
`downloadHelper.addTrackSelectionForSingleRenderer()` is called with an appropriate bitrate, but`downloadRequest.streamKeys` is empty. 

#### Expected behavior
TrackSelectionDialog contains a list of available audio/video tracks. 

### Link to test content
```
{
        "name": "Asset",
        "uri": "http://secure-cf-c.ooyala.com/Q1cG85NTE6Df3A95XMMbKGsPg6yaEZGm/1/dash/1.mpd",
        "drm_license_url": "http://player.ooyala.com/sas/drm2/BjcWYyOu1KK2DiKOkF41Z2k0X57l/Q1cG85NTE6Df3A95XMMbKGsPg6yaEZGm/widevine_modular_offline/ooyala",
        "extension": "mpd"
}
```
The issue is reproduced with other DRM assets.

### A full bug report captured from the device
A bug report has been sent by email.

### Version of ExoPlayer being used
ExoPlayer 2.10.2 - the issue is reproduced
ExoPlayer 2.9.3 - there is no issue with DRM assets

###  Device(s) and version(s) of Android being used
Pixel 2 XL + Android 9

**Comment by tonihei** [comment]
I think there are two issues in the code above:

1. 
```
downloadHelper.addTrackSelectionForSingleRenderer(
              representation.periodIndex,
              representation.renderIndex,
              DownloadHelper.DEFAULT_TRACK_SELECTOR_PARAMETERS,
              Collections.emptyList());
```
This code downloads the track selected by default for the given renderer. That means, the bitrate check you do above doesn't make a difference at all. If you want to select a very specific track which is not based on the parameters, you need to set an `SelectionOverride` in the last parameter. 

2. The default track selected by the code is above is likely empty because the `DownloadHelper` thinks that none of the tracks are playable. The most likely reason for that is that you haven't specified the `DrmSessionManager` when creating the `DownloadHelper`. You need to call the long constructor with `DownloadHelper.forDash(uri, dataSourceFactory, renderersFactory, drmSessionManager, trackSelectorParameters)` to create the download helper and pass in your drmSessionManager. 

If you want to let the user select a certain maximum video height for example, you could simplify the final selection a lot by just using something like this:
```
 downloadHelper.replaceTrackSelections(
     /* periodIndex= */ 0,
     DownloadHelper.DEFAULT_TRACK_SELECTOR_PARAMETERS.buildUpon()
         .setMaxVideoSize(
               /* width= */ Integer.MAX_VALUE,
               /* height= */ userSelectedMaxHeight)
         .build());
```

I successfully managed to download the provided example stream in our demo app using the extended constructor above, so I assume that's the main issue.

**Comment by AlinaVoronkovaEpam** [comment]
@tonihei many thanks for the quick answer! it works for me.

**Comment by talhatariq** [comment]
thanks for what


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alina <notifications@github.com> Date: 04/07/2019  8:12 p.m.  (GMT+05:00) To: google/ExoPlayer <ExoPlayer@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [google/ExoPlayer] ExoPlayer doesn't download DRM assets (#6129) 
@tonihei many thanks for the quick answer! it works for me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/google/ExoPlayer/issues/6129?email_source=notifications\u0026email_token=AGEHFFIIEEEUCI4E7T7VMN3P5YHMDA5CNFSM4H5ZPNZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZHVBQI#issuecomment-508514497",
"url": "https://github.com/google/ExoPlayer/issues/6129?email_source=notifications\u0026email_token=AGEHFFIIEEEUCI4E7T7VMN3P5YHMDA5CNFSM4H5ZPNZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZHVBQI#issuecomment-508514497",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
