### ISSUE TITLE
ExoPlayer : Can play video error not foud flie !!   if  play video Error  got to next video from array

### ISSUE THREAD

**Issue by peapea27566** [google/ExoPlayer#6138]
Help me plz 

i can play video to Exoplayer  if video now play error  got play next video soon??
Video play list from Array  can play to SDCard

Can i Exoplayer

**Comment by ojw28** [comment]
Please completely fill out the [bug report](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) or [content not playing](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=content+not+playing%2C+needs+triage&template=content_not_playing.md&title=) template for us to take a look. Please post the filled out template below, rather than filing a new issue. Thanks!
