### ISSUE TITLE
Nexus Player - Double Speed Video

### ISSUE THREAD

**Issue by iNdieboyjeff** [google/ExoPlayer#615]
Don't know if anyone else has experienced this, but I'm finding that on the Nexus Player I regularly get video playing back at double speed.  This is via HLS and SmoothStreaming.

The video plays at double speed, and then pauses till the next chunk has loaded.

The only way to solve the issue is to reboot the box.  Video playback then returns to normal, but eventually the problem returns.

Any ideas?

**Comment by akavrt** [comment]
I can confirm this problem. For whatever reason sometimes after using ExoPlayer (with basic setup for HLS playback, nothing extraordinary) inside our Android TV app, playback speed doubles and that speed increase affects other apps as well (looks like a system-wide problem related to codec).

This problem is really easy to reproduce on Nexus Player with Android 5.1.1. Our app is already available on Google Play and could be reached through https://play.google.com/store/apps/details?id=net.megogo.tv 

I could provide code sample if needed.

**Comment by ojw28** [comment]
Regrettably, I have never managed to reproduce this issue. We've seen some other reports of it though. As far as I can tell the issue isn't widespread.

At this stage I wonder whether it's specific to something like (a) other applications installed on the device, (b) the model of TV that the device is plugged into etc. Any information you can provide, and particularly full bug reports captured with `adb bugreport` would be helpful.

**Comment by akavrt** [comment]
Actually, we were able to reproduce this issue on both Nexus Player and Nvidia Shield set-top boxes only when any of those is connected via HDMI plug to the standard computer monitor (without build-in speakers). The issue disappears when set-box is connected to a TV.

**Comment by ojw28** [comment]
Interesting. It's possible that it's an issue with the monitor's HDMI implementation, although it may be the case that devices could be more robust when the issue is encountered.

**Comment by ojw28** [comment]
Please could you provide information about your monitor (i.e. the exact model number)? Thanks.

**Comment by iNdieboyjeff** [comment]
I seem to recall I encountered this a lot when using DVI to connect rather than HDMI

**Comment by akavrt** [comment]
> Please could you provide information about your monitor (i.e. the exact model number)? Thanks.

My work setup includes Nexus Player (6.0.1) connected via HDMI plug to the Dell P2214Hb.

**Comment by VLIK1234** [comment]
[bugreport.txt](https://github.com/google/ExoPlayer/files/138027/bugreport.txt)
I have the same problem. Attach my bugreport, monitor connected to with dvi to hdmi connector to the Dell p2412hb.

**Comment by akavrt** [comment]
I've rechecked our setup, both of our boxes (Nexus Player and Nvidia Shield) are connected to the Dell monitors via HDMI -> DVI cables. Sorry for the inaccuracy.

**Comment by ojw28** [comment]
Thanks for the information. It's likely that the HDMI<--->DVI cables being used are at least partly to blame in cases where this reproduces. They're most likely dropping audio in a strange way. We still haven't managed to reproduce. I'll give it another try this week, but we wont be prioritizing the issue, since it sounds like something unlikely to affect users with "normal" setups (e.g. NexusPlayer<--HDMI-->TV).

**Comment by ojw28** [comment]
I think the conclusion here is as above; these issues are caused by certain HDMI<->DVI cables, which end users are very unlikely to be using in "normal" setups.
