### ISSUE TITLE
How to dynamically add bytes data to Exoplayer MediaSource to continue playing downloaded bytes seamlessly

### ISSUE THREAD

**Issue by arasan81** [google/ExoPlayer#6174]
### [REQUIRED] Searched documentation and issues
Searched on stackoverflow.com and GitHub for Exoplayer repository. But I did not get the correct solution.

### [REQUIRED] Question
How to dynamically add media chunks to Exoplayers MediaSource to continue playing the downloaded chunks seamlessly?

I would like  to know if there is any way to load streaming bytes of a large video file ( small chunk of data) into Exo-Player as it downloads. I am downloading the large video file from an external server using our middle ware. I don't want to wait for the complete video to download and load the media data for playback.
Would help a lot if you have any ideas and suggestions or even point me in the right direction.
Thanks in advance.

### A full bug report captured from the device
NA

### Link to test content
Content can be any format (mostly HEVC, MP4 etc) that is being streamed by a STB box.

**Comment by arasan81** [comment]
Please check the format now.

**Comment by arasan81** [comment]
Hi @ojw28 ,
Any update for this query?

**Comment by ojw28** [comment]
ExoPlayer supports streaming playbacks by default. In other words, if you provide a URL to ExoPlayer, it'll start playback having only downloaded a small portion of the media and then request data as it's needed from the server.

If you want to implement something similar but where data is requested from a non-standard source (i.e. from your middleware rather than over HTTP), then you'll need to implement your own custom `DataSource` that knows how to load data from your middleware, and inject that into the player. There are lots of example `DataSource` implementations in the library, so taking a look at those should be sufficient to help you get started.
