### ISSUE TITLE
Playing encrypted HLS content with local AES Key

### ISSUE THREAD

**Issue by 00hacktheworld00** [google/ExoPlayer#6181]
Hi,
My issue is that I have an m3u8 url for an encrypted video.
It has a KEY inside the playlist but that is not valid url.

I need to use the KEY which I have saved locally on my device to decrypt and play the content.

I tried a lot of things like :
Custom Data Source
AES128DataSource
CipherDataStream

But not able to play it.

Everytime I get HttpDataSource$HttpDataSourceException or some other error.

**Comment by AquilesCanta** [comment]
The best way I can think of, without forking the library, is injecting a [custom playlist parser](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsMediaSource.Factory.html#setPlaylistParserFactory-com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParserFactory-) that replaces the existing key data. So you can provide your own key data from the app.

The [field](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/playlist/HlsMediaPlaylist.Segment.html#fullSegmentEncryptionKeyUri) you need to replace contains an URI. Since you possess the key locally, you should inject a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) there.
