### ISSUE TITLE
Using ExoPlayer on Kotlin

### ISSUE THREAD

**Issue by avecost** [google/ExoPlayer#6191]
New to ExoPlayer, and hitting a blank wall, I have converted parts of the java demo app to kotlin and was successful in running the streaming part. 

but i need the feature for offline playback and encoutering this weird (maybe for me) problem on the TrackSelectionDialog

![image-smaller](https://user-images.githubusercontent.com/1026627/61341134-c0c19f00-a877-11e9-887c-9ac22de67b90.png)

as you can see there is no default selected, and once you select one of the option, the option selectbox will jump to the other option without selecting it.

Sorry for my bad english. Need your guidance where to look to conquer this wall.

tia

**Comment by AquilesCanta** [comment]
I don't think this is an ExoPlayer related issue. It would seem to me that you lost some functionality when you converted to kotlin, since the demo app seems to work ok. Please try your luck in a general Q&A site, like stack overflow. 

It may be worth tracking #5854 for conversion of demo apps to kotlin.
