### ISSUE TITLE
Why do some issues gets closed and limits to collaborators only?

### ISSUE THREAD

**Issue by mr5z** [google/ExoPlayer#6200]
This question is not about the use of the library but how the collaborators handles the filed issues.

I was about to follow up some questions on the issues below:
1. [Cannot find sync byte. Most likely not a Transport Stream. #5039](https://github.com/google/ExoPlayer/issues/5039)
2. [Exoplayer slow seekTo() update #1399](https://github.com/google/ExoPlayer/issues/1399)

As for #5039
> This will be fixed in 2.9.1

I can still see this issues even on v2.10.3

As for #1399
> The time it takes to scrub to a frame partly depends on the performance of the video decoder, which varies between different Android devices. I can't think of any reason Android would be inherently slower or faster than another platform in general.

But why can't it be done in ExoPlayer?

I think the complainants explained their findings well enough but why does it seems to me that the collaborators doesn't want to deal with it or they can't do anything about it.

Why do some issues gets closed and limits to collaborators only?

Isn't it to better keep it open to the public so people can follow up and probably suggest solutions instead of being shut off?

**Comment by ojw28** [comment]
> #5039 - I can still see this issues even on v2.10.3

I could be mistaken, but I think the issue was fixed for the content that was provided to us in that issue. If you have other content that exhibits the same failure then the root cause may well be different. You should file a new issue with test content so that we can take a look at it.

> Why do some issues gets closed and limits to collaborators only? Isn't it to better keep it open to the public so people can follow up and probably suggest solutions instead of being shut off?

Issues are locked after they've been closed for a certain period of time. We do this because prior to doing so, we observed that the majority of responses on such issues were irrelevant or at best vaguely related to the closed issue itself. This then made old issues harder for people to read because the end of the thread would no longer correspond to the actual resolution of the issue. We'd sometimes clean the issue up by requesting that the respondent file a new issue and also removing their response, but this is obviously extra (unnecessary) work. It's easier just to lock such issues so that filing a new one is the only option. If an old issue is locked and you think it's relevant to something that you're seeing, please file a new issue and reference the old one from it.

Please do file an issue, providing test content, for the playback issue you're seeing with 2.10.3.
