### ISSUE TITLE
The current time becomes abnormal when the manifest becomes static from dynamic at the end of live streaming.

### ISSUE THREAD

**Issue by keicotu** [google/ExoPlayer#6208]
### [REQUIRED] Issue description
When the manifest is changed from the dynamic to static, the current time returned from ExoPlayer is abnormal value.
There is a function in AWS MediaService, called time-shifted viewing, the start and end time can be set in URL for playing streaming within the duration. However, the end time can be the time in the future, and the streaming will be live with a fixed start time. When the end time arrival, the last updated manifest would become static from dynamic and current time would become abnormal. If we reload the same URL (both start and end time are in the past), the current time will be normal.
(time shifted viewing: [https://docs.aws.amazon.com/mediapackage/latest/ug/time-shifted.html](https://docs.aws.amazon.com/mediapackage/latest/ug/time-shifted.html) )

### [REQUIRED] Reproduction steps
1. Play the dash time-shifted viewing URL with start and end time. The start time is past and end time is in the future.
2. When end time arrivals and manifest type becomes static from dynamic, the current time is abnormal.

### [REQUIRED] Link to test content
(email the link to dev.exoplayer@gmail.com)

### [REQUIRED] A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/3415680/bugreport.zip)

### [REQUIRED] Version of ExoPlayer being used
v2.9.3

### [REQUIRED] Device(s) and version(s) of Android being used
device: Galaxy S8+
os version: android 7.0

PS. attach a snapshot of once reproduced:
![startover (1)](https://user-images.githubusercontent.com/20722460/61643532-a81d1300-acd5-11e9-988b-437a7860576c.png)

**Comment by ojw28** [comment]
In nearly all previous cases where we've seen this, it's because the stream provider is incorrectly transforming the manifest at the end of playback. If you could capture what the manifest looks like just before the end of playback, and just after, then we can give you an indication of whether we believe the transformation is incorrect, and in what way.

That might be the best first pass at trying to diagnose this. If we're still stuck after that, then we can see about having you provide a test stream at that point. Thanks!

**Comment by keicotu** [comment]
> In nearly all previous cases where we've seen this, it's because the stream provider is incorrectly transforming the manifest at the end of playback. If you could capture what the manifest looks like just before the end of playback, and just after, then we can give you an indication of whether we believe the transformation is incorrect, and in what way.
> 
> That might be the best first pass at trying to diagnose this. If we're still stuck after that, then we can see about having you provide a test stream at that point. Thanks!

**Comment by keicotu** [comment]
In the zip, "0715_startover_dynamic.mpd" is the manifest before the end of playback (still dynamic) and "0715_startover_static.mpd" is the manifest after the last updated (become static).

[mpd.zip](https://github.com/google/ExoPlayer/files/3417958/mpd.zip)
Thanks~

**Comment by ojw28** [comment]
The addition of `@presentationTimeOffset` values in the manifest when it becomes static isn't valid. If the manifest update just didn't add those, but was otherwise exactly as it is now, then I think it would probably be a valid update (it's hard to be 100% certain, but it looks good otherwise).

**Comment by ojw28** [comment]
I think you should contact AWS support to ask them to fix this. If they disagree that their manifest transformation is incorrect, then feel free to direct them here and we can discuss it with them. Closing for now.

**Comment by keicotu** [comment]
Thanks for your reply and I've forwarded the information.

**Comment by nicoweil** [comment]
Hi @ojw28 can you please provide a spec section reference to support your statement "The addition of @presentationTimeOffset values in the manifest when it becomes static isn't valid"? I don't find it in the MPEG DASH spec or the DASH-IF IOP. We can suggest the addition of this constraint in DASH-IF IOP section 4.6.4 if needed. Thanks

**Comment by ojw28** [comment]
I don't know that it's explicitly stated anywhere, but by definition of what `@presentationTimeOffset` is, it doesn't make sense for its value to change (note that adding it with a non-zero value where it was previously absent is equivalent to changing its value, since when it's absent it's assumed to have a default value of 0).

To go into a bit more detail, `@presentationTimeOffset` is the offset between the sample presentation timestamps contained within the segments, and the elapsed time since the start of the period. Segments can't move around relative to the start of the period, and obviously the sample presentation timestamps contained within the segments aren't changing. It therefore follows that `@presentationTimeOffset` must be fixed.

@sandersaares has been doing some great work rewriting DASH-IF IOP, including a section that more clearly defines the timing model. You can read the current working document [here](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html). This working document does explicitly disallow `@presentationTimeOffset` changes:

> The following basic restrictions are defined here for MPD updates:
> 
> * `MPD@id` SHALL NOT change.
> * `MPD@availabilityStartTime` SHALL NOT change.
> * `Period@id` SHALL NOT change.
> * `Period@start` SHALL NOT change.
> * `Period@duration` SHALL NOT change except when explicitly allowed by other statements in this document.
> * The adaptation sets present in a period (i.e. the set of `AdaptationSet@id` values) SHALL NOT change.
> * The representations present in an adaptation set (i.e. the set of `Representation@id` values) SHALL NOT change.
> * The functional behavior of a representation (identified by a matching `Representation@id` value) SHALL NOT change, neither in terms of metadata-driven behavior (including metadata inherited from adaptation set level) nor in terms of media segment timing. In particular:
> 	* `SegmentTemplate@presentationTimeOffset` SHALL NOT change.
> 	* `SegmentBase@presentationTimeOffset` SHALL NOT change.

**Comment by nicoweil** [comment]
@sandersaares did a great job with this IOP update proposal, which publication is highly expected. I know that other IOP editorial constraints have prevented it to be published so far, so we are a bit in a grey zone here. I will check if we can align our implementation on it of if we have argumented concerns against the "SegmentTemplate@presentationTimeOffset SHALL NOT change" clause.

I will also sync with @sandersaares to see how we can enrich Section 4.6.4 - Transition Phase between Live and On-Demand to add more constraints than what is currently listed (only Static manifest: adds the attribute MPD@mediaPresentationDuration and Static manifest: removes the attribute MPD@minimumUpdatePeriod).

**Comment by sandersaares** [comment]
>  I know that other IOP editorial constraints have prevented it to be published so far, so we are a bit in a grey zone here.

FYI, the latest plan is to publish the timing model chapter ASAP as a stand-alone addendum to v4.3, later to be merged into v5 once v5 gets published. Remaining work is mostly to make it easier to understand where the requirements come from (with references to DASH/CMAF etc).

If there are additional improvements that can be made to document behavior in this regard, I am very eager to hear about both the challenges and the proposed solutions to them!

**Comment by nicoweil** [comment]
Hi @sandersaares, I think that the possible document improvement is to either add a link in section 4.6.4 (Transition Phase between Live and On-Demand) to the constraints of 5.2.7.5. (MPD updates) if all of those constraints apply, or to isolate specific constraints that apply specifically to the transition use case.
