### ISSUE TITLE
Specific HLS url is not working.

### ISSUE THREAD

**Issue by gb103** [google/ExoPlayer#6210]
### Searched documentation and issues
Exoplayer Github repository / Issues list
Stackoverflow Forums
Medium Forums

### Question
When trying to play a HLS url, it is not working, although several other HLS urls are working fine.
The difference which I observed compare to other HLS urls is,
a) This has only video , no audio content
b) It's codec information is different than other media codecs which I am getting with other HLS Urls
CODECS="avc1.640028, mp4a.40.5"
For others it is,
CODECS="avc1.640028, mp4a.40.2"

Although it is working on demo exoplayer app, but not in my case, what thing I am missing in player initialisation which can display such behaviour ?

### A full bug report captured from the device
2019-07-22 12:54:41.633 26599-28097/com.gaana E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type audio/mp4a-latm.
        at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:64)
        at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:134)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:584)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

### Link to test content
Master.m3u8 response :
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=1292365,AVERAGE-BANDWIDTH=871167,RESOLUTION=1080x1920,CODECS="avc1.640028, mp4a.40.5",CLOSED-CAPTIONS=NONE
https://vodhls-vh.akamaihd.net/i/mp4/clip/qaLKY23pO4/LKYVYEng3p/1555732149.mp4/index_0_av.m3u8?set-akamai-hls-revision=5&hdntl=exp=1563866928~acl=%2f*~data=hdntl~hmac=719203f49708a49817970d1bbbbbadea61ef0232ff69805f4b7f6d0b15d38672

index.m3u8 response :
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:9.040,
https://vodhls-vh.akamaihd.net/i/mp4/clip/qaLKY23pO4/LKYVYEng3p/1555732149.mp4/segment1_0_av.ts?set-akamai-hls-revision=5&hdntl=exp=1563866928~acl=/*~data=hdntl~hmac=719203f49708a49817970d1bbbbbadea61ef0232ff69805f4b7f6d0b15d38672
#EXTINF:3.200,
https://vodhls-vh.akamaihd.net/i/mp4/clip/qaLKY23pO4/LKYVYEng3p/1555732149.mp4/segment2_0_av.ts?set-akamai-hls-revision=5&hdntl=exp=1563866928~acl=/*~data=hdntl~hmac=719203f49708a49817970d1bbbbbadea61ef0232ff69805f4b7f6d0b15d38672
#EXT-X-ENDLIST

I CAN SHARE HLS URL as well on the email, as it's validity only for 4 hours.

**Comment by gb103** [comment]
After disabling audio renderer, it is working fine, But I can not see such code in demo exoplayer app, but still it was working there.

**Comment by gb103** [comment]
@ojw28 @tonihei  Please revert.

**Comment by AquilesCanta** [comment]
The issue here is that your master playlist declares audio codecs, but the content doesn't contain audio. There are multiple ways I can think of:
- Remove the audio codec from the master playlist.
- Try disabling chunkless preparation (you are using chunkless preparation, right?).
- Disable the audio renderer (or do not set one in the player in the first place) when you know you are playing this type of content.
- Use chunkless preparation but when you detect this issue (SampleQueueMappingException) re-prepare the player disabling chunkless preparation.
-  Use chunkless preparation but when you detect this issue (SampleQueueMappingException) re-prepare the player after disabling the audio renderer.

There may be more options, but these are the ones I can think of right now.
