### ISSUE TITLE
Notification stop button is not visible when multiple track is playing

### ISSUE THREAD

**Issue by squti** [google/ExoPlayer#6215]
Exo player shows stop button in notification just when single track pass to it. In multiple track it doesn't show stop button except in last track. How can I fix this to show stop button always ?

**Comment by marcbaechinger** [comment]
The button is there but because there are too many button the last one is not visible.

The notification can in total display five buttons. If you have a playlist with multiple items these will be

1. SKIP_TO_PREVIOUS
2. REWIND
3. PLAY/PAUSE
4. FAST_FORWARD
5. SKIP_TO_NEXT
6. STOP (often not displayed as this is position 6)

If you are on the last item the SKIP_TO_NEXT is not displayed and the stop button gets position 5. In all other cases the buttons overflow, so the last one is not displayed. 

You can choose to for instance not show other buttons (like rewind and fast forward) to get space, if navigation is more important.

Another option is that when the player is paused, the use can swipe away the notification. You can use this gesture/event for stopping the player and the service instead of the stop button.

**Comment by squti** [comment]
> The button is there but because there are too many button the last one is not visible.
> 
> The notification can in total display five buttons. If you have a playlist with multiple items these will be
> 
> 1. SKIP_TO_PREVIOUS
> 2. REWIND
> 3. PLAY/PAUSE
> 4. FAST_FORWARD
> 5. SKIP_TO_NEXT
> 6. STOP (often not displayed as this is position 6)
> 
> If you are on the last item the SKIP_TO_NEXT is not displayed and the stop button gets position 5. In all other cases the buttons overflow, so the last one is not displayed.
> 
> You can choose to for instance not show other buttons (like rewind and fast forward) to get space, if navigation is more important.
> 
> Another option is that when the player is paused, the use can swipe away the notification. You can use this gesture/event for stopping the player and the service instead of the stop button.

That's right. Could you give me a code example to invisible rewind and fast forward in navigation?

**Comment by marcbaechinger** [comment]
You can set the `rewindIncrementMs` and `fastforwardIncrementMs` to zero to achieve this:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html

**Comment by squti** [comment]
Thanks. It works!
