### ISSUE TITLE
AudioProcessor always delayed

### ISSUE THREAD

**Issue by l0rn** [google/ExoPlayer#6216]
### Searched documentation and issues

I did search the official docs on https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html and also looked and the included AudioProcessors like the `SonicAudioProcessor`

### Question

I am currently implementing an AudioProcessor that is processing audio via jni and some c++ code. The jni processing can be enabled and disabled by a user control in an app. See an rough implmentation of this processor here: https://gist.github.com/l0rn/30b9f846f869e55e1b0c6cb241e19114

My problem here is the following: If a user decides to enable the processing it always takes ~100 to 500ms until the effect kicks in. I am assuming that there is still unprocessed audio left in the output buffer, which leads me to the question what my options are to decrease this delay... i was thinking of **decreasing the output buffer**, but i didn't find the docs to do so. However this would be my main question to comply with the "specific exoplayer questions policy"

I'm also open to other ideas but i guess i should take this to stackoverflow

**Comment by andrewlewis** [comment]
Yes, the delay is probably caused by buffered output within or 'downstream' from the audio processor. You have control over your own audio processor part so I will assume that is already avoiding buffering more output than necessary. To eliminate `SilenceSkippingAudioProcessor` and `SonicAudioProcessor` you will need to keep playback parameters set to the defaults. Then there's the platform `AudioTrack`, which has a default buffer size of between 250 and 750 ms. You could try passing a smaller buffer size in bytes to `DefaultAudioSink.configure`, but this may increase the chance of the `AudioTrack` underrunning.

**Comment by l0rn** [comment]
I did not realize that SilenceSkipping and SonicAudioProcessor are both enabled by default - thanks for that! And also for the general clarification. I'm gonna see how far I get with this.... If I want realtime i guess i need to put my stuff further down the stack ;)
