### ISSUE TITLE
Offline HLS playback with encryption

### ISSUE THREAD

**Issue by emilsob** [google/ExoPlayer#6231]
### Searched documentation and issues

https://github.com/google/ExoPlayer/issues/5193
https://github.com/google/ExoPlayer/issues/5424
https://github.com/google/ExoPlayer/issues/6122
https://github.com/google/ExoPlayer/issues/4821

https://exoplayer.dev/

### Question
We want to make it possible to locally store adaptive HLS streams in an encrypted form in order to play this content later. 

To describe the problem: 
Offline playback without any explicit encryption works perfectly fine, same as playing a local encrypted `mp3` file with use of Exoplayer's `Aes` module. The problem occurs when we try to make use of Exoplayer's `Aes` module along with the Exoplayer's Downloader. In short, we construct a `DownloadManager` as in #5193 (with some differences caused by changes in the `DownloadManager` api) and it looks like the content is being properly downloaded. After the content is downloaded, we use `AesCipherDataSource` to wrap our cache data source and pass it as before to the `HlsMediaSourceFactory`, but it looks like the encryption / decryption fails. In logcat we can find the following error: (`Input does not start with the #EXTM3U header`).

So the question is: is there possibility to update documentation for this area or could you provide some informations / guide regarding proper way of implementing such functionality in the current Exoplayer version (2.10.3)?

### Device(s) and version(s) of Android being used
Samsung Galaxy S8, Samsung SM-T813, Emulators with Android 6+

**Comment by marcbaechinger** [comment]
@AquilesCanta may I ask you to look into this?

**Comment by AquilesCanta** [comment]
I'll need to look at the content to understand what's going on. If you don't want to share it publicly, please send a link or the files to exoplayer.dev@gmail.com. If you cannot share the content, I cannot help anymore.

> Input does not start with the #EXTM3U header

Means that you are probably trying to decrypt the playlist. So my first advise would be to avoid using an `AesCipherDataSource` for anything but media.

However, you should not need to apply `AesCipherDataSource` to media segments either because HLS encryption is automatically handled by the HlsMediaSource by parsing the #EXT-X-KEY tags from the media playlist.

So my advise is: please fix the content to match the HLS specification. I can have a look at the content and provide a piece of advise about what I suspect is wrong.

**Comment by jakoss** [comment]
I'm attaching master playlist and one of playlists.

What we (me and emilsob) are trying to do is to encrypt offline content using local key (stored by us in Android KeyStore). We have no option to add #EXT-X-KEY tags to playlists so we need to encrypt this on device by ourselves.

[playlist.zip](https://github.com/google/ExoPlayer/files/3482529/playlist.zip)

**Comment by AquilesCanta** [comment]
Please clarify:

When you play the provided playlist directly from the network, does it work?
If not, you should definitely either:
- Fix the content to include EXT-X-KEY where needed.
- Inject a custom decrypting data source as suggested in the comment above.

If yes, then at which point are you encrypting the content? How are you decrypting the content?

**Comment by emilsob** [comment]
Yes, when the playlist is provided directly from the network (or cache) it does work as expected. It also works correctly when we do not try to encrypt the downloaded content, issue occurs only when we make use of `Aes` Module. Please, look at the snippet below:

 

The way we create `DownloadManager` in the `DownloadService`:

 
```kotlin
val cacheSink = CacheDataSink(cache, -1)
val downloaderConstructorHelper = DownloaderConstructorHelper(
    cache,
    OkHttpDataSourceFactory(httpClient, USER_AGENT)
    object: DataSource.Factory {
        override fun createDataSource(): DataSource {
        return AesCipherDataSource(secretKey, FileDataSource())
    },
    object: DataSink.Factory {
        override fun createDataSink(): DataSink {
            return AesCipherDataSink(secretKey, cacheSink, ByteArray(10 * 1024))
        }
    },
    null // priorityTaskManager
)
 
return DownloadManager(
    appContext,
    DefaultDownloadIndex(dbProvider),
    DefaultDownloadFactory(downloaderConstructorHelper)
)
```

 

 

The way we create our `HlsMediaSource`:

 
```kotlin
val dataFactory = DataSource.Factory {
    AesCipherDataSource(secretKey, cachedDataSourceFactory.createDataSource())
}
val hlsMediaSourceFactory = HlsMediaSource.Factory(dataFactory)
    .setAllowChunklessPreparation(true)
```

 
    
When we don't use encryption, we simply make use of `cachedDataSourceFactory` (without wrapping it in `AesCipherDataSource`) as `HlsMediaSourceFactory`'s parameter and it works as expected - we have fully functional offline player.

**Comment by ojw28** [comment]
The problem is that you have an asymmetry between where you're encrypting during download and where you're decrypting during playback. During downloading, the flow of data looks like this. Note the encryption is happening when writing individual files into the cache:

![Screenshot 2020-06-09 at 13 52 31](https://user-images.githubusercontent.com/7881572/84149622-ac226280-aa58-11ea-9055-6fc807487785.png)

During playback, the flow of data looks like this. Note that decryption is happening on the continuous stream of data from the `CacheDataSource`, rather than the individual files. This is an important difference, and will lead to incorrect decryption. Note also that if the content is partially cached and some of it needs to be fetched from the network, this configuration will attempt to decrypt content that has never been encrypted.


![Screenshot 2020-06-09 at 13 55 25](https://user-images.githubusercontent.com/7881572/84150029-379bf380-aa59-11ea-95f5-766ab9c6988a.png)

What you should be doing, is building a chain that looks like this, so that the decryption happens in an equivalent place as where the encryption is happening.

![Screenshot 2020-06-09 at 13 55 29](https://user-images.githubusercontent.com/7881572/84150013-336fd600-aa59-11ea-8240-2bdd820ed791.png)

One other minor problem with your code is that you're using the same `CacheDataSink` instance for every `AesCipherDataSink`, where-as you should be creating a new one each time.

There's a minimal patch [here](https://github.com/google/ExoPlayer/commit/b2694e4962ba5a2ff2812ceda0c1868cceb38a25) that shows how to get cache encryption working in the ExoPlayer demo app. You can also just checkout the [branch](https://github.com/google/ExoPlayer/tree/experiment-aes-cache).
