### ISSUE TITLE
Mp3 livestream doesn't start on ExoPlayer, but works correctly on desktop browsers

### ISSUE THREAD

**Issue by goncalosilva-appgeneration** [google/ExoPlayer#6245]
### [REQUIRED] Content description
I tried playing the stream below with ExoPlayer but it doesn't work. It starts buffering without issues, but after 1-2 seconds it ends abruptly without playing any sound.
No errors are shown in logcat, and EventLogger doesn't suggest what the problem might be.

### [REQUIRED] Link to test content
https://radiomarca.streaming-pro.com:8031/radiomarca.mp3
Before testing this stream, you need to trust the SSL certificate to avoid getting CertPathValidatorException.

### [REQUIRED] Version of ExoPlayer being used
2.10.3

### [REQUIRED] Device(s) and version(s) of Android being used
- Google Pixel XL with Android 9.
- Huawei P10 with Android 9.

### [REQUIRED] A full bug report captured from the device
[bugreport-marlin-PQ3A.190505.001-2019-07-31-09-33-53.zip](https://github.com/google/ExoPlayer/files/3450611/bugreport-marlin-PQ3A.190505.001-2019-07-31-09-33-53.zip)

**Comment by marcbaechinger** [comment]
Is this the setup you are going to aim for in your app? How exactly do you want users use this if the cert path is not trusted?

**Comment by goncalosilva-appgeneration** [comment]
Hi Marc,

I tested the stream on mobile browsers and the certificate (from COMODO) is accepted without issues by Chrome, Edge, Opera and Brave.
Only Firefox shows a warning message.

**Comment by baechinger** [comment]
When you try the stream without https or from another site, does the video play as expected? I mean can we rule out network issues or is this a https certificate issue?

**Comment by ojw28** [comment]
Regarding the certificate issue, have you read [this Comodo knowledge base article](https://ssl.comodo.com/support/knowledgebase)? If you're using Windows server then it seems quite likely that's the problem.

Beyond the certificate issue, the stream itself appears to be malformed. It starts with a Xing header that defines the media to be a fixed length and duration (~2 seconds long), which doesn't make sense for a radio stream. ExoPlayer is (in my opinion) doing the right thing by not playing beyond the end of the data that the Xing header indexes, because it could legitimately be non-mp3 data (e.g. random metadata postfixed onto the end of the file) or mp3 data that the Xing header is specifying shouldn't be played. I don't see a strong argument for changing ExoPlayer, given at this point this seems to be an isolated case of someone producing malformed media. If this is your media, I'd suggest you fix it on the serving side. Or else if you believe a Xing header is valid in this case, it would be great if you could explain why.

Thanks!

**Comment by goncalosilva-appgeneration** [comment]
Unfortunately it's not my media.
I suspected that it was an ill-formed stream, but it's weird that all browsers (desktop and mobile) can play it without any issues, which is why I opened a new ticket. Even Android's native MediaPlayer can open the file.

Your argument is reasonable.
Thanks for the help and keep up the good work.
