### ISSUE TITLE
Player View not in Full mode when orientation changes

### ISSUE THREAD

**Issue by DasJhaman** [google/ExoPlayer#6252]
### [REQUIRED] Searched documentation and issues
Exoplayer 2.9.4 version.

### [REQUIRED] Question
Hello i have two layouts portrait and landscape, portrait have fixed size of player view and landscape is `match_parent`, when player changes orientation in landscape the player view size is not `match_parent` hers is screen shot attached [https://ibb.co/yFtYyPG](url) and when landscape mode changed this is how become the player view screen shot attached [https://ibb.co/KhQgcgY](url) . 

Please help me out how can i fix this issue.

**Comment by ojw28** [comment]
If you replace the `PlayerView` with a regular `View` and give it a bright red background or something, so you can see the space that it's occupying, then does this still happen? If so then this is a general Android question, rather than being anything ExoPlayer specific, and you'd be better off asking how to fix your layout on Stack Overflow.

If the problem is specific to `PlayerView` then you need to provide more information. In this case source code for a minimal demo app that reproduces the problem would be the best thing to provide, so that we can reproduce what you're seeing and advise on what's wrong.
