### ISSUE TITLE
Some videos play at 2.0 speed in some mtk devices

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#6253]
### [REQUIRED] Content description
I play the video: 
    http://static.enjoyui.com/test-res/test_riverside.mp4.
    It will play in 2.0 speed,but I set the speed is 1.0.
    The video is mono, but get the channelcount is 2;
   {
    MediaFormat format = codec.getOutputFormat();
    format.getInteger(MediaFormat.KEY_CHANNEL_COUNT);
    }
I test in some device (qcom),it is normal;

### [REQUIRED] Version of ExoPlayer being used
2.8.2

### [REQUIRED] Device(s) and version(s) of Android being used
V15 Android 9.0 (mtk)

**Comment by lsgfly** [comment]
I find the the channels is 2 by auto Atom Parsers. 
but the channels_Original is 1. 
can we use the channels_Original as the channelcount.

**Comment by ojw28** [comment]
The media specifies that it contains 2 audio channels. It seems some audio decoders are clever enough to correct the format as the data is passed through the decoder, but I'm guessing the MTK one just passes the channel count through without validating correctness, which is why you end up with double speed playback.

The media is broken in this case, so I think you should expect undefined behavior.

Could you please elaborate on what `channels_Original` is? Does this piece of data exist somewhere within the stream? If this is content you control the generation of, you should just ensure that the channel count is set correctly in the media.

**Comment by lsgfly** [comment]
The channels_original is that I solved with tools(MediaInfo).
This is the result.

ID                                       : 2
Format                                   : MPEG Audio
Format version                           : Version 2
Format profile                           : Layer 3
Codec ID                                 : mp4a-69
Duration                                 : 12 s 659 ms
Duration_LastFrame                       : -11 ms
Bit rate mode                            : Constant
Bit rate                                 : 32.0 kb/s
Channel(s)                               : 2 channels
Channel(s)_Original                      : 1 channel
Sampling rate                            : 22.05 kHz
Compression mode                         : Lossy
Stream size                              : 49.5 KiB (4%)
Writing library                          : LAME3.100UUUUUUUUUUL
Default                                  : Yes
Alternate group                          : 1

There is some discussion about channels and channels_original. 
https://sourceforge.net/p/mediainfo/feature-requests/413/
But now I do not know how to parse channels_original and should use channels_original or channels   
 as channelcount?

**Comment by ojw28** [comment]
The referenced thread doesn't seem to contain enough information for us to do anything here. I'm going to close this on the assumption that the media is bad (i.e. contains an incorrect channel count in the container). We haven't seen this issue reported until now, so it's unlikely to be a widespread problem.
