### ISSUE TITLE
Does Exo support audio channel ?

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#6288]
I want to switch audio channel, left volume scalar, right volume scalar and stereo, but I don't found how to set it.
**Does Exo support audio channel? If ok, how can I do?**

**Comment by andrewlewis** [comment]
Swapping channels and modifying their volumes is not currently supported out of the box, but it's possible to implement it with your own audio processor, possibly based on the existing `ChannelMappingAudioProcessor`. See #2659 for more information. If that doesn't help, please provide some more details about what you're trying to do.

**Comment by VeiZhang** [comment]
@andrewlewis Thanks a lot, I'm trying.

**Comment by VeiZhang** [comment]
@andrewlewis Sorry, I had followed your tips, copy `ChannelMappingAudioProcessor`, but I met problems:
```
java.lang.ArrayStoreException: com.google.android.exoplayer2.audio.SilenceSkippingAudioProcessor 
cannot be stored in an array of type xxx.ChannelMappingAudioProcessor[]
```

I override DefaultRenderersFactory:
```
DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(mContext) {
    @Override
    protected AudioProcessor[] buildAudioProcessors() {
        return new ChannelMappingAudioProcessor[0];
    }
}
```

And there is some important questions, I still don't know how ChannelMappingAudioProcessor works. How to set or get current audio channel.

**Comment by andrewlewis** [comment]
I'll submit a fix for the `ArrayStoreException` but for now you can just change your implementation to return an `AudioProcessor` array with a `ChannelMappingAudioProcessor` in it (instead of a `ChannelMappingAudioProcessor` array) to avoid this.

`ChannelMappingAudioProcessor` will let you swap audio channels (e.g., switching left/right in a stereo stream) but it doesn't support changing volumes. See `ChannelMappingAudioProcessor.setChannelMap`. If you read #2659 there are some ideas about how to scale the audio samples if you need to control their volumes, but I'm afraid we don't have time to provide additional detailed guidance on that.
