### ISSUE TITLE
Format language parameter returning 3 letters instead of 2

### ISSUE THREAD

**Issue by harshmittal29** [google/ExoPlayer#6292]
I am creating my own Format object to sync my VTT file with the video
This is how I create a format object 

```
Format textFormat = Format.createTextContainerFormat("vtt" + 1, "English",
                            MimeTypes.APPLICATION_M3U8, MimeTypes.TEXT_VTT, null, -1, flag, C.ROLE_FLAG_CAPTION, "en");
```

I get following object in return after creation 

> Format(vtt1, Finnish, application/x-mpegURL, text/vtt, null, -1, eng, [-1, -1, -1.0], [-1, -1])

Here the format language has changed from "en" to "eng". 

It was returning 2 letters before recent update. Is it possible for me to get 2 letters instead of 3?

**Comment by tonihei** [comment]
The language gets normalized into a fixed format to be able to make language comparison (e.g. for track selection based on language preferences).

We recently changed our normalization from 3-letter codes to 2-letter codes because they are more common and better integrated into the rest of the Android system. That means 2.10.4 and above should have a 2-letter code again.
