### ISSUE TITLE
An audio bug occurred with really loud scratching noise when change speed

### ISSUE THREAD

**Issue by nguyennhi263** [google/ExoPlayer#6307]
I've managed to use SimpleExoPlayer to play HLS streams successfully and implemented a working way of selecting different playback speeds (1.25x, 1.5x, etc) by setting PlaybackParameters on the player. But in sometime, the sound scratch like a noise.
It's work fine with version r-2.8.3

**Comment by tonihei** [comment]
Thanks for reporting. Could you please provide all the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md)? Specifically, it would be very helpful to have an example stream and the device you tested on so that it's more likely that we can reproduce the issue.
