### ISSUE TITLE
hls stream has higher playback start time than progressive. Served from same CDN

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#6310]
### [REQUIRED] Searched documentation and issues
I looked at stackoverflow for explainations, some blogs etc.

### [REQUIRED] Question
I have a hls stream (Audio) served from amazon cloudfront cdn, and same audio as .mp3 served from same cdn. In client side, exoplayer seem to take more time for HLS stream to start than the regular stream (mp3).
is this an expected scenario?
the difference in playback start time is about 2-3 seconds. hls takes 2-3 more seconds for playback to start.
does parsing the hls manifest adds this overhead?

**Comment by AquilesCanta** [comment]
Have you read this post: [faster HLS preparation](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6)? Are you using chunkless preparation?

Please provide sample content for both HLS and mp4 for us to look at.

It's worth noting that, at the very least, HLS will be an HTTP roundtrip (for the media playlist, 2 if there is a master playlist) slower than mp4 for starting playback. 2-3 seconds sounds quite a lot. Depending on the content, chunkless preparation may help with that.

**Comment by shubhamvashisht** [comment]
@AquilesCanta yes i have set allowChunklessPreparation to true.
Master playlist : http://d3d7iaj1xyzes9.cloudfront.net/6319159fe7e9ca4148d2ce3337dfd2d5b3484819-96.m3u8

Media playlist : http://d3d7iaj1xyzes9.cloudfront.net/6319159fe7e9ca4148d2ce3337dfd2d5b3484819-96-variant.m3u8

Mp3 url : http://d3d7iaj1xyzes9.cloudfront.net/6319159fe7e9ca4148d2ce3337dfd2d5b3484819-96.mp3

**Comment by ojw28** [comment]
As above, if you're playing an HLS master playlist then you have 3 round trips rather than 1, just because of how HLS works. The player needs to request the master playlist, then the media playlist, then the first segment, before it can play anything. In MP3 you just make a single request.

You should investigate how long those round trips are (e.g. look at network traffic), and whether they account for the additional latency.
