### ISSUE TITLE
MP3 stream stops playing after audio ad 

### ISSUE THREAD

**Issue by dim4ikhot** [google/ExoPlayer#6315]
Hi,
I know that a similar question already was asked before([#5658](https://github.com/google/ExoPlayer/issues/5658)), but now it closed, but the issue is still exists. But in my case all the time I press PLAY, stream plays an audio ad and stops, so I cannot play the stream. I'm using the latest version of Exoplayer - 2.10.4. But the interesting thing is that this stream was working well with version r2.4.3.

2.10.4 returns `Player.STATE_ENDED` after audio ad finished playback, where r2.4.3 just continued playing. 

Here is the stream for where I reproduced an issue:
http://198.143.144.226:8277/

Thanks for any help.

Bests,
Dmitriy

**Comment by tonihei** [comment]
As you pointed out, this stream has the same problem as the one in #5658 .

The content producer just glued together two mp3 files which are incompatible:
 1. The ad with a seek map for the first 9 seconds.
 2. The unseekable live stream.

To solve this issue, the stream should either provide a full XING seek map for the entire duration or shouldn't publish a seek map at all. 

It used to "work" up until version 2.9. because we just continued playing even if the official duration has already been reached. This is not really the right approach because we can easily end up reading unrelated garbage data at the end of file as reported in #4954
