### ISSUE TITLE
Exoplayer - orientation changes handling

### ISSUE THREAD

**Issue by harshmittal29** [google/ExoPlayer#6333]
Hi Exoplayer Team,

Exoplayer is amazing as it handles orientation changes very well from/to going to/from full screen mode.
I want to understand what does Exoplayer doing internally to do these changes so smoothly.

**Comment by sravan1213** [comment]
@harshmittal29 This is done using android configChanges flag for activity. 
`android:configChanges="orientation|screenSize"`

please refer https://developer.android.com/guide/topics/resources/runtime-changes for more info.

**Comment by harshmittal29** [comment]
I understand the orientation.
What I want to understand is the player using some lifecycle on changing the orientation?
The reason is I want to have different UI for full screen vs small screen.

**Comment by tonihei** [comment]
As @sravan1213  pointed out, we are only using the "configChanges" flag to ensure our surfaces are kept in the demo app when changing orientation.

There is #1845 to track better documentation for general purpose switches to fullscreen. Please refer to that issue for details.

From Android 10 onward, there will also be the new SurfaceControl API that allows you to move an existing surface around (including from and to full screen).

**Comment by ojw28** [comment]
To expand on this a bit more:
* Our demo app uses `android:configChanges` as described above.
* On API level 23 and above, we have a trick in `MediaCodecVideoRenderer` that helps to handle orientation changes in a (mostly) seamless way even if the activity isn't handling the configuration change using `android:configChanges`. In this case the `Activity` gets recreated. The problem that arises is that there's a period of time during this process where there's no valid `Surface` to output to, whilst at the same time the `MediaCodec` needs a valid `Surface`. This means that without doing something special, you end up needing to tear down the `MediaCodec`, instantiate a new one when you get a valid `Surface` again, and restart decoding from a keyframe. This wont be anywhere near a smooth experience. The trick we use is that we have a special `DummySurface`, which is an off-screen `Surface` that we create internally. We use this when we otherwise don't have a valid `Surface`, and by doing so can avoid `MediaCodec` recreation, which makes things much smoother. One caveat is that there's quite a long list of devices for which we've had to disable this on API levels 23 - 26 because it didn't work properly. See `MediaCodecVideoRenderer.shouldUseDummySurface`, which calls `codecNeedsSetOutputSurfaceWorkaround`, which is where the long list is.
* On API level 29 and above the new `SurfaceControl` API mentioned by @tonihei will provide a much better solution than our trick.
