### ISSUE TITLE
Dash Audio track selection inconsistent

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#6335]
We have 2 dash DRM streams with audio tracks.
As far as we know the default language that should be picked in dash is the first audio adaptation set.
In the following streams 1,2 we can see that the dash has Hindi as the first language in manifest
But in the first we can see in Charles that the Language that is playing in the demo app  is Hindi and in the second the language that is playing is Telugu by default.
Could you please explain when the first audio is selected and when other one is selected in dash please?

We have sent an email on dev.exoplayer@gmail.com by Subject Name:  "Dash Audio track selection inconsistent".

We can see the same in 'release-v2' version.

-Thanks

**Comment by tonihei** [comment]
Thanks for filing the issue. As already indicated in the answer to your email, this may be related to your phone's system language setting. If it's set to Telugu, then this will be preferred independent of the order in the manifest. Can you verify if that's the case here?

**Comment by GouravSna** [comment]
No, The device language is English.

**Comment by tonihei** [comment]
I'm able to reproduce the problem. But I needed to fake the user-agent because the stream doesn't load when using Android user agents.

The reason for this audio selection is that our `DefaultTrackSelector` prefers tracks with a higher bitrate if all other selection criteria are equal. Therefore we select Telugu with a bitrate of 64002 bps over Hindi with a bitrate of 64001 bps. 

This doesn't make sense in this case and is meant for cases where different quality variants of the same audio track are provided. We should probably only apply the bitrate comparison if the language (and potentially other parameters) are the same.

**Comment by GouravSna** [comment]
- Thanks @tonihei
