### ISSUE TITLE
MediaSource reflected in MediaDrmCallback

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6342]
### Use case description
To my understanding, starting with version 2.11.0, `DrmSessionManager` will be injected into the `MediaSource`. To me, it makes perfect sense to reflect that in the `MediaDrmCallback` so we actually know what `MediaSource` we are making the key request to.

### Proposed solution
Somehow get the `MediaSource` into the parameter for `executeKeyRequest` in `MediaDrmCallback`.

### Alternatives considered
Custom implementation of `MediaDrmCallback` where we pass the same parameters as for the `MediaSource`(e.g. track id). This is not preferred, because then we would need as many `MediaDrmCallback` classes as `MediaSource`s and there might be more information in the already prepared `MediaSource`(e.g. we are resolving the url based on the track id), so this information is lost in this alternative.

**Comment by marcbaechinger** [comment]
@AquilesCanta Can you please comment on this?

**Comment by AquilesCanta** [comment]
What information do you need in the MediaDrmCallback?

MediaSource is an exoplayer core functional component. I strongly doubt you intend to call MediaSource methods from MediaDrmCallback, so I suppose you want to downcast it to retrieve some information.

Considering MediaDrmCallback is such a lightweight component, I don't see any issue with creating one per MediaSource. Please clarify this bit if you find any issue with it.

**Comment by kgrevehagen** [comment]
Your assumption is correct, I don't intend to call `MediaSource` methods from `MediaDrmCallback`, but instead retrieve information stored in them.

If you don't see it as a problem of creating one `MediaDrmCallback` per `MediaSource`, this won't be a problem after 2.11.0, I can then provide my `MediaDrmCallback` with whatever I want, and it is a one-to-one relationship between the two.
But, since `MediaDrmCallback` is part of `DefaultDrmSessionManager` it would mean that we also need one `DefaultDrmSessionManager` per `MediaSource`. Would this be a problem? 

This is not possible in 2.10.4, but I guess it won't be useful to add this functionality if it can be solved like described in 2.11.0.

Feel free to close this if the above is true, thanks so much for your answer!

**Comment by ojw28** [comment]
In the general case, I think we want to keep the relationship between `MediaSource`, `DrmSessionManager` and key requests deliberately fuzzy. We have plans to allow sharing and reuse of `DrmSession` instances across multiple `MediaSource` instances that need the same keys. And also to start keeping `DrmSession` instances open for some period when they're not being used, in case they're needed again. In a world where these kind of features exist, it becomes increasingly unclear, or at least arbitrary, to which individual `MediaSource` a key request should be attributed back to.

So I don't think we can plumb `MediaSource` instances through to `MediaDrmCallback` inside the library. If you want to make the attribution clear then I agree with the approach suggested above, in which you build your components so that there's a 1:1:1 relationship between `MediaSource`, `DefaultDrmSessionManager` and `MediaDrmCallback`, which then makes attribution clear (and on a practical level, let's you build a `MediaDrmCallback` specific to the corresponding `MediaSource`. I don't see any issues with this approach.

**Comment by kgrevehagen** [comment]
Thanks for clearing up. I'm using this logic now, and it works seamlessly :)
