### ISSUE TITLE
Please a good tutorial about this exoplayer

### ISSUE THREAD

**Issue by PeyamMaroufi** [google/ExoPlayer#640]
Hi,
I've been looking for a good media player for a logn time since the traditional media player in android doesnt always work as it should.
I have some m3u8 files that are streaming urls.  What I so far have done is downloading the Exoplayer project and make a .Jar of it ( trust me , it took me 5 days just to figure out how to do it) . The only think I want to do is to play the streaming url. Ive been looking at the playActivity, it imports DemoPlayer and there I get lots of problems. "setbackgrounded" in player.setbackgrounded doesn't work and AS gives error all the time. 

For us that only want to develop a simple application and are not as experienced as you guys are please please make a simple tutorial. I've been asking around so much and it almost makes me give up.

**Comment by Schizo** [comment]
Are you using Android Studio? If you are using android-studio, it is very easy to setup ExoPlayer, for Eclipse i am not sure.

**Comment by mingfai** [comment]
it's of course always better with more tutorial and documentation. but in general, the demo project is sufficient for me to understand how to use this library.

to my understanding, the proper/official way is to implement our own player base on DemoPlayer. for me I'm lazy and just copy the DemoPlayer with small customization to my project.(and then every time I upgrade exoplayer i got to sync the DemoPlayer.java that is tedious) I wish the DemoPlayer is not just a demo but a high level player class, perhaps designed to be extended, e.g. change the private fields to protected. 

If the DemoPlayer is not a demo but a BasePlayer that is made to be easy to use, documentation/tutorial works may start at that class.

**Comment by ojw28** [comment]
As above, the demo app is pretty simple to setup / compile. I don't think we want to start writing tutorials about general Android development, setup and IDEs. These can be found elsewhere, and if we did write them we'd need to periodically update them, which would require a non-trivial amount of effort.

@mingfai - Your point about DemoPlayer is valid. Some of the open issues, such as #514, will naturally simplify this class over time as we push more functionality inside of ExoPlayer itself (that particular feature request will remove ~100 lines of code from DemoPlayer).

We may at some point move DemoPlayer into the library itself as a high level class, however it's unclear whether this is a good idea because most developers end up wanting to make some kind of modifications to it to better suit their use case.
