### ISSUE TITLE
audio & video are out of sync

### ISSUE THREAD

**Issue by HasanElHefnawy** [google/ExoPlayer#6408]
### [REQUIRED] Issue description
In the demo app "Exo IMA Demo", after making the code changes shown in attachments. While playing the video, when I press the "Home" button or "Recents" button in Navigation Bar, then go back to the app, I find the video frame before leaving the app is different from the video frame after returning to the app. In this case, if I resume the video, I get a frozen video frame for a couple of seconds till the audio and video are in sync. This occurs on the physical device. But, on the emulator, the video frame before leaving the app is **slightly** different from the video frame after returning to the app. This difference may not be noticed. I also **don't** get a frozen video frame when resuming the video. I couldn't test on other physical devices.
[MainActivity.java.txt](https://github.com/google/ExoPlayer/files/3585816/MainActivity.java.txt)
[PlayerManager.java.txt](https://github.com/google/ExoPlayer/files/3585817/PlayerManager.java.txt)
![MainActivity java](https://user-images.githubusercontent.com/45438166/64463293-c911ba00-d103-11e9-9aee-a00d3784c3ba.jpg)
![PlayerManager java](https://user-images.githubusercontent.com/45438166/64463304-d2028b80-d103-11e9-8658-3b49c941c461.jpg)

### [REQUIRED] Reproduction steps
As above.

### [REQUIRED] Link to test content
The same video
https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv

### [REQUIRED] A full bug report captured from the device
None.

### [REQUIRED] Version of ExoPlayer being used
No change.

### [REQUIRED] Device(s) and version(s) of Android being used
Physical device: Lenovo A7010 VIBE K4 Note (Lollipop 5.1 API 22)
Emulator: Nexus 5X (API 27)

**Comment by andrewlewis** [comment]
It looks like the modifications will prevent the player being released when going into the background. (Side note: this is not good because you are holding onto resources that other apps might want to use, which can be problematic for the case of video decoders.) I guess what is happening is that the player receives a new output `Surface` when the app returns to the foreground, and at this point it has to render a frame. The physical device is running API 22, so we can't use `MediaCodec.setOutputSurface`, which means that we need to reconfigure the decoder and decode from the preceding keyframe. On the emulator we can use `setOutputSurface` but playback has to advance by one frame because `MediaCodec` doesn't support re-rendering its last output frame.
