### ISSUE TITLE
HLS stream is pixelated on Android 7.0 and lower

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#6412]
### [REQUIRED] Issue description
HLS stream is either pixelated or fails playback on Android 7.0 and lower.

### [REQUIRED] Reproduction steps
Add the URL as one of the demo HLS streams and you can see the pixelation. Higher resolution/bitrates are grayed out and not selectable.

### [REQUIRED] Link to test content
https://curiosity-video-output.secure.footprint.net/bitmovin-outputs/COP_OurViolentSun.mov/52871d6a2d3e8636e22ba3519e7f8997.m3u8

### [REQUIRED] A full bug report captured from the device
[hls_exoplayer_logs.txt](https://github.com/google/ExoPlayer/files/3601134/hls_exoplayer_logs.txt)

#### Screenshot of non-selectable tracks
<img width="312" alt="non_selectable_tracks" src="https://user-images.githubusercontent.com/7673320/64703686-f3a0a180-d47a-11e9-9bca-e30f9237f075.png">

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Android 7.0 and lower

**Comment by ojw28** [comment]
> N/A - not crash logs.

Bug reports contain a lot of useful debugging information, regardless of whether there's a crash. For example, if you'd have included one, we could use it to obtain some of the other information you've omitted to provide, such as what device you're testing on. Please include all of the information requested in the issue template.

**Comment by ofuwape** [comment]
> > N/A - not crash logs.
> 
> Bug reports contain a lot of useful debugging information, regardless of whether there's a crash. For example, if you'd have included one, we could use it to obtain some of the other information you've omitted to provide, such as what device you're testing on. Please include all of the information requested in the issue template.

@ojw28  Updated with logs

**Comment by ojw28** [comment]
The device (which I think is the emulator?) doesn't advertise support for H264 high profile, which is the profile of all the variant streams in the content provided. ExoPlayer correctly evaluates that according to the advertised support, none of the streams are playable. It then tries to play the lowest quality one regardless just in case it works.

I wouldn't put too much weight on how the emulator behaves. Technically, there's no requirement that Android devices support high profile (main profile has been required from Android 6, as per [this documentation](https://developer.android.com/guide/topics/media/media-formats)), so you might want to make sure some of the lower quality variants use main profile instead. That said, I suspect that in practice pretty much all devices will support high profile.

I think everything is working as intended here. My advice would be to test on some real devices, rather than using the emulator.
