### ISSUE TITLE
How to implement adaptive playback for multi key protected DASH?

### ISSUE THREAD

**Issue by peterlisak** [google/ExoPlayer#6417]
### [REQUIRED] Searched documentation and issues
I've not found any relevant description how adaptive streaming should works when multi key protection is used and device is not complying with policy for some of the keys. 

### [REQUIRED] Question
We'd like to use multi-key protected DASH with Widevine Modular as shown on https://demo.unified-streaming.com/cpix/#!/DASH or https://github.com/Axinom/public-test-vectors#v7-multidrm-multikey. Playlists contain SD, HD and Audio adaptation sets protected by different keys that have different requirements (like security level, HDCP, etc.). 
We have tested mentioned playlists on shaka player (v2.5.5) and exoplayer (v2.9.6).
- In shaka the switching between SD and HD groups has worked automatically and if a browser does not fulfil requirements for some of DRM keys, the relevant group was not used in adaptive streaming.
- In exoplayer we've noticed that there is no auto switching between SD and HD track groups. Can exoplayer work with this kind of DASH manifests? Can it filter out AdaptationSet/RepresentationSet based on requirements defined in DRM license as Shaka does?

Any advice? What is the correct approach to implement multi-key protected adaptive streaming?

### A full bug report captured from the device
Not Applicable.

### Link to test content
https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey/Manifest_1080p.mpd
and media.exolist.json file,
```
{
        "name": "v7-MultiDRM-MultiKey 1080p",
        "uri": "https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey/Manifest_1080p.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://drm-widevine-licensing.axtest.net/AcquireLicense",
        "drm_key_request_properties": {
          "X-AxDRM-Message": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiODAzOTliZjUtOGEyMS00MDE0LTgwNTMtZTI3ZTc0OGU5OGMwIiwiZW5jcnlwdGVkX2tleSI6ImxpTkpxVmFZa05oK01LY3hKRms3SWc9PSJ9LHsiaWQiOiI5MDk1M2UwOS02Y2IyLTQ5YTMtYTI2MC03YTVmZWZlYWQ0OTkiLCJlbmNyeXB0ZWRfa2V5Ijoia1l0SEh2cnJmQ01lVmRKNkxrYmtuZz09In0seyJpZCI6IjBlNGRhOTJiLWQwZTgtNGE2Ni04YzNmLWMyNWE5N2ViNjUzMiIsImVuY3J5cHRlZF9rZXkiOiI3dzdOWkhITE1nSjRtUUtFSzVMVE1RPT0ifSx7ImlkIjoiNTg1ZjIzM2YtMzA3Mi00NmYxLTlmYTQtNmRjMjJjNjZhMDE0IiwiZW5jcnlwdGVkX2tleSI6IkFjNFVVbVl0Qko1blBROU4xNXJjM2c9PSJ9LHsiaWQiOiI0MjIyYmQ3OC1iYzQ1LTQxYmYtYjYzZS02ZjgxNGRjMzkxZGYiLCJlbmNyeXB0ZWRfa2V5IjoiTzZGTzBmcVNXb3BwN2JqYy9ENGxNQT09In1dfX0.uF6YlKAREOmbniAeYiH070HSJhV0YS7zSKjlCtiDR5Y"
        }
}
```

**Comment by BucherTomas** [comment]
This is covered here https://github.com/google/ExoPlayer/issues/3780#issuecomment-367270921

**Comment by ojw28** [comment]
Isn't it also covered here: https://exoplayer.dev/drm.html

**Comment by ojw28** [comment]
If your main issue is that switching between different `AdaptationSet`s isn't working automatically, then that's probably because the manifest isn't specifying that this is possible. A manifest should include `urn:mpeg:dash:adaptation-set-switching:2016` `SupplementalProperty` elements to indicate this. Without this signalling, for all the player knows, the different `AdaptationSet`s could contain completely different content, in which case automatically switching between them would not be appropriate.

Use of `urn:mpeg:dash:adaptation-set-switching:2016` is described in the [DASH-IF Guidelines](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf).

**Comment by peterlisak** [comment]
Ok, thanks. It seems it solved one part of our problem. After injecting `urn:mpeg:dash:adaptation-set-switching:2016` to manifest, it seems auto switching is working now. 

Another part of issue is that when player/device is not complying with DRM license for one of `AdaptationSet` (for example because security level 1 or HDCP is not supported by device), it still tries to switch to that and playback fails. Shouldn't player be signalled by CDM about eligibility to play those `AdaptationSets`?

Or maybe we just have wrong expectations. What is the proper approach to use multi key protected DASH with exoplayer? 

Thank you.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/4825. Short summary:

* Ideally a player would do what you're suggesting, yes
* Unfortunately, Android did not contain platform APIs to support this prior to API level 23
* We plan to implement what you're suggesting for API level 23 and above, and this is what the referenced issue is tracking. That said, we are not yet considering this high priority. The vast majority of apps are still targeting older API levels as well. For as long as this is true developers will unfortunately need to implement their own solutions for this problem, and where developers are having to do this they may as well use the solutions they come up with for newer devices as well (they'll probably also be a bit more efficient than what the player will be able to do internally). ExoPlayer doing the right thing on API level 23 and above only really starts to provide significant value when a significant number of app developers have their minimum API level set to 23 or higher

Closing, since the first part is solved, and the second part is tracked by https://github.com/google/ExoPlayer/issues/4825.
