### ISSUE TITLE
video lose some frames but audio still be played correctly

### ISSUE THREAD

**Issue by ubo5** [google/ExoPlayer#6419]
#6387 # 
### Issue description
When I use exoplayer to play serveral vidoes, found that some videos could lose some video info 
but audio still got played.
Below is two picture to describe this situation clearly. Picture one is the video(I will give a link later) played using potplayer, picture two is the video played using exoplayer.If you may pay attention to the timeline in the 2 pictures, you will find that in exoplayer lose about some frames about a few seconds, but it does not affect the audio.
pic1
![1](https://user-images.githubusercontent.com/45504451/64690623-71889b00-d4c3-11e9-99bc-091745ab1e9d.PNG)
pic2
![2](https://user-images.githubusercontent.com/45504451/64690718-a7c61a80-d4c3-11e9-87ac-9399bae6b40a.PNG)
ge.png…]()

### Reproduction steps
To reproduce this, you can use the video link which I will give a link and the example project demo module. I just change the default content json in the assets to insert my video info.
```
 {
        "name": "local (MP4,H264)",
        "uri": "url_to_the_video",
        "extension": "mp4"
  },
```

### Link to test content
I put the video on my google driver
https://drive.google.com/file/d/1D22xzbsNq8SMoxyNcxQFPjXTybQdW9qS/view?usp=sharing

### Version of ExoPlayer being used
I tried 2.9.6 and the lateset exoplayer example project

**Comment by ojw28** [comment]
The media seems to explicitly contain an edit list indicating that the start of the video should not be played. If another player is playing it "correctly", then it's likely just because that player doesn't support MP4 edit list functionality.

The problem here is the media (i.e. why does it contain an edit list at all?). So I would suggest you fix it, if it's media you control. That said, if you want to disable edit list functionality in ExoPlayer, then you can do so by creating the `ProgressiveMediaSource` for playback like this:
```
return new ProgressiveMediaSource.Factory(dataSourceFactory,
    new DefaultExtractorsFactory()
        .setMp4ExtractorFlags(Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS))
    .createMediaSource(uri);
```
where use of **FLAG_WORKAROUND_IGNORE_EDIT_LISTS** disables the functionality. If you do this, the video plays as you'd expect.

**Comment by ubo5** [comment]
@ojw28 thanks! The media is the problem.  I have no idea about `edit list` before this, will have a look about it.
Here is a version can used in 2.9.*(since `ProgressiveMediaSource` added in 2.10.0)
And another useful link: [exoplayer doc troubleshooting](https://exoplayer.dev/troubleshooting.html#why-do-some-mp4fmp4-files-play-incorrectly)
```
DataSource.Factory dataSourceFactory =
                new DefaultDataSourceFactory(mCtx, 
                    mCtx.getResources().getString(R.string.app_name));

return new ExtractorMediaSource.Factory(dataSourceFactory).
    setExtractorsFactory(
        new DefaultExtractorsFactory()
        .setMp4ExtractorFlags(Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS)
    ).createMediaSource(uri);
```
