### ISSUE TITLE
Player stops in looping video

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6421]
### [REQUIRED] Content description
The player goes into STATE_BUFFERING after 1.5 minutes playing.
VLC plays this content fine.

### [REQUIRED] Link to test content
http://77.72.80.16/http-progressive/29

### [REQUIRED] Version of ExoPlayer being used
2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
STB Geniatech 495X (chip Amlogic s905x)
Android 6.0.1

### [REQUIRED] A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/3600868/bugreport.txt)

**Comment by ojw28** [comment]
When streaming MPEG-TS, we'd generally expect timestamps to increase over time, except in the case where they roll over due to overflow of the 33 bit MPEG-TS timestamp field. For the stream provided there's an unexpected discontinuity in the timestamps that's unrelated to overflow of the 33 bit field, which I assume happens at the point where the video loops.

I guess we could look at handling arbitrary timestamp discontinuities, but this seems like a really strange use case. I can't think of a good reason for live streaming a looping video, when you could just provide the video as a regular MP4 and have the client loop do the looping. One fairly major benefit of doing it that way is that it allows the video to be cached, both on the client or in the edge cache servers of a CDN.

Even if you do want to live stream content that contains timestamp discontinuities, there are alternatives such as HLS and DASH that support properly signalling when discontinuities occur to the client, rather than the approach used here which seems to just concatenate the content together in the hope the client will handle it.

I'm going to close this because I don't think it's worth the time investment to handle this case any better. If you can think of a valid use case where streaming video in this way would be a good option, please reply here and we can reconsider!
