### ISSUE TITLE
 Is it possible to download PDF files with CacheDataSourceFactory?

### ISSUE THREAD

**Issue by matheusbrandao** [google/ExoPlayer#6448]
For example, I have an application that caches audios and videos for offline studies, and would like to use the "same logic" for PDF files. It's possible?

**Comment by tonihei** [comment]
The downloader for progressive files (like the one you'd use for an mp4 file) is not making any assumptions about the file contents. So, yes, downloading the PDF file into the ExoPlayer cache would work. 

The question is - how do you plan to use it afterwards? The cache is build for playback and the only sensible way to read the contents of the file is to use a `CacheDataSource`. So unless you have a PDF reader/viewer that can use ExoPlayer's `DataSource` as an input, it's difficult to retrieve. You may be able to wrap the `CacheDataSource` with an `DataSourceInputStream` and I guess it may be possible to display the PDF using an `InputStream`. Note that we can't provide any more advice on customizations like that because it goes beyond media playback.

**Comment by matheusbrandao** [comment]
Hey man. 

That is exactly the point. I saw that it was possible to download, but did not know how to consume the content.

But thanks to your tip, I was able to do it with `DataSourceInputStream`. Thank you very much.
