### ISSUE TITLE
Play from source which is still downloading

### ISSUE THREAD

**Issue by muz786** [google/ExoPlayer#6453]
Hi,

I wanted to avoid the bottleneck to wait 4 5 seconds before a video starts to stream using the URL on devices with slower internet connection.
To solve the problem, I started downloading the video in advance on app load. On video screen I gave the path to the local video file which is still downloading but it does not play and give the error EOF exception.To summarize the video cannot play until the whole file is downloaded.

I looked at the mp4 structure and figured that the metadata of mp4 file is at the end of file by default so I also tried by reconfiguring the video encoding to place this metadata at the start of the file using ffmeg but still it did not work.

Is there any way to avoid the EOF exception on video file that is still downloading in progress?

Any help will be highly appreciated.

**Comment by tonihei** [comment]
Downloading content to a file and playing it at the same time doesn't work because the player doesn't know that the file is incomplete and may easily read faster than the download is progressing. So even if the metadata of the file is at the beginning, you man run into EOF exceptions. 

Instead, you should use ExoPlayer's download classes to ensure the data is written to a cache ExoPlayer can understand and also to ensure that the player is reading the data directly over network is needed.  See the [downloading documentation](https://exoplayer.dev/downloading-media.html) and also #6204 for a similar question about downloading and playing at the same time.
