### ISSUE TITLE
How to start exoplayer in landscape mode?

### ISSUE THREAD

**Issue by sonahovhannisyan** [google/ExoPlayer#6461]
Is there a way to start ExoPlayer in landscape mode without loosing rotation functionality ?

**Comment by icbaker** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Are you using the ExoPlayer [UI components](https://exoplayer.dev/ui-components.html)?

**Comment by ojw28** [comment]
I'm not sure at all whether it's the best way, but I suspect you can achieve this with a combination of `Activity.setRequestedOrientation` and [OrientationEventListener](https://developer.android.com/reference/android/view/OrientationEventListener.html).

This doesn't seem like an ExoPlayer specific issue; I think the same question could apply to an `Activity` containing any other type of content as well. If so, you may have more luck asking on StackOverflow, since we're not particularly expert on Android UI development.

**Comment by sonahovhannisyan** [comment]
Thank you guys for the answer and sorry for my late response. Unfortunately achieving this with using activity's orientation setting resulted to loose the rotation functionality later, which was the reason I was curious if ExoPlayer could offer similar functionality from inside it's engine. But I ended up with just hardcoding the orientation in landscape mode, which is good for now. So I'm closing this ticket. Thanks a lot for the help.
