### ISSUE TITLE
Can we add an ad  after the video is ended by ima.

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#6479]
### [REQUIRED] Question
Now i can add an ad before the video is played.
Can we add an ad after the video is ended. 
If we can, What do I need to do about it?

### Link to test content
In case your question is related to a piece of media, which you are trying to

**Comment by andrewlewis** [comment]
If you want to play a postroll ad it should be included in the VMAP ad tag and will be played automatically.

If you are trying to do something different please describe it in more detail.

**Comment by lsgfly** [comment]
In the demo-ima, the ad always played before the video is played.
How should I change the code so that the advertisement can be played after the video ended?

**Comment by andrewlewis** [comment]
Using a VMAP ad tag with a postroll is the only way to do this with the IMA extension at the moment, I'm afraid. We always play plain VAST ad tags as prerolls. Last time we discussed this limitation we decided not to give flexibility to choose where to play the ad because VMAP ad tags already support this use case.
