### ISSUE TITLE
Video 360 problem

### ISSUE THREAD

**Issue by nbabaka** [google/ExoPlayer#6480]
Hi there.

Content - Any 360 Video. STEREO_MODE_MONO
Android 6.0 Marshmallow
ExoPlayer - 2.10.5

Video 360 starts playing from a different angle of view each time. 
Than X & Y axles slowly rotate in normal position, but not Z.
Is it possible to start video depends on sensor position and look forward to the "start" position?

Thank you/

**Comment by kjh9765** [comment]
What class did you use to move the video up and down?

**Comment by andrewlewis** [comment]
I'm not sure I understand what the bug is here, but you could try using `TYPE_ROTATION_VECTOR` in [`SphericalGLSurfaceView`](https://github.com/google/ExoPlayer/blob/656556b/library/ui/src/main/java/com/google/android/exoplayer2/ui/spherical/SphericalGLSurfaceView.java#L89) (on the dev-v2 branch) instead of `TYPE_GAME_ROTATION_VECTOR`. If that doesn't help, please could you describe in more detail what behavior you see and what you expect? Thanks.
