### ISSUE TITLE
Delete next and previous buttons from the Notification

### ISSUE THREAD

**Issue by obadajasm** [google/ExoPlayer#6491]
Hello ExoTeam

Can we delete the next and previous buttons?
So in Total it only shows two buttons the Play and Stop

In this issue [#5344]  we could add more buttons and make them functional to the PlayerNotificationManager

(https://github.com/google/ExoPlayer/issues/5344) 
![IMG_20191001_012557](https://user-images.githubusercontent.com/38117091/65921295-841f3180-e3ea-11e9-866e-ef9e175cc7ae.jpg)

**Comment by marcbaechinger** [comment]
Yes, you can use [setUseNavigationActions(boolean useNavigationActions)](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L741) to determine whether the next and previous actions are included in the notification.

**Comment by ojw28** [comment]
Rather than adding documentation, we will instead aligned `PlayerNotificationManager` with our other UI components by allowing enabling/disabling "next" and "previous" separately. This will also get "next" and "previous" into the method names, which should make them easier to find! Removing the `documentation candidate` tag.
