### ISSUE TITLE
Playback with adaptive video and adaptive audio

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#6497]
I have been trying to find this information but only found one case here from 2 years ago and it's not clear the current status as it was closed.

I'm playing a SS+PR stream with Exoplayer, both video and audio are adaptive with a few profiles each.
Video is adapting properly.
Audio is not adapting at all, it stays in the same profile all the time.

Is that a known limitation in Exoplayer? Any plan to improve that?

If so, what's the recommended way of handling that before is officialy added to Exoplayer?
Select one stream at the beginning of the playback and keep playing it? How can that be done?

How can that be handled when part of the audio profiles are stereo and part 5.1? Can 5.1 be played in a stereo device?

Will it make any difference to use DASH instead of SS?

Android Tv 7.1.1
Exoplayer 2.10.2
Streams: Smooth Streaming + Playready

**Comment by tonihei** [comment]
> Any plan to improve that?

Parallel adaptation of both video and audio is already tracked by #5111. We are currently running experiments to verify the impact on performance metrics before making this the default.

If you want to try it out yourself, you can use `DefaultTrackSelector.experimental_allowMultipleAdaptiveSelections()` to turn the feature on. Note that this is just an experimental flag so far and will be renamed or removed in future versions.

> How can that be handled when part of the audio profiles are stereo and part 5.1? Can 5.1 be played in a stereo device?

The `DefaultTrackSelector` will never select tracks that are not supported by your device. So the 5.1. tracks will only be part of a selection if they can actually be played. Also, by default, we won't allow adaptation between different channel counts (i.e. stereo and 5.1) because there may be an audible discontinuity when we switch formats. But you can explicitly allow this by setting `DefaultTrackSelector.Parameters.allowAudioMixedChannelCountAdaptiveness` to true.

> Will it make any difference to use DASH instead of SS?

No.
