### ISSUE TITLE
No CEA608 closed captions on HLS streams.

### ISSUE THREAD

**Issue by ddv2005** [google/ExoPlayer#6499]
Hello,

I have HLS stream that has CEA608 CC but player doesn't expose any Text tracks because no CC decoder created. DefaultHlsExtractorFactory has workaround for that case in createTsExtractor but it does not work because muxedCaptionFormats just empty but not null. 

[patch.txt](https://github.com/google/ExoPlayer/files/3677896/patch.txt)

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

We can't do anything without the media.

**Comment by AquilesCanta** [comment]
Once you provide a stream for us to test this, I will reopen the issue.

**Comment by ddv2005** [comment]
**### [REQUIRED] Issue description**
No CEA608 closed captions on HLS streams

**### [REQUIRED] Reproduction steps**
Open HLS stream http://51.77.66.11/index.m3u8 in any ExoPlayer2 app. Player doesn't expose any Text tracks because no CC decoder created. DefaultHlsExtractorFactory has workaround for that case in createTsExtractor but it does not work because muxedCaptionFormats just empty but not null.

**### [REQUIRED] Link to test content**
http://51.77.66.11/index.m3u8

**### [REQUIRED] Version of ExoPlayer being used**
2.9.6

**Comment by AquilesCanta** [comment]
The issue is that the manifest is explicitly declaring 

`#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE...`

As per spec, ExoPlayer assumes no ClosedCaptions:

```
      If the value is the enumerated-string value NONE, all EXT-X
      -STREAM-INF tags MUST have this attribute with a value of NONE,
      indicating that there are no closed captions in any Variant Stream
      in the Master Playlist
```

Also relevant reads:
https://medium.com/google-exoplayer/hls-playback-in-exoplayer-a33959a47be7
https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6
 #6283

If you want to work around this, you might want to inject your own playlist parser which removes or fixes the closed caption tag.
