### ISSUE TITLE
Custom build type fails provisioning for DRM

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6533]
### [REQUIRED] Searched documentation and issues
exoplayer.dev
GitHub issues
Various javadocs

### [REQUIRED] Question
I created a custom build type for my builds such that I can run DRM side-by-side with our market version for testing purposes, so I did the following in our `build.gradle.kts`:
```
create("custom") {
    applicationIdSuffix = ".custom"
    signingConfig = signingConfigs.getByName("debug")
    matchingFallbacks = listOf("debug")
}
```

This somehow results in the app not being provisioned for DRM. If I change the `applicationIdSuffix` to `debug` or `release`, then everything works as expected.

Is there any way to get the app provisioned for DRM with a build type not being debug or release?

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by kgrevehagen** [comment]
**Update:** I got it working by running the code that is in `executeProvisionRequest()` in the `HttpMediaDrmCallback`. I have a custom DrmMediaCallback, that's why this didn't run by default.

So, the question still remains, is this expected behavior, that it should not work without provisioning manually when we have something other than debug or release build type?

Also, are there other cases where the app/device might not be provisioned? I guess it's safe to have this provision request either way? I'm just afraid of having this code in production if I'm not sure when it will be called, if it will be called at all.

**Comment by ojw28** [comment]
It sounds like your `MediaDrmCallback` implementation just didn't implement provisioning correctly, and now you've fixed it so that it does? Your implementation is required to implement provisioning correctly.

The rules for when provisioning occurs are somewhat complicated, since they vary by device and Android version. On some devices provisioning wont ever be requested because they'll have been provisioned in the factory. On some devices a provisioning request only needs to occur once across all apps (i.e. once one app has provisioned the device, no further provisioning requests will occur either for that app or any other app). On some devices provisioning is per app.

I suspect that your test device falls into the final category, that your app was broken for all build types, and that the device had already been provisioned for your normal build types by some previous version of your app. If you were to do a full factory reset of the test device and then install your normal build, with your custom `DrmMediaCallback` that did not implement provisioning correctly, then I suspect you will/would see failures in that case too. Does that make sense?

**Comment by kgrevehagen** [comment]
This makes perfectly sense, thanks for explaining.
Since I never needed to do provisioning, I thought I could get away with implementing it, but I guess all implementations should have it in place.
