### ISSUE TITLE
How to Clear Buffered Resources when HLS Switches Different Orbits

### ISSUE THREAD

**Issue by lifawei** [google/ExoPlayer#6546]
How to Clear Buffered Resources when HLS Switches Different Orbits？I called Util.removeRange (mediaChunks, chunkIndex, mediaChunks.size ()) in the HlsSampleStreamWrapper.reevaluateBuffer () method, which triggers AudioTrack: Discontinuity detected [expected 55024000, got 15002666].

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found here. If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

We won't be able to respond or help unless the issue is formatted as described above. We need more information.

**Comment by tonihei** [comment]
`reevaluteBuffer` is not yet supported in HLS. There is an enhancement to track this in #6322.
