### ISSUE TITLE
The stream which width/height are not aligned with VideoCapabilities.mWidthAlignment/VideoCapabilities.mHeightAlignment can't be played.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6551]
### [REQUIRED] Issue description
As described in #https://github.com/google/shaka-streamer/issues/36. If the HLS live output stream's resolution is 1129 * 480,  the player can't played it.  
The decoder's capabilities are not support the width/height which not aligned with `VideoCapabilities.mWidthAlignment / VideoCapabilities.mHeightAlignment`. 

```
/MediaCodecInfo: NoSupport [sizeAndRate.support, 1129x480x-1.0] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [kungfupanda, MiBOX3_PRO, Xiaomi, 22]
```

Device info: MiBOX3_PRO, Xiaomi
```
capabilities_OMX.MTK.VIDEO.DECODER.AVC: 
[
        requestedMimeType=video/avc, 
        mimeType=video/avc, 
        profileLevels=[
                    [profile=1, level=1],  [profile=1, level=2],  [profile=1, level=4],  [profile=1, level=8],  [profile=1, level=16],  [profile=1, level=32], 
                    [profile=1, level=64], [profile=1, level=128], [profile=1, level=256], [profile=1, level=512], [profile=1, level=1024],  
                    [profile=1, level=2048], [profile=1, level=4096], [profile=1, level=8192], [profile=1, level=16384], [profile=1, level=32768], 
                    [profile=2, level=1], [profile=2, level=2], [profile=2, level=4], [profile=2, level=8], [profile=2, level=16], [profile=2, level=32], 
                    [profile=2, level=64], [profile=2, level=128], [profile=2, level=256], [profile=2, level=512], [profile=2, level=1024], 
                    [profile=2, level=2048], [profile=2, level=4096], [profile=2, level=8192], [profile=2, level=16384], [profile=2, level=32768], 
                    [profile=8, level=1], [profile=8, level=2], [profile=8, level=4], [profile=8, level=8], [profile=8, level=16], [profile=8, level=32], 
                    [profile=8, level=64], [profile=8, level=128], [profile=8, level=256], [profile=8, level=512], [profile=8, level=1024], 
                    [profile=8, level=2048], [profile=8, level=4096], [profile=8, level=8192], [profile=8, level=16384], [profile=8, level=32768]
        ], 
        videoCapabilities=[
                    bitrateRange=[1, 300000000], 
                    heightAlignment=2, 
                    widthAlignment=2, 
                    supportedWidths=[64, 1920], 
                    supportedHeights=[64, 1088], 
                    supportedFrameRates=[0, 960]
        ],
        colorFormats=[19, 2135033992, 2130706433], 
        FEATURE_AdaptivePlayback
]
```
```
MediaCodecVideoRenderer.java
protected int supportsFormat(MediaCodecSelector mediaCodecSelector,
      DrmSessionManager<FrameworkMediaCrypto> drmSessionManager, Format format)
      throws DecoderQueryException {
      ........
}
```
If I manually reset the resolution to align with `VideoCapabilities.mWidthAlignment / VideoCapabilities.mHeightAlignment` in above function.  e.g. reset width:1129 to 1130 or 1128. The decoder is able to play the format.  I don't know whether fix the problem like this is reasonable. 

### [REQUIRED] Reproduction steps
The content I has sent to you to [dev.exoplayer@gmail.com.](url)

**Comment by ojw28** [comment]
I think it's a property of H.264 itself that odd resolutions are not supported. In which case 1129 in not a valid width, and so it's correct that the decoder (or any decoder, for that matter) would not advertise support for it.

I think the problem here is just that the RESOLUTION tag in `hls.m3u8` is incorrect. The real width of the stream is 1130, as seen if you inspect the actual media using a tool like `mediainfo`:

```
> mediainfo video_480p_2M_init.mp4
[...]
Width                                    : 1130 pixels
Height                                   : 480 pixels
[...]
```

**Comment by ojw28** [comment]
So this is an error in the source media. If it's your media then you should fix it [edit: I just saw your shaka bug. If they're responsible for generating `hls.m3u8` then it seems like a bug in their packager?].

I think we've seen the same issue before, so we might put a workaround into ExoPlayer that'll round odd H.264 resolutions up to the nearest even resolution. Note that this assumes the error in the source media is a rounding error. Let's use this issue to track deciding whether we want to do this.

**Comment by Romantic-LiXuefeng** [comment]
@ojw28 I use the Bento4 mp4info to dump the video_480p_2M_init.mp4.   It's  sample width is 1130, and display width is 1129.
`./mp4info --verbose video_480p_2M_init.mp4v`

```
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    90000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 0.000 Kbps
    sample count with fragments: 0
    duration with fragments:     0
    duration with fragments:     0 (ms)
  display width:  1129.411743
  display height: 480.000000
  Sample Description 0
    Bytes: 000000000000000100000000000000000000000000000000046a01e000480000004800000000000000010a41564320436f64696e670000000000000000000000000000000000000000000018ffff00000034617663430142c01fffe1001d6742c01fda011c3de4fff078007811000003000100000300300f1832a001000468ce3c8000000010706173700000078000000781
    Coding:      avc1 (H.264)
    Width:       1130
    Height:      480
    Depth:       24
    AVC Profile:          66 (Baseline)
    AVC Profile Compat:   c0
    AVC Level:            31
    AVC NALU Length Size: 4
    AVC SPS: [6742c01fda011c3de4fff078007811000003000100000300300f1832a0]
    AVC PPS: [68ce3c80]
    Codecs String: avc1.42C01F
```

**Comment by kqyang** [comment]
@ojw28 I believe there is another bug in ExoPlayer. 

The resolution in HLS master playlist is the "display" resolution. See https://tools.ietf.org/html/rfc8216#section-4.3.4.2.1:

>    If an EXT-X-STREAM-INF tag contains a RESOLUTION attribute and a
      VIDEO attribute, then every alternative video Rendition MUST have
      an optimal display resolution matching the value of the RESOLUTION
      attribute.

The display resolution is not the same as frame resolution (a.k.a storage resolution or codec resolution) for non square pixels. 

As shown in https://github.com/google/ExoPlayer/issues/6551#issuecomment-542713388, the content has a frame resolution of 1130:480 and a display resolution of 1129:480. 

The player should use frame resolution instead of display resolution when querying video capabilities as frame resolution is what decoder cares. 
 - For mp4 files, frame resolution can be extracted from width and height in Sample Description box.
 - For TS files, the player has to inspect SPS to extract the frame resolution.

**Comment by ojw28** [comment]
It's unfortunate that the HLS specification has defined it that way...

> The player should use frame resolution instead of display resolution when querying video capabilities as frame resolution is what decoder cares. For mp4 files, frame resolution can be extracted from width and height in Sample Description box. For TS files, the player has to inspect SPS to extract the frame resolution.

It's infeasible to implement this efficiently, since it would require downloading the start of every variant prior to the start of playback. The increased latency doesn't seem like an acceptable tradeoff, so I think it's better to leave things as they are now. Note that the commit referenced above should solve the problem in practice unless the display and frame resolutions are significantly different, which is not something we've seen in practice.
