### ISSUE TITLE
Render lag when seeking

### ISSUE THREAD

**Issue by Samuel-Isirima** [google/ExoPlayer#6559]
I am writing a project that requires me at some point to do some seeking in quick succession. Problem is that the video freezes all through the seek period or sometimes, renders a few screens and then freezes while the seekbar and current time text get updated correctly. I already tried this project on desktop, with java and javafx and it works perfectly, so I think it is a problem with exoplayer's seeking system.

I'm using exoplayer version 2.10.5 and testing on a real device.

Is there any way around this?

**Comment by Samrobbo** [comment]
Hi

From the information you've provided, it's difficult for us to assist. 

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Once you've done this, we will be more capable of helping.

**Comment by tonihei** [comment]
Based on the information provided, it just looks as if your issue is caused by the fact that ExoPlayer loads the video over network and so every seek needs to load new data before playback can continue. Desktop players are likely to preload the entire video as the memory constraints are not as tight as on a phone and thus seeking will be very fast. You can start downloading the video before playback using the instructions at https://exoplayer.dev/downloading-media.html. The player can the read the data from disk and seeking should be pretty fast. If you are already reading from a local file, please clarify your expectations.

**Comment by Samuel-Isirima** [comment]
I'm playing an mp4 video file. I'm trying to seek randomly for a feature in my project, in quick succession.
```
runnable = new Runnable() {
                                @Override
                                public void run() {
                                   if(player.getCurrentPosition() != 0){
                                    handler.removeCallbacksAndMessages(null);
                                        player.seekTo(player.getCurrentPosition() + randPosition());
                                        handler.postDelayed(this,300);
                                    }
                                }
                            };
handler.postDelayed(runnable,0);
```
This is what I get on the run Console.

I/art: Background sticky concurrent mark sweep GC freed 1977(82KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 23MB/24MB, paused 993us total 199.149ms
I/art: Background partial concurrent mark sweep GC freed 6340(295KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 24MB/40MB, paused 1.204ms total 163.901ms.

Seeking in quick succession with as much as 300ms between seeks causes a lag in the video rendering while the seekbar and playback time text get updated correctly.

**Comment by tonihei** [comment]
That still doesn't clarify whether you are playing a local file or over network :) 

It would be helpful if you clarify your expectations too. If you are seeking to different positions every 300ms, what do you expect to see for video, or hear for audio? It may be that the seeks are currently overlapping and the player will only show a video frame for last received seek (under the assumption that the user intention changed).

**Comment by Samuel-Isirima** [comment]
I am playing a local file from the raw folder.
I expect the video scene for the current position after each seek to render.

**Comment by tonihei** [comment]
> I expect the video scene for the current position after each seek to render.

That probably doesn't work as such because if the seeking takes longer than your delay, the difference between seek and frame display will grow over time.

For example, imagine you issue a seek every 300ms and the seek takes 900ms to complete. Then you get:
time 0: seek (1)
time 0.3: seek (2)
time 0.6: seek (3)
time 0.9: seek (4), display (1)
time 1.2: seek (5),
time 1.5: seek (6)
time 1.8: seek (7), display (2)
....
time 12.6: ... display (7)

It sounds as if you'd like to see some frames while doing fast repeated seeking, right? Not necessarily all frames, but some of them would be fine? If so, you can wait for a frame to be rendered before issuing another seek command. The simplest way is to wait until the player state changes back to `STATE_READY`:
time 0: seek (1)
time 0.3: no seek, but save position (2)
time 0.6: no seek, but save position (3)
time 0.9: no seek, but save position (4), display (1)
time 1.0: STATE_READY -> seek to last saved position: seek(4)
time 1.3: no seek but save position (5)
time 1.6: no seek but save position (6)
time 1.9: no seek but save position (7), display (4)
time 2.0 STATE_READY -> seek to last saved position: seek(7)
.. and so on. 

This way you get a timely display of the some frames, but a lot of the seeks are just dropped.
