### ISSUE TITLE
Drm videos not playing in lollipop Widevine “cenc”

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#6568]
### I'm getting this error.

**ExoPlayerImplInternal: Source error. com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403**

ExoPlayerImpl: Init 7d4d5e1 [ExoPlayerLib/2.10.4] [generic_x86_64, Android SDK built for x86_64, unknown, 23]

Above Lollipop it's playing below they are not playing

**Comment by krocard** [comment]
Which scheme is your Widervine CENC content using? 
Widevine CENC; “cbcs”, “cbc1” and “cens” schemes are only supported on API 25 and above.

See https://exoplayer.dev/supported-devices.html

If you are using the Widevine CENC; "cenc" sheme, it should be supported on Lolipol. If not so, is the URL of the video public ? If so, could you post it here? Alternatively, email it to dev.exoplayer@gmail.com.

**Comment by AquilesCanta** [comment]
My 2 cents: We shouldn't get to a 403 if the device is attempting to play a non supported drm scheme, since track selection should detect it beforehand. This is most likely an authentication issue with your app, but it's impossible to say due to lack of information. I'd suggest you provide all information required in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), for us to look at it. But this is most likely a license [server-side issue](https://en.wikipedia.org/wiki/HTTP_403).

**Comment by gokulkalagara** [comment]
thanks, @AquilesCanta, but I have a small doubt why it is playing in above lollipop devices

**Comment by AquilesCanta** [comment]
Under the assumption you are using the exact same code and configuration for all android versions, Is it possible that your server is not granting access to the lollipop UserAgent?

It's pretty easy to test this: When creating HttpDataSource.Factory you pass to HttpMediaDrmCallback that you inject in the DefaultDrmSessionManager, use the same user agent you are using in newer android versions. This would be my best guess.
