### ISSUE TITLE
Can't play widevine drm content with demo-cast app

### ISSUE THREAD

**Issue by hermasyp** [google/ExoPlayer#6571]
Hello Exoplayer team, I've been try to play widevine content by adding drm scheme and drm license url to the DemoUtil.java like this. 

    samples.add(
        new Sample(
            "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears.mpd",
            "Example DRM",
            MIME_TYPE_DASH,
            C.WIDEVINE_UUID,
            "https://proxy.uat.widevine.com/proxy?provider=widevine_test"));

But It cannot be played, is that any step that I missing to play drm content by chromecast ?

**Comment by AquilesCanta** [comment]
Please try the dev branch and reach back.

**Comment by hermasyp** [comment]
hello @AquilesCanta , I try with dev-v2-r2.10.6. same result here. still can't play drm content

**Comment by hermasyp** [comment]
sorry, I changed into dev-v2 branch. and the sample works ! may I know when it will release ? @AquilesCanta

**Comment by AquilesCanta** [comment]
Not sure, I can't provide any timelines. Maybe @ojw28 can. The summary for this issue is:

If you need the cast extension to play DRM-protected content on 2.10.X, you should use the app id that appears in the [dev-branch's DefaultCastOptionsProvider](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/DefaultCastOptionsProvider.java).

This should be fixed in 2.11.X.
