### ISSUE TITLE
Detect DTS changes

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6572]
### [REQUIRED] Searched documentation and issues
Search by keyword 'DTS'

### [REQUIRED] Question
How to detect changes in DTS (decoding time stamp)? The listener or something else.

I need this for my other issue https://github.com/google/ExoPlayer/issues/6421

**Comment by ojw28** [comment]
This is not something we support. As stated in the other issue, the use case seems very unusual. If you really do want to live stream a looping video, then there are multiple standard compliant ways of doing so, including:

* Using HLS with `EXT-X-DISCONTINUITY` tags to indicate where discontinuities are in the stream.
* Using DASH with multiple `Period` elements to indicate where discontinuities are in the stream.
* Using TS and transcoding the stream into the container on-the-fly to ensure the timestamps only wrap due to overflow of the 33 bit MPEG-TS timestamp field.

Without good justification of why we should support the use case described, I don't think we can justify spending time on it. Sorry.

**Comment by tipoc123** [comment]
But I just want to log current DTS (decoding timestamp) value. Do you know where I can find it?

**Comment by ojw28** [comment]
It's not something that we really intentionally expose anywhere. You might be able to inject a custom `TimestampAdjuster` into a `TsExtractor` to intercept (and possibly even correct) the timestamps. This is not something we can provide detailed guidance on however.

**Comment by AquilesCanta** [comment]
I think the better way would be injecting your own `PesReader` using `TsPayloadReader`. 

I don't think the timestamp adjuster differentiates between PTS and DTS (could be wrong).

**Comment by tipoc123** [comment]
> I think the better way would be injecting your own PesReader using TsPayloadReader.

@AquilesCanta, thank you so much!
