### ISSUE TITLE
Searched too many bytes while resynchronizing.

### ISSUE THREAD

**Issue by mladenrakonjac** [google/ExoPlayer#658]
This is my code. I don't understand what I am doing wrong? 

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

       exoPlayer = ExoPlayer.Factory.newInstance(1);

        transferListener = new TransferListener() {
            @Override
            public void onTransferStart() {

            }

            @Override
            public void onBytesTransferred(int bytesTransferred) {

            }

            @Override
            public void onTransferEnd() {

            }
        };

        final Uri uri = Uri.parse("http://37.187.90.121:3474/;stream.mp3");

        mp3Extractor = new Mp3Extractor();
        dataSource = new DefaultUriDataSource(getApplicationContext(), "musicStream");
        sampleSource = new ExtractorSampleSource(uri, dataSource, mp3Extractor, 1, BUFFER_SIZE);
        MediaCodecAudioTrackRenderer audioRenderer =
                new MediaCodecAudioTrackRenderer(sampleSource, null, true);
        exoPlayer.prepare(audioRenderer);

  
    }

and I got this:

com.google.android.exoplayer.ParserException: Searched too many bytes while resynchronizing.

**Comment by ojw28** [comment]
When you're building your ExtractorSampleSource, I think you're passing 1 as the requested buffer size, and BUFFER_SIZE as the requested retry count. A buffer of 1 byte is obviously too small, which is why you end up with the error. The arguments to this constructor changed in an unfortunate way between releases, so that might be why this has happened, sorry!

Note that the constructor you're calling is also deprecated. Please update to use one of the non-deprecated ones, and use the demo app as a guide for how to do so. This should hopefully resolve your problem!

**Comment by eudson** [comment]
I used the demo app to guide me, but times to times this error appears in the console. I'm using exoplayer 2 dev experimental

**Comment by andrewlewis** [comment]
@eudson Please file a new issue with full steps to reproduce via the demo app, including a link to the media you're trying to play. Thanks.
