### ISSUE TITLE
CastPlayer should report Shuffle is disabled

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#6582]
### Use case description
When switching from ExoPlayer to CastPlayer, I have an UI inconstancy on the Shuffle state when ExoPlayer was shuffle enabled.
The UI is still reporting that CastPlayer queue is shuffled.

### Proposed solution
in CastPlayer::updateInternalState() add something like
`notificationsBatch.add(new ListenerNotificationTask(listener -> listener.onShuffleModeEnabledChanged(false));`

**Comment by AquilesCanta** [comment]
I don't really see how this can happen. 

CastPlayer doesn't currently support shuffle mode. Plus player control view seems to update the button state accordingly. The notification is not necessary because it should never change. 

Can you state exactly what's going on? Perhaps provide a set of minimal changes to reproduce in the demo app?

**Comment by loki666** [comment]
maybe I should have added that I'm using the mediasession extension.
My UI is observing the MediaController shuffleMode.

When i switch from ExoPlayer (with shuffle enabled) to CastPlayer, the shuffleMode of the MediaController is not set to false, because CastPlayer doesn't report it through the onShuffleModeEnabledChanged() method

**Comment by tonihei** [comment]
Looks as if the shuffle mode (`mediaSessionCompat.setShuffleMode`) needs to be reset when changing player implementations.

**Comment by loki666** [comment]
looks good
