### ISSUE TITLE
Are Amazon FireOS devices now supported in Google Exo ?

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#6584]
### [REQUIRED] Searched documentation and issues
Looked in forums, and release notes. Just needing confirmation since Amazon is again planning on porting 2.10.6.
Google Exo 2.8.3 indicates "Improved compatibility with FireOS"

### [REQUIRED] Question
Are Amazon FireOS devices now supported in Google Exo ? Amazon hasn't ported Google Exo since 2.10.1 and the test FireOS devices that we tested Google's Exo, worked.
So the question is more about, are the Amazon FireOS support now part of Google's Exo or should we continue to wait for Amazon ports ?

Thanks

Note: Our current production apps are on Amazon port of Exo 2.9.6. We are planning on updating to 2.10.6 for our next release along with the latest DAI sdk (3.14.0)

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by krocard** [comment]
From: https://exoplayer.dev/supported-devices.html

> **FireOS (version 4 and earlier)**
> Whilst we endeavour to support FireOS devices, FireOS is a fork of Android and as a result we are unable to guarantee support. Device specific issues encountered on FireOS are normally caused by incompatibilities in the support that FireOS provides for running Android applications. Such issues should be reported to Amazon in the first instance. We are aware of issues affecting FireOS version 4 and earlier. We believe FireOS version 5 resolved these issues.

**Comment by krocard** [comment]
It's hard for us to officially support it because we have no control over the underlying platform.

That said, we encourage developers to use our version if it works for them. The Amazon fork is basically identical except for 8 changes they patch on top (https://github.com/amzn/exoplayer-amazon-port/commits).
Those patches are features most apps do not need, or are non-functionial changes (e.g. "change the version string").

Given that most developers choose Exoplayer instead of MediaPlayer because they want media consistency in their developer&user experience, we would recommend staying with the official ExoPlayer release except if you need some features or workarounds provided by Amazons port.
