### ISSUE TITLE
Exoplayer play offline files

### ISSUE THREAD

**Issue by learnyst** [google/ExoPlayer#6585]
### [REQUIRED] Searched documentation and issues
Tell us where you’ve already looked for an answer to your question. It’s
important for us to know this so that we can improve our documentation.

_I have searched in exoplayer docs and also in stackoverflow. Also checked some of the issues raised_

### [REQUIRED] Question

_We are using DASH for adaptive streaming. Our users can download the DASH streams for offline viewing. These DASH streams are NOT downloaded using the exoplayer download feature. These DASH streams are downloaded using external downloader.

Our DASH stream has 3 file. Audio stream, Video Stream and manifest file. These files are available on the local file system in android. 

Queries:
1. How to use exoplayer to play the offline DASH streams (which are not downloaded using the exoplayer downloadmanager)

2. When playing the DASH streams offline, we will not have all the streams. We will have one audio and one video stream. But DASH manifest will have all the streams. How to play offline streams using this manifest? I think exoplayer has force select stream option. Can we use in this case?_

### A full bug report captured from the device
Not a bug. This is general question.

### Link to test content
This is a generic question.

**Comment by tonihei** [comment]
There are multiple ways to filter the streams in a manifest:
1. Select the right track selection options in `DefaultTrackSelector`. You could set a maximum bitrate/resolution for example and also the `forceHighestSupportedBitrate` flag.
2. Filter the manifest using `StreamKey`s. That's what ExoPlayer's download module is doing. The stream keys are basically indices in the manifest that are allowed for playback. You can specify them in  `DashMediaSource.Factory.setStreamKeys`. Have a look at [`DashManifest.copy`](https://github.com/google/ExoPlayer/blob/41b3fc110178e9a5c969a0102c5b074189065273/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifest.java#L173) to see how they are applied to your manifest.
3. Change or build the manifest manually. The `DashMediaSource` allows you the side-load a manifest (by calling `createMediaSource(DashManifest)` in the `Builder` (instead of `createMediaSource(url)`). This way, you can construct a manifest according to your needs from scratch or edit an existing one.

**Comment by learnyst** [comment]
@tonihei thanks.

How can we play the dash stream from the local disk? can we give the file:// url directly to exoplayer? what is the correct way to play the downloaded dash stream?

**Comment by tonihei** [comment]
If you need to update the URLs, you should probably use the implementation described in point (3) above. You can basically build the `DashManifest` object yourself and then pass it to the player. If you want to parse the existing manifest first for easier construction of the new manifest, you can use the `DashManifestParser` to read it from the mpd file.
