### ISSUE TITLE
When playing audio in AAC format, calling getDuration() does not get the total duration.

### ISSUE THREAD

**Issue by HQLIE2018** [google/ExoPlayer#6591]
When playing AAC format audio, calling getDuration() does not get the total duration, and calling seekTo() is also invalid. The version is 2.9.4. How can I solve this problem?

**Comment by tonihei** [comment]
Please provide more detailed information as requested in the issue template. Especially example media and the expectations for the duration would be helpful to debug this any further.

**Comment by HQLIE2018** [comment]
When I play AAC audio, the total duration always returns -9223372036854775807, and I tried several AAC audios.

**Comment by tonihei** [comment]
This value is `C.TIME_UNSET`, the placeholder value that tells you that the duration is (still) unknown. As said above, please provide us with example media if you want us to check if it's media related. Otherwise it sounds as if the duration is just not known yet at the point where you call `getDuration()`. Please listen to `EventListener.onTimelineChanged` to get informed about any updates to the media information.
