### ISSUE TITLE
Playing cenc mp4 in exoplayer

### ISSUE THREAD

**Issue by learnyst** [google/ExoPlayer#6605]
When filing a question:
-----------------------
### [REQUIRED] Searched documentation and issues
I have read exoplayer docs and also searched in stackoverflow and issues

### [REQUIRED] Question
Can we play mp4 files encrypted with cenc in exoplayer? We have used mp4encrypt tool to encrypt mp4 files with method as "MPEG-CENC" and also with KID and KEY(https://www.bento4.com/documentation/mp4encrypt/) . We have not added any other headers like pssh. 

1. How can we play this cenc encrypted mp4 file in exoplayer?
2. Can we use widevine drm for to supply keys for this file?

Please help in playing cenc mp4 file using widevine drm.

### A full bug report captured from the device
Not a defect

### Link to test content
Query

**Comment by ojw28** [comment]
It's not really clear to me exactly what this question is asking. To use Widevine, I think the stream would need to contain a Widevine PSSH atom (or you'd at least need to provide one out of band). You'd presumably also need a license proxy.

**Comment by learnyst** [comment]
@ojw28 We have fragmented mp4 files with are encrypted using bento4 mp4encrypt(CENC encryption). I used FragmentedMp4Extractor and provided drmInitData. With this I am able to play the fragmented mp4 files.

But the fragmented mp4 files dont have sidx. So I am not able to seek. FragmentedMp4Extractor is creating SeekMap.Unseekable streams. If I modify the exoplayer code in seekmap and return true from isSeekable then I am able to seek.

    @Override
    public boolean isSeekable() {
      return true;
    }

Below are my queries:
1. I did not find any way to extend FragmentedMp4Extractor and override isSeekable. Is there any way to do this?
2. If point-1 is not possible, then is the possible to play the fragmented mp4 file as a DASH stream by loading dashmanifest? The fragmented mp4 has both audio and video streams in one file

If both point-1 and 2 are not allowed, then is there a way to make the fragmented mp4 files seekable?

Note: We already have fragmented mp4 files encrypted using cenc with the user. So we need to play fragmented mp4 files.

**Comment by ojw28** [comment]
> If I modify the exoplayer code in seekmap and return true from isSeekable then I am able to seek.

The seek bar may appear to be enabled, but you're not able to seek. Where-ever you move the seek bar, you'll find that it simply seeks back to the start of the stream.

The `sidx` box is what defines the time-to-byte mapping that we need to seek within the stream. If this is not provided, we have no efficient way of determining what byte offset to start from for a given seek position. Hence seeking is not supported if the stream does not contain a `sidx` box.

> If both point-1 and 2 are not allowed, then is there a way to make the fragmented mp4 files seekable?

(1) doesn't fix the problem, as explained above. (2) is not possible because we don't support muxed FMP4 in DASH, and in any case you still need to include a `sidx` box or provide the time-to-byte mapping in the form of a segment timeline in the DASH manifest.

The correct solution is to generate files that contain a `sidx` box, which is what's required for us to efficiently support seeking into FMP4 streams.

**Comment by waqasyousafy** [comment]
where is the solution brothers i am facing the same problem
