### ISSUE TITLE
Notification issues for Android 10 devices.

### ISSUE THREAD

**Issue by abhishekredspace** [google/ExoPlayer#6624]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/6416
https://github.com/google/ExoPlayer/commit/f08258e48d5240624283d787e7f34e0b22b4cd22
https://developer.android.com/about/versions/10/features#media-notifications

### [REQUIRED] Question
Question 1: I am using exoplayer version 2.10.7 to play an audio stream. When audio playback happens we do not show a seek bar and run it as a service with notification attached to it. On Android 10 device, we started seeing a seekbar in the notification. On doing some research, I found your commit with the fix. Though we show them as a live stream(like a radio station) but `player.getDuration` does return a value which is not equal to `C.TIME_UNSET`. So in any case, either it has a duration or not, how can I stop the seekbar to be shown on the notification. 

I tried some code following google docs as well but did not solve the problem. Please help this has become a blocker for our release.

```
val sessionConnector = MediaSessionConnector(mediaSession)
val mediaMetadata = MediaMetadataCompat.Builder().putLong(MediaMetadata.METADATA_KEY_DURATION, C.TIME_UNSET).build()
mediaSession.setMetadata(mediaMetadata)
sessionConnector.setPlayer(exoPlayer)
```        
Question 2: Data on my notification is showing correctly but when I Lock screen, I see No title.
![device-2019-11-06-155002](https://user-images.githubusercontent.com/16784627/68358589-561ac480-00ef-11ea-83b6-ee43c69b902b.png)

### A full bug report captured from the device
NA

### Link to test content
If you need the stream, I will have to talk to our backend team for the evergreen stream as our stream carries a session that expires after a few hours. Let me know if you need them.

**Comment by marcbaechinger** [comment]
Question 1:
The easiest and proper way to do that is to make your stream appear as not seekable. I think this is currently not the case. If the stream was not seekable, the action `PlaybackStateCompat.ACTION_SEEK_TO` would be omitted and the notification would not show the seekbar. Besides the notification, other problems may pop up with a stream which says it is seekable but actually it's not.

Besides this you can override this by setting your own metadata. I think your approach above with setting the metadata can work, but you need to make sure that the `MediaSessionConnector` does not override your metadata. Also instead of setting a duration of C.TIME_UNSET you should just omit setting the duration. Easiest is probably to do this in your custom `MediaMetadataProvider`:

Sample code (not tested):
```
connector.setMediaMetadataProvider(new MediaMetadataProvider() {
    @Override
    public MediaMetadataCompat getMetadata(Player player) {
          MediaMetadataCompat.Builder builder = new MediaMetadataCompat.Builder();
          // set everything you need and make sure it reflects what is currently playing in player.
          // Do not set the duration though.
          return builder.build();
    }
});

```

Please have a look at what the `DefaultMediaMetadataProvider` does if you want to have lockscreen and everything working.

Question 2:
The title on the lock screen is taken from the metadata I believe. Does it show 'no title' without your modification regarding metadata? I'd say that the `DefaultMetadataProvider` does set the metadata that the title is set properly. Can you double check if this was introduced by your approach of overriding the metadata?

**Comment by abhishekredspace** [comment]
Thanks for your reply. 
1. That works now.
2. So even if I remove all the metadata related code, I still see the issue. So basically I removed.
```
        mediaSession.setMetadata(mediaMetadata)
        sessionConnector.setMediaMetadataProvider{ _ ->
            mediaMetadata
        }
```

**Comment by abhishekredspace** [comment]
Ok I think we need to call `invalidateMediaSessionMetadata` as well. Calling that when metadata is updated, does the trick. Not sure if that is the right solution though, but works as now.

**Comment by marcbaechinger** [comment]
Cool. I'm closing for now. Please reopen if needed.
