### ISSUE TITLE
IMA DAI AdEvents possibly corrupted by TrackSelector

### ISSUE THREAD

**Issue by kbalana** [google/ExoPlayer#6627]
### [REQUIRED] Searched documentation and issues
Already have spoken with the DAI team. They've suggested that problem may lies on ExoPlayer's side, so here I am - https://groups.google.com/forum/#!topic/ima-sdk/WgitrZlD3T4

### [REQUIRED] Question
During implementation of DAI SDK I've stumbled upon on some strange behaviour. In our app, we use ExoPlayer with some additional components (like TrackSelector, DRMSessionManager, BandwithMeter etc). Everything seems to work fine, I can read AdEvents correctly (they're being triggered via IMA DAI SDK) untill trackSelectors parameter setRenderedDisabled() will be used.

Below is a problematic fragment:
```
DefaultTrackSelector.Parameters brokenParams = trackSelector.buildUponParameters().setRendererDisabled(C.TRACK_TYPE_TEXT, true).clearSelectionOverrides().build();
trackSelector.setParameters(brokenParams);

mPlayer = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(mContext),
trackSelector, new DefaultLoadControl());
```
Unfortunately. I have to have it that way. Question is: Is that an expected behaviour? If yes, how to make AdEvents work again?

### A full bug report captured from the device
See below

### Link to test content
I've added this problematic line to example app, made by DAI team. You can compile it at test by yourself.
https://drive.google.com/file/d/1HWwRrVm2JOf4ibIE7DYTO2PutrcFGl4N/view?usp=sharing

Thanks in advance,
Christopher

**Comment by ojw28** [comment]
`setRendererDisabled(C.TRACK_TYPE_TEXT, true)` isn't correct usage of the API. The first argument is supposed to be a renderer index, not a track type constant. The track type constant that you're using is coincidentally the index of the metadata renderer, and so you end up disabling the metadata renderer, which is why you no longer receive the events.

It's unclear why you would need to disable the text renderer, but if you really need to do this then you have a couple of options:

If you don't need text rendering at all, you can build the player to not include a text renderer in the first place (which means you don't have to do anything with the track selector):
```
RenderersFactory renderersFactory = new DefaultRenderersFactory(mContext) {
  @Override
  protected void buildTextRenderers(
     Context context,
     TextOutput output,
     Looper outputLooper,
     int extensionRendererMode,
     ArrayList<Renderer> out) {
    // Overridden to nothing.
  }
};
mPlayer = ExoPlayerFactory.newSimpleInstance(
    renderersFactory,
    trackSelector,
    new DefaultLoadControl());
```

If you want text renderers as part of the player, but want to disable them, then you can do:
```
DefaultTrackSelector.ParametersBuilder paramsBuilder =
    trackSelector.buildUponParameters();
for (int i = 0; i < mPlayer.getRendererCount(); i++) {
  if (mPlayer.getRendererType(i) == C.TRACK_TYPE_TEXT) {
    paramsBuilder.setRendererDisabled(i, true);
  }
}
trackSelector.setParameters(paramsBuilder);
```
