### ISSUE TITLE
Parse channel count and sample rate from ALAC initialization data, for robustness

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#6648]
We do this for AAC [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L1118). Doing the same for ALAC will fix the issue that [this pull request](https://github.com/google/ExoPlayer/pull/6629) is attempting to work around.

**Comment by ojw28** [comment]
@ArtYemelianov - This is now fixed in the dev branch.

**Comment by ArtYemelianov** [comment]
@ojw28 , thanks for the quick response and fix. It was great! 

I would like to ask when your team will the next version release? Perhaps do you have a plan to release?

**Comment by JJSarrasin** [comment]
@ArtYemelianov I'm following very close since a few weeks because I'm waitinng on a 2.11.0 feature. They've never been so closed. It should be a matter of day (or hours), but they sadly didn't want to communicate on release date.

**Comment by ojw28** [comment]
There will be a small 2.10.8 release this week (probably tomorrow) that includes this change.

@JJSarrasin - We don't communicate release dates for major releases simply because we don't know exactly when they'll be. We'd rather release something when it's ready than communicate a release date and end up either missing it, or having to cut corners to hit it.

**Comment by JJSarrasin** [comment]
@ojw28 I understand your point of view. On my side if I knew the 2.11.0 would take "so long", I would have done differently by waiting on the master branch with a hack instead of importing the dev-v2 branch.
If the switch between dev-v2 and master could be easily done in gradle without needing to import the whole project, it wouldn't be a "problem". Thanks for your commitment
