### ISSUE TITLE
Problem playing video DASH+WV in a specific mobile phone

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#6654]
Using the exoplayer demo application for version 2.10.4 in a concrete mobile phone I'm not able to play DASH+widevine video.

The information of the device it's the following:
Device name: Galaxy J7
Model number: SM-J700H
Android version: 6.0.1
Kernel version: 3.10.61-13202935
Build number: MMB29K_J700HXWU3BRC1

This it's the concrete asset used from exoplayer demo:
```
{
        "name": "Exoplayer test asset WV: Secure SD (MP4,H265)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears_sd.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
 }
```

The error given by exoplayer it's:
```
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: Playback error.
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1122)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CryptoException: Unknown Error
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1113)
11-14 20:13:49.282 17940 27651 E ExoPlayerImplInternal: 	... 6 more
```

Attached a file with the logs of the device whem the error it's reproduced:
[error_logs.txt](https://github.com/google/ExoPlayer/files/3847178/error_logs.txt)

With this mobile phone using the DASH-IF reference player this video can be played.

**Comment by laurafuente** [comment]
Hi, Is there any news about this issue?
Thanks

**Comment by marcbaechinger** [comment]
It appears that this is a device specific problem with the DRM implementation or a bug in the platform DRM of the Android version used on this device.

Searching for the given device on the net, tells me that it can be upgraded to Android 7. 

Did you test with this the device with the most recent OS available for that device? If you tested, can you confirm this does fix the problem?

**Comment by jt64** [comment]
Can you please attach a full bugreport from boot until after failed playback?

**Comment by tsaezmirada** [comment]
After updating the OS Android, the affected device can playback drm content without issues.

Attached the captures with all the information before and after the upgrade.
![before_upgrade_1](https://user-images.githubusercontent.com/58779383/70629462-55170e80-1c2a-11ea-80ef-84d681d7de63.jpg)
![before_upgrade_2](https://user-images.githubusercontent.com/58779383/70629464-55170e80-1c2a-11ea-9432-bdbdc37e560d.png)
![after_upgrade_1](https://user-images.githubusercontent.com/58779383/70629465-55afa500-1c2a-11ea-87e1-75b6f09d1443.jpg)
![after_upgrade_2](https://user-images.githubusercontent.com/58779383/70629468-55afa500-1c2a-11ea-8d2b-b139c08a487d.jpg)
![after_upgrade_3](https://user-images.githubusercontent.com/58779383/70629470-55afa500-1c2a-11ea-8dd7-e418ebd4be31.jpg)

As you will see, some parameters have changed as the Security SW version, kernel and Build number.

Please, could you give us an explanation how it impacts on drm content for the device and the root cause.

If more test needed, let us know.

**Comment by tsaezmirada** [comment]
Hello Exoplayer team,

How is going the investigation? 

We would need to provide an explanation of the problem to our client and a solution different from upgrade the OS from the final customer's devices.

Please, let us know if you need more test or any other evidence.

BR,
Tania

**Comment by ojw28** [comment]
I don't think we received a full bug report as requested above, which is needed to investigate this issue. Marking this issue as "need more info" because we still need this if we're to investigate further, however since you've upgraded the device to a newer build on which the issue does not reproduce, it's unclear whether you'll be able to provide one at this point.

> and a solution different from upgrade the OS from the final customer's devices.

If the issue is in the platform then it's likely that an alternative solution exists.

**Comment by tsaezmirada** [comment]
Thanks for the feedback, we will try to get all the information you need. You requested a full bugreport from boot until after failed playback. Then we will test it again getting the completed log.

Is needed anything else could you help to investigate?

**Comment by tsaezmirada** [comment]
Please, keep open this ticket since we need the client test with one of he affected devices and send us the logs.

**Comment by tsaezmirada** [comment]
[android_logs.txt](https://github.com/google/ExoPlayer/files/4267134/android_logs.txt)

Hello Exoplayer team, 

I would like to re-open this jira with new logs from other affected device by this issue. As requested, attached a full report from the starting of the app up to close with all playback done and failing.

Please, keep us updated or if any other requirement is needed.

Regards,
Tania

**Comment by jt64** [comment]
Thank you for the new log provided. We aren't able to tell from the log which device make/model the failure happened on, can you provide that information also?

We do see the same error code returned from the trustlet indicating that communication failed during the decrypt call so can confirm it is the same problem.

02-28 20:49:52.890  3115  4056 E wv_dash : Trustlet did not send a valid return code: 0x6000

We will provide the log to the manufacturer which will hopefully allow them to diagnose the problem.

**Comment by tsaezmirada** [comment]
Hello Exoplayer team,

Here some pics with the device hw and sw info:
![Screenshot_20200312-161626](https://user-images.githubusercontent.com/58779383/76606521-ab8a3680-6512-11ea-8909-9912a71fc71b.png)
![Screenshot_20200312-161654](https://user-images.githubusercontent.com/58779383/76606527-adec9080-6512-11ea-9f5d-e85a43ea5af3.png)
![Screenshot_20200312-161631](https://user-images.githubusercontent.com/58779383/76606533-afb65400-6512-11ea-9824-0c926c0b9c41.png)
![Screenshot_20200312-161617](https://user-images.githubusercontent.com/58779383/76606535-b0e78100-6512-11ea-9463-9aa49f22da9f.png)


Keep me updated please.

Many thanks!

**Comment by tsaezmirada** [comment]
Hello @jt64 

Can we have some update for this issue?

Thanks a lot for your support!

**Comment by jt64** [comment]
Thank you for the additional screen shots. I have forwarded them to Samsung and requested a status update.

**Comment by jt64** [comment]
Sorry I'm a big confused, the original problem reported was on this device:

Device name: Galaxy J7
Model number: SM-J700H

But the screen shot images you most recently sent are for :

Device name: Galaxy S6
Model Number: SMG920F

Can you clarify?

**Comment by jt64** [comment]
Samsung noted that the "Trustlet did not send a valid return code: 0x6000" error could be caused if the device is in an unreliable state. One possible condition could be if the device has been unlocked/rooted.

Also we do need a full bugreport, not just logcat. The bugreport contains dumpstate information that is necessary to find out more about this problem.

**Comment by tsaezmirada** [comment]
Thanks @jt64, I will organise a new test with the client. 
Just to clarify that this issue has been reported for different models of Samsung devices as
Device name: Galaxy J7 -Model number: SM-J700H and  Device name: Galaxy S6-Model Number: SMG920F.

I will give you update with the dumpstate asap.

**Comment by tsaezmirada** [comment]
Hello @jt64 ,

Here the dumpstate you requested during the playback with the same device from last test time. Additionaly we got some logs just in case.
[Uploading dumpstate.log
[android.log](https://github.com/google/ExoPlayer/files/4486494/android.log)
…]()

We keep waiting for Samsung analysis. 

Thanks for your support.

**Comment by ojw28** [comment]
Did you mean to attach a file called `dumpstate.log` to the above response? Because I don't think you were successful, if so.

**Comment by tsaezmirada** [comment]
Attached now the dumpstate.log compressed:
[dumpstate.zip](https://github.com/google/ExoPlayer/files/4488447/dumpstate.zip)

**Comment by jt64** [comment]
Thank you for providing the dumpstate file, we are following up with Samsung

**Comment by jt64** [comment]
This is the information we received from Samsung:

First of all, I cannot find any widevine related log from dumpstate.
I wanted to see kernel log when TA returns "0x6000" error. But, it seems that user just executes dumpdate without testing widevine.

But, I can see below in kernel log.

```
<6>[ 8716.274222]  [1:         mc_log: 3114] MobiCore mcd: 501|Err tima  read_range_hash_and_cmp: TIMA_PKM_HASH_DB: Code segment modified start addr: 0x40276000!!
<6>[ 8716.274315]  [1:         mc_log: 3114] MobiCore mcd: 501|Err tima  measure_verify_kernel: TIMA_PKM_HASH_DB: KERNEL VERIFICATION FAILED
<6>[ 8716.274366]  [1:         mc_log: 3114] MobiCore mcd: f01|TIMA_MEASURE_KERNEL_ONDEMAND:  ICCC : Kernel status ret:-1 ro_ret:0 
<6>[ 8716.274417]  [1:         mc_log: 3114] MobiCore mcd: f01|TIMA_MEASURE_KERNEL_ONDEMAND:  ICCC type:-16777216 value:1 
...
<6>[ 8716.282663]  [2:         mc_log: 3114] MobiCore mcd: 501|Err tima  generate_response_string: TIMA_INIT: Kernel verification failure
<6>[ 8716.282683]  [2:         mc_log: 3114] MobiCore mcd: 501|Kernel verification failure
```

According to above log, system tried to verify kernel but it failed.
This log is from Samsung Mobile's solution, but It seems that kernel is modified.

As I mentioned at comment #6, Widevine TA checks system's reliability before decryption.
Samsung Mobile provides one API and Widevine TA checks system's status by using this API.
If this API returns failure, Widevine TA doesn't execute decryption and just returns "0x6000" error.
This is Samsung Mobile's requirement.

Based on previous log and this dumpstate log, I can say that current decryption failure happens due to reliability of device.
I don't know the current status of this device exactly and why it decides that kernel is modified, but I think Widevine TA is working as intended.

**Comment by tsaezmirada** [comment]
Thanks @jt64 for the feedback,

Is there any solution we can provide to the customer? Probably the mobile is rooted....

**Comment by tsaezmirada** [comment]
Hello @jt64 , any solution found for customers?

Or do you need any other information?

**Comment by jt64** [comment]
I agree that the mostly likely case is that the device is rooted. That is a configuration that Samsung does not allow for playback of secure video. That's the information to feed back to the customer. Thanks.
