### ISSUE TITLE
BehindLiveWindowException

### ISSUE THREAD

**Issue by andrea157** [google/ExoPlayer#6683]
Hi I have problems with playing a live stream. With a poor connection at some point ExoPlayer throws a "BehindLiveWindowException" exception. I tried to edit the "HlsChunkSource" class on line 292 in the library

```
if (chunkMediaSequence < mediaPlaylist.mediaSequence) {
      fatalError = new BehindLiveWindowException();
      return;
    }

```
with

```
  if (chunkMediaSequence <mediaPlaylist.mediaSequence) {
       chunkMediaSequence = mediaPlaylist.mediaSequence + 2;
     }

```
it is a very stupid test I know, but in this way the player does not freeze anymore but goes on until it retrieves a valid chunk.

I wanted to know what problems this change can give, if there is a better way to write this change or if a way to force ExoPlayer to look for a new valid chunk is already in liberia.

Thanks

**Comment by AquilesCanta** [comment]
It's a design decision that falling behind the live window has to be handed by the application. 

The proposed approach is not ideal, because:
- The Renderer will perceive a discontinuity.
- It doesn't handle the case where one track is falling behind, but another one isn't. In which case you'll perceive a bit of a disruption in playback.

I'd suggest you try preventing the BLWE instead of reacting to it. There's plenty of material about it in this issue tracker. Please have a look around. You can start with #4723.
