### ISSUE TITLE
Freezes when playing a specific DASH stream

### ISSUE THREAD

**Issue by viralpump** [google/ExoPlayer#6684]
### [REQUIRED] Issue description
1) Freezes when playing a specific DASH stream encoded by h265 codec (using ExoPlayer 2.7.3).
When playing other similar streams (4k, h265), there are no problems.
2) When using the ExoPlayer version 2.10.3, the DASH from point 1 does not play at all - a codec error
3) BUT vlc player (v 3.1.7) on this device plays this DASH (from point 1) perfectly and without freezes (in both cases: vlc player 3.1.7 and exoplayer 2.7.3 uses same processes in top - screens form top are attached in mail)

### [REQUIRED] Reproduction steps
Reproduction app on github available there: 
https://github.com/supapavel/drmtest/tree/master/my_drm_aplication
For reproduce:
1. Build
2. Click "Non DRM"
It will play next streem: https://media.axprod.net/TestVectors/v7-Clear/Manifest.mpd
From: https://github.com/Axinom/public-test-vectors

### [REQUIRED] Link to test content
https://media.axprod.net/TestVectors/v7-Clear/Manifest.mpd
From: https://github.com/Axinom/public-test-vectors

### [REQUIRED] A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
1. ExoPlayer 2.7.3
2. ExoPlayer 2.10.7

### [REQUIRED] Device(s) and version(s) of Android being used
OS: Android 9.0
Device: Debugging board based on the next chipset: https://browser.geekbench.com/v4/cpu/11947168

**Comment by AquilesCanta** [comment]
@ojw28 Mind having a look?

**Comment by ojw28** [comment]
The test stream (https://media.axprod.net/TestVectors/v7-Clear/Manifest.mpd) contains both H264 and H265 video representations. By default, I think ExoPlayer's `DefaultTrackSelector` will choose the H264 ones. The only reason this isn't happening in this case is that the underlying platform is claiming to be incapable of playing H264 at any resolution. You can see where this is happening in the bug report because there are 14 log lines starting with `MediaCodecInfo: NoSupport [sizeAndRate.support`. Is that intentional? I.e. did you intentionally break H264 capability reporting in the platform to force H265? If not, that seems like a problem with the device.

I tried playback of the test stream on a Galaxy S8, with a workaround in place to disable H264 and force playback of the H265 streams. Playback worked correctly on my device. It seems likely that the freezing issue is a problem with the underlying platform, particularly given this is a debugging board. Have you observed the same issue on any production devices? If not, you should report the problem to whoever's responsible for the platform on this device.
