### ISSUE TITLE
Can't play locally saved 4k or high resolution videos smoothly 

### ISSUE THREAD

**Issue by shan-mustafa** [google/ExoPlayer#6691]
I want to play video files that are stored on local storage. Exoplayer play videos with Good Resolution 
 perfectly without any buffering but when i try you play 4k or high resolution videos Exo Player start buffering alot (start buffering within more or less 10 seconds then start playing again). But when i played same file with MXPlayer or Android Video Player ( a selection dialog pop up when click a video to play) then both player play the file smoothly without any buffering. 
Really appreciate if some one can answer what i need to do to achieve smooth playing of locally stored files without buffering.

**Comment by icbaker** [comment]
Please follow the issue template:
https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md

Specifically:

1. Are you talking about the ExoPlayer demo app here, or your own app built using the ExoPlayer library?
   * If it's your own app, what version of ExoPlayer are you using?
1. If you're reproducing this in the ExoPlayer demo app, can you attach a bug report here (or email it to dev.exoplayer@gmail.com)?
1. Are you able to share sample media that you're using to reproduce this (or email it to dev.exoplayer@gmail.com)?
   * If you're able to share the media we need a lot more information about the video, audio & container formats being used.
1. What devices & Android versions are you seeing this on?

**Comment by shan-mustafa** [comment]
No , I integrated Exoplayer in my App. Also there is no sound only video play with buffering though everything work fine on MX-Player and Android Media player so it shouldn't be the hardware problem,  Please check below details:
- ExoPlayer version : 2.10.7
- File extension : mpg
- File resolution: (1920 x 1080)
- Hardware : Rockchip Processor TV device
- Android version : 7.1.2

- I couldn't reproduce it on demo App because it can't find any option there to select my file from storage.

**Comment by icbaker** [comment]
I'm afraid this isn't really enough information to diagnose the problem.

You can add a local file to the demo app by editing [media.exolist.json]( https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json) using a `file:///` URI, then deploying to your device. e.g.:

```
[
  {
    "name": "High res videos",
    "samples": [
      {
        "name": "My Video",
        "uri": "file:///path/to/your/file",
      }
    ]
  }
]
```

To confirm you're seeing 2 separate symptoms:

1. There is no audible sound.
1. The video doesn't play smoothly - it appears to be buffering.

Please try and reproduce with the demo app and share a bugreport either here or to dev.exoplayer@gmail.com - preferably with the sample media too so we can try and reproduce the problem ourselves. The demo app enables a lot of logging so we get much more info from a BR taken from there than in your own integration.

**Comment by shan-mustafa** [comment]
Thanks i able to set my file URI....
Yes i am facing two issues:
1- There is no audible sound.
2- The video doesn't play smoothly - it appears to be buffering.

Now i figured out that demo App and Exo-Player integration in my App both behaving exactly the same. In other words yes i able to replicate these issues on Demo App.
Here is the video link:
https://we.tl/t-41GR45m4pR

Please check at your end and i really appreciate if you could help me out. So that i can make a decision to stick with Exo or try something else , i got the deadline Thanks....

**Comment by icbaker** [comment]
Thanks for the media sample - it looks like it's mpeg2 video & ac3 audio. Note that neither of these formats are supported on all android devices:
https://developer.android.com/guide/topics/media/media-formats#core

More information on supported formats:
https://exoplayer.dev/supported-formats.html#sample-formats

When I play that media on my device (Pixel 3A XL w/ Android 10) it shows a blank video with no audio and says in the logs (and in a toast) that neither the video nor audio are supported (that's what `supported=NO_UNSUPPORTED_TYPE` means):

```
tracks [eventTime=0.67, mediaPos=0.00, window=0, period=0, 
  Renderer:0 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=224, mimeType=video/mpeg2, res=1920x1080, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
  Renderer:3 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=189, mimeType=audio/ac3, channels=5, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
]
```

Does your device support both mpeg2 and ac3? If not, and you're relying on software decoders (e.g. ffmpeg), that might explain why the video isn't playing smoothly. And if the software decoder doesn't include AC3, that might explain why the audio isn't playing at all.

I suggest you take a look in the logs of the demo app when you reproduce on your device, and see if the audio track is shown as supported and selected (`[X]` rather than `[ ]`).

**Comment by shan-mustafa** [comment]
I convert this file to MP4 then tried it and its working no buffering with perfect audio but it shall be so kind of you if you can explain how i can use ffmpeg and VP9 extension (Decoders) so i can achieve this without manually converting file to mp4 first...
I don't know how to add the environmental variables and all these stuff to setup ffmpeg extension in my project to make it work. Really appreciate your guide here...

**Comment by icbaker** [comment]
There are instructions for building the ffmpeg and vp9 extensions in their respective READMEs:
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9

> I don't know how to add the environmental variables and all these stuff to setup ffmpeg extension in my project to make it work. Really appreciate your guide here...

This seems more like a general unix/shell question rather than ExoPlayer specific - probably best to get more information from somewhere like Stack Overflow.

**Comment by shan-mustafa** [comment]
May be you are right this part is not specific to ExoPlayer. But i've read below documentation.... 
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9

and these doc don't make sense and i think the method mentioned here is not for Windows. So if could please answer how i can setup my project with these extensions to play the file without conversion that may help most people here . I did some research and added Environmental Variables in Windows System Properties but that didn't work out and solve the decoding issue. May be i am missing something..
So if you know how to add these decoder extensions and what code do i need to change in my project which apparently seems just to add a flag in DefaultRenderersFactory then it shall be very generous of you.  Please....

**Comment by icbaker** [comment]
I'm afraid I don't have any experience developing on Windows, so I can't be of much help.

We don't really have the bandwidth to offer support for all the different environments people might be using - our instructions are unix-centric because that's what we use to develop ExoPlayer.

Looks like there's some info in closed issues:
https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=+ffmpeg+windows+

In particular https://github.com/google/ExoPlayer/issues/3127#issuecomment-342355697.

**Comment by shan-mustafa** [comment]
Ok no problem Thank you no much, really appreciate your help.
