### ISSUE TITLE
exoPlayer.duration get a wrong time with 240k bitrate mp3.

### ISSUE THREAD

**Issue by tonggang1308** [google/ExoPlayer#6698]
Export mp3 files with different bitrates from the same wav file. Mp3 files with 192k, 320k bitrate can get the correct duration. But the duration for mp3 with 240k is problematic.  If you get 240k bitrate MP3 duration through ffmpeg, you can get it correctly.

we are using exoplayer r2.10.8.

[mp3.zip](https://github.com/google/ExoPlayer/files/3895240/mp3.zip)

**Comment by icbaker** [comment]
Thanks for the report. I can reproduce this in the demo app - the 192k and 320k files show a duration of 3:49 and the 240k file shows a duration of 3:35.

**Comment by andrewlewis** [comment]
These three MP3s all appear to be constant bitrate and they don't have Xing, VBRI or MLLT seeking metadata. The 192k stream has a constant MPEG audio frame size of 626 bytes, while the 240k stream alternates between 835 and 731 bytes per MPEG audio frame. ExoPlayer is using the bitrate of the first MPEG audio frame, which is 256 kbit/s (the even-numbered frames have a bitrate of 224 kbit/s, presumably to achieve the requested 240 kbit/s rate) to calculate the duration, which is why it's wrong.

I guess you will get the correct duration if you pick a constant bitrate that is supported directly in MPEG audio frames without needing to alternate frame sizes (I guess 224 or 256 kbit/s). One way to fix handling of these kind of files would be scan them to build a time-to-byte mapping, which also allows calculating an exact duration, but this requires loading more data compared to just using header metadata.

**Comment by icbaker** [comment]
This thread suggests that a constant bitrate (CBR) MP3 must have all frames at the same bitrate:
https://hydrogenaud.io/index.php?topic=52216.0

So by that definition, this file isn't valid (because to be variable bitrate it needs an Xing header as flagged by Andrew).

You're probably best off either using an explicitly VBR file or picking a supported CBR bitrate (list here: https://en.wikipedia.org/wiki/MP3#Bit_rate).
