### ISSUE TITLE
Implement ID3 Timed Metadata support for HLS

### ISSUE THREAD

**Issue by andudo** [google/ExoPlayer#67]

**Comment by outlying** [comment]
Current implementation doesn't seem valid. According to ID3v2.3.0 documentation 
> [There may be more than one "TXXX" frame in each tag](http://id3.org/id3v2.3.0#User_defined_text_information_frame)
but since Map is used to build metadata information in Id3Parser we only get information about last TXXX frame read from ID3 tag.

It's more like ID3 parsing problem than Timed Matadata, but still TM is not working because of that

**Comment by jlacivita** [comment]
@outlying I suggest filing a bug, not commenting on a closed enhancement

**Comment by outlying** [comment]
@jlacivita I created PR after this comment #1234
