### ISSUE TITLE
java.io.EOFException: ExoPlayer does not play short AAC File

### ISSUE THREAD

**Issue by patrick131313** [google/ExoPlayer#6700]
When I try to play an AAC File under 30 seconds ExoPlayer throws java.io.EOFException if "FLAG_ENABLE_CONSTANT_BITRATE_SEEKING" is set.

Currently I use version 2.9.3. I tried also with 2.10.8 and it still reproduces

Device(s) and version(s) of Android being used
Samsung Galaxy s8+ Android 8
Lg Q6 Android 8.1

I sent the report and AAC File on email at dev.exoplayer@gmail.com

**Comment by icbaker** [comment]
Thanks for the report - I'm able to repro in the demo app at 2.10.8 with the media you provided.

I'll dig deeper into what's going on here next week.

**Comment by icbaker** [comment]
I think this is happening because the file contains an incomplete ADTS frame at the end - so during the scan to setup the seeking, we're expecting to read 326 bytes but only 236 are available. How was this file produced? It seems it might have been sliced from a larger file using e.g. Unix `split`?

We probably shouldn't completely fail playback in this case though (given we successfully play the file when not using constant bitrate seeking) - I'll send a change that makes this slightly more robust.

**Comment by patrick131313** [comment]
I record files from online streams, I slice the file when I stop the recording. I don't check if the frame is complete or not.

**Comment by icbaker** [comment]
This should be fixed on the dev-v2 branch now.
