### ISSUE TITLE
Want to get accurate current position? Right now it always giving 10 millisecond interval position.

### ISSUE THREAD

**Issue by gchouhan-systango** [google/ExoPlayer#6703]
Hi team, I have requirement to get current position in every 1 millisecond. When I am getting current position in every milliseconds it is giving in interval of 10 milliseconds from the player. not exact millisecond. There is any way to set default interval of position to 1 millisecond. Please suggest any solution if available. 
thanks

**Comment by icbaker** [comment]
Is this playing a video? What frame rate is your source video at?

'position' doesn't really make sense at any higher resolution than frame rate, which if you're looking at a 60fps video is 1000 / 60 = 16.66ms - so 10ms of resolution seems reasonable.

**Comment by skalyani-systango** [comment]
@icbaker 
Let me elaborate a bit on this.

**What We Want to Achieve**
We are working with HLS stream served by AWS CloudFront. We have a pre-defined list of `long` numbers that represent elapsed time in milliseconds. So we run an infinite `Handler` with 1ms delay and we continuously query for Exoplayer's current time during video playback in that `Handler`'s Runnable. As soon as the player's current position matches one of the items in the list, we proceed with our logic that runs in the background and doesn't interfere with Exoplayer.

**Our Problem**
The values returned by `getCurrentPosition()` method are always in multiples of 10ms (which also means that the minimum difference between the last 2 values is always at least 10ms). This results into most of the numbers in our list being skipped when we attempt to match because not all of them are in multiples of 10ms.

Please feel free to revert if any more information is needed. I will try to let on as much as I can without breaching our client's IP :) .

**Comment by icbaker** [comment]
Stupid question: Can you just trigger if the currentPosition is within a certain range of target time (e.g. 200ms). i.e. `if (targetTimeMs <= currentPosition && currentPosition <= targetTimeMs + 200)`

It's unlikely we're going to make any additional guarantees about the resolution of the time returned from `getCurrentPosition()`.

And generally making millisecond-precision equality comparisons across threads seems quite error-prone. What if your Handler doesn't get scheduled on one of its iterations because the CPU is contended?

**Comment by ojw28** [comment]
Executing something every millisecond sounds very inefficient. If you want to "do something" at a certain `eventPosition`, you can ask the player to tell you when that position is encountered:
```
player.createMessage(eventTarget)
    .setPosition(eventPosition)
    .setDeleteAfterDelivery(deleteAfterDelivery)
    .setHandler(new Handler())
    .send();
```
Where `eventTarget.handleMessage` will be called at `eventPosition`. You should set `deleteAfterDelivery` to `false` if you want the event to be triggered again if the event position is encountered again (e.g. because the user seeks backward and then plays through it again), or `true` if you're only interested in the first encounter.

Even if you can't use this functionality for some reason, you should still do something more efficient than your current approach. For example, every time the player resumes playback (at the start, or after a seek, or whatever), you know the duration of time that needs to elapse before your next `eventPosition` is encountered. So you should be able to post something to a `Handler` that's delayed by that amount of time.

**Comment by gchouhan-systango** [comment]
@ojw28 Thank you so much for providing this solution. this solved my problem. Thanks again.

**Comment by ojw28** [comment]
This is documented [here](https://exoplayer.dev/listening-to-player-events.html). Removing `documentation candidate` label.
