### ISSUE TITLE
Сan not compile flac extension according to the instructions

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#6715]
Many errors:
/android-ndk-r17c/build//../sources/cxx-stl/gnu-libstdc++/4.9/include\bits/c++0x_warning.h:32:2: error:
      This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently
      experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the \
 ^

**Comment by kim-vde** [comment]
Can you try to follow the extension [build instructions of the dev-2 branch](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/flac/README.md) using NDK r20? It this does not work, can you provide the whole stack trace?

**Comment by master255** [comment]
Nothing worked!
~/flac/src/main/jni$ cd "${FLAC_EXT_PATH}"/jni && ${NDK_PATH}/ndk-build APP_ABI=all -j4
Android NDK: Could not find platform files (headers and libraries)    
/home/oleg/android-ndk-r20b/build/core/init.mk:427: *** Android NDK: Aborting    .  Stop.

And I want to compile a release, not a version for developers.

**Comment by master255** [comment]
And place the label "bug". This is a bug on the release. Let's not fool each other.

**Comment by ojw28** [comment]
@master255 - If you wish to get help from our team, please consider changing your tone to be a bit more polite. Thank you.

**Comment by master255** [comment]
@ojw28 Ok. Sorry if I was rude. I will try to be more kind.

**Comment by kim-vde** [comment]
The FLAC extension build is currently broken. This has already been fixed in a4e7274cca0ab57f0b23bfa0251a06fae243bf94 but has not been merged to the release branch yet.

I see two options:
1) You wait a few weeks until the fix is merged to the release branch.
2) You apply the necessary changes from the commit mentioned above to fix your current version.

Note that, when I try to build the release branch (with NDK r15c), I don't have the same errors as you (the ones I have are linked to the use of `std`). It is possible that your error comes from an NDK configuration issue so I would try to re-download the same NDK version or to download another one to see what happens.

**Comment by master255** [comment]
Thank you very much for the clarification. I will wait for the release.
