### ISSUE TITLE
Does IMA Sdk Supports VMAP extensions?

### ISSUE THREAD

**Issue by RezaMortazavi** [google/ExoPlayer#6735]
Does exo Ima sdk supports companion or extensions in VMAP?
I need to show some custom view above my ads , VMAP document suggest to do this by extensions:
Extensions : Container for Extensions that provide
ability to express information not
supported by VMAP.

**Comment by RezaMortazavi** [comment]
@andrewlewis any suggestions?

**Comment by andrewlewis** [comment]
Regarding extensions, please see [this IMA SDK forum thread](https://groups.google.com/d/msg/ima-sdk/QnxlFhtoIMg/ZvpLFf-ZAwAJ). It sounds like this is not supported.

Companion ads should work. #6432 has some information on how to use them that may be useful (though primarily that issue is tracking an IMA SDK issue with targetSdkVersion and companion ads).

**Comment by AlienAsRoger** [comment]
@andrewlewis this link https://groups.google.com/g/ima-sdk/c/QnxlFhtoIMg doesn't work

**Comment by andrewlewis** [comment]
Please could you try https://groups.google.com/d/msg/ima-sdk/QnxlFhtoIMg/ZvpLFf-ZAwAJ?

Edit: I've updated the comment above so will hide these last two comments. Thanks for reporting the problem.
