### ISSUE TITLE
Expose API to override system locale for audio track selection

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#6742]
Hi,

In dash we are using selection flag to decide the default lang and  if all audio tracks have the same value we take the first adaptation set as default.

It seems like the behaviour has changed Exo-Player will set the default as the language that the device is configured on if such language exist.

1) Is there a way to disable this behaviour?
2) Is it the same behaviour for text tracks as well?

Thanks,
Gilad.

**Comment by christosts** [comment]
Hi,

Can you please point what version of the ExoPlayer you were using before and what version are using now? Also, can you please provide us with a link to DASH manifest parser and an example how you set the flags to see what's happening.

If cannot share those publicly, please send them to dev.exoplayer@gmail.com using the subject "Issue #6742"

**Comment by giladna** [comment]
Hi,
This behaviour is there after moving to 2.10.0 and up 
in 2.9.6 it is still using the first adaptation set in the manifest.

basically I just not have api to ask which audio language track is now selected 
in demo app it is called auto but actually no way to get its name

it can only be taken from the LoggerEvent from getTrackStatusString

is there any other way to find it?

sending the stream in mail.

10x
Gilad.

**Comment by giladna** [comment]
@christosts 

I could do it this way 
not sure it is the optimal one though

```
       if (trackType == TRACK_TYPE_AUDIO) {
            for (int i = 0; i < trackList.size(); i++) {
                AudioTrack audioTrack = (AudioTrack) trackList.get(i);
                if (trackSelectionArray != null && trackSelectionArray.length >= TRACK_TYPE_AUDIO) {
                    TrackSelection trackSelection = trackSelectionArray.get(TRACK_TYPE_AUDIO);
                    if (trackSelection != null) {
                        Format selectedFormat = trackSelection.getSelectedFormat();
                        if (selectedFormat != null) {
                            if (selectedFormat.language != null && selectedFormat.language.equals(audioTrack.getLanguage())) {
                                defaultTrackIndex = i;
                                break;
                            }
                        }
                    }
                }
            }
        }

        if (trackType == TRACK_TYPE_TEXT) {
            if (trackSelectionArray != null && trackSelectionArray.length >= TRACK_TYPE_TEXT) {
                TrackSelection trackSelection = trackSelectionArray.get(TRACK_TYPE_TEXT);
                if (trackSelection != null) {
                    Format selectedFormat = trackSelection.getSelectedFormat();
                    if (selectedFormat != null) {
                        for (int i = 0; i < trackList.size(); i++) {
                            TextTrack textTrack = (TextTrack) trackList.get(i);
                            if (selectedFormat.language != null && selectedFormat.language.equals(textTrack.getLanguage())) {
                                defaultTrackIndex = i;
                                break;
                            }
                        }
                    }
                }
            }
        }
```

**Comment by giladna** [comment]
@christosts 

Only wondering how to disable the auto track selection by device Locale.

10x

**Comment by giladna** [comment]
@christosts  any update on this

1. Is there a way to disable this behaviour?
2. Is the Locale behaviour same for text tracks as well?

**Comment by christosts** [comment]
Hi @giladna 

1. Reading the language from the system's locale cannot be turned off. Note, however, that it is only applied after other parameters and everything else being equal. So, if you have a preferred language, you should set it in the DefaultTrackSelector parameters (if you are using the DefaultTrackSelector). If you don't specify a preferred language, and the manifest has multiple languages, the player will use the system's languages, as per DASH spec.

2. Text tracks don't use the user's Locale directly, but the auto-selection prefers text tracks with the same language as audio if nothing else is specified.

If this behavior does not address your use-case, can you please share the use-case in more detail? If there is not language preference set, then why do you pick the first audio track by default? For example [the DASH spec (page 51)](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf) says the client can pick an audio track randomly from the audio tracks that are valid for selection.

You mention in the issue description that you
> are using selection flag to decide the default lang and if all audio tracks have the same value we take the first adaptation set as default.

Was this configuration on ExoPlayer version 2.9.6? If so, can you please share the code so that we can understand exactly what the use-case was? Maybe we can schedule a fix if you had a previous customization on ExoPlayer that is no longer applicable.

Regarding your question
> basically I just not have api to ask which audio language track is now selected in demo app it is called auto but actually no way to get its name

If you want to pick up the language of the audio track, you can read that from the `onTracksChanged` event raised from the player
```
// MyPlayerEventListener myPlayerEventListener = ...
// player.addListener(myPlayerEventListener);
class MyPlayerEventListener implements Player.EventListener {
  @Override
  public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
      MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
      if (mappedTrackInfo != null) {
        for (int i = 0; i < mappedTrackInfo.getRendererCount(); i++) {
          if (mappedTrackInfo.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
            TrackSelection trackSelection = trackSelections.get(i);
            if (trackSelection != null) {
               String language = trackSelection.getSelectedFormat().language;
               // ...
              }
            }
          }
        }
      }
  }
}
```

and you can use a `DefaultTrackNameProvider` to create the track description string.

**Comment by giladna** [comment]
@christosts  
thanks,
that exactly was my solution to find the default selected tough it is not an easy api :) 
not sure I need a fix for it but maybe adding option to disable this Locale decision since it sounds bit like application logic to call. 

thanks a lot for your time!

**Comment by ojw28** [comment]
Here's a slightly simpler approach for getting the audio language that doesn't use `trackSelector.getCurrentMappedTrackInfo()`:

```
public void onTracksChanged(
    TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
      for (int i = 0; i < player.getRendererCount(); i++) {
        int rendererType = player.getRendererType(i);
        if (rendererType == C.TRACK_TYPE_AUDIO) {
          TrackSelection trackSelection = trackSelections.get(i);
          if (trackSelection != null) {
            String language = trackSelection.getFormat(0).language;
            // ...
          }
        }
      }
    }
```

> not sure I need a fix for it but maybe adding option to disable this Locale decision since it sounds bit like application logic to call.

As @christosts mentioned, the application already has control over which audio language gets selected via the `DefaultTrackSelector` parameters.

"Picking the first adaptation set as the default" was (and still is) arbitrary, since I don't think an adaptation set being first in a DASH manifest carries any special meaning. So I don't think we need a way of reverting back to that logic. If you want to indicate a default adaptation set in the manifest, you should use a `Role` element with scheme `urn:mpeg:dash:role:2011` and value `main` to do this. ExoPlayer looks at this type of `Role` element before it considers the device Locale when selecting the adaptation set.
