### ISSUE TITLE
can't find referenced class com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment on release

### ISSUE THREAD

**Issue by leemoxx** [google/ExoPlayer#6771]
### [REQUIRED] Issue description
I cannot generate signed apk/bundle. Whenever I do it, I get the following messages on failure:

`com.google.android.exoplayer2.text.ssa.SsaDecoder: can't find referenced class com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment`

`com.google.android.exoplayer2.text.ssa.SsaStyle$Overrides: can't find referenced class com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment`

### [REQUIRED] Reproduction steps
Attempt to generate a signed apk/bundle. I am using **ProGuard**.

### [REQUIRED] Version of ExoPlayer being used
Latest (v2.11.0).

**Comment by icbaker** [comment]
I'm not able to reproduce this building a release/proguarded APK of the demo app at 2.11.

Can you provide more detailed repro instructions, including information about how you're depending on the ExoPlayer library?

**Comment by leemoxx** [comment]
Hello @icbaker and thanks for the help. I am upgrading from 2.10.4 -> 2.11.0. I did not have any issues creating signed APKs before, so those messages are new to me. I am only adding the ui and core to my project:

`implementation 'com.google.android.exoplayer:exoplayer-core:2.11.0'`
`implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.0'`

I have just tried enabling R8 instead of ProGuard, and I was able to create a signed APK without issues. Though, I favor ProGuard because it handles one aspect better. Note that I am only playing offline files on my app.

Does the demo app use R8 or ProGuard?

**Comment by icbaker** [comment]
Thanks for the details - I'm able to reproduce by setting `android.enableR8=false` in `gradle.properties` and switching the demo app to pull the dependency in from jcenter instead of local sources.

I actually see 4 warnings - the 2 you've mentioned here & 2 javax-related ones:

```
Warning: com.google.android.exoplayer2.text.ssa.SsaDecoder: can't find referenced class com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment
Warning: com.google.android.exoplayer2.text.ssa.SsaStyle$Overrides: can't find referenced class com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment
Warning: com.google.android.exoplayer2.util.NonNullApi: can't find referenced class javax.annotation.Nonnull
Warning: com.google.android.exoplayer2.util.NonNullApi: can't find referenced class javax.annotation.meta.TypeQualifierDefault
```

The javax ones should be suppressed in the same way we suppress the other compile-time annotation classes:
https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/proguard-rules.txt#L61

I'll send a change to add `-dontwarn javax.annotation.**` there.

It's less obvious we want to be suppressing the `SsaAlignment` warning - I suspect this is related to having `IntDef` values inside the `IntDef` interface - though it's a little strange this:

a) Doesn't affect `@HlsMetadataType` which follows the same pattern.
b) Only affects ProGuard and not R8.

We're going to look into this in a bit more detail.

In the short term, you should be able to get your app building again by adding both these suppressions to your own `proguard-rules.txt`:

```
-dontwarn javax.annotation.**
-dontwarn com.google.android.exoplayer2.text.ssa.SsaStyle$SsaAlignment
```

**Comment by leemoxx** [comment]
Thank you so much for the solution and explanation @icbaker I have tried keeping the class originally but that did not help. I have thought about suppressing the warning, but I was afraid it would cause issues. I am not sure if I should be closing this issue or not, so I will leave that to you.

**Comment by icbaker** [comment]
I'll keep this open for now to track removing IntDef values that are defined inside their interfaces.
