### ISSUE TITLE
How can I change the repeat mode icon?

### ISSUE THREAD

**Issue by xuanthebui** [google/ExoPlayer#6779]
<ImageButton
            android:id="@id/exo_repeat_toggle"
            style="@style/ExoMediaButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_replay_24px" />

Please help me!!!

**Comment by Samrobbo** [comment]
Hi, the [exoplayer.dev UI components](https://exoplayer.dev/ui-components.html#overriding-layout-files) section provides some guidance on this.

**Comment by xuanthebui** [comment]
@Samrobbo Thanks.
next and previous changed,, but repeat_mode_toggle not change. ;((

**Comment by Samrobbo** [comment]
@ojw28 What are your thoughts?

**Comment by ojw28** [comment]
If you just want to change the icons without modifying the layout, then you can do so directly. The list of icon drawables that you can override can be found here:

https://github.com/google/ExoPlayer/blob/r2.11.0/library/ui/src/main/res/values/drawables.xml.

So, for example, if you want to replace the play icon with your own `custom_play_icon` drawable, you could specify the following in your application's `drawables.xml`:
```
<drawable name="exo_controls_play">@drawable/custom_play_icon</drawable>
```
For the repeat mode there are actually three icons you need to override (see the list). Note also that for the repeat mode the icons can only be overridden from ExoPlayer 2.11.0, since we fixed this recently (https://github.com/google/ExoPlayer/issues/6709).

If you want to change both the icons and the layout then for the repeat mode you'll need to override both together. This is because the `PlayerControlView` updates the icon on the `ImageButton` programmatically to be one of the three available icons, depending on the current player state.
