### ISSUE TITLE
Recommended DefaultAllocator values for rendering a local mp4 video file

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#680]
What are the best values to init the DefaultAllocator values when rendering a local mp4 file?
My considerations are quickest start-time and lowest memory allocation?

**Comment by ojw28** [comment]
Start time doesn't really depend on DefaultAllocator values. Leaving the segment size at around 64K as in the demo app is probably sensible. You could reduce the number of segments (and hence the total buffer size) to reduce the memory allocation.

You need to be careful though; some MP4 files aren't particularly well interleaved, meaning there might be a few MBs containing only audio, then a few MBs containing only video and so on. If you make the buffer too small to handle this then I imagine you'll run into problems (possibly stalled playbacks).

**Comment by dnutcracker** [comment]
Ok.
In my special case I'm dealing with starting ~9 videos simultaneously(!) using a rather small mp4 file (±1MB) - so I'm looking for the buffer size sweet spot.
Indeed when trying values that were too small I've encountered a stalled playback...

**Comment by dnutcracker** [comment]
Also - what is the use-case of using the initialAllocationCount in the DefaultAllocator?

**Comment by ojw28** [comment]
If you know exactly what's being played then experiment to find the smallest value that doesn't cause any issues, and then add a bit of a margin. If you don't know exactly what's being played, or if you can't test all content, then you might want to make the margin a little bigger. You'll have to decide for yourself what you consider a safe margin to be. There are no theoretical right answers to the question, since it depends on the exact way that the content has been encoded, and there aren't (useful) theoretical upper bounds.

Individual allocations are made as required by DefaultAllocator. initialAllocationCount can be used to allocate a number of them up front as a single memory allocation. This approach can provide better performance than making each allocation individually when running on Dalvik and when you need a large buffer. For small buffers it probably doesn't make any difference.

**Comment by dnutcracker** [comment]
Thanks, I appreciate the detailed answer.

**Comment by ptran-gpfw** [comment]
@ojw28 Follow up question, re: commit 7f9b12982da435ee99e1c57afbf4e1c184059b69, do you have guidelines for BUFFER_SEGMENT_COUNT when implementing a RendererBuilder?
