### ISSUE TITLE
How to play second track directly?

### ISSUE THREAD

**Issue by subhashreesahu** [google/ExoPlayer#6800]
I have a mp4 video file that contain 2 video track and i want to play the second video directly so how can i achieve that.

**Comment by imbichitra** [comment]
I also want the same thing.

**Comment by tonihei** [comment]
Is this in any way related to #6723? If so, please read the comment in https://github.com/google/ExoPlayer/issues/6723#issuecomment-568293355 about selecting the second track. You can do this by providing an `SelectionOverride` to `DefaulTrackSelector`.

If the issue is different, please clarify with all the details requested in the issue template (e.g. example media, reproduction steps, expected results).
