### ISSUE TITLE
Question abount the bandwidth prediction algorithm

### ISSUE THREAD

**Issue by Lrange** [google/ExoPlayer#6805]
I'm interested in the bandwidth prediction algorithm and have questions about the details.
Why SlidingPercentile uses the squared value of downloaded bytes？
Is there any relevant data to prove that this algorithm is reliable?

**Comment by tonihei** [comment]
> Is there any relevant data to prove that this algorithm is reliable?

Actually, no :) This algorithm is an ad-hoc solution that proved to work fine in practice and it has been used for years now. We recently started an investigation into all the shortcomings of the current algorithm. You can read and comment on the document [here](https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c/edit) if you like (it's part of our [public design doc section](https://exoplayer.dev/design-documents.html) on the webpage).

> Why SlidingPercentile uses the squared value of downloaded bytes？

Each data transfer provides an estimate of the bitrate. We want to weight these estimates by their reliability, because the larger the number of transferred bytes the more reliable the estimate. 
To do this, we make the simplified assumption that the measurement error is normally distributed. Let's say the bandwidth estimate after the transfer of `1` single byte has a standard deviation of `σ`, then the bandwidth estimate after `n` bytes has a standard deviation of `σ/sqrt(n)` (see [standard error](https://en.wikipedia.org/wiki/Standard_error#Population)). The weights we need for our sliding percentile class are the inverse of this standard deviation (i.e. `sqrt(n)`) because the smaller the standard deviation the larger the weight should be. Please don't try to read too much into this logic, because as said initially, it's only a heuristic that proved to work well.

**Comment by tonihei** [comment]
Closing for now under the assumption that the question has been answered. Feel free to reopen if not.
