### ISSUE TITLE
How to improve playback start time of aes128 encrypted HLS & MPD-DASH playback

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6811]
### [REQUIRED] Searched documentation and issues
No references found

### [REQUIRED] How can we improve playback start time of aes128 encrypted HLS playback.
We have kept DEFAULT_BUFFER_FOR_PLAYBACK_MS less than the hls chunk size so that playback starts immediately. However we see for AES128 files playback starts with a delay of ~1s compared to unencrypted hls chunks.

For MPD DASH, is there any optimisation option similar to setAllowChunklessPreparation (for hls) or anything else? 

Is there anyway to optimize the playback start time for Dash and AES128 streams?

**Comment by ojw28** [comment]
> However we see for AES128 files playback starts with a delay of ~1s compared to unencrypted hls chunks.

AES-128 will typically add an extra round trip before playback can start (to obtain the key). So it's unsurprising that latency would be higher. The size of delay will depend on network and server latency.

> For MPD DASH, is there any optimisation option similar to setAllowChunklessPreparation (for hls) or anything else?

The optimization that `setAllowChunklessPreparation` enables for HLS is something that you get "for free" in the DASH case, without needing any configuration.

> Is there anyway to optimize the playback start time for Dash and AES128 streams?

DASH startup latency should be pretty fast. For HLS I'd expect latency to be somewhat higher simply due to the way that HLS works. In particular because the player has to request the master playlist and then make a subsequent request for a media playlist, where-as the equivalent in DASH is a single request for the manifest.

For AES-128 encrypted HLS, there are a few options for removing the key request from the critical path when starting playback, however both are changes to the content rather than the player.

1. You could not encrypt the first few segments of the media (i.e. the first `EXT-X-KEY` tag would appear a few segments into the media playlist). This would remove the key request from the critical path when starting playback _from the beginning of the media only_.
1. You could use `data://` URIs to embed keys directly into the `EXT-X-KEY` tags within the media playlists. Note that the practicality and security implications of this approach likely depend on the specifics of your architecture, so that's something you'd need to evaluate.

**Comment by krackjack234** [comment]
Thanks @ojw28
