### ISSUE TITLE
chore(tools): add release-drafter.yml inside .github

### ISSUE THREAD

**Issue by snitin315** [google/ExoPlayer#6829]
**Actual Behaviour**
Currently we don't have the `release-drafter.yml` file which is very useful to keep track of a project. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
Right Configuration can  categorises the changes into headings, and automatically suggests the next version number as well.

for more info visit [here](https://github.com/release-drafter/release-drafter)

**I Would like to work on the issue**

**Comment by ojw28** [comment]
I'm not sure we need this. We already keep the [dev-v2 branch RELEASENOTES.md](https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md) updated, and this seems to work well enough to not require any additional tooling.

It's also a bit unclear how well this fits with the way ExoPlayer is developed, since the core development team are not working directly on GitHub / Git, and changes are mirrored to GitHub as commits directly into the `dev-v2` branch, rather than pull requests corresponding to distinct features or lines of work.
