### ISSUE TITLE
Latency/lag while network streaming H264 via UDP...

### ISSUE THREAD

**Issue by KalebKE** [google/ExoPlayer#686]
I am trying to live network stream H264 video from my server to a device via UDP using TSExtractor and UdpDataSource. I am currently using VLC to stream the source which is wrapped in a TS container. It essentially works in the sense that I can see the video play on the device.

The problem is that over time, the video on the device becomes very latent relative to what the sever is currently streaming out. The video being displayed on the device can be many seconds (up to a minute before something totally breaks) behind what is being streamed from the VLC server. I expect the video on the device to play from the live edge, but this is clearly not happening and I am unsure of the source of them problem.

When the live stream starts, the device will lag behind the server by maybe 500ms, which is totally acceptable. This acceptable playback of the stream can go on for long periods of time.

The latency issue appears to begin when packets are dropped (this is UDP). AudioTrack will report a discontinuity is detected. TsExtractor will report an unexpected start code. EventLogger will eventually report dropped frames. Some period of time later, the video playback on the device will resume, but always some period of time (seems to be related to the time when packets were originally lost) behind what the server is currently streaming. After a few periods of dropped packets, the device can be lagging behind the server by many seconds.

When the video being displayed on the device is significantly behind what is being streamed by the server, I can pause the server and the device will continue to play the video up to the point where the server was paused. Clearly, a lot of bytes are being buffered somewhere on the device when the device starts to lag behind the server.

So, two questions...

1.) Where would many seconds of possibly uncompressed video be buffered? I have crawled through most of ExoPlayer and I am not seeing anything obvious. I suspect compressed video is being buffered somewhere in the codec itself, but I thought I would eliminate ExoPlayer first.

2.) If the buffering is occurring in ExoPlayer (or even in the codec), is there anything I can do to mitigate/resolve the issue so the player always tries to play from the front of the buffer (the live edge)? I am trying to keep the video as "live" as possible, so if packets get dropped, I could not care less (up to a point), I just want to play the video I receive as soon as possible.

**Comment by KalebKE** [comment]
Possibly making some progress. The source of the problem appears to be caused by a block on the playback thread, possibly caused by TSExtractor when it receives some packets it doesn't like. 

I have caught the error log with the block a couple of times. The Delta is the time in seconds that FeedInputBuffer() and DrainOutputBuffer() have been blocked.

Log:

08-06 11:24:12.675: W/TsExtractor(20628): Unexpected start indicator: expected 130 more bytes
08-06 11:24:12.703: D/MediaCodecTrackRenderer(20628): Feed Delta: 2.415919 Thread: 11279
08-06 11:24:14.445: D/EventLogger(20628): state [28.89, true, R]
08-06 11:24:14.506: D/MediaCodecTrackRenderer(20628): Drain Delta: 1.8790482 Thread: 11279
08-06 11:24:14.514: D/MediaCodecTrackRenderer(20628): Feed Delta: 1.0737418 Thread: 11279
08-06 11:24:16.849: D/MediaCodecTrackRenderer(20628): Drain Delta: 2.415919 Thread: 11279
08-06 11:24:16.873: D/MediaCodecTrackRenderer(20628): Feed Delta: 2.415919 Thread: 11279

Log: 

08-06 11:32:47.868: W/TsExtractor(21351): Unexpected start code prefix: 131558
08-06 11:32:47.870: W/TsExtractor(21351): Unexpected start indicator: expected 130 more bytes
08-06 11:32:47.891: D/MediaCodecTrackRenderer(21351): Feed Delta: 5.1002736 Thread: 11313
08-06 11:32:47.909: D/EventLogger(21351): state [18.90, true, R]
08-06 11:32:47.910: W/TsExtractor(21351): Unexpected start code prefix: 131560
08-06 11:32:47.911: W/TsExtractor(21351): Unexpected start indicator: expected 130 more bytes
08-06 11:32:52.971: D/MediaCodecTrackRenderer(21351): Drain Delta: 4.831838 Thread: 11313
08-06 11:32:52.991: D/MediaCodecTrackRenderer(21351): Feed Delta: 4.0265317 Thread: 11313

I am still not sure why playback doesn't resume from the live edge of the buffer when the input buffer is being fed again. It might be related to the playback time, which is also being blocked. Or, the input buffer might be getting fed from another buffer fed by the Data Source, which does not appear to be blocked.

**Comment by KalebKE** [comment]
I have sorted the issue and I will describe the solution for anyone else that is interested...

The biggest problem related to live streaming is that the TrackRenderers can be stopped by the ExoPlayer implementation when it thinks buffering/rebuffering needs to occur. When the TrackRenderer is stopped by the ExoPlayer implementation, the MediaCodec buffers are no longer being filled or drained, and the stream gets buffered on the upstream side of things (more on this later). Once ExoPlayer is happy with the state of the buffer, playback resumes from the point that it stopped, usually many seconds behind the live edge of the stream. This is bad if you want to keep your stream as "live" as possible. The quick (maybe not ideal) solution is to just prevent ExoPlayer from ever stopping the TrackRenderers from rendering. I did this by creating a static flag in ExoPlayer called LIVE_STREAM. If LIVE_STREAM = true, then ExoPlayer isn't allowed to stop the renderers.

The important stuff actually happens in ExoPlayerImplInternal.java:

```
if (allRenderersEnded && (durationUs == TrackRenderer.UNKNOWN_TIME_US || durationUs <= positionUs))
{
	setState(ExoPlayer.STATE_ENDED);
	stopRenderers();
}
	else if (state == ExoPlayer.STATE_BUFFERING && allRenderersReadyOrEnded)
{
	setState(ExoPlayer.STATE_READY);
	if (playWhenReady)
	{
		startRenderers();
	}
}
// Don't stop renderers to rebuffer when live
else if (!ExoPlayer.LIVE_STREAM && state == ExoPlayer.STATE_READY && !allRenderersReadyOrEnded)
{
	rebuffering = playWhenReady;
	setState(ExoPlayer.STATE_BUFFERING);
	stopRenderers();
}
```

The next issue is related to the upstream buffer itself, specifically RollingSampleBuffer. If you want to keep things as "live" as possible (most likely using UDP instead of TCP), at some point you will have to give up quality in the sense that if for some reason the renderers fall behind the live edge, you will need to skip frames to catch up.

RollingSampleBuffer is designed to buffer up a lot of upstream data, and essentially just keeps growing larger as needed. This is great for TCP where you might want to wait for lost packets to arrive, or implement some sort of seeking or want to conserve battery life by turning off the wireless radio after you have enough of the stream buffered. It is bad if you want to use UDP to keep things "live". 

Instead of allowing RollingSampleBuffer to buffer large portions of the stream, to keep things as close to the live edge as possible, I wrote a new class very similar to RollingSampleBuffer except it has a small size and enforces that size by skipping packets if it gets to large. 

Finally, on Android devices I have found that over 1% of UDP packets arrive out of order, and another 0.3% get lost all together. To reorder packets I changed to RTP and wrote a RtpDataSource that reorders the packets and then strips the RTP header.

All of that and I finally have reasonable quality video streaming over RTP with less than a second of latency.

**Comment by ropez** [comment]
@KalebKE Thank you for taking the time to post this.

We too are having problems with ExoPlayer and live UDP streams (multicasts in our case). As you wrote, the player often stops and waits for buffers to fill. Also, even when it is actually playing, the quality is very bad. It looks like it's only rendering something like 2 images per second, of a normal TV stream (HD or SD).

I'm not sure if it is entirely or partially the same problem that you described. Was your patch ever included in ExoPlayer? Is there now a solution that doesn't involve patching the player?

I'm worried about the statistics you mentioned, 1% out of order and 0.3% packet loss. Was this on a Wifi connection? We are in fact using an ethernet connection on a "Asus Nexus" GoogleTV device. Also, the multicast video works fine when playing in the "MX Player" app, except for lack of deinterlacing.

**Comment by KalebKE** [comment]
@ropez Coming back around to some of this today, I apologize for the late response.

I never submitted a patch for this because I decided that ExoPlayer wasn't a good fit for live streaming video over UDP/RTP. Or at the very least, it would require significant amounts of work to create a new  "path" within ExoPlayer that would allow UDP/RTP packets to pass through the demuxer and eventually into MediaCodec to be decoded and rendered... efficiently as possible with as little buffering as possible.

As it turns out, being able to use large buffers with TCP is far easier than UDP live streaming. A couple keys to UDP live streaming where ExoPlayer was failing.

- The network thread should **only** receive packets, fill a buffer efficiently and do nothing else. If a packet arrives and the network thread is busy doing something else then that packet is lost forever. As I recall, ExoPlayer was doing to much work on the network thread (partially because of the complexity of the RollingSampleBuffer and UriDataSource) and packets were being dropped. The upstream stuff in ExoPlayer was clearly designed with TCP in mind. This was the biggest reason I gave up on ExoPlayer and I am not even sure this can be fixed without breaking a lot of other things.

- You do need buffers. One buffer for the network, another buffer for the demux and a decoder buffer. Draining and filling these buffers with threads is extremely CPU intensive unless you batch the calls to the demuxer and decoder, etc... This is easy with TCP and a large buffer. Fill a buffer with a lot of data, drain the buffer into another buffer, and then sleep until the first buffer fills with lots  of data again. With small buffers, this is much more difficult and drain calls are much more frequent. ExoPlayer took the first approach and tries to be efficient. It is difficult to change this behavior without modifying core components of ExoPlayer (ExoPlayerImplInternal) and not breaking anything else.

In the end I rolled my own implementation because I knew I was always going to receive a transport stream via UDP/RTP and I could make a very efficient implementation, although it isn't very flexible like ExoPlayer is.

**Comment by keith4ever** [comment]
@KalebKE I just found this great issue & solution now. I had a similar issue (although I'm not using UDP) and the key is how to control the buffer size to reduce streaming latency as much as possible. 
If you don't mind, can you share your idea how you improved RollingSampleBuffer so that it keeps only the minimum buffered data?  
From my study it seems the data is stored in InfoQueue and its 'capacity' controls the size of each buffer, but not sure you managed it to under certain size. 
Very much appreciated.

**Comment by tresvecesseis** [comment]
@KalebKE I have a similar scenario to yours, but we have implemented a RtpExtractor (connected to an UdpDataSource) for our live service and a RtspDatasource for our VoD service, we are in the process of cleaning both to submit them upstream, but we are interested in knowing why you decided to implement RTP support as a DataSource and to study your patches (if possible) to make exoplayer a tool better suited for these kind of scenarios.

**Comment by duanyao** [comment]
I encountered the same problem when streaming MPEG-TS over HTTP on an instable WIFI. I solve this problem by implement variable playback speed ( #1691 ), and speed up playback when there is too much data buffered. E.g.

``` java
if (player.getBufferedPosition() - player.getCurrentPosition() > 500) {
  player.setPlaybackSpeed(1.25);
} else {
  player.setPlaybackSpeed(1);
}
```

Now I can achieve 0.6~0.8s latency constantly.

I think this approach should also work for MPEG-TS over UDP.

**Comment by tao1** [comment]
@tresvecesseis I am very interested by your RtpExtractor. Do you intend to submit it in near future ?

**Comment by tresvecesseis** [comment]
We have finished our second version of the RtpExtractor but we are not completely happy with the design. Our RtpExtractor is very complex because it integrates a multi flow rtp muxer to have features like Unicast-Based Rapid Acquisition of Multicast RTP flows (the Alcatel Lucent proprietary version) and RTP retry for lost packet retransmission (based on RFC 4585 RTCP NACK FB messages). Our current design based on Java NIO IO multiplexing plus JNI for dealing with the multicast sockets due to limitations on the Android Java framework is not ready for submission until we rethink how better integrate with the rest of the Exoplayer library.

If you only need a basic rtp extractor for MP2T streams (basically an RTP header striper) I could provide a quick hack for you.

**Comment by tao1** [comment]
@tresvecesseis Oh yes please. I just need basic rtp extractor for MP2T.

**Comment by tresvecesseis** [comment]
Dev-v1 or Dev-v2 version?

**Comment by tao1** [comment]
V1 please

Le 25 août 2016 10:19 AM, "tresvecesseis" notifications@github.com a
écrit :

**Comment by tresvecesseis** [comment]
not time to try but should work, since our last work in the v1 branch there was some changes in buffers class so if you could have problems:

`diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java b/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
index 78ca511..b95efdb 100644
--- a/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
@@ -165,6 +165,13 @@ public final class ExtractorSampleSource implements SampleSource, SampleSourceRe
     }
     try {
       DEFAULT_EXTRACTOR_CLASSES.add(
+              Class.forName("com.google.android.exoplayer.extractor.rtp.TsOverRtpExtractor")
+                      .asSubclass(Extractor.class));
+    } catch (ClassNotFoundException e) {
+      // Extractor not found.
+    }
+    try {
+      DEFAULT_EXTRACTOR_CLASSES.add(
           Class.forName("com.google.android.exoplayer.extractor.flv.FlvExtractor")
               .asSubclass(Extractor.class));
     } catch (ClassNotFoundException e) {
diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java b/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java
new file mode 100644
index 0000000..6c7e47f
--- /dev/null
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java
@@ -0,0 +1,173 @@
+package com.google.android.exoplayer.extractor.rtp;
+
+import android.util.Log;
+
+import com.google.android.exoplayer.C;
+import com.google.android.exoplayer.extractor.DefaultExtractorInput;
+import com.google.android.exoplayer.extractor.Extractor;
+import com.google.android.exoplayer.extractor.ExtractorInput;
+import com.google.android.exoplayer.extractor.ExtractorOutput;
+import com.google.android.exoplayer.extractor.PositionHolder;
+import com.google.android.exoplayer.extractor.ts.PtsTimestampAdjuster;
+import com.google.android.exoplayer.extractor.ts.TsExtractor;
+import com.google.android.exoplayer.upstream.ByteArrayDataSource;
+import com.google.android.exoplayer.upstream.DataSpec;
+import com.google.android.exoplayer.util.ParsableByteArray;
+
+import java.io.IOException;
+
+public class TsOverRtpExtractor implements Extractor{
+    private int TS_PACKET_SIZE = 188;
+    private int BUFFER_SIZE = TS_PACKET_SIZE;
+    private ExtractorInput out;
+    private ByteArrayDataSource dataSource;
+    private byte[] data = new byte[BUFFER_SIZE];
+    private ParsableByteArray bufferData;
+    private TsExtractor tsExtractor;
+    private String TAG = "TsOverRtp";
+
+    public class RtpPacket {
+        int ssrc;
+        int timestamp;
+        int seqNumber;
+        int p;
+        int x;
+        int m;
+        int cc;
+        int v;
+
+        RtpPacket() {
+            ssrc = 0;
+            timestamp = 0;
+            seqNumber = 0;
+            p = 0;
+            x = 0;
+            m = 0;
+            cc = 0;
+            v = 0;
+        }
+    }
+
+    RtpPacket lastPacket;
+
+    public TsOverRtpExtractor() {
+        this(new PtsTimestampAdjuster(0));
+    }
+
+    public TsOverRtpExtractor(PtsTimestampAdjuster ptsTimestampAdjuster) {
+        this(ptsTimestampAdjuster, 0);
+    }
+
+    public TsOverRtpExtractor(PtsTimestampAdjuster ptsTimestampAdjuster, int workaroundFlags) {
+        Log.d(TAG, "Creating rtpoverts object");
+        tsExtractor = new TsExtractor(ptsTimestampAdjuster, workaroundFlags);
+        lastPacket = new RtpPacket();
+        bufferData = new ParsableByteArray(data, BUFFER_SIZE);
+        dataSource = new ByteArrayDataSource(bufferData.data);
+        DataSpec dataSpec = new DataSpec(null, 0, TS_PACKET_SIZE, null);
+        try {
+            dataSource.open(dataSpec);
+        } catch (IOException e) {
+            Log.e(TAG, "Exception creating Rtp DataSource", e);
+        }
+        out = new DefaultExtractorInput(dataSource, 0, C.LENGTH_UNBOUNDED);
+    }
+
+    @Override
+    public void init(ExtractorOutput output) {
+        tsExtractor.init(output);
+    }
+
+    @Override
+    public boolean sniff(ExtractorInput input) throws IOException, InterruptedException {
+        Log.d(TAG, "Sniffing...");
+        byte[] scratch = new byte[1];
+        for (int i = 0; i < 5; i++) {
+            input.peekFully(scratch, 0, 1);
+            if ((scratch[0] & 0xFF) != 0x47) {
+                int bytes = extractRtpHeader(input, (int)scratch[0]);
+                input.peekFully(scratch, 0, 1);
+                if ((scratch[0] & 0xFF) == 0x47) {
+                    input.advancePeekPosition(TS_PACKET_SIZE - 1);
+                    continue;
+                }
+                return false;
+            }
+            input.advancePeekPosition(TS_PACKET_SIZE - 1);
+        }
+        return true;
+    }
+
+    @Override
+    public int read(ExtractorInput input, PositionHolder seekPosition) throws IOException, InterruptedException {
+        input.read(bufferData.data, 0, 1);
+        if ((bufferData.data[0] & 0xFF) != 0x47) {
+            int rtpHeaderLength = extractRtpHeader(input, (int) bufferData.data[0]);
+            if (rtpHeaderLength != 0) {
+                input.skipFully(rtpHeaderLength - 1);
+                if (!input.readFully(bufferData.data, 0, TS_PACKET_SIZE, true)) {
+                    return RESULT_END_OF_INPUT;
+                }
+            }
+        } else {
+            if (!input.readFully(bufferData.data, 1, TS_PACKET_SIZE - 1, true)) {
+                return RESULT_END_OF_INPUT;
+            }
+        }
+        return tsExtractor.read(out, seekPosition);
+    }
+
+    @Override
+    public void seek() {
+        tsExtractor.seek();
+    }
+
+    @Override
+    public void release() {
+        tsExtractor.release();
+    }
+
+    private int extractRtpHeader(ExtractorInput input, int rtpByte) throws IOException, InterruptedException {
+        byte[] scratch = new byte[1];
+        int count = 0;
+        int peekPos = 0;
+        int version = (rtpByte & 0xc0) >> 6;
+        if (version == 2) {
+            input.peekFully(scratch, 0, 1);
+            int packetType = scratch[0] & 0x7f;
+            if (packetType == 33) {
+                int p, x, cc, m;
+                byte[] extensionLength = new byte[2];
+                byte[] seq = new byte[2];
+                input.peekFully(seq, 0, 2);
+                lastPacket.v = version;
+                lastPacket.p = (rtpByte & 0x20) >> 5;
+                lastPacket.x = (rtpByte & 0x10) >> 4;
+                lastPacket.cc = rtpByte & 0x0f;
+                lastPacket.m = packetType & 0x80;
+                lastPacket.seqNumber = seq[1] + seq[0]*16;
+                //Log.d("RTP", "sequence number = " + seqNumber);
+                peekPos = 4; // timestamp
+                peekPos += 4; // SSRC
+                peekPos += 2; // profile defined
+                count = 14;
+                if (lastPacket.cc != 0) {
+                    peekPos += 4 * lastPacket.cc;
+                    count += 4 * lastPacket.cc;
+                }
+                if (lastPacket.x != 0) {
+                    input.advancePeekPosition(peekPos);
+                    input.peekFully(extensionLength, 0, 2);
+                    int skipHeader = ((extensionLength[0] & 0xff) << 8 | (extensionLength[1] & 0xff)) * 4;
+                    count += 2;
+                    input.advancePeekPosition(skipHeader);
+                    count += skipHeader;
+                }
+            }
+        }
+        return count;
+    }
+}
diff --git a/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java b/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
index 018e1a5..3c3bc7d 100644
--- a/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
@@ -15,6 +15,7 @@
  */
 package com.google.android.exoplayer.upstream;

+import com.google.android.exoplayer.C;
 import com.google.android.exoplayer.util.Assertions;
 import com.google.android.exoplayer.util.Util;

@@ -38,11 +39,13 @@ public final class DefaultUriDataSource implements UriDataSource {

   private static final String SCHEME_ASSET = "asset";
   private static final String SCHEME_CONTENT = "content";
+  private static final String SCHEME_RTP = "rtp";

   private final UriDataSource httpDataSource;
   private final UriDataSource fileDataSource;
   private final UriDataSource assetDataSource;
   private final UriDataSource contentDataSource;
+  private final UriDataSource udpDataSource;

   /**
    * {@code null} if no data source is open. Otherwise, equal to {@link #fileDataSource} if the open
@@ -111,6 +114,7 @@ public final class DefaultUriDataSource implements UriDataSource {
     this.fileDataSource = new FileDataSource(listener);
     this.assetDataSource = new AssetDataSource(context, listener);
     this.contentDataSource = new ContentDataSource(context, listener);
+    this.udpDataSource = new UdpDataSource(listener);
   }

   @Override
@@ -128,6 +132,8 @@ public final class DefaultUriDataSource implements UriDataSource {
       dataSource = assetDataSource;
     } else if (SCHEME_CONTENT.equals(scheme)) {
       dataSource = contentDataSource;
+    } else if (SCHEME_RTP.equals(scheme)) {
+      dataSource = udpDataSource;
     } else {
       dataSource = httpDataSource;
     }
`

**Comment by tresvecesseis** [comment]
No time to try but should work, there were some changes in the buffer clases about buffer reuse that could cause problems:

``` java
diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java b/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
index 78ca511..b95efdb 100644
--- a/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java
@@ -165,6 +165,13 @@ public final class ExtractorSampleSource implements SampleSource, SampleSourceRe
     }
     try {
       DEFAULT_EXTRACTOR_CLASSES.add(
+              Class.forName("com.google.android.exoplayer.extractor.rtp.TsOverRtpExtractor")
+                      .asSubclass(Extractor.class));
+    } catch (ClassNotFoundException e) {
+      // Extractor not found.
+    }
+    try {
+      DEFAULT_EXTRACTOR_CLASSES.add(
           Class.forName("com.google.android.exoplayer.extractor.flv.FlvExtractor")
               .asSubclass(Extractor.class));
     } catch (ClassNotFoundException e) {
diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java b/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java
new file mode 100644
index 0000000..6c7e47f
--- /dev/null
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/rtp/TsOverRtpExtractor.java
@@ -0,0 +1,173 @@
+package com.google.android.exoplayer.extractor.rtp;
+
+import android.util.Log;
+
+import com.google.android.exoplayer.C;
+import com.google.android.exoplayer.extractor.DefaultExtractorInput;
+import com.google.android.exoplayer.extractor.Extractor;
+import com.google.android.exoplayer.extractor.ExtractorInput;
+import com.google.android.exoplayer.extractor.ExtractorOutput;
+import com.google.android.exoplayer.extractor.PositionHolder;
+import com.google.android.exoplayer.extractor.ts.PtsTimestampAdjuster;
+import com.google.android.exoplayer.extractor.ts.TsExtractor;
+import com.google.android.exoplayer.upstream.ByteArrayDataSource;
+import com.google.android.exoplayer.upstream.DataSpec;
+import com.google.android.exoplayer.util.ParsableByteArray;
+
+import java.io.IOException;
+
+public class TsOverRtpExtractor implements Extractor{
+    private int TS_PACKET_SIZE = 188;
+    private int BUFFER_SIZE = TS_PACKET_SIZE;
+    private ExtractorInput out;
+    private ByteArrayDataSource dataSource;
+    private byte[] data = new byte[BUFFER_SIZE];
+    private ParsableByteArray bufferData;
+    private TsExtractor tsExtractor;
+    private String TAG = "TsOverRtp";
+
+    public class RtpPacket {
+        int ssrc;
+        int timestamp;
+        int seqNumber;
+        int p;
+        int x;
+        int m;
+        int cc;
+        int v;
+
+        RtpPacket() {
+            ssrc = 0;
+            timestamp = 0;
+            seqNumber = 0;
+            p = 0;
+            x = 0;
+            m = 0;
+            cc = 0;
+            v = 0;
+        }
+    }
+
+    RtpPacket lastPacket;
+
+    public TsOverRtpExtractor() {
+        this(new PtsTimestampAdjuster(0));
+    }
+
+    public TsOverRtpExtractor(PtsTimestampAdjuster ptsTimestampAdjuster) {
+        this(ptsTimestampAdjuster, 0);
+    }
+
+    public TsOverRtpExtractor(PtsTimestampAdjuster ptsTimestampAdjuster, int workaroundFlags) {
+        Log.d(TAG, "Creating rtpoverts object");
+        tsExtractor = new TsExtractor(ptsTimestampAdjuster, workaroundFlags);
+        lastPacket = new RtpPacket();
+        bufferData = new ParsableByteArray(data, BUFFER_SIZE);
+        dataSource = new ByteArrayDataSource(bufferData.data);
+        DataSpec dataSpec = new DataSpec(null, 0, TS_PACKET_SIZE, null);
+        try {
+            dataSource.open(dataSpec);
+        } catch (IOException e) {
+            Log.e(TAG, "Exception creating Rtp DataSource", e);
+        }
+        out = new DefaultExtractorInput(dataSource, 0, C.LENGTH_UNBOUNDED);
+    }
+
+    @Override
+    public void init(ExtractorOutput output) {
+        tsExtractor.init(output);
+    }
+
+    @Override
+    public boolean sniff(ExtractorInput input) throws IOException, InterruptedException {
+        Log.d(TAG, "Sniffing...");
+        byte[] scratch = new byte[1];
+        for (int i = 0; i < 5; i++) {
+            input.peekFully(scratch, 0, 1);
+            if ((scratch[0] & 0xFF) != 0x47) {
+                int bytes = extractRtpHeader(input, (int)scratch[0]);
+                input.peekFully(scratch, 0, 1);
+                if ((scratch[0] & 0xFF) == 0x47) {
+                    input.advancePeekPosition(TS_PACKET_SIZE - 1);
+                    continue;
+                }
+                return false;
+            }
+            input.advancePeekPosition(TS_PACKET_SIZE - 1);
+        }
+        return true;
+    }
+
+    @Override
+    public int read(ExtractorInput input, PositionHolder seekPosition) throws IOException, InterruptedException {
+        input.read(bufferData.data, 0, 1);
+        if ((bufferData.data[0] & 0xFF) != 0x47) {
+            int rtpHeaderLength = extractRtpHeader(input, (int) bufferData.data[0]);
+            if (rtpHeaderLength != 0) {
+                input.skipFully(rtpHeaderLength - 1);
+                if (!input.readFully(bufferData.data, 0, TS_PACKET_SIZE, true)) {
+                    return RESULT_END_OF_INPUT;
+                }
+            }
+        } else {
+            if (!input.readFully(bufferData.data, 1, TS_PACKET_SIZE - 1, true)) {
+                return RESULT_END_OF_INPUT;
+            }
+        }
+        return tsExtractor.read(out, seekPosition);
+    }
+
+    @Override
+    public void seek() {
+        tsExtractor.seek();
+    }
+
+    @Override
+    public void release() {
+        tsExtractor.release();
+    }
+
+    private int extractRtpHeader(ExtractorInput input, int rtpByte) throws IOException, InterruptedException {
+        byte[] scratch = new byte[1];
+        int count = 0;
+        int peekPos = 0;
+        int version = (rtpByte & 0xc0) >> 6;
+        if (version == 2) {
+            input.peekFully(scratch, 0, 1);
+            int packetType = scratch[0] & 0x7f;
+            if (packetType == 33) {
+                int p, x, cc, m;
+                byte[] extensionLength = new byte[2];
+                byte[] seq = new byte[2];
+                input.peekFully(seq, 0, 2);
+                lastPacket.v = version;
+                lastPacket.p = (rtpByte & 0x20) >> 5;
+                lastPacket.x = (rtpByte & 0x10) >> 4;
+                lastPacket.cc = rtpByte & 0x0f;
+                lastPacket.m = packetType & 0x80;
+                lastPacket.seqNumber = seq[1] + seq[0]*16;
+                //Log.d("RTP", "sequence number = " + seqNumber);
+                peekPos = 4; // timestamp
+                peekPos += 4; // SSRC
+                peekPos += 2; // profile defined
+                count = 14;
+                if (lastPacket.cc != 0) {
+                    peekPos += 4 * lastPacket.cc;
+                    count += 4 * lastPacket.cc;
+                }
+                if (lastPacket.x != 0) {
+                    input.advancePeekPosition(peekPos);
+                    input.peekFully(extensionLength, 0, 2);
+                    int skipHeader = ((extensionLength[0] & 0xff) << 8 | (extensionLength[1] & 0xff)) * 4;
+                    count += 2;
+                    input.advancePeekPosition(skipHeader);
+                    count += skipHeader;
+                }
+            }
+        }
+        return count;
+    }
+}
diff --git a/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java b/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
index 018e1a5..3c3bc7d 100644
--- a/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java
@@ -15,6 +15,7 @@
  */
 package com.google.android.exoplayer.upstream;

+import com.google.android.exoplayer.C;
 import com.google.android.exoplayer.util.Assertions;
 import com.google.android.exoplayer.util.Util;

@@ -38,11 +39,13 @@ public final class DefaultUriDataSource implements UriDataSource {

   private static final String SCHEME_ASSET = "asset";
   private static final String SCHEME_CONTENT = "content";
+  private static final String SCHEME_RTP = "rtp";

   private final UriDataSource httpDataSource;
   private final UriDataSource fileDataSource;
   private final UriDataSource assetDataSource;
   private final UriDataSource contentDataSource;
+  private final UriDataSource udpDataSource;

   /**
    * {@code null} if no data source is open. Otherwise, equal to {@link #fileDataSource} if the open
@@ -111,6 +114,7 @@ public final class DefaultUriDataSource implements UriDataSource {
     this.fileDataSource = new FileDataSource(listener);
     this.assetDataSource = new AssetDataSource(context, listener);
     this.contentDataSource = new ContentDataSource(context, listener);
+    this.udpDataSource = new UdpDataSource(listener);
   }

   @Override
@@ -128,6 +132,8 @@ public final class DefaultUriDataSource implements UriDataSource {
       dataSource = assetDataSource;
     } else if (SCHEME_CONTENT.equals(scheme)) {
       dataSource = contentDataSource;
+    } else if (SCHEME_RTP.equals(scheme)) {
+      dataSource = udpDataSource;
     } else {
       dataSource = httpDataSource;
     }
```

**Comment by tao1** [comment]
@tresvecesseis **Many thanks !** But I am afraid you're right regarding changes in buffers. Indeed sniff() fails even if extractRtpHeader() returns 14.
I'll try to patch your code. What did changed in buffers reuse ?

**Comment by tresvecesseis** [comment]
Sorry, not in my development machine, We needed to modify the ByteArrayDataSource class, I´m not sure but i think that this part of the code has changed but it´s been more tan a year since we last touched this, try this patch:

diff --git a/library/src/main/java/com/google/android/exoplayer/upstream/ByteArrayDataSource.java b/library/src/main/java/com/google/android/exoplayer/upstream/ByteArrayDataSource.java

index e16b3a7..c6998f2 100644

--- a/library/src/main/java/com/google/android/exoplayer/upstream/ByteArrayDataSource.java

+++ b/library/src/main/java/com/google/android/exoplayer/upstream/ByteArrayDataSource.java

@@ -64,6 +64,10 @@ public final class ByteArrayDataSource implements DataSource {

     System.arraycopy(data, readPosition, buffer, offset, length);

     readPosition += length;

     remainingBytes -= length;

+    if (remainingBytes == 0) {

+      remainingBytes = data.length;

+      readPosition = 0;

+    }

     return length;

   }

 }

**Comment by tao1** [comment]
@tresvecesseis Your last patch makes it work using my version of TsOverRtpExtractor adapted for my 4K source :) Rtp headers length is 12 in my case.
Thank you so much !

**Comment by tresvecesseis** [comment]
You´re welcome. In any case the code it´s a hack for a subset of the RTP packets (just to test our streams) and some assumptions could break the Exoplayer library as you had seen, we are cleaning our full RTP patch and we plan to submit it for the v2 branch, once this has been done we could backport it to the v1 branch (if times permits) so be careful with this code, it could break in many ways.

Sergio
