### ISSUE TITLE
Make Metadata-extractors fail fast

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#6862]
### Use case description
Right now incorrectly videos with incorrect metadata failing to play with cryptic assert:
`Loading finished before preparation is completed`

The most primitive scenario is to pass 0-length video.
You could try it in any sample app.

Failure to find the moov segment by any reason causes the same assert.
I guess failure to find tracks will cause the similar problem as well.

### Proposed solution
The Extractor should throw an error instead of letting the upper layer to guess what went wrong.
Ideally extractor should provide some information about file size, missing fields etc.

It will simplify debugging of such issues.

**Comment by ojw28** [comment]
ExoPlayer is a library for playing media, which in the vast majority of cases should be well formed. It's not intended to be a library for debugging exactly what's wrong with malformed media, and there are various other tools for this purpose. Furthermore, adding such logic would likely add *a lot* of code into our extractors for better debugging of unusual cases. I don't think it's worth it.

Are there valid use cases for this from the perspective of a relatively normal person using a media application (for such people, there's no difference between media not playing and media not playing because a particular ISO BMFF box is missing).

**Comment by dryganets** [comment]
I agree for the user there is no difference why video is not playing, but there is a difference for the application developer. And meaningful messages will definitely make the debugging loop shorter which will result in better user experience as the problems will be addressed faster.

Isn't it better to see an exception that video was 0 size instead of just `Loading finished before preparation is completed`?

By moving such problems in the separate cohort you will make it easier to debug it for everyone.

If it is impossible to narrow down why preparation has failed while loading of video was finished maybe it is possible to fast fail some well known cases?

Maybe there is way to specify which extractor failed?

Or tell which parameters are mandatory for an extractor?

**Comment by Tolriq** [comment]
@ojw28 I have an use case for that, my application can play media from many different sources in nearly any possible formats.

Some of the sources supports transcoding to adapt the media to the player, but it's a lot of work to manually detect the special codecs that some devices support, so it would be nice to be able to have a nice and quick explicit failure explaining that it's because no extractor or no supported codec to try to switch to transcoding to something that should work on all CTS devices.
I'm not sure embedding ffprobe + manual MediaCodec enumeration is a nice solution as it's a huge .so dependency + require lots of works to perfectly match what ExoPlayer will really be able to play or not.

Same thing for sources that does not transcode, if codecs are not supported I could ask the user if the wants to watch the media in VLC due to for example too high price for the DTS licence to integrate the necessary decoder in a paid app. 

Errors could also be file unavailable, or broken or anything :(

**Comment by ojw28** [comment]
There's already an explicit way to determine whether the file contains a track with an unsupported codec. You can see this case logged in the demo app, with `NO_UNSUPPORTED_TYPE` appearing in the logs. You can write similar logic to detect this case yourself (and then do whatever you want). The relevant code in `EventLogger` is [here](https://github.com/google/ExoPlayer/blob/r2.11.1/library/core/src/main/java/com/google/android/exoplayer2/util/EventLogger.java#L250).

Playback failures containing `UnrecognizedInputFormatException` as the cause also allow you to identify cases where the container is unsupported (i.e. there's no extractor capable of handling the stream). Obviously it's not possible for us to tell you which container the media is using in this case, since doing so would require us to write an extractor to detect that specific container, which by definition is something we don't have in this case. It's also inevitable that media streams for which we do have extractors can be mapped onto this case, if they're malformed in a way that means we no longer detect the container type correctly.

**Comment by Tolriq** [comment]
Thanks it still makes looking a multiple different places and time frame but seems to cover the major cases.
But there's something strange that I encountered when looking at https://github.com/google/ExoPlayer/issues/6837

That logger report that there's only one track, that it's associated to the renderer yet it's not supported.
And ExoPlayer ends up by having a proper timeline and duration, plays no sound for the whole duration but we can seek and everything seems to work, just no sound.

```
2020-01-06 20:52:20.562 Verbose/MusicPlayer: tracks [eventTime=24.33, mediaPos=0.00, window=0, period=0, 
2020-01-06 20:52:20.564 Verbose/MusicPlayer:   Renderer:0 [
2020-01-06 20:52:20.566 Verbose/MusicPlayer:     Group:0, adaptive_supported=N/A [
2020-01-06 20:52:20.569 Verbose/MusicPlayer:       [ ] Track:0, id=1, mimeType=audio/alac, channels=2, sample_rate=44100, language=und, supported=NO_UNSUPPORTED_TYPE
2020-01-06 20:52:20.571 Verbose/MusicPlayer:     ]
2020-01-06 20:52:20.573 Verbose/MusicPlayer:   ]
2020-01-06 20:52:20.574 Verbose/MusicPlayer: ]
```

From where you point in the logger it seems the track should not be associated with the player? And so without an associated track the player should refuse to load the media?

So the real test for me would be to check for music if there's a supported audio track associated to the renderer, and for video at least 1 supported audio and 1 supported video track?

**Comment by ojw28** [comment]
Ah yes, the link I provided was to slightly the wrong place, since you'd expect unsupported audio/video tracks to be mapped to the respective renderers. Still, it's clear there's more than enough information in `MappedTrackInfo` to do what you need.

Note that this discussion is all off topic from the original request, which was about errors that currently result in `new ParserException("Loading finished before preparation is complete.")`.

**Comment by Tolriq** [comment]
Thanks, the details are out of the original request, but I was at first hoping for something related being a function that given a MediaSource would return a well defined result saying ok or not ok with a set of reasons. Seing your answers I guess making a feature requests for this have no chance to be accepted?

**Comment by ojw28** [comment]
It's not feasible to implement such a feature in a sensible way. Codec support isn't even evaluated in the `MediaSource`, since it's not the `MediaSource`s responsibility to try and play the media.

**Comment by ojw28** [comment]
Coming back to the original request:

> I agree for the user there is no difference why video is not playing, but there is a difference for the application developer. And meaningful messages will definitely make the debugging loop shorter which will result in better user experience as the problems will be addressed faster. Isn't it better to see an exception that video was 0 size instead of just Loading finished before preparation is completed?

Yes, it would definitely be better, but there are many thousands of potential reasons for failure in our extractors. It would not be a good use of time for us to create friendly debug messages for all of them, and it would add a significant amount of bloat to the library.

> If it is impossible to narrow down why preparation has failed while loading of video was finished maybe it is possible to fast fail some well known cases?

The well known case is that the media is not malformed. I'm not sure that feeding a file of length 0 to the player is a common case. It's also easy for a developer to debug themselves by taking a very cursory look at what they've fed in.

> Maybe there is way to specify which extractor failed? Or tell which parameters are mandatory for an extractor?

Determining which extractor will be being used is equivalent to knowing what container format the media uses, which is also easy to determine with a very cursory look at what was fed in (e.g., `mediainfo file.ext` on the command line).
