### ISSUE TITLE
buffer dropped when decode h264 25fps video

### ISSUE THREAD

**Issue by haohaozaici** [google/ExoPlayer#6864]
### [REQUIRED] Searched documentation and issues
According to https://github.com/google/ExoPlayer/issues/2159, I checked the ffmpeg, VP9 and av1 extension related code.

### [REQUIRED] Question
I am trying to implement a ffmpeg video renderer extension. When decoding h264 25fps video, I found that a large number of buffers are dropped, but it does not happen when decoding h264 60fps video.

In the decode method, one frame is indeed decoded every 40ms, but I don't know why a lot of buffers are dropped and the video does not look smooth.

I tried to modify the code for dropping the buffer in `SimpleDecoderVideoRenderer`. Even if the buffer is not dropped, the video(25fps) still does not look smooth. What is causing the buffer to be dropped?

thank in advance!

### A full bug report captured from the device
[bugreport-gemini-QQ1B.191205.011-2020-01-13-01-02-30.zip](https://github.com/google/ExoPlayer/files/4050915/bugreport-gemini-QQ1B.191205.011-2020-01-13-01-02-30.zip)

**Comment by haohaozaici** [comment]
I use `VideoDecoderOutputBuffer` and `VideoDecoderGLSurfaceView` to display the decoded yuv data on the surface.

Here is the status of DecoderCounters when decoding
```xml
timeUs=16000000,
DecoderCounters{
    decoderInitCount=1,
    decoderReleaseCount=0,
    inputBufferCount=404,
    skippedInputBufferCount=0,
    renderedOutputBufferCount=248,
    skippedOutputBufferCount=5,
    droppedBufferCount=147,
    maxConsecutiveDroppedBufferCount=3,
    droppedToKeyframeCount=0
}
```

**Comment by ojw28** [comment]
This question appears to be about a custom extension, rather than about the ExoPlayer library. Hence falls outside the scope of the issue tracker.

The issue is also not reproducible because you haven't provided any information on where we might obtain your custom extension. Marking as needs more info for now, because it's not possible to provide guidance without being able to reproduce the problem.

**Comment by haohaozaici** [comment]
Thanks for reply ~

I push my code to https://github.com/haohaozaici/ExoPlayer/tree/release-v2/extensions/ffmpeg-haohao. You can run the debug apk directly, or you can download the project and run it. Maybe you need my compiled libffmpeg.so file and video file.

[demo-withExtensions-debug.apk](https://drive.google.com/file/d/1xPaxYGl1r0VGpt7k25u8F7b6aRb64wdy/view?usp=sharing)
[libffmpeg.so(arm64-v8a)](https://drive.google.com/file/d/1PCEz-nrmNSSTz3NNNedfQV4VbAa3sHyN/view?usp=sharing)
[720p_h264.mp4](https://drive.google.com/file/d/1f2M0KprTl9IVCTBmTwySTVHRaSOJ75A4/view?usp=sharing)

Briefly explain what I did.
1. create `FfmpegVideoRenderer` same as `Libgav1VideoRenderer`
2. create `FfmpegVideoDecoder` like `Gav1Decoder` but  decode method like `FfmpegDecoder`, then provide `getExtraData()` method for h264 type.
3. Modify the `ffmpegDecode` jni method from the ffmpeg_jni.cc file, copy frame data to `VideoDecoderOutputBuffer`.
4. create `FFmpegRenderersFactory` to build custom VideoRenderers.

For a quick try, only VIDEO_OUTPUT_MODE_YUV mode is currently supported.

I spent a lot of time checking the code, but I don't know where the problem is, hope this will be helpful for others like me who want to build custom extensions.

**Comment by ojw28** [comment]
This is cool! Is it something you'd consider contributing back to the core project?

The problem with your current implementation is that it assumes each input buffer will produce a corresponding output buffer with the same timestamp. [The assumption is here, where you initialize the output buffer with the input buffer's timestamp](https://github.com/haohaozaici/ExoPlayer/blob/release-v2/extensions/ffmpeg-haohao/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegVideoDecoder.java#L148).

I think this assumption is true specifically for AV1 and VP9, but for some other video codecs it's normal for the input buffers to be out-of-order, and you can see this if you log the timestamps of the buffers being queued to the codec. The decoder is responsible for re-ordering them, and provides the output buffers back in the correct order. For every buffer you give to the decoder, you might get zero, one or multiple buffers back, and the output order is not equal to the input order.

To correctly handle these cases, I think you'll need to get the output buffer timestamps back from FFmpeg along with the decoded data, rather than passing them directly from input buffer to output buffer in the Java layer. You should probably also split `ffmpegDecode` into separate native methods for feeding input and reading output, to account for the possibility of multiple output buffers becoming available when you feed a single input buffer.

**Comment by haohaozaici** [comment]
Thank you for your reply and patience for viewing my code ~

It's a great honor to be able to contribute back to the core project, but before that, I hope my code runs correctly for a period of time without obvious errors or efficiency problems. I'm not an experienced developer, so it may take a long time. Anyway, I will continue to share my code and what I have done.

Back to the question, I observed that the input buffers are indeed out of order, because I don't understand the detailed behavior of the `SimpleDecoder#decoder()` method, so I can't find the reason for the error. Next, I will modify my code according to your suggestions, and carefully read the AV1 and VP9 extensions related codes.

The Chinese New Year is coming soon, and my progress may be suspended for half a month.

Once again, thank you very much~

**Comment by andrewlewis** [comment]
@haohaozaici, please feel free to send a pull request even if the code has remaining issues or needs further testing. We'd be grateful for the contribution and can fix up any issues on our side when we merge the pull request. Thanks!

**Comment by ojw28** [comment]
Hi @haohaozaici - Have you considered contributing this as a pull request? Thanks!

**Comment by haohaozaici** [comment]
@ojw28 
I'm very sorry for not responding to your message in time.
I fixed the problem I raised, and then completed a rough version, which only supports h264, yuv420p, VIDEO_OUTPUT_MODE_YUV mode, and many bugs have not been fixed. I really want to continue doing this, but I'm afraid I can't do it well. If possible, I will refine the code and submit a pull request.

**Comment by ojw28** [comment]
As @andrewlewis mentions above, I think it's fine for you to contribute what you have so far, maybe limited to H.264 initially. Once it's submitted it'll be easier for others to help out and contribute to the feature too.

**Comment by haohaozaici** [comment]
I submitted a pull request https://github.com/google/ExoPlayer/pull/7079 and will be tracking issues related to ffmpeg video renderer there. I hope everyone can help improve this feature if possible.

**Comment by andrewlewis** [comment]
@haohaozaici Thanks!
