### ISSUE TITLE
Ability to play downloaded streams by content id

### ISSUE THREAD

**Issue by Cubxity** [google/ExoPlayer#6870]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Ability to play downloaded content using the contentId provided in DownloadRequest.
![image](https://user-images.githubusercontent.com/27609129/72263038-6633b080-3618-11ea-9005-a1d1e465e4b7.png)

### [REQUIRED] Use case description
Streaming URLs get changed for the same media that it was downloaded from.

### Proposed solution
Make the cache lookup the download for the contentId that would be provided in MediaSource.

### Alternatives considered
I have not considered any other alternatives since this seems to be the only way.

**Comment by ojw28** [comment]
Assuming this is for progressive content, which it seems to be based on the screen capture you've provided (which uses `TYPE_PROGRESSIVE`), then you can use `customCacheKey` for this. It's purpose is exactly to allow mapping multiple URLs onto the same cache key, to handle the case where the streaming URL might change.

When building the `ProgressiveMediaSource`, use `setCustomCacheKey` on `ProgressiveMediaSource.Factory` to specify the same cache key for playback. This should also work when using `DownloadHelper.createMediaSource`, but it seems we're missing a line of code to actually make that work. I'll get that fixed.

**Comment by Cubxity** [comment]
@ojw28 also, would this be possible for DASH and HLS?

**Comment by ojw28** [comment]
DASH and HLS are significantly more complicated because you're no longer dealing with one URL, but many URLs. Which of the URLs can change and how many there are depends on exactly how the content is being produced.

Are you in control of the serving side? If so, what are the properties of the streams you want to do this for (e.g. does every segment have its own URL or do you have one URL per variant with byte ranges for the segments, and which URLs expire/change?).

**Comment by Cubxity** [comment]
@ojw28 I am not in control of the serving side. I'm currently developing an app that supports various streaming services. The Dash/HLS url does refresh/expire after a while. I would like to be able to play and download a dash/hls video with some unique media id.

**Comment by ojw28** [comment]
Dealing with expiring URLs and not having any control over the media sounds like quite an unusual use case. Is it a legitimate one?

**Comment by Cubxity** [comment]
I mean, it's basically doing what youtube-dl does, (scrapping the page and extract stuff, etc) but it handles the streaming

**Comment by Cubxity** [comment]
Any update on this feature? @ojw28

**Comment by ojw28** [comment]
> I mean, it's basically doing what youtube-dl does, (scrapping the page and extract stuff, etc) but it handles the streaming

This doesn't sound like a legitimate use case. You're trying to circumvent something that's explicitly designed to make it hard for you to do what you're trying to do. I.e., it's hard by design.

It's possible to handle expiring URLs in DASH and HLS using `CacheKeyFactory`, but in order to implement that interface you normally need to know the details of how the content URLs work, so that you can map all content URLs that actually point to the same piece of content onto the same cache key. In other words, if you were the owner of the content, it would be relatively straightforward for you to implement this. Given that you're not, it's hard and is not something we provide guidance on.
