### ISSUE TITLE
DASH Widevine content seekTo() confusing behavior

### ISSUE THREAD

**Issue by Shadkirill** [google/ExoPlayer#6878]
### [REQUIRED] Issue description
When seeks to position playing DASH Widevine content, for a few seconds video playing with changed speed .

### [REQUIRED] Reproduction steps
1) Open demo app.
2) Select "Widevine DASH Policy Tests (GTS)"
3) Select "WV: HDCP not spicified"
4) Seek() to random position few times

### [REQUIRED] Link to test content
Use standart json file in ExoPlayer demo app.

### [REQUIRED] Device(s) and version(s) of Android being used
Android STB with android version 7.

Video of the bug:
https://drive.google.com/file/d/1Mp3_5nQscN9SmS92xl9vuo7n16VmpCHt/view?usp=sharing

**Comment by ojw28** [comment]
The device probably fails our compatibility tests due to platform bugs. You can read about our compatibility tests and how to run them [here](https://exoplayer.dev/oems.html). If that's the case, you should contact the device manufacturer and ask them to resolve the problem. If that's not the case, please let us know.
