### ISSUE TITLE
H264 TS video not seekable in exoplayer

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#6894]
I am playing the .mp4 h264 video in exoplayer with defaultExtractor. Video is not seekable. When i seek the video it goes to start everytime i want to seek it. Others MP4 videos plays fine without any issue . Help me I am beginner of exoplayer . Frame rate is 25. I am playing the video offline.

**Comment by icbaker** [comment]
We need more information to be able to help. Please fill in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md) (copy-paste it here, and fill in every section).

Does this reproduce in the ExoPlayer demo app?

Can you provide test content that demonstrates the issue? Either upload it here or email it to dev.exoplayer@gmail.com with subject "Issue #6894".

**Comment by andrewlewis** [comment]
Potentially relevant: fragmented MP4 files without sidx boxes are not seekable (see the later replies on #6605 for more details).

**Comment by waqasyousafy** [comment]
#andrewlewis thanks for your suggestion but i am still confused between the these two concepts.one you have told me and second one is moov atom to be replaced at the begining of the videos . Please clear it to what it should be??

**Comment by andrewlewis** [comment]
@waqasyousafy It would be easiest to help if you could share the media with us so we can try to determine exactly what's wrong with it (rather than speculating on what might be wrong).

It is best practice to put header data at the start of the stream so the player doesn't need to request header data from the end of the stream. For fragmented MP4 streams we need a sidx box to make them seekable (this does not apply to unfragmented MP4s).

**Comment by waqasyousafy** [comment]
@andrewlewis Sorry for late replying . Here is the video link i am using in playing :
https://drive.google.com/open?id=16CJJKU-p6Dwd3WBi8KaVuBJn1y8Os7qi

**Comment by icbaker** [comment]
Thanks for the media - although the provided file has a `.mp4` extension, it's actually an MPEG-TS file, not MP4:

```
$ mediainfo matchvideo.mp4
General
ID                                       : 1 (0x1)
Complete name                            : matchvideo.mp4
Format                                   : MPEG-TS
File size                                : 11.4 MiB
Duration                                 : 1 min 9 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 344 kb/s
FileExtension_Invalid                    : ts m2t m2s m4t m4s tmf ts tp trp ty
```

I don't see exactly the behaviour you describe - when I play this file in the demo app there seek bar is completely disabled (rather than allowing seeking, but always returning to the beginning) - are you seeking programmatically without checking whether ExoPlayer thinks the media is seekable? That might cause the 'return to start' behaviour.

The file is not seekable due to constraints in ExoPlayer's handling of MPEG-TS streams. This is tracked in https://github.com/google/ExoPlayer/issues/5097. As a workaround you can increase the value of `TsDurationReader#TIMESTAMP_SEARCH_BYTES` - I tried this locally and your video became seekable.

**Comment by waqasyousafy** [comment]
@icbaker thank you but i did not figure it out how to use it . I have searched a lot but not find any solution yet can you please refer me some example if you agree . I will be grateful to you .

**Comment by icbaker** [comment]
You will have to fork ExoPlayer and change the value yourself locally, then amend your gradle config to depend on your locally-compiled version rather than the one provided via jcenter. 

This is the line you need to change:
https://github.com/google/ExoPlayer/blob/ea342a671c610916fdcdcb3c4f5c740ff1374719/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsDurationReader.java#L39

There's some general gradle advice about depending on a local jar here:
https://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

**Comment by waqasyousafy** [comment]
Thank you so much @icbaker . It solved my problem . You know its my first project in android . I am very happy to complete this . Thank you for help

**Comment by waqasyousafy** [comment]
Hi @icbaker  I am getting an issue with mpeg-ts video . Discontinuity detected many times . 
I have searched a lot on stack overflow and GitHub . There is only one discussion that the media is not correct . But other players play the video fine .Exo palyer freeze at once when discontinuity detected . Is there any solution for this problem. I will be very grateful to you .

**Comment by waqasyousafy** [comment]
The image of discontinuity is here and media is also here 
Video:
https://drive.google.com/file/d/13cPGZghCKIAeRYbTlRbMW2GGPaMrEVqH/view?usp=sharing
Image :
https://drive.google.com/file/d/1Y9Ykz1PXCn9qK2mu0UCJwiSgbj4yxXsN/view

**Comment by icbaker** [comment]
This sounds like a new problem. Please file a new issue, and make sure you fill in all the sections of the template (including a bugreport text file):
https://github.com/google/ExoPlayer/issues/new/choose

**Comment by icbaker** [comment]
Ah, just spotted you already filed #6970. Let's keep the discontinuity discussion over there.
