### ISSUE TITLE
WebM video playback with missing audio

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#690]
I was doing some WebM testing and found a number of sample files which fail to play correct via ExoPlayer. These same sample files play fine via Chrome. 

 - VP8 / Vorbis: https://drive.google.com/file/d/0B5F60IW5qC-vWDB2ZW5LRlQycmc/view?usp=sharing
 - VP9 / OPUS: https://drive.google.com/file/d/0B5F60IW5qC-vTk85Nl9peF9XUUU/view?usp=sharing

The first sample was grabbed from http://www.webmfiles.org/demo-files, but i'm not sure if I still have the source for the second file.

**Comment by vigneshvg** [comment]
@IanDBird do you have more information on how exactly these files are failing to play? The first file should play fine on most android devices as VP8 and Vorbis have been supported since early versions of android (i tried it in the demo app running kitkat and it worked fine).

about the second file, VP9 is only supported from android kitkat and Opus is only supported (albeit partially) from lollipop. so it's unlikely that the second file would've played correctly if you used an android version from before that. also if you'd like to playback the second file on older versions of android, you can consider using the ExoPlayer VP9 and Opus native extensions [1]. I verified it with the native demo app [2] and it plays back just fine.

[1] https://github.com/google/ExoPlayer/tree/master/extensions
[2] https://github.com/google/ExoPlayer/tree/master/demo_misc/webm_sw_decoder

**Comment by IanDBird** [comment]
@vigneshvg - I was testing both files running on the Nvidia Shield Android TV. Playback started for both files but no audio was played on either. I have another WebM test file i'm using which is VP9 + Vorbis and works fine. If you think this issue might be device specific, i'm happy to go back an testing using:
 - ExoPlayer demo application
 - Other Android TV devices

Our application would only allow playback of this content if the device was shipped with native support, rather than looking to add the custom extensions.

**Comment by vigneshvg** [comment]
@IanDBird thanks for the information. i am guessing Opus is not being played back because it's not supported in the version of android you are in. although, i'm able to reproduce the first file not playing audio in kitkat with exoplayer (it plays back fine via MediaPlayer API though).

**Comment by IanDBird** [comment]
@vigneshvg - i'll double check the device, but I was under the impression that Opus was supported in Lollipop and above? (All Android TVs run at least Lollipop).

**Comment by vigneshvg** [comment]
@IanDBird afaik, Opus on lollipop is partially supported and has some known issues.
