### ISSUE TITLE
More Exoplayer players active in the same time

### ISSUE THREAD

**Issue by XanderSan** [google/ExoPlayer#6904]
I would create an app using a ListView or a RecyclerView to play many 360 video at the same time using Exoplayer and, clicking on a video, show it fullscreen.
Is it possible? Is there some samples of this feature?

Thanks in advance

**Comment by icbaker** [comment]
See discussion of using multiple players here:
https://github.com/google/ExoPlayer/issues/1286#issuecomment-190148041
https://github.com/google/ExoPlayer/issues/2855

You're likely to run into problems because your device might well only have one decoder, so decoding multiple videos simultaneously isn't really possible on these devices.

**Comment by XanderSan** [comment]
Ok, thanks for the response.
If possible I need an example that shows how open more than one player and test if it works on my device.

**Comment by icbaker** [comment]
This comment outlines the high-level approach you could take: https://github.com/google/ExoPlayer/issues/2855#issuecomment-303465454

This isn't something we have existing examples or documentation for because it's not likely to work on so many devices.
