### ISSUE TITLE
Player restart live dash stream after it ends

### ISSUE THREAD

**Issue by abellybeer** [google/ExoPlayer#6918]
Hello, I've been testing exoplayer to play live dash streams. So far I can play them without any problem, execept when the live event ends and manifest file changes to a different one. I managed to keep a track of manifest urls but it seems exoplayer just loads first live event and neglets to keep updating infos contained on new manifest file. I am not familiar with java but I already tried these lines on PlayerActivity.java
`     player.seekTo(0);
      player.setPlayWhenReady(true);`

So, lets say a live event has 30min duration. Exoplayer plays it until it ends and when it ends it pauses and when I click play it start the same event but not the new one that is already started and changed on manifest file. My solution would be restart the stream once it ends its 30min and then gets to read new manifest file and imediatelly plays new live event.

I've set my manifest files headers with php to no-cache. Is this the right approach? I would like to have a little help here on how to do this.

Thanks in advance.

**Comment by ojw28** [comment]
It's not a valid manifest transformation to replace one manifest file with another at the same URL. If they're different events they should have different URLs.

**Comment by abellybeer** [comment]
Hey @ojw28! Thanks for your answer! So the best approach for this would be having a static manifest.mpd URL that redirects to different manifest.mpd accordinly to live events?
 So when a live event ends, exoplayer will try to download static manifest.mpd that will redirect him to a dinamyc manifest.mpd

Is that how I should do?

**Comment by ojw28** [comment]
Two separate live events are two separate pieces of media. You need to re-prepare the player with the new piece of media, which should also have a different URL. Where you get the URLs from is up to you as a service provider to resolve. Typically you'd provide a service that your application can query to obtain the live event URLs to play.

**Comment by abellybeer** [comment]
So, it will be better if I load media.exolist.json externally? Because I can put new links there everytime they update. But my question is, once I open one live event, will exoplayer know that particular stream name had his manifest.mpd changed to a different one? This is what I am struggling to solve.
I want exoplayer to know when theres a new url to load a keep streaming without stop.

**Comment by ojw28** [comment]
`media.exolist.json` is just something our demo app uses. It's not part of the ExoPlayer library, and I wouldn't expect a real application to be using it.

> But my question is, once I open one live event, will exoplayer know that particular stream name had his manifest.mpd changed to a different one?

I don't really understand what this means. If you have a service that's providing multiple live events, you almost certainly need a server that your app can query to obtain the playback URLs and associated metadata for each event. This logic will be specific to your service and application.

Once you have a URL of a live event that you wish to play, at that point you should use ExoPlayer to play it. When you want to start playing a different live event, you should re-prepare the player for that event.

**Comment by abellybeer** [comment]
Ok, I understand your point. How do I re-prepare my player for next live event without having to close stream and reopening it? Once my live event ends, it shows "Playback failed" on screen so I need to reopen stream and then it starts new live event.

**Comment by ojw28** [comment]
If the live event is ending with a valid DASH manifest transformation then the player should transition to the ended state (rather than failing). If playback is failing then it's likely that the DASH live stream isn't ending in a compliant way.

When you want to start playing a new live event you should build a corresponding `MediaSource` and pass it to the player, just the same as the way you start playing the first live event.

If you want seamless transitions then you should really just have one DASH live stream that's continually updating to contain all of the content.

**Comment by abellybeer** [comment]
My DASH manifest changes its baseURL parameter when theres a new live event coming. Also, when I tried watching one live event and then forcing my php to send a DASH manifest from another live event, I noticed exoplayer gets confused with start time and current time. It throws playback failed and I have to move the time bar and then it updates all the info from new DASH manifest and start playing it normally.
It is possible to flush all this data and reload it again? Maybe a trigger that reloads all that data once the streams stops playing and restarts it.

**Comment by ojw28** [comment]
> My DASH manifest changes its baseURL parameter when theres a new live event coming.

I don't understand how this is compliant with the DASH specification. It's not valid just to do an arbitrary non-compliant manifest transformation and expect the player to figure out what you meant.

As per my previous responses, if it's a separate live event then it should probably be a separate manifest with a separate URL. You should "flush" the player by re-preparing it with a new `MediaSource` for the new live event. Alternatively, if this is a continuous live stream where one event is ending and the next is immediately starting, then you should start a new `Period` as a dynamic update within the existing DASH manifest.

Closing, since this is not an ExoPlayer issue.
