### ISSUE TITLE
Best way to retrieve current frame's Presentation Time Stamp from MPEG2-TS

### ISSUE THREAD

**Issue by CalebGartner** [google/ExoPlayer#6923]
### [REQUIRED] Searched documentation and issues
I've looked around in both the source code and documentation, specifically for [TimestampAdjuster](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/util/TimestampAdjuster.java) and PesReader. I know that the PTS values are extracted in [PesReader.java:219](https://github.com/google/ExoPlayer/blob/ea342a671c610916fdcdcb3c4f5c740ff1374719/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/PesReader.java#L219), and that the timestamp adjuster permanently converts them on line 237. I understand the conversion/adjusting process as well, but I cannot find a way to either reverse the conversion later on (since the adjusting depends on constantly changing previous PTS values) or map these values to the current frame.

I haven't been able to find any similar issues. I know that you can get the current frame's presentation time in [VideoFrameReleaseTimeHelper](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/VideoFrameReleaseTimeHelper.java), but that seems to correspond to playback time instead.

### [REQUIRED] Question
What is the best way to find the PTS value (from the MPEG2-TS) that corresponds to the currently displayed frame?

**Comment by ojw28** [comment]
This is not something we support. What are you actually trying to do (i.e., what's the feature for which this is needed)?

**Comment by CalebGartner** [comment]
I apologize; I should have been more explicit. In short, I'm trying to add the current frame's PTS value to a HTTP request header. I realize that it's an uncommon use-case.

I'm working with a setup that is streaming previously recorded TV content in MPEG2-TS format to the Exoplayer client. This means that the PTS values from the stream do not start at 0, but will usually start at hours or even days into the stream. These PTS values are, of course, extracted as mentioned above, then subsequently lost. However, I also need to support some server-side trickmodes, and this is currently implemented by triggering the trickmode request client-side (from the Exoplayer app), and sending the trickmode request to the server as additional HTTP headers that have been added to a custom DataSource. 

For instance, sending the server a trickmode request to skip forward by 30 seconds from a given PTS means retrieving the PTS associated with the currently displayed frame, adding it to the the DataSource's HTTP request headers via [setRequestProperty()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/HttpDataSource.html#setRequestProperty-java.lang.String-java.lang.String-), and re-preparing the current MediaSource to close the current connection and open a new one (that will have an MPEG2-TS 30 seconds from the sent PTS). 

Please let me know if there's anything else I can add or clarify.

**Comment by ojw28** [comment]
How does this feature handle PTS wrap-around every ~26 hours? Wrap-around of PTS in MPEG-TS is one of the reasons why we don't expose PTS directly as the playback position, because the playback position should always be increasing. Containers like FMP4 don't have this problem because they allow for timestamps to be represented with sufficient bits such that wrap-around will never occur.

I wonder whether it's possible for you to achieve what you want without direct support from ExoPlayer. For example, if you know the PTS corresponding to the start of the stream, then I think you're able to calculate the PTS corresponding to whatever the current playback position is as reported by ExoPlayer. Does that sound right? If so, is the PTS corresponding to the start of the stream something you already have, or else would being able to extract just that PTS from ExoPlayer be sufficient to support your use case?
