### ISSUE TITLE
UI components: Customize previous / next

### ISSUE THREAD

**Issue by wahdatkashmiri33** [google/ExoPlayer#6926]
In the **Exo-Player** video resumes from resumed position and i click on Previous control in Media Player then instead of directly playing previous video it seeks current video to 0 milliseconds and at that time when i click previous it goes to previous video.

 
   What i want is if i am in the middle of video then on clicking on previous it should directly playing previous video instead of resetting current video to start position.

**Comment by ojw28** [comment]
This is supported in `dev-v2` by the ability to pass a custom `ControlDispatcher` into UI components, which can do something different than `DefaultControlDispatcher` which is what now contains the logic for seeking to the start of the current piece of media rather than the start of the previous one.
