### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by dsotr** [google/ExoPlayer#6942]
### [REQUIRED] Searched documentation and issues
This link states the document used is deprecated, do we have evidence that it is still safe to use?
https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/BaseDisplayContainer.html#public-abstract-void-registervideocontrolsoverlay-view-videocontrolsoverlay

### [REQUIRED] Question
Are you planning to update this method using registerFriendlyObstruction ?
(link: https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/BaseDisplayContainer.html#public-abstract-void-registerfriendlyobstruction-friendlyobstruction-friendlyobstruction)

### A full bug report captured from the device
N/A: not related to a bug, we are investigating issues with viewability measurements through open measurement and noticed exoplayer is using a deprecated method; a confirmation would be highly beneficial.

### Link to test content
N/A

**Comment by andrewlewis** [comment]
The IMA extension currently depends on IMA 3.11.3, which should continue working until September per their [deprecation schedule](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/deprecation).

We'll update to the non-deprecated method once we do the upgrade for #6429. This can't be done yet because as part of bringing in the API changes in that release we are also relying on server-side changes that have not rolled out yet. Please follow that issue for progress updates.
