### ISSUE TITLE
Always keep showing next and previous button in notification

### ISSUE THREAD

**Issue by squti** [google/ExoPlayer#6961]
How could I keep showing the next and previous button on the ExoPlayer notification when there is just one MediaSource?

**Comment by marcbaechinger** [comment]
You could override `PlayerNotificationManager.getActions(Player player)` and return the list of actions you want to put into the notification at a given player state. Please read the Java doc of that method which gives some more details.

If the user taps the 'previous' or 'next' button in the notification, the call is delegated to `controlDispatcher.dispatchPrevious(Player player)` or `controlDispatcher.dispatchNext(Player player)` respectively. You can set your own `ControlDispatcher` (subclass `DefaultControlDispatcher` is easiest) to handle these actions.

Actually you have to use your own `ControlDispatcher` because the default control dispatcher can't do something sensible with a 'next' operation when there is only one single item in the playlist. I reckon you want to go to the start of the item again, but then it's the same what the 'previous' button would do which is there by default.

Besides all this: have you considered using custom actions which allows you to add your own button at the end of the standard actions? This provides a way to add custom button without the hassle of overriding `getActions`. Worth investigating in case you haven't yet.
