### ISSUE TITLE
different mimeType between FlacExtractor and LibflacAudioRenderer

### ISSUE THREAD

**Issue by xufuji456** [google/ExoPlayer#6979]
Hello, I don't figure out that the mimeType is "audio/raw" in FlacExtractor of FLAC extension. However, the specific mimeType is "audio/flac" in LibflacAudioRenderer. As s result, LibflacAudioRenderer couldn't work for FlacExtractor.

**Comment by kim-vde** [comment]
The `FlacExtractor` from the FLAC extension is not intended to be used with the `LibflacAudioRenderer` because the frames are decoded directly in the extractor and PCM data is therefore outputted. You have 2 possibilities:
- use the `FlacExtractor` from the FLAC extension and render with `MediaCodecAudioRenderer`, or
- use the (newly-released) `FlacExtractor` from the core library and render with any renderer able to decode FLAC frames (`MediaCodecAudioRenderer` from API 27+, `LibflacAudioRenderer`, `FfmpegAudioRenderer`).

**Comment by xufuji456** [comment]
@kim-vde Thank you very much. I got it.
