### ISSUE TITLE
HLS support for different GOP between variants

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#699]
Each variant in playlist may have different GOP, thus they may have different increasing speed of media sequence index. Currently when ExoPlayer meet this situation, it will keep loading that chunk playlist. It should reset the previous chunk index and keep loading the new TS of the new variant.

My workaround is modify these lines in HlsChunkSource:

````java
        if (chunkMediaSequence < mediaPlaylist.mediaSequence ||
                !variants[nextVariantIndex].format.equals(previousTsChunk.format)) {
          // If the chunk is no longer in the playlist or index of variants is switched. Skip ahead and start again.
          chunkMediaSequence = getLiveStartChunkMediaSequence(nextVariantIndex);
          liveDiscontinuity = true;
        }
````

Second way is to modify these lines:
````java
      if (mediaPlaylist.live && shouldRerequestMediaPlaylist(nextVariantIndex)) {
        return newMediaPlaylistChunk(nextVariantIndex);
      } else if (previousTsChunk != null &&
              !variants[nextVariantIndex].format.equals(previousTsChunk.format)) {
        chunkMediaSequence = getLiveStartChunkMediaSequence(nextVariantIndex);
        liveDiscontinuity = true;
        chunkIndex = chunkMediaSequence - mediaPlaylist.mediaSequence;
      }
````

**Comment by ojw28** [comment]
Is this actually a common thing? Do you have any examples? If it's rare then in my opinion it's far better to require the provider to change the way they're serving content, as opposed to having every player need to handle every obscure edge case. The latter just leads to all player implementations being bloated and error prone.

**Comment by bsysop** [comment]
It depends from providers, some "cheap chinese video transcoder" machines have no much options for change that (I know this very good, they are cheap but really poor), they can't change that and GOP come very irregular, i actually got this problem, but opposite to @b95505017 my playback need to decrease and not increase speed, because that i changed ExoplayerLib to don't play last files in PlayList, then now ExoplayerLib play about first files, then if got a GOP problems, so buffer hold they situation until GOP back to normal size (It means my Streaming can play about 8 hours, after that begins to Buffering every time).

I check how VLC handle that, they looks no much different than ExoPlayer, but look they don't play last 3 files in playback, they play the middle of the playlist moreless (About VLC i don't check that deeply).

**Example of irregular GOP when generating HLS from HTTP LiveStreaming:**
10s
10s
10s
10s
1s
1s
1s
1s
1s
1s

Then if ExoPlayer play the last 3 files, means we got 3s buffer, if LiveStream delay 2 seconds to deliver the content, then exoplayer go to last file, and this means no Buffer enough if got another problem, and this begins to buffering every time.

I think this problem are always in "Chinese transcoder", but this affects Exoplayer and of course another players.!.

**Comment by b95505017** [comment]
Thanks @bsysop's comment! 
Another example is that some streaming services provide a "Source" quality, accompanied by Low/Middle/High quality. The difference between them is that Low/Middle/High is transcoded, but the Source is not, it provide the original raw media data. 
So the problem is that Source may have different GOP than Low/Middle/High, and lots of major players could handle this situation. I think that ExoPlayer should handle this as well.

**Comment by Ood-Tsen** [comment]
Hello  @b95505017 , this case is not usual.
Do you mind to share sample links for this issue?

**Comment by ojw28** [comment]
- Yes; we should support different variants having different length segments.
- The fix proposed at the top of this issue does not look correct. I'll take a look at a different fix.

**Comment by ojw28** [comment]
I don't understand the HLS spec; it seems woefully under-specified with respect to how switching between variants should actually work. Specifically, the RFC states:

```A client MUST NOT attempt to use the Media Sequence Number to
   synchronize between streams - see Section 6.3.2.```

This is fine. It says that we shouldn't assume that media sequence numbers are the same across different variants, which is what this issue is tracking. Section 6.3.2 then says:

```Every time a Media Playlist is loaded or reloaded from a Playlist
   URI, the client MUST determine the next Media Segment to load, as
   described in Section 6.3.5, if it intends to play the presentation
   normally (i.e., in playlist order at the nominal playback rate).```

This is also fine. When we switch variant in a live stream we need to reload the playlist of the newly selected variant in order to discover the latest set of available media segments. So when we do this, we need to use Section 6.3.5 to determine which segment to use. Section 6.3.5 then says:

```The first segment to load is generally the segment that the client
   has chosen to play first - see Section 6.3.3.

   In order to play the presentation normally, the next Media Segment to
   load is the one with the lowest Media Sequence Number that is greater
   than the Media Sequence Number of the last Media Segment loaded.```

This is where things go wrong. The first paragraph only seems to make sense when starting playback, not when switching variant. The second paragraph doesn't apply, because the first quote above explicitly states that we cannot use the sequence number.

What's actually needed is a way to determine the absolute timing difference between segments in one playlist v.s. segments in another playlist. For on-demand (i.e. not live) streams this can be achieved by calculating the absolute start time of each segment. For live streams, however, this is not possible, because segments are being removed from the start of the playlists, and it's not possible to determine the absolute time that has elapsed prior to the first segment in a given playlist. So it seems it is not possible to determine the absolute timing difference, which makes guaranteeing a seamless switch impossible unless you make further assumptions beyond the specification (e.g. that you can actually use the sequence number).

So, does anyone know how this is actually supposed to work?

**Comment by jeoliva** [comment]
Good question. The lack of absolute time references makes crazy working with HLS and things like:
* Variant synchronization when working with live streams and DVR.
* Synchronization of live streams with alternate audio tracks.
* Synchronization of live streams using captioning.
* etc

Some of the things I used in the past as a solution for this:


* Option 1: This has some "computing cost" but provides the most stable behavior and what I guess iOS is doing after analyzing how iOS player behaves is using variant timestamps (PTS) to synchronize variant of live streams. For live streams these are relative time references but according to HLS specification:
	> Matching content in variant streams MUST have matching timestamps.
      This allows clients to synchronize the streams.

I said this has some cost because this means that when a sync is needed, we need to download segments, analyze its first packets to get at least the first timestamp and check if this is the segment we are looking for. Please, note that there are situations where when switching from one bitrate to other, we should start playing in the middle of the segment, for example, because current segment is longer than previous one.

Alternatively you can use:
* Option 2: ID3 tag "com.apple.streaming.transportStreamTimestamp". This is typically used for synchronizing webvtt live captioning and also alternate audio tracks. This field should be added to the audio elementary track and many encoders and CDNs have ways of embedding this field in HLS streams. You can not assume this field will be there but in case it is, you can use it as a trusted time reference.

> Each Elementary Audio Stream segment MUST signal the timestamp of its
   first sample with an ID3 PRIV tag [ID3] at the beginning of the
   segment.  The ID3 PRIV owner identifier MUST be
   "com.apple.streaming.transportStreamTimestamp".  The ID3 payload MUST
   be a 33-bit MPEG-2 Program Elementary Stream timestamp expressed as a
   big-endian eight-octet number, with the upper 31 bits set to zero.

* Option 3: Use the tag EXT-X-PROGRAM-DATE-TIME to define an absolute time reference for each variant. In case this is present, then you can use its value and packets timestamp to synchronize content coming from different variants. I haven't seen many streams using this field but, as this is defined in variant files (text based files), it shouldn't be complicated to be added by a content provider that knows his streams are using variants with different number of segments.

HLS spec:
> The EXT-X-PROGRAM-DATE-TIME tag associates the first sample of a
   Media Segment with an absolute date and/or time.  It applies only to
   the next Media Segment.

>  The date/time representation is ISO/IEC 8601:2004 [ISO_8601] and
   SHOULD indicate a time zone and fractional parts of seconds:

>   #EXT-X-PROGRAM-DATE-TIME:<YYYY-MM-DDThh:mm:ssZ>

>   For example:

>   #EXT-X-PROGRAM-DATE-TIME:2010-02-19T14:54:23.031+08:00

>   EXT-X-PROGRAM-DATE-TIME tags SHOULD provide millisecond accuracy.

>   See Section 6.2.1 and Section 6.3.3 for more information on the EXT-
   X-PROGRAM-DATE-TIME tag.


My humble opinion: Option 1 is needed to ensure we can always sync a variants of a stream. When working with option 1, both option 2 and option 3 are good to be implemented as a faster way of finding the right segment to be loaded.

**Comment by ojw28** [comment]
Option 1 is the only thing I can think of that would be guaranteed to work reliably, but it seems pretty unreasonable to me. It's also non-trivial due to PTS timestamp rollover; you could get unlucky! It seems better just to require that different variants have the same segment lengths and indices, as we do currently. Either that requirement really should be part of the HLS spec in the first place, or at least *something* should exist in the HLS spec for solving this issue!

Option 2 doesn't seem viable for the general case.

For Option 3, the RFC states:
```
The client MUST NOT depend upon the correctness or the consistency of the value of
the EXT-X-PROGRAM-DATE-TIME tag; its value is informative.
```
Which isn't particularly helpful.

**Comment by jeoliva** [comment]
Fully agree. There is another problem with option 1 that is keeping timestamps consistent across different variants is not easy. I know many companies working with complex configuration (dedicated encoders for specific bitrates or with primary/backup configurations) where keeping this HLS spec requirement is not possible. Mainly when you are not working with super expensive encoders that allows timestamp sync across different encoding devices. In fact, even a temporary high CPU load in the encoder could cause deviations in timestamps of an specific variant.

That's the reason because I said lack of an absolute time reference in HLS is something that made me crazy :). Timestamp is the option more reliable but there is not a totally reliable solution.

**Comment by ojw28** [comment]
I believe this if fixed in 1.5.10 and in 2.x.

**Comment by b95505017** [comment]
@ojw28 Is this issue fixed in this commit?
https://github.com/google/ExoPlayer/commit/f1c16565d26a37848b10a3131124961e110deae3

**Comment by ojw28** [comment]
Yes, that's correct.
