### ISSUE TITLE
Does Exoplayer support RTSP protocol videocamera streaming?

### ISSUE THREAD

**Issue by sindycarlo** [google/ExoPlayer#7004]

**Comment by phhusson** [comment]
Typing "rtsp" in the search field of issues clearly shows this is answered
in #55 and the answer is no.
Typing "rtsp" in the pull request field shows there is an implementation
available in https://github.com/google/ExoPlayer/pull/3854

**Comment by portizb** [comment]
@sindycarlo I am the author of the implementation available in the PR  #3854.
For now, the current branch is not merged with the latest changes on ExoPlayer/dev-v2.

From my own repository, you can get the most updated version and merged from dev-v2.

git clone -b dev-v2-rtsp https://github.com/portizb/ExoPlayer.git

**Comment by sindycarlo** [comment]
i have imported "implementation 'com.google.android.exoplayer:extension-rtmp:2.8.4'". i tested protocol rtsp for a live streaming video, and it's working. but doesn't work with rtsp live streaming webcam. i don't know why.

**Comment by portizb** [comment]
@sindycarlo ExoPlayer supports RTMP using the RTMP extension which is based on LibRtmp over JNI. You can download the source code from [LibRtmp Client for Android](https://github.com/ant-media/LibRtmp-Client-for-Android) or [ExoPlayer with RTMP and FLV](https://github.com/ant-media/ExoPlayer-with-RTMP-and-FLV-seek).

This extension does not work with RTSP, either in live broadcast using an RTSP server or from a webcam, because it only supports the rtmp protocol.

Therefore, if you need to use rtsp with ExoPlayer, you must use this library (It is in native Java code, it does not use JNI). To do this, you must use one of the following branches:

- From the repo PR #3854 (Not merged with the latest changes in dev-v2): 
[tresvecesseis:dev-v2-rtsp](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp) 

- From my repo (Merged from ExoPlayer dev-v2 and release-v2): 
 [portizb:dev-v2-rtsp](https://github.com/portizb/ExoPlayer/tree/dev-v2-rtsp)
[portizb:release-v2-rtsp](https://github.com/portizb/ExoPlayer/tree/release-v2-rtsp)

**Comment by Samrobbo** [comment]
Short answer is no, see the comments (thank you!) by phhusson and portizb.

**Comment by claincly** [comment]
RTSP support is added in ExoPlayer 2.14.
