### ISSUE TITLE
Unknown enum constant AnnotationTarget.ANNOTATION_CLASS

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#7007]
I didn't touch anything. This error occurs when you compile the project.

![image](https://user-images.githubusercontent.com/31779629/75122541-86429f00-56af-11ea-8bc1-eb0e3bcb731e.png)

**Comment by tonihei** [comment]
That's a known issue caused by the fact that a Kotlin annotation for Java code is defined in Kotlin instead of Java (see [here](https://youtrack.jetbrains.com/issue/KT-33141)). This should be fixed as soon as we can update our dependency version to 1.3.70.

But it's not an actual problem and you can ignore the warning for now.

**Comment by inat-tv** [comment]
Ok thanks bro

**Comment by inat-tv** [comment]
> That's a known issue caused by the fact that a Kotlin annotation for Java code is defined in Kotlin instead of Java (see [here](https://youtrack.jetbrains.com/issue/KT-33141)). This should be fixed as soon as we can update our dependency version to 1.3.70.
> 
> But it's not an actual problem and you can ignore the warning for now.

Ok thanks bro

**Comment by tonihei** [comment]
This issue is fixed now, closing.
