### ISSUE TITLE
DRM failure notifications / fallback support

### ISSUE THREAD

**Issue by dbrain** [google/ExoPlayer#7012]
### [REQUIRED] Use case description
Our users devices have various levels of widevine support. When widevine fails, we fall back to other DRM methods (expressplay, clearkey),

As of 2.11 the way `ExoMediaDrm` is created has changed to be via a `Provider`, this has changed the way the errors are thrown and has made it awkward to implement DRM fallback (if I'm not missing something).

Essentially there's a few issues:
- `FrameworkMediaDrm.DEFAULT_PROVIDER` try/catches `UnsupportedDrmException` and returns a `DummyExoMediaDrm`. When this happens playback will continue without rendering the video (black screen) which as far as I can tell is undetectable.
- If you implement your own `ExoMediaDrm.Provider` to remove the try/catch the exception is thrown in an uncatchable spot by the usual error handlers

The only solution I could find was using an `AppManagedProvider` and creating the `FrameworkMediaDrm.newInstance` at a predictable spot so we can capture the `UnsupportedDrmException` ourselves. But this opens us to leaking `ExoMediaDrm` instances, which is what the whole `ExoMediaDrm.Provider` deal was about.

### Recipe to produce issue
- Try to play widevine encrypted content on a device without widevine support (using FrameworkMediaDrm.DEFAULT_PROVIDER`), see screen go black
- Alternatively, implement a `ExoMediaDrm.Provider` that always returns `DummyExoMediaDrm` and give it to `DefaultDrmSessionManager.Builder()` and see screen go black during playback with no notification
- Alternatively again, implement a `ExoMediaDrm.Provider` that just throws an exception. See the app crash in a (as far as I can tell) uncatchable way rather than going through usual player error callbacks

### Proposed solution
Allow `UnsupportedDrmException` from a provider to bubble up like any other error. If the content is secure and the renderer fails because it can not be decrypted playback shouldn't continue.

Essentially I want to be able to know that the DRM has failed and the secure content can not be played so I can try other methods / show the user an error instead of a black screen.

### Alternatives considered
Mentioned above, but for now it's essentially reverting the functionality to pre `ExoMediaDrm.Provider` by using an `AppManagedProvider`. But this opens us to leaking `ExoMediaDrm` instances.

**Comment by AquilesCanta** [comment]
>  this has changed the way the errors are thrown and has made it awkward to implement DRM fallback

As you correctly point out in "Alternatives considered" you can use an `AppManagedProvider` to use exactly the same approach as before the introduction of `ExoMediaDrm.Provider`, so 2.11 shouldn't make anything awkward. You can still do things as before. 

> But this opens us to leaking ExoMediaDrm instances, which is what the whole ExoMediaDrm.Provider deal was about.

It's the way it was before 2.11. And the idea behind an `AppManagedProvider` is that the App takes care of MedaDrm resource management, as before 2.11.

=========

**Why is the proposed solution not the best option?**

Because that would prevent ExoPlayer from playing other variants in the same media that are supported. For example, if the stream has clear SD and widevine protected HD, if we don't surface the MediaDrm creation exception we can still play the SD tracks.

=========

**What's the solution then?**

To provide a bit of guidance, I'm assuming you want to check whether the device supports Widevine or not. I can think of many solutions of doing this:

- The way the demo app does it.
```
if (Util.SDK_INT < 18) {
      // DRM is unsupported on API < 18.
    } else if (!MediaDrm.isCryptoSchemeSupported( /* DRM scheme, e.g. widevine */)) {
      // DRM scheme unsupported. Depending on the scheme, worth reporting.
    } else {
      // We support DRM.
    }
```
- Look for the current track selection information for UNSUPPORTED_DRM tracks.
- If you **really** want to catch the MediaDrm instantiation exception, just provide a default-like provider and when catching an exception return the dummy provider (for the reasons explained above) but signal your app of the exception and do things as before.
- Instantiate and release a MediaDrm in your app. This is most likely the worst option.
