### ISSUE TITLE
Spontaneous Ad completion using IMA SDK extension

### ISSUE THREAD

**Issue by janhofman** [google/ExoPlayer#7016]
Hello,

I'm trying to make an app with ExoPlayer and its Ima Extension and I've encountered an issue:

**Introduction**
ExoPlayer version: 2.11.1
I have `MainActivity` with fragment that has `com.google.android.exoplayer2.ui.PlayerView` , this activity is locked to portrait mode.
I have another activity called `VideoFullscreenActivity` which contains only `PlayerView`
If user requests fullscreen version of video I take the existing `SimpleExoPlayer` and assign it to the new view along with same `AdsMediaSource` , `ImaAdsLoader`, no new objects apart from the `PlayerView` itself are being created.

**Issue**
Let's say there are multiple pre-rolls and first Ad is playing. When I go to fullscreen, everything works as intended. Ad continues to play as you would expect. However when I go to fullscreen and last pre-roll is playing that ad gets "skipped" and I get callback that it was `AdEvent.AdEventType.COMPLETED` 

Is that intended behavior?

**Comment by jakub-tausk** [comment]
Hello Andrew,

please give advice.

Thank you

**Comment by andrewlewis** [comment]
It sounds like you are switching between `PlayerView`s when transitioning between window/full-screen. The IMA SDK mostly runs its code in a `WebView` that gets inserted on top of the player output view (assuming you are using `PlayerView` as the `AdViewProvider` when creating the `AdsMediaSource`). I wonder whether the change of player view is causing the `WebView` running the IMA SDK to get destroyed, or the IMA SDK is becoming unhappy in some other way due to a visibility change.

Could you try keeping the `ImaAdsLoader` but instantiating a new player and `AdsMediaSource` during the transition to see if that fixes it?

To make this as seamless as possible you could alternatively try making your own `FrameLayout` and passing that as the ad view group in a custom `AdsLoader.AdViewProvider`. The idea is to make sure IMA's web view doesn't get destroyed across the transition. This might require reorganizing the app to avoid the activity transition (so you can keep the same frame layout), so might not be feasible.

The behavior with an ad getting skipped across what is effectively backgrounding/resuming sounds like #4140, which will be fixed when the new ads managers have been released and are used by the extension, tracked by #6429.
