### ISSUE TITLE
Supporting viewport-independent OMAF video.

### ISSUE THREAD

**Issue by xujunjie21** [google/ExoPlayer#7018]
I want to use the exoplayer to implement viewport independent omaf video. The platform has completed the conversion of MPD files of the dash protocol. How can I parse, decode and splice multiple tile videos in the exoplayer.

**Comment by Samrobbo** [comment]
Hi,

As far as I know, ExoPlayer doesn't support this at the moment.

**Comment by andrewlewis** [comment]
Just to add to what Sam wrote: it's beyond the scope of this tracker to give detailed guidance on parsing/rendering for this format, but if you want to implement it yourself you will probably need to make customizations like:
- Reading and handling the OMAF metadata. This may require a custom extractor if we don't surface the metadata currently because it's not in part of the MP4 container that we treat as generic metadata.
- Feeding the decoder(s) the right bitstream. I don't know the details of the format, but I suspect this will involve either having multiple video renderers to decode tiles separately (requiring changes to the track selector) or constructing valid access units by joining tiles.
- Having decoder(s) render to off-screen `SurfaceTexture`(s), and rendering the result using a mesh to an output view.

Aside: ExoPlayer does already support spherical video rendering, I think based on [this spec](https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md), so you may be able to leverage some existing code there.

This is probably quite a big project, and it's unlikely we'd want to merge support unless there is a good justification for taking on the maintenance cost of the extra code (e.g., if the format is very popular).
