### ISSUE TITLE
DRM license response with caching.

### ISSUE THREAD

**Issue by vengateshvengi** [google/ExoPlayer#7032]
we are implementing widevine proxy on top of license server.That proxy server will cache the license server response based on each content-id and my question is.
Does exoplayer will play on passing the cached license response for the widevine license request?
On executing this process ,exoplayer throws an error :
       Failed to handle key response (2000)

**Comment by AquilesCanta** [comment]
I think this is a server-side question not in the scope of this issue tracker. I imagine license responses are request-specific and caching requires specific support.
- If you are using a media-serving stack, I'd contact them.
- You may be able to get some existing material / help from the [shaka packager](https://github.com/google/shaka-packager/issues) issue tracker.
- Perhaps it's also worth looking in the [widevine website](https://www.widevine.com/) for useful resources.
- It's always a good idea to ask in a general Q&A site, like stack overflow.

**Comment by ojw28** [comment]
> That proxy server will cache the license server response based on each content-id and my question is.

@rrfrias could confirm this for sure, but I don't think that's a valid thing to do. My understanding is that:

1. Every license request generated by a device is different (even if for the same content id)
1. When a license request is generated by a device, it will only accept a license response that was generated by the license server using that exact request

If this understanding is correct, then getting `Failed to handle key response (2000)` is expected because your caching layer causes a mismatch between the request and response. In particular, you're trying to pass a response that was generated from some previous request, rather than from the current request.

**Comment by rrfrias** [comment]
I concur with ojw28@'s response. Caching a license at the proxy service is not a supported use-case. You might want to discuss whether there are alternate ways of achieving your goals by contacting the widevine partner engineering team (or https://www.widevine.com/contact).
