### ISSUE TITLE
How to determine if a format is downloaded/cached?

### ISSUE THREAD

**Issue by Cubxity** [google/ExoPlayer#7044]
When filing a question:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Searched documentation and issues
I have searched for issues on the GitHub repository.

### [REQUIRED] Question
I would like to know how to determine if the format is available offline/cached (DASH & HLS). This will be used for quality/format selector. Also, how to choose the downloaded format by default? Since sometimes the player plays streams that are not cached/downloaded.

**Comment by krocard** [comment]
I'm guessing by format, you mean a specific Stream ? DASHS &HLS can both stream from remote and local resources.
I think you want the TrackSelector to select the best quality if the content is local. I could not find such option in DefaultTrackSelector. @tonihei Do you know if this feature is already possible without building a custom DefaultTrackSelector?

**Comment by Cubxity** [comment]
@krocard 
- I would like to know which Format in the track group is available offline (in order to show in the quality selector)
- And yes I would like the TrackSelector to also select the best quality if content is local.

**Comment by tonihei** [comment]
`DownloadHelper` already chooses the best supported quality by default, so no need to change any options here. Otherwise you can customize the selection by setting custom `DefaultTrackSelector.Parameters` if you like.

You can query the already downloaded data as described in https://exoplayer.dev/downloading-media.html#querying-downloads. Each `Download` contains a list of `StreamKeys` which are indices into the DASH manifest or HLS playlist for the downloaded formats. If you want to store additional metadata with the downloads (e.g. resolution), you can add any data you like with second `byte[]` parameter when calling `DownloadHelper.getDownloadRequest`.

**Comment by Cubxity** [comment]
Also, another thing, would it be possible to download a separate subtitle file (f.ex Subrip) with a DASH/HLS download?

**Comment by tonihei** [comment]
You can download it completely separate and then merge them back together at playback time using a `MergingMediaSource`. There is an open feature request to download them together as a bundle in #5615

**Comment by tonihei** [comment]
Assuming the question was answered and closing the issue. If not, please reopen.
