### ISSUE TITLE
UnrecognizedInputFormatException: None of the available extractors...

### ISSUE THREAD

**Issue by morfeo9950** [google/ExoPlayer#7045]
Hi, im having this issue with the demo app, im using this link ( https://1fichier.com/?jpm7ht5bm7bn17a5yqzs ) [](https://1fichier.com/?jpm7ht5bm7bn17a5yqzs)   to test the demo app in the hls section, i only add my hls test stream in the media.exolist.json, it is giving me this error and in the player shows the Playback failed message, the original vid is a .mkv and i use a free software to create the .ts files, vodobox is the freeware im using, i test my hls in an online web player from akamai website and it was working fine, slow but still working, i dont know if it is a problem with my hls or video container or something else, thanks for any help you could provide.

**Comment by icbaker** [comment]
We need more information.

Please complete the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md) in full (copy paste it into a new comment here), including attaching a bug report taken after reproducing in the demo app, as requested in https://github.com/google/ExoPlayer/issues/6892#issuecomment-594614728.

**Comment by icbaker** [comment]
This error comes from ProgressiveMediaSource, not HlsMediaSource, so it means the demo app is incorrectly trying to play your HLS file as a progressive (i.e. non-adaptive, non-chunked) file.

This is likely because when reading the JSON file, the demo app guesses the type of the stream based on the file extension. If it doesn't see an extension, or recognise it, then it just falls back to the default of ProgressiveMediaSource. Since your stream URL doesn't end in `.m3u8`, it doesn't try to use the HlsMediaSource.

Can you try with this JSON entry and see if works (i.e. we explicitly tell the demo app to use the HLS MediaSource):

```JSON
{
  "name": "Issue 7045",
  "uri": "https://1fichier.com/?jpm7ht5bm7bn17a5yqzs",
  "extension": "m3u8"
}
```

**Comment by MokshBhansali** [comment]
i Will also face this error when i'm fetching my **VIDEO URL** from firebase storage.
this is error i'm face on my terminal :- 


E/flutter ( 4274): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream., null)
E/flutter ( 4274): null

This is my Firebase video url 
https://firebasestorage.googleapis.com/v0/b/pops-72d37.appspot.com/o/2019_10_02_12_34_05_trim.mp4'%7D?alt=media&token=081a006c-1367-4bba-8ebb-50b3aabe8487
if any one have solution just revert back.
Thank you

**Comment by icbaker** [comment]
@MokshBhansali 

The URL you provided works fine for me in the [demo app](https://exoplayer.dev/demo-application.html#1-editing-assetsmediaexolistjson) with this JSON:

```
{
  "name": "Issue #7045",
  "samples": [
    {
      "name": "Firebase URL",
      "uri": "https://firebasestorage.googleapis.com/v0/b/pops-72d37.appspot.com/o/2019_10_02_12_34_05_trim.mp4'%7D?alt=media&token=081a006c-1367-4bba-8ebb-50b3aabe8487"
    }
  ]
}
```

Your problem seems unlikely to have the same root cause as OP's issue (despite the error messages seeming similar), so if you need further help please file a new 'Question' issue and make sure you fill in the issue template, including attaching a full bug report from `adb bugreport`.
