### ISSUE TITLE
Playback retry with tokenised DRM info

### ISSUE THREAD

**Issue by xirac** [google/ExoPlayer#7062]
### [REQUIRED] Searched documentation and issues
I had a look into SimpleExoPlayer.retry() method.

### [REQUIRED] Question

I'm playing Dash + Widevine streams on a CDN using ExoPlayer 2.11.1  

When starting a stream playback:
1. The application is requesting an the CDN streamer final uri to the load balancer
2. The application is requesting a tokenised DRM uri to the service platform
3. The application use DRM uri to create a HttpMediaDrmCallBack and build a DrmSessionManager
4. The application use stream final uri + DrmSessionManager to build a DashMediaSource
5. This DashMediaSource is used to prepare the SimpleExoPlayer instance
6. As soon as the player request the DRM uri, this uri is not valid anymore

When a CDN streamer fails to deliver the stream, I'm retrying the playback on another CDN  streamer like this:
1. The application is catching the ExoPlaybackException.TYPE_SOURCE error as soon as the CDN stream fails
2. The application is request a new CDN streamer final uri to the load balancer
3. The application is requesting a new tokenised DRM uri to the service platform
4. The application use DRM uri to create a HttpMediaDrmCallBack and build a DrmSessionManager
5. The application use stream final uri + DrmSessionManager to build a DashMediaSource
6. This new DashMediaSource is used to prepare the SimpleExoPlayer instance **without reseting position and state**

From my tests, it works pretty well, but I'm wondering if there is a cleaner way to do this same or part of this job on ExoPlayer side rather than on application side.
My main concern is on step 3 which could be avoided if player was reusing the previous descrambling data instead of requesting an expired DRM uri at step 6.

Thanks for your help.

**Comment by tonihei** [comment]
It sounds as if you can cut this process short with injecting a custom `DataSource` in the `HttpMediaDrmCallback` passed to the `DefaultDrmSessionManager`.

This custom `DataSource` will be used every time a key or provisioning request is sent. So if your uris become invalid, it makes sense to just use another uri the next time a request is started. This could be an automatic retry for example that happens even before step 1 (catching the catching the ExoPlaybackException.TYPE_SOURCE error). You can probably use a `ResolvingDataSource` for that and handle all the uri resolution in the `resolve` method.  Note that you'll need to provide some custom URI as the drmLicenseUri to pass in all metadata that your `Resolver` needs to resolve to the actual uri, or just use the request properties to pass required metadata around.

If you do this, then you can also just use `player.retry()` because the `DataSource` takes care of resolving the Uri.

Aside: The first step above (The application is requesting an the CDN streamer final uri to the load balancer) can also be handled in the same way. You can pass a media identifier to DashMediaSource ("myscheme://mediaId=34456") and then use a `ResolvingDataSource` to resolve to the actual streamer URI when needed.

**Comment by tonihei** [comment]
Assuming the question was answered and closing the issue. If not, please reopen.
