### ISSUE TITLE
Video and audio freezes with DASH manifest

### ISSUE THREAD

**Issue by yes-eng** [google/ExoPlayer#7071]
Similiar complain as describes in issue #1536.

The issue was repredused with SEI Robotics box, model SEI500Y with Amlogic s905x2 SOC.
Android version 9.0.0

### [REQUIRED] Issue description
With DASH we can see multiple inquiries to the CDN servers which each time choose different server while with HLS we can see single inquiry to one of the servers.
This behavior cause video and audio freezes.

### [REQUIRED] Version of ExoPlayer being used
2.11.1

### [REQUIRED] Device(s) and version(s) of Android being used
Its beeen seen with SEI500Y with Android 9.0.0
The issue is repreduced few times in hour

**Comment by tonihei** [comment]
Could you please provide more information that would help use to answer this query?

- Does this issue only happen on the mentioned device or does it also happen on other devices?
- Can you provide us with test DASH or HLS links that would allow us to reproduce?
- Can you also clarify what the actual problem is exactly? What kind of "inquiries to the CDN" are you seeing, for what, and how often? And what would you expect to see instead?
