### ISSUE TITLE
How to reSample a wav file to support exoPlayer?

### ISSUE THREAD

**Issue by ar-karimi** [google/ExoPlayer#7090]
Is there any way to **upSample** a **wav file** with **2000Hz** to **8000Hz** sample rate to **supporting** Exo Player? Does the **SonicAudioProcessor** class have that capability? I couldn't use third-party libraries to do that. Please help me

**Comment by marcbaechinger** [comment]
`SonicAudioProcessor` won't help you with this I'm afraid. 

I understand you can't play 2000Hz files because playback is not supported by the framework [as mentioned here](https://source.android.com/compatibility/android-cdd#5_5_audio_playback).

I don't think there is an easy way to re-sample this on the fly. Actually doing this once on the server for all clients, would be the best option. There are chances you are not able to do this for some reasons.

You can try to play the 2000Hz file with the [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) which does not require the framework for playback but does everything in software. It may be able to play it. I'm not sure though, but if there is no easy upsample option it's probably worth a try.

**Comment by andrewlewis** [comment]
You could also try `SonicAudioProcessor.setOutputSampleRateHz(8000)`. To use that you need to pass in the audio processor into the chain of audio processors in the audio sink. Marc's suggestions (FFmpeg extension or server-side transcoding) will likely give better quality though.
