### ISSUE TITLE
Modules 'base' and 'player' contain entry 'res/layout/exo_playback_control_view.xml' with different content.

### ISSUE THREAD

**Issue by FlorentDambreville** [google/ExoPlayer#7102]
### [REQUIRED] Issue description
I have an app with multiple Dynamic Modules. 

In order to add the download feature to my app, I need to import the `DownloadNotificationHelper` component into my "base" module. So I've added the ExoPlayer UI dependency : `com.google.android.exoplayer:exoplayer-ui:2.11.1` to my "base" module. 
Since I already have this dependency in the module "player" Now I have this compilation error message : 
```Modules 'base' and 'player' contain entry 'res/layout/exo_playback_control_view.xml' with different content.```

### [REQUIRED] Reproduction steps
In a multi modules android project, just add the dependency `com.google.android.exoplayer:exoplayer-ui:2.11.1` in the base module and an another module and try to compile.

### [REQUIRED] Version of ExoPlayer being used
Version `2.11.1`

**Comment by marcbaechinger** [comment]
I've created a project with a base module and a dynamic feature module. Both are having a dependency to the ui module of ExoPlayer. 

I can run the app in the emulator and when I unpack the APK i can find the `exo_playback_control_view.xml` in the APK. So it seems that the merge was successful. 

Are you using ui components in one or the other or in both modules? I currently hava a layout file in each module which is using the `PlayerView`. Can you think of something I need to depend on in one or the other module to be able to reproduce the issue?

**Comment by FlorentDambreville** [comment]
I am using `PlayerView` with a custom `exo_playback_control_view.xml` in the player module. In the base module I only use the `DownloadNotificationHelper`.
The player module depends on the base module (I have `implementation project(':app')` in the player build.gradle)

**Comment by marcbaechinger** [comment]
Ok, this matches the error message. :) It seems that there is an issue when merging, because `exo_playback_control_view.xml` is different in the modules. That's actually not an ExoPlayer issue, but a problem of the setup. I'll try to get some advise whether this can be avoided or if this a limitation we need to work around somehow.

For a quick solution, you can rename your custom layout file and  declare the layout id in the `app:controller_layout_id` attribute of the PlayerView element. Given you rename your file to `custom_playback_control_view.xml`, this should then be something like that:

```
<com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      app:controller_layout_id="@layout/custom_playback_control_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>
```

This should help as a quick fix.

Another thought: If you declare the exoplayer-ui module in in your base module as api you would not need that ui dependency in the player module again I think. Can you build your app that way?

```
api 'com.google.android.exoplayer:exoplayer-ui:2.11.3'
```

**Comment by FlorentDambreville** [comment]
Nice ! 

Thanks for the quick fix, I'll try it. :)

Also, I've tried to add the api dependency to my base module  
```api 'com.google.android.exoplayer:exoplayer-ui:2.11.3'```
And I get the same error message :/

Please, let me know if you find an other way to fix this issue. And let me know if you need me to open an issue elsewhere.

**Comment by ojw28** [comment]
Given the resources are different, I think they probably should have different names. So I think the solution suggested by @marcbaechinger is probably the correct one :).
