### ISSUE TITLE
Demo App: Allow forcing usage of the license url of the MediaItem

### ISSUE THREAD

**Issue by albertdaurell** [google/ExoPlayer#7114]
### Use case description

Testing samples from [media.exolist.json](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json) we set the `drm_license_url` but it's not forced so it's using the one from the KeyRequest by default.  `drm_license_url` is only used if the media does not contain/define any license.

A long time ago it was added from this pull [Add possibility of forcing a specific license URL in HttpMediaDrmCallback #3136](https://github.com/google/ExoPlayer/pull/3136) a way to be able to force the license url, setting `forceDefaultLicenseUrl` to `true`:

`public HttpMediaDrmCallback(String defaultLicenseUrl, boolean forceDefaultLicenseUrl, HttpDataSource.Factory dataSourceFactory)`

But from samples we can NOT force to use the drm_license_url by default and avoid using the one from the KeyRequest/media. If the media contains the url... there is no way to override it to do our internal tests without modifying the source code.

There was a similar question a long time ago about this https://github.com/google/ExoPlayer/issues/2958

### Proposed solution

We have 2 ways to fix this issue, from my point of view if you set this url is because you want to use it so for me the simple solution is this one:

**Forcing always the license url**

We only need to add the forceDefaultLicenseUrl ( true ) from PlayerActivity:

https://github.com/google/ExoPlayer/blob/62092e664586175107a3aaac3e1b0efa3059049f/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L544

`new HttpMediaDrmCallback(licenseUrl, true, licenseDataSourceFactory);`

### Alternatives considered

- We can define a new parameter from PlayerActivity 
  `public static final String DRM_FORCE_LICENSE_URL_EXTRA = "drm_force_license_url";`
-  Add the parameter to the DrmInfo class.
- Use this parameter from examples. 
- etc...

### Comments

If you want I can do the pull request but at least, at first, I wanted to know if you prefer the first option or the second one or you prefer not doing it and I can modify the repo locally or clone my own repo...

Thanks in advance

**Comment by marcbaechinger** [comment]
We expect quite a few changes regarding the `Sample` class in the demo app as it will be replaced by a `MediaItem` class. So doing this for the `Sample` class would not make much sense now, but you are just in time so that we can make sure that this will be possible with the new MediaItem.

I think I agree that it would make sense to always set `forceDefaultLicenseUrl` when the licenseUri is set in the MediaItem/Sample. A developer could just not declare the `licenseUri` if the uri in the media should be used.

I'll update this issue when this has been implemented with the MediaItem in this sense.
