### ISSUE TITLE
How to improve buffering

### ISSUE THREAD

**Issue by silvershort** [google/ExoPlayer#7118]
I am loading the video with the code below.

```
public class MainActivity extends AppCompatActivity {

    PlayerView exo_playerview;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        exo_playerview = findViewById(R.id.exo_playerview);

        DataSource.Factory dataSourceFactory =
                new DefaultHttpDataSourceFactory(Util.getUserAgent(this, Util.getUserAgent(this, this.getString(R.string.app_name))));

        MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse("https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv"));
        SimpleExoPlayer simpleExoPlayer = new SimpleExoPlayer.Builder(this).build();

        exo_playerview.setPlayer(simpleExoPlayer);
        simpleExoPlayer.prepare(mediaSource);
    }
}
```

If you move the seekbar to the beginning while watching a video, buffering takes place.

Buffering takes at least 0.5 seconds and sometimes takes more than 1 second.

I think this is a bad experience for users.

Is there any way to improve this?
At least I want the buffering to be faster when moving to a scene I've already seen.

**Comment by marcbaechinger** [comment]
You may want to look into [`CacheDataSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java) do apply caching of data which has already been downloaded.

Wrap your `DefaultHttpDataSourceFactory` in a `CacheDataSourceFactory` and provide a `SimpleCache`. With this data is downloaded once only and seeking backwards reads from local data instead of from the network. 

> At least I want the buffering to be faster when moving to a scene I've already seen.

Looking ahead is a bit more complicated as you can imagine. :)

If you know what the user is going to watch you can download the content beforehand. The offline classes use the same cache as the `CacheDataSource`.  I think the challenge will be more to predict user behaviour though.

**Comment by silvershort** [comment]
Thank you for answer.
Caching was difficult, so the initial buffering time was improved by adjusting the minBufferMs value of DefaultLoadControl.
