### ISSUE TITLE
video not visible only audio is playing below android version 8.0

### ISSUE THREAD

**Issue by trayambak** [google/ExoPlayer#7146]
in xml if i set ' app:surface_type="surface_view" ' than only audio is playing below 8.0 android devices and when i am calling setZOrderOnTop(true) on playerview surfaceview than controls are not visible. 
Please help if i am doing something wrong.

**Comment by ojw28** [comment]
I think it's probably expected that `setZOrderOnTop` would render the surface on top of the controls (hence meaning they're not visible). You shouldn't have to do that, however.

Does the problem occur in the [main ExoPlayer demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main)? If not then it's most likely an application issue with your app, which you'll need to debug. If it does then please properly fill in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) so that we can investigate (please copy the template into this issue, rather than filing a new one).
