### ISSUE TITLE
Shoutcast audio stream glitching

### ISSUE THREAD

**Issue by pi-mad** [google/ExoPlayer#7176]
I have updated the player to 2.11.3 from a very old version as i'm using a template and building it to how I want it so it had 2.9.6 installed which the stream works with no problems and no glitching but as I upgraded to 2.10.0 or higher it starts glitching.

Look forward to your reply

**Comment by andrewlewis** [comment]
We need a link to the stream you're trying to play to diagnose this effectively.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by pi-mad** [comment]
Email sent with the stream link and some other info!

**Comment by pi-mad** [comment]
Hi, i'm just messaging as I haven't received any feedback from my issue?

**Comment by ojw28** [comment]
I tried playing the provided stream in our demo app, and it plays fine there. You can try this for yourself using the instructions [here](https://exoplayer.dev/demo-application.html).

I don't know what the template project that your app is using does, but it seems like an issue with the way the template has integrated ExoPlayer, rather than an issue with ExoPlayer itself.
