### ISSUE TITLE
How to support seamless playback between jumping to ad h5 web detail page and backing to player actiivity?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#7200]
As the title, I using my own ad SDK, not using IMA extension.  The ad need to jump the h5 detail web page when user click the button,   how to support pause the player when jump to h5 detail page and resume the player when back to the player activity?

**Comment by AquilesCanta** [comment]
Can we rephrase the issue as a question on how to seamlessly transition playback from one activity to the other? Is the ads part related in any way? Please clarify.

If yes, then unfortunately this is something that needs to be fixed by the app since it's inherent to activity lifecycle, which is out of ExoPlayer's control. There's is plenty of material about this available, in this issue tracker (e.g. #4706, #7155) and in other places (e.g. [Stack Overflow](https://stackoverflow.com/questions/51697109/exoplayer-video-transition-from-one-activity-to-other-without-stopping-plaback)).

**Comment by Romantic-LiXuefeng** [comment]
@AquilesCanta  Thanks!
