### ISSUE TITLE
Extend to support raw H264 video stream in ExoPlayer Over Web sockets.

### ISSUE THREAD

**Issue by rajashekarvys** [google/ExoPlayer#7209]
**Scenario**
We are opening a web socket to our backend which is providing a raw H.264 stream.

**What We've Tried**
as suggested in this issue #3503 & #5175 we have converted Ac3Extractor to H264Reader.  Our Extractor is receiving the bytes from the DataSource and passing them to H264Reader.consume(ParsableByteArray).
We have used 
detectAccessUnits true and 
 reader.packetStarted(0, FLAG_DATA_ALIGNMENT_INDICATOR);

**Problem:**
Only one frame is playing.
We have observed in `startNalUnit(absolutePosition, nalUnitType, pesTimeUs);`
`pesTimeUs` is always 0.

@andrewlewis have suggested in issue #5175 to assuming a constant frame rate. We have tried multiple way to increment the `pesTimeUs`  but video is playing too fast or a playing single frame only.

Can u guys please suggest a way to resolve it.

**Comment by AquilesCanta** [comment]
I can see only two options:
- **Recommended**: Put the stream in a container format, which will include timing information which is currently missing (TransportStream or FragmentedMp4).
- Or write your own extractor (it will look a lot like what you have already I think) but arbitrarily assigns a duration to each frame (I guess you know the stream's framerate), you just manually increase the output timestamp.

If at any point you need audio/video synchronization, you'll definitely have to pack stuff into a container format. Hope this helps. Please let me know if I didn't answer your question. Please close otherwise.

**Comment by rajashekarvys** [comment]
Thanks for quick response.

We have tried increasing timestamp by manually video playing as  expected.

We would like to try **Recommended** way as well. Can you suggest a way to convert stream in to container format (Raw H264 byte arrays to FragmentedMp4)

**Comment by AquilesCanta** [comment]
You'll need to use a tool for that. Maybe ffmpeg or derivatives? This is out of the scope of this issue tracker though. I'm sure a quick research will answer this for you. Closing this now. Good luck!
