### ISSUE TITLE
Issue playing HLS with streams that include low-bandwidth variant (TS) without a video track

### ISSUE THREAD

**Issue by johanlindquist** [google/ExoPlayer#721]
We are seeing issues in the player when playing a stream which contains a variant for low bandwidth that does not have any video track in it (TS file with audio-only).  Higher bandwidth variants contain both video and audio.  There are NPE's occuring since the Extractor#getSampleQueue will not have the queue for video when the variant is hit.

Another related issue is that if the player starts with the audio-only variant, video will never be enabled.

Any immediate ideas on how this could be resolved?  We are almost thinking that there is a need for a dummy reader to be included if the video track suddenly "disappears" in this way.

**Comment by ojw28** [comment]
In order of preference:
1. Use DASH or SmoothStreaming instead.
2. Include the CODECS attribute in the HLS master playlist. The player will filter out the audio only variant in this case.

**Comment by johanlindquist** [comment]
Hi

1. I wish we could but we need to support both Android and iOS with the same content
2. This is a work-around that we have used in the past (especially for audio-only which are AAC files) but for this particular issue, we need the audio-only variant to play.    We have thought about re-encoding the content with a still-image but that is not an option in this case.

**Comment by ojw28** [comment]
If I understand correctly, many service providers achieve (1) by transmuxing DASH to HLS at the edge of their networks. It's also not ideal to provide a sub-optimal experience on Android devices due to iOS limitations, although I acknowledge there are practical/cost reasons why you may choose to do this.

Regarding (2), you should include the CODECS and RESOLUTION tags if at all possible in all HLS streams, regardless of the issue being tracked here. Among other things, doing so will enable devices to correctly filter out streams that they're not capable of playing.

We have no short term plan to support seamless switching between audio and audio+video variants. It's something we'd like to support eventually, but it's not going to happen any time soon. When it does arrive, it'll be in the context of supporting dynamic changes to available tracks.

**Comment by ojw28** [comment]
This is also tracked by #545. Closing this one.
