### ISSUE TITLE
PlayerNotificationManager event onNotificationCanceled is never called

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7276]
### [REQUIRED] Issue description
Hi everyone, 

Notification cannot be swiped and onNotificationCanceled is never called.

### [REQUIRED] Reproduction steps
```
`
@Override
public void onCreate() {
super.onCreate();

final Context context = this;

player = ExoPlayerFactory.newSimpleInstance(context, new DefaultTrackSelector());

// playlist preparation

// player.prepare(concatenatedSource, false, false);
player.prepare(playlist);
player.setPlayWhenReady(true);

PlayerNotificationManager.MediaDescriptionAdapter notificationAdapter = new PlayerNotificationManager.MediaDescriptionAdapter() {
    // implementation
};

PlayerNotificationManager.NotificationListener notificationListener = new PlayerNotificationManager.NotificationListener() {

    @Override
    public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
        System.out.println("onNotificationCancelled dismissedByUser "+dismissedByUser);
        stopForeground(true);
    }

    @Override
    public void onNotificationPosted(int notificationId, Notification notification, boolean ongoing) {
        startForeground(notificationId, notification);
    }
};

Intent dialogIntent = new Intent(this, PlayerActivity.class);
dialogIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

startActivity(dialogIntent);
playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
        context, "channelId", R.string.player_activity_name, R.string.player_activity_description, 1, notificationAdapter, notificationListener );
playerNotificationManager.setPlayer(player);
```
`

### [REQUIRED] Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer-core:2.10.5

### [REQUIRED] Device(s) and version(s) of Android being used
    compileSdkVersion 29
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29

Many thanks !!

**Comment by marcbaechinger** [comment]
The notification can only be swiped when not assigned to a foreground service. So it requires you to stop the foreground service, when the notification is not ongoing anymore (that is when the player is paused).

You are pretty close to that already with the code you show above.  You need to change `onNotificationPosted()` and check wether the notification is still ongoing. If paused `isOngoing` is false and you should stop the foreground service. Now the notification can be swiped, because it's not tied to a foreground service anymore.

When you receive the cancellation event after swipe, you can totally destroy your service. The user needs to restart in the app UI without notification. That's when you can start the cycle again and start your foreground service again.

That could probably look like this:

```
@Override
public void onNotificationPosted(
    int notificationId, Notification notification, boolean ongoing) {
  if (ongoing) {
    startForeground(notificationId, notification);
   } else {
     stopForeground(/* removeNotification= */ false);
   }
}

@Override
public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
   stopSelf();
}
``` 

Please let me know if this help.

**Comment by ghost** [comment]
I understand perfectly I think, it works as expected. Thank you so much!
