### ISSUE TITLE
av1 video with ima ads play failed

### ISSUE THREAD

**Issue by ycpysu2004** [google/ExoPlayer#7282]
[REQUIRED] Issue description

Use exo2.11.3 libgav1 to play av1 video and insert ima advertisement in the middle, mediacodec configure fails when playing mid-roll advertisement, showing that the surface cannot be connected

[REQUIRED] Reproduction steps
use exo demo， the uri info as below：
"name": "av1 mkv 480x270 Chimera-AV1-8bit-480x270-552kbps",
        "uri": "/mnt/sdcard/av1/Chimera-AV1-8bit-480x270-552kbps.mp4",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator="

the steps as below:
The pre-roll advertisement in the first 10 seconds is played successfully, then the 10-second video is played, and the mid-roll advertisement is played again failed

[REQUIRED] Link to test content
the media.exolist.json file as below
      {
        "name": "av1 mkv 480x270 Chimera-AV1-8bit-480x270-552kbps",
        "uri": "/mnt/sdcard/av1/Chimera-AV1-8bit-480x270-552kbps.mp4",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator="
      },

[REQUIRED] A full bug report captured from the device

[Log-av1 video with ima ads play failed.txt](https://github.com/google/ExoPlayer/files/4522226/Log-av1.video.with.ima.ads.play.failed.txt)

[REQUIRED] Version of ExoPlayer being used
2.11.3 demo

[REQUIRED] Device(s) and version(s) of Android being used
XIAO MI 8 , android 9

**Comment by kim-vde** [comment]
Can you please provide a link to the mp4 test content? 
If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ycpysu2004** [comment]
May I ask what information is needed, I provided the information as requested, I do n’t know what else is missing

**Comment by ycpysu2004** [comment]
Use a local av1 video, add an ad tag, it is easy to reproduce

**Comment by kim-vde** [comment]
You don't need to provide more information. I was unable to reproduce but it was my mistake. I can reproduce now. Sorry for the inconvenience.

**Comment by ycpysu2004** [comment]
> You don't need to provide more information. I was unable to reproduce but it was my mistake. I can reproduce now. Sorry for the inconvenience.


Thanks, looking forward to your reply

**Comment by kim-vde** [comment]
This is indeed a bug. Thanks for reporting it.

The problem occurs because the same `Surface` is used for rendering with `Libgav1VideoRenderer` and then with `MediaCodecVideoRenderer`.

To overcome this issue in the short term, you can use 2 `SurfaceView`s (changing their z-order as needed) and pass each underlying `Surface` to the appropriate renderer (for example by sending a message of type `Renderer.MSG_SET_SURFACE` to the renderers).

**Comment by ycpysu2004** [comment]
> in the short term
Thank you for your reply, I have a few questions
1. I found that if you play the ad before playing the av1 video, the native window can be disconnected when the mediacodec instance is released, so the av1 video can be played normally, but if the av1 video has been played and then the ad is played, then the av1 side cannot disconnect native window, so my question is can we find a way to disconnect av1 from native window? So that the mediacodec will not fail
2. You said that you can use two surfaces to solve this problem in the short term, so what is a better solution in the future? Because our products have a need to change the surface during playback, the two surfaces are very inconvenient
3. To solve this problem, I solved it in another way, I used opengl to render the av1 video. It seems that OpenGL automatically disconnected the native winodw internally when it was released. Do you think this is a reasonable solution?

**Comment by kim-vde** [comment]
1. Yes, the problem only occurs from `Libgav1VideoRenderer` to `MediaCodecVideoRenderer`, and not the other way around. We are still investigating how to solve this in ExoPlayer, so that the app developers will not have to worry about it. The corresponding commit reference will automatically be added to this issue when the fix is available.
2. Same as 1.
3. Yes, it is a good workaround!

**Comment by ycpysu2004** [comment]
Thank you for your suggestions and look forward to the final solution！

**Comment by kim-vde** [comment]
After investigation, we found out that the problem is due to a known limitation in the framework canvas rendering (see the orange rectangle in the [Surface documentation](https://source.android.com/devices/graphics/arch-sh)). This limitation will probably disappear one day (but not in the near future).

For this reason and because a fix would be very complex to implement, we will not fix the issue for now.

Note also that the GL rendering mode is the recommended way of rendering AV1 streams because it has better performances.

Could you explain in more details how you solved the problem using OpenGL? More precisely, I wonder how it works with MediaCodec.

**Comment by ycpysu2004** [comment]
The bottom layer of GL is also opengl, I think their principle is the same. My way is to create an opengl context in the rendering thread, and then close the opengl context when closing av1 rendering, so that it can be disconnected from the surface

**Comment by ycpysu2004** [comment]
I don't know why opengl is disconnected from the surface when it is closed

**Comment by kim-vde** [comment]
Could you provide a code sample to illustrate your solution? It could be useful for developers encountering the same issue in the future. Thanks!

**Comment by ycpysu2004** [comment]
OK, here is some steps:

**Comment by ycpysu2004** [comment]
OK, here is some steps
1、cover yuv420 data to rgba data
2、build opengl context, see details in the file
3、render rgba data directly in opengl
[OpenGLContext.cpp.txt](https://github.com/google/ExoPlayer/files/4573993/OpenGLContext.cpp.txt)
[OpenGLContext.h.txt](https://github.com/google/ExoPlayer/files/4573994/OpenGLContext.h.txt)

**Comment by kim-vde** [comment]
Thanks for sharing.
