### ISSUE TITLE
Play custom encrypted video from Server

### ISSUE THREAD

**Issue by vickyexpert** [google/ExoPlayer#7287]
I have a video file encrypted manually from our backend team. This video is on the server, I have to fetch the link runtime and start streaming on ExoPlayer. I don't have to download it and store it locally and all. Just while user clicks on play video I just have to check URL and then using that URL start video play in Exo player.
Earlier I have made this working for a local file. I have cipher with key and IV and using that I was able to decrypt and stream video parallel but for online from the server I am not able to make it work.

**Comment by christosts** [comment]
Can you please explain exactly how you are trying to decrypt the file in both setups, the local (which is working) and the remote? 

For example, I assume you are using the [AesCipherDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.html) in both cases, right? How are you creating the AesCipherDataSource for local files and for the remote file?

**Comment by vickyexpert** [comment]
Actually I have tried with local file streaming only, and for that, I am using the below example and it is working fine for me.

http://blog.moagrius.com/android/android-play-encrypted-video-in-exoplayer/
[http://blog.moagrius.com/android/android-play-encrypted-video-in-exoplayer/]Offline Video


But now we are not supporting offline videos, so we have a button like play video and to that button, there is server link of video like https://domain/videos/test_video.webm

this test_video.webm is encrypted and stored on a server.

So now while a user will click on the play button I have to pass the Url and play the video, but a video is encrypted so I have to decrypt it on the fly and stream to Exo player.

I tried above the same link, but it is showing me "File Not Found Exception" as the URI is server URL not local file Uri therefor.

**Comment by vickyexpert** [comment]
See below logic:

```
public EncryptedFileDataSource(Cipher cipher, TransferListener listener) {
    mCipher = cipher;
    mTransferListener = listener;
  }

  @Override
  public long open(DataSpec dataSpec) throws EncryptedFileDataSourceException {
    // if we're open, we shouldn't need to open again, fast-fail
    if (mOpened) {
      return mBytesRemaining;
    }
    // #getUri is part of the contract...
    mUri = dataSpec.uri;       ### _**//Here mUri is Server URL, so throwing error**_
    // put all our throwable work in a single block, wrap the error in a custom Exception
    try {
      setupInputStream();
      skipToPosition(dataSpec);
      computeBytesRemaining(dataSpec);
    } catch (IOException e) {
      throw new EncryptedFileDataSourceException(e);
    }
    // if we made it this far, we're open
    mOpened = true;
    // notify
    if (mTransferListener != null) {
      mTransferListener.onTransferStart(this, dataSpec);
    }
    // report
    return mBytesRemaining;
  }
```

**Comment by christosts** [comment]
If you are re-using the code from the blog post you shared (http://blog.moagrius.com/android/android-play-encrypted-video-in-exoplayer/), then this will not work with the file stored on a web server because that code is reading strictly from the the filesystem. 

In that piece of code, you have to start with changing the method `setupInputStream()` to open a connection with the server based on the file's URI and open an input stream from there. For example, ExoPlayer's [DefaultHttpDataSource](https://github.com/google/ExoPlayer/blob/r2.11.4/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java) is using [URL.openConnection()](https://developer.android.com/reference/java/net/URL#openConnection()).

I'm afraid this question falls to a more generic programming category and it is not a specific ExoPlayer one. If you need resources how to open an input stream from a file located in a web server, maybe Stackoverflow can be a more suitable place to get assistance.

**Comment by ojw28** [comment]
More generally, I wonder why you're trying to stream an encrypted video in the first place. What protection does the encryption provide that's not already provided just by using https (together with some kind of authentication as part of the request)?

**Comment by vickyexpert** [comment]
@christosts Actually I have tried to implement DefaultHttpDataSource, AesCipherDataSource, and also tried to prepare different kinds of media sources like progressive media source, extractor media source but still I am not able to make it work. I know how to open input stream and how to access it from the server. But this issue is related to ExoPlayer as I am not able to do the same with this player streaming. I can read stream I can download it, I can store it. But I am not able to read in a player data source to stream.
