### ISSUE TITLE
how do we pause player when headset or bluetooth is disconnected and play when reconnected 

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#7288]
how do we pause player when headset or bluetooth is disconnected and play when reconnected 

I am using this code 

 ```
mediaSession = new MediaSessionCompat(AudioPlayerService.this, ConstantValues.MEDIA_SESSION_TAG);
        mediaSession.setActive(true);
        playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());
        mediaSessionConnector = new MediaSessionConnector(mediaSession);
        mediaSessionConnector.setQueueNavigator(new TimelineQueueNavigator(mediaSession) {
            @Override
            public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
                return getMediaDescriptionl(SongsList, windowIndex);
            }
        });
        mediaSessionConnector.setPlayer(player);
```

I have referred this 

https://www.youtube.com/watch?v=svdq1BWl4r8

I have come across this 

https://stackoverflow.com/questions/52133798/pause-exoplayer-when-headphones-unplugged

Is there an inbuilt functionality that we can use to pause/play player when headset or bluetooth is disconnected/reconnected

**Comment by andrewlewis** [comment]
For pausing when audio is becoming noisy (headset/bluetooth disconnect), please try `SimpleExoPlayer.setHandleAudioBecomingNoisy(true)` (added in ExoPlayer 2.11.0).

For resuming when a headset or Bluetooth audio device is connected, we don't currently provide automatic handling for that (for the vast majority of use cases it would be preferable to have the user choose to unpause if some time has passed since reconnection). If you definitely want this functionality please have a look at [ACTION_HEADSET_PLUG](https://developer.android.com/reference/android/content/Intent#ACTION_HEADSET_PLUG) and documentation on [bluetooth profiles](https://developer.android.com/guide/topics/connectivity/bluetooth#Profiles), and search on Stack Overflow if you need more guidance on how to use them.
