### ISSUE TITLE
How to implement a callback after every track is listened in ConcatenatingMediaSource?

### ISSUE THREAD

**Issue by mzonov** [google/ExoPlayer#7298]
Hello. I've implemented concatenating of tracks with `ConcatenatingMediaSource`. But I need to know with some listener that track is listened.

For example, I have **3 tracks** and it needs to implement a callback immediately after the next track was listened to. How can I implement it? 

P.S. There is `onPlayerStateChanged` with `Player.STATE_ENDED` state but it triggers after all tracks were listened.

**Comment by christosts** [comment]
If you only want to know when an item in the list was played, listen to `onPositionDiscontinuity(int reason)`. If the reason is `DISCONTINUITY_REASON_PERIOD_TRANSITION`, it's a transition from one item to the next.

Note: This event is also triggered for transitions in a multi-period stream (live streaming), but I assume your items are not live-streams.

Closing this ticket, feel free to re-open if you need more information.
