### ISSUE TITLE
Implement multiple audio tracks support for HLS

### ISSUE THREAD

**Issue by andudo** [google/ExoPlayer#73]

**Comment by johanlindquist** [comment]
Naively, could an approach here not simply be to create something along these linkes?

 MediaCodecAudioTrackRenderer -> "Multi HLS Sample Source" -> Many HLS Chunk Sources (one for each media (audio) track in the playlist.

May of course be missing something obvious.

**Comment by ojw28** [comment]
Roughly speaking, yes. Although the exact point at which the division happens is TBD. For DASH and SmoothStreaming, we divide at the ChunkSource layer with a [MultiTrackChunkSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/MultiTrackChunkSource.java).

Caveats that may not have occurred are:

- The fact that there's audio in the primary audio/video stream, as well as in the separate audio tracks, makes wiring things up significantly more complicated than if the only options were the separate audio tracks. I haven't really thought much about what the best way to do this is.
- When you're downloading audio from a separate source, it's necessary to balance loading of the video and audio to make sure they load at approximately the same rate. You'd probably want to have them share the same underlying buffer pool as well. For DASH and SmoothStreaming, we use a [LoadControl](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/LoadControl.java) to do this.

You're really much better off using DASH or SmoothStreaming if you want multi-audio (you're much better off even if you don't want it, but it becomes even more true if you do). The HLS approach seems pretty bolted on to me, and if you select the non-primary audio track you end up downloading two audio tracks simultaneously, one of which you throw away. That's not exactly a good technical solution.

**Comment by johanlindquist** [comment]
HLS does indeed have quite a few things working against it but with a lot of content being used on multiple platforms, it seems to have managed to dig itself in quite well and is bound to be around for a while.

As for the dual download of audio-tracks - we have in-fact seen TS segments without an audio track entirely (probably to avoid just that - the dual download).  Nevertheless, this sort of setup does make wiring up UIs and such to support the various scenarios somewhat a nightmare.

Also, I guess the dual-download would also apply to something like subtitles/closed captions if they are both in the TS segment (as eia 608) and also web-vtt?

**Comment by perchrh** [comment]
@ojw28 How about this strategy for ExoPlayer: implement support for multi-audio in HLS only for the case with separate downloads. The case with multi-audio in one TS is an older solution and has a major drawback, that it increases the effective bitrate of the stream. For these reasons I expect that this case is not as important to most ExoPlayer-HLS users.

@johanlindquist You are right, the subtitle-case is analogous, they can be either in the TS or separate downloads, or both.

**Comment by johanlindquist** [comment]
I would be tempted to say +1 to @perchrh suggestion, if playlist contains EXT-X-MEDIA, simply ignore any audio in the TS.  If the (video) TS still contains audio data, it could be considered a server issue and should be fixed there by re-encoding the streams?

**Comment by canatella** [comment]
My branch contains a tentative fix for the audio part. It is loosely based on the multi track support for Dash. It only support one audio group for all the streams and completely bypass the TS audio. I think this is the basic use case for alternative audio as mentioned by @perchrh and @johanlindquist. See https://github.com/canatella/ExoPlayer/tree/master

It has problem with audio synchronisation. Any idea what's the problem? When switching audio tracks, it starts synchronised but it's quickly drifting.

Also there is no load control as mentioned in the comment  by @ojw28.

- canatella/ExoPlayer@a0a78922faae5ff42f961da21d741dc3f1c76582 adds support for parsing X-EXT-MEDIA directives,
- canatella/ExoPlayer@a414830a3ca947ad025335118d0024fd9c40073d and canatella/ExoPlayre@155832e93faa9c412def141ec663ddc7758563d9 make HlsChunkSource an interface,
- canatella/ExoPlayer@56ab2b2c8f34223f792e89d2d98650f5166a4237 adds a MultiTrackSource interface.
- canatella/ExoPlayer@6bf8f8ad4fde13c167b0e77da8138204c3b5c414 implements alternate audio media support in HLS renderer builder.

**Comment by andreimarinescu** [comment]
Any more progress on this end? We're in a position now that we need support for this, so if there's no ExoPlayer support we're going to look into implementing it. 

Any pointers for the best way to add support for multi track audio (and subtitles) would be highly appreciated. Also, if this is relevant for the main project, we'd gladly contribute our implementation.

**Comment by andreimarinescu** [comment]
Just following up on this. Would the discussion in #514 be relevant for HLS as well?

**Comment by johanlindquist** [comment]
Posted this by mistake in #514.

Something to bear in mind if using two chunk sources for live HLS (each loading playlists individually), which would the case for multi-audio.

There is a big risk the two will not correctly synchronize audio since the loading of playlists can (and will) happen at different times and under the right circumstances, the player will choose different start segments to start with.

For example:

Video playlist is loaded and contains sequence numbers 5,6,7,8,9,10 - playback will start with 8
Audio playlist is loaded and contains 6,7,8,9,10,11 - playback should start with 8 but code currently will pick 9.

So, there is a need to synchronize this somehow between the chunk sources.

**Comment by ojw28** [comment]
Yes, definitely something to bear in mind. We already have much of what we need to ensure this from our work on DASH. Specifically, LoadControl can be used to ensure that separate tracks load at the same rate (so that we don't end up buffering 10 minutes of audio and 10 seconds of video).

If the media timestamps in the separate streams are aligned properly then synchronization should happen automatically (I'd really hope that this is true). If not, we'll need to do a bit more work to get this right.

**Comment by johanlindquist** [comment]
While the timestamps usually are synchronized (in the playlist), there is still a chance that the playlists could be refreshed in-between loads so there is definitely a need to do the initial sync also using sequence numbers in the playlist (rather than just position in the list).

Also, there is the question I brought up in #552 which could be used to sync the audio/video even closer I believe.

**Comment by andreimarinescu** [comment]
I've noticed that the [e770e5c] should almost finalize this issue. Any help needed here for the final step? Is there a way of setting this up to work with it already? I've done a quick test with the demo app and no audio tracks are detected (seems in line with the commit message for HLS).

**Comment by ojw28** [comment]
Significant further work is required beyond the change linked to above for HLS. #514 has an update of where we are with multi-track across the various different playback types.

**Comment by andreimarinescu** [comment]
Thanks, @ojw28. I had a look over the codebase in the meanwhile and noticed that the HlsPlaylistParser isn't even looking at the AUDIO media tags yet, and I guess there's further work needed with reworking the HlsSampleSource. Thanks anyway for the update!

**Comment by SachiraChin** [comment]
@ojw28 Is there any update on this? Trying to play video hosted in Azure Media Services which only have below streams

- HLS + AES
- Smooth Streaming + AES

Second cannot be used because ExoPlayer doesn't support AES for Smooth Streaming. On HLS, only video works. Any update would help me a lot.

**Comment by ojw28** [comment]
No update, sorry. It's interesting that you have SmoothStreaming+AES streams. Perhaps we should support that case; SmoothStreaming is a much nicer standard than HLS, so it would be a shame to be pushing people to HLS because we support AES there and not for SmoothStreaming. Could you open a separate issue for that, and if possible link to the specification that defines how AES works in SmoothStreaming? Thanks!

**Comment by SachiraChin** [comment]
Created new issue #964. Hope it has enough information. Thanks.

**Comment by amed500** [comment]
Hey Guys, any update or any solution about Multi-Audio HLS support ?
thanks in advance.

**Comment by ojw28** [comment]
I have this more or less working locally, but I'm struggling to find test streams to verify that the implementation is correct. Please could anyone interested in this feature provide their streams for testing, either here or to `dev.exoplayer@gmail.com`.

I'm particularly interested in live streams with multiple audio tracks, since I haven't found any examples of this. VOD streams are helpful too. I know Apple provide a test stream with alternate audio, but their alternate track is a constant sound, which means you can't use it to verify that A/V sync is correct!

**Comment by akavrt** [comment]
> Please could anyone interested in this feature provide their streams for testing, either here or to dev.exoplayer@gmail.com.

We are really interested in this kind of functionality. I've sent link to the aforementioned e-mail.

**Comment by ojw28** [comment]
Got it, thanks.

**Comment by ReinhardG** [comment]
We can provide a multi-audio & subtitle VoD asset as well: https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

Feel free to encode additional multi audio streams on you own at https://bitmovin.com/encoding/.

**Comment by chile-zhong** [comment]
@ojw28 Hey Guys, any update or any result after test streams  about Multi-Audio HLS support ?
thanks.

**Comment by ajmfulcher** [comment]
I've come up with a limited solution to this one based on the way WebVTT is currently handled in the ExoPlayer demo app:
https://github.com/google/ExoPlayer/compare/master...ajmfulcher:alternative_audio?expand=1

Using this solution, an alternative audio stream will be used if supplied; if one isn't present, the audio included in the multiplexed segments will be used instead.  With some further modification to DefaultHlsTrackSelector you could select a specific alternative audio track when setting up the renderers.  Video and audio syncing seems fine using this method.

I don't think this is something I should PR, as it seems @ojw28 is working on a more complete solution, but in the meantime this might be worth trying out if your use-case means that you don't need to dynamically switch between audio streams after instantiation.

**Comment by dsahm** [comment]
@ajmfulcher Thanks for the tip. I have implemented your changes in my project, yet no sound. Do I have to do some further modifications apart from implementing your changes? Thanks for helping, Daniel.

**Comment by ojw28** [comment]
Please test the solution merged into dev. Thanks.

**Comment by igor9silva** [comment]
@ojw28 is it possible to download the dev branch from Central Maven or I have compile it before it goes into master?

**Comment by ojw28** [comment]
It'll be merged into master in the next release, at which point it'll become available. We don't provide dev branch binaries, although it's pretty easy to check out the source code from the repository and build one yourself.

**Comment by igor9silva** [comment]
Thanks @ojw28 will do it now.
