### ISSUE TITLE
How to check if an Audio codec is supported by a device.

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#7321]
### [REQUIRED] Searched documentation and issues
Gone through the MediaCodecAudioRenderer.java file and supportsFormat function. But need to know in detail how to check Audio Codec is supported or not and what all parameters to be validated using Decoder info against the Manifest file. 

### [REQUIRED] Question
How to check an Audio codec like ec3/ac3/aac or any other audio codec is supported by Device or not. What all the audio parameters to be considered/validated. Using MediaCodec utility we can find the decoder list but need to know what all the detail parameters to be validated from Decoder info against Manifest to say particular Audio codec is supported or not. If detail explanation is provided it will be helpful. Thanks in advance.

**Comment by Samrobbo** [comment]
Hi,

As far as I understand, you can get this information by reading through [MediaCodecVideoRenderer.supportsFormat](https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L366) and [MediaCodecAudioRenderer.supportsFormat](https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L365), otherwise you could read through the [MediaCodecInfo.isFormatSupported](https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java#L244), which the renderers access through getDecoderInfos. 

It may be that you want to read into how we derive a Format based on the media (which is used to check decoder support), in which case you should look at the specific media source.
