### ISSUE TITLE
Exoplayer wrong thread initialization for background playback.

### ISSUE THREAD

**Issue by athulantonynp** [google/ExoPlayer#7323]
In issue #5759 , it is stated that the initialization of SimpleExoplayer instance from the wrong thread will not be permitted for future versions of Exoplayer and an exception will be thrown if the user attempted to. This totally makes sense. But one issue which is going to pops up once this got implemented is background playback. I couldn't find a recommended way to implement background playback using exoplayer except for some blogs in the medium. Most of their approach is to use a foreground service thread for the initialization of exoplayer. This is working on most of the devices (Freezes UI sometimes in my device during the initial buffer). But I don't think this is the proper way to use it. Is there any recommended way to solve this issue?

**Comment by marcbaechinger** [comment]
By default a service runs on the main thread of the process which hosts the service. So I'd expect that creating the player instance on this main thread works in the same way as it would in an app activity which runs in the foreground.

Just to be clear on terminology, I think you are referring to the application's main thread when you are mentioning 'foreground service thread'.

In general I think it's recommended or at least a proper way to create the player on the main thread. This is, however, not enforced by the restriction you are mentioning. What is enforced is that the API methods of the player are called on the same Looper-Thread which has created the player though. That's a fine difference which means it does not need to be the main thread but a Looper thread.

> This is working on most of the devices (Freezes UI sometimes in my device during
> the initial buffer). 

With the exception of `release()`, the API methods of ExoPlayer are all asynchronous methods which only put a message into the message queue of the playback thread ([see diagram](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html)) and then immediately return. If you are seeing a freeze of the UI that you think is related to waiting for the BUFFERING state to end, that needs further investigation, but I don't think it's related with creating/calling the player on the main thread for the async reasons given above.

Can you give me some more details on whether this freeze does produce some logs istatements in logcat or how you think it is caused?

> But I don't think this is the proper way to use it.

I think initialization on the main thread in a service sounds ok to me. Why are you thinking this is not a proper use for it? Is it because you are seeing the freeze from above or for some other reasons?
