### ISSUE TITLE
BaseURL not used when in AdaptationSet

### ISSUE THREAD

**Issue by ShaiAmirSynamedia** [google/ExoPlayer#7327]
### [REQUIRED] Issue description
When BaseURL is in AdaptationSet level, it's not being used by the player.
The player tried to retrive the init file without the BaseURL and fails to do so.
The expected behaviour is that the player will use the BaseURL when trying to retrive the init (and segment) file.
For reference, DASH reference player plays the same content successfully.

### [REQUIRED] Reproduction steps
Use the attached manifests example where BaseURL in in AdaptationSet level.
Attached also BaseURL in Period level which does work.

### [REQUIRED] Link to test content
Content available only within a specific private VLAN.

### [REQUIRED] A full bug report captured from the device
Attached.

### [REQUIRED] Version of ExoPlayer being used
Demo App
commit 7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2

### [REQUIRED] Device(s) and version(s) of Android being used
[ro.com.google.clientidbase]: [android-technicolor-tv]
[ro.com.google.gmsversion]: [N_Q1_2017_BUILD_3783102]
[ro.com.technicolor.core]: [arneis-prerelease-17q2]
[bugreport-NTH42-2020-05-04-15-36-33.zip](https://github.com/google/ExoPlayer/files/4574670/bugreport-NTH42-2020-05-04-15-36-33.zip)
[mpd.zip](https://github.com/google/ExoPlayer/files/4574674/mpd.zip)

**Comment by ojw28** [comment]
I don't think the problem is that the `BaseURL` is in the `AdaptationSet`. The problem is that that `BaseURL` element is after the `Representation` elements, rather than before.

ExoPlayer's MPD parser doesn't parse the entire MPD into an object model and then process it. It mostly works by scanning the MPD from start to end. Hence the `BaseURL` needs to appear before the elements that make use of it.

The DASH specification does mandate the ordering, presumably to allow for more efficient parsing approaches such as the one ExoPlayer uses. It's actually pretty strict. Use of `xs:sequence` here means that the elements _must_ occur in exactly the defined order:

```
<xs:sequence>
  <xs:element name="Accessibility" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="Role" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="Rating" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="Viewpoint" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="ContentComponent" type="ContentComponentType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="BaseURL" type="BaseURLType" minOccurs="0" maxOccurs="unbounded"/>
  <xs:element name="SegmentBase" type="SegmentBaseType" minOccurs="0"/>
  <xs:element name="SegmentList" type="SegmentListType" minOccurs="0"/>
  <xs:element name="SegmentTemplate" type="SegmentTemplateType" minOccurs="0"/>
  <xs:element name="Representation" type="RepresentationType" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
```

So I think the conclusion here is that the media is incorrectly formatted. To fix this, try reordering the elements into the order required by the spec.

**Comment by ShaiAmirSynamedia** [comment]
Understood, thank you very much.
