### ISSUE TITLE
Tunneled video playback in Android

### ISSUE THREAD

**Issue by lwb5934** [google/ExoPlayer#7334]
1、Why we must use SurfaceView in tunneled mode? Why not TextureView?
2、In non-tunnel mode, why can I use surfaceview to play HDR, while textureview cannot play？（used Android 9）

**Comment by andrewlewis** [comment]
> 1、Why we must use SurfaceView in tunneled mode? Why not TextureView?

The information [here](https://source.android.com/devices/tv/multimedia-tunneling#for_device_manufacturers) about how composition of tunneled video output works might explain why, but I'm afraid I'm not familiar with the details.

Could you give some details about why you need `TextureView` support? I think there are only limited cases where it's necessary on recent Android versions.

> 2、In non-tunnel mode, why can I use surfaceview to play HDR, while textureview cannot play？（used Android 9）

This is probably a framework bug. It would be useful if you could file a bug following the instructions [here](https://source.android.com/setup/contribute/report-bugs). Can you reproduce it on Android 10 or the developer preview?

**Comment by lwb5934** [comment]
Thank you for your reply!
1、why need TextureView support?
First, Textureview is more flexible, I can used surface which created by SurfaceTexture to the OpenGL, and process the video frames(such as VR and 360⁰ video playback).
Second, using mediacodec+OpenGL can fix some display bug, so I need TextureView.
2、using SurfaceView or TextureView display HDR
In non-tunnel mode, and use mediacodec for decoding and display, I can use SurfaceView display HDR, while TextureVeiw cannot display. During TextureView, convert hdr to sdr for playback. But I can use mediacodec + opengl to display HDR correctly(processed the video frames).So, what is the difference between SurfaceView and TextureView showing hdr? Whether the created surface is different or the display stage is different?
Thanks!

**Comment by andrewlewis** [comment]
Are you sure you need to use tunneled mode? A goal of tunneling is to remove the CPU from the pipeline processing video where possible, to be able to handle 4k content on TV devices with slower CPUs. If you need to do processing on video output rendered to an off-screen texture, I don't think there's much benefit to be had from using tunneling even if it did work! So I'd suggest just not using tunneling.

`TextureView` output gets composited as part of the UI in RGB. [Enhance graphics with wide color content](https://developer.android.com/training/wide-color-gamut) may have some useful info but I haven't tried using wide color gamut mode so I'm not sure. If that's not satisfactory, please report the behavior you are seeing and the expected behavior on the [platform bug tracker](https://source.android.com/setup/contribute/report-bugs) and reply with a link to the issue you have filed here. Thanks!

**Comment by lwb5934** [comment]
The current tunnel mode of exoplayer needs to be turned on by myself, or if exoplayer detects that the tunnel mode is satisfied, the mode is enabled on the mobile phone.
thanks!

**Comment by andrewlewis** [comment]
It's only used if you enable it and it's supported by the device for the format you are trying to play. You can call `setTunnelingAudioSessionId` on the default track selector parameters builder to enable it (and an audio session ID can be generated via `C.generateAudioSessionIdV21(context)`).
