### ISSUE TITLE
No sound for mp4 with pcm

### ISSUE THREAD

**Issue by HPIWicket** [google/ExoPlayer#734]
Hey,

I try to play a mp4 video file that was generated on an iOS device. The video is fine but there is not audio. When I am debugging the issue it seems like that only one track (the video track) is recognised. 

The following info about the file is provided by VLC:

Stream0:
  Type: Video
  Codec: H264 - MPEG-4 AVC (part10) (avc1)

Stream1:
  Type: Audio
  Codec: PCM S16 LE (sowt)
  Channels: Mono
  Sample rate: 22050 MHz
  Bits per sample: 16

This was tested on Android 5.1.1 with ExoPlayer 1.4.1 and the MP4Extractor.

Thanks

**Comment by ojw28** [comment]
When you say generated, do you mean it was recorded with the regular camera on the device? What device was it / what version of iOS is it running? Thanks!

**Comment by HPIWicket** [comment]
The video was generated out of a recorded video file and a sound file with AVFoundations, The device was an iPhone 5C, an iPhone 5 and an iPhone 6, running iOS 8 or 9.

**Comment by ojw28** [comment]
If you could provide a sample file, we'll take a look at this. Either by attaching one here, or emailing olly.exoplayer [at] gmail [dot] com. Thanks!

**Comment by HPIWicket** [comment]
I will generate a sample file and send it to you. What I found out is, that it is not a mp4 video file but a mov video file. Still the question is the same as mov uses h264 with PCM.

**Comment by ojw28** [comment]
We don't have plans to support mov any time soon. In general, tools are better off outputting mp4 if they want their output to work across different devices. "sowt" doesn't appear to be valid in mp4, where I think you'd need to use "twos". We don't support that either right now, primarily because no-one has ever asked for it.

Leaving this marked as enhancement, to support "twos" and "sowt" if it happens to be very little additional work.

**Comment by HPIWicket** [comment]
Thanks a lot for the information :)

**Comment by Ood-Tsen** [comment]
Hi @HPIWicket , my I have your test content ?

**Comment by HPIWicket** [comment]
@Ood-Tsen  I send you an email ;)

**Comment by HPIWicket** [comment]
@ojw28 could you provide a hint how I could add this functionality myself?

**Comment by ojw28** [comment]
You'd need to:
1. Add ```TYPE_sowt = Util.getIntegerCodeForString("sowt");``` in ```Atom.java```
1. In ```AtomParsers.parseAudioSampleEntry``` you'll probably see ```atomType``` being equal to this value when playing the test content. You need to ensure that ```out.mediaFormat``` is set correctly in this case. I'm not really sure exactly what it should be set to, so that's something you'll have to figure out. It may also be necessary to apply a transformation to the actual media. Again, I'm not sure what's required here.

**Comment by HPIWicket** [comment]
ok thank you

**Comment by Shusshu** [comment]
@HPIWicket  any luck on this?

**Comment by HPIWicket** [comment]
@Shusshu not really, it is pretty easy to get the ExoPlayer to recognise the audio stream, but since this is a raw audio stream you would have to change the decoder to passthrough the audio samples. At this point it didn't work for me with the AudioTrack. 

This should not be a very big problem as AC3 also does this and https://github.com/google/ExoPlayer/issues/317 indicates what has to be done. But for me it was easier to change the generated video format, so that is is readable by default.

**Comment by vinayak-garg** [comment]
Did anyone get this audio type working? Any pointers on implementing it would be great too.

**Comment by ojw28** [comment]
This is supported as of version 1.5.8 :) (thanks to @dcower).
