### ISSUE TITLE
Setting OnLongClickListener on PlayerView.getVideoSurfaceView() Breaks Controller's Show/Hide on Touch

### ISSUE THREAD

**Issue by oaa8** [google/ExoPlayer#7350]
### [REQUIRED] Issue description
It appears that setting a longClickListener on the VideoSurfaceView of a `PlayerView` causes `onTouchEvent()` to not be called for the `PlayerView` which then means that `toggleControllerVisibility()` isn't called.

### [REQUIRED] Reproduction steps
1. Update the sample app to have the following code when initializing the `PlayerView`:
``` Java
playerView.getVideoSurfaceView().setOnLongClickListener(v -> {
  Toast.makeText(playerView.getContext(), "Long Click Detected", Toast.LENGTH_LONG).show();
  return true;
});
```

[Example is here](https://github.com/oaa8/ExoPlayer/commit/1c9e709790efecfa0da36147ca63fea90ac094ac)
2. Compile and launch the application
3. Long press in the video area (on the `VideoSurfaceView`)
4. Observe that the Toast "Long Click Detected" is shown
5. Tap on the video area (a few times)

#### Expected Behavior
As a result of step 5, the visibility of the controls is toggled by each tap
#### Actual Behavior
The visibility of the controls is not toggled unless touching **outside** the video

### [REQUIRED] Link to test content
Any video will work

### [REQUIRED] A full bug report captured from the device
[Here's code to reproduce the issue](https://github.com/oaa8/ExoPlayer/commit/1c9e709790efecfa0da36147ca63fea90ac094ac)

### [REQUIRED] Version of ExoPlayer being used
2.11.4

### [REQUIRED] Device(s) and version(s) of Android being used
This appears to be device independent.  Reproduced in an emulator on API level 29.  Reproduced on older versions of Exo Player on Samsung's S9+, Galaxy Fold.

**Comment by ojw28** [comment]
I think this is essentially unsupported because the show/hide logic is listening for the same touch events as the `OnLongClickListener`, and (without special wiring) those events can only be consumed once.

I think the use case is sufficiently obscure for it to not be worth spending time on figuring out how to support both simultaneously. You can also work around the issue by explicitly setting a regular `OnClickListener` alongside the `OnLongClickListener`:
```
playerView.getVideoSurfaceView().setOnLongClickListener(v -> {
  Toast.makeText(
      playerView.getContext(),
      "Long Click Detected",
      Toast.LENGTH_LONG).show();
  return true;
});
playerView.getVideoSurfaceView().setOnClickListener(v -> {
  playerView.performClick();
});
```
Note that with this workaround, the show/hide logic is subtly different if you click outside of the video surface (show/hide is triggered when the finger is lifted, whether it's a long or a short click) compared to inside (show/hide is triggered only when the finger is lifted for a short click). However, given you're trying to register a `OnLongClickListener` to do something else, that may actually be what you want.
