### ISSUE TITLE
What should I do if an error occurs during the playlist? 

### ISSUE THREAD

**Issue by HanGao1** [google/ExoPlayer#7359]
What should I do if an error occurs during the playlist? When I am in the playlist, the playback address is empty, which causes the playback to fail. Calling next is invalid and cannot be played again.

**Comment by krocard** [comment]
The expected behaviour is for ExoPlayer to recover (aka try again) from any player error when going to the next item on the playlist or playing again the current item. Thus I'm not sure to understand the issue you are facing.

Could you post the stacktrace of the error you encountering during playback? That would help us understand what is the problem here.

Please also post a step by step procedure to trigger the issue. Thanks
