### ISSUE TITLE
Play a  specific dash content in landscape full-screen mode, some noises are generated.

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#7371]
Hello,

I played a specific dash content using the demo app in landscape full-screen mode, I encountered a problem.
When I change a specific representation to another specific representation, some noises are generated in a video image.

It occurred only a specific model phone and specific content.
And, it did not occur portrait mode.

Could you confirm this issue and please tell me how to avoid the problem.

### Issue description
・Galaxy S10+ (Android 9)(SC-04L)
・Exo ver 2.11.4 (7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2)
・content：https://dev-vod.dch.dmkt-sp.jp/vod/hikaritv/hikaritv_maejimahigashi_hd264/20200219123456/manifest2.mpd

### Reproduction steps

Launch the Exo demo app.
Play the content(listed in the issue description section) in landscape full-screen mode.
Select this representation using app's function "Select Tracks".
```bash
<Representation width="512" height="288" mimeType="video/mp4" codecs="avc1.640015" startWithSAP="1" id="video_4" bandwidth="663183"></Representation>
```
Select this representation using app's function "Select Tracks", then some noises are generated in a video image.
```bash
<Representation width="480" height="270" mimeType="video/mp4" codecs="avc1.640015" startWithSAP="1" id="video_3" bandwidth="443468"></Representation>
```

Please check the attached log file below.
[log.zip](https://github.com/google/ExoPlayer/files/4619873/log.zip)

Thank you!

**Comment by rishun-fsi** [comment]
Please see the attached file and check the details.
[bugreport-2020-05-14-10-17-00.zip](https://github.com/google/ExoPlayer/files/4625982/bugreport-2020-05-14-10-17-00.zip)



![issue_capture](https://user-images.githubusercontent.com/43164510/81891925-c184a800-95e4-11ea-9cb1-d71e1fdf9818.gif)

If you have any further questions, please let me know.

Thank you in advance

**Comment by krocard** [comment]
@ojw28 does that ring a bell? Is there anything we can do without access to a Galaxy S10+?
Note that I can not access the content linked, and I did not see anything suspicious in the log.

**Comment by ojw28** [comment]
The test URL gives me a HTTP 403 (forbidden) error. I tried proxying through Japan, but that didn't help either. We need an accessible test stream to investigate this further.

**Comment by rishun-fsi** [comment]
Hello @ojw28 ,
I am sorry that this URL is not accessible for now, We are trying to fix that problem as soon as possible, please wait us there for a little longer, thank you.

**Comment by rishun-fsi** [comment]
Hello @ojw28 ,
I'm sorry to have kept you waiting.
Now I think you can link to the following URL, please confirm.
test content：https://tvod-origin.hikaritv.net/video/test/maejima/manifest.mpd

If you have any other questions, please let me know.
Thank you in advance

**Comment by ojw28** [comment]
I see issues when seeking on a Pixel 3 device, regardless of which representation is selected. Immediately after a seek I see that the video is temporarily grey and corrupted. The root cause seems to be that the FMP4 segments in this content incorrectly specify that every sample is a key-frame. This causes playback to start decoding at a non-keyframe following a seek (or equivalently, following a change in which representation is selected). Starting to decode from a non-keyframe is invalid and will cause the visual corruption.

In most cases a decoder will recover once it's fed the next genuine key-frame, but this is not guaranteed. Behaviour up until that point is also undefined. The issue you're seeing is probably just the way that the Samsung S10+ decoder is handling the problem.

I don't know what tool you used to generate this content, but the correct fix is to repair or regenerate the content so that the keyframes are marked correctly. If you have ExoPlayer checked out as source code, you can also work around the problem by modifying [this line](https://github.com/google/ExoPlayer/blob/r2.11.5/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DefaultDashChunkSource.java#L815) to pass:
```
flags | FragmentedMp4Extractor.FLAG_WORKAROUND_EVERY_VIDEO_FRAME_IS_SYNC_FRAME
```
We don't plan on making it easier to set this flag without making a source modification, since there is no evidence this is a widespread problem for DASH content.
