### ISSUE TITLE
DownloadManager and CachedMedia source duplicate download

### ISSUE THREAD

**Issue by bogdanDroidAds** [google/ExoPlayer#7379]
### [REQUIRED] Searched documentation and issues
I looked on stackoverflow and in this issue tracker but could not find something exactly like my issue.

### [REQUIRED] Question
I have the following scenario. I want to download some media, and at some point in the future play that media using exoplayer. For this I used the DownloadManager, as in the documentation. To playback the media I used the CacheMediaSourceFactory as the documentation advises.
The problem: if I start the playback soon enough (before the download is finished), a second connection starts and it downloads the media again, not using what's already downloaded by the DownloadManager. To simulate this I used Charles porxy throttling feature.
Is there any way to avoid a second connection?

**Comment by krocard** [comment]
I think the issue is that until fully downloaded, ExoPlayer will not consider it available and download stream it instead, but @marcbaechinger will know more.
@marcbaechinger is there a way for exoplayer to use the partially downloaded file instead of downloading the chunks a second time?

**Comment by tonihei** [comment]
If you want to use two Cache instances (one for download and one for temporary caching), #5867 sounds related.

Otherwise, as @krocard pointed out above, each chunk of data is only available after it has been fully downloaded. For adaptive streams (e.g. DASH, HLS), this is after every chunk. And for progressive media (e.g. mp4), the stream is artificially chunked into 5MB pieces.

Please also read through this comment: https://github.com/google/ExoPlayer/issues/6204#issuecomment-529526833
Essentially, you should make sure that:
 1. The playback cache data source is read-only to avoid writing to the same cache again.
 2. The `CacheDataSource.FLAG_BLOCK_ON_CACHE` is set for playback so that same data isn't downloaded again and the source waits for the downloader instead.

**Comment by bogdanDroidAds** [comment]
Thanks. I will take a look
