### ISSUE TITLE
IllegalStateException in Live Dash stream on FireTVs

### ISSUE THREAD

**Issue by icetronics** [google/ExoPlayer#7381]
### [REQUIRED] Issue description
On certain FireTV models some of the Live streams fail to play and crash the player. I would like to inquire whether this behavior rings any bell or you spot any issues with the stream.

### [REQUIRED] A full bug report captured from the device
sent via email

### [REQUIRED] Version of ExoPlayer being used
2.10.8

### [REQUIRED] Device(s) and version(s) of Android being used
- [FireTV Gen2 - Android 5.1](https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-stick.html?v=ftvstickgen2)
- [FireTV 4K Stick - Android 7.1](https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-stick.html?v=ftvstick4k)

**Comment by krocard** [comment]
Looking into the bug report, I can not see any ExoPlayer related logs. Do you mind pointing me to which error you are refering to?

**Comment by krocard** [comment]
Additionally I don't see any activity in the 25 min before the bug report was taken. It would be helpfull if the bug report was taken just after the issue occured.

**Comment by krocard** [comment]
Would it be possible for you to take an other bug report or tell me at what time the issue occured in the one you sent us?

**Comment by krocard** [comment]
Or do you mean the IllegalStateException that was thrown at 19:09 (26h hours before the bug report was taken):
~~~
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: Error while accessing provider:com.amazon.device.controller.provider
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: java.lang.IllegalStateException: Could not find provider: com.amazon.device.controller.provider
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.amazon.android.extension.firetvscreentimeout.HurleyThunderBtDisconnector.disconnect(HurleyThunderBtDisconnector.java:86)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.amazon.android.extension.firetvscreentimeout.FireTVScreenTimeoutCallback.screenOff(FireTVScreenTimeoutCallback.java:116)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.server.power.VendorNotifierCallback.callScreenOff(VendorNotifierCallback.java:33)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.server.power.Notifier$8.run(Notifier.java:484)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at android.os.Handler.handleCallback(Handler.java:751)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at android.os.Looper.loop(Looper.java:154)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.server.SystemServer.run(SystemServer.java:361)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.server.SystemServer.main(SystemServer.java:228)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
05-13 19:09:04.313   604   604 E HurleyThunderBtDisconnector: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
~~~

Unfortunately, this code is not part of Android, so I can only guess from the function signatures.
It looks like an error when the screen is turned off and BT connection with the TV remote is disconnected.
The wake lock was released just before:

~~~
05-13 19:09:03.932   604   624 I AmazonPowerManagerVendorCallback: Wakelock released UID:1000 PID:604 Tag:WindowManager
~~~

I don't think this error is related to your stream playback failure though, given that it occurs when the screen is turned off due to inactivity.

**Comment by krocard** [comment]
I don't think the playback error is part of the bug report. Please take an other one just after the stream playback error.

**Comment by krocard** [comment]
Additionally, the Dash manifest you sent us is using http:// and not https://. Maybe you're hitting this playback error just because of a cleartext restriction?
Consider checking that you are using an https URL in your app.
