### ISSUE TITLE
dequeueOutputBuffer() returning -1

### ISSUE THREAD

**Issue by Swathi-Thirunarayanan** [google/ExoPlayer#7382]
### Description:
I am trying to implement frame reverse (after every key press, it goes back by 1 frame) in exoplayer. I was successful with MPEG2 content but unfortunately for MPEG4 (AVC) content, when I try to do frame reverse, dequeueOutputBuffer() is always returning -1. I am trying to understand the reason behind it. When i traced back dequeueOutputBuffer() to find the root cause, I was stuck at native function. I wasn't able to go further deep to find the root cause.

```
private native final int native_dequeueOutputBuffer(
            @NonNull BufferInfo info, long timeoutUs); 
```
### FYI: Input Buffer seems to have content.
I added logs in feedInputBuffer(), MediaCodecRenderer.java to confirm that input buffer queue is not empty.
```
      Log.d("Swathi", "InputBuffer queueInputBuffer PTS in us: "+presentationTimeUs);
      codec.queueInputBuffer(inputIndex, 0, buffer.data.limit(), presentationTimeUs, 0);
```
### Logs:
> 2020-05-14 18:24:25.697 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 200200
> 2020-05-14 18:24:25.702 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 3003000
> 2020-05-14 18:24:25.713 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 6206200
> 2020-05-14 18:24:25.717 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 9409400
> 2020-05-14 18:24:25.722 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 11544867
> 2020-05-14 18:29:42.743 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 14748067
> 2020-05-14 18:29:42.747 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 19019000
> 2020-05-14 18:29:42.751 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 23289934
> 2020-05-14 18:29:42.755 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 27560867
> 2020-05-14 18:29:42.758 15576-15640/com.google.android.exoplayer2.demo D/Swathi: InputBuffer queueInputBuffer PTS in us: 31831800

### Question:

1. Why is dequeueOutputBuffer() returning -1, when inputbuffer queue has content?

**Comment by christosts** [comment]
That is not a straight forward task to achieve. Just to make sure I get the question right, I am assuming that when you go backwards by 1 frame, you pick the specific encoded sample, queue it as input buffer and expect to be output from MediaCodec.

I'm not sure which parts of ExoPlayer you are using, but in principle you cannot/should not assume that if you enqueue 1 input buffer for decoding, you will receive 1 output buffer immediately. Video encoding/compression techniques use information from multiple frames to efficiently compress/encode a specific frame. I like how this tutorial explains this concept

https://github.com/leandromoreira/digital_video_introduction#frame-types

On a very high-level, some frames, called I-frames, are encoded without any reference to other frames - if you decode an I-frame, you will get an output buffer directly. P-frames reference information from I-frames. To decode P-frames, the referenced I-frame must have been enqueued already so that the MediaCodec has kept it its internal memory and use that information to decode the P-frame. B-frames reference both I-frames and P-frames, therefore to decode a B-frame both the I-frame and P-frame must have been enqueued already. Frames are organized in groups called group-pictures (GOP) which is a sequence of I, P and B frames, e.g. "IBBBP". Notice the B-frames are referencing a P-frame that will be displayed later on screen. To play this sequence of video frames, you must enqueue them in this order: IPBBB. The P-frame goes before the B-frames. You don't have to worry about ordering frames when playing forwards because video streams have the frames organized already in the right decoder-order and then the decoder (MediaCodec) outputs them re-ordered by their presentation timestamps.

However, if you want to go backwards, say to the first B frame of the example above, you cannot simply enqueue it. You have to enqueue I and P first (and not to display them on screen) and then enqueue B, get it from the output and show it.

Short answer: to go backwards to a frame, you have to jump to the beginning of the GOP that contains the frame, start queueing input buffers from that point, and display only the frame whose PTS matches the frame you are looking for. This is a simple approach, you might not want to do that for every frame you go back, especially if you are on the same GOP. For example, you may spare some resources if you keep track of the GOP you are in, or don't release the non-displayed frames immediately, and so on.

ExoPlayer (and other players) jump to beginning of GOPs when they do seeking. I have not tried it myself, maybe you can solve your task just seeking to the previous frame if you know the exact timestamp (the player should be paused). This is suboptimal, but it may be a quick solution to your task.

However, this question sounds more of generic video playback/MediaCodec use, so I'll close this issue. Feel free to re-open if you have a specific question or an issue with ExoPlayer.
