### ISSUE TITLE
Moving files from internal to external storage

### ISSUE THREAD

**Issue by henorek** [google/ExoPlayer#7397]
Hello there,

When I try to transfer files from one place to another, unfortunately, this does not happen. The only thing that happens is the .uid file in the target path, below I attach screenshots showing the cache structure before and after.

/data/user/0/package.name/files/
![image](https://user-images.githubusercontent.com/13158167/82331300-39d3da80-99e4-11ea-8cbc-d7f6599fd72f.png)

/storage/emulated/0/Android/data/package.name/files/
![image](https://user-images.githubusercontent.com/13158167/82332397-a3a0b400-99e5-11ea-9d5e-9d7b4eef89cf.png)

The paths between which I want to move files are determined by methods
`ContextCompat.getExternalFilesDirs`
for external storage and
`context.getFilesDir`
for internal memory, so I considers them reliable.

Any ideas why this is happening? Of course, ExoPlayer does not play these (or any other) media during file transfer.

**Comment by mseroczynski** [comment]
If you have any suggestions on what to try please share them with us but please do not let this issue to be here unresponded for a long time - functionality broke right after we've migrated caching downloaded files mechanism to ExoPlayer (we've started using it believing it would be better to trust ExoPlayer than our own solution) and now we're in a dead end with tons of support messages.

**Comment by ojw28** [comment]
Particularly in cases where you want a fast answer, please take care to ensure you've provided sufficient information for us to help. For example, concrete reproduction steps ("transfer files from one place to another" could mean many things). Or ideally a small demo app that reproduces the problem, so that we don't have to spend time re-building the same thing in order to see what the problem is. Marking "need more info" until one of these is provided.

**Comment by mseroczynski** [comment]
> Particularly in cases where you want a fast answer, please take care to ensure you've provided sufficient information for us to help. For example, concrete reproduction steps ("transfer files from one place to another" could mean many things). Or ideally a small demo app that reproduces the problem, so that we don't have to spend time re-building the same thing in order to see what the problem is. Marking "need more info" until one of these is provided.

Thanks for fast response. Let me get one thing clear here - are you suggesting that transfering files (copy A->B, delete A) from one directory to another while player is released works in ANY scenario and reproducing this particular bug is anyhow complicated...? In such case - in which scenario it works?

**Comment by ojw28** [comment]
> are you suggesting that transfering files (copy A->B, delete A) from one directory to another while player is released works in ANY scenario and reproducing this particular bug is anyhow complicated...?

I tried downloading something in the demo app into a cache using directory A, moving the cache directory to B, updating the demo app to use cache directory B, and it was able to find and use the cache files fine at their new location. So yes, there are scenarios where this appears to work.

**Comment by mseroczynski** [comment]
Ok, the reason of this bug was different. ExoPlayer creates *.uid file on storage to recognize cache directory and this file need to remain untouched. If it is deleted by external mechanism ExoPlayer will continue to use such cache (will successfully download new files without problem etc.) but when app is restarted (and ExoPlayer is initialized again) it will delete these files from unrecognized cache without *.uid file. Another thing is that it will leave all the info about these "just deleted" files in legacy Table in it's database (instead of dropping it if its not recognized anymore?). Another thing is that some of these files with state 3 (STATE_COMPLETED) will have values like "99.996" in "percent" column. 

Anyway, this task is figured out now, thanks for checking on it - the problem was in not knowing that just restarting an app may cause cleaning of successfully downloaded files when *.uid file is gone before downloading.
