### ISSUE TITLE
Audio is not being played from local cache

### ISSUE THREAD

**Issue by mddrill** [google/ExoPlayer#7417]
### [REQUIRED] Searched documentation and issues

I have Looked through the issue tracker, the exoplayer documentation for downloading media as well as stackoverflow

### [REQUIRED] Question

I am using a CacheDataSourceFactory to download mp3s for offline access both during streaming and via direct downloading with a DownloadService. In both cases I can see files being created in my download directory, but when I disconnect the device from internet and try to play the mp3, it doesn't work. As far as I can tell I am doing exactly what the [downloading media](https://exoplayer.dev/downloading-media.html) documentation says to do, so I don't know what's wrong. I have also posted a stackoverflow question for this, but no one seems to know the answer: https://stackoverflow.com/questions/61961937/why-is-my-cache-not-being-used-by-exoplayer

Here is my code:

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val httpDataSourceFactory = DefaultHttpDataSourceFactory(Util.getUserAgent(this, "test.myuser"))
        val cacheDataSourceFactory = CacheDataSourceFactory(Injector.provideCache(this),
                DefaultDataSourceFactory(this, DefaultDataSourceFactory(this, httpDataSourceFactory)),
                FileDataSource.Factory(), null,
                CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,  null
        )

        val exoPlayer = SimpleExoPlayer.Builder(this).build()

        findViewById<ImageButton>(R.id.play_button).setOnClickListener {
            play(exoPlayer, cacheDataSourceFactory)
        }
        findViewById<ImageButton>(R.id.download_button).setOnClickListener {
            download()
        }
    }

    private fun play(player: SimpleExoPlayer, dataSourceFactory: DataSource.Factory) {
        Log.d("TestExoplayer", "play")

        val url = "https://storage.googleapis.com/uamp/" +
                "The_Kyoto_Connection_-_Wake_Up/" +
                "01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3"
        val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse(url))
        player.prepare(mediaSource)
        player.playWhenReady = true
    }

    private fun download() {
        Log.d("TestExoplayer", "download")
        val url = "https://storage.googleapis.com/uamp/" +
                "The_Kyoto_Connection_-_Wake_Up/" +
                "01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3"
        val downloadRequest = DownloadRequest(
            url,
            DownloadRequest.TYPE_PROGRESSIVE,
            Uri.parse(url),
            Collections.emptyList(),
            null,
            null
        )
        DownloadService.sendAddDownload(this, MyDownloadService::class.java, downloadRequest,false)
    }
}
```

```
class MyDownloadService : DownloadService(
    FOREGROUND_NOTIFICATION_ID_NONE,
    DEFAULT_FOREGROUND_NOTIFICATION_UPDATE_INTERVAL,
    DOWNLOAD_NOTIFICATION_CHANNEL_ID,
    R.string.exo_download_notification_channel_name,
    /* channelDescriptionResourceId= */ 0){
    override fun getDownloadManager(): DownloadManager {
        val databaseProvider = ExoDatabaseProvider(this)

        val downloadCache = Injector.provideCache(this)
        val dataSourceFactory =
            DefaultHttpDataSourceFactory(Util.getUserAgent(this, "test.myuser"))
        return DownloadManager(
            this,
            databaseProvider,
            downloadCache,
            dataSourceFactory
        )
    }

    override fun getForegroundNotification(downloads: MutableList<Download>): Notification {
        TODO("Not yet implemented")
    }

    override fun getScheduler(): Scheduler? {
        return if (Util.SDK_INT >= 21) PlatformScheduler(this, JOB_ID) else null
    }

}
```

```
private const val DOWNLOAD_CONTENT_DIRECTORY = "downloads"

object Injector {

    var cache: SimpleCache? = null

    @Synchronized
    fun provideCache(context: Context): Cache {
        if (cache == null) {
            val downloadDir = context.getExternalFilesDir(null)
            val downloadContentDirectory = File(downloadDir, DOWNLOAD_CONTENT_DIRECTORY)
            cache =
                SimpleCache(downloadContentDirectory, NoOpCacheEvictor(), ExoDatabaseProvider(context))
        }
        return cache!!
    }
}
```

### A full bug report captured from the device
In case your question refers to a problem you are seeing in your app, capture a
full bug report using "adb bugreport". Please attach the captured bug report as
a file. If you don't wish to post it publicly, please submit the issue, then
email the bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234", where "#1234" should be replaced with your issue number.

### Link to test content
In case your question is related to a piece of media, which you are trying to
play, please provide a JSON snippet for the demo app’s media.exolist.json file,
or a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where
"#1234" should be replaced with your issue number. Provide all the metadata we'd
need to play the content like drm license urls or similar. If the content is
accessible only in certain countries or regions, please say so.

**Comment by marcbaechinger** [comment]
This looks quite ok at the first glance. I wonder whether there is a glitch when you create the `CacheDataSourceFactory`. The nested `DefaultDataSourceFactory` looks suspicious without knowing whether this is the issue I would just try the most simplest approach there as a start:

```
val httpDataSourceFactory = DefaultHttpDataSourceFactory(
    Util.getUserAgent(this, "test.myuser"))
val cacheDataSourceFactory = CacheDataSourceFactory(
    Injector.provideCache(this),
    httpDataSourceFactory,
    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
```

If this does not help, can you please add an `EventLogger` to the player and create a bug report just after you tried playing the cached media? When uploaded here, this allows me to investigate what's going on:

```
player.addAnalyticsListener(new EventLogger(null));
```

**Comment by mddrill** [comment]
So I realized that if I keep the MainActivity open after downloading the mp3 and turning on airplane mode, the mp3 will play offline. It's only after I destroy the activity that the mp3 no longer plays, suggesting that the mp3 is being cached in memory, but not on disk. Am I incorrect in thinking it should be cached on disk? My use case is downloading podcast episodes to be played for several hours where there may not be internet connection, can exoplayer do this?

I hooked up the eventlogger and this was the output I got after destroying the activity and trying to play the downloaded media:

```
2020-05-27 21:40:00.601 8348-8348/com.example.myapplication D/EventLogger: state [eventTime=20.43, mediaPos=0.00, window=0, false, BUFFERING]
2020-05-27 21:40:00.602 8348-8348/com.example.myapplication D/EventLogger: state [eventTime=20.43, mediaPos=0.00, window=0, true, BUFFERING]
2020-05-27 21:40:00.603 8348-8348/com.example.myapplication D/EventLogger: timeline [eventTime=20.43, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2020-05-27 21:40:00.603 8348-8348/com.example.myapplication D/EventLogger:   period [?]
2020-05-27 21:40:00.603 8348-8348/com.example.myapplication D/EventLogger:   window [?, false, false]
2020-05-27 21:40:00.603 8348-8348/com.example.myapplication D/EventLogger: ]
2020-05-27 21:40:00.627 8348-8348/com.example.myapplication D/EventLogger: mediaPeriodCreated [eventTime=20.46, mediaPos=0.00, window=0, period=0]
2020-05-27 21:40:00.630 8348-8348/com.example.myapplication D/EventLogger: loading [eventTime=20.46, mediaPos=0.00, window=0, period=0, true]
2020-05-27 21:40:00.644 8348-8348/com.example.myapplication E/EventLogger: internalError [eventTime=20.48, mediaPos=0.00, window=0, period=0, loadError
      UnknownHostException (no network)
    ]
2020-05-27 21:40:00.647 8348-8348/com.example.myapplication E/EventLogger: internalError [eventTime=20.48, mediaPos=0.00, window=0, period=0, loadError
      UnknownHostException (no network)
    ]
2020-05-27 21:40:01.651 8348-8348/com.example.myapplication E/EventLogger: internalError [eventTime=21.48, mediaPos=0.00, window=0, period=0, loadError
      UnknownHostException (no network)
    ]
2020-05-27 21:40:03.655 8348-8348/com.example.myapplication E/EventLogger: internalError [eventTime=23.49, mediaPos=0.00, window=0, period=0, loadError
      UnknownHostException (no network)
    ]
2020-05-27 21:40:03.665 8348-8348/com.example.myapplication D/EventLogger: mediaPeriodReleased [eventTime=23.50, mediaPos=0.00, window=0, period=0]
2020-05-27 21:40:03.665 8348-8348/com.example.myapplication E/EventLogger: playerFailed [eventTime=23.50, mediaPos=0.00, window=0, period=0
      UnknownHostException (no network)
    ]
2020-05-27 21:40:03.665 8348-8348/com.example.myapplication D/EventLogger: loading [eventTime=23.50, mediaPos=0.00, window=0, false]
2020-05-27 21:40:03.665 8348-8348/com.example.myapplication D/EventLogger: state [eventTime=23.50, mediaPos=0.00, window=0, true, IDLE]
```

**Comment by marcbaechinger** [comment]
Yes, ExoPlayer is able to play offline content and the media is cached on disk.
The logs show that the player tries to download from the network though.

With the information available, it seems to me that the media has not been downloaded and stored for some reason. It would be great if you could do the process of downloading and playing the media and after this [take a bug report](https://developer.android.com/studio/debug/bug-report) and upload here. The bug report will then have included the entire logs which i can check.

For debugging reasons, it would also be interesting to check the download index before you try to play the downloaded media. We would see whether the url is indexed and what the state of the download is. The [documentation describes how](https://exoplayer.dev/downloading-media.html#querying-downloads) you can query the `DownloadIndex` from the `DownloadManager`.

**Comment by mddrill** [comment]
Okay, so in the process of reproducing this, I deleted and recreated my emulator and that seems to have solved the case where I press the download button to download the mp3. But when I stream the mp3, turn off wifi and and try to play the mp3 from disk it doesn't work. I was under the impression that since I'm playing the media source through the cache data source, it should cache the media file on disk while streaming, is this correct? If not, is there a way to accomplish this?

[bugreport-Pixel_2_API_29-2020-05-28-23-01-32-1c555016-052c-4162-a3a8-5273c2f0eaba.zip](https://github.com/google/ExoPlayer/files/4699471/bugreport-Pixel_2_API_29-2020-05-28-23-01-32-1c555016-052c-4162-a3a8-5273c2f0eaba.zip)

In case the cache data source _is_ supposed to cached the streamed mp3 on disk, here is a bug report where I reproduce this (it should be at around 10:57pm in the logs). After streaming the mp3, I can see the uid file gets created in the downloads directory, but there is no number directory with the .exo file.

As a side note, is there documentation that explains what that uid file is for? It seems like the .exo file is the actual media file, I'm curious what the uid file is doing.

**Comment by marcbaechinger** [comment]
Yes, the media file is cached to disk. When I add your url to the demo app and press the download button for it in the sample chooser activity it creates a file in

```
/sdcard/Android/data/com.google.android.exoplayer2.demo/files/downloads/7
```

the directory 7 may be different. In the directory there is a single file containing the cached file:

```
-rw-rw----  1 u0_a241 sdcard_rw 3.5M 2020-06-04 11:42 4.0.1591267346811.v3.exo
```

When putting in the airplay mode the media plays fine. I can stop the app or even redeploy with AndroidStudio and the file still plays from cache.

I tested this an a physical device. I'm afraid but my emulator is currently not working so I could not test this on an emulator.

I'd like to kindly ask you to do two things, **probably best on a physical device** so we can rule out any problems brought in by the emulator:

**1) Download your file in the demo app**
Add the url to the demo app and do the downloading and offline playback. You can then inspect what happens in case when it works. There are two step you can observe: 

a) Downloading the stream.
You'll see a notification confirming the download has ended. You can't see much there in the logs.  I see a single line saying that this is a progressive stream without periods. Just a single file:

```
com.google.android.exoplayer2.demo D/DownloadTracker: No periods found. Downloading entire stream.
```

After this the file is stored somehwere in `/sdcard/Android/data/com.google.android.exoplayer2.demo/files/downloads`.

b) Play the stream in airplay mode
If you now playback in airplay mode you can see the logs of playback just the same as when streamed from the net. 

**2) Review your download service**
After gaining trust that ExoPlayer can cache in the demo app you can look into your app. And do the same process. 

a) Make sure you are aware in which directory your cache is pointing to. Please do not use the cache directory of your file which the os would probably clean up in some ways. Probably start with [what the demo app is doing in the `DemoApplication` class](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java#L120).
b) Start with the simplest `cacheDataSourceFactory` you can think of, probably similar to what the demo app does. See my comment with the code snippet above for that.
c) Do the download and observe the logs for any suspicious things (no permission for storage, directory not found, ExoPlayer expections)
d) Check the download directory on your device whether it contains a directory created and a file downloaded.
e) play the file with airplane mode on
f) If this does not work, please create a bug report which contains the logs for all the steps a) - e). I think the current bugraport does only show the failed playbacks but not the download process. The first ExoPlayer line i see is

```
05-28 22:24:31.699 10133  5580  5580 D EventLogger: state [eventTime=2.68, mediaPos=0.00, window=0, false, BUFFERING]
```

That's where the playback starts and fails with an `UnkownHostException` because the your app wants to get to the network.

**Comment by mddrill** [comment]
I'm not sure if you understood my last post. Explicitly downloading the mp3 with DownloadService.sendAddDownload is working as I expect. What's not working as I expect is streaming with 

```
val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse(url))
player.prepare(mediaSource)
player.playWhenReady = true
```
I believe that if I do this directly without ever having downloaded the media, it should still cache the media on disk, right? Since I'm using a cacheDataSourceFactory.

When I do this, I can see the uid file getting created, but there is not exo file.

**Comment by ojw28** [comment]
You've configured the `CacheDataSourceFactory` to be read-only, by explicitly the `cacheWriteDataSinkFactory` argument to `null`:
```
CacheDataSourceFactory(
    Injector.provideCache(this),
    DefaultDataSourceFactory(this,
        DefaultDataSourceFactory(this, httpDataSourceFactory)),
    FileDataSource.Factory(),
    null,                                  // <--------- Configured as read only.
    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
    null
)
```

If you want it to be writable you should probably build one using the simpler constructor:
```
CacheDataSourceFactory(
    Injector.provideCache(this),
    DefaultDataSourceFactory(this,
        DefaultDataSourceFactory(this, httpDataSourceFactory)),
    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR
)
```

**Comment by mddrill** [comment]
The writable cache data source worked! Thanks.

Before you close this ticket, could you point me to documentation on what .uid and .exo files are/do? If there is no documentation, could someone give me a brief explanation?

**Comment by ojw28** [comment]
The `.uid` file is a unique identifier for the cache. The identifier is written into the name of the file (the actual content of the file is empty). It's used when querying the database for information related to the cache. Using a UID rather than a location allows this process to be robust against someone moving the cache, swapping SD cards in/out of their device, etc.

The `.exo` files contain cached media data. Each file may correspond to just a part of the original file to which they correspond.

The structure of the cache on disk is not part of our API. We make no guarantees about what files will be present or what data they contain. In other words, you should not write any code that relies on the information above.
