### ISSUE TITLE
DefaultTrackSelector - preferred audio/text based on track id.

### ISSUE THREAD

**Issue by tpiDev** [google/ExoPlayer#7419]
**DefaultTrackSelector - preferred audio/text based on track id.**

### [REQUIRED] Searched documentation and issues
Found: https://github.com/google/ExoPlayer/pull/4886 which describes possibility of override `DefaultTrackSelector#selectAudioTrack` which could be probably point of start to select expected track by ID with `TrackSelection.Definition`, but it looks more like a workaround for this case.

### [REQUIRED] Question
We want to start a playback of DASH media with expected audio and text track.
Currently `DefaultTrackSelector.Parameters` allow to specify `preferredAudioLanguage` and `preferredTextLanguage`. 

This case is not suitable for us, as each _stream track_ has specific ID and we need to select based on it. This ID we already know before preparing a playback, so it can be provided to `DefaultTrackSelector`. 

Im considering providing PR extending `Parameters` with `preferredTextIdTrack` and `preferredAudioIdTrack`, but first would like to ensure if it will be best approach, or it could be handled differently with ExoPlayer. Thanks for support!

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by tpiDev** [comment]
**Update**: It turned out logic is more complex, so it won't work with simple compare track id  in our case - it seems not proper for public PR.  However question would stay if it will be safe to rely simply on overriding of ```DefaultTrackSelector.selectAudioTrack``` to provide expected ```TrackSelection.Definition```

**Comment by tonihei** [comment]
Yes, it's safe to override `selectAudioTrack` to return the expected `TrackSelection.Definition` and `AudioTrackScore`. 

But please note two caveats:
 1. If multiple audio renderers have assigned track groups, this method will be called multiple times (once for each renderer) and `DefaultTrackSelector` will compare the returned `AudioTrackScore` values to decide which one to select. This will use the `Parameters` again.
 2. When overriding `selectAudioTrack`, you should use the protected `isSupported` method to check whether the renderer can actually play the format. Otherwise you may easily select a format that is not playable by a renderer.

> This case is not suitable for us, as each stream track has specific ID and we need to select based on it. 

Is there another differentiating property besides the id that would allow you the specify preferences (like language, role flags etc)? In general it seems preferable to use properties that can be applied across multiple streams, independent of the ids in the manifest. This helps to set parameters for a playlist or when reusing the player. The idea is that a user would not specify that they want to play id "dfdsfbvfb" (because that's meaningless from a user perspective), but rather say: "I prefer audio in Chinese, with additional audio description of the video track". Having said that, I think it also makes sense to have this logic in other places in your app and only instruct the player to prefer one particular track with a given id. If this is still what you need, we can think about adding this as a parameter to `DefaultTrackSelector`.

**Comment by tonihei** [comment]
@tpiDev  Do you have any further input to the questions above?

**Comment by tpiDev** [comment]
Thanks for feedback @tonihei ! Right now this topic is on hold and no further changes needed on your side..
