### ISSUE TITLE
how to play pcm file with exoplayer,can't find any tutorial.

### ISSUE THREAD

**Issue by meixililu** [google/ExoPlayer#7420]

**Comment by meixililu** [comment]
can anybody help?

**Comment by marcbaechinger** [comment]
What kind of file are you trying to play? Can you send me a link to that file?
It depends what container you are using (WAV?) and what kind of PCM data is in that container. 

I can test for you in case you provide me with a link to the file or the file itself.  If you don't wish to post it publicly, please submit the issue, then email the link to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number.

**Comment by meixililu** [comment]
sorry,I want to play this pcm(http://res.mzxbkj.com/temp/3c37e8276a5fa206242139dbb8b4ec87.pcm) with exoplayer,but failed.

**Comment by marcbaechinger** [comment]
Media sample data need to be in a container format that is supported by ExoPlayer. For PCM data this is commonly a WAV file. The file for which you pasted the link in your comment seems to be a file which just contains the raw PCM data.

There is a page around supported media files for Android which is helpful for ExoPlayer as well, because that's what the underlying codecs of the media framework support. There is a [section about wav files](https://developer.android.com/guide/topics/media/media-formats) which tells what kind of PCM data is supported (search for `PCM/WAVE`on that page).

So to play the file with ExoPlayer you need to convert it to a WAV file first.

**Comment by meixililu** [comment]
Thank you.
