### ISSUE TITLE
Player Stuck at Discontinuity

### ISSUE THREAD

**Issue by CeenIt** [google/ExoPlayer#7432]
Hi,

I am experiencing the same thing mentioned in the closed issue #7237
The following URL plays fine in QuickTime, ShakaPlayer, VideoJS, AVPlayer and more but NOT in ExoPlayer.
When ExoPlayer reaches the discontinuity it gets confused and fails.
https://s3-us-west-1.amazonaws.com/dev.ceen.it-media/1080-1081-master-v3.m3u8

This url is a master playlist that looks like this:
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=2305600,RESOLUTION=1920x1080,VIDEO-RANGE=SDR,CODECS="avc1.4d402a,mp4a.40.2",FRAME-RATE=50.000,AUDIO="program_audio_0"
1080-1081-video-index-v3.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio_0",LANGUAGE="und",NAME="Alternate Audio",AUTOSELECT=YES,DEFAULT=YES,URI="1080-1081-audio-index-v3.m3u8"

The video comes from a playlist that looks like this:
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="1080-video-init.mp4"
#EXTINF:2.033333,
1080-native-ios-selfie-video-0.m4s
#EXTINF:1.133333,
1080-native-ios-selfie-video-1.m4s
#EXT-X-DISCONTINUITY:
#EXTINF:3.000000,
1081-web-android-selfie-video-0.m4s
#EXTINF:0.066667,
1081-web-android-selfie-video-1.m4s
#EXT-X-ENDLIST

The audio comes from a playlist that looks like this:
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="1080-audio-init.mp4"
#EXTINF:2.020136,
1080-native-ios-selfie-audio-0.m4s
#EXTINF:1.207438,
1080-native-ios-selfie-audio-1.m4s
#EXT-X-DISCONTINUITY:
#EXTINF:2.020136,
1081-web-android-selfie-audio-0.m4s
#EXTINF:1.076984,
1081-web-android-selfie-audio-1.m4s
#EXT-X-ENDLIST

Thank you!

**Comment by AquilesCanta** [comment]
Seems to me the issue here is that the discontinuity tags have a trailing colon `:`. From reading [the spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.3) it doesn't seem to me this is legal.

However, quicktime is able to parse the tag correctly (I was suspecting the other players were just ignoring the tag and still handling the discontinuity correctly). I'll see if I can write a workaround for this, but the fastest way for you to get this running is to remove the trailing colon.

Can you provide some info on how you produced the content? Did you use a tool to generate the playlists?

**Comment by gpdeedler** [comment]
That was it!
Thank you so much!
No need to figure out a workaround as I was able to correct the issue on my end.

**Comment by AquilesCanta** [comment]
@gpdeedler are you in any way related to @CeenIt ?

Aside, could you provide info on how the streams were generated? It'd be useful to know if this was due to a manually-crafted malformed playlist or the default behavior of a packager.

**Comment by gpdeedler** [comment]
Yes I'm the same guy but different projects so different id's.

The streams were generated manually so it was my mistake!

**Comment by AquilesCanta** [comment]
Thank you for the confirmation!
