### ISSUE TITLE
Allow setting "allow-frame-drop" to 0 when MediaCodecVideoRenderer is rendering to a surface (Q+)

### ISSUE THREAD

**Issue by emilieroberts** [google/ExoPlayer#7439]
When MediaCodecVideoRenderer is rendering to a surface on SDK 29+, allow-frame-drop should be set to 0, or be user configurable. This is an integer field that should be set when [configuring the MediaFormat here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1332).

By default, MediaCodec can silently drop frames. See [using the output surface](https://developer.android.com/reference/android/media/MediaCodec#using-an-output-surface) in the Android docs.

Currently users who need to ensure they get every frame, for video editing for example, cannot rely on this renderer.

**Comment by andrewlewis** [comment]
For batch processing like video editing, apps can override `MediaCodecVideoRenderer.getMediaFormat` to set `allow-frame-drop` (side note: depending on how the media clock is handled, they likely need to subclass the renderer anyway to turn off ExoPlayer's late frame dropping logic). This applies when rendering to a `SurfaceTexture` or `ImageReader`.

Before Android Q, according to the media framework team, frame dropping occurs once ten or more frames are pending handling via `onFrameAvailable`. I'm not certain about the details, but I think the way to avoid this is to avoid blocking the thread on which `onFrameAvailable` is called, and to call `updateTexImage` soon after each call to `onFrameAvailable`.

My understanding is that apps playing video to `SurfaceView` don't need to do anything because frames can only be dropped when they are on the same vsync in that case (there is no user-visible impact).

**Comment by andrewlewis** [comment]
Marking as a low priority enhancement in case we want to set the configuration key by default when targeting Q or later if we know we aren't using `SurfaceView`.

**Comment by emilieroberts** [comment]
Just FYI: If I use a GLSurfaceView for decoding, and try to decode as fast as possible, 50-75% of frames are dropped in the current implementation.

Overriding getMediaFormat in MediaCodecVideoRenderer and setting the integer "allow-frame-drop" to 0 prevents this and 0 frames are dropped.

`mediaFormat.setInteger("allow-frame-drop", 0)`

Also noticed MediaFormat is missing a proper MediaFormat key const for this value in Android proper.

**Comment by andrewlewis** [comment]
Regarding the `MediaFormat` key, this was added just after the API cut for Android S unfortunately but should be in the next release.

**Comment by ojw28** [comment]
Is the configuration key set to the best value for normal video playback? If so then I'm not sure there's anything to do here, since that's what `MediaCodecVideoRenderer` is designed for. If using it for another purpose, extending it to override the key seems reasonable.

**Comment by andrewlewis** [comment]
Yes. If an app wants to do batch processing (receiving every frame in a `SurfaceTexture`) it can override `getMediaFormat` as described earlier in this thread.
