### ISSUE TITLE
Support native memory allocation controlled by LoadControl

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#7445]
### [REQUIRED] Use case description
Base on my tests on old  devices, such as Android version 4.2 ~ 4.4, when the app had allocated some heap memory, eg the app loaded some images. At this time , if start to play, the player need to allocate memory. There maybe cause some bad effects:

-  The Dalvik virtual machine may cause gc frequently, base on my tests, this maybe cost 100ms ~ 200ms, and cause audio underrun and video drop frames. The playback is terrible.

- If the memory is limited, and the content bitrate is high, maybe cause OOM.
[https://github.com/google/ExoPlayer/issues/7354#issuecomment-628899924](https://github.com/google/ExoPlayer/issues/7354#issuecomment-628899924).
Like the issue-7354, it maybe could resolve the issues by setting `DefaultLoadControl.setPrioritizeTimeOverSizeThresholds = false`, I think, another way to solve this issue is to allocate the memory in native.

**Comment by ojw28** [comment]
> The Dalvik virtual machine may cause gc frequently, base on my tests, this maybe cost 100ms ~ 200ms, and cause audio underrun and video drop frames. The playback is terrible.

You can avoid this by block allocating the entire media buffer up front. This avoids repeated allocations triggering the GC when the media buffer would otherwise need to grow during the initial buffering stage. You can do this by setting `initialAllocationCount` to non-zero when creating a `DefaultAllocator`, which you can then pass into a `DefaultLoadControl`. We have not generally found this to be necessary when playing content that's reasonable for the mobile device on which it's being played (see comment below), but it does effectively avoid this type of GC problem when a large buffer does end up being required.

> If the memory is limited, and the content bitrate is high, maybe cause OOM.
#7354 (comment).

42 Mbps is unnecessary for any Android device by at least a factor of 3. Probably a much larger factor for Android devices that aren't connected up to a big screen. At best delivering such high quality content to a mobile device is going to waste a lot of battery and network for no user benefit. It's also not surprising that such streams would be unsupported, particularly on older devices.

I don't think we need to do anything here. The percentage of devices affected is low single digits at this point, most streams that are reasonable to deliver to such devices don't cause this issue to occur, and there is the block allocation workaround for unreasonable streams, as outlined above.
