### ISSUE TITLE
How do I Play AVI File?

### ISSUE THREAD

**Issue by syedalinaqi** [google/ExoPlayer#745]
I m trying to play this file http://archive.org/download/BigBuckBunny_328/BigBuckBunny.avi
but getting error... I have tried all the methods in the demo app... but no use... so how do i play it??

**Comment by andrewlewis** [comment]
ExoPlayer doesn't include an Extractor for reading AVI containers, but the file may be readable using the platform MediaExtractor via FrameworkSampleSource. Note that the class is deprecated due to the [problems described in its javadoc](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/FrameworkSampleSource.java).

Even if it's possible to extract the samples, be warned that in general Android devices do not have codecs for some of the formats often used in AVI files (like VfW and DivX).

**Comment by kunalbhatia** [comment]
can we still not support avi files or we have a alternative way to play it?

**Comment by andrewlewis** [comment]
I'm afraid we still don't, and have no plans to support this via the new extractor model. As per my previous comment, you can try the deprecated FrameworkSampleSource.

If you have control over the input media format, please use a more modern container like MP4.
