### ISSUE TITLE
Loop creates OutOfMemoryError when playing video from local file

### ISSUE THREAD

**Issue by iWillBeUnderYourBed** [google/ExoPlayer#7480]
When I try to play a video from a local file (I assume it's `.mp4`) in the `ExoPlayer 2.10.6`, I get a `OutOfMemoryError`. I download the video from a `firebase` DB and then load it with `Exoplayer`. The `fragment` with the `Exoplayer` exists twice, but I release the `Exoplayer` in `onPause`.

Here where I initialise the `Exoplayer`, `displayVideo` is called in `onResume` and later while the `fragment` is running:
    
    private void displayVideo() {       
        releaseMediaPlayer();
        exoPlayer = ExoPlayerFactory.newSimpleInstance(getContext());      
        mMediaPlayerView.setPlayer(exoPlayer);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getContext(), com.google.android.exoplayer2.util.Util.getUserAgent(getContext(), getContext().getString(R.string.app_name)));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.fromFile(new File(getContext().getExternalFilesDir(null), profilePicVideoName)));
        exoPlayer.prepare(videoSource);
        exoPlayer.setPlayWhenReady(true);
        exoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);
        mMediaPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);
    }

Here where I release the `Exoplayer`:

    @Override
    public void onPause() {
        super.onPause();
        releaseMediaPlayer();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        releaseMediaPlayer();
    }

    private void releaseMediaPlayer() {
        if (exoPlayer != null) {
            exoPlayer.release();
            exoPlayer = null;
        }
        mMediaPlayerView.setPlayer(null);
    }

The video-file in `firebase` is < 1MB.

`new File(getContext().getExternalFilesDir(null), Helper.profilePicVideoName).length()` = 629440

And the **error-message** is pretty useless:

    E/art: Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 10220 free bytes and 9KB until OOM"
    E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 19092 free bytes and 18KB until OOM

Ok, without the loop of the video, no `OutOfMemoryError` is thrown. It doesn't matter, if I loop the video with `setRepeatMode`, with a `LoopingMediaSource` or by adding a Listener that calls `exoPlayer.prepare`.

The only thing that stops the `OutOfMemoryError` is adding a listener, and with every loop to release everything with `releaseMediaPlayer()` and then re-instantiating `Exoplayer`, `Mediasource` and so on. But then there is a black frame between every loop and the CPU is used way more than necessary. The memory consumption drops DRASTICALLY from 180 MB, where `OutOfMemory` occurs to < 100 MB. 

Why can't I loop the regular way? What can I do to get rid of the black frame or to optimize CPU usage?

Version of ExoPlayer being used
2.10.6

Device(s) and version(s) of Android being used
samsung sm-9005 - galaxy note3
android version 5.0

**Comment by ojw28** [comment]
Please can you share a piece of content that reproduces this issue?

**Comment by iWillBeUnderYourBed** [comment]
This is what I test it with at the moment, but the problem seems to appear with every video file.

[07b8d94a-104a-4d26-9a62-855b9375693bVIDEOVIDEOVIDEO.zip](https://github.com/google/ExoPlayer/files/4759126/07b8d94a-104a-4d26-9a62-855b9375693bVIDEOVIDEOVIDEO.zip)

**Comment by ojw28** [comment]
I tried using repeat modes with the provided video on both 2.10.6 and 2.11.5 in our demo app, and did not see the issue on a couple of devices I have (Galaxy S8, Pixel). The Java heap stayed stable at about ~40MB for the whole app (not just the player), which should not cause an `OutOfMemoryError` on any device.

* Is this issue device specific?
* Does the issue reproduce with the ExoPlayer demo app?
* Is it possible that the rest of your app is consuming a lot of memory, and that the additional memory that the player is using is pushing your memory usage over the edge? If you're not using `android:largeHeap="true"`, that's something you should look at.

---

Some additional background that might help to make sense of this: When repeat mode is enabled, ExoPlayer treats a short video the same as a longer video from a buffering perspective. What this means is, if the buffering policy is to "buffer 15 seconds", ExoPlayer will build a 15 second buffer that effectively ends up containing the 1 second video repeated 15 times. This will cause increased memory consumption compared to the case where the same short video is played with repeat mode turned off. This is obviously inefficient, however we do not think it's important to optimize the case because:

1. The increased memory consumption only occurs when the video is shorter than the target buffer duration. For longer duration videos it makes no difference.
1. The increased memory requirement is still less than or equal to the memory required to play a longer duration video with repeat mode turned on or off. We assume nearly all apps will need to play some longer videos without running out of memory, which implies they need to be able to handle this amount of memory being required for playback anyway.

**Comment by ojw28** [comment]
@iWillBeUnderYourBed - Please respond to the questions above if you wish for us to investigate this further. Thanks!

**Comment by iWillBeUnderYourBed** [comment]
Sorry for not posting sooner, I don't get to work on the problem for now. Also thank you @ojw28 for the background info. I think that's the issue, I have really small videos and putting them in loop mode let the memory usage explode. I tweaked a few parameter, that helped, I can't post whcih ones for now, but I think this issue can be closed.
