### ISSUE TITLE
Audio is not working when using UDP with ffmpeg?

### ISSUE THREAD

**Issue by vjsingh96** [google/ExoPlayer#7483]
Here is my FFmpeg command. 

`        final String[] cmd = {"-i", videoPath, "-vcodec", "copy", "-af", "volume=20" + "dB", "-strict", "experimental", "-f", "mpegts", "udp://127.0.0.1:8081", outputAudioMux};
`
Here my Exoplayer code setting.
 ```
player = ExoPlayerFactory.newSimpleInstance(this);
        player.addAnalyticsListener(new EventLogger(null));
        playerView.setPlayer(player);
        MediaSource mediaSource;
        if (converted) {
            mediaSource = buildMediaSource(videoUri);
        } else {
            mediaSource = buildMediaSource(Uri.parse("udp://@127.0.0.1:8081"));
        }
        player.setVolume(100f);
        player.setPlayWhenReady(playWhenReady);
        player.seekTo(currentWindow, playbackPosition);
        demo demo = new demo();
        player.prepare(mediaSource, false, false);
```

The audio of the video is working fine when after completed the conversion

**Comment by ojw28** [comment]
"Not working" is not a sufficient description of the problem for us to help. Please provide a detailed description and properly fill in the issue template. Thanks!

**Comment by vjsingh96** [comment]
@ojw28 Thank you for the reply.
My issue is that I am using FFmpeg to increase the volume level of the video at the same time using exoplayer to preview the video and for live preview, I,m using UDP to stream real-time video while converting through FFmpeg. Video streaming is working fine but the audio of that video is not playing.

**Comment by ojw28** [comment]
I'm not sure there's really much we can do to help here, since the time that would be required for us to recreate what you're doing is far too great to justify spending time on, given it's such a niche use case. If a fully working sample project were provided as source code, it would be somewhat easier.

As a general comment, converting a video file through FFmpeg sounds like a very inefficient and error-prone approach to increasing volume, if that's all you're trying to do. You'd be much better off discarding this approach entirely, and writing a custom `AudioProcessor` to boost volume during playback inside of ExoPlayer. There's an example, albeit for a slightly different use case, in https://github.com/google/ExoPlayer/issues/6090.
