### ISSUE TITLE
 ExoPlayer coding limitations

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#7488]
Hi  all,

I am working on customizing a player based on the ExoPlayer library.
Therefore, I need some information before starting the development :
The ExoPlayer can support a frame rate of 50fps? Are there any limitations of the ExoPlayer library on streams with 1920 * 1080 resolution?

Thank you very much in advance for your response.

BR,

**Comment by ojw28** [comment]
ExoPlayer doesn't have any limitations with respect to certain frame-rates or resolutions.

The capabilities of the device on which the app is running may come in to play, however. For example, it's possible that some very low end or old devices will not be able to handle 1080p at 50fps, or will need to drop frames to keep up. Note that any such restrictions are inherent restrictions of the device capabilities, rather than restrictions caused by ExoPlayer.
