### ISSUE TITLE
Change quality programmatically

### ISSUE THREAD

**Issue by johnsky95** [google/ExoPlayer#7489]
Hi to All!
I am using the latest exo player currently and I am stuck at a feature for a week almost.

I have the below code:
```
    private fun play(
        videos: Array<Uri>,
        audios: Array<Uri>,
        subtitles: Array<Subtitle>
    ) {
        val p = player!!

        val dataSourceFactory = DefaultDataSourceFactory(
            context,
            HttpClient.USER_AGENT_CHROME_WINDOWS_10
        )
        val factory = ProgressiveMediaSource.Factory(dataSourceFactory)
        val sources = ArrayList<MediaSource>()

        videos.forEach { sources.add(factory.createMediaSource(it)) }
        audios.forEach { sources.add(factory.createMediaSource(it)) }
        subtitles.forEach {
            val subtitleFormat =
                Format.createTextSampleFormat(
                    it.id, // An identifier for the track. May be null.
                    it.mime, // The mime type. Must be set correctly.
                    C.SELECTION_FLAG_DEFAULT, // Selection flags for the track.
                    it.language // The subtitle language. May be null.
                )

            sources.add(
                SingleSampleMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(it.uri, subtitleFormat, C.TIME_UNSET)
            )
        }

        p.prepare(MergingMediaSource(*sources.toTypedArray()))
        p.playWhenReady = true
    }
```

Video's list and Audio's are sorted by quality from highest to lowest.
When I simulate a low network, exo player still starts the video on Full HD.

I wanted to change programmatically the quality so it starts from medium, but oh my god, it is lots of studying just to change a track quality. I have studied the Demo App how their dialog does change, and then I needed to read about track selector, overrides etc etc ...

Is there any other way to change the current playing track instead of studying the whole architecture of EXO Player.

Also, I wonder why exo player is not selecting the best quality using the Bandwidth, I though this is supported as well?

Thanks for your time and hope to get some help.

**Comment by ojw28** [comment]
> Also, I wonder why exo player is not selecting the best quality using the Bandwidth, I though this is supported as well?

There are adaptive media specifications that support this properly: DASH, HLS and SmoothStreaming. We support all three, and would recommend them in that order of preference (i.e., DASH first).

You can't generally provide a player with a bunch of different quality videos files and expect adaptive format selection to just work. Most players don't support merging of separate video files at all. So, if you want adaptive playback, you should really be using a proper adaptive media specification such as DASH.

**Comment by johnsky95** [comment]
> > Also, I wonder why exo player is not selecting the best quality using the Bandwidth, I though this is supported as well?
> 
> There are adaptive media specifications that support this properly: DASH, HLS and SmoothStreaming. We support all three, and would recommend them in that order of preference (i.e., DASH first).
> 
> You can't generally provide a player with a bunch of different quality videos files and expect adaptive format selection to just work. Most players don't support merging of separate video files at all. So, if you want adaptive playback, you should really be using a proper adaptive media specification such as DASH.

Thanks for your feedback.

How I can then change the quality programmatically?

**Comment by ojw28** [comment]
If you use DASH, HLS or SmoothStreaming then the quality will automatically vary based on the available bandwidth by default. For manual programmatic selection, by far the easiest way is to set constraints on `DefaultTrackSelector`. For example:
```
trackSelector.setParameters(
    trackSelector.buildUponParameters()
        .setMaxVideoSize(1024, 768));
```
If you use DASH, HLS or SmoothStreaming, automatic adaptation based on bandwidth will still occur for the subset of available tracks that satisfy the constraints. Unlike automatic adaptation, the transition when a constraint is set will not be seamless (this is by design).

Constraint based track selection will work for the case where you're merging separate video files as well, except without automatic adaptation, so you'll just get the best single track that satisfies the constraints. Note also that some information might not be available to the track selector with this approach. In particular, the track selector might be able to determine what the bitrate of each of your separate files is, in which case the `setMaxVideoBitrate` constraint wont work properly. This is one of the things that the proper adaptive streaming specifications solve, since bitrate, resolution etc of each track are specified in a manifest file that the player downloads at the start of playback. Another thing that proper adaptive streaming specification solve is allowing seamless quality switches, by ensuring that key-frames are properly aligned in the different tracks.

For learning more about programmatic selection, there's quite a bit of information available:

* https://exoplayer.dev/track-selection.html
* https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html
