### ISSUE TITLE
base64 transcoding key can not play

### ISSUE THREAD

**Issue by guangmingxiong9999** [google/ExoPlayer#7493]
I play after OpenSSL base64 transcoding key, and then can not play, may I ask what is the problem,This is my URL link http://pp3zvsk2n.bkt.clouddn.com/video/20200610/1591872123205dd04/ea33c51a84db4c78bf.m3u8.  please reply to receive

**Comment by ojw28** [comment]
This video doesn't play for me in VLC or Safari either, so it seems that the media is broken.

Closing because diagnosing broken media is outside the scope of this issue tracker. I'd suggest you ask on the tracker for whatever tool you're using to generate this media, or on StackOverflow. If you have a piece of media that plays successfully with other players and only ExoPlayer has an issue, then please let us know.

**Comment by guangmingxiong9999** [comment]
use ijkPlayer can play @ojw28

**Comment by ojw28** [comment]
It looks like the key URI is returning the wrong number of bytes (24, whereas I think 16 is expected because the key is supposed to be 128 bits). I suggest you take a look at that, and also get to the point where it plays correctly in VLC or Safari.

**Comment by guangmingxiong9999** [comment]
I know Thanks
