### ISSUE TITLE
ExoPlayer video rotation with GL

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7495]
I have check ExoPlayer GL demo. I added `surface_type="texture_view"` in `PlayerView` in xml. Then I rotate `PlayerView` on 90 with button click. But `PlayerView` is rotate but video plays same as before, Video frame did not show at 90 angle.

Please guide me.

I hope for your response.

**Comment by ojw28** [comment]
Do you really want to rotate the whole `PlayerView`? It sounds like a strange thing to want to do because it would presumably rotate the controls to an orientation other than that of the device.

If you just want to rotate the video then I think you should be looking for a solution that uses `TextureView.setTransform`. There's an example in `PlayerView` itself. Either way, it's probably best if you explain exactly what your use case is, so that we can provide the best guidance.

**Comment by ghost** [comment]
Thanks for your response.
Actually, I am working on video editing app. There is video rotation functionality. So I want to rotate video to display use how it looks like. So Apply `90` rotation to `Playerview`. But If `GL filter` applied then rotation did not work. My problem is that how can I rotate video after `GL filter` applied.

**Comment by ojw28** [comment]
Have you tried approaches based on `TextureView.setTransform` as suggested above?

**Comment by ghost** [comment]
I didn't know how to use that, can please you explain me in detail that how can I use that in  `ExoPlayer GL demo` to rotate video?

**Comment by ojw28** [comment]
In the GL demo the rendering is done by `BitmapOverlayVideoProcessor`. The `a_position` and `a_texcoord` attributes define the positions of the vertices of the rectangle that ends up being drawn, and the texture coordinates that are mapped to each one, respectively. So I think you need to understand enough OpenGL to work out how that works, and then modify that code to render the video rotated.

As a quick test, I was able to rotate the video by modifying [this line](https://github.com/google/ExoPlayer/blob/r2.11.7/demos/gl/src/main/java/com/google/android/exoplayer2/gldemo/BitmapOverlayVideoProcessor.java#L100) to use the coordinates:
```
{0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1}
```
This also rotated the overlay, so depending on exactly what you're trying to do, you might need to figure out how to split the rendering of that out.

Closing this, since it's more an OpenGL question than an ExoPlayer question. If you need help with the OpenGL parts of `BitmapOverlayVideoProcessor`, you'd probably be best off asking somewhere like StackOverflow, and posing the question in terms of OpenGL.
