### ISSUE TITLE
Timeshift HLS

### ISSUE THREAD

**Issue by mr-bob** [google/ExoPlayer#750]
Hi,

I'd like to know if you have any plans on timeshifting / seeking functionallity on live HLS?
I get a three hour window from my server so it is possible to jump backwards but when I seek in the exoplayer it doesn't work.

Any ideas, suggestions or ETA on when this might be implemented?
If I get pointed in a helpful direction I might be able to contribute with a solution myself.

/ Bob

**Comment by haitech** [comment]
See #87
I dont think there is any ETA for it yet, and most likely Dash/Smoothstream will be implemented first

**Comment by ojw28** [comment]
Yes, this is tracked by #87, and DASH will be implemented first (it's already more or less done for DASH; it's just not accessible in a particularly easy way).

**Comment by dahlbergbob** [comment]
Can I get a reminder on when the dash-implementation is done so that I can borrow it and implement it for HLS aswell?




And can I get in touch with the person writing it so that I get the main changes a tad more served than searching in the blind. 




That would be awsome! =)


-- 

#! 

----------------------------------------------Bob Dahlberg

@mr_bob

github.com/mr-bob

linkedin.com/in/dahlbergbob
