### ISSUE TITLE
Retrieve current active sources

### ISSUE THREAD

**Issue by johnsky95** [google/ExoPlayer#7507]
### [REQUIRED] Searched documentation and issues
I have searched over stackoverflow and same on the issues on github for exo player.

### [REQUIRED] Question
How to receive current playing sources from the player, like: Video Url, Audio url, Subtitle Url etc.

I know some people say that, If you give the url to the player, why you do not save it. But the thing is that, I do not give to the player only one url but instead a list of. Then player selects automatically one. I want to receive the one which player is using currently.

Thank You.

**Comment by kartiknagarro** [comment]
@johnsky95 You can use getCurrentWindowIndex() method on player object.

**Comment by KartikMalik06** [comment]
@johnsky95  you can use `getCurrentWindowIndex()` method on player object.

**Comment by AquilesCanta** [comment]
If you want to know which item in the playlist the Player is playing then please let me know, but because of

> Then player selects automatically one

I suspect that you are playing adaptive media and you want to get the URLs which the player is consuming from. Depending on what you want to do with that URL, you can use [MediaSourceEventListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.html), which you can inject via [addEventListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSource.html#addEventListener-android.os.Handler-com.google.android.exoplayer2.source.MediaSourceEventListener-). And then listen for [onLoadStarted](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.html#onLoadStarted-int-com.google.android.exoplayer2.source.MediaSource.MediaPeriodId-com.google.android.exoplayer2.source.MediaSourceEventListener.LoadEventInfo-com.google.android.exoplayer2.source.MediaSourceEventListener.MediaLoadData-) events, from where you can obtain the [dataSpec](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.LoadEventInfo.html#dataSpec) associated with the load.

Please let me know if this answers your question.

**Comment by johnsky95** [comment]
> If you want to know which item in the playlist the Player is playing then please let me know, but because of
> 
> > Then player selects automatically one
> 
> I suspect that you are playing adaptive media and you want to get the URLs which the player is consuming from. Depending on what you want to do with that URL, you can use [MediaSourceEventListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.html), which you can inject via [addEventListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSource.html#addEventListener-android.os.Handler-com.google.android.exoplayer2.source.MediaSourceEventListener-). And then listen for [onLoadStarted](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.html#onLoadStarted-int-com.google.android.exoplayer2.source.MediaSource.MediaPeriodId-com.google.android.exoplayer2.source.MediaSourceEventListener.LoadEventInfo-com.google.android.exoplayer2.source.MediaSourceEventListener.MediaLoadData-) events, from where you can obtain the [dataSpec](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSourceEventListener.LoadEventInfo.html#dataSpec) associated with the load.
> 
> Please let me know if this answers your question.

Thanks for your reply. Well it is not a playlist but a MergedMediaSource which has the same video but on different qualities. It also has subtitles as well the audio.

I wanted to know how to receive current video url, audio url and subtitle url which is automatically selected from Exo.

Thanks again.

**Comment by johnsky95** [comment]
> @johnsky95 you can use `getCurrentWindowIndex()` method on player object.

Thats work for a Playlist. But I am using a MergedMediaSource and I am playing same video, only with list of urls which are different qualities, different audios and subtitles.

Thank you.

**Comment by AquilesCanta** [comment]
But if you are using a custom MediaSource (I'm assuming `MergedMediaSource` is a custom component unrelated to `MergingMediaSource`), then I think you are in the best position to decide how to surface this information, since at some point in your code, you should know which is the MediaSource you are obtaining samples from. Am I missing something?

**Comment by johnsky95** [comment]
> But if you are using a custom MediaSource (I'm assuming `MergedMediaSource` is a custom component unrelated to `MergingMediaSource`), then I think you are in the best position to decide how to surface this information, since at some point in your code, you should know which is the MediaSource you are obtaining samples from. Am I missing something?

It was a typo I am sorry. I am using the built one MergingMediaSource

**Comment by AquilesCanta** [comment]
Could you describe in detail what you are trying to achieve?

**Comment by johnsky95** [comment]
> Could you describe in detail what you are trying to achieve?

`    private fun play(
        videos: Array<Uri>,
        audios: Array<Uri>,
        subtitles: Array<Subtitle>
    ) {
        val dataSourceFactory = DefaultDataSourceFactory(
            context,
            "ExoPlayer"
        )
        val factory = ProgressiveMediaSource.Factory(dataSourceFactory)
        val sources = ArrayList<MediaSource>()

        videos.forEach { sources.add(factory.createMediaSource(it)) }
        audios.forEach { sources.add(factory.createMediaSource(it)) }
        subtitles.forEach {
            val subtitleFormat =
                Format.createTextSampleFormat(
                    it.id, // An identifier for the track. May be null.
                    it.mime, // The mime type. Must be set correctly.
                    C.SELECTION_FLAG_DEFAULT, // Selection flags for the track.
                    it.language // The subtitle language. May be null.
                )

            sources.add(
                SingleSampleMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(it.uri, subtitleFormat, C.TIME_UNSET)
            )
        }

        p.prepare(MergingMediaSource(*sources.toTypedArray()))
        p.playWhenReady = true
    }`

I use the above code to play some urls.

The player picks some urls automatically, and I need to know what is the url that the player is currently using for Video, Audio and Captions.

**Comment by ojw28** [comment]
> The player picks some urls automatically, and I need to know what is the url that the player is currently using for Video, Audio and Captions.

I think it's clear that you want a way of retrieving the URLs corresponding to the selected tracks. What you haven't explained is _why_ you need to do this, which is important when evaluating this request. It's not something that we currently support, and without a clear motivating use case we're unlikely to add support for it.
