### ISSUE TITLE
IMA post roll is not playing well

### ISSUE THREAD

**Issue by hyl0376** [google/ExoPlayer#7518]
### [REQUIRED] Issue description
In a demo app, playing post roll after the video ends looks abnormal.

### [REQUIRED] Reproduction steps
1. When video ends with no seeking action, post roll ad layer is not exposed. And then, set app to background (like press home button) and back to foreground, post roll is start at first position not the paused position.
2. When video ends with seeking action (seek to the end of the video), post roll ad layer is well exposed and played. But  set app to background (like press home button) and back to foreground, post roll is stopped.

Tested with ExoPlayer demo app, 'IMA sample ad tags' - VMAP post-roll, VMAP post-roll + bumper.

### [REQUIRED] A full bug report captured from the device
1. [logcat](https://github.com/google/ExoPlayer/files/4796104/exoplayer_postroll_play_ends.txt)
2. [logcat](https://github.com/google/ExoPlayer/files/4796107/exoplayer_postroll_play_ends_seek.txt)
[bugreport.zip](https://github.com/google/ExoPlayer/files/4796108/bugreport.zip)

### [REQUIRED] Version of ExoPlayer being used
2.11.5

### [REQUIRED] Device(s) and version(s) of Android being used
Galaxy note8 API 26, Android Emulators API 29

**Comment by andrewlewis** [comment]
Thanks for reporting this. There are two bugs here:
1. Postrolls now preload (since the recent API changes), but that means we need to trigger content complete when transitioning to the preloaded postroll.
1. On resuming from background during a postroll, the period duration is unset briefly (I think we no longer use the content duration from the ad playback state) so we think the ad has ended and tell the IMA SDK that, which causes a `stopAd` call.

We should have a fix for these soon.

**Comment by ojw28** [comment]
Fixed in the commits referenced above. This will be part of 2.11.6, which should be released today or tomorrow.
