### ISSUE TITLE
Widevine Initial Bitrate

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7534]
Hi, @ojw28

I am writing this as a question in regards to a previously closed bug 6756. Where provided solution is not working for me. Since that issue is in locked state so I am unable to add comment on same thread.

**Original Issue**
How to ensure exoplayer starts with a specific bitrate #6756

**Already Reported Bug**
[issue.](https://github.com/google/ExoPlayer/issues/6756)

**ExoPlayer Version**
2.11.5

**Solution Provided**
Using maxVideoBitrate and setForceHighestSupportedBitrate(true) did the trick and not setInitialBitrateEstimate.

**Problem**
Even after setting a high video bit rate of 1920 my content always plays in low bit rate. Below is my code. I also tried with setInitialBitrateEstimate but no help. Is there anything else needs to ensure the content plays on certain bit rate at start. Please help me out here with how to set a initial bit rate in the Player.

Thanks in advance
```
if (trackSelectorParameters == null) {
  var trackBuilder=  DefaultTrackSelector.ParametersBuilder(mContext).setMaxVideoBitrate(1920)
  if (Util.SDK_INT >= 21) {
    trackBuilder.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(mContext))
  }
  trackSelectorParameters = trackBuilder.build()
}
```

**Comment by icbaker** [comment]
> Even after setting a high video bit rate of 1920 my content always plays in low bit rate.

I could be wrong, but 1920 looks suspiciously like a horizontal resolution (i.e. 1920 x 1080), not a bitrate in bits-per-second, e.g. 8Mbps.

[`DefaultTrackSelector.ParametersBuilder#setMaxVideoBitrate(int)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.ParametersBuilder.html#setMaxVideoBitrate-int-) says "Maximum allowed video bitrate in bits per second.". 1920 bits-per-second is only 1.9kbps, which is **very** low for a video file (i.e. a 90 minute movie would be only 855 kilobytes).

 If you're trying to set a max resolution, you need to use [`DefaultTrackSelector.ParametersBuilder#setMaxVideoSize(int, int)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.ParametersBuilder.html#setMaxVideoSize-int-int-). 

It's hard to offer any more help without access to the media you're using to test this so that we can reproduce and understand the problem on our end. If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using subject "Issue #7534". Please also update this issue to indicate you’ve done this.

**Comment by Taranlayal10** [comment]
My bad I was setting resolution instead of Bit rate value. It is resolved now, Thanks
