### ISSUE TITLE
DASH Playready Content not playing on sample ExoPlayer for Android TV

### ISSUE THREAD

**Issue by khushank9** [google/ExoPlayer#7535]
### Issue description
DASH content protected with Playready DRM is not playable via Sample Exoplayer App for Android TV device.

### Reproduction steps
Use the following Content and License URL's in media.exolist.json for playback.
**Please note that the similar content is Playable via Bitmovin for Edge browser that supports DASH+ Playready.**
###  Link to test content
```
    {
        "name": "Dash Playready",
        "uri": "https://delta19tatasky.akamaized.net/out/vod/v1/PKTS2020032310085103_smil/i/25.mpd",
        "drm_license_url": "https://tatasky.stage.ott.irdeto.com/playready/rightsmanager.asmx?CrmId=tatasky&AccountId=tatasky&ContentId=19379_19694&SessionId=13DCDE445493A6C2&Ticket=DB63236AA01F1F78",
        "drm_scheme": "playready"
  }
```

### Bug report
Android TV
[bugreport-usw4026tat-PTT1.190228.001-2020-06-22-16-46-17.zip](https://github.com/google/ExoPlayer/files/4812896/bugreport-usw4026tat-PTT1.190228.001-2020-06-22-16-46-17.zip)

Firestick
[firestick.txt](https://github.com/google/ExoPlayer/files/4812898/firestick.txt)

### Version of ExoPlayer being used
ExoPlayer Version: 2.8.2

### Device(s) and version(s) of Android being used
This was tested on following devices which support Playready DRM

- TataSky Android TV STB
- Amazon Firestick

**Comment by ojw28** [comment]
For the Firestick, the server is returning an HTTP 500 response code, which means a generic internal server error occurred. Look in the logs for:
```
InvalidResponseCodeException: Response code: 500
```
So you should investigate why that's happening in your license server. It's possible that the problem is caused by the Firestick creating a key request that the server can't parse, but I think you need to diagnose why the server is complaining before we can investigate further, since it could also be something else, including a bug on the server side. You should also check to see whether the issue still reproduces with a recent version of ExoPlayer, since the issue might be fixed already. In particular, as per our [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md), 2.11.4 contains a specific fix for PlayReady content on Fire TV Stick Gen 2.

Please could you also try reproducing the TataSky issue with a new version of ExoPlayer? That one looks a bit like the underlying platform is just in a broken state, however.
