### ISSUE TITLE
WAKE_LOCK equivalent for mobile network

### ISSUE THREAD

**Issue by fmatosqg** [google/ExoPlayer#7537]
I maintain a live radio streaming app (https://play.google.com/store/apps/details?id=com.deepend.sen) where lots of users complain about audio dropping. I improved as far as fixing all the problems I can reproduce, but we still get lots of reports that confirm we can still do better.

I recently stumbled on #6914 and found it interesting so I don't have to deal with wakelock logic by myself, on top of it being code reviewed by people who really understand the inner parts of exoplayer. However nowhere I can figure out how to do the same thing for **network problems over mobile.** **I'd appreciate any ideas in this direction** (apart from whitelisting permissions or asking the user to do something), even if they're out of scope for this lib.

I'm emailing a set of streaming urls through dev.exoplayer@gmail.com, these are the ones that our users have access to. There's no DRM on them as far as I know, and we have a very short 30s window, which is relevant since we report on live sport matches multiple times per week.

Right now I'm on exoplayer 2.10.6, and planning to upgrade to 2.11.x.

I have logic to detect `BehindLiveWindowException`  which should be caught and restart the stream, and it works well in both controlled conditions and when I'm driving with my own phone. 

Since I can't reproduce the problem it's hard to pin down what android version and model are being used. Fair enough, the bulk of our user base is high end samsungs from the last 2, 3 years, but we have report of other Samungs and manufacturers.

**Comment by icbaker** [comment]
The javadoc for [`WifiLock`](https://developer.android.com/reference/android/net/wifi/WifiManager.WifiLock) makes it sound like you don't need a lock to keep mobile data active:
> Before using a WifiLock, consider carefully if your application requires Wi-Fi access, or could function over a mobile network, if available.

StackOverflow agrees: https://stackoverflow.com/questions/13440433/android-wifilock-how-about-mobile-data-access-lock

Thanks for the streams, but if you're unable to reproduce the problem it seems unlikely we will be able to.

The title of your issue is asking specifically about wakelock handling, but the body sounds much more open-ended: "some users are reporting audio drops".  It seems there could be many more causes of audio drops than a missing wakelock. What makes you think the audio drops would be fixed by wakelock handling?

Have you confirmed these user reports come from exclusively from users on mobile data? Could it be that the audio drops come from connection interruptions rather than the device going to sleep?

**Comment by fmatosqg** [comment]
Thx for the stack overflow link, it was what I was looking for.

here's one comment from there 
> apps affected by Doze are blocked from establishing new network connections

And thinking like an engineer, nobody said that I can keep my open connections going as long as there's battery and a cell tower nearby.

We have more than one type of problem for sure. My focus now is making sure the network is as reliable as possible, and we have enough docs for wifi but I still can't find anything official for mobile. We have info about radio not spending energy and going on some sort of low-power, WorkManager filters for kicking it off while having network etc, but no official docs saying that while in doze I can keep a mobile stream going as long as I have CPU for my threads. I'd still love reading something more recent about it, since that question is from 2012.


I understand this may not look like the right place to ask such a question, but I was open to any other solution or workaround that would make it through my end goal of not blaming network problems, be it wifi or mobile. Once I'm confident that's covered I'd start frying smaller fish.
