### ISSUE TITLE
Charles proxy question

### ISSUE THREAD

**Issue by guangmingxiong9999** [google/ExoPlayer#7538]
Hope m3u8 video use Charles proxy  can not get caught .Is there any way to solve it? thanks

**Comment by icbaker** [comment]
I'm afraid I don't really understand what you're asking.

We have an [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md) that lays out the information we need in order to best answer questions. Please copy/paste that into this issue, and fill in each headed section (and delete the explanatory text).

**Comment by guangmingxiong9999** [comment]
Now my m3u8 video can get caught use charles proxy.If have method can not get caught like ijkplayer.

**Comment by icbaker** [comment]
I'm afraid I still don't really understand the question or the problem.

It's likely you'll need to write a lot more than 2 sentences in order to provide enough information for us to help you.

Please take a look at the issue template to see the sort of information we need: https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md

**Comment by ojw28** [comment]
I think the question is whether it's possible to configure ExoPlayer so that its requests do not get intercepted by Charles Proxy. ExoPlayer doesn't know anything about Charles Proxy, and has no way of doing so, so I think the answer is no.

That said, depending on what you're trying to do, you might be asking the wrong question. It's possible that the question you should be asking is whether Charles Proxy supports a way of not intercepting traffic from ExoPlayer. If it's possible to configure Charles Proxy to not intercept traffic with a certain `User-Agent`, then that would probably work. By default ExoPlayer will put `ExoPlayerLib` as part of the `User-Agent`, so you could try and use that as the basis for a filtering rule. Else, you'll need to find some other filtering mechanism supported by Charles Proxy that's sufficient to filtering ExoPlayer requests.
