### ISSUE TITLE
Why seekTo() causes the buffered data to cleaned up?

### ISSUE THREAD

**Issue by matanmarciano** [google/ExoPlayer#7540]
Hello,
I am playing an HLS live stream.
When I try to seek (using GUI) forward (a bit) the buffered data get lost and the player changes his state to BUFFERING and I need to wait a while for re-play.

How can I overcome this issue?

**Comment by tonihei** [comment]
I can't see anything suspicious when playing an HLS live stream I have. Could you provide us with the stream and reproduction steps (in case it doesn't always reproduce)?

**Comment by fgl27** [comment]
Have you check `player.getTotalBufferedDuration()` before `seekto`? 

Because this be a live stream is expected that the amount of time buffered be small, and maybe you are seeking to a position bigger than `getTotalBufferedDuration` maybe outside live window, it also can help to understand better if there is a issue.
