### ISSUE TITLE
Set Audio Stream Type

### ISSUE THREAD

**Issue by SteveEdson** [google/ExoPlayer#755]
How do I replicate the functionality of [setAudioStreamType(int)](http://developer.android.com/reference/android/media/MediaPlayer.html#setAudioStreamType(int)) found in the standard MediaPlayer?

I have tried requesting the audio focus as the `AudioManager.STREAM_ALARM`, and although it was granted, it does not seem to be working.

Thanks.

**Comment by ojw28** [comment]
There's currently no way to do this, because we assumed that STREAM_MUSIC would be the correct choice for everyone using ExoPlayer.

Could you explain a little about the use case. Are you actually using ExoPlayer to play an alarm? We can probably add this functionality if there's a valid use case for it :).

**Comment by SteveEdson** [comment]
I'm developing an app for a radio station, one of the features is to be able to wake up to an alarm that plays the stream, therefore it seems appropriate to use the `STREAM_ALARM` mode.

As an example, see the alarm clock in the BBC iPlayer Radio app - https://play.google.com/store/apps/details?id=uk.co.bbc.android.iplayerradio

Thanks

**Comment by ojw28** [comment]
Got it, thanks! It looks like the correct way to do this would be to pass the stream type through the MediaCodecAudioTrackRenderer constructor, into (ExoPlayer's) AudioTrack constructor, and then use the passed value in the three places in AudioTrack where we currently use the STREAM_MUSIC constant. So in your application, you'll specify the type when you build the renderer.

Does that sound reasonable for what you need to do? Thanks!

**Comment by SteveEdson** [comment]
Yeah that sounds ideal, cheers!

**Comment by bbincybbaby** [comment]
@ojw28 can u explain it using code ?

**Comment by andrewlewis** [comment]
@bbincybbaby Since ae0ac55 we support re-setting the stream type at any time. If you're using SimpleExoPlayer, call [SimpleExoPlayer.setAudioStreamType](https://github.com/google/ExoPlayer/blob/270f68a/library/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L300) passing in the `C.STREAM_TYPE_*` constant you want to use.
