### ISSUE TITLE
Rename the language in ExoPlayer to be inclusive

### ISSUE THREAD

**Issue by faith-murphy** [google/ExoPlayer#7565]
### [REQUIRED] Use case description
The language in the ExoPlayer code and documentation is non-inclusive. This is a request to update the code and comments to reflect the guidelines Google has laid out for writing inclusive documentation (https://developers.google.com/style/inclusive-documentation)

### Proposed solution
Rename the non-inclusive language in the ExoPlayer to be inclusive. For example, the method #getBlacklistDurationMsFor() in LoadErrorHandlingPolicy

### Alternatives considered
None

**Comment by kim-vde** [comment]
Thanks for reporting this issue! We will start working on this in the near future.

**Comment by kim-vde** [comment]
We plan to rename the occurrences of non-inclusive words gradually, starting with the comments and private fields. We will then proceed to renaming the public API (which needs more care, so it might come a bit later).

Note that we are not planning to rename the words that reference directly the terminology of the specifications that we are implementing.

**Comment by ojw28** [comment]
I believe we've cleaned up the vast majority of non-inclusive language, and have also incorporated a check into our code pre-submit to make sure we don't introduce any more. In the few cases where non-inclusive language remains, it's most likely because it would have been very disruptive to correct it.
