### ISSUE TITLE
Correct implementation of Exoplayer to play audio from InputStream

### ISSUE THREAD

**Issue by kmrinmoy07** [google/ExoPlayer#7566]
### [REQUIRED] Searched documentation and issues
I have searched the answer in the whole internet as I could but not getting any proper solution. I also saw the issues and I found one issue in which this is asked but I could follow it correctly to make my project work. It would be very good if you include in your docs.

### [REQUIRED] Question
I have some encrypted audio files downloaded and while playing its content by decrypting and passing its content as byte array works perfectly but during this process I am getting some OOM error at low RAM devices. So I want to pass the CipherInputStream directly to Exoplayer and after many tries now I am able to play the audio but still now I am unable to handle the proper skipping/forwarding of audio. So I need some help in this regards.
I have posted my code below
         
          public class CustomDataSource implements DataSource {

              private String fileName;
              private long bytesRemaining;
              private long nextReadPos;
              private InputStream inputStream;

             public CustomDataSource(Context context,String fileName) {
                     this.fileName = fileName;
                    nextReadPos = 0;
                     try {
                            SecretKeySpec sks = new SecretKeySpec(context.getResources().getString(R.string.encryptPassword).getBytes(),
                "AES");
                           Cipher cipher = Cipher.getInstance("AES");
                           cipher.init(Cipher.DECRYPT_MODE, sks);
                           FileInputStream fileInputStream = new FileInputStream(fileName);
                           inputStream = new CipherInputStream(fileInputStream, cipher);
                      } catch (Exception e) {
                          e.printStackTrace();
                   }
                }

             @Override
              public long open(DataSpec dataSpec) throws IOException {
                    try {
                         long totalFileSize;
                         RandomAccessFile file2 = new RandomAccessFile(fileName, "r");
                         totalFileSize = file2.length();
                         nextReadPos = dataSpec.position;
                         bytesRemaining = dataSpec.length == C.LENGTH_UNSET ? totalFileSize - dataSpec.position
                : dataSpec.length;
                        if (bytesRemaining < 0) {
                                  throw new EOFException();
                           }
                      } catch (IOException e) {
                         throw new FileDataSource.FileDataSourceException(e);
                     }

                   return bytesRemaining;
                  }

                @Override
                public int read(byte[] buffer, int offset, int readLength) throws IOException {
                       if (bytesRemaining == 0) {
                          return -1;
                       } else {
                           int bytesRead = 0;
                            try {
                              bytesRead = inputStream.read(buffer, offset, (int) Math.min(bytesRemaining, readLength));
                             nextReadPos += bytesRead;
                           } catch (IOException e) {
                             throw new FileDataSource.FileDataSourceException(e);
                          }
                               return bytesRead;
                        }
                   }

                  @Override
                  @Nullable
                  public Uri getUri() {
                        return Uri.fromFile(Environment.getExternalStorageDirectory());
                  }
                 
               }

              //Initialising exoplayer 
                 exoPlayer = ExoPlayerFactory.newSimpleInstance((MainActivity) context);
                 exoPlayer.addListener(listener);
                exoPlayer.setAudioAttributes(audioAttributes,true);

               DataSpec dataSpec = new DataSpec(null);
                final CustomDataSource inputStreamDataSource =  new CustomDataSource(getApplicationContext(), filePath);
                try {
                    inputStreamDataSource.open(dataSpec);
                } catch (IOException e) {
                    e.printStackTrace();
                }

                DataSource.Factory  dataSourceFactory = new DataSource.Factory() {
                    @Override
                    public DataSource createDataSource() {
                        return inputStreamDataSource;
                    }
                };

              audioSource = new ProgressiveMediaSource.Factory(factory)
                            .createMediaSource(inputStreamDataSource.getUri());
             exoPlayer.prepare(audioSource);
            exoPlayer.setPlayWhenReady(true);

**Comment by kim-vde** [comment]
Have you tried to use an [AesCipherDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.html)?

**Comment by kmrinmoy07** [comment]
No, I have not tried it till now. Let me check it if I can implement it correctly. If you have any sample code I would request you to post it as it would ḥelp me a lot

**Comment by kmrinmoy07** [comment]
I have implemented this [class](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.java) in my project but I am unable to prepare the MediaSource for Exoplayer. Could you please help a little bit

**Comment by kim-vde** [comment]
Could you send the logs that you get?

**Comment by kmrinmoy07** [comment]
Thanks for the comment, after few trials finally I am able to successfully implemented the `AesCipherDataSource` but I had to change my `encrypt` method too. The default [AesCipherDataSource](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.java) was only able to decrypt files which were encrypted using this [method](https://github.com/google/ExoPlayer/issues/5083#issuecomment-437976602) using `AesCipherDataSink`. But it could be better if my previous encrypt method could also be used, as already most of app user had saved files using my previous encrypt method. I have also pasted the old encrypt method which I have used

              private static void encrypt(Context context) {
               try {
                    InputStream fis = new ByteArrayInputStream(audio);
                    FileOutputStream fos = new FileOutputStream(file);
                    SecretKeySpec sks = new SecretKeySpec(context.getResources().getString(R.string.encryptPassword).getBytes(),
                    "AES");
                     // Create cipher
                    Cipher cipher = Cipher.getInstance("AES");
                    cipher.init(Cipher.ENCRYPT_MODE, sks);
                    // Wrap the output stream
                    CipherOutputStream cos = new CipherOutputStream(fos, cipher);
                    // Write bytes
                    int b;
                    byte[] d = new byte[1024];
                    while ((b = fis.read(d)) != -1) {
                       cos.write(d, 0, b);
                    }
                    cos.flush();
                    cos.close();
                    fis.close();
                  } catch (Exception e) {
                     e.printStackTrace();
                  }
               }

**Comment by kim-vde** [comment]
Then I think you need to implement your own DataSource by extending the AesCipherDataSource.

**Comment by kmrinmoy07** [comment]
Yes, I have already tried it. I did as done in this [comment#5083](https://github.com/google/ExoPlayer/issues/5083#issuecomment-437901562) but there is a issue in it. 

> When I use the custom AesDataSource and I seek beyond the already buffered part, it throws ParserException: Searched too many bytes inisde Mp3Extractor.

**Comment by kim-vde** [comment]
Ok. This error means that the Mp3Extractor can't find the Mp3Frames. This is probably due to an error in the decryption process. 

Do you get the same error when you are using the `AesCipherDataSource` together with the `AesCipherDataSink`?

I would try to debug to see what happens when you seek forward to a non-buffered position and to compare the bytes decrypted with the ones of the unencrypted file to see if they match.

**Comment by kmrinmoy07** [comment]
> Do you get the same error when you are using the AesCipherDataSource together with the AesCipherDataSink

**No**, with `AesCipherDataSink` there is no such error. Only with our own encrypt method the above said problem seems to occur

**Comment by kim-vde** [comment]
Then my guess would be that the decryption is not the exact opposite of the encryption, and therefore that the resulting MP3 file is corrupted.

**Comment by kmrinmoy07** [comment]
If I use my own encryption method as given [above](https://github.com/google/ExoPlayer/issues/7566#issuecomment-652876183) and implement the default `AesCipherDataSource` then yes it is correct that the decryption is not the exact opposite of the encryption. Alternatively, if I use a custom `AesCipherDataSource` with our own `AesFlushingCipher` mechanism then the above [problem](https://github.com/google/ExoPlayer/issues/7566#issuecomment-652930116) is seen. So the only way that I am successfully able to implement is to use a new encrypt method with `AesCipherDataSink`. But the problem in this is that my android app is already live & many users had already downloaded lots of encrypted files which would be now useless. Is there anyway that I can solve the problem 

> When I use the custom AesDataSource and I seek beyond the already buffered part, it throws ParserException: Searched too many bytes inisde Mp3Extractor.

Then may be I can use my previous encrypt method and those previously downloaded encrypted files could still be used

**Comment by kim-vde** [comment]
> Alternatively, if I use a custom `AesCipherDataSource` with our own `AesFlushingCipher` mechanism then the above [problem](https://github.com/google/ExoPlayer/issues/7566#issuecomment-652930116) is seen.

I think this is probably the best way to solve your problem if you cannot use another encryption method. What I was saying is that there is probably something wrong in the custom `AesCipherDataSource` you implemented, because it should work.
How do you configure your decoding cipher?

**Comment by ojw28** [comment]
To add some more detail to this thread:

When implementing encryption/decryption for media, it's quite important to use a cipher that supports random access. Otherwise, when the player needs to seek to the middle of the file, it's necessary to decrypt from the start of the file up to the point at which data is needed, which is obviously quite inefficient. ExoPlayer's built in components use `AES/CTR/NoPadding` specifically because it has these properties, and in addition because partial blocks can be self-padded and decrypted successfully. Any kind of cipher mode that uses chaining from one block to the next does not have these properties, and to implement `DataSource.open` to any non-zero position would require you to open, decrypt and discard the underlying data up to the requested position. Even for ciphers that do support chaining but cannot be self-padded, you'd need to implement `DataSource.open` to open, decrypt and discard from the previous block boundary up to the requested position. This could all be summarised as, "it's quite complicated to get right" :).

Your implementation may need to implement some of the logic described above, depending on what you get when you ask for just "AES". In addition there are at least three bugs in the code at the top:

1. `nextReadPos` isn't used anywhere, so it's basically completely ignoring the read position requested in the `DataSpec` that's passed to `open`.
1. Application code should not be calling `open` on the `DataSource` directly.
1. `createDataSource` should be creating a new instance of your `DataSource`, not repeatedly returning the same one.

If you implement the `DataSource` correctly for the encryption/decryption scheme you're using, then playback will work properly. Since you're using a custom scheme, this is kinda beyond the scope of this issue tracker, although the information provided above may help!

If the scheme you're using isn't suitable for media in general then your best bet may be to implement an upgrade step that decrypts the existing files and rewrites them to use `AES/CTR/NoPadding`, at which point you'd be able to use ExoPlayer's standard components going forward.
