### ISSUE TITLE
Avoid the final modifier all together

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#757]
As you saw in my previous PR (that was accepted, thanks!) I had issues with final methods that I needed to override. While bumping ExoPlayer in our project I'm now experiencing more issues with added final modifiers. For instance, a test broke since we couldn't mock a certain class which had final methods. Therefore, again, unless there's a very good reason, I suggest removing any final modifiers to make it easier for consumers of the SDK to test their applications. I was able to solve my specific issue by a rather ugly workaround, so this is more of a general suggestion.

**Comment by ojw28** [comment]
It's a tricky one. From a developer's point of view and given a single version of the library, it's easiest for the developer if they can arbitrarily extend whatever they want as you suggest. In practice however, what we've seen both within Google's own app teams and externally, is that developers will extend and override things that were never intended to be extended or overridden, and use this ability to implement all kinds of strange things that we didn't intend to support in the way they're implementing them. This is problematic for a few reasons, including:

- It tends to make upgrading to a newer version of the library more painful; because if we don't intend for something to be extended and overridden then we're less likely to guarantee that it's still there and working in the same way from one version to the next, or even that it will still be possible to achieve the same functionality by extension as you were able to achieve in an earlier version. We don't guarantee API stability between versions anyway, but these extension points are effectively parts of API that we haven't even thought about, so they're much more likely to change.

- It encourages developers to implement features in their own code using extension, where often those features could and should be implemented more cleanly and in a more maintainable way within the library.

It's important to note that final could mean either "we don't think it makes sense to extend this" or (more likely) "we haven't thought about whether it makes sense to extend this, and no-one has needed to yet". We're happy to remove final modifiers on a case by case basis where there are valid reasons and if it looks sensible to do so, but I think that defaulting to final is the right thing to do. It forces us to actively think about whether each extension point is sensible, as well as whether or not we'd rather achieve what the app developer is trying to do directly in the library. It also forces app developer to think about whether there's a more suitable approach. A few things I've observed internally are:

- Developers tend to overuse extension, where composition would be a much better choice.

- Developers tend to mock things that really don't need mocking (e.g. immutable classes where it's trivial just to construct a real instance of the real class).
