### ISSUE TITLE
High speed PlaybackParameters make sequence of short videos get stuck sometime

### ISSUE THREAD

**Issue by dmkenza** [google/ExoPlayer#7571]
# Issue description

I play sequence  of videos with high speed and sometime render just stopped, but play work I'm getting STATE_ENDED

I see stuck sometime when speed =  2 

When speed >  3  I see only first video without changed.

For speed < 1 play normal without a freeze.
 

### Reproduction steps

I create small videos with ffmpeg from images (each 1s)
using this command 
"-y -loop 1 -f image2 -i  $imgPath -vf format=yuv420p,scale=trunc(iw/2)*2:trunc(ih/2)*2  -t 1 $pathVideo"

I have 20 minivideos.
I create OpenGl Render with surface.

Surface I use in Exoplayer
``player.setVideoSurface(surface)``

When I create one ConcatenatingMediaSource and
ProgressiveMediaSource for each video

   `` val source: MediaSource = ProgressiveMediaSource.Factory(FileDataSource.Factory()).createMediaSource(Uri.parse(path))``

 ``concatenatingMediaSource.addMediaSource(source)``

In end

``player.setPlaybackParameters( PlaybackParameters(speed ,1f , true) )``

``player.prepare(concatenatingMediaSource , true, false)``

###  A full bug report captured from the device
In log Warnings  I see only

``ExtendedACodec: Failed to get extension for extradata parameter``

###  Version of ExoPlayer being used
exoplayer:2.11.7

### Device(s) and version(s) of Android being used
Xiaomi Mi 9 Lite Android 9

**Comment by kim-vde** [comment]
Can you explain what you mean when you said the video is getting stuck? Does the playback resume after some time?

Can you send a few of your small videos so that we can try to reproduce the problem? If you're unable to share test contents publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by dmkenza** [comment]
It wasn't problem of exoplayer.

I had similar problem like in this
https://stackoverflow.com/questions/14185661/surfacetexture-onframeavailablelistener-stops-being-called
