### ISSUE TITLE
VMAP ads tag with custom cue points

### ISSUE THREAD

**Issue by JoshuaChewStar** [google/ExoPlayer#7572]
I have 3 VMAP ads tag and all 3 has a "Preroll" value in it, I have to load these 3 ads into a video and treat them each as a preroll, midroll and postroll.

I tried to follow this example but turns out I can only use mp3/mp4 or other video format as the Uri instead of adTag
[stackoverflow](https://stackoverflow.com/questions/49871348/how-to-show-ads-at-specific-points-using-exoplayers-ima-extension)

I cannot modify the VMAP ads tag because it is out of my control.

Is there any way that I can load the 3 VAMP ads tag and manually inserting them to different cue points?
Please do advice what approach can I implement.

I'm using v2.11.7 and already included extension-ima

Thank you!

**Comment by andrewlewis** [comment]
Can you download all the ad tags at the start and generate a new VMAP based on them yourself, then pass that to `ImaAdsLoader.Builder.buildForAdsResponse`? I think that might be the best way to do this (my only concern is that you need to request all those ads at the start, rather than requesting them just before playback reaches the cue points, but I'm not sure if that will be an issue for your use case).

**Comment by JoshuaChewStar** [comment]
Hmm, sure I can try this out first, will let you know how's the outcome. Thanks!
