### ISSUE TITLE
When is sound actually heard/outputted?

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#7577]
### [REQUIRED] Searched documentation and issues
- Github, Stack Overflow, exoplayer.dev, ExoPlayer Javadoc
- https://exoplayer.dev/listening-to-player-events.html#player-state-changes

### [REQUIRED] Question
I did some testing in the sample app, to figure out when sound was actually heard/outputted. It seems to me that `onPlayerStateChanged()` with `STATE_READY` and/or `isPlaying()` callbacks are received before sound can actually be heard. This is especially noticeable when we increase the `AudioTrack` buffer, where the aforementioned callbacks can be received up to 500 ms before actual sound can be heard(depending on the buffer size). While this is easiest seen with a bigger buffer, it is also happening with the default settings, making our metrics for startup time incorrect.

My experience is that sound is actually heard when the `AudioTrack` fills up its buffer(for the first time).
Is my assumption correct?
If so, does it make sense to create some kind of callback `isSoundOutputted()` to better give us the true startup time of an asset?

Note: If this is true, then the information in https://exoplayer.dev/listening-to-player-events.html#player-state-changes is ambiguous, depending on what "immediately play" means in this context: "Player.STATE_READY: The player is able to immediately play from its current position."

### A full bug report captured from the device
N/A

### Link to test content
Play whatever content you want.

**Comment by tonihei** [comment]
I think your assumptions about what is happening are correct - @andrewlewis may be able to verify in more detail.

It's a known issue that the playback time (as dictated by the actual `AudioTrack` play position) isn't starting to move until shortly after the player state becomes `STATE_READY`. Unfortunately, there doesn't seem to be a way to know exactly when the `AudioTrack` starts outputting sound and `STATE_READY` only means that the audio renderer is ready to play (i.e. we can call `AudioTrack.play` and have enough buffer to expect playback to start). 

There is one way you can determine the actual start position of playback, but it can be only be determined after playback already started. If you wait for short duration after `isPlaying()` becomes true (e.g. 1000ms), you can check the current player position (`Player.getCurrentPosition`, e.g. 800ms) and the subtract it from the current time to know when the audio track actually started playing. In my example, this would be 200ms after `isPlaying()` became true. This is correct within a few milliseconds, as you can verify by repeatedly using this method. Values we've seen are usually in the range of 100ms. Note that you need to take into account the playback speed, if applicable.

> making our metrics for startup time incorrect

They are (by this definition) not correct in absolute terms, but note that the part you are not measuring is also not within your or our control and will have the same additional offset in all cases. if you are worried about measuring improvements and seeing trends, then `isPlaying()` should still provide a good value because it captures all the parts you can control.

**Comment by tonihei** [comment]
Closing because the question was answered above. Feel free to reopen if not.
