### ISSUE TITLE
How to exclude a decoder?

### ISSUE THREAD

**Issue by parth-paghadal** [google/ExoPlayer#7578]
How can i set sw and hw decoder feature in my exoplayer app?

**Comment by kim-vde** [comment]
Could you please provide more details about what you are trying to do? The [MediaCodec documentation](https://developer.android.com/reference/android/media/MediaCodec) might be relevant.

**Comment by parth-paghadal** [comment]
4k video is laging

**Comment by parth-paghadal** [comment]
4K video is play with leg that's why i want to set hardware decoder so i think it can solve my problem.is it?

Here is my **MediaSorce**
val dataSourceFactory = DefaultDataSourceFactory(this,userAgent,bandwithMeter)
            val progressiveMediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(currentMedia?.path?.toUri())
            return MergingMediaSource(progressiveMediaSource)

and here is initlization of **SimpleExoPlayer**
val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory()
trackSelector = DefaultTrackSelector(this,videoTrackSelectionFactory)
val defaultRenderersFactory = DefaultRenderersFactory(this)        defaultRenderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)
simplePlayer 
 = SimpleExoPlayer.Builder(this,defaultRenderersFactory,trackSelector,DefaultLoadControl(),bandwithMeter,Handler().looper,
            AnalyticsCollector(Clock.DEFAULT),true,
            Clock.DEFAULT
        ).build()
playerView.player = simplePlayer
simplePlayer.playWhenReady = true
simplePlayer.prepare(mediaSource)

i try [this video ](https://pixabay.com/videos/download/video-34091_source.mp4)  first i download in locale storage and than i tried to play it.

Try on Lenovo Vibe K5 Note with Android Marshmellow

**Comment by kim-vde** [comment]
> defaultRenderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)

This will prefer the extension renderers, which use software decoders. What happens if you use `EXTENSION_RENDERER_MODE_OFF` instead? This is the default value so you do not need to call `defaultRenderersFactory.setExtensionRendererMode()`.

What is the format of your media?

**Comment by parth-paghadal** [comment]
Thanks for your reply but after setting EXTENSION_RENDERER_MODE_OFF there no change 

**Format of video is** Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 23.975218], [-1, -1]) and 
moreover i got error from simpleExoPlayer
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 23.975218], [-1, -1])

**Comment by fgl27** [comment]
I don't know about the `DecoderInitializationException` but...

I had some related issue and it only solved when I used a custom `MediaCodecSelector` 
https://github.com/fgl27/SmartTwitchTV/blob/master/apk/app/src/main/java/com/fgl27/twitch/BlackListMediaCodecSelector.java

how to use
https://github.com/fgl27/SmartTwitchTV/blob/master/apk/app/src/main/java/com/fgl27/twitch/PlayerActivity.java#L399
`BLACKLISTEDCODECS` is a String array that contains the unwanted codecs.

you can list all codecs from a device using `MediaCodecList` for example for a particularly type `avc`

```java
    public static ArrayList<String> GetCodecsType(String CodecType) {
        ArrayList<String> result = new ArrayList<>();

        for (MediaCodecInfo codec : new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos()) {
            if (!codec.isEncoder()) {
                for (String type : codec.getSupportedTypes()) {
                    if (type.contains(CodecType)) {
                        result.add(codec.getName());
                    }
                }
            }

        }
        return result;
    }
```

Now you have all codecs names, filter unwanted and pass to `BlackListMediaCodecSelector`.

**Comment by kim-vde** [comment]
I tried to play the video on a Google Pixel device and on a Samsung device and it works for both. It might be a device-specific issue.

Could you try playing the test content on your device using the ExoPlayer [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main)?

**Comment by kim-vde** [comment]
I think this could be the same problem as in #6503.

Can you:
- Provide us the Build.DEVICE value for your device.
- Provide us the Build.MODEL value for your device.
- Try adding your device to [codecNeedsSetOutputSurfaceWorkaround()](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1557) to see if it fixes the issue?

If it does, I can add the fix to the code so that the issue is permanently fixed.

**Comment by fgl27** [comment]
On my case the reason SW decoder needed to be blocked is because some device have confusing decoder information.

For example I try to play a AVC his stream that is encoded with profile level 5.2, device SW decoder advertises max level 5.2 but HW only 5.1, on that case ExoPlayer uses the SW because it has the proper level and the video lags, when I force disable the SW decoder no lag, as the HW is very capable to play the content.

That happens to a Xiaomi mi box for example and other device that use `OMX.google.h264.decoder`, that is why by default I just block AVC SW decoder on ExoPlayer.

![device_avc_decoders](https://user-images.githubusercontent.com/13755892/82634787-1328c600-9bd5-11ea-95fb-04ad3370b3b9.png)

Is that a issue that can be prevented without that `MediaCodecSelector` workaround?

**Comment by kim-vde** [comment]
If you want to exclude a codec, then I think using a `MediaCodecSelector` is the way to go. You can pass it using [`DefaultRenderersFactory.setMediaCodecSelector()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html#setMediaCodecSelector-com.google.android.exoplayer2.mediacodec.MediaCodecSelector-) and then pass the `RenderersFactory` to the [`SimpleExoPlayer` builder](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.Builder.html#Builder-android.content.Context-com.google.android.exoplayer2.RenderersFactory-).

Note that, even though it is true that, on some devices, decoders capabilities are underreported, it is risky to ignore them because it may be that although a certain stream with a particular profile/level is supported, another one at the same profile/level may not be supported.

Note also that the error you are getting with the OMX.MTK.VIDEO.DECODER.AVC decoder means that ExoPlayer is trying to use this hardware-accelerated decoder but that it doesn't support the format. This error could also be linked to the problem I mentioned in [this comment](https://github.com/google/ExoPlayer/issues/7578#issuecomment-653589433).
