### ISSUE TITLE
Audio fails using EXTENSION_RENDERER_MODE_PREFER when ffmpeg library doesn't support the codec.

### ISSUE THREAD

**Issue by neuro79** [google/ExoPlayer#7583]
### [REQUIRED] Issue description

Application running Exoplayer 2.11.7 with multiple audio renders (ffmpeg extension and default device renderer) and the option extension render mode = EXTENSION_RENDERER_MODE_PREFER. FFMPEG extension has been compiled using only opus, orbis and flac. When Exoplayer tries to reproduce a source using AAC codec the audio track selection fails and we don't have audio in the playback.

Adding AAC codec to ffmpeg compilation process the audio is reproduced properly
Changing option to EXTENSION_RENDERER_MODE_OFF or EXTENSION_RENDERER_MODE_ON audio is reproduced properly (hardware supports AAC)

Inside RendererCapabilities we can see ffmpegAudioRender in the index 1 and then MediaCodecAudioRenderer in index 2.

The findRenderer process (MappingTrackSelector) calls supportsFormatInternal from FfmpegAudioRenderer and returns FORMAT_UNSUPPORTED_SUBTYPE, findRenderer then check the next Renderer and detect that bestRenderIndex is number 2. So this is working as expected. But then we are able to see and error reporting mime type audio/ffmpeg is not supported and playback begins with video but no audio.

- We has been able to reproduce in older version 2.10.2 too.

### [REQUIRED] Reproduction steps
- Enable ffmpeg extension.
- Compile ffmpeg extension using a limited list of codecs (i.e: opus, orbis and flac)
- Use setExtensionRendereMode = EXTENSION_RENDERER_MODE_PREFER
- Play content using AAC audio codec.

### [REQUIRED] Link to test content
Provided by email.

### [REQUIRED] A full bug report captured from the device
Provided by email.

### [REQUIRED] Version of ExoPlayer being used
2.11.7 and 2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
Issue is reproduced 100% of times.
Device running SDK 23. 6.0.1
armeabi-v7a

**Comment by ojw28** [comment]
This works fine for me in the demo app with 2.11.7. Playback plays with sound, using the `MediaCodec` based audio renderer.

> error reporting mime type audio/ffmpeg is not supported

This warning isn't related to the problem you're seeing, and can be safely ignored.

Is this issue device specific?  Either way, please try reproducing the problem with the 2.11.7 ExoPlayer Demo app, because it logs additional information that's useful for debugging. Please capture a bug report taken just after experiencing the failure. Thanks!

**Comment by neuro79** [comment]
We  have tested the Exoplayer Demo app in the device and as you said it is working properly. We have been debugging our application to try to understand what is making the audio fail in our case and we found that the reason is the way we are managing the Subtitle enable/disable process.

We are using this code to disable subtitles:

           trackSelector.setParameters(trackSelector.buildUponParameters()
                    .setRendererDisabled(C.TRACK_TYPE_VIDEO, true)
                    .setRendererDisabled(C.TRACK_TYPE_TEXT, true)
                    .build()
            );

We was using C.TRACK_TYPE_VIDEO and C.TRACK_TYPE_TEXT because we though that the value of this parameter was being used to find the renderer of this type and then disabled them but looks like the value is applied directly over the redenderIndex. 

We did a modification in our code to find the TEXT render indexes and apply the flag only in the render of type C.TRACK_TYPE_TEXT and now audio is working properly. 

Is this the recommended way to modify track selector to disable all the renderers of  C.TRACK_TYPE_TEXT?

**Comment by ojw28** [comment]
Yes, you need to pass renderer indices rather than `C.TRACK_TYPE_X` constants to `setRendererDisabled`.

I assume that to find the renderer indices, you're iterating over the renderer indices and using `Player.getRendererType(i)` or `MappedTrackInfo.getRendererType(i)` to determine whether the renderer at index `i` is a type that should be disabled. If so then yes, you're doing the right thing.
