### ISSUE TITLE
AC3 content in MPEG-PS does not play properly

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7589]
Hello, I am expanding the mpeg-1 ps file, and the playback of audio and video is normal, but the audio data parsed by the existing mpeg-2 ps is almost a buzzing sound, and the trouble will be resolved as soon as possible. Thank you

**Comment by kuailedeadai** [comment]
The audio encoding format is ac-3

**Comment by kim-vde** [comment]
Hi,

Could you please explain in more details what the issue is:
- What do you mean by "mpeg-1 ps" and "mpeg-2 ps"? Are they media in the PS container format containing MP1 and MP2 elementary streams?
- What do you mean by "expanding the mpeg-1 ps"?
- Could you send a test content that has the buzzing sound? If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by kuailedeadai** [comment]
Hello, I'm talking about the audio and video files of the PS container. MPEG1 PS and mepg2 PS are two different PS formats. At present, exoplayer only supports mepg2 PS. I have developed the MPEG 1 ps format. However, when testing the. Mpg file, I found the audio buzzing sound. Check the log. The file format belongs to mepg2 PS, and the audio encoding format belongs to AC-3. Here are the audio buzzing files: The document has been sent to your email, thank you

**Comment by kuailedeadai** [comment]
Hello, have you received the email I sent you about the buzzing sound of mpeg-2 ps audio? Hope you can solve this problem as soon as possible, thank you

**Comment by kim-vde** [comment]
Yes I received it. I will have a look.

**Comment by kim-vde** [comment]
I haven't had the time to look into the issue in details. This is probably going to take a few days or weeks.

If this is urgent, feel free to debug the code and submit a pull request.

**Comment by kuailedeadai** [comment]
I have solved this problem. For dvd files, audio has a special header (4 bytes). For details, please refer to: http://stnsoft.com/DVD/ass-hdr.html
