### ISSUE TITLE
Can I play stream In a unit test?

### ISSUE THREAD

**Issue by matanmarciano** [google/ExoPlayer#7619]
Hello,
After some research about using Exoplayer in a unit test, I found ExoPlayerTestRunner class.
But I'm not sure if this is actually what I need.

I need to run the exoplayer (in a unit test) and register as analytics listener to get notifications and pass/fail the unit test according to the notifications.

**Comment by tonihei** [comment]
We recently improved our support for using ExoPlayer in Robolectric based unit tests. This replaces the `ExoPlayerTestRunner`, but will only be released in 2.12 (within the next few weeks).

You will then be able to do something like this:
```
ExoPlayer player = new TestExoPlayer.Builder(context) /* setMoreCustomPlayerElementsHere */. build();
player.addAnalyticsListener(...);
// You could also use your real MediaSource here and read test media from assets.
player.setMediaSource(new FakeMediaSource(new FakeTimeline(/* windowCount= */ 1)));
player.prepare();
player.play();
.. and so on....

// There are other similar methods to wait for certain things to happen.
TestExoPlayer.runUntilPlaybackState(player, Player.STATE_READY);
assertThat(player.getState()).isEqualTo(Player.STATE_READY);
```

**Comment by matanmarciano** [comment]
OK so until 2.12 release my use case is no possible?

**Comment by tonihei** [comment]
You should be able to do something similar with the current `ExoPlayerTestRunner`, by using an `ActionSchedule` to control when certain things happen. The logic is less straight-forward and you can't access the `Player` itself to use it as part of your code. That's why we replaced it. Depending on your exact use case you may still be able to use it though. If you want to see some example for how we used it in unit tests, have a look at [`ExoPlayerTest`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/test/java/com/google/android/exoplayer2/ExoPlayerTest.java).

**Comment by matanmarciano** [comment]
I already looked at `ExoPlayerTest` and the `ExoPlayerTestRunner ` & `ActionSchedule ` not seems that fit to my use case.
am I wrong?

I want to run some stream and get notifications: `onBandwidthEstimate`, `onDownstreamFormatChanged` but not sintetic trigger's. In want real playing and real exo implementation.

**Comment by tonihei** [comment]
If you want a real playback including `onBandwidthEstimate`, I assume you also want to download media over network? In this case you should just use ExoPlayer as it is in the test (without any test runners or fake components).

**Comment by matanmarciano** [comment]
Yes, it is exactly what I want. to run SimpleExoPlayer instance in a unit test and pass/fail the unit test by my internal logic,  based `onBandwidthEstimate` value's. But how it is possible? I have tried it and the player not start playing..no errors or something.

**Comment by tonihei** [comment]
Using the real ExoPlayer from a unit test is no different from using it in an Activity. The only problem is that you need to block test execution until your test condition is fulfilled. For example, you can use `InstrumentationRegistry.getInstrumentation().runOnMainSync` to run your player related code on the main thread and then wait on the test thread until some condition becomes true.

**Comment by matanmarciano** [comment]
I have to run the unit test under Android device right? or it is possible to run Exoplayer in a Junit?

**Comment by tonihei** [comment]
Android tests are also using Junit, but I assume you mean running tests without an actual device using Robolectric? Both are possible, but if you intend to access network data in the test you likely need to run it on an actual device (or an emulator) because Robolectric tests are hermetic and can't access anything outside of the test jar itself. If you want to use Robolectric, please refer to the `ExoPlayerTestRunner` / `TestExoPlayer` explanations above.

**Comment by matanmarciano** [comment]
OK it works, many thanks!

**Comment by tonihei** [comment]
Closing because the question was answered above. Feel free to reopen if not.
