### ISSUE TITLE
I want to show the total time of all videos in the playlist playing on PlayerView

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7633]
I want to show the total time of all videos in the playlist playing on PlayerView,
Each my videos will be synchronized with the total duration of the playlist, i cannot find some how to do it on the internet, maybe it is not support my problem, Please help me!

**Comment by marcbaechinger** [comment]
You can go through all the windows of the [Timeline](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.html) and sum up all durations of these windows. This would give you the total duration which you then can display in the UI. You would have to customize the UI for that though I think.

There is a challenge with this approach. If you want to know the actual duration of a stream, you need to have the stream prepared. Before preparation the window.duration gives you C.TIME_UNSET. So you have to opt-out of lazy preparation. With lazy preparation, the media sources are only prepared just shortly before they are actually played. So you have to use the lazyPreparation flag to false (either when you build the player or when you use a `ConcatenatingMediaSource` pass lazyPreparation=false to the constructor of the source). This implies that the player immediately starts downloading data for all streams in the playlist. That's actually something you want to avoid, specifically if the number of videos in the playlist is large. It will create a burst of network requests at the very begin.

Can you shed some more light on what you are trying to achieve? I guess you would not only want to have the total duration of the playlist, but the UI should also show for instance the position within that total duration, which seems tricky to do. How do you imagine does the timebar with the scrubber behave? Do you just hide the timebar, so that the user can not seek?

**Comment by andrewlewis** [comment]
Just a quick addition to what Marc said: `PlayerView.setShowMultiWindowTimeBar` may help with what you are trying to do, but see also #4727 which relates to the problem of lazy preparation with progressive media.
