### ISSUE TITLE
Restore AdsMediaSource$MediaSourceFactory on 2.11

### ISSUE THREAD

**Issue by fmatosqg** [google/ExoPlayer#7638]
When removing `AdsMediaSource$MediaSourceFactory` class on version 2.11 it causes other developers's code to not be when written for exoplayer 2.9 and 2.10. This is specially problematic with flutter plugins that include different versions of exoplayer. 

This was the original error, which was not in a project I have access to.
```
E/flutter (25192): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/ads/AdsMediaSource$MediaSourceFactory;
```

Gradle dependency tree for the flutter project, where `video_player` refers to the following library (also called flutter plugin) https://pub.dev/packages/video_player :
```
+--- project :video_player
|    +--- io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7 (*)
|    +--- com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)
|    +--- com.google.android.exoplayer:exoplayer-hls:2.9.6
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    +--- com.google.android.exoplayer:exoplayer-dash:2.9.6
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    +--- com.google.android.exoplayer:exoplayer-smoothstreaming:2.9.6
|    |    +--- com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
```

Gradle dependency try for same project, but showing the part for another flutter library / plugin https://pub.dev/packages/media_info:

```
+--- project :media_info
|    +--- io.flutter:flutter_embedding_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7 (*)
|    +--- com.github.bumptech.glide:glide:4.10.0
|    |    +--- com.github.bumptech.glide:gifdecoder:4.10.0
|    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    +--- com.github.bumptech.glide:disklrucache:4.10.0
|    |    +--- com.github.bumptech.glide:annotations:4.10.0
|    |    +--- androidx.fragment:fragment:1.0.0 -> 1.1.0 (*)
|    |    \--- androidx.vectordrawable:vectordrawable-animated:1.0.0 -> 1.1.0 (*)
|    +--- com.google.android.exoplayer:exoplayer-core:2.11.5
|    |    \--- androidx.annotation:annotation:1.1.0
|    \--- net.sourceforge.streamsupport:android-retrofuture:1.7.2
|         \--- net.sourceforge.streamsupport:android-retrostreams:1.7.2
```

More details at 
https://stackoverflow.com/questions/62880525/flutter-app-crashes-when-video-player-loads-hls-video/62885914#62885914

I'd like to ask to reinstate class `AdsMediaSource$MediaSourceFactory` with a deprecated annotation, and inheriting from MediaSourceFactory so code writtten for 2.10 is totally "source code compatible" with exoplayer 2.11. 

There are a few factors that make this problem worse:
- it manifests as a crash at run time, not at compile time, only when trying to play a video
- since it's related to IMA, not sure if it would happen with any videos or only ones with some kind of IMA pre-roll or in the middle of the video
- it's coming from a mix of 2 flutter plugins that are made incompatible, where developers never add the exoplayer dependency directly, so may not even be aware of the problem

I believe the reason of the crash clear. Otherwise I can try to make a sample android or flutter project reproducing it. My guess is that by simply adding those 2 plugins and playing a normal video would make the app crash - according to the project dev description. In any way he has reported that http://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8 had him crash.

I also believe that neither `video_player`, nor `media_info` did nothing wrong, or are able to guarantee that all their versions are compatible with each other, unless this issue is resolved. If I missed something I'd be glad to bring this issue to their attention suggesting a correction course.

**Comment by andrewlewis** [comment]
ExoPlayer doesn't provide API compatibility guarantees across versions I'm afraid, so it is not safe to mix modules with different version numbers (though there may be cases where interfaces happen not to change). If you see gradle dependency resolution doing something like this `com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)` then there is a risk things won't work.

Is it feasible to get video_player to upgrade to depend on ExoPlayer 2.11.5? Or otherwise to have both dependencies use the same version?

Or can you downgrade your dependency on video_player to a version that used an older version of ExoPlayer if you know that worked?

> I'd like to ask to reinstate class AdsMediaSource$MediaSourceFactory with a deprecated annotation, and inheriting from MediaSourceFactory so code writtten for 2.10 is totally "source code compatible" with exoplayer 2.11.

Are you sure there won't be any other incompatibilities if we do this? 

Regarding the crash a runtime: I tried to find a way to make gradle dependency resolution fail for this kind of case a while ago but there didn't seem to be an easy way to do it. Longer term we are looking into the possibility of stabilizing a subset of the API (at which point gradle's dependency resolution would work correctly for ExoPlayer) but this won't happen soon.

**Comment by fmatosqg** [comment]
Hi @andrewlewis thx for your reply.

I'll try to bring a bit of context about `video_player` lib. It is THE official way to play videos in flutter. It's fair to say it's the counterpart of exoplayer for flutter android. I'd expect pretty much anybody doing video in flutter to use it. They do accept pull requests, but I'm looking for a one time solution instead of chasing a fix every time exoplayer breaks compatibility.

For how things work in flutter world I'd also not expect application developers to grasp gradle dependencies. Some will do, but given the abstraction such devs deal with and their own dependency system, it's not a requirement to understand either gradle or cocoapods, which actually bring native mobile dependencies into their builds in a seamless way. It's usually a strength, but in this particular case will be a weak link. 

Would you recommend an approach for `video_player` that only allows for exact gradle exoplayer version and forbids "automatic" upgrades, causing build to break instead of failing at runtime? I'm not familiar with a term to describe `com.google.android.exoplayer:exoplayer-core:2.9.6 -> 2.11.5 (*)` but that's what I mean.

**Comment by fmatosqg** [comment]
@andrewlewis  In the mean time, would you mind if I created a PR with such a class, scheduling it to be deleted again in, say, exoplayer 3.0 ?

**Comment by ojw28** [comment]
As above, ExoPlayer does not currently provide API compatibility guarantees across versions. It doesn't really make sense for us to accept a PR that hides one specific compatibility break. In any case, there are likely to be further compatibility issues when you try and use `2.11.5` rather than `2.9.6` that you just haven't encountered yet.

Given ExoPlayer doesn't provide API compatibility guarantees, this seems like a problem with the Flutter `video_player` and `media_info` libs. They probably need to either (a) require that a specific version of the ExoPlayer dependency is used, or (b) each bundle the specific version of ExoPlayer that they need internally, with a modified package name to avoid conflicting with one another. Option (a) would effectively prevent the two libs being used together, so probably option (b) is the only viable solution. Note that this does increase binary size somewhat, but ExoPlayer is pretty small, and presumably each lib is only using a small subset of ExoPlayer anyway, so most of the two copies will be removed during proguard / R8 optimization.

Closing this because it's not an ExoPlayer issue. I suggest you follow up with the Flutter / `video_player` / `media_info` folks.

**Comment by ojw28** [comment]
Note: I updated my comment above to be more accurate. Please give it a read on GitHub (rather than email). Thanks!

**Comment by fmatosqg** [comment]
Thx @ojw28 . I'll be pursuing solution a) as far as I can.

This conversation is very enlightening and also will impact how I'll depend on exoplayer for my company's internal private audio library.

I'd like to ask if future release notes can include breaking compatibility notes whenever possible, for developers sanity. Not only for flutter's sake, but also for pure android devs, since breaking compatibility is fairly unexpected in maven/gradle world where we indirectly pull dozens if not hundreds of dependencies for a small sized project.

**Comment by ojw28** [comment]
Note that option (a) doesn't work if two different Flutter libraries need different versions of ExoPlayer, as appears to be the case for the project whose dependencies are shown at the top of this thread. For this reason, Flutter libraries should really be following option (b).

> I'd like to ask if future release notes can include breaking compatibility notes whenever possible, for developers sanity. Not only for flutter's sake, but also for pure android devs, since breaking compatibility is fairly unexpected in maven/gradle world where we indirectly pull dozens if not hundreds of dependencies for a small sized project.

Developers who use ExoPlayer directly (which is the common case) will see compatibility changes as compile time errors when upgrading to a newer version, so there's really no ambiguity there. Libraries should really be following option (b) as above, in which case an app developer using the library doesn't need to worry about compatibility, and the library developer will see compatibility changes as compile time errors when upgrading to a newer version. We should write a documentation page for library developers, explaining option (b) and why it's what they should do.

**Comment by evant** [comment]
I'm sorry I don't really understand this stance. It really is best practice for libs to tell you what the breaking changes there are and how to upgrade in their release notes. This makes it easier for a developer to update the lib, gives and idea of what the lift might be for deciding when to do it, and guides where testing efforts should go when making the update. Actually looking at your changelog there are in fact several places where classes that were removed were called out, however it seems like `AdsMediaSource$MediaSourceFactory` was missed.

**Comment by ojw28** [comment]
To clarify, we do make a best effort to call out breaking changes in our release notes, particularly for APIs that developers are likely to be using directly. All I was saying is that if we do forget to list something, then there's still no ambiguity if developers are using ExoPlayer in the recommended way, because they'll always see breaking changes as compilation errors rather than by being surprised by runtime failures.

It should be noted that exhaustively listing breaking changes in the release notes does nothing to solve the problem described in this issue, unless you happen to know exactly which ExoPlayer APIs the plugins that you're using are calling, which seems fairly unlikely. So it's not really related to the issue at hand. The fundamental problem, where you're not really sure whether what you've built is going to fail at runtime, remains.

As a final point, and as @andrewlewis mentioned above, we are looking at the possibility of stabilising a marked subset of ExoPlayer's API surface. The idea is that this subset would consist of the APIs that developers commonly need to use, but exclude the majority of the API surface that's in practice "internal only", except for developers who need to do fairly involved customisations and have pretty advanced use cases. This would provide forward compatibility guarantees for apps and libraries that are able to only depend on the stable subset.
