### ISSUE TITLE
Offline downloaded unable to play, its required internet to play

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7657]
### Issue description
user downloaded the protected dash content videos, sometimes are not unable to stream in offline mode still, the videos are download and license is also not expired. 
It raises the playback exception

**com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect**

**Caused by: java.net.UnknownHostException: Unable to resolve host "d2jx687vmgx9ce.cloudfront.net": No address associated with hostname**

### Reproduction steps
Its occurs sometimes while downloading protected dash videos

### Version of ExoPlayer being used
EXO-PLAYER 2.11.6

### [REQUIRED] Device(s) and version(s) of Android being used
Brand: Redmi Note 7 Pro, Android OS: 9
Brand: Realme X2, Model: RMX1992, OS: 10
Brand: Samsung, Model:  SM-G570F, OS: 8

**Comment by gokulkalagara** [comment]
I share the bug report via mail with exoplayer implementation.
In the bug report, line number 65,150 contains the error message @ojw28 please check it

**Comment by ojw28** [comment]
The fact that you're seeing that error indicates that the content that the player is attempting to play has not been downloaded. This is why the player is attempting to request the content over the network.

One thing to pay particular attention to for DASH content is to ensure that for playback, you tell the player to only try and play the representations that have been downloaded. Else the player may attempt to adapt to a representation that has not been downloaded. This is normally done by using `DownloadHelper`, as is documented on [this page of our developer guide](https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams). Note in particular:

> You can create a MediaSource for playback by calling DownloadHelper.createMediaSource [...] **The created MediaSource is aware of which tracks have been downloaded, and so will only attempt to use these tracks during playback**. See PlayerActivity in the demo app for a concrete example.

Please check your code and make sure the player is not trying to play non-downloaded representations. If you're sure that this is happening correctly, please modify your code so that an `EventLogger` is attached to the player, and capture another bug report shortly after experiencing the issue. `EventLogger` will log additional useful information, which may help us to narrow down the cause. It's generally useful just to do this by default in your code, since the logging isn't particularly high volume, and is really helpful when inspecting bug reports when issues do arise.

**Comment by gokulkalagara** [comment]
**//download request**

```
 DownloadRequest downloadRequest = ((HelperApplication) getActivity().getApplication()).getDownloadTracker().getDownloadRequest(uri);
        if (downloadRequest != null) {
                if (((HelperApplication) getActivity().getApplication()).getDownloadTracker().getDownload(uri).state == Download.STATE_COMPLETED) {
                    fromOffline = true;
                    return DownloadHelper.createMediaSource(downloadRequest, dataSourceFactory,
                            viewModel.generateDRMManager(Util.getUserAgent(Utility.getContext(), Constants.APP_NAME), uri, securityLevel));

                }
        }
```

 **// for offline not adding the Event logger**

```
if (fromOffline) {
            player.addAnalyticsListener(new AnalyticsListener() {
                @Override
                public void onTracksChanged(EventTime eventTime, TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

                    MappingTrackSelector.MappedTrackInfo mappedTrackInfo =
                            trackSelector != null ? trackSelector.getCurrentMappedTrackInfo() : null;
                    if (mappedTrackInfo == null) {
                        return;
                    }
                    try {

                        for (int i = 0; i < mappedTrackInfo.getTrackGroups(0).length; i++) {
                            TrackGroupArray trackGroupArray = mappedTrackInfo.getTrackGroups(i);
                            for (int j = 0; j < trackGroupArray.get(i).length; j++) {
                                Logger.d("Download Resolution", "" + trackGroupArray.get(i).getFormat(j).height);
                                videoPlayerBinding.tvQuality.setText("" + trackGroupArray.get(i).getFormat(j).height);
                                return;
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            });


        } else {
            player.addAnalyticsListener(new EventLogger(trackSelector));
        }
```

@ojw28 I'm not adding event logger for download content, for that reason event logger did not get for the records
If it is online content it will get event logger logs. 


I'm downloading only single resolution, TrackSelector is default and also for offline videos we not allowing change the track selector for offline video
                
trackSelector = new DefaultTrackSelector(activity(), videoTrackSelectionFactory);

**Comment by gokulkalagara** [comment]
@ojw28 Thank you for quick reply

**Comment by ojw28** [comment]
Copy / pasting some random snippets of code from your app isn't going to help here. As per my comment above, the fact that you're seeing the error you're seeing indicates that the content the player is attempting to play has not been downloaded. You'll need to more thoroughly debug why this is the case.
