### ISSUE TITLE
Not able to playback the MPEG-4 ALS content (Error : Media includes audio tracks, but none are playable by this device)

### ISSUE THREAD

**Issue by imranhsn** [google/ExoPlayer#7660]
### [REQUIRED] Searched documentation and issues
I have looked for same issues but still can't find an answer.

### [REQUIRED] Question
I am trying to playback the MPEG-4 ALS DASH content from demo app, it shows `Media includes audio tracks, but none are playable by this device`. When I check the [support format](https://exoplayer.dev/supported-formats.html), I didn't found this format for DASH. So I have some query about it.

1. Is it possible to playback MPEG-4 ALS content from Exoplayer?
2. If yes, how can I playback this video from Exoplayer?

I have the ALSDecoder library native file, I think its all about decoder problem and I have to use the decoder library. But where I have to use this decoder library?. I check Ffmpeg extension for custom renderer but when I debug the DRM video, it didn't call the `createDecoder` method. I am confuse about the process and need proper guideline.

Testing Device:
1. Xiaomi Mi pad 4 (OS 8.1) - L3 security
2. Pixel 3 XL (OS 10.0) - L1 security

### A full bug report captured from the device
```2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:5 [
2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=p0aa0br1854859, mimeType=audio/mp4a-latm, bitrate=1854859, codecs=mp4a.40.36, channels=2, sample_rate=96000, language=en, supported=NO_UNSUPPORTED_DRM
2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger:     ]
2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger:   ]
2020-07-13 00:48:18.707 29652-29652/com.google.android.exoplayer2.demo D/EventLogger: ]
```
### Link to test content
Sorry, I don't have permission to share the link.

**Comment by ojw28** [comment]
`NO_UNSUPPORTED_DRM` indicates that the stream is using an unsupported DRM type. Or alternatively, you're not providing a `DrmSessionManager` to facilitate decryption. What type of DRM protection does the stream have?

If you were to resolve the DRM issue, I'm not sure whether you'd encounter a subsequent issue due to your use of MPEG-4 ALS. The easiest way to test this would be to get an equivalent stream without any DRM protection, and to try playing that.

> I have the ALSDecoder library native file, I think its all about decoder problem and I have to use the decoder library. But where I have to use this decoder library?. I check Ffmpeg extension for custom renderer but when I debug the DRM video, it didn't call the createDecoder method. I am confuse about the process and need proper guideline.

If you need to use a custom decoder library to play the content, then you'll need to make an extension that's equivalent to the FFmpeg extension, but calls into whatever decoder library you need instead. Exactly how to implement this really depends on the details of the library you're using, and is not something we can provide much support on. The existing extensions should serve as fairly good starting points for trying to do this, however.

**Comment by imranhsn** [comment]
Here I am provided `DrmSessionManager `, it's not an issue. The DRM protection used Widevine.. When I enable FFmpeg extension and debug DRM video from the Exoplayer demo app, it also returns `NO_UNSUPPORTED_DRM ` from `supportsFormatInternal` method of `FfmpegAudioRenderer ` and didn't call `createDecoder` method but the video is working fine. For clear key, it returns `FORMAT_HANDLED` and calls the `createDecoder` method.

```@Override
  @FormatSupport
  protected int supportsFormatInternal(
      @Nullable DrmSessionManager<ExoMediaCrypto> drmSessionManager, Format format) {
    Assertions.checkNotNull(format.sampleMimeType);
    if (!FfmpegLibrary.isAvailable()) {
      return FORMAT_UNSUPPORTED_TYPE;
    } else if (!FfmpegLibrary.supportsFormat(format.sampleMimeType) || !isOutputSupported(format)) {
      return FORMAT_UNSUPPORTED_SUBTYPE;
    } else if (!supportsFormatDrm(drmSessionManager, format.drmInitData)) {
      return FORMAT_UNSUPPORTED_DRM;
    } else {
      return FORMAT_HANDLED;
    }
  }
```

> If you need to use a custom decoder library to play the content, then you'll need to make an extension that's equivalent to the FFmpeg extension, but calls into whatever decoder library you need instead. Exactly how to implement this really depends on the details of the library you're using, and is not something we can provide much support on. The existing extensions should serve as fairly good starting points for trying to do this, however.

The decoder library takes inputStream data as input. I know you can't provide much support, it's okay. But as I see from debugging `createDecoder` method doesn't call from `FfmpegAudioRenderer ` class for DRM video, is there any way to implement this decoder library in that case? I just want to know If I want to resolve this issue where I need to change? or what I need to do? I think it will be helpful to me.

Thank you.

**Comment by ojw28** [comment]
You see `NO_UNSUPPORTED_DRM` when using the FFmpeg extension because the FFmpeg extension doesn't support DRM. There are valid security reasons for not supporting DRM with software decoder extensions, because it's very difficult to actually ensure the level of protection that the DRM scheme is intended to be used for in this case (in which case, there's not really much point using DRM in the first place).

As above, exactly how to integrate with a specific decoder library is going to depend on the details of the library itself, and is not something we can provide much support on. The type of media you're trying to play is quite different to what the vast majority of streaming providers serve to mobile devices, so you should also consider whether serving a more usual media format might be a better option than doing a lot of client side work.
