### ISSUE TITLE
Not able to get bandwith for UDP MPEG-TS stream

### ISSUE THREAD

**Issue by xoancosmed** [google/ExoPlayer#7661]
### Searched documentation and issues
Looked issues:
- https://github.com/google/ExoPlayer/issues/6843
- https://github.com/google/ExoPlayer/issues/2029

### Question
I'm playing an UDP MPEG-TS stream in ExoPlayer, but I'm not able to get metrics like the bandwidth, although I'm able to get the frame drop.

This is how I'm generating the stream (where `SampleVideo.mp4` is input video file and `192.168.1.22` is the IP of my Android device):

```bash
ffmpeg -re -i SampleVideo.mp4 -f mpegts udp://192.168.1.22:1235
```

If I try this using the official Android VLC app setting the stream source to `udp://@:1235` the video plays as expected.

This is my code to intialize the player (there are some parts I removed from my code to make it more clear and understandable):

```java
private void initializePlayer() {
            mUiUpdateHandler = new UiUpdateHandler(this);
            bandwidthMeter = new DefaultBandwidthMeter.Builder(MetricVideoActivity.this).build();
            bandwidthMeter.addEventListener(mUiUpdateHandler, (elapsedMs, bytes, bitrate) -> {
                        bitrateEstimate = bitrate;
                        bytesDownloaded = bytes;
                        bytesTotal += bytes;
                        timeTotal += elapsedMs;
            });

            DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this, getDrmSessionManager(), DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF);
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            player = ExoPlayerFactory.newSimpleInstance(this, renderersFactory, trackSelector, new CustomLoadControl(new CustomLoadControl.EventListener() {
                @Override
                public void onBufferedDurationSample(long bufferedDurationUs) {
                    bufferedDurationMs = bufferedDurationUs;
                }
            }, mUiUpdateHandler));

           player.addListener(eventLogger);
           player.setMetadataOutput(eventLogger);
           player.setPlayWhenReady(true);
           simpleExoPlayerView.setPlayer(player);

           MediaSource mediaSource = buildMediaSource(uri);
           player.prepare(mediaSource, !haveResumePosition, false);
}

private MediaSource buildMediaSource(Uri uri) {
            ExtractorsFactory tsExtractorFactory = () -> new TsExtractor[]{new TsExtractor(TsExtractor.MODE_SINGLE_PMT,new TimestampAdjuster(0), new DefaultTsPayloadReaderFactory())};
            UdpDataSource.Factory factory = () -> new UdpDataSource(5000, 100000);
            return new ExtractorMediaSource(
                    uri,
                    new DefaultDataSourceFactory(this, bandwidthMeter, factory),
                    tsExtractorFactory,
                    mainHandler, eventLogger);
}
```

Where:
- The variable `uri` is `udp://@192.168.1.22:1235` (I also tryed `udp://@:1235` like in VLC, but in that case the video doesn't play and I get a timeout exception).
- The variable `mainHandler` is an object of the type `android.os.Handler`.
- The variable `eventLogger` is a custom class which implements `EventListener`, `AdaptiveMediaSourceEventListener` and `MediaOutput`.
- The variable `bandwidthMeter` is of type `com.google.android.exoplayer2.upstream.DefaultBandwidthMeter`.

If I place a breakpoint or log inside the bandwidthMeter's event listener, It's never called. **How can I properly attach my bandwithMeter to the UDP source?**

Also, I noticed that the methods `onLoadCompleted` or `onDownstreamFormatChanged` from `AdaptiveMediaSourceEventListener` (implemented by `eventLogger`) are also never called.

I'm using ExoPlayer 2.11.6 on Android 9.

**Comment by tonihei** [comment]
I don't think you have to create a custom bandwidth meter for that. It would probably be easier to just use:
```
player.addAnalyticsListener(new AnalyticsListener() {
  @Override 
  public void void onBandwidthEstimate(
      EventTime eventTime, int totalLoadTimeMs, long totalBytesLoaded, long bitrateEstimate) {
    ...
  }
});
```

**Comment by ojw28** [comment]
@tonihei - I think the problem with that approach is that bandwidth estimates are only generated when a network request is completed, which doesn't happen for this type of playback except when the playback is ended.

**Comment by xoancosmed** [comment]
I agree with @ojw28. I tried the AnalyticsListener and it's not called until the end of the video or until I cut the live video streaming. So, is there any way I can get the estimated bandwith without waiting the playback to end?

**Comment by tonihei** [comment]
Yes, I missed that you are using `ExtractorMediaSource`.  In this case, you'll only get the estimate after playback ended and possibly after seeks.

Note that our `DefaultBandwidthMeter` was written with adaptive playbacks using chunks of media in mind. In this world, it's easier to wait until a network connection is closed to get an estimate. And more crucially, we also don't need an estimated bandwidth until the previous load finished and the next adaptive bitrate decision needs to be made.

In addition to that, the bandwidth you get at the end of playback is likely to be an underestimate because there are some times in which we keep the connection open but don't read data.  This violates the assumption made by the `DefaultBandwidthMeter` that the data is always loaded at maximum possible speed.

> So, is there any way I can get the estimated bandwith without waiting the playback to end?

Only by writing your own `BandwidthMeter` implementation. As noted above, our current implementation makes some assumptions that only make sense for adaptive playback and can't be easily reused for your request. But you should still be able to write a `BandwidthMeter` implementation that listens to `onTransferStart`, `onBytesTransferred` and `onTransferEnded` to calculate your own estimate in `onBytesTransferred` (=during playback). Note some caveats:
 - These methods are called from background threads, so you need some form of synchronization. If there are multiple loads, they may also overlap.
 - `onBytesTransferred` will be called very often and you shouldn't start any heavy computation in this method, or maybe only every second or so.

Finally, I'd recommend that you simplify your code setup (e.g. following the simplifications mentioned in this [blog post](https://medium.com/google-exoplayer/https-medium-com-google-exoplayer-simplified-bandwidth-meter-usage-17d8189f978b)) and only set your custom `BandwidthMeter` in`SimpleExoPlayer.Builder.setBandwidthMeter`.

**Comment by xoancosmed** [comment]
I'll try with a custom BandwidthMeter and with those simplifications. Thank you so much for the explanation @tonihei

**Comment by tonihei** [comment]
I'll close the issue because it looks as if the question was answered satisfactory.
