### ISSUE TITLE
How to download only highest quality video (DASH)?

### ISSUE THREAD

**Issue by lavajaw** [google/ExoPlayer#7682]
### [REQUIRED] Searched documentation and issues
I check documentation and also saw similar issue 
https://github.com/google/ExoPlayer/issues/6911

### [REQUIRED] Question
When I download media item (movie or episode) on android device (DASH/ DRM content) I download all qualities for that media items. I see in code that as default is selected 
setForceHighestSupportedBitrate(true)
but still size is for example 600mb and should be 300. Also iOS team from my company confirmed that that size is for all qualities and advise me to try to select only highest. But how to do it? My code is same as in issue #6911 

### Link to test content
I cant provide you DRM content here.

**Comment by tonihei** [comment]
If you are using `DownloadHelper`, it automatically downloads the highest quality only. Can you share which `TrackSelectionParameters` you specify for `DownloadHelper` (if any) and what the list of `DownloadRequest.streamKeys` is for the `DownloadRequest` returned by `DownloadHelper.getDownloadRequest`?

**Comment by ojw28** [comment]
It's also worth giving [the relevant documentation](https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams) a read, if you haven't done so already.

**Comment by lavajaw** [comment]
Hello:
`
public static CacheDataSourceFactory buildReadOnlyCacheDataSource(
            DataSource.Factory upstreamFactory, Cache cache) {
        return new CacheDataSourceFactory(
                cache,
                upstreamFactory,
                new FileDataSource.Factory(),
                /* cacheWriteDataSinkFactory= */ null,
                CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
                /* eventListener= */ null);
}

public static DataSource.Factory buildDataSourceFactory(Context context, Cache cache) {
        DefaultDataSourceFactory upstreamFactory = new DefaultDataSourceFactory(context, buildHttpDataSourceFactory());
        return buildReadOnlyCacheDataSource(upstreamFactory, cache);
}

dataSourceFactory = buildDataSourceFactory(getApplicationContext(), getDownloadCache(this));
public static RenderersFactory buildRendersFactory(Context context) {
        return new DefaultRenderersFactory(/* context= */ context)
                .setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF);
}

DownloadHelper.forDash(context, uri, dataSourceFactory, buildRendersFactory(context))`

**Comment by lavajaw** [comment]
Adn for streamKeys i have size 0 (I dont have them).

I just saw this description in DownloadRequest:
 /** Stream keys to be downloaded. If empty, all streams will be downloaded. */
So my streamKeys array size is 0, so all are downloaded. How to change this?

**Comment by tonihei** [comment]
Yes, that's likely the reason for downloading all qualities. The only way this can happen is if no tracks are selected. This could be the case for example because no stream is supported by the device. If you'd like us to look further, please provide a minimal reproducible example including test media so that we can understand what it is happening and whether there is a bug we need to fix and if there is something we should improve in the API.

**Comment by lavajaw** [comment]
@tonihei ok, i can provide you informations, but content is protected so i can send you some informations in DM or on mail?

**Comment by tonihei** [comment]
Ah :) If the content is protected and requires DRM keys to play, then this is probably the reason no track is selected. The track selection will claim it can't play the streams because the DRM session manager isn't set. You can try passing the correct `DrmSessionManager` via the longer `DownloadHelper.forDash` method to see if it helps. Otherwise, you can share information via dev.exoplayer@gmail.com with "Issue #7682" in the subject line.

**Comment by lavajaw** [comment]
Ok, i will try to add DrmSessionManger first. I am not sure how to create DrmSessionManager (FrameworkMediaCrypto) . Maybe you have any example for this?

**Comment by tonihei** [comment]
The same way you are playing the media. If you don't use a `DrmSessionManager` for playback, then you probably don't need one.

**Comment by lavajaw** [comment]
@tonihei just to confirm that longer DownloadHelper.forDash method worked. Thanks
