### ISSUE TITLE
How to get the live latency?

### ISSUE THREAD

**Issue by mehdibf** [google/ExoPlayer#7685]
### [REQUIRED] Searched documentation and issues
- https://github.com/google/ExoPlayer/issues/6099
- https://exoplayer.dev/doc/reference-v1/com/google/android/exoplayer/dash/mpd/UtcTimingElementResolver.UtcTimingCallback.html
- https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html#windowStartTimeMs

### [REQUIRED] Question
I am trying to calculate the live latency of a live stream. I was not able to find any API to get the value from so I tried to implement the solution suggested in https://github.com/google/ExoPlayer/issues/6099. 

`long currentSystemTime = System.currentTimeMillis();
          Timeline.Window window = player.getCurrentTimeline().getWindow(player.getCurrentWindowIndex(), new Timeline.Window());
          long liveLatency = currentSystemTime - (player.getCurrentTimeline().getWindow(player.getCurrentWindowIndex(),window).windowStartTimeMs + player.getCurrentPosition());`

the problem is that currentSystemTime is not synchronized with the server time. Is there any API to request the server UTC Time after it has been resolved in onTimestampResolved?

**Comment by tonihei** [comment]
The latest dev-v2 branch has a method `player.getCurrentLiveOffset()` that returns the live offset. However, for HLS, it does not adjust the offset for out-of-sync client clocks. We may add this feature as part of #5011, but it's not strictly needed for HLS live playback because the playback itself is not dependent on the client clock (that is different from DASH for example, where the client clock may be relevant). 

However, you can retrieve and add the offset yourself by using `SntpClient.initialize(loader, callback)` to load the offset and then calculate `SystemClock.elapsedRealtime() + SntpClient.getElapsedRealtimeOffsetMs() - window.windowStartTimeMs + player.getCurrentPosition()`.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
