### ISSUE TITLE
Improve GSM support

### ISSUE THREAD

**Issue by mathavanmanoharan** [google/ExoPlayer#7695]
### [REQUIRED] Version of ExoPlayer being used LATEST

###Used Redmi k20 pro  OS 10

**Comment by tonihei** [comment]
According to https://developer.android.com/guide/topics/media/media-formats#core, GSM should be supported, but I'm not certain about the details. If you want us to have a look, please provide example media that reproduces your problem.

**Comment by mathavanmanoharan** [comment]
Ya thanks for your reply. And hereby I attached the sample media file for
.gsm format which I used and not playable. But it's played in MX player.
Please find the attached file. Thanks in advance

**Comment by mathavanmanoharan** [comment]
But in your exo player official document, there is nothing mentioned about
.gsm format please take a look at progressive media source. I used
progressive media source.

https://exoplayer.dev/supported-formats.html

**Comment by mathavanmanoharan** [comment]
[sample1_exo.zip](https://github.com/google/ExoPlayer/files/5012234/sample1_exo.zip)
please find the sample media file which I used for .gsm format.

**Comment by tonihei** [comment]
Thanks for the file. It seems that there are at least two missing features in ExoPlayer to play GSM files or GSM encoded data:
 1. The provided file is apparently using some form of GSM container format that isn't supported. Do you have any details on how this file is generated and according to which specifications? That would help to understand what it is exactly.
 2. GSM encoded media can be put in a WAV file (see https://en.wikipedia.org/wiki/WAV#Comparison_of_coding_schemes, 8kgsm.wav). This file is also not supported by ExoPlayer because the `WavExtractor` rejects it.

**Comment by andrewlewis** [comment]
Adding needs more info label as https://github.com/google/ExoPlayer/issues/7695#issuecomment-667919367 has a pending question.
