### ISSUE TITLE
stream video in parts and play

### ISSUE THREAD

**Issue by punitagoel2403** [google/ExoPlayer#7707]
_Note: I am new to video streaming!_
I am trying to stream a video, which works well but it takes 17-18 sec at least to load for the first time ( second time it is better as I am caching the video)
I thought, I probably need to use a streaming data URL (server side), which provides partial content and not entire video in one go, but for that exoplayer denies playback, as no datasource is able to read it.  Then I read in one of the issues raised in past here, that exoplayer by default supports streaming, and fetches only a part of video from URL and starts playing it. But it is not happening in my case.  It loads almost complete video in one go.

My code:

```
if (player == null) {
            TrackSelection.Factory videoTrackSelectionFactory = new RandomTrackSelection.Factory();
            TrackSelector trackSelector = new
                    DefaultTrackSelector(videoTrackSelectionFactory);
            LoadControl loadControl = new DefaultLoadControl.Builder()
                    .setAllocator(new DefaultAllocator(true, 16))
                    .setBufferDurationsMs(2000,2000,1000,1500)
                    .setTargetBufferBytes(C.LENGTH_UNSET)
                    .setPrioritizeTimeOverSizeThresholds(true).createDefaultLoadControl();


            player = new SimpleExoPlayer.Builder(context)
                    .setTrackSelector(trackSelector)
                    .setLoadControl(loadControl)
                    .build();
            concatenatingMediaSource  = new ConcatenatingMediaSource();

        }
        HostnameVerifier hostnameVerifier = new HostnameVerifier() {
            @Override
            public boolean verify(String s, SSLSession sslSession) {
                return true;
            }
        };
        HttpsURLConnection.setDefaultHostnameVerifier(hostnameVerifier);
        HttpsURLConnection.setDefaultSSLSocketFactory(getSSLSocketFactory());

        DefaultHttpDataSourceFactory dataHttpSourceFactory = new
                DefaultHttpDataSourceFactory(Util.getUserAgent(context,
                "my-app"));
        dataHttpSourceFactory.getDefaultRequestProperties().set("Cookie", VolleyRequests.getSessionId());
        DataSource.Factory dataSourceFactory = new CacheDataSourceFactory(VideoCache.getInstance(context), dataHttpSourceFactory);
        MediaSource mediaSource1 =  new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(url);
        player.addListener(new PlayerEventListener());
        LoopingMediaSource loopingSource = new LoopingMediaSource(mediaSource1);
        concatenatingMediaSource.addMediaSource(loopingSource);
        player.prepare(concatenatingMediaSource);
```

Can anyone please tell, if I am missing anything from client or server side. I couldn't find any suitable solution anywhere.
The video type is mp4

**Comment by ojw28** [comment]
Why are you overriding the default values when instantiating the `LoadControl`? In particular using `16` in `new DefaultAllocator(true, 16)` doesn't look like a sensible value. The default is to use `65536`, so `16` is likely to be way too small and will incur quite significant performance overhead. The first two values passed to `setBufferDurationsMs` also look very small.

Also, why are you using `RandomTrackSelection`? That's only really useful for debugging purposes.

Particularly if you're new to ExoPlayer, I'd strongly recommend you don't start fiddling around with the parameters. Try removing your `LoadControl`, and your `TrackSelector`, and the corresponding calls to `setLoadControl` and `setTrackSelector`. This will give you a player that's in a sensible default configuration.

If that resolves the issue, then the issue is with the way you're configuring the player. Try changing these values one at a time, making sure to understand exactly what each one is doing, and you should be able to figure out that way which value(s) are problematic.

If the issue remains even with the player in a default configuration, then you'll need to share the MP4 file with us so that we can take a look.

**Comment by punitagoel2403** [comment]
I removed both the parameters, still the same situation. But I guess the problem is with video. I tried using some internet downloaded video, and it took not more than 10 sec in starting initially, (although it I believe it could have been even better - but it is working as expected, buffering while playing). 
I even tried my video (generated in the app through cam recording) and internet picked video in Exoplayer demo (misc- Dizzy (MP4)), the results were same. Around 10 sec for internet generated video and 45 sec for the video generated through my app. 

I am attaching both the videos for your reference. 

[video files.zip](https://github.com/google/ExoPlayer/files/5016890/video.files.zip)

**Comment by ojw28** [comment]
Yes, the problem is with the video file. MP4 files consist of "boxes" that contain information required for playback. Before playback can start, the player needs to process the `moov` box, which contains information about the type of the media in the file. After it's done so, it needs to read the actual audio and video samples from the `mdat` box(es), at which point it can start playback.

The optimal order of boxes in MP4 files is therefore to have the `moov` box before any `mdat` boxes, so that the player loads information in the order that it needs it. Both of the files you provided have the opposite ordering, with the `moov` box at the end of the file, meaning that they're not prepared in a way that's optimal for streaming. You can easily see how the file is structured using the [ISOBMFF Box Structure Viewer](https://gpac.github.io/mp4box.js/test/filereader.html) tool.

Although not optimal, it's not that uncommon for the `moov` to be at the end of an MP4 file, because it's a bit cheaper at file creation time to write a file with this ordering. At playback time, a player needs to skip over `mdat` boxes until it finds the `moov` box, process it, and then jump back to the first `mdat` box again to begin reading the audio and video samples for playback. In the normal case with this ordering, there's only a single large `mdat` box containing all of the audio and video samples. This is the case with the "internet picked video" you provided. In this case, ExoPlayer knows that it needs to skip over a large amount of data before it has a chance of finding the `moov`. It therefore stops downloading data from the server and instead issues a new network request starting after the end of the `mdat`. Hence the player can find the `moov` and start playback without having to download the entire file first.

The reason your "app generated video" is particularly bad is that not only is the `moov` at the end of the file, but the audio and video samples are written into a large number of small `mdat` boxes, rather than a single large one. The trick where ExoPlayer would issue a new network request toward the end of the file doesn't work, and its only option for finding the `moov` is the skip forward through the file one `mdat` box at a time, until it's eventually downloaded the entire file, at which point it finally discovers the `moov` at the end. At this point it can process it and jump back to the first `mdat` box.

So, to fix this, you need to make sure your content either uses a single large `mdat` box like the "internet picked video", or (better!) has the `moov` before the `mdat` boxes.

**Comment by punitagoel2403** [comment]
Brilliant!! Thank you for such detailed explanation. I was using a compression lib, which was messing up the structure. Now it is working flawlessly.

But for files that I am allowing a user to pick from gallery, there are chances of "moov" box being at the end, like you mentioned. So, is it advisable to restructure it, or else, those particular files would still take a while to load.

**Comment by ojw28** [comment]
If the user is picking files that are local on the device, there's no point in restructuring them.

If the files are being streamed over the network, then having the `moov` at the end is going to add ~2 network round trips to the startup latency compared to if it were at the beginning. Whether eliminating that is worth re-transcoding the content is up to you!

**Comment by punitagoel2403** [comment]
Thank you Oliver. Can you also provide me some link/ source where from I can get this valuable understanding of videos and work on my own compression and other utilities of videos? Or some already built good libraries?

**Comment by ojw28** [comment]
I don't think there really is a single source of information for this kind of thing, so your preferred search engine is generally the best starting point.
