### ISSUE TITLE
Current thumbnail gets changed while coming from background

### ISSUE THREAD

**Issue by vairaganeshv** [google/ExoPlayer#7721]
**[REQUIRED]** Issue description

Thumbnail of the video gets changed when you put the application in background and foreground simultaneously

[REQUIRED] Reproduction steps

1. play the video
2. put the app in background
3. bring the app to foreground
4. Repeat step 2 and 3 for multiple times (10 - 20).

While playing the video put the app in background from the android fragment life cycle event i have pause the player in onPause() and onStop()

        if (player != null && player.isPlaying()) {
            player.setPlayWhenReady(false);
        }
		
Player will intialized only once on 

    public void onResume() {
        super.onResume();
        if (Build.VERSION.SDK_INT < 24) {
			initializePlayer();
        }
    }
	
	    public void onStart() {
        super.onStart();
        if (Build.VERSION.SDK_INT >= 24) {
		initializePlayer();
        }
    }
	
	Player will gets released
	
	    public void onDestroy() {
        super.onDestroy();
			releasePlayer();
        }

[REQUIRED] Version of ExoPlayer being used

**exoplayer version 2.10.5**

[REQUIRED] **Device(s)** and version(s) of Android being used

**Redmi note 6 pro**

**Comment by ojw28** [comment]
This is a known limitation of the underlying platform. Each time your app comes back into the foreground, a new `Surface` is created. It's not possible to re-render the same output buffer as was rendered to the previous `Surface` to the new `Surface`, and therefore we need to advance one frame to render something. Fortunately, users don't tend to repeatedly foreground and background apps in this way, so it's rarely a problem in practice.

The underlying platform limitation was resolved in API level 29 via the addition of the [SurfaceControl](https://developer.android.com/reference/android/view/SurfaceControl) API. This allows you to keep the same `Surface` and re-parent it to the new view with the previous output buffer still rendered to it. Use of this API is demonstrated in the our [surface demo](https://github.com/google/ExoPlayer/tree/release-v2/demos/surface). That said, since it only works on API level 29 and later, it's not going to be helpful for the majority of devices quite yet.

Another way to avoid the frame jumping forward is to do an explicit seek each time the app comes back into the foreground. This is expensive and slow, however!
