### ISSUE TITLE
How to use dubbing in ExoPlayer?

### ISSUE THREAD

**Issue by halilozel1903** [google/ExoPlayer#7723]
Hi,

I want to use dubbing in ExoPlayer.

How can I use dubbing?

Help me please.

**Comment by ojw28** [comment]
This question is much too vague for us to be able to help, sorry.

**Comment by halilozel1903** [comment]
I want to add a dub to a video.

For example English, Turkish dubs.

I could not find an example like this.

How can I add dub into video in ExoPlayer?

**Comment by ojw28** [comment]
It really depends on what type of media you have. You obviously need to start from a point where you have all of the content, including the dub track. Preparing your content isn't in scope for this issue tracker. So, what format is that content in? Can you provide sample media that includes the dub track and explain more precisely what your problem is? It's very unlikely we'll be able to help with such a brief description of the problem.

**Comment by halilozel1903** [comment]
There is a hls type video in the app. I want to show subtitles and dubbing options in this video.

**Comment by ojw28** [comment]
To reiterate the request above:

> Can you provide sample media that includes the dub track and explain more precisely what your problem is? It's very unlikely we'll be able to help with such a brief description of the problem.

Without sample media and without a detailed description, it's not possible for us to help.
