### ISSUE TITLE
Demo app doesn't play ClearKey content on API level <= 26

### ISSUE THREAD

**Issue by TheJohnBowers** [google/ExoPlayer#7735]
### [REQUIRED] Issue description
Exoplayer Demo application says clearkey is an unsupported DRM scheme on release-v2 branch (2.11.7).   This only happens on actual devices, not on emulated devices. 
I did not figure out exactly when it stopped working, I only know that it did work in 2.10.0 and it no longer works in 2.11.7

### [REQUIRED] Reproduction steps
Simply try to play the test content below in the demo application on release-v2.  The same content plays fine on 2.10.0 
IMPORTANT - You must use a real device to see the issue.  When using an emulated device content plays fine with 2.11.7

### [REQUIRED] Link to test content
      {
        "name": "ClearKey sample that worked on 2.10.0",
        "uri": "https://content.uplynk.com/f3b6abb6da59413ab6f6241922a3b4e5.mpd?ck=1",
        "drm_scheme": "clearkey",
        "drm_license_url": "https://content.uplynk.com/ck",
        "drm_multi_session": true
      },
### [REQUIRED] A full bug report captured from the device
Sent to dev.exoplayer@gmail.com as "Issue #7735"

### [REQUIRED] Version of ExoPlayer being used
2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Android 7.0 Samsung Galaxy S8
Android Fire TV Stick
Those are the only 2 devices I have tested, but I suspect this issue is not really sensitive to devices or android versions.

**Comment by ojw28** [comment]
It's not about whether it's running on an emulator or not. It's about the API level of the device. The issue occurs on API level 26 and earlier. The issue is _only_ an issue with the demo app, not with the actual library. If you comment out the check that the demo app is making, playback works successfully on API level 26 and earlier.

The problem is that on API level 26 and earlier, the ClearKey CDM had to be accessed using `C.COMMON_PSSH_UUID` rather than `C.CLEARKEY_UUID`. The actual library code modifies the UUID to the one needed for playback, but the demo app is making a direct check for support without UUID modification. We'll fix that, or possibly just remove the check completely.
