### ISSUE TITLE
TS video block to exclude special binaries

### ISSUE THREAD

**Issue by JaredLees** [google/ExoPlayer#7740]
To prevent the M3U8 video stream from being used by others, I added some special binaries to the TS video block. I wanted to use Exoplayer to exclude special binaries before playing them. How could I do that?

**Comment by andrewlewis** [comment]
By "added some special binaries" do you mean that the TS stream contains additional data that your app needs to throw away to get a valid stream (designed to make players without this functionality fail to play the stream)? Or something else? It's a bit unclear what you are asking, so I may have completely misunderstood the question.

If it is the former, the details will depend on how the extra data has been added to the stream. You may need to implement a custom `DataSource`, or fork the TS payload reader(s), for example.

Aside: If this way of doing content protection is something you've come up with yourself I'd advise against doing that, and instead recommend using something more industry-standard. Otherwise you may find that the scheme is easy to compromise. You could (for example) look at using Widevine or AES-128 in HLS to protect your streams. (For the case of AES-128 in HLS, I would avoid including the symmetric key in the APK and instead get the key having checked the integrity of the requesting app using [SafetyNet](https://developer.android.com/training/safetynet/attestation).)

**Comment by JaredLees** [comment]
Thank you. That's the first case you mentioned.

I want to add some special binaries at the beginning of the stream, if I don't customize, but want to rewrite some code in HlsDataSource to implement it. I want to know where is the entry point for reading TS data before each play, and I want to process the file at the entry point.

**Comment by JaredLees** [comment]
After reading the source code of exoplayer and seeing the TsExtractor, can I do this operation for it in the Read method?

**Comment by andrewlewis** [comment]
> I want to add some special binaries at the beginning of the stream

If the only difference between the stream you are serving and a 'normal' (valid) MPEG-TS stream is that you always have some extra bytes at the start, you can probably do this by writing a custom `DataSource` that skips the first _n_ bytes. That would be straightforward and is format-agnostic.

If you are embedding the extra data somewhere else in a more complicated way that depends on the MPEG-TS container syntax, you will need to read through the code for the TS extractor to figure it out yourself (I'm afraid we don't have time to give detailed step-by-step support on this kind of niche use case).

**Comment by JaredLees** [comment]
I just want to confirm that There is no problem for me to do this at TsExtractor. Thanks for your reply and Suggestions!

**Comment by AquilesCanta** [comment]
I think, as @andrewlewis points out, it's better if you do it in the DataSource. After the open call and before the first read() call (maybe during open()). TsExtractor.read() will be invoked after sniffing. But sniffing will fail if there is a blob before the TS, which means you'll never reach the read call.

> I want to know where is the entry point for reading TS data before each play

I think that's up to you, considering you are responsible of prepending the binary data.
