### ISSUE TITLE
Australian Subtitle is not showing for livestream

### ISSUE THREAD

**Issue by MrtDolphin0128** [google/ExoPlayer#7746]
Subtitles are not visible for streaming videos.

**Comment by andrewlewis** [comment]
Could you provide some details about how this is related to #7747 and #7749? We need the information requested in the [new issue template], so please fill that out.

Setting aside the lack of information about what the enhancement is, the pull request currently has a few issues that mean we couldn't merge it (for example, it commits native binaries into the core module, and seems to add a lot of debug logging).

**Comment by MrtDolphin0128** [comment]
It is for the case when we try to play UDP stream,
In this case subtitles are not showing.
Anyway i made custom engine to make Australian subtitles visible but I am not sure how to push my code to google repository.
Can you help me with this?
Best

**Comment by andrewlewis** [comment]
Please fill out the [new issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/feature_request.md). For example, it would be useful to know what specification the subtitles follow and/or what specific features are missing, and how libcce was built in your pull request.

**Comment by MrtDolphin0128** [comment]
libcce is from https://github.com/CCExtractor/ccextractor .
I built .so files from it and used it in my customized engine.
So can you please help me to push my code?

**Comment by andrewlewis** [comment]
> So can you please help me to push my code?

The first step is to fill out the [new issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/feature_request.md) as I've requested already twice. Please don't ignore this request this time. Make sure to include what specification the subtitles follow and/or what specific features are missing.

Then we will review the information and decide whether to add this functionality to ExoPlayer. I'm afraid we can't promise to include this, because whenever we merge new functionality we need to spend resources reviewing and maintaining it. If we decide that it's worth it we'll take a look at the pull request. I guess this may be related to the discussion in #7220. To set expectations, I'd be surprised if we can merge this quickly given the pull request uses an external dependency and is non-trivial.

@icbaker Ian, do you have any guidance on whether this is worth adding and if so how it should be implemented? Thanks.

**Comment by icbaker** [comment]
I think we need the info Andrew has requested from the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/feature_request.md) in order to properly evaluate the feature request.

I'm not quite sure what "Australian subtitles" are in terms of precise specs (as Andrew asked) but there's mention of that phrase in the Freelancer link in https://github.com/google/ExoPlayer/issues/7220#issuecomment-621546539 - so is this referring to DVB Teletext subtitles? In that case, we can probably dupe this against that existing feature request.

Regarding using CCExtractor in the PR:
ExoPlayer currently doesn't have a dependency on CCExtractor and we're generally very cautious about taking additional dependencies because they introduce additional maintenance burden. This is doubly true for dependencies with native code.

Additionally, we can only take dependencies in the core library if their license is the same as ExoPlayer's (Apache v2). CCExtractor is GPLv2 licensed, so if we used it then it would need to be depended on by an extension (see the [vp9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9) as an example).

That said, all our existing subtitle decoding logic is in Java. I suspect it's feasible to write this support in Java too, which would a) be consistent and b) in the core library without needing an extension. This would be strongly preferable to using CCExtractor. I think we're unlikely to accept a PR that implements this using CCExtractor when we weigh up the maintenance cost we'd be introducing against the benefits it brings.

You are of course free to make & maintain your own extension that isn't pushed back to ExoPlayer, and users can get the functionality by depending on both your extension & core ExoPlayer. This would allow you to depend on CCExtractor without needing to convince us of anything.

**Comment by MrtDolphin0128** [comment]
Can you just allow me to my code in a new branch of your repository?
I would be happy if my code can used for other dev guys who are interested in ExoPlayer.

**Comment by icbaker** [comment]
> Can you just allow me to my code in a new branch of your repository?
> I would be happy if my code can used for other dev guys who are interested in ExoPlayer.

No, we can't allow you to push un-reviewed code to a branch of the google/ExoPlayer repository.

Others can already use your code from the existing fork you've made: https://github.com/MrtDolphin0128/ExoPlayer/tree/AusSubtitle

The downside of this is that, since you've forked then customised the whole of ExoPlayer, anyone depending on this will only get updates to ExoPlayer when you pull them in. This is why I suggested building & maintaining an extension in your own repo instead if you want to keep the code in its current form with the CCExtractor dependency - that way people will be able to depend on ExoPlayer from us and australian subtitle support from you.

We will accept a high quality pull request that implements DVB teletext subtitle support in pure java without additional/native dependencies. If that's impossible for some reason it would be interesting to understand why DVB teletext subtitles are different to all the existing subtitle formats we support. Based on that discussion we can revisit the discussion and consider accepting a PR for a DVB teletext extension that requires native/external dependencies.

**Comment by icbaker** [comment]
If you're able to confirm that this feature request is the same as DVB Teletext Subtitles then I can dupe this against https://github.com/google/ExoPlayer/issues/7220.

If not, please provide all the information we keep asking for to explain what "Australian subtitles" are, including links to specs/standards where appropriate.

**Comment by MrtDolphin0128** [comment]
The following tickets are Related:

Open Enhancement: https://github.com/google/ExoPlayer/issues/5491 Support for DVB EBU Teletext subtitles
Open Enhancement: https://github.com/google/ExoPlayer/issues/7746 Australian Subtitle is not showing for livestream
Open: https://github.com/google/ExoPlayer/pull/7749 Aus subtitle
Closed: https://github.com/google/ExoPlayer/issues/7662 I can't play files from google drive on Exoplayer
Closed: Duplicate: https://github.com/google/ExoPlayer/issues/7220 Add support for DVB EBU Teletext
Closed: https://github.com/google/ExoPlayer/issues/7747 Need help about pushing my code to repository
Closed: https://github.com/google/ExoPlayer/issues/7677 How to show subtitle without url on Exoplayer
Closed: https://github.com/google/ExoPlayer/issues/6642 Teletext

### Use case description

Exoplayer does not support EBU subtitles.
This enhancement is to provide EBU Teletext subtitles for Australia and New Zealand (and probably other countries)
This is vital as Exo is being developed into IPTV systems for aged care and hospitality, and is of course a legal requirement in some jurisdictions.

### Proposed solution

As the Exoplayer does not support EBU Teletext closed caption / subtitle decoding. This enhancement to the Exoplayer library provides this functionality. The specifications of EBU teletext are located https://github.com/google/ExoPlayer/issues/7220

In Australia, most subtitles are provided word by word building up the lines.
The subtitles are positioned in the lower left of the screen to accommodate multiple lines.

As some conversion is taking place from the incoming teletext stream, to display using the existing Exoplayer teletext functionality, some aspects of the original stream may not be honored such as foreground and background colour and text position.

The library calls upon an external dependency, CCExtractor https://github.com/CCExtractor/ccextractor , per the advise by @icpaker.

### No alternatives are available at this time.

**Comment by icbaker** [comment]
Thanks for confirming this is the same functionality covered #7220 - I'll mark this one as a duplicate since that one is older and contains more technical info/details.

I've also added a comment to your PR, I suggest we keep any implementation-specific discussion (including whether to use CCExtractor) on the PR thread to avoid spamming #7220.

**Comment by MrtDolphin0128** [comment]
ExoPlayer supports almost all subtitles in the world but Australian Subtitles are not supported now.
So I  customized the ExoPlayer to support Australian Subtitles.

1. Introduction about CCExtrator

CCExtrator is a tool used to extract subtitles for TV recording videos.
https://github.com/CCExtractor/ccextractor
The core functionality is written in C.
And also CCExtrator can extract subtitles for the all videos which recorded from Australian TV channels.

2. Making .so file using CCExtrator and Java library class for using .so file

CCExtrator is a windows tool so I converted full source code of CCExtrator to JNI code for Android development.
Australian TV channels process transport streams in units of 188-byte size packet.
And with almost every packet, there is another packet called “PES Packet”.
You can get subtitles through these PES packets.


PES Packet   Field | Field Setting
-- | --
stream_id | Set to ‘1011 1101’ indicating “private stream 1”.
PES_packet_length | Set to a value that specifies the length of the PES packet, as defined in   ISO/IEC 13818-1.
data_alignment_indicator | Set to ‘1’ indicating that the subtitle segments are aligned with the PES   packets.
PTS of subtitle page | The presentation Time Stamp, indicating the time at which the   presentation begins of the display set carried by the PES packet(s) with this   PTS.
PES_packet_data_byte | The PES data field.

I made following Java functions that be using JNI functions:
- write function: Perform the function of passing the bytes of transport stream to the input memory of CCExtrator.
- run function: Perform the function of running the CCExtrator for getting subtitles in other thread.
- appendSubtitle function: Peform the function of passing the subtitles obtained through CCExtrator to Exoplayer.

3. Updating the ExoPlayer
I updated TsExtractor class(extractor.ts.TsExtractor)
In this class, byte data is passed to the Java library class (CceLibrary.java), which manages CCExtractor by each 10 packets (1880 bytes).
CCExtator returns the obtained subtitles as ssa format.
So it was necessary to update a Ssa subtitle part(text.ssa.*) and SingleSampleMediaPeriod class (source.SingleSampleMediaPeriod).
Each time the CCExtrator reads a piece of subtitle from input packets, CceLibrary class adds the obtained subtitle to a list of cues (saving the subtitles).

Finally my customized Exoplayer can support Australian Subtitles.

**Comment by MrtDolphin0128** [comment]
Hello.

I just want to pull my customized project for ExoPlayer to your Github project.
This is just a pull, and it won't affect your original ExoPlayer project.
Only a few developers who using the Australian channel and also interested in ExoPlayer will use my customized project.

WHY DON’T YOU ALLOW TO USE JNI CODE?

You are using JNI code like me too. A total of 5 modules in the extensions are projects organized to use JNI code professionally.

1. “av1” module in extensions.
Gav1Library Class configures and queries the native library (“gav1JNI”).
And also there are jni code and c source file and header file in jni folder now.

     

2. “ffmpeg” module in extenions.
FfmpegLibrary Class are using 4 native libraries(“avutil”, “swresample”, “avcodec”, “ffmpeg”). Right?
And also there is jni code file in jni folder too.

3. “flac” module in extensions.
FlacLibrary Class configures and queries the native library (“flacJNI”).
And also there are jni code files and c header files in jni folder too.

4. “opus” module in extensions.
OpusLibrary Class configures and queries the native library (“opusV2JNI”).
And also there are jni code file in jni folder too.

5. “vp9” module ject in extensions.
VpxLibrary Class in “vp9” are using two native libraries (“vpx” and “vpxV2JNI”) and there are jni code file in jni folder.


The 5 modules mentioned above use JNI, and I also want to pull my project that using JNI for ccextractor. And I just customized some functions and some structures of CCExtractor project but I didn’t copy and converted the whole project to so file.
If you want to get Australian Subtitles from live transport stream, you have to use CCExtractor’s engine and also as you know, c language, unlike Java language, has a new concept of “pointer”, so it’s very difficult to convert this itself to Java code.
![screenshot](https://user-images.githubusercontent.com/28615034/90866609-84943280-e3d7-11ea-9f58-7fb64fe2e5e4.jpg)

**Comment by icbaker** [comment]
>I just want to pull my customized project for ExoPlayer to your Github project.
This is just a pull, and it won't affect your original ExoPlayer project.
Only a few developers who using the Australian channel and also interested in ExoPlayer will use my customized project.

I don't understand this - your PR is against the dev-v2 branch where we actively develop ExoPlayer. If we accept your PR then your code will  be included in our 'original ExoPlayer project'. Note: This is **not** a suggestion to request a PR against a different branch. We **only** accept external PRs against dev-v2. All PRs we accept get included in the 'original ExoPlayer project', therefore they all have to meet all our requirements. PR #7749 currently does not meet these.

-------

>WHY DON’T YOU ALLOW TO USE JNI CODE?
>
>You are using JNI code like me too. A total of 5 modules in the extensions are projects organized to use JNI code professionally.

We do use JNI in some extensions. We don't use it from the core modules. JNI adds complexity to the build process - every app that (even transitively) depends on a JNI library has to handle that complexity.

When we use JNI we weigh up the complexity against the benefits the library brings, and the feasibility of implementing the same feature in pure Java. All the examples you gave are video/audio decoding libraries, which are both much more complex than subtitle decoding and more performance sensitive (because the data volumes involved are higher).

I explained how you could convince us a native implementation of this was necessary in the two options I posted [here](https://github.com/google/ExoPlayer/pull/7749#issuecomment-673939507):
>To reiterate my statement from #7746 (comment), we will accept:
>
>1. A high quality PR implementing this support in pure Java, with no external dependencies. Or,
> 2. A clear, reasoned argument with plenty of technical detail that convinces us a pure Java implementation for this is impossible, and a high quality PR adding an extension to support this using native dependencies (see the vp9 extension as an example).
>    * Note: It's going to be challenging to convince us of this, since we already have pure Java support for what I believe are very similar subtitle formats embedded in MPEG transport streams (e.g. CEA-608).

This is not "a clear, reasoned argument with plenty of technical detail":

>If you want to get Australian Subtitles from live transport stream, you have to use CCExtractor’s engine and also as you know, c language, unlike Java language, has a new concept of “pointer”, so it’s very difficult to convert this itself to Java code.

I remain unconvinced that a pure Java implementation of DVB Teletext subtitle support is impossible.

----

I'm going to close the PR as we're not going to accept it in its current form. Please re-open (or file a new one) with an approach that follows either of my two suggestions (quoted above).
