### ISSUE TITLE
Can't play specific stream

### ISSUE THREAD

**Issue by Nelsun** [google/ExoPlayer#7756]
Hi guys.

Have issue with this stream http://iptvenc5ks.tep.ch:8060/hls/18/18.m3u8
I hope it's not geo-blicked.
Have access to more than 400 streams, but have this issue on two of them only.

The tests are with 
    releaseVersion = '2.11.7'
    releaseVersionCode = 2011007

Stream can't start becase TsExtractor didn't consume the data from PmtReader, becase PAT segments are comming too often .. or not in right place. 
Found that in SectionReader line 117 > "if (bytesRead == totalSectionLength ) " bytesRead is always under totalSectionLength .
Then found that inTsExtractor.PatReader around line 487 (have logs in the file) "tsPayloadReaders.put(pid, new SectionReader(new PmtReader(pid));" overrides nonfinished SectionReader for the current PID. 
As workaround did check for that pid and if exists keep old SectionReader in tsPayloadReaders.

Where is the bug ? Is this proper way to be fixed or to say to our stream provider to fix the stream ?

Thanks in advance.

**Comment by AquilesCanta** [comment]
I think the media is malformed. From the [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.2):

```
The Media Initialization Section of an MPEG-2 Transport Stream
Segment is a Program Association Table (PAT) followed by a Program
Map Table (PMT). [...] The first two
Transport Stream packets in a Segment without an EXT-X-MAP tag SHOULD
be a PAT and a PMT.
```
That being said I don't really know why we don't remove the PAT reader after reading a PAT specifically in HLS. I suspect it's related to robustness so I'm not sure it's safe to remove. I'll put in place a check in order to avoid overwriting an existing PMT reader.

**Comment by Nelsun** [comment]
Thanks all
