### ISSUE TITLE
PLAY ENCRYPTED HLS STREAM

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#7765]
I am trying to play encrypted HLS stream and i am getting key url and IV in manifest but i want to use another key for decryption which i will provide to the player via code. I am using AesCipher class for providing the key and creating a data source but i am unable to integrate this data source with HLSDataSourceFactory and play the stream successfully.
HLSdatasource is not taking aes cipher data source as input. Can anybody help in this

**Comment by marcbaechinger** [comment]
@AquilesCanta Do you mind looking into this issue please?

**Comment by AquilesCanta** [comment]
Hi @anandsingh2903, it's impossible for me to assist you with the given information. If you want us to help we will need to provide specific details of what you are expecting to happen, and what you are observing. I would advise not to paste a great amount of code here since we are rarely able to tell anything from the provided code. We need a precise description of what the problem is, and what solutions you have attempted.

Before you provide more information, though, please have a look around in the issue tracker, since this is a topic that has been asked about on multiple occasions. For instance, check out #5362. Do have a look around [existing issues](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+hls+encrypted+datasource).

**Comment by anandsingh2903** [comment]
Hi @AquilesCanta , I have already gone through those issue trackers but they weren't of much help that's why i had to raise a new one. Let me tell you about the problem in detail :

I have playlist.m3u8 hosted which already contains info of AES key like Key URL and IV and all the stream TS files have been encrypted with that a key already. Now normally exoplayer already reads playlist.m3u8 and reads EXT-KEY tag for the key info, hits the key url in order to fetch the key and uses it to decrypt the stream and play it on the player but i want to implement a way where exoplayer doesn't use that key info it is fetching from playlist.m3u8 instead i provide it the key via some parameter or class if it exists and it uses that key provided by me externally to decrypt the Stream. I don't know whether this is possible to implement or not, so you will have to help me out in clearing this doubt.

**Comment by AquilesCanta** [comment]
This looks a lot like #6181.

**Comment by anandsingh2903** [comment]
Yes, i am trying to achieve the same thing. But i am unable to understand how to implement this custom playlist parse, couldn't find any documentation or tutorial on it.

**Comment by AquilesCanta** [comment]
I think that what I'd do if I were you would be wrapping [HlsPlaylistParser](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistParser) using an implementation that, given a media playlist, replaces the [`fullSegmentEncryptionKeyUri`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/playlist/HlsMediaPlaylist.Segment.html#fullSegmentEncryptionKeyUri) and [`encryptionIV`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/playlist/HlsMediaPlaylist.Segment.html#encryptionIV) of the playlist's segments to be what you need them to be. Hope this helps!
