### ISSUE TITLE
No audio on multi-channel tracks on allwinner H6

### ISSUE THREAD

**Issue by prostaferesi** [google/ExoPlayer#7783]
### [REQUIRED] Issue description
Exo can't reproduce audio in some circumstances on allwinner H6 android box. It seems this chip can't handle multichannel audio track. I also used ffmpeg audio renderer in order to understand if it was just codec issue. With VLC or ijkplayer the audio has no problem

### [REQUIRED] Reproduction steps
Build exoplayer demo (with or withouth ffmpeg extension support) with the sample I provided below

### [REQUIRED] Link to test content
Here you can find a little video with the problem I described above
https://miscstuff01.z6.web.core.windows.net/bad.mp4

### [REQUIRED] A full bug report captured from the device
logcat says something like
2020-08-19 17:12:28.006 1897-9719/? W/AudioFlinger: pause because of UNDERRUN, framesReady = 1504,minFrames = 2048, mFormat = 0x1
2020-08-19 17:12:28.049 1897-9719/? I/chatty: uid=1041(audioserver) AudioOut_1D identical 1 line
2020-08-19 17:12:28.092 1897-9719/? W/AudioFlinger: pause because of UNDERRUN, framesReady = 1504,minFrames = 2048, mFormat = 0x1
2020-08-19 17:12:28.135 1897-9719/? W/AudioFlinger: pause because of UNDERRUN, framesReady = 1024,minFrames = 2048, mFormat = 0x1

But a complete bugreport has been sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.11.7 but tried also with dev-v2

### [REQUIRED] Device(s) and version(s) of Android being used
Android box T95 max with allwinner H6 soc
Android 9

**Comment by prostaferesi** [comment]
update:

If I enable passthrough in android sound menu, the audio is ok.
I tried also to downmix manually(creating a new file) with ffmpeg from 6 channels to 2, and audio is ok.
Is there any way to downmix to stereo when these kind of issues occur?

**Comment by andrewlewis** [comment]
From the emailed bug report, this is a 6 channel 48 kHz stream (in AAC format):

```
08-19 17:12:25.259 10124  9124  9124 D EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, channels=6, sample_rate=48000, language=it, supported=YES
```

I'm a bit puzzled that playback of the 6 channel stream isn't working, as support for downmixing is required in the Android 9 compatibility definition [here](https://source.android.com/compatibility/9/android-9-cdd#5_5_1_raw_audio_playback). I think this should be reported to the device OEM as a bug in their implementation.

ExoPlayer does not have an audio mixer (we rely on the platform), but here are some options for workarounds:
- If you are happy with a low quality solution that just discards channels you could fork `ChannelMappingAudioProcessor`, configure it to discard all but stereo channels and add that to the audio sink's audio processor chain (see also #7666).
- Similarly, you could investigate writing your downmixing audio processor based on ChannelMappingAudioProcessor (it could take a weighted combination of the 5.1 channels to produce stereo left/right).
- You could fork the ffmpeg extension and configure the resampler used internally in its JNI code to output two channels rather than the same number of channels as the input.
