### ISSUE TITLE
Is there a way to know if the downloaded files have been deleted? 

### ISSUE THREAD

**Issue by luiscurini** [google/ExoPlayer#7785]
Hi, 

We're using exoplayer for downloads but now we'd like to now if there's a way to check if the files downloaded for a specific video url are still present. This will allow us to show a warning that some files were deleted and allow the user to redownload or to delete the download and change the amount of space used by the download.  I tried to look in the documentation, stackoverflow and the issues here but I didn't find an answer to this.

Thanks

**Comment by marcbaechinger** [comment]
You can [query the `DownloadIndex`](https://exoplayer.dev/downloading-media.html#querying-downloads) for a given download by the id you defined for the `DownloadRequest`. If you are using a custom id, you should know what the id is, if you are not using a custom id, the default is just the video url. You can get the `DownloadIndex` from the `DownloadManager` you are using.

```
@Nullable Download download = downloadManager.getDownloadIndex().getDownload(id);
if (download != null) {
  switch (download.state) {
    case Download.STATE_COMPLETED:
      // completely downloaded
      break;
    case Download.STATE_DOWNLOADING:
      // available after downloading
      break;
    case Download.STATE_QUEUED:
      // available after downloading
      break;
    case Download.STATE_FAILED:
      // ...
      break;
    // see further states you may be interested in Download.STATE_XYZ
  }
} else {
  // the given id is not in the index and hence the file is not downloaded
}
```

Alternatively you can get all downloads available at once with `DownloadIndex.getDownloads()`.

Please also look into the `DownloadTracker` which is part of the demo application. You will find the method [`loadDownloads`](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L113) and [`isDownloaded`](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L83) interesting:

```
private void loadDownloads() {
    try (DownloadCursor loadedDownloads = downloadIndex.getDownloads()) {
      while (loadedDownloads.moveToNext()) {
        Download download = loadedDownloads.getDownload();
        downloads.put(download.request.uri, download);
      }
    } catch (IOException e) {
      Log.w(TAG, "Failed to query downloads", e);
    }
  }

public boolean isDownloaded(Uri uri) {
  Download download = downloads.get(uri);
  return download != null && download.state != Download.STATE_FAILED;
}
```

**Comment by luiscurini** [comment]
Yeah but with this I would only get the status of the download. But for example if the download was completed, the user removes some .exo files for an specific video using a file manager. Is there a way to know about this?

**Comment by marcbaechinger** [comment]
When you download media with the `DownloadManager` you can specify a `Cache` which is probably a `SimpleCache` instance for which you can define a directory where the files are stored. If you avoid using a directory like `context. getExternalCacheDir()` or `context. getCacheDir()`, it's unlikely that a user accidentally deletes the .exo files you've downloaded with the API.

If it's about the case you are mentioning, when a user deliberately uses a file manager to delete .exo files, things get complicated. I'm not sure whether the API the 'Cache' interface gives you would help. But I think that's beyond of what we can support you here on the issue tracker I'm afraid. I even don't know if that's reliably possible at all because I'm pretty sure that downloading/caching has not been built with having in mind users are going to delete files manually underneath the API.

**Comment by luiscurini** [comment]
Exactly, we're using `SimpleCache` with `getExternalFilesDirs`. 

I though the same thing, the user shouldn't really delete these files. But I just wanted to know if maybe there was an option to check whether all the .exo files for a download were still available. 

Thanks you!

**Comment by marcbaechinger** [comment]
Ok, cool! I'm closing this issue. Please reopen if you want something to add.
