### ISSUE TITLE
Can we force to widevine level to L3 even for devices which are having L1 as well?(only if the key is L3)

### ISSUE THREAD

**Issue by PratimMallick** [google/ExoPlayer#7790]
### [REQUIRED] Question
There are lot of devices which is L1 widevine security level. While playing contents encrypted with L3 keys, exoplayer choses to use L1 because that is the more preferred way of decrypting the content - since its h/w based.
But we have seen that there are certain issues like - `Failed to restore key`,  `Failed to get Key Request`, `Failed to handle provision response`, `DRM vendor-defined error` - happen on specific devices.  These are the errors from native drm module. No matter what is done by the user like reinstalling app, restarting of device does not help. We tried to fix this by forcing to L3 security level on these devices and it looks to have solved these errors.

The question here is, **Is it recommended to force L3 widevine decryption on a device which has L1 as well while de-crypting using L3 keys?**

This issue is faced by 4-5k users on our platform on a daily basis

### A full bug report captured from the device
Havent been able to get bug report as these issues have come to our users. I do have some logs captured from their device. I can upload that if it helps you.

### Link to test content
This issue happens while regular playback or offline playback of L3 encrypted contents on devices such as 👍 
Xiaomi Redmi Note 8 Pro, Samsung Galaxy J8, Vivo Y51L, Samsung Galaxy Note 3 Neo, Samsung Galaxy A50 and a lot more.  Please note that the issue is not present on all devices of the same model

**Comment by marcbaechinger** [comment]
In general I would use L1 for the reasons you have given above. Whether you can fallback to L3 for devices which do not work with L1, is a decision that depends on whether this is ok for the content owner. I can't give you a general recommendation.

I would indeed force only on a per device model basis. Probably it is only needed for certain formats/codecs on a given device, if you care about having as much L1 coverage as possible. In cases for that not all devices of the model are affected, you probably need to distinguish by OS version as well or by similar more fine-grained properties of a device. 

As an aside: The [`MediaCodecUtil`](https://github.com/google/ExoPlayer/blob/r2.11.4/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java) has somes useful methods to get codec info for a given device. It may be helpful to take some decisions based on that information. Looking into the source code of `MediaCodecUtil` can probably be useful in general, when coping with the problems you are describing. You may know that already though.

This snipped below forces L3 for all devices for the ExoPlayer demo app by adding a property [when creating the DrmSessionManager](https://github.com/google/ExoPlayer/blob/r2.11.4/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L493):

```
drmSessionManager =
    new DefaultDrmSessionManager.Builder()
        .setUuidAndExoMediaDrmProvider(drmInfo.drmScheme,
            uuid -> {
              try {
                FrameworkMediaDrm mediaDrm = FrameworkMediaDrm.newInstance(uuid);
                // Force L3.
                mediaDrm.setPropertyString("securityLevel", "L3");
                return mediaDrm;
              } catch (UnsupportedDrmException e) {
                return new DummyExoMediaDrm<>();
              }
            })
        .setMultiSession(drmInfo.drmMultiSession)
        .build(mediaDrmCallback);
```

**Comment by ojw28** [comment]
Although closely related, it's important to decouple to license policy (i.e., the rules and required protection levels required for playback, which may be specified by the content provider) from the actual Widevine CDM implementation:

* If your license policy requires a level of protection that only a L1 Widevine CDM implementation will support, then obviously you need to use a L1 Widevine CDM implementation, else playback will fail.
* If your license policy is supported by both L1 and L3 Widevine CDM implementations, then you can choose to use either when both are available. Since you're able to successfully use the L3 Widevine CDM to play your content, I assume this must be the case here. There isn't really a security reason for not using the L3 implementation in this case, since by definition it meets the requirements specified by the policy. There may be some performance implications of selecting one implementation or the other. Since L1 implementations vary between devices, the performance implications of selecting one or the other may also vary between devices, which makes it hard to provide guidance.

Ultimately, if you only need an L3 implementation and if it's performing well for your use case, there's no particular reason why you shouldn't force it by default. There are definitely some apps that do this. There are other apps that force L3 by default and maintain an explicit list of approved devices on which L1 is enabled (although this is normally to enable higher quality content for these devices, for which the license policy requires a level of protection that only a L1 Widevine CDM implementation will support). There are other apps that use L1 by default and maintain an explicit list of devices that are forced down to L3 instead. All of these models can work, so it's really up to you which is best for your exact use case!
