### ISSUE TITLE
Handle invalid stream URI

### ISSUE THREAD

**Issue by xeinebiu** [google/ExoPlayer#7792]
### [REQUIRED] Searched documentation and issues
**Stackoverflow**

### [REQUIRED] Question
Given a list of URI's which points to same video but different hosts and qualities, if 1 URI points to a video which may be have been deleted, EXO Player will break and only show black screen and **currentMappedTrackInfo** returns null.

I would like someone to help because I find to understand very hard the technical stuff in EXO Player.
I need some kind of TrackSelector which can jump to another URI if current one is not valid.

Thank you.

**Comment by marcbaechinger** [comment]
> Given a list of URI's which points to same video but different hosts and qualities,

Can you give some more details about what you are doing? Like are you using an adaptive media source (HLS, Dash)? How do you prepare the player? A code sample can help as well if you are new to the terminology. This way we have a better idea of what you are trying to achieve and how.

**Comment by xeinebiu** [comment]
> > Given a list of URI's which points to same video but different hosts and qualities,
> 
> Can you give some more details about what you are doing? Like are you using an adaptive media source (HLS, Dash)? How do you prepare the player? A code sample can help as well if you are new to the terminology. This way we have a better idea of what you are trying to achieve and how.

Thanks for trying to help @marcbaechinger 

I am using the "**_DefaultTrackSelector(context)_**" and I prepare a list of URI`s to EXO which all of these URI`s are the same VIDEO, except that they are from different servers.

1. **Uri A** -> server.com/video.mp4
2. **Uri B** -> server.de/video_de.mp4
3. **Uri C** -> server.uk/video_uk.m3u8
4. More Uri's

If one of these URI returns an error instead of video data, the exo player shows only the duration of the video but never starts. After 1-2 minutes it will throw **_onPlayerError_** an exception "503 Server Error" because **URI B** failed.

What I would like to happen instead is the failed URI or Media Stream to be ignored instead to crash the playback.

Below is the method which loads given list of URI's.

```
    private fun initExoPlayer() {
            playerTrackSelector.parameters = playerTrackSelector.parameters.buildUpon()
                .setMaxVideoSize(defaultQuality.width + 1, defaultQuality.height + 1)
                .build()
        
        player = SimpleExoPlayer.Builder(requireContext())
            .setTrackSelector(playerTrackSelector)
            .build()

        playerView.player = player
        playerView.keepScreenOn = true
    }
private fun play(videos: Array<Uri>) {
        val dataSourceFactory = DefaultDataSourceFactory(context, "Exo Player")
        val progressiveFactory = ProgressiveMediaSource.Factory(dataSourceFactory)
        val hlsFactory = HlsMediaSource.Factory(dataSourceFactory)
        val sources = ArrayList<MediaSource>()
        videos.forEach {
            if (it.toString().endsWith(".m3u8")) {
                sources.add(hlsFactory.createMediaSource(it))
            } else
                sources.add(progressiveFactory.createMediaSource(it))
        }     
// p = EXO Player
        p.prepare(MergingMediaSource(*sources.toTypedArray()))
        p.playWhenReady = true
    }
```

**Comment by marcbaechinger** [comment]
I think there are some difficulties involved with that approach. I wonder whether it makes sense to just use a single media source to prepare the player and then, when you hit an exception you can just prepare again with a fallback uri and a new media source.

The approach with the `MergingMediaSource` involves that all of the available child media sources are going to be prepared at preparation. Without preparing the player doesn't know what tracks are available in the streams, so your track selector will never be able to select something because the tracks are not known before preparation completed. So if one of these fail, you get the load error which then gives you the playback error you are seeing. On the other hand, if all of these media sources work fine, you never want to switch a track and the duplicate download of the redundant stream is in vain and makes it inefficient.

Another gotcha would be that you need to make sure that you do not select a video track of one and an audio track of another stream. Progressive streams like mp4 do have audio and video data muxed together. So if you only want to use the audio stream, all the video data needs to be downloaded as well. This again would cause the double amount of data being downloaded.

As I said in the  beginning. An easy approach is just to re-prepare when a playback error is reported. This is a sample snippet which does that. You'll need to sanitize and probably adapt that but it shows the approach.

```
    Uri initialUri = Uri.parse("https://html5demos.com/assets/dizzy_gives_a_404.mp4");
    ProgressiveMediaSource.Factory factory = new ProgressiveMediaSource.Factory(dataSourceFactory);
    player.addListener(new Player.EventListener() {
      @Override
      public void onPlayerError(ExoPlaybackException error) {
        Log.e("playback error", "re-prepare with another stream");
        Throwable cause = error.getCause();
        if (cause instanceof DefaultHttpDataSource.HttpDataSourceException) {
          Uri failedUri = ((DefaultHttpDataSource.HttpDataSourceException)cause).dataSpec.uri;
          if (failedUri.equals(initialUri)) {
            ProgressiveMediaSource mediaSource = factory
                .createMediaSource(MediaItem.fromUri("https://html5demos.com/assets/dizzy.mp4"));
            player.setMediaSource(mediaSource);
            player.prepare();
          }
        }
      }
    });
    ProgressiveMediaSource mediaSource = factory
        .setLoadErrorHandlingPolicy(
            new DefaultLoadErrorHandlingPolicy(/* minimumLoadableRetryCount */ 0))
        .createMediaSource( MediaItem.fromUri(initialUri));

    player.setMediaSource(mediaSource);
    player.prepare();
```



There is an option of crafting a single HLS stream with a playlist that contains all the alternative video stream. This way the tracks land in the same track group and you can define alternatives in the playlist. The playlist can then define alternatives to achieve something like a fallback. So if you are familiar with crafting HLS playlists, you may want to look into this. I can't give you much support on this I'm afraid.
