### ISSUE TITLE
How to detect the required output protections for playback with L1 widevine keys

### ISSUE THREAD

**Issue by PratimMallick** [google/ExoPlayer#7794]
### [REQUIRED] Question
Getting `CryptoException: Required output protections are not active` error on trying to play UHD contents using exo player. These contents are protected by widevine keys which needs `L1 security level`,  `HDCP_2.2` and `analog_output_disable = true`. Both these criterions are met in this android 4k streaming box running on Android OS 9.0. I have been able to check both the security level and HDCP level via `securityLevel` and `hdcpLevel` property strings of Widevine object and they are proper.

Please suggest what could be the issue? Could this be due to the presence of analog audio output port? How does exoplayer/Android check for the value of `analog_output_disable` or corresponding flag to check if analog video output is present or not on a device?

### A full bug report captured from the device
https://drive.google.com/file/d/1ICLvOmbgkE6ydhNj4blaXLT9DBzJw_65/view?usp=sharing

**Comment by AquilesCanta** [comment]
Something I'm noticing in the bugreport is the following line:

`Renderer error: index=0, type=video, format=Format(video/hvc1/2, null, null, video/hevc, hvc1.2.4.L90.90, 919689, null, [854, 480, 23.976025], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM`

which is rather suspicious because we shouldn't be trying to play the video track if DRM is unsupported. 

> Please suggest what could be the issue? Could this be due to the presence of analog audio output port

You can try disabling the audio track to rule this out. Also, considering the error shown above, I'm inclined to think this is related to video.

Would you kindly obtain and share with us a bugreport after playing your stream in the demo app?

**Comment by ojw28** [comment]
> Something I'm noticing in the bugreport is the following line:
> `Renderer error: index=0, type=video, format=Format(video/hvc1/2, null, null, video/hevc, hvc1.2.4.L90.90, 919689, null, [854, 480, 23.976025], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM`
> which is rather suspicious because we shouldn't be trying to play the video track if DRM is unsupported.

There was a bug where `rendererSupport=NO_UNSUPPORTED_DRM` was spuriously printed whenever playback of any DRM protected stream failed due to `CryptoException`. It will be fixed in 2.12 (the commit that fixed it is https://github.com/google/ExoPlayer/commit/283bed8cb2013be239a3ee9bed0fb2f3f5d2f8cb). So you should probably just disregard this.

**Comment by PratimMallick** [comment]
@AquilesCanta Please find the bugreport from exoplayer sample app

https://drive.google.com/file/d/1z_S8di8pT_7_NhW0aK7nuRWylgz1k12M/view?usp=sharing

Would you be able to tell how to detect if `analog_output` is present or not in the device from app?

**Comment by AquilesCanta** [comment]
Some useful information is available in #4825. I suggest you take a look at the [key status callbacks](https://developer.android.com/reference/android/media/MediaDrm.KeyStatus) to see if you can find any useful info on the usability of keys. Specifically [STATUS_OUTPUT_NOT_ALLOWED](https://developer.android.com/reference/android/media/MediaDrm.KeyStatus#STATUS_OUTPUT_NOT_ALLOWED) looks relevant. I don't think information about the device will be enough to define whether a given piece of content will be supported or not. You will need to query license info for that, which define the content's playback constraints.

Please let me know if you manage to make any progress, or if you have any further questions.

**Comment by PratimMallick** [comment]
The key status callbacks could be used only when the playback starts right? I need to know this. information before hand, so that if the device doesnot meet required output protection level(`L1 widevine,  HDCP 2.2 and analog_disable_output` in our case) , we would serve non HD content to such devices.

I am able to get info about widevine security level and HDCP level, but not able to get if `analog_disable_output` is 0 or 1. Any way to get that?

**Comment by AquilesCanta** [comment]
When you say "serve non HD ..." you mean to the user, is that correct (not a server-side decision)? In other words, your manifest has both HD and non-HD content, and you can render the non-HD one when output constraints are not met for HD. If my interpretation is correct, then you should track #4825, which tracks enhancing ExoPlayer by preventing it from adapting to qualities where DRM constraints are not met. If my understanding is not correct, please clarify.

That being said, I am not aware of a way of checking whether secure output path requirements are met before loading the keys. I have sent a question to @rrfrias, who may be able to provide some insight. In the meantime, I can think of a few options but I will explain the more complex one so perhaps a variation suits your usecase:

1. You use a custom [track selection factory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelection.Factory.html) which by default doesn't select HD tracks that require secure output path.
2. You start playback.
3. You should now be able to side-load the HD keys and check their status. If status is ok, you can signal to your created track selections that it's now ok to select HD tracks.
4. If the bitrate allows, the player should seamlessly transition to HD content.

I'm sure we can come up with simpler solutions, because this one requires some customization in both track selection and DRM sides.

**Comment by PratimMallick** [comment]
Thanks @AquilesCanta for the solution. Would wait for @rrfrias to get back if there is any other way to know this, as we would like to show a logo based on this to the user on a page which is before the playback

**Comment by AquilesCanta** [comment]
We have filed a bug for adding a relevant feature in the Android platform [Internal ref: b/168322023]. Note that this will be usable only on newer Android versions.

I think your use case is reasonable and I'll try to think of a workaround which works on earlier Android versions. I'm thinking of something like a locally hosted license response which we can feed to MediaDRM to check key status without waiting for a server roundtrip. I'll discuss with @rrfrias some more and post here if we reach any conclusion.

**Comment by SaurabhOfficial** [comment]
@AquilesCanta I see b/168322023 is an internal ref, is there some way to track it?

**Comment by dino-saurabh** [comment]
@AquilesCanta I see b/168322023 is an internal ref, will it be possible for us to track it?

**Comment by AquilesCanta** [comment]
b/168322023 has been fixed for a year now. I'll assigned to @icbaker who's the DRM expert on the ExoPlayer side.

**Comment by rrfrias** [comment]
168322023 was addressed in android 12. You can contact Widevine partner engineering https://www.widevine.com/contact for more information to query output protections supported by the device. This is however not available for earlier android releases. We probably need to have an internal conversation and see if there is anything we can do for earlier releases.

**Comment by icbaker** [comment]
Closing this as I don't think there's anything additional ExoPlayer can do here.
