### ISSUE TITLE
Disable HeadsUp Notifaication on High Priorty Notifications 

### ISSUE THREAD

**Issue by MostafaBalba** [google/ExoPlayer#7806]
HeadsUp Notifaication  showsUP on High Priorty and high Priority set to Notifications and notification channel 
making the prioity default or low isn't convienient also the HeadsUp Notifaication isnot convienient for music streaming

**Comment by marcbaechinger** [comment]
According to the [documentation about notifications](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up), heads up notification are shown for important notifications. The importance level of a notification [is defined by the notification channel](https://developer.android.com/training/notify-user/channels#importance).

By default the `PlayerNotificationManager` creates a [notification channel with `IMPORTANCE_LOW`](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L455). From this I would expect that tthe `PlayerNotificationManager` by default does not create notifications with a heads up notification.

Can you give me some more details how you create your instance of the 'PlayerNotificationManager'? Are you using a `channelId` of a channel you created yourself? If this is the case can you review the importnace level of that channel?

**Comment by MostafaBalba** [comment]
I know , but i want to make the importance high without heads up notification, low and default doesnot show heads up but they push notification down in notifications list which is inconvenient

**Comment by marcbaechinger** [comment]
I think that is a platform behaviour we can not work around I'm afraid. 

The documentation says that a reason for showing a heads up notification is the following: `The notification channel has high importance on devices running Android 8.0 (API level 26) and higher.`

So if you give the notification channel a high importance the system creates a heads up notification. I don't think there is a way around this with high importance.  

On what API level do you see that the notification is pushed down? I'm asking because I think the ordering is probably a bit different for different API levels. If you do a notification with the `PlayerNotificationManager` (and optionally a `MediaSession`) the notification is a media style notification and  is placed prominently at the top in recent OS version even with the default importance which is low. 

![image](https://user-images.githubusercontent.com/584321/91450831-a3ca0e80-e874-11ea-8d57-bc15ceb37fd2.png)

**Comment by MostafaBalba** [comment]
I am testing on api 26 and i am attaching a media session to it but notification sometimes gets pushed down (not alot ) using default importance for channel and notification priority high , i am just trying to simulate soundcloud and spotify notification behaviour they are always on top

**Comment by MostafaBalba** [comment]
I found that spotify also gets pushed down on some cases so it depends on system

**Comment by marcbaechinger** [comment]
Thanks for the update. I close this issue. Please reopen if needed.
