### ISSUE TITLE
Exoplayer jumping of exo position when seek to some small seconds.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7822]
Hello,
I am developing an application where I am using exoplayer.I have some question regarding seek operation when I stream live in exoplayer.
First , when I get url for stream I get exo position and exo duration where exo duration is fix.where exo position is showing current play back time.Now when I seek suppose 10 sec back from live content in stream then exo position is some times seek to 10 sec back from current play back but the time showing there is some what jumps from like this if i get time 1:20 then i seek to 10 sec back then it shows 1:10 perfect but after some sec pass time is like 1:11,1:12,1:13,1:14 like this but again it goes back and set to 1:10 and where it loops like 1:10 , 1:09, 1:10 ,1:11,1:10,1:09 like this 
Can any one help me.

**Comment by ojw28** [comment]
The playback position is the position within the live window of media that the server is making available to the player. When you see the playback position jump backwards by 4 seconds, that's because the server has removed 4 seconds of media from the start of the live window. It's probably added 4 seconds of new content to the end of the live window at the same time, effectively shifting the live window 4 seconds ahead of where it was previously. You can read more about the timeline model used by ExoPlayer [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.html).

**Comment by ghost** [comment]
@ojw28 First of all thanks for your support.So as per this behaviour can we say that it's natural behaviour of HLS stream which we provide to exoplayer ? player has lots of capabilities to tackle with stream but as per server side implementation player behave like jumping from live window is it correct assumption ? just give me guidance about this.

**Comment by ojw28** [comment]
Yes, that sounds correct.
