### ISSUE TITLE
Android resource linking failed When Importing Exoplayer as CompileOnly in a Module

### ISSUE THREAD

**Issue by dgrdinh** [google/ExoPlayer#7826]
When building a module that imports exoplayer as compile-only we are getting an error:

Execution failed for task ‘:xxxxx:verifyReleaseResources'.
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
……..resource id/exo_play not found.

We are implementing ExoPlayer in a module that gets imported into an App.  The Module imports ExoPlayer using “compileOnly” like so:

compileOnly 'com.google.android.exoplayer:exoplayer-core:xx.xxx.xx’
compileOnly 'com.google.android.exoplayer:exoplayer-ui:xx.xxx.xx'
compileOnly 'com.google.android.exoplayer:exoplayer-hls:xx.xxx.xx'

The App then imports exoPlayer for us as “implementation” like so:

implementation "com.google.android.exoplayer:exoplayer-core:xx.xxx.xx”
implementation "com.google.android.exoplayer:exoplayer-ui:xx.xxx.xx"
implementation "com.google.android.exoplayer:exoplayer-hls:xx.xxx.xx"

The Module uses a Custom Controls layout that overrides “exo_play” like so:

```
<ImageButton
    android:id="@id/exo_play"
    android:layout_width=“xxxx”
    android:layout_height=“xxxx”
    android:scaleType="fitXY"
    android:src="@drawable/play_icon" />
```

We believe that because we are overriding the @id/exo_play in our module, the “verifyReleaseResources” task is checking to see if the value is defined in the values file.  Since since exoPlayer is imported as “compileOnly” this value is not defined at this point, but defined when the app is built.  Therefore, the error occurs because it cannot verify that the resource has been found.

**Comment by ojw28** [comment]
The documented use case for `compileOnly` is:

> allowing you to declare non-transitive dependencies used only at compilation time

I would assume that your module code uses ExoPlayer at runtime, in which case I don't think declaring it as a `compileOnly` dependency is really a valid thing to try and do. Could you explain what your use case is that's leading you to try this?

As above, I think what you're trying to do probably isn't valid. If it is valid, then I think this would be an Android tool chain issue, rather than an ExoPlayer issue.

**Comment by ojw28** [comment]
Looking at the Android specific documentation [here](https://developer.android.com/studio/build/dependencies), it says:

> Note: You can't use the compileOnly configuration with AAR dependencies.

The modules you're declaring `compileOnly` dependencies on are AARs, so I think it's probably not supported for that reason? The reason it fails is related to resources, whose inclusion is one of the things that differentiates AARs from JARs, so that's also consistent with this theory.
