### ISSUE TITLE
Seeking issue on mp3 files

### ISSUE THREAD

**Issue by zjamshidi** [google/ExoPlayer#7830]
Since my last issue (#7355) is closed, I'm opening a new issue. While we are waiting for the implementation on Release `2.12.0`, is there any workaround to make the seeking more accurate?

**Comment by ojw28** [comment]
It seems like the feature you need is part of `2.12.0`, so there's not really any way around that unless you want to (a) try and use the `dev-v2` branch rather than a stable release, or (b) try and back-port the changes yourself to whatever release you're using.

The good news is `2.12.0` is arriving very soon (tentatively targeted for this week), so you're probably best off just waiting.

**Comment by zjamshidi** [comment]
Thanks for your reply. I will wait for the release
