### ISSUE TITLE
4K H.264 AVC movie cannot be played by Exoplayer, but can play on MediaPlayer

### ISSUE THREAD

**Issue by josephusmv** [google/ExoPlayer#7835]
Hello, 

I am trying to play a H.264 4K movie using exoplayer, but the video decoding process seems failed. The AAC is play out fine, but AVC shows black screen.
I was suspect that the device not support this video profile so I tried it using MediaPlay, but on which the video plays fine.
Per my understanding, the Exoplayer is using the same lower level MediaCodec as MediaPlay. And it seems just a wrapping for the MediaPlayer. If MediaPlay could play it, it has no reason the device does not support. So it seems more likely the Exoplayer has done something caused this.

Attachment is the logs during playback.

Please help.
[Hisen4KAVC.log](https://github.com/google/ExoPlayer/files/5155275/Hisen4KAVC.log)

**Comment by christosts** [comment]
Can you please provide the information mentioned in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). We'd need a link to your test content, the device that this is occurring (including Android version), what version of ExoPlayer you are using, and a bug report.

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #7835".

**Comment by josephusmv** [comment]
[REQUIRED] Issue description
Playing 4K video on a customerized TV device.

[REQUIRED] Reproduction steps
Could only be reproduced on my customers device, which is a Android 4.4 embedded TV box.

[REQUIRED] Link to test content
Unrelated.

[REQUIRED] A full bug report captured from the device
Please see my original attachment.

[REQUIRED] Version of ExoPlayer being used
r2.11.7


[REQUIRED] Device(s) and version(s) of Android being used
My Customer's own TV device, and Android 4.4.

Addition:
I have tested with MediaPlayer, it could play the give 4K video

**Comment by christosts** [comment]
These issues are often specific to device and content, and in order for us to debug we need a sample of the failed content, details of the device (so we can test on a similar one if possible) and/or a [bug report](https://developer.android.com/studio/debug/bug-report) captured from the device (you have attached logs, but a bug report contains more information).

Please consider:
- sending us a sample of your H264 content
- a bug report when the issue happens so that we may locate any errors reported from the codec 

Also, can you clarify whether the issue happens with the ExoPlayer demo app (modified or not) or you app only?
