### ISSUE TITLE
How to hide the exoplayer status bar?

### ISSUE THREAD

**Issue by eservicetv** [google/ExoPlayer#7840]
hello my query is how can I hide status bar in exoplayer player.

**Comment by marcbaechinger** [comment]
May I ask you to look into our [Developer Guide page about UI components](https://exoplayer.dev/ui-components.html) to see whether this helps?

If it does not help can you give us some more info on what you mean with 'status bar'? With status bar peop[le commonly refer to the status bar of the phone rather than of ExoPlayer. Can you please give some more details in case the dev guide does not help?

**Comment by eservicetv** [comment]
I want exoplayer to fill the full screen

**Comment by marcbaechinger** [comment]
You need to make the `PlayerView` take the entire space of your activity and then make the activity full screen. There are different options for doing that which are [documented in an Android Developer Guide](https://developer.android.com/training/system-ui/immersive).
