### ISSUE TITLE
TTML Subtitles disappear too quickly when there is a new segment

### ISSUE THREAD

**Issue by cf256** [google/ExoPlayer#7844]
### Issue description
When watching a DASH stream with subtitles, the subtitles can disappear too quickly after a new segment loads. 

So lets say a stream has segmented subtitles and each segment is 1 minute. 

`<p begin="00:00:55.000" end="00:01:05.000" region="speaker">This subtitle should last for 10s, but is stopped after 5s</p>`

Next segment would be something like:

`<p begin="00:01:15.000" end="00:01:25.000" region="speaker">This subtitle should last for 10s, and does</p>`

The first subtitle would be cut off at the 60 second mark, while the second one would work fine.
The first `SubtitleOutBuffer` would have a timeUs of 0, and the next one would next would have a timeUs of 60000000 (60 second). 

This would result in the release of the previous cues.

This is caused by the `TextRenderer` calling `subtitle.release()`  when it shouldn't I think. 

So in this block of code.: 
```
if (nextSubtitle.isEndOfStream()) {
        if (!textRendererNeedsUpdate && getNextEventTime() == Long.MAX_VALUE) {
          if (decoderReplacementState == REPLACEMENT_STATE_WAIT_END_OF_STREAM) {
            replaceDecoder();
          } else {
            releaseBuffers();
            outputStreamEnded = true;
          }
        }
} else if (nextSubtitle.timeUs <= positionUs) {
        // Advance to the next subtitle. Sync the next event index and trigger an update.
        if (subtitle != null) {
          subtitle.release();
        }
        nextSubtitleEventIndex = nextSubtitle.getNextEventTimeIndex(positionUs);
        subtitle = nextSubtitle;
        this.nextSubtitle = null;
        textRendererNeedsUpdate = true;
      }
    }
```
The code below makes it work (but I'm sure there are better ways to deal with this) 
```
long nextEventTime = -1;
if (subtitle != null) {
    int nextEventTimeIndex = subtitle.getNextEventTimeIndex(positionUs);
    if (nextEventTimeIndex != INDEX_UNSET) {
        nextEventTime = subtitle.getEventTime(nextEventTimeIndex);
    }
}

if (nextSubtitle.isEndOfStream()) {
    if (!textRendererNeedsUpdate && getNextEventTime() == Long.MAX_VALUE) {
        if (decoderReplacementState == REPLACEMENT_STATE_WAIT_END_OF_STREAM) {
            replaceDecoder();
        } else {
            releaseBuffers();
            outputStreamEnded = true;
        }
    }
} else if (nextSubtitle.timeUs <= positionUs && positionUs > nextEventTime) {
    // Advance to the next subtitle. Sync the next event index and trigger an update.
    if (subtitle != null) {
        subtitle.release();
    }
    nextSubtitleEventIndex = nextSubtitle.getNextEventTimeIndex(positionUs);
    subtitle = nextSubtitle;
    this.nextSubtitle = null;
    textRendererNeedsUpdate = true;
    }
}
```

### Reproduction steps
We've been able to reproduce this in the Exoplayer Demo Application. 
1. Play an asset with subtitles that are split into segments.
2. observe that the subtitles disappear too quickly (i.e. it disappears before the person is done with the sentence) 
 
###  Link to test content
Will send a separate email with content to test on. 

### A full bug report captured from the device
[bugreport-sdk_google_atv_x86-PSR1.180720.121-2020-09-02-12-08-59.zip](https://github.com/google/ExoPlayer/files/5161601/bugreport-sdk_google_atv_x86-PSR1.180720.121-2020-09-02-12-08-59.zip)

### Version of ExoPlayer being used
Observed on dev-v2 and in the latest release 2.11.8. 

### Device(s) and version(s) of Android being used
Any device/TV/Mobile. 
Android versions 9 and 10 at least.

**Comment by nigelmegitt** [comment]
The reported behaviour looks correct, i.e. I do not believe it to be a bug.

If a subtitle occurs in more than one segment it needs to be duplicated in the subtitle document for each segment it appears in. This is because the DASH + MP4 rules for presenting subtitles limit the number of active subtitle documents to a maximum of 1; in the second segment, the new TTML document is active and the previous one is not active, so any content in the previous document that extends outside its segment's active interval must be truncated, as is being reported here.

In my view the correct resolution to the issue is to fix the upstream encoder + packager that is generating the subtitle segments.

**Comment by cf256** [comment]
Hi! Thanks for the reply. I'll check with our platform team. The reason I assumed it was an Exoplayer bug was that the subtitles appears to work in our other clients. iOS/Web etc.

**Comment by ojw28** [comment]
@nigelmegitt is correct. The easiest way to reason about why your current media is invalid is to consider what happens if the user seeks to 61s. The player will request the segment starting at 60s, however this segment does not contain the subtitle that should be displayed. In other words, seeking doesn't work unless segments are self-contained. There's some more detail in https://github.com/google/ExoPlayer/issues/7374#issuecomment-628726695.

**Comment by cf256** [comment]
Thanks for the explanation! We are following this up as a bug with the packager we use.
