### ISSUE TITLE
Does exoplayer has a feature like bitrate converter for streaming mp3 file

### ISSUE THREAD

**Issue by isuru18113** [google/ExoPlayer#7855]
This is not an issue and I just ask this question to clarify my doubt. I just want to know, If I have stored a 320kbps mp3 in firebase cloud storage, Can I let the users **choose** the **bitrate** of the song (Either 64kbps, 128kbps, or 320kpbs) via **exoplayer**? Or should I have to store 3 different bitrates mp3 files in storage and stream them?

**Comment by christosts** [comment]
What would be the purpose of choosing the bitrate? To download fewer bytes? ExoPlayer is a client-side library and can operate on content once the content arrives at the client device. If you want to change to bitrate of the hosted mp3 file in order to transfer less/more bytes, this needs to happen at the remote server, and that's outside ExoPlayer's functionalities.

For clarity, ExoPlayer has some audio processing facilities (for example look at [ResamplingAudioProcessor](https://github.com/google/ExoPlayer/blob/r2.11.8/library/core/src/main/java/com/google/android/exoplayer2/audio/ResamplingAudioProcessor.java)) that operate on the audio content once it is available on the device. I don't think this is for the use-case in question.

Closing this issue, feel free to re-open if the answer did not provide enough information.
