### ISSUE TITLE
Switch player view surface type

### ISSUE THREAD

**Issue by hinditutorpoint** [google/ExoPlayer#7863]
Hi sir how can switch playerview surface type programmatically dit not  find any setter method.
I want to like 
If(Build.VERSION.SDK_INT >= Build.VERSION_CODES_N){
//surface view
}else{
//Texture view
}

**Comment by hinditutorpoint** [comment]
Sir I am waiting

**Comment by kim-vde** [comment]
You cannot do that because. The SurfaceView is initialized in the PlayerView constructor and its reference cannot be changed.

Maybe if you provide more details about your problem we can try to figure out an alternative solution.

**Comment by hinditutorpoint** [comment]
As per your documention surface view better than texture view but you say that below n device not supported surface view that condition what be do

**Comment by kim-vde** [comment]
Where did you see that `SurfaceView` is not supported before N?

**Comment by ojw28** [comment]
I think this recommendation is documented [here](https://exoplayer.dev/ui-components.html#choosing-a-surface-type).

As noted above, there isn't a setter to change the `PlayerView` surface type from code. You should use the `surface_type` attribute of `PlayerView` in your layout xml. You can do this by putting one version of your layout in your `layout` directory, and another in your `layout-v24`. See [this page](https://developer.android.com/guide/topics/resources/providing-resources) for more details (search for "Platform Version (API level)" to find the right part of the page).

If you're building your own player UI rather than using `PlayerView`, then you can probably just inflate the surface you need directly in your own application code.

**Comment by hinditutorpoint** [comment]
Thanks sir
