### ISSUE TITLE
Arithmetic overflow when calculating sampleDecodingTime resulting in negative value

### ISSUE THREAD

**Issue by mikaelstaldal** [google/ExoPlayer#789]
When using dynamic DASH stream, the decodeTime is a very large value. I have seen e.g. 14419621440000000.

In com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.parseTrun() line 498 that large value is used in this calculation (cumulativeTime is derived from decodeTime):

     sampleDecodingTimeTable[i] = (cumulativeTime * 1000) / timescale;

This calculation can overflow and result in a negative sampleDecodingTime which prevents the player from starting playback further on.

This can be fixed by rearranging the calculation like this:

      sampleDecodingTimeTable[i] = (cumulativeTime / timescale) * 1000L;

**Comment by ojw28** [comment]
To clarify, is 14419621440000000 the sampleDecodingTimeTable value or the cumulativeTime value? What's the value of timescale in this case?

You can't change the calculation in that way without losing precision in some cases, although we do have a util method that attempts to "do the right thing" [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/util/Util.java#L407).

**Comment by mikaelstaldal** [comment]
14419621440000000 is the sampleDecodingTimeTable, but it doesn't really matter since cumulativeTime gets a value in the same range. Timescale is 1000000.

**Comment by ojw28** [comment]
I'm still slightly confused. So am I correct in saying that for the case you refer to there is no rollover issue? In which case I assume you're filing the issue because you're concerned that rollover may occur in some other cases.

Even if timestamps are set relative to the Epoch, it'll still be another 24 years before rollover does become an issue. So it doesn't seem worth worrying about?

**Comment by mikaelstaldal** [comment]
I just reproduced the issue again, with these values:
decodeTime=14422175220000000
cumulativeTime=14422175220000000 
timescale=10000000

I don't know what rollover mean in this context. I file this issue since playback doesn't work (get stuck in STATE_BUFFERING).

**Comment by ojw28** [comment]
Is this your stream or a stream provided by a third party? Rollover means the same as overflow in this context. Can you provide access to the stream itself?

I don't think those values are sensible, and so would speculate that there are issues with the actual stream itself. It appears they're out by a factor of 1000 from sensible values (decodeTime should have three fewer zeros or timescale should have three additional zeros).

**Comment by mikaelstaldal** [comment]
It is my stream (or rather a stream produced by another department in my company). Perhaps it contains odd timestamps. Unfortunately, we cannot easily provide access to it due to DRM and licensing issues.

My initial proposal:

    sampleDecodingTimeTable[i] = (cumulativeTime / timescale) * 1000L;

does not work properly, probably due to losing precision. But then I tried:

    sampleDecodingTimeTable[i] = Util.scaleLargeTimestamp(cumulativeTime, 1000, timescale);

and that solved my issue.

**Comment by ojw28** [comment]
Ignore my comment above about the values not being sensible. They are. The reason you're hitting this issue where other people aren't is simply because the timescale you're using is so large. You really don't need the level of precision that such a large timescale allows, and I would advise you to follow up with the team generating this content and suggest that they might like to change it. It will likely improve compatibility across different players by avoiding this kind of issue. For reference, YouTube's DASH streams use 90000 for video and the frequency for audio (e.g. 44100).

That said, we will make the change proposed above. Thanks!
