### ISSUE TITLE
Do you support F-Droid inclusion?

### ISSUE THREAD

**Issue by dpriskorn** [google/ExoPlayer#7897]

**Comment by ojw28** [comment]
It's somewhat unclear what your question is, since ExoPlayer is a library, not an application. We do provide some demo applications, but these are intended for developers rather than for end users.

ExoPlayer is distributed under the [Apache License 2.0](https://github.com/google/ExoPlayer/blob/release-v2/LICENSE), so you can use it in ways permitted under that license. We don't take any specific view on F-Droid.
