### ISSUE TITLE
Exo player notification get collapsed in locked screen when other notification appears

### ISSUE THREAD

**Issue by ravisaini1990** [google/ExoPlayer#7899]
I am using the Exo player notification manager to show the notification for my audio player app. Here I am facing an issue that when I am on the locked screen and other application notification also coming so the player  in notification get collapsed, the action button get hidden as you can see in the attached image. 

What I need -
I need Exo player notification manager to be in expanded form always with an action play/pause icon. I have given High priority to my player.

Actual -
When other notification comes player gets collapsed, as you can refer to the attached image.

Need the solution for it that the player always appears in the expanded form.

### A full bug report captured from the device
Sent on the email address dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.11.5

###  Device(s) and version(s) of Android being used
MI A3 and Android 10

Link : [Locked_collapsed_exo_notification](https://ibb.co/9c2Lxww)

**Comment by ravisaini1990** [comment]
[Collapsed_player](https://www.linkpicture.com/q/Exo.jpg)

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).


The same applies to https://github.com/google/ExoPlayer/issues/7824. If you have solved the problem in #7824 you can close the issue.

**Comment by ravisaini1990** [comment]
> Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).
> 
> The same applies to #7824. If you have solved the problem in #7824 you can close the issue.

I closed the previous ticket, kindly provide me the solution for this ticket @marcbaechinger

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

I really ask for that information, specifically for a [bug report](https://developer.android.com/studio/debug/bug-report), because I need that information. A notification is placed by the OS and hence it is required that I know what device and OS version you are using. All this information is in the bug report available for me. So please create that bug report and upload according to the issue template, so I can efficiently help you and avoid that we need to write back and forth several time until I have collected all the information.
