### ISSUE TITLE
Caching and Streaming HLS playlists at the same time. 

### ISSUE THREAD

**Issue by Roland-1** [google/ExoPlayer#7920]
### [REQUIRED] Searched documentation and issues
Read the documentation in your developer website, but failed to find sufficient information regarding by question, https://exoplayer.dev/doc/reference/  as some docs aren't up to date. 

### [REQUIRED] Question
Is it possible to simultaneously cache and stream HLS? I have just migrated from streaming .mp4 files to HLS and for mp4 i have used proxy cache server to cache videos on disk while watching, for faster playback when opening next time. Now i am trying to do the same for HLS but fail to find any way to do so.

**Comment by icbaker** [comment]
Are you asking for a way to do this within ExoPlayer, or using a separate process?

It sounds like your MP4 solution worked outside ExoPlayer:
> for mp4 i have used **proxy cache server** to cache videos on disk while watching

Setting up a cache server for HLS is certainly possible (that's basically how video streaming CDNs work), but it might not be as simple as for just MP4 files. That said, it doesn't sound like an ExoPlayer question so we can't really offer much more help with this - you're probably better off asking in a different forum e.g. Stack Overflow.

If I've misunderstood, and you are actually doing all this within ExoPlayer, maybe you could clarify in more detail what you had working with .mp4 files and how you'd like to recreate that for HLS.

**Comment by Roland-1** [comment]
Thanks for the response. Yes you got it right i was just passing local proxy uri to ExoPlayer for playback when using .mp4. I was wondering if i can achieve the same(simulations caching and playback) using ExoPlayer caching tools with HLS?

**Comment by icbaker** [comment]
Thanks for explaining - I'll pass this over to @marcbaechinger.

**Comment by marcbaechinger** [comment]
Unlike MP4 HLS is an adaptive stream. This means there are several qualities of video and/or audio streams defined in the manifest. The player then selects dynamically from these alternatives according to the estimated current bandwidth. 

So the challenge you are having is that the player may choose different variants when playing again. This would mean that a) the variant cached before is not used and b) you may cache another variant again in a second playback.

You could restrict playback to a single variant of video or audio but then you lose the adaptive behaviour which not really makes a point. :)

You would have the same problem with the proxy server approach BTW. 

Can you confirm my assumption that your HLS stream is actually adaptive in a sense that the playlist does declare multiple variants? (short: can you provide a sample stream so I can verify :)

Caching as a such is easy to [setup with ExoPlayer.](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network)

**Comment by Roland-1** [comment]
Yeah i can confirm that HLS stream is adaptive, BTW its .m3u8 playlist file.  The main point for using HLS is that i want to optimize the start-up time of video. As the video is segmented to smaller chunks i assume that the load times will be quicker than ordinary .mp4 when streaming from server.

**Comment by marcbaechinger** [comment]
Well, the segmentation in chunks alone doesn't make startup quicker. Even for mp4 ExoPlayer loads chunks by using HTTP range requests. But because the HLS chunks are available in qualities lower than the quality of the mp4, the startup is probably quicker, if the bandwidth of a user is not optimal (obviously I assume your HLS stream offers tracks in lower qualities than the mp4). 

Adaptive streams have further advantages over mp4 of course. Users with rather limited network speed (mobile network) will experience less re-buffering, because the player chooses a lower quality than the mp4 when bandwidth gets scarce.

With mp4, [pre-caching](https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6) as well as caching would be easier which is difficult for adaptive for the reasons above. ExoPlayer provides this with the `CacheMediaSource` without the need for a http proxy.

**Comment by Roland-1** [comment]
OK great, thank you for your help. I guess i'll continue using .mp4 and just do pre-caching.
