### ISSUE TITLE
Subtitle bottom padding broken on 2.12

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#7934]
I don't know if this is an intended change or if it is a bug. 
I updated from 2.11.8 to 2.12 and my subtitle bottom padding broke. I didn't actually have a value configured but I noticed with 2.12 the subtitles were all the way at the bottom. So I tried setting the padding using `videoView.subtitleView?.setBottomPaddingFraction(0.9f)` where `0.9f` is an exaggerated value to make sure it works, and it didn't make a difference. With 2.11.8 and `0.9f` the subtitles show up all the way at the top. 

I went back to 2.11.8 and verified everything. I'm attaching two pictures of the subtitles on 2.11.8 and 2.12. Same vtt file, same video file and no bottom padding configured, just defaults. 

2.11.8
![image](https://user-images.githubusercontent.com/1638377/93397525-663b1e80-f83f-11ea-979a-5be8b1da89d8.png)

2.12
![image](https://user-images.githubusercontent.com/1638377/93397537-6cc99600-f83f-11ea-8788-e262aad80908.png)

**Comment by icbaker** [comment]
This is actually working as intended - though I appreciate it might seem a bit strange.

Here's the reasoning/more technical detail:

`Cue` is a format-agnostic subtitle representation. The source data could be in many different formats, e.g. SubRip (.srt), TTML, WebVTT, CEA-608/708, etc.

Some of these formats either don't allow the vertical position to be specified or aren't clear what behaviour is expected when it's not specified (e.g. SubRip). In these cases we use `Cue#line == DIMEN_UNSET` to signify we don't really have any idea where the cue should be positioned vertically. `SubtitleView` has `bottomPaddingFraction` in order to provide a sensible default position in this case.

However, in the WebVTT case, the spec tells us exactly how to calculate the `line` value when it's not specified in the source file: https://www.w3.org/TR/webvtt1/#webvtt-cue-line-automatic. This is what changed in 2.12: We started respecting defaults specified by the WebVTT spec (specifically https://github.com/google/ExoPlayer/commit/b3f94e3768577abfa365fcea88cbd04f5f2a1827). Since there's no uncertainty, there's no need for the `Cue#DIMEN_UNSET` setting.

ExoPlayer considers the `webvtt` and `ui` packages completely distinct, the `SubtitleView` is just one possible implementation of the UI-visible `TextOutput`. The `Cue` object carries data between these packages, and each decoder is responsible for including as much info in this object as the relevant spec provides.

A couple of ideas/suggestions:
1. Specify a `line` value in your WebVTT source file
1. If that's impossible, e.g. you're displaying multiple simultaneous cues and relying on the auto-layout rule I linked above, then maybe:
    1. ExoPlayer could add a new property to `SubtitleView` which simply reduces the height of the subtitle viewport relative to the video viewport. However this would break any subtitles that had been carefully aligned with on-screen content using fractional line positioning, so I think it's very unlikely we'd add this.
    1. We could do the same as above, but only make it affect cues with `Cue#lineType == NUMBER`. I'm not very enthusiastic about adding more levers to `SubtitleView` though, it already has quite a confusing array of options imo. We could re-purpose `bottomPaddingFraction` to avoid adding a new lever, but that would be a subtle breaking change for all our developers so we can't do it.
    1. If you never want subtitles to appear at the bottom of the screen (i.e. `Cue#line = -1`), you could mutate the `Cue` objects before they get displayed and change the `line` value to something else. There's some instructions to do this in https://github.com/google/ExoPlayer/issues/7243#issuecomment-614651130.
    1. You could resize `SubtitleView` in your app's layout so that its bottom edge is offset above the bottom edge of the video viewport.
