### ISSUE TITLE
player getting stuck in mid of video

### ISSUE THREAD

**Issue by idragonpro** [google/ExoPlayer#7948]
Hi Team,
We need support for our existing exoplayer account.
We have been using your player for the last 3 years and faced no issues.
But now we have integrated IMASDK for In-stream ads and player is getting stuck in the middle of the video. 
And also there are many issues we are facing.
So, Plz contact us or forward this mail to the concerned department.
It is very difficult to find support for your company.
Thanks & RegardsAshwini

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by idragonpro** [comment]
Hi,

We need someone to talk on call

Can you plz share Exoplayer's contact details?

Thanks
Ashwini

**Comment by marcbaechinger** [comment]
Thanks for your patience! 

This is an open source project hosted on GitHub. The contact details you are having are correct in the sense that you can explain us your problem here by filing an issue according to the issue template (see below). Without information about what your problem is, we can not really help you some further I'm afraid. Please note, that we can not give you 1:1 support for helping you developing your solution. We are happy though to check whether the ExoPlayer library works correctly and, in case of us identifying a bug in our code, look into these problems at a best effort basis. 

So, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
