### ISSUE TITLE
Sealmessly switch the video tracks ASAP

### ISSUE THREAD

**Issue by changxiangzhong** [google/ExoPlayer#7969]
### [REQUIRED] Searched documentation and issues
 - ExoPlayer official document
 - ExoPlayer source code
 - Question  #6630

### [REQUIRED] Question
Our requirement is just like #6630, and we have tried and experimented the solution provided by @tonihei - to customize the `AdaptiveTrackSelection::canSelectFormat()` method - it's a great idea.

We have one additional demand - ASAP. The issue is it takes a while to see the image quality change after we notify the `AdaptiveTrackSelection` to change the criteria. Our assumption is it's the buffer. So the question is if there a method, that we can invalidate part of the buffer - we don't want to keep the track switch smooth, seamless and fast

Cheers.

**Comment by tonihei** [comment]
Glad you found the `canSelectFormat` method useful :) 

Just to provide some background: The player buffers media up to maximum configured value in `DefaultLoadControl` (which is 50 seconds by default). If you update your selection by changing the logic in `canSelectFormat`, it only applies to newly loaded media chunks. So for the user, the new decision won't be visible until all the previously loaded 50 seconds of media have been played. That's the effect you are seeing I think.

The `AdaptiveTrackSelecton` class also has a method called `evaluateQueueSize` that is called to figure out whether existing loaded chunks should be discarded. So, if you want to apply your change sooner, you can probably override this method too and return a low value for the first time it's called after you update your selection (and otherwise forward to the base class implementation). Note that this also means all the data needs to be loaded again and thus it incurs more network traffic and you have a higher chance of getting rebuffers.

**Comment by changxiangzhong** [comment]
@tonihei Thank you!

This the the change I've made.  
![image](https://user-images.githubusercontent.com/5352145/94186707-4f33a680-fea7-11ea-9454-41157caf0c46.png)

We found an interesting property `minDurationToRetainAfterDiscardMs`, It's comments is as following. We suspect it's the safe margin to keep the ABR smooth, i.e. avoid getting rebuffers. 
```
   * @param minDurationToRetainAfterDiscardMs When switching to a track of significantly higher
   *     quality, the selection may indicate that media already buffered at the lower quality can be
   *     discarded to speed up the switch. This is the minimum duration of media that must be
   *     retained at the lower quality.
```

With this solution, we are getting more ANR issues. But any comments would be appreciated.

**Comment by changxiangzhong** [comment]
@tonihei I've done a bit more experiment with this solution. In the `AdaptiveTrackSelecton::evaluateQueueSize()`, we tried also with **dump everything/return 0**. But still it takes up to  12 second(worst case) between triggering the event and seeing the image quality drop. We are using tunneling BTW. 

TBH, I'm not quite convinced with deploy this patch to real customer. Could you please evaluate the risk of this change? Can you please think about what kind of regression issues this can introduce?

**Comment by tonihei** [comment]
>  But still it takes up to 12 second(worst case) between triggering the event and seeing the image quality drop. We are using tunneling BTW.

Even if you specify 0, the player can't discard media chunks the decoders already read from. With tunnelling in particular, it may be that you are reading multiple seconds ahead. 

> TBH, I'm not quite convinced with deploy this patch to real customer. Could you please evaluate the risk of this change? Can you please think about what kind of regression issues this can introduce?

That's up to you what you'd like to deploy. The change in itself it probably working as expected, but whenever you discard data it means the user needs to reload this data in a new quality. This always increases the risk of new rebuffers and also increases the network usage for the user. So it really depends on our intended use case and what you think is most important for your app when making these decisions.

**Comment by changxiangzhong** [comment]
@tonihei Thanks again for your advice. We are developing stuff on STB boxes, so
- Don't care about the bandwidth that much
- Risk of re-buffering is acceptable from my point of view. **Video rendering thread** is taking way much resources. We need to find a way to reduce the CPU usage to react on user interactions.

BTW, some interesting figures to share with you - on our platform(derived from banff) `MediaCodecVideoRender::feedInputBuffer()` takes almost 3X time with DASH+Widevine than SS+Playready. 4.5ms VS 12 ms **in average**. In burst cases, SS could take up to 250 ms ~ 300 ms.

So we see the conclusion - dash is better.
