### ISSUE TITLE
Custom DataSource: initialization of MKV file takes too long 

### ISSUE THREAD

**Issue by Artman12** [google/ExoPlayer#7970]
### [REQUIRED] Searched documentation and issues
MatroskaExtractor source code
Several issues

### [REQUIRED] Question
I have implemented custom `DataSource `to use with `ProgressiveMediaSource`.

```
private MediaSource buildMediaSource() {
    MyDataSource.Factory factory = new MyDataSource.Factory(getItem());
    return new ProgressiveMediaSource.Factory(factory).createMediaSource(Uri.EMPTY);
}
```

When I try to open MKV file, the player calls `read(byte[] buf, int offset, int readLength)` function multiple times, passing `1` as `readLength`.

This results into minutes of initialization time before video starts playing (player wants to read ~600000 times by 1 byte on the video I have)

For a test I've setup my own http server and formed an uri for this video, which I then used like this:

```
new ProgressiveMediaSource.Factory(new DefaultHttpDataSourceFactory("sdfsdfds")).createMediaSource(uri); // uri looks like https://127.0.0.1:34567/video.mkv
```

and then player began to request `16384 `as `readLength`. Video initialization takes few seconds.

Additional information: The file I have is 3Gb. That 600k 1 byte reads happen when player wants to read at the end of the file. The file is not optimized for streaming or anything.

Is there a way for me to tell player to read bigger chunks?
Or maybe there is a way to speed up initializing video in `MatroskaExtractor`? I still need seeking though

### Link to test content
I cannot provide you my video, but It happens not only on 1 video file, I've been receiving reports about long initialization time for multiple MKV video files.

**Comment by Samrobbo** [comment]
Hi, without an example piece of media, it will be hard for us to diagnose the problem. 

 If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Artman12** [comment]
I've sent a google drive uri pointing to MKV video file to dev.exoplayer@gmail.com

**Comment by kim-vde** [comment]
I cannot reproduce because:
- I cannot play the file remotely with the link you provided. I need a link that points directly to the file instead of a Google drive link.
- The file is too large to be played locally.

The Matroska extractor tends indeed to request a lot of individual bytes to compute the length of variable-length integers.

What you can try to do is:
- Try to play your file with our demo app to see if there is anything wrong with how you set up the player.
- Use a custom ExtractorsFactory containing only the MatroskaExtractor. This will skip the sniffing step which could be time consuming. Note that this only works if you know in advance that the file is gonna be a Matroska file.
- Implement a custom [DataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html) that would have a minimum read length per request and store the data in an intermediate buffer. Wrapping your data source in a [CacheDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheDataSource.html) might also help if you sometimes read the same portions of the file multiple times.

**Comment by Artman12** [comment]
Thank you for your response.

Too bad you can't download and play that file locally. Reading ~600000 bytes one by one looks suspiciously odd. But it may be a file problem. I cannot provide you with another file, because all files which reproduce such behavior have big size.

My case is that I transfer the file using my own native library over network via my own protocol in chunks of 1MB. My buffer size is 10MB, it is kept in memory in native code.
I think my problem is that for each `read()` call I have to ask native library to return me that 1 requested byte and it is time consuming as I have to convert several structures from Java to C++, copy C++ buffer to Java. A lot work just to get that 1 byte.

I wrote a quick test to request data from native library in big chunks and cache them on Java side. Turns out it works well. I will rewrite my code to optimize this case.

I will close this issue
