### ISSUE TITLE
Is there a way to download metadata (duration) for all MediaItems in a playlist?

### ISSUE THREAD

**Issue by strangesource** [google/ExoPlayer#7978]
### Searched documentation and issues
StackOverflow, Issues, Documentation, Blog

### Question
When loading/playing a playlist using the new playlist api introduced in 2.12.0, only data for the first item is loaded up until a few seconds before the transition to the next item happens. `Window.durationMs` from the second item stays `C.TIME_UNSET` until this point.

While this is perfectly fine for most applications, I do need the duration of all `MediaItem`s in the playlist upon loading.

This leads me to the question if there is any way to configure the loading behaviour of a playlist to include the duration (manifest?) of all items right at the beginning?

**Comment by strangesource** [comment]
I just found this: 
`SimpleExoPlayer.setUseLazyPreparation(false)` but unfortunately it does not work for progressive sources. Is that a known limitation? 🤔

**Comment by marcbaechinger** [comment]
Yes, it's the intended default behaviour to prepare lazily. You can change this by setting 

```
SimpleExoPlayer simpleExoPlayer = new SimpleExoPlayer.Builder(context)
    .setUseLazyPreparation(false)
    .build()l
```

in this case all media items are prepared as soon as you add them to the playlist. As soon as an media source that is created for an item has preparation completed, a `onTimelineChanged` event is sent to your app with `TIMELINE_CHANGE_REASON_SOURCE_UPDATE`. There is no guarantee in what order these events arrive. So if you have three (non-live stream) items in the playlist, you can wait until you receive three callback calls with `TIMELINE_CHANGE_REASON_SOURCE_UPDATE` and then you have all the durations in the timeline.

Like you mentioned, lazy preparation is enabled by default because this would cause an initial burst of network requests. If your playlist is short that may be acceptable for your app.

**Comment by marcbaechinger** [comment]
:) We just cross posted. That should work though. That's not a known limitation. That would be a bug if not working. I'll look into that :)

**Comment by strangesource** [comment]
Thanks for the fast answer!!! Much appreciated. I will have another look into the Issue I am having with the progressive source.

**Comment by marcbaechinger** [comment]
I created a playlist with 4 items. With the default configuration the first two items are prepared initially (the media is quite short that's why the second item is prepared as well). But then it waits until playback advances to prepare the third and fourth item.

The third item is prepared after about 69 seconds:
```
timeline [eventTime=69.18, mediaPos=68.14, window=0, period=0, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
```

When setting `useLazyPreparation` to false, all media sources are prepared immediately as expected:

```
mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
timeline [eventTime=0.23, mediaPos=0.00, window=0, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
timeline [eventTime=0.24, mediaPos=0.00, window=0, period=0, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
timeline [eventTime=0.28, mediaPos=0.00, window=0, period=0, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
timeline [eventTime=0.77, mediaPos=0.00, window=0, period=0, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
  period [128.27]
  period [135.65]
  period [59.30]
  ...
  window [128.27, true, false]
  window [135.50, true, false]
  window [59.18, true, false]
```

The logs (printed by `EventLogger`) show that all four `SOURCE_UPDATE`s arrived after 0.77 seconds when the media position is still on 0.0. The list of windows in the log is kept at a max of 3 but it shows that the durations are available already.

If you see a different behaviour, can you add the [`EventLogger`](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger) to your app and do a bug report when you prepare your player and the upload this here so I can investigate?

**Comment by strangesource** [comment]
I was able to reproduce my observed behaviour in the plain ExoPlayer with the these two `MediaSource` items:

```
        mediaItems = new ArrayList<>();
        mediaItems.add(MediaItem.fromUri("https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd"));
        mediaItems.add(MediaItem.fromUri("https://html5demos.com/assets/dizzy.mp4"));
```
And ` setUseLazyPreparation(false)`.

Duration is only available shortly before switching to the next source.

Here is the log you requested, hope that helps. 🙂 
[log.txt](https://github.com/google/ExoPlayer/files/5276490/log.txt)

**Comment by marcbaechinger** [comment]
Seems like my media was too short and my sample was misleading. Sorry about this. You are right. For progressive media sources, the first real media period needs to be prepared. This does not happen at the preparation time of the source. Only adaptive media have the duration available immediately at source preparation.

I'm sorry for any inconvenience caused. We have issue #4727 which covers this limitation already. It is marked as an enhancement for this. Like the comment here in the [`ProgressiveMediaSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaSource.java#L343).

**Comment by strangesource** [comment]
Thanks @marcbaechinger, this helped me out a lot. The workaround propposed in the issue might work for us as well. 👍
