### ISSUE TITLE
Dinamically refresh data source request property on token expired

### ISSUE THREAD

**Issue by alexandru811** [google/ExoPlayer#7995]
We are using auth token to authorize access to the audio resources consumed by Exoplayer. Currently if the token expires, the request fails and exo player stops. 

Is there a way in which a data source ( or more specific its request headers) can be updated after being initially loaded? What mechanism can be used to perform the refresh and then update the existing media source with the new values so that the player can be restarted?

Looking maybe for an interceptor or something similar to the Okhttp authenticator to enable reactive authentication when needed.

**Comment by AquilesCanta** [comment]
For this specific usecase, I think your best shot is using a custom wrapper data source:
1. Implement a [DataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html) (Say AuthenticatingDataSource) which wrapps the current DataSource implementation that you are using.
2. Inject AuthenticatingDataSource using the DataSource factory that corresponds to your MediaSource.

In order to implement AuthenticatingDataSource you should modify open to look something like follows:

```java
public long open(DataSpec dataSpec) throws ... {
  try {
    wrappedDataSource.open(...);
  catch (InvalidResponseCodeException e) {
    if (e.responseCode == 403) {
      // Tokens expired (you might need to adequate this to your use case).
      Util.closeQuietly(wrappedDataSource);
      // Renew tokens.
      wrappedDataSource.setRequestProperty(...);
    }
  }
```

So now, whenever AuthenticatingDataSource detects the tokens have expired, it sets new tokens without ExoPlayer ever noticing this change. Would this work?

**Comment by sunhb** [comment]
My app is a audio play service based on UAMP. I have a similar requirement. 

1. When I set up a playlist, I only had some missing metadata sometimes.
For example, its media url address is not available. 
2. When playing to this media, I need the player to stop playing and notify the front end of the need to do some operations such as buy a license or login required to continue. 

3. The user then completes the necessary operation which play service needs.

4. The service then triggers a new request to obtain a real media url, and then dynamically update to the original location of the media in the playlist and start playing. 

But I can't find the corresponding listener let play service know I need hold on here and waiting for user do something, do not throws media uri can’t open Exception.

**Comment by AquilesCanta** [comment]
@sunhb, this seems unrelated to the original issue. Please file a fresh issue. Also, I'm not sure I understand the problem, so I would also:
- Remove unnecessary context.
- Expand a bit more in terms of what you are doing and what you are expecting ExoPlayer to do.
