### ISSUE TITLE
ExoPlayer can't reliably detect 4k display (?)

### ISSUE THREAD

**Issue by piterwilson** [google/ExoPlayer#800]
I am using this stream 

http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8

There's a 4K stream in the manifest but it never gets picked. 

VideoFormatSelectorUtil.getDisplaySize cannot correctly pick up 4K resolution when testing with a  sony X83C. It always reports 1920x1080. 

I am wondering if this is an platform issue, a vendor issue and if ExoPlayer has any way to detect a that device like the sony X83C is 4k capable. 

This will be a big shame for Android TV on said device. 

Thanks,

**Comment by piterwilson** [comment]
Just to add more information the device is exactly a `KD-43X8305C`

**Comment by andrewlewis** [comment]
The UI on this device is probably rendered at 1080p, but SurfaceView surfaces can show full 4K resolution. Display.getRealSize is reporting the lower UI resolution so the stream is getting filtered out.

As per https://developer.android.com/preview/api-overview.html#4K-display we need to use Display.Mode which was added in API 23. For earlier platform versions we would need to find out the real resolution in some other way or implement a workaround.

**Comment by ojw28** [comment]
This is fixed for Sony Bravia devices. This issue now tracks the general purpose solution, which is to use Display.Mode on API level 23+.

**Comment by cobarx** [comment]
Can you also add support for the nVidia Shield TV and the Sony Xperia Z5 Premium. The Shield TV model name is "SHIELD Android TV". For the Z5 Premium the models are: E6833, E6853, and E6883. There is also a Z5 Premium prototype we're using for testing with a model of 12VG68IB05IY81C2 (all prototype units share the same model). Please add that as well.

**Comment by ojw28** [comment]
The general purpose solution will cover these devices once they receive an M update. In the meantime, I'm not sure we're particularly motivated to special case these devices because. For the shield tv device, whether the display is 4K depends on what display the shield box is plugged into. In many (probably most) cases, the display wont be 4K. For the Z5 models it's not hugely important simply because the screen isn't big enough for 4K to be noticeably better (and conversely, 4K will drain more battery and require more data).

**Comment by davebytes** [comment]
The Sony X830C Android TV reports properly per pre-M system property, same as SHIELD ATV does.  adb shell getprop reports:
[sys.display-size]: [3840x2160]
