### ISSUE TITLE
Is there a way I can disable sound ducking?

### ISSUE THREAD

**Issue by Turbozanik** [google/ExoPlayer#8001]
Question:
Is there a way I can disable sound ducking? 

Use case:
I have a video played by ExoPlayer in my app, and I have a dialog with a sound also played with ExoPlayer and if the dialog is shown during the video,  the video sound is lowered, and our customer want's to keep the video sound level the same.

**Comment by krocard** [comment]
I think what is going on, is that that the dialogue is taking the audio focus as TRANSIENT, leading to the ExoPlayer instance losing the audio focus as AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK.

Note that your dialog sound should not be very long, and the ducking should thus be quite short. If it is not the case, the video is duck longer, the issue comes from the dialog sound. Maybe it has a long silence tail?

If the ducking is short, and still an issue, you need to decide which behaviour your want you video to have:
 1) never duck on any notification sound (not recommended and I will only detail if you need this solution)
 2) duck normally, except for this dialog sound.

2 is quite easy, just disable audio focus handling on your dialog playing ExoPlayer. When calling `Builder.setAudioAttributes`, pass false to the second parameter `handleAudioFocus`.

**Comment by krocard** [comment]
Please reopen if your issue is not solved.
