### ISSUE TITLE
Switch between MP4 Streams on the fly 

### ISSUE THREAD

**Issue by dzabdelhak** [google/ExoPlayer#8028]
hi 
I am Using Exoplayer2 as my video player 
I have multiple .mp4 links for the same video but different  Qualities 
I added a spinner to the player view to choose quality and therefore switch the media source to the other URL 
its working fine but i want to know if I can make the switch process smoother by pre-buffering some  space after the current position on all qualities 
here's what I am using right now : 
```
 @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l)  { // spinner on selected methode
        Customqualityitem items = (Customqualityitem)adapterView.getSelectedItem();
        long currenttime= player.getCurrentPosition();
        boolean isreadytoplay = player.getPlayWhenReady();
        String urltobuild = items.getUrl();
      Uri u = Uri.parse(urltobuild.replace("https","http"));
       mediaSource = mediaSource(u,DetailsActivity.this);
        player.prepare(mediaSource);
        player.setPlayWhenReady(isreadytoplay);
        player.seekTo(currenttime);
```
I don't know if Exoplayer have somthing like this and/or  how  I can do it manually ? 
and if its not possible i want to know if i am doing it the right way or there is improvements to my current solution. 
Thanks.

**Comment by tonihei** [comment]
If you'd like to adapt between different qualities of the same video, you should package your media in segments and publish a DASH manifest, HLS playlist or SmoothStreaming manifest with your available qualities. See https://exoplayer.dev/supported-formats.html#adaptive-streaming for supported adaptive streaming formats.

If you really want to prebuffer some media with MP4s only, then you probably need to set up a second player and switch the output surface when you are ready to switch. I wouldn't recommend this approach though because it uses multiple video decoders (and some devices only have one), is resource-intense and complicated to implement.

**Comment by dzabdelhak** [comment]
thank you
