### ISSUE TITLE
Support for EXT-X-PLAYLIST-TYPE

### ISSUE THREAD

**Issue by brian-chu-twc** [google/ExoPlayer#805]
Does Exoplayer support EXT-X-PLAYLIST-TYPE for HLS?

I put live stream in the demo app and the control still show up. There is no isPlaylistType() or similar function to return 'event' or 'vod'. If we have this function, we can use it to change the UI accordingly.

Thanks

**Comment by ojw28** [comment]
You can distinguish a live stream from a vod one by querying the player's duration after it is prepared. Live streams will return ```UNKNOWN_TIME```, where-as vod streams will return the known duration of the stream.

**Comment by programkom** [comment]
But this issue points to some other issue. X-PLAYLIST-TYPE (EVENT|VOD) , if value = EVENT then this should point to player that  stream can be rewinded in past and 1st chunk should be played. additionaly, playlist wont include END tag and chunks will/can be appended to end of playlist since stream's duration changes every X seconds.

**Comment by londhenamdev** [comment]
I am also facing the same issue for exoplayer if X-PLAYLIST-TYPE= EVENT then player should start from current chunks that is live and specifies the buffering duration that can be seek back.  Thanks in Advance
