### ISSUE TITLE
Should I expect IllegalArgumentExceptions when calling release()?

### ISSUE THREAD

**Issue by hallyhaa** [google/ExoPlayer#8087]
### [REQUIRED] Searched documentation and issues
Didn't find anything on the exoplayer.dev web site

### [REQUIRED] Question
I see an IllegalArgumentException reported to Firebase/Crashlytics and wonder if I am supposed to do player.release() within a try/catch block ... ? This is with ExoPlayer 2.12, and the exception seems to be that the SimpleExoPlayer, in its release() method, calls streamVolumeManager.release(), and the Context object claims the manager's BroadcastReceiver isn't registered. I think this is completely under ExoPlayer's control, not mine.

Is this happening if one calls release() twice on a player object? (I don't think so).

Here's the stack trace:

```
android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1499)
android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1605)
android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:678)
com.google.android.exoplayer2.StreamVolumeManager.release (StreamVolumeManager.java:165)
com.google.android.exoplayer2.SimpleExoPlayer.release (SimpleExoPlayer.java:1706)
```

### A full bug report captured from the device
Will be emailed.

### Link to test content
N/A. The exception is seen in Firebase, but I have no further details about it.

**Comment by andrewlewis** [comment]
Thank you for reporting this.

Can you tell from Firebase which particular Android devices/versions are affected and how widespread the issue is?

I think we should just catch this exception and log a warning but it would be good to understand how widespread the problem is. If it's only on a small number of devices/builds that will give confidence that we are right to expect this call to succeed, and give us information so we can report this to the device OEM. If it is evenly spread across different devices that could point to an Android framework issue, or a problem with how the API is being used. Thanks!

**Comment by hallyhaa** [comment]
I have seen this only twice. Once on a Samsung Galaxy S10+ running Android 10, the other time on a Huawei P30 Pro running Android 9. They were not rooted, they were running in the background and proximity was on (whatever that means).
