### ISSUE TITLE
Google DAI HLS/TS video freeze in ad break caused by a SCTE35 marker in an ID3 Tag

### ISSUE THREAD

**Issue by jdeisenh** [google/ExoPlayer#8095]
Issue description

When trying to play content that was stitched by Google DAI (Dynamic Ad Insertion) into live content, we experience hangs in the second (!) and all following ad breaks. This happens only with exoplayer, on any platform tested.
On the exoplayer demo app, the second ad breaks will show a freezed video frames, while the audio continues to run. 
After several seconds, video continues in sync with audio
The overlay shows an increase of db (droppedBufferCount) by several hundert frames, and an increase of droppedToKeyframeCounter by 1. 
We think that there a no unflagged discontinuities in our stream, apple mediastreamvalidator does not complain.

A lot of trial and error showed that the problem is related to an ID3 tag containing an SCTE35 Marker generated by our origin server (Unified Streaming) in the first segment after the ad break. (This is the CUE-IN). 
Nothing happens immediately after this, but the next ad break, 30 minutes or longer later, will start with frozen video. 
When filtering out the ID3 PID from the TS, the issue disappears. 
Disabling this code block 
https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java#L579
also avoids the problem (with unknown side effects)

Reproduction steps
Start the linked content from exoplayer demo app. This is a minimal static playlist to reproduce the problem, consisting of
* The first chunk from after an ad break, containing the ID3 Tag
* (Rest of the live content has been removed)
* CUE-OUT/Discontinuity
* Ad break chunks, which show the problem

Link to test content

https://fut.dev.wpstr.tv/tmp/broken_dai/s8.m3u8
This was generated from Google DAI, then converted into a static playlist for reproducability

https://fut.dev.wpstr.tv/tmp/broken_dai/s8_mod.m3u8
A slight variation where the ID3 PID has been filtered from one chunk. Does not show the problem.

I can provide a link to the live stitched content directly from the Google DAI Service, but the video chunks won't be delivered outside germany. Setting up a proxy for worldwide reproducability is possible if needed. With this stream, it takes several minutes to reproduce the problem. 

A full bug report captured from the device
I skipped this because its so easily reproducable. Can do if needed

Version of ExoPlayer being used
Tested with r2.12.0, also seen on several older versions. Not a recently introduced problem

Device(s) and version(s) of Android being used:
All Version of android we tested, including Android 10, Fire OS 5 and 7, Android TV 9.

**Comment by jdeisenh** [comment]
P.S. Also reproducable with AVD emulator from the android SDK

**Comment by AquilesCanta** [comment]
Thanks for the detailed report. I'll take a look and reach back.

**Comment by AquilesCanta** [comment]
So what's causing the issue is the timestamps in the content's (not ad) ID3 track. The PTSs in the content are:

```
ID3 (there are only two):
PTS: 4748350544 (0x11b061450)  [= 90 kHz-Timestamp: 14:39:19.4504]
PTS: 4749878623 (0x11b1d655f)  [= 90 kHz-Timestamp: 14:39:36.4291]

AUDIO:
PTS: 4749250783 (0x11b13d0df)  [= 90 kHz-Timestamp: 14:39:29.4531]
PTS: 4749268063 (0x11b14145f)  [= 90 kHz-Timestamp: 14:39:29.6451]
...
PTS: 4749853663 (0x11b1d03df)  [= 90 kHz-Timestamp: 14:39:36.1518]
PTS: 4749869023 (0x11b1d3fdf)  [= 90 kHz-Timestamp: 14:39:36.3224]

VIDEO
PTS: 4749250544 (0x11b13cff0)  [= 90 kHz-Timestamp: 14:39:29.4504]
PTS: 4749254144 (0x11b13de00)  [= 90 kHz-Timestamp: 14:39:29.4904]
...
PTS: 4749873344 (0x11b1d50c0)  [= 90 kHz-Timestamp: 14:39:36.3704]
PTS: 4749876944 (0x11b1d5ed0)  [= 90 kHz-Timestamp: 14:39:36.4104]
``` 

The first ID3 timestamp is 10 seconds before the first audio/video timestamp. This makes ExoPlayer think that the first audio and video samples occurs at approximately second 10 of the stream. You can confirm this by looking at the time bar of the demo app's playback controls when playing the stream: It will jump from 0 to 10 immediately.

Then, when adjusting the ads' timestamps this doesn't occur because the ID3 are within the segment's duration, but the generated video timestamps follow the playlist's timestamps because there was a discontinuity. Which means, from ExoPlayer's perspective, the video timestamps look something like this:

```
10.0
10.04
...
16.88
16.92
7.04 <-- At this point there's the discontinuity. Since the first segment is 7 seconds in duration according to the playlist, it adjusts the second segments` timestamps to start from 7.
7.12
...
21.88
21.92
```

But when the video renderer thinks it's rendering position 16.92 and suddenly it has to render a sample from 7.04, then it think it's falling behind playback so it starts dropping frames, which is what you observe.

### How to fix it:

The easiest way is to fix the content by putting the ID3 packet with the early timestamp in the corresponding TS segment. The ID3 timestamp with PTS 14:39:19.4504 belongs in a segment 10 seconds earlier than the one in which it is now. Otherwise, if we calculate the duration of a segment as the time between the first and last samples in it, the duration of the segment is 17 seconds. 10 seconds more than declared in the playlist (which would be non-spec-compliant).

If you don't have control over the media, then one option is disabling ID3 parsing. The fastest way of achieving this is injecting a custom [TsPayloadReader.Factory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/TsPayloadReader.Factory.html) which returns an empty [TsPayloadReader](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/TsPayloadReader.html) for `TsExtractor.TS_STREAM_TYPE_ID3`.

If disabling ID3 parsing is not an option, then we should explore more complex options like forking the ExoPlayer ID3 parser to either avoid outputting ID3 samples where the timestamp is outside of the duration of the segment.

Please let me know how you think we should continue.

**Comment by jdeisenh** [comment]
Thank you for the thorough analysis. That helps a lot. 
Ignoring ID3 is not an options, since DAI and thus ad revenue depends on it. 
We are currently working on fixing the media, if that fails we will consider a fork as a last resort.

Thanks again!

**Comment by AquilesCanta** [comment]
Great, happy to provide some ideas if that would help. In my opinion, fixing the media would be the best option, though.
