### ISSUE TITLE
How to perform partial download of media using exoplayer

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8105]
### [REQUIRED] Question
We want to partially download a creative and start playback as soon as possible. This feature we want for all kind of media formats including mp4

We have set the buffer sizes in DefaultLoadControl of exoplayer but while playing mp4 contents we don't see the content getting downloaded with 206 http status. Looks like the entire mp4 creative is getting downloaded with 200 status and there is no **partial download**

Will the DefaultLoadControl settings of exoplayer ensure that even for mp4 assets, playback will start as soon as DEFAULT_BUFFER_FOR_PLAYBACK_MS of data is available?  

For mp4 files, we can ensure that the moov atom is at the start of file so that player can immediately starts playing once few seconds of data is available.

If this is not the case the now can we ensure partial download of creative and immediate start of playback?

Thanks.

**Comment by andrewlewis** [comment]
> We have set the buffer sizes in DefaultLoadControl of exoplayer but while playing mp4 contents we don't see the content getting downloaded with 206 http status

I think we don't request a partial range but instead make an unbounded request and then consume data from the stream gradually. So even though the status isn't 206 it's still loading progressively.

To understand this in detail you could try stepping through the code in `ProgressiveMediaPeriod.ExtractingLoadable.load` to see how the data source gets opened and how loading and extraction of samples starts/stops as needed. Actual playback of the loaded data is decoupled from the request completing because the extractor writes to a queue of samples and on the separate playback thread renderers will read from the queue while loading is ongoing.

> Will the DefaultLoadControl settings of exoplayer ensure that even for mp4 assets, playback will start as soon as DEFAULT_BUFFER_FOR_PLAYBACK_MS of data is available?

Yes, with the caveat that there are some edge cases where it's more complicated (like if a renderer can't become ready for some reason). To find out more please read the code in `ExoPlayerImplInternal` around `doSomeWork` and `shouldTransitionToReadyState`.

> For mp4 files, we can ensure that the moov atom is at the start of file so that player can immediately starts playing once few seconds of data is available.

This is a good thing to do, but if the moov box isn't at the start ExoPlayer with skip (either via a range request if the intervening boxes are above a certain size, or by reading and discarding data otherwise) then read the moov box then jump back. So it's not a requirement but a good idea if you want playback to start quickly. See `Mp4Extractor.readAtomPayload`.

**Comment by krackjack234** [comment]
Thanks @andrewlewis
