### ISSUE TITLE
skipAd () in ImaAdsLoader just work for first Item

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8114]
I have a VMAP tag that contains many VAST tags, When imaAdsLoader.skipAd () only works for the first Item and does not work for another ad.

**Comment by andrewlewis** [comment]
Please check that the ads are declared as skippable in the VMAP ad tag. Are you playing audio-only ads? Could you share the ad tag?

**Comment by sajjadshahbazi** [comment]
just that work for the first item

**Comment by sajjadshahbazi** [comment]
ads in video mp4 and main content is hls

**Comment by andrewlewis** [comment]
Could you share the ad tag?

**Comment by sajjadshahbazi** [comment]
val imaSdkSettings = ImaSdkFactory.getInstance().createImaSdkSettings()
            imaSdkSettings.language = "fa"
            imaAdsLoaderBuilder.setImaSdkSettings(imaSdkSettings)

            imaAdsLoader = imaAdsLoaderBuilder.buildForAdTag(
                Uri.parse(
                    "https://demo.reviveadservermod.com/demo_vmap/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&zones=preroll:0.0-0%3D58&nz=1&source=&r=R0.05822725687175989&block=1&format=vmap&charset=UTF-8&loc=location.protocol+window.location.hostname"
                )
            )

            playerView.player = this
            playControllerView.player = this
            imaAdsLoader?.setPlayer(this)

**Comment by sajjadshahbazi** [comment]
https://demo.reviveadservermod.com/demo_vmap/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&zones=preroll:0.0-0%3D58&nz=1&source=&r=R0.05822725687175989&block=1&format=vmap&charset=UTF-8&loc=location.protocol+window.location.hostname

**Comment by sajjadshahbazi** [comment]
Did I send the items you requested for review?

**Comment by andrewlewis** [comment]
When I played the ad tag, the second and third ads are not skippable so I think this is working as intended. If you want them to be skippable you need to configure this on your ad server.

Please note that the method `ImaAdsLoader.skipAd` is only intended for audio ads, as mentioned in its javadoc. For video ads, users are control of skipping the ad via the ad overlay rendered by the IMA SDK. The method exists so that audio-only apps can skip ads because there is no ad overlay rendered by the IMA SDK in that case.

I think you are already aware of this based on #8098 but just to be clear: showing video ads and implementing your own UI for skipping is likely to be against IMA policies.
