### ISSUE TITLE
can't get duration of audio file which  extension is .aac

### ISSUE THREAD

**Issue by l20160606sy** [google/ExoPlayer#8118]
[No information provided]

**Comment by ojw28** [comment]
This is a known limitation. You should consider using a more appropriate container format for your audio, such as MP4, which will not have this problem.

**Comment by l20160606sy** [comment]
But I found that sometimes the audio of AAC files can get the total duration, and sometimes it can't

**Comment by ojw28** [comment]
I think the duration might become known once the player has buffered to the end of the stream, so you may find that duration is determined quickly for short AAC files (which are fully buffered up-front), and toward the end of the playback for longer AAC files (where this is not possible).

The problem is that the player doesn't have an efficient way to determine the duration of the content from only the start of the file. Processing the entire file is clearly a very inefficient way of determining duration, and so we opt not to do this. If this is a requirement you should use a modern container format such as MP4, which specifies its duration directly at the start of the file in a way that the player can easily read.

**Comment by l20160606sy** [comment]
OK, got it.thanks
