### ISSUE TITLE
Additional comment about 'get Dash stream sizes' issue

### ISSUE THREAD

**Issue by Jason239** [google/ExoPlayer#8119]
> `DashManifest.durationMs` combined with the representation bitrates seems sufficient for this use case. Closing on this basis, but please feel free to comment or clarify if you're still stuck!

_Originally posted by @ojw28 in https://github.com/google/ExoPlayer/issues/4714#issuecomment-504524539_

I have further question about the above issue.
The 'representation bitrates' mentioned above is, as you know, the maximum of all segments, so we can't get the accurate file size.
How do you think about this?

**Comment by ojw28** [comment]
> The 'representation bitrates' mentioned above is, as you know, the maximum of all segments, so we can't get the accurate file size.

The definition is a bit more complicated, but you're right that it's essentially a peak bitrate rather than an average. I probably didn't understand this when I made my previous comment, so I think my previous comment was just not very correct; sorry about that :).

I'm not sure it's possible to efficiently determine download size from a DASH manifest, at least not in the general/worst case. If the DASH manifest is only providing segment URLs then I think you'd need to do a HEAD request for every segment in order to determine the size accurately.

If you have control over the content being played, you're probably interested in a much more specific case, so it'll depend somewhat on what your DASH manifests look like. For single-segment VOD content you probably only have to make one HEAD request for each representation, which is more reasonable. If you specify ranges of the URLs then that probably works as a way of including the exact content lengths directly in the manifest.

**Comment by Jason239** [comment]
Okay, thanks for your detailed reply ;)
