### ISSUE TITLE
mediaChunks list handling in ChunkSampleSource is not robust against initial sample skipping

### ISSUE THREAD

**Issue by Bastian35022** [google/ExoPlayer#812]
In the `readData` method of `ChunkSampleSource`, some entries of the `mediaChunks` member are (sometimes) removed in this section:

    BaseMediaChunk currentChunk = mediaChunks.getFirst();
    while (haveSamples && mediaChunks.size() > 1
        && mediaChunks.get(1).getFirstSampleIndex() == sampleQueue.getReadIndex()) {
      mediaChunks.removeFirst();
      currentChunk = mediaChunks.getFirst();
    }

Now, if some samples are skipped initially (e.g. if the content does not start with a sync sample), the read index can be higher than the value returned by `mediaChunks.get(1).getFirstSampleIndex()`, avoiding the removal of chunks from the list in general. This leads to a wrong assignment of `currentChunk`.

I guess it could simply be solved by making the `==` a `<=`, which at least works for me.

**Comment by ojw28** [comment]
I don't really understand. What exactly does skipping mean in this context? In other words, where does the skipping happen, and how does it lead to the two being out of sync? I tried deliberately ignoring the fact that the first keyframe(s) in some media are keyframes, but couldn't reproduce an issue.

**Comment by ojw28** [comment]
Ah, managed to figure out what you mean now. To check we're talking about the same thing, the way I see this happening is as follows:

- Suppose the first chunk contains zero keyframes, and that the second chunk contains a keyframe but not as the first sample.
- Suppose the first two chunks are fully buffered.
- A call to readData will call sampleQueue.getSample, which will skip to the first eligible sample, which is the keyframe in the middle of the second sample.
- The next call to readData will hit the issue you describe, where the sampleQueue.getReadIndex returns a value larger than mediaChunks.get(1).getFirstSampleIndex().

Is this consistent with your understanding? I think the fix is to change == to <= as you suggest. I'll get that done. Thanks!

As an aside, what media are you playing where chunks don't start with keyframes? DASH/SmoothStreaming chunks should always start with keyframes, so it sounds a bit like the media is bad?

**Comment by Bastian35022** [comment]
Yes, that's the issue i was referring to, sorry for the bad wording :/

I am using DASH content, and i agree that it is usually not a good idea. However, it is necessary when you want to get down the latency by shortening the segment duration (fractional seconds in my case), while avoiding a bad compression efficiency through frequent usage of keyframes. This way you can end up starting with a number of consecutive segments without keyframes when tuning into a live stream.

**Comment by ojw28** [comment]
Got it. Note however that you wont get proper seamless switching between formats if you adopt that approach. When the player wants to switch from one quality to another, it will download chunk N of the old format and then chunk (N+1) of the new format. If the latter chunk doesn't start with an access point, there is no way for the player to perform the switch seamlessly, and it will necessarily discard media up until the first keyframe that it discovers in the new format.
