### ISSUE TITLE
How to play live byteArray data

### ISSUE THREAD

**Issue by DaveBoy** [google/ExoPlayer#8125]
i have a live byteArray data from dlna/cast or other way from a screen cast.
the question is how to input it to the Exoplayer.

i know the method by byteArrayDataSource from [issues/5571](https://github.com/google/ExoPlayer/issues/5571),but how to update the byteArray in the byteArrayDataSource?when i creat the byteArrayDataSource,I only have current byteArray data，how to set the next Frame byteArray data?Constant setting new byteArrayDataSource?

**Comment by DaveBoy** [comment]
i found the Aes128DataSource、RtmpDataSource、UdpDataSource SourceCode is return C.LENGTH_UNSET in open method.
That keeps reading the newest data through the ’read‘ method, right?

**Comment by ojw28** [comment]
You will need to implement your own `DataSource` to support this. And yes, you're correct to say that:

1. `open` will need to return `C.LENGTH_UNSET` because the length of your data is unknown or unbounded.
1. `read` should be implemented to return the next part of the data to be read on each call.

**Comment by DaveBoy** [comment]
tks for your reply
