### ISSUE TITLE
Exoplayer CC(Closed caption) issue in FireTV app : Rejected by Amazon Store

### ISSUE THREAD

**Issue by gautamlook** [google/ExoPlayer#8130]
I am working on TV app for FireTV. 

Amazon store have rejected my app due to CC issue. Matter is that CC(Closed Caption) is not working fine for some of the videos.

I am using Exoplayer player with custom CC(Closed Caption) button. If button ON then CC is enable and show the closed caption and if button OFF then CC is disable to show.

I am using below code for detecting CC is coming or not in Videos.

```
    private boolean checkAndSetClosedCaptions() {
            // This is the body of the logic  for see if there are even video tracks
            // It also does some field setting
            MappingTrackSelector.MappedTrackInfo mappedTrackInfo = MainActivity.trackSelector.getCurrentMappedTrackInfo();
            if (mappedTrackInfo == null) {
                return false;
            }
            for (int i = 0; i < mappedTrackInfo.length; i++) {
                TrackGroupArray trackGroups = mappedTrackInfo.getTrackGroups(i);
                if (trackGroups.length != 0) {
                    switch (player.getRendererType(i)) {
                        case C.TRACK_TYPE_TEXT:
                            return true;
                    }
                }
            }
            return false;
        }
```

This code is working fine when CC is coming then 'checkAndSetClosedCaptions' return true and not coming then return false.

But for some videos, CC is coming with Unknown name.

In this case, 'checkAndSetClosedCaptions' is return true but close caption is not showing when i enabled cc from button.
Video URL :
https://redirect.field59.com/video/608fd60f54c844ccabe023a8126c2d0b2158201a.m3u8

I am using below code for enable and disable Closed caption for English language.

   

  ```
   private void captionEnable() {
            MainActivity.trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder()
                    .setRendererDisabled(C.TRACK_TYPE_VIDEO, false)
                    .clearSelectionOverrides(C.TRACK_TYPE_VIDEO)
                    .setPreferredTextLanguage("en")
                    .setPreferredAudioLanguage("en")
                    .build());
            SharedPreferenceUtils.getInstance(activity).setValue(AppConst.CLOASED_CAPTION, true);
            selectTracksButton.setImageResource(R.drawable.player_button_cc_select_blue);
            onOff.setText("On");
        }

```
 

  ```
    private void captionDisable() {
            MainActivity.trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder()
                    .setRendererDisabled(C.TRACK_TYPE_VIDEO, true)
                    .clearSelectionOverrides(C.TRACK_TYPE_VIDEO)
                    .setPreferredTextLanguage("en")
                    .setPreferredAudioLanguage("en")
                    .build());
            SharedPreferenceUtils.getInstance(activity).setValue(AppConst.CLOASED_CAPTION, false);
            selectTracksButton.setImageResource(R.drawable.player_button_cc_selector);
            onOff.setText("Off");
        }
```

How to hide the CC(Closed Caption) button when I found above condition.

**Comment by icbaker** [comment]
Thanks for providing the media - I'm able to reproduce the behaviour you're seeing in the demo app: the 'track selector' dialogue shows a text track called 'Unknown' but selecting it displays no subtitles.

This is happening because `DefaultHlsExtractorFactory#exposeCea608WhenMissingDeclarations` defaults to true:
https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java#L70-L72

You can change this in two ways:

1. Change the manifest to explicitly declare that it has no captions using `CLOSED-CAPTIONS=NONE` (the track is only auto-created when the manifest doesn't declare presence of a subtitle track either way).

2. Set your own `DefaultHlsExtractorFactory` (constructed with `exposeCea608WhenMissingDeclarations = false`) on `HlsMediaSource.Factory`.

**Comment by gautamlook** [comment]
Thanks for the update. it is working fine for Videos URL
https://redirect.field59.com/video/608fd60f54c844ccabe023a8126c2d0b2158201a.m3u8

But 'Closed Caption' has coming stop  for below Video URL (Before set 'exposeCea608WhenMissingDeclarations = false', Closed Caption is showing on this  videos ) 
https://redirect.field59.com/video/71e09e82cd78f9a10875f17e2478674cc094d228.m3u8

can you tell me what is issue and how to handle both type videos.

**Comment by icbaker** [comment]
The second video **does** have a text track in the TS segments, but it also isn't declared in the manifest.

So by setting `exposeCea608WhenMissingDeclarations = false`, we don't surface this track.

The easiest solution is to change the manifests so that they correctly declare whether media includes a text track or not.

@AquilesCanta might have ideas of how you can handle this from the ExoPlayer side.

**Comment by AquilesCanta** [comment]
> The easiest solution is to change the manifests so that they correctly declare whether media includes a text track or not.

Agreed. The purpose of the master playlist's closed caption EXT-X-MEDIA tag is to signal these tracks. You can either provide caption service descriptors in the TS, or you provide EXT-X-MEDIA declarations in the master playlist. Other than that there are no reliable ways of knowing whether there's or not a 608 track in the media.
