### ISSUE TITLE
Download not working when we set drm_key_request_properties , Is it possible to download offline and play ?

### ISSUE THREAD

**Issue by tariqul000** [google/ExoPlayer#8144]
I modify **media.exolist.json** file to look like the bellow code.. it working for playing but I couldn't download the video. Is there any way in new Exoplayer to download and play DRM key protected video?  I found a demo app with old version that most of the file depreciated!!  
`[
  {
    "name": "Widevine DASH  testing app",
    "samples": [
      {
        "name": "Test DRM -acquire license",
        "uri": "https://manifest.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://wv.com",
        "extension": "mpd",
        "drm_key_request_properties": {
          "x-keyos-authorization": "GVudGljYXRpb25YTUw+"
        },
        "drm_multi_session": true
      }
    ]
  }
]`

**Comment by ojw28** [comment]
@christosts - Do we need to plumb `drm_key_request_properties` into the `WidevineOfflineLicenseFetchTask` class that you added in the demo app's `DownloadTracker`?

**Comment by tariqul000** [comment]
If  I understand clearly then you are right. you need to add  drm_key_request_properties  into the WidevineOfflineLicenseFetchTask class.  The present demo app not working to offline download when anyone uses Widevine drm_key_request_properties ... can you please look into this issue.

**Comment by abhishekpatil26** [comment]
> If I understand clearly then you are right. you need to add drm_key_request_properties into the WidevineOfflineLicenseFetchTask class. The present demo app not working to offline download when anyone uses Widevine drm_key_request_properties ... can you please look into this issue.

Do not use "drm_key_request_properties"
Instead try by passing key request properties like below
```
"drm_license_url": "https://wv.com/proxy?video_id=2000204308&jct=iM8kywAOjyuF-iiCix5CCg&pxe=1604924336&st=WwPgMoHF7Mn_EqrNBgt0nA" : {
"token": "eyJ0eXAiOiAP9sISEVKl_dUJ2HX9TQ",
"uniqueid": "d16d3e4b-454c-a739-dd686905bebb",
"usergroup": "39ee6de93ed8",
"os": "android",
"devicetype": "phone",
"Content-Type": "application/json",
"user-agent": "MyApp/1.9.0.10 (Linux;Android 10) ExoPlayerLib/2.11.7"
```

**Comment by christosts** [comment]
Hi @tariqul000,

Can you please share the content you are testing with so that we verify the fix? If the content cannot be shared publicly, can you please email it to dev.exoplayer@gmail.com with subject "Issue #8144"?

When you send it, please add a comment in this issue so that we get notified.

Thank you

**Comment by macmagician** [comment]
Hi @christosts,

I have also emailed you additional information regarding, and referencing this issue, and your proposed fix.

Thank you

**Comment by christosts** [comment]
Hi @tariqul000  and @macmagician 

While I'm writing a fix for this issue, I need to clarify how you will be able to download Widevine protected content from an app.

At the moment, offline downloads in ExoPlayer do not automatically support DRM-protected content, and the app has to glue itself some pieces together. Specifically, the app has to implement the equivalent of what `WidevineOfflineLicenseFetchTask` does in the ExoPlayer demo app: download the offline license (you can use [OfflineLicenseHelper](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java)), set it in the download request and kick off the download. That is, after the fix for this issue you should be able to download Widevine-encrypted content from the demo app, but that will not work out-of-box for your apps.

The demo app code can be used as guide to on how you can connect the pieces together. Here's how the ExoPlayer demo app glues things:
1. When `DownloadHelper` triggers the `onPrepared` callback,  the app searches for DRM init data in the content's DASH manifest. The DRM init data are stored inside a `Format` instance - [see onPrepared on the demo app](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L200).
2. The app then starts to download the offline DRM license via`WidevineOfflineLicenseFetchTask`. Eventually, the `WidevineOfflineLicenseFetchTask` is triggering [OfflineLicenseHelper.downloadLicense()](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L405). If you are using custom request headers, then at this point you need to make sure to create the `OfflineLicenseHelper` with this overload of [OfflineLicenseHelper.newWidevineInstance()](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java#L109) which allows you to specify custom request headers. You should already have access to other information needed by this method (or consult with the demo app).
3. Once the offline license is downloaded, the demo app uses the `DownloadHelper` instance to create a new `DownloadRequest` with the offline license key (see [buildDownloadRequest()](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L364)) and kicks off the download (see [startDownload()](https://github.com/google/ExoPlayer/blob/r2.12.1/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L359) in the demo app).

Please note the above works for Widevine-protected content with the DRM init data present in the manifest. It will not work if the DRM init data are located in the content's init segment.

**Comment by christosts** [comment]
@macmagician thank you for the test link. I'm afraid ExoPlayer won't be able to download the specific content for the reason mentioned in the previous comment: the pssh box is not in the manifest, but in the initialisation segment. 

Please consider moving the pssh box on the manifest. Note that doing so is somewhat the suggested practice
https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html#CPS-cmaf

**Comment by christosts** [comment]
Hi, I pushed commit [dc86b62](https://github.com/google/ExoPlayer/commit/dc86b625c50725a3a8bf1b4310b2bc8986d56922) to pass the `drm_key_request_properties ` to the `WidevineOfflineLicenseFetchTask ` on the dev-v2 branch. Please note, as per my comment above, you DASH content should contain  the pssh box inside the DASH manifest in order to download content.

I am closing this issue, feel free to re-open if there's anything I missed.
