### ISSUE TITLE
Does ExoPlayer support multiple EventStream tags in the same DASH period?

### ISSUE THREAD

**Issue by strangesource** [google/ExoPlayer#8155]
### [REQUIRED] Searched documentation and issues

- issue tracker
- https://exoplayer.dev/
- javadoc

### [REQUIRED] Question
When playing a DASH VOD stream with multiple `<EventStream>` tags in the same period, only the events from the first EventStream seem to be emitted. Is that a known limitation of ExoPlayer, intended behaviour or a bug?

### Link to test content
The manifest looks something like this:
```xml
<Period id="123456" start="..." bitstreamSwitching="true">
    <EventStream schemeIdUri="urn:scte:scte35:2014:xml+bin" timescale="90000">
      <Event id="2">
      ...
      </Event>
    </EventStream>
    <EventStream schemeIdUri="urn:scte:scte35:2013:xml" timescale="90000">
      <Event id="2">
  ...
      </Event>
    </EventStream>
    <AdaptationSet mimeType="video/mp4" segmentAlignment="true">
...
</Period>
```

Edit: I send you an email with a sample stream.

**Comment by strangesource** [comment]
I did look into this in a bit more detail and for me the situation presents as follows: 

`EventStream` s are individual track groups that are of type `TRACK_TYPE_METADATA`. Each `EventStream` is a track in its own `TrackGroup` and can therefore be selected via e.g. `SelectionOverride`. 

However it is - to my understanding - not possible to enable multiple `TrackGroup`s in parallel, therefore it is not possible to enable multiple `EventStream`s at the same time.

When reading trough the DASH specification I can not find anything stating this limitation hence it seems to be an ExoPlayer restriction only. 

Please correct me if I am wrong. 🙂

**Comment by ojw28** [comment]
Thanks for investigating. What you've discovered is largely true.

However, I think it's possible to make this work by having more than one `MetadataRenderer` instance. To do this, you just need to get an extra `MetadataRenderer` instance into the player. For example by injecting a custom `RenderersFactory` via `SimpleExoPlayer.Builder(Context, RenderersFactory). To create your custom `RenderersFactory`, you should be able to extend `DefaultRenderersFactory` and override the `buildMetadataRenderers` method. You can probably just implement it to call `super.buildMetadataRenderers` twice :).

So yes, it's not exactly obvious, but it should be possible for you to get this working!

**Comment by strangesource** [comment]
Thanks for the answer, now that is what I call a hidden feature. 😄

**Comment by ojw28** [comment]
Heh, yes! It's a limitation due to the current architecture, where there are a static number of renderers and each one can only play a single `TrackGroup`. This largely makes sense for audio and video, short of very niche use cases. The same is mostly true for text and metadata as well, however for these track types it is somewhat more likely for there to be use cases that need multiple tracks selected at once, as is the case here.

I think we'll try and remove this limitation at some point, but it's unlikely to happen any time soon because it will likely require a fairly non-trivial architectural change. It's also not entirely clear what that change should be, and whatever we do it'll likely have some significant implications for how track selection works. So, it's something that we think it's best to live with for now, given there is a way (albeit a hidden one) to get things working for those who need it!

**Comment by strangesource** [comment]
Thanks very much for the context, makes a lot of sense how you described it.
