### ISSUE TITLE
black screen when the app change to foreground from background

### ISSUE THREAD

**Issue by DaveBoy** [google/ExoPlayer#8171]
Good Friday.
when i play a video，change to background and then change to foreground，the player screen become black。
i find the solution from the [example](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java),it always release the player when the app   change to background,and init the player when the app change to foreground。
but this solution still has a short black screen time when the init player?is there any better solution?

**Comment by lcf87** [comment]
It's rather an *expected* behaviour because ExoPlayer has to release the decoder on entering back ground.

But there is a dirty way around if you are really keen on it:

In `StyledPlayerView`

- Change `surfaceType` to `SURFACE_TYPE_TEXTURE_VIEW`.
- In the constructor, set `shutterView.setVisibility(INVISIBLE);`.
- In `closeShutter()`, set `shutterView.setVisibility(View.GONE);`.

For texture view, [reference this doc](https://exoplayer.dev/ui-components.html#choosing-a-surface-type).

**Comment by DaveBoy** [comment]
tks very much,i will try it
