### ISSUE TITLE
Why the DefaultRenderersFactory's enableDecoderFallback is false by default?

### ISSUE THREAD

**Issue by Gumio** [google/ExoPlayer#8185]
### [REQUIRED] Question
Hello. Is there a reason why the DefaultRenderersFactory's setEnableDecoderFallback is set to false by default?

I have AB tested and analyzed the Boolean values at 50/50 and it doesn't seem to have any effect on JoinTime or anything else. Does it have a negative impact on performance?

Apart from that, interestingly enough, AndroidTV improved 99.9% of sessions on AndroidTV.

I was curious, so I felt free to ask about it. Best regards.

**Comment by kim-vde** [comment]
Using a lower-priority decoder if the best suited decoder initialization fails is not an expected default behaviour. Playback will continue without throwing any error, while there was something wrong in the decoder initialization.

As for performance, it depends on what you do if the decoder fails (and on what you mean exactly by performance):
- If you retry, then it is probably best not to fallback on a lower-priority decoder because your retry might succeed.
- If you don't retry, then it is probably best to fallback on a lower-priority decoder because it will allow you to continue playback.

From a time and space complexity point of view, performance shouldn't be affected by this parameter. Enabling it will just try the next decoder instead of throwing.

**Comment by Gumio** [comment]
Thank u! I understand.
