### ISSUE TITLE
About translation contribute

### ISSUE THREAD

**Issue by bnk159hair** [google/ExoPlayer#8187]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description

Hello, we are Korean university students. This project is an area we are interested in, so we would like to contribute.
We want to contribute through the Korean translation of the project. Is it okay to contribute?

**Comment by ojw28** [comment]
It's unclear what you're proposing to translate, exactly.

* All of the strings in the library modules are already translated into Korean ([example](https://github.com/google/ExoPlayer/blob/r2.12.1/library/ui/src/main/res/values-ko/strings.xml)).
* Strings in the demo applications are intentionally not translated. We could add translations if there's significant demand for it, although we'd do so via our internal process so that we can be sure the translations are updated quickly whenever the english strings are modified.
* We can't accept a contribution to translate https://exoplayer.dev, because we'd need to keep it in sync with any future changes to the English version. This is not something that will be practical to do via ad-hoc external contributions.

If you think I've missed something where there is an opportunity, please let us know. Please also let us know if you think there's significant demand for the demo applications to be translated. These two points aside, I think we'll have to politely decline your offer, but many thanks for offering!
