### ISSUE TITLE
DASH MPD@minBufferTime support

### ISSUE THREAD

**Issue by Bastian35022** [google/ExoPlayer#819]
Currently (dev branch), the MPD@minBufferTime parameter of DASH content is not considered for initial buffering of data. Instead, buffering behavior is configured when instantiating ExoPlayerImpl, plus the latency to the live point can be set for live content. For most cases this is sufficient, but for live streaming, MPD@minBufferTime is very good for adapting the buffering behavior to the rate control (specifically VBV in MPEG) used, and thus only buffering for the shortest duration that is necessary, improving the latency.

Will you add support for this?

**Comment by ojw28** [comment]
Perhaps, but it doesn't seem like a priority. It also feels like in general, the client would be better placed than the server to determine a suitable value for the duration of media to buffer before starting playback (e.g. the client knows about what type of network it's on, and may have information about the network conditions).

**Comment by Bastian35022** [comment]
Sure, some useful information is only available on the client side (excluding some modern approaches). Using both MPD@minBufferTime and the client-defined buffering configuration, where the player needs to fulfill both requirements, should work well for all cases, if the complexity is reasonable.

**Comment by ojw28** [comment]
Where do server requirements come from, exactly? It's unclear to me why the server should need to place any constraints on the minimum buffer duration.

**Comment by Bastian35022** [comment]
It is actually unrelated to channel conditions, but instead recommends the minimum number of bytes to buffer from the codec's perspective:

For coded video, the frame size usually varies quite a lot. This variation can be constrained using rate control schemes such as the video buffering verifier model (https://en.wikipedia.org/wiki/Video_buffering_verifier), which guarantees the client buffer to never be empty, if a specific number of bytes is received before starting playback, under the assumption of a CBR channel. This is achieved on the encoder-side by staying below a specific average bitrate during a specific time window, at all times.

The minBufferTime in DASH configures this minimum number of bytes (in combination with the bandwidth attribute of a representation). From what i've seen, minBufferTime is usually <= 2 seconds.

**Comment by tonihei** [comment]
ExoPlayer already uses the `minBufferTime` when figuring hour how far away from the live edge it should be playing. This is to ensure we always leave at least one GOP in the buffer (as specified by `minBufferTime`) so the decoder never runs out of buffers. 

This issue is talking about the initial start up of the stream though, which I believe is irrelevant as ExoPlayer waits until it has all the necessary buffers to play some duration of media (as configured by `DefaultLoadControl`). So in the extreme case where we have to load `MPD@minBufferTime` data to have all the information needed for even a single frame, ExoPlayer will not start playback until it has this information available. After the initial start up of the stream, we should make the assumption that loading the stream is faster than playing it and as long as we stay far enough away from the live edge (see above), `MPD@minBufferTime` never becomes relevant again. I'll close the issue under this assumption. Feel free to reopen (or file a new one) if necessary.
