### ISSUE TITLE
Set default video/audio codec when play m3u8 file

### ISSUE THREAD

**Issue by tuanlt2** [google/ExoPlayer#8194]
### [REQUIRED] Searched documentation and issues
I have used google search to find the answer but I can't get the answer.

### [REQUIRED] Question
In normal case, m3u8 file will have both video and audio codecs (example: CODECS="avc1.4d401e,mp4a.40.2").
But when m3u8 file misses video codec (example: CODECS="mp4a.40.2"), only audio are played (black screen).
And when m3u8 file misses audio code (example: CODECS="avc1.4d401e", only video are played (no audio).
Can I set default video/audio codec for ExoPlayer?

**Comment by kim-vde** [comment]
I think that the CODECS attribute is mandatory so you should probably add it to the HLS file so that it is widely supported.

I don't know any way to set default CODECS values in ExoPlayer. Any idea @christosts @AquilesCanta ?

**Comment by christosts** [comment]
According to the HLS spec, the CODECS attribute needs to contain the codecs for all formats in the rendition. Please see [RFC 8216](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07), [section 4.4.6.1.1](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#page-38) and [section 6.2.4](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#section-6.2.4).

My suggestion is to fix the media and include all codecs in the playlist.

If fixing adding the missing codec is not possible, you may override the default behavior in two ways:
1. Inject a custom [HlsPlaylistParser](https://github.com/google/ExoPlayer/blob/r2.12.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistParser.java) which populates the missing format codecs. You may inject a custom `HlsPlaylistParser` by [HlsMediaSource.Factory.setPlaylistParserFactory](https://github.com/google/ExoPlayer/blob/r2.12.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java#L196). 
2. If the CODECS attribute is empty, the ExoPlayer may parse all tracks in the provided streams because this [edge-case check here](https://github.com/google/ExoPlayer/blob/r2.12.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java#L198). Therefore, if removing all CODECs from the playlist is easier than adding the missing one, you might want to see if this works in your case.
