### ISSUE TITLE
How to change the sound resampler?

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#8198]
@ojw28 , I have been using ExoPlayer for a very long time, as the main one. For watching movies and listening to music.

But yesterday I found the resempler setting in VLC (--audio-resampler). It was the default setting for soxr.
Available options: any,samplerate,ugly,soxr,speex_resampler,none.
I have set any.
It feels like I bought new speakers. Now I hear low frequencies that I haven't heard before (for a long time using Exoplayer) and high frequencies are more contrasting. This applies to any music in mp3 and flac format.

**The question is, does ExoPlayer have this setting?**
Why do you cut the upper and lower frequencies in ExoPlayer?

**Comment by ojw28** [comment]
I don't think ExoPlayer does do any cutting of upper and lower frequencies.

You could implement a custom `AudioProcessor` to boost or reduce certain frequencies, but it's not something we support directly. It may also be possible to use `android.media.audiofx.Equalizer`, but it's not something I've ever tried.

**Comment by master255** [comment]
@ojw28 No. The resempler cannot be fixed with the equalizer. EQ changes sound after resempler.
Did you compare VLC sound with yours?
I have a program to do it.
Anyone will hear the difference in sound. The difference is big.

**Comment by ojw28** [comment]
ExoPlayer doesn't do any resampling at all for the majority of audio streams. In most cases we pass through exactly what's in the stream to the underlying platform. This seems like the correct thing to do. We do re-sample some high bit-depth audio formats, but an issue in that logic would not be consistent with "this applies to any music in mp3 and flac format" in your description, since as I say, the majority of audio streams aren't subject to this re-sampling.

I'm not sure what `soxr` is doing in VLC or why you prefer it, and we have no plans to drop our other work to look at this as a matter of urgency. You're welcome to do this research yourself and figure out where such an algorithm could be plugged into ExoPlayer. It should also be noted that audio preferences are subjective, and we have not received this request from other developers.

**Comment by master255** [comment]
@ojw28 

> I'm not sure what soxr is doing in VLC

No no! Read more carefully. Soxr is a resempler that uses VLC by default and it cuts the upper and lower frequencies just like your player.
I chose another resempler (any) to get the full sound quality.
I can hear exactly what ExoPlayer cuts the bass and high frequencies.
Perhaps you are using a cheap technique?
I use the Galaxy S8+ and the Bose QC35 headphones.
This can be heard very well on my Sony TV.
Even in movies you can hear the difference.

You should hear it. Otherwise, you don't understand what's going on.

You can hear the difference by playing any flac file with my player. It contains both modules: ExoPlayer and VLC (with "any" resampler).
You can find it by looking at the MediaLibrary in the playmarket. It is paid app. If you want, I will send you a promotional code for free purchase. Write me your email.

**Comment by ojw28** [comment]
Right, I meant `any` rather than `soxr`. That typo aside, as per my previous responses, ExoPlayer doesn't do any re-sampling at all for the majority of audio streams that we support. It's not possible for us to be using a cheap (or expensive!) technique when there's simply no re-sampling taking place.

**Comment by master255** [comment]
@ojw28 But somehow you have a digital-to-analog conversion? This is where the frequencies are trimmed and smoothed. This is a problematic place in ExoPlayer.

**Comment by ojw28** [comment]
For built-in speakers and 3.5mm headphone jack output, digital to analog conversion is implemented in hardware (the component responsible for doing this is called a DAC, and is typically provided by SOC vendors such as Qualcomm).

USB and bluetooth outputs do not require digital to analog conversion because they are digital outputs. In this case the conversion is done by a DAC in the connected device (e.g., bluetooth headphones contain their own DAC circuitry).

So no, ExoPlayer doesn't do any digital to analog conversion. Neither do other media players; digital to analog conversion is fundamentally something that happens in electronics and not in software.

**Comment by master255** [comment]
@ojw28 Then perhaps you need to implement some improvement. Ok. If you choose to ignore the problem, I won't bother you.
But the problem, as far as I hear it (and many other peoples), is very big.
Close the question if you want to ignore it.

**Comment by ojw28** [comment]
We work with many major streaming providers and power billions of playbacks per day, and have not received complaints about this type of audio quality issue from anyone else. So evidence suggests that it's not a very big problem. Closing because there's nothing particularly actionable for us to do here.

**Comment by master255** [comment]
@ojw28 Users just think that's all their device can do. And the frequencies are actually trimmed.
As I said, until you hear it, you will not understand.

**Comment by master255** [comment]
@ojw28 https://source.android.com/devices/audio/src
It says here that Android uses resemplers:
linear
cubic
sinc with original coefficients
sinc with revised coefficients

Which of them uses ExoPlayer?
And can you change it to libsamplerate, which is used in VLC?
