### ISSUE TITLE
IMA Extension : Multiple Ads not played with empty vast 

### ISSUE THREAD

**Issue by hyl0376** [google/ExoPlayer#8205]
### [REQUIRED] Issue description
Our VMAP AD contains 2 pre-rolls, the second of which can be empty. When I try to play this adTagUrl with demo app, the player plays the first ad well but it freezes before the second ad plays. There's no sound or buffering. I found #5006, #6097 but it still looks weird. This adTagUrl works fine in IMA SDK sample app (https://github.com/googleads/googleads-ima-android/releases AdvancedExample v3.24). I've emailed this adTagUrl to dev.exoplayer@gmail.com.

### [REQUIRED] Reproduction steps
I just switch "ad_tag_uri" in media.exolist.json to our custom adTagUrl and play.

### [REQUIRED] Link to test content
Our custom adTagUrl has been sent to dev.exoplayer@gmail.com.

### [REQUIRED] A full bug report captured from the device
A logcat and bug report have been sent to email too.

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Google Pixel 3 Android 11, API 30

**Comment by hyl0376** [comment]
Are there any updates?

**Comment by andrewlewis** [comment]
Sorry for the delay. I don't see any events from the IMA SDK relating to the second ad in the preroll ad pod, which is unexpected. I'll check the AdvancedExample to find out why it's working there, and then see if we can at least time out the ad loading to avoid playback getting stuck. Please let me know if you've found out anything else about what's going on since filing this.

**Comment by hyl0376** [comment]
Thanks for your kind support. It works fine on exoplayer 2.11.4(which I have used before 2.12.1 update) so I guess it seems to be due to preloading ads.
I'll continue to dig into the problem, too, so let me know if there is anything new.
