### ISSUE TITLE
Unexpected fallback behaviour in DefaultHlsExtractorFactory

### ISSUE THREAD

**Issue by matamegger** [google/ExoPlayer#8219]
### Issue description
Since v2.12.0 the `DefaultHlsExtractorFactory` seems to always fall back to a `TsExtractor` if the fed in stream is not compatible with any other extractor. However, this fallback behaviour ignores the `inferred type` of the stream.

The problem here is that even if the inferred type would fit the `fmp4Extractor` it will fall back to the `TsExtractor` when the branches in the fmp4 stream are not explicitly supported by the extractor. (in v2.12.0 you changed the logic to actually sniff the assets and detect such incompatibilities)  

I think this can be considered a bug, in that particular case a `fmp4Extractor` might be still able to play back the asset.. at least it has a higher chance than the `TsExtractor`.

### Reproduction steps
Load a fmp4 HLS asset with a by the Fmp4Extractor unsupported branch e.g. `iso9`

### Link to test content
Send via email.

### A full bug report captured from the device
```
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:552)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:416)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:284)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
```

### Version of ExoPlayer being used
`2.12.0` and `2.12.1`

### Device(s) and version(s) of Android being used
Don't think that is very relevant, as it is concretely about changes in the `DefaultHlsExtractorFactory`, but tested on an emulator with API 27 and a OnePlus 5T API 29

**Comment by matamegger** [comment]
I did file this as an issue, though as an external it could be also a question on if this fallback behaviour was intended in the first place.

**Comment by kim-vde** [comment]
Can you please send a test content for which the error occurs? If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using subject "Issue #8219".

**Comment by matamegger** [comment]
I already send the test content when I opened the issue. Let me know if something is missing.

**Comment by kim-vde** [comment]
Ah yes, sorry.

If no extractor recognizes the media file, a better fix is to change the extractors or the media file directly in order to solve this problem instead of hoping that the extractor corresponding to the file extension will work (particularly for MP4 files for which there are 2 possible extractors: Mp4Extractor and FragmentedMp4Extractor). This is what sniffing is for.

In the case of the content you provided, the FragmentedMp4Extractor is capable of reading it but does not recognize it in the sniffing step because it has brand `iso9` which is not supported. According to annex E of ISO/IEC 14496-12:2015, readers are required to implement all features documented for a brand and we can therefore not add brand `iso9` to the list of supported brands because we do not parse the iso7-9 boxes (`elng`, `sthd`, `trep` and `assp`). To fix the problem, you should add brand `iso6` to claim that readers supporting this brand can read your content (particularly as your content doesn't contain the iso7-9 boxes).

**Comment by matamegger** [comment]
Thanks for your investigation. I am aware of this particular situation and I totally agree that the stream should refer the correct supported branches and that sniffing the streams in the first place is a better way, than just using the inferred type.
I have to admit, I did forgot about the non-fragmented mp4 extractor in that manner.

I don't think that always using the `TsExtractor` as "fallback" is a nice solution. I get the point with mp4 and fmp4, but even for that it would be a "better" fallback to use the fmp4 extractor, as we do not expect any non-fragmented mp4 in that context.
Using the `TsExtractor` as fallback for every filetype seems quite random. (Maybe you have some insights on that decision).


_Through the conversation, this issue is maybe no longer a "bug", but rather "just" an improvement_

**Comment by kim-vde** [comment]
The choice for TsExtractor is actually not random. It allows us to handle a specific case where we know sniffing will fail. This occurs when the TS initialization data is provided through an EXT-X-MAP tag. This initialization data consists of a PAT table followed by a PMT table. The TsExtractor will fail sniffing because it searches for 5 packets and will only find 2 in this case.

Fixing the sniffing algorithm for that case would of course be a better solution, but it is not easy to do because the TS packets signature is only one byte long. Reducing the number of packets checked during sniffing to 2 would therefore result in high chances of false positives (i.e. `sniff()` returns true for non TS data).

**Comment by AquilesCanta** [comment]
My two cents. Falling back to TsExtractor has historic reasons (for example, #4033), and even though I agree falling back according to the extension is a reasonable improvement, there may be people relying on that mechanism now.

I would suggest considering the use of a custom extractor factory (which potentially wraps or forks the default one) so that you can use the fallback strategy you prefer until we are able to handle your usecase correctly in the library.

**Comment by kim-vde** [comment]
Regarding the content you provided: according to annex E of ISO/IEC 14496-12:2015, the brands in the input file serve as a permission to the reader to read the file. If a reader supports iso2-6 only, a file with brand iso9 only indicates that the reader shouldn't attempt to play the file. So I am not sure it is an improvement to fall back to the FragmentedMp4Extractor in this specific case.

**Comment by matamegger** [comment]
I see. Thanks for the insights.
> I would suggest considering the use of a custom extractor factory (which potentially wraps or forks the default one) so that you can use the fallback strategy you prefer until we are able to handle your usecase correctly in the library.

Sound very reasonable.

> Regarding the content you provided: according to annex E of ISO/IEC 14496-12:2015, the brands in the input file serve as a permission to the reader to read the file. If a reader supports iso2-6 only, a file with brand iso9 only indicates that the reader shouldn't attempt to play the file. So I am not sure it is an improvement to fallback to the FragmentedMp4Extractor in this specific case.

Well, "improvement".. taking just some other extractor seems more "wrong" than using at least the type specific one.
But I see all the points. Also given the history background and that real improvements would require a lot more structural changes.

Thanks for your feedback and time! From my side this can be closed :)
