### ISSUE TITLE
How play downloadable link to exoplayer from mega.nz server and degoo etc.

### ISSUE THREAD

**Issue by heinaungzan** [google/ExoPlayer#8223]
I want to play from my video from cloud server.But i have no idea how play(I can play video from gdrive and dropbox).
https://cloud.degoo.com/share/vzN4NqaAgv4vNZ  (degoo server download link)
https://mega.nz/file/ZgMhXYKS#WeeFfTd8DEjlD0QjR0XtvPEfEb2kwBQz8wtK7NBQeA0.   (mega.nz server download link)
Please help me.

**Comment by ojw28** [comment]
These are links to web pages from which you can start to download files. These are not directly playable by media players such as ExoPlayer. You need to provide ExoPlayer with a direct link to the media content itself.

How to get direct links to the media content from the download services you mention is a question for the providers of those services. Note that they may well deliberately design their service to not allow this or to make it difficult, for example because their business model relies on a user visiting the download web page so that they can display an ad. If this is the case then such services are not designed for what you're trying to do, and you may need to pay for hosting elsewhere.

Closing, since this is not an ExoPlayer question.

**Comment by master255** [comment]
@heinaungzan You need a special Mega.nz decryption library and a lot of coding.
