### ISSUE TITLE
SimpleExoPlayer.seekTo无效

### ISSUE THREAD

**Issue by MangoPuddings** [google/ExoPlayer#8247]
播放ADTS录音文件的时候，每次seekTo（）。都会重头播放

**Comment by icbaker** [comment]
Google translate:
>When playing an ADTS recording file, seekTo() every time. Will replay

**Comment by icbaker** [comment]
By default ExoPlayer doesn't support seeking in ADTS files. You can enable seeking by assuming that the file is constant bitrate (this will likely cause problems if the file is variable bitrate). See the ADTS row and footnote here:
https://exoplayer.dev/supported-formats.html#progressive-container-formats

When calling `SimpleExoPlayer.seekTo()` on non-seekable media, the expected behaviour is to restart playback from the beginning (as you observe).

To avoid accidentally calling `seekTo()` when playing non-seekable media, you can use `Player#isCurrentWindowSeekable()`, and only call `seekTo()` if this returns true.
