### ISSUE TITLE
when rotate video ,the size is false.

### ISSUE THREAD

**Issue by design365** [google/ExoPlayer#8248]
### [REQUIRED] Issue description
The size of the video is 6:9. When rotated by 90 degrees, the left and right sides of the video are not displayed completely, it seems to be cropped in the horizontal direction.

### [REQUIRED] Reproduction steps
set rotation:
mCropVideoView.getPlayView().getVideoSurfaceView().setRotation(90);
and set:
mPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT);
player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT);

every resize mode is also not working.

### [REQUIRED] Version of ExoPlayer being used
    api "com.google.android.exoplayer:exoplayer-ui:2.8.0"
    api "com.google.android.exoplayer:exoplayer-core:2.8.0"
### [REQUIRED] Device(s) and version(s) of Android being used
android 10. and 5.

**Comment by icbaker** [comment]
Based on the advice you received in #8099, I wonder if you're using `TextureView` rather than `SurfaceView`? If so, you should be using the [`setTransform()`](https://developer.android.com/reference/android/view/TextureView#setTransform(android.graphics.Matrix)) method Andrew linked there.

I wouldn't expect this line to successfully rotate the video in any case (that's just a method on Android's `View` class):
```
mCropVideoView.getPlayView().getVideoSurfaceView().setRotation(90);
```

Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by design365** [comment]
@icbaker 
I use TextureView.
the setTransform() method rotate， the video is stretched and deformed after rotating.
please check.
