### ISSUE TITLE
How to avoid small laggy when prepare the player?

### ISSUE THREAD

**Issue by kingfisherphuoc** [google/ExoPlayer#8269]
ExoPlayer Version: 2.12.1
Device OS: 8.0

In my application, I have an infinite animation. Actually, it's a `TextSwitcher`animation running from left to right. However, whenever I tried to prepare the player, I got a jitter issue with the text's animation. Although it's just a few milliseconds, it caused my texts was like jumping from left to right. Here's the prepare video method:

```
 private fun prepareVideo(uri: Uri): SimpleExoPlayer? {
        val simpleExoPlayer = SimpleExoPlayer
            .Builder(this) //                .setLoadControl(defaultLoadControl)
            .build()
        val mediaItem = MediaItem.fromUri(uri)
        simpleExoPlayer.setMediaItem(mediaItem)
        val eventListener: Player.EventListener = object : Player.EventListener {
            override fun onPlaybackStateChanged(state: Int) {
                if (state == ExoPlayer.STATE_READY) {
                    playVideo(simpleExoPlayer)
                }
            }
        }
        simpleExoPlayer.addListener(eventListener)
        simpleExoPlayer.playWhenReady = false
        simpleExoPlayer.prepare()
        showToast("Prepare video")
        return simpleExoPlayer
    }
```
P/s: I tried to record a video, but I cannot post it here. It's a demo, so I can provide the source code.
this is my demo UI:

![device-2020-11-23-231955](https://user-images.githubusercontent.com/962484/99986957-6bd65700-2de2-11eb-9056-1dde9f1a4e8d.png)

**Comment by AquilesCanta** [comment]
We will need a more precise question here. I don't think a sample app would be useful at this point, since it's not obvious this is an ExoPlayer issue. Please narrow down the cause of the issue and provide any evidence suggesting this is related to ExoPlayer. For example, things that I would check would be:
- Is the UI thread doing too much work?
- Is there any operation blocking the UI thread?
- Is the UI thread starving?
- Is there a CPU spike at some point?
- Does the issue change when playing media from different sources (for example, internet vs locally)?

Unfortunately, we cannot allocate resources to debugging apps provided through our issue tracker. We will be able to assist, however, with any well-scoped ExoPlayer issue or question, but in general, we can't do any debugging for you. Please provide more information below.

EDIT: Please consider also posting the question in a general Q&A site, like StackOverflow.

**Comment by kingfisherphuoc** [comment]
Hi, sorry for the delay. I found the issue. It's because of creating a new `SimpleExoPlayer`. It took around 200ms to create a player instance. I dont know why it took too long to do so. As a result, I created a player pool and reused them if needed.
