### ISSUE TITLE
Parameter specified as non-null is null.    Parameter format in onVideoFrameAboutToBeRendered

### ISSUE THREAD

**Issue by Turalllb** [google/ExoPlayer#8277]
![Снимок экрана 2020-11-25 в 10 57 20](https://user-images.githubusercontent.com/28982210/100198587-1185e500-2f0d-11eb-97f5-8a7b41501a26.png)

Occurs when the player is opened.  This is quite critical, I don't see any ways to protect it from the application.  version 11.7

**Comment by Turalllb** [comment]
Occurs when the player is opened

**Comment by AquilesCanta** [comment]
If I understand the screenshot correctly, you are able to reproduce the problem locally. If that's the case:
- Please never provide a screenshot of a logcat, copy-pasting the logcat text is better in every way.
- Please provide reproduction steps, as requested in the issue template. If you cannot provide reproduction steps, please explain why. Any and all context is useful here for us to efficiently use our time to help you.
- Please try reproducing in the newest release version of ExoPlayer, and ideally in the dev branch so that we can rule out the possibility that it has been fixed since that version, which is now considerably old.

**Comment by Turalllb** [comment]
I cannot do this yet, in version 2.12.0, there are significant changes in the work with drm.  I'll open the question a little later
