### ISSUE TITLE
How do I keep playback going once the screen locks (but not when the user navigates to a different fragment/activity)?

### ISSUE THREAD

**Issue by sedubois** [google/ExoPlayer#8279]
### Searched documentation and issues

- https://exoplayer.dev/troubleshooting.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded
- https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b
- https://github.com/google/ExoPlayer/issues/7987
- I also asked help on StackOverflow: https://stackoverflow.com/q/64956508/4623987

### Question

Having ExoPlayer smoothly continue playback when the device screen is locked/unlocked requires handling many details such as:
- managing permissions
- starting the service
- configuring and managing the notification
- adapting the actions to be taken in the player activity's lifecycle
  - not releasing player if it is playing and the screen gets locked
  - but still releasing player if player view is instead exited with back button
  - making sure playback continues smoothly when unlocking the screen instead of jumping back where it was before screen got locked
  - handling possible differences between media types, e.g. audio vs. video
  - avoiding crashes ...

It would be extremely helpful if there existed a version of the "official" demo showing this case, so that there is a reference available for implementation in our own apps.

Here is what I got so far:
https://github.com/sedubois/ExoPlayer/compare/release-v2...sedubois:background-playback

The notification works OK, however I don't know how to adapt the activity code to make sure the player keeps playing or gets released when it should. Furthermore if I "simply" add a check `!player.isPlaying()` in onPause/onResume, then the playback does continue smoothly when locking the screen, but it leads to other issues, e.g. the app crashes when exiting the player, and when unlocking the screen during playback, the playback position jumps backwards to where it was when the screen had gotten locked.

Would it be possible to have support in order to clear up those details? May I open a PR with the above branch to kick off a discussion?

Thank you very much for your time.

**Comment by AquilesCanta** [comment]
There's no official audio demo app yet. I'm sure you are already aware of [UAMP](https://github.com/android/uamp), though. It's not maintained by the ExoPlayer team, but it showcases solutions involved in the creation of an audio app, many of which are listed above. How would your proposal differ from UAMP?

**Comment by sedubois** [comment]
Thank you @AquilesCanta, I've never tried that demo. However this request is not specific to audio. Our app plays both audio and video and should support both, that is why we basically made it as a clone if the ExoPlayer main demo app. 

If a video is being played, it should continue playback when screen is locked, just like with audio. (The only optimization would be, if there is a way to do so, to stop transmitting video data while the screen is locked and only transmit audio. But that is for me beyond the scope of what is asked here.)

**Comment by AquilesCanta** [comment]
> However this request is not specific to audio

Ah, missed that part. Thanks for the clarification.

To get this out of the way, I don't think we will be adding background playback to ExoPlayer's main demo app since it's already more complex than many of our users would like. We have discussed the creation of new demo apps to show case other aspects of the library, but I don't think background playback with video was one of them. I don't know if it was not deemed meaningful/complex enough, but it hasn't been discussed as far as I can tell.

> The notification works OK, however I don't know how to ...

The issues described sound like lifecycle management and surface management issues to me. I think we can assist you given a scoped question and the right amount of context. Also stack overflow may be an even better place to start, since some issues may not even be related to ExoPlayer specifically. Other than that, I don't think we have the bandwidth to provide more general support than this, or plans for a new demo app in this area for the time being.

Am I misunderstanding the proposal? Is there something concrete for us to do about this issue? Perhaps someone from my team can chime in to provide their point of view.

**Comment by sedubois** [comment]
Thank you @AquilesCanta 

> I don't think background playback with video was one of them

Once again the request here has nothing specific to video or audio, and I would expect this to get reflected in the implementation. The ExoPlayer main demo already essentially does not distinguish much between audio and video, which I find a great strength. This is the primary reason why we were able to integrate it in our app and avoid the complexity of having separate codebases for audio and video players.

This request is to fulfill a basic expectation from our users, that playback should continue even if the screen gets locked, whatever is being played (but then the user can monitor and control the playback from the notification area). This is for instance so that they can put their device in their pocket, keep their hands free, do some other activity, save battery, etc.

> I think we can assist you given a scoped question and the right amount of context.

Sure, let's try to break down the questions one by one. First, based on what is already done in https://github.com/sedubois/ExoPlayer/compare/release-v2...sedubois:background-playback, how to ensure the player keeps running when minimising the app or locking the screen, but still stopping and releasing the player if the user navigates away from the player screen but stays in the app (i.e., by tapping the "back" button)?

> Also stack overflow may be an even better place to start

The question is [also on StackOverflow](https://stackoverflow.com/questions/64956508/android-exoplayer-demo-continue-playback-with-screen-locked), in case you would prefer continuing there.

Thank you very much!

**Comment by AquilesCanta** [comment]
> how to ensure the player keeps running when minimising the app or locking the screen

You need to create a service, like [UAMP](https://github.com/android/uamp) does. Otherwise, the system may choose to kill your app.

> but still stopping and releasing the player if the user navigates away from the player screen

When you detect that the user navigates away from your fragment, you need to tell the component owning the player (which probably runs on the playback service) to pause or release the player. This step is unrelated to ExoPlayer and there is literature available in the android documentation webpages. Example: https://developer.android.com/guide/navigation/navigation-custom-back.

Assigning @dturner in case he has something to add.

EDIT: Can't assign @dturner, I'll close once he responds here.

**Comment by sedubois** [comment]
> You need to create a service

This is done already: https://github.com/sedubois/ExoPlayer/compare/release-v2...sedubois:background-playback#diff-9a0c7dc9f52200b2c99a7e7ba7bbd7770d2bcd467e8d23a1ff1fd96f534bd228R320

NB: when I comment out `releasePlayer()` in `onStop()`/`onPause()`, I can already observe that playback continues once the screen gets locked, so this confirms the service is running. (However it also continues playback when navigating away from the player within the app itself; then if the player is re-entered, the app crashes, hence the next question about differentiating between back navigation and locking screen.)

> you need to tell the component owning the player (which probably runs on the playback service) to pause or release the player ... Example: https://developer.android.com/guide/navigation/navigation-custom-back

Thank you very much, I will try to use `requireActivity().onBackPressedDispatcher.addCallback` as suggested and report back here.

**Comment by dturner** [comment]
I agree with @AquilesCanta. Move the responsibility of playback into a service, specifically a [`ForegroundService`](https://developer.android.com/guide/components/foreground-services), this is able to continue playing when the screen is locked.

Take a look at the `MusicService` class in UAMP for a reference implementation: https://github.com/android/uamp/blob/main/docs/FullGuide.md#musicservice

**Comment by AquilesCanta** [comment]
> This is done already:

Yeah, I'm sorry I didn't have a look. Along the same lines, we cannot assist ExoPlayer users in general Android development practices. This is more related to Android Activity lifecycle than it is about ExoPlayer. If you have issues which relate specifically to ExoPlayer, or questions around the ExoPlayer API, we can help. Otherwise, please continue using Stack Overflow or other relevant projects available on github.
