### ISSUE TITLE
Rare failed assertions

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#8283]
### [REQUIRED] Issue description
I'm getting some errors reported to crashlytics due failing assertions.
Here are 3 different issues, I can move them to separate issues if it makes sense and if any work will be made for them

#### DefaultAudioSink.getEncodingAndChannelConfigForPassthrough
```
Non-fatal Exception: java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:203)
       at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
       at com.google.android.exoplayer2.audio.DefaultAudioSink.getEncodingAndChannelConfigForPassthrough(DefaultAudioSink.java:1434)
       at com.google.android.exoplayer2.audio.DefaultAudioSink.isPassthroughPlaybackSupported(DefaultAudioSink.java:1412)
       at com.google.android.exoplayer2.audio.DefaultAudioSink.getFormatSupport(DefaultAudioSink.java:474)
       at com.google.android.exoplayer2.audio.DefaultAudioSink.supportsFormat(DefaultAudioSink.java:450)
       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.shouldUseBypass(MediaCodecAudioRenderer.java:305)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:560)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2173)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:852)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```
```
EventLogger: videoEnabled [eventTime=1677.70, mediaPos=0.00, window=0, period=0]
EventLogger: audioEnabled [eventTime=1677.70, mediaPos=0.00, window=0, period=0]
EventLogger: tracks [eventTime=1677.70, mediaPos=0.00, window=0, period=0
EventLogger:   MediaCodecVideoRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=1/256, mimeType=video/avc, codecs=avc1.64002A, res=1920x1080, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   MediaCodecAudioRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=1/257, mimeType=audio/ac3, channels=2, sample_rate=44100, language=en, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   FfmpegAudioRenderer []
EventLogger:   TextRenderer []
EventLogger:   MetadataRenderer []
EventLogger:   CameraMotionRenderer []
EventLogger: ]
EventLogger: downstreamFormat [eventTime=1677.71, mediaPos=0.00, window=0, period=0, id=1/256, mimeType=video/avc, codecs=avc1.64002A, res=1920x1080]
EventLogger: videoDecoderInitialized [eventTime=1677.74, mediaPos=0.00, window=0, period=0, OMX.Nvidia.h264.decode]
EventLogger: videoInputFormat [eventTime=1677.74, mediaPos=0.00, window=0, period=0, id=1/256, mimeType=video/avc, codecs=avc1.64002A, res=1920x1080]
EventLogger: downstreamFormat [eventTime=1677.74, mediaPos=0.00, window=0, period=0, id=1/257, mimeType=audio/ac3, channels=2, sample_rate=44100, language=en]
EventLogger: audioInputFormat [eventTime=1677.74, mediaPos=0.00, window=0, period=0, id=1/257, mimeType=audio/ac3, channels=2, sample_rate=44100, language=en]
EventLogger: audioSessionId [eventTime=1677.76, mediaPos=0.00, window=0, period=0, 393]
EventLogger: audioInputFormat [eventTime=1677.76, mediaPos=0.00, window=0, period=0, id=1/257, mimeType=null, channels=4, language=en]
EventLogger: videoDisabled [eventTime=1677.78, mediaPos=0.00, window=0, period=0]
EventLogger: audioDisabled [eventTime=1677.78, mediaPos=0.00, window=0, period=0]
```

### [REQUIRED] Reproduction steps
Callstacks are from automatic error reports and I can not reproduce them locally

### [REQUIRED] Link to test content
Errors are from automatic error reports and I do not own media

### [REQUIRED] A full bug report captured from the device
n/a

### [REQUIRED] Version of ExoPlayer being used
r2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
BRAVIA 4K GB ATV3, Xiaomi MiBox S, NVidia Shield TV

**Comment by AquilesCanta** [comment]
Yes, I think it's better if we split this into two. I'll modify this issue to keep the `DefaultAudioSink.getEncodingAndChannelConfigForPassthrough` here, and you can file a fresh issue for the TS issue. Thanks for the report.

**Comment by AquilesCanta** [comment]
@krocard mind taking a look into this? I suspect this assertion failure is caused by `Assertions.checkNotNull(format.sampleMimeType)`. We should figure out under what circumstances that may happen. Or perhaps there's a better candidate cause for the assertion failure?

**Comment by krocard** [comment]
An audioformat must always contain a `sampleMimeType`  as checked at the last line of:
https://github.com/google/ExoPlayer/blob/ffea2a64b30f40bb298a6f97b9a0ec828312c138/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L1445-L1453
is the new input format passed to `MediaCodecRenderer.onInputFormatChanged`
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L554-L560

This format comes from the `upstreamFormat` in the sample queue which was set from the `AC3Reader`.
The `AC3Reader` reader always call sets `sampleMimeType ` as can be seen here:
https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/Ac3Reader.java#L205-L213

This means `frameInfo.mimeType` must have been null. This value comes from:
https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/common/src/main/java/com/google/android/exoplayer2/audio/Ac3Util.java#L433-L441
So the null value is intentional to disable rendering. 

Nevertheless, I could not find where such disabling logic is implemented, it seems like it is missing to avoid this crash.

@tonihei could you take a look? You added this code in https://github.com/google/ExoPlayer/commit/afd9014b823a3ff194a6f410cefe4bed53280693 for #5638. Do you remember which component was expected to reject the format?

**Comment by tonihei** [comment]
> Do you remember which component was expected to reject the format?

The track selection wouldn't select the audio renderer for a null sampleMimeType. 
Regardless of that, it should be more robust to just return false from supportsFormat if the mimeType is null. WDYT?

**Comment by krocard** [comment]
After discussion with @tonihei, we think that the issue is that the AC3 changed format during playback to a fscod 3. which should stop playback. Unfortunately this is not something that is supported and while it would be preferable to run the track selector again on such format change, this is not how the current format change architecture is designed.

The solution we are going for is to stop playback by throwing a Renderer Exception instead of the current NPE.

If the playback interruption is an issue is what should be a very rare situation, we could have a playback retry, but I'm concern it would result in a retry infinite loop if the retry seeks just before the format change.
We would need the problematic media to test this retry, in its absence, we will just interrupt playback.

**Comment by krocard** [comment]
@stari4ek do you have access to a sample to confirm that the workaround fixes the issue?

**Comment by stari4ek** [comment]
Sorry, I do not have access to stream. Got report from crashlytics.

**Comment by ojw28** [comment]
> The solution we are going for is to stop playback by throwing a Renderer Exception instead of the current NPE.

I think this was implemented by the change ref'd above. Since we don't have a test stream, I don't think there's much more to do here.
