### ISSUE TITLE
Audio duration is not right

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#8284]
When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Issue description
when I play audio with url, found the duration is not right. Exoplayer returned duration is 82 mins 20 secs, but actually the duration is 82 mins 32 secs which could be verified by quick time on mac.
the url: https://media.xiaoyuzhoufm.com/aHR0cHM6Ly9ob3N0aW5nLnNoZW5nZm0uY24vcG9kY2FzdC1kb3dubG9hZC8zMjYvNTItJWU3JTk2JWFiJWU4JThiJTk3JWU3JThlJWIwJWU5JTg3JThkJWU1JWE0JWE3JWU4JWJmJTliJWU1JWIxJTk1JWVmJWJjJThjJWU3JWJlJThlJWU0JWI4JTgwJWU3JWJhJWJmJWU0JWI4JTkzJWU1JWFlJWI2JWU1JWE2JTgyJWU0JWJkJTk1JWU4JWE3JWEzJWU4JWFmJWJiLm1wMw==.mp3

### [REQUIRED] Reproduction steps
play the above url audio link.

### [REQUIRED] Link to test content
https://media.xiaoyuzhoufm.com/aHR0cHM6Ly9ob3N0aW5nLnNoZW5nZm0uY24vcG9kY2FzdC1kb3dubG9hZC8zMjYvNTItJWU3JTk2JWFiJWU4JThiJTk3JWU3JThlJWIwJWU5JTg3JThkJWU1JWE0JWE3JWU4JWJmJTliJWU1JWIxJTk1JWVmJWJjJThjJWU3JWJlJThlJWU0JWI4JTgwJWU3JWJhJWJmJWU0JWI4JTkzJWU1JWFlJWI2JWU1JWE2JTgyJWU0JWJkJTk1JWU4JWE3JWEzJWU4JWFmJWJiLm1wMw==.mp3

### [REQUIRED] A full bug report captured from the device
none

### [REQUIRED] Version of ExoPlayer being used
2.11.8

### [REQUIRED] Device(s) and version(s) of Android being used
this issue is not related with specific device

**Comment by AquilesCanta** [comment]
I don't know how QuickTime or VLC calculate the duration, but this file is an mp3 file with no duration metadata, so any provided duration is served on a best-effort basis. Just for the record, ffplay calculates a similar duration to ExoPlayer (Duration: 01:22:20.47), so I'm not 100% convinced this difference is caused by ExoPlayer doing something wrong, but rather using a constant bitrate approach similar to what ffplay does.

We are happy to take action if we know precisely what we may improve. In this case, ExoPlayer's best effort duration doesn't match some players' duration (while it does match others). If you can provide an efficient way in which we might improve the current approach, we will take a look into it. For instance, an approach that will not work for us would be downloading the entire stream to calculate the sum of each sample's duration.

**Comment by tuesda** [comment]
@AquilesCanta Thanks for your response, I will close this issue.
