### ISSUE TITLE
Subtitles can be cropped - why is SubtitleView inside AspectRatioFrameLayout?

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8293]
When I use ``styledPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM)``, it sizes video the way I want but it can also cause the subtitles to be cropped outside the screen.

I can fix that by taking out ``SubtitleView`` from ``AspectRatioFrameLayout`` and putting it just outside of it (in [exo_styled_player_view.xml](https://github.com/google/ExoPlayer/blob/r2.12.1/library/ui/src/main/res/layout/exo_styled_player_view.xml)). 

I wasn't able to find any information on subtitles in relation to resizing player view. Is there any reason for ``SubtitleView`` to be inside of ``AspectRatioFrameLayout`` (because of something like TV screens) or could it possibly be a bug?

This behaviour can be replicated in the ExoPlayer demo by putting ``app:resize_mode="zoom"`` inside ``StyledPlayerView`` of ``player_activity.xml``.

![Screenshot_20201128-222950](https://user-images.githubusercontent.com/1071643/100526784-76229780-31cc-11eb-9f0d-5e863de1bf09.jpg)

![Screenshot_20201128-223008](https://user-images.githubusercontent.com/1071643/100526789-7de23c00-31cc-11eb-8723-6d683c2b8a91.jpg)

Possible related issue from other library using ExoPlayer: react-native-video/react-native-video#1491

**Comment by AquilesCanta** [comment]
@icbaker, would you mind taking a look at this?

**Comment by icbaker** [comment]
Thanks for the report - I can reproduce what you're seeing.

I don't know if this is WAI/expected :) It's honestly kinda tricky to reason about...

Some subtitles will have been carefully designed to line up exactly with in-video content (e.g. the translation for a sign, especially in anime), so they **need** to be transformed with the video like you're seeing (otherwise they won't be in the right place).

But in other cases the subtitles often just need to appear "somewhere visible".

Some open questions I need to think more about:
* Do 'precisely positioned' subtitles also need to be enlarged? Maybe some of the proportional ways of setting subtitle font sizes could be updated to consider screen heigh/width somehow.
* `SubtitlePainter` already has logic to override subtitle layout info if it would result in drawing the subtitle outside the video viewport. Maybe this logic could be updated to consider the actual screen edge as well.
  * The size question above is relevant here, because doing nothing about the size would cause the screenshot above to overflow to two lines, whereas it might be preferable (in this case) to keep it all on one line by making the text smaller.

So at first glance I'm not sure just moving the `SubtitleView` outside of the `AspectRatioFrameLayout` will work in the general case - it's an interesting proposal though, thanks for suggesting it.

**Comment by moneytoo** [comment]
Thank you for the info.

One more thing that comes to my mind regarding different sizing of video view vs subtitle view are displays with cutouts. You may want (depending on the type of video of course) to expand video view across the whole screen but inset subtitle view to make sure it's always fully visible.

**Comment by nigelmegitt** [comment]
@moneytoo There's provision for this kind of thing in IMSC: if present, the (optional) [`ittp:activeArea`](https://www.w3.org/TR/ttml-imsc1.2/#ittp-activeArea) attribute provides guidance to players about which parts of the rendering area actually contain subtitles. The same attribute is also included in [EBU-TT-D (PDF)](https://tech.ebu.ch/docs/tech/tech3380v1_0_1.pdf)

Normally with positioned subtitles the goal is to specify the subtitle rendering area to be coincident with the video. If for some reason, as you suggest, not all of the video is visible, then you need to make a decision about whether a) to make the subtitle rendering area match the video, and then crop it, so that positional alignment is retained, or b) to scale the subtitle rendering area so that it fits, and reduce the accuracy of the positional alignment. With a), if you don't have any further information, you risk cropping some of the subtitles too, so they aren't all readable.

Of course there's an option c) which is to partially scale just to ensure there's no cropping of subtitles, but still crop some of the subtitle area afterwards.

In terms of text height, that's defined in IMSC (and EBU-TT-D) as being relative to the subtitle rendering area height, so it should scale proportionally.

**Comment by moneytoo** [comment]
Now I also understand that while my "hack" works as I want to for majority of media (with text subtitles), it doesn't play nice with PGS subtitles (as sample from #3008) - they are stretched according to its View.
