### ISSUE TITLE
Play the HLS video

### ISSUE THREAD

**Issue by jianxiaobai999** [google/ExoPlayer#8311]
How can I make the cache last while playing HLS video so I can play it smoothly

**Comment by christosts** [comment]
The question is not clear to me, especially what exactly you mean by `play it smoothly`. Can you please provide more information about the setup and the expected behavior? For questions, we have an issue template that can assist figuring out what to information to include. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).
