### ISSUE TITLE
Crypto key not available occurs when playing Widevine DASH on a specific device

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#8319]
The conversation in Issue #7356 was locked, I created a new Issue.

<br>

> Do i have your permission to share the bugreport and repro steps that you mentioned in the email with Sony?

I am very sorry that I took so long. I have received permission to share the bugreport and repro steps with Sony, so please share it.

<br>

> Also the license expiration date is 2020-06-18. Is it possible to extend it or share different content so that we/Sony can repro?

We have sent content with a license expiration date of `2020-06-01 00:00:00` to dev.exoplayer@gmail.com.
Please use this content.

Thanks in advance

**Comment by Daphne-CoffeeIT** [comment]
I have the same issue on a Samsung Galaxy A40 (SM-A405FN) which runs on Android 10. The first time after I restarted the phone, I am able to play the Widevine DASH asset, but after the first time it gives me the "Crypto key not available" error. Are there any updates on this issue?

**Comment by vhly** [comment]
Hi all,

I had spent long time to fix this exception,
and I collected some information for it.

First, some info for you:

1. If ClearKey DASH asset, Don't use LocalMediaDrmCallback, it's bad for some Android device, because Low level drm implement not support multi key response in one request;
2. When network change or dash sub video size change, the drm session manager need get video key again, but pre load key is not exists, I think drm key in secret memory or device secret region has some timeout.
3. I think your video has first clear content not encrypt, for example you use ShakaPackager with -clearlead parameter, I had some videos encrypted with first 30s clear, (-clearlead 30 ), and played with Exo Player always throw "Crypto key not available" Exception. I think 30s clear duration is bad, but I want to do this. So I change my MediaDrmCallback implement with "One Request return One Response Key", and then , It well done.
4. I don't have Widevine license, so I can't test it for this issue. but I think it will be ok. And I suggest you use ExoPlayerDemo to Test your videos and LicenseServer. 
5. I think Widevine System will ok than ClearKey implement.

Second, there is a website [blackfire.mobi](https://blackfire.mobi) (Chinese) to show how to fix this issue with ClearKey system.
I think this will show some Information to you.

**Comment by AquilesCanta** [comment]
Hi @ogawa-ma, are you still seeing this issue?  Would you kindly share a new sample stream (ideally which does not expire) so that we can forward the report to Sony?

**Comment by ogawa-ma** [comment]
@AquilesCanta 
Hi.
I apologize for the delay in getting back to you.
It's still seeing this issue.
I have sent the information about the streams that have not expired to your dev.exoplayer@gmail.com.

**Comment by AquilesCanta** [comment]
Hi @rrfrias, we have sample content (expires a year from now, under subject Issue #8319) and a bugreport (under subject Issue #7356). Do you think it's enough to forward the issue to Sony? Can you assist with this device-specific issue?

**Comment by rrfrias** [comment]
We will work with Sony to investigate this issue

Internal ref: 188626755

**Comment by rrfrias** [comment]
The device (SOV34) launched in Oct, 2016. Sony might not be able to fix the issue because the product has been reached the end of product life already. Are you seeing this issue on a more recent device than Xperia XZ(OS:8.0.0)?

**Comment by rrfrias** [comment]
@ogawa-ma, if you are able to reproduce this on a more recently released device, do open another tracker.

**Comment by ogawa-ma** [comment]
@rrfrias 
I'm sorry I was late.
It was not happening on devices newer than Xperia XZ (OS: 8.0.0).
I understood that Sony cannot resolve this issue as this product has already reached the end of its product life.
Thank you for your confirmation.
