### ISSUE TITLE
Multiple player surfaces will exceed the screen width

### ISSUE THREAD

**Issue by MenShengSeLang** [google/ExoPlayer#8325]
The width of the callback on onSurfaceSizeChanged exceeds the screen，Is there a good solution?I am using com.google.android.exoplayer2.ui.PlayerView

**Comment by krocard** [comment]
I'm expecting that a surface can be partially/totally offscreen with a size exceeding the screen. Nevertheless in my limited experience with `PlayerView` it was not bigger than the screen.
Maybe @ojw28, would know how it can happen?

**Comment by krocard** [comment]
@zdxhrjgc Could you explain what you mean by "multiple player surfaces"? Is your app showing multiple players?

It would be great if you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ojw28** [comment]
> I'm expecting that a surface can be partially/totally offscreen with a size exceeding the screen

This can happen if you're using a non-standard resize mode (set by calling `PlayerView.setResizeMode`, or by using the `resize_mode` attribute in a layout file). If your application is doing this, then it's possible that what you're seeing is working as intended.

Note also that some devices run their UI layer at a lower resolution than the physical resolution of the display. This is typically the case for some TVs, where the UI layer is run at 1080p but it's possible for `Surface` content to be displayed at 4K. If "exceeds the screen" means "exceeds the resolution of the UI layer" rather than "exceeds the physical resolution of the display", then I think what you're seeing could also be working as intended in this case too.

If the above information doesn't help, I think you'll need to provide a small demo along with clear reproduction steps that make it easy for us to reproduce exactly what you're seeing. This will allows us to explain why you're seeing what you're seeing in the specific case you're interested in. Please include full details of the device you're able to reproduce the issue on as well.

I would also note that it's unclear exactly what issue you're trying to fix. A number being larger than you expect isn't in itself a problem. Presumably it becomes a problem when you then try and use that number to do something, but you haven't included any information about what you're trying to do.
