### ISSUE TITLE
MediaCodec.setOutputSurface

### ISSUE THREAD

**Issue by Turalllb** [google/ExoPlayer#8329]
We already know about this problem and there are quite a few already closed issues. The problem is that some devices do not support DummySurface. And you need to be careful when working with the PlayerLayerView, if you set it visibility to GONE while the player is running, then we will get the below exception. If we pause the video, we need to wait for an unknown time (about 2 seconds on android TV devices) before we can block the visibility of GONE. All these problems can be solved, for example, we can use alpha instead of visibility to hide the display when we need it (There are cases when it is needed). But there is a case when I cannot solve the problem: The video is playing, the application is minimized, in onPause before calling super.onPause I execute exoPlayer.playWhenReady = false. But I will still get the following exception in the logs and when I deploy the application I will have a black screen on some devices. Why am I not listing what devices they are? Because there have already been many questions related to this exception, which you closed with crutches.  Tell me how best to get out of the situation when you need to minimize the application on such a problematic device and not get a black screen when you deploy the application?

java.lang.IllegalArgumentException
at android.media.MediaCodec.native_setSurface(Native Method)
at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1979)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1308)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:627)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:593)
at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1022)
at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:988)
at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:970)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:367)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:65)

The problem exists on exoplayer 11.7, I'm almost sure that in version 12, you did not fix it and it may not be fixed due to problems with MediaCodec

p.s. Conducted an experiment: Paused the video, waited 10 seconds, minimized the application. PlayerLayerView continues to exist, this is a TV and there are no screen rotations, but I get the same exception in the logs.

I researched a little the question, when the player is paused and I minimize the application, then this code is executed:

![Снимок экрана 2020-12-08 в 15 06 46](https://user-images.githubusercontent.com/28982210/101482436-c980ac80-3967-11eb-8b33-aefabb7b699c.png)
![Снимок экрана 2020-12-08 в 15 11 42](https://user-images.githubusercontent.com/28982210/101482451-cf768d80-3967-11eb-8a7c-acc7a55dc2b4.png)

**Comment by Turalllb** [comment]
I will give a couple of examples where this bug was discussed and steps were given to reproduce the problem: https://github.com/google/ExoPlayer/issues/6930     https://github.com/google/ExoPlayer/issues/677  https://github.com/google/ExoPlayer/issues/2703

**Comment by Turalllb** [comment]
I tried to check how it works on YouTube. After I pause, minimize the application and re-deploy, they ignore my user pause and apparently re-do exoplayer.prepare (mediaSource)

**Comment by krocard** [comment]
This is a known bug of some implementations of some platform video codecs. ExoPlayer can not fix it, only workaround it by releasing the codec and then re-initializing it instead of setting the outputSurface:
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L515-L520

Unfortunately, we can only find out which [problematic decoders to workaround](https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1578) through issues like yours.

You may try to enable the workaround by adding your problematic device [here](https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1621). If it solves your issue, please let us know so that we can add it the list for the next ExoPlayer version.

**Comment by Turalllb** [comment]
@krocard  Please clarify if I understood you correctly. In such situations, you check if the device is included in your list of problem devices and if it is found there, then mediaKodec is released, if it is not in the list, but the device has problems, I will get this exception

**Comment by krocard** [comment]
Exactly. We have a list devices known to not support `setOutputSurface`. For them we use the inefficient workaround of destroying and recreating the codec.

If a device has this `setOutputSurface` issue, but is not on the list, the workanourd will not be used and this `IllegalArgumentException ` will be thrown.

If you could please answer the device you are observing the issue on, as well as it's android version, we will update this list and you should no longer see the issue.

**Comment by Turalllb** [comment]
@krocard   the problem device  Xiaomi Mi Box S, In the settings, the model is called MIBOX4

**Comment by krocard** [comment]
Do you also know the android version this issue is observed on?

**Comment by Turalllb** [comment]
in 9 android

**Comment by Turalllb** [comment]
You can give me a release branch and I will test it on this device

**Comment by krocard** [comment]
I have created a branch on my fork for you to test over 2.12.2: https://github.com/krocard/ExoPlayer/tree/mi-box-s-set-surface-workaround. The fix is https://github.com/krocard/ExoPlayer/commit/e27732f5987eb2a32a722b1c75e9abed5d188349.

I believe the `DEVICE` value is [oneday](https://storage.googleapis.com/play_public/supported_devices.html#:~:text=MIBOX4). Looking at the [official list of android devices](https://storage.googleapis.com/play_public/supported_devices.html#:~:text=dangal,magnolia), we can see that similar (dangal, magnolia...) Xiaomi devices are already workaround:
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1579-L1594

`oneday` probably shares the same decoder, so it make sense to workaround it too.

I'm wondering if the MiBox 1,2,3 and mini also share the same bug.

[internal change cl/347975125]

**Comment by Turalllb** [comment]
@krocard, Hi,  sorry for taking too long. 
Yes, I checked the Device value, it is oneday. Unfortunately, we do not have these MiBox 1,2,3 and mini devices.   
I tested on MiBox s, it really stopped crashing. 
Since my project uses version 2.11.7, and the transition to 2.12. + Due to changes in working with the drm is not very fast, I tested it on the 2.11.7 branch, adding your code. The screenshot shows the result. And it worked.

Tell me in which version we can expect this change. Thank you

**Comment by krocard** [comment]
The fix should be present in the next minor release 2.12.3.

**Comment by wazerstar** [comment]
#

> 
> 
> @krocard, Hi, sorry for taking too long.
> Yes, I checked the Device value, it is oneday. Unfortunately, we do not have these MiBox 1,2,3 and mini devices.
> I tested on MiBox s, it really stopped crashing.
> Since my project uses version 2.11.7, and the transition to 2.12. + Due to changes in working with the drm is not very fast, I tested it on the 2.11.7 branch, adding your code. The screenshot shows the result. And it worked.
> 
> Tell me in which version we can expect this change. Thank you



> 
> 
> @krocard, Hi, sorry for taking too long.
> Yes, I checked the Device value, it is oneday. Unfortunately, we do not have these MiBox 1,2,3 and mini devices.
> I tested on MiBox s, it really stopped crashing.
> Since my project uses version 2.11.7, and the transition to 2.12. + Due to changes in working with the drm is not very fast, I tested it on the 2.11.7 branch, adding your code. The screenshot shows the result. And it worked.
> 
> Tell me in which version we can expect this change. Thank you

I have an Mibox 3, I can test with if needed you can also get control over it via remote if needed, not sure what I would be doing here to help out.

**Comment by krocard** [comment]
2.12.3 was released a few weeks ago. If the issue is still observed on it or a more recent version, please reopen the issue.
