### ISSUE TITLE
ExoPlayer 2.12.x How to detect transitions between media periods

### ISSUE THREAD

**Issue by KarlGallagher** [google/ExoPlayer#8335]
Hello,

In earlier versions of ExoPlayer we are leveraging OnMediaPeriodCreated/Released from the AnalyticsListener interface to determine when the player transitions between media periods.  We use this to manage our SSAI solution so that transitioning into periods that contain ad meta data results in calls to our ad monitoring platform.

This is removed from the interface in 2.12.x

Is there any indirect/direct replacements for this functionality,  how in general is the best way to detect period transitions?
Thanks.

**Comment by krocard** [comment]
@marcbaechinger, for context you removed `OnMediaPeriodCreated ` in https://github.com/google/ExoPlayer/commit/f81a353bf8bf58358517bd6b8bd780fd50f0517c.

**Comment by marcbaechinger** [comment]
For identifying playback of ads I think you can use `AnalyticsListener.onPositionDiscontinuity(EventTime eventTime, @DiscontinuityReason int reason)`. There is a reason `Player.DISCONTINUITY_REASON_AD_INSERTION` of which the java doc says:

```
/** Discontinuity to or from an ad within one period in the timeline. */
int DISCONTINUITY_REASON_AD_INSERTION = 3;  
```

The `EventTime` object passed to the callback gives you more details, like the `MediaPeriodId` with the ads information, so it allows you to identify transitions from media to ad and back.

Please let me know if that works for you.

Aside: I think the `onMediaPeriodCreated/Released` that you used before is actually less precise because at least in theory the creation of the media period does not necessarily mean it is actually played.

**Comment by marcbaechinger** [comment]
I need to add some clarifications for your use case with SSAI that I did not realize and cover in my previous comment.

In case you are using eg. a multi-period DASH stream to insert ads, the player is not aware whether a given period is content or ad. So my comment regarding `DISCONTINUITY_REASON_AD_INSERTION` is misleading.  You also will not find any ad properties in the `MediaPeriodId` in such cases.

When you are using server side ad insertion, period transitions are always notified with `DISCONTINUITY_REASON_PERIOD_TRANSITION` in all cases because the player does not know whether it's an ad or not. Hence you need to listen to position discontinuities of type `DISCONTINUITY_REASON_PERIOD_TRANSITION` and then figure out whether it is an ad according to what you expect from your manifest.

**Comment by KarlGallagher** [comment]
@marcbaechinger Thank you have the detailed explanation.

Closing this

**Comment by karlg-arris** [comment]
Closed as answered
