### ISSUE TITLE
Weird behaviour when seek operation is performed while playing preroll ad.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#8349]
Steps to Reproduce.

1. Play any video with preroll.
2. Seek when player is in ready state.  Please add following code in PlayerListener of demo app

```
 @Override
    public void onPlaybackStateChanged(@Player.State int playbackState) {
      if (playbackState == Player.STATE_READY) {
        player.seekTo(20_000);
      }
}
```

Observe player goes into weird state. Ad gets skipped and play randomly along with content.

100% reproducible on latest version of exo-player.

I understand exoplayer doesn't support seek during ads, but there is already a warning for this. performing this operation should not cause this issue.

**Comment by krocard** [comment]
I have added the seek on STATE_READY in the demo app but the seek was ignored as expected:
```
D/EventLogger: state [eventTime=0.90, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, READY]
D/EventLogger: seekStarted [eventTime=0.90, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0]
W/ExoPlayerImpl: seekTo ignored because an ad is playing
```

Please provide the media with the prerolled media so we can reproduce and a bug report.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by sravan1213** [comment]
Hi @krocard ,

Attached video and logs for reference. In the video you can observe first preroll is completed before second preroll started and video got stuck at 1st mid-roll. 

Also attaching patch for seek logic.

Hope this helps 
[issue_8349.zip](https://github.com/google/ExoPlayer/files/5700455/issue_8349.zip)

**Comment by krocard** [comment]
Thank you, I managed to reproduce the issue.

The issue is due to `pendingOperationAcks` being incremented even if the seek is ignored. When the seek is ignored, an updatedPlaybcak info is sent with an `operationAcks` of 0.
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L598-L607

This lead to ExoPlayer considering that an operation is still in flight, and `playbackInfo` is no longer updated.

We could call `incrementPendingOperationAcks(1)` on the sent `PlaybackInfoUpdate`, but I'm not sure it is the right thing to do because it also sets `hasPendingChange`, which is not true.

This regression was introduced by b1e9257de143e9f377895b63868ef47b4fc0eea9 in 2.12.0.

@icbaker could you take a look.
