### ISSUE TITLE
Question: Is there any reason to keep "multiSession" flag in DefaultDrmSessionManager?

### ISSUE THREAD

**Issue by linhai326** [google/ExoPlayer#8367]
It seems in recent versions of exoplayers, this flag is used only in DefaultDrmSessionManager.
Logically, no-key-rotation content is just a special version of key-rotation content (rotated with infinite interval time).
Is there any reason that we have to set this flag to be false when the content only requires single key-request?
what side effect will it have if we by default set it true and play the content with key-rotation turned off?

**Comment by tonihei** [comment]
@AquilesCanta  Do you know if there is any downside in turning this flag on for content without key rotation.

**Comment by AquilesCanta** [comment]
The reason for the multiSession flag is that it's common for media to bring in keys for all elementary streams when issuing the key request for any of the elementary streams. 

Example: both audio and video are signalled as protected. However, issuing a license request for the video keys will also bring in audio keys, so having a single DRM session in that scenario is enough. If we turned off multisession and the license request information was different in any way between video and audio, ExoPlayer would perform one key request for audio and one for video, even though in most non-key-rotation cases, a single key request would be enough. Let me know if this answers your question.

**Comment by linhai326** [comment]
@AquilesCanta 
Thank you so much for your reply.
My original question is if there is any side-effect if we always turn on multi-session flag.

If i understand it correctly, what you are saying is: we should turn on multi-session even for non-key-rotation media in the case that audio and video have different license info. 
So it sounds there is not much side-effect if we keep this flag as true (turn on multi-session).
Is that correct understanding?

**Comment by ojw28** [comment]
If you turn `multiSession` on for non-key-rotated media:

1. If your content has identical PSSH boxes (this is what contains the "license request information") for all streams, there will be no side effects at all.
2. If your content has different PSSH boxes for audio and video, the side effect is that there will be two DRM sessions, each making their own key requests, rather than just one. This is what @AquilesCanta is describing above. In practice, this means (a) higher load on your license server, and (b) probably a very marginal increase in playback failure, simply because the additional session is one more thing that can go wrong. In practice I suspect these side effects are acceptable.
3. If your content has different PSSH boxes for different video streams, then you may see a small visual pause in playback when the player adapts from one video quality to another.
