### ISSUE TITLE
Order of moving controls from basicControls to extraControls in StyledPlayer

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8380]
### Use case description
I am customizing/adding controls to the `exo_basic_controls` of Styled Player. When there's not enough room, [StyledPlayerControlViewLayoutManager.onLayoutWidthChanged()](https://github.com/google/ExoPlayer/blob/r2.12.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlViewLayoutManager.java#L628-L692) moves controls to `exo_extra_controls`. 
This method however starts the moving at the beginning of the view (with leftmost control in LTR context). 

### Proposed solution
Personally I see the controls similarly to actions in an app bar. In app bars, the most used actions should be placed on the left (according to [material design](https://material.io/components/app-bars-top#anatomy)). 

> Place most-used actions on the left, progressing towards the least-used actions on the far right. Any remaining actions that don’t fit on the app bar can go into an overflow menu.

So IMHO it would make a bigger sense if the moving started from the end/right so that the most used controls are always visible (if possible).

**Comment by ojw28** [comment]
The styled player UI components were designed by the UX team, who are aware of material guidelines. Note that your reference is specifically about app bars at the top of the application's UI. From a quick skim, this guidance doesn't seem to be part of the material page about app bars at the bottom of the UI, although in any case that's not really exactly what this is.

Closing, since these components have already gone through UX review. People will always have different opinions and personal preferences for UI components. ExoPlayer provides out-of-the-box components to help you to get started quickly, but it's always possible to design and implement your own if you have very strong or specific requirements.
