### ISSUE TITLE
How to organize MediaSources/DataSources, when url has to first be resolved from external API

### ISSUE THREAD

**Issue by aasitnikov** [google/ExoPlayer#8383]
In my application media items are represented by some integer content id (723141234 for example), and before playing it I need to query backend method, that converts this content id to an actual url, that contains media. One of the requirements is to be able to download and play media offline. What is the best practice to handle such case? 

Currently I have this idea in mind:
1. Feed the player with some synthetic url, to be able to read it from cache in offline situation without having to go to backend (content://723141234 for example)
1. Create ProgressiveMediaSource - as it accepts arbitrary DataSource
2. Create CacheDataSource - if device is offline and this cache has content with synthetic url in it, then player will play cached data
3. Create ResolvingDataSource, to convert synthetic url to real url by calling backend method in Resolver.resolveDataSpec()
4. Create DefaultHttpDataSource/OkHttpDataSource to finally fetch media

**Comment by marcbaechinger** [comment]
I agree that what you describe sounds like the best way to do it for caching. The upstream `HttpDataSource` is wrapped by a `ResolvingDataSource` that is again wrapped by a `CacheDataSource`.

`CacheDataSource` -> `ResolvingDataSource` -> `DefaultHttpDataSource/OkHttpDataSource`

Aside: If you want to use the `DownloadService` for downloading you need to override [`DownloadService.getDownloadManager`](https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadService.java#L726). You then need to create a `DownloadManager` and [pass a `DataSource.Factory` to its constructor](https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java#L224): the upstreamFactory to pass to that constructor will be the `ResolvingDataSource` because the `CacheDataSource` will be created for you internally with the `Cache` that you pass to the same constructor.

**Comment by aasitnikov** [comment]
Thanks 🙏
