### ISSUE TITLE
How to access the decoded frame during playback ?

### ISSUE THREAD

**Issue by ekremcet** [google/ExoPlayer#8385]
Hi,

Sorry in advance if this a replicated question but I couldn't find the proper answer in existing issues. 

I wanted to ask about how can we access the decoded frame during the playback? Any help is appreciated.

Thanks

**Comment by ojw28** [comment]
Depending on your exact use case, you may find https://github.com/google/ExoPlayer/issues/6920 and https://github.com/google/ExoPlayer/issues/3105 useful. If not, I'd suggest you expand in more detail exactly what your use case is.

**Comment by ekremcet** [comment]
Hi @ojw28,

Thanks for the answer. I wanted to do some processing on the decoded frame before displaying it to the user so I think #6920 should work for my case.

**Comment by ekremcet** [comment]
Bringing this up again because I couldn't solve the problem. #6920 was about adding an overlay which is not what I wanted to do. What I want to do is :

1. Get the decoded frame
2. Modify the frame (i.e. change pixel values)
3. Send it to display

Is it possible to do this with ExoPlayer ?

Thanks

**Comment by andrewlewis** [comment]
GL shaders are quite flexible so you may be able to do the modifications needed in the shader. Showing an overlay is just an example.

If you really need to do modifications on the CPU then using MediaCodec in byte buffer mode (rather than surface mode) may help, but ExoPlayer doesn't use this mode because it's likely to be very inefficient. You could also try reading bitmap data back from the output surface. See also #7167.
