### ISSUE TITLE
Which version is stable?

### ISSUE THREAD

**Issue by idokit365** [google/ExoPlayer#8389]
Which version is stable if I need basic function only which can play local video and seek to ?
Which version is more stabled v1 and v2, and which sub version should I selecting ?
Thanks.

**Comment by marcbaechinger** [comment]
For ExoPlayer v2 there are two branches. The release branch and the dev-v2 branch.  

The release branch has a version number 2.x.x assigned and we publish [RELEASENOTES](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) that tell what new features and bug fixes are included. The [README](https://github.com/google/ExoPlayer/blob/release-v2/README.md) file of the project has a banner at the top which shows the latest release number.

For each release we publish the artefacts, so they can [be included as gradle dependencies](https://exoplayer.dev/hello-world.html#add-exoplayer-modules) in your project. We recommend using the latest release version of v2 for your app.

The dev-v2 branch is the tip of the source tree. To use it, you need to clone this repo. It's in general not recommended to use the dev-v2 branch for your project except you really know what you want and what you do.

While v1 of ExoPlayer is still available here on GitHub, this version is considered deprecated. The last v1 version has been released in August 2016. You shouldn't use v1 because v2 is much more advanced and v1 misses many features available in v2. You also wouldn't get proper support for v1 via documentation or here on the issue tracker for the reasons above.

**Comment by ojw28** [comment]
`2.12.2` is the latest (and therefore recommended) version.
