### ISSUE TITLE
ExoPlayer doesn't check if AVC/HEVC profile/level are supported when playing media file directly

### ISSUE THREAD

**Issue by equeim** [google/ExoPlayer#8393]
It seems that ExoPlayer can only check if video profile/level is supported by decoder (as reported by MediaCodecInfo.getCapabilitiesForType) only when profile/level information is provided in DASH/HLS manifest.

The only exception is MPEG-TS extractor that can get profile/level information from AVC bitstream.

If that is not an intentional design decision, I would like to make a pull request that will allow ExoPlayer to extract profile/level information from AVC and HEVC bitstreams for other extractors too.

**Comment by ojw28** [comment]
I don't think there was ever an intentional decision _not_ to implement this. That said, the value of doing so seems smaller than for DASH/HLS. For DASH/HLS, it might be the difference between playback succeeding and failing, since variant streams may use different profiles/levels, and a subset may be supported. For progressive streams I would assume it's the difference between playback failing with a clear error and playback failing with a less clear error.

Does that align with your understanding, and is your goal here just to make the failure mode clearer? If so, that seems fine, although given the relatively limited usefulness, I think we'd want to keep the implementation fairly straightforward. If it's fundamentally extremely complicated then it might be preferable not to implement it at all. Hopefully that's not the case though!

So, I think the next steps here would be:

* If your goal is to make the failure mode clearer and if you think it's fairly straightforward, feel free to go ahead and send a pull request to the `dev-v2` branch.
* If you have other goals, let's discuss what those are :).

As a final note, it's possible this might also fix https://github.com/google/ExoPlayer/issues/5882.

Thanks!

**Comment by equeim** [comment]
>For progressive streams I would assume it's the difference between playback failing with a clear error and playback failing with a less clear error.

The problem is that not all decoders fail with error in these cases. Some will "decode" frames, but show black screen or distorted image, for example. This makes it hard for application to appropriate action in these cases (which is especially important for things like ads when you would want to skip unsupported ad video and show actual content).

I suspect that it's decoders fault to not indicate error when unsupported profile is passed for decode, but there is an API for check if is supported beforehand and it makes for player to use it.

Regarding implementation complexity: for AVC it is very easy, since the code is already there. All that is needed is a few lines to actually hook it up in extractors. For HEVC it would require a bit of additional SPS parsing, but it's quite straightforward too.

**Comment by ojw28** [comment]
Thanks for the clarification! Perhaps send a pull request for AVC to get started, in that case, and follow up with the HEVC one separately :)?

**Comment by equeim** [comment]
That's what I plan to do!
