### ISSUE TITLE
Flickering single line of pixel with 800 px height content on Sony TV  

### ISSUE THREAD

**Issue by vrayv** [google/ExoPlayer#8394]
There is a known bug on some tv models explained here:

https://forums.plex.tv/t/playback-issue-sony-bravia-930e-flashing-artifacts-at-bottom-of-screen/230819/81

ExoPlayer seems to experience the same bug. I am doubtful its the problem with the exoplayer but rather with the TV itself (but those 2 might be connected because it seems sony uses exoplayer internaly).

The problem is happening when the video height is exactly 800 pixels.

The easiest workaround would be to detect the size and crop the video to 799 pixels.

Is there any easy code that can be implemented here?

**Comment by marcbaechinger** [comment]
It's a bit difficult to understand what is going on from the forum thread you referenced (there are 81 comments :). When skimming over it I understand that the issue is seen with the Plex app. It seems to be present for Sony TVs only and only for content with 800 pixels height. There are some comments saying it was fixed or reproducible after an update of the Plex app.

I actually don't really want to validate the comments in the forum but instead would like to look into a small test fixture which shows the behavior with the single line of pixel being displayed flickering on the Sony TV. If we have such an example we can see that we can test this on a Sony TV (we are all WFH so this may be not as easy as when we are in the office. Sorry in advance for this).

Probably our demo app is enough for this, together with a 1920x800 or 1900x800 content stream as reported to be displayed wrongly in the Plex forum thread.

Can you provide us with such an example and/or stream, the OS version and Sony TV model with which you can repro the behavior? That would enable us to see if we can repro.

Regarding cropping the video by this single pixel row at the bottom, I don't think that there is an easy API to crop the video just by a single line (see #5394 also). You can try experimenting with resizing the `PlayerView` and use an appropriate `resize_mode=""`. That should work with every content (drm'd and clear).  Or you can probably use a `TextureView` and use [`setTransform()`](https://developer.android.com/reference/android/view/TextureView#setTransform(android.graphics.Matrix)). This does work with content without drm only. Or you may just want to hide the single pixel line UI wise :).

All of this is more or less hacky as it is only required for some given devices. Best would be we look at this with a test fixture as I mentioned above. So if you can provide us with this, that would IMO be the best thing to do.

**Comment by vrayv** [comment]
I temporarily fixed it by adding 2 black lines with height of 1 pixel to bottom and top of the video view.

    <View
        android:layout_gravity="top"
        android:gravity="top"
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:background="@android:color/black"
        />
    <View
        android:layout_gravity="bottom"
        android:gravity="bottom"
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:background="@android:color/black"
        />

I will try to prepare some demo clips you can use to debug the issue. I think more tv's could be affected but samsung and lg are not android tv's so you need to run the clips using android box and exoplayer.

**Comment by vrayv** [comment]
I sent you 4 files for testing. The behavior is slightly different when playing with different devices using same exo player / library.

1. When played directly on sony tv android, Demo1.mkv will experience flickering line on the bottom of the screen. It's visible in the phone recorded video Demo1_flickering_sonytv.mp4.

Demo1.mkv has vertical pixel size of exactly 800 pixels.

The Demo2.mkv does not have any issues when played directly on sony tv. It has vertical size of 802 pixels.

2. Demo2.mkv and Demo1.mkv have both slightly different issue when played with firetv stick on sonytv. They both experience top and bottom horizontal fixed line during entire video.
The line is shown in the Demo2_upanddownline_firetv.mp4 video recorded by the phone.

Both issues are resolved by adding top and bottom horizontal black line over the video as explained above. The issue is probably reproducable on some other models using the exoplayer library.

**Comment by vrayv** [comment]
I seem to have resolve the issue. Problem happens if you share the player activity with a webview. Creating a new activity just for the player seem to fixes the issue. The flickering borders could be something from the webview code trying to outline the video elements and its probably some part of a webview buggy implementation because outline was turned off.
