### ISSUE TITLE
Im using Exoplayer version 2.12.1, is the any way to add a header to every single download request form specific URL ?

### ISSUE THREAD

**Issue by giangpham2811** [google/ExoPlayer#8399]

**Comment by giladna** [comment]
@ojw28 
I think this is more general question also for online

previously (before 2.12) Data source was given a parameter to DashMediaSource.Factory or HlsDataSource
but now with MediaItem approach there is no possibility to change DefaultDataSourceFactory headers in the MediaSourceFactoy after player was set 
and the issue that in our case we might need to update the headers for each media playback while the player is alive
is there a way to set the headers in that case?

**Comment by giladna** [comment]
@ojw28 
headers are configurable only for the DRM request I think that it might be needed for the media playback as well

**Comment by ojw28** [comment]
This issue was about setting headers for download requests, which is tracked by https://github.com/google/ExoPlayer/issues/6166.

For playback, you still have the option of using the `MediaSource` based APIs rather than those based on `MediaItem`, if you need fine-grained control over request headers for playback.

**Comment by giladna** [comment]
@ojw28  thanks

thanks for the response
I would expect that MediaItem will give me ability to change the headers for the URL of the same as it is for DRM license URL

I also noticed that all the external subtitles that are defined inside the media Item will not be available for use if I give the

mediaItem to the  MediaSourceFactory

So I have two code path for this now

It is on purpose?

Once the api is deprecated now it will be great to have old functionality in the new one as well

10x

**Comment by giladna** [comment]
@ojw28  
I saw that you consider adding this behaviour
" I think a good first step would be to add requestHeaders to MediaItem.PlaybackProperties"

it is on work? I think this is exactly what we need for this.

**Comment by giladna** [comment]
@ojw28 
should I open an issue for that
1. missing headers modification support in MediaItem PlaybackProperties
2. if MediaItem is filled with external subtitles this data is not being used in case we give MediaItem to build the MediaSource

**Comment by icbaker** [comment]
> if MediaItem is filled with external subtitles this data is not being used in case we give MediaItem to build the MediaSource

Please open an issue for this - I'm not sure exactly what you mean from this description so you'll need to provide clear reproduction steps, possibly including sample media.

(I'll leave @ojw28 to comment on the other one)

**Comment by ojw28** [comment]
> Once the api is deprecated now it will be great to have old functionality in the new one as well

We don't have any plans to deprecate the `MediaSource` based API. They're different APIs for different use cases (`MediaItem` for simpler use cases, `MediaSource` for cases where a greater degree of customization is required). We are considering adding request headers into `MediaItem`, but it's complicated for adaptive streaming because there are different types of requests being made, in some cases to completely different servers, and different developers might want different headers attached (or not attached) to each request type. As a result, it's unclear that just adding a single set of headers will really end up doing the right thing. This is under some discussion in https://github.com/google/ExoPlayer/pull/7852, and I'm not sure we need a separate issue to track it.

As @icbaker says, please file a separate issue for the subtitle issue.
