### ISSUE TITLE
Subtitles display error

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#8417]
Hello, I have a mkv file. The subtitles are in S_HDMV/PGS format, but the content information decoded by the subtitles is empty, causing the subtitles to not be displayed. The file address is as follows:
https://w4files.ws/c3087ddae5d47b08?pt=RwHf%2FqA0fzsKx%2Fe4xgrs9AAX5Dur7nXUEC7Spy7aI7c%3D

**Comment by icbaker** [comment]
The link provided doesn't seem to let me download the content - it just opens spam links.

Please host the file somewhere we can access it.

**Comment by kuailedeadai** [comment]
The file link is as follows：
https://drive.google.com/file/d/1dqK22uK-EoeOeSVeUEYqge_vpVp8mZ2Y/view?usp=sharing
thanks

**Comment by icbaker** [comment]
Thanks for the report - can I ask what version of ExoPlayer you're using?

I can reproduce the behaviour you're seeing on the dev-v2 branch, but not in 2.12.2 (the latest release).

On the dev-v2 branch the problem comes from a mistake in this commit (the change in `PgsDecoder` shouldn't have been made):
https://github.com/google/ExoPlayer/commit/46598a46fd3c13a9be906abd6c673b9487ba5d50#diff-39c6b6e64d3086f4f9b7ba84285282de60b61f9408d9e6f087288f9625e9c690

This commit is not yet included in a released version of the library.

I'll revert the `PgsDecoder` changes from that commit which should fix the playback for the file you provided on the dev-v2.

Let me know if you're seeing this problem on a different version of ExoPlayer, because that might indicate a different problem.
