### ISSUE TITLE
Weird bug when playing with surfaceview on some devices

### ISSUE THREAD

**Issue by swifityG** [google/ExoPlayer#8423]
There is weird bug when playing using surfaceview in one specific media, I not sure what causing it because I cant reproduce it because I don't have those devices.

I know it's probably the devices/media fault but I didn't see anyone reported this bug so I just wanted to inform you guys. 

This is a pic of how the media shows when using surfaceview
https://gofile.io/d/zCQ6pv

this is the link to the media - https://cdnapisec.kaltura.com/p/2748741/sp/2748741/playManifest/entryId/1_x3xriuot/deliveryProfileId/672/protocol/https/format/applehttp/a.m3u8

In case its geoblocked I uploaded a sample I got with ffmpeg
https://gofile.io/d/BogXQr

The bug occurs from my understanding of users report from Xiaomi mibox devices and "probox2 Air Plus" devices and there is might be more.

Exoplayer version is last dev

**Comment by andrewlewis** [comment]
I had a look at the provided sample but couldn't find anything obviously wrong with the stream using a few different tools. Based on the provided screenshot, I agree it's likely that the media is invalid and the error is not concealed as well by this device, or it could be a bug with the specific device's decoder. Your best bet is probably to report this the device/chipset makers so they can root cause it.

**Comment by swifityG** [comment]
Thank for the help even tho I dont think reporting this issue to Xiaomi/amlogic is worth even trying 😔
