### ISSUE TITLE
Advice for adding support for playing scrambled TS stream

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#8469]
Hi,

I'm trying to deal with playing a scrambled TS stream with CENC. I'm just starting the project so I don't have all the information, but it seems to me to be Widevine CAS related (#5804 ).

So in the received TS, each Elementary Stream has a conditional access descriptor giving:
- CA system ID (Widevine here)
- ECM PID
- Scheme (CENC here)
- PSSH PIDs

I implemented this parsing but now I need some advice from you on the best way to architecture ECM and PSSH data reading, and the way to provide the necessary DRM data to ExoPlayer to descramble data with MediaDrm/MediaCas.
My guess:
1. add some info in EsInfo about CA descriptors
2. create an EcmReader which implements SectionPayloadReader to parse ECM (Key ID, IV)
3. add it to a TsPayloadReader.Factory with a new TsExtractor.TS_STREAM_TYPE_ECM type
4. same thing for PSSH
5. add these readers in TsExtractor.tsPayloadReaders for them to be called and parse data
6. give all these extracted DRM data to ExoPlayer (this part is really blurry for me, but I guess it has something to do with DrmInitData)
7. certainly something I'm missing

Could you help me on this? Any remark, thought, advice is welcome.

Best Regards,
Christophe

**Comment by ojw28** [comment]
As you probably figured out, this is not something that ExoPlayer supports directly. The feature request that tracks adding support is https://github.com/google/ExoPlayer/issues/4021, however it's unlikely to be prioritized because the industry as a whole has shifted toward FMP4/CMAF.

We are unable to provide detailed implementation guidance. The research required to do so would probably be the majority of the time investment to actually implement the feature, and as noted above this is not a feature we're currently choosing to invest time on. You might be able to work with @lys1737, since according to https://github.com/google/ExoPlayer/issues/4021 they have attempted to implement this already. In any case, I would suggest asking on that issue.

**Comment by ojw28** [comment]
It's also possible that your use case is a duplicate of https://github.com/google/ExoPlayer/issues/5804, rather than https://github.com/google/ExoPlayer/issues/4021. It was somewhat unclear to me, based on the description provided.
