### ISSUE TITLE
cannot git clone https://git.xiph.org/opus.git libopus

### ISSUE THREAD

**Issue by T-10001** [google/ExoPlayer#8470]
Tried to follow steps on https://github.com/google/ExoPlayer/tree/release-v2/extensions/opus to build the opus extension

`git clone https://git.xiph.org/opus.git libopus` causes error `fatal: unable to access 'https://git.xiph.org/opus.git/': gnutls_handshake() failed: Error in the pull function.` on WSL Ubuntu 20.04.

**Comment by ojw28** [comment]
This is because the opus repository seems to have moved. You need to use `https://gitlab.xiph.org/xiph/opus.git` rather than `https://git.xiph.org/opus.git`. We have updated our instructions in the `dev-v2` branch, in https://github.com/google/ExoPlayer/commit/d2950c2e973293d040abde7a76aca346789447d0.
