### ISSUE TITLE
When creating MediaSource using createMediaSource(mediaItem) and it was populated with subtitles the player will not consider them as text tracks

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#8477]
Hi,

Given MediaItem.Subtitle  list  is missing in playback text tracks  if the MediaSource is built from given MediaItem having the subtitles 

When I was trying to explore the usage MediaSource instead of MediaItem for the Playback URL headers modifications

I have  populated the MediaItem playback params with the external subtitles.
I could not see that external subtitle in the tracks dialog when I tested this solution 

I have modified a bit the demo app main activity to call `setMediaSource` instead of `setMediaItems`
I have also assumed that single  non drm dash media without subtitles is selected.

I have populated subtitleList and set it to mediaItem in pos 0. 
created a dash media source  
and called
player.setMediaSource(dashMediaSource,!haveStartPosition); 
instead of 
player.setMediaItems(mediaItems, /* resetPosition= */ !haveStartPosition);

then called prepare
```
List<MediaItem.Subtitle> subtitleList = new ArrayList<>();
String url = "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt";
MediaItem.Subtitle externalSubtitle = new MediaItem.Subtitle(Uri.parse(url), MimeTypes.TEXT_VTT,"en", C.SELECTION_FLAG_DEFAULT, C.ROLE_FLAG_SUBTITLE, "ENGLISH-EXTERNAL");
subtitleList.add(externalSubtitle);
...
mediaItems.get(0).buildUpon().setSubtitles(subtitleList);
...
DashMediaSource dashMediaSource = new DashMediaSource.Factory(new DefaultDashChunkSource.Factory(dataSourceFactory), dataSourceFactory).createMediaSource(mediaItems.get(0));
player.setMediaSource(dashMediaSource,!haveStartPosition);
//player.setMediaItems(mediaItems, /* resetPosition= */ !haveStartPosition);
player.prepare();
```

Version:
Exo Player version: 2.12.3
Android 10
Samsung Galaxy 10e

**Comment by ojw28** [comment]
`MediaItem` is immutable, so the line `mediaItems.get(0).buildUpon().setSubtitles(subtitleList)` isn't actually doing anything. If you're trying to replace the first item in the list with an item that has subtitles, you'd need to do something more like:
```
MediaItem mediaItemWithSubtitles = mediaItems.get(0).buildUpon().setSubtitles(subtitleList).build();
mediaItems.set(0, mediaItemWithSubtitles)
```
To check that the subtitles have been attached correctly, you can try attaching a debugger on the `player.setMediaItems` line and inspecting the items that are actually being passed.

**Comment by giladna** [comment]
@ojw28 
I am afraid this is not the root cause I first tried updating it in the IntentUtil class  in the builder
then moved it to main activity for the readability  
please check this 

Even if we pass the the subs in the time the mediaItem it is not working 

from IntentUtil
```
private static List<MediaItem.Subtitle> createSubtitlesFromIntent(
          Intent intent, String extrasKeySuffix) {
    List<MediaItem.Subtitle> subtitleList = new ArrayList<>();
    String url = "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt";
    MediaItem.Subtitle externalSubtitle = new MediaItem.Subtitle(Uri.parse(url), MimeTypes.TEXT_VTT,"en", C.SELECTION_FLAG_DEFAULT, C.ROLE_FLAG_SUBTITLE, "ENGLISH-EXTERNAL");
    subtitleList.add(externalSubtitle);
    return subtitleList;
  }
```
<img width="1231" alt="Screen Shot 2021-01-19 at 8 34 53" src="https://user-images.githubusercontent.com/16818804/104996841-4310bd80-5a31-11eb-9377-22c215e24fd3.png">
<img width="1231" alt="Screen Shot 2021-01-19 at 8 34 53" src="https://user-images.githubusercontent.com/16818804/104996851-47d57180-5a31-11eb-86d0-6c26aa24a183.png">

**Comment by giladna** [comment]
@ojw28 
I see but the issue is still there. 
actually I first tried this on the IntentUtli.java where it is building the subs and moved it to the PlayerActivity for the explanation simplicity.

please check this:

```
  private static List<MediaItem.Subtitle> createSubtitlesFromIntent(
          Intent intent, String extrasKeySuffix) {
    List<MediaItem.Subtitle> subtitleList = new ArrayList<>();
    String url = "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt";
    MediaItem.Subtitle externalSubtitle = new MediaItem.Subtitle(Uri.parse(url), MimeTypes.TEXT_VTT,"en", C.SELECTION_FLAG_DEFAULT, C.ROLE_FLAG_SUBTITLE, "ENGLISH-EXTERNAL");
    subtitleList.add(externalSubtitle);
    return subtitleList;
  }
```
I have changed the createSubtitlesFromIntent to build my subtitle

and this is the only code change in the PlayerActivtiy

```

    DashMediaSource dashMediaSource = new DashMediaSource.Factory(new DefaultDashChunkSource.Factory(dataSourceFactory), dataSourceFactory).createMediaSource(mediaItems.get(0));
    player.setMediaSource(dashMediaSource,!haveStartPosition);
    //player.setMediaItems(mediaItems, /* resetPosition= */ !haveStartPosition);
```

<img width="1231" alt="Screen Shot 2021-01-19 at 8 34 53" src="https://user-images.githubusercontent.com/16818804/104997248-f24d9480-5a31-11eb-8c3b-9741ad7e6d20.png">
<img width="1220" alt="Screen Shot 2021-01-19 at 8 33 10" src="https://user-images.githubusercontent.com/16818804/104997263-f8dc0c00-5a31-11eb-85ae-20432a231834.png">

**Comment by ojw28** [comment]
Once you have a correctly built `MediaItem`, you should pass it to the player using `player.setMediaItem` and let the player build the `MediaSource` directly.

You don't need to build the `DashMediaSource` from the `MediaItem` directly, and this approach will not work with side-loaded subtitles because that use case needs more than just a `DashMediaSource`. If you let the player build the `MediaSource` internally, it'll build the correct `MediaSource` for the `MediaItem` and the subtitles will work.

The way you're sharing code with us is quite confusing. If you're still unable to get this to work, please provide a _single_ code block that:

1. Creates a `MediaItem` from scratch
2. Passes it to the player using `setMediaItem`
3. Does not contain any commented out lines
4. Reproduces the issue

Thanks!

**Comment by giladna** [comment]
@ojw28 
I am not sure what you find confusing in my sample.
I have replaced createSubtitlesFromIntent with my Subtitle  in The intentUtil
And was using the mediaItem to build the MediaSource and populate the player with the mediaSourece instead of the mediaItem

I cannot use MediaItem Directly.

I have to go through this MediaSource creation since I have to set my own headers.
I would love to have the setHeaders API or player to pass the subtitles in the mediaItem to the mediaSource

 and saving the need to implement it with Merging Media source

let me know is sample still required.

thanks,
Gilad.

```
return new MergingMediaSource(buildMediaSourceList(mediaSource, externalSubtitleList));
```

```
    private MediaSource[] buildMediaSourceList(MediaSource mediaSource, List<PKExternalSubtitle> externalSubtitleList) {
        List<MediaSource> streamMediaSources = new ArrayList<>();
        List<MediaItem.Subtitle> mediaItemSubtitles = buildSubtitlesList(externalSubtitleList);
        if (externalSubtitleList != null && externalSubtitleList.size() > 0) {
            for (int subtitlePosition = 0 ; subtitlePosition < externalSubtitleList.size() ; subtitlePosition ++) {
                MediaSource subtitleMediaSource = buildExternalSubtitleSource(mediaItemSubtitles.get(subtitlePosition));
                streamMediaSources.add(subtitleMediaSource);
            }
        }
        // 0th position is secured for dash/hls/extractor media source
        streamMediaSources.add(0, mediaSource);
        return streamMediaSources.toArray(new MediaSource[0]);
    }


    @NonNull
    private MediaSource buildExternalSubtitleSource(MediaItem.Subtitle mediaItemSubtitle) {
        return new SingleSampleMediaSource.Factory(getDataSourceFactory(null))
                .setLoadErrorHandlingPolicy(externalTextTrackLoadErrorPolicy)
                .setTreatLoadErrorsAsEndOfStream(true)
                .createMediaSource(mediaItemSubtitle, C.TIME_UNSET);
    }

```

**Comment by ojw28** [comment]
> I am not sure what you find confusing in my sample.

It's confusing because you don't ever provide a single code block that fully demonstrates the problem you're describing. The snippets provided are always partial and it's unclear what code is actually being executed in what order. Commented out lines of code add to this lack of clarity. Code samples are much simpler for us to understand if they're just a single block of contiguous code that reproduces the problem.

The job of a `MediaSourceFactory` is to convert a `MediaItem` into a `MediaSource`. `DashMediaSource.Factory` creates `DashMediaSource` instances directly, which do not support side-loaded subtitles. As above, side-loaded subtitles need more than just a `DashMediaSource`. `DefaultMediaSourceFactory` contains additional logic to construct a `MergingMediaSource` for side-loaded subtitles. So, in conclusion:

1. If you want to convert a `MediaItem` to a `MediaSource` in a way that supports side-loaded subtitles as specified by the `MediaItem`, then you need to use `DefaultMediaSourceFactory` or a custom factory you've created that supports side-loaded subtitles. `DashMediaSource.Factory`does not support side-loaded subtitles.
1. At the point where you need to create the `MediaSource` outside of the player, there's little value in using `MediaItem` at all. If you have existing logic that correctly builds the `MediaSource` instances you need outside of the player, then you'd be best off just keeping that logic, particularly if you need customization support such as setting request headers.

**Comment by giladna** [comment]
@ojw28 
Got it,
The I am wondering  what is the benefit that we  need to give the mediaItem itself  to the createMediaSource and not using url in the deprecated api which build the media source?
the API actually forces to use MediaItem even if it is not a must.

What do I miss.

**Comment by ojw28** [comment]
Ah right, yes, you do need a `MediaItem` to give to the non-deprecated `createMediaSource` methods, even when building a `MediaSource` instances outside of the player. So point (2) of my previous response wasn't really correct.

Point (1) still is correct though: If you need side-loaded subtitle support then you should use `DefaultMediaSourceFactory` rather than `DashMediaSource.Factory`. `DefaultMediaSourceFactory` has the additional logic needed to build a `MergingMediaSource` for the side-loaded subtitles. Alternatively, you can use `DashMediaSource.Factory` to build a `DashMediaSource`, and then you can wrap it in a `MergingMediaSource` yourself.

It is a bit confusing that some of the `MediaSourceFactory` implementations only support a subset of what can be specified in the `MediaItem`. In this example, it's confusing that `DashMediaSource.Factory` does not support side-loaded subtitles. We will have a think about how best to document or resolve this.
