### ISSUE TITLE
How to reduce the playback latency of rtmp stream?

### ISSUE THREAD

**Issue by luohaohaha** [google/ExoPlayer#8481]
When I play the rtmp stream, the latency takes about 6 seconds, I want to adjust it to about 2 seconds, so I modified the DefaultLoadControl, but it seems to have no effect。

But I found a very interesting problem during the test. If I push the stream first, and then ExoPlayer pulls the stream, the latency is about 4~6 seconds. If I use ExoPlayer to pull the stream and wait, and then push the stream, the latency will be 2. In seconds, is there any good solution?

```
SimpleExoPlayer simpleExoPlayer = new SimpleExoPlayer.Builder(this,
                new DefaultRenderersFactory(this),
                new DefaultTrackSelector(this),
                factory,
                new DefaultLoadControl.Builder().setBufferDurationsMs( 25_000,
                        25_000,
                        1250,
                        0).setTargetBufferBytes(-1).build(),
                DefaultBandwidthMeter.getSingletonInstance(this),
                new AnalyticsCollector(Clock.DEFAULT)).setTrackSelector(trackSelector).build();
```

**Comment by ojw28** [comment]
Is this a live stream? If so, then I wonder whether the difference between the two cases is having to wait for a key-frame in the stream? The first frame of any stream will always be a key-frame. It could be that in the second case you describe, the player receives data starting at the first frame, and so can start decoding immediately from that point. Conversely, it could be that in the first case you describe, the player receives data starting at some non-first frame, meaning that it has to wait to encounter the next key-frame before it can start decoding. If this is the root cause, I think the only solution is to adjust the stream itself to contain more regular key-frames.

On the ExoPlayer side I think you're doing roughly the right thing, although:
* You can probably reduce `bufferForPlaybackMs` from `1250` all the way down to `0`.
* You'd normally want `bufferForPlaybackAfterRebufferMs` to be greater than `0` (e.g., `1000`) to avoid very frequent stuttering in the case that the player encounters a re-buffer. Note that this parameter has no affect on initial startup latency.
