### ISSUE TITLE
Every first ad in AdGroup is getting timeout

### ISSUE THREAD

**Issue by ppodgorski** [google/ExoPlayer#8492]
### Issue description
With our adTagUrl (VMAP) every first ad in AdGroup is getting timeout. When I revert this commit: https://github.com/google/ExoPlayer/commit/fe754f313e8ddba5a77f149ee23f0082c1c2fea6 everything is working fine. I've emailed our adTagUrl to dev.exoplayer@gmail.com.

### Reproduction steps
Just switch "ad_tag_uri" in media.exolist.json to our custom adTagUrl and play.

### Link to test content
Our custom adTagUrl has been sent to dev.exoplayer@gmail.com.

### A full bug report captured from the device
```
I/ImaAdsLoader: AdEvent: {errorMessage=VAST media file loading reached a timeout of 8 seconds., errorCode=402, type=adPlayError}
```

###  Version of ExoPlayer being used
2.12.3

### Device(s) and version(s) of Android being used
Huawei P30 Pro, Android 10.0

**Comment by andrewlewis** [comment]
The first ad in the ad group is 2 seconds long (it looks like an intro logo) and the player is stuck buffering presumably because the next media period can now be created (after fe754f3) but we don't get a URL to actually prepare it, and load control is not allowing playback to start with only two seconds of media buffered.

**Comment by andrewlewis** [comment]
Fix in review and this bug will be updated when it's on the development branch. Thanks for reporting the issue!

**Comment by ppodgorski** [comment]
@andrewlewis Thanks a lot for the quick action!
