### ISSUE TITLE
HLS live stream not playing

### ISSUE THREAD

**Issue by ekamsoftwares-india** [google/ExoPlayer#8502]
Hi, I am trying to play various m3u8 streaming, but I am stuck with one URL: 
https://radios-gt.cdn.nedmedia.io/radios/gt/galaxia.m3u8

Here is the error: /SimpleExoPlayer: Player is accessed on the wrong thread. 

Please advise.

Thank you,
Bikram Sekhon

**Comment by marcbaechinger** [comment]
You need to call methods on the player from the same thread that created the player. Please see the entry on the troubleshooting page of the DevGuide:

https://exoplayer.dev/troubleshooting.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean

**Comment by ekamsoftwares-india** [comment]
Hi, we tested this URL in the demo of exoplayer, but it didn't worked there as well. Can you please advise ?

**Comment by marcbaechinger** [comment]
I'm getting a HTTP/404 with the URL above. Please make sure the media is accessible with the URL or provide another URL that provides the content. 

Your initial report was about `Player is accessed on the wrong thread.`. This is not related to the content you are playing but about how you integrate ExoPlayer in your app. Can you please a bit more specific in what the expected and observed result is after you updated the url?

```
$ curl --verbose "https://radios-gt.cdn.nedmedia.io/radios/gt/galaxia.m3u8"
*   Trying 143.204.94.106:443...
* Connected to radios-gt.cdn.nedmedia.io (143.204.94.106) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.cdn.nedmedia.io
*  start date: Aug 13 00:00:00 2020 GMT
*  expire date: Sep 12 12:00:00 2021 GMT
*  subjectAltName: host "radios-gt.cdn.nedmedia.io" matched cert's "*.cdn.nedmedia.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5555e613b540)
> GET /radios/gt/galaxia.m3u8 HTTP/2
> Host: radios-gt.cdn.nedmedia.io
> user-agent: curl/7.74.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< content-type: text/html
< content-length: 178
< server: nginx/1.10.0 (Ubuntu)
< date: Wed, 27 Jan 2021 08:58:37 GMT
< vary: Accept-Encoding
< x-cache: Error from cloudfront
< via: 1.1 24475cc722041223cf99f56b55432566.cloudfront.net (CloudFront)
< x-amz-cf-pop: FRA50-C1
< x-amz-cf-id: 8H260uPSo3o_EoS2F0kb69m5qUR7NEMHmD8dHLcqEQsbyhkURrG_RA==
< age: 2
< 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host radios-gt.cdn.nedmedia.io left intact
```

**Comment by ekamsoftwares-india** [comment]
Hi, the URL is working. Kindly test it here: https://www.hlsplayer.net/

**Comment by marcbaechinger** [comment]
Yeah, thanks. I get a HTTP/200 now. The stream does not play on ExoPlayer or the web player you pasted above. With each timeline update of the live stream the position negatively increases:

```
timeline [eventTime=317.87, mediaPos=-320.25, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
``` 

@christosts can you have a look please?

**Comment by ekamsoftwares-india** [comment]
@marcbaechinger  the link is playing in the web player. Please check the screenshot: http://prntscr.com/xpxn4g

**Comment by marcbaechinger** [comment]
Oh, yes. Sorry, it's audio only. Thanks for mentioning. :)

**Comment by ekamsoftwares-india** [comment]
@christosts any solution Sir. :)

**Comment by christosts** [comment]
I see the stream declares a video track without any video data, which the player cannot handle. The player cannot complete the media preparation because it's trying to read video data too. You can verify the existence of the video track by inspecting one of the `ts` files with `tsanalyze` or `dvbsnoop`.

Similar issues have been reported in #7469, #6112, #3712, #3158 with the difference that in these issues the audio tracks were empty, whereas in this case the video track is empty.

If you're in control of the media encoding, can you change the encoding parameters to remove the empty video track declaration?

**Comment by ekamsoftwares-india** [comment]
Unfortunately, we do not have control on this m3u8 link. Is there any solution for this ?

**Comment by christosts** [comment]
Can you try to set the [DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM](https://github.com/google/ExoPlayer/blob/r2.12.3/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/DefaultTsPayloadReaderFactory.java) flag on a custom `HlsMediaSource.Factory` and set this custom media source to the player? For example, in the demo app's [PlayerActivitiy](https://github.com/google/ExoPlayer/blob/r2.12.3/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L290), this snippet should work

```
HlsMediaSource.Factory hlsFactory = 
    new HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(
        new DefaultHlsExtractorFactory(DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM, true));

player = new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
    .setMediaSourceFactory(hlsFactory)
    ...;
```

Please note this flag will ignore H264 video tracks, therefore you should use it only for this content, otherwise playbacks will ignore video tracks.

**Comment by ekamsoftwares-india** [comment]
Wow, it worked. Thank you so much. You made my day. :)
