### ISSUE TITLE
Cache writer clarification?

### ISSUE THREAD

**Issue by GobuTranxit** [google/ExoPlayer#8536]
Hi,

When we try multiple downloads using cache writer will process sequentially or parallelly?
It'll process like download manager right?

**Comment by marcbaechinger** [comment]
The `CacheWriter` does use a single `CacheDataSource`. If you call the `cache` method on it, it opens the source and reads from it to fulfill the `DataSpec` that is passed to it in the constructor. In that sense the `CacheWriter` does load a block of data from a data source sequentially. The loaded data is stored in the cache that is associated to the `CacheDataSource` from which the `CacheWriter` reads. 

> When we try multiple downloads using cache writer will process sequentially or parallelly?

When you call the `cache` method on multiple `CacheWriter` instances without taking care that a former call returned before calling `cache` on the next writer instance, then it will process in parallel. It's up to the caller to coordinate this. The `CacheWriter` itself will just read from the data source.

> It'll process like download manager right?

I don't think you can compare `CacheWriter` with `DownloadManager`. The `DownloadManager` coordinates downloads and depending on how it is configured, it may download multiple downloads in parallel. This boils down to using the `CacheWriters` in parallel. That's more of an implementation detail though, as the `DownloadManager` itself uses instances of the `Downloader` (i.e. `ProgressiveDownloader` and `SegmentDownloader`) rather than directly dealing with 'CacheWriter' instances.
