### ISSUE TITLE
ActionFileUpgradeUtil.upgradeAndDelete issues when upgrading from 2.9.3 to 2.11.4

### ISSUE THREAD

**Issue by sidferreira** [google/ExoPlayer#8543]
I've been trying to run the upgrades deeply based on the Demo app, but having a couple of differences that I need to handle:

- I have downloaded contents both in internal and external storages
- The downloads are in an unusual structure:
```
~/Files/_downloads (actionFile)
~/Files/downloads (directory with the downloaded files)
```

When I run the `DownloadUtil.upgradeActionFile` I'm keeping `/* deleteOnFailure= */ false,`, the method is called but things just doesn't happen.
I checked Exoplayer's database and it shows:

![Screen Shot 2021-02-03 at 5 18 22 PM](https://user-images.githubusercontent.com/143615/106831028-0b666000-6644-11eb-9c94-edd12b087aa6.png)

Can anyone help me understand where may be my mistake?

Thanks in advance

**Comment by sidferreira** [comment]
After digging more, I found out that there was customization when saving the ActionFile in our project. So in the test below: https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/offline/ActionFile.java#L128-L133 the `type` returns a value that doesn't match any of those here, having an EOF Exception when it tries to read line 133.

**Comment by marcbaechinger** [comment]
I do not assume that your last comment is saying that you fixed the problem. If you fixed your problem you can obviously ignore my following comments. :) Please close the issue in this case, if not, read ahead to see whether I can help.

Do I understand correctly that you have a `legacySegmented` stream that is not recognized as a such because the customization of the action file used a different `downloadType` for a segmented download?

This would explain the behavior I think. When you pass `deleteOnFailure=false` to `ActionFileUpgradeUtil.upgradeAndDelete(...)` the file never gets deleted which is expected. This is because with the EOF exception when `ActionFile.load` is called, migration does not work and with `success || deleteOnFailure` never evaluating to true the file is not deleted.

What's the actual type of the file? Is it DASH, HLS or Smooth Streaming that is just having a `downloadType` that is called differently? If that's the case does it help to change the source code on L128 to recognize your 'downloadType' as segmented and then further down on L145 fix the mime type?

That probably fixes the migration, and probably also playback because ExoPlayer only supports download and playback for the given fragmented types and can't do something sensible if it is something else.

Please let me know whether this helps and if not, can you please clarify what you are trying to achieve with 'deleteOnFailure=false'? It's probably hard for us to help and you need to change the source code of the migration yourself to make your customization work. LMK, I'm happy to assist as good as I can.

**Comment by sidferreira** [comment]
Hey @marcbaechinger! So, your comments gave me some ideas and helped me to understand what was going on.
Just FYI, this code was developed by a 3rd party, 2 years ago, and we can't rely on them at this moment.

The said "multihls" type, is just a copy of `HlsDownloader` with two small tweaks. The code has `part` and `numParts` values that are used to parallelize the download. `numParts` is actually the max number of parallel downloads.

I'm working on a small tool to just change the type from `multihls` to `hls`, hopefully, that's the only change I have to worry about.

I know this issue is "out of scope", but any suggestion to address this will be welcome.

```java
        for (Uri mediaPlaylistUri : mediaPlaylistUris) {
            HlsMediaPlaylist mediaPlaylist;
            try {
                mediaPlaylist = (HlsMediaPlaylist) loadManifest(dataSource, mediaPlaylistUri);
                /* HERE */
                if (_part == 0) segments.add(new SegmentDownloader.Segment(mediaPlaylist.startTimeUs, new DataSpec(mediaPlaylistUri)));
            } catch (IOException e) {
                if (!allowIncompleteList) {
                    throw e;
                }
                /* HERE */
                if (_part == 0) segments.add(new SegmentDownloader.Segment(0, new DataSpec(mediaPlaylistUri)));
                continue;
            }

            HlsMediaPlaylist.Segment lastInitSegment = null;
            List<HlsMediaPlaylist.Segment> hlsSegments = mediaPlaylist.segments;
            for (int i = 0; i < hlsSegments.size(); i++) {
                /* HERE */
                if (i % _numParts == _part) {
                    HlsMediaPlaylist.Segment segment = hlsSegments.get(i);
                    HlsMediaPlaylist.Segment initSegment = segment.initializationSegment;

                    if (initSegment != null && initSegment != lastInitSegment) {
                        lastInitSegment = initSegment;
                        addSegment(segments, mediaPlaylist, initSegment, seenEncryptionKeyUris);
                    }
                    addSegment(segments, mediaPlaylist, segment, seenEncryptionKeyUris);
                }
            }
        }
```

The class was called like this:

```kotlin
for (i in 0 until DownloadService.MAX_CONCURRENT_SEGMENTS) {
  DownloadService.startWithAction(context, DownloadService::class.java, 
    MultiHlsDownloadAction(uri, downloadKey.toByteArray(), renditions, i, DownloadService.MAX_CONCURRENT_SEGMENTS),
    false)
}
```

**Comment by ojw28** [comment]
> I know this issue is "out of scope", but any suggestion to address this will be welcome.

I think the best thing for you to do would be to fork `ActionFileUpgradeUtil` and `ActionFile` into your own codebase. Modify `ActionFile` to be aware of your additional type (e.g., `DOWNLOAD_TYPE_HLS_MULTI = "multihls"`) and treat it in the same way as the regular `DOWNLOAD_TYPE_HLS` type is handled. Then, use your forked `ActionFileUpgradeUtil` to do the upgrade, and the right thing should just happen during the upgrade step. I think this is the same suggestion @marcbaechinger was alluding to above.

Note that I don't think you need to make any changes in `ActionFileUpgradeUtil`. It only needs forking so that it uses your forked `ActionFile` implementation, rather than the one in the ExoPlayer library.

**Comment by sidferreira** [comment]
@ojw28 I did that fork, I tried both keeping the type as `multihls` and  changing to `hls`, with no good results as mentioned in #8597
