### ISSUE TITLE
ExoPlayerImplInternal: Playback error when Build MediaSource from ByteArrayDataSource 

### ISSUE THREAD

**Issue by HungQB** [google/ExoPlayer#8552]
I am trying to play an mp3 using ByteArray . as far as I found out in some forums #5571 . 
Here's how I create a MediaSource .
```
 private MediaSource createMediaSourceFromByteArray(byte[] data, DrmSessionManager drmSessionManager) {
    ByteArrayDataSource byteArrayDataSource = new ByteArrayDataSource(data);
    Uri audioByteUri = new UriByteDataHelper().getUri(data);
    DataSpec dataSpec = new DataSpec(audioByteUri);
    try {
      byteArrayDataSource.open(dataSpec);
    } catch (IOException e) {
      e.printStackTrace();
    }
    DataSource.Factory factory = new DataSource.Factory() {
      @Override
      public DataSource createDataSource() {
        return byteArrayDataSource;
      }
    };
    MediaSource mediaSource = new ProgressiveMediaSource.Factory(factory)
              .setDrmSessionManager(drmSessionManager)
              .createMediaSource(MediaItem.fromUri(audioByteUri));

    return mediaSource;
  }
```

But the exoplayer cannot play it with the following error : 
![error](https://user-images.githubusercontent.com/73470210/107002272-9028b980-67bd-11eb-897c-c8029dda9c86.PNG)
I am still trying to find solutions. I have seen a similar problem, but still have no answer . [https://stackoverflow.com/questions/57996960/unrecognizedinputformatexception-none-of-the-available-extractors-could-read-th](url)

**Comment by icbaker** [comment]
`ByteArrayDataSource` ignores the `DataSpec.uri` property, you can just pass `Uri.EMPTY` to the `DataSpec`. This is mentioned in the [second comment](https://github.com/google/ExoPlayer/issues/5571#issuecomment-468003394) of the issue you linked:
> > Is there any way I can remove the need for the Uri
> 
> You don't need to remove the need for the Uri. You should be able to pass an empty uri.

You shouldn't call `open()` on the `ByteArrayDataSource` - that will be done by the library when you start playback. This is also mentioned in the [same comment](https://github.com/google/ExoPlayer/issues/5571#issuecomment-468003394):
> Probably unrelated, you don't need to/shouldn't open the data source. So basically you should remove the
> 
> ```
> try {
>         byteArrayDataSource.open(dataSpec);
>     } catch (IOException e) {
>         e.printStackTrace();
>     }
> ```
> 
> block.


If after those changes you still see the same `UnrecognizedInputFormatException` then I would suggest trying to play the same bytes from a file instead of a byte array. 

If this results in the same error then there's either something wrong with the MP3 file or ExoPlayer isn't compatible with it - to investigate that we'd need you to provide the media file. 

If playback succeeds when playing from a file then it suggests something is wrong with the way you're building up your byte array. Note that you shouldn't modify the array after passing it to the `ByteArrayDataSource`. To investigate this we'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by HungQB** [comment]
Awesome, I fixed it at your suggestion. Thanks for your help !
