### ISSUE TITLE
Layout orientation for app:controller_layout_id

### ISSUE THREAD

**Issue by cohenItay** [google/ExoPlayer#8558]
Just define a simple fragment / activity. 

use: 
```xml
 <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="fixed_width"
        app:controller_layout_id="@layout/exo_player_controls_full_screen"
        app:keep_content_on_player_reset="true"/>
```

while exo_player_controls_full_screen has orientations :
```
land/exo_player_controls_full_screen
prot/exo_player_controls_full_screen
```

result: portrait is always used, event though when in landscape mode.

**Comment by ojw28** [comment]
Perhaps the activity isn't being recreated because you have `android:configChanges="...orientation..."` in your manifest. See [this page](https://developer.android.com/guide/topics/resources/runtime-changes) for more information. It's also possible that you've misspelled `port`, although this is most likely just a typing error in your report.

The above tips aside, it's not possible for us to accurately diagnose your problem from the very incomplete information you've provided. For us to assist further, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
