### ISSUE TITLE
ExoPlayer requests an unwanted segment after quality switch 

### ISSUE THREAD

**Issue by SukritGupta17** [google/ExoPlayer#8562]
### Description

Running some test content (HLS - 2 second segments) I've noticed that ExoPlayer downloads the first segment of a quality once again when it switches to a different quality after the initial start up quality.
When the video starts, ExoPlayer uses its DefaultBandwidthMeter to select a starting quality based on the network type, if the network is actually slower it will switch down the quality after the first segment of the initial quality, but will re-download the first segment of the new quality.
Too illustrate this I ran a test video with network profiler turned on and recorded the requests, please see the attached image:
<img width="1445" alt="Screen Shot 2021-02-08 at 4 22 41 pm" src="https://user-images.githubusercontent.com/4430757/107179143-e13ce580-6a29-11eb-88d6-39d5af64f78b.png">

The video playback starts from 1440p and then drops down to 720p after the first segment, but ExoPlayer downloads the first segment of 720p as well.

Is this an expected behaviour?

### Reproduction steps

- Get the ExoPlayer demo application:
    - git clone https://github.com/google/ExoPlayer.git.
    - checkout to latest tagged release git checkout tags/r2.12.0
    - open the demo app found in demo/main.
- Add the test content in the media.exolist.json file found under demo/assets:
    - Add:
```
{
"name": "Sample content",
"uri": <Emailed to dev.exoplayer@gmail.com using a subject in the format "Issue #1234">
}
```
under the HLS section
- Run with Network profiler turned on
- In the Emulator, drop the signal quality so the initial bandwidth estimates are incorrect and the quality switches after the first segment.
- Observe the requests being made.

### A full bug report captured from the device
No bug report required as the player does not produce any errors.

### Version of ExoPlayer being used
ExoPlayer version 2.12.0

### Device(s) and version(s) of Android being used
Pixel 4 android emulator, Android version 11

**Comment by christosts** [comment]
Using the playlist you provided, there are 'overlapping' downloads as intended.

The overlapping downloads are expected with the specific HLS playlist: when changing video tracks, the player will re-download the last segment of the previous track. For example, if at segment 19 the player decides to switch from 480p to 720p, it will download segment 18 for 720p as well. You should see overlapping downloads for every track switch with the specific playlist. This is due to the HLS spec not guaranteeing that the every segment starts with a key-frame. In order to make seamless transitions between  tracks, the player re-downloads the previous segment in the new track in order to locate the last key-frame just before the adaptation point.

If you let the playback continue and the player makes more adaptation switches, you should be able to see this pattern on every track switch. I'll close the ticket for now, but if you see a different behavior (e.g. downloading the 1st segment on every track switch regardless of the current position) please re-open.

If overlapping segment downloads is a concern for your use-case, consider using the [EXT-X-INDEPENDENT-SEGMENTS](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#page-16) attribute in the playlist which informs the player that each segment can be decoded independently. That would prevent the player from performing overlapping downloads. You need to of course ensure that segments are encoded properly of course.
