### ISSUE TITLE
Any kind of animation on top of exoplayer results in video performance issues

### ISSUE THREAD

**Issue by boulaycote** [google/ExoPlayer#859]
I am trying to add scrolling text on top of a video playback. As soon as the animation starts, the video playback rate rapidly falls. When the animation ends or is stopped, performance gets back to normal.

I have also noticed that when I plug in a mouse and I move the cursor around over the video, the same thing happens.

Should this normally be an issue, or is it related to my devices specs somehow?

The animation is a `TextView` being moved around with an `ObjectAnimator`.

Thanks

**Comment by ojw28** [comment]
All ExoPlayer does is to draw into the surface it's provided with. Any UI performance issues are beyond the scope of this issue tracker, so you'll likely have to try and figure this out for yourself. A good resource is the Android [performance tools page](https://developer.android.com/tools/performance/index.html). The rendering analysis tools provided there may well help you track down the root cause of the problem.
