### ISSUE TITLE
Access to playing Ad uris

### ISSUE THREAD

**Issue by fpitters** [google/ExoPlayer#8590]
We haven't found any way to access playing Ad stream URL that are hold inside `AdPlaybackState.AdGroup`. 

The urls are being reported as media source events (`onLoadStarted` or `onLoadCompleted`) but it's not possible to match them with Ad groups/indexes.

Is there anything we have missed? 
Otherwise would it be possible to provide them through `Period` or some other API?

**Comment by andrewlewis** [comment]
Edit: the information below doesn't help because `Period.adPlaybackState` is private.

They are in [`AdPlaybackState.AdGroup.uris`](https://github.com/google/ExoPlayer/blob/56feb96/library/common/src/main/java/com/google/android/exoplayer2/source/ads/AdPlaybackState.java#L52) (and as you are probably aware, you can get the `AdPlaybackState` from the `Timeline.Period`).

**Comment by andrewlewis** [comment]
Sorry, just saw that `adPlaybackState` is private in `Timeline.Period`.

**Comment by andrewlewis** [comment]
We could add a getter, but could you give some more details on your use case first? I'm not sure why apps would need this information. Thanks.

**Comment by tonihei** [comment]
> The urls are being reported as media source events (onLoadStarted or onLoadCompleted) but it's not possible to match them with Ad groups/indexes.

The ad group and ad indices are reported for each event as part of `EventTime.mediaPeriodId.adGroupIndex/adIndexInAdGroup`.

**Comment by andrewlewis** [comment]
Good point, thanks Toni!

**Comment by fpitters** [comment]
Yep, sorry to say, only for tracking purpose :)

> The ad group and ad indices are reported for which each event as part of 
`EventTime.mediaPeriodId.adGroupIndex/adIndexInAdGroup.`

Thanks, I've missed that.
