### ISSUE TITLE
How do I enable Closed caption in Exoplayer when in Picture-in-picture mode?

### ISSUE THREAD

**Issue by guitarsforever** [google/ExoPlayer#8596]
**Background:**

I already have exoplayer + PiP implemented in my Android application. The player supports Closed captions well when in Activity mode or Full-screen mode.

**Problem/Question**

When exoplayer/ activity is in PiP mode, the Closed Captions gets disabled automatically. I understand that for mobile the real-estate is very small in picture-in-picture mode to support CC. However, I want CC to be enabled for Exo-player in PiP mode when enabled on a tablet. There is no documentation by Android/Google to handle this or have any reference anywhere. Any help is appreciated.

**Comment by moneytoo** [comment]
CC work for me in PiP in latest ExoPlayer. I just tweak the size using setFractionalTextSize and it's quite usable then. (I'm not sure if I make anything special to achieve that.)

**Comment by icbaker** [comment]
I'm not aware of anything special ExoPlayer is doing with subtitles + picture-in-picture - I would naively expect it to "just work".

As @moneytoo said you may need to change the text size, because it's often defined as a percentage of the viewport height, which might result in very small text in PiP mode. This can depend on your source subtitles - it's possible for them to set an absolute text size in terms of pixels.

If you're still seeing problems can you provide  a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

The easiest way is probably to fork the demo app and add your PiP logic. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by guitarsforever** [comment]
Thank you. This helped.
