### ISSUE TITLE
Help troubleshooting cache being ignored

### ISSUE THREAD

**Issue by sidferreira** [google/ExoPlayer#8597]
I'm currently stuck to version 2.11.4 of Exoplayer. I created a migration path from 2.9 to this version and the database seems to be upgraded properly.

Now, when I try to play the content, it seems to always pick the content from the internet, not loading if I'm offline.

The `mediaSource` is set based on
```
dataSourceFactory = new CacheDataSourceFactory(
        pair.second,
        upstreamFactory,
        new FileDataSource.Factory(),
        null,
        CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
        null);
return new ProgressiveMediaSource
        .Factory(dataSourceFactory)
        .createMediaSource(uri);
```

> EDIT:  For now the upstream is `FileDataSource` so I'm sure it won't use the internet to fetch any missing data.

I'm unsure how to debug to find out what is wrong...

__EDIT 18 Feb__

I had a partial (or false-positive) success yesterday but most of the problem still happens.

My "success" was when it managed to play the 1st minute of the call but then got errors not finding parts of the stream.

The `ActionFile` content was saved with a custom `Action`( #8543 ), with some specifics behaviors on `getSegment` block. I wonder if I need to port the `DESERIALIZER` to the newer version to be able to play it properly.

If it works best, feel free to contact me through email.

**Comment by christosts** [comment]
@ojw28 can you take a look?

**Comment by ojw28** [comment]
A note regarding the customization described in #8543: ExoPlayer 2.12.0 added direct support for downloading segments in parallel, by passing an executor to the `DownloadManager`. See [this documentation](https://exoplayer.dev/downloading-media.html#creating-a-downloadmanager). Newer versions of the ExoPlayer demo app use `Executors.newFixedThreadPool(/* nThreads= */ 6)` to allow up to six parallel requests, shared across all ongoing downloads. An application that has an existing executor for background fetches (e.g., to load images) may wish to use that. So, if you're trying to lose this functionality, 2.13.2 or 2.12.2 would be better bets to upgrade to. ExoPlayer's built in support is significantly better than the support that your third party vendor added.

Regarding the issue described here: It's a little unclear exactly what problem you're describing. When you say that the cache is being ignored, is this (a) only for downloads that have been upgraded having been downloaded with a version of your app that used 2.9, or (b) also an issue for new downloads made by the updated version of your app?

* If (a) then it's either a problem with the upgrade process or a problem with the download functionality of the old version of your app. In this case, I'd:
  1. Double check whether your download functionality really worked correctly in the previous version of your app. I.e., are you certain the old version didn't also have the problem where it would try and request downloaded content from upstream?
  2. Check whether the issue only applies to downloads that were _partially_ completed when you performed the upgrade, as opposed to those that were _fully_ downloaded. Specifically for your custom upgrade process, the way your `multihls` variant worked was to add multiple downloads, each of which was responsible for downloading only part of the content. After the upgrade, these are going to be flattened into a single download entry for the content. If only a subset of the multiple downloads have completed prior to upgrade, you need to be careful to ensure that the single download entry after the upgrade gets state `QUEUED` rather than `COMPLETED`. In terms of the demo app, this would be done by upgrading `DOWNLOAD_TRACKER_ACTION_FILE` (which stores completed downloads) first, and `DOWNLOAD_ACTION_FILE` (which stores in-progress downloads) second. This is the opposite order to what the demo app currently does.
* If (b) then it's probably just an issue with the new version of your app and/or ExoPlayer 2.11.4, and so you should be able to debug the problem without worrying about the previous version or the upgrade step.

> The ActionFile content was saved with a custom Action, with some specifics behaviors on getSegment block. I wonder if I need to port the DESERIALIZER to the newer version to be able to play it properly.

There should be no need to do this. If you get the upgrade right then things should work

**Comment by sidferreira** [comment]
@ojw28 Indeed it was a poor choice of words. So, at that moment I had the cache configured, action file upgraded, everything "ok" but it seems that it was just ignoring things. In my last test, a chunk of the video loaded properly but the remaining didn't. AFAIR I did test the download to be sure it was working completely, but as it is 2 weeks ago I'll do another round of tests.

According to item `II`, I had to do a workaround and I was forcing the `COMPLETE` state, so this is already an issue found.

I'll take a round of tests on this and let you know.

Thanks in advance for this help!

**Comment by sidferreira** [comment]
@ojw28 I did some tests, including trying to bypass the "multiple download" thing but I still have issues playing the download.

The code to create the media source is:
```
FileDataSource.Factory upstreamFactory = new FileDataSource.Factory();

DataSource.Factory dataSourceFactory = new CacheDataSourceFactory(
        downloadDirectory,
        upstreamFactory);
//        new FileDataSource.Factory()
//        null,
//        CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
//        null);

return new ProgressiveMediaSource
        .Factory(dataSourceFactory)
        .createMediaSource(uri);

// return new HlsMediaSource
//        .Factory(dataSourceFactory)
//        .createMediaSource(uri);
```

Tried both HLS and Progressive and none of them seems to load anything.
I used `FileDataSource` as upstream just to avoid it load from the web if it fails.

I wonder how to debug that to find out if the problem is:
a) the cache is not resolving stuff properly
b) the migration is failing
c) there's a small detail missing (like using HlsMediaSource.Factory instead of ProgressiveMediaSource.Factory).

I may send these files if needed

**Comment by ojw28** [comment]
> It's a little unclear exactly what problem you're describing. When you say that the cache is being ignored, is this (a) only for downloads that have been upgraded having been downloaded with a version of your app that used 2.9, or (b) also an issue for new downloads made by the updated version of your app?

It remains unclear from both of the responses above what the answer to this question is.

> I wonder how to debug that to find out if the problem is:
> a) the cache is not resolving stuff properly
> b) the migration is failing
> c) there's a small detail missing (like using HlsMediaSource.Factory instead of ProgressiveMediaSource.Factory).

You should be able to tell whether it's (b) or something else just through answering the question above. Which should be possible to do with a bit of manual testing.

**Comment by sidferreira** [comment]
@ojw28 we're not downloading contents as we're changing our download process. We're just trying to play old content. I'll try to add the download feature real quick just to find out the answers to A/B. Note that the downloads are working as expected on the older version.

**Comment by ojw28** [comment]
Marking as `needs more info`. As of now it sounds like this is probably an issue with your upgrade procedure from a non-standard previous implementation.

**Comment by sidferreira** [comment]
@ojw28 sorry for the long delay, after fixed I had to run against the clock.
In the end, using `DownloadHelper.createMediaSource(downloadRequest, cacheDataSourceFactory);` addressed the missing problems.
Thanks for all your help!
