### ISSUE TITLE
Switch problem between the adaptation-set videos

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#8600]
Hi,

I have a problem with the switching  between two videos adaptation-set  with this stream provided by dash-if : https://dash.akamaized.net/dash264/TestCasesIOP33/adapatationSetSwitching/1/manifest.mpd
In fact, ExoPlayer fails to play the second adaptation set implicitly. The traces below show that the trackSelector does not select the tracks of the second video adptation-set  :

_D/EventLogger:       Group:0, adaptive_supported=YES_NOT_SEAMLESS [
D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, bitrate=999120, codecs=avc1.640028, res=1920x1080, fps=24.0, language=en, supported=YES
D/EventLogger:       [X] Track:1, id=2, mimeType=video/avc, bitrate=2003095, codecs=avc1.640028, res=1920x1080, fps=24.0, language=en, supported=YES
D/EventLogger:       [ ] Track:2, id=3, mimeType=video/hevc, bitrate=1029626, codecs=hev1.1.6.L120.90, res=1920x1080, fps=24.0, language=en, supported=YES
D/EventLogger:       [ ] Track:3, id=4, mimeType=video/hevc, bitrate=2067007, codecs=hev1.1.6.L120.90, res=1920x1080, fps=24.0, language=en, supported=YES
        ]_

Does exoPlayer support multi video codec streams ?
the "adaptation-set-switching" TAG,  is it mandatory to switch implicitly from  one video adaptation-set to another  ?

BR,

**Comment by tonihei** [comment]
The adaptation sets contain representations with different codecs. Because they are marked with the `"urn:mpeg:dash:adaptation-set-switching:2016"` property, both adaptation sets are merged together to one ExoPlayer `TrackGroup` as seen in your `EventLogger` snippet above. This theoretically allows switching between these tracks during playback. 

The other relevant factor are the renderers that need support for switching between tracks of different codecs. ExoPlayer tests the renderer support for this and the `adaptive_supported=YES_NOT_SEAMLESS` output tells you that they support adaptation between all these tracks, but whenever we change codecs, the adaptation won't be seamless. That's why the `DefaultTrackSelector` only selects two tracks of one codec so that it can adapt seamlessly between them.

You can also change the configuration of the track selection to your needs:
 - `DefaultTrackSelector.ParametersBuilder.setPreferredVideoMimeType(mimeType)` to set your preferred mime type.
 - `DefaultTrackSelector.ParametersBuilder.setAllowVideoMixedMimeTypeAdaptiveness(true)` allows the player to adapt between different MIME types.
 - `DefaultTrackSelector.ParametersBuilder.setAllowVideoNonSeamlessAdaptiveness(true)` allows the player to use non-seamless adaptation. You probably need this flag and the flag above to actually select all 4 tracks in your example. 

Based on this particular stream, I also wouldn't recommend adaptation between the different mime types because their bitrate order mixes them to [avc->hevc->avc->hevc], so the player would constantly run into non-seamless adaptation updates.

**Comment by Xlcghs** [comment]
Thank you for this explanation. 
It is clear !

**Comment by tonihei** [comment]
Closing because the question was answered.
