### ISSUE TITLE
Exoplayer works unstable when there are packet lost

### ISSUE THREAD

**Issue by motokazmin** [google/ExoPlayer#8602]
Hello. Before I need to explain a little about our environment  where we observe bug described below. 
We are telecom company and provide our clients by tv content through multicast . Due to network issues users may suffer  from this. Therefore we use own recovery server to request lost packets. The scheme is the following:

![viprox](https://user-images.githubusercontent.com/29951880/108339265-45a93300-71e8-11eb-9426-f80155a09a93.png)

Here viproxik service converts input stream to tcp one and in case of lost it requests lost packest from stream recovery server.
All work fine except case with heavy losses and fat streams( to simulate network issues we use mikrotik). In this case I obverve the following:

![memory](https://user-images.githubusercontent.com/29951880/108341041-4e9b0400-71ea-11eb-883f-21392d6ac966.png)

The picture above shows good case when after few minutes(when audio is Ok bur video is freezed) the player restores its functionality. But often I have crash our application after consuming all available memory.

Investigating this problem I have found the following. At some moment MediaCodecVideoRenderer::processOutputBuffer stops being called by MediaCodecRenderer::drainOutputBuffer because  
codec.dequeueOutputBuffer(outputBufferInfo, getDequeueOutputBufferTimeoutUs()) returns -1.

Also I see other problem. When memory consumtion increases at this moment I can switch on other channel or turn off packet loss on mikrotik (to restore streaming)- I see that memory consumption never returns to usual level.

I have found similar issue, https://github.com/google/ExoPlayer/issues/6647 , and we tryed to fix my problem as described in this one. I see that the behaviour of my player is changed - but not how I whant . Now I have periodical stop/restart player, memory consumption is restricted now. But  after a few time my player stops forever.

**Comment by christosts** [comment]
There are multiple parameters here so I'll need to ask a few questions in case I can offer any assistance. Because of your setup, I can probably only offer debugging advice since I cannot replicate your setup.

According to your diagram, the player is downloading the video from the vicproxik using TCP, but is that HTTP? Is your service receiving a UDP stream and re-packages it in some format than can be delivered over HTTP? 

Can you please share more information on the environment:
- what is the exact format of the transported video between ExoPlayer and vicproxik? DASH? Progressive file (mp4, mkv)?
- if it's DASH, how big are the segments (duration)?
- what is the bitrate of the video? Since you are converting a UDP stream, should I assume there is only one bitrate/resolution available? What is the resolution and bitrate for audio and video?
- what is the version of ExoPlayer you are using?
- what is the bandwidth throughput between ExoPlayer and vicproxik? Please check values reported from DefaultBandwidthMeter, if you are not passing a custom bandwidth meter.
- what are the values that you are now using on DefaultLoadControl that solved the memory issues?

> Investigating this problem I have found the following. At some moment MediaCodecVideoRenderer::processOutputBuffer stops being called by MediaCodecRenderer::drainOutputBuffer because
> codec.dequeueOutputBuffer(outputBufferInfo, getDequeueOutputBufferTimeoutUs()) returns -1.

That indicates the MediaCodec does not have decoded video samples available, which is expected to happen while the player is in a buffering state. While playback is frozen, the player is waiting for data to arrive from the network and to be fed to the MediaCodec (look for calls to codec.queueInputBuffer() or codec.queueSecureInputBuffer()), but the player still checks if there are video frames available for rendering.

By default, when the player is rebuffering, it will wait until 5 seconds of video are buffered in order to start playback (see [DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS](https://github.com/google/ExoPlayer/blob/r2.13.1/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L55)). For 5 seconds of video to occupy 200MB in memory as your graph suggests, it means the bitrate is 320Mbps. Either my calculation is way off, or something is not working as expected. I've asked above, what is the bitrate of the video? And what parameters did you set on DefaultLoadControl that solved this problem? Also, on your diagram, the player remains frozen for 4 minutes. Does it take 4 minutes to download 5 seconds of video? What kind of packet loss did you introduce? It'd be interesting to see how many data the player downloaded during that interval. Let's clarify first how data are transported between the server and ExoPlayer (HTTP?) and then I'll provide more specific help on this.

> I have found similar issue, #6647 , and we tryed to fix my problem as described in this one. I see that the behaviour of my player is changed - but not how I whant . Now I have periodical stop/restart player, memory consumption is restricted now. But after a few time my player stops forever.

It sounds like the parameters you have set on DefaultLoadControl are not letting the player buffer enough data (in terms of duration) to sustain smooth playback. That could be if the content is of high bitrate but the bandwidth throughput (or latency with the server) cannot accommodate this content bitrate. That's why I asked the information above.

If you are testing this with the demo app, can you please share logs and a bugreport from the device after the player stops forever?

**Comment by motokazmin** [comment]
Hello @christosts - I have collected logcat as you asked. Bellow are answers on your questions:
1. According to your diagram, the player is downloading the video from the vicproxik using TCP, but is that HTTP? - **yes it is HTTP stream**
2.  Is your service receiving a UDP stream and re-packages it in some format than can be delivered over HTTP? -  **udp payload is transmetted to  http one**
3. what is the exact format of the transported video between ExoPlayer and vicproxik? DASH? Progressive file (mp4, mkv)? - **ts format**
4. what is the version of ExoPlayer you are using? - **2.11.1**
5. what is the bandwidth throughput between ExoPlayer and vicproxik? - **exoplayer and viprocik live on same stb device, viprocik uses loopback to communivate with exoplayer**
6. what is the bitrate of the video? - **I guess approximately 5 - 15 Mbps(your calculation was wrong, calculate not for 5 seconds but 5 minutes)**
7. what are the values that you are now using on DefaultLoadControl that solved the memory issues? - **I use default settings.**

Here is memory consumtion for logcat file:
![memory_for_logcat](https://user-images.githubusercontent.com/29951880/108505881-1d453580-72c9-11eb-9503-620e87cdf1b9.png)

Logcatfile is : 
[logcat_for_exeplayer.txt](https://github.com/google/ExoPlayer/files/6010042/logcat_for_exeplayer.txt)

Also I'd like to give more comment. I have turn off log from :processOutputBuffer method to avoid spamming. But also I see negative and too high values for earlyUs(**when problem appeares**)

_processOutputBuffer, isStarted true, pos is 17034277, earlyUs is 9223372036837741532, result: true
processOutputBuffer, isStarted true, pos is 49233452, earlyUs is -73452, result: true__

**Comment by christosts** [comment]
> 6\. what is the bitrate of the video? - **I guess approximately 5 - 15 Mbps(your calculation was wrong, calculate not for 5 seconds but 5 minutes)**

On the original graph, there is an interval of `~4 minutes` between labels `video freeze` and `restore video`. During that time, the player is probably buffering content. By default, the player would automatically start playback if at least 5 seconds of video is buffered. As I originally wrote, if the 200MB of memory were occupied by buffered content, for those 5 seconds of content needed, the video bitrate would have to over 300Mbps, which sounds unrealistic.

Do you keep the player paused while the packet loss is happening (and manually restart playback)? Or do you let the player automatically restart playback?

I see in the attached logs that they are produced from your app. There are many parameters in play here, so it's best to narrow down the problem. Can you please try playing the content from with the demo app? Can (if not already) vicproxik run on a separate process, perhaps on a separate physical device? That would help figure out if the problem is coming directly from the player

**Comment by motokazmin** [comment]
Hi @christosts 
I have reproduced bug on exoplayer test app + udpxy + packets drop on mikrotik. Same behaviur. Now you can reproduce it easy. I will upload modified exoplayer demo project + executable udpxy service + modified media.exolist.json

[udpxy.zip](https://github.com/google/ExoPlayer/files/6038459/udpxy.zip)
.
Below is small howto 👍 

1. Wrapper on udpxy
        demos/main/src/main/java/com/google/android/exoplayer2/demo/FileUtils.java
        demos/main/src/main/java/com/google/android/exoplayer2/demo/UdpxyService.java


2. SampleChooserActivity::onCreate - starting udpxy service

    try {
      startService(new Intent(this, UdpxyService.class));
    } catch (IllegalStateException e) {
      Log.d("krv", "Cannot start udpxy service: " + e);
    }

3. Upload udpxy file in /data/data/com.google.android.exoplayer2.demo/files/ folder

4. Change "uri": "http://127.0.0.1:45242/udp/235.10.10.169:1234" (media.exolist.json)  on your multicast address 

5. Run demo app on device, make packet drop...

**Comment by 0xb0ba** [comment]
you can run udpxy in any convenient way, for example adb.
drop multicast packets for example iptables:
"iptables -A INPUT -i eth0 -d 225.0.0.0/8 -m statistic --mode random --probability 50 -j DROP"

scheme: network--multicast--drop--udpxy--http--player

**Comment by motokazmin** [comment]
He @christosts .
I'm trying to understand why player goes into a stupor. Two illustrate my things I will use pictures from docs. Below is my memory dump when stupor is happened:
![Снимок экрана (64)](https://user-images.githubusercontent.com/29951880/109188184-b5e52500-77a3-11eb-9116-3233ab1cf8e6.png)
It seems for me that we continue to load peaces of data from internet but at same time don't  stop consumation by video render - as a confirmation I hear the audio all time before crash. As we can see from the stack trace we continue to allocate memory in 
SampleQueue class.

![Снимок экрана (65)](https://user-images.githubusercontent.com/29951880/109189385-06a94d80-77a5-11eb-83b9-b2b3678a92fd.png)


My idea - player has logic error in LoadControl or Extraxtor classes. We're supposed to stop it consumation at some moment. But really I can't imagine what is the right thing to do, given that the guaranteed delivery protocol is used. I think the best solution in this situation - flush all buffers and reinitialize player...

**Comment by christosts** [comment]
I replicated your setup as much as possible but I did not see the memory issues you mentioned.

To clarify things, your attached zip file contains an Android build of udpxy and some code on the ExoPlayer demo app that starts the udpxy executable. That said, the part that requests lost packets  from your initial description is missing.  That means that any packet loss will not be recovered and the video will have errors on screen. Also you did not provide a stream to use. From your instructions

> * Change "uri": "http://127.0.0.1:45242/udp/235.10.10.169:1234" (media.exolist.json)  on your multicast address

I assume you have access to a UDP stream, which is not available to us. I used VLC to stream a local file over UDP to my device. I tried introducing 1-50% of packet loss. Overall, the memory of the player in my tests seems to be stable. 

I wanted to check if the player has any memory leak while downloading content from a very slow connection. I also checked downloading from an HTTP server throttling the bandwidth to force the player to go into buffering, and still did not see any obvious memory issues.

**Comment by christosts** [comment]
> It seems for me that we continue to load peaces of data from internet but at same time don't stop consumation by video render - as a confirmation I hear the audio all time before crash. As we can see from the stack trace we continue to allocate memory in SampleQueue class. My idea - player has logic error in LoadControl or Extraxtor classes. We're supposed to stop it consumation at some moment. But really I can't imagine what is the right thing to do, given that the guaranteed delivery protocol is used. I think the best solution in this situation - flush all buffers and reinitialize player...

If the player is given data from udpxy, it will store them in the sample queues and renderers will attempt to at least decode them. Since in the setup udpxy is fed with incomplete information (lost packets are not recovered), it's unclear to me what the output of udpxy is. Unfortunately, I do not have the capacity to inspect the stream that udpxy produces. Are you certain that all the memory is occupied by the sample queue?

**Comment by motokazmin** [comment]
hi @christosts .
Try make the same experiments with packet loss 70% and stream bitrate 10-15Mbts...

**Comment by motokazmin** [comment]
Hi @christosts 
Please confirm how you can reproduce the bug before any other activity - I will be able to plan my future work.

**Comment by motokazmin** [comment]
Hi @christosts .
I'd like to subscribe my suggestion how to fix this by. This solution has some side effects - I hope yoou will correct me to make fix more accuracy.
I have added observers on AudioUnderrun and DroppedVideoFrames and reinitialize player when one of the these events is happened:
```
  private class ActivityAnalyticsListener implements AnalyticsListener {
    @Override
    public void onAudioUnderrun(
        EventTime eventTime, int bufferSize, long bufferSizeMs, long elapsedSinceLastFeedMs) {
      Log.d("krv", "ActivityAnalyticsListener::onAudioUnderrun, next initializePlayer");
      initializePlayer();
    }

    @Override
    public void onDroppedVideoFrames(EventTime eventTime, int count, long elapsedMs) {
      Log.d("krv", "ActivityAnalyticsListener::onDroppedVideoFrame, next initializePlayers, count = " + count + "  elapsedMs = " + elapsedMs + " eventTime = " + eventTime.toString());
      initializePlayer();
    }
```

I see that this fix impoves user expireence and works stable. But has the following limitations:
1. Events (AudioUnderrun, DroppedVideoFrame) happen much later than the moment of the permanent frieze of the picture-about a minute and a half. For the user experience, it would be better to do the player reinitialization earlier.
2. Event onDroppedVideoFrames is happened twice - as result I have one extra player initialization
3. Memory after first reinitialization is not freed.

![Снимок экрана (66)](https://user-images.githubusercontent.com/29951880/109947573-83c74c00-7cea-11eb-88c9-55af2e53f0e9.png)

4. I would like to reduce the re-launch time of the player after reinitialization...

**Comment by christosts** [comment]
> hi @christosts .
> Try make the same experiments with packet loss 70% and stream bitrate 10-15Mbts...

I could not reproduce. I used 70% packet loss and I streamed with vlc the [60fps 1080p video file](https://github.com/google/ExoPlayer/blob/r2.13.2/demos/main/src/main/assets/media.exolist.json#L195) in the demo app, which is encoded at ~10Mbits. I need to stress that the environment setup is quite irregular: the UDP stream is broken due to the packet loss and I can't tell how udpxy is re-constructing the stream.

Regarding the callback handling: The onAudioUnderrun and onDroppedVideoFrames can happen during normal playback, and it's risky to be taken as indications of severe errors.  If your app decides to re-initialize the player immediately when these events occur, it might be too sensitive. 

> Events (AudioUnderrun, DroppedVideoFrame) happen much later than the moment of the permanent frieze of the picture

The onDroppedVideoFrames is called whenever a number of dropped frames has been observed, by default it's every 50 dropped frames. If you want this callback to be called sooner/earlier, you can tune its sensitivity when constructing the video renderer [here](https://github.com/google/ExoPlayer/blob/r2.13.2/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L377). The onAudioUnderrun callback is called when lower-level audio buffers are not filled fast enough while the app has downloaded data already, and it's used to indicate there's a delay inside the player to deliver downloaded data to the audio renderer. But if audio-buffers run out of data because the player has not downloaded data in the first place, the player should be in a BUFFERING state this event will be not triggered. Instead, `onPlaybackStateChanged` will have been triggered first to tell the application the player is not playing. 

In your use-case however, things are more complicated. As I said, if both audio and video freeze, the player may switch to a buffering state and raise the `onPlaybackStateChanged` event to detect when the player enters a `BUFFERING` state. Your listener can wait for that event and decide to re-initialize the player. That said, going to a buffering state can happen under 'regular' conditions too (e.g. network was a bit slow for a while), therefore your logic to re-initalize the player should take more criteria into consideration (e.g. player is in buffering state for at least X time and you have detected severe packet loss in the UDP stream). 

However, you are testing with a UDP stream that is missing packets and it's not guaranteed if the player will switch to a buffering state. If you want to stop the player when the video seems to be frozen, you can attach a [VideoFrameMetadataListener](https://github.com/google/ExoPlayer/blob/r2.13.2/library/common/src/main/java/com/google/android/exoplayer2/video/VideoFrameMetadataListener.java). This listener raises an callback for each frame. Your app can detect if frames are not being rendered for some time in order to detect video is frozen.

> Event onDroppedVideoFrames is happened twice - as result I have one extra player initialization
> Memory after first reinitialization is not freed.

I think this is probably because the previous player instance is still alive. Looking by the your code snippet, it looks like you are calling `initializePlayer()` [directly from the demo app](https://github.com/google/ExoPlayer/blob/r2.13.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L254)? If yes, you need to first release the existing player and then create a new one.

Overall comment: As I mentioned above, your setup looks quite irregular. You are testing a UDP stream under severe packet loss and using a proxy which I'm not sure how it re-constructs the stream. ExoPlayer has not been designed to work under such conditions. From you original description of the issue, it looks like you are also developing a module to read and  -to some extend- understand UDP streams. If you are going to that level of detail, have you considered using ExoPlayer's [support for UDP](https://github.com/google/ExoPlayer/blob/r2.13.2/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java) directly, possibly adding custom logic in [UdpDataSource](https://github.com/google/ExoPlayer/blob/r2.13.2/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java) to work with re-delivered packets that your "Stream recovery server" is doing?
