### ISSUE TITLE
Problem with exoplayer bridge in Unity. Stuttering on high resolutions...

### ISSUE THREAD

**Issue by Yarrrrrrr** [google/ExoPlayer#8605]
Hey guys! 
**We have an interesting stuff to investigate.** 
The problem is with exoplayer bridge in Unity. The problem is that on Oculus Quest 2 it looses frames on 8K resolution videos 60 fps. It looks like stuttering on high resolutions/fps.
We have checked it on AVPro version 1.11.7 and 2.0.6. Also we have checked it on our own Exoplayer bridge. (They use exoplayer 2.12.1 and 2.8.4). Result is the same, for some reason exoplayer updates the texture with the different delay. 
We have tried AVPro in Unity 2018.4, 2019.4 and latest 2020 version. The behavior is the same, it's skipping frames. For some reason internal Unity Video player (starting from version 2019) is not skipping frames, but it's to slow for our purposes. Also Skybox VR player for Oculus Quest is not stuttering as well, but they use their own fork of exoplayer.
We have prepared the demonstration video with blinking dots. You can use it to check it on your side.
Also we've attached apk file for Oculus Quest with AVPro demonstration scene playing in video. You can check how it stutters. Just look to left and right after start. Video is mapped to the standard AVPro 360 mesh. When AVPro will skip the frame you won't see the corresponding dot.

At the same time CPU and GPU of Oculus Quest 2 is not overloaded at all so the bottleneck is somewhere else.
**If you have any ideas why it could happen, please share your thoughts! 
Thanks in advance!**

Video:
https://www.dropbox.com/s/a799kpispvyoyz3/vrtest_grid3x2_60fps_8k_hevc_180_180x180_3dh_LR.mp4?dl=0
APK for Quest/Quest2:
https://www.dropbox.com/s/78bn21k43hhu2oi/testavpro.apk?dl=0

**Comment by christosts** [comment]
We can't offer detailed assistance as we don't have a way to replicate your setup, but here are some high-level ideas that may help. First of all, I'm assuming your content is being decoded through MediaCodec. If not, then the remaining comment does not apply.

To address dropped frames/stuttering on high resolution/bitrate/frame rates, there are 2 features in 2.12.1 that we have tried in the past. Both of them are not enabled by default (the second is still experimental) and both of them try to tune the interaction of ExoPlayer with the platform's MediaCodec. You might want to try them separately or in combination. You need to have access to how the player is constructed, which I guess you have through your own bridge, right?

First, you can try setting a [render time limit](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L465) on MediaCodecRenderer instances. Try out values from 10 to 40 milliseconds, and even try setting a different limit for audio (MediaCodecAudioRenderer) and video (MediaCodecVideoRenderer). You must set the time limit right after creating a MediaCodecRenderer instance. 
- You can either pass your own renderers instances to the player, so that you instantiate each renderer yourself.
- You can pass a renderer factory to the player. Maybe the easiest way is to wrap `DefaultRenderersFactory` and when [createRenderers](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L303) is called, iterate over the renderers the `DefaultRenderersFactory` returned and call `setRenderTimeLimitMs` on `MediaCodecRenderer` instances.

Second, you can try operating the MediaCodec in asynchronous mode. The feature will also force ExoPlayer to use a few more threads to interact with MediaCodec instances. You set it directly calling [experimentalSetMediaCodecOperationMode( OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING)](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L490) on MediaCodecRenderer instances. Similarly, this method must be called right after the renderer instance is created. If you use the renderer factory option from above, there's a method directly exposed on DefaultRenderersFactory. You can call it directly and the DefaultRenderersFactory will forward the operating mode when creating the MediaCodecRenderer instances internally. Note: this feature is experimental and hasn't been released yet. We have found at least one bug since 2.12.1.

Let me know if any you tried any of the above and made a difference.
