### ISSUE TITLE
Audio Effect

### ISSUE THREAD

**Issue by miniesahni1** [google/ExoPlayer#8617]
Observed Behaviour
I am using “setAuxEffectInfo” in Exoplayer to add an effect audio track. I am able to play audio with the effect but not able to save the audio with effect.

Question: Is it possible to also save the audio with the effect applied?

**Comment by Samrobbo** [comment]
ExoPlayer is a playback library, so the effects are only applied as the audio is processed by the device. Therefore there is no way to save or store audio once it has been adjusted by ExoPlayer effects.

**Comment by krocard** [comment]
As Sam said, the effect is applied in the platform's audio engine, just before being sent to the speaker. As a result the audio is not easily accessible. This is similar to why the audio capture in ExoPlayer doesn't have any volume attenuation or equalization.
There are 3 solutions to capture the audio after the effect is applied.
 1) Do not use a platform effect. Instead port the AOSP effect to ExoPlayer's Processor. The Effect will then be applied in your app instead of by the platform and you will have full control over it.
     - This might be significant work, but is the most flexible solution.
 2) Use the platform's [playback capture API](https://developer.android.com/guide/topics/media/playback-capture) to capture the audio just before it is mixed. It will still be full volume, but will have effect applied.
     - The playback capture API allows to capture the audio of any app, not just yours. As a result, the user will be prompted to allow your app to record other apps. This is significantly more intrusive for the user.
  3) Capture the audio without the effect from Exoplayer and reapply the effect internally using third party audio effect library.
     - This is probably the simplest solution but will not guarantee that the same audio is heard and recorded due to the difference in effect implementation.

**Comment by krocard** [comment]
3) Capture the audio without the effect from Exoplayer and reapply the effect internally using third party audio effect library. This is probably the simplest solution but will not guarantee that the same audio is heard and recorded due to the difference in effect implementation.
