### ISSUE TITLE
Error on playing mkv large file error: Decoder failed: OMX.Exynos.hevc.dec

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#8618]
I am playing to mkv large file in exoplayer but getting the error

 Decoder failed: OMX.Exynos.hevc.dec
here is the link of video i am playing :https://drive.google.com/file/d/1_WXMY2YWixBdEaDuLPdYk-IniPuBXeyw/view?usp=sharing
here is the codec screen short

![codec](https://user-images.githubusercontent.com/22340353/108710777-50403100-7536-11eb-9932-9a393a7e5848.png)

**Comment by Samrobbo** [comment]
Hi

The access is denied for me to access that video. Please provide public access and let me know once you've done that.

If there is an issue with giving public access, you can email it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by waqasyousafy** [comment]
ok  https://drive.google.com/file/d/1_WXMY2YWixBdEaDuLPdYk-IniPuBXeyw/view?usp=sharing

**Comment by Samrobbo** [comment]
Given that the content is pirated, I can't do much debugging. It's very likely that the pirated movie was recompressed with questionable codec settings, and that's whats causing the issue.

If you have another MKV file that is NOT pirated media and is exhibiting the same behaviour, we may be able to look into this more.

**Comment by waqasyousafy** [comment]
what is the solution bros other players are playing that media also is it recompressed with questionable codec settings.????

**Comment by ojw28** [comment]
@waqasyousafy - If you're going to open issues on this issue tracker, _please_ start filling in the issue template properly. A one line issue description akin to "doesn't work" is not useful to anyone, and spams a relatively large number of people with a pointless email.

If content is not playing correctly, please fill out the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) providing the requested information. For example, you should provide a bug report, ideally when trying to play the content in the ExoPlayer demo app, captured just after playback failure occurs. This would let us see useful logging that occurs in the lead up to the failure you experience. It's possible (although not guaranteed) that this logging would allow us to instantly tell you why this content does not play. Providing a single line, like `Decoder failed: OMX.Exynos.hevc.dec`, does not give us the useful information that we need to efficiently handle your request. I would also note that at least one of your previous issues was reporting a valid issue, but provided so little information that we were unable to understand what the problem was until months later. Providing clear reproduction steps at the time would have likely avoided this.

If you're not going to go to the effort of filing issues as requested, please refrain from filing them at all, since it's a waste of your time, our time, and anyone who subscribes to this issue tracker's time. If you could also refrain from calling us "bros" in favour of something a little more inclusive, that would also be appreciated. Thanks.
