### ISSUE TITLE
Why getSelectedIndex in FixedTrackSelection is returning 0

### ISSUE THREAD

**Issue by nandovelazquez** [google/ExoPlayer#8621]
Hi,
In my application, I try to get the selected audio track by getting the TrackSelection first and then looking for its selected index. I noticed I was always getting 0 from `trackSelection.getSelectedIndex()` and I found that this is hardcoded only for the `FixedTrackSelection` class and not for the `AdaptiveTrackSelection` class.

Is there any particular reason for this? Is there another way to get the selected track?

Thanks!

**Comment by Samrobbo** [comment]
The `FixedTrackSelection` class javadoc states `A {@link TrackSelection} consisting of a single track.`. Therefore `getSelectedIndex()` for that track selection will always return 0, because that's the only track index it knows about. 

If you give me some more information about what you're trying to do, I can try to assist more.

**Comment by ojw28** [comment]
`TrackSelection.getSelectedIndex` is not actually intended for application use. It's a method internal to the player that's used to control adaptive track selection. In `2.14` we'll be making it harder to access, for this reason.

If you want to query the selected track, use some combination of `TrackSelection.getFormat`, `TrackSelection.getTrackGroup`, `TrackSelection.getIndexInTrackGroup` and `TrackSelection.indexOf`.
