### ISSUE TITLE
MS Smoothstreaming manifest parser should support SystemID UUID wrapped by braces

### ISSUE THREAD

**Issue by twcapps** [google/ExoPlayer#863]
Hi,

We noticed that exoplayer does not parse MS SS with a SystemID UUID wrapped in braces correctly. See example below from SS Documentation [MS-SSTR]:

    <?xml version="1.0" encoding="UTF-8"?>
      <SmoothStreamingMedia MajorVersion="2" MinorVersion="0" Duration="2300000000" TimeScale="10000000">
        <Protection>
          <ProtectionHeader SystemID="{9A04F079-9840-4286-AB92E65BE0885F95}">
            
         </ProtectionHeader>
      </Protection>
    </SmoothStreamingMedia

Older manifest files without the braces work correctly:

   <ProtectionHeader SystemID="9A04F079-9840-4286-AB92E65BE0885F95">

Newer manifest files do not:
     <ProtectionHeader SystemID="{9A04F079-9840-4286-AB92E65BE0885F95}">

Link to relevant part of the code:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingManifestParser.java#L406

This is exoplayer 1.4

**Comment by ojw28** [comment]
Interestingly, isn't the example in MS-SSTR a violation of the definition in MS-SSTR itself? Specifically, shouldn't there be a dash between `AB92` and `E65BE0885F95` in the example, since SystemID is defined as:

```
SystemID = "{"
 4*4 HEXCODED_BYTE "-"
 2*2 HEXCODED_BYTE "-"
 2*2 HEXCODED_BYTE "-"
 2*2 HEXCODED_BYTE "-"
 6*6 HEXCODED_BYTE "-"
 "}"
```

Also, isn't this definition itself also wrong, because it defines a dash before the closing curly brace?!

Those question aside, yes, we should be handling the case where the UUID is enclosed in curly braces.

**Comment by ojw28** [comment]
This is fixed in the dev branch. Thanks!
