### ISSUE TITLE
NPE in ExoPlayerImplInternal.shouldUseRequestedContentPosition()

### ISSUE THREAD

**Issue by MichaelRocks** [google/ExoPlayer#8640]
**ExoPlayer version:** 2.12.3
**Android version:** 6.0
**Android device:** ZTE Blade V7 Lite (V0720)

We receive crash reports with the following stacktrace in production:
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean MediaSource.MediaPeriodId.isAd()' on a null object reference
com.google.android.exoplayer2.ExoPlayerImplInternal.shouldUseRequestedContentPosition (ExoPlayerImplInternal.java:2371)
com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal (ExoPlayerImplInternal.java:1275)
com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal (ExoPlayerImplInternal.java:1218)
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:566)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:207)
android.os.HandlerThread.run (HandlerThread.java:61)
```

All these crashes are from the same device model but from different users. Unfortunately we're not able to reproduce this crash in a test environment, so I cannot provide any additional information.

**Comment by ojw28** [comment]
@tonihei - Any ideas about this?

**Comment by tonihei** [comment]
No idea. The value that is supposedly null is marked as non-null and as long as our static null checks are working as expected I'd assume it is indeed non-null. Also checked all places where it's set again and none of them look suspicious.

It's also not likely to be any kind of concurrency issue because the value is only written and read from our internal playback thread.

The only more far-fetched explanations I can think of are build problems (e.g. when doing incremental builds after updating ExoPlayer, combining multiple ExoPlayer versions, or problems with multidex), problems resolving the error stack trace (e.g. when using the wrong proguard mapping file), or corrupted runtimes (e.g. using rooted devices).

That all also doesn't really explain how this can be device-specific.

@MichaelRocks  Sorry for the delay with this issue. Do you have any other information regarding this issue? For example, can you see whether the affected devices are rooted for example? And how often does it happen compared to general usage of this device on your app?

**Comment by MichaelRocks** [comment]
@tonihei I believe you're right and this bug might not be related to ExoPlayer. It's quite rare and reproduces only on this particular device, which isn't rooted btw. Moreover, we don't receive these crashes on the latest versions of our app. Seems this issue should be closed. Sorry for wasting your time.
