### ISSUE TITLE
Drm enable videos get stuck on 1080p and 2x

### ISSUE THREAD

**Issue by NitinSharma639** [google/ExoPlayer#8657]
Hello Exoplayer Team

I am developing an application where I am using drm enable videos. The problem is when we play video 2x speed and change the resolution to 1080 p the video get stuck. We are using exoplayer:2.10.8. 

We can reproduce the bug many times on some devices. Is there any solution to this bug or any workaround to check if the device support some resolution or not.

There is one more issue with drm enabled content on 2x speed the frame rate is dropping. I think these both issues are due to hardware is not supporting the particular bitrate or speed. But we are not aware of any method which provide the info about device supporting particular speed or resolution.

Can you provide us some some solution or workaround. I am attaching the video and logs.

https://drive.google.com/file/d/1m3MI32F0TBzfGZ1cVXq20-TKGqR7nGwj/view?usp=sharing

https://drive.google.com/file/d/1iIfDRwxqxo2H6mGa0516vZCZe2gmbR3p/view?usp=sharing

Thanks

**Comment by krocard** [comment]
@AquilesCanta, do you have experience with time accelerated playback of drm media? I'm guessing that the drop frame is expected, but the freezing could not be.

@NitinSharma639 Could you please share a full bug report generated after the issue occurs? I'm afraid the error log you attach will not be enough to properly diagnostic the issue. Test content would also be great for us to try to reproduce.
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by NitinSharma639** [comment]
Hello Exoplayer Team

I have shared with you the test content. Please check.

**Comment by icbaker** [comment]
If this issue only reproduces occasionally then (as requested above by @krocard) please provide a bug report taken using `adb bugreport` after a reproduction (not just logcat snippets).

The example project provided over email seems to be incomplete, I'm unable to run gradle sync:
```
Build file '/usr/local/google/home/ibaker/Downloads/OfflinePlaybackSampleApp/build.gradle' line: 2

A problem occurred evaluating root project 'OfflinePlaybackSampleApp'.
> Could not get unknown property 'ANDROIDX_APPCOMPAT' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Fixing the unresolved substitutions to hard-code to 'latest' versions:
```
dependencies {
    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation "androidx.recyclerview:recyclerview:1.2.0"
    implementation "androidx.vectordrawable:vectordrawable:1.2.0"
    implementation "com.squareup.picasso:picasso:2.8"
}
```

I get a new error:
```
Build file '/usr/local/google/home/ibaker/Downloads/OfflinePlaybackSampleApp/build.gradle' line: 2

A problem occurred evaluating root project 'OfflinePlaybackSampleApp'.
> Could not find method implementation() for arguments [androidx.appcompat:appcompat:1.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Please provide a project that builds out of the box with no local changes required.

**Comment by NitinSharma639** [comment]
@icbaker Hi 

We are able to regenerate this bug. Please check I have send you the code. We are able to generate this bug on following device.

Samsung Galaxy Tab A (8.0",2019)
Model: SMT295
Android version : 10 
One UI Coreversion: 2.1


Thanks

**Comment by icbaker** [comment]
The Drive link provided over email is access restricted - please make it accessible.

**Comment by NitinSharma639** [comment]
Sent the permissions

**Comment by icbaker** [comment]
I ran the provided app and changed the speed to 2x then the resolution to '1080 X 1920'. I didn't observe the video getting stuck. This was on a Pixel 3a XL.

If this is device specific then please specify the devices you observed the problem on **and** provide bugreports taken with `adb bugreport` after reproducing the problem (preferably with an EventLogger attached and wired up with a TrackSelector: https://exoplayer.dev/debug-logging.html).

The provided project is not a **minimally** reproducible example. If this is a bug with ExoPlayer then you should be able to craft a much smaller project that reproduces the problem using only ExoPlayer libraries directly without using Brightcove. It's much more likely we'll be able to help with that because we don't know what Brightcove is doing on top of ExoPlayer.

**Comment by NitinSharma639** [comment]
Hi @icbaker  

We will provide the example and minimal code with exoplayer. We were able to reproduce this bug with explayer as well. This bug is happening on MI devices and Samsung Devices. Can you please check the use case defined on MI or Samsung devices with the app provided in the meantime. If you are able to reproduce may be you will give us some solution.


Thanks

**Comment by icbaker** [comment]
I don't currently have access to Samsung or MI devices. I can take a look at bug reports if you can provide them.

**Comment by NitinSharma639** [comment]
@icbaker 

I have sent bugreport please check.

**Comment by icbaker** [comment]
Thanks for the BR - as you say it looks like the codec can't handle the rate of data you're throwing at it.

ExoPlayer does check the frame size & rate, but we don't consider playback speed at this point (`format.frameRate` is the source material frame rate, not the rate at which it will be displayed after speed adjustment):
https://github.com/google/ExoPlayer/blob/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java#L209

It's tricky to make this respect playback speed because the speed could change after we've already selected a decoder (as is the case in your repro steps). You could do this check yourself though in response to the user requesting a speed change. Or even pre-emptively when setting up the UI, and disable the 2x button if the device doesn't support it?

You may also have some luck by configuring MediaCodec to operate in best-effort mode instead of realtime. You can do this by subclassing `MediaCodecVideoRenderer` and overriding `getMediaFormat` to call the superclass and then do:

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
  mediaFormat.setInteger(MediaFormat.KEY_PRIORITY, 1);
}
```

You'll then need to plumb in your custom renderer by passing in a custom `RenderersFactory` when building your `SimpleExoPlayer`.

**Comment by NitinSharma639** [comment]
Hi @icbaker 

Can you please provide us some sample code or some codelab or any kind of example so we can integrate it in production environment.

Thanks

**Comment by icbaker** [comment]
There's an example of providing a custom `RenderersFactory` here: https://exoplayer.dev/shrinking.html#specify-which-renderers-your-app-needs

**Comment by NitinSharma639** [comment]
Hello @icbaker 

Can we resolve this issue using com.google.android.exoplayer2.ui.PlayerView in our app.

Thanks
