### ISSUE TITLE
Optimising audio latency for Head-Tracked video App

### ISSUE THREAD

**Issue by Segotia-Dev** [google/ExoPlayer#8665]
Hello Exoplayers!

I am writing a video App that applies audio effect that changes in real time with the viewers head movements.   I have a sensor attached to the viewer's headphone generating data and I have subclassed the AudioProcessor class to create a "MyAudioProcessor" class and I add that to the audio processing chain (alongside the SonicProcessor) class.

The Exoplayer architecture makes all of the above simple enough to do, but the audio latency is HUGE.  That is to say: the time it takes for head movements (Sensor data) to be "heard" in the processed audio output is in the order of multiple hundreds of milliseconds, which is unusable.

So the question is multi-part:
1.  I believe that audio is ultimately pushed to the hardware (and pulled through the audio processing chain) using Android's AudioTrack API.  Is there an easy fix by way of configuring this AudioTrack-based component to eliminate or reduce its contribution to the overall audio latency?
2.  Are there other components to the audio path that I can remove and/or optimise to eliminate or reduce overall audio latency?  (I guess I could remove eg the SonicProcessor but I doubt that it's going to reduce overall latency much)
3. If I wanted to redo the audio engine and replace it with say Oboe or Superpowered, where should I start to look?

Thanks!
Team Segotia

**Comment by krocard** [comment]
Unfortunately ExoPlayer is not optimized for low latency audio. Depending on your latency targets and algorithm constraints, different solutions can be used.

## 1 Remove audioTrack buffer latency impact by applying the effect after it
If your custom effect can be expressed using [Android audio effect framework](https://developer.android.com/reference/android/media/audiofx/AudioEffect), either because it is simple such as an equalizer or a dynamic range compressor, or it can be expressed using the much more advanced [dynamic processor](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing), then this will reduce the latency significantly (~40 to 20 ms) as the effect is applied after the audio track buffer.

If latency is still too high, try applying solution 2's `AudioTrack.PERFORMANCE_MODE_LOW_LATENCY` to force a low latency output. No need to change the buffer size.

## 2 Minimize audioTrack buffer
If your custom effect cannot use the audio effect framework, and thus needs to be implemented in your app, the audioTrack latency must be minimized. If your audio latency requirement is not too low (~60 to 40ms) then this might be possible.

For API >= 26,
https://github.com/google/ExoPlayer/blob/4364b9150f236813a2070fc79d3bcb76e11969ac/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L2023-L2030
needs to be changed to add `setPerformanceMode(AudioTrack.PERFORMANCE_MODE_LOW_LATENCY)`.

Additionally reduce the buffer size passed to `setBufferSize` to the value returned by `AudioTrack.getMinBufferSize`.
Unfortunately, there is no easy way to customize the DefaultAudioTrack, so you will have to copy the class to customize it.

Note though that ExoPlayer is not tuned for such low AudioTrack buffers. It may thus underrun.

## Do not use AudioTrack
Finally, if you want to achieve the lowest latency, I would recommend Oboe. It was written and is maintained by our Android audio latency expert and allows reaching the lowest latency available on Android. It is perfect if you are targeting (~20ms to 5ms) latency.

Unfortunately ExoPlayer has no Oboe support, so you will need either
 - not to use ExoPlayer
 - customize ExoPlayer to support Oboe. This is probably quite complex.
 - use ExoPlayer only for decoding, store the sample in a queue and play in a separate thread with oboe.

## Conclusion
Without knowing more about your use case (where does the audio come from, does it too has low latency requirement, does the video needs to be sync with the audio, what type of processing is your app applying...), it is hard for me to recommend a solution.

## Note
The latency numbers mentioned are estimates only, some, usually low end, devices have very high latency due to audio stack tuning by the OEM and nothing the app can do can lower that latency.

**Comment by Segotia-Dev** [comment]
Thank you for this prompt and really useful answer.  

**The use case**
It's pretty much your standard User using Exoplayer to watch video content using a headset, with our external head-tracker IMU/sensor attached to the headset.  When she turns her head we capture that IMU data and use it to modify parameters of our DSP process.

**Problem Statement**
When the User turns her head, she will indeed hear the desired effect, but it's multiple 100s of milliseconds after the head turn action.  So there's an unworkable latency between us receiving and applying the IMU data to modify our DSP processing.

**Further Comments from Us on your Questions/Comments**
*  _Where does the audio come from?_  We'd like Exoplayer to do all the good stuff including audio decoding etc.  So the audio comes from the video content, via Exoplayer decoding, audio processing chain and routing to HAL/HW
* _Does the video needs to be in sync with the Audio?_  Yes definitely, in the same way as you'd expect the audio to be in sync with the video in "normal" playback.  So the audio needs to be in sync with the video, including our DSP processing using the Exoplayer audio processor chain.
* Latency Requirement:  we'd like to achieve a maximum latency from "head turn" -> heard DSP effect of say 60ms (so we're hopeful after reading your first (excellent) response to our issue
* DSP processing:  Our DSP is a sort of "complex downmixer" or "virtualiser":  it takes audio (Mono, Stereo, 5.1 or 7.1, decoded by Exoplayer) and processes it to produce a 2-channel (headphone) output.  The latency of our DSP = the audio processing blocksize, which we typically like to set to 128, or 256 frames.  But we can do larger block sizes no problem, given that the latency of the DSP process is a small contributor to the overall latency problem we're hearing.

I hope this helps.  We really appreciate the speed and exactness of your response and look forward very much to your further comments and guidance.

Thanks!
Team Segotia

**Comment by krocard** [comment]
Thanks for your answer. Given your requirements, I would recommend trying solution 2 first.
I think you should try to copy DefaultAudioSink, make the modification suggested and inject the customized class by subclassing `DefaultRenderersFactory` to override `buildAudioSink`.
If this hack validates that the latency is good enough and no underrun is observed, we can discuss about adding a new `performanceMode` to `DefaultAudioSink` or allowing subclassing it to customize it's audioTrack configuration.

**Comment by krocard** [comment]
After making the suggested changes, if the latency is still too high, please take a bug report during playback. Make sure that playback continues until the bug report is fully generated (a few minutes).
I'll take a look at the audio track configuration in audioflinger.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by krocard** [comment]
> Latency Requirement: we'd like to achieve a maximum latency from "head turn" -> heard DSP effect of say 60ms (so we're hopeful after reading your first (excellent) response to our issue

I would like to highlight that you external head-tracker IMU/sensor and it's communication channel (BLE?) also have a latency that might need to be reduced to reach that target.

**Comment by Segotia-Dev** [comment]
Thanks again Kevin for your thorough treatment of this issue.  We understand that the Head-tracker & BLE components themselves also contribute to the overall head-turn->DSP->heard-in-headphone latency.  We have been advised that this latency is in the order of single-digit ms.
We will follow your suggestions carefully and let you know how that pans out.
Thanks

**Comment by krocard** [comment]
> We will follow your suggestions carefully and let you know how that pans out.

Thanks, I'll gladly hear about your findings.

As the question has been answered, I'll mark the issue as closed. Feel free to reopen if you need a clarification on my answers. Please open a new issue (referencing this one) if you have a related but different question/problem.
