### ISSUE TITLE
how to listen current time ?

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8680]
I was listening to the current time through the generateEventTime's fun of AnalyticsPlayerCollector (version: 2.12.0).
I updated the exoPlayer version (2.13.2) but the generateEventTime's fun of AnalyticsPlayerCollector is final and can't override that.

how to listen to the current time of the video in the new version  (2.13.2)?

**Comment by ojw28** [comment]
I don't think the way you were doing it previously was a good approach.

You can query the playback position simply by calling `Player.getCurrentPosition()`. If you want to query the playback position periodically, then you should call it periodically from your own code. You may also want to trigger an update from `Player.EventListener.onPositionDiscontinuity` (you can register a listener using `Player.addListener`), since this method is called when there's a discontinuous jump in the position.

**Comment by sajjadshahbazi** [comment]
I have many different events in different positions and need to listen to the position.

**Comment by sajjadshahbazi** [comment]
you told me AnalyticsPlayerCollector.generateEventTime is not a good approach.
do calling Player.getCurrentPosition() every 1 second  once is good approach?

Player.EventListener.onPositionDiscontinuity is called just when ExoPlayer wants to ready and or when seeking a new position.

I want to listen to the changes in position.

please guide me

**Comment by ojw28** [comment]
> do calling Player.getCurrentPosition() every 1 second once is good approach?

It really depends on what you want to do. If you want to update a UI component every second, then yes, this is a good approach. If you want to trigger actions at very specific positions in the playback, then it's not a good approach because 1 second accuracy wont be sufficient for this. In that case, you can use the approach described in [this documentation](https://exoplayer.dev/listening-to-player-events.html#firing-events-at-specified-playback-positions).

At a general level ExoPlayer provides you with the ability to query the position at an arbitrary time (`Player.getCurrentPosition`), listen for events for things like playback pausing/resuming/buffering/seeking (`EventListener` callbacks), and trigger events at arbitrary positions as documented at the link above. With these three things it should be possible to build something that's suited for whatever your exact use case is.
