### ISSUE TITLE
so weird bug(raw source error)

### ISSUE THREAD

**Issue by ckdrb7017** [google/ExoPlayer#8684]
I want to load a raw file getting uri by file name from server.
When I get the file name and raw id, it's same to hardcoded string file name.
But the filename from server is not working.
the both raw ids are same 2131689473
For example,

fun getLocalAlarmEffectUri(context: Context, fileName: String): Uri {
    val rawFileId = context.resources.getIdentifier(fileName, "raw", context.packageName)
    showLog("rawFileId : ${rawFileId}")
    return RawResourceDataSource.buildRawResourceUri(rawFileId)
}

val localFileUrl = getLocalAlarmEffectUri(context, url)
val localFileUrl2 = getLocalAlarmEffectUri(context, "speech_start")

The localFileUrl is not working, But the localFileUrl2 is working. 
When I use the localFileUrl, I got this error But localFileUrl2 is working well.

E/ExoPlayerImplInternal: Source error.
    d.b.a.b.z0.a0: None of the available extractors (e, g, j, e, j, f, g0, c, d, z, b, b, h) could read the stream.
        at d.b.a.b.z0.r$b.b(:1067)
        at d.b.a.b.z0.r$a.h(:951)
        at d.b.a.b.d1.y$d.run(:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by tonihei** [comment]
> `val localFileUrl = getLocalAlarmEffectUri(context, url)`
> `val localFileUrl2 = getLocalAlarmEffectUri(context, "speech_start")`
>
> The localFileUrl is not working, But the localFileUrl2 is working.
> When I use the localFileUrl, I got this error But localFileUrl2 is working well.

What's the value of `url` you pass to the first method? It would also be helpful if you could describe other properties of your setup, for example: what are the names and ids of the available resources? 

The error stack trace indicates that ExoPlayer is trying to read a file that is either not a media file or has an unsupported format.

**Comment by ckdrb7017** [comment]
the value of the url is "speech_start", same value but different result. there is no mistake I checked several times.

**Comment by tonihei** [comment]
It's very unlikely that it is exactly the same value and still having a different effect. There is some auto-resolution of resource ids going on when building the code, so I assume it's something related to that. It might also be related to Proguard/R8 removing your resource if it thinks it 's not needed. So please make to test in debug mode without code shrinkage. 

If the issue is indeed more about Android resource resolution, then it's probably best to ask on StackOverflow or similar sites. If you think it's related to ExoPlayer's `RawResouceDataSource`, please provide reproduction steps for the problem we can follow as well (or a small example project showing the problem).

**Comment by ckdrb7017** [comment]
Thanks for your help. The cause was Proguard/R8. I'll be careful for asking issue.
