### ISSUE TITLE
Question about seamless audio playback within Merging & Clipping MediaSource

### ISSUE THREAD

**Issue by ChenGuanshu** [google/ExoPlayer#8688]
Hi,
My use case is to playback a few video segments with extra audio source (mp3 probably). Currently I am using the MediaSource like Concatenating(Merge(video1, audio(0,1)), Merge(video2, audio(1,2)), ...) or Merge(Concatenating(video1, video2, ...), Concatenating(audio(0,1), audio(1,2))). Both work but just with some audio glitch during segment transition.

I check some similar question like https://github.com/google/ExoPlayer/issues/6103 and https://github.com/google/ExoPlayer/issues/2347. I understand the recommended solution is to clip the audio with the end of an audio sample. Combing my exploration, I am asking which of the following approach is the most correct direction to dig in.

1. Option 1: an utility function to find out the clipping position. This approach will probably limit our flexibility on clipping in any  position. Each audio format needs to be handled individually.
2. Option 2: a customized MergingMediaSource allow merge sources with different period number. By looking into the MediaPeriod transition in ExoPlayerImplInternal, I feel like this not gonna work. But it seems to be the most correct direction because it's simple for media construction.
3. Option 3: a customized ConcatenatingMediaSource return 1 period to allow merged. Just a thought, no clear idea.
4. Option 4: a shared MediaSource embedded into ClippingMediaSource to avoid unnecessary seek initialization. Each ClippingMediaSource setup separately with a extractor, If I can use a shared extractor, I can probably skip the seek operation when the next segment starts.
5. Option 5: 2 player instances, one for audio, one for video. But it's hard to do the AV sync and manage async operations

I personally wanna dig in option 2 and would like to hear you experts' thought. 
Any feedback or idea are appreciated! Thank you!

**Comment by tonihei** [comment]
Thanks for providing all the options already - very well thought through!

> with extra audio source (mp3 probably)

Using mp3 might be an issue in itself for this use case, because the clipping relies on accurate timestamps (in particular if we want to merge it back together). Unfortunately, mp3 isn't well suited for accurate seeking or clipping, so you would be better off using a container format that has exact sample index data like MP4. See https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files. I have the feeling, this might be the reason for the glitch you are hearing.

> I understand the recommended solution is to clip the audio with the end of an audio sample.

The most important aspect is more that video streams are clipped at exactly a keyframe position. If you know the keyframe positions of the video track you can set the `enableInitialDiscontinuity` flag of `ClippingMediaSource` to `false` to ensure the transition becomes seamless. But the flag needs to stay `true` (and the transition non-seamless) if the video clip doesn't start with a keyframe. It sounds as if this may not be relevant to you as you are only clipping audio? Still good if you know the exact sample timestamp for clipping to ensure everything is as smooth as possible, but playback still gets smooth transitions even if you don't know the exact timestamps because the discontinuity flag is disabled by default for audio-only. This works because all audio samples are "keyframes".

> Option 1: an utility function to find out the clipping position. This approach will probably limit our flexibility on clipping in any position. Each audio format needs to be handled individually.

That shouldn't be needed as pointed out above. 

 > Option 2: a customized MergingMediaSource allow merge sources with different period number. By looking into the MediaPeriod transition in ExoPlayerImplInternal, I feel like this not gonna work. But it seems to be the most correct direction because it's simple for media construction.

That doesn't work unfortunately because each `MediaSource` needs to publish the media model as a single `Timeline` with a fixed number of `Periods` and `Windows`. So it's unclear how this would work for sources with different number of periods. The only way this could work is to publish a `Timeline `with one `Window` and one `Period` that combines everything together. I think this is your Option 3.

> Option 3: a customized ConcatenatingMediaSource return 1 period to allow merged. Just a thought, no clear idea.

This should be theoretically possible, but is very advanced and complicated. It also requires to have the exact same format for each individual source file so that the player doesn't need to reconfigure its codecs. The implementation roughly needs to do the following:
 - When the player requests a `MediaPeriod` for this one `Timeline.Period`, create a special wrapper `MediaPeriod`.
 - This wrapper `MediaPeriod` can create the underlying actual `MediaPeriods` of the different source files.
 - The wrapping `MediaPeriod` also needs to provide a single `SampleStream` that concatenates all the samples from the individual `SampleStreams` of the underlying `MediaPeriods`.

Related: There is also #4868 that tracks adding a version of `ConcatenatingMediaSource` that combines everything to one `Window` (but still multiple `Periods`).

> Option 4: a shared MediaSource embedded into ClippingMediaSource to avoid unnecessary seek initialization. Each ClippingMediaSource setup separately with a extractor, If I can use a shared extractor, I can probably skip the seek operation when the next segment starts.

Hard to say if that works or not! We already share `Extractors` for other cases, for example extracting TS streams from consecutive HLS segments. But I'm not sure how well this pattern integrates into `ClippingMediaSoure` (or a similar class).

> Option 5: 2 player instances, one for audio, one for video. But it's hard to do the AV sync and manage async operations

This isn't too hard actually (compared to the other proposals above). You can force the video player to use the position of the audio player as its clock:
 - The audio player has the primary clock.
 - The video player needs a `Renderer` that implements MediaClock. You could override a `NoSampleRenderer` for example to create one, or possibly also subclass `MediaCodecVideoRenderer` and implement the interface.
 - From `getPositionUs()` you need to return the media position as `audioPlayer.getCurrentPosition()`.

Hope that helps!

**Comment by ChenGuanshu** [comment]
Thanks @tonihei , your feedback is really helpful and I learn a lot from it!! 

I think we would adopt the option of 2 players instances. Before that I spent a few days in learning the Mp3Extractor/MediaSource/AudiorRenderer and try to understand the root cause of the glitch. Here's what I observed
1. The extractor can't perform accurate seek even for CBR format. For a 44.1K mp3, an audio frame counts for 1152/44100s = 26ms. but in my debugging, seeking to a position of 26*x ms doesn't results what I want.
2. When transition to a second segment, the first 1-2 frame could be dropped by the codec (without flush or reconfigure). For example If I seek to the 2.1s and the extractor outputs 2.1s, 2.2s, 2.3s to the codec, I only see the frame of 2.3s drained from the codec. This is also occurred when I was developing another feature.

I think that's why there are glitch during the segment transition. It would be great if you have any insight on this but nvm if you don't see it before. I could be wrong because the code is a little bit complicated for me to fully understand and debug.
Anyway, thanks for your thoughtful answer!

**Comment by tonihei** [comment]
> When transition to a second segment, the first 1-2 frame could be dropped by the codec (without flush or reconfigure). For example If I seek to the 2.1s and the extractor outputs 2.1s, 2.2s, 2.3s to the codec, I only see the frame of 2.3s drained from the codec. This is also occurred when I was developing another feature.

The frame drop logic can be quite complicated to follow without knowing all the details. It could be related to how seeks are handled (e.g. needing to decode from the previous keyframe), it could be related to a delay in the video renderer (e.g. if it needs to be flushed) or it could be a media issue where frame timestamps are not the ones we expect. If you have good reproduction steps with example media, we can take a look to see if everything is working as expected or whether there is something wrong.

**Comment by ChenGuanshu** [comment]
Sure thing. My reproduction is based on an old version used in our App. I will try with a latest release and see if it's still an issue. Will let you know when I get a free cycle for this. Thank you!
