### ISSUE TITLE
Exoplayer playback failed issue 

### ISSUE THREAD

**Issue by Saravana-Gunaseelan** [google/ExoPlayer#8690]
Our testers found a video file that was getting stuck when seeking to a particular position in the video.

I tested it against the demo application recommended in the template (  http://exoplayer.dev/demo-application.html).
I modified the `media.exolist.json` to just my test file

```
[
  {
    "name": "Test",
    "samples": [
      {
        "name": "Test media",
        "uri": "file:///storage/emulated/0/Download/01_2x2.mp4"
      }
    ]
  }
]
```

The issue occurs when seeking to 0:30 in the video. Seeking anywhere else works correctly. The issue was also **not** reproducible in exoplayer-2.11.x. The media used can be found here:

https://drive.google.com/file/d/1sbirYDNNcn6bpCGhSLCCvxmyUHt_K0DO/view?usp=sharing

I have attached a video where I was able to reproduce the bug:

https://user-images.githubusercontent.com/53452295/110393781-c2ce0800-8030-11eb-8f6f-620db9ee4566.mp4

Error log from my demo app:

```
2021-03-08 17:12:28.395 15042-15177/com.leia.stereodemo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1015)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
```

- ExoPlayer version number - 2.12.x, 2.13.x, Lastest code in branch release-v2
- Android version - 11
- Android device - Pixel 4 XL

**Comment by tonihei** [comment]
Could you also provide the video causing the problem? If you don't want to post it publicly you can also send it via email to dev.exoplayer@gmail.com with "Issue #8690" in the subject.

**Comment by Saravana-Gunaseelan** [comment]
> Could you also provide the video causing the problem? If you don't want to post it publicly you can also send it via email to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with "Issue #8690" in the subject.

I have attached the video link in the above ticket. Attaching it here too:
https://drive.google.com/file/d/1sbirYDNNcn6bpCGhSLCCvxmyUHt_K0DO/view?usp=sharing

**Comment by tonihei** [comment]
Sorry, I must have missed that!

**Comment by tonihei** [comment]
I think this may be working as intended. Your file only has 4 keyframes at samples 0, 250, 500 and 750, which are about 130MB of data apart from each other. So if you seek to just before a keyframe the player needs to load data from the previous keyframe and eventually reaches its default memory limit of 131 MB without having enough media available for playback yet. This is what the exception is detecting. In 2.11. we forced loading more data in such case without any upper limit, that's why you can't reproduce in 2.11.

To solve this, you should ideally create the file with more keyframes if it has such a high bitrate, or increase the allowed memory limit in `DefaultLoadControl.Builder.setTargetBufferBytes`.

**Comment by Saravana-Gunaseelan** [comment]
Makes sense. Thanks for the explanation @tonihei !
