### ISSUE TITLE
The call to defaultAudioLink.flush causes OutOfMemory

### ISSUE THREAD

**Issue by huozhezhazha** [google/ExoPlayer#8728]
If we release more than one ExoPlayer, it will cause the DefaultAudioLink.flush () to be called and create many threads, sometimes causing OutOfMemory，Can you use a thread pool instead?

**The source code is as follows**

      new Thread("ExoPlayer:AudioTrackReleaseThread") {
        @Override
        public void run() {
          try {
            toRelease.flush();
            toRelease.release();
          } finally {
            releasingConditionVariable.open();
          }
        }
      }.start();
    }

**An error is as follows**

java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Try again
java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:893)
at com.google.android.exoplayer2.audio.DefaultAudioSink.flush(DefaultAudioSink.java:1004)
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:714)
at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1142)
at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by AquilesCanta** [comment]
@andrewlewis, I was about to send a CL to allow the user inject an Executor to which the release task is passed (and the default implementation just creates a new thread), but perhaps I'm missing something obvious here (like a better solution).

**Comment by andrewlewis** [comment]
@huozhezhazha How many players are being released at the same time when you see this error? Is the device already in a low memory situation? It would be useful if you could give details about how to reproduce the error. I wonder if there's a way you can reuse players to avoid the condition that triggers this error arising in the first place.

> @andrewlewis, I was about to send a CL to allow the user inject an Executor to which the release task is passed (and the default implementation just creates a new thread), but perhaps I'm missing something obvious here (like a better solution).

Is the idea that the app would inject a single-threaded executor so that only one thread is used to release all the audio tracks across all the players? I'd be concerned that the main thread might be blocked for too long if doing that (the last player will wait until all the other `AudioTrack.release` calls have returned before it can do its call).

I can't think of something better but it would be nice to understand what's happening in more detail. The code has been like this for a long time and I think this issue was only raised once before. Tangentially, that was in the context of seeking frequently, and @Samrobbo added [`experimentalSetEnableKeepAudioTrackOnSeek`](https://github.com/google/ExoPlayer/blob/a95b2eb/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L251) so we could experiment with not creating a thread for every seek operation (probably won't help here because the audio track still has to be released when the audio sink gets released).

**Comment by huozhezhazha** [comment]
@andrewlewis 
- The user opens multiple video pages, takes a shortcut back to the home page, these pages are destroyed in a short time and release() is called 
- Exceeding the maximum limit on the number of threads resulting in OOM

**Comment by andrewlewis** [comment]
@huozhezhazha It's unclear how many players are active concurrently in this situation, but it does sound quite inefficient to create many players at the same time like that. Can you have a smaller pool of players and reuse them in your UI when switching between video pages? I'd say in general it's not good to use so much memory that the device is close to OOM'ing, as it will cause background apps to be killed making the device less responsive.
