### ISSUE TITLE
Seeking problem in AES encrypted HLS video.

### ISSUE THREAD

**Issue by GyanendroKh** [google/ExoPlayer#8737]
m3u8 file: [https://files-eu-d3.nextstream.org/stream/0001/1e884422fe4ee523f3f83d559d6a85ca4d4d1282376386c2470d6840c7e26352/uwu.m3u8](https://files-eu-d3.nextstream.org/stream/0001/1e884422fe4ee523f3f83d559d6a85ca4d4d1282376386c2470d6840c7e26352/uwu.m3u8)

The file should be requested with `Referer: https://kwik.cx/` header.

I can play the video with no problem at all. But when seeking to a location (which is not yet buffered), the video freezes. The controls does not work at all. The only way it will play again is when I seek to the start (position 0).

Exo's `PlayerView` shows in the timeline, the pre buffered part and when I seek to part of the video which is already buffered, it works. not on unbuffered.

https://user-images.githubusercontent.com/16163526/111759209-5fab6380-88c3-11eb-89cd-f44283a991c0.mp4

**Comment by AquilesCanta** [comment]
@christosts, mind taking a look?

**Comment by christosts** [comment]
I tested the content with the dev-v2 branch. The playlist has video and audio muxed in TS containers. Whenever there is a seek, the following happens:

- the player loads a segment around the seek point which adds no sample to the sample queue
- the player tries to load the next segment, but because the previous segment did not add any samples to the queue, the loader is blocked waiting the TimeStampAdjuster to be initialised [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/common/src/main/java/com/google/android/exoplayer2/util/TimestampAdjuster.java#L96) (note, this link is pointing to the dev-v2 branch) (the TimeStampAdjuster should have been adjusted by the previous load)

This happens on every seek regardless of where the seek point is. I haven't figured out yet why this happens. 

One possibility is that the content is not packaged correctly. Inspecting the sample timestamps, I can see that for some segments the first sample is 1ms before the segment's start time based on the playlist segment durations. But I'm not sure yet this is the problem. 

@GyanendroKh Have you tried playing this content with another player?

@ojw28 any ideas why loading the first segment after a seek would not add any samples?

**Comment by GyanendroKh** [comment]
@christosts I haven't tried with other players personally. But the same file is being served in production at [animepahe.com](animepahe.com), and it works fine. They are using [https://plyr.io/](https://plyr.io/) to pay the video.

**Comment by ojw28** [comment]
The media is malformed. Specifically, only the first segment contains a PAT, where-as the [HLS specification](https://tools.ietf.org/html/rfc8216#section-3.2) requires a PAT at the start of _every_ segment:

> Transport Stream Segments MUST contain a single MPEG-2 Program; playback of Multi-Program Transport Streams is not defined. Each Transport Stream Segment MUST contain a PAT and a PMT, or have an EXT-X-MAP tag (Section 4.3.2.5) applied to it.  The first two Transport Stream packets in a Segment without an EXT-X-MAP tag SHOULD be a PAT and a PMT.

When starting playback from a segment other than the first one (e.g., after a seek), the pack of a PAT means that the extractor cannot successfully output any samples, and so playback never restarts.
