### ISSUE TITLE
Custom UI Texts/Animation Overlay on the PlayerView

### ISSUE THREAD

**Issue by saurabhchalke** [google/ExoPlayer#8742]
I have a use case wherein I am trying to overlay text/animation views based on the current timestamp of the video frame on the screen.
As per the docs, I have come across the PlayerControlView, I wanted to know if I can include my custom UI views in there?
Also, is this the most efficient way to accomplish my use case (as opposed to having a StackView, listening to the current timestamp and updating UI view on top of stack).

Would appreciate it if you could share any code samples for this case.

**Comment by andrewlewis** [comment]
> As per the docs, I have come across the PlayerControlView, I wanted to know if I can include my custom UI views in there?

Rather than `PlayerControlView` you probably want the containing `PlayerView`. There is an overlay frame layout provided for convenience, which you can get via `StyledPlayerView.getOverlayFrameLayout` or `PlayerView.getOverlayFrameLayout`.

> Also, is this the most efficient way to accomplish my use case (as opposed to having a StackView, listening to the current timestamp and updating UI view on top of stack).

I'm afraid I can't help regarding `StackView` -- a general-purpose question/answer site is a better place to ask about that.

In terms of how to accomplish this use case in general, there are two relevant ExoPlayer features that come to mind:
- You can get [events at specified playback positions](https://exoplayer.dev/listening-to-player-events.html#firing-events-at-specified-playback-positions). See also #4176. This won't let you do frame-accurate synchronization for the overlay though.
- If you do need frame-accurate synchronization, you can render to a `SurfaceTexture` and control frame release so you get a callback to update any overlay just before the frame is rendered. See also gldemo's [`VideoProcessingGLSurfaceView`](https://github.com/google/ExoPlayer/blob/7e6a141/demos/gl/src/main/java/com/google/android/exoplayer2/gldemo/VideoProcessingGLSurfaceView.java) and #5860. This is quite a lot of code to get right, so if you don't need perfect synchronization the other approach is better.

Or you could do your own position polling as described in #7775 (which, like the first option above, won't give you frame-accurate synchronization).
