### ISSUE TITLE
HLS Freezing When Repeating

### ISSUE THREAD

**Issue by sdoward** [google/ExoPlayer#8752]
When playing and replaying a HLS stream exoplayer is pausing for a split second when replaying the stream. 

You can find an sample project that shows the issue here https://github.com/sdoward/hls_pausing_issue

**Comment by andrewlewis** [comment]
The last video frame timestamp we see is 12.28 seconds but the HLS manifest has a duration of 13 seconds and the [media segment](https://videos.sharethemeal.org/VID_1x1_GUINEA_HM_2021_12_Sec_20210303_stream_00001.ts) seems to have a duration of ~ 16 seconds. So I think the problem is the duration and frame timestamps aren't consistent.

One thing I noticed is that if I enable repeat mode and play the media segment directly (as a plain MPEG-TS file), then seek within the stream and let it play to the end, the last frame's timestamp changes depending on where I seek to. That may give a clue about what's wrong with the media but I don't know enough about the details of MPEG-TS to help further I'm afraid.

**Comment by sdoward** [comment]
@andrewlewis Thanks for that. It gives me a lead. Much appreciated!
