### ISSUE TITLE
 Stopping video stream on changed PCR

### ISSUE THREAD

**Issue by Pavel-Polyakov** [google/ExoPlayer#8762]
Hi!

Context:
- I use [astra](https://cesbo.com/en)  software for organize streaming

Problem looks like that:
- on astra I see error like `Mar 24 15:04:22[NTV mp3 265 (10s) i/1] mpegts/sync. pcr out of range. -8880ms`
- at the same time exoplayer stops the video. but audio continues playing.
- in log I see messages just about changed timestamp
```
03-24 15:05:14.581  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709391,bufferHdr.nTimeStamp=-240
03-24 15:05:14.581  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709311,bufferHdr.nTimeStamp=-280
03-24 15:05:14.581  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709271,bufferHdr.nTimeStamp=-200
03-24 15:05:14.590  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709351,bufferHdr.nTimeStamp=0
03-24 15:05:14.592  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709471,bufferHdr.nTimeStamp=-120
03-24 15:05:14.592  3168  7280 D AmlogicVideoDecoderAwesome: mInputTimeStampChanged = true,mLastInputTimeStamp=18446744073709431,bufferHdr.nTimeStamp=-40
```
- and video never goes on

I’ve tried on demo application of exoplayer on two devices: with amlogic and nvidia tegra, and the problem is reproducing on both. But other player (VLC) correctly handle this case — it freezes for some time and then continue the playback.

For reproduce I've up the demo stream which looped for 10 seconds. Video freezes on each iteration
url: http://178.154.192.240:50384/ntv_265_mp3_10s

**Comment by kim-vde** [comment]
Thanks for reporting this issue.

The stream you provided doesn't play on my device for 2 reasons:
1. The presentation timestamp of the first PES packet is followed by a packet with a smaller presentation timestamp, causing the first timestamp sent to the audio decoder to be negative. More precisely, the first PES packet is an H265 packet with pts 264872. It is followed by a few H265 packets and then by the first MPEG packet, which has pts 262080. As ExoPlayer offsets all the packets so that the first packet corresponds to timestamp 0, it computes a negative timestamp for the first audio (MPEG) packet. You can avoid this by passing a dts smaller than all pts values in the first packet, or by implementing your own TimestampAdjuster that doesn't offset the timestamps. This is similar to #8220.
2. The fact that the timestamps are looping produces negative timestamps in ExoPlayer. This is similar to #6983.

Both issues mentioned are already marked as enhancements, which means we are aware of them and have plans to fix them, even though it could not be in the near future because we have other priorities ATM.
