### ISSUE TITLE
Video freeze when using exo player in Tivimate on NVIDIA shield 

### ISSUE THREAD

**Issue by yangsan01** [google/ExoPlayer#8766]
Hi,
I, and many others, are experiencing video freeze when using exoplayer within Tivimate app on the NVIDIA shield.  Exo player is the built-in (default) player for the Tivimate app. The issue seems to be random. Alteast the people I communicated with cannot find a pattern.  The video freezes while the audio continues. The only work around so far is to change the channel in Tivimate and return .  This seems to be an issue with all versions of Tivimate and all models of NVIDIA shield. 

Any help would be appreciated. 
Thanks in advance.

**Comment by ojw28** [comment]
If you have an issue with a particular application, then you need to report it to the application developer.

It's impossible to say whether this is an issue with ExoPlayer or Tivimate's integration of it from the information provided. The application developer will need to figure this out, and file an issue with more concrete information if they believe a problem in ExoPlayer is the root cause.
