### ISSUE TITLE
CacheDataSource: Playing downloaded content across app launches

### ISSUE THREAD

**Issue by ALexanderLonsky** [google/ExoPlayer#8797]
Hello,
[This section](https://exoplayer.dev/downloading-media.html#playing-downloaded-content) says:

> To play downloaded content, create a CacheDataSource.Factory **_using the same Cache instance_** that was used for downloading

Does `using the same Cache instance` mean that it's not possible to play downloaded content across app launches?

Actually, I don't use any download manager, I cache data like described [here](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network).

What I see: the cache works well until I restart my app, after the first restart it creates duplicated cache for the same video file.

After the first playback and any next one in the same app instance:
```
video-cache/0/0.0.1617652975110.v3.exo
video-cache/6/0.1474158.1617652975451.v3.exo
video-cache/7/0.48.1617652975565.v3.exo

```
cacheFolder size: 1477318

If restart the app and play the same file again it adds these:
```
video-cache/0/1.48.1617653163215.v3.exo
video-cache/6/1.0.1617653162792.v3.exo
video-cache/7/1.1474158.1617653163114.v3.exo
```

and `cacheFolder` size is doubled: 2954636

**Comment by marcbaechinger** [comment]
Like you expect this should store data on the disk and then when the player wants to load the same URI again it should read from disk. This should work accross app launches.

I'm pretty sure this is working as intended as the `CacheDataSource` is around since a while. If you don't specify a custom cache key, the uri is used as the key. So in case the URI changes between these app launches that would explain why it is downloaded twice. If you have differet URIs (e.g. because it expires), you need to set a custom cache key.

Can you give us a bit more context of what you are downloading? The above mention of `the same` uri does apply for progressive media that has a single variant only and hence a single URI. If you are using adapative content, then the player may chose different variants for the next playback which means that there are mulitple/different URIs invoved and a second playback may want to cache different URIs. 

So if it's about on the fly caching with adative content this may be more advanced because you may need to restrict playback to the very same variant that you downloaded. This is a bit contrary to playing adaptive content that wants to take advantage of different qualities to provide the best user experience.

**Comment by ALexanderLonsky** [comment]
@marcbaechinger thank you for the comprehensive answer!
thanks to your clarification I've realized that our URI indeed has one param that may be changed and I've caught this only by playing more around it.
