### ISSUE TITLE
ERROR: java.lang.IllegalStateException: Unexpected runtime error

### ISSUE THREAD

**Issue by kaweesi** [google/ExoPlayer#8798]
I am using exoplayer for switching between multiple streams, i seem to be experiencing some unclear issue on every switch: ERROR: java.lang.IllegalStateException: Unexpected runtime error

I normally reinitiate the player but this in the long run causes some audio delay and the video goes ahead audio in the same stream.

Has anyone encountered this before?

**Comment by ojw28** [comment]
There's nothing we can really help with here, given so little information. If you wish to file a bug about this, please fill out the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) completely in order to provide the information that's necessary for us to help.
