### ISSUE TITLE
Leaking memory through ashmem gralloc-buffers under android emulator

### ISSUE THREAD

**Issue by zevv** [google/ExoPlayer#8801]
When repeatedly starting and stopping video assets in the Exoplayer demo, the com.google.android.exoplayer2.demo process seems to leak memory and ashmem file descriptors. The issue can best be reproduced like this:

- Start exoplayer
- Start a video
- grep gralloc /proc/<pid>/maps
- Back to menu, start another video
- grep gralloc /proc/<pid>/maps

After each video, three additional fd's will have laked:

```
94b33000-94b56000 rw-s 00000000 00:04 18479      /dev/ashmem/gralloc-buffer (deleted)
94e14000-94e37000 rw-s 00000000 00:04 17634      /dev/ashmem/gralloc-buffer (deleted)
9504f000-95072000 rw-s 00000000 00:04 16768      /dev/ashmem/gralloc-buffer (deleted)
```

The size of these maps adds up to the process' PSS memory, so after a while the OOM killer will come by and choose the exoplayer process as a victim, `dumpsys meminfo | grep exoplayer` will show the growing memory size after each video.

**Comment by ojw28** [comment]
This sounds like an emulator issue, rather than an issue with ExoPlayer. It may well have the same root cause as [this issue](https://issuetracker.google.com/142528714), which is an emulator memory leak that we've already reported. As per that issue, it may be fixed for API level 29+.

I'd suggest following that issue. If you believe it to be a different issue, then you should file it [here](https://b.corp.google.com/issues/new?component=192727&template=843117)
