### ISSUE TITLE
Movie black bars are gray on Sony bravia in hdr mode

### ISSUE THREAD

**Issue by vrayv** [google/ExoPlayer#8803]
On sony bravia android TV's the movie top and bottom black bars are gray when tv is switched to hdr mode.

Interesting fact is that black pixels are correctly displayed on the movie itself.

It seems the proposed solutions for many other players is to create transparent background on the black bar layer. 

For example here:
https://github.com/xbmc/xbmc/issues/14865

Problem with exoplayer is that black bars are displayed on the surface view and black color is assigned internally.

Can you provide some instructions how to handle this problem?

**Comment by ojw28** [comment]
> Problem with exoplayer is that black bars are displayed on the surface view and black color is assigned internally.

I'm not sure this is correct. The `SurfaceView` will always be completely filled with the movie content. The movie may have black bars "burnt in" to the video stream itself, but in that case I'd expect them to be rendered properly based on:

> Interesting fact is that black pixels are correctly displayed on the movie itself.

ExoPlayer's UI components size the `SurfaceView` to be the correct aspect ratio (i.e., it does not occupy the full `StyledPlayerView`/`PlayerView`, unless the aspect ratio of the movie is the same as the aspect ratio of the view). You can see this using Android's layout inspector:

![Screenshot 2021-04-09 at 21 44 15](https://user-images.githubusercontent.com/7881572/114238738-080d8e80-997d-11eb-953a-9178a0b77ac6.png)

It's therefore unclear what you're referring to. Could you point to where in code you think we're setting a black background color internally, since I couldn't find any code or layout XML that does this.

**Comment by vrayv** [comment]
I investigated further following your advice and realized that black bars are android main window background (exoplayer does not draw the bars).

By changing the color of the window background the bars colors are changed. Problem is that both color black or color transparent on the background window does not solve this issue.

This seems as android implementation issue on sony bravia tv's where android ui colors are not properly rendered in hdr mode.

Only fix I could think of at exoplayer level is maybe a switch that will force exoplayer to draw the bars in the same mechanic it draws the video?

**Comment by vrayv** [comment]
Ok, it seems I managed to resolve the issue.

Its important to make main layout transparent and force android:windowBackground on the theme transparent.

Something like:



```
 <style name="CustomTheme" parent="android:Theme.DeviceDefault.NoActionBar">
 <item name="android:windowBackground">@color/custom_window_background</item>
 </style>
 
 <color name="custom_window_background">#00000000</color>

```

Assign the theme properly in the AndroidManifest.XML.

On the creation of the main window:

dialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));

This makes all background transparent and give no chance to sony android to render wrong black color in hdr mode.

**Comment by heyangJob** [comment]
> On sony bravia android TV's the movie top and bottom black bars are gray when tv is switched to hdr mode.
> 
> Interesting fact is that black pixels are correctly displayed on the movie itself.
> 
> It seems the proposed solutions for many other players is to create transparent background on the black bar layer.
> 
> For example here:
> [xbmc/xbmc#14865](https://github.com/xbmc/xbmc/issues/14865)
> 
> Problem with exoplayer is that black bars are displayed on the surface view and black color is assigned internally.
> 
> Can you provide some instructions how to handle this problem?

hello, We also use the same equipment as yours to play 4K video card. Do you have such imagination? Which version of ExoPlayer is used..Thank you!
