### ISSUE TITLE
updating guava

### ISSUE THREAD

**Issue by umerov1999** [google/ExoPlayer#8821]
Can i update guava from 27.1-android to 30.1.1-android? Does Exoplayer work correctly, if i update guava?

**Comment by icbaker** [comment]
ExoPlayer doesn't use any Guava APIs marked `@Beta`. Guava's commitment to binary compatibility from 21.0 onwards means that ExoPlayer should run fine against our current declared dependency (27.1-android) and any future versions: https://github.com/google/guava/wiki/PhilosophyExplained#non-beta-apis

However we deploy this library into a context where 27.1 is the newest version available - so for now we're not going to change the version we compile against (in order to prevent accidentally depending on any APIs added after 27.1):
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/constants.gradle#L24

Hopefully that answers your question - let me know if not.
