### ISSUE TITLE
Play TV archive 

### ISSUE THREAD

**Issue by davydovvladimir** [google/ExoPlayer#8827]
Hello dear developers!

I need to implement the ability to play TV archive in HLS format.
The time window for playback is set in a HTTP GET request to the server using the start_time / end_time as request parameters:
http://some_server/TV_CHANNEL/variant.m3u8?start_time=A&end_time=B
The server returns closed or non-closed (if end_time is in the future) playlist.
Seamless switching from one time window to the next is one of requirements.

How is this usually done with ExoPlayer?

There is an idea to use playlists https://exoplayer.dev/playlists.html to seamlessly switch from one window to another:
```
MediaItem firstItem = MediaItem.fromUri ("server_url?start_time=A&end_time=B");
MediaItem secondItem = MediaItem.fromUri ("server_url?start_time=B&end_time=C");
player.addMediaItem(firstItem);
player.addMediaItem(secondItem);
```
But here the question arises, how to handle the case when two time windows overlaps? I mean a situation where one HLS playlist contains segments from another.
How can I avoid replaying segments after switching to a new playlist?

Thanks!

**Comment by icbaker** [comment]
> But here the question arises, how to handle the case when two time windows overlaps? I mean a situation where one HLS playlist contains segments from another.
> How can I avoid replaying segments after switching to a new playlist?

This sounds like something that should be solved on the serving side - if you're trying to play seamlessly from time A to time C, and you request A -> B and B -> C as in your example, isn't it up to the server to ensure it doesn't serve you the same segments in both HLS playlists?

More generally - wouldn't it make more sense to just request A -> C directly from the server and just get a single HLS playlist?

**Comment by davydovvladimir** [comment]
Thank you for the quick response!

> isn't it up to the server to ensure it doesn't serve you the same segments in both HLS playlists?

The server doesn't know anything about previous client request (A->B), so it can't guarantee there is no overlap.
Maybe I can somehow align the time B to the segment boundary. I will perform some experiments and ask to the server's support team.

> More generally - wouldn't it make more sense to just request A -> C directly from the server and just get a single HLS playlist?

The server has an archive for 3 days. If I request a playlist from "3 days ago" to "live" it will has very big size  and will not be closed. The player will refresh it and create a heavy load on the server. So, using of closed playlist for small window (1h for example) is more preferable.

**Comment by tonihei** [comment]
Have you considered using [HLS delta updates](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#section-6.3.7) to avoid large playlist updates? This would allow you to keep a single playlist and the player automatically only requests the latest playlist delta (after an initial full request).

**Comment by icbaker** [comment]
Toni's suggestions sounds sensible - if you can avoid trying to use ExoPlayer playlists for this I think your life will be easier.

Regarding the original question about seamless transitions though, in case it's useful:

The transition between two items in a playlist will be seamless if they both use the same codec and the second item starts at a keyframe.

You can use the `MediaItem.clippingProperties` to remove content from the beginning and end of an item. Clipping content from the beginning introduces the risk of not starting at a key frame. 

So if you know that item A -> B includes content from t=A-5 to t=B+4, while B -> C includes content from t=B-3 to t=C+3, then you can clip the first item to end at t=B-3 (and it's assumed that the second item, unclipped, will start at a keyframe).

If this transition might happen in the middle of a scene you obviously need to be careful to be completely frame-accurate with your clipping.

This isn't really the intent of the MediaItem/Playlist API though - it's generally intended that items represent distinct pieces of media.

**Comment by davydovvladimir** [comment]
> Have you considered using [HLS delta updates](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#section-6.3.7) to avoid large playlist updates? This would allow you to keep a single playlist and the player automatically only requests the latest playlist delta (after an initial full request).

Unfortunately, it is not supported by server side.

**Comment by davydovvladimir** [comment]
> You can use the `MediaItem.clippingProperties` to remove content from the beginning and end of an item. Clipping content from the beginning introduces the risk of not starting at a key frame.

But for this we need to know the clipping parameters before the request. Is it possible to somehow intercept the beginning of the MediaItem playback when we know for sure the parameters of the overlap?

I mean the following idea. When the player receives media playlist for the window B->C, then we analyze timeline parameters of this playlist and set correct starting time for playback.

**Comment by icbaker** [comment]
Clipping the end of the currently playing item is not possible, it's tracked by https://github.com/google/ExoPlayer/issues/3163.

**Comment by davydovvladimir** [comment]
> Clipping the end of the currently playing item is not possible, it's tracked by #3163.

I think it is not required. I meant changing of start playback position of media item responsible for the window B->C.
Can we change it immediately after receiving playlist from the server?

**Comment by icbaker** [comment]
You can change a future `MediaItem` by replacing it in the playlist, something like:

```java
player.addMediaItem(
    nextIndex,
    player.getMediaItemAt(nextIndex)
        .buildUpon()
        .setClipStartPositionMs(XXX)
        .build());
player.removeMediaItem(nextIndex + 1);
```

But note that if you don't clip to a keyframe then the transition between the items won't be seamless (because the decoder needs to start from a keyframe, so it will need to decode (and then not show) some frames before it reaches the first frame you've asked it to show, which takes time). This is why I recommended clipping the end of the item, rather than the beginning, as that's not sensitive to key frames.

It may also be possible to customise the ExoPlayer HLS components to achieve what you want - @christosts might have thoughts on that.

**Comment by christosts** [comment]
> But for this we need to know the clipping parameters before the request. Is it possible to somehow intercept the beginning of the MediaItem playback when we know for sure the parameters of the overlap?
> 
> I mean the following idea. When the player receives media playlist for the window B->C, then we analyze timeline parameters of this playlist and set correct starting time for playback.

One idea (maybe I'm repeating your idea): If you plan to request A->B and then B->C, you can tune B so that is perfectly aligns with segment boundaries. Since you can't decide that before hand, you can request A->B, figure out exactly the duration of the fetched playlist, and then request `B'`->C, where `B'` is tuned to start exactly after the last segment of the first playlist.

How to do this: The player exposes the playlist manifest through `Player.getCurrentManifest()`. When the timeline changes, you can get the manifest, cast it from `Object` to `HlsManifest`, and from there you can inspect the master and media playlists contents. From the media playlist, you can figure out the duration of the playlist and information about each segment. After you parse the fetched playlist, you can decide what `B'` should be.

Another idea (much more difficult and not tested): Theoretically, you may try injecting a custom [HlsPlaylistTracker](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistTracker.html) which will be responsible for making all the HLS playlist requests. Your custom tracker will decide  `start_time `and `end_time` based of your custom logic, and merge the fetched playlists into one big HLS playlist with no overlapping segments. The player will assume you are playing a single media item with a single window which will change every time a new playlist is fetched (not sure how the UI will work there). In addition, newly fetched playlists will be merged with the previous playlist, therefore the app will have an incrementally growing java object that represents the playlist since the playback started. The HlsPlaylistTracker is quite a complicated component, so this task is hard (apart from somewhat speculative!) and it will be hard for us to assist you in more detail.

**Comment by davydovvladimir** [comment]
> One idea (maybe I'm repeating your idea): If you plan to request A->B and then B->C, you can tune B so that is perfectly aligns with segment boundaries. Since you can't decide that before hand, you can request A->B, figure out exactly the duration of the fetched playlist, and then request B'->C, where B' is tuned to start exactly after the last segment of the first playlist.

> How to do this: The player exposes the playlist manifest through Player.getCurrentManifest(). When the timeline changes, you can get the manifest, cast it from Object to HlsManifest, and from there you can inspect the master and media playlists contents. From the media playlist, you can figure out the duration of the playlist and information about each segment. After you parse the fetched playlist, you can decide what B' should be.

Thanks! I got it.  But, as the guys from the servers said, when I request B 'on the server, then in response with some probability I can still get a media segment from the previous range (A->B).

So, the idea with custom HlsPlaylistTracker implementation looks like more suitable, despite the complexity.

I have a lot of information now. I will try different ways.
Thanks to everyone who answered!
