### ISSUE TITLE
Migrating from ExoPlayerFactory with AudioProcessor

### ISSUE THREAD

**Issue by devingryu** [google/ExoPlayer#8841]
So, I want to process audio with AudioProcessor when playing audios with ExoPlayer2.
I found that it can be achieved by using the below code(According to [this question](https://stackoverflow.com/questions/58857797/exoplayer-custom-audioprocessor-equalizer) )

```kotlin
private fun initPlayer(context: Context): ExoPlayer {

        val audioProcessor = SonicAudioProcessor()

        val renderersFactory = object : DefaultRenderersFactory(context) {
            override fun buildAudioProcessors(): Array<AudioProcessor> {
                return arrayOf(audioProcessor)
            }
        }

        val player: SimpleExoPlayer = ExoPlayerFactory.newSimpleInstance(
            context,
            renderersFactory,
            DefaultTrackSelector(),
            DefaultLoadControl()
        )

        player.addListener(object : Player.EventListener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                callback?.onPlayStateChanged(playWhenReady)
            }
        })

        return player
    }
```

...but now ExoPlayerFactory is deprecated, and there is no buildAudioProcessors() to override in DefaultRenderersFactory now. However, I couldn't find any documentation to achieve my goal in the latest version of ExoPlayer.

Thanks in advance.

**Comment by icbaker** [comment]
The `DefaultRenderersFactory#buildAudioProcessors()` method was removed in https://github.com/google/ExoPlayer/commit/363a2a3b45488c53f12c8382d3c6a8b41ac5866f.

It was replaced with `buildAudioSink()`.

You can override that to achieve what you want by constructing a `DefaultAudioSink` in the same way that `DefaultRenderersFactory` does, but pass in a `AudioProcessorChain` containing your `AudioProcessor` instead of `new DefaultAudioProcessorChain()`.
