### ISSUE TITLE
No sound for flac file

### ISSUE THREAD

**Issue by zhhach123** [google/ExoPlayer#8867]
On devices which android version higher than 9 work fine.
But on devices which is lower than 9 there is no sound while playing flac audios.
On android 9 devices some work well but some no sound while playing flac audios.
I am using verison 2.12.0.\
Thanks.

**Comment by icbaker** [comment]
Are you using the FLAC extension or the FLAC extractor bundled in the core library? If the latter (which is the default if you haven't explicitly included the FLAC extension), then see the *** footnote here (API 27 is Android 8.1.0, i.e. just before 9):
https://exoplayer.dev/supported-formats.html#progressive-container-formats

**Comment by zhhach123** [comment]
private void createNewPlayer() {
        LogUtils.e("MusicService", "createNewPlayer");
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory();
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        RenderersFactory renderersFactory;
        DefaultDrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
        renderersFactory =
                new DefaultRenderersFactory(AppConfig.instance, 1) {
                    @Override
                    public AudioProcessor[] buildAudioProcessors() {
                        return new AudioProcessor[]{};
                    }
                };
        player = ExoPlayerFactory.newSimpleInstance(this, renderersFactory, trackSelector, drmSessionManager);
        CurrentMusicBean.getInstance().setPlayerAlive(true);
        dataSourceFactory = new DefaultDataSourceFactory(AppConfig.instance,
                Util.getUserAgent(AppConfig.instance, AppConfig.instance.getResources().getString(R.string.app_name)), defaultBandwidthMeter);
        mediaDataSourceFactory = buildDataSourceFactory(true);
        proxy = AppConfig.getProxy(AppConfig.instance);
    }

This is my method to create Exoplayer.Is there any problems on the devices which is before API 27.Am i  use the wrong renderfactory?

Thanks.

**Comment by icbaker** [comment]
It looks like you're trying to use the FLAC extension, based on this line (since `DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON = 1`):
```
renderersFactory =
            new DefaultRenderersFactory(AppConfig.instance, 1) {
```

Have you built & depended on the FLAC extension as described here?
https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac

You'll need something like `implementation project(':exoplayer-decoder-flac')` in the dependencies section of your `build.gradle` and you should see the following logcat line if it's being loaded correctly (from [here](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L517)):
```
Loaded LibflacAudioRenderer.
```

If you don't see that line then you need to look into your dependencies setup to understand why the extension isn't being loaded properly.

If you do see that line logged and you still don't hear audio then you can make sure the `LibflacAudioRenderer` is being used by attaching an [`EventLogger`](https://exoplayer.dev/debug-logging.html) initialized with a track selector, probably something like:
```java
player.addAnalyticsListener(new EventLogger((MappingTrackSelector) player.getTrackSelector()));
```

When you play the file you should see a section in the `tracks` output for `LibFlacAudioRenderer` that includes the audio track (more info on the log format: https://exoplayer.dev/debug-logging.html#media-tracks).

**Comment by zhhach123** [comment]
thanks,I have solved this problem.
