### ISSUE TITLE
How to play the second or the third mp4 of my own file?

### ISSUE THREAD

**Issue by tumnus17** [google/ExoPlayer#8871]
Hi all ,
I have a file xxx.ivf which contain 3 mp4 video and when i play the video using MediaItem.fromUri(ivfUri); it alway play the first video then the player will be idle,so how to play the second or third video.the three videos are continuous MP4 ,and the offset of their beginning and the end are known。

**Comment by tumnus17** [comment]
the  atoms are like this：
ftyp 
moov 
sidx 
sidx
moof 
mdat 
ftyp
moov 
sidx 
sidx
moof
mdat
ftyp 
moov 
sidx
sidx
moof 
mdat
（some picture）

**Comment by kim-vde** [comment]
If I understand correctly, you have a file containing concatenated MP4s. As the start and end offsets are known, you can clip the input file to play the second and third MP4. This is explained on [this page](https://exoplayer.dev/media-items.html#clipping-a-media-stream).

**Comment by kim-vde** [comment]
This seems to be a duplicate of #6720. Please tell us if your problem is different, and explain why it is different. 

You can find more information about customization in ExoPlayer [here](https://exoplayer.dev/customization.html).

**Comment by tumnus17** [comment]
Thank you for your answer. It does help，but my question is not exactly the same as  #6720，it's similar to #6723 .The xxx.ivf file starts with a custom header. By parsing this header, we can get the offset of the next few mp4s. After parsing, the first mp4 will be played, and then the user interface will have two selection buttons for the user to choose to play the second one or the third one.    The atom structure of ivf file is as follows：

csth（custom header）
ftyp（the start of first mp4）
moov
sidx
sidx   
moof
mdat （the end of first mp4）
ftyp （the start of second mp4）
moov
sidx
sidx
moof
mdat（the end of second mp4）
ftyp （the start of third mp4）
moov
sidx
sidx
moof
mdat（the end of third mp4）

So I want to know how to switch between different mp4s in a same file source.Thanks again.

**Comment by kim-vde** [comment]
ExoPlayer does not support the `csth` atom so you will need to parse it by yourself.

Once you have the start and end offsets of all the MP4s, you can create one `MediaSource` per MP4, using a different resolving data source for each. You can then pass the list of `MediaSources` to the player using `SimpleExoPlayer.setMediaSources()`, and seek to a specific media source by using `SimpleExoPlayer.seekTo()` or `SimpleExoPlayer.seekToDefaultPosition()`.

Depending on what you want exactly, you might need to have one player instance per `MediaSource`, instead of a single player containing a playlist.

**Comment by tumnus17** [comment]
Got it.Thanks for the help😁.
