### ISSUE TITLE
 Playlist with mixed framerate variants

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8872]
If a master playlist contain mixed framerate variants, i.e. 30fps and 60fps, can ExoPlayer pick by itself the one applicable for the device?

**Comment by kim-vde** [comment]
I am not sure I understand the question.

If you are asking about adaptive streaming, ExoPlayer supports DASH, HLS and SmoothStreaming and picks the suitable bitrate depending on the bandwidth, the device, etc. See our [Supported formats page](https://exoplayer.dev/supported-formats.html).

If your question is different, please clarify what you mean by "mixed framerate variants".

**Comment by ghost** [comment]
I have attached sample playlist with mix framerate for better understanding.
We want to know if exoplayer smart enough to pick the 30fps/60fps variant based on device capability.
In other word, we want to know if exoplayer capable to pick not only the right bitrate but also framerate (30fps/60fps)
[Consolidated-Sample-Playlist-20210406.zip](https://github.com/google/ExoPlayer/files/6387945/Consolidated-Sample-Playlist-20210406.zip)

**Comment by kim-vde** [comment]
The file provided is an HLS master playlist. Can you help on this @christosts ?

**Comment by christosts** [comment]
First, ExoPlayer will query the platform for support of a specific frame rate using the MediaCodecInfo.VideoCapabilities API, please see [MediaCodecInfo.VideoCapabilities.areSizeAndRateSupported](https://developer.android.com/reference/android/media/MediaCodecInfo.VideoCapabilities#areSizeAndRateSupported(int,%20int,%20double)), assuming your app is running on devices with API >= 21. All supported frame rates will be available for playback.

Second, the choice of which variant to play happens in [TrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelector.html), which by default is a [DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) instance. The  DefaultTrackSelector's parameters can be tuned to set a minimum/maximum frame rate which are useful if you know the playlist's frame rates and the frame rates supported on the device upfront. If you don't specify any filters, then all variants will be available during playback. In this case, adaptation is performed based on resolution and bitrate, therefore it is possible to switch between different frame rates. 

I guess you might want to stick to a specific frame rate, e.g. if the device supports 60fps, you might want to use only these variants and drop the 30 fps ones. If you don't have information on the playlist or device capabilities upfront, you'd need to make the decision at runtime by overriding [DefaultTrackSelector.selectVideoTrack](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html#selectVideoTrack-com.google.android.exoplayer2.source.TrackGroupArray-int:A:A-int-com.google.android.exoplayer2.trackselection.DefaultTrackSelector.Parameters-boolean-).

@tonihei is there another way to filter out specific frame rates at runtime?

**Comment by tonihei** [comment]
If I the understand the original question correctly, it's just about whether ExoPlayer checks device capabilities before selecting tracks. And the answer is: yes, unsupported tracks are not selected for playback. 

Otherwise I don't have much to add really.
 - If the device supports all variants (60fps, 30fps, 15fps) then it will select all of them for playback and adapt between them seamlessly. 
 - You can filter them out with `DefaultTrackSelector.Parameters.minVideoFrameRate/maxVideoFrameRate` in advance or by overriding `DefaultTrackSelector.selectVideoTrack` if you want to filter them out after the super method has done its work. However, looking at your playlist it doesn't seem to be a good idea to limit a 60fps device to just the 60fps variants. Because if this device is playing the stream in a slow network it would no longer be able to switch down to lower bitrates as the lower bitrates also happen to have lower framerates.

**Comment by tonihei** [comment]
Closing the issue as the question was probably answered.
