### ISSUE TITLE
noob question; how do I build demo

### ISSUE THREAD

**Issue by danmar** [google/ExoPlayer#8879]
I have tried to follow the instructions here;
https://exoplayer.dev/demo-application.html

I downloaded and installed android studio today (linux machine) so it's latest and greatest.

When I build I get this message;
```
Failed to install the following Android SDK packages as some licences have not been accepted.
   build-tools;29.0.2 Android SDK Build-Tools 29.0.2
```
I went looking in the SDKManager and I can't see any way to install "Android SDK Build-Tools 29.0.2". However I could install the "Android SDK Build-Tools 31.0.2"

I still get the same error message. Can you please advice? Can I install the 29.0.2 version somehow? Or would it be possible to change ExoPlayer project to use 31.0.2 somehow?

**Comment by fgl27** [comment]
The reason is right there "some licences have not been accepted."

Android studio issues resolution is something very easy to find as is used for so many.

Just Google the error, usually first result has the answer

https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not

**Comment by danmar** [comment]
ok thanks. I managed to get this working somehow.
