### ISSUE TITLE
to know why the below M3u8 link not play in exo player getting error playback failed (its a active Link)

### ISSUE THREAD

**Issue by Pradeesh76** [google/ExoPlayer#8884]
help to know why the below m3u8 link not working in ExoPlayer

https://acv.asianetmobiletvplus.com/webstreams/8f8e72769cb3e3a6e27c220e1e3887b8.smil/playlist.m3u8

rest all other links working fine in example provided  even in new version   r2.13.3 

any solution to play this link in Exo Player

Before filing a question:
-------------------------

- Ask general Android development questions on Stack Overflow
- Search existing issues, including issues that are closed
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website (https://exoplayer.dev/) and Javadoc
  (https://exoplayer.dev/doc/reference/)

When filing a question:
-------------------------

Describe your question in detail.

In case your question refers to a problem you are seeing in your app:

- Output of running `$ adb bugreport` in the console

In case your question is related to a piece of media:

- URI to test content
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

Don't forget to check supported formats and devices
(https://exoplayer.dev/supported-formats.html).

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

**Comment by kim-vde** [comment]
ExoPlayer doesn't play the provided stream because it gets a 403 (Forbidden) when trying to get the content of https://acv.asianetmobiletvplus.com/webstreams/8f8e72769cb3e3a6e27c220e1e3887b8.smil/playlist.m3u8. FFMPEG doesn't play it either for the same reason.

On the other hand, the file can be read from the browser or with curl.

The next step is to figure out why the server refuses to answer the request.

Edit: the server seems to refuse the request because the user agent is empty. If I hardcode it to anything in the CronetDataSource, then the content plays.
