### ISSUE TITLE
DownloadHelper: No way to pass extractor in DownloadHelper.createMediaSource, unable to play ProgressiveMedia

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#8897]
We can only process bug reports that are actionable. Unclear bug reports or
reports with insufficient information may not get attention.

Before filing a bug:
-------------------------

- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website: https://exoplayer.dev/
- Check the supported formats: https://exoplayer.dev/supported-formats.html
- Try playing problematic media in the demo app:
  http://exoplayer.dev/demo-application.html

When reporting a bug:
-------------------------

Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub. To
increase the chance of your issue getting attention, please also include:

- Clear reproduction steps including observed and expected behavior
- Output of running "adb bugreport" in the console shortly after encountering
  the issue
- URI to test content for reproduction
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

- ExoPlayer version number: r2.13.3
- Android version
- Android device

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

Whenever play the downloaded ProgressiveMedia I am getting below Error:
https://github.com/google/ExoPlayer/blob/1f17756ad2cb4f427bac57de8d0911147307cd06/library/core/src/main/java/com/google/android/exoplayer2/source/BundledExtractorsAdapter.java#L87-L93

Because DownloadHelper is always forcing the `ExtractorsFactory.EMPTY` as the ExtractorFactory which will miss the `Mp4Extractor.FACTORY` to extract the ProgressiveMedia to render.

`DownloadHelper.createMediaSource(downloadRequest, dataSourceFactory)`

https://github.com/google/ExoPlayer/blob/ec437350543fa43763b7ba74e0b43ec37a1ee224/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L890-L897

**Comment by christosts** [comment]
Would you mind trying to explain in more detail what your application is doing?

The pieces of code that you pointed are not directly related when downloading ProgressiveMedia. Specifically, `createMediaSourceInternal ` is not be called because the DownloadHelper does not need a media source to download progressive media.


https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L408-L426

Are you attempting to play content while it is being downloaded?

**Comment by drayan85** [comment]
Yes, I am trying to play the Downloaded ProgressMedia without internet connection

**Comment by christosts** [comment]
My question was if your app is trying the play the media **while** it is being downloaded, that is while there is still internet connection and the file is not downloaded completely.

**Comment by drayan85** [comment]
No, Played after successfully downloaded and close the app and open it again.

Basically, The player starts to play the Downloaded ProgressiveMedia file

PS: This issue not related to downloading. 

Unfortunately, the demo app doesn't have any progressive media sample URL. You can add any Progressive Media URL to the demo app, download the video file, and then try to play. It will throw the exception as I mentioned above

**Comment by christosts** [comment]
The demo app has several URLs pointing to content that is [progressive](https://exoplayer.dev/progressive.html) (e.g. mp4 and mkv files). Using 2.13.3, I downloaded several of them, switched off the wifi and played the content fine. 

As pointed to my comment [above](https://github.com/google/ExoPlayer/issues/8897#issuecomment-833402151), the DownloadHelper does not call `createMediaSourceInternal ` for progressive media. 

Can you please provide a link to the test content you are using so that I can reproduce the issue using the demo app? If you cannot share the link publicly, please send an email at dev.exoplayer@gmail.com with the subject "Issue #8897"

**Comment by drayan85** [comment]
Sorry for my bad miss out on the `.MP4` file in the Demo app.

In my case still, I am using `MediaSource` to prepare the player because Casting videos is not working with the selected Subtitle when I am using `MediaItem` to prepare the player to play the video.

```
DownloadRequest downloadRequest = DemoUtil.getDownloadTracker(this).getDownloadRequest(mUri);
DataSource.Factory dataSourceFactory = DemoUtil.getDataSourceFactory(this);
MediaSource mediaSource = new DefaultMediaSourceFactory(dataSourceFactory, Mp4Extractor.FACTORY).createMediaSource(downloadRequest.toMediaItem());
```

Currently, I am using `DefaultMediaSourceFactory` with the `Mp4Extractor.FACTORY` to convert the `MediaItem` to the MediaSource and manage to play the Downloaded video.

**Comment by drayan85** [comment]
https://github.com/google/ExoPlayer/blob/ec437350543fa43763b7ba74e0b43ec37a1ee224/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L890-L897

According to the DownloadHelper, it is Creating the `DefaultMediaSourceFactory` object with `ExtractorsFactory.EMPTY`.

But in the `DefaultMediaSourceFactory` constructor 2nd param description clearly saying that the Extractor for ProgressiveMedia as code snippet shows below. Still passing `ExtractorsFactory.EMPTY` from the `DownloadHelper` class is causing me the issue.

https://github.com/google/ExoPlayer/blob/c5a8154970cc950a84138e6503c6558fdb1961ef/library/core/src/main/java/com/google/android/exoplayer2/source/DefaultMediaSourceFactory.java#L147-L168

**Comment by christosts** [comment]
As I said in [my previous comment](https://github.com/google/ExoPlayer/issues/8897#issuecomment-833402151), `DownloadHelper.createMediaSourceInternal` is used by the DownloadHelper internally at the time to download media, and specifically it is not called when downloading progressive content, but only when downloading adaptive content. 

> Currently, I am using DefaultMediaSourceFactory with the Mp4Extractor.FACTORY to convert the MediaItem to the MediaSource and manage to play the Downloaded video.

On your [comment above](https://github.com/google/ExoPlayer/issues/8897#issuecomment-833551181), you provided a snippet code that works - is it possible to provide the snippet of code that fails so that we can see if/where's the bug.

Also, have you read the documentation [how to play downloaded content](https://exoplayer.dev/downloading-media.html#playing-downloaded-content), including the steps how to [configure a MediaSource](https://exoplayer.dev/downloading-media.html#mediasource-configuration) for downloaded content?

**Comment by drayan85** [comment]
> ent?

Thanks Now I understood the way need to play the downloaded media source.
