### ISSUE TITLE
Seeking to a negative value makes the ExoPlayer to pause over HLS

### ISSUE THREAD

**Issue by nandovelazquez** [google/ExoPlayer#8906]
Passing a negative value to the `player.seekTo()` function makes the ExoPlayer puts itself in a "pause" state and it never re-positions the `playhead` to 0 seconds. Still, we can see that the seek command is executed in the logcat.

To reproduce this we can use the Exo demo app. In the `PlayerActivity` set a delay of, could be 10 seconds, and then execute a `player.seetTo(-3000)`. Then the video will pause, the current position label will be at -0:00 but the Play/Pause button will stay as playing, and nothing else will happen. 
There is no error message returned/thrown by the ExoPlayer nor printed in the logcat. 

This is only with HLS videos. DASH and SmoothStreaming videos work fine.

Could you take a look, please?

**Comment by christosts** [comment]
Thanks for reporting this, I can verify it happens on r2.13.3. I'm still investigating to see exactly what's happening

**[update]**
I can see there's inconsistent  behavior, not only between different kind of sources (DASH vs HLS), but also between videos of the same kind. From the demo app, seeking to `-5000`:
- the "Clear DASH" assets can seek  but the "60fps DASH" freezes.
- From the HLS content, " the "Apple 4x3 basic stream (TS)" freezes but "Apple 16x9 basic stream (TS)" works with the negative position.

The correct fix of this would be to not allow seeking to a negative position at all and make this behavior consistent for all media types. 

For your application: please make sure you are not seeking with negative timestamps. If you are already performing this on DASH content and it works, I'd suggest you change that. Otherwise, when this fix is implemented, it might break your app.

**Comment by nandovelazquez** [comment]
That was fast!

Thank you, I'll keep this in mind. 👍

**Comment by dino-saurabh** [comment]
Hi @christosts @claincly can I take this up ?

**Comment by SaurabhOfficial** [comment]
@ojw28 what could be other possible ways to not allow negative seek position across all Media Types ?
is there a possibility that assertions might break a lot of code based on current exo-player ?

**Comment by dino-saurabh** [comment]
@ojw28 apart from assertions what could be possible ways to not allowing negative seek for various media types?

**Comment by ojw28** [comment]
This should be fixed by the commit above, which constrains the seek position after it's resolved to a period position, for which negative values really are always invalid.
