### ISSUE TITLE
exoplayer takin 4-5 seconds to buffer even on good network

### ISSUE THREAD

**Issue by vinitshahane** [google/ExoPlayer#8913]
Hi,
I am using exoplayer 2.13.3 it is always taking 4-5 seconds to buffer when loading for first time. even on good wifi network its taking same time.
is there any setting to reduce start buffer time.

**Comment by christosts** [comment]
By default, ExoPlayer will buffer [2.5 seconds](https://github.com/google/ExoPlayer/blob/r2.13.3/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L49) of content before starting playback. You may try to create you own [DefaultLoadCotrol](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html) instance that buffers less content for startup and set in on the player. But 2.5 seconds is not that much, and requiring 4-5 seconds to download 2.5 seconds may indicate that there may be other reasons of delay. Please try the above and update this ticket if it didn't work.

**Comment by vinitshahane** [comment]
I tried changing bufferForPlaybackMs to 1.5 sec but haven't observed any change. is there nay other way to change starting buffer time? adding code my code below.
```
DefaultLoadControl.Builder builder = new DefaultLoadControl.Builder();
            final int loadControlStartBufferMs = 1500;
            builder.setBufferDurationsMs(
                    DefaultLoadControl.DEFAULT_MIN_BUFFER_MS,
                    DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                    loadControlStartBufferMs,
                    DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS);
            DefaultLoadControl loadControl = builder.createDefaultLoadControl();
```

**Comment by vinitshahane** [comment]
Also tried playing my video in avplayer and webview and it is loading quickly within 1-2 sec. If you want I can send sample video as well.

**Comment by christosts** [comment]
> If you want I can send sample video as well.

Yes, please share a link to the content. If you cannot share it publicly here, please email it to dev.exoplayer@gmail.com with subject in the format "Issue #8913" and update this issue once you sent the email.

Thanks

**Comment by vinitshahane** [comment]
I researched more into this and found out the issue is with seekto(). in my app in some videos i need to start playing from some given position which is taking time to load. e.g if video length is 5min  and i want to play it directly from 2 min then its taking time other if i play it from start its not taking time. is there any option by which i can directly start video from any position without any delay?

**Comment by christosts** [comment]
There are can be a few parameters that affect this on your app, please share the content and also a snippet of code that reproduces your observation, so that we can reproduce too. For example, to see the delay with your content on the demo app, is it enough to change the demo-up and add a player.seekTo() in [PlayerActivity](https://github.com/google/ExoPlayer/blob/r2.14.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L283)?

**Comment by vinitshahane** [comment]
yes its is enough to add player.seekto(). i am adding my sample activity which is taking 2.5-3 sec to load.(here i have added sample video link which is also taking time 2-3 sec)

Note: tried my app video on ios and web its loading quickly.

`public class ExoplayerActivity extends AppCompatActivity  {

    // creating a variable for exoplayerview.
    SurfaceView exoPlayerView;
    // url of video which we are loading.
    String videoURL = "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_exoplayer);
        exoPlayerView = findViewById(R.id.idExoPlayerVIew);
        try {
            SimpleExoPlayer player = new SimpleExoPlayer.Builder(ExoplayerActivity.this).build();
           // exoPlayerView.setPlayer(player);
            player.addListener(mDefaultEventListener);
            player.setVideoSurfaceView(exoPlayerView);
            // Build the media item.
            MediaItem mediaItem = MediaItem.fromUri(videoURL);
        // Set the media item to be played.
            player.setMediaItem(mediaItem);
            player.seekTo(17000);
        // Prepare the player.
            player.prepare();
        // Start the playback.
            player.play();



        } catch (Exception e) {
            // below line is used for
            // handling our errors.
            Log.e("TAG", "Error : " + e.toString());
        }
    }

    private Player.DefaultEventListener mDefaultEventListener = new Player.DefaultEventListener() {
        @Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

        }

        @Override
        public void onLoadingChanged(boolean isLoading) {
            // Do nothing.
            //KlLog.d(TAG, "onLoadingChanged");
        }

        @Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
            // Do nothing.
            Log.d("TAG", "onPlayerStateChanged"+playbackState);
            //KlLog.d(TAG, "changed state to " + stateString
            //      + " playWhenReady: " + playWhenReady);
        }

        @Override
        public void onRepeatModeChanged(@Player.RepeatMode int repeatMode) {
            // Do nothing.
        }

        @Override
        public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {
            // Do nothing.
        }

        @Override
        public void onPlayerError(ExoPlaybackException error) {


        }

        @Override
        public void onPositionDiscontinuity(final int reason) {
            super.onPositionDiscontinuity(reason);

            //KlLog.d(TAG, "onPositionDiscontinuity : " + exoPlayer.getCurrentWindowIndex());
        }
    };
}`

**Comment by christosts** [comment]
Some background (copied from this [comment](https://github.com/google/ExoPlayer/issues/8671#issuecomment-790381298)): 

> when seeking to an arbitrary position, the player needs to start loading frames from the nearest key frame before the seek position, thus the frames in between must be decoded and then discarded. There is no way to avoid the delay but it can be minimized by having the media contain more frequent key frames.


Starting playback at `17000` as your snippet above, it did take time on my tests (2-4 seconds to start playback). The file that we received is compressed quite well, which as a result does not have frequent key frames (to reduce file size). The player needs to perform 2 HTTP requests (I did not measure the latency to the server), first to read the the file headers and then another HTTP request to 'jump' to the nearest key frame, and I see the player started processing frames from 13000ms, which I guess is the nearest preceding key frame. 

If you want to improve seeking, you can try (not in particular order)
- using a different encode for the file, so that the content has more key frames (with the cost of file size increase)
- trying out on a server with lower latency
- Setting the player's seek parameters to not perform exact seeking ([Player.setSeekParameters()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setSeekParameters(com.google.android.exoplayer2.SeekParameters))), but seek to the closest sync point? That should improve seeking time, but the playback will not start at the point you asked but the point of the key frame.

**Comment by billyjoker** [comment]
Is it a good idea to reduce a bit the DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS ? I mean, not at the beginning but when during the playback is needed a rebuffering
