### ISSUE TITLE
Exoplayer take more time to play video with firebase Url .

### ISSUE THREAD

**Issue by abhayjaiswal** [google/ExoPlayer#8914]
Exoplayer take very more time for play video with firebase url . But I have tried play video with other url then take less time compare then firebase url . my internet speed is also fine . I have paid firebase storage service .

Firebase Demo Video  Url :-  https://firebasestorage.googleapis.com/v0/b/klapus-874c7.appspot.com/o/ExpertUploadVideos%2F20210506_222414.mp4?alt=media&token=69185e1a-5c2f-47af-91cd-30122670ed08

Other video url also take more time more then 40 second or more .

I have used below version :-
ExoplayerVersion:-  2.10.8
Device:- I have test on more device but same result .

**Comment by christosts** [comment]
When I try to open the video from your URL above, I see the response-to-first-byte is between 0.6 to 1 seconds (this is latency time, excluding the time it takes for the bytes to download). You can see that from opening the link from a browser and inspecting the network statistics. This delay is not related to the internet speed (I have access to > 100Mbps).

I also see the player has to make a 3 HTTP requests to fill up its buffers, these are causing a delay of 2-3 seconds, excluding the time to actually transfer the data. 

Unless I understood your question wrong, I'd say that the video is not served fast enough. I'm not aware of the firebase service, maybe you need to tune how static files are served so that they are served through a CDN.

I'll close this issue for now, feel free to re-open if I did not understood your question correctly or more information is needed. 

Thanks
