### ISSUE TITLE
Settings popup disabling fullscreen using StyledPlayerControllView

### ISSUE THREAD

**Issue by jordyamc** [google/ExoPlayer#8922]
While using a fullscreen sticky activity, if the settings popup is opened, the fullscreen is disabled, the system bars won't hide anymore, and it shows above the player, also there is no option to disable the settings button

![Screenshot_20210510-012657](https://user-images.githubusercontent.com/6831873/117615200-00cdd200-b12f-11eb-879c-907a24606af1.png)
![Screenshot_20210510-012716](https://user-images.githubusercontent.com/6831873/117615204-01666880-b12f-11eb-8ff2-c492a69ba5cc.png)
![Screenshot_20210510-012726](https://user-images.githubusercontent.com/6831873/117615205-01666880-b12f-11eb-8da1-da68ec39b5ad.png)

**Comment by ojw28** [comment]
Hiding and displaying the system bars is handled by application code rather than by ExoPlayer, so it's somewhat unclear to what extent this is an ExoPlayer issue. If you'd like us to take a look at what's going on, please could you provide a simple GitHub project that we can clone to reproduce the issue? Thanks!
