### ISSUE TITLE
Identifying content type with URL redirects (HTTP 302)

### ISSUE THREAD

**Issue by croccio** [google/ExoPlayer#8925]
302 redirect not works properly also with 
`setAllowCrossProtocolRedirects(true)`

the channel url is this:
`https://www.mytivu.it/Application/Channels/TV8.php`

**Comment by christosts** [comment]
> the channel url is this:
> `https://www.mytivu.it/Application/Channels/TV8.php`

The url redirects to another url that returns HTTP 403. Do you need special setup to open the url (e.g. agent)? I tested with curl from command line and from Chrome

**Comment by croccio** [comment]
No, i put it on vlc and on safari and it works without problem.

**Comment by christosts** [comment]
The url resolves to 
http://retry.skyanywhere3-i.akamaihd.net/hls/live/510694/mtv8sdlive/index.m3u8

which returns 403 for me. I tested on Chrome, curl (bash), Safari and vlc, all on a Macbook. Could this url be geo-protected?

**Comment by croccio** [comment]
i don't know sorry. i tried it from italy and from switzerland and it works.

Il giorno mer 12 mag 2021 alle ore 17:10 christosts <
***@***.***> ha scritto:

**Comment by christosts** [comment]
I was able to access the content through a proxy in Italy. I tested on 2.13.3. The link failed to play on ExoPlayer because the player could not figure out the correct content type and assumed the link points to progressive media  (eg. mp4), whereas the URL redirects to an HLS stream.

To fix this:
- On the demo app, you can pass a hint to the player to load the URL as an HLS stream. The json entry should be
```
{
  "name": "...",
  "uri": "https://www.mytivu.it/Application/Channels/TV8.php",
  "extension": "m3u8"
}
```

- On your app: the default behavior of the player is to infer the content type from the URL, defaulting to progressive media if the URL does not clearly indicate it's HLS, DASH or SmoothStreaming. Your URL redirects to an HLS stream and you can hint that to the player by setting the corresponding MIME type when you build the [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html#setMimeType-java.lang.String-). That also means that in your app you need to know the kind of content beforehand, when creating the MediaItem.

I'm closing this issue, please free to re-open if you need more information.
