### ISSUE TITLE
Bug in streaming HLS H265 video, massive frame drop

### ISSUE THREAD

**Issue by brabeler** [google/ExoPlayer#893]
I have previously been using ExoPlayer 1.4.2 to stream a HLS H265 video and had no issue.  Then when upgrading to 1.5.1, the video plays but has massive frame drop, only about half the frames play and the video is very jerky.

I compared the source between the two versions and went through the changes in extractor/ts/TsExtractor.java and extractor/ts/H265Reader.java.

Bug 1:  I noticed that the addition of the DTS decode timestamp adjustment in TsExtractor.java was causing the value of PtsTimestampAdjustor.timestampOffsetUs to go from -1466733 in 1.4.2 to -1400000 in 1.5.1.  This has the effect of shifting all the timestamps earlier and skipping 2 of them.  So instead of getting 0, 166833, 100100, 33367, 66733, 133467 (as in 1.4.2), I get 0, 233566, 166833, 100100, 133466, 200200 (after fixing for bug 2 below).  So I can just comment out the line "ptsTimestampAdjuster.adjustTimestamp(dts);" and make things work like in 1.4.2, but I don't think that is your intention.

Bug 2: The changes in H265Reader.java are causing the samples to be extracted and decoded in a different order than before.  In 1.4.2, even through the H265 samples are not extracted in presentation time order, the frames would always be decoded and sent to MediaCodecVideoTrackRenderer.processOutputBuffer() in presentation time order.  Now in 1.5.1, the frames are not sent in presentation time order, causing the massive frame drop.  I narrowed down the problem to the fact that the timestamps being used in H265Reader are one sample ahead of what was used in 1.4.2 (after removing the code for the DTS adjustment).  So instead of getting 0, 166833, 100100, 33367, 66733, 133467 (as in 1.4.2), I get 166833, 100100, 33367, 66733, 133467, 333667.  Notice that timestamp 0 is missing completely.  As a temp fix in SampleReader.endNalUnit(), I added "sampleTimeUsPrev = sampleTimeUs" before sampleTimeUs is set, and then use sampleTimeUsPrev as the timestamp passed to sampleMetadata().  This fix causes the timestamps to be the same as in 1.4.2, and the sample sizes are the same as well.

As a side note, my temp fix for bug 2 fixes the issue 99.9% of the time, but there is another issue when it is SampleReader.startNalUnit() that is calling outputSample().  In this case, the timestamp is correct but the size of the sample is wrong compared to 1.4.2.  Also this call is made at the beginning of every TS segment, except the first one.  I have not yet noticed the effect of the sample size difference, since it only occurs for one sample every 8 seconds.

My device is a Samsung Note 4 running Lollipop 5.01.  I am happy to give you any more details necessary in order to fix this bug.  Thanks.

**Comment by ojw28** [comment]
Can you provide test media that reproduces the issue? That aside, I don't fully understand what you mean. Specifically:

*I noticed that the addition of the DTS decode timestamp adjustment in TsExtractor.java was causing the value of PtsTimestampAdjustor.timestampOffsetUs to go from -1466733 in 1.4.2 to -1400000 in 1.5.1. This has the effect of shifting all the timestamps earlier and skipping 2 of them.*

I agree this can shift the timestamps from what they were set to previously, but how did you conclude that it caused skipping? The TsExtractor is still generating the exact same number of timestamps as before. Where exactly are the timestamps you quoted taken from?

*I narrowed down the problem to the fact that the timestamps being used in H265Reader are one sample ahead of what was used in 1.4.2 (after removing the code for the DTS adjustment). So instead of getting 0, 166833, 100100, 33367, 66733, 133467 (as in 1.4.2), I get 166833, 100100, 33367, 66733, 133467, 333667.*

That would be a problem. Do you happen to know exactly which change caused the problem? I'll take a look.

**Comment by ojw28** [comment]
We believe the fix above (courtesy of @andrewlewis ) resolves the issue. Please can you verify that this is the case. We may do a small 1.5.2 release to get the fix into the master branch. Thanks!

**Comment by brabeler** [comment]
Thank you for the fast fix.  Yes this did fix the frame dropping issue.

I still have the issue with the DTS decode timestamp causing the timestamps to shift forward and skip the first two values.  I will open a separate issue for that.
