### ISSUE TITLE
TrickPlay support for HLS/DASH stream

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#8933]
We are implementing TrickPlay with ExoPlayer. We have a preview thumbnail information available on both HLS/Dash manifest.
Did some investigation on the existing issues and just wanted to confirm, if it is supported or not?

If it is currently not supported then, do you have it on your roadmap?

**Comment by Samrobbo** [comment]
If you look at #474, the associated commits and comments discuss in detail the support we have for TrickPlay. It looks as though the PR #6270 added support for this. Does that cover your use case?

**Comment by nishantkp** [comment]
Hi @Samrobbo,

How would I select a trick-play track? By default, it is not doing it.

**Comment by Samrobbo** [comment]
(Added @AquilesCanta as an additional assignee as he knows more about this than I do) 

From what I understand, ExoPlayer does _not_ support TrickPlay out of the box. The way to expose the track that is intended for trick play would involve extending the DefaultTrackSelector so that that track is not ignored. However after that you would have to control how you use this track yourself.

What exactly is your use case for this? TrickPlay as a term is slightly overloaded, so knowing what you want to use this for helps us answer this a little clearer. You mentioned wanting to show thumbnail information, rather than wanting to do a fast-forward/rewind style functionality?

**Comment by AquilesCanta** [comment]
To expand a bit on what @Samrobbo says:

> How would I select a trick-play track

You can extend the DefaultTrackSelector and override [selectVideoTrack](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html#selectVideoTrack-com.google.android.exoplayer2.source.TrackGroupArray-int:A:A-int-com.google.android.exoplayer2.trackselection.DefaultTrackSelector.Parameters-boolean-) so that it picks whichever trickplay track you want. You can identify a trickplay track by its Format's [roleFlags field](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Format.html#roleFlags), which will have the flag [ROLE_FLAG_TRICK_PLAY](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#ROLE_FLAG_TRICK_PLAY) set.

So once you've selected the track, you can start consuming it. If what you want to do is showing a thumbnail, I guess the best way is to have a dedicated player for the thumbnail. To select the thumbnail you want, you seek to the position you want (in the thumbnail player, which does not select an audio track), while having playWhenReady false. Also, for a good UX, you might want to download the thumbnail track, assuming it's reasonably small.

Hope this helps! Let me know if there's anything unclear. You might want to play a bit with the points I mention above.

**Comment by nishantkp** [comment]
@Samrobbo @AquilesCanta 
Thanks a bunch for the info.
We want to show a preview thumbnail when a user scrubs on the seek-bar.
