### ISSUE TITLE
MediaDrm: MediaDrm went away with unhandled events

### ISSUE THREAD

**Issue by dzungvu** [google/ExoPlayer#8949]
Hi, I'm working on a player project which uses Exoplayer ver 2.13.2
After download a dash drm content and wait for key expired. I can't renew the key using offlineLicenseHelper. Which I've done is:
```kotlin
val offlineLicenseHelper = OfflineLicenseHelper.newWidevineInstance(
                licenseUrl,
                httpDataSourceFactory,
                eventDispatcher
            )

val licenseKey = offlineLicenseHelper.renewLicense(downloadRequest.keySetId)
```

And I received message:

```
W/MediaDrm: MediaDrm went away with unhandled events
I/chatty: uid=10305(vn.test.fplayertest.debug) identical 1 line
W/MediaDrm: MediaDrm went away with unhandled events
W/System.err: kotlin.KotlinNullPointerException
```

I couldn't figure out what is the problem and where I can place a MediaDRM handler. So, can you help me for this issue.

**Comment by icbaker** [comment]
Can you provide more precise information (including some of the things requested in the template provided when you filed this issue)?

> I can't renew the key using offlineLicenseHelper.

What actually happens when you try and renew it? You included a very short log snippet but it doesn't contain any errors or exceptions, only warnings. A bug report (captured with `adb bugreport`) would probably contain more useful information - especially if you have an [EventLogger](https://exoplayer.dev/debug-logging.html) attached in your app.

If possible please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

----

Are you sure that the `MediaDrm went away with unhandled events` log line is actually a problem?

> where I can place a MediaDRM handler.

I don't think it's something you can fix by adding a handler/listener - I think the error is saying "an event has arrived but my native implementation has gone away". Take a look at the code here:
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/media/java/android/media/MediaDrm.java;l=914;drc=53fe96661be60ee70e16d3039339b9f069904a61

**Comment by dzungvu** [comment]
Thanks for your quick support. I found that the error was caused by other process beyond Exoplayer library. So, I'll close this.
Sincere Thanks!
