### ISSUE TITLE
Exoplayer download service unable to download different HLS videos with different cookie value for authentication 

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#8950]
I have implemented a download service and it is working fine with normal HLS URL's....but when i try download a HLS URL which usses some cookie value for authentication...my download fails because download manager initializes only once in download service of exoplayer. Is there any way to restart the service every time or change the instance of download manager every time for each video or to stop the download service if one video has been completed and start service again for another video as that would solve my issue.

**Comment by marcbaechinger** [comment]
When you subclass the `DownloadService` you need to implement the `getDownloadManager` method. So you can construct the `DownloadManager` yourself.  So your app can determine what `DataSource.Factory` is passed to the constructor of `DownloadManager`. If you pass a `ResolvingDataSource.Factory` you can change the request at the moment when the request is issued. This seems to be a flexible way to change your request.

>  restart the service every time or change the instance of download manager every time

Would the apporach above help for this? Instead of creating a new service or download manager you would be able to change the request you are doing with the `ResolvingDataSource` that modifies the `DataSpec` passed to the upstream data source by consulting the `ResolvingDataSource.Resolver` that you implement.

Please let me know if this helps.

If not, can you clarify a bit how the request to the server needs to be changed for successfully downloading with authentication?

**Comment by anandsingh2903** [comment]
Alright will try your suggested implementation and will get back to you.

**Comment by anandsingh2903** [comment]
This is working great....thanks
