### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#8956]
We have `PlayerView` that integrates `ExoPlayer` and plays a video content. The `PlayerView` is embedded in `PlayerFragment` that can be placed in any layout. We have `FullscreenPlayerActivity` that has fullscreen style and contains `PlayerFragment`.

When an user taps on fullscreen button, we register `Activity` lifecycle and starts `FullscreenPlayerActivity`. When the `Activity` is created, we register its `Fragment` lifecycle and when `PlayerFragment`'s `View` is created, we remove `PlayerView` from `PlayerFragment` that is embedded in layout and add the `PlayerView` into `PlayerFragment` that is in `FullscreenPlayerActivity`.

In other words, when an user taps on fullscreen button, the `PlayerView` from _Screen with embedded player_ is moved into `PlayerFragment` from `FullscreenPlayerActivity`.

Screen with embedded player | Screen with fullscreen player
--- | ---
an `Activity` | `FullscreenPlayerActivity`
`PlayerFragment` | `PlayerFragment`
`PlayerView` | -

This mechanism works fine on mid and high end devices, but on low end devices we have a problem. When we remove `PlayerView` from `PlayerFragment` that is embedded in layout, an user sees a black rectangle for a fraction of a second and black screen for maybe two seconds in `FullscreenPlayerActivity`. Audio playback continues without interruption. We are using `SurfaceView` in `VideoComponent` that is moved together with the `PlayerView` from embedded into fullscreen player.

Could you please help as, how to eliminate the black rectangle and the black screen that are visible for a few seconds? Functionality is similarly with the Youtube app, where the problem does not occur.

**Comment by icbaker** [comment]
Do you observe the problem only when playing DRM content or clear content as well? (the original issue mentioned DRM, but that was removed in a later edit)

If it's happening during Widevine L1 then it's probably the limitation of the underlying platform described in https://github.com/google/ExoPlayer/issues/6847#issuecomment-571929790.

If you see it in other cases please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally, and be specific about what behaviour you see on what devices. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by chladto1** [comment]
I know about the [#6847 comment](https://github.com/google/ExoPlayer/issues/6847#issuecomment-571929790) and I wanted to focus attention on clear content that has the issue as well.

From source code and debugging we found that GL thread in `GLSurfaceView` is stopped when the `View` is removed from `ViewGroup` (when `onDetachedFromWindow` is called) and started again when added into another `ViewGroup` (`onAttachedToWindow`).

In our case, on Moto X Play, `PlayerView` that contains `GLSurfaceView` is added into `PlayerFragment` in `FullscreenPlayerActivity`, almost second later `onSurfaceCreated` is called and `onDrawFrame` is called few dozens milliseconds later.

We tried to ignore `onDetachedFromWindow` to not stop GL thread but it did not help and screen was black forever.

**Comment by icbaker** [comment]
@andrewlewis may be able to comment from a GL perspective, but it would be helpful if we're able to reproduce the problem you're seeing so please  provide the [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) requested above.

**Comment by andrewlewis** [comment]
> From source code and debugging we found that GL thread in `GLSurfaceView` is stopped when the `View` is removed from `ViewGroup` (when `onDetachedFromWindow` is called) and started again when added into another `ViewGroup` (`onAttachedToWindow`).

I think the detachment of the output view is the problem. To make this transition work without any interruption to playback I think it is necessary to avoid the surface view ever being removed from the view hierarchy. See also https://github.com/google/ExoPlayer/issues/6958#issuecomment-586936724 about how to implement full screen transitions in general.

Video decoder `MediaCodec`s need to have an output surface attached at all times. From API 23 you can set the output surface of the codec, and in ExoPlayer we have an off-screen surface that's used when the app doesn't have a surface (for example, due to not having an output surface view surface available transiently), but before API 23 and on devices where setting the output surface is known not to work correctly ExoPlayer has to release and create a new decoder when the output surface changes, and when you get a new codec you effectively have to do an 'exact seek' up to the current player position before you have a frame to show, which can take time.

> In our case, on Moto X Play, `PlayerView` that contains `GLSurfaceView` is added into `PlayerFragment` in `FullscreenPlayerActivity`, almost second later `onSurfaceCreated` is called and `onDrawFrame` is called few dozens milliseconds later.

It sounds like you are passing the `GLSurfaceView` to the player so I don't think there any GL-specific considerations here. However, another option when you are using OpenGL is to have the player/`MediaCodec` render to a `SurfaceTexture` surface instead, and then copy from there to your GL output view (like in [gldemo](https://github.com/google/ExoPlayer/tree/release-v2/demos/gl/src/main/java/com/google/android/exoplayer2/gldemo)). This way you can keep the surface texture attached to the codec at all times. However, I think to have playback be uninterrupted you also need to ensure the lifetime of the output views before/after the transition overlap.

If that's too much detail, my advice would just be to modify your layout so you can use a single output view and move/resize it for the full screen transition.
