### ISSUE TITLE
Mp3's duration is not right

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#8963]
- Clear reproduction steps including observed and expected behavior
  - Play below mp3 audio url, the duration which Exoplayer returned is not right.
    - Exoplayer's duration is 4:29:57
    - ffmpeg's duration is 1:32:21
   - Because mp3's duration is estimated with bitrate, Exoplayer's bitrate is 32kb/s，ffmpeg's bitrate is 96kb/s, so I guess the problem is the bitrate.
- URI to test content for reproduction
<https://r.typlog.com/eyJzIjoxNjAwLCJlIjo2NTM4LCJwIjoyLCJ1IjoiNjEyMy5tcDMifQ.vKNDyBl7Q9eCvA7KO2OUlQl21Mo/oohomechat/8385162738_706123.mp3>

- ExoPlayer version number
  2.11.8
  
- Android version
  Android 10
- Android device
  Samsung note 9 (This issue is not related with specific device

**Comment by tuesda** [comment]
Is there any progress?

**Comment by kim-vde** [comment]
This is similar to #4071.

The duration computed by ExoPlayer is an estimate based on the bitrate of the first sample. It is incorrect because ExoPlayer assumes that the bitrate is constant for all samples but this is not true for the content you provided.

FFMPEG probably has a better estimate because it reads many (possibly all) sample bitrates to get an estimate. We cannot do that in ExoPlayer for performance reasons.

If you want the duration to be correct, you should add it to the metadata (ID3 TLEN tag for example).

**Comment by tuesda** [comment]
ok, appreciate for your response
