### ISSUE TITLE
What is the replacement of DefaultDrmSessionEventListener in v2.14.0?

### ISSUE THREAD

**Issue by nandovelazquez** [google/ExoPlayer#8969]
I’m upgrading from v2.11.8 to v2.14.0 and I noticed that the `DefaultDrmSessionEventListener` class was removed and I couldn’t find documentation related to that and/or how a callback should be set to handle DRM errors.

Could you guys help me on how I can implement this now?
Thanks

**Comment by krocard** [comment]
The file was renamed by commit https://github.com/google/ExoPlayer/commit/c6bf6aae2a2617dfa84d6a49e60fc5a5a94d4ce3 *Rename DefaultDrmSessionEventListener to DrmSessionEventListener*.

I will add this line to 2.12 release note, sorry for the confusion.

**Comment by nandovelazquez** [comment]
Thanks for clarifying that. 
Now, how could I pass a `DrmSessionEventListener` to the `DefaultDrmSessionManager`? Since the `DefaultDrmSessionManager` doesn't have anymore the `addListener(Handler handler, DrmSessionEventListener eventListener)` method.

**Comment by icbaker** [comment]
Apologies for the sparse release notes around these changes - you now add `DrmSessionEventListener` instances to a `MediaSource` rather than a `DefaultDrmSessionManager` by calling [`MediaSource#addDrmEventListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSource.html#addDrmEventListener(android.os.Handler,com.google.android.exoplayer2.drm.DrmSessionEventListener)). ExoPlayer will plumb this through and eventually pass it to the `DrmSessionManager` as part of the the `EventDispatcher` passed to `acquireSession()`.

If you're using the `MediaItem` API then directly mutating `MediaSource` instances is slightly tricky - you'll probably need to provide a custom `MediaSourceFactory` instance when constructing the player (possibly by wrapping `DefaultMediaSourceFactory`).

P.S. You can get the same DRM events via the `AnalyticsListener` interface which you can register directly on the `Player`, which might be easier. More info: https://exoplayer.dev/analytics.html

**Comment by nandovelazquez** [comment]
That helped me. Thanks!
