### ISSUE TITLE
Issues with Notifications in 2.14.0

### ISSUE THREAD

**Issue by fourofspades** [google/ExoPlayer#8974]
Upgraded my app from 2.13.3 to 2.14.0 and made the necessary changes, but I am getting a strange problem.

On most (but not all) devices, I am getting a crash:

android.app.RemoteServiceException: Bad notification for startForeground

I think it's being thrown from my audio playback service, I think around the point media metadata updates.  I am using the new ExoPlayer.Listener and onMediaMetadataChanged override method.

Even stranger, it doesn't seem to occur in debug configurations, only release R8 configurations.   I'm struggling to track it down.   It also doesn't help there is no sample code for the notification UI in the demo app.  I don't think I am doing anything wrong, it's pretty much the same as other apps I found on Github that use Exoplayer (although they have yet to adopt 2.14.0)

**Comment by fourofspades** [comment]
Done some more debugging, it's not related to R8 code shrinking/obfuscation, and it's related to Android version, it's broken on my Pixel running 11, but works on older devices.

**Comment by ojw28** [comment]
Have you looked at the many Stack Overflow posts on this issue? For example [this one](https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1)? Perhaps your app isn't creating a notification channel? If you're using `PlayerNotificationManager`, then I think you need to either:

1. Call the `PlayerNotificationManager.Builder.setChannel*` methods so that the notification channel is created for you. If you previously used `PlayerNotificationManager.createWithNotificationChannel`, make sure you're still passing all of the same values via the `Builder`.
2. Create the notification channel yourself in application code.

**Comment by fourofspades** [comment]
Creating an NotificationChannel was enough to get things working again.  I didn't need this previously (using exoplayer 2.13.3), and it wasn't clear from the release notes that it's now a mandatory requirement for 2.14.0

The error isn't exactly helpful either.  "bad" notification. Not exactly telling you anything useful.

**Comment by ojw28** [comment]
For clarity, both the requirement for a notification channel and the corresponding error message are properties of the underlying platform, not of ExoPlayer. So there was definitely a requirement that a notification channel was created prior to ExoPlayer 2.14. Glad to hear you managed to resolve the issue!
