### ISSUE TITLE
ExoPlayer doesn't recognize TTML subtitles with DFXP profile in DASH streams

### ISSUE THREAD

**Issue by vkoehler** [google/ExoPlayer#8988]
**Issue description**

we have some DASH streams that contain TTML subtiltes with DFXP profile. ExoPlayer shows these tracks as UNMAPPED:

D/EventLogger:   Unmapped [
D/EventLogger:     Group:0 [
D/EventLogger:       [ ] Track:0, id=textstream_deu=1000, mimeType=null, bitrate=1000, codecs=dfxp, language=de, supported=NO
D/EventLogger:     ]
D/EventLogger:     Group:1 [
D/EventLogger:       [ ] Track:0, id=textstream_eng=1000, mimeType=null, bitrate=1000, codecs=dfxp, language=en, supported=NO
D/EventLogger:     ]

**Link to test content**
by email

**Version of ExoPlayer being used**
exoplayer version: 2.14.0

**Comment by icbaker** [comment]
Thanks for the link to the test content. Unfortunately when I try and play it I get an HTTP 500 error from your license server:
```
2021-05-27 18:13:40.953 20326-20481/com.google.android.exoplayer2.demo E/DefaultDrmSession: DRM session error
      com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:196)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:155)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:599)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

We currently expect that `codecs` field in the manifest to contain `stpp.ttml.im1t` (yours contains `dfxp`).

I'm struggling to find information on the difference - and so I'm not sure what ExoPlayer should do with a track with `codecs="dfxp"` - can we just treat like we do other TTML tracks? This page suggests there might be some subtelty around timing: https://docs.unified-streaming.com/documentation/package/subtitles.html#ttml-in-fmp4

Do you have a spec reference I can take a look at to understand this further?

If you could either provide some unprotected content, or help me resolve the HTTP 500 DRM error that would be great.

I'm going to mark this as an enhancement rather than a bug.

**Comment by vkoehler** [comment]
DFXP is actually the first version of TTML -> TTML1. I'm not sure what is the difference to the newer TTML format, but here you can find the specification:
https://www.w3.org/TR/ttml1/#profiles

I found an old issue regarding DFXP support for SmoothStreaming. So it seems that ExoPlayer supports this TTML profile in SmoothStreaming streams: #4824.

The problem of the test content is that it's only available for a limited time, because one of the DRM headers contains an access token. I sent an updated playlist with unprotected content.

**Comment by icbaker** [comment]
Ah sorry I wasn't clear - I understand that DFXP is another name for TTML - but my question is really around the DASH spec and the `codecs` attribute of the `AdaptiatonSet` node in the XML.

I tried playing the clear manifest you provided (thanks!) with both the [Shaka player demo](https://shaka-player-demo.appspot.com/demo/#build=uncompiled) and [dash.js](https://reference.dashif.org/dash.js/v3.2.2/samples/dash-if-reference-player/index.html).
* Shaka refused to play the stream [complaining my browser couldn't handle the codecs in the stream](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4032). Checking https://shaka-player-demo.appspot.com/support.html against the codecs listed in the manifest it seems like the only one 'missing' is `dfxp`.
* dash.js played the stream but didn't display any video and didn't list the subtitle tracks in the track selector.

I also tried modifying ExoPlayer to treat `codecs=dfxp` the same as `codecs=stpp.*` (the way that TTML-in-MP4 is usually signalled) - the subtitle tracks are recognised and appear in the track selector, but when selecting them no subtitles are shown on screen. Assuming the subtitle tracks are non-empty this suggests they need to be handled/parsed differently to TTML.

So I think the next step is to find the part of the DASH spec that discusses `codecs=dfxp`, in order to understand what would be involved in supporting this format. The fact that two other major players don't seem to support this either makes me wonder if it's not part of the spec though? Not sure.

**Comment by vkoehler** [comment]
mimeType of these subtitles in the manifest is application/mp4. According to DASH-IF-IOP it's Timed Text with ISO BMFF encapsulation. Indeed these files can be parsed with an mp4 parser. You can see mdat boxes containing the actual TTML-XML:
![image](https://user-images.githubusercontent.com/68728774/120322351-9b5fa200-c2e4-11eb-88f8-f20652202a6d.png)

**Comment by icbaker** [comment]
The [DASH-IF-IOP v3.0](https://dashif.org/docs/DASH-IF-IOP-v3.0.pdf#page=117) doc mentions:
> (2) the sample entry ‘**`stpp`**’ is generic for TTML based timed text and not specific to SMPTE-TT

And it doesn't seem to mention `dfxp` anywhere as far as I can see.

I found that MP4Box also doesn't recognise the `dfxp` box type in these MP4 files when extracting the content (it does extract the content successfully):
```
$ MP4Box subs.ismt -raw 1
[iso file] Unknown box type dfxp in parent stsd
[IsoMedia] Track 1 type dfxp not natively handled
```
----

So I agree that the files are MP4 and contain valid TTML, but I'm not convinced that:
1. The DASH spec allows `dfxp` as a value for the `codecs` parameter - I think it expects `stpp` for all TTML variants.
2. The MP4 spec knows what a `dfxp` box is, and/or allows it inside `stsd`.

Given that two other major players don't play these streams, and I can't find support for this format in the specs, I think the solution to this is to fix the media rather than modifying ExoPlayer to handle this unusual content.

**Comment by vkoehler** [comment]
thanks, it's much clearer now. Not specified dfxp box is indeed strange. 

I addressed both points to our content production team.

**Comment by vkoehler** [comment]
Our content production team confirmed an issue with multiple assets, that must be fixed. I agree, it doesn't make sense to handle this in the ExoPlayer. Thanks for support!
