### ISSUE TITLE
HLS - Audio can start playing slightly before video (at start and after seek)

### ISSUE THREAD

**Issue by Manjunath-N** [google/ExoPlayer#900]
Hello,
          During the start of the playback, its observed that Video is stuck and only audio plays for few seconds and later the  video starts to play along with audio.
Tried disabling the AV sync logic to check if that be an issue, but not. Is this issue known?

Link used for the playback:
Link: http://stream2g04-f23.1plus1.ua/380555/smil:380555.smil/playlist.m3u8

Regards
Manjunath N

**Comment by ojw28** [comment]
This can happen if the server does not place video keyframes at or near to the start of each media segment. Ideally streaming services should be doing this, because it makes things like seamless switching between qualities easier and more efficient (this approach is used as standard by adopters of SmoothStreaming and DASH).

We're aware that where a stream does not have this property, audio can start playing shortly before video. I'm not sure we're inclined to fix it any time soon. If you control the stream yourself, you should look at the feasibility of placing keyframes at the start of your media segments.

**Comment by tresvecesseis** [comment]
I think we should discard all the audio frames with a timestamp lower than the first keyframe, in some of our promo channels the audio have an offset greater than one second, in this  case  we start buffering in a few tens of milliseconds,  but we don't start playing the audio until we get a video timestamp greater than the first audio timestamp and we only start playing the video  when the audio reaches the timestamp of the first video keyframe showing a static image of the  keyframe in the meantime

**Comment by Manjunath-N** [comment]
I cross checked the audio and video timestamps injected to the MediacodecTrackrenderers and they are exactly the same.

**Comment by sergiomartinez4** [comment]
Hi @Manjunath-N , were you able to get around this issue?

**Comment by peyoh** [comment]
Hello, 
we are observing such  issue with content generated by 
shaka packager `https://github.com/google/shaka-packager`.  
With another player,
shaka player  `https://github.com/google/shaka-player`
there is no A/V sync issues. Of course they are using javascript with html5, not Java 
and maybe html video element handles better this sync.

**Comment by ojw28** [comment]
(Removed unrelated comment about DASH)

**Comment by ojw28** [comment]
I don't think we plan on fixing this. Servers should place a key-frame at (or at least near) the start of each segment.
