### ISSUE TITLE
canSelectFormat is not working as expected in 2.14.0

### ISSUE THREAD

**Issue by rajinikanth0602** [google/ExoPlayer#9001]
I am facing an issue with 2.14.0 related to blocking the formats using `canSelectFormat`.

Our test hls video has `256p`, `640p`, `1280p` and `1920p` (Url : https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8), I am trying to achieve the seamless trackselection with custom adaptive track selection class overriding `canSelectFormat` and `evaluateQueueSize`. 

In case of Adaptive selection, we are blocking high resolution formats, for above test video, we are blocking `1920p`.
In case of non-Adaptive selection(like for ex: `256p` was selected), we are blocking all the formats except `256p`.

Ideally Exoplayer has to start loading the `256p` format once we start blocking all the other formats, but the player starts loading the `256p` only on seeking to some position, attached the logs below for the same.

At `00:52:37.331` in logs : User is in Adaptive mode, so we are returning `true` in `canSelectFormat` for `256p`, `640p`, `1280p` and the player has selected the `1280p`.

At `00:52:39.682` : User has selected `256p` track, we are returning `false` in `canSelectFormat` for all formats except `256p`, but in the logs you can see the player has started loading `1280p` at `00:52:44.010`, it continues to load 1280p till I seek to some position at `00:52:51.812`, after that it starts loading the correct format.  

`onLoadStarted` log is printed from AnalyticsListener callback. 

[logs_exoplayer.txt](https://github.com/google/ExoPlayer/files/6571989/logs_exoplayer.txt)

**Comment by andrewlewis** [comment]
Please could you provide a minimal patch to the demo app so that we can reproduce this?

**Comment by rajinikanth0602** [comment]
@andrewlewis Please check the patch and screen recording attached below.

STR : 
* Open HLS -> Apple 4x3 basice stream (TS) video.
* Select 256x106 resolution.

In this case, I am blocking all the formats except 256p in `canSelectFormat()`, but the player doesn't select the 256p format till we manually seek the play position. (seeked at 00:59 secs in the attached video)
 
[0001-canSelectFormat-is-not-working-as-expected-9001.txt](https://github.com/google/ExoPlayer/files/6601079/0001-canSelectFormat-is-not-working-as-expected-9001.txt)

https://user-images.githubusercontent.com/12000793/120861624-371f3580-c5a5-11eb-8fd1-e0e049c26e74.mp4

**Comment by andrewlewis** [comment]
@christosts Please could you take a look? Thanks!

**Comment by christosts** [comment]
I believe the AdaptiveTrackSelection is falling in this case [here](https://github.com/google/ExoPlayer/blob/r2.14.0/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L361-L365). 

https://github.com/google/ExoPlayer/blob/92e05bcd6608b48cc4d20974f55e6a9136274c33/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L361-L366

Your custom track selection selects a format with lower bitrate than the currently playing one, but because there are plenty of buffered data, the AdaptiveTrackSelection will continue on the existing format thinking it can continue downloading higher bitrates until the buffer is low enough to down switch. 

If you want to down switch faster, you can tune the AdaptiveTrackSelection's `maxDurationForQualityDecreaseUs` and pass a custom value in the AdaptiveTrackSelection constructor from your CustomAdaptiveTrackSelection. This will affect every adaptive decision though. Every time the AdaptiveTrackSelection decides it should switch to a lower bitrate because there is a drop in bandwidth throughput, the down-switch will happen sooner. That is not necessarily bad, you might see fewer re-buffer rates. On the other hand, periodic drops on bandwidth throughput might cause more frequent down-switches, therefore the users will see more adaptive switches.

I can't see an easy way if you want to further customize this, for example if you want to make faster down-switches when your CustomAdaptiveTrackSelection forces a change, but don't change the `maxDurationForQualityDecreaseUs` if the down switch is caused by network conditions. One idea on the extreme side, you can fork AdaptiveTrackSelection directly instead of subclassing it and modify the logic in `updateSelectedTrack()` yourself.

Note: In your patch, I suggest making the CustomAdaptiveTrackSelection thread-safe since it's handling callbacks on the app main thread and on the player's internal thread.
