### ISSUE TITLE
ExoPlayer sideloading subtitles not working

### ISSUE THREAD

**Issue by CommanderRag** [google/ExoPlayer#9021]
I am trying to show subtitles from my .srt file in exoplayer but it does not work.
Do I need to use a seperate SubtitleView to get my subtitles to show up?
Is the subtitleView in the PlayerView is not enough?
I use PlayerView btw.

The exoplayer version I use is 2.14.0.

The addTextOutput method.
```
simpleExoPlayer.addTextOutput(cues -> {
                playerView.getSubtitleView().setCues(cues);
                playerView.getSubtitleView().setVisibility(View.VISIBLE);
                playerView.getSubtitleView().onCues(cues);
                assert cues.get(0).text != null;
                Log.d("subtitles", cues.get(0).text.toString());
            });
```

I also tried to implement to `TextOutput` but that did not work too.

The contents of my sample.srt file:
```
1
00:00:00,000 --> 00:00:01,500
For www.forom.com

2
00:00:01,500 --> 00:00:02,500
<i>Tonight's the night.</i>

3
00:00:03,000 --> 00:00:15,000
<i>And it's going to happen
again and again --</i>
```

The function I use to load my subtitles:
```
public void buildMediaSourceV3(Uri uri){
        String subtitlesUri = sharedPreferencesSubtitles.getString(videoName.getText().toString(), "");

        DataSource.Factory factory = new DefaultDataSourceFactory(VideoPlayer.this, getPackageName(), new DefaultBandwidthMeter());
        MediaItem mediaItem = MediaItem.fromUri(uri);
        MediaSource videoSource = new ProgressiveMediaSource.Factory(factory).createMediaSource(mediaItem);
        if(subtitlesUri.equals(""))
        {
            simpleExoPlayer.addMediaSource(videoSource);
        }
        else
        {
                MediaItem.Subtitle subtitle = new  MediaItem.Subtitle(Uri.parse(subtitlesUri), MimeTypes.APPLICATION_SUBRIP, "en");
                //Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
                MediaSource textMediaSource = new SingleSampleMediaSource.Factory(factory).createMediaSource(subtitle, C.TIME_UNSET);
                textMediaSource.getMediaItem().mediaMetadata.subtitle.toString();
                MergingMediaSource mergingMediaSource = new MergingMediaSource(videoSource, textMediaSource);
                simpleExoPlayer.addMediaSource(mergingMediaSource);
        }
    }
```

**Comment by claincly** [comment]
Can you share the relevant media? It'd be hard to pinpoint the issue without it.

**Comment by CommanderRag** [comment]
The video is [https://www.youtube.com/watch?v=rUWxSEwctFU](url) which I downloaded using youtube-dl.

**Comment by claincly** [comment]
Have you tried putting the subtitle URI in a `MediaItem`, instead of creating a media source?

There's a `setSubtitles()` method in `MediaItem.Builder`

https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/common/src/main/java/com/google/android/exoplayer2/MediaItem.java#L425

**Comment by icbaker** [comment]
It's likely the subtitle track isn't being selected - it won't be selected by default unless you either set `MediaItem.Subtitle.selectionFlags = SELECTION_FLAG_DEFAULT` (and pass this to `MediaItem` rather than trying to construct the `MediaSource` yourself) or change the `TrackSelector` to select it by some other means. More info about track selection: https://exoplayer.dev/track-selection.html

You can check this by attaching an `EventLogger` backed by a `TrackSelector` (from `player.getTrackSelector()`, you should be able to safely cast this to `MappingTrackSelector`) and looking at the track output - if the text track is marked with `[ ]` instead of `[X]` then it's not being selected. More info about attaching an `EventLogger`: https://exoplayer.dev/debug-logging.html

**Comment by CommanderRag** [comment]
I gave up and implemented my own subtitle showing view. 
I don't know why it did not work.
Maybe because the uri of the subtitle file had 
`content://` in it.
