### ISSUE TITLE
ExoPlayer has dependencies that are only available via jcenter()

### ISSUE THREAD

**Issue by electrodragon** [google/ExoPlayer#9032]
I have included the ExoPlayer by placing it locally in my computer, it works fine if i add jcenter() in my repositories, but as it is going to shut down soon. so android studio is also suggesting to remove its usages, and when i remove i get these three errors.

```
Failed to resolve: com.google.vr:sdk-base:1.190.0
Show in Project Structure dialog
Affected Modules: exoplayer-extension-gvr
```

```
Failed to resolve: net.butterflytv.utils:rtmp-client:3.1.0
Show in Project Structure dialog
Affected Modules: exoplayer-extension-rtmp
```

```
Failed to resolve: com.linkedin.dexmaker:dexmaker:2.21.0
Show in Project Structure dialog
Affected Modules: exoplayer-library-core
```

I went to the dex maker site and add their maven sona type repo url 
```
maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
}
```
but the same error.

**Comment by ojw28** [comment]
You should just keep using `jcenter()` for now. These will be fixed by the time it's actually shut down:

1. We will probably just withdraw the `exoplayer-extension-gvr` module. It's been deprecated for quite a long time now
2. https://github.com/ant-media/LibRtmp-Client-for-Android/issues/96 tracks `net.butterflytv.utils:rtmp-client` being provided via maven central
3. `com.linkedin.dexmaker:dexmaker` can be easily fixed by updating our dependency to `2.28.1`
