### ISSUE TITLE
How to pass `setMaxVideoBitrate` in new `SelectionOverride`

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#9035]
My case is with **DASH** content.
**ExoPlayer Version:** v2.14.0 (No relation with version)
**On ExoPlayerDemo:** I did not try yet to reproduce due to complex changes required.

I am passing `setMaxVideoBitrate` on `DefaultTrackSelector.ParametersBuilder` while creating the `DefaultTrackSelector` and I can see that my video max Bitrate is limited to what I passed.

Then after it, I am creating my own `SelectionOverride` and on the same `DefaultTrackSelector.ParametersBuilder`; I call `parametersBuilder.setSelectionOverride` and pass my `SelectionOverride`  and then pass it to `DefaultTrackSelector` using `setParameters`.

I can see that `DefaultTrackSelector.ParametersBuilder` has the old `setMaxVideoBitrate` which I passed 1st time but still, I don't see that it has any impact. My video starts to play between the given `SelectionOverride`.

PS: This is the current analysis and assumption that may be Player is not considering the old parameters in case when new `SelectionOverride` is given.

**Comment by ojw28** [comment]
A selection override will override any other constraints that you've specified. In other words, if you specify an override and if that override applies to the currently available tracks, then you will get exactly the tracks specified by the override. This is by design. 

If you want to specify a selection override and if you also want to exclude tracks that exceed a particular bitrate, then you should not include such tracks in the override in the first place.
