### ISSUE TITLE
Switch Video Seamlessly

### ISSUE THREAD

**Issue by cmfcm** [google/ExoPlayer#9043]
I'm working on a project which need to switch video seamlessly, the basic requirements are:  

I have some videos, e.g. 3 videos A, B and C, I need to switch among them seamlessly according to the user's input. I used `seektoDefaultPosition` to realize that easily.

However, another special requirement is after playing B or C , A must be played regardless of user's input, I've gone through the doc. but I did not find any listener which is triggered when each `mediaItem` finish(or I could directly use `seektoDefaultPosition`). Is there any easier idea which doesn't modify the order of the player list?  

Thank you!

**Comment by icbaker** [comment]
* I'm not sure I **completely** understand your problem - I'll have a go at answering your questions but if it seems like I'm missing the point then it might be helpful for you to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. Then I'll be able to better understand exactly what you're doing and what you're trying to achieve.
  * This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
* 'seamless' probably has many different definitions, so it could be we're imagining different things when we're using that word. I'm using it to mean the kind of transition that drops no video frames or audio samples, so you wouldn't notice it in the middle of a panning camera movement and a sine wave audio track (both very vulnerable to frame/sample drops). You're discussing jumping around between videos in response to user input, which sounds like it will always appear non-seamless by this definition, since there will presumably always be audio & video discontinuities.
   * Maybe you just want to avoid as much buffering/other pauses as possible? i.e. make the transition 'fast' even if it's not 'seamless'?

In order to seamlessly transition from MediaItem N to MediaItem N+1, the player has to start buffering & feeding samples from N+1 into the decoder before N has finished playing.

So if your playlist looks like [A, B, C] (and both B & C start with keyframes, which they should do unless they've been truncated for some reason), then without any interaction with the player it should seamlessly play through A then B then C.

If you want to suddenly switch part way through playing A to start playing B or C as soon as a user interacts with your app then it's basically impossible to make that truly seamless, because none of the pre-buffering or decoder-feeding has been done.

Pre-buffering the start of multiple items (so that a sudden transition can be done faster) isn't currently very easy (see https://github.com/google/ExoPlayer/issues/3327).

Pre-feeding samples to the decoder isn't possible **before** the user input (because you need to be feeding A's samples into the decoder at this point). The only way to avoid the delay associated with pre-warming a decoder during a sudden, user-initialized, transition is to maintain a second player and just switch the surfaces between them - however this is a pretty advanced use-case and I'm afraid we can't provide detailed guidance - you may like to take a look through other issues on this tracker to see how other people are doing this.

-------

>However, another special requirement is after playing B or C , A must be played regardless of user's input, I've gone through the doc. but I did not find any listener which is triggered when each mediaItem finish(or I could directly use seektoDefaultPosition). **Is there any easier idea which doesn't modify the order of the player list?**

Why don't you want to modify the playlist? The easiest way to play A after B or C is to just insert A into the playlist after B or C (using [`Player#addMediaItem(int, MediaItem)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#addMediaItem(int,com.google.android.exoplayer2.MediaItem)). It's completely fine to insert A multiple times into the same playlist.

You can listen to [`Player.Listener#onMediaItemTransition()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onMediaItemTransition(com.google.android.exoplayer2.MediaItem,int)) to know when B or C start playing, so you know when to insert A (it's marked as deprecated but that's just meant to indicate you're supposed to implement `Player.Listener` instead of `Player.EventListener`).
