### ISSUE TITLE
"Decoder init failed" occurs at video playback start

### ISSUE THREAD

**Issue by KazukiSugiyama107** [google/ExoPlayer#9053]
#### Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

#### Question
The following error occurred during streaming playback.
Is there a problem with a particular device because it is a decoder problem?

```
onPlayerError error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.IMG.MSVDX.Decoder.AVC.secure, Format(video-avc1-3, null, null, video/avc, avc1.4D4028, 1000000, null, [800, 450, 29.97003], [-1, -1])
ExoPlaybackException.TYPE_RENDERER
Decoder init failed: OMX.IMG.MSVDX.Decoder.AVC.secure, Format(video-avc1-3, null, null, video/avc, avc1.4D4028, 1000000, null, [800, 450, 29.97003], [-1, -1])
```

* Version of ExoPlayer being used: 2.12.1
* Terminal where the error occurs: AGS2-W09
* Android version: Android 8.0.0

#### A full bug report captured from the device
I sent it to dev.exoplayer@gmail.com.

**Comment by ojw28** [comment]
Unfortunately the point of failure doesn't seem to be included in the bug report. Did you capture it shortly after encountering the issue? If you didn't do this, please could you do it and send us the fresh bug report? If you did do this the first time, please could you capture logcat output at the point of failure, and provide us with that instead? Make sure to capture the failure and at least a couple of seconds either side.

If you're providing the updated information by email, please update the GitHub issue once you've done so, so that we know you've sent it. Thanks!

**Comment by KazukiSugiyama107** [comment]
Thank you for your confirmation! 
We will check the acquisition status of the bug report and request the acquisition of the bug report again.

**Comment by ojw28** [comment]
Marking as `needs more info` until the updated bug report has been provided.

**Comment by skogl** [comment]
I get the same error message on some devices if I use wrong drm key for playback. Other devices give different message (something about secure input buffer).
