### ISSUE TITLE
Concurrent buffer data loading implementation

### ISSUE THREAD

**Issue by DarkAnakin** [google/ExoPlayer#9059]
Hi,
I have a non critical issue when I try to play a video that the server take always more time to return a result than actual data duration.
As data buffered will always be consumed faster than the loading one, the player will need to rebuffer.

I use cronet extension as datasource with 6 fixed thread pool and need at least the video track use at least 2 concurrent thread to load  the data. How can this be implemented?

**Comment by ojw28** [comment]
I don't understand the question. You seem to be saying that (a) the server cannot transfer media at faster than 1x speed, and (b) this means that the client will need to re-buffer. This is correct, and (b) is fundamentally unavoidable if (a) is true. If you wish to avoid re-buffering, you'll need to make it so that (a) is false. For example by re-encoding the content at a lower bitrate.

Please could you clarify what your question is?

**Comment by DarkAnakin** [comment]
Of course the issue should be resolve on the server side but I don't have any control on it. I try to play a live 4k content but if the link between the client and the server is not optimal the player need to re-buffer or play at lower resolution. After I have read the parallelize downloads implementation in the version 1.12 I have thinking that maybe I could solve my issue but I could not found how.
Feel free to close this "issue" if you think this case should not be resolve on client side.

Thanks

**Comment by ojw28** [comment]
Closing because it doesn't sound like a client issue.
