### ISSUE TITLE
question of AC3 volume level.

### ISSUE THREAD

**Issue by hanlareum** [google/ExoPlayer#9074]
When using ffmpeg extension, the volume level of AC3 2channel and AC3 6channel is different.
How can I fix it?

**Comment by ojw28** [comment]
ExoPlayer feeds the sample data through FFmpeg to decode it, and then feeds the decoded output to `AudioTrack` for playback. So the player is more or less just an intermediary here.

I'm somewhat unclear what you mean by "different", because the source content itself is different. Are you sure the source content has the same volume in both cases? For us to investigate further, you'll need to provide us with some reproduction steps, including the relevant test stream(s).
