### ISSUE TITLE
How can I play flac files which sample rate is 384kHz or 352.8kHz.Is there any functions to resample flac files.

### ISSUE THREAD

**Issue by zhhach123** [google/ExoPlayer#9077]
Hi,
I have a android project using Exoplayer to play music.Now I have a project function to play DXD audio files.This audio files is flac files which format is 384kHz/24bit or 352.8kHz/24bit.Most of mobilephones do not support the sample rate.So,is there any solutions?
My solution is to resample these DXD files to 192kHz or 176.4kHz,then play them.Is there any functions to resample flac files in Exoplayer?
Thanks.

**Comment by ojw28** [comment]
Have you tried using the FLAC extension? It looks like we removed any restriction on sample rate in [this commit](https://github.com/google/ExoPlayer/commit/67a748f47d6aa7973e5f2cb168907d55a266263b), which would suggest that playback might work from 2.11.2 and above.

If it doesn't please provide complete information as requested in our issue template, including reproduction steps.

**Comment by zhhach123** [comment]
Yes,I have using the Flac extension.The question is the function AudioTrack.getMinBufferSize() return -2.
`        if ( (sampleRateInHz < AudioFormat.SAMPLE_RATE_HZ_MIN) ||
                (sampleRateInHz > AudioFormat.SAMPLE_RATE_HZ_MAX) ) {
            loge("getMinBufferSize(): " + sampleRateInHz + " Hz is not a supported sample rate.");
            return ERROR_BAD_VALUE;
        }
`
AudioFormat.SAMPLE_RATE_HZ_MAX is 192000,my audio files format is larger than that.So it returns is not a supported sample rete.

**Comment by ojw28** [comment]
Ah. I think what happens is that the FLAC extension can decode the audio fine, but the decoded PCM is still in the high sampling rate, which the underlying platform cannot handle.

As such, this type of audio is currently unsupported. You may be able to figure out a way to resample to a lower rate either in the FLAC extension, or using an `AudioProcessor`. Since it's a niche use case, it's unfortunately not something we'll able to provide any detailed guidance on.
