### ISSUE TITLE
Possible bug in player

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#9088]
Protocol used: DASH 
Android version: 10
Emulator: Yes 
Exoplayer demo app used? : Yes
DRM scheme: Widevine 
Authentication HTTP headers: Bearer "token" 

Steps: 
1.Setup demo app with stream url, drm license, token. 
2. Player start to play content correctly.
3. Once content finish STATE_ENDED never is called. 

playWhenReady: true , playStateReady: ready, windows: 0. 
 

More info via email.

**Comment by icbaker** [comment]
When I play the content provided over email in the demo app I see the playback counter continue past the 2:26:03 'end time' and no `STATE_ENDED` event is logged from the `EventLogger`.

I removed the `EventStream` section of the manifest and now the playback stops at 2:26:03 and `STATE_ENDED` **is** logged.

The `presentationTime` and `presentationTimeOffset` values in the `EventStream` seem to be relative to the unix epoch (I'm guessing, because that puts them on 20th June 2021). However the DASH spec defines `Event.@presentationTime` as:
> specifies the presentation time of the event relative to the start of the Period.

Given that this period is 2h26m long, and the first Event is defined to happen about 51 years after the beginning of the period, I think that explains why playback doesn't stop at 2h26 - it will continue for about 51 years waiting for the events to fire.

@ojw28 can confirm I've understood the DASH spec correctly - but this looks to me like non-compliant media.
