### ISSUE TITLE
Exoplayer loads more than 2 seconds data for bufferForPlaybackMs of 1 second, before start of playback. Why ?

### ISSUE THREAD

**Issue by harishiyer0204** [google/ExoPlayer#9089]
I understand that ExoPlayer does not wait for an entire chunk to download before starting playback. However, with chunk length being 4 seconds and "bufferForPlaybackMs" set to 1 second, it still loads more than 2 seconds of content before starting playback. What could be the reason for this?

**Comment by ojw28** [comment]
There's a certain amount of parallelism in the way this logic works. Once `bufferForPlaybackMs` of media has been downloaded, playback will start. But whilst playback is starting the player is continuing to download media, so depending on how quickly media is being downloaded, and on how quickly playback is able to start, there may be more media in the buffer by the time playback has actually started. It's essentially a race between two operations that are occurring in parallel.

It's unclear how you are actually measuring this, in order to state that this is what happens. It could be that your testing methodology is not valid.
