### ISSUE TITLE
How to add AdsLoadedListener in new ImaAdsLoader.Builder

### ISSUE THREAD

**Issue by Debayudh** [google/ExoPlayer#9097]
We are migrating our code from older version of exoplayer and working towards keeping the app code in line with the exo sample app.
Following is the code to add the adsloader in exo sample app:
`private AdsLoader getAdsLoader(MediaItem.AdsConfiguration adsConfiguration) {
    // The ads loader is reused for multiple playbacks, so that ad playback can resume.
    if (adsLoader == null) {
      adsLoader = new ImaAdsLoader.Builder(/* context= */ this).build();
    }
    adsLoader.setPlayer(player);
    return adsLoader;
  }`

We are unable to add an AdsLoadedListener into the adsLoader. Is there any way/workaround to add this into the new ImaAdsLoader?

Note: 
We are moving out of using the ConcatenatingMediaSource for merging ads to adding the adUrl in MediaItem, as used in exo sample app.
In earlier versions, after calling, `builder.buildForAdTag(loadedAdTagUri)` , 
we were calling `adsLoader.getAdsLoader().addAdsLoadedListener(mAdsLoadedListener);`

**Comment by icbaker** [comment]
`MediaItem` instances are converted to a `MediaSource` by a `MediaSourceFactory`. By default this is a `DefaultMediaSourceFactory`, which has a [`setAdsLoaderProvider()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/DefaultMediaSourceFactory.html#setAdsLoaderProvider(com.google.android.exoplayer2.source.DefaultMediaSourceFactory.AdsLoaderProvider)) method that allows you to customise how the `AdsLoader` is built.

You can see an example here: https://exoplayer.dev/media-sources.html#customizing-media-source-creation

**Comment by Debayudh** [comment]
@icbaker We are already calling setAdsLoaderProvider.
However, we need to provide an instance of ImaAdsLoader / exoplayer2.source.ads.AdsLoader inside that.
Currently, neither of the two have apis exposed for adding an AdsLoadedListener.

**Comment by Debayudh** [comment]
Also, imaAdsLoader.getAdsLoader() is always giving null, so cannot add the adsLoadedListener there.\

**Comment by Debayudh** [comment]
@andrewlewis  any suggestions?

**Comment by icbaker** [comment]
Thanks for clarifying the problem further.

Can you give a bit of context about what logic you have inside your `AdsLoadedListener#onAdsManagerLoaded(AdsManagerLoadedEvent)` implementation? It may be that you can get the same trigger by implementing [`AdsLoader.EventListener#onAdPlaybackState(AdPlaybackState)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/ads/AdsLoader.EventListener.html#onAdPlaybackState(com.google.android.exoplayer2.source.ads.AdPlaybackState)) or we can expose another listener/callback integration point that gives you the info you need.

We deliberately hide the raw `onAdsManagerLoaded` callback, because it could result in the app mutating the underlying IMA `AdsManager` in a way that confuses the IMA extension implementation.

**Comment by Debayudh** [comment]
@icbaker 
We have a custom seekbar that we use separately, and to populate the ad cue points, we are using the 
`adsManagerLoadedEvent.getAdsManager().getAdCuePoints()`

Also, could you guide us on how to add the AdsLoader.EventListener into ImaAdsLoader?
the builder.setAdEventListener() requires AdEvent.AdEventListener to be passed and not AdsLoader.EventListener.
(Note: we are not creating a mediasource and calling `ImaAdsLoader.start(`, only passing the ImaAdsLoader into `DefaultMediaSourceFactory`)

**Comment by icbaker** [comment]
> @icbaker
> We have a custom seekbar that we use separately, and to populate the ad cue points, we are using the
> `adsManagerLoadedEvent.getAdsManager().getAdCuePoints()`

To get the cue points you should be able to implement [`Player.Listener#onTimelineChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onTimelineChanged(com.google.android.exoplayer2.Timeline,int))* and iterate through the [`Periods`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Period.html) of the timeline, using the `getAd___()` methods to identify ad periods and then extract the info you needed for your UI. You can look at how the ExoPlayer UI code does this here:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1027-L1048

*This is marked as deprecated but that's just meant to indicate you're supposed to implement `Player.Listener` instead of `Player.EventListener`.

--------

> Also, could you guide us on how to add the AdsLoader.EventListener into ImaAdsLoader?
> the builder.setAdEventListener() requires AdEvent.AdEventListener to be passed and not AdsLoader.EventListener.
> (Note: we are not creating a mediasource and calling `ImaAdsLoader.start(`, only passing the ImaAdsLoader into `DefaultMediaSourceFactory`)

You're right, that wasn't a good example. Do you still need to know this given the suggestion above for cue points? If so, can you again provide the context for what info from `AdsLoader.EventListener` you need.

**Comment by Debayudh** [comment]
@icbaker using onTimelineChanged works for getting the cue points.
Thank you for helping.
