### ISSUE TITLE
Setting Audio/Video name to TextView

### ISSUE THREAD

**Issue by VivekThummar52** [google/ExoPlayer#9107]
Hey there, i'm just started using exoplayer after very long time and i have one question, let me explain it to you:

we can use `exo_id's` for `button`, `seekbar` and some other controls like:

    <ImageButton android:id="@+id/exo_rew" />    //  default id
    <ImageButton android:id="@+id/exo_ffwd" />   //  default id
 and many more but i'm unable to find anything similar for showing file name to `TextView`, i tried to find solution in `Issue` section but there are too many closed issues to find the solution, so i'm asking this question, what basically i wan't to say is that if giving `default id's` to buttons works automatically(like we don't need `findViewById()` and `clickListeners`) is there any way that can automatically get `file title` from `filePath` and set it to `TextView`?

**Comment by icbaker** [comment]
What is `filePath` in this context? It sounds like something defined by your application rather than by ExoPlayer?

ExoPlayer identifies media with `MediaItem`, which has a `uri` field, but this might be e.g. an HTTP URL, or any other supported scheme.

I may be misunderstanding, but it sounds like you're basically asking to add a `TextView` to `PlayerView` with some custom content? If doing that requires changes to `PlayerView` then your best bet is probably to fork `PlayerView` and make the changes you need (see this comment for why we deliberately make our UI components relatively uncustomisable: https://github.com/google/ExoPlayer/issues/9072#issuecomment-863454293).

**Comment by VivekThummar52** [comment]
Sorry, it's my mistake because it's looks like it is almost impossible to do what i want but still i will ask you one more time(may be there will be any solution)..
Suppose i'm playing video from android device and there is some video at some location named `sample video.mp4`, then may be exoplayer can extract title `sample video` from it and then automatically title was set to the `textView` in which we want it to set by applying `defaultId` just same as applying id to buttons for `play\pause` which automatically handles button clicks and task..

and is there any way to prevent github from adding `needs triage` label automatically and  *sorry for trouble because my request is a little bit complicated..*

**Comment by icbaker** [comment]
ExoPlayer only identifies media by URI. In the case of a local file, that's something like `file:///sdcard/Download/my video.mp4`, and I can see how `my video` might be a useful value to extract from that.

However, the URI might be `https://long.cdn.domain.com/long-obscure-path/with-lots/of-numbers/837489379872395479823759/4738278.mpd?and=some&query=parameters#and-maybe-a-fragment`. In that case what should ExoPlayer show? It's quite likely the URI contains **no** information about what the title of the actual media being played is.

If we try and take "the last part of the path and remove the extension" (which is roughly the algorithm you're proposing I think) then we'd get `"4738278"` - not super informative :)

So that's why this feature request doesn't make sense in all the contexts that ExoPlayer is used. And the comment I linked above explains why we don't make changes to our UI components that only facilitate niche use-cases.

I'm going to close this because I don't think there's anything for ExoPlayer to do here.

----
> and is there any way to prevent github from adding `needs triage` label automatically

Don't worry about that, we use it to indentify which issues are waiting a response from the reporter (needs more info) vs from us (needs triage) - so when you replied the bot changes the labels to indicate I should look at the issue again.
