### ISSUE TITLE
Why is Exoplayer making multiple requests?

### ISSUE THREAD

**Issue by meyerhp** [google/ExoPlayer#9125]
My question is related to this issue: https://github.com/google/ExoPlayer/issues/6635

I understand that Exoplayer needs to make three requests due to the order of the boxes in the MP4 file, but why is it doing the same thing for Ogg? And is there a way to get around this issue similar to the solution provided for MP4 files:

> Note also that reordering the boxes in the MP4 so that the moov comes before the mdat also allows the player to play the file with a single request

Here is a sample API I used for testing
https://gist.github.com/meyerhp/66bb82bfd163a009a1836a91cc7ce1da
And I used a sample ogg file downloaded from [here](https://file-examples.com/index.php/sample-audio-files/sample-ogg-download/)

Android sample code
```
val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(this)
val mediaSource: MediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
            .createMediaSource(fromUri("http://192.168.101.248:8000"))
val player: SimpleExoPlayer = SimpleExoPlayer.Builder(this).build()
player.setMediaSource(mediaSource)
player.prepare()
player.play()
```

Using the Test API, I get the following output

1. First request: No range header - (Server returns 0 - 1000000)
2. Second request: Range: bytes=934694 - (Server returns 934694 - 1934694)
3. Third request: Range: bytes=4229- (Server returns 4229 - 1004229)

```
range requested:  0 - 1000000 
stream closed:  0 - 1000000
range requested:  934694 - 1934694
stream closed:  934694 - 1934694
range requested:  4229 - 1004229
stream closed:  4229 - 1004229
```

Tested on version `2.14.1` and `2.13.3`

Thanks

**Comment by kim-vde** [comment]
The extractor jumps to the end of the Ogg file to compute the duration. Indeed, the duration is computed based on the granule position of the last [page](https://en.wikipedia.org/wiki/Ogg) (see [DefaultOggSeeker](https://github.com/google/ExoPlayer/blob/r2.14.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ogg/DefaultOggSeeker.java)). I don’t think it is possible to do any differently because there is no duration metadata field in Ogg.
