### ISSUE TITLE
How to get new duration of a video after changing its speed?

### ISSUE THREAD

**Issue by ridanasif** [google/ExoPlayer#9134]
Hi. I know it's not an important question but is there any way that I can get the new total duration of a video after changing it's speed using the Playback Params? I think we could just get the duration by simply multiplying the original duration with the speed that we have passed in the playback params but this could be just arbitrary right? Is there any official way on how to do this? Any help would be appreciated. Regards.

**Comment by kim-vde** [comment]
What I would do is listen to [`onPlaybackParametersChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onPlaybackParametersChanged(com.google.android.exoplayer2.PlaybackParameters)) and compute the duration with `player.getDuration() / playbackParameters.speed`. It is best to use the listener instead of the setter because you will get notified of the actual speed if the requested speed cannot be set for some reason.

The speed adjustment is not always exact but should be quite precise so that you can rely on the computation mentioned above.

**Comment by ridanasif** [comment]
Thank you for the response. Will look onto that. But isn't onPlaybackParametersChanged Deprecated?

**Comment by kim-vde** [comment]
`Player.EventListener.onPlaybackParametersChanged` is deprecated because `Player.EventListener` is deprecated but `Player.Listener.onPlaybackParametersChanged` is not. This is not well reflected in the Javadoc. We will fix that in the next version.
