### ISSUE TITLE
Integrate External Widevine L3 Library to ExoPlayer

### ISSUE THREAD

**Issue by morganch01** [google/ExoPlayer#9137]
Issue content removed due to security reason

**Comment by icbaker** [comment]
If I understand correctly you're basically asking for the reverse of https://github.com/google/ExoPlayer/issues/2414 (and https://github.com/google/ExoPlayer/issues/4372).

They wanted to use the platform `MediaDrm` and an app-bundled video decoder, while you want to use an app-bundled DRM implementation and a platform decoder (`MediaCodec`).

I don't think you can do this easily because [`MediaCodec#configure`](https://developer.android.com/reference/android/media/MediaCodec#configure(android.media.MediaFormat,%20android.view.Surface,%20android.media.MediaCrypto,%20int)) takes a `MediaCrypto` instance which is tightly coupled to `android.media.MediaDrm`. Basically the `sessionId` is used by `MediaCodec` behind the scenes (inside the Android framework) to lookup the keys and decrypt the samples. This structure is designed to avoid the need for an application to ever have access to the decrypted media bytes, to ensure in the L1 case the bytes can stay on a secure hardware path from the Trusted Execution Environment to the screen.

I think your only option is to do the suggestion in https://github.com/google/ExoPlayer/issues/2414#issuecomment-279283583 and implement your own [`Renderer`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Renderer.html) that does both the decryption and decoding. It might be possible to do this by wrapping `MediaCodec{Audio,Video}Renderer` and doing the decryption before passing the decrypted buffers along to the inner renderer. This is probably pretty complicated and I'm afraid we won't be able to offer detailed support.

**Comment by morganch01** [comment]
@icbaker Thanks for the clarificatoin.

I checked #2414 and #4372, it seems their solution is based on Opus extension, which we may not needed. I assume it is still possible to do the override to the `MediaCodecAudioRenderer` and plug it into the ExoPlayer without those extra extension?

**Comment by icbaker** [comment]
You might be better off wrapping rather than extending/overriding.

e.g. you could access the input bytes from a `MediaCodecAdapter` that wraps a `SynchronousMediaCodecAdapter` - probably inside `queueInputBuffer`. We have a simple example of this pattern that we use for testing (we just record the bytes that are passed in, obviously you would need to do more):
https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/testutils/src/main/java/com/google/android/exoplayer2/testutil/CapturingRenderersFactory.java#L202-L210

**Comment by ronak2121** [comment]
Hi @icbaker,

Sone more questions we had on this matter:

1. will Exoplayer help us with manifest download/parse and asset muxing if we do the above? How does that work?
2. We understand the PSSH box is available under the DRMInitInfo, but when it’s time to decrypt audio, what kind of input would we get? Is it similar to an AVPacket that you’d get from FFmpeg? Can you point that out to us?
3. To do our own decryption, we’ll have to generate challenges, fetch licenses and all that..  so how will that work if we did that logic in the renderer?

**Comment by icbaker** [comment]
> 1. will Exoplayer help us with manifest download/parse and asset muxing if we do the above? How does that work?

If you're customising the renderer then ExoPlayer's existing components can handle everything before the `SampleQueue` in the diagram here:
https://exoplayer.dev/glossary.html#exoplayer. This includes handling manifest parsing and downloading the content for selected tracks. There will be a `SampleQueue` for each track being played, and each one will have its own `Renderer`.

> 2. We understand the PSSH box is available under the DRMInitInfo, but when it’s time to decrypt audio, what kind of input would we get? Is it similar to an AVPacket that you’d get from FFmpeg? Can you point that out to us?

Not sure I completely understand the question - but I think it shows my suggestion to implement a `MediaCodecAdapter` isn't enough because it doesn't give you access to the `Format` associated with the samples. You'll probably need to implement the whole `Renderer` interface. That will let you read `Format` objects from the `SampleQueue`. You might be able to adapt the existing `MediaCodec(Audio|Video)Renderer` implementations for your needs by forking them and making changes.

> 3. To do our own decryption, we’ll have to generate challenges, fetch licenses and all that..  so how will that work if we did that logic in the renderer?

I suggest you look at how `MediaCodec(Video|Audio)Renderer` interact with the framework DRM and replicate the same in your custom versions. You'll need some side-channel communication to replicate what's normally handled inside the DRM framework.

**Comment by morganch01** [comment]
Hi,

We've been following suggestion from @icbaker to customize MediaCodecAudioRenderer so that we can have access to the buffer, iv and keyId. So the basic flow and structure is like:
1) We implemented the ExoMediaDrm interface (say "CustomExoMediaDrm") -- for provisioning, license exchanging, and creating/closing session, it is backed by our own CDM; for createMediaCrypto() we are reusing the FrameworkMediaCrypto.
2) We are reusing the DefaultDrmSessionManager to manage the sessions from "CustomExoMediaDrm" -- we've set the custom factory to provide the "CustomExoMediaDrm".
3) Created a CustomAudioRenderer to which overrides the MediaCodecAudioRenderer, and currently only overriding the onInputFormatChanged() and onQueueInputBuffer(), so that we can get buffer, iv and keyId info. 
4) We've also created CustomMediaCodecAdapterWrapper which wraps the SynchronousMediaCodecAdapter, and overriding the queueInputBuffer() and queueSecureInputBuffer() methods. And we are planning to extract the data from buffer and then decypt it and put it back to the buffer, so that the underlying MediaCodec can decode the decrypted audio.

However, we are hitting the "android.media.MediaCodec$CodecException: Error 0x80000000" (same as https://github.com/google/ExoPlayer/issues/6141).

From documentation of "MediaDrm" (https://developer.android.com/reference/android/media/MediaDrm)

> Once the app has a sessionId, it can construct a MediaCrypto object from the UUID and sessionId. The MediaCrypto object is registered with the MediaCodec in the MediaCodec#configure method to enable the codec to decrypt content.

I am wondering whether in order to use "MediaCodec" from Android to decode the audio, I would have to use "MediaDrm" from Android altoghther? Would there be any work around if we don't use "MediaDrm" (using our own CDM), but still use "MediaCodec"? e.g. make the MediaCodec though our content is not Drm protected?

Appreciate for the insights.

**Comment by morganch01** [comment]
I think I just figure out to how to fix the "CodecException: Error 0x80000000". I just need to don't pass the "MediaCrypto" parameter to the "MediaCodec" configuration. 

Hitting other errors when try to queue the buffer, would provide follow up updates.

**Comment by morganch01** [comment]
Hi,

Following the above approach, I am reaching to a point that able to play the audio, but the audio is stuttering.


Observation:

From the log, I saw that after each time we called queueInputBuffer() with the decrypted buffer, we got the following decoder errors:

2021-08-11 14:28:00.627 1172-9898 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4006  // there are also 0x4002, 0x4004, 0x4007 error codes.
2021-08-11 14:28:00.627 1172-9898 W/C2SoftAacDec: AAC decoder returned error 0x4006, substituting silence


After queueing up couple buffers, e.g. after 9 queueInputBuffer() calls, we would got discontinuity error:

2021-08-11 14:28:01.078 5486-9855 E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 750608253, got 750376054
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:792)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1917)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)


But the playback doesn't fail with above errors, it just keep stuttering.


Implementation:


In the CustomAudioRenderer, we get the decryption informations from DecoderInputBuffer:

    override fun onQueueInputBuffer(buffer: DecoderInputBuffer) {
        val iv = buffer.cryptoInfo.iv
        val key = buffer.cryptoInfo.key
        decryptionInfoTracker.iv = iv
        decryptionInfoTracker.key = key
        decryptionInfoTracker.data = buffer.data
        super.onQueueInputBuffer(buffer)
    }


As mentioned above, we have CustomMediaCodecAdapterWrapper which wraps the SynchronousMediaCodecAdapter, and overriding the queueSecureInputBuffer() methods.
Inside the queueSecureInputBuffer(), we get the byte array from ByteBuffer, pass it to our own CDM to decrypt, and inserting the decrypted byte array back to the ByteBuffer.

    override fun queueSecureInputBuffer(
        index: Int,
        offset: Int,
        info: CryptoInfo,
        presentationTimeUs: Long,
        flags: Int
    ) {

        val l3Cdm = currentWidevineCdmHolder.widevineCdm
        val data = decryptionInfoTracker.data  

        // don't hold on to the buffer.
        decryptionInfoTracker.data = null
        if (data == null) {
            underlyingCodecAdapter.queueSecureInputBuffer(
                index,
                offset,
                info,
                presentationTimeUs,
                flags
            )
            return
        }


        val originalByteArray = ByteArray(data.limit())

        // read and copy content to a byte array
        data.get(originalByteArray)

        // clear the buffer after read, so that it is ready to write again.
        data.clear()

        val sessionId = l3Cdm?.currentSessionId
        val inBuffer = originalByteArray
        val iv = decryptionInfoTracker.iv
        val keyId = decryptionInfoTracker.key
        val newByteArray = if (sessionId != null && iv != null && keyId != null && l3Cdm != null) {

            l3Cdm.decrypt(sessionId, inBuffer, iv, keyId)
        } else {
           
            originalByteArray
        }

        data.put(newByteArray)
        data.limit(newByteArray.size)

        if (l3Cdm == null) {
            underlyingCodecAdapter.queueSecureInputBuffer(
                index,
                offset,
                info,
                presentationTimeUs,
                flags
            )
            return
        }

        underlyingCodecAdapter.queueInputBuffer(index, offset, data.limit(), presentationTimeUs, flags)
    }


The configuration passed the initialize the MediaCodec is with these information:

codecInfo = {MediaCodecInfo@52468} "c2.android.aac.decoder"
crypto = null
flags = 0
format = {Format@52448} "Format(1, null, null, audio/mp4a-latm, mp4a.40.2, 73000, und, [-1, -1, -1.0], [2, 22050])"
mediaFormat = {MediaFormat@52465} "{sample-rate=22050, mime=audio/mp4a-latm, channel-count=2, priority=0, csd-0=java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]}"
surface = null


Other research done:

I've check the MediaCodec official documentation and also some post, e.g. https://stackoverflow.com/questions/22332003/decoding-h264-bytestream-on-android . But couldn't quite figure out which part is already done by ExoPlayer and which part I need to custom by myself. e.g. Do I need to configure the BUFFER_FLAG_CODEC_CONFIG flag somewhere?

Appreciate for the help and any insight! And let me know if you need any more information.

**Comment by morganch01** [comment]
The above solution works and we are able to complete the custom widevine L3 integration to app. 
Thanks a lot for the suggestions and support.
Closing this ticket.
