### ISSUE TITLE
Some Dolby Vision videos do not play in ExoPlayer (while play in platform MediaPlayer)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9139]
Some Dolby Vision videos (`dvhe.05.09`, `dvhe.07.06`) do not play in ExoPlayer - audio plays but picture stays black. The same video files play fine in platform native MediaPlayer.

Such files are for example these from https://github.com/google/ExoPlayer/pull/7667#issuecomment-666641337, specifically:

- https://www.makemkv.com/download/dvtest/P5_Dolby_Amaze.mkv
- https://www.makemkv.com/download/dvtest/P7_FEL_GIJoe_The_Rise_of_Cobra.mkv
- https://www.makemkv.com/download/dvtest/P7_MEL_GIJoe_The_Rise_of_Cobra.mkv

All these 3 files do not play (picture) on OnePlus 7 (Android 10) in ExoPlayer (while work in MediaPlayer). I get the same results when testing these files on Xiaomi Mi Box S (Android TV 9).

- ExoPlayer version number: 2.14.1

Demo project (this is what I also used when capturing bugreports): https://github.com/moneytoo/ExoPlayerDemo/tree/players

Bugreports:

- MediaPlayer (P5_Dolby_Amaze): [bugreport-OnePlus7-QKQ1.190716.003-2021-07-01-21-00-49.zip](https://github.com/google/ExoPlayer/files/6750363/bugreport-OnePlus7-QKQ1.190716.003-2021-07-01-21-00-49.zip)
- ExoPlayer (P5_Dolby_Amaze): [bugreport-OnePlus7-QKQ1.190716.003-2021-07-01-21-05-19.zip](https://github.com/google/ExoPlayer/files/6750369/bugreport-OnePlus7-QKQ1.190716.003-2021-07-01-21-05-19.zip)

**Comment by kim-vde** [comment]
Profiles 5 and 7 are not mapped to HEVC (see [`MediaCodecVideoRenderer#getDecoderInfos`](https://github.com/google/ExoPlayer/blob/r2.14.1/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L378)) in ExoPlayer because:
- Profile 5 is not backward compatible (BL signal cross-compatibility ID is 0 in the specs).
- Profile 7 is deprecated. The backward compatibility information is present in the stream.

If I map the streams you provided to HEVC, then they play correctly, which is surprising for profile 5.

I'll see with the Dolby team if I can find out more and what we can do about that.

**Comment by kim-vde** [comment]
Update:

- Profile 5 is playing with an HEVC decoder but with the wrong colors. That's why its signal cross-compatibility ID is set to 0 in the specs (meaning it is compatible with no other format) and that's also the reason we don't map it to HEVC.
- As for profile 7, it is not easy to determine whether it is HEVC compatible in `MediaCodecVideoRenderer#getDecoderInfos` as it depends from one content to the other. As this profile is deprecated, we decided never to map it to HEVC for simplicity.

Things are therefore working as intended.

**Comment by moneytoo** [comment]
Thank you very much for your informative answer. Mapping profile 7 to HEVC works so it's really easy to enable if desired. Great!
