### ISSUE TITLE
How to pass exoplayer instance one activity to other activity

### ISSUE THREAD

**Issue by NG-Gaurav** [google/ExoPlayer#9140]
We have a two activity one for play video in portrait mode and other for landscape. on click full screen button video pass to  landscape activity and on back press portrait mode activity open. so how can use single player for both activity .

**Comment by ridanasif** [comment]
Use Fragments.

**Comment by kim-vde** [comment]
If you want to use an activity, there are multiple ways to share data between activities. [This link](https://stackoverflow.com/questions/4878159/whats-the-best-way-to-share-data-between-activities) explains the most common ones.

**Comment by gauravtyagi328** [comment]
https://drive.google.com/file/d/18aWqnZOl1ZVscdRV775SVsqxIMlhObla/view?usp=sharing
Please check this video. here video player is not rotating smoothly because we are using two activity. one for mini player and second for full player activity. so can we player rotating smoothly with two activity.

**Comment by ridanasif** [comment]
> https://drive.google.com/file/d/18aWqnZOl1ZVscdRV775SVsqxIMlhObla/view?usp=sharing
> Please check this video. here video player is not rotating smoothly because we are using two activity. one for mini player and second for full player activity. so can we player rotating smoothly with two activity.

As I mentioned above, It's better to use fragments in these specific cases. You are experiencing this delay because you are starting a new activity each time a user goes fullscreen, which could be a heavy process, depending on your activity code. What I suggest is that instead of creating an activity every time a user goes fullscreen, switch between fragments using a single exoplayer instance. This is much more memory efficient and you will notice little to no delay, providing a good user experience.
