### ISSUE TITLE
using SilenceMediaSource instead of content video

### ISSUE THREAD

**Issue by soheilnavvabi** [google/ExoPlayer#9145]
I need to show VAST ads without showing any video after that. I have already read [#7929](https://github.com/google/ExoPlayer/issues/7929) where it is suggested to use `silenceMediaSource`, so I have tried:

`player.setMediaItem(new SilenceMediaSource(1000000).getMediaItem().buildUpon().setAdTagUri(Uri.parse("...")).build());`

but again it throws exception and does not trigger `AD_COMPLETED` event. my goal is to show ad and then 1 second of silent video. what is the problem in my code? thanks.

**Comment by andrewlewis** [comment]
Please could you try switching to creating the `AdsMediaSource` directly and passing it using `player.setMediaSource` instead of using the `MediaItem`-based API? The `DefaultMediaSourceFactory` doesn't create `SilenceMediaSource` instances (and I suspect it's very rare that people will want that functionality).

**Comment by soheilnavvabi** [comment]
yes! I switched to `AdsMediaSource` and it worked like a charm! thanks.

`AdsMediaSource adsMediaSource = new AdsMediaSource(new SilenceMediaSource(1000000), new DataSpec(Uri.parse("...")), ID, new DefaultMediaSourceFactory(getContext()), adsLoader, playerView);`
