### ISSUE TITLE
ID3Reader does not read packet of ID3v2.4.0 properly. 

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#9155]
Hi, I have got a problem of rendering ID3 Tags when playing my hls contents.

`ID3Reader` does not read some ID3 v2.4.0 Frames , even though `ID3Decoder` support it.
By below code condition, ID3decoder cannot get data.

https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/Id3Reader.java#L119

I am sending ts files to `dev.exoplayer@gmail.com` 
Can you kindly check this?

Below are my environment. 

#### Test Information
- ExoPlayer version number
 r2.14.1
- Android version
All
- Android device
All

**Comment by kim-vde** [comment]
There is a problem in the ID3 data of the content provided. There is only one packet of type ID3. This packet has payload size 1135 while the ID3 data in the packet advertises a total size of 1143. The `Id3Reader` therefore doesn't output the sample metadata because `sampleBytesRead ` is 1135 and `sampleSize ` is 1143 on [this line](https://github.com/google/ExoPlayer/blob/r2.14.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/Id3Reader.java#L119). The `Id3Reader` is expecting more ID3 data but there is none.

Where does this content come from?

**Comment by HyowonHwang** [comment]
Thanks for your effort. We will try fix the content.
