### ISSUE TITLE
Play speed try to support 8x+

### ISSUE THREAD

**Issue by bookzhan** [google/ExoPlayer#9156]
I changed MAX_PLAYBACK_SPEED to 100, then set setPlaybackParameters(new PlaybackParameters(20), the silent video can be played normally, and the playback time is 1/20 of the original.  It can be played normally when only audio is played(E.g. wav, mp3,m4a),and the playback time is 1/20 of the original. But the maximum speed can only support 4 times when playing a video with sound. What is the reason?

**Comment by marcbaechinger** [comment]
In general there is a max playback speed set to 8.f in the `DefaultAudioSink.MAX_PLAYBACK_SPEED`. I think that is what you are referring to when you say you changed the value to 100. So if audio is enabled this is the upper limit for playback speed, and this actually seems sensible because playing a stream with more than 8 times unit speed with audio turned on doesn't make really a valuable use case (please see also #8413 around this topic).

Technically, when I change `DefaultAudioSink.MAX_PLAYBACK_SPEED` to 18 and then set the playback speed to 18 it plays this with that speed for a video with sound. So besides that I think that an upper speed limit of 8x with audio is a sensible upper limit, I can not reproduce your observation.

I recommend to switch off audio if you want to go over 8x.
