### ISSUE TITLE
Expected behavior when pre-caching?

### ISSUE THREAD

**Issue by gmbett** [google/ExoPlayer#9172]
Hi,

I'm looking into the possibility of pre-caching a video before it's played but it doesn't seems to work. Maybe I'm doing something wrong or my expectations are wrong.

I'm using version 2.14.1 and to pre-cache a video I'm doing:

```
val dataSpec = DataSpec.Builder().apply {
    setUri(videoUri)
    setKey(videoUri.toString())
}.build()

val cacheWriter = CacheWriter(
   ExoPlayerHelper.newCacheDataSource(applicationContext).createDataSource(),
   dataSpec,
   null //temporaryBuffer
   ) { ->
       // progressListener logic
     }

cacheWriter.cache()
```

In the above code, `videUri` is just the `URL` that points to the video.

`ExoPlayerHelper:`
```
internal object ExoPlayerHelper {

   /**
    * Builds a new [CacheDataSource.Factory].
    */
   fun newCacheDataSource(
      context: Context
   ): CacheDataSource.Factory {
      val directoryCache = getPlayerSimpleCache(context)

      return CacheDataSource.Factory().apply {
         setCache(directoryCache)
         setUpstreamDataSourceFactory(
            OkHttpDataSource.Factory(RestServiceFactory.getGeneralOkHttpClient()).apply {
               setCache(directoryCache)
               setUserAgent(NetworkUtils.getUserAgent())
          })
          setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
       }
   }

   private fun getPlayerSimpleCache(context: Context): SimpleCache {
      if (directoryCache == null) {
         val cacheDirectory = context.cacheDir

         val cacheSize = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val storageManager =
               context.getSystemService(Context.STORAGE_SERVICE) as StorageManager
            storageManager.getCacheQuotaBytes(storageManager.getUuidForPath(cacheDirectory))
            } else {
               DEFAULT_CACHE_DIR_SIZE_BYTES
            }

            directoryCache = SimpleCache(
               cacheDirectory,
               LeastRecentlyUsedCacheEvictor(cacheSize),
               ExoDatabaseProvider(context)
            )
      }
      return directoryCache!!
   }
}
```

To play later the video I'm doing:

```
   val ctx = requireActivity()
   val trackSelector = ExoPlayerHelper.newTrackSelector(ctx)

   // Player Initialization
   player = SimpleExoPlayer.Builder(
      ctx,
      ExoPlayerHelper.newRendersFactory(ctx)
   ).apply {
      setMediaSourceFactory(DefaultMediaSourceFactory(ExoPlayerHelper.newCacheDataSource(ctx)))
      setLoadControl(ExoPlayerHelper.newLoadControl())
      setTrackSelector(trackSelector)
   }.build().apply {
      addListener(ExoPlayerListener())
      setVideoTextureView(binding.videoTextureView)
      addAnalyticsListener(EventLogger(trackSelector))
   }

   val mediaSource = ExoPlayerHelper.newMediaSource(context = ctx, uri = videoUri)
   player.apply {
      setMediaSource(mediaSource, true)
      prepare()
      playWhenReady = true
   } 
```

What I see, is that `CacheWriter` successfully downloads all the video but when it's played later, I can still see that the player is buffering.

So what is the expected behavior? The player shouldn't enter the `BUFFERING` state if the video was completely pre-cached beforehand, right?

Moreover, is there a way to debug the cache logic? In the events that are logged by `EventLogger` I don't see anything related to cache. 

I see that `CacheWriter` uses a `DataSpec` with a key, but then how the player knows which key should be used?

Does `CacheWriter` always re-cache a video even if it was previously cached?

**Comment by marcbaechinger** [comment]
Let me answer your questions in arbitrary order :) 

> Does CacheWriter always re-cache a video even if it was previously cached?

The [JavaDoc of CacheWrite.cache says](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheWriter.java#L94) that any data that's already cached is skipped. Looking at the code also tells me this seems to be the case.

> I see that CacheWriter uses a DataSpec with a key, but then how the player knows which key should be used?

If you don't set a specific key, the [URI is used by default](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheKeyFactory.java#L25) similar to what you do. You can just leave this out in case your URI is stable and does not change on the server. Usually you only need to provide a custom key if the URI expires and needs to be changed after it has expired. I think in your case you can just not call `setKey()`.

If you set a custom key you need to provide it with `MediaItem.Builder.setCustomCacheKey(String customCacheKey)`. That should happen in your `ExoPlayerHelper.newMediaSource(context = ctx, uri = videoUri)` if you want this. 

> is there a way to debug the cache logic? 

I think the `CacheWriter.ProgressListener` gives you some limited insigths. You may want to wrap your upstream `DataSource` with a [`StatsDataSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/StatsDataSource.java). That's about it besides using a debugger and setting break points of course.

> The player shouldn't enter the BUFFERING state if the video was completely pre-cached beforehand, right?

I'd expect that you still see a `STATE_BUFFERING` but just very briefly. There is still a short moment when no data is available until data is available but it should be shorter then loading from the network. You will still see the `STATE_BUFFERING` in the logs for example.

To test whether the network is accesses I usually just put my device in airplane mode. If the player tries to access the network this will fail in airplane mode.

Aside: is there a `OkHttpDataSource.Factory.setCache(directoryCache)` method like you call it in your code? Or am I just confused due to my lack of Kotlin experience?

**Comment by gmbett** [comment]
Hi Marc,

Thanks for your answers.

I will check the key logic, because I still see many BUFFERING in the logs, so probably the player is just fetching everything again from the network.

>is there a OkHttpDataSource.Factory.setCache(directoryCache) method like you call it in your code? 

Yes, is here:
```
OkHttpDataSource.Factory(RestServiceFactory.getGeneralOkHttpClient()).apply {
               setCache(directoryCache)
               setUserAgent(NetworkUtils.getUserAgent())
          }
```

The `apply` function is just a way to call multiple methods on the same object, you can read it as:

```
val factorty = OkHttpDataSource.Factory(RestServiceFactory.getGeneralOkHttpClient())
factory.setCache(directoryCache)
factory.setUserAgent(NetworkUtils.getUserAgent())
```

**Comment by marcbaechinger** [comment]
If you still see problems please also post the code of 

```
ExoPlayerHelper.newMediaSource(context = ctx, uri = videoUri)
```

**Comment by gmbett** [comment]
Okay, just one more question... if the video is properly pre-cached, which value should return:

```
player.getBufferedPosition()
```

It should be already the full length of the video or that is not the case?

**Comment by marcbaechinger** [comment]
No, the loading behavior is the same like when it loads from the network. It loads piece by piece like the `LoadControl` tells. So I think by default it loads about 50 seconds ahead. Then stops loading until it needs more data.

**Comment by gmbett** [comment]
okay, thanks!
