### ISSUE TITLE
Audio mp3 duration equal to C.TIME_UNSET for some url

### ISSUE THREAD

**Issue by ralexey** [google/ExoPlayer#9178]
Hello.

I am working on app that plays Audio mp3 files using ExoPlayer.
App gets audio duration using `player.getDuration()`
App allows to play audio using URLs but it also allows to download audio before play.
For some URLs `play.getDuration()==C.TIME_UNSET` but for some URLs it returns correct value.
For downloaded files it returns correct value always.
I tried to add some URLs to the ExoPlayer demo app:
```
  {
    "name": "Demo",
    "samples": [
      {
        "name": "GOOD",
        "uri": "https://www.himmlisches-jerusalem.de/wp-content/uploads/media/audio/fellowships/2021/06/DEU/2021-06-27_Der Berg Zion und das himmlische Jerusalem (Hebr.12) (V2)-DEU.mp3"
      },
      {
        "name": "BAD",
        "uri": "https://www.himmlisches-jerusalem.de/wp-content/uploads/media/audio/fellowships/2021/06/DEU/2021-06-25_Getriebene silberne Posaunen immer einsatzbereit-DEU.mp3"
      }
    ]
  }
```
and modified `DebugTextViewHelper.java`:
```
  /** Returns a string containing audio debugging information. */
  protected String getAudioString() {
    Format format = player.getAudioFormat();
    DecoderCounters decoderCounters = player.getAudioDecoderCounters();
    if (format == null || decoderCounters == null) {
      return "";
    }
    return "\n"
        + format.sampleMimeType
        + "(id:"
        + format.id
        + " hz:"
        + format.sampleRate
        + " ch:"
        + format.channelCount
        + getDecoderCountersBufferCountString(decoderCounters)
        + " duration:"
        + player.getDuration()
        + ")";
  }
```
It shows correct duration for the GOOD url and `C.TIME_UNSET` for the BAD url.
I tried to use `release-v2` and `dev-v2` - no difference.
How can i get correct duration for any url?
(Looks like this is the same issue as #7314 but i can't comment that issue)

**Comment by tosam144** [comment]
Hi, is there progress on this issue? I have the same problem and would be happy to see a solution. Thanks!

**Comment by christosts** [comment]
The mp3 file labelled "BAD" is a constant bit-rate MP3 file for which ExoPlayer estimates the duration with the calculation `file size / bitrate`. For files transferred over the network, the size is determined by the HTTP response headers sent by the server. The demo app, by default, will use the Cronet HTTP data source, for which the server returns gzip compressed content, and ExoPlayer's CronetDataSource cannot determine the full length of the file. As a result, the duration of the file cannot be calculated.

The file labelled GOOD works because it contains additional metadata information with Xing headers that the player uses to get the duration. 

This can be solved in a few ways:
- The server does not send compressed data:
   - Use the DefaultHttpDatasource. For its default behavior, the server responses were not compresed; you can test this in the demo app by setting [DemoUtil.USE_CRONET_FOR_NETWORKING](https://github.com/google/ExoPlayer/blob/80332f7f1be7f0ea59440b4888560d228f405789/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L60) to false. 
    - Configure the CronetDataSource to instruct the server to not compress the returned data. I was able to do that in the demo app by adding the request header `Accept-Encoding: gzip;q=0,deflate;q=0`. There are APIs in `HttpDataSource` and `HttpDataSource.Factory` to set custom request headers. You can find more information on [Customizing server interactions](https://exoplayer.dev/customization.html#customizing-server-interactions) documentation page.
   - Transferring the data uncompressed means transferring more data, therefore there might be a performance penalty. However, media content is already compressed, I'm not sure if gzip really transfers less data. 
- Alternatively, ensure that all MP3 files used have metadata written like the one labelled GOOD. Note that Xing headers are not required to be present in an MP3 file. 
- Perhaps you can consider using a more streaming-friendly container, like MP4, which solves this issues by always containing related metadata.
