### ISSUE TITLE
Can HDMI Input be used as a source of media in ExoPlayer?

### ISSUE THREAD

**Issue by kaweesi** [google/ExoPlayer#9184]
I use exoplayer for broadcasting, i am wondering if it's possible to pickup HDMI sources to play in exoplayer ATM? this requires devices with HDMI input ports to receive the video content.

If this isn't supported i would wish to have this included in exoplayer

**Comment by Samrobbo** [comment]
My understanding of this is that HDMI ports on most android devices do not support receiving, only transmitting. However, in the event that you're working on a TV, then look into https://source.android.com/devices/tv, which might help.

I don't think this is possible to support as a result. 

Feel free to give more information and context, in case I'm misunderstanding the question.

**Comment by krocard** [comment]
ExoPlayer doesn't support playing from a recording source, neither the camera, the mic or an HDMI input. The main goal of ExoPlayer it to play content received from an asynchronous source.
Supporting this could be possible by implementing a custom data source, but will be very complex due to the very different constraints between ExoPlayer and a sync media source.

Playing an HDMI source would make much of ExoPlayer code useless or meaningless. For example, there would be no need for decoding, buffering and seeking would be meaningless...

I suspect the simplest way to implement this use case would be to implement a custom loopback in the app, without using ExoPlayer. Retrieve regularly new input frames and push them to the surface. Similarly capture audio and play it immediately.
