### ISSUE TITLE
Can ExoPlayer play gapless looping audio?

### ISSUE THREAD

**Issue by boywithk9** [google/ExoPlayer#920]
We have looping background sounds in our apps, and with the Android mediaplayer, there's a noticeable gap when the audio files loop. We've tried both m4a and ogg audios, but the gap is always there. Does ExoPlayer eliminate these gaps?

**Comment by andrewlewis** [comment]
There is currently no simple way to achieve this with ExoPlayer: for gapless playback it is necessary to read the relevant metadata from source, trim decoded audio samples from the start/end of the presentation based on the metadata and use the same Android AudioTrack instance across the transition from one source to the next. #497 tracks adding support for doing this.

(Note that the Android framework's MediaPlayer has a method [setNextMediaPlayer](http://developer.android.com/reference/android/media/MediaPlayer.html#setNextMediaPlayer(android.media.MediaPlayer)) which might work for your use case, but this is unrelated to ExoPlayer so we can't provide support here.)

**Comment by boywithk9** [comment]
Thanks for your reply. Just to be clear, this is for looping a single audio file, not sequential playback of multiple audio files. It seems like your reply might be based on a misunderstanding that it was for sequential audio files. Does that make a difference? It's hard to believe it's so difficult to prevent gaps in looped audio on Android. On iOS, it's automatic. 

Thanks

**Comment by andrewlewis** [comment]
I don't think it makes any difference. In the current design, you can implement looping by seeking back to the start of the stream when playback ends, but this won't be gapless because the player can't prepare what will be played next in advance. Also, we don't currently trim encoder delay/padding samples, which means the output will include silence at the start/end of playback for streams that use this.

For now, I'd probably just use MediaPlayer.setNextMediaPlayer. If you need to use ExoPlayer for some reason and you know that the input media does not use encoder delay and padding, it might be possible to implement gapless looping using a custom concatenating SampleSource specialized to your use case, perhaps using #1070 as a starting point.

**Comment by andrewlewis** [comment]
We now extract and apply gapless playback metadata (see #497). Playlist support in #1270 will make this easy to use (including for looping).

**Comment by Flyview** [comment]
Will the gapless support also work for video? Specifically looping the same
video without a gap.

**Comment by andrewlewis** [comment]
It's still work in progress, but I think video transitions should be seamless.

**Comment by dmota-systango** [comment]
You can use LoopingMediaSource as source instead.

MediaSource source = new ExtractorMediaSource(videoUri, ...);
// Loops the video indefinitely.
LoopingMediaSource loopingSource = new LoopingMediaSource(source);

Ref: https://google.github.io/ExoPlayer/guide.html#seamlessly-looping-a-video
