### ISSUE TITLE
Bug on video 50 fps FHD/SD

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [google/ExoPlayer#9217]
Hello, 

I don't know if I'm in the right place, so here's my problem, I have videos in 50 fps in full HD or SD and it lags all the time especially in streaming and iptv, the image freezes and resets immediately and as soon as an image goes too fast, it freezes. 

It's quite annoying, I have this problem on many applications that use the exoplayer such as Tivimate, XCIPTV, etc... I would like to know if it's possible to fix this bug for the next version of your exoplayer because it hurts my eyes. 

I have a good web connection, I have fiber at 400 mega and I am in rj45 in cat7 with a box amazon fire cube.

I thank you for your answers

Sincerely

Translated with www.DeepL.com/Translator (free version)

**Comment by marcbaechinger** [comment]
Thanks for reporting. Do you have some logs or similar from that device? It would also be interesting to know which version of ExoPlayer you are using like which version and whether you are using an ExoPlayer from this repository or the fork from Amazon. I don't have much experience with Amazon device in general and the fire cube in particular, but in case it is not properly working I'd try the fork and report to Amazon what you find.

If you send me a [bug report](https://developer.android.com/studio/debug/bug-report) I can look into the logs and see whether I find something that helps us some further. From the information available here in this issue it hard to say what the cause of the problem is besides that it may be a device specific issue for which Amazon would be best to help.

**Comment by TechComputerServiceDunkerque** [comment]
The problem is that only the dev of the application tivimate or xciptv has these logs... I'm a user of these versions which are downloadable on play store if you want to watch, my seller can even give you a 24h test so you can see where it bugs if you want of course, it's mostly the french channels in fhd 50 fps that lag all the time. On the other hand under vlc no worries if it can help with this detail. I also have the same problem with xiaomi Mi Box S.

Translated with www.DeepL.com/Translator (free version)

**Comment by marcbaechinger** [comment]
Can you please file a bug against the app so that they are aware of it? They can probably give you some info in case they know about the issue on these devices. If they think its an ExoPlayer issue they certainly can file a bug here with the required information, so it becomes actionable for us. We can't give user support for apps I'm afraid.

**Comment by TechComputerServiceDunkerque** [comment]
I tried to do this on Thursday, he said he does not see the problem while we are several to complain on the subject on several forums for many other applications iptv, same problem found, just with channels in 50 fps, 25 fps, 30 fps, no problem found ... That's why I came to you to try to solve the problem because it's impossible to be heard by the developer of the applications that use your player.

Translated with www.DeepL.com/Translator (free version)

**Comment by TechComputerServiceDunkerque** [comment]
> Can you please file a bug against the app so that they are aware of it? They can probably give you some info in case they know about the issue on these devices. If they think its an ExoPlayer issue they certainly can file a bug here with the required information, so it becomes actionable for us. We can't give user support for apps I'm afraid.



> Can you please file a bug against the app so that they are aware of it? They can probably give you some info in case they know about the issue on these devices. If they think its an ExoPlayer issue they certainly can file a bug here with the required information, so it becomes actionable for us. We can't give user support for apps I'm afraid.

Hello, according to some developer, I am told to tell you that this comes from the h265 codec (1920x1080) 50FPS of exoplayer which has a slow decoder. In h264 format, no problem though. Do you think you know where the problem comes from because at vlc no problem with the h265 codec.
