### ISSUE TITLE
Caching Policy

### ISSUE THREAD

**Issue by jpark58** [google/ExoPlayer#9235]
Hello!

I was just wondering what is the best or recommended caching policy with exoplayer?

https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6

Of course, I check above blog post. But, can you recommend how to manage caches? like how much chunk to be cached or how many seconds to be cached. I know this is pretty much up to the developer. But, I am having troubles finding references for such cases.

Thank you in advance

**Comment by marcbaechinger** [comment]
I think this is a question that can't be generally answered easily because it depends on configurable variables and the media. 

The use case is to preload some data so that when the user skips to a given window the player can immediately start playing without buffering. 

Assuming you are using the `DefaultLoadControl`. The `DefaultLoadControl.Builder` has a method `setBufferDurationMs` that has four parameters that affect the buffering behavior. If you use the default configuration `bufferForPlaybackMs` is set to `DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS` which is 2500 ms. 

So if you pre-cache you want at least pre-cache more than 2500ms of media to avoid that the player needs to download media before playback. You probably want to pre-cache significantly more than that to make sure the buffer is not depleted quickly for users with a slow connection, but `bufferForPlaybackMs` is the lower minimum bound to avoid downloading from the network for initial playback of a stream.

You notice that this value is a duration in ms and accordingly you need to figure out how much data in bytes this is for any given media for which you pre-cache. So the number of bytes is obviously different for an MP3 than for an HD video.
