### ISSUE TITLE
Add the ability to download a stream based on the bandwidth

### ISSUE THREAD

**Issue by romainpiel** [google/ExoPlayer#9236]
### [REQUIRED] Use case description
When downloading a stream using `DownloadHelper`, the default behaviour is to download the highest supported bitrate. While this is fine, it defeats a bit the point of using HLS or DASH. It would be great if it behaved like when streaming (ie. download the best stream for the current device bandwidth).

### Proposed solution
I had a look under the hood and the track selector is [initialised with a fake bandwidth meter](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L494). Could we potentially switch to the `DefaultBandwidthMeter` as we do when streaming?

### Alternatives considered
Alternatively, can the track selector get exposed by the download helper? That would give the users of the library more control on this sort of issues.

Thanks a lot! 🙏

**Comment by christosts** [comment]
Have you checked the methods supported already by the [DownloadHelper](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadHelper.html)? You may pass `DefaultTrackSelector.Parameters` in several methods in order to tune the track selection. I believe these give the flexibility already, either upfront or after the manifest is obtained (see the [demo app code](https://github.com/google/ExoPlayer/blob/r2.14.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L247-L265) for the 2nd use case).

If the existing APIs do not work for your use-case, can you please describe your use-case in more detail?

By passing a real bandwidth meter, I assume you mean adapting to the real network conditions, however that would mean downloading different chunks at different resolutions/bitrates. Adapting to network conditions is desired when streaming video on-demand (=> downloading and watching the content at the same time. I want to avoid using the term "real-time" to avoid confusion). However, when watching content offline you don't expect the video to change resolutions because at the time when the download happened (in the past) the network throughput was oscillating. 

For example, let's say I kick-off a download while at home to watch later, e.g. in the subway or in a plane. There are no time constraints for the download speed to match the playback speed since I'm not watching the content in parallel to downloading it, therefore I don't really need the video to be adaptive.

**Comment by romainpiel** [comment]
Thanks for the quick reply @christosts 🙌  

Unfortunately, the `DefaultTrackSelector.Parameters` are not dynamic enough for my use-case. They allow to download a specific bitrate, or for a specific screen size but I'd like it to go a bit further by choosing the best bitrate for the current connectivity.

My use-case is as follow: I have a screen with several videos, one playing after the other. When opening the screen, I'd like the ability to prefetch the next videos while streaming the first one. That way if the user skips to the next video, the loading time is hopefully shorter. I managed to do that by using a shared cache between the `ExoPlayerView` and the `DownloadHelper`.
The issue I'm finding though is that if the device is not on the best connectivity, we'll be downloading the best quality of the video while we want to stream a lower quality. I could potentially make sure the track selector used when streaming and the one used when downloading are aligned but that doesn't sound ideal. It would be even cleaner if there was some sort of setting (to `DownloadHelper` or `DefaultTrackSelector.Parameters`) to download the best quality for the current bandwidth.

**Comment by christosts** [comment]
An idea:

If you follow the [link from the demo app](https://github.com/google/ExoPlayer/blob/r2.14.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L247-L265) I shared above, this is the piece of code in the demo app to manually select tracks after the manifest is downloaded. There are APIs in the  DownloadHelper to help you set the track after the manifest is downloaded.

On your application, you may create a `DefaultBandwidthMeter` instance yourself and pass it to the player, therefore you will have access to the player's bandwidth estimate. When the manifest is fetched, you can consult with the `DefaultBandwidthMeter` on what is the current estimated bandwidth throughput and select tracks accordingly. 

Would that help you?

**Comment by romainpiel** [comment]
Ah right, yes that makes sense 👍  I guess I'd need to do a bit of plumbing to make that work. Thanks for your help! Feel free to close this ticket if you feel like it doesn't make sense to add that to the library.

**Comment by christosts** [comment]
I'll close the issue for now but feel free to re-open if you try out the idea and does not work for your app as expected.

Note that:
- the download will still fetch a single resolution/bitrate
- you should tune how much of the reported bandwidth throughput can be used, e.g. might have to tune it of the player does other downloads in parallel, and ~definitely~ maybe pick tracks whose bitrate as slightly less than the reported available bandwidth.
