### ISSUE TITLE
Ad tag retrieval unblocking

### ISSUE THREAD

**Issue by danish241194** [google/ExoPlayer#9237]
Currently if we add an AdTag Uri and Content Uri and then prepare and play as shown below
```
MediaItem firstItem =
    new MediaItem.Builder()
        .setUri(firstVideoUri)
        .setAdTagUri(adTagUri)
        .build();

player.addMediaItem(firstItem);
player.prepare();
player.play()
```
(using IMA)

player doesn't play content till ads are fetched, In my case i don't want player to wait for Ads as it increases ( time to display first frame) .Is there any way i can achieve this.

**Comment by marcbaechinger** [comment]
I think if you are using an `adTagUri`, the ad tag from that URI is fetched first to check what ads are to be inserted. If there is a preroll ad, then the ad is loaded and played first. If there is no preroll add the ad media will be loaded as soon as it is required.

Can you give us some more details on what is in that ad tag and whether there is a pre-roll involved? Do you see that ExoPlayer is waiting for ad media that is not playing as pre-roll? You can also post the URI to the ad tag for inspection if you want.

**Comment by marcbaechinger** [comment]
Another note: If this is about a case where the ad tag is not properly loading, you [can set a timeout](https://github.com/google/ExoPlayer/blob/002ee4d/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L279).

**Comment by danish241194** [comment]
@marcbaechinger thanks for your response , As per your comment " the ad tag from that URI is fetched first to check what ads are to be inserted " here we don't want it to fetch it in the beginning as we are always having mid roll ads. Can we control this ad Tag fetch call , i mean to can we do it like fetch at some particular second of video content.

**Comment by marcbaechinger** [comment]
I don't think this is possible. The ad tag is always loaded first.

**Comment by andrewlewis** [comment]
Not sure if this is helpful, but there is a way to "preload" the ad tag independently of starting playback, see [`ImaAdsLoader.requestAds`](https://github.com/google/ExoPlayer/blob/002ee4d/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java). Maybe you can preload the ad tag before starting playback as a workaround.

**Comment by danish241194** [comment]
@marcbaechinger Are ads tag url and content url calls getting fired simultaneously ?

**Comment by andrewlewis** [comment]
`AdsMediaSource` prepares the content `MediaSource` at the same time as requesting the ad tag. However, the content media period isn't created until the ad tag has loaded, because media periods are always created in order and we don't whether we need to create a media period for a preroll ad until the ad tag has loaded. So if the content is progressive (like an MP4), it won't actually start loading until the ad tag has loaded. #4727 tracks being able start loading progressive content in `prepareSource` rather than at the point of creating the media period.

In the short term, I'd recommend either pre-requesting the ad tag (if there is a suitable point before starting playback when you know you'll need the ads) or alternatively splitting the content into two clips where the first clip is just content (with no ad tag URI) and the second clip has the ad tag URI. The ad tag will be preloaded before playback reaches the second clip. To make the transition seamless, the second clip needs to start on a keyframe.

**Comment by danish241194** [comment]
thanks @andrewlewis , wondering if we already have ad tag url's response (VAST)  as string , can we pass this thing directly to player so that it can directly use it and  doesn't have to fetch this same response from ad tag url.

**Comment by andrewlewis** [comment]
Yes, although it requires everything to be part of the ad tag (you can't have a VMAP ad tag that points to other ad tags). It should work to build a `data:` scheme URI and pass that as the ad tag URI -- see [this documentation](https://github.com/google/ExoPlayer/blob/d0dd33e/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L72-L79).
