### ISSUE TITLE
Wrong duration read from mp3 file

### ISSUE THREAD

**Issue by gemiren** [google/ExoPlayer#9238]
The mp3 file linked here https://media.blubrry.com/melhoresdomundo/ia601509.us.archive.org/30/items/mdm600/mdm600.mp3 has duration 28:06:00. When played with ExoPlayer it returns duration 2:37:41. Is there a way to get the full duration?

- ExoPlayer version number: 2.11.8
- Android version: Android 11
- Android device: Pixel 3

**Comment by christosts** [comment]
I tested with r.2.14.2. I can verify that ExoPlayer returns a duration of 2:37:41. When I inspect the file with `mediainfo` or try to play with VLC, the returned duration is 28:06:00.

According to `mediainfo` the file is constant-bit-rate, encoded at 64Kbps and the size of the file is 772MB. I suspect the duration in VLC and `mediainfo` matches the calculation `file_size / bitrate`. ExoPlayer however calculates the duration from a  Xing header found in the file.

@kim-vde I see that for this particular file, the duration is based on the calculations of Mp3Extractor.maybeReadSeekFrame(). Can you please take a look? Maybe the headers set in the file are not accurate (bad media encoding?) or perhaps there is something to look in the extractor.

Note: when I play the file over VLC (_locally and over the network_) and try to seek past the first 2 hours, playback is distorted. So at the moment, I'm more inclined on the media not being encoded properly.

**Comment by kim-vde** [comment]
ExoPlayer computes the duration from the Xing header ([code](https://github.com/google/ExoPlayer/blob/r2.15.0/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp3/Mp3Extractor.java#L415)) and this duration (2:37:41) doesn't match the one computed from the assumption that your content has constant bitrate (28:06:00, which is computed from the file size and the bitrate, as @christosts mentioned).

- If your content has constant bitrate, then you should remove the Xing header because seeking does not require it.
- If your content has variable bitrate, then you should fix the Xing header (if incorrect) to indicate correct values (or use another way of providing a seek table like a VBRI header or MLLT table).

For your information, the following information is used in ExoPlayer to compute the duration from the Xing header:
- The frame count, which has a value of 262 815 and is retrieved from the Xing header,
- The number of samples per frame, which has a value of 576 and is retrieved from the first MPEG audio header,
- The number of samples per seconds, which has a value of 16 000 and is also retrieved from the first MPEG audio header.

Are you sure that the duration of 28:06:00 is the correct one?
