### ISSUE TITLE
OfflineLicenseHelper.getLicenseDurationRemainingSec is too slow

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#9265]
exoplayerVersion = '2.14.2'
  
  Device: SM-G935FD
  
  I need to get downloads list with licenses and their times (DurationRemaining) so I do this:
```
  val downloads = downloadManager.downloadIndex.getDownloads(Download.STATE_COMPLETED)
     val list = (0 until downloads.count)
            .map { index ->
                downloads.moveToPosition(index)
               val download =  downloads.download
                  val start = System.currentTimeMillis()
    val licenseDurationRemainingSec = offlineLicenseHelper.getLicenseDurationRemainingSec(download.request.data)
    Log.e("OfflineLicenseHelper", "getLicenseDurationRemainingSec: ${System.currentTimeMillis() - start} ")
   
 Pair(download,licenseDurationRemainingSec)
            }
```
    
Log:

```
E/OfflineLicenseHelper: getLicenseDurationRemainingSec: 603 
E/OfflineLicenseHelper: getLicenseDurationRemainingSec: 565 
E/OfflineLicenseHelper: getLicenseDurationRemainingSec: 541 
```

~550ms for each item 

Why `com.google.android.exoplayer2.drm.OfflineLicenseHelper#getLicenseDurationRemainingSec` is so long process? 
Maybe exist any faster method to get all downloads with their licenses DurationRemaining?

**Comment by icbaker** [comment]
I experimented with this on a Pixel 5. I found `getLicenseDurationRemainingSec` was generally taking ~300ms, which, although faster than what you're seeing, still seems quite slow.

I added some logging in `DefaultDrmSession` and found there's a couple of major contributors to this slowness:
* [`android.os.MediaDrm#openSession`](https://developer.android.com/reference/android/media/MediaDrm#openSession()) (~200ms)
* [`android.os.MediaDrm#restoreKeys`](https://developer.android.com/reference/android/media/MediaDrm#restoreKeys(byte[],%20byte[])) (~100ms)

I remembered from a previous issue that `MediaDrm#openSession` is **much** slower when it's a 'new' `MediaDrm` instance (https://github.com/google/ExoPlayer/issues/8892#issuecomment-841321291). So I experimented with making `OfflineLicenseHelper` use the same underlying `MediaDrm` instance - this is possible but a little tricky:
1. Construct your `DefaultDrmSessionManager` manually. You must disable session keep-alive by setting [`sessionKeepAliveMs`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.Builder.html#setSessionKeepaliveMs(long)) to `C.TIME_UNSET`. This also only works if all your items have the same DRM properties (e.g. `defaultLicenseUrl`).
2. Manually call `DefaultDrmSessionManager#prepare()` once (you also need to make sure to call `release()` when you're done).
3. Pass your `DefaultDrmSessionManager` to the [`OfflineLicenseHelper` constructor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html#%3Cinit%3E(com.google.android.exoplayer2.drm.DefaultDrmSessionManager,com.google.android.exoplayer2.drm.DrmSessionEventListener.EventDispatcher)).

This works because it prevents the internal reference count of `DefaultDrmSessionManager` from ever dropping to zero (which means it never releases its internal `MediaDrm` instance).

I found that did speed up the `MediaDrm#openSession` calls a bit (more like ~100ms instead of ~200ms) - but not as much as my anecdotal tests in the other issue would suggest.

------

I think it's likely that `OfflineLicenseHelper#getLicenseDurationRemainingSec` will always be pretty slow - it works by interacting with the DRM framework, which on most devices involves calls down into a Trusted Execution Environment (TEE). This slowness is somewhat outside ExoPlayer's control(as an app-level library). You might be better off rejigging your code to avoid needing to call it as frequently? Maybe you could cache the expiration time somewhere.

Aside: I noticed you seem to be using `DownloadRequest.data` to store the `keySetId`, but I think you should probably use `DownloadRequest.keySetId` for this.

**Comment by Kolyall** [comment]
1. "Maybe you could cache the expiration time somewhere." 
Why exoplayer lib doesn't do that to avoid calling TEE every time for each cached element in DownloadManager? Just store LicenseDurationRemaining with success downloaded item.

**Comment by Kolyall** [comment]
2. "Aside: I noticed you seem to be using DownloadRequest.data to store the keySetId, but I think you should probably use DownloadRequest.keySetId for this."
`keySetId` is `null`
![Screenshot from 2021-08-09 09-59-45](https://user-images.githubusercontent.com/3495165/128670198-79a4d372-b7c4-4966-80dd-4109134d010e.png)

**Comment by Kolyall** [comment]
3. `setSessionKeepaliveMs(C.TIME_UNSET)` no affect , The same result ~470-530ms for each item :
```
ksid3C131721, time: 476ms
ksid5A6D9D3F, time: 475ms
ksid981B3CD5, time: 506ms
ksidC218137B, time: 490ms
ksidD09C448C, time: 472ms
ksidFA2876F4, time: 497ms
ksidF358949E, time: 480ms
ksid26775E49, time: 472ms
ksid31734EE3, time: 505ms
ksid6C36641E, time: 525ms
ksid22A8B78C, time: 484ms
ksidF9E41A86, time: 475ms
ksidC3D0444F, time: 465ms
ksid2E1ADF13, time: 481ms
ksidE4CB02F5, time: 499ms
ksid45707F6B, time: 500ms
ksidF40B510D, time: 478ms
```

**Comment by Kolyall** [comment]
@icbaker could you please answer for detailed questions?

**Comment by icbaker** [comment]
>> Maybe you could cache the expiration time somewhere.
>
> Why exoplayer lib doesn't do that to avoid calling TEE every time for each cached element in DownloadManager? Just store LicenseDurationRemaining with success downloaded item.

The license may be renewed without DownloadManager being aware. If we cached this value it would be hard/impossible to ensure it always remained correct/fresh. As an app you have more context about your license behaviour & refresh logic, so you're more likely to be able to cache it correctly.

-----

>> Aside: I noticed you seem to be using `DownloadRequest.data` to store the `keySetId`, but I think you should probably use `DownloadRequest.keySetId` for this.
>
> `keySetId` is `null`

The app is responsible for setting the fields in `DownloadRequest`, so if the keySetId is ending up in the `data` field it's because the app is putting it there, not ExoPlayer.

-----

> `setSessionKeepaliveMs(C.TIME_UNSET)` no affect , The same result ~470-530ms for each item :

There isn't enough information here to understand if you've correctly implemented all the steps in my suggestion (as I said, it's tricky). If you want me to take a closer look please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Given the expected speed-up isn't transformational it may not be worth pursuing this approach (vs the caching approach).

**Comment by Kolyall** [comment]
@icbaker 
4. Why when the method `OfflineLicenseHelper#getLicenseDurationRemainingSec` is called then music playback lags?

**Comment by icbaker** [comment]
There isn't enough information to understand exactly what behaviour you're seeing and try and understand why it might be happening. Please provide a minimal reproducible example (details above).
