### ISSUE TITLE
On Android 10 users can swipe to remove MediaStyle notification

### ISSUE THREAD

**Issue by Colaman0** [google/ExoPlayer#9275]
I use the PlayerNotificationManager to create notification and call startForeground, if the notification bar is not fully expanded, I can swipe to remove the notification, 
but when i expanded notification such as show the seekbar,  i can't  swipe to remove.

is seem like i can't use MediaStyle and set MediaSession at the same time

This is the problem I found on Android 10.

**Comment by marcbaechinger** [comment]
Are you sure you are seeing this on Android 10? I'm a bit confused, because I see this behavior on Android 11 (API 30) and greater only if I'm not mistaken. However, I think the behavior is working as intended and caused by a change how the framework handles media style notification with media session tokens. 

Since Android 11 (API 30) the framework creates a carousel with a mini player in the notification drawer for each app that has a media style notification with a media session. This is most obvious when you start a second audio app like Spotify or YouTube Music. If this is the case there are multiple mini players side by side in the carousel. If you swipe left or right it shows the player for one or the other app (there are two little dots at the botto of the mini player that show that there are two mini players).

![image](https://user-images.githubusercontent.com/584321/129939892-cc037083-adb7-4ab5-a1c7-9f0889e9285c.png)

In the minimized view, the user can swipe away the mini player. They are not stopped though. When you enlarge the notification drawer they are still there in the larger version that includes the seekbar:

![image](https://user-images.githubusercontent.com/584321/129940518-59e0ddc5-fb62-4393-b805-14b78c698c89.png)

In this larger view mode the user can not swipe away the mini players. 

Your observation is correct, that this behavior only applies to notifications that have the media session token set. If the token is not set, the notification only shows as a normal notification (not as a mini player in the carousel). In this case the notification can be swiped away when the notification is not attached to a foreground service (like for instance when the player is paused `stopForeground()` should be called to enable this).

**Comment by Colaman0** [comment]
Thanks for your answer , The notification does run as you said
