### ISSUE TITLE
ExoPlayer doesn't respect the specific profile of the HEVC codec

### ISSUE THREAD

**Issue by brozikcz** [google/ExoPlayer#9277]
It seems to be broken the detection of the current format with these changes in this ticket #8393 https://github.com/google/ExoPlayer/blob/80332f7f1be7f0ea59440b4888560d228f405789/library/common/src/main/java/com/google/android/exoplayer2/util/CodecSpecificDataUtil.java#L114
The detection worked well in 2.12.* but doesn't work in 2.14.* version.

The issue is the video with the hev1 profile is detected as hvc1.

current videoFormat:
```
Format(video_1=1473000, null, video/mp4, video/hevc, hvc1.1.6.L120.90, 1473000, null, [1280, 720, 25.0], [-1, -1])
```
the same profile parsed from manifest: 
```
Format(video_1=1473000, null, video/mp4, video/hevc, hev1.1.6.L120.90, 1473000, null, [1280, 720, 25.0], [-1, -1])
```

ffprobe output:
```
  Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], 25 tbr, 600 tbn, 25 tbc (default)
    Metadata:
      handler_name    : USP Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : HEVC Coding
```

**Comment by claincly** [comment]
I am not sure if I understand correctly.

Are you playing HLS/DASH or a local file? I don't understand what "current format" means. please clarify, thanks!

**Comment by brozikcz** [comment]
Eh, sorry.

Yes, we use the DASH for streaming and the issue is the wrong detection profile from HEVC bitstream because the detection has a hardcoded `hvc1` profile and we use the `hev1`.

`SimpleExoPlayer.getVideoFormat()` returns wrong `codec` in `Format` object because the information of codec is extracted from bitstream / chunk but the `SimpleExoPlayer.currentTrackSelections.all()` returns right codec in `Format` because the information is parsed from the manifest.

**Comment by ojw28** [comment]
Am I right in thinking that this is purely a reporting issue? In other words, playback and all player functionality works fine, and the only thing that's wrong is that the `Format.codec` field is set to `hvc1.1.6.L120.90` when you expect it to be set to `hev1.1.6.L120.90`?

If it is just a reporting issue, could you clarify why this is important to you? My understanding is that they're essentially identical except for where SPS/PPS is placed in the container. It's unclear why the difference between the two would be important to application code.

**Comment by brozikcz** [comment]
I'm not sure how much it's important. The original ticket https://github.com/google/ExoPlayer/issues/8393#issuecomment-750320522 says something of the wrong detection of format and then the player shows "black screen or distorted image".

And the next thing is adaptive video selections and I'm not sure if the switching is compared just with `mimeType` or using the `codec` for the detection of the same type.

**Comment by ojw28** [comment]
Unless you're seeing an actual playback issue that you know is caused by this, I think we can close this as a known quirk. If you are seeing an actual issue, it should be easy to validate whether this is the true root cause simply by changing the hardcoded value and seeing if it resolves any issue that you're seeing. If it does, please provide concrete reproduction steps here. Alternatively, if you're seeing an issue that's not resolved by changing the hardcoded value, please file a new issue since this will not be the root cause. Alternatively, if you're not seeing a playback issue at all, then I don't think anything needs to be done.

Regarding where the value is hardcoded: I don't think it's possible to do anything better inside `buildHevcCodecStringFromSps`, because I think the SPS data looks identical in both cases. We could plumb the "correct value" down from higher up, but it doesn't seem worth it unless it's causing an issue.
