### ISSUE TITLE
How to  delete simplecache safely?

### ISSUE THREAD

**Issue by jpark58** [google/ExoPlayer#9280]
Thank you in advance.
I always appreciate help from this community. 

I was just wondering what would be the most safe way to delete an instance of SimpleCache?
What I am trying to implement is to delete all cached contents before the app is destroyed. 

I called `SimpleCache.delete(dir, exoDatabaseProvider)` in `onDestroy()`. I know the `onDestroy()` is not always called.(Please let me know if you have a suggestion about when to call the `SimpleCache.delete()`)

Opening the Device File Explorer in Android Studio, I see that the whole cache file directory has been deleted. 

But the problem is when I reopen the app. The error message shows that there must be some errors when deleting the instance of simplecache. How do I resolve this problem?
```
E/SQLiteLog: (1) no such table: ExoPlayerCacheIndex4829447483381d6b in "DELETE FROM ExoPlayerCacheIndex4829447483381d6b WHERE id = ?"
```

In `onCreate()`, the app starts caching. So, the app has to cache new data every time user opens the app and any old cached data must be deleted before the app starts. 

Thank you!

**Comment by ojw28** [comment]
There is no hook for executing code when your app is about to be destroyed. Note also that `Activity.onDestroy` is called when a single activity is destroyed, not when your app process is destroyed.

That aside, using `SimpleCache.delete` is the correct way to delete the content that may have been persisted by a `SimpleCache`. When you call this method, you should ensure that you don't hold a reference to the `SimpleCache` instance being deleted, and that you've called `SimpleCache.release` on any instance that you did have.

I think the error message is most likely because you're holding a reference to the `SimpleCache` instance that you've deleted, which you then try to do something with.
