### ISSUE TITLE
setHandleAudioBecomingNoisy(true) regression in 2.15.0

### ISSUE THREAD

**Issue by fourofspades** [google/ExoPlayer#9290]
Updated exoplayer to 2.15.0 and noticed audio continued to play when Bluetooth device disconnects.

Is this a know regression, or is there some code I need to change?

**Comment by claincly** [comment]
@krocard Will this be related to the recent audio buffer change?

**Comment by krocard** [comment]
@claincly I'm not sure which audio buffer change you are referencing. The one I mentioned yesterday is far from merged.
To @Samrobbo who implemented the audio becoming noisy. Has there been any changes in 2.15.0?

**Comment by Samrobbo** [comment]
There hasn't been any changes to audio becoming noisy since implementation, based on the history of the `AudioBecomingNoisyManager`. 

@fourofspades Can we get some more information on your usecase? Ideally filling out as much of the issue template as you can, which is found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). 

If you're unable to share bug reports publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by fourofspades** [comment]
Just done some more testing, and it's working now.  Will monitor the issue
and report back. It may have been a one off, or I managed to click play
with phone on my pocket somehow.
