### ISSUE TITLE
Explayer and wakelock

### ISSUE THREAD

**Issue by diabloo** [google/ExoPlayer#930]
hi, 
I hava a question I use exoplayer for online audio streaming and i see by testing and this without aquiring wakelock and wifilock that the player   keeps playing for more than 20 min without touching the phone . does this mean that i dont need wakelock and wifilock when i use exoplayer

ps: tested on LG G2 (4.4.2)

**Comment by andrewlewis** [comment]
ExoPlayer does not acquire a WakeLock or WifiLock directly, but MediaCodecAudioTrackRenderer uses an AudioTrack which should keep the device awake while audio is playing (and for a few seconds after audio playback stops). If audio playback was continuous that might explain why the device stayed awake with the screen off.

However, the device can sleep if audio playback is interrupted and it is not being kept awake by a WakeLock. This could happen if the player runs out of data and needs to rebuffer from the network, for example. So streaming apps that play audio when the screen is off should acquire a WakeLock and WifiLock during playback. It is important to release the locks if/when playback is finished so that the device can sleep.

**Comment by diabloo** [comment]
Thank your for this clear answer
