### ISSUE TITLE
Video & Audio out of sync #intermittently

### ISSUE THREAD

**Issue by ashishgupta2510** [google/ExoPlayer#9301]
We intermittently get the video & Audio out of sync issue while playing the long live streams. While the audio keeps playing but video gets frozen for few seconds then it starts playing again from the next segment. This issue is very intermittent and hard to reproduce. We checked few of the threads on the same kind of issues [#4559](https://github.com/google/ExoPlayer/issues/4559) & [#3829](https://github.com/google/ExoPlayer/issues/3829). Could you please confirm if any fix was sent for above issues, if yes then please confirm the version. Also could you please confirm if any other open thread is going on for the similar issue.

- ExoPlayer version number :- 2.11.5
- Android version:- Not specific to any OS version
- Android device:- Not specific to any android device

**Comment by ojw28** [comment]
The issue you describe doesn't sound particularly related to the other issues that you've referenced (although as an aside: one of them did get a fix, but it was in 2.9.0, so you'll already have the fix in the version you're using).

Unfortunately, without clearer reproduction steps, I don't think there's really much that we can do to help here. It could equally well be a server-side issue with the way the live stream is generated. Marking "needs more info" because I don't think this is actionable without clearer reproduction steps.

**Comment by ashishgupta2510** [comment]
Please confirm what additional information is required to reproduce this issue.

**Comment by ojw28** [comment]
We would need clearer reproduction steps as noted above.
