### ISSUE TITLE
How can we override getActionIndicesForCompactView() of PlayerNotificationManager.Builder

### ISSUE THREAD

**Issue by ravisaini1990** [google/ExoPlayer#9303]
Please suggest the way to override getActionIndicesForCompactView() of PlayerNotificationManager using the builder, since the earlier way to extends PlayerNotificationManager is deprecated now.
ExoPlayer Version : 2.14.1

**Comment by marcbaechinger** [comment]
I think this is not possible with the current state of the `PlayerNotificationManager`. There is a single constructor that is private so if you want to subclass `PlayerNotificationManager` you can't call any super constructor at all. 

We need to provide a fix for this which probably makes the constructor protected as a first step. Further the `PlayerNotificationManager.Builder` needs some changes as well to be reusable by subclasses.

**Comment by dway123** [comment]
Just curious: What was the change that broke or deprecated the previous way to extend `PlayerNotificationMaager`?

**Comment by marcbaechinger** [comment]
We first added a builder and deprecated public constructors in favor of a single private constructor with [this commit](https://github.com/google/ExoPlayer/commit/63ae8f541738b43d0deb271a758c14b0961def58). Later, this [commit](https://github.com/google/ExoPlayer/commit/a264a0a04f58aecdec662ac3af64263fb022939a) removed the deprectated constructors, so only the private constructor was left which prevents subclassing.

It's actually the first commit that was mistaken in making the constructor `private` instead of `protected`. It just worked until the deprecated constructors have been removed.

**Comment by dcvz** [comment]
@marcbaechinger any insight on the efforts to allow this again? Being able to do this would be great for us.

**Comment by marcbaechinger** [comment]
Have you noticed the commit above? This is on `dev-v2` already and will be released soon.

**Comment by dcvz** [comment]
Ah, must've missed it! Glad to hear! If I may ask (knowing estimates are approximate), is soon expected to be days or weeks?

**Comment by marcbaechinger** [comment]
I think 2.15.1 will be released this or next week.
