### ISSUE TITLE
Broken recognize of the initial type of network

### ISSUE THREAD

**Issue by brozikcz** [google/ExoPlayer#9307]
It seems to be broken with https://github.com/google/ExoPlayer/commit/f8727b5e875e4e8e7abe3bfebd2c101dd41541aa commit.

The initial network type is broken in `DefaultBandwidthMeter` because the value from `getNetworkType` is `C.NETWORK_TYPE_UNKNOWN` after the first call.

```
  private DefaultBandwidthMeter(
      @Nullable Context context,
      Map<Integer, Long> initialBitrateEstimates,
      int maxWeight,
      Clock clock,
      boolean resetOnNetworkTypeChange) {
    this.initialBitrateEstimates = ImmutableMap.copyOf(initialBitrateEstimates);
    this.eventDispatcher = new EventDispatcher();
    this.slidingPercentile = new SlidingPercentile(maxWeight);
    this.clock = clock;
    this.resetOnNetworkTypeChange = resetOnNetworkTypeChange;
    if (context != null) {
      NetworkTypeObserver networkTypeObserver = NetworkTypeObserver.getInstance(context);
      networkType = networkTypeObserver.getNetworkType();
      bitrateEstimate = getInitialBitrateEstimateForNetworkType(networkType);
      networkTypeObserver.register(/* listener= */ this::onNetworkTypeChanged);
    } else {
      networkType = C.NETWORK_TYPE_UNKNOWN;
      bitrateEstimate = getInitialBitrateEstimateForNetworkType(C.NETWORK_TYPE_UNKNOWN);
    }
  }```

**Comment by ojw28** [comment]
It's a little bit ambiguous whether this is broken or working as intended. In the new version the network type is initially `NETWORK_TYPE_UNKNOWN` because it's determined asynchronously. Once it's determined, `onNetworkTypeChanged` is called on any registered listeners. The reason for the change is to allow for disambiguation between 4G and 5G NSA, which I think either has to be asynchronous, or is more conveniently asynchronous, due to the underlying platform APIs used to disambiguate between these two cases.

That said, we did also see some problems internally as a result of the change, and we have [Internal ref: b/190021699] tracking whether we want to do something different.

**Comment by brozikcz** [comment]
I see, I'll rewrite our bandwidth provider impl.

**Comment by ojw28** [comment]
To clarify, have you solved this on your side by handling `NETWORK_TYPE_UNKNOWN` as an initial state? If so then I'll go ahead and close this (and the associated pull request). I'll keep the internal bug [Internal ref: b/190021699] open to possibly revisit the behavior.

**Comment by brozikcz** [comment]
Yes, I have a workaround in our implementation.
