### ISSUE TITLE
How to find Cue points are available inside the m3u8 file using exoplayer?

### ISSUE THREAD

**Issue by androaddict** [google/ExoPlayer#9313]
I am using latest Exoplayer version. We have live streaming URL (m3u8) it contains Original video as well as Ads. The URL is working fine without any problem, Ad also playing fine without any problem. But I want to print the log like ad started whenever ad stated and also ad end log whenever ad closed. Is it possible in latest Exoplayer version(2.14.2) to print the ads events?

**Comment by ojw28** [comment]
How are the ads marked in the stream? If they're marked using in-stream ID3 metadata then you can register to receive this metadata with:

```
player.addListener(new Listener() {
  @Override
  public void onMetadata(Metadata metadata) {
    // Metadata should be delivered here.
  }      
});
```

If the ads are marked in some other way, you'll need to provide more information for us to help. Thanks!

**Comment by androaddict** [comment]
Thanks for replay @ojw28 

We insert ads through SSAI(Server side Ad Insertion) 

above the URL is sample for Live streaming URL. It contains Original content as well as Ads. I need to print the something whenever ads started & ended.

**Comment by ojw28** [comment]
I don't see any ID3 metadata in the stream.

It's necessary for a SSAI solution to put markers of some kind into the stream so that clients can identify which parts of the stream are ads (if an ad is inserted in a completely seamless way on the server-side, it's obviously not possible for a client to determine where the ad is). I think you'll need to ask whoever's implementing the SSAI what markers they're adding to do this. Once you have this information, we can advise on how that information can be picked up using ExoPlayer APIs.

**Comment by androaddict** [comment]
Okay fine@ojw28. I will look at once again. As per discussion if any ID3 Meta data available in this stream means we can able to track the ad events(like start and end) right ??

**Comment by ojw28** [comment]
If ID3 metadata were inserted into the stream at the start and end of each ad, then yes.

**Comment by androaddict** [comment]
Okay @ojw28 Thanks for the your valuable support. We will check and update you. Thanks lot
