### ISSUE TITLE
OkHttpDataSource.open Fatal Exception: java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#9315]
- ExoPlayer version number: 1.15.0
- com.google.android.exoplayer:extension-okhttp:2.14.2
- Android version: 11 & 5.1
- Android device: Samsung

I'm using okhttp:2.14.2 because since 2.15.0 the minimum SDK version requirement from 16 to 21 and I still need to support SDK version 19 to 21.

I get the folllowing log from crashlytics:

```
Fatal Exception: java.lang.NoSuchMethodError
No direct method <init>(ILjava/lang/String;Ljava/util/Map;Lcom/google/android/exoplayer2/upstream/b;[B)V in class Lcom/google/android/exoplayer2/upstream/HttpDataSource$InvalidResponseCodeException; or its super classes (declaration of 'com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException' appears in base.apk)
com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open (OkHttpDataSource.java:324)
com.google.android.exoplayer2.upstream.StatsDataSource.open (StatsDataSource.java:84)
com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load (ProgressiveMediaPeriod.java:1014)
com.google.android.exoplayer2.upstream.Loader$LoadTask.run (Loader.java:409)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)
```

I don't have much more information as what url/video caused it :/ I'm investigating as well.

**Comment by ojw28** [comment]
It's not valid to mix and match ExoPlayer modules with different versions. In other words, 2.14.2 of the OkHttp extension module is not compatible with 2.15.0 of the core module.

We no longer officially support OkHttp prior to API level 21. Note that from December, OkHttp will stop back-porting even critical fixes to their releases that support earlier API levels ([as noted here](https://square.github.io/okhttp/#requirements)).

If you really need to use OkHttp on earlier API levels, I think you should:

1. Remove your dependency on `com.google.android.exoplayer:extension-okhttp`.
1. Fork the 2.15.0 versions of the Java classes contained in this module into your own codebase ([find them here](https://github.com/google/ExoPlayer/tree/r2.15.0/extensions/okhttp/src/main/java/com/google/android/exoplayer2/ext/okhttp)). There are only two classes, so this isn't particularly terrible.
1. Add a dependency to the OkHttp version you want to use in your own gradle file.

You can then use your forked version of the OkHttp extension directly.

I'm pretty sure this will work fine for 2.15.0. Note that you may have to update the Java classes when you upgrade to newer versions of ExoPlayer (you will know if you need to do this because your app code will stop compiling). Note also that this approach may stop working or become a bit more difficult if we start depending on features of OkHttp that were added after the version of OkHttp that you want to use.

**Comment by yoobi** [comment]
Okay I wasn't sure it was because exoplayer version mismatch, I'll try your method and if it gets too difficult to maintain I'll make a flavor of my APK that will use 2.14.2 for 19 to 21 and 2.15.0 for version 22 and more.

Thank you for your quick answer
