### ISSUE TITLE
How to detect ads in HLS live streams

### ISSUE THREAD

**Issue by androaddict** [google/ExoPlayer#9340]
I want to get the below details from M3U8 file
1,#EXTM3U
2.#EXT-X-VERSION:
3.#EXTINF
4.#EXT-X-DISCONTINUITY
5.#EXT-X-PROGRAM-DATE-TIME
6.#EXT-X-DATERANGE

so I need to get the above details from m3u8. so plan to pharsing. How to do that ? Any default function available for exoplayer ?

**Comment by androaddict** [comment]
@icbaker @christosts Any update one this ?

**Comment by ojw28** [comment]
We do not expose this information directly in a particularly raw format. HLS playlists are really intended for consumption by the player, and I would not expect application code to need such direct access. Depending on exactly what you need to do this for, it's possible that we expose a more processed form of some of the data you're interested in.

So, why do you need to do this? What feature are you building that requires this information?

**Comment by androaddict** [comment]
@ojw28  I want to find the Ads while Live streaming using Exoplayer Android

**Comment by androaddict** [comment]
@ojw28  I want to find the Ads while Live streaming in exoplayer android

**Comment by ojw28** [comment]
The right way to do this is to ensure that the streams have appropriate metadata baked into them for this, as was discussed in https://github.com/google/ExoPlayer/issues/9313. If you're using some kind of media playlist level metadata, then you'll need to provide a sample stream so that we can understand exactly how ads are marked in the content.

As an aside, this is the third (or possibly fourth) separate issue that you've filed about this problem. Please can you just keep replying to a single issue (it doesn't matter whether it's open or closed). It's very confusing, and inefficient for us to deal with, when you file a new issue every time.
