### ISSUE TITLE
ExtractorSampleSource same range multiple requests

### ISSUE THREAD

**Issue by abdallah95** [google/ExoPlayer#935]
Hello :)
If a DataSource is opened and the requested range of data is read successfully, is it possible that the ExtractorSampleSource might request the same range of data again if an internal error related to the Extractor or whatever has occured? given I will be using only ExtractorSampleSource and not any other SampleSource with unknown implementation.

**Comment by abdallah95** [comment]
well after some debugging i found out that it does...at the beginning of streaming it opened the datasource with position=0 which is obvious and after reading from it the positionHolder.position=75477...but for the second loop(inside the ExtractorLoadable load() while-loop) it opened the datasource with position=37710 which is less than what was read at first...is it really normal? and if yes why it would do that, it looks like an inefficient use of resources?

**Comment by ojw28** [comment]
We make no guarantees about what ranges of data we're going to read, or when we're going to read them. Note that it's partly dependent on both the container format and the layout of the media within it.

The specific case you mention is an inefficiency, and is a quirk that's necessary due to the way track selection works in ExoPlayer. We're aware of this. We will most likely be able to optimize this in the future, but this will be done as a bigger change around track selection.

**Comment by abdallah95** [comment]
hello again...if I integrated my datasource inside a cachedatasource...and let's say the range 0-8000 was read at first and it succeeded and then the range 3000-8000 was requested again...does the cachedatasource give any guarantee that the range 3000-8000 will be read from the cache not from the upstream datasource?
another question how BUFFER_SEGMENT_SIZE and BUFFER_SEGMENT_COUNT should be assigned?
