### ISSUE TITLE
Is there a better way to handle this kind of special MPEG-4 file playback issue?

### ISSUE THREAD

**Issue by ybai001** [google/ExoPlayer#9359]
We meet a special MPEG-4 file playback issue. ( We will provide test file via email dev.exoplayer@gmail.com.) This MPEG-4 file includes four tracks, which are
- One normal H.264 video track (v)
- One normal AAC audio track (a)
- One metadata track (Have the same timescale and sample duration as AAC track) (m1)
- Another metadata track (One sample only and it is located at the end of MPEG-4 file.) (m2)
So the file is organized in this way:
============================================
| v_1 | a_1 | m1_1 | v_2 | a_2 | m1_2 | ............ | v_N | a_N | m1_N | m2_1 |
============================================
That means metadata track2 is poor sample interleaving.

When playing starts, we need to get the data of the second metadata track since this metadata is a global metadata and will be used from the beginning of playback. 

We tested several this kind of MPEG-4 files. some of them can be played while some of them are failed. After an investigation, we found it is related to the method getTrackIndexOfNextReadSample() in Mp4Extractor.java.

The test file size is ~5.76MB. In our application, it can't be played due to the sample in metadata track 2 can't be read. Here is a log piece.
`08-31 14:55:46.543  7047  7081 D XXX     : InputPos=5205177 preferredTrack=video/avc minAccBytesTrack=application/bcp2 nextReadTrack=video/avc`
`08-31 14:55:46.543  7047  7081 D XXX     : MinAccBytes=206 minAccNeedReload=true preferredAcc=5460286`
`08-31 14:55:46.543  7047  7081 D XXX     : Track[audio/mp4a-latm] sample{offset=5269878 accBytes=5439601 skipAmount=64701 reqReload=false} minAcc=5439601 minAccNeedReload=false preferredAcc=5439601`
`08-31 14:55:46.543  7047  7081 D XXX     : Track[application/bcp1] sample{offset=5366737 accBytes=2372751 skipAmount=161560 reqReload=false} minAcc=2372751 minAccNeedReload=false preferredAcc=5439601`
`08-31 14:55:46.543  7047  7081 D XXX     : Track[application/bcp2] sample{offset=6015785 accBytes=206 skipAmount=810608 reqReload=true} minAcc=206 minAccNeedReload=true preferredAcc=5439601`
`08-31 14:55:46.543  7047  7081 D XXX     : Track[video/avc] sample{offset=5205177 accBytes=5460286 skipAmount=0 reqReload=false} minAcc=206 minAccNeedReload=true preferredAcc=5460286`

At the end of method getTrackIndexOfNextReadSample(), the logic is
`    return minAccumulatedBytes == Long.MAX_VALUE`
`            || !minAccumulatedBytesRequiresReload`
`            || preferredAccumulatedBytes < minAccumulatedBytes + MAXIMUM_READ_AHEAD_BYTES_STREAM`
`        ? preferredTrackIndex`
`        : minAccumulatedBytesTrackIndex;`

For our case, 

- "minAccumulatedBytes == Long.MAX_VALUE" is FALSE
- "!minAccumulatedBytesRequiresReload" is FALSE since minAccumulatedBytesRequiresReload is TRUE
- "preferredAccumulatedBytes < minAccumulatedBytes + MAXIMUM_READ_AHEAD_BYTES_STREAM" is TRUE since 5460286 < 206 + 10 * 1024 * 1024

The result is preferredTrackIndex (video/avc) is returned for this calling. And minAccumulatedBytesTrackIndex(It is application/bcap2) can't be returned in the next callings. (For our test file, the total duration is 60 seconds and this track is read after 10 seconds. But we need to read it at the beginning of playback.)
If we decreased value of MAXIMUM_READ_AHEAD_BYTES_STREAM to a suitable value, minAccumulatedBytesTrackIndex(application/bcp2) can be returned and it is our expected result.
If this kind of file is big enough, we find it can be played since "preferredAccumulatedBytes < minAccumulatedBytes + MAXIMUM_READ_AHEAD_BYTES_STREAM" is FALSE and minAccumulatedBytesTrackIndex(application/bcap2) is returned.

Our questions are
(1) Do you have any suggestions about how to handle this case? We don't want to change the source code of ExoPlayer. If there is a way to handle this case in getTrackIndexOfNextReadSample() as a common handling, it will be better. (For our case, we can decrease the value to a small one but it is NOT a good handling in our mind. 
(2) Honestly, we don't fully understand the intention of sentence "preferredAccumulatedBytes < minAccumulatedBytes + MAXIMUM_READ_AHEAD_BYTES_STREAM". From the comments of this method, we know it is used to deal with poor sample interleaving case. Could you provide more explanation about it? Thanks a lot.

**Comment by kim-vde** [comment]
In your case, the extractor always extracts the samples in order of their byte offset. The reason it only extracts sample `m2_1` at the end is that, if it wasn’t doing that, it would need to reload the source multiple times, which is generally a time-consuming operation (for example, it can translate into opening a new network connection). Indeed, the extractor would need to 
- Jump forward in the input to read sample `m2_1` (because the distance from the input position to the offset of `m2_1` is larger than `RELOAD_MINIMUM_SEEK_DISTANCE`).
- Jump back in the input to read the `a/v/m1` samples (because jumping back always requires a reload).

The logic that compares the accumulated bytes is there to avoid having too many samples in memory in case of a poorly interleaved media file. For each sample, `sampleAccumulatedBytes` contains the total size of the samples preceding it in terms of timestamps. In other words, it is the number of bytes that should be rendered before the current sample. The larger it is, the longer the sample will need to stay in memory. Condition `preferredAccumulatedBytes < minAccumulatedBytes + MAXIMUM_READ_AHEAD_BYTES_STREAM` is there to make sure that the preferred sample won’t stay in memory for too long. This “security” is never triggered in your case though, because the media file is reasonably small.

Reducing the value of `MAXIMUM_READ_AHEAD_BYTES_STREAM` will make this security stricter, so that source reloads will occur more often. This could be acceptable if your samples are usually well interleaved.

We recently had to solve a similar problem to the one you are having ([commit](https://github.com/google/ExoPlayer/commit/c0a0708fc382172e85cd377d4de771e8bd99fc2e)). We modified the extractor so that it first jumps to the end and reads the metadata there, and then jumps back to the start to go on with the “normal extraction”. You could modify the `Mp4Extractor` directly to do something similar, or, if you don't want to change the source code, try to implement a custom extractor that would wraps the `Mp4Extractor`.

**Comment by ybai001** [comment]
Sorry for late response.
Thanks for your detailed answer. It's truly out of my anticipation.
