### ISSUE TITLE
compileSdkVersion, targetSdkVersion and ExoPlayer Support for Android 11

### ISSUE THREAD

**Issue by jrw95** [google/ExoPlayer#9366]
Hello,

I'm wondering if you could provide some details on ExoPlayer support for Android 11.

I looked through the release notes and see that there is a note for 2.11.0 that indicates support for Android 10 (setting the `compileSdkVersion` to 29). I couldn't find a note that indicated support for Android 11, however the `compileSdkVersion` has been set to 30 since r2.13.0, and the `targetSdkVersion` was updated to 30 with r2.15.0. There are also two release notes that reference changes to support Android 11 (one to pass a frame rate hint in r2.12.0, and one to fix a strict mode warning in r2.14.2).

I also checked through the blog and couldn't find anything that referenced supporting Android 11 explicitly, as [this post does for Android 10 with r2.11.0](https://medium.com/google-exoplayer/exoplayer-2-11-whats-new-e0e0701e4b6c).

If we want to announce support for Android 11 with our player SDK, should we upgrade to r2.15.0? We're in progress on an update to r2.14.2 at this time.

Also, just out of curiosity, why is the `appTargetSdkVersion` in the demos one API version lower?

Thanks very much.

**Comment by ojw28** [comment]
> If we want to announce support for Android 11 with our player SDK, should we upgrade to r2.15.0? We're in progress on an update to r2.14.2 at this time.

r2.14.2 should be fine. The `targetSdkVersion` was 28 for that release, but it was being held there due to a compatibility issue between Android Studio / Robolectric / Java 9. See [this line](https://github.com/google/ExoPlayer/blob/r2.14.2/constants.gradle#L20), which was referencing [this issue](https://issuetracker.google.com/issues/143232359). That issue had nothing to do with actual compatibility of the library with Android 10 or 11, and I don't see any additional compatibility changes in r2.15.0.

> Also, just out of curiosity, why is the appTargetSdkVersion in the demos one API version lower?

This is so that the demo app can use the [requestLegacyExternalStorage opt-out for scoped storage](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage), which is useful for local testing. At some point we'll have to do a bit of work and stop relying on this, but that's why it's set to 29 for now. Again, this has nothing to do with compatibility of the library with Android 11.
