### ISSUE TITLE
Check if an error is caused by a Renderer

### ISSUE THREAD

**Issue by perracodex** [google/ExoPlayer#9369]
In version 2.15.0 the **onPlayerError** signature has changed from:

`public void onPlayerError(ExoPlaybackException error)`

to:

`public void onPlayerError(PlaybackException error)`

With the older signature we could check if the error was caused by a renderer by querying the error type:

`if (error.type == ExoPlaybackException.TYPE_RENDERER)`

How can now be checked with **PlaybackException**? There is no equivalent in **PlaybackException.errorCode**

**Comment by AquilesCanta** [comment]
The simple answer is: Use

```
if (error instanceof ExoPlaybackException
    && ((ExoPlaybackException) error).type == ExoPlaybackException.TYPE_RENDERER)
```

But the better answer is use `error.errorCode` which provides a finer grained description of what the issue is.

**Comment by perracodex** [comment]
Thank you for the answer.
I checked all the possible codes available for **error.errorCode**, but couldn't find any to be the equivalent for **TYPE_RENDERER**,
Should I assume that for all "renderer" errors the only solution would be as in your answer?

**Comment by AquilesCanta** [comment]
There is no equivalent of TYPE_RENDERER because knowing that an error happened in the renderer is deemed not useful. It just tells you it happened in the renderer. The cause could be a DRM issue, an AudioTrack issue, a decoder issue, or even something else. So knowing the type is not really a significant usecase. It would be more meaningful to know what you do if the error is of TYPE_RENDERER.
