### ISSUE TITLE
Midroll ads sometimes blocks the player and skips the ads

### ISSUE THREAD

**Issue by silvestr-palianchuk-dev** [google/ExoPlayer#9375]
FF-ing through the midroll ads sometimes blocks the player and skips the ads.

Tested on: 
**Device:** Fire TV (Fire OS 5.2.7.8)
**ExoPlayer versions:** 2.14.0, 2.15.0

```
09-01 13:41:32.153  9872  9872 E EventLogger:   com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: java.io.IOException: Failed to load ad group 1
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.android.exoplayer2.ext.ima.AdTagLoader.handleAdGroupLoadError(AdTagLoader.java:1059)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.android.exoplayer2.ext.ima.AdTagLoader.access$1000(AdTagLoader.java:79)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.android.exoplayer2.ext.ima.AdTagLoader$ComponentListener.getContentProgress(AdTagLoader.java:1325)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.ads.interactivemedia.v3.internal.ew.f(IMASDK:1)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.ads.interactivemedia.v3.internal.ew.g(IMASDK:1)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.ads.interactivemedia.v3.internal.ew.e(IMASDK)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.google.ads.interactivemedia.v3.internal.eu.run(Unknown Source)
09-01 13:41:32.153  9872  9872 E EventLogger:       at android.os.Handler.handleCallback(Handler.java:751)
09-01 13:41:32.153  9872  9872 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:95)
09-01 13:41:32.153  9872  9872 E EventLogger:       at android.os.Looper.loop(Looper.java:154)
09-01 13:41:32.153  9872  9872 E EventLogger:       at android.app.ActivityThread.main(ActivityThread.java:6194)
09-01 13:41:32.153  9872  9872 E EventLogger:       at java.lang.reflect.Method.invoke(Native Method)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
09-01 13:41:32.153  9872  9872 E EventLogger:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
09-01 13:41:32.153  9872  9872 E EventLogger:   Caused by: java.io.IOException: Failed to load ad group 1
09-01 13:41:32.153  9872  9872 E EventLogger:       ... 14 more
09-01 13:41:32.153  9872  9872 E EventLogger:   Caused by: java.io.IOException: Ad preloading timed out
09-01 13:41:32.153  9872  9872 E EventLogger:       ... 12 more
09-01 13:41:32.153  9872  9872 E EventLogger: ]
```

**How to reproduce:**
- Start playback 
- FF until the midroll ad marker is reached
- do not discontinue the FF process yourself, but wait for it to stop on its own

**Expected result:**
The playback is stopped when midroll ad marker is reached and the video ads start

**Actual result:**
The playback is paused, but the video ads do not start and the user needs to press play by themselves in order to continue the playback

Full Logs: https://deltatre-my.sharepoint.com/:t:/g/personal/silvestr_polianchuk_massive_co/Eddhw0G0_khBkj1YrCZxWdEB4mziKvzJiAigU-itCqSpxw?e=BzLPgu
Video: https://deltatre-my.sharepoint.com/:v:/g/personal/silvestr_polianchuk_massive_co/EaRnTsxGFcxMsr_NTHu67VYBxm-WHMaKSNNah0i0nnaptQ?e=JEL7JL
BugReport: https://deltatre-my.sharepoint.com/:u:/g/personal/silvestr_polianchuk_massive_co/EXr_UxDudtpFv6W716VYXEIBQ_e52DZtYe4WHejnqwRqkA?e=9CGJdx

**Comment by kim-vde** [comment]
I tried to reproduce the issue on our [demo app](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/main) (content "IMA sample ad tags" > "VMAP pre-, mid- and post-rolls, single ads") but I couldn't. Could you try to reproduce on this app by adding your content to [media.exolist.json](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/assets/media.exolist.json), and provide us with the JSON object that you added to this file? If you're unable to share this information publicly, please send it to dev.exoplayer@gmail.com using subject #9375. Please also update this issue to indicate you've done this.

Can you also clarify what you observe exactly? Is it
- "FF-ing through the midroll ads sometimes blocks the player and skips the ads.", or 
- "The playback is paused, but the video ads do not start and the user needs to press play by themselves in order to continue the playback"?

Note: #7956 looks similar so it might be related.

**Comment by usopphammer** [comment]
I work with Silvestr on the same project. Our ad URL has been changed and with the new URL there are no errors in exoplayer demo and our app for now. The bug can be closed. I will reopen it if the issue appears again.
