### ISSUE TITLE
Black screen appear on some videos when pause and resume the activity .

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#9376]
I also have used it in another project's  activity . With same video sample when we press home button and then come back it shows black screen . If you think  that sample video can help you , I am sharing it with you now . this happens in just in lollipop version devices. I have tested in oppoA37f . 

https://user-images.githubusercontent.com/22340353/131622821-587ab18a-a363-4c10-a0d7-a2b647db897d.mp4

reproduction steps 
1-play video
2-press home button 
3-brows app form recents or from home (i want to say brows app to front)
4-repeat it for 3 to 4 times black screen will appear .
Also sending you the reproduction video
  

https://user-images.githubusercontent.com/22340353/131622712-9a9b2c71-7356-4b9a-8aa8-b37e6db8a930.mp4

I am sending you other project video also

https://user-images.githubusercontent.com/22340353/131622974-e61dd441-b501-402b-9ce5-dcf6ba482028.mp4

**Comment by kim-vde** [comment]
Note: this bug is a continuation of #9354.

Can you try to reproduce on our [demo app](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/main)?

You said the issue is only present in Lollipop. Have you tried on lower and higher API levels? Was the issue not present then?

**Comment by waqasyousafy** [comment]
That was closed so I have no choice to further discuss it . So , I have tested on other devices not reproduced . I have tested video it shows black screen for short time and then time is increasing on black.

https://user-images.githubusercontent.com/22340353/131990376-cf41db2e-1b10-4796-ab0e-d081b9e4d1b4.mp4

**Comment by kim-vde** [comment]
I have tried to reproduce on the demo app with a Nexus 5 running Android 5.1.1 (Lollipop). I can indeed see a black screen when the app is moved to the background and then back to the foreground. I observed this for every video I have tried.

I am not sure it is a bug though. When you move the app to the background, [`PlayerActivity.onPause`](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L166) is called and the player is released. When you move it back to the foreground, [`PlayerActivity.onResume`](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L152) is called and the player is recreated. It takes a bit of time to prepare the player so that it can start playing.

To make sure this is indeed the reason, you could log the time the player takes to be ready and see if it matches more or less the black screen duration.

**Comment by waqasyousafy** [comment]
I have produced this in my application with not releasing the player in activity . In your case you point is valid that player is releasing on pause and taking time to reinitialize the player. But I am afraid that player is not releasing in pause state then it also showing same behavior with backscreen increasing in time duration if you do it continuously .

**Comment by waqasyousafy** [comment]
any reply????

**Comment by kim-vde** [comment]
You should probably release the player when the app goes to the background so that it doesn't hold resources that might be needed by other apps (like we do for the demo app).
