### ISSUE TITLE
Intercepting Controls / Detecting Transition at End of Playlist

### ISSUE THREAD

**Issue by cdowless** [google/ExoPlayer#9377]
In my application, the player should move to another playlist once the last media item of the current playlist finishes playing / is skipped. There are two cases for this:

- On last media item in playlist, press Skip Next; then go to playlist A
- On last media item in playlist, auto-transition; then go to playlist A

Since Skip Next is disabled by default when the current media item is the last in the playlist, I've set the repeat mode to `Player.REPEAT_MODE_ALL`. This was just a quick way to enable the skip button on the last media item (may not be the best approach).

I've tried handling these two cases in `onPositionDiscontinuity()` and/or `onMediaItemTransition()`, but I can't seem to capture these cases (since a skip and seek are treated as the same reason). I've also looked at extending `DefaultControlDispatcher()` where I override `dispatchNext()`, but I'm not sure if this is the right avenue and wanted to check with the team here first.

EDIT: I'm also aware of the state `Player.STATE_ENDED`, but this didn't fit my use case since I want the Skip Next button to cause the same behavior.

What is the best way to approach this?

I've done some searching on Stack Overflow and the ExoPlayer issues, but can't find the exact answer I'm looking for. Thanks for the support.

**Comment by kim-vde** [comment]
Which version of ExoPlayer are you using? 

On the latest version, you could try to:
- Wrap your player in a [`ForwardingPlayer`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ForwardingPlayer.html).
- Override `isCommandAvailable` and `getAvailableCommands` so that commands `COMMAND_SEEK_TO_NEXT_WINDOW` and `COMMAND_SEEK_TO_NEXT` are always available. This should enable the next button.
- Override methods `seekToNextWindow`  and `seekToNext` to seek to the first item of the next playlist if the current item is the last one of the playlist.
- Listen to events as you have suggested for the case where the last item of the playlist ends.

**Comment by cdowless** [comment]
I'm on the latest version - will give this a try. Thanks for the help!

I currently have it working with the somewhat hacky "turn on repeat to keep the seek to next command available", but will likely replace with your recommendation as this seems cleaner / more stable.
