### ISSUE TITLE
The return of MediaDrmCallback::executeKeyRequest should be @Nonnull?

### ISSUE THREAD

**Issue by changxiangzhong** [google/ExoPlayer#9398]
In our project, we inherited and customized `MediaDrmCallback::executeKeyRequest()` function to add our own magic, such as tokens, to talk to our DRM server.
In our existing implementation, it returns **NULL** in case of timeout exception. I've gone through the function `DefaultDrmSession::MediaDrmCallback::executeKeyRequest()`, my understanding is 

- Under no circumstances, should `MediaDrmCallback::executeKeyResponse()` returns null
- In case of exception, we could throw `MediaDrmCallbackException`

So, is my understanding correct? If it's correct, do you mind if we mark the return @Nonnull? I can make a PR afterwards

**Comment by icbaker** [comment]
All ExoPlayer API surfaces are non-null by default (i.e. if there's no annotation, then everything is assumed to be non-null). This is achieved via the `package-info.java` files ([drm package example](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/drm/package-info.java)) by annotating the whole package with [`@NonNullApi`](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/util/NonNullApi.java). We don't annotate anything individually `@NonNull`.

Android Studio should detect this `@NonNullApi` annotation correctly - so if you're developing your `MediaDrmCallback` implementation in Android Studio it should warn you when you return `null`. I just tried it by modifying `HttpMediaDrmCallback` and it warned me: 
>'null' is returned by the method declared as @NonNullApi

**Comment by changxiangzhong** [comment]
@icbaker Thanks for you reply. We don't see any warning regarding the null return. We would respected the warning if it was there. 
![image](https://user-images.githubusercontent.com/5352145/132374357-583613af-a161-4722-b457-0036bad03763.png)

**Comment by icbaker** [comment]
Thanks for the extra details - I tried implementing `MediaDrmCallback` in a new Android Studio project that depends on ExoPlayer via a maven artefact (rather than the test I did before, which modified a class inside the project).

I also don't see a warning when returning `null` from `executeKeyRequest`.

I **do** see warnings when passing `null` to other methods that are implicitly @NonNull (marked with the same mechanism) - e.g. `Util.getUtf8Bytes(null)`.

This looks like a bug in Android Studio / Lint - I filed https://issuetracker.google.com/199161212 which you can follow along if you're interested.

Thanks for reporting!

**Comment by icbaker** [comment]
Turns out this isn't an Android Studio bug, it's a problem in the way ExoPlayer splits packages across different AARs. This is only a temporary state, so everything should be sorted in future. More info in https://issuetracker.google.com/199161212.
