### ISSUE TITLE
Extract Subtitle from Video and set in TrackSelection dialog

### ISSUE THREAD

**Issue by jesro** [google/ExoPlayer#9399]
I have app which recieve video in C.TYPE_DASH DashChunkSource, C.TYPE_SS, C.TYPE_HLS HlsMediaSource, C.TYPE_OTHER  DefaultDataSource, ProgressiveMediaSource types. i find it by using Util.inferContentType(videoURI.lastPathSegment)

I need to extract subtitle language from videoURI and set it into trackSelector parameter
 like below:  (if i receive english language subtitle from videoURI, i need to set english in trackselectorDialog)
 Do i need to set it like below for my requirement?
```
 trackSelector.setParameter(
        trackSelector
           .buildUponParameters()
           .setMaxVideoSizeSd()
           .setPreferredAudioLanguage("")   // set it here   for audio
           .setPreferredTextLanguage("")   // set it here  for text
        )
```
        
Because now my trackselection dialog was set to "Auto" which i set by default (inspite of video have subtitle or not or with different language subtitle).  How to extract subtitle language and select into trackselector dialog subtitle language when player starts playing.       

![Screenshot_1631015851](https://user-images.githubusercontent.com/10104522/132341037-7483dc51-b85e-4466-89e0-0f2cd4f54af9.png)

**Comment by ojw28** [comment]
Once the manifest has been loaded by the player, you can query the available tracks using `Player.getCurrentTrackGroups`. You can also listen to `EventListener.onTracksChanged` to be notified when the tracks become known.

Once you have the `TrackGroupArray`, iterate through the `TrackGroups`, and the formats within each `TrackGroup`. Once you find the one corresponding to text, you should find the language in the `Format.language` field.

**Comment by jesro** [comment]
I checked with Player.EventListener.onTracksChanged i get Formats array from TrackGroupsArray

```
val format: Format? = trackGroups[index].getFormat(0)
Log.d("AllFormats", format?.metadata.toString)  // it prints         null, entries=[HlsTrackMetadataEntry[subs, English]]

//  Format(1/8219, null, null, application/cea-608, null, -1, null, [-1, -1, -1.0], [-1, -1])
//  Format(subs:English, English, application/x-mpegURL, text/vtt, null, -1, en, [-1, -1, -1.0], [-1, -1])

if (format?.language != null && format?.sampleMimeType != null && format?.sampleMimeType!!.contains("application")) 
 {
    Log.d("SubtitleLanguages", format?.language) // it prints  'en'
 }
```

In playlist i have 
`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="eng",URI="hdntl=exp=1631727001~acl=%2f*~data=hdntl~hmac=XXXXXXXXXXXXXX/playlistcaptions-cc-0.m3u8"`

If multiple subtitle language comes, how to find the one which video plays by default?  Because im not getting subtitle for Default, only null comes in callback?
For this playlist, video plays English subtitle automatically when video starts playing in exoplayer. For some video no subtitle plays, how to find these difference.

**Comment by ojw28** [comment]
If you just try and play your stream in the demo app, you should see that its logcat output is able to tell which tracks are selected. See [this page](https://exoplayer.dev/debug-logging.html#media-tracks) for more details.

You should be able to enable similar logging in your own application by registering an `EventLogger` to your player instance as described [at the top of the same page](https://exoplayer.dev/debug-logging.html). Take a look at the `EventLogger` source code if you'd like to understand how it's doing this. You should be able to use the same approach in your own application.

Note that the "difference" you refer to is due to the media itself (e.g., whether it specifies `AUTOSELECT=YES` on a track in the master playlist). The value of `Format.selectionFlags` for each track lets you query what the media specifies for each track. The possible flags are documented [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#SELECTION_FLAG_DEFAULT).
