### ISSUE TITLE
Map HLS manifest tags to a point in playback time

### ISSUE THREAD

**Issue by bhupikagautam** [google/ExoPlayer#9417]
I am working with the timed metadata and to access the #EXT-X-DATERANGE tag I get the manifest in the onTimelineChanged Listener using  getCurrentManifest(), from the manifest obtained I am able to get the tags list and extract the required tags.
Is there a mechanism to map the tags in this list to the point in the playback time that they correspond to?

I tried the getCurrentPosition() but it does not seem to be accurate to the playback time and also gives out negative values some of the time

**Comment by tonihei** [comment]
I think you should be able to add 
`Player.getCurrentTimeline().getWindow(windowIndex, new Timeline.Window()).windowStartTimeMs` to `player.getCurrentPosition()` to calculate the current position in milliseconds since the UNIX epoch. 

Please also refer to the picture and explanations in this section: https://exoplayer.dev/live-streaming.html#detecting-and-monitoring-live-playbacks

If you like to trigger a custom event once the player reaches a specific playback position defined in #EXT-X-DATERANGE, you may want to have a look at sending messages at a playback time as well: https://exoplayer.dev/listening-to-player-events.html#firing-events-at-specified-playback-positions Note that the position you have to provide to the message is in the same time frame as `player.getCurrentPosition`, so it would be `extXDateRangeUnixTime - timeline.window.windowStartTimeMs`.

**Comment by tonihei** [comment]
Closing because I think the question was answered.
