### ISSUE TITLE
Is there a way to prevent `DownloadHelper` from downloading a segment on instantiation for HLS sources

### ISSUE THREAD

**Issue by strangesource** [google/ExoPlayer#9425]
When creating a `DownloadHelper` for an `HLS` source using the `forMediaItem` methods, preparing the download helper will download the first segment from the variant playlist. 
This is non - ideal for users on metered networks where data is very expensive.
 
I tracked this down and it seems to originate from preparing a `HlsMediaPeriod`  which needs a chunk to determine the format of the tracks (as there is no `CODECS` attribute present on the variant).

My question would be if there is a way to download tracks for an HLS source without the need to download an initial segment?

**Comment by christosts** [comment]
The player can prepare HLS media sources without downloading the first segment by doing a _chunkless preparation_ (related [blog post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6)). I assume you may have seen this feature already because you mentioned there is no CODECS attribute present on the variant: chunkless preparation needs CODECS and it won't make a difference if the playlist does not have CODECS in it. However, by default chunkless preparation is not enabled in the `DownloadHelper`, therefore the first segment will be downloaded always.

As a first step, you may try to enable chunkless preparation to get some benefits for at least those playlists that can be prepared as such. To do so, instead of using the `DownloadHelper.forMediaItem` methods, please use the [DownloadHelper](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadHelper.html#%3Cinit%3E(com.google.android.exoplayer2.MediaItem,com.google.android.exoplayer2.source.MediaSource,com.google.android.exoplayer2.trackselection.DefaultTrackSelector.Parameters,com.google.android.exoplayer2.RendererCapabilities%5B%5D)) constructor and pass a custom HLS media source that has chunkless preparation enabled. This is a modified snippet form the demo app's `DownloadTracker`:

```
HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory)
          .setAllowChunklessPreparation(true)
          .createMediaSource(mediaItem);
DefaultTrackSelector.Parameters parameters = DefaultTrackSelector.Parameters.getDefaults(context)
          .buildUpon()
          .setForceHighestSupportedBitrate(true)
          .build();
DownloadHelper downloadHelper = new DownloadHelper(mediaItem,
          hlsMediaSource, parameters, DownloadHelper.getRendererCapabilities(renderersFactory));
```
My assumption so far is that app knows it's downloading an HLS asset, hence it's creating an HLS media source directly. If the app can't know beforehand the content is HLS, you may refer to the [DownloadHelper source code](https://github.com/google/ExoPlayer/blob/r2.15.1/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadHelper.java#L408-L426) to see how media source types are identified by `DownloadHelper.forMediaItem`.

So, at this point, the question is whether you can ensure the playlists have CODECS? If not, there is a way to insert CODECS when the playlist is downloaded. **Please note, I have not tested the following, so try it out cautiously.** You can use a custom `HlsPlaylistParser` to insert CODECS yourself. Continuing the snippet above, you can inject a custom `HlsPlaylistParserFactory` to the HLS media source that inserts CODECS in the playlist and then uses the player's default HLS playlist parsers:

```
HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(httpDataSourceFactory)
    .setAllowChunklessPreparation(true)
    .setPlaylistParserFactory(new HlsPlaylistParserFactory() {
      @Override
      public ParsingLoadable.Parser<HlsPlaylist> createPlaylistParser() {
        return new ParsingLoadable.Parser<HlsPlaylist>() {
          @Override
          public HlsPlaylist parse(Uri uri, InputStream inputStream) throws IOException {
            String playlist = Util.fromUtf8Bytes(Util.toByteArray(inputStream));
            String newPlaylist = // modify playlist to contain CODECS
            ByteArrayInputStream bain = new ByteArrayInputStream(Util.getUtf8Bytes(playlist));
            return new HlsPlaylistParser().parse(uri, bain);
          }
        };
      }

      @Override
      public ParsingLoadable.Parser<HlsPlaylist> createPlaylistParser(
          HlsMasterPlaylist masterPlaylist,
          @Nullable HlsMediaPlaylist previousMediaPlaylist) {
        return new HlsPlaylistParser(masterPlaylist, previousMediaPlaylist);
      }
    })
    .createMediaSource(mediaItem);
```
For this to work, you need to pass the actual CODECS of the content, therefore the app should somehow know the CODECS. Can you build an out-of-band mechanism that communicates CODECS? This is very hacky but maybe it's of some use to your use-case.

**Comment by strangesource** [comment]
Hi @christosts, thanks a bunch for the very detailed answer. 🙇  Much appreciated.

We will consider the suggestions while our situation already improved with https://github.com/google/ExoPlayer/pull/8025 as the lowest resolution track is now prepared as opposed to the highest resolution.
