### ISSUE TITLE
DataSourceException.POSITION_OUT_OF_RANGE，AAC decoder returned error 0x0005, substituting silence

### ISSUE THREAD

**Issue by RexSuper** [google/ExoPlayer#9446]
我现在遇到了一个困难的问题，播放器播放歌曲突然没有声音了，切歌之后可以恢复，详细报错如下，请问如何解决呢。
核心报错是

I have encountered a difficult problem. The player suddenly has no sound when playing songs. It can be recovered after cutting songs. The detailed error reports are as follows. How can I solve it.
The core error is

1.AAC decoder returned error 0x0005, substituting silence
2.AAC decoder returned error 0x4004, substituting silence
3.upstream.DataSourceException

~~~
48485-09-18 09:35:03.911 E/EventLogger( 2336): internalError [eventTime=3024.76, mediaPos=15.09, window=0, period=0, loadError
48486:09-18 09:35:03.911 E/EventLogger( 2336):   com.google.android.exoplayer2.upstream.DataSourceException
48487-09-18 09:35:03.911 E/EventLogger( 2336):       at com.google.android.exoplayer2.upstream.cache.b.a(CacheDataSource.java:284)
48488-09-18 09:35:03.911 E/EventLogger( 2336):       at com.google.android.exoplayer2.upstream.t.a(StatsDataSource.java:83)
48489-09-18 09:35:03.911 E/EventLogger( 2336):       at com.google.android.exoplayer2.source.h$a.b(ProgressiveMediaPeriod.java:962)
48490-09-18 09:35:03.911 E/EventLogger( 2336):       at com.google.android.exoplayer2.upstream.Loader$c.run(Loader.java:415)
48491-09-18 09:35:03.911 E/EventLogger( 2336):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
48492-09-18 09:35:03.911 E/EventLogger( 2336):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
48493-09-18 09:35:03.911 E/EventLogger( 2336):       at java.lang.Thread.run(Thread.java:764)
48494-09-18 09:35:03.911 E/EventLogger( 2336): ]
~~~

**Comment by RexSuper** [comment]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/38449675/133884081-aa68c5b4-26b8-4d47-b25d-64560e7d7098.png">

**Comment by RexSuper** [comment]
![image](https://user-images.githubusercontent.com/38449675/134331512-e45f81a0-7cc7-4d40-afaa-86cc3eac87ce.png)

**Comment by RexSuper** [comment]
![5b45918483d05eda12f9a653789b9d3a](https://user-images.githubusercontent.com/38449675/134331610-33873080-8806-4e8a-9a69-0334344bc92f.png)

**Comment by RexSuper** [comment]
经过分析，这个问题核心是下载的时候产生了DataSourceException.POSITION_OUT_OF_RANGE
这和之前的"Response code: 416"非常类似，但是之前有OnPlayError的回调，我们下层还可以做回调处理。这次的bug没有。
EOFException
28849:09-18 09:34:38.892 E/EventLogger( 2336):       at com.google.android.exoplayer2.source.j.a(SampleDataQueue.java:191)

请问我该如何处理这种情况呢？

After analysis, the core of this problem is that datasourceexception.position is generated during downloading_ OUT_ OF_ RANGE
This is very similar to the previous "response code: 416", but there was a callback of onpayerror before, and we can also do callback processing in the lower layer. There is no bug this time.
EOFException
28849:09-18 09:34:38.892 E/EventLogger( 2336):       at com.google.android.exoplayer2.source.j.a(SampleDataQueue.java:191)
How can I handle this situation?

**Comment by krocard** [comment]
@kim-vde could you take a look at this EOF handling of MP4 extractor. Is this expected (for example the file is truncated) or is some handling missing.

@RexSuper Could you please share the problematic mp4? 
If you're unable to share the test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by RexSuper** [comment]
> @kim-vde could you take a look at this EOF handling of MP4 extractor. Is this expected (for example the file is truncated) or is some handling missing.
> 
> @RexSuper Could you please share the problematic mp4?
> If you're unable to share the test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

https://user-images.githubusercontent.com/38449675/134447944-e9339516-c799-4816-8aeb-1af603cc0f37.mp4

This is the MP4 that has a problem, but it is not a necessary problem. Therefore, it is very difficult for me to analyze this problem now. I need your help. Even if it is not solved, let me know that the wrong callback has a way to resume playback. Thank you very much

**Comment by RexSuper** [comment]
@kim-vde @krocard

**Comment by kim-vde** [comment]
The file you sent plays correctly (I can hear audio until the end and no exception is thrown) for me on the [demo app](https://github.com/google/ExoPlayer/tree/r2.15.1/demos/main). Can you try to play the file locally (i.e. by storing it on your device and using a [`DefaultDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultDataSource.html) for example) on your app and tell me whether you still encounter the issue?

The `DataSourceException` indicates that there is a problem when retrieving the data (for instance from the server). This probably causes the unexpected `RESULT_END_OF_INPUT` when reading the input. What type of `DataSource` are you using? If you are reading the file from a server, can you share the link to it so that I can try to reproduce? If you're unable to share the link publicly, please send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

Regarding the error callback, this depends on the version of ExoPlayer you are using. On the latest version, you can use [`Player.addListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#addListener(com.google.android.exoplayer2.Player.Listener)) and [`Listener.onPlayerError`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onPlayerError(com.google.android.exoplayer2.PlaybackException)).

**Comment by RexSuper** [comment]
I didn't reproduce this problem locally. The video and log provided by the user. Because it is not always a problem, it is difficult to handle. At present, I will listen to "onplayerrerror" to retry the corresponding processing. At present, my exo version "onplayerrerror" does not contain this error. I will update the exo version to temporarily solve the impact caused by this problem. If I have new discoveries, I will synchronize them in time.
