### ISSUE TITLE
Capitalize first letter of a text in track selector menu items

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9452]
This is how the audio selector of `StyledPlayerView` looks like in two languages (English and Czech):

![languages](https://user-images.githubusercontent.com/1071643/133937946-74be1518-4d19-4935-b4eb-a1743d296766.png)

In Czech (and other languages probably as well), the language name (`angličtina`) is in all lower case characters. But because of the use in this menu, I think the first letter should be upper cased in [DefaultTrackNameProvider.buildLanguageOrLabelString()](https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/ui/src/main/java/com/google/android/exoplayer2/ui/DefaultTrackNameProvider.java#L92).

- ExoPlayer version number: 2.15.0
- Android version: Android 10
- Android device: OnePlus 7

**Comment by krocard** [comment]
This is the string returned by `Local.getDisplayName`, I'm not sure we want to do any transformation on it. The characters returned might not even have a upper case concept.  @ojw28 you are marked as UI owner in our triage guide, so assigning to you as minor.

**Comment by ojw28** [comment]
I think `Locale.getDisplayName` returns a string that would be suitable for use mid-sentence. In English, language names are generally capitalized whether they occur at the start or in the middle of a sentence, so it makes no difference. I'm guessing this is not the case in Czech, which is why this ends up being problematic. We probably want to use `UCharacter.toTitleCase` to convert the string into a suitable title case before returning it.

**Comment by moneytoo** [comment]
Locale names are "title cased" at least in the platform Settings app. This is what it uses internally: https://android.googlesource.com/platform/frameworks/base.git/+/refs/tags/android-11.0.0_r45/core/java/com/android/internal/app/LocaleHelper.java#68

**Comment by ojw28** [comment]
Thanks for the pointer!

**Comment by ojw28** [comment]
This is fixed by the three commits ref'd above (the second is a rollback, and third is a roll forward that includes a fix for the initial commit).
