### ISSUE TITLE
onAdsManagerLoaded callback never triggered 

### ISSUE THREAD

**Issue by aemre** [google/ExoPlayer#9453]
I want to access adsmanager object like:
@Override
    public void onAdsManagerLoaded(AdsManagerLoadedEvent adsManagerLoadedEvent) {
        //HERE
    }

but this cb never called.
Why this callback never triggered? How can I access adsManager object ?

**Comment by andrewlewis** [comment]
> Why this callback never triggered? How can I access adsManager object ?

When using the IMA extension there isn't currently a way to access this; see also the discussion in #9097.

Please also check #8158 for ways to do things without relying on accessing the `AdsManager` directly. What do you need the ads manager for?

**Comment by aemre** [comment]
I adsmanager for custom ads ui.
How can I custom without adsManager?

**Comment by andrewlewis** [comment]
Do you want to do UI customization following the same approach as #9504 (disabling the IMA SDK UI (with the ad campaign allowlisted to be able to do this))?

**Comment by JorgeNPAW** [comment]
Hello, I work for a company who tracks ad behavior and we are facing the same problem. 

It looks like since the last updates, when you try to access ImaAdsLoader.getAdsLoader(), it usually returns null. And so to check when it stops being null, we need to create a timer/loop since there is no callback/listener notifying this. 

But also, when it stops being null and we try to addAdsLoadedListener to the AdsLoader, it looks like it's too late because the listener has been called already even if we make the timer check every millisecond. 

We need to get on time to the AdsLoadedListener to retrieve the AdsManager/StreamManager.

**Comment by Narsuf** [comment]
Hello, I work for a company who tracks ad behavior and we are facing the same problem.

It looks like since the last updates, when you try to access ImaAdsLoader.getAdsLoader(), it usually returns null. And so to check when it stops being null, we need to create a timer/loop since there is no callback/listener notifying this.

But also, when it stops being null and we try to addAdsLoadedListener to the AdsLoader, it looks like it's too late because the listener has been called already even if we make the timer check every millisecond.

We need to get on time to the AdsLoadedListener to retrieve the AdsManager/StreamManager.

**Comment by andrewlewis** [comment]
> We need to get on time to the AdsLoadedListener to retrieve the AdsManager/StreamManager.

What specifically do you need the `AdsManager` for? For tracking ad behavior I'd have thought just the ad event listener would be enough -- see also #8158 which has instructions for listening for ad events.

**Comment by Narsuf** [comment]
I would be lossing access to adCuePoints/cuePoints from AdsManager/StreamManager with that approach.

**Comment by andrewlewis** [comment]
They are accessible in the player's timeline: see https://github.com/google/ExoPlayer/issues/8070#issuecomment-712249284.
