### ISSUE TITLE
PlayerNotificationManager notification background color not changing

### ISSUE THREAD

**Issue by broscr** [google/ExoPlayer#9456]
I created PlayerNotificationManager. But background color of the notifications does not change .It's just the color changed of the icons.

<a href="https://ibb.co/42CzpqV"><img src="https://i.ibb.co/42CzpqV/Screenshot-1632149398.png" alt="Screenshot-1632149398" border="0"></a>

```
  NotificationManager notificationManager =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);


        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
                    context.getString(R.string.app_name),
                    NotificationManager.IMPORTANCE_HIGH);

            notificationManager.createNotificationChannel(channel);
        }


        playerNotificationManager = new PlayerNotificationManager.Builder(context, 151, CHANNEL_ID)
                .setMediaDescriptionAdapter(new PlayerNotificationManager.MediaDescriptionAdapter() {
                    @Override
                    public CharSequence getCurrentContentTitle(Player player) {
                        return player.getCurrentMediaItem().mediaMetadata.displayTitle;
                    }

                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                        return null;
                    }

                    @Nullable
                    @Override
                    public CharSequence getCurrentContentText(Player player) {
                        return null;
                    }

                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback callback) {
                        if (!activity.isDestroyed()) {
                            Glide.with(activity)
                                    .asBitmap()
                                    .load(player.getCurrentMediaItem().mediaMetadata.artworkUri)
                                    .into(new CustomTarget<Bitmap>() {
                                        @Override
                                        public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                            callback.onBitmap(resource);
                                        }

                                        @Override
                                        public void onLoadCleared(@Nullable Drawable placeholder) {

                                        }
                                    });

                        }
                        return null;
                    }
                })
                .build();


        playerNotificationManager.setColor(ResourcesCompat.getColor(context.getResources(), R.color.orangeSecond, null));
        playerNotificationManager.setColorized(true);
        playerNotificationManager.setDefaults(151);
        playerNotificationManager.setUseFastForwardAction(false);
        playerNotificationManager.setUsePreviousAction(true);
        playerNotificationManager.setUseNextAction(true);
        playerNotificationManager.setVisibility(NotificationCompat.VISIBILITY_PUBLIC);
        playerNotificationManager.setUseRewindAction(false);
        playerNotificationManager.setPriority(PRIORITY_HIGH);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            playerNotificationManager.setBadgeIconType(BADGE_ICON_LARGE);
        }
        playerNotificationManager.setSmallIcon(R.drawable.ic_little_icon);
        playerNotificationManager.setPlayer(player);
```

**Comment by broscr** [comment]
@marcbaechinger I'm waiting....

**Comment by marcbaechinger** [comment]
This works for me on Android 10 with `setColor/setColorized` being set without using an artwork and [having a media session set](https://developer.android.com/reference/android/app/Notification.Builder#setColorized(boolean)). 

When you are using an artwork, the color of the notification is derived from the color of the artwork used for the given media that is currently playing. It looks like for your case of the screenshot this is white taken from the picture. This is done that way by the `MediaStyle` notification the `PlayerNotificationManager` is using.

Seems like this is not applied for Android 11 though, where the notification is turned into a mini player. Since Android 11, without an artwork it seems to fall back to the theme color the user has chosen AFAIU.

**Comment by marcbaechinger** [comment]
To refine the comment from above a bit:

I assume `playerNotificationmanager.setColor(color)` and `playerNotificationManager.setColorized(true)` is always set.

**Using the `PlayerNotificationManager` without a media session token:**

The notification is colorized when used as a notification for a foreground service. If not, only the buttons of the actions of the notifcation are colorized. When using the notification with a foreground service that houses a player to play audio when the app is in background, this can have strange effects. The reason for this is that we recommend to remove the service from the foreground when the player is paused. This allows the app to be well-behaving and to not unnecessarily use resources.

Because [the system is only colorizing the notifcation when in use with a foreground service](https://developer.android.com/reference/android/app/Notification.Builder#setColorized(boolean)), this has the effect that the notification is colorized when playback is pause, but not when playback is ongoing. So the notification would constantly change the color according to this state. This is probably not desired and not recommended.

 This applies for Android 10 and 11 and with or without returning a `Bitmap` with `PlayerNotificationManager.MediaDescriptionAdapter.getCurrentLargeIcon():Bitmap`.

**Using the `PlayerNotificationManager` with a media session token:**

Android 10 and lower: The artwork in the notification is taken from the callback`PlayerNotificationManager.MediaDescriptionAdapter..getCurrentLargeIcon():Bitmap`. When a bitmap is delivered the notification is colored according to the colors of the artwork. If no `Bitmap` is delivered by the callback, the color from `PlayerNotificationManager.setColor()` is applied when `PlayerNotificationManager.setColorize(true)` has been called with `true`. This happens independently from the notification being attached to a foreground service or not.

The artwork of the media session is apparently not used in Android 10.

Android 11 and higher: Since API 30 a media style notification is turned into a mini player in the Android Notification tray. Any media using a notification with a media session token produces such a miniplayer and they may be positioned side-by-side. 

When using a media session token with Android 11 the notification background is never applied according to `playerNotificationManager.setColor(color)`. The color is ignored by the system in any case. 

The precedence when selecting a artwork is the following:

1) the artwork of the media session metadata (similar to item currently playing). For users of the `MediaSessionConnector` this is delivered by `DefaultMediaMetadataProvider/(Timeline)QueueNavigator` or the custom `MediaSessionConncetor.MediaMetadataProvider`set to the connector.
2) the artwork delivered as a bitmap by `PlayerNotificationManager.MediaDescriptionAdapter.getCurrentLargeIcon()` is used as fallback artwork by the system that creates the mini player.
3) no artwork is selected. In this case the miniplayer is not colorized according to the `PlayerNotificationManager.setColor()` but according to the theme of the user. The value set to `setColor` is ignored in any case when using a media session on Android 11.

**Comment by broscr** [comment]
Thank you i try.
