### ISSUE TITLE
How to add subtitle to exoplayer 

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9478]
I am using exoplayer for my application . my video URL is coming from json file and I would like to add subtitle for the video . which is in srt format . can you guys help me how  to add subtitle to my exoplayer 

My exoplayer code : using exoplayer version : **implementation 'com.google.android.exoplayer:exoplayer:2.14.1'**

```
   private void setUpExoplayer(String url) {
        LoadControl LoadControls = new DefaultLoadControl();
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        ExoTrackSelection.Factory videoTrackSelectionFactory = new
                AdaptiveTrackSelection.Factory();
        trackSelector = new
                DefaultTrackSelector(VideoPlayerActivity.this, videoTrackSelectionFactory);
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this);
        renderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        simpleExoPlayer = new SimpleExoPlayer.Builder(this, renderersFactory)
                .setTrackSelector(trackSelector)
                .build();
        videoPlayer.setPlayer(simpleExoPlayer);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "ChristianGospelApp"));
        MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(MediaItem.fromUri(Uri.parse(url)));
        simpleExoPlayer.prepare(mediaSource);
        simpleExoPlayer.setPlayWhenReady(true);
    }
```
Json file :https://raw.githubusercontent.com/windowschares/charles/main/1/all_movies.json
my video URL format is mp4 and I would like to add srt format for subtitle. subtitle will be played via external link please help me regarding this

**Comment by icbaker** [comment]
You need to parse the JSON yourself, ExoPlayer can't help you with that.

Once you have a subtitle URI that you know is SubRip (.srt) then you can create a `MediaItem.Subtitle` object (MIME Type is [`MimeTypes.APPLICATION_SUBRIP`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/MimeTypes.html#APPLICATION_SUBRIP)) and pass it to `MediaItem.Builder#setSubtitles`. If you want it to be displayed by default you'll need to also pass [`C.SELECTION_FLAG_DEFAULT`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#SELECTION_FLAG_DEFAULT) to the `Subtitle` constructor.

https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks

You'll need to use `DefaultMediaSourceFactory` and not `ProgressiveMediaSource.Factory`. It may be easier to set the `MediaItem` directly on the `Player` rather than manually instantiating a `MediaSource`: https://exoplayer.dev/media-items.html
