### ISSUE TITLE
Poor RTSP playback with Axis cameras

### ISSUE THREAD

**Issue by sproctor** [google/ExoPlayer#9484]
I'm attempting to switch from the branch at https://github.com/portizb/ExoPlayer to 2.15.1. The portizb branch works fairly well.

2.15.1 spams my logs with unexpected packet messages for the first 30 seconds or so, then they're pretty rare after. https://gist.github.com/sproctor/2d12b39f62359b373d61f39d184d46f1

The stream starts off a bit distorted and after about 10 seconds, looks good. Occasionally there appear to be clipped frames, a bit of distortion in the middle of a frame. This doesn't happen with the portizb branch.

I don't know how to record a stream from the camera, but I can do it if someone points me to a howto.

**Comment by claincly** [comment]
Looking at the spam lines, it seemed that there are quite some number of packets lost (or late) on their ways. For example, 24086 is not received before 24087. After receiving 24087, 24089 is received instead of 24088.

```
Received RTP packet with unexpected sequence number. Expected: 24086; received: 24087. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 24088; received: 24089. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 24090; received: 24092. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 24093; received: 24097. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 24098; received: 24101. Dropping packet.
```

You can try tweaking this number (30), to a bigger number, say 100. This lets ExoPlayer waits longer for out-of-order packets.

https://github.com/google/ExoPlayer/blob/2a88f0fb295ff5b56e6fbcbe7e91bdf922cbae13/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/RtpExtractor.java#L209
