### ISSUE TITLE
how to avoid "Player is accessed on the wrong thread." in aidl

### ISSUE THREAD

**Issue by ghoulhyk** [google/ExoPlayer#9485]
I start a service on child process mode to play music, in order to keep playing when app be killed by system. And I use aidl to communicate between main app and ExoPlayer in child process.
`new SimpleExoPlayer.Builder(context).setLooper(Looper.myLooper()).build();`
this is how i instantiate the ExoPlayer, but it warning me "Player is accessed on the wrong thread."
So how can i  instantiate the ExoPlayer, or has there some better way to implement this function.
I`m a non-native english speakers, so the language maybe not smoothly，thanks for your help

**Comment by krocard** [comment]
The looper passed in `setLooper` must be the thread that your app will use to call the player. The issue is that AIDL is specifically designed to dispatch call to a thread pool:

> Calls from a remote process are dispatched from a thread pool the platform maintains inside of your own process. You must be prepared for incoming calls from unknown threads, with multiple calls happening at the same time. In other words, an implementation of an AIDL interface must be completely thread-safe. Calls made from one thread on same remote object arrive in order on the receiver end.

https://developer.android.com/guide/components/aidl.

As the player is NOT thread safe, making direct calls from AIDL to the player, is not possible.

Do you really need the concurrency access? If not, consider implementing a [https://developer.android.com/guide/components/bound-services#Messenger](Messenger) instead as recomended by https://developer.android.com/guide/components/aidl top disclaimer.
