### ISSUE TITLE
Setting surface frame rate

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9486]
I understand that ExoPlayer uses [Surface.setFrameRate()](https://github.com/google/ExoPlayer/blob/2a88f0fb295ff5b56e6fbcbe7e91bdf922cbae13/library/core/src/main/java/com/google/android/exoplayer2/video/VideoFrameReleaseHelper.java#L368) to leverage the lightweight refresh rate swithing on Android 11 and newer ([as explained here](https://developer.android.com/guide/topics/media/frame-rate)).

To offer similar pulldown free experience on older devices, I used the `preferredDisplayModeId` switching in my app. I noticed that ExoPlayer does not report frame rate in lots of user media files (mostly local mkvs). But to get around this, I can use `ffprobe`.

Does this mean that on Android 11+, the refresh rate swithing only works when ExoPlayer knows the video frame rate? Is there any way how I could supply the externally detected frame rate to the surface? If not, are there any plans for such API or should we just create/manage our own surface (I didn't really explored what does it take)?

**Comment by krocard** [comment]
You can disable `Surface.setFrameRate` calls from ExoPlayer using `VIDEO_CHANGE_FRAME_RATE_STRATEGY_OFF`.
I'm not sure we have any plans for an app to provide their own frame rate, except maybe by wrapping extractors and overriding the values, but that is a lot of work.

**Comment by ojw28** [comment]
> I understand that ExoPlayer uses Surface.setFrameRate() to leverage the lightweight refresh rate switching on Android 11 and newer (as explained here).

This is correct, although note that the display has to actually support seamless refresh rate switching for this to do anything useful. It's a hint to the underlying platform, which can update the display refresh rate or not depending on what the hardware supports.

> Does this mean that on Android 11+, the refresh rate switching only works when ExoPlayer knows the video frame rate?

As of `2.13.0`, ExoPlayer will dynamically infer the video frame-rate from the individual frame timestamps in order to call `Surface.setFrameRate()` even if the video stream does not declare a fixed frame-rate. Support for this was added in [this commit](https://github.com/google/ExoPlayer/commit/855db95fb363a3909624aec5c477dee5d2d89057#diff-0ecc8c850fd29360d8c13018e3c4d34ac1ffb85b0183d94c95f320cdf3a89f68). The approach is able to adapt to dynamic frame-rate changes in the stream.

I think you're probably defining "knows the video frame rate" as whether it's set in the track `Format`, which is only the case if the video stream declares a fixed frame-rate. In which case no, your statement is not correct. `Surface.setFrameRate()` will be called for the vast majority of video streams. The only case where it wont be called is if the video has really inconsistently spaced video frames (i.e., is genuinely not fixed frame-rate, even when only looking at small parts of the stream).

> You can disable Surface.setFrameRate calls from ExoPlayer using VIDEO_CHANGE_FRAME_RATE_STRATEGY_OFF.
I'm not sure we have any plans for an app to provide their own frame rate, except maybe by wrapping extractors and overriding the values, but that is a lot of work.

Note that this is not released yet. It's available in the `dev-v2` branch, and was added in [this commit](https://github.com/google/ExoPlayer/commit/0097a79c2d221dc55ef1147f6f3144f2735a997a). As @krocard notes, it provides the ability to disable calls to `Surface.setFrameRate` made from within ExoPlayer, and is useful for the case in which you want to call this method directly from application code instead.

**Comment by moneytoo** [comment]
> As of `2.13.0`, ExoPlayer will dynamically infer the video frame-rate from the individual frame timestamps in order to call `Surface.setFrameRate()` even if the video stream does not declare a fixed frame-rate. Support for this was added in [this commit](https://github.com/google/ExoPlayer/commit/855db95fb363a3909624aec5c477dee5d2d89057#diff-0ecc8c850fd29360d8c13018e3c4d34ac1ffb85b0183d94c95f320cdf3a89f68). The approach is able to adapt to dynamic frame-rate changes in the stream.
> 
> I think you're probably defining "knows the video frame rate" as whether it's set in the track `Format`, which is only the case if the video stream declares a fixed frame-rate. In which case no, your statement is not correct. `Surface.setFrameRate()` will be called for the vast majority of video streams. The only case where it wont be called is if the video has really inconsistently spaced video frames (i.e., is genuinely not fixed frame-rate, even when only looking at small parts of the stream).
> 
> >

Thank you very much for your answer. This is really helpful.
