### ISSUE TITLE
Key moments highlight in Exoplayer video bar

### ISSUE THREAD

**Issue by mallikarjunch09** [google/ExoPlayer#9505]
<img width="319" alt="Screenshot 2021-09-29 at 3 01 16 PM" src="https://user-images.githubusercontent.com/54542577/135242681-b481fb3a-e83e-47d2-bc74-35efbad7c8c3.png">
Hi Guys, I'm trying to achieve a key moments highlights**(yellow patches on video player progress bar)** in the exoplayer video progress bar. 
I'm not getting how to achieve this functionality in exoplayer android
Is there any way to add some highlights(yellow patches on the bar to some duration) in the video progress bar

for example there is total 60 second video, in this period i want to highlight for set of 10 to 15 seconds, 30 to 35 seconds, 50 to 55 seconds etc

**Comment by krocard** [comment]
ExoPlayer doesn't have any native support for this feature. Nevertheless you can customize the [DefaultTimeBar](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/DefaultTimeBar.java) view to add such indicators.

Assigning to @ojw28 to track this possible improvement.

**Comment by ojw28** [comment]
It's not really feasible for us to accommodate UI requests such as this one, since they tend to be application specific to application use cases. At some point, if you need custom playback controls, you need to implement them yourself in application code (feel free to fork those provided by ExoPlayer as a starting point!).
