### ISSUE TITLE
Getting Rebuffering event

### ISSUE THREAD

**Issue by danish241194** [google/ExoPlayer#9511]
I have a requirement of doing some stuff whenever rebuffering occurs.Is there any way to get this event whenever rebuffer occurs

rebuffer event is buffering event which excludes initial joining and buffering after seek.

**Comment by krocard** [comment]
By rebuffering event, do you mean:

 1. having the player go to state buffering from state ready.
 2. having to download a segment never downloaded
 3. having to download a segment that was already downloaded (eg due to a different track selection)
 4. having to flush and rebuffer some audio due to an audio output change
 5. some other buffering event

**Comment by danish241194** [comment]
Yes, above mentioned points are contributing for my re-buffering event definition. In simple words i can say whenever player goes to Buffering state from Ready state without any user intervention (seek ) .

**Comment by krocard** [comment]
`Listener.onPlaybackStateChanged` will be called when transitioning from state `READY` to `BUFFERING`. Nevertheless, it will not tell you why. `Listener.onPositionDiscontinuity` will be called if there was a seek, with the reason.
By listening to `Listener.OnEvent`, you will have all this information in one callback.

**Comment by krocard** [comment]
Does this answer your question?
