### ISSUE TITLE
Support for 10 bit depth in the AV1 extension (`libgav1`)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9523]
Does the AV1 extension (`libgav1`) support 10 bit depth? If not, shouldn't it be excluded as a render for video with 10 bit depth?

When I set `EXTENSION_RENDERER_MODE_ON` and attempt to play 10 bit 1920x1080 video, the device decoder (`c2.android.av1.decoder`) is skipped because of reported incompatibility and extension renderer is used - but `libgav1` is unable to render it:

```
com.google.android.exoplayer2.ext.av1.Gav1DecoderException: gav1GetFrame error: High bit depth (10 or 12 bits per pixel) output format is not supported with YUV surface.
com.google.android.exoplayer2.ExoPlaybackException: Libgav1VideoRenderer error, index=0, format=Format(1, null, null, video/av01, null, -1, null, [1920, 1080, 23.976048], [-1, -1]), format_supported=YES
```

The device decoder is skipped because `VideoCapabilities.isSizeSupported(1920, 1080)` returns `false`. The device reports capability for AV1 video only up to 1920x1072 pixels. However when I disable the use of the AV1 extension, 1920x1080 videos play - 8 bit videos play seamlessly (checked VFPO), 10 bit videos play as well, though they shutter depending on bitrate/complexity. I received report of this behavior on Realme X2 Pro device (Snapdragon 855+, Android 11) but I was able to duplicate it on my own device (OnePlus 7 - Snapdragon 855, Android 10).

Unlike this device SW decoder, `libgav1` seems to handle even resolutions like 2560x1440 (4k plays as well, but may shutter depending on bitrate/complexity) so it's usefull as fallback renderer.

**Comment by andrewlewis** [comment]
> Does the AV1 extension (libgav1) support 10 bit depth? If not, shouldn't it be excluded as a render for video with 10 bit depth?

It looks like it's supported when using `VIDEO_OUTPUT_MODE_YUV` (using `VideoDecoderOutputBufferRenderer`, with conversion down to 8-bit) but not `VIDEO_OUTPUT_MODE_SURFACE_YUV` (rendering to `Surface`/`ANativeWindow`).

I think we found that the former was higher performance, so I'd recommend switching to that mode. Is this an acceptable short term workaround even though it isn't actually fixing the capabilities reporting?

> Unlike this device SW decoder, libgav1 seems to handle even resolutions like 2560x1440 (4k plays as well, but may shutter depending on bitrate/complexity) so it's usefull as fallback renderer.

The level capabilities for the device decoder were updated by [this change](https://android-review.googlesource.com/c/platform/frameworks/av/+/1727155) and the max resolution was also increased [here](https://android-review.googlesource.com/c/platform/frameworks/av/+/1743306). So from Android 12 I think the decoder in the framework can be used.

Just in case it's useful info: the device decoder `c2.android.av1.decoder` is probably also `libgav1` (I say probably because theoretically the device maker may have replaced the implementation provided in AOSP). I'm a bit surprised you are seeing dropped frames with the device decoder at the same resolutions where the extension works.

**Comment by moneytoo** [comment]
> I think we found that the former was higher performance, so I'd recommend switching to that mode. Is this an acceptable short term workaround even though it isn't actually fixing the capabilities reporting?

Thank you for the suggestions. I will need to learn more about that (and try on my own) to understand how well this fits/works for general purpose player of user content.

> I'm a bit surprised you are seeing dropped frames with the device decoder at the same resolutions where the extension works.

To clarify this - I wasn't able to directly compare the device decoder and the AV1 extension. The device decoder plays everything up to 1920x1080 without shuttering, when the content is 8 bit. The shuttering was with 10 bit content which I wasn't yet able to try with the AV1 extension. However the AV1 extension allows me to play higher resolution content (like 1440p) which the device decoder fails to render at all.

**Comment by andrewlewis** [comment]
Thanks. I'll close this for now on the assumption that the surface YUV rendering option will address the immediate problem. We could try to add workarounds for the device decoder's underreporting of capabilities or for the extension decoder capability overreporting (dependent on output mode) but I'm not convinced it's worth the effort and added code complexity currently. Please reopen this issue or file a new one if this approach doesn't work out.
