### ISSUE TITLE
Casting HLS AES content

### ISSUE THREAD

**Issue by SashiWork** [google/ExoPlayer#9564]
Hi,

I'm trying to find a way to Cast the HLS AES content.
But I couldn't find a way to set a Media Source with custom DataSource.Factory to the CastPlayer.

If there is any way we can achieve this through CastPlayer, please let me know.

**Comment by claincly** [comment]
Why do you have to set a DataSource factory for playing back DRM content?

Maybe I'm missing something, please clarify.

**Comment by SashiWork** [comment]
We are not using DRM content,
We are using HLS AES encrypted content provided by our BE team. To play the content we will be passing the Token for it through DataSource.

If any clarifications required please do let me know.

**Comment by SashiWork** [comment]
Hi Team, 

Can anybody please help me out here.
Let me know if it is not possible.

**Comment by nvrubl** [comment]
@SashiWork hi, you can't set a Media Source with custom DataSource.Factory to the CastPlayer in order to play HLS encrypted content. I've had the same problem. So what i did (afaik it's the only solution)  - 
1. Create custom web receiver 
2. Pass all of the validation headers from the app into your own custom web receiver
3. Do all of the token auth or whatever logic you have in the web receiver (for example if you need to set some custom headers in order to retrieve m3u8 playlist, you can do that in web receiver)
 [https://developers.google.com/cast/docs/web_receiver/basic](url) - can help you with getting started. 
But keep in mind that **you need to use your own custom made web receiver** and **not the default one**, because of the additional headers or whatever logic you want to add there.

**Comment by SashiWork** [comment]
Thank you for clearing it to me.
