### ISSUE TITLE
Why Format.language use 2-letter code?

### ISSUE THREAD

**Issue by sunnybaby** [google/ExoPlayer#9568]
Hello,

Recently, we found that the language code will be defaultly converted to 2-letter when Format built.
Related codes shown below.
[https://github.com/google/ExoPlayer/blob/95e6db931a047775c1aa792c452be7996167a08f/library/common/src/main/java/com/google/android/exoplayer2/Format.java#L924](url)
>   private Format(Builder builder) {
    id = builder.id;
    label = builder.label;
    language = Util.normalizeLanguageCode(builder.language);

[https://github.com/google/ExoPlayer/blob/95e6db931a047775c1aa792c452be7996167a08f/library/common/src/main/java/com/google/android/exoplayer2/util/Util.java#L678](url)
> if (languageTagReplacementMap == null) {
      languageTagReplacementMap = createIsoLanguageReplacementMap();
    }
    @Nullable String replacedLanguage = languageTagReplacementMap.get(mainLanguage);

[https://github.com/google/ExoPlayer/blob/95e6db931a047775c1aa792c452be7996167a08f/library/common/src/main/java/com/google/android/exoplayer2/util/Util.java#L2478](url)
>   private static HashMap<String, String> createIsoLanguageReplacementMap() {
    String[] iso2Languages = Locale.getISOLanguages();
    HashMap<String, String> replacedLanguages =
        new HashMap<>(
            /* initialCapacity= */ iso2Languages.length + additionalIsoLanguageReplacements.length);
    for (String iso2 : iso2Languages) {
      try {
        // This returns the ISO 639-2/T code for the language.
        String iso3 = new Locale(iso2).getISO3Language();
        if (!TextUtils.isEmpty(iso3)) {
          replacedLanguages.put(iso3, iso2);
        }

From the variable names and comments, I think it's intended to convert language code from iso3 to iso2.
But actually,  _Locale.getISOLanguages()_ returns language code following iso1. Related specs:
[https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getISOLanguages()](url)
[https://www.iso.org/iso-639-language-codes.html](url)

So I'm not sure whether it's a bug or my misunderstanding.
Wish for your confirmation and reply.
Thanks!

**Comment by tonihei** [comment]
> From the variable names and comments, I think it's intended to convert language code from iso3 to iso2.
> But actually, Locale.getISOLanguages() returns language code following iso1.

I think the confusion may be that ISO 630 Part **1** covers the **2** letter codes and ISO 630 Part **2** the **3** letter codes. The variable names refer to the length of the codes, not the parts of the ISO spec. 

> Why Format.language use 2-letter code?

The general reason is that we need to normalize language codes to a single format that allow comparisons, ordering etc. ExoPlayer receives language codes from 3 different sources: The system Locale languages, the media itself and from user preferences. We considered using the 3 letter codes as our normalized code, but it turns out that converting 2-letter to 3-letter codes is much harder to do correctly on Android than converting 3-letter to 2-letter codes. Hence, we normlize to ISO 630 Part 1 2-letter codes.
