### ISSUE TITLE
video uploaded from ios and  Video being played without audio on android 

### ISSUE THREAD

**Issue by sreereddymenon** [google/ExoPlayer#958]
my client has android and ios platform apps .if i have uploaded from ios and audio fails to play on android.  

I  have tired using my response URL on demo app.I have got the same result..audio fails to play .
URL for testing is . 

https://v2r1-dot-default-dot-zinc-cooler-662.appspot.com/media/224516765274051541359668846535909199412

any help?

**Comment by ojw28** [comment]
What code is responsible for generating the media file when it's recorded on iOS? Is that your own code, or is iOS generating the media file for you? Upon first inspection, the media appears to have some invalid data in its Mp4AudioSampleEntry box, which is preventing information about the audio track from being parsed.

**Comment by ojw28** [comment]
This happens because ExoPlayer's Mp4Extractor claims compatibility with QuickTime files, but does not parse QuickTime `SoundDescription` entries correctly. Useful links:

http://lists.apple.com/archives/QuickTime-API/2007/Oct/msg00061.html
https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html
https://searchcode.com/codesearch/view/70087452/#l-69

I think we need to:
- Have Mp4Extractor read the brand out of the ftyp atom, to determine whether the file is QT rather than MP4.
- Have AtomParsers parse `SoundDescription` entries rather than `AudioSample` entries if so (nb - the two are very similar, although structurally slightly different).

**Comment by ojw28** [comment]
We'll push a fix for this relatively soon. Note that we don't officially claim to support QuickTime files, so whilst we'll fix things to correctly play this sample, we're supporting QuickTime on a "best effort" case only. For best compatibility, you should use MP4 instead.

**Comment by sreereddymenon** [comment]
Thanks a lot !!

**Comment by ojw28** [comment]
This is fixed on the dev branch.

**Comment by sergiomarquesmoura** [comment]
Will you release a new version to jCenter with this fix included? Would be much appreciated
