### ISSUE TITLE
how to get bitrate from mp4?

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#9587]
I try to get bitrate from trackFormat when maybeFinishPrepare .
But it is -1. How can I get the correct value.
 private void maybeFinishPrepare() {
    for (int i = 0; i < trackCount; i++) {
      Format trackFormat = Assertions.checkNotNull(sampleQueues[i].getUpstreamFormat());
      Log.i("test", " bitrate = " +trackFormat.bitrate );
  }

I want to calculator the value when processMoovAtom. Is it right?

  
    private void processMoovAtom(ContainerAtom moov) throws ParserException {
        .......
        for(int i=0;i<this.tracks.length;i++) {
            long count = 0;
            for (int j=0;j<this.tracks[i].sampleTable.sampleCount;j++) {
                count+= this.tracks[i].sampleTable.sizes[j];
            }
            long bitrate = 1000 * 1000 * 8 * count/this.durationUs ;
        }

        extractorOutput.endTracks();
        extractorOutput.seekMap(this);
    }

**Comment by tonihei** [comment]
We generally don't fill in the bitrate for progressive formats because it's unclear what's it's used for. The bitrate value is meant to inform adaptive track selections, but this doesn't apply to progressive formats like MP4. It's also unclear how the bitrate is defined exactly. Your example code above uses the actual samples only, but it's also possible to use the entire file size including all additional metadata, headers and unrelated information. See also the same discussion in #2638 which was closed eventually because there wasn't a good reason to implement this feature.
