### ISSUE TITLE
Impossible to inherit from DefaultHttpDataSource

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#9607]
Constructors in class `DefaultHttpDataSource` are deprecated or private in the current ExoPlayer version 3.15.1. So they will be probably removed in version 3.16.x. It's mean an application will not be ably to inherit and override some of the default functionality. We are overriding just `DefaultHttpDataSource#open(DataSpec)` method to set our `SSLSocketFactory` as default in `HttpsURLConnection`. Could you please suggest any suitable alternative solution?

**Comment by mike-targetr** [comment]
I share your frustration with this class. It is common to want to modify how the HttpURLConnection is first created and also perform changes at the point where the InputStream is opened. However, the current implementation makes this really difficult. Could this class be refactored to keep these points in mind?

**Comment by ojw28** [comment]
For the original issue, we probably just need to change the private constructor to be protected instead. Would that solve your issue @chladto1 ? @icbaker - Should we have something in our style guide about this? I can't think of a case where a non-final class with only private constructors ever makes sense? I could be wrong, but I think this came up in the context of another class as well.

@mike-targetr - Your issue sounds a bit different. We're open to allowing useful extension points, but without understanding exactly what you're trying to do, it's a little hard to know what type of refactoring would be most suitable. I would somewhat debate the "it is common" part of your statement. Given the number of users of ExoPlayer and the low volume of requests about this topic, I think a tiny fraction of developers need this, and they likely have fairly specific needs. Please file a new issue that explains specifically what you need to modify, and we can take a look at accommodating that.

Assigning to @icbaker for the style question (and to make the trivial visibility change if you agree that's the right thing to do!).

**Comment by icbaker** [comment]
> For the original issue, we probably just need to change the private constructor to be protected instead. Would that solve your issue @chladto1 ? @icbaker - Should we have something in our style guide about this? I can't think of a case where a non-final class with only private constructors ever makes sense? I could be wrong, but I think this came up in the context of another class as well.

Alternatively should `DefaultHttpDataSource` be (eventually) `final`? That would be the natural step when we delete the currently-deprecated constructors. 

I think the requested functionality (set a `SSLSocketFactory` as default in `HttpsURLConnection`) can be implemented using a `ResolvingDataSource` that wraps a `DefaultHttpDataSource` and putting the the call to `HttpsURLConnection#setDefaultSSLSocketFactory` in `Resolver#resolveDataSpec` (the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern))

Composition is generally preferred over inheritance where possible (Effective Java 3rd Ed, Item 18).

**Comment by chladto1** [comment]
@ojw28 Yes, that would be great!
@icbaker The most effective code is no code. More code means more complexity and more potential bugs.

Rich Skrenta writes:
>Code is bad. It rots. It requires periodic maintenance. It has bugs that need to be found. New features mean old code has to be adapted. The more code you have, the more places there are for bugs to hide. The longer checkouts or compiles take. The longer it takes a new employee to make sense of your system. If you have to refactor there's more stuff to move around. Furthermore, more code often means less flexibility and functionality. This is counter-intuitive, but a lot of times a simple, elegant solution is faster and more general than the plodding mess of code produced by a programmer of lesser talent.

**Comment by mike-targetr** [comment]
One example is adding a Proxy to the HttpURLConnection. This is something that should be easy, but AFAIK it is not straightforward? Other requirements could probably be achieved by the ResolvingDataSource - that's new to me. With regards to the InputStream - this is to intercept/wrap what is being read / monitor it etc - admittedly this is quite custom. I think protected methods at point of opening Connection and getting the InputStream would maximize the flexibility of this class.

**Comment by icbaker** [comment]
@chladto1 I assume you're not literally claiming that reducing lines-of-code should be the ultimate goal of a software project with no other considerations? Inheritance may result in fewer lines of code but it can lead to systems that are harder to reason about. This isn't just my opinion or that of Effective Java: https://google.com/search?q=prefer+composition+over+inheritance

@mike-targetr Please file a new issue with specific request(s) so we can discuss them separately.

**Comment by chladto1** [comment]
@icbaker Yes, in physics simulator, you can do a collision detection by very simple algorithm with complexity O(N²) or better, write spatial division algorithm that can be close to O(C * N) but requires a lot of code, especially in asynchronous running. But this is not a physics simulator.

Sorry, but I do not see a reason, why I shouldn't be able to inherit a class in my own code, override a method and add one line of code. This requires exactly 6 lines of code that anyone can understand in seconds.

Using `ResolvingDataSource` requires some additional knowledge, read documentation, that in real life, many people do not. I do not say that your solution is bad, but why to do things more complex that is really needed :)

**Comment by icbaker** [comment]
@chladto1 since I believe you're asking about setting a static property of `HttpsURLConnection`, is there a reason you need to do this in an ExoPlayer component at all? It seems a little surprising to be touching such a global property so deep in a specific library's component. If you really do want to change all `HttpsURLConnection` instances you could perhaps make the call elsewhere in your app code and, since it's a static property, it would have the desired effect on `DefaultHttpDataSource` (and any other code that instantiates `HttpsURLConnection`) - that would avoid you even needing to use `ResolvingDataSource`.

I'm going to close this as it doesn't seem that the use-case as described requires inheriting from `DefaultDataSource`.

As @ojw28 says, we're open to considering other requests for customisation hooks (both for this class and others), please file new issues with specific requests that we can evaluate. Depending on the request it may make sense to redesign `DefaultHttpDataSource` to be extensible (by exposing some of it's internal workings as `protected`), or designing it to take some compositional components.

**Comment by chladto1** [comment]
@icbaker We can no do this, because we are providing SDK and an application can set its own `SSLSocketFactory` in every BE request which it actually does.

**Comment by ojw28** [comment]
I filed https://github.com/google/ExoPlayer/issues/9626 to track what I think are the two concrete requests in this issue.

> We are overriding just DefaultHttpDataSource#open(DataSpec) method to set our SSLSocketFactory as default in HttpsURLConnection.

This sounds extremely fragile to me. The socket factory you're setting is going to impact on other requests being made by code within your application, and is also subject to race conditions if some other code is also setting some other default factory. You almost certainly should be using the non-static `HttpsURLConnection.setSSLSocketFactory` method instead. Doing so is difficult currently for some of the reasons mentioned in this issue. We can use https://github.com/google/ExoPlayer/issues/9626 to track adding proper support for this use case.

> With regards to the InputStream - this is to intercept/wrap what is being read / monitor it etc - admittedly this is quite custom.

This really does seem like a case where composition would be a better option. It's certainly a lot more flexible, since it allows you to apply the same monitoring to all other `DataSource` implementations too, rather than just non-`DefaultHttpDataSource`. We actually have something similar within the library, in [StatsDataSource](https://github.com/google/ExoPlayer/blob/r2.15.1/library/core/src/main/java/com/google/android/exoplayer2/upstream/StatsDataSource.java), which you could take a look at as a point of reference for a nice way of doing this.

**Comment by chladto1** [comment]
@ojw28 Yes, I agree, overriding `DefaultHttpDataSource.open(DataSpec)` can be very fragile and better would be to override `DefaultHttpDataSource.openConnection(URL)` and set `HttpsURLConnection.setSSLSocketFactory(SSLSocketFactory)` but this method cannot be overridden in the current implementation.
