### ISSUE TITLE
Android 12 Support?

### ISSUE THREAD

**Issue by jrw95** [google/ExoPlayer#9609]
Hello,

We align our SDK Android OS support with ExoPlayer's `targetSdkVersion ` and `compileSdkVersion`, and we're wondering when you'll be supporting Android 12.

From the release notes, there was an issue fixed in r2.14.2 to add a flag required by Android 12, but that's the only mention of that OS level. In the meantime, we're planning to acquire devices to test our SDK with r2.14.2 (our currently supported version).

Thanks very much.

**Comment by ojw28** [comment]
We'll be making some additional improvements for Android 12 compatibility in 2.16, which you can read about in the [dev branch release notes](https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md). Whether you care about these changes really depends on how you're using the library. If you don't use `DownloadService` and don't intend to start calling `Surface.setFrameRate` directly to perform non-seamless display mode changes (this is a new feature in Android 12), then you don't really need to wait. For the other two release notes:

* The one about platform transcoding is only relevant if you intend to explicitly enable it in your application manifest, which I doubt you want to do.
* The WorkManager one is important if you use that extension, but you can upgrade the dependency in your own `build.gradle` independently of updating to a newer release of ExoPlayer.

Finally, it should be noted that our Cast extension depends on the Cast SDK, and that's yet to receive an update to be Android 12 compatible. They're working on it.

**Comment by ojw28** [comment]
A couple of additional points:

* I don't think `compileSdkVersion` is relevant. You can pick any value that's at least as large as the largest value specified by the libraries you depend on. I can't think of a good reason why you shouldn't just always have it set to the highest stable version.
* The reason our `targetSdkVersion` is set to 30 rather than 31 in the `dev-v2` branch (and possibly 2.16) is related to Robolectric adding support for Android 12, which is pending in https://github.com/robolectric/robolectric/pull/6776. So you can consider 2.16 as targeting 31, even if that's not what our `constants.gradle` file says. We may want to look at whether we can split out a separate target version specifically for unit tests, so that this isn't a point of confusion next year!
