### ISSUE TITLE
How to write custom shuffle order

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#9611]
ExoPlayer 2.15.1

This is probably a feature requests, but I can't find a proper way to tell exoplayer to invalidate it's timeline / window indexes.
Then end goal is that doing a `seekTo(windowIndex, x)` would trigger a reload of the media at said window index and not reuse it's current internal and reuse the media.
Even after a `stop()` + `prepare()` the media is not reloaded.
My current solution is to seekto a different index then seekto the proper one but this sometimes trigger a little sound glitch.

**Comment by ojw28** [comment]
Generally speaking, a media item should not be changing its content underneath the player, so it's unclear why triggering a reload would ever be necessary. Please could you explain the use case in more detail?

**Comment by Tolriq** [comment]
@ojw28 Actually the media item does not really change, the playlist is managed 100% outside of ExoPlayer as the playlist system is used for many other players and duplicating the current shuffle logic is really complex with current CustomShuffle stuff (I have not figure out how).

So the playlist of ExoPlayer is just a list of "pointers". So window index 1, 2, 3 points to file 1 2 3 when not shuffled but 3 1 2 in shuffled mode. This works well as the file next follow the next randomized and everything. Properly support playlist item moving, The only issue is that since I can't invalidate the indexes, preloading of the next item needs my hack if it has started and breaks the gapless when next item changes + if the user try to play the window index before the shuffle since the index for ExoPlayer have not changed then it does not load the new item that is actually at this index.

Everything works nicely and fit my need, I just need to find a better way to invalidate index without touching the playlist.
It is also useless to clear / read the fake playlist in ExoPlayer as it would not change it's current window index :(

Edit: So the needs would maybe more to be tell that the playlist have changed without having it changed and a way for us to tell ExoPlayer it's new currentWindow based on the new playlist content.

**Comment by Tolriq** [comment]
@ojw28 
Ok so I actually could fix the gapless issue is there was a `getMediaSourceAt` that allows me to get the next mediasource then remove it then add it again, it properly reset. And I can live with the small glitch when trying to restart a song at same index as it's quite rare.

When using the `getMediaItemAt` then remove / add it again, playback fails as the proper datasource is no more involved and ExoPlayer can't load the media. (Error with `onPlayerError@609: onPlayerError: 2001 / java.net.MalformedURLException: unknown protocol: hash` meaning it does not goes through the dataSourceFactory defined on the original mediaSource.

Any reason there's no such function or why the MediaItem is then wrongly handled ?

Edit: Both getMediaSourceAt and removeMediaSource are missing for this to work.

**Comment by Tolriq** [comment]
@ojw28 Should I open a separate issue for the missing `getMediaSourceAt` / `removeMediaSource` and `getMediaItemAt` not properly replacing it? (Depending on the case it's either a feature request or a bug report don't have enough knowledge about internals)

**Comment by ojw28** [comment]
I'm really struggling to understand much of this issue, which is making doing anything about it pretty hard. E.g., sentences like "This works well as the file next follow the next randomized and everything" don't make sense.

Re the questions toward the end of this thread:

There is a 1:1 correspondence between `MediaItem` and `MediaSource`, so a `removeMediaSource(int)` method would do exactly the same thing as `removeMediaItem(int)` already does. You can think of the `MediaItem` as the immutable description of the media, and the `MediaSource` as the component that actually contains functionality for loading it. When you add a `MediaItem` to the player, a corresponding `MediaSource` is built internally by a `MediaSourceFactory`. For advanced use cases you can build and pass ` MediaSource` directly from application code, in which case the player retrieves the corresponding `MediaItem` by calling `MediaSource.getMediaItem`.

> When using the getMediaItemAt then remove / add it again, playback fails as the proper datasource is no more involved and ExoPlayer can't load the media. (Error with onPlayerError@609: onPlayerError: 2001 / java.net.MalformedURLException: unknown protocol: hash meaning it does not goes through the dataSourceFactory defined on the original mediaSource.

It sounds like you've initially created the `MediaSource` yourself in application code, but then the second time you add it you're passing the `MediaItem`, in which case a `MediaSource` will be built internally by a `MediaSourceFactory` as described above. So you're getting a different `MediaSource` built in a different way, which is why the `DataSource` you're expecting to be used isn't being used.

The cleanest way for you to fix this, if possible, is:

1. Write a `MediaSourceFactory` implementation that will generate the `MediaSource` instances that you need for your application. Pass this to the `Builder` when creating your player instance.
1. Never create `MediaSource` instances in your application code (other than in your `MediaSourceFactory` implementation, which you give to the player to use). Use the `MediaItem` based player APIs for everything.

You should find that this does what you need.

**Comment by ojw28** [comment]
@marcbaechinger - Whilst I don't think it's required for this use case, I guess there is a question about whether `ExoPlayer` should define `getCurrentMediaSource()` and `getMediaSourceAt()` methods for completeness. `ExoPlayer` adds setters that take `MediaSource` instances that are equivalent to the `MediaItem` based methods defined in `Player`, but does not add corresponding getters. Is that an omission or by design?

**Comment by Tolriq** [comment]
@ojw28 
1) I'm not native English speaker so doing my best to be understood with small sentences.

The initial need was to have access to activeDataSource in onPositionDiscontinuity 
https://github.com/google/ExoPlayer/issues/7525
The solution was to assign a specific Factory to each media source so here we are and why I need to be able to remove the MediaSource to get the MediaSource then be able to add it again. I can't rebuilt the MediaSource from the MediaItem.

Now about the playlist issue, I need to handle the playlist outside of ExoPlayer as the internals are reused for many different kind of players and does not match how ExoPlayer handles it. The current shuffle mode ShuffleOrder does not seems to allow me to duplicate my actual logic inside ExoPlayer to have it do the exact same thing as the other players.

So my solution is that in ExoPlayer I'm always in non shuffle mode and the ExoPlayer playlist is just some special url that indicate their position, then the datasource use the real playlist to actually load the proper item, and via on position discontinuity I can update the application real playlist position playlist that is different from ExoPlayer one.
This works perfectly but generate 2 edge case because if the playlist change I can't indicate that to ExoPlayer so that it invalidate it's timeline.
1) If I try to seekTo window position 2 and active item was position 2 for ExoPlayer then ExoPlayer does not actually reload the item from the source it reuse it's internal state. (IMO this could be problematic if there's need to for example refresh a token or something). And I did not find a way even with a stop / prepare to force it. Only solution is to seek to another windowIndex then back to that one.
2) If the next mediaItem have started to load for gapless then it's also not invalidated (This is normal as I can't invalidate the timeline), This is where I need to be able to remove the mediaSource and add it back at the same place to have ExoPlayer properly start to load the proper item.

I hope it's more clear.

Still a TL;DR to be very clear: 
> There is a 1:1 correspondence between MediaItem and MediaSource, so a removeMediaSource(int) method would do exactly the same thing as removeMediaItem(int) already does.

This is not true from the returned value point of view, one return a MediaItem, the other would return a proper MediaSource allowing me to add it back to force the ExoPlayer reset, something that I can't do with the MediaItem.

**Comment by ojw28** [comment]
> This is not true from the returned value point of view, one return a MediaItem, the other would return a proper MediaSource allowing me to add it back to force the ExoPlayer reset, something that I can't do with the MediaItem.

If you're creating the `MediaSource` instances in application code, just keep them in a list in application code? Why do you need the player to give them back to you? Admittedly it would be slightly more convenient, which is where my question to @marcbaechinger above comes from, but I don't see why you'd be reliant on this.

**Comment by marcbaechinger** [comment]
> whether ExoPlayer should define getCurrentMediaSource() and getMediaSourceAt() methods for completeness. Is that an omission or by design?

I don't see a design reason that would make this an omission. :) 

The API that the `MediaSource` interface offers is actually not for being called by app code but by the player and probably solely on the playback thread. Since the actual design is that the media source is either created by the app or internally by the `MediaSourceFactory` having such a method wouldn't serve a use case I can think of except the one that is mentioned in this thread, which is, for being retrieved just to be re-added again. This seems quite a marginal use case to me.

It's also worth noting that in the case of the `DefaultMediaSourceFactory` the actual type of the returned media source of such a method may be surprising for the user and calling any method on such a source may not called the source that is expected to be called (complex media source composition). So avoiding this confusion is probably by design. :) 

Given that an app can use the `set/addMediaSource` methods or inject a custom `MediaSourceFactory` in which also a custom `DataSourceFactory` can be injected, I don't really see a common need for these methods to be honest. Even for the use cases explained here in this thread. Like @ojw28 says, an app can maintain a list of media sources, use `removeMediaItemAt(index)` and then add the media source from the list again with `addMediaSource(index, source)` again.

To be fair, it wouldn't be difficult to add this and we had such a `getMediaSource(index)` method on the `ConcatenatingMediaSource`. I think I'd still need some more convincing arguments (like why the existing customization means are not sufficient) to start adding this by myself, given we want to keep the API surface as small as possible. :)

**Comment by Tolriq** [comment]
1) MediaSource

There's many different issues but the usage of MediaSource as explained in linked old issue is tied to needs in the DataSource.

It's tied to access to the source data in all the needed places. I explained it in the linked issue here :https://github.com/google/ExoPlayer/issues/7525 

The player needs more than playing urls, I need to start transcoding / stop transcoding on the server in the datasource open / close. This requires complex data that can't really be added to the urls.
This forces me to create MediaSources with different Factories to pass the necessary data. This works.

Now about keeping the sources of course I can keep them but why should I when there's already everything exposed to properly handle them? Without the need for gapless I would handle all on my side and most issues would be gone.

So about the MediaSources maybe I should reopen an issue for how to properly pass custom data from MediaItem to DataSource is using MediaSource from apps is unwanted.. Tag is not passed along, DataSourceSpec have CustomData but I did not find a way to fill it from MediaItem builder.
If there's a way to add a custom object to MediaItem that can be accessed in the DataSource from a single Factory then yes the need is not present. Else as I'm forced to use MediaSource having the rest of the API that covers it makes sense.

2) Invalidate Timeline.

The need for that is to be able to externalize the playlist while still allowing Gapless. Without invalidation I can't force reload the next item, I can't tell the player that the playlist have changed and it's current index is changed without actually doing all the work inside ExoPlayer.
And current API for custom ShuffleOrder does not seems to properly cover this. Maybe there's a way but I can't figure out how to delegate things properly and have the ShuffleOrder triggering the changes for the player to adapt.

Maybe some example about advanced usage of ShuffleOrder could help here. 

The other solution is to always just have 2 items in ExoPlayer, but as I'm event driven to be able to replay the same index I need to clearMediaItems then add them again, this triggers a non playing state, so the UI hides as nothing is playing then is shown back again. So unfortunately I can't do that, as even with some debouncing and delays it's not reliable.

**Comment by ojw28** [comment]
You've already explained why you're making your own `MediaSource` instances. There's no reason to re-state this.

I really don't understand what your remaining problem is. You don't have the `MediaSource` instance to re-add it, but you could solve this simply by keeping the `MediaSource` instances in your own `List` alongside the player. As we acknowledge, a `getMediaSourceAt(int)` method would be a bit more convenient, but maintaining a `List` isn't exactly hard. Could you clarify what your actual remaining problem is?

**Comment by Tolriq** [comment]
I was answering to @marcbaechinger who said : 
> The API that the MediaSource interface offers is actually not for being called by app code.

So I'm pointing again why I do that and asking again if there should not be another better way since it was stated it's not meant to be used like that and so conclusion would be that I should not be doing that.

I know my English is bad but still no need for aggressivity.

The remaining problem is just explained above and in first post, the add/remove of mediasource only workaround a small part of the need, the double windowindex change is a workaround with side effects.

You never answered about the initial need, just that you did not understood it, I tried again to explain it and you again just focus one of workaround I use without addressing the original question.

So let's simplify the problem, the Original need is not possible/not wanted, so I need to replicate all my playlist logic inside ExoPlayer specially the shuffle / repeat one.

New simple need: Is it possible to have some advanced example about custom advanced ShuffleOrder
Documentation is close to 0. Only could find https://github.com/google/ExoPlayer/issues/5426 that gives some ideas but it says some API should be added and it seems it have not been.
Specifically I want to have the shuffled order kept externally so being passed along with all the create / clone stuff and having the current window index to move with the shuffling. So if current playlist is 1, 2, 3 and playing index 0 (so 1) then shuffle and 1 is now 3, current window index should be 2 and we are at the end of the playlist.

**Comment by ojw28** [comment]
@tonihei might be able to address the `ShuffleOrder` question.

**Comment by tonihei** [comment]
> Even after a stop() + prepare() the media is not reloaded.

Not relevant to the rest of the discussion, but that is surprising actually because `stop()` should release all media-related resources. 

> Specifically I want to have the shuffled order kept externally

I think the underlying cause for the problems you are facing is that you swap out the actual media underneath a `MediaSource` to support some custom shuffle logic. The problems occur because the player assumes it's still the same media as before (=same ids in the `Timeline` for example), but you'd like the tell the player that the media changed and it needs to invalidate everything it loaded already. 

Fundamentally, there are two ways how you can approach this:
 1. **Make sure the player knows that the media has changed by properly swapping out the items (including all ids).**
    If you do that, the player will invalidate all previously buffered data for this item and reload the media as you expect. This is the path you were exploring above already and it really comes down to setting or adding a new `MediaSource` to the playlist. As you have a customized `MediaSource`, you either need to:
     - use the `ExoPlayer.{set/add}MediaSource` APIs only and create a new `MediaSource` every time you want to invalidate its contents 
     - or add a custom `MediaSourceFactory` in the Player builder that allows you to convert `MediaItems` to your custom `MediaSource`. This way you can use the `MediaItem` APIs including `getMediaItemAt`.
 2. **Tell ExoPlayer about your shuffle order and let the player handle all updates.**
     This seems preferable as it avoids all reloading of media as far as possible and thus should give your users a better/faster playback experience. If I understand your needs correctly, you want to specify a custom order and be able to update this custom shuffle order at any time during playback. Both use cases are supported by the player as far as I can tell and if you think it doesn't work, please provide an example of an update you'd like to do, but that doesn't work. Example for how the shuffled order can be forced to a specific order:
     ```
     // Original unshuffled playlist.
     player.addMediaItems(A, B, C);   
     // Set shuffle order to start playback with C, followed by A and B. 
     player.setShuffleOrder(new DefaultShuffleOrder(new int[] {2,0,1}, randomSeed);  
     // Turn shuffled mode on (assuming it was requested by the user):
     player.setShuffleModeEnabled(true);
     // Actually start playback.
     player.prepare();
     player.play();
     /* ... later ... */
     // Currently playing item B (=index 1), update the shuffle order to follow with A and C.
     player.setShuffleOrder(new DefaultShuffleOrder(new int[] {1,0,2}, randomSeed);
     /* ... later ... */
     // Add new item to playlist. This randomly inserts it in the existing shuffle order.
     player.addMediaItem(D);
     // Override the shuffle order to force the shuffled position of the new item to be just after B:
     player.setShuffleOrder(new DefaultShuffleOrder(new int[] {1,3,0,2}, randomSeed);
     /* .. later... */
     // Turn shuffle mode off when requested by the user. Playback will now continue from the current
     // item in the original order.
     player.setShuffleModeEnabled(false);
     ```

**Comment by Tolriq** [comment]
> Not relevant to the rest of the discussion, but that is surprising actually because stop() should release all media-related resources.

It only works if I reset, but then I need to add again the whole playlist.

> If I understand your needs correctly, you want to specify a custom order and be able to update this custom shuffle order at any time during playback

My main problem is more about the currentWindowIndex when changing from shuffled to unshuffled to shuffled.

The app displays the playlist in the order it will be played and handle it's own currentPosition to indicate the active media. This what most users want for proper reordering via drag/drop even when in shuffle mode. (The app plays to many different players like UPnP, FireTv, Roku, ... Exoplayer is just one of them).

I can handle shuffle state, unshuffled state and have the proper next item played with reordering and everything displayed properly.

But since the currentWindowIndex does not change and we can't indicate that it's changed during the shuffle we can't update it when switching from one mode to another.

So if playlist in not shuffled  is A B C D and we are playing A. When toggling shuffle playlist becomes for example B C A D.
Auto advance should play D as it's now the media after A that is currently playing, but it will play C then after properly A D.
Same issue when changing from shuffled to unshuffled.

Please note that I do not want to "cheat" and have B C forced to be after D, because the shuffle order takes in account playcounts and repeat mode and some other parameters so the order matters (Reason why I want to replicate the app playlist logic for consistency over all players, and not just the default ExoPlayer way to handle shuffling)

So the issue with ShuffleOrder is that I can't tell ExoPlayer to follow the media it's currently playing to update it's currentWindowIndex when the playlist order change.

The only way I can think of would be that I never use ExoPlayer shuffle and remove all items before current + all after current then add all the new proper previous and next ones, but that's a little overkill and ressources intensive.
So I'd really like to have a way to handle this need handled by ExoPlayer, that does not seems like an uncommon need to have the shuffling change have the index follow the new item position.

**Comment by tonihei** [comment]
> So the issue with ShuffleOrder is that I can't tell ExoPlayer to follow the media it's currently playing to update it's currentWindowIndex when the playlist order change.

This is working as intended because the `getCurrentWindowIndex` returns the index in the original unshuffled playlist.

If you want to display the shuffled order (and the currently playing item in the shuffled order), you need to iterate the Timeline to retrieve the right order:
```
Timeline timeline = player.getCurrentTimeline();
while (int index = timeline.getFirstWindowIndex(true); index != C.TIME_UNSET; index = timeline.getNextWindowIndex(index, REPEAT_MODE_OFF, true)) {
  addMediaItemToUI(player.getMediaItemAt(index));
  if (index == player.getCurrentWindowIndex()) {
    highlightItemAsCurrentlyPlaying();
  }
}
```
You can also add the index as metadata to the UI element, so when a user taps on an item, you know where to seek to.  But given you have your custom shuffle order stored externally anyway, this is probably not an issue.

Both displaying this shuffled list and seeking to a new item based on this list will be simplified by #5426, but you can still do it without these proposed methods.

**Comment by Tolriq** [comment]
There's a misunderstanding here.

I have no issue displaying or handling the sorting and handling manual clicking and all user generated actions.

The issue is about Exoplayer auto advancing to the next item. Since there's no way to modify the windowindex it will not move to the proper next item for my needs.

As explained earlier given the unsorted Playlist A B C D, and currently playing A (so index 0).
If the new wanted shuffled order is B A D C, then I'd like to have Exoplayer to play D after the end of media as it's the correct one. Instead it will play again A that is index + 1.

The B A C D order in the shuffled mode is the requirement as well as keeping position to play the proper next song after the current one.

Currently there's no way to achieve that. Getnextindex is called a tons of times so there's no way to hack something with it.

Ideally when changing the shuffleorder there should be a way to indicate the next index position to handle this need. (Keeping window index in sync with the media)

All other solutions drop gapless. While gapless when going to shuffle is less important. When returning to unshuffled it's nice to have it working instantly.

**Comment by tonihei** [comment]
> As explained earlier given the unsorted Playlist A B C D, and currently playing A (so index 0).
If the new wanted shuffled order is B A D C, then I'd like to have Exoplayer to play D after the end of media as it's the correct one. Instead it will play again A that is index + 1.

This is already working as you describe. If you set the shuffle order to BADC while playing item A, the player will make sure to play D next with a seamless transition.

**Comment by Tolriq** [comment]
Ok so there's some magic in the defaultshuffleorder to achieve that as I could not have this working with a custom one. It always play the position pointed at current + 1.
Some more docs on that point would be nice.

**Comment by tonihei** [comment]
It's not very magical really :) It just plays the next item in the ShuffleOrder you provided (instead of currentIndex + 1). 

We have some minimal documentation here: https://exoplayer.dev/playlists.html#setting-a-custom-shuffle-order
What kind of information were you missing specifically? I guess we can extend the playlist page to cover more details about repeating and shuffling in general.

**Comment by Tolriq** [comment]
I'm building a custom shuffle order so not expanding the default one.

The shuffled and getnext first last all works.
But when enabling / disabling the shuffle order it plays the index + 1 so there's something I don't do correctly  but I can't have it play the proper one.

If the defaultone is supposed to do that I at least know it's possible and somewhere to look at.
But yes that page is not explaining how to to properly build a shuffleorder just that you can, I tried and failed :)


I suppose the magic happens with the constructor from a fixed shuffle order that actually change it when using the getnext and not directly using the index in the provided array.

**Comment by Tolriq** [comment]
Ok thanks for the help I get it working when debugging with the default one.

I guess the major lack of documentation is about the timeline impacts of the shuffleorder (or actually the fact that it have no impact on it)

> This is working as intended because the getCurrentWindowIndex returns the index in the original unshuffled playlist.

This + the fact that to seek to an item in the shuffled order you need to seek to the original index and not the position in the shuffled list makes it hard to grasp what's going on.

A note in the https://exoplayer.dev/playlists.html#setting-a-custom-shuffle-order about that (shuffle does not impact timeline) and maybe a second one on the graphs here https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.html  

Because from just the descriptions of the ShuffleOrder and currentWindowIndex it's not that clear.

And because of that remind the need to reapply the customorder after each playlist change to actually have ExoPlayer refreshes it's nextitem as that part is also not very clear. 

In the end when you get the 2 concepts rights it all makes sense, but this is quite a different approach to shuffle than all other ones I've seen so I started with wrong assumptions.

Anyway it works now so thanks for taking the time to explain.

**Comment by tonihei** [comment]
Glad to hear it works! And thanks for the hints on improving the documentation.
