### ISSUE TITLE
Unable to play video with partial cache

### ISSUE THREAD

**Issue by SabaZafar22** [google/ExoPlayer#9620]
I am creating instance by using following code

```
httpDataSourceFactory = new DefaultHttpDataSource.Factory().setAllowCrossProtocolRedirects(true);

defaultDataSourceFactory = new DefaultDataSourceFactory(context, httpDataSourceFactory);
trackSelector = new DefaultTrackSelector(context);

cacheDataSourceFactory = new CacheDataSource.Factory()
        .setCache(simpleCache)
        .setUpstreamDataSourceFactory(httpDataSourceFactory)
        .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
instance = new StoriesVideoPlayManager();
bandwidthMeter = new DefaultBandwidthMeter.Builder(TelloApplication.getInstance()).build();
extractorsFactory = new DefaultExtractorsFactory();
mediaDataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "StoriesPlayer"), bandwidthMeter);
player = new SimpleExoPlayer.Builder(TelloApplication.getInstance()).setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory)).build();
player.addAnalyticsListener(new EventLogger(trackSelector));
```

and set uri to player by following code

```
Log.d(TAG, "isCached "+simpleCache.getCachedSpans(uri.toString()));
MediaItem mediaItem = MediaItem.fromUri(uri);
mediaSource = new ProgressiveMediaSource.Factory(cacheDataSourceFactory).createMediaSource(mediaItem);
player.setPlayWhenReady(isPlay);
player.setMediaSource(mediaSource);
player.prepare();
```

'simpleCache.getCachedSpans(uri.toString())' this is returnng isCached [[0, 2048]]
 but I am unable to play video untill fully cached, is there anything I am missing?

**Comment by icbaker** [comment]
The code snippet you've provided seems slightly confused.

You are instantiating 4 `DataSourceFactory` instances:
* `httpDataSourceFactory`
* `defaultDataSourceFactory` with `baseDataSourceFactory = httpDataSourceFactory`
* `cacheDataSourceFactory` with `upstreamDataSourceFactory = httpDataSourceFactory`
* `mediaDataSourceFactory`

You don't appear to be using `defaultDataSourceFactory` nor `mediaDataSourceFactory`. Removing these also removes all usages of `bandwidthMeter`.

`extractorsFactory` also appears to be unused and `instance` is not used in this code snippet.

You are instantiating an `EventLogger` using a `trackSelector` instance which doesn't actually seem to be set as the `TrackSelector` on the `Player`.

You are instantiating a `DefaultMediaSourceFactory` and setting this on the `SimpleExoPlayer.Builder` but then instantiating `MediaSource` isntances yourself and passing them directly to `Player#setMediaSource` meaning that the Player's `MediaSourceFactory` instance won't be used. Is there a reason you're instantiating `MediaSource` instances yourself instead of using `Player#setMediaItem`?

I think your code snippet can be simplified to (note the change on the `addAnalyticsListener` line):

```java
httpDataSourceFactory = new DefaultHttpDataSource.Factory().setAllowCrossProtocolRedirects(true);

cacheDataSourceFactory = new CacheDataSource.Factory()
    .setCache(simpleCache)
    .setUpstreamDataSourceFactory(httpDataSourceFactory)
    .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
player = new SimpleExoPlayer.Builder(TelloApplication.getInstance())
    .setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory))
    .build();
player.addAnalyticsListener(new EventLogger((MappingTrackSelector) player.getTrackSelector()));
```

```java
Log.d(TAG, "isCached "+simpleCache.getCachedSpans(uri.toString()));
player.setPlayWhenReady(isPlay);
player.setMediaItem(MediaItem.fromUri(uri));
player.prepare();
```

-----

> but I am unable to play video untill fully cached, is there anything I am missing?

Please provide more information about exactly what you expect to happen and what you observe. Given the code you've provided I would expect that playback will begin as soon as enough of the media is **buffered** (not cached) to start playback (generally this is the metadata and first frame or two of compressed media, but it can depend on the way a file has been encoded). It may help to take a screen recording of what you're seeing and attach it here.

If you'd like us to take a further look at what's going on then please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
