### ISSUE TITLE
How to use "Fast forward", "Rewind" and "Seek to" commands to control playback with Google Assistant ?

### ISSUE THREAD

**Issue by vender98** [google/ExoPlayer#9627]
**Exoplayer version**: 2.13.1

**Case:**
I am trying to use Google Assistant to control playback in my video app for Android TV. To make my app accessible for Google Assistant commands I use `MediaSessionCompat` and `MediaSessionConnector`. The way I configure the player looks as follows:

```kotlin
val player = SimpleExoPlayer.Builder(context, renderersFactory)
...
mediaSession = MediaSessionCompat(context, "MEDIA_SESSION_TAG")
mediaSessionConnector = MediaSessionConnector(mediaSession).apply {
    setPlayer(player)
}
...
```

That way some commands like "Play", "Pause", "Stop" works flawlessly. But if try to execute commands like "Fast forwards", "Rewind" or "Seek to", the Google Assistant respond "Sorry, I can not do this on this App". Moreover, I can not debug any method in `MediaSessionConnector.ComponentListener` – the breakpoints in method `onEvents()` of `Player.EventListener` or in methods `onSeekTo()`, `onFastForward()`, `onRewind()` are not called. As a result, I can't even figure out what is the reason why these commands don't work.

I found the same question on SO – https://stackoverflow.com/q/66040200/11935726, but it has no any answers.

What should I do to be able to use commands "Fast forwards", "Rewind" and "Seek to" ? Could this be influenced by a way I configure the player itself or a way I prepare its playback and media source ?

**Comment by marcbaechinger** [comment]
What actions can be used through the media session is defined by the actions that are advertised in the playback state of the session. By default (like your snippet above) the `MediaSessionConnector` advertises the following actions:

```
PlaybackStateCompat.ACTION_PLAY_PAUSE
          | PlaybackStateCompat.ACTION_PLAY
          | PlaybackStateCompat.ACTION_PAUSE
          | PlaybackStateCompat.ACTION_SEEK_TO
          | PlaybackStateCompat.ACTION_FAST_FORWARD
          | PlaybackStateCompat.ACTION_REWIND
          | PlaybackStateCompat.ACTION_STOP
```
If in addition a `TimlineQueueNavigator` is added the actions `ACTION_SKIP_TO_PREVIOUS` and `ACTION_SKIP_TO_NEXT` are advertises in the same way.

Apps that have access to the media session can call these actions, so that they arrive at the `MediaSessionConnector` that delegates them accordingly. It's up to these apps which of the actions are called. Google Assistant is one of such an app with access to the session.

I found this [table of actions](https://developer.android.com/guide/topics/media-apps/interacting-with-assistant#transport_controls) that are documented to be used by Google Assistant.

I tested the transport control commands that I found in this list with the `MediaSessionConnector` on mobile (I don't have access to a Android TV device right now I'm afraid). These are the documented transport control actions that Assistant is supposed to support according to the doc I linked above:

* Pause
* Stop
* Resume
* Rewind by 30 seconds
* Next song (needs `TimelineQueueNavigator`)
* Previous song  (needs `TimelineQueueNavigator`)

Besides the commands listed in the doc above I also tested the following seek commands:

'Fast forward 1 minute'   -> seeks forward to current position + 1 minute
'Fast forward to 1 minute'   -> seeks forward to position 1:00

All of them worked fine for me. As I said this is on mobile. I can test this on a TV when I have access to a Android TV device. In the meanwhile, can you test for me whether this works for your Android TV device if you add a duration to the voice command? Like "30 seconds" or "2 minutes"?

The following worked for me as well on mobile but it doesn't seem to be documented like this:

'Fast forward' -> seeks forward for 30 seconds
'Rewind' -> seeks back for 30 seconds

I'm not sure whether there is a difference between mobile and TV (see below also regarding app version).

> the breakpoints in method onEvents() of Player.EventListener or in methods onSeekTo(), [...] are not called.

If Asssistant tells you that it can't do that for your app, then you would not receive a command in your app. I don't think that the problem is within your app or the `MediaSessionConnector` in this case but rather that Assistant never issues such an action. 

If you test the rewind/fast forward command with a duration and this does not work can you please let me know what Android TV version you are using and the version of the Google app that runs on this device? This would be helpful for us when testing on a TV device. As this suggests, Google Assistant is implemented by an app and it may be that different apps slightly vary in what actions the support and how, depending on platform (tv/mobile) or version of the app. So it would be important to know the version, so we know why we have different findings.

If you find none of the above commands is working it may be an further option that you install the [ATV reference app](https://github.com/android/tv-samples/blob/main/ReferenceAppKotlin/app/build.gradle) from this repository and see whether this is working with this ref app. It's not much different to what you do though, It is using the `MediaSessionConnector` with ExoPlayer as well.

**Comment by vender98** [comment]
@marcbaechinger thanks for your explanation.

So answering to your questions: 

> In the meanwhile, can you test for me whether this works for your Android TV device if you add a duration to the voice command? Like "30 seconds" or "2 minutes"?

I have tested a various combinations, including those that specifies a duration – "Fast forward", "Fast forward 30 seconds", "Rewind by 30 seconds", etc. Each one has the same result – "Sorry, I can not do this on this App".

> If you test the rewind/fast forward command with a duration and this does not work can you please let me know what Android TV version you are using and the version of the Google app that runs on this device?

I was trying to test on Nvidia Shield with Android 9.0, also on Sony Bravia 4K UR3 with Android 9.0. Version of Google app is 4.20.0.20210927.1.

> If you find none of the above commands is working it may be an further option that you install the ATV reference app from this repository and see whether this is working with this ref app.

I tried to install ATV reference app and test these commands on it – everyone works perfectly. "Fast forward", "Rewind", "Rewind for 30 seconds" – everything is OK. I also tried to test these commands on the [ExoPlayer main demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main). The result is same – commands works perfectly.


Now I think it might depend on the type of media source for the player, or perhaps the playback configuration. Don't you think so ?

**Comment by marcbaechinger** [comment]
The only thing what comes to mind is that the media needs to be seekable to make the `MediaSessionConnector` advertise the seek actions. If it is not seekable seeking does not work, but not only via Assistant I'd think.

Two other things come to mind for further investigation:

1) Can you deploy your app and while the app is playing do

```
adb shell dumpsys media_session
```

This will show the state of the media session including the bitmask of the advertised command. You can paste the output here if you want me to look into this.

2) When you tried with the ATV ref app or the ExoPlayer demo app. Did you use the same media/media source as you do in your app?

Alternatively: Can you let me know how you create the media source and probably the URI you are using? You can send this to dev.exoplayer@gmail.com using a subject in the format "Issue #9627" if you don't want to share in public (let me know here in case you have done that).

**Comment by vender98** [comment]
1. The output of
```
adb shell dumpsys media_session
```
during the playback in my app is as follows:
<details>
  <summary>Output</summary>
MEDIA SESSION SERVICE (dumpsys media_session)

7 sessions listeners.
Global priority session is null
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: android.media.session.ICallback$Stub$Proxy@2f4e22c
  Last MediaButtonReceiver: null
  Restored MediaButtonReceiver: null
  Media button session is **${packageName}**/MEDIA_SESSION_TAG (userId=0)
  Sessions Stack - have 1 sessions:
    MEDIA_SESSION_TAG **${packageName}**/MEDIA_SESSION_TAG (userId=0)
      ownerPid=11089, ownerUid=10215, userId=0
      package=**${packageName}**
      launchIntent=null
      mediaButtonReceiver=null
      active=false
      flags=3
      rating type=0
      controllers: 0
      state=PlaybackState {state=2, position=3438002, buffered position=3446833, speed=0.0, updated=240816004, actions=2360159, custom actions=[], active item id=0, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x0 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata:size=5, description=MediaDescription title, MediaDescription subtitle, MediaDescription description for 0
      queueTitle=null, size=1

Audio playback (lastly played comes first)
  uid=10215 packages=**${packageName}**
</details>

And also I would like to attach the output during the playback in ATV ref app, if it makes sense:
<details>
  <summary>Output</summary>
MEDIA SESSION SERVICE (dumpsys media_session)

7 sessions listeners.
Global priority session is null
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: android.media.session.ICallback$Stub$Proxy@2f4e22c
  Last MediaButtonReceiver: null
  Restored MediaButtonReceiver: null
  Media button session is com.android.tv.reference/ReferenceAppKotlin (userId=0)
  Sessions Stack - have 1 sessions:
    ReferenceAppKotlin com.android.tv.reference/ReferenceAppKotlin (userId=0)
      ownerPid=12899, ownerUid=10218, userId=0
      package=com.android.tv.reference
      launchIntent=null
      mediaButtonReceiver=null
      active=true
      flags=3
      rating type=0
      controllers: 6
      state=PlaybackState {state=2, position=45023, buffered position=99328, speed=0.0, updated=243314828, actions=2360159, custom actions=[], active item id=0, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x0 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata:size=5, description=The Psychiatrist Gets Clampetted, null, A Beverly Hills psychiatrist pursues Granny instead of Pearl when Granny's love potion misfires.
      queueTitle=null, size=1

Audio playback (lastly played comes first)
  uid=10218 packages=com.android.tv.reference
</details>

2. Did you use the same media/media source as you do in your app?

No, I used the different media source in my app compared to the ones in the ATV ref app or ExoPlayer demo app. So I tried to copy the logic of creating the media source from ATV ref app to the my app and the result remained the same – the commands "Fast forward", "Rewind", "Seek to" still do not work. I used this URI – https://storage.googleapis.com/atv-reference-app-videos/episodes-beverly-hillbillies/bh34-psychiatrist-gets-clampetted.mp4.

The output of
```
adb shell dumpsys media_session
```
using media sources from the ATV ref app:
<details>
  <summary>Output</summary>
MEDIA SESSION SERVICE (dumpsys media_session)

7 sessions listeners.
Global priority session is null
User Records:
Record for full_user=0
  Volume key long-press listener: null
  Volume key long-press listener package: 
  Media key listener: null
  Media key listener package: 
  Callback: android.media.session.ICallback$Stub$Proxy@2f4e22c
  Last MediaButtonReceiver: null
  Restored MediaButtonReceiver: null
  Media button session is **${packageName}**/MEDIA_SESSION_TAG (userId=0)
  Sessions Stack - have 1 sessions:
    MEDIA_SESSION_TAG **${packageName}**/MEDIA_SESSION_TAG (userId=0)
      ownerPid=13358, ownerUid=10215, userId=0
      package=**${packageName}**
      launchIntent=null
      mediaButtonReceiver=null
      active=false
      flags=3
      rating type=0
      controllers: 0
      state=PlaybackState {state=3, position=48061, buffered position=103658, speed=1.0, updated=244363350, actions=2360159, custom actions=[], active item id=0, error=null}
      audioAttrs=AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x0 tags= bundle=null
      volumeType=1, controlType=2, max=0, current=0
      metadata:size=5, description=MediaDescription title, MediaDescription subtitle, MediaDescription description for 0
      queueTitle=null, size=1

Audio playback (lastly played comes first)
  uid=10215 packages=**${packageName}**
</details>

**Comment by vender98** [comment]
@marcbaechinger 
I found the problem.
I forgot to set the session active by
`mediaSession.isActive = true`.

As a results some commands, like "Pause", "Play", "Stop", worked correctly. And at the same time, commands like "Fast forward", "Rewind" – didn't.

Thank you for your help !
