### ISSUE TITLE
Error OMX.MS.AVC.Decoder

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#9630]
i when playing movie get this error in some tv devices :

[OMX.MS.AVC.Decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010

this error mostly while exoplayer release and renew then play new file

**Comment by sajjadshahbazi** [comment]
exoplayer version : 2.14.1

**Comment by icbaker** [comment]
Please provide more information:

* Precisely what devices and OS versions do you see this on?
  * It sounds like you've also found some devices where this log line does **not** appear - please also list these devices and OS versions.
* What's the user-visible impact when this log line appears? (a screenrecording might help here)
* Are you able to reproduce the problem using the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html)?
  * If yes, please provide the result of running `adb bugreport` immediately after reproducing the problem in the demo app.
  * If no, that suggests this is likely a problem with your application rather than the ExoPlayer library. I suggest you dig into understanding what your application is doing differently to the demo app.

**Comment by newhinton** [comment]
Not knowing if this issue is the same, but i can reproduce the errormessage. 
Some videos, i assume some HDR content, results in this issue. 

Using this in the demo-app should allow you to reproduce it aswell:

```
      {
        "name": "reddit (broken)",
        "uri": "https://v.redd.it/0n1otu272k971/DASH_720.mp4"
      },
      {
        "name": "reddit2 (working)",
        "uri": "https://v.redd.it/buksivkk5q081/DASH_1080.mp4"
      }
```

A 'real-world' example is opening the same videos (from their posts) in the '[Slide](https://github.com/ccrama/Slide/issues/3396)'-app for reddit (i linked an issue with a post that does not work)

Edit:
2.14.2 and 029a2b27cbdc27cf9d51d4a73ebeb503968849f6

LineageOS 18 and on Emulator API 29


The user visible result is that the audio plays, but video stays black. I'll add a debuglog shortly

```

2021-11-20 22:18:36.773 8822-11258/com.google.android.exoplayer2.demo E/ACodec: [OMX.google.hevc.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2021-11-20 22:18:36.785 8822-11258/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -1010)
2021-11-20 22:18:36.857 8822-8822/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [eventTime=1.01, mediaPos=0.00, window=0, period=0, OMX.google.hevc.decoder]
2021-11-20 22:18:36.858 8822-8822/com.google.android.exoplayer2.demo D/EventLogger: videoInputFormat [eventTime=1.01, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/dolby-vision, codecs=hev1.08.10, res=406x720]
```

**Comment by icbaker** [comment]
@newhinton I played the links you've provided in the 2.16.1 demo app on a Pixel 5 on Android R. The first shows no video and then playback fails, while the second plays successfully.

Logcat output from the demo app shows that the first video is encoded in a way that's incompatible with the Pixel 5's HEVC decoder (`supported=NO_EXCEEDS_CAPABILITIES`):
```
D/EventLogger: tracks [eventTime=0.05, mediaPos=0.00, window=0, period=0
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=1, mimeType=video/dolby-vision, codecs=hev1.08.10, res=406x720, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger:     ]
D/EventLogger:   ]
```

Devices running Android 10 are [not required to support Dolby Vision content](https://source.android.com/compatibility/10/android-10-cdd#5_3_8__dolby_vision), so this is all working as intended from ExoPlayer's perspective. If an app is running on a device that doesn't support Dolby Vision then it shouldn't try and play Dolby Vision content. 

(as an aside, it's generally better to file new issues than to add replies on to ambiguous existing ones like this. We don't know the root cause of the problem in the original issue here because not enough information was provided, so it's impossible to say whether your issue is related or not)

**Comment by newhinton** [comment]
@icbaker Should i create a new issue asking to support that codec so that we have a standalone issue for that, or is it 'wont-fix' anyway?

**Comment by icbaker** [comment]
ExoPlayer (an application-level library) doesn't control what codecs are supported by a device: 
* https://exoplayer.dev/supported-formats.html
* https://exoplayer.dev/supported-formats.html#hdr-video-playback

So this issue tracker is not the right place to request device-level codec support.
