### ISSUE TITLE
Memory Usage Problem

### ISSUE THREAD

**Issue by ProtoScott** [google/ExoPlayer#9636]
We're having a problem with a Sony Xperia phone that is causing the display to glitch out when ExoPlayer goes over 256MB of memory usage for the GPU (when playing encrypted content).

Is there a way for us to limit the GPU memory usage to 256MB or less?

- ExoPlayer version number
2.14+
- Android version
11/12
- Android device
Xperia 1 MK III

**Comment by christosts** [comment]
I assume that GPU memory is occupied after decoding video samples. ExoPlayer does not have direct control over how much memory the platform will use for video decoding. The player sends as many video samples for decoding as the platform (i.e. [MediaCodec](https://developer.android.com/reference/android/media/MediaCodec)) allows it to.

Here's an idea you could experiment with on the latest ExoPlayer version (2.16) **that has not been tested - so please try at your own risk**. You could limit how many video frames can be decoded at any time by limiting the number of video samples sent for decoding. The idea is to keep a counter of samples sent for decoding: the counter goes up each time a sample (input buffer) is queued to `MediaCodec` and the counter goes down each time a video frame (=> output buffer) is released. 

You could achieve this by creating your own `MediaCodecAdapter`: wrap [SynchronousMediaCodecAdapter](https://github.com/google/ExoPlayer/blob/r2.16.0/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/SynchronousMediaCodecAdapter.java) and apply the counting logic when (de)queueing input buffers and releasing output buffers:

```java
public final class CustomMediaCodecAdapter implements MediaCodecAdapter {
  private final SynchronousMediaCodecAdapter adapter;
  private int queuedInputCount;

  @Override
  public int dequeueInputBufferIndex() {
    if (queuedInputCount >= X) { // try X = 12?
      return MediaCodec.INFO_TRY_AGAIN_LATER;
    }
    return adapter.dequeueInputBufferIndex();
  }

  @Override
  public void queueInputBuffer(
      int index, int offset, int size, long presentationTimeUs, int flags) {
    queuedInputCount++;
    adapter.queueInputBuffer(index, offset, size, presentationTimeUs, flags);
  }

  @Override
  public void queueSecureInputBuffer(
      int index, int offset, CryptoInfo info, long presentationTimeUs, int flags) {
    queuedInputCount++;
    adapter.queueSecureInputBuffer(
        index, offset, info.getFrameworkCryptoInfo(), presentationTimeUs, flags);
  }

@Override
  public void releaseOutputBuffer(int index, boolean render) {
    queuedInputCount--;
    adapter.releaseOutputBuffer(index, render);
  }

  @Override
  public void releaseOutputBuffer(int index, long renderTimeStampNs) {
   queuedInputCount--
    adapter.releaseOutputBuffer(index, renderTimeStampNs);
  }

  @Override
  public void flush() {
    queuedInputCount = 0;
    adapter.flush();
  }
}
```

You'll then need to create the player passing a `RenderersFactory` instead of letting the Player use its default one. You can wrap (or re-use) the player's [DefaultRendererFactory](https://github.com/google/ExoPlayer/blob/r2.16.0/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java) to create the default `Renderer`s and replace the `MediaCodecVideoRenderer` with your custom one.

I ran a few local tests and see some overall memory usage drop, but this has never been tested in a wider setup, so if you try it  please test very thoroughly. This idea reduces the amount of data buffered for decoding, therefore increasing the possibility of re-buffers/underruns. Also, decoders need at least an amount of samples to be queued for decoding before outputting decoded data, so don't try to reduce the number of buffers too much (I wouldn't go below 8, in my example I suggested 12).

Let me know if you tried and what was the outcome.
