### ISSUE TITLE
Diff from adding the M2TsExtractor to ExoPlayer 2.

### ISSUE THREAD

**Issue by ooyellow58** [google/ExoPlayer#9639]
Diff from adding the M2TsExtractor to ExoPlayer 2.

[Add M2TsExtractor to ExoPlayer 2.diff.zip](https://github.com/google/ExoPlayer/files/595671/Add.M2TsExtractor.to.ExoPlayer.2.diff.zip)

_Originally posted by @Avetri in https://github.com/google/ExoPlayer/issues/1488#issuecomment-261041447_

**Comment by ooyellow58** [comment]
How to convert this diff file into java classes?

**Comment by icbaker** [comment]
The linked file is a patch. There's a relevant stack overflow question on applying git patches here: https://stackoverflow.com/questions/2249852/how-to-apply-a-patch-generated-with-git-format-patch

You need to apply it to the specific commit it was generated from (or one relatively close to it), otherwise you will likely see conflicts because the files that are being edited may have changed significantly or moved around.

This is a general development/git question, and not ExoPlayer-specific, so I'm going to close this. If you need further help on using `git` I suggest asking elsewhere, possibly on Stack Overflow.
