### ISSUE TITLE
Switching between MediaSource at runtime

### ISSUE THREAD

**Issue by Clement-Jean** [google/ExoPlayer#9640]
As I am developing an application that is Offline first (user can download the videos) I want to be able to do the following at runtime:

```
IF cookies != null && !video_downloaded:
   run HLSMediasource // https://
ELSE
   run ProgressiveMediaSource // file://
```

The cookies here mention the signed cookies I'm getting beforehand. The problem that I have now is that I'm building the playlist by adding `MediaSource` depending on the `MediaItem` URI. This is not optimal for two reasons:

- I might be building the playlist and the cookie didn't arrive yet, this will create a `ProgressiveMediaSource` which doens't exist. 
- as my users are able to download, they are also able to delete the file and once the file is deleted, they couldn't have access to the stream since it is a `ProgressiveMediaSource` that was built.

I would like to know if there is a way to do that at runtime (maybe with `TrackSelector` ?) and if yes could guide me with little bit of code ? If it is not possible, what would be the best alternative ?

**Comment by Clement-Jean** [comment]
Any idea? I'm still trying to find the solution @marcbaechinger

**Comment by marcbaechinger** [comment]
Please accept my apologies for my late response. 

You could create your own [`CompositeMediaSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/CompositeMediaSource.html) implementation that acts as a delegator in front of the child source. Then when the composite source is prepared by the player you can take the decision to either prepare a `HlsMediaSource` or a `ProgressiveMediaSource` as a child source and instantiate and prepare the child source. The `CompositeMediaSource` will take care of delegating calls to the child source then.

An easier alternative would be to first set the media source that is more likely to be played. As I understand this would be the offline source for your app. Then if the cookie arrives you can replace the media source with another type. Of course this option only works nicely when the source is not already playing because else replacing it would interrupt playback until the new source is prepared.

**Comment by Clement-Jean** [comment]
The composite media source sounds like an elegant solution, I'll try that, thank you

**Comment by marcbaechinger** [comment]
Closing this issue. Please re-open if you have some more questions.
