### ISSUE TITLE
Stream quality

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#9659]
Dear engineers,
While I believe the issue I experience is hardly related to ExoPlayer, I do see different behavior on VLC, and therefore decided to ask a question here.
There are couple streams I have with weird quality, it seems like sound is jammed periodically, like on old tape player.
It might be related to stream format itself (wrong bit rate, packet length, etc ...) but those streams plays well on VLC.

Examples are:

http://stream3.polskieradio.pl:8022/
http://stream3.polskieradio.pl:8008/

Thanks a lot in advance.

**Comment by christosts** [comment]
I can reproduce the "choppy" audio. I see these are shoutcast streams and contain ICY metadata headers. For some reason that I have not identified yet, the ICY metadata are not read properly and therefore the player does not configure the audio pipeline correctly. 

Interestingly, this happens when using `cronet` (`CronetHttpDataSource`) to download the stream, which is the default HTTP client in the player's demo app. However, When the `DefaultHttpDataSource` is used, which uses Java's built-in HTTP client, the ICY headers are read correctly and audio works fine. I will further investigate why this happens, but as a short answer, you may try using the `DefaultHttpDataSource` in the demo app: switch `USE_CRONET_FOR_NETWORKING` to false in [DemoUtil](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L60).

**Comment by ChernyshovYuriy** [comment]
Thanks for the feedback!
Is there significant difference between cronet and default data source? My application is simple radio broadcast, without drm,  download and other fancy options. I might stick to default one then.

**Comment by christosts** [comment]
There is some documentation you can read at https://exoplayer.dev/network-stacks.html

For simple use cases, you should not see issues using the `DefaultHttpDataSource`.
