### ISSUE TITLE
Decode  AC3/EAC3 to PCM

### ISSUE THREAD

**Issue by ivostefanoff** [google/ExoPlayer#9662]
Hello,
i have some trouble while playing streams containing AC3/EAC3 audio on Abdroid TV Box.
When the audio route from the Android settings are "Auto", the AC3 is correctly extracted from FFMPEG extension and correctly played, but no volume correction is able, because of passthrough mode. Some old TV has no AC3/EAC3 support, causing missing audio. What is the correct way for extract/transcode with ExoPlayer/FFMPEG extension AC3/EAC3 to AAC or MP3 or just stream to PCM?
Thank you

**Comment by andrewlewis** [comment]
> When the audio route from the Android settings are "Auto", the AC3 is correctly extracted from FFMPEG extension and correctly played, but no volume correction is able, because of passthrough mode.

I don't think the ffmpeg extension supports passthrough mode -- it only handles the input media if ffmpeg was compiled including the decoder for the format and it can output PCM to the audio sink. If you see that playback is using encoded audio passthrough, the `FfmpegAudioRenderer` is probably signaling that it doesn't support decoding the format so ExoPlayer is falling back to `MediaCodecAudioRenderer` (which does support passthrough).

> Some old TV has no AC3/EAC3 support, causing missing audio. What is the correct way for extract/transcode with ExoPlayer/FFMPEG extension AC3/EAC3 to AAC or MP3 or just stream to PCM?

Decoding to PCM is the expected behavior of the ffmpeg extension if you've bundled the required codecs.

Please check you've compiled it correctly, including explicitly enabling the decoders you want to include. See also https://exoplayer.dev/supported-formats.html#ffmpeg-extension. You may want to set a breakpoint in `FfmpegAudioRenderer.supportsFormatInternal` and step through the checks there to make sure everything has been built correctly.
