### ISSUE TITLE
Compatibility issue, ExoPlayer cannot play this two audio files.

### ISSUE THREAD

**Issue by hufozhu** [google/ExoPlayer#9668]
Hi, we find two audio files cannot be played on ExoPlayer, but everything goes fine on Chrome, ffplay and some other players. 
Here are the urls, and issues should be easily reproduced on demo.

url1:
- https://static.storyfm.cn/media/2021/08/no-storyfm-today-2021-8-27.wav
    - Got EOFException

![image](https://user-images.githubusercontent.com/1925674/140902488-14f5ac9e-828e-46b3-b003-4fe0414cab2f.png)

url2:

- https://rio.xyzcdn.net/crazycapital/ep1.mp3
    - Got UnrecognizedInputFormatException
![image](https://user-images.githubusercontent.com/1925674/140902884-0aa0748c-5468-466c-ae62-67d47960bb9d.png)

- ExoPlayer version number
    - 2.16.0
- Android version
    - 11
- Android device
    - Mi 11 M2011K2C

Thanks for your great player.

**Comment by christosts** [comment]
I tried both files, remotely (over network) and locally and failed with the same errors as above.

@kim-vde can you please take a look?

**Comment by kim-vde** [comment]
**url1**

This file is malformed. Let me explain why. A WAV file consists of a succession of chunks, each with an ID and a size. To read the sample data, ExoPlayer looks for the chunk with ID DATA. It skips the chunks it reads until it finds the DATA chunk by skipping the number of bytes corresponding to the size field of each chunk. The file you provided contains a chunk with ID bext preceding the DATA chunk which advertises an incorrect size (the size field is 677 while the actual size is 678). As a result, when ExoPlayer skips the bext chunk, the read position is not placed at the start of the next chunk as it should be and that's why it's failing. If you change the byte at position 26 from 0xa5 to 0xa6, the file plays properly.

The other players probably manage to play the file because they skim though the whole file until finding 4 bytes corresponding to the DATA ID (ignoring the chunk sizes). We don't want to do that in ExoPlayer because it would be inefficient.

**url2**

The MP3 file provided contains ID3 data (30 930 bytes), then some other data (62 602 bytes), then the actual MP3 data. ExoPlayer allows a maximum of 32768 "other data" bytes between the ID3 data and the MP3 data for performance reason (see `MAX_SNIFF_BYTES` in [`Mp3Extractor`](https://github.com/google/ExoPlayer/blob/r2.16.0/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp3/Mp3Extractor.java#L127)). The file plays with MediaPlayer so the issue should be fixed when #5718 is implemented.

**Comment by hufozhu** [comment]
@kim-vde Thanks a lot for your reply. I will subscribe #5718 waiting for the fix. And I also wonder if there is any possibility Exoplayer could provide more compatibility but less efficient config, because we are making a podcast app which we can not control the media files hosted by podcasters.

**Comment by kim-vde** [comment]
We do sometimes provide settings for less-efficient-but-more-robust behaviours in [`DefaultExtractorsFactory`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/DefaultExtractorsFactory) (see https://exoplayer.dev/customization.html#customizing-extractor-flags). I wouldn't do that for the WAV file issue though because the file is clearly malformed, it's the first time this issue is reported AFAIK, and it would change the logic in the code quite extensively. If you really want to support this file, you can implement your own WAV extractor and your own extractors factory.

**Comment by hufozhu** [comment]
Thanks again for your works, I understand all of this and I will close this issue.
