### ISSUE TITLE
How to tell `MediaItem.SubtitleConfiguration`s apart in `ExoPlayer.getCurrentTracksInfo().getTrackGroupInfos()`?

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9673]
I'm using latest ExoPlayer 2.16.0. Let's say I want to save and restore user selected audio and subtitle "tracks" on app restart. If I add multiple `MediaItem.SubtitleConfiguration`s, how I can I distinguish these in `ExoPlayer.getCurrentTracksInfo().getTrackGroupInfos()`?

```
Format(null, null, null, application/x-subrip, null, -1, null, [-1, -1, -1.0], [-1, -1])
Format(null, null, null, application/x-subrip, null, -1, null, [-1, -1, -1.0], [-1, -1])
```

`MediaItem.SubtitleConfiguration` doesn't let me specify any id. Label or user facing name may not be necessarily unique, especially if I allow users loading subtitles. The only difference may be the subtitle content/uri.

In ExoPlayer 2.15.1, I was able to tell a difference from `DefaultTrackSelector.SelectionOverride.groupIndex`.

**Comment by icbaker** [comment]
This seems like a reasonable request - I think it would make sense to add `SubtitleConfiguration.Builder` setter that propagates through to `Format#id`.

I'm not sure about `Format#accessibilityChannel` (the only 'text-specific' field in `Format`), since I don't think it's actually relevant for any sideload-able subtitle formats.
