### ISSUE TITLE
Subtitle sideload (with subtitlesconfiguration) is not working with HLS media

### ISSUE THREAD

**Issue by devingryu** [google/ExoPlayer#9713]
Tested on version 2.16.0

```kotlin
    private fun setSource(context: Context, subtitleURI:String?, videoURI:String) {
        if(player == null) exoInit(context)

        val subtitleConf = MediaItem.SubtitleConfiguration.Builder(Uri.parse(sampleSubtitle))
                .setLanguage("en")
                .setMimeType(MimeTypes.TEXT_VTT)
                .setRoleFlags(0)
                .build()

        val mediaItem = MediaItem.Builder()
            .setUri(videoURI)
            .setSubtitleConfigurations(listOf(subtitleConf))
            .build()

        val source = DefaultHttpDataSource.Factory()
            .setUserAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0")
        val mediaSource = HlsMediaSource.Factory(source)
            .createMediaSource(mediaItem)
        val newSub = MediaItem.Subtitle(Uri.parse(subtitleURI), MimeTypes.TEXT_VTT,"ko")
        val textMediaSource: MediaSource = SingleSampleMediaSource.Factory(source).createMediaSource(newSub,C.TIME_UNSET)
        val mergingSource = MergingMediaSource(mediaSource,textMediaSource)

        player!!.setMediaSource(mergingSource)
        player!!.addAnalyticsListener(EventLogger(trackSelector));
        player!!.prepare()
    }
```

This code doesn't work. No subtitles (except default dummy subtitle of HLS) are shown in EventLogger either. Using original method which uses `MediaItem.Subtitle` and `MergingMediaSource` works well.

It seems that sideloaded subtitle is overwritten with default dummy subtitle of HLS *.m3u8 file.

Thanks in advance.

**Comment by icbaker** [comment]
The provided code snippet is a little bit confusing (it seems to use both `MediaItem.Builder#setSubtitleConfigurations` **and** `MergingMediaSource`? You shouldn't need to use both). Having said that, I think the problem is that the subtitle fields of `MediaItem` are only supported by `DefaultMediaSourceFactory` and **not** `HlsMediaSourceFactory`, so the `mediaSource` produced here won't include the sideloaded subtitles:
```
val mediaSource = HlsMediaSource.Factory(source).createMediaSource(mediaItem)
```

I'm not sure you need to use the `MediaSource` API at all? I think you can pass your customised `DefaultHttpDataSourceFactory` to the player by setting it on a `DefaultMediaSourceFactory` and then use `Player#setMediaItem` directly (this will invoke the `MediaSourceFactory` inside the `Player`):

```
val dataSource = DefaultHttpDataSource.Factory(context)
    .setUserAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0")
player = ExoPlayer.Builder(context).setMediaSourceFactory(DefaultMediaSourceFactory(dataSource)).build()

val subtitleConf = MediaItem.SubtitleConfiguration.Builder(Uri.parse(sampleSubtitle))
    .setLanguage("en")
    .setMimeType(MimeTypes.TEXT_VTT)
    .build()

val mediaItem = MediaItem.Builder()
    .setUri(videoURI)
    .setSubtitleConfigurations(listOf(subtitleConf))
    .build()

player!!.setMediaItem(mediaItem)
player!!.addAnalyticsListener(EventLogger(trackSelector))
player!!.prepare()
```

**Comment by devingryu** [comment]
Thanks, and sorry for making a confusion to you. I wasn't aware that HlsMediaSource doesn't accept sideloaded subtitles. With your solution, it works well.

I'm not sure if I can ask this here, but I was wondering if there is any way to lazy load `MediaItem` with `CompositeMediaSource`. I need to retrieve real *.m3u8 link by parsing xml file. 
I think it's pretty similar with #5883, but I'm not sure how I can manage `getMediaItem()` before loading m3u8 link. In order to create `MediaItem`, I need a direct URI.

Is there any way to achieve this?

**Comment by icbaker** [comment]
There's a similar question that the person solved themselves using an HTTP interceptor here (`androidx.media3` is the [future home for ExoPlayer](https://android-developers.googleblog.com/2021/10/jetpack-media3.html)): https://github.com/androidx/media/issues/4

Another approach would be to use a [`ResolvingDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) to map from the XML URI to the media URI (you can block `Resolver#resolveDataSpec` for as long as you need, so you can download the XML file in here, parse it, and extract the media URI). This resolution will happen when the `MediaItem` is loaded for playback. There's one caveat: You need to [explicitly set the MIME type of the underlying media](https://exoplayer.dev/media-items.html#handling-non-standard-file-extensions) when building the `MediaItem` with the XML URI (because ExoPlayer normally tries to guess the MIME type from the file extension, but this obviously isn't possible if the URI always ends in `.xml`).

**Comment by devingryu** [comment]
Thanks! It helped me a lot. Now closing this issue.
