### ISSUE TITLE
Forced subtitle DASH support checking for wrong Role@value

### ISSUE THREAD

**Issue by theRealRobG** [google/ExoPlayer#9727]
When checking for forced subtitle behaviour in the `DashManifestParser.java`, the `Role@value` being matched against is `forced_subtitle`:
https://github.com/google/ExoPlayer/blob/r2.16.1/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L1477
https://github.com/google/ExoPlayer/blob/r2.16.1/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L1547

But according to the 4th edition of ISO/IEC 23009-1 ([publicly available here](https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html)) this should be checking for `forced-subtitle`. This is defined in **Table 31 — `Role@value` attribute for scheme with a value `"urn:mpeg:dash:role:2011"`**:
| `Role@value` | Description | Applicable Media Type(s) (Informative) |
| --- | --- | --- |
| `forced-subtitle` | Textual information meant for display when no other text representation is selected. It is used to clarify dialogue, alternate languages, texted graphics or location/person IDs that are not otherwise covered in the dubbed/localized audio. | `text` |

![Table 31 — Role@value attribute for scheme with a value "urn:mpeg:dash:role:2011"](https://user-images.githubusercontent.com/13763704/143018221-f3b05048-0d9e-4a87-a419-a6436467e9ab.png)

**Comment by icbaker** [comment]
Thanks for pointing this out - as you've probably realised, we added support for this after it was requested in https://github.com/google/ExoPlayer/issues/8781 and we used `forced_subtitled` based on this comment from April 2018: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/165#issuecomment-378193268

Given you've mentioned later in that thread that Shaka have have also done the same thing, I suspect there will now be content out there with a mix of the two spellings :( It's probably best for now if I update ExoPlayer to support both spellings - so that content that used to work with ExoPlayer (with the 'wrong' spelling) will keep working. I'll make that change.

**Comment by theRealRobG** [comment]
Yes, makes sense as a pragmatic approach.

Thanks for quick reply!
