### ISSUE TITLE
How to use contentId as a key when using cacheDataSourceFactory

### ISSUE THREAD

**Issue by Pavel87** [google/ExoPlayer#9748]
Hi team, 

I am trying to load offline content via **cacheDataSourceFactory** but not sure how to use the contentId from downloads table to load correct content.
![Screen Shot 2021-12-01 at 6 42 32 PM](https://user-images.githubusercontent.com/5558923/144347886-0145b7a8-b992-4ff4-a54d-65ae310456f3.png)

With my setup the player is rather trying to match the **URI** field in the table rather than content id.

```
        val dataSourceFactory: DataSource.Factory = DefaultHttpDataSource.Factory()
            .setUserAgent(Util.getUserAgent(context, "xyz!"))

        val cacheDataSourceFactory: DataSource.Factory = CacheDataSource.Factory()
            .setCache(offlineBookManager.getDownloadCache())
            .setUpstreamDataSourceFactory(dataSourceFactory)
            .setCacheWriteDataSinkFactory(null)

        player = ExoPlayer.Builder(ctx)
            .setMediaSourceFactory(DefaultMediaSourceFactory(cacheDataSourceFactory))
            .build()
```

**Comment by ojw28** [comment]
It's unclear to me what you're trying to do, or why. What's actually wrong with matching the URI? That said, if you want to use custom cache keys to identify progressive content, then you just need to:

1. Specify it when building the `DownloadRequest` that you use to make the download (i.e., `DownloadRequest.Builder.setCustomCacheKey`). If you're using `DownloadHelper`, then pass a `MediaItem` that has a `customCacheKey` to `DownloadHelper.forMediaItem`, and it'll build you a `DownloadRequest` containing the key you specify.
1. For playback, give a `MediaItem` to the player that has the same `customCacheKey`.

Note that this doesn't work for adaptive content, because adaptive content consists of many smaller files, each of which would need its own key.

**Comment by Pavel87** [comment]
In my use case I have 2 or more users on device who should be able to
access the downloaded ABR content however each user is using a slightly
different URI so we can identify which user can access the content online.

When I download the content with one user it will store the URI in
exoplayer DB but then I want to access it from another user which is using
slightly different URI and that is my issue.

**Comment by Pavel87** [comment]
accidentally closed... @ojw28 please see my comment above.

**Comment by ojw28** [comment]
For ABR content, this is just not something that we currently support.

**Comment by Pavel87** [comment]
It would be nice to have. For now, I work around it by doing a lookup into downloads and pulling the URIs, and feeding them into the player.
