### ISSUE TITLE
Low latency stream dropframes

### ISSUE THREAD

**Issue by hot1sp** [google/ExoPlayer#9750]
Hi

We're observing playout issue on DASH Low Latency Live stream with ExoPlayer version 2.13.2, while noticed a frequent freeze frames on playing the Live stream and ExoPlayer reports on Buffer of zero and dropped Frames (please find attached the log from ExoPlayer)
On the attached MPD file you can see the following LLC Parameters published on the manifest of that Live LLC channel:

minimumUpdatePeriod="PT2S" maxSegmentDuration="PT2.006S" minBufferTime="PT8.024S">
    ServiceDescription id="0">
        Latency target="8000" max="10006"/>
    /ServiceDescription>

So DASH Packager publish minBufferTime of 8 seconds while ExoPlayer reports on buffer of zero at the time that playout issues occur
Also, the Latency target is being set to 8 seconds, while the LLC stream observed with a reduced Latency of 4-5 seconds at the time of those playout issue occur
Questions:
Are you familiar with another Values we need to set those parameters (minBufferTime, Latency which is the OffsetMS) which're more optimize for ExoPlayer to improve and stabilize the LLC DASH Playout ?
The fact that this manifest is only containing targetOffsetMs (as Latency target) and maxOffsetMs (as Latency max), WITHOUT minOffsetMs could produce such an issues of rebuffering on the ExoPlayer ?
Can you advise if any other LLC parameter is missing (missing for the ExoPlayer to properly play the LLC Live stream) on the attached MPD file that we need to publish on the DASH manifest of LLC Live channel ?
Also please advise on the recommended values for those parameters on Low Latency, as with those ones we're encountering playout issues on LLC
DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000
DEFAULT_BUFFER_FOR_PLAYBACK_MS = 2500
DEFAULT_MAX_BUFFER_MS = 50_000
DEFAULT_MIN_BUFFER_MS = 50_000

Thanks
[MPD_DASH_LLC.txt](https://github.com/google/ExoPlayer/files/7640157/MPD_DASH_LLC.txt)

**Comment by tonihei** [comment]
Could you provide a link to the live version of the manifest instead of a snapshot? If you don't want to post it here, please send the link to dev.exoplayer@gmail.com with subject "Issue #9750". 

> Also, the Latency target is being set to 8 seconds, while the LLC stream observed with a reduced Latency of 4-5 seconds at the time of those playout issue occur

Sounds as if something in the timing is not quite as expected, because I would expect playback to have exactly this 8 second latency. How did you determine the latency is 4-5 seconds? Is that the value returned by `Player.getCurrentLiveOffset()` or a manual observation by comparing against an external clock? I noticed that you included a custom `UTCTiming` element in the stream, so any offsets are calculated against this time source.

> Are you familiar with another Values we need to set those parameters (minBufferTime, Latency which is the OffsetMS) which're more optimize for ExoPlayer to improve and stabilize the LLC DASH Playout ?

The only noteworthy thing is that a max latency of 10 seconds with a target of 8 seconds prevents the player from moving the target further away if needed. If you remove the max latency value, the player will move the target latency further away if it realizes that the network and loading of segments can't support the required latency (which seems to be the case here). Because the max latency value is set though, the player can't move the target further away than 10 seconds to respect the boundaries set by the manifest.

> The fact that this manifest is only containing targetOffsetMs (as Latency target) and maxOffsetMs (as Latency max), WITHOUT minOffsetMs could produce such an issues of rebuffering on the ExoPlayer ?

No, the `minOffsetMs` is rarely ever relevant for playback because ExoPlayer tries to keep playback at the `targetOffsetMs`.

> Can you advise if any other LLC parameter is missing (missing for the ExoPlayer to properly play the LLC Live stream) on the attached MPD file that we need to publish on the DASH manifest of LLC Live channel ?
Also please advise on the recommended values for those parameters on Low Latency, as with those ones we're encountering playout issues on LLC

No other parameter is missing and the `LoadControl` parameters are not likely to make a difference.

**Comment by He12345678901** [comment]
I had shared with a link to the live version of manifest, just sent it to dev.exoplayer@gmail.com with subject "Issue #9750"
please provide your response on that link Only via the email, thanks.
I had determined the latency is 4-5 seconds as per manual observation comparing to the original broadcast feed.
our custom UTC Timing element has No offset
about max Latency parameter, I cannot remove it ,BUT increasing the minBufferTime (above 8 seconds) parameter can help to stabilize the LLC stream ? how is that minBufferTime values should be aligned in respect to those buffer parameters' values ?
DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000
DEFAULT_BUFFER_FOR_PLAYBACK_MS = 2500
DEFAULT_MAX_BUFFER_MS = 50_000
DEFAULT_MIN_BUFFER_MS = 50_000

about more parameters on the DASH manifest:
"@PlaybackRate" parameter is mandatory for ExoPlayer ?
"@availabilityTimeOffset" and "@availabilityTimeComplete" are mandatory if the chunk is equal to segment duration of 2 seconds ?
thanks

**Comment by tonihei** [comment]
> I had shared with a link to the live version of manifest

Thanks, I'll have a look.

> BUT increasing the minBufferTime (above 8 seconds) parameter can help to stabilize the LLC stream ?

The `minBufferTime` is a property of the content: it describes how much bustiness or jitter is in the content encoding, usually the max GOP size in your encoding. It has only little to do with how the player behaves when playing the stream. The only influence is that ExoPlayer won't get closer than `minBufferTime` to the live edge to avoid dropped frames or underruns due to this content encoding jitter. But it's not a value that should be used to influence the player behavior. That's what the `ServiceDescription` is for.

> how is that minBufferTime values should be aligned in respect to those buffer parameters' values ?

As mentioned above, there is no alignment needed.

> "@PlaybackRate" parameter is mandatory for ExoPlayer ?

No, ExoPlayer will use a default of 3% maximum adjustment of the playback rate if needed.

> "@availabilityTimeOffset" and "@availabilityTimeComplete" are mandatory if the chunk is equal to segment duration of 2 seconds ?

No, these are only needed (and should only be used) if your chunks are available for loading before they are complete. This helps low-latency streaming, but is not a requirement (and setting this flag only depends on your actual encoding pipeline and when chunks become available for loading)

**Comment by He12345678901** [comment]
about yours statement,
The only influence is that ExoPlayer won't get closer than minBufferTime to the live edge to avoid dropped frames or underruns due to this content encoding jitter - We're observing that issue shown on the player logs with droppedFrames and then Remaining Buffer = 0, so is there a better relation need to be set on those parameters' values, meaning the minBufferTime=8sec and the Latency (which is the maxOffsetMS=10sec and targetOffsetMS=8sec) ? should we adjust those values to another ones ?

about those Buffer parameters, can you please advise on a different values more adapted for Low Latency ? are there some other Buffer parameters we need to check and adjust in addition ?
DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000
DEFAULT_BUFFER_FOR_PLAYBACK_MS = 2500
DEFAULT_MAX_BUFFER_MS = 50_000
DEFAULT_MIN_BUFFER_MS = 50_000

thanks

**Comment by He12345678901** [comment]
also to add that at the time of dropped frames and remaining Buffer = 0, we're getting CurrentLiveOffset 12573.
are there with another set of values advised to those parameters (or other Buffer ones) to avoid buffer going down to 0 and dropped frames in low latency stream ?
DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000
DEFAULT_BUFFER_FOR_PLAYBACK_MS = 2500
DEFAULT_MAX_BUFFER_MS = 50_000
DEFAULT_MIN_BUFFER_MS = 50_000

thanks

**Comment by tonihei** [comment]
I tested the stream and the best achievable live offset I can get is around 13-15 seconds. This is because chunks needed to play closer to the live edge haven't been published yet. For example in the static snapshot linked in your first post above, the video segments in the first `AdaptationSet` end at UNIX time `(16382968148104240+1799*20000000)/10000000=1638300412` = `2021-11-30 19:26:52 UTC`, whereas the manifest snapshot seems to be from `2021-11-30 19:27:03 UTC` (see `publishTime`). 

The player usually adapts to this situation by choosing a live offset that is a safe distance from the point where it would rebuffer, but because the `max` value of the `Latency` element is set to `10006`, the player will not do this because the manifest tells it to never increase the latency above 10 seconds. If I override the `max` value to something much larger, the stream plays perfectly fine without rebuffers. Ideally, you would fix the `target` value instead because 8 seconds is unlikely to be achievable with the stream as it is.

In addition, we can add a correctness check to our code to ensure the calculated minLiveOffset <= the calculated maxLiveOffset, which isn't the case here as they come from different sources. If we do that, the stream is also "fixed" by ignoring the impossible max offset defined by the manifest.

**Comment by He12345678901** [comment]
ok thanks, what is the ideal (as per DASH LLC standard) time difference between publishTime of the Manifest to the publish time of chunks (most closer to live edge) under AdaptationSet in order to make sure that playing is fine without rebuffers ? I guess that for Latency target of 8 sec and Latency max of 10 sec , that difference should be not more than few 6 seconds..isn't it ?

**Comment by tonihei** [comment]
There is no ideal time as this depends on the capabilities of your media pipeline and your required latency level. But generally, you are right, the target latency should be in the range of the available chunks to make it possible to reach it.

**Comment by He12345678901** [comment]
ok thanks, and do you see a point to adjust the following Buffering parameters' values (or another buffer parameters) to improve and stabilize the low latency playout so that it'd be playing just fine ?
DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 2000
DEFAULT_BUFFER_FOR_PLAYBACK_MS = 1500
DEFAULT_MAX_BUFFER_MS = 50000
DEFAULT_MIN_BUFFER_MS = 15000

**Comment by He12345678901** [comment]
one more point regarding: chunks needed to play closer to the live edge haven't been published yet - in addition to playout issues and when they occur, the Latency compared to Live point is being reduced from the proposed target of 8 seconds to 5 seconds (by manual observation check) - is it normal in this case considering the point you had noted about the manifest ? could it be because of the dropped frames we can see as the latency is not in range of available chunks ? thanks.

**Comment by tonihei** [comment]
>  and do you see a point to adjust the following Buffering parameters' values (or another buffer parameters)

No, there is no point in adjusting these values.

> the Latency compared to Live point is being reduced from the proposed target of 8 seconds to 5 seconds (by manual observation check) 

I'm not sure where the 5 seconds are coming from, the effective latency is increased to at least 12-13 due to the technical limitations of not having all segments available yet.

**Comment by He12345678901** [comment]
ok, about the current manifest constraint you noted that target latency is not in the range of the available chunks to make it possible to reach it - when trying to play the same low latency link provided with DashIf player we can see that it's more stable, much less Rebuffering
how can you explain that, given the current manifest limitation of not having all segments available yet (at least at the boundaries of Latency target and Latency max published values) ?
thanks

**Comment by tonihei** [comment]
The DASH-IF player likely added similar correctness checks we are in the process of adding too. After adding these checks ExoPlayer will also correct the target latency to be strictly inside the available live window even if the manifest itself defines it to be outside the live window as in this case.

**Comment by He12345678901** [comment]
ok fine, But in the DashIf , although having those additional correctness, still it's maintaining the Latency (relative to live broadcast feed) of around 8 seconds and not more - I'd expect it to correct/increase Latency as per manifest live window, isn't it ? how can you explain it ?

**Comment by He12345678901** [comment]
and about similar correctness checks you are in the process of adding too - in which ExoPlayer version and when it should be released with such a correctness for target latency ?
thanks

**Comment by tonihei** [comment]
The checks have been added by the commit above and will be part of the next release.
