### ISSUE TITLE
AudioTrack handleBuffer RESULT_POSITION_DISCONTINUITY has a problem

### ISSUE THREAD

**Issue by zondaOf2012** [google/ExoPlayer#976]
On AudioTrack ,  handleBuffer(ByteBuffer buffer, int offset, int size, long presentationTimeUs) should use startMediaTimeUs += Math.abs(bufferStartTime - expectedBufferStartTime);  rather than startMediaTimeUs += bufferStartTime - expectedBufferStartTime; ?

**Comment by ojw28** [comment]
I don't think so, no. The adjustment needs to be able to move both backward and forward.

**Comment by ojw28** [comment]
Could you explain why you believe it should be different? Thanks.

**Comment by ojw28** [comment]
Note that the HLS sample you provided under a related issue is a case of bad media, rather than a problem with the player.

**Comment by zondaOf2012** [comment]
However, the same video source can play on the iOS platform . If use "startMediaTimeUs += bufferStartTime - expectedBufferStartTime;" , some "DISCONTINUITY's video"  will be stop play.

**Comment by zondaOf2012** [comment]
In compatibility, in the hope that Exoplay is as good as MPMoviePlayerController.

**Comment by ojw28** [comment]
The change you suggest is not correct, and whilst it might happen to work for the sample you provide, it will prevent correctly generated media from playing properly in some cases. The right solution here is to fix the source media.

We're not really aiming to play arbitrary bad media. I would also debate whether a player that can handle such media is better, since it encourages people to create bad media in the first place, which is not a good thing.
