### ISSUE TITLE
Question about I-Frame only track playing

### ISSUE THREAD

**Issue by yzhon** [google/ExoPlayer#9764]
Hi, Dear Developers:

I have some questions about I-Frame track playing. Any help information may be grateful.
What if an I-Frame-Only track contains same content just like original content, can this kind of track be played normally, just like normal track( #EXT-X-STREAM-INF track).

**Comment by icbaker** [comment]
An "i-frame only" track with exactly the same content as a conventional video track would surely have a prohibitively high bitrate? Because you're not able to leverage any of the efficiency gains from interleaving much smaller p- or b-frames in between the i-frames. So it's not completely obvious why you would want to do this.

That said, you can [forcibly select such a track](https://exoplayer.dev/track-selection.html#selecting-specific-tracks). Note that this will disable any adaptive track selection behaviour - when adapting between tracks the `DefaultTrackSelector` will never select 'trick play' (i-frame only) tracks: 
https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L1944-L1947
