### ISSUE TITLE
Can Exoplayer IMA extension only play ads without providing content url ?

### ISSUE THREAD

**Issue by chinmaymujumdar** [google/ExoPlayer#9768]
We have an OTT platform app, where we manage content playback via custom player(not exoplayer) also we serve DFP video ads in between the content. Previously we were using IMA sdk 3.22.0 where this sdk was handling the ads playback with there own in built player. But with latest sdk version they have deprecated those methods and expect app to handle ads playback via VideoAdPlayer interface, which requires app to manage ads playback. 

Google team has suggested to use exoplayer IMA extension if we do not wish to manage ads playback. But after checking documents for IMA extensions, it requires us to provide content url as well. We are already managing content playback via a different player and wants only ad playback to managed by IMA extension. Is that possible ?

Or only way out of this is to manage ads playback via custom implementation using VideoAdPlayer ?

**Comment by tonihei** [comment]
ExoPlayer's IMA integration was written to work well with ExoPlayer playbacks, in particular since you need to send IMA events corresponding to playback positions, making sure the content is paused at the right time and the right ad metadata is received before needing to play the ad. Looking at it in this way, the player you are using would need its own IMA integration that does all that for you (and this implementation would be based on the `VideoAdPlayer` interface).

Having said that, you can still try to use ExoPlayer's IMA integration to play ads without content. For example, you can use a `SilenceMediaSource` to create empty content. See #9145 or #7929 where this has come up before. This integration only works well if you want to show a single ad without further playback integration. It gets more complicated if you want to make sure that this ExoPlayer instance "plays" in sync with your player if you want the ads to be shown at the right time for example.

**Comment by chinmaymujumdar** [comment]
So in that case we cannot use Exoplayer IMA extension as we need to play vmap ads(adrule) which has pre-roll, multiple midrolls and post-roll. 

Also old IMA sdk had their own in built player which was accessible using below method.

AdDisplayContainer adDisplayContainer = mSdkFactory.createAdDisplayContainer();
adDisplayContainer.setAdContainer(videoAdContainer);

But this seems to be deprecated now and only options(based on the sample apps) are using Exoplayer IMA extension or to use VideoAdPlayer interface. 

Using VideoAdPlayer interface requires app to manage ad playback, Ima sdk will send us the url of the ad to play. But app will use its own player to play ads and will update the sdk about content and ad progress via VideoAdPlayer interface callbacks. (This is what they have done in their advance sample app)

Any idea why IMA sdk team have stopped supporting their in built player ? or it is available to use via some other methods ? This seems odd that this funtionality is still available in IOS sdk.

**Comment by tonihei** [comment]
If you were using the built-in IMA player, you'd have to same problem that your player and the IMA player need to be kept in sync (e.g. to pause playback while an ad is playing). So with a custom player, it's really the best option to handle the interaction with IMA directly as shown in their "Advanced sample app".

Since ExoPlayer supports simple and straight-forward integration with IMA, there is also no reason to have this IMA-internal player anymore, as you can easily create an ExoPlayer instance and connect it to the IMA SDK. This gives you the same setup the previous built-in player provided.

**Comment by tonihei** [comment]
Closing issue as the question was answered.
