### ISSUE TITLE
ParametersBuilder class have some deprecated functions.

### ISSUE THREAD

**Issue by hemant1109** [google/ExoPlayer#9772]
I am using exoplayer 2.16.1 and I found some functions are deprecated in TrackSelectionDialog class as mention below:

1. `setSelectionOverride(rendererIndex, trackGroupArray, override)`
2. `clearSelectionOverrides(rendererIndex)`
3. `getSelectionOverride(rendererIndex, trackGroupArray)`

Please share demo for updated functions for them respectively. 
Thanks in advance.

**Comment by tonihei** [comment]
2.16.0 replaced the mentioned method in the `DefaultTrackSelector` by new methods directly in the `Player` interface that lets you modify track selections. Please see https://exoplayer.dev/track-selection.html#selecting-specific-tracks for the high-level documentation.

  - `TrackSelectionParameters.Builder.setOverrideForType` replaces the `DefaultTrackSelector.ParametersBuilder.setSelectionOverride`. Note that this replaces all previous overrides for the same track type. 
  - `TrackSelectionParameters.Builder.clearOverrideForType` replaces `DefaultTrackSelector.ParametersBuilder.clearSelectionOverride`. If we want to clear all overrides, it's also easier to just a create new instance of `TrackSelectionParameters.Builder`.
  - `TrackSelectionParameters.asList()` returns all existing overrides as a replacement for `getSelectionOverride`. 

Note that the new overrides don't require to specify a `rendererIndex` and `trackGroupArray` anymore. And the overrides themselves don't require a list of tracks if you want to select the entire group: 
`setOverrideForType(new TrackSelectionOverride(trackGroup))` 
instead of `setSelectionOverride(rendererIndex, trackGroupArray, new SelectionOverride(groupIndex, trackIndices)`.

>  found some functions are deprecated in TrackSelectionDialog

`TrackSelectionDialog` wasn't migrated yet because it's more of a debug tool in our demo app than anything else and we need to decide how we want it to look like in the future. If you want to see a more realistic UI integration, it's worth checking the track selection code in `StyledPlayerControlView` (e.g. [here](https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L2153))

**Comment by hemant1109** [comment]
Thank you @tonihei and @icbaker for quick response on this.

**Comment by tonihei** [comment]
Closing issue as the question was answered.
