### ISSUE TITLE
Does Exoplayer really buffer video ?

### ISSUE THREAD

**Issue by eshkoliGilad** [google/ExoPlayer#978]
It seems that when playing streaming mp4 url, Exoplayer doesn't really do anything with the section already buffered.
For example, with a 1 minute video, after playing 20 seconds, when seeking to 15 sec, it loses all buffered section and re-buffering again and takes time to load like when starting video all over again.
And it happens repeatedly all over again.

Does Exoplayer save this buffered portion and actually uses it somehow? how can I save the state of already played chunks? because I know ExoPlayer does not support Caching right now for mp4.

Thanks in advance.

**Comment by ojw28** [comment]
ExoPlayer currently discards media that's been played (i.e. is behind the current position) in order to use that memory to buffer further ahead. We have longer term aims around not doing this specifically in the case that we've buffered to the end of the stream already (in which case there's no requirement to reclaim the memory), but this wont happen for a while.
