### ISSUE TITLE
Cannot find a recommended way or moment for releasing the simple-cache instance, in the ExoPlayer Android documentation.

### ISSUE THREAD

**Issue by eddardsnarf** [google/ExoPlayer#9789]
I've tried searching everywhere in the documentation or the github issues page for my current use-case, but couldn't find anything. Apologies if I missed anything.
Current use-case on Android:
- I have a backstack of 2 similar activities on "top" of each-other.
- both activities have a ExoPlayer which uses a CacheDataSource factory as the DataSource factory. (in this factory I'm plugging in a simple cache with a LRU evictor)
- in the OnCreate() callback of the activity, I'm basically creating a manager-class which has the above-mentioned factory created with the simpleCache.
- I've been trying in the onDestroy of the activity to call `cache.release()`, but when i exit the top activity and the bottom activity's onCreate() is called I get the `Another SimpleCache instance uses the folder` exception. 
- I've also tried using separate worker threads in order to create the factory and releasing the cache.

Admittingly, the exception makes sense, cause the cache is probably releasing on a separate worker thread and the bottom activity's onCreate is called before the cache manages to release.

Do we actually need to have cache.release() called when the app is not showing the player anymore?

Please note: I've tried setting the above mentioned manager-class as a singleton, without releasing and it works as expected, but I'm concerned about the fact that I'm not unlocking the cache-folder when the user exits the app.

**Comment by marcbaechinger** [comment]
As you say you need to release the cache before another client tries to access it.

The `onDestroy()` lifecycle method of the activity gives you not much guarantees on when it is called, so you should use `onStop()` instead. Actually I think for your use case you need to initialize/release the cache when you initialize/release the player, So this would mean moving it from `onCreate/onDestroy` to 'onStart/onStop()' or 'onResume()/onPause()' just as for the player deoending on the API level. If you look at the [lifecycle methods on the `PlayerActivity`](https://developer.android.com/guide/components/activities/activity-lifecycle) of the demo app you can see where to call initialization/release for the given API levels. 

On a more general level the answer would be, that you need to choose a lifecycle method that makes sure that the two activities do not have an overlapping time window of existence of the player. Practically that means releasing as early as possible which is what the `PlayerActivity` is doing.

**Comment by eddardsnarf** [comment]
I understand what you mean.
I just thought that doing the init/release of the SimpleCache in the `onStart/onStop` methods would make it init/release even when the app goes in the background (pressing home-button), which I'm not sure if it's a desired effect . We would be recreating the SimpleCache unnecessarily,right?

But if there is no other way, currently to do it. I'm gonna try and do it `onStart/onStop`.
Feel free to close this issue if there is no other solution.
Thanks for your help 👍

**Comment by marcbaechinger** [comment]
Yeah, I agree with your point. 

You other approach may work too in my opinion, but I was hesitant to recommend it because I'm not totally sure what happens if `SimpleCache.release()` is not called. 

I'm not worried about the file lock actually, because this file lock is just a list of paths hold by the app. So once the app has finished and is restarted these locks are gone. It was more about the call to `contentIndex.store()` that is called in `release` of `SimpleCache`. So I'm a bit worried without calling it we could loose some indexed data. 

When looking into the demo app, I see that there, `SimpleCache.release` is not called and the cache is stored in a static variable. So it may be worth considering your approach with the global cache as well. Specifically if you find that calling `SimpleCache.release` turn out to be expensive to do on the main thread when the life cycle methods are called. This is specifically worth considering, if you are using the cache only for intermediate caching of player request as opposed to the cache being used by a download component for offline. When using it with a `DownloadService` the service should take care of this.

**Comment by eddardsnarf** [comment]
Alright. Thank you for the explanation. In my honest opinion, the last paragraph that you wrote is a nice explanation which would be nice to have in the official documentation or in the demo app as a comment.

Thanks again 👍 
Closing the issue
