### ISSUE TITLE
Can I play YouTube videos with ExoPlayer?

### ISSUE THREAD

**Issue by Shantanu-tec** [google/ExoPlayer#9793]
I just simply dont want to use Any kind of Services provided by AWS..
I want my running app to able to play Video such as .m3u8 or extracted youtube urls seamlessly.

But it wont play like that even though i have tried to change my Exoplayer Library from 2.7.4 to 2.15.1.
In every upgrade in Library there are some problems like loading issues which is there to download all the available chunks at one time but my app plays videos over 4 hour that takes a lot of time to do so.. and secondly it wont stop buffering even in a video that is only 15 min long or so.

Please help me about this.

**Comment by marcbaechinger** [comment]
Sorry, I didn't understand what your issue is I'm afraid. If you have difficulties playing an HLS stream please include the URI to the stream or send it by email as described below. If your issue is different please elaborate on it. We need a bit of actionable info. Rest assured we won't ask you to use AWS (you have my word!). 

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #9793". Please also update this issue to indicate you’ve done this.

**Comment by Shantanu-tec** [comment]
I dont have any problem with hls stream. The problem is when i play youtube videos with exoplayer , so for that i have to use youtube extractor and then the extracted url will pass to exoplayer to play, but it doesnot play it smoothly, buffering keeps on occurring.

**Comment by Shantanu-tec** [comment]
is there any way where i can resolve this without using any kind of service

**Comment by marcbaechinger** [comment]
Please accept my apologies but I'm still not totally clear what the problem is.

Firstly, I'm afraid but if you are asking me to support you to play YouTube videos that have been extracted in some ways, then I think you understand that I don't provide you support for this. Let me know if you want me to explain this in more detail.

You also may want to see [the section about playing YouTube videos with ExoPlayer](https://exoplayer.dev/troubleshooting.html#can-i-play-youtube-videos-directly-with-exoplayer) on our trouble shooting page.

> is there any way where i can resolve this without using any kind of service

You would have to tell me what service that is. If this is some kind of AWS service then I am afraid I'm not familiar with that. If this service provides chunks of extracted YT videos, then please see my answer above.
