### ISSUE TITLE
What is the replacement of simpleExoPlayer.addTextOutput(textOutput)?

### ISSUE THREAD

**Issue by kapodamy** [google/ExoPlayer#9805]
it was deprecated on commit https://github.com/google/ExoPlayer/commit/38e5864f87b8e24e69db7144be3bc792a02650cd but ¿what is the replace?. Also the RELEASENOTES.md does not mention anything (only describes SubtitlteView)

**Comment by marcbaechinger** [comment]
The change in the release notes of the commit that you linked says "`SubtitleView` implements `Player.Listener`, so can be registered to a player with `Player.addListener`."

This means for my understanding that you can now use a `Player.Listener` instead of the `TextOutput`. The `TextOutput` interface had a single method `onCues(List<Cue> cues)` which now is available in `Player.Listener`. So if you before did `player.addTextOuput(textOutput)` you can now do `player.addListener(listener)`.

The method with the identical signature, will be called on the listener now instead of the `TextOutput`. Please let me know whether that works for you and accept my apologies for the release note not being clear enough.

**Comment by kapodamy** [comment]
thanks
