### ISSUE TITLE
video quality does not change

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#9808]
I use hls to play movies.
I implemented the quality change in version 2.12.0 exoplayer, which works fine for all of them users. but when version 2.14.1 exoplayer is released, I updated the exoplayer version to 2.14.1.
**In version 2.14.1 some users can not change the quality and the movie is played only on one low quality.** when can't change the quality, this message is printed in logcat: 
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 25]

This sample code is used to change the quality (this sample code is the same in version 2.12.0 and 2.14.1 and only some users in version 2.14.1 have this problem):

`

       val trackSelector = DefaultTrackSelector(this@TvVideoPlayerActivity)

        exoPlayer = SimpleExoPlayer.Builder(
                this@TvVideoPlayerActivity,
                DefaultRenderersFactory(
                        this@TvVideoPlayerActivity
                )
        ).apply {
            trackSelector?.let {
                setTrackSelector(it)
            }
        }

        trackSelector?.buildUponParameters().apply {
            if (id == MEDIA_PLAYER_QUALITY_AUTO_ADJUSTING) {
                this?.setMaxVideoBitrate(Int.MAX_VALUE)
            } else {
                this?.setForceHighestSupportedBitrate(true)
                this?.setMaxVideoBitrate(bitrate)
            }
        }?.build()?.let {
            trackSelector?.setParameters(it)
        }
`

**Comment by marcbaechinger** [comment]
It looks like these devices do not support the track to which the code you posted tries to force the player to use. It's unclear which code path the users with problems are taking. This corresponds to yuou saying that the log line is emitted when it doesn't work, because the log reports just that.

The log message from above is only for informational purpose. The player still continues to work and is just not using that given track that is not supported by the device. I don't think there's much you can do about it in this case, because it seems to be a limitation of the device.

You are saying that these users only have the lowest bitrate available. What tracks are available in the HLS stream in question? If you use an `EventLogger` when building the player, the [logs then nicely show all the tracks](https://exoplayer.dev/debug-logging.html#media-tracks) that are available and also which of those tracks are supported by a given device.

So from what you are reporting, this does seem to work as intended, because the device doesn't seem to support that track. I wonder though why you are observing that it works with the older version, which I wouldn't really understand. 

If you have access to a device with that problem I would suggest to compare the output of the tracks made by the `EventLogger` from the older version with the output of the newer version (probably try with the most recent version also?). You would see a difference in what is reported to be supported or not. If this is the case we should investigate why a given track is reported as not supported in a more recent version. We probably would need a URI to the media for further investigation.
