### ISSUE TITLE
How to preload an HLS stream ahead of memory buffer

### ISSUE THREAD

**Issue by denis-bezrukov** [google/ExoPlayer#9820]
### Background
We have a screen when we play long videos (up to 90 minutes) and we can't preload them in advance (e.g. Using HlsDownloader) because we don't know what user will pick from the library (we have more than a thousand videos). At the same time, we want to provide an immersive experience, so if the user has a good network condition on start, we want to preload it asap without playback interruption

### Requirements for that preloader
1. Do not require a ton of RAM
2. Take user seeks into account. E.g. if the user skips the first 10 minutes, the preloader needs to skip it as well. 
3. Do not cause playback rendition to degrade. Example: If network conditions allow to playback only 720p, concurrent preloading of 1080p may lead to choosing 480p on the playback level)

### Considered (but rejected) solutions
1. Increase memory buffer (via DefaultLoadControl) to fit the whole video to it. It provides the exact behavior that we want to achieve, but it has an obvious drawback. It requires a lot of RAM. E.g. 90min of 2mbps video takes 1.3GB and we can't afford it. So it violates requirement `#1`
2. Just run HLSDownloader concurrently with a playback. It violates requirements `#2` and `#3`

### Current approach: 
Before we had a similar preloader when we used progressive playback, but it was simpler because we don't have to work with renditions/playlists. And also we used our ProgressiveMediaPeriod fork which is painful to support. Moving forward with HLS I would love to avoid any forks and use only public API. I reviewed all the available APIs and the idea is: 
1. Configure minBuffer < maxBuffer (by default exoplayer use 50s for min and max, that leads to "constant" loading) smth like minBuffer = 1min, maxBuffer=2min. In this case, I'll often have a (maxBuffer - minBuffer) window for preloading
2. Setup a few listeners: 
   - a listener for tracking isLoading state
   - a seek listener to adjust preloading position after each seek
   - custom HLS playlist tracker to have an access to a playlist / obtain manifest via onTimelineChanged
3. Preload the segments while the loader doesn't load the data
4. Cancel/suspend preloading once player continues loading / seek performed

With this approach, we will not preload the data for users with bad network conditions (e.g. if they play 480p/720p) because the player won't be able to buffer maxBuffer seconds (otherwise it will pick better rendition) so we don't violate 3rd requirement
For users with a good network, the player will mostly read the data from the disk

Please let me know if there are better options or if anything in that approach can be improved. I wonder why it is not a popular feature request (I found only https://github.com/google/ExoPlayer/issues/565 but it's kinda different) not only for HLS. I would love to see this feature source type agnostic, but I don't see a way how it can be implemented (except weird ideas to make something like SampleQueue that use RAM for queue head and disk for the rest, but it breaks the current SampleQueue+Loader+LoadControl system because it's not clear who is responsible for retrieving the data from these "swap pages")

**Comment by tonihei** [comment]
Thanks for the detailed explanation of your issue!

The general approach of using a Downloader (or manually triggering a `CacheWriter`) is definitely the right one to solve requirement `#1` (because the data is stored on disk):
 - To make this work nicely, both playback and download should access the same `Cache` via a `CacheDataSource`
 - If you don't want the player to cache while playing, you can configure it to be read-only (by setting `null` to `CacheDataSource.Builder.setCacheWriteDataSinkFactory`). This should help to avoid cache contention where both playback and background downloader try to write the same segment.
 
If you want to customize download order and adapt to what playback is doing, you probably need to use `CacheWriter` directly. Potentially start by forking `HlsDownloader` and amend the logic in `SegmentDownloader.download` setting `pendingSegments` to always include you preferred segments in the right order.  (Or build a simplified version from scratch). This is needed to address `#2` because the default `HlsDownloader` would just download everything in order.
Choosing which resolution to download is up to you and you could use the same one as currently used for playback (`#3`).

The last requirement in `#3` is that the download isn't blocking playback from loading data (to avoid rebuffers and to ensure playback uses the full bandwidth of the network). The general idea you describe is right, but we have a dedicated component (`PriorityTaskManager`) to handle all the starting/stopping logic:
 - `DefaultLoadControl` needs to be configured with different min/max values to create an opportunity for downloading as you describe.
 - Create a `PriorityTaskManager` instance and set it to both the playback and download:
     - `ExoPlayer.setPriorityTaskManager` to set it for playback. While the player is loading it will reserve the playback priority and prevent all other tasks with lower priorities from running.
     - `CacheDataSource.Factory.setUpstreamPriorityTaskManager` to set it for downloading on the data source used for the downloader. When using the existing `HlsDownloader` it will automatically request the right priority, but if you use the `CacheWriter` directly, you need to use `priorityTaskManager.add(C.PRIORITY_DOWNLOAD)` before starting the download, `priorityTaskManager.remove(C.PRIORITY_DOWNLOAD)` after completing the download and `priorityTaskManager.proceed(C.PRIORITY_DOWNLOAD)` in regular intervals to block download in case a higher priority playback task is running.

**Comment by tonihei** [comment]
Closing issue because the question was probably answered.
