### ISSUE TITLE
Provide an API to get list media items instantly

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#9827]
### [REQUIRED] Use case description
Currently, `Player` interface is lacking a method that returns the list of media items, I know it can workaround by using `getMediaItemCount` and `getMediaItemAt(index)`, but the method `getMediaItemAt(index)` is abstract and the implementation seems complicated, if its complexity greater than O(1) then to build list media items it would cost > O(n):
```kotlin
fun Player.getMediaItems(): List<MediaItem> {
    return List(mediaItemCount) { index ->
        getMediaItemAt(index)
    }
}
```

### Proposed solution
Add method `getMediaItems()` to `Player` interface, and the implementation should return the list of media items instantly (O(1)).
```java
public interface Player {
    List<MediaItem> getMediaItems();
}

class ExoPlayerImpl ... {
    @Override
    public List<MediaItem> getMediaItems() {
        return mediaItems; // <- a list media items should be backed and returns instantly.
    }
}
```

**Comment by ojw28** [comment]
I'm not convinced your proposed API is a good idea, in particular because it wouldn't scale for `Player` implementations that want to represent having a very large playlist. For such cases it only really makes sense to query smaller subsets of the playlist at any one point in time, and any possible implementation of `getMediaItems` would require a large (possibly unavailable) amount of memory. I think it's for the same reason that [Adapter](https://developer.android.com/reference/android/widget/Adapter) uses a very similar design, as an example of this pattern being used elsewhere.

Are you actually facing a concrete problem as a result of this API not existing, and if so could you describe what it is?

**Comment by Khang-NT** [comment]
I intend to use `getMediaItems` to build queue UI, or to implement a function like checking duplicate media item before inserting. But looking into `CastPlayer` implementation, I see it's not reliable to get the `MediaItem` object back from `Player`, so I guess I need to do it another way.

**Comment by ojw28** [comment]
Similar to the `Adapter` case mentioned, a scalable queue UI implementation should only need to query the part of the queue that's actually visible. Querying the entire queue, which might be huge, is inefficient if the display is only showing a small part of it.

**Comment by Khang-NT** [comment]
@ojw28 thanks for clarify. But I still don't really get it, says if I have 10000 media items to play, I also have to create `List<MediaItem>(10000)` and set it to `Player`, there's no way to set `Adapter<MediaItem>` to `Player`?

**Comment by ojw28** [comment]
That's true, and is also somewhat a scalability issue. I think that it is theoretically possible for a custom player to not support modifying the media items, and to expose its own internally maintained list, however.
