### ISSUE TITLE
How does ExoPlayer access Subtitles files on Android 11?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#9842]
Hello. I have noticed that when I provide ExoPlayer with the subtitles file real path it is able to display it (without issues) on video without the app having `MANAGE_EXTERNAL_STORAGE` permission and without asking the user to select a path or file using APIs. How is this possible? Thank you.

**Comment by ojw28** [comment]
ExoPlayer doesn't do anything special to access files. We use `RandomAccessFile` to read `file:///` URIs, which is a standard API. So either you're mistaken that the permission is required for the specific case, or you're mistaken that the app doesn't have the permission, or there's something wrong with the platform permission enforcement. The final one seems fairly unlikely to me.

Closing this, since you should find that reading the file directly using `RandomAccessFile` also succeeds, in which case even in the unlikely event that there is an issue, it would be in the underlying platform rather than in ExoPlayer.
