### ISSUE TITLE
This specific stream does not play

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#9843]
This stream does not play (https://serve-first.folxplay.tv/folx/ch-4/master.m3u8) but plays on Chrome using Native MPEG-Dash + HLS Playback extension on Chrome.

**Comment by ojw28** [comment]
The media is invalid, because the `EXT-X-MAP` URIs point to segments that contain media samples. As per the HLS specification:

> The Media Initialization Section can be specified by an EXT-X-MAP (Section 4.3.2.5) tag. The Media Initialization Section MUST NOT contain sample data.

You can see this by:

1. Opening the file you link to in a text editor, and pulling out one of the media playlist URIs. For example `https://serve-first.folxplay.tv/folx/ch-4/1080-HAQ2FT2U88.m3u8`.
2. Opening that file and pulling out the `EXT-X-MAP` URI: `https://serve-first.folxplay.tv/folx/ch-4/init-HAQ2FT2U88-4000.mp4`
3. If you open that file in Chrome, there is audio and video, so clearly it (incorrectly) contains sample data.
