### ISSUE TITLE
Cannot play HLS 

### ISSUE THREAD

**Issue by lnmcc** [google/ExoPlayer#986]
Thanks for your reply. But I cannot play this test URL: http://221.181.100.81:8080/xxx/20151124/56ff9d67c9a3495db38acd1c8fa1e01f_20151124_174419.ts?test=1 . and I can Play it using VLC or HTML. Can you help me ? Thanks.

**Comment by Avetri** [comment]
There is no HLS. It's a TS file by HTTP.

**Comment by cizekmilan** [comment]
Please send link with m3u8 file.

**Comment by Avetri** [comment]
Two streams are defined int the PMT. Video, H264 - PID 0x100 and audio, AAC - PID 0x101.
But only with PID 0x100 one there is.

**Comment by Avetri** [comment]
<p>new Sample("#986", "http://221.181.100.81:8080/56ff9d67c9a3495db38acd1c8fa1e01f/20151124/56ff9d67c9a3495db38acd1c8fa1e01f_20151124_174419.ts?test=1", PlayerActivity.TYPE_OTHER),</p>

**Comment by lnmcc** [comment]
OH, I am sorry. I post the wong URL.   This one :

http://221.181.100.81:8080/56ff9d67c9a3495db38acd1c8fa1e01f.m3u8?test=1

**Comment by Avetri** [comment]
It is not a HLS (m3u8) playlist. It is just a M3U playlist!

**Comment by Avetri** [comment]
You can switch off initialization of an audio reader:

<p>--- library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java	(revision )
+++ library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java	(revision )
@@ -311,7 +311,7 @@
             pesPayloadReader = new MpegAudioReader(output.track(TS_STREAM_TYPE_MPA_LSF));
             break;
           case TS_STREAM_TYPE_AAC:
-            pesPayloadReader = new AdtsReader(output.track(TS_STREAM_TYPE_AAC));
+//            pesPayloadReader = new AdtsReader(output.track(TS_STREAM_TYPE_AAC));
             break;
           case TS_STREAM_TYPE_ATSC_E_AC3:
           case TS_STREAM_TYPE_ATSC_AC3:</p>

But it is only a temporary solution because of the wrong PMT.

**Comment by lnmcc** [comment]
OH ,I found the problem, very very thanks!! ^_^
