### ISSUE TITLE
Why are there no subtitles?

### ISSUE THREAD

**Issue by tmi111** [google/ExoPlayer#9885]
```
MediaItem.SubtitleConfiguration subtitle =
    new MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleSrt))
    .setMimeType(MimeTypes.APPLICATION_SUBRIP) // The correct MIME type (required).
    .setLanguage("en") // The subtitle language (optional).
    //.setSelectionFlags(selectionFlags) // Selection flags for the track (optional).
    .build();

MediaItem mediaItem = new MediaItem.Builder()
    .setUri(Uri.parse(preparedMsg))
    .setSubtitleConfigurations(ImmutableList.of(subtitle))
    .build();
HlsMediaSource source = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem);
mPlayer.setMediaSource(source);
```

Here I am. Why are there no subtitles, thank you

**Comment by icbaker** [comment]
The subtitle fields of `MediaItem` are only supported by `DefaultMediaSourceFactory`, so you should try using that instead of `HlsMediaSource.Factory`. `DefaultMediaSourceFactory` will delegate to `HlsMediaSource.Factory` for content URIs that end in `.m3u8` or if the `MediaItem.Builder#setMimeType` is `MimeTypes.APPLICATION_M3U8`.

**Comment by tmi111** [comment]
Thanks for your reply

**Comment by tmi111** [comment]
```
DataSource.Factory dataSourceFactory = new DefaultDataSource.Factory(mContext);
MediaItem.SubtitleConfiguration subtitle =
    new MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleSrt))
        .setMimeType(MimeTypes.APPLICATION_SUBRIP)
        .setLanguage("en")
        .build();
MediaItem mediaItem = new MediaItem.Builder()
    .setUri(Uri.parse(preparedMsg))
    .setSubtitleConfigurations(ImmutableList.of(subtitle))
    .build();
MediaSource mediaSource = new DefaultMediaSourceFactory(dataSourceFactory)
    .createMediaSource(mediaItem);
mPlayer.setMediaSource(mediaSource);
mPlayer.prepare();
```

Like this?

**Comment by tmi111** [comment]
DataSource.Factory dataSourceFactory = new DefaultDataSource.Factory(mContext);
 MediaItem.SubtitleConfiguration subtitle =
         new MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleSrt))
                 .setMimeType(MimeTypes.APPLICATION_SUBRIP)
                 .setLanguage("en")
                 .build();
 MediaItem mediaItem = new MediaItem.Builder()
         .setUri(Uri.parse(preparedMsg))
         .setSubtitleConfigurations(ImmutableList.of(subtitle))
         .build();
 MediaSource mediaSource = new DefaultMediaSourceFactory(dataSourceFactory)
         .createMediaSource(mediaItem);
 mPlayer.setMediaSource(mediaSource);
 mPlayer.prepare();

Like this?

**Comment by icbaker** [comment]
That looks like it should work, yes. You can actually simplify it a bit by:
* Knowing that `DefaultMediaSourceFactory` will create a `DefaultDataSource.Factory` internally if you just pass a `Context` to its constructor.
* Using the `Player#setMediaItem` methods, as detailed here: https://exoplayer.dev/media-items.html
   * And since you're not customising `DefaultMediaSourceFactory`, you don't need to explicitly construct it - just let the `ExoPlayer` instance construct it internally instead.

Which means this ought to be equivalent code:

```
MediaItem.SubtitleConfiguration subtitle =
    new MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleSrt))
        .setMimeType(MimeTypes.APPLICATION_SUBRIP)
        .setLanguage("en")
        .build();
MediaItem mediaItem = new MediaItem.Builder()
    .setUri(Uri.parse(preparedMsg))
    .setSubtitleConfigurations(ImmutableList.of(subtitle))
    .build();

mPlayer.setMediaItem(mediaItem);
mPlayer.prepare();
```

Note that the subtitle track will not be selected by default, unless you've customised the [track selection behaviour of the player](https://exoplayer.dev/track-selection.html). If you want this subtitle track to always be selected, you could pass `C.SELECTION_FLAG_DEFAULT` to `SubtitleConfiguration.Builder#setSelectionFlags`.

**Comment by tmi111** [comment]
This amazing,  I added SubtitleConfiguration.Builder#setSelectionFlags，subtitles finally appeared, thank you very much 


**In case I don't see you,good afternoon,good evening and good night**
