### ISSUE TITLE
Can't find SimpleExoPlayer, ExoPlayerFactory, ExtractorMediaSource

### ISSUE THREAD

**Issue by Sagar0-0** [google/ExoPlayer#9890]
I was following an udacity's application development course and cloned one of their old project and after updating everything to newer compatible versions of libs and dependencies, I am having errors like some classes or features of this library is missing. In that project, they used SimpleExoPlayer, ExoPlayerFactory, ExtractorMediaSource but doesn't seems to be there anymore. Are they removed or what? Any replacements for them?  
Project link: https://github.com/udacity/AdvancedAndroid_ClassicalMusicQuiz
<img width="472" alt="image" src="https://user-images.githubusercontent.com/85388413/150774050-dfb548d9-3e2e-4682-8a4e-89af42fb176b.png">

**Comment by BrettyWhite** [comment]
Some of that stuff was recently deprecated. look at the release notes: https://github.com/google/ExoPlayer/releases/tag/r2.16.0

**Comment by marcbaechinger** [comment]
We usually keep deprecated methods and classes for at least two major releases before we remove it.

The course above is based on `ExoPlayer 2.2.2` which is quite old in the sense of about 14 major releases behind the current version. I think this is not really helpful for the audience of a course about starting with ExoPlayer, because migrating from 2.2.2 to 2.16.2 isn't really straight forward I'm afraid.

Looks like you already found https://github.com/udacity/AdvancedAndroid_ClassicalMusicQuiz/issues/27

**Comment by Sagar0-0** [comment]
Got what I wanted, Thanks! Here's the [solution](https://github.com/Sagar0-0/AdvancedAndroid_ClassicalMusicQuiz) if anyone got stuck in similar project.
