### ISSUE TITLE
Sample Implementation of canSelectFormat in AdaptitveTrackSelection

### ISSUE THREAD

**Issue by saeedata** [google/ExoPlayer#9896]
Thanks Tonihei for your kindness.
In the end I succeeded in implementing something working fine for my use case

_Originally posted by @guidofranceschini in https://github.com/google/ExoPlayer/issues/6630#issuecomment-554633117_

Hi, I guess I have a same usecase and I couldn't resolve that. could you please share you implementation? the canSelectFormat method is called just for the first track, however when I change the media bitrate it won't be called again.

**Comment by tonihei** [comment]
I'll reply on #6630 with the example to keep it all in one place.

> canSelectFormat method is called just for the first track

This method is called every time the player needs to make a new selection for a media chunk. But note that the [calling loop](https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L592) returns early as soon as it found a matching format, so that's why you might only see one call to the first track in the list.
