### ISSUE TITLE
mkv video not seekable

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#9901]
Video not seekable am playing the video format mkv 3840x2160 4k hdr(ultra hd) 60fps.
I have tested in other players like xplayer and mx player it is seekable but in exo not seekable .
Using exo 2.14.2
android version: 5 to 11
not seekable in all devices

this is the video link
https://drive.google.com/file/d/1OY9ZFJuCGc-CUBm4k9ANanDsAgkgE4hq/view

**Comment by kim-vde** [comment]
This is because the file doesn't contain any seek map ("Cues" element in Matroska). A seek map maps timestamps to byte positions in the file, to avoid having to parse the file up to the seeking point when seeking. ExoPlayer doesn't support seeking when the cues element is not present because:
1. The [Matroska specification](https://www.matroska.org/technical/elements.html) indicates the cues element "SHOULD be set when the Segment is not transmitted as a live stream".
2. The easiest way to implement seeking in this case would probably be to parse the file until the seek point but this is inefficient.
