### ISSUE TITLE
General delay for subtitle timing 

### ISSUE THREAD

**Issue by Kaaveh** [google/ExoPlayer#9902]
I followed [this solution(#854)](https://github.com/google/ExoPlayer/issues/854#issuecomment-599237344) to apply delay to subtitle, but not working. As my customer want, I must implement most closely this feature. What is simplest and easiest way to set offset timing to subtitle?

**Comment by icbaker** [comment]
I'm afraid we can't offer detailed support for workarounds provided in comments by other developers. If you can't get the workaround described in the linked comment to work, I'm afraid we can't really help.

ExoPlayer currently doesn't support modifying the offset of subtitles, #854 tracks adding this support.

**Comment by Kaaveh** [comment]
I've confused about @ojw28's solution code. Now a day, all of method's solution code not exist any more. Could you please help me to rewrite solution code with most recent methods of `Exoplayer` version?

```java
int captionTrackIndex = player.getSelectedTrack(captionRendererIndex);
player.setSelectedTrack(captionRendererIndex, TRACK_DISABLED);
player.sendMessage(singleSampleSource, MSG_SET_SAMPLE_TIME, offset);
player.setSelectedTrack(captionRendererIndex, captionTrackIndex);
```

**Comment by icbaker** [comment]
Just to check: The code snippet you've copied won't do anything on its own, you will also need to implement the handling of `MSG_SET_SAMPLE_TIME` (which never existed as a constant in ExoPlayer) in `SingleSampleMediaSource` (by making it implement `PlayerMessage.Target`). The details of how to do this are not covered in #854. The code snippet is from ExoPlayer v1 which is why it doesn't really match up to anything in ExoPlayer v2. It's unclear if this is still the best approach for solving this problem in ExoPlayer v2. As I said, we're not able to provide detailed support for such deep customisations to the library.

That said, the translation of that code into ExoPlayer 2.16.1 looks something like:

```java
ExoPlayer player = ...
player.setTrackSelectionParameters(
    player
        .getTrackSelectionParameters()
        .buildUpon()
        .setDisabledTrackTypes(ImmutableSet.of(C.TRACK_TYPE_TEXT))
        .build());
player.createMessage(singleSampleMediaSource).setType(MSG_SET_SAMPLE_TIME).setPayload(offset).send();
player.setTrackSelectionParameters(
    player
        .getTrackSelectionParameters()
        .buildUpon()
        .setDisabledTrackTypes(ImmutableSet.of())
        .build());
```

**Comment by Kaaveh** [comment]
Thanks for your response @icbaker . Let me recap what I see. I move further and complete code like below. but one question: 
What should I do with `offset` value when `messageType == MSG_SET_SAMPLE_TIME` ?


```kotlin
private fun setSubtitleOffsetTiming(offset: Long){
    val MSG_SET_SAMPLE_TIME = 1

    val singleSampleMediaSource =
        PlayerMessage.Target { messageType, message ->
            if (messageType == MSG_SET_SAMPLE_TIME){
                // TODO: What should I do with offset?
            }
        }

    player?.trackSelectionParameters = player?.trackSelectionParameters
        ?.buildUpon()
        ?.setDisabledTrackTypes(ImmutableSet.of(C.TRACK_TYPE_TEXT))
        ?.build()!!
    player?.createMessage(singleSampleMediaSource)?.setType(MSG_SET_SAMPLE_TIME)
        ?.setPayload(offset)?.send()
    player?.trackSelectionParameters = player?.trackSelectionParameters
        ?.buildUpon()
        ?.setDisabledTrackTypes(ImmutableSet.of())
        ?.build()!!
}
```
