### ISSUE TITLE
Can not read metadata since a change of server of streams (metadata is dismissed by Exoplayer)

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#9918]
Hi, I was reading metadata well done with Exoplayer, so I could read fine and I could listen properly from onMetadata(Metadata metadata). 

The problem is that we had a change of the server of streams and I can not read metadata nevermore. iOS devices still can read metaddata, so I think is an Exoplayer issue.

I have tested on `Exoplayer 2.14` this behaviour. The only sure is that with the old server I can read metadata and when the server was replaced by another one, I can not reveive metadata.

I have debugged inside the library at the early listeners, and I can see this method from Metadata.java

```
  public Metadata(Entry... entries) {
    this.entries = entries;
  }
```

This constructor is called each second but the `entries` are empty, so I am stuck at this point. 

I would need some theory about why the incoming metadata could be dismissed, or where can I see the raw metadata before being proccessed.

Thanks in advance.

**Comment by tonihei** [comment]
Do I understand correctly, that getting metadata stopped working with the **same** ExoPlayer version 2.14 after you switched servers? If so, there must be some difference in the media stream itself to cause this problem. In order to further debug this, we'd need access to the actual media. You can also send a link to dev.exoplayer@gmail.com with "Issue #9918" in the subject if you don't want to share it publicly.

**Comment by billyjoker** [comment]
Yes @tonihei, that's the point. So I will reach you with the email contact as you proposed, thanks!!

Also I have tested on Exoplayer demo 2.16.1 with the same behaviour.

One interesting point with the last tests is that if they send with key TXXX neither Android neither iOS receive data, but if they send under other key, indeed an invented key like 'ID3T', they iOS receive data, so that reforces the theory that something related with the encoding maybe is a wrong pattern or coding stantdard used

**Comment by tonihei** [comment]
I seems none of your ID3 tags sets the `data_alignment_indicator` bit to `1`, which is required to detect that a new ID3 is starting (compared to a previous one just continuing). ExoPlayer sees the ID3 tags but ignores them all because it thinks they are the continuation of a previous one. If I change our code to just assume that every ID3 tag has this bit set, I can see all the metadata being extracted correctly. A similar issue came up in https://stackoverflow.com/questions/56281622/how-to-extract-timed-id3-metadata-from-hls-stream-in-exoplayer where they proposed to write lots of wrappers to do the hack I just described, but if you control the media, you should really try to fix the stream instead.

For reference, I commented out this line for testing: https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/Id3Reader.java#L75

**Comment by billyjoker** [comment]
@tonihei firstly many thanks for your time testing this issue, I have reported to the people who manage the servers, it seems that you are right about the missing flag. 

For testing I applied your workaround and it works like a charm!!
