### ISSUE TITLE
PlayerNotificationManager: Notification is not cancelled

### ISSUE THREAD

**Issue by y20k** [google/ExoPlayer#9921]
I am maintaining two media apps that use very similar `MediaBrowserService` implementations. A radio app and a podcast app. Both apps use `PlayerNotificationManager` to manage their playback notifications. Both use `setUseStopAction(true)` to display a stop button. The `stop()` action triggered by the button is intercepted by a `ForwardingPlayer`. 

The `ForwardingPlayer` issues `playerNotificationManager.setPlayer(null)` to dismiss the notification when it intercepts `player.stop()`.

I "investigated": `PlayerNotificationManager` internally calls `notificationManager.cancel(notificationId)` and then triggers `onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean)` in a `PlayerNotificationManager.NotificationListener`:

```
override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
    super.onNotificationCancelled(notificationId, dismissedByUser)
    stopForeground(true)
    isForegroundService = false
    stopSelf()
}
```

All the above steps including the `notificationManager.cancel(notificationId)` are executed. I checked that using the debugger.

Now comes the strange thing.
1. The code works as intended on API 25. The notifications of the radio app and the podcast app are both cancelled, when the user taps the stop button in the notification.
2. Same for API 30 and API 31 for the podcast app
3. **BUT on API 30 and API 31 the notification for the radio app is NOT removed. Although `notificationManager.cancel(notificationId)`, `stopForeground(true)`, `stopSelf()` ARE executed.**

One difference between both apps: the radio app never calls `player.pause()` but instead always uses `player.stop()` even when the user technically tapped on a pause button. But I am not sure how that could play into the issue here.

**Screenshots**

Notification of the radio app (the stop button is the X on the right)
![notification-normal](https://user-images.githubusercontent.com/9103935/152058029-70aeaedd-62c5-4ba0-95e1-f332e2d267ad.png)

Notification of the radio app after the X button has been tapped - it should be removed
![notification-after-cancel](https://user-images.githubusercontent.com/9103935/152058041-b159ad4a-9ae1-43ef-9aac-8722a33bcd34.png)

Both mentioned media apps currently use ExoPlayer v2.16.1

**Update:** I recognize that there is most likely a problem with the way I am using ExoPlayer. But I am really stuck and I hope that anyone can give me a hint in which direction I should investigate further. What could be the cause that the notification is not removed even though `notificationManager.cancel(notificationId)`, `stopForeground(true)`, `stopSelf()` are executed.

**Update 2:** I found a difference between the two apps. I set a break point for the debugger in `onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) ` in `PlayerNotificationManager.NotificationListener`. The radio app, that refuses to dismiss the notification, displays an error on the debug screen: **player = Cannot find local variable 'player'**. The podcast app, that behaves correctly, does not display this error.
<a href="https://user-images.githubusercontent.com/9103935/155371745-fdd64571-11b2-44bd-978c-c46d173d2c8a.png"><img src="https://user-images.githubusercontent.com/9103935/155371745-fdd64571-11b2-44bd-978c-c46d173d2c8a.png" width="640" /></a>

**Comment by marcbaechinger** [comment]
Sorry for my late response.

I think this is triggered by the the system that accesses your service to add a media resumption notification, so that a user can resume playback from the notification after your app has been stopped.

Please check the [documentation](https://developer.android.com/guide/topics/media/media-controls) about it also.

You can verify this by logging when the methods `onGetRoot` is accessed after you stop the app. I believe the `clientPackageName` that calls the method is `com.android.systemui` or similar in this case. Easy to recognize if you log the arguments (it's probably difficult to debug with a break point after you have stopped the app, so try just logging first).

You have the option to implement this in the sense of the documentation I linked above. Then a user can restart playback of the last recent item with that notification (see documentation). Note that such a call against your service may be done when booting the device also. So that the user would be able to resume from the last recent item your app has played.

I think an alternative is to return `null` for the given `clientPackageName`. Then the resumption notification is not added by systemui.

**Comment by y20k** [comment]
Hi @marcbaechinger 

THANK YOU. That was the problem. I investigated SO much time into this, but I failed to consider the media resumption notification. I am super grateful.
