### ISSUE TITLE
hls 4k video is not playing

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#9922]
Hi . 

I tried to play an hls url with demo app but id didn't play the video at all and it didn't show any error on console also  , however it showed by browser properly . 
I added the url link here . 

`https://livelist01.yowi.tv/lista/a8a88df9a27c5adb08c931429a6eb7041ced7336/master.m3u8`

Could you please check it? Thanks .

**Comment by tonihei** [comment]
It seems ExoPlayer is unable to find any track data in the TS files and only adds the ID3 track. Playback then continues with just playing metadata, that's why you can't see any video and there is also no error.

@kim-vde Do you know what could have happened here? I tested the two flags we recommend for similar problems (https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play), but they don't make a difference here.

**Comment by kim-vde** [comment]
The media provided contains 3 tracks:
1. A track with stream_type 0x15: this is the ID3 track.
2. A track with stream_typ 0xCF: this is a "ISO/IEC 13818-7 ADTS AAC with AES-128-CBC frame encryption" according to [1].
3. A track with stream_typ 0xDB: this is a "ITU-T Rec. H.264 and ISO/IEC 14496-10 with AES-128-CBC slice encryption" track according to [1].

The `TsExtractor` parses these 3 tracks but is unable to find a `TsPayloadreader` for track 2 and 3 because it doesn't support these stream types (see [2]). This enhancement is already tracked by #4021.

[1] https://en.wikipedia.org/wiki/Program-specific_information#Elementary_stream_types
[2] https://github.com/google/ExoPlayer/blob/r2.16.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/DefaultTsPayloadReaderFactory.java#L138
