### ISSUE TITLE
Add custom filter before rendering DRM content

### ISSUE THREAD

**Issue by mbertini** [google/ExoPlayer#9930]
Hi, I'm trying to understand the feasibility of a computer vision application.

The use case is that of a company that would like to improve the user experience of its DRM protected content without changing the encoding of the streamed media but instead improving the visual quality on the device of the end user

I'd like to know if it is possible to add a custom filter, think a deblocking filter that improves the visual quality of a video, before rendering the frames of DRM content.
Is it possible to make this filter part of the DRM video playing pipeline ?

**Comment by tonihei** [comment]
Generally, the point of having DRM is that any modification or access to the decoded video frames is not possible. Because as soon as you get access to the frames, you could for example copy it to another file and redistribute it. Having said that, this only strictly applies if playback uses a secure output path (often referred to as Level 1), and modifications may be possible when using (or forcing) Level 3 where the fully secure output path isn't used. This again depends on the content license since it must not require such a secure output path. 

Assuming your content license allows it, you can force Level 3 by doing something similar to https://github.com/google/ExoPlayer/issues/7790#issuecomment-678473131.

If you do this (or use non-DRM-protected content), you can access the frames by one of the methods mentioned in https://github.com/google/ExoPlayer/issues/7167#issuecomment-608306654. If you intent to run this filter as part of the ongoing playback, you likely need to use OpenGL as shown in our [GL demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/gl).

**Comment by mbertini** [comment]
Thanks for the answer !
I hoped it was possible to provide some sort of callback for a standard decoder or customized decoder within a trusted application, I mean the organization that has the license can customize its own secure path e.g. providing its own version of VP9/AV1/HEVC decoder with its own improved deb locking filter.

**Comment by tonihei** [comment]
The "secure path" can only be provided by the device manufacturer because it's usually implemented in its own hardware (the [trusted execution environment](https://en.wikipedia.org/wiki/Trusted_execution_environment)). 

There are probably still some ways in which this can be made to work:
 - If the content allows it, you can avoid using the secure path (e.g. by forcing the Widevine Level 3) and then apply any post-processing you like (see links in my first reply above).
 - You can also bypass all Android default components (like `MediaDrm` and `MediaCodec`) completely by doing your own in-app DRM handling (including decryption) and decoding. See https://github.com/google/ExoPlayer/issues/4372 or https://github.com/google/ExoPlayer/issues/2414 where similar questions came up.
 - Some devices support a secure GL context on the GPU that let's you modify the decoded frames. See https://source.android.com/devices/graphics/arch-st#st_vid_play. However, this is only supported by a subset of devices and we got reports in the past where this wasn't reliable (see for example https://github.com/google/ExoPlayer/issues/3373).

**Comment by tonihei** [comment]
Closing because the question was answered.
