### ISSUE TITLE
Cast doesn't work

### ISSUE THREAD

**Issue by hannesa2** [google/ExoPlayer#9941]
When I [add an own video](https://github.com/hannesa2/ExoPlayer/commit/5c9bc056100660ff88961f95c7b5277a2b05d90b) in cast sample here [DemoUtil.java#L54-L59](https://github.com/google/ExoPlayer/blob/release-v2/demos/cast/src/main/java/com/google/android/exoplayer2/castdemo/DemoUtil.java#L54-L59)

I can see movie local on my device 👍, but when I cast this item, the player keeps black and I see this
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/3314607/152636154-5013ac76-2234-4997-8f91-e0b0b2a61f1d.png">
and this
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/3314607/152636178-d1e1ef14-24d2-4116-8cd8-e954e18eb25a.png">

Does someone has a hint for me what's wrong here ?

**Comment by marcbaechinger** [comment]
I think the problem is that the cast device does not support that MP4 file. I tested with your URL on an Chromecast Ultra and a Nest Hub. The Ultra does not play the media at all, while the Hub plays audio only. The controls in the demo app work when the audio is playing. Locally, the media plays well with ExoPlayer on Android as well for me (very interesting content btw :)). I don't think there is a problem on the demo app or player side.

The error log show something that is unrelated to this I think. When playing with Cast the media plays and logs on the remote device running an HTML app that does not affect a surface texture in the Android app.

**Comment by hannesa2** [comment]
I use such a device , no clue what type it is
<img width="407" alt="image" src="https://user-images.githubusercontent.com/3314607/152762718-e76f68c8-b03f-45f0-b4db-47690a04ecd2.png"> 
and a Nest hub (2nd gen)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/3314607/152762947-1cae698f-3344-49de-b44a-40a1897cbbf2.png">

both neither play audio nor play video.

So I tried same movie with VLC for Android, and there a message appears 
![image](https://user-images.githubusercontent.com/3314607/152763253-0fb872a2-c469-4a2f-b82d-542b5f4edc6f.png)

and tata !! ... it works on both devices 🎉

I've to build VLC by my own and see what's make it work. 

If in ExoPlayer-cast a callback with wrong format would appear, I would be satisfied
