### ISSUE TITLE
hls Streaming suddenly stopped giving E/ExoPlayerImplInternal: Source error  UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by drashad88** [google/ExoPlayer#9961]
All the videos in my app suddenly stopped working and i tried many of the suggested solutions here but none worked. Please advise

---------------CODE USED---------------

String userAgent = Util.getUserAgent(getActivity().getApplicationContext(), "app-name");
            // Create a data source factory.
DataSource.Factory dataSourceFactory = new DefaultHttpDataSourceFactory(userAgent);

String videoUrl = "http://124631476-recorded-hls.ums.ustream.tv/playlist/directhls/recorded/124631476/playlist.m3u8?sgn=951b31d8c27cb402c4e24177f6705b9238e37fb8";

Uri uri = Uri.parse(videoUrl);
HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
player.prepare(hlsMediaSource);

------------------ERROR-----------------------

E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

**Comment by ojw28** [comment]
It looks like the server is rejecting your user agent. If you're the streaming provider, you should follow up with the team that's providing the streams to establish what the user agent should be set to. If you're not the streaming provider, then is it possible that they've made a change to deliberately stop these streams from playing in your app?

Closing in any case, since this does not appear to be an ExoPlayer issue.
