### ISSUE TITLE
Expoplayer issue resulting in bugged out Anime app

### ISSUE THREAD

**Issue by Imphzlse** [google/ExoPlayer#9973]
This bug only affects my Android tablet running android 7.0 it is also a Samsung and experiences this issue in saikous player which is gotten from exoplayer. The bug is that whenever I try to adjust my tablets quality to 1080l even tho the screen cap is 720p it loads up a black screen that loads infinitely. This bug is very frustrating because it literally won't let me play 1080p on the device. The creator of the saikou also said that this is an issue on expoplayers end not his.

Link to the app:
https://github.com/saikou-app/saikou/releases/download/1.0.10/Saikou.1.0.10.5_fixed.apk

**Comment by icbaker** [comment]
I'm afraid we can't provide direct support to users of apps that incorporate ExoPlayer. You should report your issue to the app developer, and if they believe it's a problem with our library they should report the issue to us, with all the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) that we need to understand and investigate issues. 

You haven't provided enough information for us to determine if the problem is in the app or our library.
