### ISSUE TITLE
Video caching not working as intended? 

### ISSUE THREAD

**Issue by zozo11299** [google/ExoPlayer#9980]
Hello team so this is a semi question semi report for the feature video caching

I was using exoplayer to watch a 300 mb online video, I purposely paused the video for around 10 minutes so it can cache the video, I have the cache limit to 500 mb so it was clearly enough for all sorts of caching within the video, problem is after I came back 10 minutes, only around half a minute of a 23 minute video being cached why would this happen?

Note that both my internet and storage were more then enough

So I would like to know why this is happening, maybe it's how the feature works so I would like to know (it happens all the time it's not a one time thing)

**Comment by icbaker** [comment]
Please provide more information. How are you configuring the "cache limit to 500 mb"?

Note that `DefaultLoadControl` will aim to buffer a maximum of [50s](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html#DEFAULT_MAX_BUFFER_MS) and [131MB](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html#DEFAULT_VIDEO_BUFFER_SIZE) of video by default.

When you pause playback, the player won't automatically try and load any media beyond the limit enforced by the `LoadControl` (either into the in-memory buffer or any persistent storage).

We have an open feature request to support concurrent playback and downloading - depending on exactly what you're trying to do, this issue may be a duplicate of that: https://github.com/google/ExoPlayer/issues/8645

**Comment by LagradOst** [comment]
(I think) He is referring to a CacheDataSource.setCache of a SimpleCache with LeastRecentlyUsedCacheEvictor of 500mb. Is this implementation of cache wrong to reduce buffering? Do exoplayer require additional calls to ensure that it can cache 500mb of video when paused?

**Comment by icbaker** [comment]
There's two different concepts that it's important to understand here:
* buffering
* downloading/caching

ExoPlayer uses 'buffering' to refer to reading data into memory as part of a normal playback. The amount of data buffered is controlled by the `LoadControl`. As described above, the `DefaultLoadControl` will read up to 50s ahead of the playback position.

'Downloading' or 'caching' refers to persisting media content to disk (not memory). This can happen as part of normal playback (if you just include a `CacheDataSource` in your `DataSource` chain) or you can use [ExoPlayer's download components](https://exoplayer.dev/downloading-media.html) to explicitly download content outside of a playback context.

If you're using a `CacheDataSource` during normal playback (without using any download components), then this will only cache data (to disk) that is buffered (to memory) as part of that normal playback. If you pause the player, the buffering (and therefore caching) will also pause - because it will reach that point 50s ahead of the playback position as influenced by the `LoadControl`.

If you want to leave the player paused and download the entire stream onto disk (but not memory), then I think that will be possible once #8645 is implemented - but is currently unsupported.

**Comment by zozo11299** [comment]
Thanks for feed back I found what I want
