### ISSUE TITLE
2.16.1   There is sound but no picture when playing video in rv40 encoding format

### ISSUE THREAD

**Issue by ludoven** [google/ExoPlayer#9982]
Hello
I'm having an issue with version 2.16.1 of the player
When the played video is in rv40 encoding format, the player does not support this format,
When I use the Ffmpeg extension, I found that ExoPlayer removed FfmpegVideoRenderer in version 2.16.0,
I would like to know how can I use ExoPlayer to play a video encoded in rv40.
thanks

**Comment by icbaker** [comment]
> When I use the Ffmpeg extension, I found that ExoPlayer removed FfmpegVideoRenderer in version 2.16.0,

The `FfmpegVideoRenderer` has never been released, because it's not yet finished and ready for use in production. We 'removed' it in the 2.16.0 release (and all previous releases) in the sense that it exists on the dev-v2 branch, and we remove it when preparing a release branch. Implementing this is tracked by https://github.com/google/ExoPlayer/issues/2159.

If your device doesn't support the encoding of your video then your choices are either to re-encode the video to a more widely supported format, or bundle a software decoder with your app. You can follow #2159 if you want to bundle an ffmpeg-based software video decoder.

I'm going to close this, because I don't think there's any additional work to track here beyond what's already covered by #2159.
