### ISSUE TITLE
why dashdownloader does not download lower bitrate track when network is slow? if it does, how to check it?

### ISSUE THREAD

**Issue by kshailes94** [google/ExoPlayer#9985]

**Comment by ojw28** [comment]
It's working as intended that ABR changes based on the available bandwidth are disabled for downloads.

It's not a requirement that downloads have to complete within a certain duration. One of the reasons that a user might want to download content (rather than streaming it) is so that they can then play the highest quality stream, despite not having the bandwidth to do so when streaming.

Note also that the application is able to select which quality is downloader picks when initializing the download. Application code could do this based on the network type, or by presenting a dialog to the user. Our demo app presents a dialog to the user, so you could take a look at the demo app code if you're interested in understanding how to do this.

**Comment by kshailes94** [comment]
can it be enabled for downloads ?

**Comment by ojw28** [comment]
No, this is not supported.
