### ISSUE TITLE
What do I need to setup in order to get the genre from onMetadataChanged ?

### ISSUE THREAD

**Issue by laurentiu-git** [google/ExoPlayer#9991]
Hey guys, what do I need to setup in order to get the genre from `onMetdataChanged`, as shown in the below example
```
private inner class MediaControllerCallback : MediaControllerCompat.Callback() {
   override fun onMetadataChanged(metadata: MediaMetadataCompat?) {
            // When ExoPlayer stops we will receive a callback with "empty" metadata. This is a
            // metadata object which has been instantiated with default values. The default value
            // for media ID is null so we assume that if this value is null we are not playing
            // anything.
            val genre = metadata?.genre
}
```

I have tried to the same configuration as in uamp sample, but I think I am missing something, I am able to access the genre value from `onMediaMetadataChanged` from ` Player.Listener`.

I am also using this part in my project

```
fun MediaMetadataCompat.Builder.from(jsonMusic: JsonMusic): MediaMetadataCompat.Builder {
    val durationMs = TimeUnit.SECONDS.toMillis(jsonMusic.duration)
    id = jsonMusic.id
    title = jsonMusic.title
    artist = jsonMusic.artist
    album = jsonMusic.album
    duration = durationMs
    genre = jsonMusic.genre
    mediaUri = jsonMusic.source
    albumArtUri = jsonMusic.image
    trackNumber = jsonMusic.trackNumber
    trackCount = jsonMusic.totalTrackCount
    flag = MediaItem.FLAG_PLAYABLE
  
    displayTitle = jsonMusic.title
    displaySubtitle = jsonMusic.artist
    displayDescription = jsonMusic.album
    displayIconUri = jsonMusic.image
    // Add downloadStatus to force the creation of an "extras" bundle in the resulting
    // MediaMetadataCompat object. This is needed to send accurate metadata to the
    // media session during updates.
    downloadStatus = STATUS_NOT_DOWNLOADED
    // Allow it to be used in the typical builder style.
    return this
}
```

Also the property value is present if I try o access it in `onLoadChildren` from `MediaBrowserServiceCompat`
```  
 val item = musicSource.songs.map { item ->
                  val genre = item.genre
                  MediaBrowserCompat.MediaItem(item.description,
                  MediaBrowserCompat.MediaItem.FLAG_PLAYABLE)
}
result.sendResult(item)
```

**Comment by marcbaechinger** [comment]
Sorry for my late response.

Where do you set the `genre`? If you set the genre in the `MediaItem` of ExoPlayer, then you need to make sure that it is copied into the `MediaMetadataCompat` object that is set to the media session. With `MediaSessionConnector` the app is responsible for doing that by providing a `TimelineQueueNavigator` that implements `getMediaDescription`. 

If you are using UAMP that in the current version of UAMP is based on `MediaMetadataCompat` rather than the `MediaItem` then you need to change UAMP along these lines. As far as I understand UAMP reads a JSON file and then build a list `MediaMetadata` of which elements then are provided as the `MediaDescription` for the queue item [here](https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L463). So what you need to do is to see that your values of `MediaItem.MediaMetadata` are used by UAMP when returning the `MediaDescription` in the `UampQueueNavigator`.

Also note that `MediaMetdataCompat.genre` only exists as UAMP added such a field in a [Kotlin extension](https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt#L64).

**Comment by laurentiu-git** [comment]
Hey, no worries thanks for your answer.

This is how I am providing the elements as `MediaDescription`, it is the same as on UAMP and I've added the genre line to check if the value is present there, which it is.
![image](https://user-images.githubusercontent.com/70561735/156237170-9b9898e9-da81-4708-ad8c-9f69e86e4943.png)

I am still missing something, but I am not sure what, since the value is present there(in QueueNavigator), should I be able to see it in `onMetdataChanged`? Because it is showing it as null in `onMetdataChanged`.

**Comment by laurentiu-git** [comment]
For those that might have the same question in the future, follow the UAMP structure and make sure that when you make the 
`MediaMetadataCompat.Builder` for the song you add this part, apparently if the extras is null, it will not work
```kotlin
 // Add downloadStatus to force the creation of an "extras" bundle in the resulting
    // MediaMetadataCompat object. This is needed to send accurate metadata to the
    // media session during updates.
    downloadStatus = STATUS_NOT_DOWNLOADED
```
